SatelliteQE/robottelo

robottelo/host_helpers/contenthost_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11537
Follow redirects on ohsnap when downloading repo file using curl
=> [6.13.z] Follow ohsnap repofile redirects

robottelo/host_helpers/contenthost_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11537
Follow redirects on ohsnap when downloading repo file using curl
=> [6.12.z] Follow ohsnap repofile redirects

robottelo/host_helpers/contenthost_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11537
Follow redirects on ohsnap when downloading repo file using curl
=> [6.11.z] Follow ohsnap repofile redirects

testimony.yaml, tests/foreman/cli/test_host.py, tests/foreman/ui/test_host.py
Making kattelo-tracer component aligned in CI to align with its team. Now it's seating in an unaligned pipeline in CI.
Now the CI can collect it right:
```
=================== test session starts ========================
platform darwin -- Python 3.11.1, pytest-7.3.1, pluggy-1.0.0
Mandatory Requirements Available: requests==2.31.0 pytest-reportportal==5.1.8 jinja2==3.1.2
Optional Requirements Available: pre-commit==3.3.2 manage>=0.1.13 sphinx==7.0.1 redis==4.5.5 sphinx-autoapi==2.1.0
rootdir: /Users/jitendrayejare/GitRepos/robottelo
plugins: ibutsu-2.2.4, mock-3.10.0, reportportal-5.1.7, xdist-3.2.1, services-2.2.1, cov-3.0.0
collected 6092 items / 6080 deselected / 12 selected …
```
=> Katello-tracer Alligned in CI

robottelo/host_helpers/satellite_mixins.py, tests/foreman/destructive/test_puppetplugin.py
Puppet enable fails due to a change in the Java version in the latest Candlepin release in a recent stream snap, whereas Puppet still requires an old Java version, DNF tries to resolve it while installing `puppetserver` and requires CDN repos to install. Here `session_puppet_enabled_sat` uses `enable_puppet_satellite` where added simple step for registering sat to CDN for RHEL content repos.
=> Fix Puppet enable test failures

tests/foreman/api/test_registration.py, tests/foreman/cli/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11538
Since the registration [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2156926) is closed as NOTABUG so updating the condition for RHEL6 client registration.
=> [6.13.z] Test case updated for RHEL6 client registration

pytest_fixtures/component/satellite_auth.py, pytest_fixtures/core/sat_cap_factory.py, robottelo/hosts.py, tests/foreman/cli/test_ldapauthsource.py, tests/foreman/ui/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11445
Every time GH Actions run  `pytest tests/robottelo/` we see the following warning message multiple times in one run. See [the following GitHub Actions run](https://github.com/SatelliteQE/robottelo/actions/runs/4892389046/jobs/8734088618#step:8:891)
```
PASSED
2023-05-05 10:30:21 - robottelo.collection - INFO - Processing test items to add testimony token markers
tests/robottelo/test_report.py::test_junit_timestamps[dummy_test-non_xdist-testcase] ..                                                                       [100%]
../../../../../opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/_pytest/config/__init__.py:747 …
```
=> [6.13.z] Fix for PytestAssertRewriteWarning

tests/foreman/maintain/test_service.py
https://github.com/SatelliteQE/robottelo/pull/11481 got merged before I could investigate. Apparently this test as it was before can pass on Satellite, but the case from the BZ will still fail. The original intent was to have the test case fail and then we can check automation when we get the stream snap with the fix in it. This test will now fail until the fix is added to stream.
=> Adding better coverage to enable/disable stream test

tests/foreman/api/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11454
-Automation for http-proxy cacert (found in Infrastructure>HttpProxy>New or edit proxy)
-The test aims to create or collect a valid cacert.crt, assign the cacert to an Http-Proxy, then sync a repo with the proxy.
-Depends on nailgun PR# [924](https://github.com/SatelliteQE/nailgun/pull/924): add cacert as a field of HttpProxy
-BZ# 2144044
=> [6.13.z] Http-Proxy cacert automation coverage

tests/foreman/maintain/test_service.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11514
https://github.com/SatelliteQE/robottelo/pull/11481 got merged before I could investigate. Apparently this test as it was before can pass on Satellite, but the case from the BZ will still fail. The original intent was to have the test case fail and then we can check automation when we get the stream snap with the fix in it. This test will now fail until the fix is added to stream.
=> [6.14.z] Adding better coverage to enable/disable stream test

tests/foreman/cli/test_remoteexecution.py
```
$ pytest tests/foreman/cli/test_remoteexecution.py::TestRemoteExecution::test_positive_run_default_job_template_by_ip
Mandatory Requirements Available: pytest-reportportal==5.1.8 broker[docker]==0.3.2 wrapanapi==3.5.15 requests==2.31.0 pytest-xdist==3.3.1 jinja2==3.1.2
configfile: pytest.ini
plugins: cov-3.0.0, …
```
=> Close looop BZ1896628

tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11570
```
$ pytest tests/foreman/cli/test_remoteexecution.py::TestRemoteExecution::test_positive_run_default_job_template_by_ip
Mandatory Requirements Available: pytest-reportportal==5.1.8 broker[docker]==0.3.2 wrapanapi==3.5.15 requests==2.31.0 pytest-xdist==3.3.1 jinja2==3.1.2
rootdir: …
```
=> [6.12.z] Close looop BZ1896628

tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11570
```
$ pytest tests/foreman/cli/test_remoteexecution.py::TestRemoteExecution::test_positive_run_default_job_template_by_ip
Mandatory Requirements Available: pytest-reportportal==5.1.8 broker[docker]==0.3.2 wrapanapi==3.5.15 requests==2.31.0 pytest-xdist==3.3.1 jinja2==3.1.2
rootdir: …
```
=> [6.13.z] Close looop BZ1896628

tests/foreman/longrun/test_oscap.py
- Parameterised OpenSCAP test was failing due to various reasons, as per discussion we decided to remove the support for rhel6 from scap.
- Also due to regression issue/BZ #2211437 test was failing (in Stream/6.14.0) for rhel7 & rhel8 as well, so added skip marker.
- Test would not run in CI.
- In 6.12 test was failing for rhel6 after running the Ansible playbook (python version issue)
=> remove rhel6 support from scap test and skip test due to bz 2211437

tests/foreman/cli/test_contentviewfilter.py
Something we missed in #11542
and [6.14.z] cherry-pick #11595
=> Remove @stream decorator

tests/foreman/api/test_http_proxy.py
This was addressed in the cherrypick of [this PR](https://github.com/SatelliteQE/robottelo/pull/11526), the failing assertion was only removed from 6.13.z, but not 6.14.z
=> Remove unnecessary failing assertion api/test_http_proxy.py

pytest_fixtures/core/contenthosts.py, tests/foreman/api/test_ansible.py
Execution of Ansible job on multiple hosts simultaneously
**Test result:**
```
pytest tests/foreman/api/test_ansible.py -k test_positive_ansible_job_on_multiple_host
platform linux -- Python 3.11.1, pytest-7.3.1, pluggy-1.0.0
Mandatory Requirements Available: jinja2==3.1.2
Optional Requirements Available: sphinx==7.0.1 manage>=0.1.13
rootdir: /home/addubey/work/robottelo
plugins: services-2.2.1, mock-3.10.0, reportportal-5.1.7, ibutsu-2.2.4, xdist-3.2.1, cov-3.0.0
collected 8 items / 7 deselected / …
```
=> Close loop - Ansible job invocation shows wrong info after remote execution job

pytest_fixtures/core/contenthosts.py, tests/foreman/api/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11491
Execution of Ansible job on multiple hosts simultaneously
**Test result:**
```
pytest tests/foreman/api/test_ansible.py -k test_positive_ansible_job_on_multiple_host
platform linux -- Python 3.11.1, pytest-7.3.1, pluggy-1.0.0
Mandatory Requirements Available: jinja2==3.1.2
Optional Requirements Available: sphinx==7.0.1 manage>=0.1.13
rootdir: /home/addubey/work/robottelo
plugins: services-2.2.1, mock-3.10.0, reportportal-5.1.7, …
```
=> [6.13.z] Close loop - Ansible job invocation shows wrong info after remote execution job

tests/foreman/api/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11597
This was addressed in the cherrypick of [this PR](https://github.com/SatelliteQE/robottelo/pull/11526), the failing assertion was only removed from 6.13.z, but not 6.14.z
=> [6.14.z] Remove unnecessary failing assertion api/test_http_proxy.py

tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11569
- Parameterised OpenSCAP test was failing due to various reasons, as per discussion we decided to remove the support for rhel6 from scap.
- Also due to regression issue/BZ #2211437 test was failing (in Stream/6.14.0) for rhel7 & rhel8 as well, so added skip marker.
- Test would not run in CI.
- In 6.12 test was failing for rhel6 after running the Ansible playbook (python version issue)
=> [6.12.z] remove rhel6 support from scap test and skip test due to bz 2211437

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11567
null
=> [6.13.z] Fix configure_puppet

tests/foreman/api/test_host.py
With fix not applied:
```
$ pytest tests/foreman/api/test_host.py::test_positive_list_hosts_thin_all
Mandatory Requirements Available: requests==2.31.0 broker[docker]==0.3.2 pytest-reportportal==5.1.8 jinja2==3.1.2 wrapanapi==3.5.15
configfile: pytest.ini
plugins: cov-3.0.0, services-2.2.1, xdist-3.2.1, reportportal-5.1.7, …
```
=> Automate BZ 1969263

tests/foreman/api/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11557
With fix not applied:
```
$ pytest tests/foreman/api/test_host.py::test_positive_list_hosts_thin_all
Mandatory Requirements Available: requests==2.31.0 broker[docker]==0.3.2 pytest-reportportal==5.1.8 jinja2==3.1.2 wrapanapi==3.5.15
configfile: pytest.ini …
```
=> [6.13.z] Automate BZ 1969263

tests/foreman/api/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11557
With fix not applied:
```
$ pytest tests/foreman/api/test_host.py::test_positive_list_hosts_thin_all
Mandatory Requirements Available: requests==2.31.0 broker[docker]==0.3.2 pytest-reportportal==5.1.8 jinja2==3.1.2 wrapanapi==3.5.15
configfile: pytest.ini …
```
=> [6.12.z] Automate BZ 1969263

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11567
null
=> [6.12.z] Fix configure_puppet

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11567
null
=> [6.14.z] Fix configure_puppet

robottelo/api/utils.py, robottelo/host_helpers/capsule_mixins.py
Kind of cherry pick for the previous implementation of the `must_succeed` flag for` wait_for_tasks` method
PR's for reference - https://github.com/SatelliteQE/robottelo/pull/10657/files
https://github.com/SatelliteQE/robottelo/pull/10647/files
PR's failed because of its absence - https://github.com/SatelliteQE/robottelo/pull/11602
=> must_succeed flag for task intended to pass/fail

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11567
null
=> [6.11.z] Fix configure_puppet

pytest_fixtures/core/contenthosts.py, tests/foreman/api/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11491
Execution of Ansible job on multiple hosts simultaneously
**Test result:**
```
pytest tests/foreman/api/test_ansible.py -k test_positive_ansible_job_on_multiple_host
platform linux -- Python 3.11.1, pytest-7.3.1, pluggy-1.0.0
Mandatory Requirements Available: jinja2==3.1.2
Optional Requirements Available: sphinx==7.0.1 manage>=0.1.13
rootdir: /home/addubey/work/robottelo
plugins: services-2.2.1, mock-3.10.0, reportportal-5.1.7, …
```
=> [6.12.z] Close loop - Ansible job invocation shows wrong info after remote execution job

tests/foreman/api/test_user.py
Requires https://github.com/SatelliteQE/nailgun/pull/928 . Test results included there.
=> Close-loop 1757394

tests/foreman/api/test_user.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11609
Requires https://github.com/SatelliteQE/nailgun/pull/928 . Test results included there.
=> [6.12.z] Close-loop 1757394

tests/upgrades/conftest.py, tests/upgrades/test_errata.py, tests/upgrades/test_remoteexecution.py, tests/upgrades/test_subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11504
This pull request introduces enhanced support for parameterization upgrade scenarios. The upgrade process now involves saving data in the scenarios_entities file for each parameter during the pre-upgrade steps. This allows for more flexible and efficient handling of upgrades involving parameterization. Additionally, the implementation includes a mechanism to retry the upgrade process using the post-upgrade steps, ensuring a robust and reliable upgrade experience.
- Data Persistence: The upgrade process now saves relevant data in the scenarios_entities file for each parameter involved in the upgrade. This enables seamless tracking and management of parameterization upgrade scenarios.
- Pre-upgrade Steps: The codebase has …
=> [6.13.z] adding support for parameterization upgrade scenarios

tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11569
- Parameterised OpenSCAP test was failing due to various reasons, as per discussion we decided to remove the support for rhel6 from scap.
- Also due to regression issue/BZ #2211437 test was failing (in Stream/6.14.0) for rhel7 & rhel8 as well, so added skip marker.
- Test would not run in CI.
- In 6.12 test was failing for rhel6 after running the Ansible playbook (python version issue)
=> [6.14.z] remove rhel6 support from scap test and skip test due to bz 2211437

tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11569
- Parameterised OpenSCAP test was failing due to various reasons, as per discussion we decided to remove the support for rhel6 from scap.
- Also due to regression issue/BZ #2211437 test was failing (in Stream/6.14.0) for rhel7 & rhel8 as well, so added skip marker.
- Test would not run in CI.
- In 6.12 test was failing for rhel6 after running the Ansible playbook (python version issue)
=> [6.13.z] remove rhel6 support from scap test and skip test due to bz 2211437

pytest_fixtures/component/repository.py, robottelo/host_helpers/repository_mixins.py
This is just a proposal to fix the setup for `test_errata_installation_with_swidtags` test (an potentially few others using the  same fixture). The test fails in setup due to the fact that SCA is enabled and custom repos (in AK) are disabled by default in 6.14.
So I just decided to skip the subscription manipulation and do the content override on AK creation time.
=> Fix activation key setup

pytest_fixtures/component/repository.py, robottelo/host_helpers/repository_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11667
This is just a proposal to fix the setup for `test_errata_installation_with_swidtags` test (an potentially few others using the  same fixture). The test fails in setup due to the fact that SCA is enabled and custom repos (in AK) are disabled by default in 6.14.
So I just decided to skip the subscription manipulation and do the content override on AK creation time.
=> [6.14.z] Fix activation key setup

robottelo/host_helpers/repository_mixins.py
Similar to #11667, this proposes a fix in `setup_activation_key` when the org is SCA-enabled and thus no subscription manipulation is relevant.
=> [6.13.z] Fix activation key setup

pytest_plugins/rerun_rp/rerun_rp.py
=> `rp_api_key` replaced `rp_uuid` in RP pytest plugin config

pytest_plugins/rerun_rp/rerun_rp.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11678
=> [6.14.z] `rp_api_key` replaced `rp_uuid` in RP pytest plugin config

pytest_plugins/rerun_rp/rerun_rp.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11678
=> [6.13.z] `rp_api_key` replaced `rp_uuid` in RP pytest plugin config

pytest_plugins/rerun_rp/rerun_rp.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11678
=> [6.12.z] `rp_api_key` replaced `rp_uuid` in RP pytest plugin config

pytest_plugins/rerun_rp/rerun_rp.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11678
=> [6.11.z] `rp_api_key` replaced `rp_uuid` in RP pytest plugin config

pytest_fixtures/component/satellite_auth.py, pytest_fixtures/core/sat_cap_factory.py, robottelo/hosts.py, tests/foreman/cli/test_ldapauthsource.py, tests/foreman/ui/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11445
Every time GH Actions run  `pytest tests/robottelo/` we see the following warning message multiple times in one run. See [the following GitHub Actions run](https://github.com/SatelliteQE/robottelo/actions/runs/4892389046/jobs/8734088618#step:8:891)
```
PASSED
2023-05-05 10:30:21 - robottelo.collection - INFO - Processing test items to add testimony token markers
tests/robottelo/test_report.py::test_junit_timestamps[dummy_test-non_xdist-testcase] ..                                                                       [100%]
../../../../../opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/_pytest/config/__init__.py:747 …
```
=> [6.12.z] Fix for PytestAssertRewriteWarning

tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11630
```
$ pytest tests/foreman/cli/test_host.py::test_positive_list_with_nested_hostgroup
Mandatory Requirements Available: broker[docker]==0.3.2 requests==2.31.0 pytest-reportportal==5.1.8 pytest-xdist==3.3.1 wrapanapi==3.5.15 cryptography==41.0.1 jinja2==3.1.2
Optional Requirements Available: pre-commit==3.3.2 redis==4.5.5 manage>=0.1.13 sphinx==7.0.1 …
```
=> [6.12.z] Close-loop BZ 1955421

pytest_fixtures/component/satellite_auth.py, robottelo/hosts.py, tests/foreman/cli/test_ldapauthsource.py, tests/foreman/ui/test_ldap_authentication.py
Cherry-pick of #11445.
Fixes #11527.
* Fix for PytestAssertRewriteWarning
This patch fixes the following warning:
PASSED
2023-05-05 10:30:21 - robottelo.collection - INFO - Processing test items to add testimony token markers
tests/robottelo/test_report.py::test_junit_timestamps[dummy_test-non_xdist-testcase] ..                                                                       [100%]
../../../../../opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/_pytest/config/__init__.py:747
/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/_pytest/config/__init__.py:747: PytestAssertRewriteWarning: Module already imported so cannot be rewritten: …
=> [6.11.z] Fix for PytestAssertRewriteWarning

tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11630
```
$ pytest tests/foreman/cli/test_host.py::test_positive_list_with_nested_hostgroup
Mandatory Requirements Available: broker[docker]==0.3.2 requests==2.31.0 pytest-reportportal==5.1.8 pytest-xdist==3.3.1 wrapanapi==3.5.15 cryptography==41.0.1 jinja2==3.1.2
Optional Requirements Available: pre-commit==3.3.2 redis==4.5.5 manage>=0.1.13 sphinx==7.0.1 …
```
=> [6.13.z] Close-loop BZ 1955421

pytest_plugins/requirements/update_requirements.py
=> CI declines colorcodes and so for req assist plugin

pytest_plugins/requirements/update_requirements.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11677
This PR:
=> [6.13.z] CI declines colorcodes and so for req assist plugin

pytest_plugins/requirements/update_requirements.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11677
This PR:
=> [6.14.z] CI declines colorcodes and so for req assist plugin

pytest_plugins/requirements/update_requirements.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11677
This PR:
=> [6.11.z] CI declines colorcodes and so for req assist plugin

pytest_plugins/requirements/update_requirements.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11677
This PR:
=> [6.12.z] CI declines colorcodes and so for req assist plugin

tests/foreman/api/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11683
Adds coverage for:
https://bugzilla.redhat.com/show_bug.cgi?id=2043089
https://bugzilla.redhat.com/show_bug.cgi?id=2211962
Requires https://github.com/SatelliteQE/nailgun/pull/935
=> [6.14.z] Add test for orphaned content removal from capsule

tests/foreman/maintain/test_advanced.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11684
Fixes `foreman/maintain/test_advanced.py::test_positive_satellite_repositories_setup`. The test fails because 6.13 is now GA. This updates the test to accommodate this. Also removes a part of the test for beta that is no longer relevant.
=> [6.13.z] Fix failing foreman/maintain/advanced test

tests/foreman/maintain/test_advanced.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11684
Fixes `foreman/maintain/test_advanced.py::test_positive_satellite_repositories_setup`. The test fails because 6.13 is now GA. This updates the test to accommodate this. Also removes a part of the test for beta that is no longer relevant.
=> [6.14.z] Fix failing foreman/maintain/advanced test

testimony.yaml, tests/foreman/cli/test_host.py, tests/foreman/ui/test_host.py
The `Katello-tracer` tests are not collected properly in automation and it seems the case is the culprit in this case.
```
05:02:40  + py.test '-m not stream' -v -rEfs --tb=short -n2 --dist loadscope tests/foreman --component Katello-tracer --junit-xml=sat-Katello-tracer-results.xml --durations=20 --durations-min=600.0 -o junit_suite_name=sat-Katello-tracer --collect-only -q
05:02:55  ============================= test session starts ==============================
...
05:03:42  collected 6093 items / 6093 deselected / 0 selected
```
Because all other components are strictly uppercase, switching this to upper too.
Plus updating the team.
=> Fix Katello-tracer component case

testimony.yaml, tests/foreman/cli/test_host.py, tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11708
The `Katello-tracer` tests are not collected properly in automation and it seems the case is the culprit in this case.
```
05:02:40  + py.test '-m not stream' -v -rEfs --tb=short -n2 --dist loadscope tests/foreman --component Katello-tracer --junit-xml=sat-Katello-tracer-results.xml --durations=20 --durations-min=600.0 -o junit_suite_name=sat-Katello-tracer --collect-only -q
05:02:55  ============================= test session starts ==============================
...
05:03:42  collected 6093 items / 6093 deselected / 0 selected
```
Because all other components are strictly uppercase, switching this to upper too.
Plus updating the team.
=> [6.13.z] Fix Katello-tracer component case

tests/foreman/endtoend/test_api_endtoend.py, tests/foreman/endtoend/test_cli_endtoend.py, tests/foreman/longrun/test_inc_updates.py
This PR converts to manifester all tests using manifests to that are not contained in the API, CLI, or UI namespaces.
=> Convert remaining tests to manifester

tests/foreman/maintain/test_backup_restore.py
Coverage for https://bugzilla.redhat.com/show_bug.cgi?id=1978764. The backup and restore tests are what we run with remote DB so this should automatically cover the scenario in the BZ.
=> Adding service status coverage to backup and restore

tests/foreman/maintain/test_backup_restore.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11716
Coverage for https://bugzilla.redhat.com/show_bug.cgi?id=1978764. The backup and restore tests are what we run with remote DB so this should automatically cover the scenario in the BZ.
=> [6.13.z] Adding service status coverage to backup and restore

tests/foreman/maintain/test_backup_restore.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11716
Coverage for https://bugzilla.redhat.com/show_bug.cgi?id=1978764. The backup and restore tests are what we run with remote DB so this should automatically cover the scenario in the BZ.
=> [6.14.z] Adding service status coverage to backup and restore

tests/upgrades/test_virtwho.py
Because ORG_DATA = {'name': 'virtwho_upgrade_org_name'} exist will effect the pre-upgrade case, so clean it before run the case, not use the dynamic name ,because post-upgrade will also this name
case : PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade --disable-pytest-warnings
platform linux -- Python 3.10.9, pytest-7.3.2, pluggy-1.0.0
rootdir: /home/virtwho/repository/robottelo …
```
=> add delete org before run virt-who config upgrade cases

tests/upgrades/test_virtwho.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11706
Because ORG_DATA = {'name': 'virtwho_upgrade_org_name'} exist will effect the pre-upgrade case, so clean it before run the case, not use the dynamic name ,because post-upgrade will also this name
case : PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade --disable-pytest-warnings
platform linux -- Python 3.10.9, pytest-7.3.2, pluggy-1.0.0
shared_function enabled - OFF …
```
=> [6.12.z] add delete org before run virt-who config upgrade cases

robottelo/content_info.py
Pulpcore 22.2.0 enhanced repository content listing by adding dates and browse up link (`../`), which broke the recursive repo scraping we use to validate the content published on both, Satellite and Capsule. See the latest Capsule-Content results:
```
tests/foreman/api/test_capsulecontent.py:129: in test_positive_uploaded_content_library_sync
caps_files = get_repo_files_by_url(caps_repo_url)
robottelo/content_info.py:68: in get_repo_files_by_url
return sorted([os.path.basename(f) for f in get_repo_files_urls_by_url(url, extension)])
robottelo/content_info.py:57: in get_repo_files_urls_by_url
files.extend(get_repo_files_urls_by_url(sub, extension))
robottelo/content_info.py:57: in get_repo_files_urls_by_url
files.extend(get_repo_files_urls_by_url(sub, extension))
...
raise exc from None
E …
```
=> Fix repo scraping

robottelo/content_info.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11741
Pulpcore 22.2.0 enhanced repository content listing by adding dates and browse up link (`../`), which broke the recursive repo scraping we use to validate the content published on both, Satellite and Capsule. See the latest Capsule-Content results:
```
tests/foreman/api/test_capsulecontent.py:129: in test_positive_uploaded_content_library_sync
caps_files = get_repo_files_by_url(caps_repo_url)
robottelo/content_info.py:68: in get_repo_files_by_url
return sorted([os.path.basename(f) for f in get_repo_files_urls_by_url(url, extension)])
robottelo/content_info.py:57: in get_repo_files_urls_by_url
files.extend(get_repo_files_urls_by_url(sub, extension))
robottelo/content_info.py:57: in get_repo_files_urls_by_url …
```
=> [6.13.z] Fix repo scraping

robottelo/content_info.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11741
Pulpcore 22.2.0 enhanced repository content listing by adding dates and browse up link (`../`), which broke the recursive repo scraping we use to validate the content published on both, Satellite and Capsule. See the latest Capsule-Content results:
```
tests/foreman/api/test_capsulecontent.py:129: in test_positive_uploaded_content_library_sync
caps_files = get_repo_files_by_url(caps_repo_url)
robottelo/content_info.py:68: in get_repo_files_by_url
return sorted([os.path.basename(f) for f in get_repo_files_urls_by_url(url, extension)])
robottelo/content_info.py:57: in get_repo_files_urls_by_url
files.extend(get_repo_files_urls_by_url(sub, extension))
robottelo/content_info.py:57: in get_repo_files_urls_by_url …
```
=> [6.12.z] Fix repo scraping

robottelo/content_info.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11741
Pulpcore 22.2.0 enhanced repository content listing by adding dates and browse up link (`../`), which broke the recursive repo scraping we use to validate the content published on both, Satellite and Capsule. See the latest Capsule-Content results:
```
tests/foreman/api/test_capsulecontent.py:129: in test_positive_uploaded_content_library_sync
caps_files = get_repo_files_by_url(caps_repo_url)
robottelo/content_info.py:68: in get_repo_files_by_url
return sorted([os.path.basename(f) for f in get_repo_files_urls_by_url(url, extension)])
robottelo/content_info.py:57: in get_repo_files_urls_by_url
files.extend(get_repo_files_urls_by_url(sub, extension))
robottelo/content_info.py:57: in get_repo_files_urls_by_url …
```
=> [6.14.z] Fix repo scraping

conf/capsule.yaml.template, conf/flavors.yaml.template, pytest_fixtures/core/contenthosts.py, pytest_fixtures/core/sat_cap_factory.py, robottelo/config/validators.py, tests/foreman/destructive/test_capsulecontent.py
This PR adds coverage for [BZ#2062526](https://bugzilla.redhat.com/show_bug.cgi?id=2062526)
For this scenario to run we need ~400 GiB storage on Capsule with RHEL7 repo (or ~120 GiB with RHSCL repo), so I had to use larger `deploy_flavor` for the Capsule.
Originally the scenario was intended to use RHEL7 repo, but due to another [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2122872) causing OOM extinction and sync task failure, I decided to go with half-sized RHSCL, which was capable to cause the deadlock too.
If/when the gunicorn BZ is resolved, we can get back to the RHEL7 repo and tweak the test for higher load.
=> Add test for the Capsule sync deadlock issue

conf/capsule.yaml.template, conf/flavors.yaml.template, pytest_fixtures/core/contenthosts.py, pytest_fixtures/core/sat_cap_factory.py, robottelo/config/validators.py, tests/foreman/destructive/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10424
This PR adds coverage for [BZ#2062526](https://bugzilla.redhat.com/show_bug.cgi?id=2062526)
For this scenario to run we need ~400 GiB storage on Capsule with RHEL7 repo (or ~120 GiB with RHSCL repo), so I had to use larger `deploy_flavor` for the Capsule.
Originally the scenario was intended to use RHEL7 repo, but due to another [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2122872) causing OOM extinction and sync task failure, I decided to go with half-sized RHSCL, which was capable to cause the deadlock too.
If/when the gunicorn BZ is resolved, we can get back to the RHEL7 repo and tweak the test for higher load.
=> [6.14.z] Add test for the Capsule sync deadlock issue

robottelo/cli/factory.py, robottelo/host_helpers/cli_factory.py, tests/foreman/api/test_reporttemplates.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11561
Test for Host - Applied Errata report template ( Very simple, just checking for the installed errata, and verifying the date field is there, and is correct ) 
This also includes an update to a clifactory method used to generate a custom product for use in Errata tests, as well as used within the new Applied Errata test. In 6.14, custom products were all disabled by default, and this overrides that to true.
=> [6.14.z] Applied errata template test and custom product fix

pytest_fixtures/component/provision_pxe.py
Due to 6.14 [RFE](https://bugzilla.redhat.com/show_bug.cgi?id=1265120)  custom products are default disabled in AK/Host (being tested by @ColeHiggins2), so here for provisioning we need to override custom client repo to be enabled prior to provisioning, so host param like enable-puppet5 could install puppet-agent itself while provisioning.
=> Enable client_repo in AK for provisioning

pytest_fixtures/component/settings.py, tests/foreman/cli/test_computeresource_rhev.py, tests/foreman/longrun/test_provisioning_computeresource.py, tests/foreman/ui/test_host.py
1. Already covered https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_computeresource_rhev.py#L411
2. Use destroy_vm_on_host_delete setting to cleanup hosts in rhevm when deleted from satellite in teardown
=> Remove redundant rhev provisioning test

pytest_fixtures/component/settings.py, tests/foreman/cli/test_computeresource_rhev.py, tests/foreman/longrun/test_provisioning_computeresource.py, tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11737
1. Already covered https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_computeresource_rhev.py#L411
2. Use destroy_vm_on_host_delete setting to cleanup hosts in rhevm when deleted from satellite in teardown
=> [6.13.z] Remove redundant rhev provisioning test

tests/foreman/api/test_repository.py, tests/foreman/ui/test_containerimagetag.py
Two container repo tests are failing in setup due to longer sync times than expected. This PR addds 50% extra time to the current sync times.
=> Fix container repo tests

pytest_fixtures/component/provision_pxe.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11735
Due to 6.14 [RFE](https://bugzilla.redhat.com/show_bug.cgi?id=1265120)  custom products are default disabled in AK/Host (being tested by @ColeHiggins2), so here for provisioning we need to override custom client repo to be enabled prior to provisioning, so host param like enable-puppet5 could install puppet-agent itself while provisioning.
=> [6.14.z] Enable client_repo in AK for provisioning

tests/foreman/api/test_repository.py, tests/foreman/ui/test_containerimagetag.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11771
Two container repo tests are failing in setup due to longer sync times than expected. This PR addds 50% extra time to the current sync times.
=> [6.14.z] Fix container repo tests

tests/foreman/api/test_repository.py, tests/foreman/ui/test_containerimagetag.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11771
Two container repo tests are failing in setup due to longer sync times than expected. This PR addds 50% extra time to the current sync times.
=> [6.13.z] Fix container repo tests

tests/foreman/endtoend/test_api_endtoend.py, tests/foreman/endtoend/test_cli_endtoend.py
stop relying on rhel7_contenthost, using rhel8 now, future parametrization made possible
=> e2e tests updated a bit

tests/foreman/endtoend/test_api_endtoend.py, tests/foreman/endtoend/test_cli_endtoend.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11465
stop relying on rhel7_contenthost, using rhel8 now, future parametrization made possible
=> [6.14.z] e2e tests updated a bit

tests/foreman/endtoend/test_api_endtoend.py, tests/foreman/endtoend/test_cli_endtoend.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11465
stop relying on rhel7_contenthost, using rhel8 now, future parametrization made possible
=> [6.13.z] e2e tests updated a bit

pytest_fixtures/component/settings.py, tests/foreman/cli/test_computeresource_rhev.py, tests/foreman/longrun/test_provisioning_computeresource.py, tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11737
1. Already covered https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_computeresource_rhev.py#L411
2. Use destroy_vm_on_host_delete setting to cleanup hosts in rhevm when deleted from satellite in teardown
=> [6.14.z] Remove redundant rhev provisioning test

tests/foreman/virtwho/api/test_esx.py, tests/foreman/virtwho/api/test_hyperv.py, tests/foreman/virtwho/api/test_kubevirt.py, tests/foreman/virtwho/api/test_libvirt.py, tests/foreman/virtwho/api/test_nutanix.py, tests/foreman/virtwho/cli/test_esx.py, tests/foreman/virtwho/cli/test_esx_sca.py, tests/foreman/virtwho/cli/test_hyperv.py, tests/foreman/virtwho/cli/test_hyperv_sca.py, tests/foreman/virtwho/cli/test_kubevirt.py, tests/foreman/virtwho/cli/test_kubevirt_sca.py, tests/foreman/virtwho/cli/test_libvirt.py, tests/foreman/virtwho/cli/test_libvirt_sca.py, tests/foreman/virtwho/cli/test_nutanix.py, tests/foreman/virtwho/cli/test_nutanix_sca.py, tests/foreman/virtwho/ui/test_esx.py, tests/foreman/virtwho/ui/test_hyperv.py, tests/foreman/virtwho/ui/test_kubevirt.py, tests/foreman/virtwho/ui/test_libvirt.py, tests/foreman/virtwho/ui/test_nutanix.py
Realize the two functions:
1. virtwho UI cases to support for Content Host Legacy UI 
2. parametrize to consolidate multiple cases with duplicated steps into one
This PR depends on the the PR
https://github.com/SatelliteQE/airgun/pull/850
Cases PASS:
```
CLI：
ESX：
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_esx.py -k test_positive_deploy_configure_by_id_script --disable-warnings -q
2 passed, 22 deselected, 2 warnings in 308.98s (0:05:08)
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest …
```
=> virtwho UI cases to support for Content Host Legacy UI and parametrize to consolidate multiple cases with duplicated steps into one

tests/foreman/api/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11433
Leaving this in draft for now, but this will contain a few of the initial tests for the publish audit feature. 
Needs this nailgun PR: https://github.com/SatelliteQE/nailgun/pull/922
=> [6.14.z] Content View Audit Tests

robottelo/hosts.py
The global registration dialog changed since this function was created, it is possible to not specify org and loc, which the register function didn't allow. The function also demanded org supplied as an object, which caused problems in onboarding more tests to it (some use org defined as a dict -- an output from cli helpers). PR changes the function in a way that doesn't require updating the existing callers
=> register function made more flexible

pytest_fixtures/component/settings.py, tests/foreman/cli/test_computeresource_rhev.py, tests/foreman/longrun/test_provisioning_computeresource.py, tests/foreman/ui/test_host.py
Cherrypick of https://github.com/SatelliteQE/robottelo/pull/11737
Fixes https://github.com/SatelliteQE/robottelo/issues/11774
=> [6.12.z] Remove redundant rhev provisioning test

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11783
The global registration dialog changed since this function was created, it is possible to not specify org and loc, which the register function didn't allow. The function also demanded org supplied as an object, which caused problems in onboarding more tests to it (some use org defined as a dict -- an output from cli helpers). PR changes the function in a way that doesn't require updating the existing callers
=> [6.13.z] register function made more flexible

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11783
The global registration dialog changed since this function was created, it is possible to not specify org and loc, which the register function didn't allow. The function also demanded org supplied as an object, which caused problems in onboarding more tests to it (some use org defined as a dict -- an output from cli helpers). PR changes the function in a way that doesn't require updating the existing callers
=> [6.14.z] register function made more flexible

.github/workflows/dependency_merge.yml
https://github.com/SatelliteQE/robottelo/actions/runs/5440265424/jobs/9893025022?pr=11790
https://github.com/SatelliteQE/robottelo/pull/11790
`cmd: yq e ".broker[docker]" ./.github/dependency_tests.yaml` was not resolving the node in the yaml file. 
this fix will resolve that. Verified on the personal fork.   
https://github.com/omkarkhatavkar/robottelo/pull/130
=> handle the condition for dependancy has brackets []

pytest_fixtures/core/contenthosts.py, tests/foreman/cli/test_host.py
The fixture now uses global registration + it plays nicely with SCA, which fixes a bunch of tests in the host component
=> katello_host_tools_host fixture fix

pytest_fixtures/core/contenthosts.py, tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11799
The fixture now uses global registration + it plays nicely with SCA, which fixes a bunch of tests in the host component
=> [6.13.z] katello_host_tools_host fixture fix

pytest_fixtures/core/contenthosts.py, tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11799
The fixture now uses global registration + it plays nicely with SCA, which fixes a bunch of tests in the host component
=> [6.14.z] katello_host_tools_host fixture fix

pytest_fixtures/core/contenthosts.py
let the rex_contenthost fixture use the register function, needs https://github.com/SatelliteQE/robottelo/pull/11783 to get in first
=> rex_contenthost now using global registration

tests/foreman/installer/test_installer.py
Add `foreman-rails-cache-store type:redis` to satellite-installer test.
=> Add test for redis type foreman-rails-cache-store

pytest_fixtures/core/contenthosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11786
let the rex_contenthost fixture use the register function, needs https://github.com/SatelliteQE/robottelo/pull/11783 to get in first
=> [6.13.z] rex_contenthost now using global registration

tests/foreman/virtwho/api/test_esx.py, tests/foreman/virtwho/api/test_hyperv.py, tests/foreman/virtwho/api/test_kubevirt.py, tests/foreman/virtwho/api/test_libvirt.py, tests/foreman/virtwho/api/test_nutanix.py, tests/foreman/virtwho/cli/test_esx.py, tests/foreman/virtwho/cli/test_esx_sca.py, tests/foreman/virtwho/cli/test_hyperv.py, tests/foreman/virtwho/cli/test_hyperv_sca.py, tests/foreman/virtwho/cli/test_kubevirt.py, tests/foreman/virtwho/cli/test_kubevirt_sca.py, tests/foreman/virtwho/cli/test_libvirt.py, tests/foreman/virtwho/cli/test_libvirt_sca.py, tests/foreman/virtwho/cli/test_nutanix.py, tests/foreman/virtwho/cli/test_nutanix_sca.py, tests/foreman/virtwho/ui/test_esx.py, tests/foreman/virtwho/ui/test_hyperv.py, tests/foreman/virtwho/ui/test_kubevirt.py, tests/foreman/virtwho/ui/test_libvirt.py, tests/foreman/virtwho/ui/test_nutanix.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11543
Realize the two functions:
1. virtwho UI cases to support for Content Host Legacy UI 
2. parametrize to consolidate multiple cases with duplicated steps into one
This PR depends on the the PR
https://github.com/SatelliteQE/airgun/pull/850
Cases PASS:
```
CLI：
ESX：
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_esx.py -k test_positive_deploy_configure_by_id_script --disable-warnings -q
2 passed, 22 deselected, 2 warnings in 308.98s (0:05:08)
(robottelo_vv) …
```
=> [6.14.z] virtwho UI cases to support for Content Host Legacy UI and parametrize to consolidate multiple cases with duplicated steps into one

tests/foreman/virtwho/ui/test_esx.py, tests/foreman/virtwho/ui/test_esx_sca.py
Update checktime format
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k test_positive_last_checkin_status --disable-pytest-warnings -q
1 passed, 33 deselected, 5 warnings in 188.94s (0:03:08)
```
Satellite6.13 cases : PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k test_positive_last_checkin_status --disable-pytest-warnings -q
. …
```
=> update checktime format for contenthost

tests/foreman/virtwho/api/test_esx_sca.py
Modify the whiltelist and blacklist item name.
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/api/test_esx_sca.py -k test_positive_filter_option --disable-pytest-warnings -q
....                                                                                                                                                                                                        [100%]
4 passed, 22 deselected, 21 warnings in 192.63s (0:03:12)
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/api/test_esx_sca.py -k test_positive_filter_option --disable-pytest-warnings -q
.... …
```
=> virtwho-config:Update whitelist&blacklist

tests/foreman/virtwho/ui/test_nutanix.py
Satellite6.14 cases :  PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest tests/foreman/virtwho/ui/test_nutanix.py -k test_positive_prism_central_deploy_configure_by_id_script  --disable-pytest-warnings -q
2 passed, 12 deselected, 4 warnings in 872.06s (0:14:32)
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest tests/foreman/virtwho/ui/test_nutanix.py -k test_positive_ahv_internal_debug_option  --disable-pytest-warnings -q
. …
```
=> add Legacy content UI support for nutanix prism central & ahv option modification

tests/foreman/virtwho/ui/test_esx.py, tests/foreman/virtwho/ui/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11811
Update checktime format
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k test_positive_last_checkin_status --disable-pytest-warnings -q
1 passed, 33 deselected, 5 warnings in 188.94s (0:03:08)
```
Satellite6.13 cases : PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k test_positive_last_checkin_status --disable-pytest-warnings -q
. …
```
=> [6.14.z] update checktime format for contenthost

tests/foreman/virtwho/ui/test_esx.py, tests/foreman/virtwho/ui/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11811
Update checktime format
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k test_positive_last_checkin_status --disable-pytest-warnings -q
1 passed, 33 deselected, 5 warnings in 188.94s (0:03:08)
```
Satellite6.13 cases : PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k test_positive_last_checkin_status --disable-pytest-warnings -q
. …
```
=> [6.13.z] update checktime format for contenthost

tests/foreman/virtwho/api/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11809
Modify the whiltelist and blacklist item name.
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/api/test_esx_sca.py -k test_positive_filter_option --disable-pytest-warnings -q
....                                                                                                                                                                                                        [100%]
4 passed, 22 deselected, 21 warnings in 192.63s (0:03:12)
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/api/test_esx_sca.py -k test_positive_filter_option --disable-pytest-warnings -q
.... …
```
=> [6.14.z] virtwho-config:Update whitelist&blacklist

tests/foreman/virtwho/api/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11809
Modify the whiltelist and blacklist item name.
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/api/test_esx_sca.py -k test_positive_filter_option --disable-pytest-warnings -q
....                                                                                                                                                                                                        [100%]
4 passed, 22 deselected, 21 warnings in 192.63s (0:03:12)
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/api/test_esx_sca.py -k test_positive_filter_option --disable-pytest-warnings -q
.... …
```
=> [6.13.z] virtwho-config:Update whitelist&blacklist

tests/foreman/virtwho/ui/test_nutanix.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11812
Satellite6.14 cases :  PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest tests/foreman/virtwho/ui/test_nutanix.py -k test_positive_prism_central_deploy_configure_by_id_script  --disable-pytest-warnings -q
2 passed, 12 deselected, 4 warnings in 872.06s (0:14:32)
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest tests/foreman/virtwho/ui/test_nutanix.py -k test_positive_ahv_internal_debug_option  --disable-pytest-warnings -q
. …
```
=> [6.14.z] add Legacy content UI support for nutanix prism central & ahv option modification

tests/foreman/virtwho/ui/test_nutanix.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11812
Satellite6.14 cases :  PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest tests/foreman/virtwho/ui/test_nutanix.py -k test_positive_prism_central_deploy_configure_by_id_script  --disable-pytest-warnings -q
2 passed, 12 deselected, 4 warnings in 872.06s (0:14:32)
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest tests/foreman/virtwho/ui/test_nutanix.py -k test_positive_ahv_internal_debug_option  --disable-pytest-warnings -q
. …
```
=> [6.13.z] add Legacy content UI support for nutanix prism central & ahv option modification

tests/upgrades/test_repository.py
SAT-16805
Upgrade scenario for enabled repos in non-sca org
In a non-sca organization, enabled repos with an attached subscription should be set to "Enabled(Override)" after an upgrade to 6.14.
=> [6.14 RFE] Upgrade test for enabled repos in sca

pytest_fixtures/component/repository.py, tests/foreman/api/test_repositories.py, tests/foreman/cli/test_repositories.py, tests/foreman/ui/test_repositories.py
These tests are for SAT-16805
Custom products should be disabled by default when attaching to a content host in 6.14
Wait to be Merged:
https://github.com/SatelliteQE/airgun/pull/852
=> [6.14 RFE] Custom products disabled by default

tests/upgrades/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11729
SAT-16805
Upgrade scenario for enabled repos in non-sca org
In a non-sca organization, enabled repos with an attached subscription should be set to "Enabled(Override)" after an upgrade to 6.14.
=> [6.14.z] [6.14 RFE] Upgrade test for enabled repos in sca

pytest_fixtures/component/provision_pxe.py, robottelo/hosts.py, tests/foreman/cli/test_host.py
This patch reverts commit 8ece887 - "Handle stream versions in version cached_property (#11467)".
#11467 has updated the `version` property to return the `stream` string if the respective Satellite/Capsule is a stream release.
This breaks the compatibility of this method in most places where we use it.
Two places where #11467 broke the logic:
* `is_open` method throws `packaging.version.InvalidVersion: Invalid version: 'stream'` if the Sat release is stream.
* With 6.15 which will start supporting RHEL 9, we will need to change the parametrization of `test_positive_leapp`. There we check for `get_sat_version().minor != 11` which will change to `get_sat_version().minor != 15`.  The patch in #11571 does not help as `get_sat_version` would return `Version('9999')` which has no minor version. …
=> Tweaks for the Satellite version properties

pytest_fixtures/component/provision_pxe.py, robottelo/hosts.py, tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11572
This patch reverts commit 8ece887 - "Handle stream versions in version cached_property (#11467)".
#11467 has updated the `version` property to return the `stream` string if the respective Satellite/Capsule is a stream release.
This breaks the compatibility of this method in most places where we use it.
Two places where #11467 broke the logic:
* `is_open` method throws `packaging.version.InvalidVersion: Invalid version: 'stream'` if the Sat release is stream.
* With 6.15 which will start supporting RHEL 9, we will need to change the parametrization of `test_positive_leapp`. There we check for `get_sat_version().minor != 11` which will change to `get_sat_version().minor != 15`.  The patch in #11571 does not help as …
=> [6.14.z] Tweaks for the Satellite version properties

conf/vmware.yaml.template, tests/foreman/ui/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11748
Uses the structure of a preexisting test, the vm_import test, to get Satellite in a state where you can view the newly added Virtualization card. Having some issues running this locally, going to get it put up and see if PRT has the same issues. 
Requires https://github.com/SatelliteQE/airgun/pull/869
=> [6.14.z] Test exercising new Virtualization card

tests/foreman/virtwho/api/test_esx.py, tests/foreman/virtwho/api/test_hyperv.py, tests/foreman/virtwho/api/test_kubevirt.py, tests/foreman/virtwho/api/test_libvirt.py, tests/foreman/virtwho/api/test_nutanix.py, tests/foreman/virtwho/cli/test_esx.py, tests/foreman/virtwho/cli/test_esx_sca.py, tests/foreman/virtwho/cli/test_hyperv.py, tests/foreman/virtwho/cli/test_hyperv_sca.py, tests/foreman/virtwho/cli/test_kubevirt.py, tests/foreman/virtwho/cli/test_kubevirt_sca.py, tests/foreman/virtwho/cli/test_libvirt.py, tests/foreman/virtwho/cli/test_libvirt_sca.py, tests/foreman/virtwho/cli/test_nutanix.py, tests/foreman/virtwho/cli/test_nutanix_sca.py, tests/foreman/virtwho/ui/test_esx.py, tests/foreman/virtwho/ui/test_hyperv.py, tests/foreman/virtwho/ui/test_kubevirt.py, tests/foreman/virtwho/ui/test_libvirt.py, tests/foreman/virtwho/ui/test_nutanix.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11543
Realize the two functions:
1. virtwho UI cases to support for Content Host Legacy UI 
2. parametrize to consolidate multiple cases with duplicated steps into one
This PR depends on the the PR
https://github.com/SatelliteQE/airgun/pull/850
Cases PASS:
```
CLI：
ESX：
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_esx.py -k test_positive_deploy_configure_by_id_script --disable-warnings -q
2 passed, 22 deselected, 2 warnings in 308.98s (0:05:08)
(robottelo_vv) …
```
=> [6.13.z] virtwho UI cases to support for Content Host Legacy UI and parametrize to consolidate multiple cases with duplicated steps into one

tests/foreman/cli/test_host.py, tests/foreman/cli/test_registration.py
This is Part1 of Registration Component Audit. This PR will Modify/Delete the test cases which uses deprecated method of host registration using subscription-manager command. Following test cases are impacted by it.
1. test_positive_list_and_unregister : Modified to use global registration method
2. test_positive_register_with_no_ak : Removed. Global Registration doesn't allow Host registration without activation key.
3. test_negative_register_twice : Modified to use global registration method.
=> [Component Audit][Part1]Modify/Delete deprecated registration method

tests/foreman/cli/test_host.py, tests/foreman/cli/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11766
This is Part1 of Registration Component Audit. This PR will Modify/Delete the test cases which uses deprecated method of host registration using subscription-manager command. Following test cases are impacted by it.
1. test_positive_list_and_unregister : Modified to use global registration method
2. test_positive_register_with_no_ak : Removed. Global Registration doesn't allow Host registration without activation key.
3. test_negative_register_twice : Modified to use global registration method.
=> [6.14.z] [Component Audit][Part1]Modify/Delete deprecated registration method

tests/foreman/cli/test_host.py, tests/foreman/cli/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11766
This is Part1 of Registration Component Audit. This PR will Modify/Delete the test cases which uses deprecated method of host registration using subscription-manager command. Following test cases are impacted by it.
1. test_positive_list_and_unregister : Modified to use global registration method
2. test_positive_register_with_no_ak : Removed. Global Registration doesn't allow Host registration without activation key.
3. test_negative_register_twice : Modified to use global registration method.
=> [6.13.z] [Component Audit][Part1]Modify/Delete deprecated registration method

robottelo/cli/factory.py, robottelo/host_helpers/cli_factory.py, tests/foreman/cli/test_operatingsystem.py
This PR aims to refactor Operating System CLI tests. There were many OS tests which are combined into one end-to-end test.
- Removing  tests which are covered already either in e2e or in some other tests
=> Component audit - Modify/Delete CLI OS tests

robottelo/cli/factory.py, robottelo/host_helpers/cli_factory.py, tests/foreman/cli/test_operatingsystem.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11831
Closes #11860
This PR aims to refactor Operating System CLI tests. There were many OS tests which are combined into one end-to-end test.
- Removing  tests which are covered already either in e2e or in some other tests
=> [6.14.z] Component audit - Modify/Delete CLI OS tests

robottelo/cli/factory.py, robottelo/host_helpers/cli_factory.py, tests/foreman/cli/test_operatingsystem.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11831
Closes #11859
This PR aims to refactor Operating System CLI tests. There were many OS tests which are combined into one end-to-end test.
- Removing  tests which are covered already either in e2e or in some other tests
=> [6.13.z] Component audit - Modify/Delete CLI OS tests

robottelo/cli/factory.py, robottelo/host_helpers/cli_factory.py, tests/foreman/cli/test_operatingsystem.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11831
Closes #11861
This PR aims to refactor Operating System CLI tests. There were many OS tests which are combined into one end-to-end test.
- Removing  tests which are covered already either in e2e or in some other tests
=> [6.12.z] Component audit - Modify/Delete CLI OS tests

tests/foreman/api/test_rhc.py
Add `api/test.rhc.py` to test https://github.com/SatelliteQE/nailgun/pull/920.
The code for the test is mostly same as ui/test_rhc.py, which tests the same funcionality but with UI, this is for API with Nailgun.
=> Add api/test_rhc.py to test RHCloud Cloud Connector Nailgun support

tests/foreman/api/test_provisioningtemplate.py, tests/foreman/api/test_template_combination.py, tests/foreman/cli/test_provisioningtemplate.py, tests/foreman/ui/test_provisioningtemplate.py
1. Removing redundant tests which are covered already either in e2e or in some other tests.
2. Replaced target_sat with module_target_sat to keep it consistent.
3. Used cli/api property instead of importing cli/api entities from nailgun, and api/cli_factory with sat objects.
4. Parametrized test_positive_update_with_manager_role for Manager and Org admin roles.
5. Using build_pxe_default endpoint from nailgun instead of using nailgun client to call it.
6. Combine template_combination tests to single e2e test.
7. Combined test_positive_remove_os_by_id and test_positive_add_os_by_id into single test.
8. Removing test_negative_template_search_using_url as not required suggested by SD
=> [Component Audit] Provisioning templates component refactor

tests/foreman/api/test_provisioningtemplate.py, tests/foreman/api/test_template_combination.py, tests/foreman/cli/test_provisioningtemplate.py, tests/foreman/ui/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11833
1. Removing redundant tests which are covered already either in e2e or in some other tests.
2. Replaced target_sat with module_target_sat to keep it consistent.
3. Used cli/api property instead of importing cli/api entities from nailgun, and api/cli_factory with sat objects.
4. Parametrized test_positive_update_with_manager_role for Manager and Org admin roles.
5. Using build_pxe_default endpoint from nailgun instead of using nailgun client to call it.
6. Combine template_combination tests to single e2e test.
7. Combined test_positive_remove_os_by_id and test_positive_add_os_by_id into single test.
8. Removing test_negative_template_search_using_url as not required suggested by SD
=> [6.14.z] [Component Audit] Provisioning templates component refactor

tests/foreman/api/test_provisioningtemplate.py, tests/foreman/api/test_template_combination.py, tests/foreman/cli/test_provisioningtemplate.py, tests/foreman/ui/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11833
1. Removing redundant tests which are covered already either in e2e or in some other tests.
2. Replaced target_sat with module_target_sat to keep it consistent.
3. Used cli/api property instead of importing cli/api entities from nailgun, and api/cli_factory with sat objects.
4. Parametrized test_positive_update_with_manager_role for Manager and Org admin roles.
5. Using build_pxe_default endpoint from nailgun instead of using nailgun client to call it.
6. Combine template_combination tests to single e2e test.
7. Combined test_positive_remove_os_by_id and test_positive_add_os_by_id into single test.
8. Removing test_negative_template_search_using_url as not required suggested by SD
=> [6.13.z] [Component Audit] Provisioning templates component refactor

tests/foreman/api/test_rhc.py
Cherrrypick of https://github.com/SatelliteQE/robottelo/pull/11395, fixes https://github.com/SatelliteQE/robottelo/issues/11866
Add api/test.rhc.py to test https://github.com/SatelliteQE/nailgun/pull/920.
The code for the test is mostly same as ui/test_rhc.py, which tests the same funcionality but with UI, this is for API with Nailgun.
=> [6.12.z] Add api/test_rhc.py to test RHCloud Cloud Connector Nailgun support

tests/foreman/api/test_rhc.py
Cherrrypick of #11395, fixes #11865
Add api/test.rhc.py to test https://github.com/SatelliteQE/nailgun/pull/920.
The code for the test is mostly same as ui/test_rhc.py, which tests the same funcionality but with UI, this is for API with Nailgun.
=> [6.13.z] Add api/test_rhc.py to test RHCloud Cloud Connector Nailgun support

tests/foreman/api/test_rhc.py
Cherrrypick of #11395, fixes #11867
Add api/test.rhc.py to test https://github.com/SatelliteQE/nailgun/pull/920.
The code for the test is mostly same as ui/test_rhc.py, which tests the same funcionality but with UI, this is for API with Nailgun.
=> [6.14.z] Add api/test_rhc.py to test RHCloud Cloud Connector Nailgun support

tests/foreman/cli/test_oscap.py
- Opening the PR against 6.14.z and will be cherry pick in 6.13.z, as no scap package available in stream branch.
- The test module `test_postive_create_scap_policy_with_valid_name` creates policies by different names as per valid input types (ex- alfa, numberinc, latin1, cjk, utf-8, etc.)
- Due to this other test modules are getting impacted, especially when listing policies using the` hammer cli `command and reading the same name from the returned list.
-` ERROR - Skipping data chunk due to 'utf-8' codec can't decode byte 0x9b in position 0: invalid start byte`
- This small fix will deleted policies created with other valid type of input strings as part of teardown.
=> delete policies which are no longer needed

tests/foreman/cli/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11872
- Opening the PR against 6.14.z and will be cherry pick in 6.13.z, as no scap package available in stream branch.
- The test module `test_postive_create_scap_policy_with_valid_name` creates policies by different names as per valid input types (ex- alfa, numberinc, latin1, cjk, utf-8, etc.)
- Due to this other test modules are getting impacted, especially when listing policies using the` hammer cli `command and reading the same name from the returned list.
-` ERROR - Skipping data chunk due to 'utf-8' codec can't decode byte 0x9b in position 0: invalid start byte`
- This small fix will deleted policies created with other valid type of input strings as part of teardown.
=> [6.13.z] delete policies which are no longer needed

tests/foreman/api/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11880
Seems that [Seamless component Metadata across tools](https://github.com/SatelliteQE/robottelo/pull/10863) was not that _seamless_ as we did not indent one of the tests correctly. :laughing: 
This PR is fixing it.
Found during work on #11878
=> [6.14.z] Fix the indent of `test_positive_allow_reregistration_when_dmi_uuid_changed`

tests/foreman/api/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11880
Seems that [Seamless component Metadata across tools](https://github.com/SatelliteQE/robottelo/pull/10863) was not that _seamless_ as we did not indent one of the tests correctly. :laughing: 
This PR is fixing it.
Found during work on #11878
=> [6.13.z] Fix the indent of `test_positive_allow_reregistration_when_dmi_uuid_changed`

tests/foreman/api/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11880
Seems that [Seamless component Metadata across tools](https://github.com/SatelliteQE/robottelo/pull/10863) was not that _seamless_ as we did not indent one of the tests correctly. :laughing: 
This PR is fixing it.
Found during work on #11878
=> [6.12.z] Fix the indent of `test_positive_allow_reregistration_when_dmi_uuid_changed`

tests/foreman/api/test_contentview.py, tests/foreman/ui/test_contentview.py
Quick update to CV end-to-end scenarios - removing the flag from a UI test that is not going to pass, ever ( the old UI has been removed from Satellite, so until the CV component eval is finished, this test won't pass) and adding it to 2 recently added tests, that exercise a large majority of cases surrounding content views, and composite content views.
=> Remove e2e flag from failing UI test, and apply it to 2 api tests

tests/foreman/ui/test_audit.py
updates don't seem to be audited atm, 2222890 filed to track, skipping meanwhile
=> audit_log update event, skip on bz

robottelo/host_helpers/capsule_mixins.py, robottelo/hosts.py
* robottelo contributors keep using the deprecated method of registration in new tests that they are adding.
* as a consequence, the QE framework keeps using the `install_katello_ca` combined with `register_host` instead of using the Satellite's Global Registration feature.
* Add a `DeprecationWarning` to the `install_katello_ca` method. Every time it is called, a deprecation warning is generated.
* When teams add new tests and run the test session, they will be notified about the deprecation if they call `install_katello_ca` in their test/s.
* Once we start seeing the deprecation warnings, we will be more aware of the need to port (most of) the existing tests to Global Registration.
```
======================================================================================================= …
```
=> Deprecate install_katello_ca method in favor of the register method

tests/foreman/ui/test_audit.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11897
updates don't seem to be audited atm, 2222890 filed to track, skipping meanwhile
=> [6.14.z] audit_log update event, skip on bz

tests/foreman/api/test_contentview.py, tests/foreman/ui/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11886
Quick update to CV end-to-end scenarios - removing the flag from a UI test that is not going to pass, ever ( the old UI has been removed from Satellite, so until the CV component eval is finished, this test won't pass) and adding it to 2 recently added tests, that exercise a large majority of cases surrounding content views, and composite content views.
=> [6.14.z] Remove e2e flag from failing UI test, and apply it to 2 api tests

tests/foreman/ui/test_ansible.py
All the roles were being imported causing the locator to be missed for `select all` roles, hence only importing the selected role used in the test case.
**Fixes:**
test_positive_create_and_delete_variable
test_positive_create_variable_with_overrides
=> Ansible test fixes for selecting only the used role in the test case

tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11894
All the roles were being imported causing the locator to be missed for `select all` roles, hence only importing the selected role used in the test case.
**Fixes:**
test_positive_create_and_delete_variable
test_positive_create_variable_with_overrides
=> [6.13.z] Ansible test fixes for selecting only the used role in the test case

tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11894
All the roles were being imported causing the locator to be missed for `select all` roles, hence only importing the selected role used in the test case.
**Fixes:**
test_positive_create_and_delete_variable
test_positive_create_variable_with_overrides
=> [6.14.z] Ansible test fixes for selecting only the used role in the test case

.github/workflows/t2_reviews.yaml
Now T2 Reviewers ACK is only requested when changes in the framework / core part of Robottelo are being changed by PR, hence to automate this process we are introducing the T2 reviewers GHA to:
- Assign T2 Reviewers
- Assign Framework Changes label to the PR
=> GHA for T2 only reviews

.github/workflows/auto_cherry_pick.yml
As default `direction: first` is used, `peter-evans/find-comment` action finds the first PRT comment from Parent PR, and add it on the cherrypicked PR (example PR https://github.com/SatelliteQE/robottelo/pull/11847), instead we should use last comment for PRT as per previous implementation.
=> Fix find-the-parent-prt-comment in GHA

.github/workflows/pull_request.yml, setup.py
As discussed on slack, we are removing support for Python 3.9 from our frameworks.
=> Remove Python 3.9 support from robottelo

.github/workflows/pull_request.yml, setup.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11953
As discussed on slack, we are removing support for Python 3.9 from our frameworks.
=> [6.14.z] Remove Python 3.9 support from robottelo

.github/workflows/pull_request.yml, setup.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11953
As discussed on slack, we are removing support for Python 3.9 from our frameworks.
=> [6.12.z] Remove Python 3.9 support from robottelo

.github/workflows/pull_request.yml, setup.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11953
As discussed on slack, we are removing support for Python 3.9 from our frameworks.
=> [6.13.z] Remove Python 3.9 support from robottelo

.github/workflows/t2_reviews.yaml
Auto Assign T2 Reviewers to framework changes being applied to zBranches now.
=> T2 Reviewers Auto Assign for zBranches

pytest_fixtures/core/sat_cap_factory.py
Fixed:
```
failed on teardown with "Failed: fixture function has more than one 'yield':
@pytest.fixture(scope='session')
def session_capsule_configured(session_capsule_host, session_target_sat):
"""Configure the capsule instance with the satellite from settings.server.hostname"""
if session_capsule_host:
session_capsule_host.capsule_setup(sat_host=session_target_sat)
yield session_capsule_host
yield
/opt/app-root/src/robottelo/pytest_fixtures/core/sat_cap_factory.py:170"
```
=> Fix double yielding for capsule conf fixture

pytest_fixtures/core/sat_cap_factory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11977
Fixed:
```
failed on teardown with "Failed: fixture function has more than one 'yield':
@pytest.fixture(scope='session')
def session_capsule_configured(session_capsule_host, session_target_sat):
"""Configure the capsule instance with the satellite from settings.server.hostname"""
if session_capsule_host:
session_capsule_host.capsule_setup(sat_host=session_target_sat)
yield session_capsule_host
yield
/opt/app-root/src/robottelo/pytest_fixtures/core/sat_cap_factory.py:170"
```
=> [6.11.z] Fix double yielding for capsule conf fixture

tests/foreman/destructive/test_contenthost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12013
The test wants to consume custom repo by AK but sets no repo override on AK (repo is assigned but disabled)
Fixes:
```
result = rhel7_contenthost.execute(f'yum -y install {FAKE_1_CUSTOM_PACKAGE}')
>       assert result.status == 0
E       assert 1 == 0
E        +  where 1 = stdout:\nLoaded plugins: ovl, product-id, search-disabled-repos, subscription-manager\nNo package walrus-0.71-1.noarch available.\n\nstderr:\nError: Nothing to do\n\nstatus: 1.status
tests/foreman/destructive/test_contenthost.py:66: AssertionError
```
=> [6.14.z] Fix test_content_access_after_stopped_foreman

.github/CODEOWNERS
=> Tier2 Reviewers Assignment

tests/foreman/data/hammer_commands.json
```
Failed: hammer job-template create
Added options:
* ansible-callback-enabled
hammer job-template update
Added options:
* ansible-callback-enabled
hammer lifecycle-environment paths
Added options:
* content-source-id
hammer simple-content-access enable
Added options:
* auto-create-overrides
```
First two coming from   https://bugzilla.redhat.com/show_bug.cgi?id=2211954
=> [6.13.z] new hammer subcommands

tests/foreman/destructive/test_packages.py
Automating customer case for `satellite-maintain packages check-update` when system is already up to date. We have to use yum here to update, because you can't use `satellite-maintain packages update --assumeyes` to update all packages.
=> Adding test for check-update when system is up to date

tests/foreman/ui/test_webhook.py
Fixes failures when there is more than one webhook.
PRT will probably fail due to unrelated vertical nav error.
=> Don't just take random webhook, search by name

tests/foreman/destructive/test_packages.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12009
Automating customer case for `satellite-maintain packages check-update` when system is already up to date. We have to use yum here to update, because you can't use `satellite-maintain packages update --assumeyes` to update all packages.
=> [6.13.z] Adding test for check-update when system is up to date

tests/foreman/cli/test_hammer.py, tests/foreman/data/hammer_commands.json
new sub-command has been added within BZ#2170917, also adjusted  test_positive_check_debug_log_level for different stdout. Stream has several other new subcommands not addressed here, aiming mainly to fix 6.14
=> new hammer command and log level fix

tests/foreman/cli/test_hammer.py, tests/foreman/data/hammer_commands.json
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11900
new sub-command has been added within BZ#2170917, also adjusted  test_positive_check_debug_log_level for different stdout. Stream has several other new subcommands not addressed here, aiming mainly to fix 6.14
=> [6.14.z] new hammer command and log level fix

pytest_fixtures/core/contenthosts.py, pytest_fixtures/core/sat_cap_factory.py, tests/foreman/destructive/test_clone.py
Update sat_ready_rhel fixture to work with osp and without params.
This is to fix failing satellite-clone tests.
=> [6.13.z] Update sat_ready_rhel fixture to work with osp

pytest_fixtures/core/contenthosts.py, pytest_fixtures/core/sat_cap_factory.py, tests/foreman/destructive/test_clone.py
Update sat_ready_rhel fixture to work with osp and without params.
This is to fix failing satellite-clone tests.
Cherrypick of #12048 to `6.12.z`
=> [6.12.z] Update sat_ready_rhel fixture to work with osp

tests/foreman/api/test_repositories.py, tests/foreman/api/test_subscription.py
This test is a part of the Repository Rewrite effort [ SAT-13253 ]
The purpose of this test to make sure the metadata for a repository is the same when synced to multiple organizations
Steps:
Create orgs with same repo, sync them, and check if the metadata information is matching all of them
=> Test for multiple orgs with the same repo[Repository Rewrite]

tests/foreman/api/test_provisioning.py, tests/foreman/api/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11940
QETestCoverage for [BZ 2168967](https://bugzilla.redhat.com/show_bug.cgi?id=2168967) / [BZ 2175005](https://bugzilla.redhat.com/show_bug.cgi?id=2175005) and [BZ 1955861](https://bugzilla.redhat.com/show_bug.cgi?id=1955861) / [BZ 1784012](https://bugzilla.redhat.com/show_bug.cgi?id=1784012)
Dependant PR - https://github.com/SatelliteQE/nailgun/pull/966
=> [6.13.z] Add automation for BZ 2175005, BZ 1955861/1784012

tests/foreman/destructive/test_packages.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12009
Automating customer case for `satellite-maintain packages check-update` when system is already up to date. We have to use yum here to update, because you can't use `satellite-maintain packages update --assumeyes` to update all packages.
=> [6.14.z] Adding test for check-update when system is up to date

robottelo/host_helpers/contenthost_mixins.py, robottelo/utils/ohsnap.py
`download_repofile()` needlessly shortens 4 digit satellite version to 3 digits
=> Fix 4-digit logic in download_repofile and ohsnap_repo_url

tests/foreman/maintain/test_health.py
=> Fix failing foreman/maintain/health tests

robottelo/host_helpers/contenthost_mixins.py, robottelo/utils/ohsnap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12057
`ohsnap_repo_url()` and `download_repofile()` needlessly shortens 4 digit satellite version to 3 digits
=> [6.14.z] Fix 4-digit logic in download_repofile and ohsnap_repo_url

tests/foreman/maintain/test_health.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11676
=> [6.13.z] Fix failing foreman/maintain/health tests

tests/foreman/maintain/test_health.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11676
=> [6.12.z] Fix failing foreman/maintain/health tests

tests/foreman/maintain/test_health.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11676
=> [6.11.z] Fix failing foreman/maintain/health tests

tests/foreman/maintain/test_health.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11676
=> [6.14.z] Fix failing foreman/maintain/health tests

tests/foreman/cli/test_repository.py
These two test cases did not pass in our PRT run for #11790 and are blocking the automatic merge.
```python
>       assert f"Successfully uploaded file '{RPM_TO_UPLOAD}'" in result[0]['message']
E       assert "Successfully uploaded file 'which-2.19-6.el6.x86_64.rpm'" in 'Successfully uploaded file which-2.19-6.el6.x86_64.rpm'
```
```python
>       assert f"Successfully uploaded file '{OS_TEMPLATE_DATA_FILE}'" in result[0]['message']
E       assert "Successfully uploaded file 'os_template.txt'" in 'Successfully uploaded file os_template.txt'
```
=> Fix TestRepository test cases

tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12088
These two test cases did not pass in our PRT run for #11790 and are blocking the automatic merge.
```python
>       assert f"Successfully uploaded file '{RPM_TO_UPLOAD}'" in result[0]['message']
E       assert "Successfully uploaded file 'which-2.19-6.el6.x86_64.rpm'" in 'Successfully uploaded file which-2.19-6.el6.x86_64.rpm'
```
```python
>       assert f"Successfully uploaded file '{OS_TEMPLATE_DATA_FILE}'" in result[0]['message']
E       assert "Successfully uploaded file 'os_template.txt'" in 'Successfully uploaded file os_template.txt'
```
=> [6.14.z] Fix TestRepository test cases

tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12088
These two test cases did not pass in our PRT run for #11790 and are blocking the automatic merge.
```python
>       assert f"Successfully uploaded file '{RPM_TO_UPLOAD}'" in result[0]['message']
E       assert "Successfully uploaded file 'which-2.19-6.el6.x86_64.rpm'" in 'Successfully uploaded file which-2.19-6.el6.x86_64.rpm'
```
```python
>       assert f"Successfully uploaded file '{OS_TEMPLATE_DATA_FILE}'" in result[0]['message']
E       assert "Successfully uploaded file 'os_template.txt'" in 'Successfully uploaded file os_template.txt'
```
=> [6.12.z] Fix TestRepository test cases

tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12088
These two test cases did not pass in our PRT run for #11790 and are blocking the automatic merge.
```python
>       assert f"Successfully uploaded file '{RPM_TO_UPLOAD}'" in result[0]['message']
E       assert "Successfully uploaded file 'which-2.19-6.el6.x86_64.rpm'" in 'Successfully uploaded file which-2.19-6.el6.x86_64.rpm'
```
```python
>       assert f"Successfully uploaded file '{OS_TEMPLATE_DATA_FILE}'" in result[0]['message']
E       assert "Successfully uploaded file 'os_template.txt'" in 'Successfully uploaded file os_template.txt'
```
=> [6.13.z] Fix TestRepository test cases

robottelo/host_helpers/contenthost_mixins.py, robottelo/utils/ohsnap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12057
`ohsnap_repo_url()` and `download_repofile()` needlessly shortens 4 digit satellite version to 3 digits
=> [6.12.z] Fix 4-digit logic in download_repofile and ohsnap_repo_url

robottelo/host_helpers/contenthost_mixins.py, robottelo/utils/ohsnap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12057
`ohsnap_repo_url()` and `download_repofile()` needlessly shortens 4 digit satellite version to 3 digits
=> [6.13.z] Fix 4-digit logic in download_repofile and ohsnap_repo_url

tests/foreman/cli/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12106
Test fixes for the OSCAP component.
=> [6.14.z] Test fixes for correctly fetching scap_profile_ids

tests/foreman/cli/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12106
Test fixes for the OSCAP component.
=> [6.13.z] Test fixes for correctly fetching scap_profile_ids

tests/foreman/cli/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12106
Test fixes for the OSCAP component.
=> [6.12.z] Test fixes for correctly fetching scap_profile_ids

tests/foreman/cli/test_contentcredentials.py, tests/foreman/cli/test_repository.py, tests/foreman/ui/test_contentcredentials.py
_CLI and UI ContentCredentials updates for failures in automation, API is already passing 100%_
**Update:** These tests still fail and will need some further investigation
- [UI] _test_positive_search_scoped_:
NoSuchElementException: Message: Could not find an element Locator
- [CLI] _test_positive_update_key_for_product_with_repo_  ,  _test_positive_update_key_for_product_with_repos_
KeyError: intermittently, the updated gpgkey info being returned is empty
They all test deleting a GPG key in use with a product/repository, this is blocked since 6.13.0 and they all fail for it:
[RHBZ: 2052904](https://bugzilla.redhat.com/show_bug.cgi?id=2052904)
**UI and CLI**
- test_positive_delete_key_for_empty_product
- test_positive_delete_key_for_product_with_repo
- …
=> Update test Contentcredentials for 6.13.z 6.14.z

tests/foreman/api/test_notifications.py
New test module for API notifications and test for RFE "Generate Alerts if a tasks are in running/Paused  state for more than a certain days."
BZ: https://bugzilla.redhat.com/1950836
=> Notifications: test for new RFE for long-running tasks

tests/foreman/api/test_notifications.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12018
New test module for API notifications and test for RFE "Generate Alerts if a tasks are in running/Paused  state for more than a certain days."
BZ: https://bugzilla.redhat.com/1950836
=> [6.14.z] Notifications: test for new RFE for long-running tasks

tests/foreman/ui/test_operatingsystem.py
This PR aims to refactor Operating System UI tests. There were some OS tests which are combined into one end-to-end test.
Removing tests which are covered already in e2e
=> Component audit - Modify/Delete UI OS tests

tests/foreman/ui/test_operatingsystem.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12046
This PR aims to refactor Operating System UI tests. There were some OS tests which are combined into one end-to-end test.
Removing tests which are covered already in e2e
=> [6.13.z] Component audit - Modify/Delete UI OS tests

docs/conf.py, robottelo/config/__init__.py
```
$ time make docs
"Copying broker_config.yaml to avoid warnings"
cp: cannot stat './broker_settings.yaml': No such file or directory
make[1]: Entering directory '/home/ogajduse/repos/robottelo/docs'
sphinx-build -W -b html -d _build/doctrees   . _build/html
Running Sphinx v7.1.2
making output directory... done
... output omitted ...
writing output... [100%] reviewing_PRs
generating indices... genindex py-modindex done
highlighting module code... [100%] robottelo.utils.version
writing additional pages... search done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.
The HTML pages are in _build/html.
Build finished. The HTML pages are in _build/html.
make[1]: Leaving directory '/home/ogajduse/repos/robottelo/docs'
real    0m23.055s
user …
```
=> Improve doc build speed ~10 times

docs/conf.py, robottelo/config/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12131
```
$ time make docs
"Copying broker_config.yaml to avoid warnings"
cp: cannot stat './broker_settings.yaml': No such file or directory
make[1]: Entering directory '/home/ogajduse/repos/robottelo/docs'
sphinx-build -W -b html -d _build/doctrees   . _build/html
Running Sphinx v7.1.2
making output directory... done
... output omitted ...
writing output... [100%] reviewing_PRs
generating indices... genindex py-modindex done
highlighting module code... [100%] robottelo.utils.version
writing additional pages... search done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.
The HTML pages are in _build/html.
Build finished. The HTML pages are in _build/html.
make[1]: Leaving …
```
=> [6.14.z] Improve doc build speed ~10 times

docs/conf.py, robottelo/config/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12131
```
$ time make docs
"Copying broker_config.yaml to avoid warnings"
cp: cannot stat './broker_settings.yaml': No such file or directory
make[1]: Entering directory '/home/ogajduse/repos/robottelo/docs'
sphinx-build -W -b html -d _build/doctrees   . _build/html
Running Sphinx v7.1.2
making output directory... done
... output omitted ...
writing output... [100%] reviewing_PRs
generating indices... genindex py-modindex done
highlighting module code... [100%] robottelo.utils.version
writing additional pages... search done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.
The HTML pages are in _build/html.
Build finished. The HTML pages are in _build/html.
make[1]: Leaving …
```
=> [6.12.z] Improve doc build speed ~10 times

docs/conf.py, robottelo/config/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12131
```
$ time make docs
"Copying broker_config.yaml to avoid warnings"
cp: cannot stat './broker_settings.yaml': No such file or directory
make[1]: Entering directory '/home/ogajduse/repos/robottelo/docs'
sphinx-build -W -b html -d _build/doctrees   . _build/html
Running Sphinx v7.1.2
making output directory... done
... output omitted ...
writing output... [100%] reviewing_PRs
generating indices... genindex py-modindex done
highlighting module code... [100%] robottelo.utils.version
writing additional pages... search done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.
The HTML pages are in _build/html.
Build finished. The HTML pages are in _build/html.
make[1]: Leaving …
```
=> [6.11.z] Improve doc build speed ~10 times

robottelo/cli/content_export.py, tests/foreman/cli/test_satellitesync.py
ISS export of docker-type repository has been backported to 6.12.5 according to [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2227854).
Here I just cherry-pick the related tests to 6.12.z branch.
=> [6.12.z] Add coverage for docker-type repository exports

pytest_fixtures/component/katello_certs_check.py, robottelo/constants/__init__.py, tests/foreman/destructive/test_katello_certs_check.py, tests/foreman/sys/test_katello_certs_check.py
Update fixture implementation to OSP in order to get correct flavor for the test `satqe-ssd.standard.std` (instead of `satqe-ssd.memory.xs`)
Marking the test that uses the fixture as non-destructive (just installs satellite on `sat_ready_rhel`)
(execution time dropped from 43min to 33min)
=> Change certs fixture to use sat_ready_rhel fixture

pytest_fixtures/component/katello_certs_check.py, robottelo/constants/__init__.py, tests/foreman/destructive/test_katello_certs_check.py, tests/foreman/sys/test_katello_certs_check.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12077
Update fixture implementation to OSP in order to get correct flavor for the test `satqe-ssd.standard.std` (instead of `satqe-ssd.memory.xs`)
Marking the test that uses the fixture as non-destructive (just installs satellite on `sat_ready_rhel`)
(execution time dropped from 43min to 33min)
=> [6.14.z] Change certs fixture to use sat_ready_rhel fixture

pytest_fixtures/component/katello_certs_check.py, robottelo/constants/__init__.py, tests/foreman/destructive/test_katello_certs_check.py, tests/foreman/sys/test_katello_certs_check.py
* Move test_positive_install_sat_with_katello_certs to non-destructive
* Change certs fixture to use sat_ready_rhel fixture
(cherry picked from commit 412201f14fd9cbe3f3c7b671595fe45f25aa1cd2)
Cherrypicks #12077
Fixes #12150
=> [6.13.z] Change certs fixture to use sat_ready_rhel fixture (#12077)

pytest_fixtures/component/katello_certs_check.py, robottelo/constants/__init__.py, tests/foreman/destructive/test_katello_certs_check.py, tests/foreman/sys/test_katello_certs_check.py
* Move test_positive_install_sat_with_katello_certs to non-destructive
* Change certs fixture to use sat_ready_rhel fixture
(cherry picked from commit 412201f14fd9cbe3f3c7b671595fe45f25aa1cd2)
Cherrypicks #12077
Fixes #12151
=> [6.12.z] Change certs fixture to use sat_ready_rhel fixture (#12077)

tests/foreman/ui/test_rhc.py
Reverts SatelliteQE/robottelo#12157
Reverting this change back as we need to have the master branch in the same state as the other `.z` branches before we merge #12162 and create cherry-pick PRs.
=> Revert "Mark test_positive_configure_cloud_connector destructive"

tests/foreman/cli/test_oscap_tailoringfiles.py
- test module `test_positive_create` create tailoring files with all possible valid input type (ex- alfa, numberinc, latin1, cjk, utf-8, etc.)
- Due to this naming type other tests (ex - `test_positive_list_tailoring_file`) getting affected.
- Error log from robottelo_gw1.log file > `broker - ERROR - Skipping data chunk due to 'utf-8' codec can't decode bytes in position 1022-1023: unexpected end of data`
- CI test module failure > `AssertionError: assert '萭ﬃ#x10726#x177E5#x1863A' in []`
- `This small fix will deleted created tailoring files with other valid type of input strings`
- **Note:** Test module for 6.12.5 was failing due to this problem, this is intermittent test failure so adding 6.13 and 6.14 label into it.
=> delete tailoring files which are no longer needed

tests/foreman/cli/test_oscap_tailoringfiles.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12156
- test module `test_positive_create` create tailoring files with all possible valid input type (ex- alfa, numberinc, latin1, cjk, utf-8, etc.)
- Due to this naming type other tests (ex - `test_positive_list_tailoring_file`) getting affected.
- Error log from robottelo_gw1.log file > `broker - ERROR - Skipping data chunk due to 'utf-8' codec can't decode bytes in position 1022-1023: unexpected end of data`
- CI test module failure > `AssertionError: assert '萭ﬃ#x10726#x177E5#x1863A' in []`
- `This small fix will deleted created tailoring files with other valid type of input strings`
- **Note:** Test module for 6.12.5 was failing due to this problem, this is intermittent test failure so adding 6.13 and 6.14 label into it.
=> [6.11.z] delete tailoring files which are no longer needed

tests/foreman/cli/test_oscap_tailoringfiles.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12156
- test module `test_positive_create` create tailoring files with all possible valid input type (ex- alfa, numberinc, latin1, cjk, utf-8, etc.)
- Due to this naming type other tests (ex - `test_positive_list_tailoring_file`) getting affected.
- Error log from robottelo_gw1.log file > `broker - ERROR - Skipping data chunk due to 'utf-8' codec can't decode bytes in position 1022-1023: unexpected end of data`
- CI test module failure > `AssertionError: assert '萭ﬃ#x10726#x177E5#x1863A' in []`
- `This small fix will deleted created tailoring files with other valid type of input strings`
- **Note:** Test module for 6.12.5 was failing due to this problem, this is intermittent test failure so adding 6.13 and 6.14 label into it.
=> [6.13.z] delete tailoring files which are no longer needed

tests/foreman/cli/test_oscap_tailoringfiles.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12156
- test module `test_positive_create` create tailoring files with all possible valid input type (ex- alfa, numberinc, latin1, cjk, utf-8, etc.)
- Due to this naming type other tests (ex - `test_positive_list_tailoring_file`) getting affected.
- Error log from robottelo_gw1.log file > `broker - ERROR - Skipping data chunk due to 'utf-8' codec can't decode bytes in position 1022-1023: unexpected end of data`
- CI test module failure > `AssertionError: assert '萭ﬃ#x10726#x177E5#x1863A' in []`
- `This small fix will deleted created tailoring files with other valid type of input strings`
- **Note:** Test module for 6.12.5 was failing due to this problem, this is intermittent test failure so adding 6.13 and 6.14 label into it.
=> [6.14.z] delete tailoring files which are no longer needed

robottelo/constants/__init__.py, tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12098
$SSIA
=> [6.13.z] Update scap tests to use deploy_flavor and Global Registration

tests/upgrades/test_virtwho.py
remove delete org and create a new location for virt-who upgrade scenarios
Cases : PASS
```robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade 
platform linux -- Python 3.10.9, pytest-7.4.0, pluggy-1.0.0
rootdir: /home/virtwho/repository/robottelo
plugins: cov-4.1.0, ibutsu-2.2.4, xdist-3.3.1, mock-3.11.1, services-2.2.1, reportportal-5.2.0
collected 2 items / 1 …
```
=> remove delete org and create a new location for virt-who upgrade scenarios

tests/upgrades/test_virtwho.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12092
remove delete org and create a new location for virt-who upgrade scenarios
Cases : PASS
```robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade 
platform linux -- Python 3.10.9, pytest-7.4.0, pluggy-1.0.0
rootdir: /home/virtwho/repository/robottelo
plugins: cov-4.1.0, ibutsu-2.2.4, xdist-3.3.1, …
```
=> [6.14.z] remove delete org and create a new location for virt-who upgrade scenarios

tests/foreman/api/test_rhc.py
Using `target_sat` fixture for the test as `module_target_sat` fixture can't be used with `destructive` marker.
=> Use target_sat for test_positive_configure_cloud_connector api test

tests/foreman/api/test_rhc.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12189
Using `target_sat` fixture for the test as `module_target_sat` fixture can't be used with `destructive` marker.
=> [6.12.z] Use target_sat for test_positive_configure_cloud_connector api test

tests/foreman/api/test_rhc.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12189
Using `target_sat` fixture for the test as `module_target_sat` fixture can't be used with `destructive` marker.
=> [6.13.z] Use target_sat for test_positive_configure_cloud_connector api test

tests/upgrades/test_virtwho.py
Fixes #12188 
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade
platform linux -- Python 3.10.9, pytest-7.4.0, pluggy-1.0.0
Mandatory Requirements Mismatch: dynaconf[vault]==3.2.0 PyYAML==6.0.1 wrapanapi==3.5.18 productmd==1.36 pytest-reportportal==5.2.1 cryptography==41.0.3 broker[docker]==0.3.3 deepdiff==6.3.1 pyotp==2.9.0
Optional Requirements Mismatch: flake8==6.1.0 sphinx==7.1.2
To update mismatched requirements, run the pytest command with '--upgrade-required-reqs' OR '--upgrade-all-reqs' option. …
```
=> [6.12.z] - remove delete org and create a new location for virt-who upgrade scenarios #12188

tests/foreman/ui/test_templatesync.py
adjusting the assertion accordingly
=> password is now redacted in the template output

tests/foreman/ui/test_templatesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12195
adjusting the assertion accordingly
=> [6.14.z] password is now redacted in the template output

tests/foreman/ui/test_settings.py
- Pagination dictionary returns different keys
- Updating code as per keys and values received in "page_content"
=> fix for per_page key issue

tests/foreman/ui/test_settings.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12212
- Pagination dictionary returns different keys
- Updating code as per keys and values received in "page_content"
=> [6.13.z] fix for per_page key issue

tests/foreman/ui/test_settings.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12212
- Pagination dictionary returns different keys
- Updating code as per keys and values received in "page_content"
=> [6.14.z] fix for per_page key issue

tests/foreman/ui/test_settings.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12212
- Pagination dictionary returns different keys
- Updating code as per keys and values received in "page_content"
=> [6.12.z] fix for per_page key issue

robottelo/host_helpers/contenthost_mixins.py, robottelo/utils/ohsnap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12057
`ohsnap_repo_url()` and `download_repofile()` needlessly shortens 4 digit satellite version to 3 digits
=> [6.11.z] Fix 4-digit logic in download_repofile and ohsnap_repo_url

tests/foreman/destructive/test_clone.py
All of the satellite-clone tests are failing on stream, because this line resolves to `6.15.0`. Instead we want it to resolve to `stream`, so I opted to use `settings.satellite.version.release`. Only need this for stream, since it's a non-issue on our other branches.
=> Fix clone tests to use the right sat_version

pytest_fixtures/core/contenthosts.py, pytest_fixtures/core/sat_cap_factory.py
(cherry picked from commit c4674c38974e22c11933407cc3d1ff1b240c0574)
Cherrypicks #12048 to `6.11.z`
=> [6.11.z] Update sat_ready_rhel fixture to work with osp

tests/foreman/maintain/test_advanced.py, tests/foreman/maintain/test_backup_restore.py, tests/foreman/maintain/test_health.py, tests/foreman/maintain/test_packages.py, tests/foreman/maintain/test_service.py
Nothing crazy going on in this initial update to our foreman-maintain test suite. Tests are either being combined with another test, updated with markers / more accurate docstrings, or completely removed as identified during the component evaluation.
=> Modify and delete foreman-maintain tests

tests/foreman/maintain/test_advanced.py, tests/foreman/maintain/test_backup_restore.py, tests/foreman/maintain/test_health.py, tests/foreman/maintain/test_packages.py, tests/foreman/maintain/test_service.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12209
Nothing crazy going on in this initial update to our foreman-maintain test suite. Tests are either being combined with another test, updated with markers / more accurate docstrings, or completely removed as identified during the component evaluation.
=> [6.14.z] Modify and delete foreman-maintain tests

tests/foreman/cli/test_capsule.py
`make_proxy` uses the `CLIFactoryError` from `cli_factory` not the error from `cli.factory`. I haven't investigated if this is a problem in other areas, but we should reconsider having two of the same error.
=> Switch CLIFactoryError import for cli/test_capsule.py

tests/foreman/cli/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12239
`make_proxy` uses the `CLIFactoryError` from `cli_factory` not the error from `cli.factory`. I haven't investigated if this is a problem in other areas, but we should reconsider having two of the same error.
=> [6.14.z] Switch CLIFactoryError import for cli/test_capsule.py

tests/foreman/cli/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12239
`make_proxy` uses the `CLIFactoryError` from `cli_factory` not the error from `cli.factory`. I haven't investigated if this is a problem in other areas, but we should reconsider having two of the same error.
=> [6.13.z] Switch CLIFactoryError import for cli/test_capsule.py

tests/foreman/cli/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12239
`make_proxy` uses the `CLIFactoryError` from `cli_factory` not the error from `cli.factory`. I haven't investigated if this is a problem in other areas, but we should reconsider having two of the same error.
=> [6.12.z] Switch CLIFactoryError import for cli/test_capsule.py

tests/foreman/cli/test_capsule.py
`request.node.name` returns the test name like `test_positive_update_name`. We can just search for `html` in `valid_data` instead.
=> Fix conditional in capsule update_name test

tests/foreman/cli/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12244
`request.node.name` returns the test name like `test_positive_update_name`. We can just search for `html` in `valid_data` instead.
=> [6.14.z] Fix conditional in capsule update_name test

tests/foreman/cli/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12244
`request.node.name` returns the test name like `test_positive_update_name`. We can just search for `html` in `valid_data` instead.
=> [6.12.z] Fix conditional in capsule update_name test

pytest_fixtures/component/katello_certs_check.py, tests/foreman/destructive/test_katello_certs_check.py, tests/foreman/sys/test_katello_certs_check.py
* Move test_positive_install_sat_with_katello_certs to non-destructive
* Change certs fixture to use sat_ready_rhel fixture
(cherry picked from commit 412201f14fd9cbe3f3c7b671595fe45f25aa1cd2)
Cherrypicks #12077 
Fixes #12149
=> [6.11.z] Change certs fixture to use sat_ready_rhel fixture (#12077)

tests/foreman/api/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12246
Updated Cert and Key file locations for 6.13 and 6.14
=> [6.14.z] Fixed failing test for recreating repositories 

tests/foreman/api/test_repositories.py
Fixing failed cherry-pick of test into 6.12.z
Parent PR: https://github.com/SatelliteQE/robottelo/pull/10428
=> [6.12.5] Cherry-pick for uploading expired manifest

tests/foreman/api/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12246
Updated Cert and Key file locations for 6.13 and 6.14
=> [6.13.z] Fixed failing test for recreating repositories 

pytest_fixtures/component/repository.py, pytest_fixtures/component/rh_cloud.py, robottelo/cli/factory.py, robottelo/hosts.py, tests/foreman/ui/test_activationkey.py, tests/foreman/ui/test_dashboard.py, tests/foreman/ui/test_errata.py, tests/foreman/ui/test_hostcollection.py, tests/foreman/ui/test_organization.py, tests/foreman/ui/test_package.py, tests/foreman/ui/test_reporttemplates.py, tests/foreman/ui/test_repository.py, tests/foreman/ui/test_rhc.py, tests/foreman/ui/test_subscription.py, tests/foreman/ui/test_sync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10394
This PR will convert all UI tests that use manifests to obtain those manifests via manifester. I will aim to push one commit for each module that I'm converting. The PR will remain in draft state until I have converted all affected modules. The list of UI modules that I will be converting is as follows:
```
test_repository.py
test_activationkey.py
test_contenthost.py
test_dashboard.py
test_errata.py
test_hostcollection.py
test_host.py
test_organization.py
test_package.py
test_reporttemplates.py
test_rhcloud_insights.py
test_rhcloud_inventory.py
test_rhc.py
test_subscription.py
test_sync.py
```
=> [6.14.z] Convert UI manifest tests to manifester

tests/foreman/ui/test_audit.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12280
The blocking bugs were closed as wotfix long time ago, interestingly the test was still skipped in automation. This PR removes it
=> [6.14.z] removed wotfix-skipped test

tests/foreman/ui/test_audit.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12280
The blocking bugs were closed as wotfix long time ago, interestingly the test was still skipped in automation. This PR removes it
=> [6.13.z] removed wotfix-skipped test

.gitignore, pytest_fixtures/core/broker.py, pytest_fixtures/core/sat_cap_factory.py, pytest_fixtures/core/upgrade.py, pytest_fixtures/core/xdist.py, robottelo/host_helpers/contenthost_mixins.py, robottelo/hosts.py, tests/foreman/api/test_provisioning.py, tests/foreman/api/test_provisioning_puppet.py, tests/foreman/destructive/test_leapp_satellite.py, tests/upgrades/test_client.py, tests/upgrades/test_errata.py, tests/upgrades/test_repository.py, tests/upgrades/test_subscription.py
This PR brings new functionality, improvements and fixes:
* Fixes #12115 - Introduce `list_cached_properties`, `get_cached_properties`, `clean_cached_properties` to allow listing names, getting values and cleaning of cached properties of a ContentHost object
* Fixes #12142
* Ignore vcd_sdk.log that comes from pyvcloud (dependency of wrapanapi)
* Introduce `get_host_by_hostname` and `get_hosts_from_inventory` to make host reconstruction shorter, clearer and less repetetive
* Add RHEL 8+ support to `REPOSET`
* Wrap `wait_for` `connect in a ContentHost `wait_for_connection` method
* Use /etc/os-release to get system identification data - introduced new _os_release cached property
* Raise `NotImplementedError` on an attempt to `power_control` a container host type
* run unregister only if the …
=> Introduce and enhance robottelo.hosts features

tests/foreman/ui/test_jobtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12283
BZ#1705866 got removed with wontfix, there doesn't seem to be a way to amend the test to make it relevant, so dropping
=> [6.12.z] removed skipped wontfix jt

tests/foreman/ui/test_jobtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12283
BZ#1705866 got removed with wontfix, there doesn't seem to be a way to amend the test to make it relevant, so dropping
=> [6.13.z] removed skipped wontfix jt

robottelo/cli/factory.py, robottelo/host_helpers/cli_factory.py, tests/foreman/longrun/test_oscap.py
Upgrade test was failing with Error
`Could not promote the content view: Cannot promote environment out of sequence`
with this fix we bypass cvv promote if already promoted to lce
=> bypass cvv promote to lce if already promoted

robottelo/cli/factory.py, robottelo/host_helpers/cli_factory.py, tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12309
Upgrade test was failing with Error
`Could not promote the content view: Cannot promote environment out of sequence`
with this fix we bypass cvv promote if already promoted to lce
=> [6.14.z] bypass cvv promote to lce if already promoted

robottelo/cli/factory.py, robottelo/host_helpers/cli_factory.py, tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12309
Upgrade test was failing with Error
`Could not promote the content view: Cannot promote environment out of sequence`
with this fix we bypass cvv promote if already promoted to lce
=> [6.12.z] bypass cvv promote to lce if already promoted

robottelo/cli/factory.py, robottelo/host_helpers/cli_factory.py, tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12309
Upgrade test was failing with Error
`Could not promote the content view: Cannot promote environment out of sequence`
with this fix we bypass cvv promote if already promoted to lce
=> [6.13.z] bypass cvv promote to lce if already promoted

tests/foreman/maintain/test_service.py
During the component evaluation SD recommended adding a check for each service being listed to this test as they have found it sometimes will report `[OK]` but miss some services.
=> Add service list check

pytest_fixtures/component/provision_libvirt.py, robottelo/constants/__init__.py, tests/foreman/api/test_computeresource_libvirt.py, tests/foreman/api/test_host.py, tests/foreman/ui/test_organization.py
1. Add Libvirt CR API e2e test
2. Remove tests which are being covered in e2e test.
3. Merge test_positive_create_with_locs and test_positive_create_with_orgs into single test.
4. Use module_org, module_location fixtures and LIBVIRT_URL constant instead of setup fixture.
5. Remove unnecessary use of on_premises_provisioning marker from tests.
=> Add Libvirt CR API e2e test and some refactor

pytest_fixtures/component/provision_libvirt.py, robottelo/constants/__init__.py, tests/foreman/api/test_computeresource_libvirt.py, tests/foreman/api/test_host.py, tests/foreman/ui/test_organization.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12208
1. Add Libvirt CR API e2e test
2. Remove tests which are being covered in e2e test.
3. Merge test_positive_create_with_locs and test_positive_create_with_orgs into single test.
4. Use module_org, module_location fixtures and LIBVIRT_URL constant instead of setup fixture.
5. Remove unnecessary use of on_premises_provisioning marker from tests.
=> [6.14.z] Add Libvirt CR API e2e test and some refactor

pytest_fixtures/component/provision_libvirt.py, robottelo/constants/__init__.py, tests/foreman/api/test_computeresource_libvirt.py, tests/foreman/api/test_host.py, tests/foreman/ui/test_organization.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12208
1. Add Libvirt CR API e2e test
2. Remove tests which are being covered in e2e test.
3. Merge test_positive_create_with_locs and test_positive_create_with_orgs into single test.
4. Use module_org, module_location fixtures and LIBVIRT_URL constant instead of setup fixture.
5. Remove unnecessary use of on_premises_provisioning marker from tests.
=> [6.13.z] Add Libvirt CR API e2e test and some refactor

pytest_fixtures/component/provision_libvirt.py, robottelo/constants/__init__.py, tests/foreman/api/test_computeresource_libvirt.py, tests/foreman/api/test_host.py, tests/foreman/ui/test_organization.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12208
1. Add Libvirt CR API e2e test
2. Remove tests which are being covered in e2e test.
3. Merge test_positive_create_with_locs and test_positive_create_with_orgs into single test.
4. Use module_org, module_location fixtures and LIBVIRT_URL constant instead of setup fixture.
5. Remove unnecessary use of on_premises_provisioning marker from tests.
=> [6.12.z] Add Libvirt CR API e2e test and some refactor

pytest_fixtures/component/rh_cloud.py, pytest_fixtures/core/sat_cap_factory.py, robottelo/constants/__init__.py, robottelo/hosts.py, tests/foreman/api/test_rhcloud_inventory.py, tests/foreman/cli/test_rhcloud_insights.py, tests/foreman/cli/test_rhcloud_inventory.py, tests/foreman/ui/test_rhc.py, tests/foreman/ui/test_rhcloud_insights.py, tests/foreman/ui/test_rhcloud_inventory.py
This PR aims to refactor tests present in `tests/foreman/ui/test_rhcloud_insights.py`.
It removes `test_delete_host_having_insights_recommendation`, `test_rh_cloud_insights_clean_statuses` and `test_insights_tab_on_host_details_page` as they are covered in existing tests and updates and parameterizes others for rhel 7, 8 and 9. 
It also removes `rhcloud_sat_host` which is unnecessary.
Depends on https://github.com/SatelliteQE/airgun/pull/940
=> Refactor tests/foreman/ui/test_rhcloud_insights.py

robottelo/host_helpers/__init__.py, robottelo/host_helpers/satellite_mixins.py, tests/foreman/ui/test_computeresource_libvirt.py
=> Add Libvirt CR setup helper to fix UI E2E tests

robottelo/host_helpers/__init__.py, robottelo/host_helpers/satellite_mixins.py, tests/foreman/ui/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12314
=> [6.14.z] Add Libvirt CR setup helper to fix UI E2E tests

robottelo/host_helpers/__init__.py, robottelo/host_helpers/satellite_mixins.py, tests/foreman/ui/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12314
=> [6.13.z] Add Libvirt CR setup helper to fix UI E2E tests

robottelo/host_helpers/__init__.py, robottelo/host_helpers/satellite_mixins.py, tests/foreman/ui/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12314
=> [6.12.z] Add Libvirt CR setup helper to fix UI E2E tests

robottelo/host_helpers/__init__.py, robottelo/host_helpers/satellite_mixins.py, tests/foreman/ui/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12314
=> [6.11.z] Add Libvirt CR setup helper to fix UI E2E tests

tests/foreman/maintain/test_health.py
Making task 31 days older is not always enough.
We have to consider long running suites (18hrs+) 
Noticed when ` test_positive_health_check_old_foreman_tasks` test was running after midnight it couldnt find old task
```
2023-08-24 00:16:21 - gw1 - broker - DEBUG - satellite.example.com executing command: foreman-rake console <<< 't = ForemanTasks::Task.where(state: "stopped").first;t.started_at = t.started_at - 31.day;t.save(:validate => false)'
2023-08-24 00:16:40 - gw1 - broker - DEBUG - satellite.example.com command result:
stdout:
Loading production environment (Rails 6.1.7.3)
Switch to inspect mode.
t = ForemanTasks::Task.where(state: "stopped").first;t.started_at = t.started_at - 31.day;t.save(:validate => false)
true
stderr:
(0, b'')
status: 0
2023-08-24 00:16:40 - gw1 - broker - …
```
=> Make old foreman task 32 days older

tests/foreman/maintain/test_health.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12396
Making task 31 days older is not always enough.
We have to consider long running suites (18hrs+) 
Noticed when ` test_positive_health_check_old_foreman_tasks` test was running after midnight it couldnt find old task
```
2023-08-24 00:16:21 - gw1 - broker - DEBUG - satellite.example.com executing command: foreman-rake console <<< 't = ForemanTasks::Task.where(state: "stopped").first;t.started_at = t.started_at - 31.day;t.save(:validate => false)'
2023-08-24 00:16:40 - gw1 - broker - DEBUG - satellite.example.com command result:
stdout:
Loading production environment (Rails 6.1.7.3)
Switch to inspect mode.
t = ForemanTasks::Task.where(state: "stopped").first;t.started_at = t.started_at - 31.day;t.save(:validate => false) …
```
=> [6.13.z] Make old foreman task 32 days older

tests/foreman/maintain/test_health.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12396
Making task 31 days older is not always enough.
We have to consider long running suites (18hrs+) 
Noticed when ` test_positive_health_check_old_foreman_tasks` test was running after midnight it couldnt find old task
```
2023-08-24 00:16:21 - gw1 - broker - DEBUG - satellite.example.com executing command: foreman-rake console <<< 't = ForemanTasks::Task.where(state: "stopped").first;t.started_at = t.started_at - 31.day;t.save(:validate => false)'
2023-08-24 00:16:40 - gw1 - broker - DEBUG - satellite.example.com command result:
stdout:
Loading production environment (Rails 6.1.7.3)
Switch to inspect mode.
t = ForemanTasks::Task.where(state: "stopped").first;t.started_at = t.started_at - 31.day;t.save(:validate => false) …
```
=> [6.12.z] Make old foreman task 32 days older

tests/foreman/ui/test_computeresource_vmware.py
Small syntax error in my last PR for virt-card, just cleaning that up 
(Wasn't caught in PRT, as the test didn't hit a condition that would cause it to happen - i.e., one of the fields not being present )
=> Syntax error fix. 

tests/foreman/ui/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12176
This simply removes an assert from the test. This portion of the virtualization card doesn't reliably appear on the card, and can cause this test to be flaky.
=> [6.14.z] Fix unreliable assertion

.gitignore, pytest_fixtures/core/broker.py, pytest_fixtures/core/sat_cap_factory.py, pytest_fixtures/core/upgrade.py, pytest_fixtures/core/xdist.py, robottelo/host_helpers/contenthost_mixins.py, robottelo/hosts.py, tests/foreman/api/test_provisioning.py, tests/foreman/api/test_provisioning_puppet.py, tests/foreman/destructive/test_leapp_satellite.py, tests/upgrades/test_client.py, tests/upgrades/test_errata.py, tests/upgrades/test_repository.py, tests/upgrades/test_subscription.py
cherry-pick of #12144
Fixes #12304
* Introduce and enhance robottelo.hosts features
* Apply suggestions from code review
* Revert Jake's suggestion as cached_property stores data in __dict__
* Clean cached properties of LEAPPed host to get non-cached OS version
* Use redhat-release to keep RHEL 6 compatibility
* Reverse operations
---------
(cherry picked from commit 49c4692d03acb0117d63a39590185d22f6ad8db8)
=> [6.14.z] Introduce and enhance robottelo.hosts features (#12144)

.gitignore, pytest_fixtures/core/broker.py, pytest_fixtures/core/sat_cap_factory.py, pytest_fixtures/core/upgrade.py, pytest_fixtures/core/xdist.py, robottelo/host_helpers/contenthost_mixins.py, robottelo/hosts.py, tests/foreman/api/test_provisioning.py, tests/foreman/destructive/test_leapp_satellite.py, tests/upgrades/test_client.py, tests/upgrades/test_errata.py, tests/upgrades/test_repository.py, tests/upgrades/test_subscription.py
cherry-pick of #12144
Fixes #12303
* Introduce and enhance robottelo.hosts features
* Apply suggestions from code review
* Revert Jake's suggestion as cached_property stores data in __dict__
* Clean cached properties of LEAPPed host to get non-cached OS version
* Use redhat-release to keep RHEL 6 compatibility
* Reverse operations
---------
(cherry picked from commit 49c4692d03acb0117d63a39590185d22f6ad8db8)
=> [6.12.z] Introduce and enhance robottelo.hosts features (#12144)

.gitignore, pytest_fixtures/core/broker.py, pytest_fixtures/core/sat_cap_factory.py, pytest_fixtures/core/upgrade.py, pytest_fixtures/core/xdist.py, robottelo/host_helpers/contenthost_mixins.py, robottelo/hosts.py, tests/foreman/api/test_provisioning.py, tests/foreman/destructive/test_leapp_satellite.py, tests/upgrades/test_client.py, tests/upgrades/test_errata.py, tests/upgrades/test_repository.py, tests/upgrades/test_subscription.py
cherry-pick of #12144
Fixes #12301
* Introduce and enhance robottelo.hosts features
* Apply suggestions from code review
* Revert Jake's suggestion as cached_property stores data in __dict__
* Clean cached properties of LEAPPed host to get non-cached OS version
* Use redhat-release to keep RHEL 6 compatibility
* Reverse operations
---------
(cherry picked from commit 49c4692d03acb0117d63a39590185d22f6ad8db8)
=> [6.11.z] Introduce and enhance robottelo.hosts features (#12144)

pytest_fixtures/component/settings.py, tests/foreman/ui/test_http_proxy.py
setting_update fixtures fails to update the default None value, and this was previously handled, but is now broken due to my earlier PR https://github.com/SatelliteQE/robottelo/pull/11737
=> Fix setting_update fixture to handle None value

pytest_fixtures/component/settings.py, tests/foreman/ui/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12414
setting_update fixtures fails to update the default None value, and this was previously handled, but is now broken due to my earlier PR https://github.com/SatelliteQE/robottelo/pull/11737
=> [6.13.z] Fix setting_update fixture to handle None value

pytest_fixtures/component/settings.py, tests/foreman/ui/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12414
setting_update fixtures fails to update the default None value, and this was previously handled, but is now broken due to my earlier PR https://github.com/SatelliteQE/robottelo/pull/11737
=> [6.14.z] Fix setting_update fixture to handle None value

pytest_fixtures/component/settings.py, tests/foreman/ui/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12414
setting_update fixtures fails to update the default None value, and this was previously handled, but is now broken due to my earlier PR https://github.com/SatelliteQE/robottelo/pull/11737
=> [6.12.z] Fix setting_update fixture to handle None value

tests/foreman/api/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12379
Just a simplification fix of the test - we don't need to spin up a host to test this, we can assert it from Satellite.
=> [6.14.z] Fix Capsule AC test

tests/foreman/api/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12379
Just a simplification fix of the test - we don't need to spin up a host to test this, we can assert it from Satellite.
=> [6.13.z] Fix Capsule AC test

tests/foreman/api/test_reporttemplates.py
PRT build results: 
- Just the 3 parameters of `test_positive_installable_errata`: **[3737] 3/3 Pass**
- All of `API/test_reporttemplates.py`: **[3738] In Progress**
`> assert rhel_contenthost.execute(f'yum install -y {FAKE_1_CUSTOM_PACKAGE}').status == 0 
E        +  where 1 = stdout:\nLoaded plugins: product-id, search-disabled-repos, subscription-manager\n\nstderr:\n(256, b'There are no enabled ...n-manager repos --enable <repo>
\n To enable custom repositories:\n     yum-config-manager --enable <repo>\n')\nstatus: 1.status`
Prior CI Failure: **[3729] 3/3 Fail**, `b'There are no enabled ...n-manager repos --enable <repo>`
Report template should find the applicable errata of package 'walrus', which was downgraded/out of date.
Assertions test the package version of 'walrus' to make sure …
=> fixes for [RFE] test_positive_installable_errata

tests/foreman/api/test_capsulecontent.py
There is some flakiness in this test, it sometimes fail with this error:
```
tests/foreman/api/test_capsulecontent.py:1278: in test_positive_capsule_sync_status_persists
assert sync_status['last_sync_time'] >= timestamp
E   AssertionError: assert '2023-08-23 23:03:51 UTC' >= '2023-08-23 23:04'
```
As I learned from DEVs, the designed&implemented behaviour is to fall back to audits when all old sync tasks get deleted (which happens on a regular basis on cleanup). So the caps sync time is taken from audits **only** when all sync tasks are missing. This implies that we need to change the test logic, because if we delete the most recent sync task (and keep older ones, which is the current logic) we don't fall back to audits but to the previous task, which is older than our timestamp and the …
=> Fix capsule sync status persists

tests/foreman/api/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12216
There is some flakiness in this test, it sometimes fail with this error:
```
tests/foreman/api/test_capsulecontent.py:1278: in test_positive_capsule_sync_status_persists
assert sync_status['last_sync_time'] >= timestamp
E   AssertionError: assert '2023-08-23 23:03:51 UTC' >= '2023-08-23 23:04'
```
As I learned from DEVs, the designed&implemented behaviour is to fall back to audits when all old sync tasks get deleted (which happens on a regular basis on cleanup). So the caps sync time is taken from audits **only** when all sync tasks are missing. This implies that we need to change the test logic, because if we delete the most recent sync task (and keep older ones, which is the current logic) we don't fall back to audits …
=> [6.14.z] Fix capsule sync status persists

tests/foreman/cli/test_syncplan.py
1. Fix for several occurrences missed during helpers refactor.
2. Force explicit time format. Earlier no offset was was provided and UTC was considered, now it seems the local system time is considered instead.
=> Fix CLI SyncPlan tests

tests/foreman/cli/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12473
1. Fix for several occurrences missed during helpers refactor.
2. Force explicit time format. Earlier no offset was was provided and UTC was considered, now it seems the local system time is considered instead.
=> [6.13.z] Fix CLI SyncPlan tests

tests/foreman/cli/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12473
1. Fix for several occurrences missed during helpers refactor.
2. Force explicit time format. Earlier no offset was was provided and UTC was considered, now it seems the local system time is considered instead.
=> [6.12.z] Fix CLI SyncPlan tests

pytest_plugins/logging_hooks.py, robottelo/hosts.py
=> Log end of test phases and broker host setup and teardown

pytest_plugins/logging_hooks.py, robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12472
=> [6.13.z] Log end of test phases and broker host setup and teardown

pytest_plugins/logging_hooks.py, robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12472
=> [6.14.z] Log end of test phases and broker host setup and teardown

pytest_fixtures/component/maintain.py, robottelo/constants/__init__.py, robottelo/host_helpers/contenthost_mixins.py, tests/foreman/maintain/test_advanced.py, tests/foreman/maintain/test_health.py, tests/foreman/maintain/test_maintenance_mode.py, tests/foreman/maintain/test_service.py, tests/foreman/maintain/test_upgrade.py
This PR:
- removes destructive marker as it doesn't work as expected with tests using module or session scoped fixtures.
- converts`sat_maintain` to module scoped fixture.
- Adds `start_satellite_services` teardown fixture, which will be used by tests that stop/disable Satellite services.
- updates `test_positive_capsule_repositories_setup` to support 6.14 and stream.
- removes `include_capsule` marker from `test_positive_health_check_available_space` as capsule doesn't have `available-space-cp` check.
- fixes `test_positive_sync_plan_with_hammer_defaults`
- updates `test_positive_satellite_repositories_setup` and `test_positive_satellite_repositories_setup` to test only one sat version.
- fixes `test_negative_pre_upgrade_tuning_profile_check` for stream.
- Update `_dogfood_helper` to not …
=> Fix foreman-maintain tests failing because of automation issues

tests/foreman/maintain/test_health.py
Unstubbing and automating health check test for foreman-proxy-verify-dhcp-config-syntax as part of the foreman-maintain audit.
=> Add health check test for verify_dhcp_config_syntax

pytest_fixtures/component/katello_agent.py, robottelo/hosts.py, tests/foreman/destructive/test_katello_agent.py
In this PR I propose two changes:
1. Since 6.14 the custom repos are disabled by default, we need to have them overridden to enabled.
2. Katello-agent fails in old (RHEL6 and 7) containers (IIRC goferd failed to start since it was missing some system service), but it pass on a regular VMs. In order to get this component tested for 6.14 RC properly I propose to set it run on the standard VMs. The price is 1.5 - 2 h of extra run time, which I find acceptable since the katello-agent gets removed from 6.15 anyway and these tests would be deleted in 18 months.
PRT results:
no_containers:
- 19 passed, 1 broker provider err (PRT#3689, 6:28:38) 
- all 20 passed (PRT#3790, 6:08:16)
with containers:
- 10 (RHEL6/7) failed, 10 (RHEL8/9) passed (PRT#3700, ~4:33:00)
=> Fix katello-agent

pytest_fixtures/component/maintain.py, robottelo/constants/__init__.py, robottelo/host_helpers/contenthost_mixins.py, tests/foreman/maintain/test_advanced.py, tests/foreman/maintain/test_health.py, tests/foreman/maintain/test_maintenance_mode.py, tests/foreman/maintain/test_service.py, tests/foreman/maintain/test_upgrade.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12440
This PR:
- removes destructive marker as it doesn't work as expected with tests using module or session scoped fixtures.
- converts`sat_maintain` to module scoped fixture.
- Adds `start_satellite_services` teardown fixture, which will be used by tests that stop/disable Satellite services.
- updates `test_positive_capsule_repositories_setup` to support 6.14 and stream.
- removes `include_capsule` marker from `test_positive_health_check_available_space` as capsule doesn't have `available-space-cp` check.
- fixes `test_positive_sync_plan_with_hammer_defaults`
- updates `test_positive_satellite_repositories_setup` and `test_positive_satellite_repositories_setup` to test only one sat version.
- fixes …
=> [6.13.z] Fix foreman-maintain tests failing because of automation issues

tests/foreman/api/test_rhcloud_inventory.py, tests/foreman/ui/test_rhcloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12511
Refactor tests present in tests/foreman/ui/test_rhcloud_inventory.py based on feedback received on Components evaluation sheet.
This PR:
- removes `test_rhcloud_inventory_mtu_field` as it's covered in foreman unit tests.
- removes `test_obfuscate_host_ipv4_addresses`, `test_exclude_packages_setting` and `test_obfuscate_host_names` and covers them in `test_rh_cloud_inventory_settings`
- removes `test_automatic_inventory_upload_enabled_setting` and `test_automatic_inventory_upload_disabled_setting` as it's covered in `test_rhcloud_inventory_auto_upload_setting`.
=> [6.14.z] Refactor tests/foreman/ui/test_rhcloud_inventory.py

pytest_plugins/logging_hooks.py, robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12472
=> [6.11.z] Log end of test phases and broker host setup and teardown

tests/foreman/api/test_rhcloud_inventory.py, tests/foreman/ui/test_rhcloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12511
Refactor tests present in tests/foreman/ui/test_rhcloud_inventory.py based on feedback received on Components evaluation sheet.
This PR:
- removes `test_rhcloud_inventory_mtu_field` as it's covered in foreman unit tests.
- removes `test_obfuscate_host_ipv4_addresses`, `test_exclude_packages_setting` and `test_obfuscate_host_names` and covers them in `test_rh_cloud_inventory_settings`
- removes `test_automatic_inventory_upload_enabled_setting` and `test_automatic_inventory_upload_disabled_setting` as it's covered in `test_rhcloud_inventory_auto_upload_setting`.
=> [6.13.z] Refactor tests/foreman/ui/test_rhcloud_inventory.py

pytest_plugins/logging_hooks.py, robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12472
=> [6.12.z] Log end of test phases and broker host setup and teardown

tests/foreman/api/test_oscap_tailoringfiles.py, tests/foreman/api/test_oscappolicy.py, tests/foreman/cli/test_oscap.py, tests/foreman/cli/test_oscap_tailoringfiles.py, tests/foreman/longrun/test_oscap.py, tests/foreman/ui/test_oscapcontent.py, tests/foreman/ui/test_oscappolicy.py, tests/foreman/ui/test_oscaptailoringfile.py
This PR is to move all SCAP related tests and modules to Endeavour Team since the component moved to that team.
=> Move SCAPPlugin Component to Endeavour Team

tests/foreman/api/test_oscap_tailoringfiles.py, tests/foreman/api/test_oscappolicy.py, tests/foreman/cli/test_oscap.py, tests/foreman/cli/test_oscap_tailoringfiles.py, tests/foreman/longrun/test_oscap.py, tests/foreman/ui/test_oscapcontent.py, tests/foreman/ui/test_oscappolicy.py, tests/foreman/ui/test_oscaptailoringfile.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12520
This PR is to move all SCAP related tests and modules to Endeavour Team since the component moved to that team.
=> [6.14.z] Move SCAPPlugin Component to Endeavour Team

tests/foreman/api/test_oscap_tailoringfiles.py, tests/foreman/api/test_oscappolicy.py, tests/foreman/cli/test_oscap.py, tests/foreman/cli/test_oscap_tailoringfiles.py, tests/foreman/longrun/test_oscap.py, tests/foreman/ui/test_oscapcontent.py, tests/foreman/ui/test_oscappolicy.py, tests/foreman/ui/test_oscaptailoringfile.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12520
This PR is to move all SCAP related tests and modules to Endeavour Team since the component moved to that team.
=> [6.13.z] Move SCAPPlugin Component to Endeavour Team

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12466
Try to delete the host record even if the host is not registered to Satellite
=> [6.13.z] Delete Host record on teardown

pytest_plugins/metadata_markers.py
Currently, when I see ibutsu report I see only 6.15, 6.14.. and never seen x.y.z format. Even we are testing on Satellite 6.13.4 it is showing as 6.13. This will fix that.
=> Passing more correct metadata sat version for ibutsu

tests/foreman/ui/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12474
Products added to a SyncPlan must contain a repo in 6.14.
=> [6.14.z] Fix UI SyncPlan

pytest_plugins/metadata_markers.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12488
Currently, when I see ibutsu report I see only 6.15, 6.14.. and never seen x.y.z format. Even we are testing on Satellite 6.13.4 it is showing as 6.13. This will fix that.
=> [6.14.z] Passing more correct metadata sat version for ibutsu

pytest_plugins/metadata_markers.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12488
Currently, when I see ibutsu report I see only 6.15, 6.14.. and never seen x.y.z format. Even we are testing on Satellite 6.13.4 it is showing as 6.13. This will fix that.
=> [6.13.z] Passing more correct metadata sat version for ibutsu

pytest_plugins/metadata_markers.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12488
Currently, when I see ibutsu report I see only 6.15, 6.14.. and never seen x.y.z format. Even we are testing on Satellite 6.13.4 it is showing as 6.13. This will fix that.
=> [6.12.z] Passing more correct metadata sat version for ibutsu

pytest_fixtures/component/katello_agent.py, robottelo/hosts.py, tests/foreman/destructive/test_katello_agent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12395
In this PR I propose two changes:
1. Since 6.14 the custom repos are disabled by default, we need to have them overridden to enabled.
2. Katello-agent fails in old (RHEL6 and 7) containers (IIRC goferd failed to start since it was missing some system service), but it pass on a regular VMs. In order to get this component tested for 6.14 RC properly I propose to set it run on the standard VMs. The price is 1.5 - 2 h of extra run time, which I find acceptable since the katello-agent gets removed from 6.15 anyway and these tests would be deleted in 18 months.
PRT results:
no_containers:
- 19 passed, 1 broker provider err (PRT#3689, 6:28:38) 
- all 20 passed (PRT#3790, 6:08:16)
with containers:
- 10 (RHEL6/7) failed, 10 …
=> [6.14.z] Fix katello-agent

pytest_fixtures/core/sat_cap_factory.py, tests/foreman/destructive/test_clone.py, tests/foreman/installer/test_installer.py, tests/foreman/maintain/test_upgrade.py, tests/foreman/sys/test_katello_certs_check.py
This is to make sure that tests that request ohsnap URLs contains a snap number in them. Even though ohsnap should provide the latest snap repo URLs it's better to be explicit and not rely on this behaviour of ohsnap.
Previously, we were setting snap number(if not provided) from robottelo setting using `_dogfood_helper` but that caused it to generate the wrong url if the release was other than the one in robottelo setting. See https://github.com/SatelliteQE/robottelo/pull/12440/files#diff-8c51f6ed7f99859d1efd6f74f29cc8e05e54bca2389c18e7e52c0203c1cbee6b
=> Update tests to use snap version when getting ohsnap repo urls

pytest_fixtures/core/sat_cap_factory.py, tests/foreman/destructive/test_clone.py, tests/foreman/installer/test_installer.py, tests/foreman/maintain/test_upgrade.py, tests/foreman/sys/test_katello_certs_check.py
Fixes https://github.com/SatelliteQE/robottelo/issues/12550
Cherry-pick of https://github.com/SatelliteQE/robottelo/pull/12528
=> [6.14.z] Update tests to use snap version when getting ohsnap repo urls (#12528)

pytest_fixtures/core/sat_cap_factory.py, tests/foreman/destructive/test_clone.py, tests/foreman/maintain/test_upgrade.py, tests/foreman/sys/test_katello_certs_check.py
Fixes https://github.com/SatelliteQE/robottelo/issues/12548
Cherry-pick of https://github.com/SatelliteQE/robottelo/pull/12528
=> [6.13.z] Update tests to use snap version when getting ohsnap repo urls (#12528)

pytest_fixtures/core/sat_cap_factory.py, tests/foreman/destructive/test_clone.py, tests/foreman/sys/test_katello_certs_check.py
Fixes https://github.com/SatelliteQE/robottelo/issues/12549
Cherry-pick of https://github.com/SatelliteQE/robottelo/pull/12528
=> [6.12.z] Update tests to use snap version when getting ohsnap repo urls (#12528)

tests/foreman/maintain/test_backup_restore.py
`tests.foreman.maintain.test_backup_restore.test_positive_backup_restore` fails with `ssh2.exceptions.Timeout` when running for `satellite` and `include-pulp` datapoints
Backing up a Satellite including pulp data takes long time.
=> Set timeout as backup takes long time

tests/foreman/maintain/test_backup_restore.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12554
`tests.foreman.maintain.test_backup_restore.test_positive_backup_restore` fails with `ssh2.exceptions.Timeout` when running for `satellite` and `include-pulp` datapoints
Backing up a Satellite including pulp data takes long time.
=> [6.14.z] Set timeout as backup takes long time

tests/foreman/maintain/test_backup_restore.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12554
`tests.foreman.maintain.test_backup_restore.test_positive_backup_restore` fails with `ssh2.exceptions.Timeout` when running for `satellite` and `include-pulp` datapoints
Backing up a Satellite including pulp data takes long time.
=> [6.13.z] Set timeout as backup takes long time

tests/foreman/maintain/test_backup_restore.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12554
`tests.foreman.maintain.test_backup_restore.test_positive_backup_restore` fails with `ssh2.exceptions.Timeout` when running for `satellite` and `include-pulp` datapoints
Backing up a Satellite including pulp data takes long time.
=> [6.12.z] Set timeout as backup takes long time

tests/foreman/api/test_permission.py
Related to https://github.com/SatelliteQE/nailgun/pull/992
=> AK update must contain org id, it is a required field

tests/foreman/maintain/test_service.py
During component evaluations, support said this should be using UTF-8, so I'm updating that here and adding e2e and upgrade to `test_positive_service_stop_restart`.
=> Update clocale test to use UTF-8

tests/foreman/maintain/test_service.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12534
During component evaluations, support said this should be using UTF-8, so I'm updating that here and adding e2e and upgrade to `test_positive_service_stop_restart`.
=> [6.14.z] Update clocale test to use UTF-8

pytest_fixtures/component/templatesync.py
Updating the fixture as BZ#2232162 evolved into documentation fixture. The new recommended way is to either use a pre-defined export dir or use a different context if custom one is needed. I chose the second option as the first one is already tested in bats tests.
=> change in import/export directory context

robottelo/host_helpers/satellite_mixins.py, robottelo/hosts.py
This PR, in combination with https://github.com/SatelliteQE/manifester/pull/21, addresses some of the errors that have been occurring in CI in cases where Manifester times out when exporting a manifest due to an upstream RHSM issue. These changes should enable Robottelo to successfully fail over to using cloned manifests in those cases.
=> Debug failover to cloned manifests

robottelo/host_helpers/satellite_mixins.py, robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12515
This PR, in combination with https://github.com/SatelliteQE/manifester/pull/21, addresses some of the errors that have been occurring in CI in cases where Manifester times out when exporting a manifest due to an upstream RHSM issue. These changes should enable Robottelo to successfully fail over to using cloned manifests in those cases.
=> [6.14.z] Debug failover to cloned manifests

robottelo/host_helpers/satellite_mixins.py, robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12515
This PR, in combination with https://github.com/SatelliteQE/manifester/pull/21, addresses some of the errors that have been occurring in CI in cases where Manifester times out when exporting a manifest due to an upstream RHSM issue. These changes should enable Robottelo to successfully fail over to using cloned manifests in those cases.
=> [6.13.z] Debug failover to cloned manifests

robottelo/host_helpers/satellite_mixins.py, robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12515
This PR, in combination with https://github.com/SatelliteQE/manifester/pull/21, addresses some of the errors that have been occurring in CI in cases where Manifester times out when exporting a manifest due to an upstream RHSM issue. These changes should enable Robottelo to successfully fail over to using cloned manifests in those cases.
=> [6.12.z] Debug failover to cloned manifests

tests/upgrades/test_performance_tuning.py
Fixes `Tuning profile 'medium' requires at least 32 GB of memory and 8 CPU cores` 
Medium tuning profile is in contrast with `satqe-ssd.upgrade.std` flavor specs
=> Avoid using medium tuning profile due to the lack of resources

tests/upgrades/test_performance_tuning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12587
Fixes `Tuning profile 'medium' requires at least 32 GB of memory and 8 CPU cores` 
Medium tuning profile is in contrast with `satqe-ssd.upgrade.std` flavor specs
=> [6.14.z] Avoid using medium tuning profile due to the lack of resources

tests/upgrades/test_performance_tuning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12587
Fixes `Tuning profile 'medium' requires at least 32 GB of memory and 8 CPU cores` 
Medium tuning profile is in contrast with `satqe-ssd.upgrade.std` flavor specs
=> [6.13.z] Avoid using medium tuning profile due to the lack of resources

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12466
Try to delete the host record even if the host is not registered to Satellite
=> [6.12.z] Delete Host record on teardown

robottelo/host_helpers/satellite_mixins.py
This PR adds a check to resolve a regression in `upload_manifest` introduced by https://github.com/SatelliteQE/robottelo/pull/12515.
=> Fix regression from cloned manifest failover

robottelo/host_helpers/satellite_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12605
This PR adds a check to resolve a regression in `upload_manifest` introduced by https://github.com/SatelliteQE/robottelo/pull/12515.
=> [6.13.z] Fix regression from cloned manifest failover

robottelo/host_helpers/satellite_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12605
This PR adds a check to resolve a regression in `upload_manifest` introduced by https://github.com/SatelliteQE/robottelo/pull/12515.
=> [6.14.z] Fix regression from cloned manifest failover

robottelo/host_helpers/satellite_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12605
This PR adds a check to resolve a regression in `upload_manifest` introduced by https://github.com/SatelliteQE/robottelo/pull/12515.
=> [6.12.z] Fix regression from cloned manifest failover

tests/foreman/api/test_provisioningtemplate.py
Fixes https://github.com/SatelliteQE/robottelo/issues/12593
Cherrypick of https://github.com/SatelliteQE/robottelo/pull/12586
(cherry picked from commit 59980dd3a970b00e4a24573c894c863c47d40d9f)
=> [6.12.z] Add automation for BZ 2024175

tests/foreman/cli/test_hammer.py
`test_positive_all_options` is consistently failing in the upgrade run as the set of enabled plugins on upgraded satellite is different than in the regular runs. Also it does not provide much value over existence tests.
=> change in upgrade marks for hammer tests

tests/foreman/cli/test_hammer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12584
`test_positive_all_options` is consistently failing in the upgrade run as the set of enabled plugins on upgraded satellite is different than in the regular runs. Also it does not provide much value over existence tests.
=> [6.14.z] change in upgrade marks for hammer tests

pytest_fixtures/component/provision_pxe.py, tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12604
Adding iPXE provisioning test as a part of the component audit.
=> [6.14.z] iPXE provisioning test

tests/foreman/api/test_role.py, tests/foreman/api/test_user.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12585
null
=> [6.14.z] Use sAMAccountName in AD LDAP, i.e. 'domain\username'

tests/foreman/api/test_role.py, tests/foreman/api/test_user.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12585
null
=> [6.13.z] Use sAMAccountName in AD LDAP, i.e. 'domain\username'

tests/foreman/maintain/test_backup_restore.py
#11349 broke RemoteDB expected files logic so that asserts are failing for remote db incremental backup
```
AssertionError: Some required backup files are missing
```
Being in the module I have taken the opportunity to streamline `expected_files` logic :wink:
=> Fix remotedb backup expected files

tests/foreman/maintain/test_backup_restore.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12645
#11349 broke RemoteDB expected files logic so that asserts are failing for remote db incremental backup
```
AssertionError: Some required backup files are missing
```
Being in the module I have taken the opportunity to streamline `expected_files` logic :wink:
=> [6.14.z] Fix remotedb backup expected files

tests/foreman/maintain/test_backup_restore.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12645
#11349 broke RemoteDB expected files logic so that asserts are failing for remote db incremental backup
```
AssertionError: Some required backup files are missing
```
Being in the module I have taken the opportunity to streamline `expected_files` logic :wink:
=> [6.13.z] Fix remotedb backup expected files

.github/workflows/weekly.yml
weekly check (that looks if customerscenario tags are not missing) was not checking for a while, the failure was on dependency install, bumping python version to get over it
=> bump python version for weekly action

testimony.yaml, tests/foreman/cli/test_leapp_client.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11553
**PR Description**
- Upgrading Rhel host to next major RHEL Realse with job templates
- Path RHEL 8.8 to 9.2
**Steps:**
1. Import a subscription manifest and enable, sync source & target repositories
2. Create CV, add repositories, create lce, ak, etc.
3. Register contenthost using ak
4. Varify target rhel repositories are enable on Satellite
5. Update all packages, install leapp tool and fix inhibitors (in advance)
6. Run Leapp Preupgrade and Leapp Upgrade job template
**Expected output:**
- Update rhel major version to another major version
=> [6.12.z] leapp scenario 8.8 to 9.2

.flake8, .pre-commit-config.yaml, pyproject.toml, robottelo/constants/__init__.py, robottelo/host_helpers/satellite_mixins.py, tests/foreman/api/test_multiple_paths.py, tests/foreman/cli/test_webhook.py, tests/foreman/endtoend/test_api_endtoend.py, tests/foreman/ui/test_bookmarks.py, tests/robottelo/test_datafactory.py, tests/upgrades/conftest.py
This patch replaces flake8 with Ruff that is 10-100x faster than flake8. It enables only a few rule sets that were enabled by pyflakes already.
Other rules will be added in future PRs.
=> Replace flake8 with Ruff

.flake8, .pre-commit-config.yaml, pyproject.toml, robottelo/constants/__init__.py, robottelo/host_helpers/satellite_mixins.py, tests/foreman/api/test_multiple_paths.py, tests/foreman/cli/test_webhook.py, tests/foreman/endtoend/test_api_endtoend.py, tests/foreman/ui/test_bookmarks.py, tests/robottelo/test_datafactory.py, tests/upgrades/conftest.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12621
This patch replaces flake8 with Ruff that is 10-100x faster than flake8. It enables only a few rule sets that were enabled by pyflakes already.
Other rules will be added in future PRs.
=> [6.13.z] Replace flake8 with Ruff

.flake8, .pre-commit-config.yaml, pyproject.toml, robottelo/constants/__init__.py, robottelo/host_helpers/satellite_mixins.py, tests/foreman/api/test_multiple_paths.py, tests/foreman/cli/test_webhook.py, tests/foreman/endtoend/test_api_endtoend.py, tests/foreman/ui/test_bookmarks.py, tests/robottelo/test_datafactory.py, tests/upgrades/conftest.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12621
This patch replaces flake8 with Ruff that is 10-100x faster than flake8. It enables only a few rule sets that were enabled by pyflakes already.
Other rules will be added in future PRs.
=> [6.14.z] Replace flake8 with Ruff

tests/foreman/ui/test_contenthost.py
Some recent updates cause custom repos to be disabled by default, this enables them before running further in the tests.
=> Fix end-to-end and bulke2e

tests/foreman/maintain/test_service.py
Cherry-pick for https://github.com/SatelliteQE/robottelo/pull/12534.
=> [6.12.z] Update clocale test to use UTF-8

tests/foreman/ui/test_contenthost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12413
Some recent updates cause custom repos to be disabled by default, this enables them before running further in the tests.
=> [6.14.z] Fix end-to-end and bulke2e

tests/foreman/maintain/test_upgrade.py
Reverting this change to how it was before. This test wasn't passing before we had the 6.15.z upgrade path in stream, but now that it's been added we can assert for 6.15 in the output.
Going forward we will need a way to turn on and off the upgrade tests for stream depending on if the upgrade path is in stream yet.
=> Remove stream specific code from upgrade_list test

tests/foreman/ui/test_rhcloud_insights.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12582
Updating Insights UI tests to use the `host_new` entity when reading the Host status, added in https://github.com/SatelliteQE/airgun/pull/966.
=> [6.14.z] update Insights test to use new host page

tests/foreman/ui/test_rhcloud_insights.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12582
Updating Insights UI tests to use the `host_new` entity when reading the Host status, added in https://github.com/SatelliteQE/airgun/pull/966.
=> [6.13.z] update Insights test to use new host page

BEST_PRACTICES.md
Helpers Best Practices Guide is here to help assist Contributors to write the helper in a write place according to its usage.
The Guide contains three main sections:
1. General Practices
2. Description of main helper modules in robottelo
3. FAQs
=> Helpers Best Practices Guide

.github/workflows/auto_cherry_pick.yml
AutoCherryPick is currently missed adding `dependencies` label to the AutoCherrypicked Dependabot PRs and hence dependabot zStream cherrypicked PRs are not automerging as its missing the label for `dependencies`.
There is another reason its missing automerging the zStream PRs for which the PR is already raised : #12483 !
Verifed its working in my local testing repository:
- The GHA run finding and setting dependencies label: https://github.com/jyejare/test-acp/actions/runs/6260767022/job/16999485038?pr=17 
- The PR opened with dependencies label since parent PR has dependencies label: https://github.com/jyejare/test-acp/pull/18
=> Copy dependencies label for dependencies PRs

robottelo/constants/__init__.py, tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12347
Second batch of changes coming from the ISS evaluation
1. Added fixtures for importing orgs. These need to be new orgs so they don't reference the original `org` fixtures, which are used for export.
2. `_enable_rhel_repo` helper function was replaced by parametrized fixture and used through the module.
3. Using the fixture above three test cases were merged with `test_positive_export_import_redhat_cv`:
* `test_positive_export_complete_version_rh_repo` - was practically same as the first (export) part of the above case.
* `test_positive_export_import_redhat_cv_with_huge_contents` - same as the above case but bigger (rhscl) repo.
* `test_positive_export_import_kickstart_tree` - was a `stub` but now …
=> [6.13.z] ISS refactor - batch 2

robottelo/constants/__init__.py, tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12347
Second batch of changes coming from the ISS evaluation
1. Added fixtures for importing orgs. These need to be new orgs so they don't reference the original `org` fixtures, which are used for export.
2. `_enable_rhel_repo` helper function was replaced by parametrized fixture and used through the module.
3. Using the fixture above three test cases were merged with `test_positive_export_import_redhat_cv`:
* `test_positive_export_complete_version_rh_repo` - was practically same as the first (export) part of the above case.
* `test_positive_export_import_redhat_cv_with_huge_contents` - same as the above case but bigger (rhscl) repo.
* `test_positive_export_import_kickstart_tree` - was a `stub` but now …
=> [6.12.z] ISS refactor - batch 2

tests/foreman/maintain/test_backup_restore.py
Cherrypick of #12645 to `6.12.z` branch
(cherry picked from commit e075c5e4f7d91e1a7a6382b11b2fef03aa6e4258)
Fixes #12653
=> [6.12.z] Fix remotedb backup expected files

.github/workflows/auto_cherry_pick.yml
Parent PR: https://github.com/SatelliteQE/robottelo/pull/12682
Fixes: #12704
By:
-  Copy dependencies label for dependencies PRs in zStreams
- Removal of duplicate cherrypicking step for dependencies PR cherrypick
=> [6.14.z] Fix dependecies PR automerge in zStream Branches

.github/workflows/auto_cherry_pick.yml
Parent PR: https://github.com/SatelliteQE/robottelo/pull/12682
Fixes: #12705 
By:
-  Copy dependencies label for dependencies PRs in zStreams
- Removal of duplicate cherrypicking step for dependencies PR cherrypick
=> [6.13.z] Fix dependecies PR automerge in zStream Branche

.github/workflows/auto_cherry_pick.yml
Parent PR: #12682 
Fixes: #12703 
By:
-  Copy dependencies label for dependencies PRs in zStreams
- Removal of duplicate cherrypicking step for dependencies PR cherrypick
=> [6.12.z] Fix dependecies PR automerge in zStream Branches

tests/foreman/cli/test_satellitesync.py
Basically coverage for [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2212523) but generalized to check all content referenced in `repomd.xml` in both exports.
=> Add customer test case for BZ#2212523

tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12687
Basically coverage for [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2212523) but generalized to check all content referenced in `repomd.xml` in both exports.
=> [6.13.z] Add customer test case for BZ#2212523

tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12687
Basically coverage for [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2212523) but generalized to check all content referenced in `repomd.xml` in both exports.
=> [6.12.z] Add customer test case for BZ#2212523

.github/workflows/dependency_merge.yml
Fixing the AutoMerge of Dependabot AutoCherrypicked PRs are not running.
Attempt to change:
- The `pull_request_target` event
- The Author check for PR now removed and just checking for `dependency` label
- Separate GHA for zStream than master as the things varies for zStream for dependecy PRs auto-merge
Good if this is merged along with https://github.com/SatelliteQE/robottelo/pull/12682 that copies dependencies label to zStream cherrypicked PRs !
=> Fix : ZStream Dependency Auto Merging

.github/workflows/dependency_merge.yml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12483
Fixing the AutoMerge of Dependabot AutoCherrypicked PRs are not running.
Attempt to change:
- The `pull_request_target` event
- The Author check for PR now removed and just checking for `dependency` label
- Separate GHA for zStream than master as the things varies for zStream for dependecy PRs auto-merge
Good if this is merged along with https://github.com/SatelliteQE/robottelo/pull/12682 that copies dependencies label to zStream cherrypicked PRs !
=> [6.13.z] Fix : ZStream Dependency Auto Merging

.github/workflows/dependency_merge.yml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12483
Fixing the AutoMerge of Dependabot AutoCherrypicked PRs are not running.
Attempt to change:
- The `pull_request_target` event
- The Author check for PR now removed and just checking for `dependency` label
- Separate GHA for zStream than master as the things varies for zStream for dependecy PRs auto-merge
Good if this is merged along with https://github.com/SatelliteQE/robottelo/pull/12682 that copies dependencies label to zStream cherrypicked PRs !
=> [6.11.z] Fix : ZStream Dependency Auto Merging

.github/workflows/dependency_merge.yml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12483
Fixing the AutoMerge of Dependabot AutoCherrypicked PRs are not running.
Attempt to change:
- The `pull_request_target` event
- The Author check for PR now removed and just checking for `dependency` label
- Separate GHA for zStream than master as the things varies for zStream for dependecy PRs auto-merge
Good if this is merged along with https://github.com/SatelliteQE/robottelo/pull/12682 that copies dependencies label to zStream cherrypicked PRs !
=> [6.12.z] Fix : ZStream Dependency Auto Merging

robottelo/constants/__init__.py, tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12347
Second batch of changes coming from the ISS evaluation
1. Added fixtures for importing orgs. These need to be new orgs so they don't reference the original `org` fixtures, which are used for export.
2. `_enable_rhel_repo` helper function was replaced by parametrized fixture and used through the module.
3. Using the fixture above three test cases were merged with `test_positive_export_import_redhat_cv`:
* `test_positive_export_complete_version_rh_repo` - was practically same as the first (export) part of the above case.
* `test_positive_export_import_redhat_cv_with_huge_contents` - same as the above case but bigger (rhscl) repo.
* `test_positive_export_import_kickstart_tree` - was a `stub` but now …
=> [6.14.z] ISS refactor - batch 2

tests/foreman/api/test_repositories.py, tests/foreman/cli/test_repositories.py
Test for syncing multiple large repositories
This is a part of the Repository Rewrite efforts. Also covers a custom case 2224031
Steps:
Enabling and syncing the following repos succeeds with no errors
Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8
Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8
Red Hat Enterprise Linux 8 for x86_64 - AppStream Kickstart 8.7
Red Hat Enterprise Linux 8 for x86_64 - BaseOS Kickstart 8.7
=> [Repository Rewrite] Sync multiple large repositories

.github/workflows/pull_request.yml, conftest.py, pytest_plugins/auto_vault.py, robottelo/utils/__init__.py, robottelo/utils/vault.py, scripts/vault_login.py, tests/foreman/api/test_repositories.py
Pytest session now verifies the vault session first.
- If the session expired, it takes you to login, and once logged in, it continues to the next step
- If the session is running, it just continues
- This only works for local execution and not in CI as CI has AppRole credentials directly!
Pytest STDOUT:
```
2023-09-11 14:02:28 - robottelo - WARNING - Warning! Vault not logged in!
2023-09-11 14:02:28 - robottelo - WARNING - Warning! The browser is about to open for vault OIDC login, close the tab once the sign-in is done!
2023-08-28 17:55:47 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
2023-08-28 17:55:47 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests …
```
=> Pytest verifies and log-in into vault

requirements-optional.txt, tests/foreman/api/test_repositories.py
Broken by #12445
But not fault of his author nor reviewers.
PR just had been raised 26 days ago - before ruff
Yet `make docs` is now failing too:
```
File "/home/lpramuk/.virtualenvs/r/lib/python3.11/site-packages/sphinx/events.py", line 97, in emit
results.append(listener.handler(self.app, *args))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/lpramuk/.virtualenvs/r/lib/python3.11/site-packages/autoapi/extension.py", line 153, in run_autoapi
if sphinx_mapper_obj.load(
^^^^^^^^^^^^^^^^^^^^^^^
File "/home/lpramuk/.virtualenvs/r/lib/python3.11/site-packages/autoapi/mappers/python/mapper.py", line 300, in load
data = self.read_file(path=path, dir_root=dir_root)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
=> Fix ruff stylecheck

robottelo/hosts.py
This should have always existed but was overlooked. It will dramatically decrease the amount of time it takes to access the api property since it doesn't need to be reconstructed each time the property is accessed.
Before
------
%timeit mysat.api.Host
3.62 ms ± 52.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After
-----
%timeit mysat.api.Host
189 ns ± 0.943 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
=> Add in the caching mechanism to the Satellite's api property

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12765
This should have always existed but was overlooked. It will dramatically decrease the amount of time it takes to access the api property since it doesn't need to be reconstructed each time the property is accessed.
Before
------
%timeit mysat.api.Host
3.62 ms ± 52.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After
-----
%timeit mysat.api.Host
189 ns ± 0.943 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
=> [6.14.z] Add in the caching mechanism to the Satellite's api property

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12765
This should have always existed but was overlooked. It will dramatically decrease the amount of time it takes to access the api property since it doesn't need to be reconstructed each time the property is accessed.
Before
------
%timeit mysat.api.Host
3.62 ms ± 52.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
After
-----
%timeit mysat.api.Host
189 ns ± 0.943 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
=> [6.12.z] Add in the caching mechanism to the Satellite's api property

.github/dependabot.yml
Removing 6.11.z label from dependabot for not to autocherrypick by ACP GHA.
=> Removing 6.11.z branch for dependabot to not to auto cherrypick

tests/foreman/api/test_user.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12722
null
=> [6.14.z] Workaround nonexistent auth source in upgrade template

tests/foreman/api/test_user.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12722
null
=> [6.13.z] Workaround nonexistent auth source in upgrade template

tests/foreman/api/test_repository.py
Simple test for a pretty complicated BZ. Basically, this creates a repository and then deletes the Upstream URL, which in the BZ case triggered the missing content ID issues. It then goes on to make sure you can both update the URL, and delete the repo, cases which were impacted in the BZ. 
The sleep at the beginning is a simple solution to a bit of a weird problem, where when creating a repo, an asynchronous task to generate the metadata is kicked off. If we adjust the URL before that's done, it will collide with that task and error out. Sleeping for 5s gets around this case.
=> Missing content ID test

tests/foreman/api/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12764
Simple test for a pretty complicated BZ. Basically, this creates a repository and then deletes the Upstream URL, which in the BZ case triggered the missing content ID issues. It then goes on to make sure you can both update the URL, and delete the repo, cases which were impacted in the BZ. 
The sleep at the beginning is a simple solution to a bit of a weird problem, where when creating a repo, an asynchronous task to generate the metadata is kicked off. If we adjust the URL before that's done, it will collide with that task and error out. Sleeping for 5s gets around this case.
=> [6.14.z] Missing content ID test

tests/foreman/api/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12764
Simple test for a pretty complicated BZ. Basically, this creates a repository and then deletes the Upstream URL, which in the BZ case triggered the missing content ID issues. It then goes on to make sure you can both update the URL, and delete the repo, cases which were impacted in the BZ. 
The sleep at the beginning is a simple solution to a bit of a weird problem, where when creating a repo, an asynchronous task to generate the metadata is kicked off. If we adjust the URL before that's done, it will collide with that task and error out. Sleeping for 5s gets around this case.
=> [6.13.z] Missing content ID test

robottelo/cli/base.py, tests/foreman/destructive/test_installer.py
The changes to base.py are also in another one of my PR's (https://github.com/SatelliteQE/robottelo/pull/12756). Simple test here to make sure cert regeneration works when the change is made to the answers file. Also providing coverage for certs-regenerate since we don't have any tests for that.
=> Add coverage for 1964037 installer cert regeneration

robottelo/cli/base.py, tests/foreman/api/test_repositories.py, tests/foreman/maintain/test_service.py
The first commit here is a cherry-pick of an old PR that I accidentally removed in one of my Foreman Maintain audits. I must not have had the latest changes on that branch. I'm adding that back in and also adding coverage for 2055790.
=> Add coverage for 2055790 to service enable disable

tests/foreman/maintain/test_health.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12745
Adding coverage for BZ1956210. Just need to assert that health check doesn't cause an SSL error.
=> [6.12.z] Add customer coverage to health check

tests/foreman/maintain/test_health.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12745
Adding coverage for BZ1956210. Just need to assert that health check doesn't cause an SSL error.
=> [6.13.z] Add customer coverage to health check

robottelo/cli/base.py, tests/foreman/destructive/test_installer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12776
The changes to base.py are also in another one of my PR's (https://github.com/SatelliteQE/robottelo/pull/12756). Simple test here to make sure cert regeneration works when the change is made to the answers file. Also providing coverage for certs-regenerate since we don't have any tests for that.
=> [6.14.z] Add coverage for 1964037 installer cert regeneration

tests/foreman/ui/test_subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12781
Robottelo fix provided for `tests>foreman>ui>test_subscription.py::test_positive_end_to_end`, this test was failing due to flash message, Also uploaded manifest has sca enabled for orgnization and because of that test couldn't read subscription status from dashboard page, So added support to read subscription table.
Note: This test `test_subscription.py::test_positive_end_to_end` is depends on changes from [airgun #992](https://github.com/SatelliteQE/airgun/pull/992) to get execute successfully.
=> [6.14.z] subscription page ui failure fix in robottelo tests

.github/workflows/pull_request.yml, conftest.py, pytest_plugins/auto_vault.py, robottelo/utils/__init__.py, robottelo/utils/vault.py, scripts/vault_login.py
CherryPick of #12378 
fixes: #12760 
Pytest session now verifies the vault session first.
- If the session expired, it takes you to login, and once logged in, it continues to the next step
- If the session is running, it just continues
- This only works for local execution and not in CI as CI has AppRole credentials directly!
=> [6.14.z] Pytest verifies and log-in into vault

.github/workflows/pull_request.yml, conftest.py, pytest_plugins/auto_vault.py, robottelo/utils/__init__.py, robottelo/utils/vault.py, scripts/vault_login.py
CherryPick of #12378 
fixes: #12757 
Pytest session now verifies the vault session first.
- If the session expired, it takes you to login, and once logged in, it continues to the next step
- If the session is running, it just continues
- This only works for local execution and not in CI as CI has AppRole credentials directly!
=> [6.13.z] Pytest verifies and log-in into vault (#12378)

tests/foreman/maintain/test_service.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12756
The first commit here is a cherry-pick of an old PR that I accidentally removed in one of my Foreman Maintain audits. I must not have had the latest changes on that branch. I'm adding that back in and also adding coverage for 2055790.
=> [6.14.z] Add coverage for 2055790 to service enable disable

tests/foreman/maintain/test_upgrade.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12647
Unstubbing this test and modifying the docstring to be more accurate and easy to understand what is being tested.
=> [6.14.z] Add test for satellite-maintain's self updating ability

tests/foreman/maintain/test_packages.py
I'm removing this stubbed case because the steps for updating satellite-maintain here are outdated. We now rely on satellite-maintain's ability to self-upgrade either by running a command like `satellite-maintain upgrade list-versions` which is being tested in https://github.com/SatelliteQE/robottelo/pull/12647 or by using `satellite-maintain self-upgrade`. Dev is planning to make some changes to these commands as well which will get there own automation when it's ready. For now we can just remove this outdated stubbed case.
=> Remove stubbed FM case that is no longer needed

robottelo/cli/base.py, tests/foreman/destructive/test_installer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12776
The changes to base.py are also in another one of my PR's (https://github.com/SatelliteQE/robottelo/pull/12756). Simple test here to make sure cert regeneration works when the change is made to the answers file. Also providing coverage for certs-regenerate since we don't have any tests for that.
=> [6.13.z] Add coverage for 1964037 installer cert regeneration

robottelo/cli/discoveredhost.py, tests/foreman/cli/test_discoveredhost.py
PR aims to add coverage for Pxe and Pxeless Discovery host provisioning via hammer(CLI).
=> Audit - Adding coverage for Discovery provisioning via CLI

robottelo/cli/discoveredhost.py, tests/foreman/cli/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12467
PR aims to add coverage for Pxe and Pxeless Discovery host provisioning via hammer(CLI).
=> [6.14.z] Audit - Adding coverage for Discovery provisioning via CLI

robottelo/cli/discoveredhost.py, tests/foreman/cli/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12467
PR aims to add coverage for Pxe and Pxeless Discovery host provisioning via hammer(CLI).
=> [6.13.z] Audit - Adding coverage for Discovery provisioning via CLI

tests/foreman/api/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12829
CVV sorting issue hits again
=> [6.13.z] Fix capsule test by CVV sort

tests/foreman/api/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12829
CVV sorting issue hits again
=> [6.12.z] Fix capsule test by CVV sort

conf/server.yaml.template, robottelo/config/__init__.py, robottelo/config/validators.py, robottelo/hosts.py, tests/foreman/api/test_role.py, tests/foreman/api/test_subscription.py, tests/foreman/api/test_user.py
This PR adds the possibility to overwrite the `verify` settings of nailgun's [ServerConfig ](https://github.com/SatelliteQE/nailgun/blob/master/nailgun/config.py#L219) 
According to the setttings given by [requests](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification)
Backwards compatibility is kept by defaulting to `False` if the new settings option is not available.
=> Nailgun ssl cert verification

conf/server.yaml.template, robottelo/config/__init__.py, robottelo/config/validators.py, robottelo/hosts.py, tests/foreman/api/test_role.py, tests/foreman/api/test_subscription.py, tests/foreman/api/test_user.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12813
This PR adds the possibility to overwrite the `verify` settings of nailgun's [ServerConfig ](https://github.com/SatelliteQE/nailgun/blob/master/nailgun/config.py#L219) 
According to the setttings given by [requests](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification)
Backwards compatibility is kept by defaulting to `False` if the new settings option is not available.
=> [6.12.z] Nailgun ssl cert verification

conf/server.yaml.template, robottelo/config/__init__.py, robottelo/config/validators.py, robottelo/hosts.py, tests/foreman/api/test_role.py, tests/foreman/api/test_subscription.py, tests/foreman/api/test_user.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12813
This PR adds the possibility to overwrite the `verify` settings of nailgun's [ServerConfig ](https://github.com/SatelliteQE/nailgun/blob/master/nailgun/config.py#L219) 
According to the setttings given by [requests](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification)
Backwards compatibility is kept by defaulting to `False` if the new settings option is not available.
=> [6.13.z] Nailgun ssl cert verification

conf/server.yaml.template, robottelo/config/__init__.py, robottelo/config/validators.py, robottelo/hosts.py, tests/foreman/api/test_role.py, tests/foreman/api/test_subscription.py, tests/foreman/api/test_user.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12813
This PR adds the possibility to overwrite the `verify` settings of nailgun's [ServerConfig ](https://github.com/SatelliteQE/nailgun/blob/master/nailgun/config.py#L219) 
According to the setttings given by [requests](https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification)
Backwards compatibility is kept by defaulting to `False` if the new settings option is not available.
=> [6.14.z] Nailgun ssl cert verification

tests/foreman/ui/test_activationkey.py
Changes a few things here to unblock this test:
- sets `install_katello_agent` to false
- selects the default location, where hosts are being registered
- uses the read_legacy_ui, instead of read, since the test is referencing the old UI
=> Change read to read_legacy_ui

tests/foreman/ui/test_activationkey.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12844
Changes a few things here to unblock this test:
- sets `install_katello_agent` to false
- selects the default location, where hosts are being registered
- uses the read_legacy_ui, instead of read, since the test is referencing the old UI
=> [6.14.z] Change read to read_legacy_ui

tests/foreman/ui/test_activationkey.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12844
Changes a few things here to unblock this test:
- sets `install_katello_agent` to false
- selects the default location, where hosts are being registered
- uses the read_legacy_ui, instead of read, since the test is referencing the old UI
=> [6.13.z] Change read to read_legacy_ui

robottelo/hosts.py
Registering host using the LCE id fails with `Failed to generate registration command:  Error: Unrecognised option '--lifecycle_environment_id'. See: 'hammer host-registration generate-command --help'` because the dashes are used for hammer CLI options.
```
Usage:
hammer host-registration generate-command [OPTIONS]
Options:
...
--lifecycle-environment[-id] VALUE/NUMBER Lifecycle environment for the host.
```
=> Fix lce id option in host registration

tests/foreman/ui/test_http_proxy.py
This test was failing in stream due to not having an org and location selected.
=> Fixed test_positive_assign_http_proxy_to_products_repositories failure

tests/foreman/ui/test_host.py
~~Use all supported RHEL versions for global registration tests,
i.e., RHEL 7,8,9, including FIPS.~~
Update:
Move from RHEL 7 to RHEL 8 hosts for non-crucial global registration tests.
Also fixed a forgotten assert in `test_global_registration_token_restriction`.
=> Hosts: move from RHEL 7 to RHEL 8 for glob. registration

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12849
Registering host using the LCE id fails with `Failed to generate registration command:  Error: Unrecognised option '--lifecycle_environment_id'. See: 'hammer host-registration generate-command --help'` because the dashes are used for hammer CLI options.
```
Usage:
hammer host-registration generate-command [OPTIONS]
Options:
...
--lifecycle-environment[-id] VALUE/NUMBER Lifecycle environment for the host.
```
=> [6.13.z] Fix lce id option in host registration

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12849
Registering host using the LCE id fails with `Failed to generate registration command:  Error: Unrecognised option '--lifecycle_environment_id'. See: 'hammer host-registration generate-command --help'` because the dashes are used for hammer CLI options.
```
Usage:
hammer host-registration generate-command [OPTIONS]
Options:
...
--lifecycle-environment[-id] VALUE/NUMBER Lifecycle environment for the host.
```
=> [6.12.z] Fix lce id option in host registration

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12849
Registering host using the LCE id fails with `Failed to generate registration command:  Error: Unrecognised option '--lifecycle_environment_id'. See: 'hammer host-registration generate-command --help'` because the dashes are used for hammer CLI options.
```
Usage:
hammer host-registration generate-command [OPTIONS]
Options:
...
--lifecycle-environment[-id] VALUE/NUMBER Lifecycle environment for the host.
```
=> [6.14.z] Fix lce id option in host registration

tests/foreman/ui/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12850
This test was failing in stream due to not having an org and location selected.
=> [6.14.z] Fixed test_positive_assign_http_proxy_to_products_repositories failure

tests/foreman/ui/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12850
This test was failing in stream due to not having an org and location selected.
=> [6.13.z] Fixed test_positive_assign_http_proxy_to_products_repositories failure

tests/foreman/ui/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12850
This test was failing in stream due to not having an org and location selected.
=> [6.12.z] Fixed test_positive_assign_http_proxy_to_products_repositories failure

tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12810
~~Use all supported RHEL versions for global registration tests,
i.e., RHEL 7,8,9, including FIPS.~~
Update:
Move from RHEL 7 to RHEL 8 hosts for non-crucial global registration tests.
Also fixed a forgotten assert in `test_global_registration_token_restriction`.
=> [6.14.z] Hosts: move from RHEL 7 to RHEL 8 for glob. registration

tests/foreman/maintain/test_packages.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12691
I'm removing this stubbed case because the steps for updating satellite-maintain here are outdated. We now rely on satellite-maintain's ability to self-upgrade either by running a command like `satellite-maintain upgrade list-versions` which is being tested in https://github.com/SatelliteQE/robottelo/pull/12647 or by using `satellite-maintain self-upgrade`. Dev is planning to make some changes to these commands as well which will get there own automation when it's ready. For now we can just remove this outdated stubbed case.
=> [6.12.z] Remove stubbed FM case that is no longer needed

tests/foreman/maintain/test_packages.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12691
I'm removing this stubbed case because the steps for updating satellite-maintain here are outdated. We now rely on satellite-maintain's ability to self-upgrade either by running a command like `satellite-maintain upgrade list-versions` which is being tested in https://github.com/SatelliteQE/robottelo/pull/12647 or by using `satellite-maintain self-upgrade`. Dev is planning to make some changes to these commands as well which will get there own automation when it's ready. For now we can just remove this outdated stubbed case.
=> [6.14.z] Remove stubbed FM case that is no longer needed

tests/foreman/maintain/test_packages.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12691
I'm removing this stubbed case because the steps for updating satellite-maintain here are outdated. We now rely on satellite-maintain's ability to self-upgrade either by running a command like `satellite-maintain upgrade list-versions` which is being tested in https://github.com/SatelliteQE/robottelo/pull/12647 or by using `satellite-maintain self-upgrade`. Dev is planning to make some changes to these commands as well which will get there own automation when it's ready. For now we can just remove this outdated stubbed case.
=> [6.13.z] Remove stubbed FM case that is no longer needed

tests/foreman/virtwho/api/test_esx.py, tests/foreman/virtwho/api/test_esx_sca.py, tests/foreman/virtwho/api/test_hyperv.py, tests/foreman/virtwho/api/test_hyperv_sca.py, tests/foreman/virtwho/api/test_kubevirt.py, tests/foreman/virtwho/api/test_kubevirt_sca.py, tests/foreman/virtwho/api/test_libvirt.py, tests/foreman/virtwho/api/test_libvirt_sca.py, tests/foreman/virtwho/api/test_nutanix.py, tests/foreman/virtwho/api/test_nutanix_sca.py
Tasks:
depend on #12619 remove content for manifest
Cases PASS:
```
(robottelo_vv_311_master) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/api/test_esx**.py
tests/foreman/virtwho/api/test_esx.py ..........                                                                                                                                                            [ 43%]
tests/foreman/virtwho/api/test_esx_sca.py .............                                                                                                                                                     [100%]
=====================================================================23 passed, 23 deselected, 138 warnings in …
```
=> fixture support for virt-who config api : data_form deploy_type virtwho_config 

tests/upgrades/test_hostcontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12859
=> [6.12.z] update case component with correct name

tests/upgrades/test_hostcontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12859
=> [6.13.z] update case component with correct name

tests/upgrades/test_hostcontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12859
=> [6.14.z] update case component with correct name

tests/upgrades/test_hostcontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12859
=> [6.11.z] update case component with correct name

robottelo/utils/vault.py
This PR brings optional logging to the vault from pytest session requested by the community. 
- Multiple options to bypass vault login,  where pytest session won't insist on logging into Vault. :
- No `.env` file
- `VAULT_ENABLED_FOR_DYNACONF` option is set to `False` in `.env` file
- Commented out VAULT_ENABLED_FOR_DYNACONF` option in `.env` file
- No `VAULT_ENABLED_FOR_DYNACONF` option in `.env` file
- Also made some code nitpicking changes !
=> Optional pytest Vault login and code nitpicking

tests/foreman/virtwho/api/test_esx.py, tests/foreman/virtwho/api/test_esx_sca.py, tests/foreman/virtwho/api/test_hyperv.py, tests/foreman/virtwho/api/test_hyperv_sca.py, tests/foreman/virtwho/api/test_kubevirt.py, tests/foreman/virtwho/api/test_kubevirt_sca.py, tests/foreman/virtwho/api/test_libvirt.py, tests/foreman/virtwho/api/test_libvirt_sca.py, tests/foreman/virtwho/api/test_nutanix.py, tests/foreman/virtwho/api/test_nutanix_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12620
Tasks:
depend on #12619 remove content for manifest
Cases PASS:
```
(robottelo_vv_311_master) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/api/test_esx**.py
tests/foreman/virtwho/api/test_esx.py ..........                                                                                                                                                            [ 43%]
tests/foreman/virtwho/api/test_esx_sca.py .............                                                                                                                                                     [100%] …
```
=> [6.14.z] fixture support for virt-who config api : data_form deploy_type virtwho_config 

tests/foreman/destructive/test_capsule_loadbalancer.py
Modifying this test to focus more on the content host being able to get content even if the capsule it's registered to is down.
=> Fixing loadbalancer e2e test

tests/foreman/destructive/test_capsule_loadbalancer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12838
Modifying this test to focus more on the content host being able to get content even if the capsule it's registered to is down.
=> [6.14.z] Fixing loadbalancer e2e test

tests/foreman/destructive/test_capsule_loadbalancer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12838
Modifying this test to focus more on the content host being able to get content even if the capsule it's registered to is down.
=> [6.13.z] Fixing loadbalancer e2e test

tests/foreman/virtwho/ui/test_esx.py, tests/foreman/virtwho/ui/test_esx_sca.py, tests/foreman/virtwho/ui/test_hyperv.py, tests/foreman/virtwho/ui/test_hyperv_sca.py, tests/foreman/virtwho/ui/test_kubevirt.py, tests/foreman/virtwho/ui/test_kubevirt_sca.py, tests/foreman/virtwho/ui/test_libvirt.py, tests/foreman/virtwho/ui/test_libvirt_sca.py, tests/foreman/virtwho/ui/test_nutanix.py, tests/foreman/virtwho/ui/test_nutanix_sca.py
depend on https://github.com/SatelliteQE/robottelo/pull/12619 remove content for manifest
Cases PASS:
```
(robottlo_vv311) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_hyperv**.py --disable-pytest-warnings -q
......                                                                                                                                                                                                      [100%]
6 passed, 6 deselected, 14 warnings in 2253.83s (0:37:33)
(robottlo_vv311) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx**.py --disable-pytest-warnings -q
.................................. …
```
=> fixture support for virt-who config ui : data_form deploy_type virtwho_config

tests/foreman/virtwho/ui/test_esx.py, tests/foreman/virtwho/ui/test_esx_sca.py, tests/foreman/virtwho/ui/test_hyperv.py, tests/foreman/virtwho/ui/test_hyperv_sca.py, tests/foreman/virtwho/ui/test_kubevirt.py, tests/foreman/virtwho/ui/test_kubevirt_sca.py, tests/foreman/virtwho/ui/test_libvirt.py, tests/foreman/virtwho/ui/test_libvirt_sca.py, tests/foreman/virtwho/ui/test_nutanix.py, tests/foreman/virtwho/ui/test_nutanix_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12640
depend on https://github.com/SatelliteQE/robottelo/pull/12619 remove content for manifest
Cases PASS:
```
(robottlo_vv311) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_hyperv**.py --disable-pytest-warnings -q
......                                                                                                                                                                                                      [100%]
6 passed, 6 deselected, 14 warnings in 2253.83s (0:37:33)
(robottlo_vv311) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx**.py --disable-pytest-warnings -q …
```
=> [6.14.z] fixture support for virt-who config ui : data_form deploy_type virtwho_config

conftest.py, pytest_fixtures/component/discovery.py, tests/foreman/api/test_discoveredhost.py, tests/foreman/api/test_repositories.py
1. Adding coverage for the auto-provision and reboot API endpoints for a single host.
2. Adding coverage for the auto-provision of multiple discovered hosts.
=> Coverage for autoprovision and reboot of discovered host

conftest.py, pytest_fixtures/component/discovery.py, tests/foreman/api/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12815
1. Adding coverage for the auto-provision and reboot API endpoints for a single host.
2. Adding coverage for the auto-provision of multiple discovered hosts.
=> [6.13.z] Coverage for autoprovision and reboot of discovered host

conftest.py, pytest_fixtures/component/discovery.py, tests/foreman/api/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12815
1. Adding coverage for the auto-provision and reboot API endpoints for a single host.
2. Adding coverage for the auto-provision of multiple discovered hosts.
=> [6.12.z] Coverage for autoprovision and reboot of discovered host

robottelo/host_helpers/contenthost_mixins.py, tests/foreman/api/test_errata.py
Previous pr was merged just a bit before I could get this in. The old method works and passes, 
but should use `.register()` going forward with the removal of katello-agent.
=> Update to errata-stream fix, use up to date register method for rhel_contenthost

tests/upgrades/test_activation_key.py, tests/upgrades/test_repository.py
Scenario test to verify that large repositories can be synced without failure after an upgrade.
Test Steps:
1. Before Satellite upgrade.
2. Enable and sync large RH repository.
3. Upgrade Satellite.
4. Enable and sync a second large repository.
=> [Repository Rewrite] Upgrade test for large repo sync

tests/foreman/cli/test_repositories.py
SAT-13325
This test verifies that invalid repositories cannot be published to a Content View
:steps:
1. Create custom product and upload repository
2. Run Katello commands to make repository invalid
3. Create content view and add repository 
4. Verify Publish fails
=> [Repository Rewrite] Added test for publishing invalid repository

tests/foreman/ui/test_host.py, tests/foreman/ui/test_rhcloud_insights.py
Found this while discussing on https://github.com/SatelliteQE/robottelo/pull/12901#discussion_r1357977814
=> Fix typo for organization field in global registration

tests/foreman/ui/test_host.py, tests/foreman/ui/test_rhcloud_insights.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12902
Found this while discussing on https://github.com/SatelliteQE/robottelo/pull/12901#discussion_r1357977814
=> [6.14.z] Fix typo for organization field in global registration

tests/foreman/ui/test_host.py, tests/foreman/ui/test_rhcloud_insights.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12902
Found this while discussing on https://github.com/SatelliteQE/robottelo/pull/12901#discussion_r1357977814
=> [6.12.z] Fix typo for organization field in global registration

tests/foreman/ui/test_host.py, tests/foreman/ui/test_rhcloud_insights.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12902
Found this while discussing on https://github.com/SatelliteQE/robottelo/pull/12901#discussion_r1357977814
=> [6.13.z] Fix typo for organization field in global registration

.pre-commit-config.yaml
This will prevent secrets from being committed to the repository. Handling it in pre-commit because a check in actions is too late.
=> Add gitleaks to pre-commit hooks

robottelo/cli/sm_packages.py
Previous package install commands are setting the command_end to the name of the package. This is causing a failure in one of our install tests. This makes sure that the status command does not pass along any package names even after an install.
=> Fix packages status

robottelo/cli/sm_packages.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12845
Previous package install commands are setting the command_end to the name of the package. This is causing a failure in one of our install tests. This makes sure that the status command does not pass along any package names even after an install.
=> [6.12.z] Fix packages status

robottelo/cli/sm_packages.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12845
Previous package install commands are setting the command_end to the name of the package. This is causing a failure in one of our install tests. This makes sure that the status command does not pass along any package names even after an install.
=> [6.14.z] Fix packages status

tests/foreman/api/test_repositories.py
[SAT-13275]
Attempt to hit the /available_repositories endpoint with no failures
:Steps:
1. Enable a Red Hat Repository
2. Attempt to hit the enpoint:
GET /katello/api/repository_sets/:id/available_repositories
3. Verify Actions::Katello::RepositorySet::ScanCdn task is run
4. Verify there are no failures when scanning for repository
=> [Repository Rewrite] Adding test for available_repositories endpoint

robottelo/cli/sm_packages.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12845
Previous package install commands are setting the command_end to the name of the package. This is causing a failure in one of our install tests. This makes sure that the status command does not pass along any package names even after an install.
=> [6.13.z] Fix packages status

tests/foreman/api/test_discoveredhost.py, tests/foreman/cli/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12914
Attempting to increase the timeout for the `wait_for` function to overcome `wait_for.TimedOutError`
=> [6.14.z] Fixing Discovery tests

robottelo/cli/sm_packages.py
Jake's #12765 added caching mechanism to the Satellite's API and CLI property.
This means that any such class property is now persistent as it is being cached now.
Fixes this pattern in ` tests.foreman.maintain.test_packages.test_positive_fm_packages_install[satellite] `:
```
sat_maintain.cli.Packages.install(packages='zsh', options={'assumeyes': True})
sat_maintain.cli.Packages.status()
```
And **cli.Packages.status()** is failing with 
```
ERROR: too many arguments
See: 'satellite-maintain packages status --help'
```
The two CLI calls run these two commands:
```
executing command:  satellite-maintain packages install --assumeyes zsh
executing command:  satellite-maintain packages status  zsh
```
Note wrongly apended **zsh** ! All successive commands have now `zsh`  being appended - …
=> Fix maintain CLI caching class attributes

robottelo/cli/sm_packages.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12918
Jake's #12765 added caching mechanism to the Satellite's API and CLI property.
This means that any such class property is now persistent as it is being cached now.
Fixes this pattern in ` tests.foreman.maintain.test_packages.test_positive_fm_packages_install[satellite] `:
```
sat_maintain.cli.Packages.install(packages='zsh', options={'assumeyes': True})
sat_maintain.cli.Packages.status()
```
And **cli.Packages.status()** is failing with 
```
ERROR: too many arguments
See: 'satellite-maintain packages status --help'
```
The two CLI calls run these two commands:
```
executing command:  satellite-maintain packages install --assumeyes zsh
executing command:  satellite-maintain packages status  zsh
```
Note wrongly apended …
=> [6.13.z] Fix maintain CLI caching class attributes

robottelo/cli/sm_packages.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12918
Jake's #12765 added caching mechanism to the Satellite's API and CLI property.
This means that any such class property is now persistent as it is being cached now.
Fixes this pattern in ` tests.foreman.maintain.test_packages.test_positive_fm_packages_install[satellite] `:
```
sat_maintain.cli.Packages.install(packages='zsh', options={'assumeyes': True})
sat_maintain.cli.Packages.status()
```
And **cli.Packages.status()** is failing with 
```
ERROR: too many arguments
See: 'satellite-maintain packages status --help'
```
The two CLI calls run these two commands:
```
executing command:  satellite-maintain packages install --assumeyes zsh
executing command:  satellite-maintain packages status  zsh
```
Note wrongly apended …
=> [6.14.z] Fix maintain CLI caching class attributes

robottelo/cli/sm_packages.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12918
Jake's #12765 added caching mechanism to the Satellite's API and CLI property.
This means that any such class property is now persistent as it is being cached now.
Fixes this pattern in ` tests.foreman.maintain.test_packages.test_positive_fm_packages_install[satellite] `:
```
sat_maintain.cli.Packages.install(packages='zsh', options={'assumeyes': True})
sat_maintain.cli.Packages.status()
```
And **cli.Packages.status()** is failing with 
```
ERROR: too many arguments
See: 'satellite-maintain packages status --help'
```
The two CLI calls run these two commands:
```
executing command:  satellite-maintain packages install --assumeyes zsh
executing command:  satellite-maintain packages status  zsh
```
Note wrongly apended …
=> [6.12.z] Fix maintain CLI caching class attributes

robottelo/utils/vault.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12822
This PR brings optional logging to the vault from pytest session requested by the community. 
- Multiple options to bypass vault login,  where pytest session won't insist on logging into Vault. :
- No `.env` file
- `VAULT_ENABLED_FOR_DYNACONF` option is set to `False` in `.env` file
- Commented out VAULT_ENABLED_FOR_DYNACONF` option in `.env` file
- No `VAULT_ENABLED_FOR_DYNACONF` option in `.env` file
- Also made some code nitpicking changes !
=> [6.14.z] Optional pytest Vault login and code nitpicking

pytest_fixtures/component/repository.py, robottelo/host_helpers/repository_mixins.py, robottelo/hosts.py, testimony.yaml, tests/foreman/api/test_errata.py, tests/foreman/cli/test_host.py, tests/foreman/cli/test_reporttemplates.py, tests/foreman/cli/test_vm_install_products_package.py, tests/foreman/destructive/test_contenthost.py, tests/foreman/ui/test_activationkey.py, tests/foreman/ui/test_contenthost.py, tests/foreman/ui/test_dashboard.py, tests/foreman/ui/test_errata.py, tests/foreman/ui/test_host.py, tests/foreman/ui/test_hostcollection.py, tests/foreman/ui/test_subscription.py
Katello agent was deprecated and is being removed from 6.15, the functionality will be replaced by REX.
This PR removes the references from helpers, mixins and tests from where they were used.
=> Remove katello-agent from helpers and mixins

tests/foreman/virtwho/ui/test_esx.py, tests/foreman/virtwho/ui/test_esx_sca.py, tests/foreman/virtwho/ui/test_hyperv.py, tests/foreman/virtwho/ui/test_hyperv_sca.py, tests/foreman/virtwho/ui/test_kubevirt.py, tests/foreman/virtwho/ui/test_kubevirt_sca.py, tests/foreman/virtwho/ui/test_libvirt.py, tests/foreman/virtwho/ui/test_libvirt_sca.py, tests/foreman/virtwho/ui/test_nutanix.py, tests/foreman/virtwho/ui/test_nutanix_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12640
depend on https://github.com/SatelliteQE/robottelo/pull/12619 remove content for manifest
Cases PASS:
```
(robottlo_vv311) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_hyperv**.py --disable-pytest-warnings -q
......                                                                                                                                                                                                      [100%]
6 passed, 6 deselected, 14 warnings in 2253.83s (0:37:33)
(robottlo_vv311) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx**.py --disable-pytest-warnings -q …
```
=> [6.13.z] fixture support for virt-who config ui : data_form deploy_type virtwho_config

pytest_fixtures/component/taxonomy.py, robottelo/constants/__init__.py, tests/foreman/ui/test_acs.py
In this PR I have implemented two tests. One end-to-end UI test tests the creation of some ACS types and actions on them and the second one tests the creation of all possible ACS types.
=> Alternate Content Source UI tests

pytest_fixtures/component/taxonomy.py, robottelo/constants/__init__.py, tests/foreman/ui/test_acs.py
=> [6.14.z] Acs test coverage

robottelo/utils/vault.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12822
This PR brings optional logging to the vault from pytest session requested by the community. 
- Multiple options to bypass vault login,  where pytest session won't insist on logging into Vault. :
- No `.env` file
- `VAULT_ENABLED_FOR_DYNACONF` option is set to `False` in `.env` file
- Commented out VAULT_ENABLED_FOR_DYNACONF` option in `.env` file
- No `VAULT_ENABLED_FOR_DYNACONF` option in `.env` file
- Also made some code nitpicking changes !
=> [6.13.z] Optional pytest Vault login and code nitpicking

robottelo/utils/vault.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12822
This PR brings optional logging to the vault from pytest session requested by the community. 
- Multiple options to bypass vault login,  where pytest session won't insist on logging into Vault. :
- No `.env` file
- `VAULT_ENABLED_FOR_DYNACONF` option is set to `False` in `.env` file
- Commented out VAULT_ENABLED_FOR_DYNACONF` option in `.env` file
- No `VAULT_ENABLED_FOR_DYNACONF` option in `.env` file
- Also made some code nitpicking changes !
=> [6.12.z] Optional pytest Vault login and code nitpicking

pytest_plugins/auto_vault.py, robottelo/utils/vault.py
Missing `Capture Output` made `make vault scripts` to break as it was trying to read and print STDOUT which was never returned due to `capture_output` was not set.
Fix:
- Set `capture_output` to True in subprocess running vault command.
- Alter logging of some events to appropriate level.
This also addresses the REGEX for Vault_enablement key in `.env` when its the first line in `.env` file.
=> Fix vault makescripts with capture output

pytest_plugins/auto_vault.py, robottelo/utils/vault.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12909
Missing `Capture Output` made `make vault scripts` to break as it was trying to read and print STDOUT which was never returned due to `capture_output` was not set.
Fix:
- Set `capture_output` to True in subprocess running vault command.
- Alter logging of some events to appropriate level.
This also addresses the REGEX for Vault_enablement key in `.env` when its the first line in `.env` file.
=> [6.14.z] Fix vault makescripts with capture output

pytest_plugins/auto_vault.py, robottelo/utils/vault.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12909
Missing `Capture Output` made `make vault scripts` to break as it was trying to read and print STDOUT which was never returned due to `capture_output` was not set.
Fix:
- Set `capture_output` to True in subprocess running vault command.
- Alter logging of some events to appropriate level.
This also addresses the REGEX for Vault_enablement key in `.env` when its the first line in `.env` file.
=> [6.12.z] Fix vault makescripts with capture output

pytest_plugins/auto_vault.py, robottelo/utils/vault.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12909
Missing `Capture Output` made `make vault scripts` to break as it was trying to read and print STDOUT which was never returned due to `capture_output` was not set.
Fix:
- Set `capture_output` to True in subprocess running vault command.
- Alter logging of some events to appropriate level.
This also addresses the REGEX for Vault_enablement key in `.env` when its the first line in `.env` file.
=> [6.13.z] Fix vault makescripts with capture output

pytest_plugins/fixture_collection.py
The processing of the list of fixtures in the command line for in Pytest Plugin `Fixture Collection` is restructured.
Earlier:
```
```
Now:
```
```
Issue and Fix:
---------------
Earlier pytest is used to process all the non specific arguments after `--uses-fixtures` option , e.g in example above it used to consider `tests/foreman` as fixture as well :)
Now, it process only a string after an option and splits string by comma to obtain the list of fixtures to collect the tests for all those fixtures.
=> Fixture collection splitting restructured

pytest_plugins/fixture_collection.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12923
The processing of the list of fixtures in the command line for in Pytest Plugin `Fixture Collection` is restructured.
Earlier:
```
```
Now:
```
```
Issue and Fix:
---------------
Earlier pytest is used to process all the non specific arguments after `--uses-fixtures` option , e.g in example above it used to consider `tests/foreman` as fixture as well :)
Now, it process only a string after an option and splits string by comma to obtain the list of fixtures to collect the tests for all those fixtures.
=> [6.13.z] Fixture collection splitting restructured

pytest_plugins/fixture_collection.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12923
The processing of the list of fixtures in the command line for in Pytest Plugin `Fixture Collection` is restructured.
Earlier:
```
```
Now:
```
```
Issue and Fix:
---------------
Earlier pytest is used to process all the non specific arguments after `--uses-fixtures` option , e.g in example above it used to consider `tests/foreman` as fixture as well :)
Now, it process only a string after an option and splits string by comma to obtain the list of fixtures to collect the tests for all those fixtures.
=> [6.12.z] Fixture collection splitting restructured

pytest_fixtures/component/domain.py, tests/upgrades/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12897
null
=> [6.14.z] [Upgrades] Add upgrade tests for ProvisioningTemplates

tests/foreman/maintain/test_backup_restore.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12974
The feature of Snapshot Backup and Restore is going to be removed.
No need to implement the stub anymore
=> [6.13.z] Remove test_positive_backup_restore_snapshot stub

tests/foreman/maintain/test_backup_restore.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12974
The feature of Snapshot Backup and Restore is going to be removed.
No need to implement the stub anymore
=> [6.12.z] Remove test_positive_backup_restore_snapshot stub

tests/foreman/maintain/test_backup_restore.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12974
The feature of Snapshot Backup and Restore is going to be removed.
No need to implement the stub anymore
=> [6.14.z] Remove test_positive_backup_restore_snapshot stub

tests/foreman/ui/test_computeresource_libvirt.py
Add workaround for cpu_mode when BZ:2236693 is open for EL9 Libvirt tests, missed updating UI tests in https://github.com/SatelliteQE/robottelo/pull/12973
=> Add workaround for cpu_mode for EL9 Libvirt UI tests

tests/foreman/cli/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12973
Add workaround for cpu_mode when BZ:2236693 is open for EL9 Libvirt tests
=> [6.12.z] Add workaround for cpu_mode for EL9 Libvirt tests

tests/foreman/api/test_capsulecontent.py
Closeloop around Bug #2154734 - openstack repos unable to sync on capsule
Added test case in `tests/foreman/api/test_capsulecontent.py` will create & sync rh openstack container repos on satellite and capsule
N/A
=> sync RHOSP repos to capsule

tests/foreman/destructive/test_packages.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12342
Automate [BZ 2073535](https://bugzilla.redhat.com/show_bug.cgi?id=2073535) (`satellite-maintain packages check-update fails when there are no packages to be updated`).
=> [6.14.z] Update `test_positive_all_packages_update`

tests/foreman/destructive/test_packages.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12342
Automate [BZ 2073535](https://bugzilla.redhat.com/show_bug.cgi?id=2073535) (`satellite-maintain packages check-update fails when there are no packages to be updated`).
=> [6.13.z] Update `test_positive_all_packages_update`

pytest_fixtures/component/provision_pxe.py, tests/foreman/api/test_discoveredhost.py, tests/foreman/api/test_discoveryrule.py
Coverage for :
```
test_positive_reboot_all_pxe_hosts
test_positive_end_to_end_crud
test_positive_provision_with_rule_priority
test_positive_multi_provision_with_rule_limit
```
The `reboot_all `scenario is expected to be breaking due to a known issue which will be worked on.
=> Discovery coverage for rule priority/limit/provisioning

tests/foreman/api/test_registration.py
Remove skip marker from test test_positive_allow_reregistration_when_dmi_uuid_changed on api/registration.py as the BZ#2229112 is no longer reproducible
=> Remove skip marker from test

tests/foreman/api/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12990
Closeloop around Bug #2154734 - openstack repos unable to sync on capsule
Added test case in `tests/foreman/api/test_capsulecontent.py` will create & sync rh openstack container repos on satellite and capsule
N/A
=> [6.13.z] sync RHOSP repos to capsule

tests/foreman/api/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12990
Closeloop around Bug #2154734 - openstack repos unable to sync on capsule
Added test case in `tests/foreman/api/test_capsulecontent.py` will create & sync rh openstack container repos on satellite and capsule
N/A
=> [6.14.z] sync RHOSP repos to capsule

pytest_fixtures/component/provision_pxe.py, tests/foreman/api/test_discoveredhost.py, tests/foreman/api/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12962
Coverage for :
```
test_positive_reboot_all_pxe_hosts
test_positive_end_to_end_crud
test_positive_provision_with_rule_priority
test_positive_multi_provision_with_rule_limit
```
The `reboot_all `scenario is expected to be breaking due to a known issue which will be worked on.
=> [6.14.z] Discovery coverage for rule priority/limit/provisioning

pytest_fixtures/component/provision_pxe.py, tests/foreman/api/test_discoveredhost.py, tests/foreman/api/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12962
Coverage for :
```
test_positive_reboot_all_pxe_hosts
test_positive_end_to_end_crud
test_positive_provision_with_rule_priority
test_positive_multi_provision_with_rule_limit
```
The `reboot_all `scenario is expected to be breaking due to a known issue which will be worked on.
=> [6.13.z] Discovery coverage for rule priority/limit/provisioning

tests/foreman/api/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13005
Remove skip marker from test test_positive_allow_reregistration_when_dmi_uuid_changed on api/registration.py as the BZ#2229112 is no longer reproducible
=> [6.13.z] Remove skip marker from test

tests/foreman/api/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13005
Remove skip marker from test test_positive_allow_reregistration_when_dmi_uuid_changed on api/registration.py as the BZ#2229112 is no longer reproducible
=> [6.14.z] Remove skip marker from test

tests/foreman/cli/test_satellitesync.py
Based on #12347.
1. Extended `test_positive_import_content_for_disconnected_sat_with_existing_content` by assertion for correct error message when non-import-only CV is used for import
2. Removed `_import_entities`
3. Added test for customer scenarios:
~`test_postive_export_import_cv_with_long_name`~
`test_positive_export_rerun_failed_import`
`test_postive_export_import_repo_with_GPG`
=> ISS refactor - batch 3

tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12651
Based on #12347.
1. Extended `test_positive_import_content_for_disconnected_sat_with_existing_content` by assertion for correct error message when non-import-only CV is used for import
2. Removed `_import_entities`
3. Added test for customer scenarios:
~`test_postive_export_import_cv_with_long_name`~
`test_positive_export_rerun_failed_import`
`test_postive_export_import_repo_with_GPG`
=> [6.14.z] ISS refactor - batch 3

tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12651
Based on #12347.
1. Extended `test_positive_import_content_for_disconnected_sat_with_existing_content` by assertion for correct error message when non-import-only CV is used for import
2. Removed `_import_entities`
3. Added test for customer scenarios:
~`test_postive_export_import_cv_with_long_name`~
`test_positive_export_rerun_failed_import`
`test_postive_export_import_repo_with_GPG`
=> [6.13.z] ISS refactor - batch 3

tests/foreman/api/test_convert2rhel.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10840
Fixed Convert2RHEL test failures.
=> [6.13.z] Convert2Rhel test fixes

robottelo/host_helpers/satellite_mixins.py, tests/foreman/cli/test_satellitesync.py
1. Automated test case for incremental export and import of a yum repo (non-RH).
2. Extended test case of mixed content CV export, repos of all types moved to fixtures and rescoped to function.
3. Minor fixes like CVV sorting issue and clean up on `move_pulp_archive`.
=> ISS refactor - batch 4

tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13017
1. Automated test case for incremental export and import of a yum repo (non-RH).
2. Extended test case of mixed content CV export, repos of all types moved to fixtures and rescoped to function.
3. Minor fixes like CVV sorting issue and clean up on `move_pulp_archive`.
=> [6.14.z] ISS refactor - batch 4

tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13017
1. Automated test case for incremental export and import of a yum repo (non-RH).
2. Extended test case of mixed content CV export, repos of all types moved to fixtures and rescoped to function.
3. Minor fixes like CVV sorting issue and clean up on `move_pulp_archive`.
=> [6.13.z] ISS refactor - batch 4

tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13017
1. Automated test case for incremental export and import of a yum repo (non-RH).
2. Extended test case of mixed content CV export, repos of all types moved to fixtures and rescoped to function.
3. Minor fixes like CVV sorting issue and clean up on `move_pulp_archive`.
=> [6.12.z] ISS refactor - batch 4

tests/foreman/data/hammer_commands.json
added to 6.13.5 in https://bugzilla.redhat.com/show_bug.cgi?id=2238361
=> added custom-cdn-auth-enabled hammer option

robottelo/utils/vault.py
Currently this throws an error in teardown if `VAULT_ADDR` is not set.
=> Check if VAULT_ADDR env var exists before deleting it

.github/workflows/auto_cherry_pick.yml
Moving away from github action to standard curl for handing the PRT comment
=> PRT comment adding using curl more standard way

robottelo/utils/vault.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13016
Currently this throws an error in teardown if `VAULT_ADDR` is not set.
=> [6.12.z] Check if VAULT_ADDR env var exists before deleting it

robottelo/utils/vault.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13016
Currently this throws an error in teardown if `VAULT_ADDR` is not set.
=> [6.13.z] Check if VAULT_ADDR env var exists before deleting it

robottelo/utils/vault.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13016
Currently this throws an error in teardown if `VAULT_ADDR` is not set.
=> [6.14.z] Check if VAULT_ADDR env var exists before deleting it

conf/docker.yaml.template
Updating the image registry configuration details in the docker config template. These details will be necessary for communicating with hub using the image registry proxy. In the CI, we have raised the `MR-1140` that contains all the required information.
=> Adding the image config details in the docker config

conf/docker.yaml.template
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12958
Updating the image registry configuration details in the docker config template. These details will be necessary for communicating with hub using the image registry proxy. In the CI, we have raised the `MR-1140` that contains all the required information.
=> [6.13.z] Adding the image config details in the docker config

conf/docker.yaml.template
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12958
Updating the image registry configuration details in the docker config template. These details will be necessary for communicating with hub using the image registry proxy. In the CI, we have raised the `MR-1140` that contains all the required information.
=> [6.14.z] Adding the image config details in the docker config

conf/docker.yaml.template
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12958
Updating the image registry configuration details in the docker config template. These details will be necessary for communicating with hub using the image registry proxy. In the CI, we have raised the `MR-1140` that contains all the required information.
=> [6.12.z] Adding the image config details in the docker config

tests/foreman/api/test_convert2rhel.py
1. For fetching latest CVV from CV we use index -1, and CVV list isn't sorted every time, so in such case, it tries to promote the older CVV which is already promoted  and fails to promote again with below error.
```
2023-10-21 03:22:56 - nailgun.client - WARNING - Received HTTP 400 response: {"displayMessage":"Cannot promote environment out of sequence. Use force to bypass restriction.","errors":["Cannot promote environment out of sequence. Use force to bypass restriction."]}
```
2.  <del> Add workaround for CentOS 8 to fetch archived contents from new vault mirror, as its EOL in end of 2021 and existing mirror contents are now moved to vault mirror.</del>
3. <del>Use --releasever=8.4.2105 when updating packages using yum to avoid upgrading to latest CentOS 8.5, which …
=> Fix convert2rhel tests by CVV sort and other fixes

robottelo/cli/factory.py, robottelo/host_helpers/cli_factory.py, tests/foreman/ui/test_errata.py
Refactor errata e2e with updated standards, contenthost through Global Registration, enable repositories with subscription manager. 
Remove `setting_update` of remote_execution_by_default:True ([BZ 2029192](https://bugzilla.redhat.com/show_bug.cgi?id=2029192)), this user setting has 
been removed for 6.15.0, and by default is set to True.
Used `request.addfinalizer` for cleanup of entities modified in the new fixture `registered_contenthost`, to prevent conflicts between parameterized runs.
~Depends on navigation fix in [airgun 1018](https://github.com/SatelliteQE/airgun/pull/1018).~ Merged
=> Stream fix errata:UI (test_end_to_end)

tests/foreman/ui/test_settings.py
Add QE test coverage for new setting display_fqdn_for_hosts, which is renamed from append_domain_name_for_hosts
pytest: tests/foreman/ui/test_settings.py -k test_positive_setting_display_fqdn_for_hosts
=> [6.15] Add test coverage for setting display_fqdn_for_hosts

tests/foreman/api/test_webhook.py
Webhook trigger is blocked by the safemode setting enabled, which is expected as the safemode prevents template rendering which is prerequisite for webhook trigger. 
The existing test didn't see this as it was looking just for one specific line in logs, so it passed even though no action was triggered.
This PR disables the safemode setting for the test so that the task is actually triggers. Also it adds a check for the successful completion of the triggered task.
=> improved webhook event trigger test

Dockerfile
Using the latest Fedora 39 image with Python 3.12 as the default version is causing failures in building the SSH2 Python library, leading to an unsuccessful build of Robottelo.
Pin the Dockerfile version for Robottelo to Fedora 38, which uses Python 3.11, to resolve compatibility issues and enable a successful build.
=> updating the fedora image to 38 as latest using python 3.12

Dockerfile
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13070
Using the latest Fedora 39 image with Python 3.12 as the default version is causing failures in building the SSH2 Python library, leading to an unsuccessful build of Robottelo.
Pin the Dockerfile version for Robottelo to Fedora 38, which uses Python 3.11, to resolve compatibility issues and enable a successful build.
=> [6.14.z] updating the fedora image to 38 as latest using python 3.12

Dockerfile
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13070
Using the latest Fedora 39 image with Python 3.12 as the default version is causing failures in building the SSH2 Python library, leading to an unsuccessful build of Robottelo.
Pin the Dockerfile version for Robottelo to Fedora 38, which uses Python 3.11, to resolve compatibility issues and enable a successful build.
=> [6.13.z] updating the fedora image to 38 as latest using python 3.12

Dockerfile
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13070
Using the latest Fedora 39 image with Python 3.12 as the default version is causing failures in building the SSH2 Python library, leading to an unsuccessful build of Robottelo.
Pin the Dockerfile version for Robottelo to Fedora 38, which uses Python 3.11, to resolve compatibility issues and enable a successful build.
=> [6.12.z] updating the fedora image to 38 as latest using python 3.12

tests/foreman/api/test_webhook.py
manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13048 closes https://github.com/SatelliteQE/robottelo/issues/13071
=> [6.14] improved webhook event trigger test

robottelo/utils/shared_resource.py, scripts/config_helpers.py, tests/robottelo/test_shared_resource.py
This class will be used to manage shared resources between multitple processes or threads. The most common case will likely be a shared upgrade satellite between multiple xdist workers.
I also handled an issues I encountered with the config_helpers script.
=> Add SharedResource class to robottelo.utils

requirements.txt, robottelo/constants/__init__.py, robottelo/host_helpers/repository_mixins.py, tests/foreman/api/test_capsulecontent.py
Satellite 6.15 will introduce new a feature to provide content counts synced to a Capsule and it needs to be tested.
This PR adds test cases to verify capsule content counts via API for unfiltered and filtered mixed-content CVs and a few additions to support it.
=> Add API tests for capsule content counts

robottelo/utils/shared_resource.py, scripts/config_helpers.py, tests/robottelo/test_shared_resource.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12341
This class will be used to manage shared resources between multitple processes or threads. The most common case will likely be a shared upgrade satellite between multiple xdist workers.
I also handled an issues I encountered with the config_helpers script.
=> [6.12.z] Add SharedResource class to robottelo.utils

robottelo/utils/shared_resource.py, scripts/config_helpers.py, tests/robottelo/test_shared_resource.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12341
This class will be used to manage shared resources between multitple processes or threads. The most common case will likely be a shared upgrade satellite between multiple xdist workers.
I also handled an issues I encountered with the config_helpers script.
=> [6.13.z] Add SharedResource class to robottelo.utils

robottelo/utils/shared_resource.py, scripts/config_helpers.py, tests/robottelo/test_shared_resource.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12341
This class will be used to manage shared resources between multitple processes or threads. The most common case will likely be a shared upgrade satellite between multiple xdist workers.
I also handled an issues I encountered with the config_helpers script.
=> [6.14.z] Add SharedResource class to robottelo.utils

conf/broker.yaml.template, robottelo/config/__init__.py
This is something that broker handles on its own and, due to import timing, isn't handled correctly in robottelo anyway. Removing the field and config mechanism should eliminate confusion around this behavior.
=> Remove BROKER_DIRECTORY from robottelo config

robottelo/hosts.py
Satellite._swap_nailgun("x.y.z") can be used to change out the operating version of nailgun.
This actually changes out the installed version of nailgun on the fly, so this should **only** be used in upgrades.
=> Add a mechanism to swap nailgun versions on demand

conf/broker.yaml.template, robottelo/config/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13027
This is something that broker handles on its own and, due to import timing, isn't handled correctly in robottelo anyway. Removing the field and config mechanism should eliminate confusion around this behavior.
=> [6.14.z] Remove BROKER_DIRECTORY from robottelo config

conf/broker.yaml.template, robottelo/config/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13027
This is something that broker handles on its own and, due to import timing, isn't handled correctly in robottelo anyway. Removing the field and config mechanism should eliminate confusion around this behavior.
=> [6.13.z] Remove BROKER_DIRECTORY from robottelo config

conf/broker.yaml.template, robottelo/config/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13027
This is something that broker handles on its own and, due to import timing, isn't handled correctly in robottelo anyway. Removing the field and config mechanism should eliminate confusion around this behavior.
=> [6.12.z] Remove BROKER_DIRECTORY from robottelo config

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12840
Satellite._swap_nailgun("x.y.z") can be used to change out the operating version of nailgun.
This actually changes out the installed version of nailgun on the fly, so this should **only** be used in upgrades.
=> [6.12.z] Add a mechanism to swap nailgun versions on demand

robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12840
Satellite._swap_nailgun("x.y.z") can be used to change out the operating version of nailgun.
This actually changes out the installed version of nailgun on the fly, so this should **only** be used in upgrades.
=> [6.13.z] Add a mechanism to swap nailgun versions on demand

requirements-optional.txt
(cherry picked from commit a044fd2b78516c1adb24709807b1d002873ec00c)
cherry-pick of #12910
=> [6.12.z] Bump pre-commit from 3.4.0 to 3.5.0 (#12910)

tests/foreman/api/test_discoveredhost.py
`test_positive_reboot_all_pxe_hosts` is failing due to ` fixture 'count' not found`
Removing `count`
=> Test fix for discovery reboot_all scenario

tests/foreman/api/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13102
`test_positive_reboot_all_pxe_hosts` is failing due to ` fixture 'count' not found`
Removing `count`
=> [6.14.z] Test fix for discovery reboot_all scenario

tests/foreman/api/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13102
`test_positive_reboot_all_pxe_hosts` is failing due to ` fixture 'count' not found`
Removing `count`
=> [6.13.z] Test fix for discovery reboot_all scenario

tests/foreman/api/test_http_proxy.py
This test already passes locally, but fails for the `auth` and `unauth-proxy` parameters in CI. 
`HTTPError 500: Internal Server Error: {"displayMessage":"Task {taks_id}: RuntimeError: The repository's publication is missing. Please run a 'complete sync' on repo_name."`
There seems to be a delay after create(), where the Metadata Generate tasks is still in progress when calling repo.update(). To resolve I have the repos wait for a sync before continuing, which in theory would wait for any in-progress metadata task.
=> Stream fix for e2e api http_proxy failure

tests/foreman/api/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13064
This test already passes locally, but fails for the `auth` and `unauth-proxy` parameters in CI. 
`HTTPError 500: Internal Server Error: {"displayMessage":"Task {taks_id}: RuntimeError: The repository's publication is missing. Please run a 'complete sync' on repo_name."`
There seems to be a delay after create(), where the Metadata Generate tasks is still in progress when calling repo.update(). To resolve I have the repos wait for a sync before continuing, which in theory would wait for any in-progress metadata task.
=> [6.13.z] Stream fix for e2e api http_proxy failure

pytest_fixtures/component/repository.py, tests/foreman/cli/test_contentaccess.py
_Hosts-Content component -> CLI tests_ were failing with  `AttributeError` because of fixture `module_gt_manifest_org` which is being used inside moduled scoped fixture `rh_repo_gt_manifest` of [repository.py](https://github.com/SatelliteQE/robottelo/blob/master/pytest_fixtures/component/repository.py#L36)
> 	`failed on setup with "AttributeError: '_io.BytesIO' object has no attribute 'filename'"`
The fixture `rh_repo_gt_manifest` simply creates new org with GT menifest, create rhst repo, sync and return the respective repo. Rest of fixtures from test module uses `module_sca_manifest_org` which creates module org with menifest.
The above setup were problematic.
Collect scattered fixtures into single module scoped fixture and use it.
No
=> use one fixture instead of multiple and remove problematic one

pytest_fixtures/component/repository.py, tests/foreman/cli/test_contentaccess.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13107
_Hosts-Content component -> CLI tests_ were failing with  `AttributeError` because of fixture `module_gt_manifest_org` which is being used inside moduled scoped fixture `rh_repo_gt_manifest` of [repository.py](https://github.com/SatelliteQE/robottelo/blob/master/pytest_fixtures/component/repository.py#L36)
> 	`failed on setup with "AttributeError: '_io.BytesIO' object has no attribute 'filename'"`
The fixture `rh_repo_gt_manifest` simply creates new org with GT menifest, create rhst repo, sync and return the respective repo. Rest of fixtures from test module uses `module_sca_manifest_org` which creates module org with menifest.
The above setup were problematic.
Collect scattered fixtures into single module scoped …
=> [6.14.z] use one fixture instead of multiple and remove problematic one

pytest_fixtures/component/repository.py, tests/foreman/cli/test_contentaccess.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13107
_Hosts-Content component -> CLI tests_ were failing with  `AttributeError` because of fixture `module_gt_manifest_org` which is being used inside moduled scoped fixture `rh_repo_gt_manifest` of [repository.py](https://github.com/SatelliteQE/robottelo/blob/master/pytest_fixtures/component/repository.py#L36)
> 	`failed on setup with "AttributeError: '_io.BytesIO' object has no attribute 'filename'"`
The fixture `rh_repo_gt_manifest` simply creates new org with GT menifest, create rhst repo, sync and return the respective repo. Rest of fixtures from test module uses `module_sca_manifest_org` which creates module org with menifest.
The above setup were problematic.
Collect scattered fixtures into single module scoped …
=> [6.13.z] use one fixture instead of multiple and remove problematic one

pytest_fixtures/component/provision_pxe.py, tests/foreman/api/test_provisioning.py
Adding UEFI HTTP Boot provisioning test. The test will be skipped till the BZ#2242925 is fixed
=> Add UEFI HTTP Boot provisioning test

pytest_fixtures/component/provision_pxe.py, tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12908
Adding UEFI HTTP Boot provisioning test. The test will be skipped till the BZ#2242925 is fixed
=> [6.14.z] Add UEFI HTTP Boot provisioning test

pytest_fixtures/component/discovery.py, tests/foreman/ui/test_discoveredhost.py
Adding UI coverage for Discovery provisioning scenarios.
=> Discovery Provisioning UI coverage

tests/foreman/installer/test_installer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12961
Applying changes from Component evaluation
- added _pit_ marker for Satellite and Capsule installation tests
- added various log checks (and removed stubbed tescases)
- removed redundant assertions
=> [6.14.z] satellite and capsule installation improvements

tests/foreman/cli/test_host.py
* #12796 changed the behavior of `setup_custom_repo` that breaks the tests that depend on it. The fixture has to return/yield `details` always
* since https://bugzilla.redhat.com/show_bug.cgi?id=2159974 is fixed, we should not need to check for SCA eligibility
* yield `details`
* remove SCA eligibility check
=> Yield details always, no need to check for SCA eligibility

robottelo/constants/__init__.py, robottelo/host_helpers/repository_mixins.py
Missing Debian repository abstraction for running robottelo tests on orcharhino.
Add abstraction for debian repository
=> Add abstraction for debian repo

pytest_fixtures/component/activationkey.py, tests/foreman/api/test_registration.py, tests/foreman/ui/test_host.py
This PR is Part-2 of Component Audit and it will have following test case additions:
1. test_positive_update_packages_post_registration
2. test_positive_host_registration_with_non_admin_user
=> Component Audit Part-2

tests/foreman/destructive/test_installer.py
Since rh cloud plugin is installed by default (Satellite 6.8) the test does not do what was intended. Original purpose was to change plugin state from disabled to enabled, but it won't change because it's already installed.
=> remove test_installer_inventory_plugin_update

pytest_fixtures/core/sat_cap_factory.py, robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13152
Some of our deployments have hardcoded deploy arguments. These should come from the config.
Take the deployment arguments from the config.
=> [6.12.z] Parametrize Satellite and Capsule deployments

pytest_fixtures/core/sat_cap_factory.py, robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13152
Some of our deployments have hardcoded deploy arguments. These should come from the config.
Take the deployment arguments from the config.
=> [6.14.z] Parametrize Satellite and Capsule deployments

pytest_fixtures/core/sat_cap_factory.py, robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13152
Some of our deployments have hardcoded deploy arguments. These should come from the config.
Take the deployment arguments from the config.
=> [6.13.z] Parametrize Satellite and Capsule deployments

tests/foreman/destructive/test_installer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13148
Since rh cloud plugin is installed by default (Satellite 6.8) the test does not do what was intended. Original purpose was to change plugin state from disabled to enabled, but it won't change because it's already installed.
=> [6.14.z] remove test_installer_inventory_plugin_update

pytest_fixtures/component/discovery.py, tests/foreman/ui/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12991
Adding UI coverage for Discovery provisioning scenarios.
=> [6.14.z] Discovery Provisioning UI coverage

pytest_fixtures/component/provision_pxe.py, tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12908
Adding UEFI HTTP Boot provisioning test. The test will be skipped till the BZ#2242925 is fixed
=> [6.13.z] Add UEFI HTTP Boot provisioning test

pytest_fixtures/component/activationkey.py, tests/foreman/api/test_registration.py, tests/foreman/ui/test_host.py
(cherry picked from commit 2e46f7e24ce7e97499a8e8064a556ee940ca9e3d)
Fixes https://github.com/SatelliteQE/robottelo/issues/13150
=> [6.14.z] Component Audit Part-2

tests/foreman/api/test_provisioningtemplate.py
Recent stream introduced change in vlan interface notation in https://github.com/theforeman/foreman/pull/9700
Update vlan paramater template test for this notation
=> Update vlan paramater template test for BZ:2075358

pytest_plugins/fspath_plugins.py, pytest_plugins/issue_handlers.py, scripts/fixture_cli.py
This change adds a new fixture_cli.py script under the scripts directory.
The basic usage of this script is to take in a space-separated list of global fixtures and run them together in a single temporary test.
e.g. python scripts/fixture_cli.py module_ak_with_synced_repo module_lce
Additionally, I had to make some minor adjustments to a couple of plugins since this temporary test doesn't follow the same rules as the rest of our framework.
=> Add basic fixture cli

pytest_plugins/fspath_plugins.py, pytest_plugins/issue_handlers.py, scripts/fixture_cli.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13101
This change adds a new fixture_cli.py script under the scripts directory.
The basic usage of this script is to take in a space-separated list of global fixtures and run them together in a single temporary test.
e.g. python scripts/fixture_cli.py module_ak_with_synced_repo module_lce
Additionally, I had to make some minor adjustments to a couple of plugins since this temporary test doesn't follow the same rules as the rest of our framework.
=> [6.13.z] Add basic fixture cli

pytest_plugins/fspath_plugins.py, pytest_plugins/issue_handlers.py, scripts/fixture_cli.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13101
This change adds a new fixture_cli.py script under the scripts directory.
The basic usage of this script is to take in a space-separated list of global fixtures and run them together in a single temporary test.
e.g. python scripts/fixture_cli.py module_ak_with_synced_repo module_lce
Additionally, I had to make some minor adjustments to a couple of plugins since this temporary test doesn't follow the same rules as the rest of our framework.
=> [6.14.z] Add basic fixture cli

pytest_plugins/fspath_plugins.py, pytest_plugins/issue_handlers.py, scripts/fixture_cli.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13101
This change adds a new fixture_cli.py script under the scripts directory.
The basic usage of this script is to take in a space-separated list of global fixtures and run them together in a single temporary test.
e.g. python scripts/fixture_cli.py module_ak_with_synced_repo module_lce
Additionally, I had to make some minor adjustments to a couple of plugins since this temporary test doesn't follow the same rules as the rest of our framework.
=> [6.12.z] Add basic fixture cli

robottelo/constants/__init__.py, tests/foreman/destructive/test_katello_agent.py
Satellite 6.14 is the last version which supports the Katello-Agent, so before upgrade the user must be warned appropriately and we should ensure he really is.
Adding a test case which uses the latest foreman-maintain and ensures the upgrade check contains the warning.
=> [6.14.z] Check upgrade warning when KA enabled

tests/foreman/cli/test_remoteexecution.py
https://github.com/SatelliteQE/robottelo/pull/11544 changed the number of required arguments  of the 
`assert_job_invocation_result` function, but it didn't update all the callers accordingly, leading to all cli rex tests failing in the stream automation run
changed callers
https://github.com/SatelliteQE/robottelo/pull/11544 requires manual cherry-picks, when that happens, this pr should be cherrypicked closely afterwards
=> fix for remote execution cli tests

tests/foreman/api/test_webhook.py
The "Deliver webhook..." task for the triggered hook previously succeeded even If the webhook execution failed for some reason. This will change in 6.15
I'm adding a negative test to cover this scenario. Note that the upstream PR isn't merged yet, so prt trigger would fail atm
SAT-21112
=> [6.15] negative test for webhook task

pytest_fixtures/core/ui.py, robottelo/hosts.py, tests/foreman/conftest.py, tests/foreman/destructive/conftest.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13055
Currently, We are unable to retrieve the Selenium UI session ID from the Airgun GitHub repository and integrate it into our automation testing tool, Robottelo. This session ID is crucial because during the test recording process, videos are generated by the Selenium Airgun repository, and these videos are associated with specific UI session IDs. To improve our testing workflow and enhance the usability of our test results, we need to establish a mechanism that allows us to access this session ID within Robottelo and incorporate it into the JUnit XML results. By doing so, we can leverage the power of the Report Portal logging system, enabling other team members to easily locate and access the video links associated with …
=> [6.14.z] recording ui-session-id for report portal logging

pytest_fixtures/core/ui.py, robottelo/hosts.py, tests/foreman/conftest.py, tests/foreman/destructive/conftest.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13055
Currently, We are unable to retrieve the Selenium UI session ID from the Airgun GitHub repository and integrate it into our automation testing tool, Robottelo. This session ID is crucial because during the test recording process, videos are generated by the Selenium Airgun repository, and these videos are associated with specific UI session IDs. To improve our testing workflow and enhance the usability of our test results, we need to establish a mechanism that allows us to access this session ID within Robottelo and incorporate it into the JUnit XML results. By doing so, we can leverage the power of the Report Portal logging system, enabling other team members to easily locate and access the video links associated with …
=> [6.13.z] recording ui-session-id for report portal logging

tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13167
https://github.com/SatelliteQE/robottelo/pull/11544 changed the number of required arguments  of the 
`assert_job_invocation_result` function, but it didn't update all the callers accordingly, leading to all cli rex tests failing in the stream automation run
changed callers
https://github.com/SatelliteQE/robottelo/pull/11544 requires manual cherry-picks, when that happens, this pr should be cherrypicked closely afterwards
=> [6.15.z] fix for remote execution cli tests

tests/foreman/api/test_webhook.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13049
The "Deliver webhook..." task for the triggered hook previously succeeded even If the webhook execution failed for some reason. This will change in 6.15
I'm adding a negative test to cover this scenario. Note that the upstream PR isn't merged yet, so prt trigger would fail atm
SAT-21112
=> [6.15.z] [6.15] negative test for webhook task

.github/dependabot.yml, conf/robottelo.yaml.template, robottelo/constants/__init__.py, tests/foreman/api/test_capsulecontent.py, tests/foreman/api/test_contentviewfilter.py, tests/foreman/destructive/test_infoblox.py, tests/foreman/maintain/test_service.py, tests/foreman/ui/test_settings.py
New 6.15 downstream and master points to stream that is 6.16
- Dependabot.yaml cherrypicks to 6.15
- Robottelo conf and constants now uses 6.16 and 6.15 satellite versions 
https://github.com/SatelliteQE/robottelo/pull/13168
=> Changes to Master due to new 6.15 and 6.16

tests/foreman/ui/test_host.py
This is testing the first set of features for the new All Hosts page. Currently this only includes the Bulk Delete feature, as well as bulk content source change. This PR includes tests for delete and bulk delete, as the Content Source change feature is something with no current coverage, despite being introduced in 6.12
This is a gap I'll look to address in the future in a seperate PR, as part of ongoing coverage increases.
Requires: 
airgun: 1039
pytest: tests/foreman/ui/test_host.py -k 'test_all_hosts_delete'
=> First tests for new All Hosts page

tests/foreman/api/test_webhook.py
https://github.com/SatelliteQE/robottelo/pull/13048 didn't get things 100% right, my apologies.
Adding an existing target url the webhook can actually GET from to succeed
This will need to get to 6.15 and 6.14. The 6.13 cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13048 didn't happen yet, I will create a manual cherry-pick for it + changes from this pr.
=> fix for webhook event trigger test

tests/foreman/api/test_errata.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13197
Intermittently, stream testing for api::test_errata.py::`test_positive_install_multiple_in_host`
will fail for one or more rhel version parameter. 
At the end, the check fails to assert that an errata install resulted in one less applicable erratum. 
The issue seems to be a post-install assertion will occur-
before the async errata applicability generate task finishes, or the task was not triggered.
Trigger errata applicability generate after errata install, using `subscription-manager`.
Most recently seen in errata-stream build from 11/17/2023, 02:38
```
tests/foreman/api/test_errata.py:228: in test_positive_install_multiple_in_host[rhel8]
assert rhel_contenthost.applicable_errata_count == pre_errata_count - 1
E …
```
=> [6.15.z] Intermittent failure of api::errata::e2e

tests/foreman/api/test_webhook.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13170
https://github.com/SatelliteQE/robottelo/pull/13048 didn't get things 100% right, my apologies.
Adding an existing target url the webhook can actually GET from to succeed
This will need to get to 6.15 and 6.14. The 6.13 cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13048 didn't happen yet, I will create a manual cherry-pick for it + changes from this pr.
=> [6.15.z] fix for webhook event trigger test

tests/foreman/api/test_webhook.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13170
https://github.com/SatelliteQE/robottelo/pull/13048 didn't get things 100% right, my apologies.
Adding an existing target url the webhook can actually GET from to succeed
This will need to get to 6.15 and 6.14. The 6.13 cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13048 didn't happen yet, I will create a manual cherry-pick for it + changes from this pr.
=> [6.14.z] fix for webhook event trigger test

robottelo/host_helpers/cli_factory.py
Changes introduced in https://github.com/SatelliteQE/robottelo/pull/11544 removed the usage of old cli.factory in favor of new cli_factory helpers. And, I've observed a few failures related default content_type missing from `hammer repository create` command used by make_repository helper, and it was present earlier and missing in cli_factory method.
```
robottelo.exceptions.CLIFactoryError: Failed to create Repository with data:
{ 'http-proxy-policy': 'none',
'name': 'sissapUBCf',
'product-id': '1',
'url': 'http://testserver.example.com:50123/fake_yum0'}
Missing arguments for '--content-type'.
```
Add content_type=yum as default in make_repository helper of …
=> Add default content type as yum for make_repository helper

tests/foreman/conftest.py
Some of the directories were missing for adding the `record_property` to test folders. This causes failure in the tests.     
Adding the directory paths fixes this issue now.
=> added the missing direcotry path for ui_session

robottelo/hosts.py, tests/foreman/api/test_rhcloud_inventory.py
We have a new option in rh_cloud report for generating inventory report without uploading it. 
Add test scenario for the disconnected option of rh_cloud report
See SAT-19991 for more info
=> Add test scenario for disconnected option of rh_cloud report

tests/foreman/cli/test_repositories.py
Parent PR: https://github.com/SatelliteQE/robottelo/pull/12322
Issue: https://github.com/SatelliteQE/robottelo/issues/12895
=> [6.14.z] Cherrypick test for invalid repositories

tests/foreman/api/test_repositories.py
Parent PR: https://github.com/SatelliteQE/robottelo/pull/12445
Issue: https://github.com/SatelliteQE/robottelo/issues/12740
=> [6.12.z] Cherrypick test sync multiple large repos 6.12.z

tests/foreman/api/test_repositories.py
ParentPR: https://github.com/SatelliteQE/robottelo/pull/12445
issue: https://github.com/SatelliteQE/robottelo/issues/12743
=> [6.13.z] Cherrypick  test sync large multiple repos 6.13.z

robottelo/host_helpers/cli_factory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13196
Changes introduced in https://github.com/SatelliteQE/robottelo/pull/11544 removed the usage of old cli.factory in favor of new cli_factory helpers. And, I've observed a few failures related default content_type missing from `hammer repository create` command used by make_repository helper, and it was present earlier and missing in cli_factory method.
```
robottelo.exceptions.CLIFactoryError: Failed to create Repository with data:
{ 'http-proxy-policy': 'none',
'name': 'sissapUBCf',
'product-id': '1',
'url': 'http://testserver.example.com:50123/fake_yum0'}
Missing arguments for '--content-type'.
``` …
=> [6.15.z] Add default content type as yum for make_repository helper

tests/foreman/conftest.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13212
Some of the directories were missing for adding the `record_property` to test folders. This causes failure in the tests.     
Adding the directory paths fixes this issue now.
=> [6.15.z] added the missing directory path for ui_session

tests/foreman/conftest.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13212
Some of the directories were missing for adding the `record_property` to test folders. This causes failure in the tests.     
Adding the directory paths fixes this issue now.
=> [6.14.z] added the missing directory path for ui_session

tests/foreman/conftest.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13212
Some of the directories were missing for adding the `record_property` to test folders. This causes failure in the tests.     
Adding the directory paths fixes this issue now.
=> [6.13.z] added the missing directory path for ui_session

pytest_fixtures/core/ui.py, robottelo/hosts.py, tests/foreman/conftest.py, tests/foreman/destructive/conftest.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13055
Currently, We are unable to retrieve the Selenium UI session ID from the Airgun GitHub repository and integrate it into our automation testing tool, Robottelo. This session ID is crucial because during the test recording process, videos are generated by the Selenium Airgun repository, and these videos are associated with specific UI session IDs. To improve our testing workflow and enhance the usability of our test results, we need to establish a mechanism that allows us to access this session ID within Robottelo and incorporate it into the JUnit XML results. By doing so, we can leverage the power of the Report Portal logging system, enabling other team members to easily locate and access the video links associated with …
=> [6.12.z] recording ui-session-id for report portal logging

robottelo/hosts.py, tests/foreman/api/test_rhcloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13210
We have a new option in rh_cloud report for generating inventory report without uploading it. 
Add test scenario for the disconnected option of rh_cloud report
See SAT-19991 for more info
=> [6.15.z] Add test scenario for disconnected option of rh_cloud report

tests/foreman/cli/test_repositories.py
Parent PR: https://github.com/SatelliteQE/robottelo/pull/12322
Issue: https://github.com/SatelliteQE/robottelo/issues/12894
=> [6.13.z] Cherrypick test for invalid repositories

tests/foreman/cli/test_remoteexecution.py
Concurrency has been reworked in dynflow
Add a test for concurrency level being honored
pytest: tests/foreman/cli/test_remoteexecution.py::TestAnsibleREX::test_positive_run_serial
=> Check that concurrency level is honored

conftest.py, pytest_fixtures/component/virtwho_config.py, tests/foreman/virtwho/api/test_esx.py, tests/foreman/virtwho/api/test_kubevirt.py, tests/foreman/virtwho/api/test_nutanix.py, tests/foreman/virtwho/cli/test_esx.py, tests/foreman/virtwho/cli/test_esx_sca.py, tests/foreman/virtwho/cli/test_hyperv.py, tests/foreman/virtwho/cli/test_hyperv_sca.py, tests/foreman/virtwho/cli/test_kubevirt.py, tests/foreman/virtwho/cli/test_kubevirt_sca.py, tests/foreman/virtwho/cli/test_libvirt.py, tests/foreman/virtwho/cli/test_libvirt_sca.py, tests/foreman/virtwho/cli/test_nutanix.py, tests/foreman/virtwho/cli/test_nutanix_sca.py, tests/foreman/virtwho/ui/test_esx.py, tests/foreman/virtwho/ui/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12619
Tasks:
1. fixture support for virt-who config cli : data_form deploy_type virtwho_config delete_host
2. module_sca_manifest content move because module_sca_manifest.content can not found
Cases PASS
```
(robottlo_vv311) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_esx.py  --disable-pytest-warnings -q
............                                                                                                                                                                                                [100%]
12 passed, 12 deselected, 7 warnings in 1140.02s (0:19:00)
(robottelo_vv_311_master) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_esx_sca.py …
```
=> [6.14.z] fixture support for virt-who config cli : data_form deploy_type virtwho_config delete_host& manifest content move

tests/foreman/cli/test_satellitesync.py
Coverage for [BZ#2092039](https://bugzilla.redhat.com/show_bug.cgi?id=2092039) is missing.
This PR. Also adds few docstring fixes.
=> Add coverage for BZ#2092039 and update few docstrings

tests/foreman/ui/test_host.py
Add UI check for new column, for 'RHEL Lifecycle status' 6.15.0 RFE.
Depends on navigation fix in [airgun#1051](https://github.com/SatelliteQE/airgun/pull/1051).
pytest: tests/foreman/ui/test_host.py::test_positive_manage_table_columns
airgun: 1051
=> RHEL Lifecycle status column, RFE for 6.15.0

tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13237
Add UI check for new column, for 'RHEL Lifecycle status' 6.15.0 RFE.
Depends on navigation fix in [airgun#1051](https://github.com/SatelliteQE/airgun/pull/1051).
pytest: tests/foreman/ui/test_host.py::test_positive_manage_table_columns
airgun: 1051
=> [6.15.z] RHEL Lifecycle status column, RFE for 6.15.0

robottelo/constants/__init__.py, tests/foreman/maintain/test_upgrade.py
Cherry-pick for https://github.com/SatelliteQE/robottelo/pull/12535 😅
Can't provide test results. Tests are marked to be skipped for the stream, as we still don't have upgrade support.
=> Fix test_negative_pre_upgrade_tuning_profile_check

robottelo/hosts.py, tests/foreman/api/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13240
In #12989 I missed one breaking change, this should fix it.
=> [6.12.z] Fix capsule download policy update

tests/foreman/cli/test_computeresource_libvirt.py
The BZ associated with the test (BZ#2236693) recently got supplemented with a customer case link, which fired the weekly customerscenario check
Adding customerscenario tag, cherry-picking all the way down
Closes #13244
=> adding customerscenario tag to libvirt e2e provision test

tests/foreman/cli/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13252
The BZ associated with the test (BZ#2236693) recently got supplemented with a customer case link, which fired the weekly customerscenario check
Adding customerscenario tag, cherry-picking all the way down
Closes #13244
=> [6.15.z] adding customerscenario tag to libvirt e2e provision test

tests/foreman/cli/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13252
The BZ associated with the test (BZ#2236693) recently got supplemented with a customer case link, which fired the weekly customerscenario check
Adding customerscenario tag, cherry-picking all the way down
Closes #13244
=> [6.14.z] adding customerscenario tag to libvirt e2e provision test

tests/foreman/cli/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13252
The BZ associated with the test (BZ#2236693) recently got supplemented with a customer case link, which fired the weekly customerscenario check
Adding customerscenario tag, cherry-picking all the way down
Closes #13244
=> [6.13.z] adding customerscenario tag to libvirt e2e provision test

robottelo/cli/user.py, tests/foreman/api/test_notifications.py
Notifications: new test for failed repo sync
This patch adds new API test for mail notification for a failed repository sync.
Other changes:
- Waiting for desired e-mail has been refactored to `wait_for_mail` function so it is more reusable for other and future tests.
Also `wait_for:fail_condition` lambda was fixed due to confusion about how it actually works.
- Fixed one assert in `test_positive_notification_for_long_running_tasks` test.
=> Notifications: new failed repo sync test

conftest.py, pytest_plugins/video_cleanup.py
The existing testing framework lacked a mechanism for customized handling of test results and video cleanup after test execution. Additionally, there was no option to skip video cleaning when tests succeeded.
Introduce a custom pytest hook, your_custom_runtest_makereport_hook, with tryfirst=True and hookwrapper=True. This hook intercepts test outcomes, records relevant information for tests in specified directories during 'call', and, during 'teardown', extracts the session_id to call _clean_video() if a test fails and video cleanup is not skipped.
Furthermore, add a new pytest option, --skip-video-cleanup, with action='store_true', default value False, and a help message. This option allows users to skip video cleaning on test success and can be set via the command line when running …
=> Add custom pytest hook for test result handling and video cleanup

robottelo/host_helpers/satellite_mixins.py, tests/foreman/cli/test_satellitesync.py
Manual CP of https://github.com/SatelliteQE/robottelo/pull/13187
Fixes https://github.com/SatelliteQE/robottelo/issues/13233
=> [6.14.z] Add coverage for BZ#2092039 and update few docstrings

tests/foreman/cli/test_subnet.py
After https://github.com/SatelliteQE/robottelo/pull/12796, we identified a failure for one of negative tests is using invalid_missing_attributes dict to validate if subnet can be updated, after pytest.raises we're also validating if subnet isn't updated, there are invalid keys in use to check subnet key.
1. Fixing the negative test with using exact values to check if subnet isn't updated with invalid values
2. Updating tests to have the teardown
3. Updating tests to use fauxfactory.gen_netmask instead of fixed netmasks
=> Fix subnet tests

conftest.py, pytest_plugins/video_cleanup.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13186
The existing testing framework lacked a mechanism for customized handling of test results and video cleanup after test execution. Additionally, there was no option to skip video cleaning when tests succeeded.
Introduce a custom pytest hook, your_custom_runtest_makereport_hook, with tryfirst=True and hookwrapper=True. This hook intercepts test outcomes, records relevant information for tests in specified directories during 'call', and, during 'teardown', extracts the session_id to call _clean_video() if a test fails and video cleanup is not skipped.
Furthermore, add a new pytest option, --skip-video-cleanup, with action='store_true', default value False, and a help message. This option allows users to skip video cleaning …
=> [6.15.z] Add custom pytest hook for test result handling and video cleanup

conftest.py, pytest_plugins/video_cleanup.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13186
The existing testing framework lacked a mechanism for customized handling of test results and video cleanup after test execution. Additionally, there was no option to skip video cleaning when tests succeeded.
Introduce a custom pytest hook, your_custom_runtest_makereport_hook, with tryfirst=True and hookwrapper=True. This hook intercepts test outcomes, records relevant information for tests in specified directories during 'call', and, during 'teardown', extracts the session_id to call _clean_video() if a test fails and video cleanup is not skipped.
Furthermore, add a new pytest option, --skip-video-cleanup, with action='store_true', default value False, and a help message. This option allows users to skip video cleaning …
=> [6.14.z] Add custom pytest hook for test result handling and video cleanup

conftest.py, pytest_plugins/video_cleanup.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13186
The existing testing framework lacked a mechanism for customized handling of test results and video cleanup after test execution. Additionally, there was no option to skip video cleaning when tests succeeded.
Introduce a custom pytest hook, your_custom_runtest_makereport_hook, with tryfirst=True and hookwrapper=True. This hook intercepts test outcomes, records relevant information for tests in specified directories during 'call', and, during 'teardown', extracts the session_id to call _clean_video() if a test fails and video cleanup is not skipped.
Furthermore, add a new pytest option, --skip-video-cleanup, with action='store_true', default value False, and a help message. This option allows users to skip video cleaning …
=> [6.12.z] Add custom pytest hook for test result handling and video cleanup

.github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13285
Add PRT comment is failing, auto merge with PRT pass checks aren't working as PRT didn't run
https://github.com/SatelliteQE/robottelo/actions/runs/7028916164/job/19125662156
Fixing curl command to not use ISSUE_NUMBER and COMMENT_BODY
=> [6.15.z] Fix copy PRT comment action in autocherrypick workflow

tests/foreman/ui/test_settings.py
After https://github.com/SatelliteQE/robottelo/pull/12796, we identified a failure for this negative tests, where validation error message for `foreman_url` setting has changed 
Updating validation error message for assertion, and removing unnecessary parametrization over `entries_per_page`
https://github.com/SatelliteQE/airgun/pull/1064
=> Update error message in negative settings test

robottelo/host_helpers/cli_factory.py
Changes introduced in https://github.com/SatelliteQE/robottelo/pull/11544 removed the usage of old cli.factory in favor of new cli_factory helpers. And, I've observed a few failures related default provider and url missing from hammer compute-resource create command used by make_compute_resource helper, and it was present earlier and missing in cli_factory method.
```
robottelo.exceptions.CLIFactoryError: Failed to create ComputeResource with data:
{'name': 'm1TzNZ2Njt'}
Command "compute-resource create" finished with status 64
Could not create the compute resource:
Error: Options --name, --provider are required.
See: 'hammer compute-resource create --help'.
```
Add provider and url for libvirt as default in make_compute_resource helper of cli_factory
=> Add default provider/url for make_compute_resource helper

tests/upgrades/test_discovery.py
The versioning of the foreman discovery image should be consistent or greater in the latest version of the satellite.
Save the FDI version pre_upgrade and post upgrading check the version.
[Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2239115)
=> Test Coverage for FDI version verification

tests/upgrades/test_discovery.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13209
The versioning of the foreman discovery image should be consistent or greater in the latest version of the satellite.
Save the FDI version pre_upgrade and post upgrading check the version.
[Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=2239115)
=> [6.15.z] Test Coverage for FDI version verification

tests/foreman/ui/test_settings.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13307
After https://github.com/SatelliteQE/robottelo/pull/12796, we identified a failure for this negative tests, where validation error message for `foreman_url` setting has changed 
Updating validation error message for assertion, and removing unnecessary parametrization over `entries_per_page`
https://github.com/SatelliteQE/airgun/pull/1064
=> [6.15.z] Update error message in negative settings test

conf/capsule.yaml.template, conf/dynaconf_hooks.py, conf/migrations.py, conf/server.yaml.template, pytest_fixtures/core/sat_cap_factory.py, robottelo/config/validators.py, robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13177
There is no distinction between content host deployment workflows and workflows to deploy the operating system on which the product is supposed to be installed. That causes issues in the PIT server testing scenario.
We would like to add a test to install Satellite and Capsule to the test collection, but we need to have a separate content host deployment workflow and the `sat_ready_rhel` and `cap_ready_rhel` workflows. That is due to the need to install the product on top of a non-released OS that we deploy using a workflow that is different from the one that we use for the content host deployment.
Create a distinction between the two workflows in the configuration and use the configuration. …
=> [6.15.z] Create distinction between the product-ready OS and the product WFs

conf/capsule.yaml.template, conf/dynaconf_hooks.py, conf/migrations.py, conf/server.yaml.template, pytest_fixtures/core/sat_cap_factory.py, robottelo/config/validators.py, robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13177
There is no distinction between content host deployment workflows and workflows to deploy the operating system on which the product is supposed to be installed. That causes issues in the PIT server testing scenario.
We would like to add a test to install Satellite and Capsule to the test collection, but we need to have a separate content host deployment workflow and the `sat_ready_rhel` and `cap_ready_rhel` workflows. That is due to the need to install the product on top of a non-released OS that we deploy using a workflow that is different from the one that we use for the content host deployment.
Create a distinction between the two workflows in the configuration and use the configuration. …
=> [6.14.z] Create distinction between the product-ready OS and the product WFs

robottelo/host_helpers/cli_factory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13283
Changes introduced in https://github.com/SatelliteQE/robottelo/pull/11544 removed the usage of old cli.factory in favor of new cli_factory helpers. And, I've observed a few failures related default provider and url missing from hammer compute-resource create command used by make_compute_resource helper, and it was present earlier and missing in cli_factory method.
```
robottelo.exceptions.CLIFactoryError: Failed to create ComputeResource with data:
{'name': 'm1TzNZ2Njt'}
Command "compute-resource create" finished with status 64
Could not create the compute resource:
Error: Options --name, --provider are required.
See: 'hammer compute-resource create --help'.
```
Add provider and url for libvirt as …
=> [6.15.z] Add default provider/url for make_compute_resource helper

tests/foreman/ui/test_settings.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13307
After https://github.com/SatelliteQE/robottelo/pull/12796, we identified a failure for this negative tests, where validation error message for `foreman_url` setting has changed 
Updating validation error message for assertion, and removing unnecessary parametrization over `entries_per_page`
https://github.com/SatelliteQE/airgun/pull/1064
=> [6.13.z] Update error message in negative settings test

scripts/fixture_cli.py
The changes included in this commit are:
- Run fixtures in separate tests so failing fixtures don't block others
- Add the ability to run fixtures that are indirectly parametrized
- Add an option to switch to verbose mode, showing test execution and results. This should help with debugging and generally seeing what' happening
- Add an option to run the fixtures in multiple xdist workers
=> Multiple enhancements to scripts/fixture_cli.py

scripts/fixture_cli.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13243
The changes included in this commit are:
- Run fixtures in separate tests so failing fixtures don't block others
- Add the ability to run fixtures that are indirectly parametrized
- Add an option to switch to verbose mode, showing test execution and results. This should help with debugging and generally seeing what' happening
- Add an option to run the fixtures in multiple xdist workers
=> [6.12.z] Multiple enhancements to scripts/fixture_cli.py

scripts/fixture_cli.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13243
The changes included in this commit are:
- Run fixtures in separate tests so failing fixtures don't block others
- Add the ability to run fixtures that are indirectly parametrized
- Add an option to switch to verbose mode, showing test execution and results. This should help with debugging and generally seeing what' happening
- Add an option to run the fixtures in multiple xdist workers
=> [6.13.z] Multiple enhancements to scripts/fixture_cli.py

scripts/fixture_cli.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13243
The changes included in this commit are:
- Run fixtures in separate tests so failing fixtures don't block others
- Add the ability to run fixtures that are indirectly parametrized
- Add an option to switch to verbose mode, showing test execution and results. This should help with debugging and generally seeing what' happening
- Add an option to run the fixtures in multiple xdist workers
=> [6.14.z] Multiple enhancements to scripts/fixture_cli.py

tests/foreman/longrun/test_inc_updates.py
Hosts-Content > longrun > increamental update feature test was failing in 6.13.z & 6.14.z because content host unabled to install katello-host-tools
Error - `failed on setup with "robottelo.hosts.ContentHostError: Failed to install katello-host-tools"`
Implemented changes which will solve said problem
Same problem has been seen in 6.13.z as well
=> Fix incremental update longrun 6 14 z

tests/foreman/ui/test_location.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13343
=> [6.14.z] Remove unnecessary on_premises_provisioning marker

tests/foreman/ui/test_location.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13343
=> [6.13.z] Remove unnecessary on_premises_provisioning marker

tests/foreman/ui/test_location.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13343
=> [6.15.z] Remove unnecessary on_premises_provisioning marker

tests/foreman/ui/test_location.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13343
=> [6.12.z] Remove unnecessary on_premises_provisioning marker

scripts/polarion-test-case-upload.sh
Test markers to be shown as test fields in polarion. 
To:
- Adhoc filter tests based on markers used by test
- Make reports in polarion based on the markers 
- Betelgeuse should be reading markers on tests at test, class and module level: 
- https://github.com/SatelliteQE/betelgeuse/pull/141 
- In robottelo, polarion test case upload scripts to read/include markers test fields in XML test case to import from polarion
=> Test markers as test fields in polarion

tests/foreman/ui/test_activationkey.py, tests/foreman/ui/test_contenthost.py, tests/foreman/ui/test_organization.py, tests/foreman/ui/test_subscription.py
6.15 Feature automation: SAT-20200
This test is verifying that the Web UI notifies users that Simple Content Access will be required for all organizations in Satellite 6.16
As of now, Stream Satellite is showing Katello 4.12 instead of Satellite 6.16. Keeping in Draft state until changes are made
=> [6.15 RFE] Prepare for SCA Only Update Web UI

scripts/polarion-test-case-upload.sh
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13324
Test markers to be shown as test fields in polarion. 
To:
- Adhoc filter tests based on markers used by test
- Make reports in polarion based on the markers 
- Betelgeuse should be reading markers on tests at test, class and module level: 
- https://github.com/SatelliteQE/betelgeuse/pull/141 
- In robottelo, polarion test case upload scripts to read/include markers test fields in XML test case to import from polarion
=> [6.14.z] Test markers as test fields in polarion

scripts/polarion-test-case-upload.sh
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13324
Test markers to be shown as test fields in polarion. 
To:
- Adhoc filter tests based on markers used by test
- Make reports in polarion based on the markers 
- Betelgeuse should be reading markers on tests at test, class and module level: 
- https://github.com/SatelliteQE/betelgeuse/pull/141 
- In robottelo, polarion test case upload scripts to read/include markers test fields in XML test case to import from polarion
=> [6.13.z] Test markers as test fields in polarion

scripts/polarion-test-case-upload.sh
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13324
Test markers to be shown as test fields in polarion. 
To:
- Adhoc filter tests based on markers used by test
- Make reports in polarion based on the markers 
- Betelgeuse should be reading markers on tests at test, class and module level: 
- https://github.com/SatelliteQE/betelgeuse/pull/141 
- In robottelo, polarion test case upload scripts to read/include markers test fields in XML test case to import from polarion
=> [6.12.z] Test markers as test fields in polarion

tests/foreman/api/test_activationkey.py
It is required to provide `organization_id` for AK update (see apidoc and the related nailgun PR). Failure:
```
tests/foreman/api/test_activationkey.py:244: in test_negative_update_name
target_sat.api.ActivationKey(id=act_key.id, name=new_name).update(['name'])
../../lib64/python3.11/site-packages/nailgun/entity_mixins.py:1076: in update
return self.read(attrs=self.update_json(fields))
../../lib64/python3.11/site-packages/nailgun/entity_mixins.py:1052: in update_json
response = self.update_raw(fields)
../../lib64/python3.11/site-packages/nailgun/entity_mixins.py:1034: in update_raw
self.update_payload(fields),
../../lib64/python3.11/site-packages/nailgun/entities.py:277: in update_payload
payload['organization_id'] = self.organization.id
E   AttributeError: 'DecClass' object has no …
```
=> Fix AK update tests - org required

tests/foreman/api/test_activationkey.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13364
It is required to provide `organization_id` for AK update (see apidoc and the related nailgun PR). Failure:
```
tests/foreman/api/test_activationkey.py:244: in test_negative_update_name
target_sat.api.ActivationKey(id=act_key.id, name=new_name).update(['name'])
../../lib64/python3.11/site-packages/nailgun/entity_mixins.py:1076: in update
return self.read(attrs=self.update_json(fields))
../../lib64/python3.11/site-packages/nailgun/entity_mixins.py:1052: in update_json
response = self.update_raw(fields)
../../lib64/python3.11/site-packages/nailgun/entity_mixins.py:1034: in update_raw
self.update_payload(fields),
../../lib64/python3.11/site-packages/nailgun/entities.py:277: in update_payload
payload['organization_id'] = …
```
=> [6.15.z] Fix AK update tests - org required

tests/foreman/api/test_syncplan.py
Cleaning up SyncPlan test after big refactor. This was missing an api param on the target_sat call. 
pytest: tests/foreman/api/test_syncplan.py -k 'test_positive_synchronize_rh_product_past_sync_date'
=> Fix missing api param in target_sat call in SyncPlan test

tests/foreman/api/test_audit.py
```
'architecture'
'decclass'
```
=> fixed api audit tests

tests/foreman/api/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13370
Cleaning up SyncPlan test after big refactor. This was missing an api param on the target_sat call. 
pytest: tests/foreman/api/test_syncplan.py -k 'test_positive_synchronize_rh_product_past_sync_date'
=> [6.15.z] Fix missing api param in target_sat call in SyncPlan test

tests/foreman/api/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13370
Cleaning up SyncPlan test after big refactor. This was missing an api param on the target_sat call. 
pytest: tests/foreman/api/test_syncplan.py -k 'test_positive_synchronize_rh_product_past_sync_date'
=> [6.14.z] Fix missing api param in target_sat call in SyncPlan test
