- tests/foreman/api/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12128
This change updates test_positive_allow_reregistration_when_dmi_uuid_changed to use global registration method in-place of old method of registration.
Also BZ#2229112 is added and this test case will get skipped until the BZ is fixed.
> [6.13.z] Registration test dmi_uuid fix

- robottelo/cli/contentview.py
- tests/foreman/destructive/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12022
Automation coverage for [BZ 2170535](https://bugzilla.redhat.com/show_bug.cgi?id=2170535) and [BZ 2218661](https://bugzilla.redhat.com/show_bug.cgi?id=2218661)
> [6.14.z] Add another test for capsule sync deadlock issue

- robottelo/hosts.py
- tests/foreman/longrun/test_oscap.py
**Automation coverage for** :
https://bugzilla.redhat.com/show_bug.cgi?id=2081777
https://bugzilla.redhat.com/show_bug.cgi?id=2211952
> [6.14.0-Feature] - Support the --local-files oscap argument

- conftest.py
- pytest_fixtures/component/puppet.py
- pytest_fixtures/core/broker.py
- pytest_fixtures/core/sat_cap_factory.py
- pytest_fixtures/core/sys.py
- pytest_fixtures/core/xdist.py
- pytest_plugins/sanity_plugin.py
- robottelo/hosts.py
- robottelo/utils/ohsnap.py
- testimony.yaml
- tests/foreman/api/test_computeresource_gce.py
- tests/foreman/api/test_host.py
- tests/foreman/api/test_organization.py
- tests/foreman/api/test_repository.py
- tests/foreman/api/test_syncplan.py
- tests/foreman/api/test_user.py
- tests/foreman/cli/test_contentcredentials.py
- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_hostcollection.py
- tests/foreman/cli/test_ping.py
- tests/foreman/cli/test_role.py
- tests/foreman/cli/test_user.py
- tests/foreman/endtoend/test_api_endtoend.py
- tests/foreman/installer/test_installer.py
- tests/foreman/sanity/test_bvt.py
Cherrypick of https://github.com/SatelliteQE/robottelo/pull/11645 in 6.13.z.
> [6.12.z] Sanity Plugin with new sanity tests runs on installer tests satellite

- conf/osp.yaml.template
- tests/foreman/cli/test_computeresource_osp.py
> Update osp.yaml and osp tests

- tests/foreman/virtwho/cli/test_esx_sca.py
- tests/foreman/virtwho/ui/test_esx_sca.py
(cherry picked from commit ecaf81ce38c6016f3b907c08e044c2e6433f6e02)
Fixes #11115
> [6.13.z] - Add virt who config cases to All Tiers Upgrade Tests #11151

- conf/osp.yaml.template
- tests/foreman/cli/test_computeresource_osp.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12145
> [6.13.z] Update osp.yaml and osp tests

- conf/osp.yaml.template
- tests/foreman/cli/test_computeresource_osp.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12145
> [6.14.z] Update osp.yaml and osp tests

- conf/osp.yaml.template
- tests/foreman/cli/test_computeresource_osp.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12145
> [6.12.z] Update osp.yaml and osp tests

- conf/osp.yaml.template
- tests/foreman/cli/test_computeresource_osp.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12145
> [6.11.z] Update osp.yaml and osp tests

- tests/foreman/cli/test_rhcloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12202
null
> [6.13.z] Fix test_positive_inventory_generate_upload_cli

- tests/foreman/cli/test_rhcloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12202
null
> [6.14.z] Fix test_positive_inventory_generate_upload_cli

- tests/foreman/cli/test_rhcloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12202
null
> [6.12.z] Fix test_positive_inventory_generate_upload_cli

- tests/foreman/endtoend/test_api_endtoend.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12206
null
> [6.14.z] added new api path

- tests/foreman/api/test_rhcloud_inventory.py
- tests/foreman/cli/test_bootstrap_script.py
- tests/foreman/cli/test_rhcloud_insights.py
- tests/foreman/cli/test_rhcloud_inventory.py
- tests/foreman/destructive/test_clone.py
- tests/foreman/destructive/test_leapp_satellite.py
- tests/foreman/installer/test_installer.py
- tests/foreman/maintain/test_advanced.py
- tests/foreman/maintain/test_health.py
- tests/foreman/maintain/test_maintenance_mode.py
- tests/foreman/maintain/test_packages.py
- tests/foreman/maintain/test_service.py
- tests/foreman/maintain/test_upgrade.py
- tests/foreman/sys/test_fam.py
- tests/foreman/ui/test_branding.py
- tests/foreman/ui/test_rhcloud_insights.py
- tests/foreman/ui/test_rhcloud_inventory.py
(cherry picked from commit 0634c568ad4208c38078fcf0b6bcc600f5375d12)
Cherrypicks  #11023 to `6.13.z`
> [6.13.z] Mark Platform team tests with e2e marker for stream

- tests/foreman/api/test_rhcloud_inventory.py
- tests/foreman/cli/test_bootstrap_script.py
- tests/foreman/cli/test_rhcloud_insights.py
- tests/foreman/cli/test_rhcloud_inventory.py
- tests/foreman/destructive/test_clone.py
- tests/foreman/destructive/test_leapp_satellite.py
- tests/foreman/installer/test_installer.py
- tests/foreman/maintain/test_advanced.py
- tests/foreman/maintain/test_backup_restore.py
- tests/foreman/maintain/test_health.py
- tests/foreman/maintain/test_maintenance_mode.py
- tests/foreman/maintain/test_packages.py
- tests/foreman/maintain/test_service.py
- tests/foreman/maintain/test_upgrade.py
- tests/foreman/sys/test_fam.py
- tests/foreman/ui/test_branding.py
- tests/foreman/ui/test_rhcloud_insights.py
- tests/foreman/ui/test_rhcloud_inventory.py
(cherry picked from commit 0634c568ad4208c38078fcf0b6bcc600f5375d12)
Cherrypicks #11023 to `6.12.z`
> [6.12.z] Mark Platform team tests with e2e marker for stream

- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12196
First batch of changes coming from the ISS evaluation:
- test cases with similar steps were merged together
- obsoleted test cases were removed
- one test case moved to more appropriate module/component
- other minor updates to address SD/PX/DEV comments
> [6.13.z] ISS refactor

- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12196
First batch of changes coming from the ISS evaluation:
- test cases with similar steps were merged together
- obsoleted test cases were removed
- one test case moved to more appropriate module/component
- other minor updates to address SD/PX/DEV comments
> [6.14.z] ISS refactor

- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12196
First batch of changes coming from the ISS evaluation:
- test cases with similar steps were merged together
- obsoleted test cases were removed
- one test case moved to more appropriate module/component
- other minor updates to address SD/PX/DEV comments
> [6.12.z] ISS refactor

- tests/foreman/maintain/test_advanced.py
- tests/foreman/maintain/test_backup_restore.py
- tests/foreman/maintain/test_health.py
- tests/foreman/maintain/test_packages.py
- tests/foreman/maintain/test_service.py
Parent PR: https://github.com/SatelliteQE/robottelo/pull/12209
> [6.13.z] Modify and delete foreman-maintain tests

- tests/foreman/cli/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11879
The changes mainly focus on merging discovery rule scenarios else removing them completely as per audit.
> [6.13.z] Component Audit for Discovery Plugin - 1

- tests/foreman/cli/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11879
The changes mainly focus on merging discovery rule scenarios else removing them completely as per audit.
> [6.14.z] Component Audit for Discovery Plugin - 1

- tests/foreman/api/test_repository.py
Updated Cert and Key file locations for 6.13 and 6.14
> Fixed failing test for recreating repositories 

- .github/workflows/auto_cherry_pick.yml
Based on the PR  https://github.com/SatelliteQE/robottelo/pull/12247 and comment https://github.com/SatelliteQE/robottelo/pull/12247#issuecomment-1680322427, many triggers are getting generated here and logic needs to change here could be written in separate GHA as well. 
many events are getting triggered could be a time difference causing this issue.
> Duplicate issues are created, as the GHA triggered based on label

- tests/foreman/destructive/test_infoblox.py
Commands for disabling dns-infoblox and dhcp-infoblox are not properly documented. Hence adding  proper commands as per https://bugzilla.redhat.com/show_bug.cgi?id=2210256#c4
> Fix infoblox test

- pytest_fixtures/component/repository.py
- pytest_fixtures/component/rh_cloud.py
- robottelo/cli/factory.py
- robottelo/hosts.py
- tests/foreman/ui/test_activationkey.py
- tests/foreman/ui/test_dashboard.py
- tests/foreman/ui/test_errata.py
- tests/foreman/ui/test_hostcollection.py
- tests/foreman/ui/test_organization.py
- tests/foreman/ui/test_package.py
- tests/foreman/ui/test_reporttemplates.py
- tests/foreman/ui/test_repository.py
- tests/foreman/ui/test_rhc.py
- tests/foreman/ui/test_subscription.py
- tests/foreman/ui/test_sync.py
> [6.12.z] Convert UI manifest tests to manifester

- pytest_fixtures/component/repository.py
- pytest_fixtures/component/rh_cloud.py
- robottelo/cli/factory.py
- robottelo/hosts.py
- tests/foreman/ui/test_activationkey.py
- tests/foreman/ui/test_dashboard.py
- tests/foreman/ui/test_errata.py
- tests/foreman/ui/test_hostcollection.py
- tests/foreman/ui/test_organization.py
- tests/foreman/ui/test_package.py
- tests/foreman/ui/test_reporttemplates.py
- tests/foreman/ui/test_repository.py
- tests/foreman/ui/test_rhc.py
- tests/foreman/ui/test_subscription.py
- tests/foreman/ui/test_sync.py
> [6.13.z] Convert UI manifest tests to manifester (#10394)

- tests/foreman/api/test_remoteexecution.py
The time to pickup value for pull provider rex jobs was set globally by one of the tests but not wasn't reset back to default, which caused interference with other pull-provider tests
> reset global ttp value

- tests/foreman/cli/test_location.py
> removed wontfix locations test

- tests/foreman/api/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11800
The time to pickup value for pull provider rex jobs was set globally by one of the tests but not wasn't reset back to default, which caused interference with other pull-provider tests
> [6.13.z] reset global ttp value

- tests/foreman/api/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11800
The time to pickup value for pull provider rex jobs was set globally by one of the tests but not wasn't reset back to default, which caused interference with other pull-provider tests
> [6.14.z] reset global ttp value

- tests/foreman/ui/test_audit.py
The blocking bugs were closed as wotfix long time ago, interestingly the test was still skipped in automation. This PR removes it
> removed wotfix-skipped test

- tests/foreman/maintain/test_upgrade.py
On stream we do not have a version to upgrade to, so this test is failing. Adding a conditional to check on stream that there are no numbers in the output.
> Assert no version available on satellite-maintain upgrade list-versions for stream

- tests/foreman/cli/test_location.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12282
1937009 closed wontfix
> [6.13.z] removed wontfix locations test

- tests/foreman/cli/test_location.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12282
1937009 closed wontfix
> [6.14.z] removed wontfix locations test

- tests/foreman/cli/test_location.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12282
1937009 closed wontfix
> [6.12.z] removed wontfix locations test

- tests/foreman/ui/test_audit.py
manual cherry-pick, closes https://github.com/SatelliteQE/robottelo/issues/12298
> [6.12] removed wotfix-skipped test

- tests/foreman/ui/test_jobtemplate.py
BZ#1705866 got removed with wontfix, there doesn't seem to be a way to amend the test to make it relevant, so dropping
> removed skipped wontfix jt

- tests/foreman/cli/test_user.py
Test for BZ#2231814, I created this in coordination with dev to be used for early testing of the upcoming upstream PR with the fix. Therefore it won't pass against the current stream
> test negative user with invalid token

- tests/foreman/ui/test_discoveryrule.py
This PR aims to clean up/combine some UI scenarios related to the discovery plugin as per the audit.
Sister PR - https://github.com/SatelliteQE/nailgun/pull/978
> Component Audit for Discovery part-2

- tests/foreman/ui/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12056
This PR aims to clean up/combine some UI scenarios related to the discovery plugin as per the audit.
Sister PR - https://github.com/SatelliteQE/nailgun/pull/978
> [6.13.z] Component Audit for Discovery part-2

- tests/foreman/ui/test_rhc.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12317
null
> [6.13.z] Fix fixture_setup_rhc_satellite

- tests/foreman/ui/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12056
This PR aims to clean up/combine some UI scenarios related to the discovery plugin as per the audit.
Sister PR - https://github.com/SatelliteQE/nailgun/pull/978
> [6.14.z] Component Audit for Discovery part-2

- tests/foreman/maintain/test_service.py
Cherry-pick for https://github.com/SatelliteQE/robottelo/pull/12323
> [6.14.z] Add service list check

- testimony.yaml
- tests/foreman/cli/test_host.py
- tests/foreman/ui/test_host.py
> Decapitalize katello-tracer to match BZ component

- testimony.yaml
- tests/foreman/cli/test_host.py
- tests/foreman/ui/test_host.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/12370
Closes https://github.com/SatelliteQE/robottelo/issues/12382
> [6.14.z] Decapitalize katello-tracer to match BZ component

- testimony.yaml
- tests/foreman/cli/test_host.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/12370
Closes https://github.com/SatelliteQE/robottelo/issues/12381
> [6.12.z] Decapitalize katello-tracer to match BZ component

- pytest_fixtures/component/rh_cloud.py
- pytest_fixtures/core/sat_cap_factory.py
- robottelo/constants/__init__.py
- robottelo/hosts.py
- tests/foreman/api/test_rhcloud_inventory.py
- tests/foreman/cli/test_rhcloud_insights.py
- tests/foreman/cli/test_rhcloud_inventory.py
- tests/foreman/ui/test_rhc.py
- tests/foreman/ui/test_rhcloud_insights.py
- tests/foreman/ui/test_rhcloud_inventory.py
Cherry-pick for https://github.com/SatelliteQE/robottelo/pull/12210
> [cherry-pick-6.14.z] Refactor tests/foreman/ui/test_rhcloud_insights.py

- tests/foreman/maintain/test_service.py
Cherry-pick for https://github.com/SatelliteQE/robottelo/pull/12323
> [6.13.z] Add service list check

- tests/foreman/maintain/test_service.py
Cherry-pick for https://github.com/SatelliteQE/robottelo/pull/12323
> [6.12.z] Add service list check

- pytest_fixtures/component/rh_cloud.py
- pytest_fixtures/core/sat_cap_factory.py
- robottelo/constants/__init__.py
- robottelo/hosts.py
- tests/foreman/api/test_rhcloud_inventory.py
- tests/foreman/cli/test_rhcloud_insights.py
- tests/foreman/cli/test_rhcloud_inventory.py
- tests/foreman/ui/test_rhc.py
- tests/foreman/ui/test_rhcloud_insights.py
- tests/foreman/ui/test_rhcloud_inventory.py
Cherry-pick for https://github.com/SatelliteQE/robottelo/pull/12210
> [cherry-pick-6.13.z] Refactor tests/foreman/ui/test_rhcloud_insights.py

- tests/foreman/api/test_errata.py
- tests/foreman/cli/test_errata.py
-Component Evaluation of Errata Management-
Marked for removal with consideration for merging (with input from DEV, QE, SD, PX):
- `API:test_positive_install_in_host`: Same scenario is tested in a loop during API:test_positive_install_multiple_in_host.
Would it be worth merging the single errata install test into the beginning of the multiple errata install test?
- `CLI:test_positive_user_permission`: A very similar situation is tested in UI:test_positive_list_permission, showing errata for a new user with permissions. Worth merging?
> Remove some redundant tests from Errata-management

- tests/foreman/ui/test_computeresource_vmware.py
Manual cherrypick for https://github.com/SatelliteQE/robottelo/pull/12405 to 6.14
> Check for existance of certain fields before asserting on them

- pytest_fixtures/component/maintain.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12245
When running foreman-maintain tests that have `sat_maintain == session_capsule_configured` it will fail here because `Capsule` does not have an `api` attribute. This update should fix the issue by explicitly calling `session_target_sat`. I also left `sat_maintain` in the fixture since I want this to be done after `sat_maintain` has been created.
> [6.12.z] Use stash to only run module_synced_repos one time

- tests/foreman/api/test_errata.py
- tests/foreman/cli/test_errata.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12385
-Component Evaluation of Errata Management-
Marked for removal with consideration for merging (with input from DEV, QE, SD, PX):
- `API:test_positive_install_in_host`: Same scenario is tested in a loop during API:test_positive_install_multiple_in_host.
Would it be worth merging the single errata install test into the beginning of the multiple errata install test?
- `CLI:test_positive_user_permission`: A very similar situation is tested in UI:test_positive_list_permission, showing errata for a new user with permissions. Worth merging?
> [6.14.z] Remove some redundant tests from Errata-management

- pytest_fixtures/component/maintain.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12245
When running foreman-maintain tests that have `sat_maintain == session_capsule_configured` it will fail here because `Capsule` does not have an `api` attribute. This update should fix the issue by explicitly calling `session_target_sat`. I also left `sat_maintain` in the fixture since I want this to be done after `sat_maintain` has been created.
> [6.13.z] Use stash to only run module_synced_repos one time

- pytest_fixtures/component/maintain.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12245
When running foreman-maintain tests that have `sat_maintain == session_capsule_configured` it will fail here because `Capsule` does not have an `api` attribute. This update should fix the issue by explicitly calling `session_target_sat`. I also left `sat_maintain` in the fixture since I want this to be done after `sat_maintain` has been created.
> [6.14.z] Use stash to only run module_synced_repos one time

- tests/foreman/endtoend/test_api_endtoend.py
- tests/foreman/endtoend/test_cli_endtoend.py
- tests/foreman/longrun/test_inc_updates.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/11669.
Resolves https://github.com/SatelliteQE/robottelo/issues/11723.
> [6.12.z] convert remaining tests to manifester

- tests/foreman/api/test_provisioning.py
Modifying the provisioning test to check if the root password is set on the provisioned VM.
> [6.14.z] Modify provisioning test to check root password is set for provisioned VM

- tests/foreman/api/test_errata.py
- tests/foreman/cli/test_errata.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12385
Issue https://github.com/SatelliteQE/robottelo/issues/12408
> [6.13.z] Remove some redundant tests from Errata-management

- tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12334
Modifying the provisioning test to check if the root password is set on the provisioned VM.
> [6.13.z] [6.14.z] Modify provisioning test to check root password is set for provisioned VM

- tests/foreman/api/test_reporttemplates.py
Failed 6.14.z cherrypick of https://github.com/SatelliteQE/robottelo/pull/12411
> [6.14.z] fixes for [RFE] test_positive_installable_errata

- tests/foreman/api/test_provisioning.py
Modifying the provisioning test to check if the root password is set on the provisioned VM.
> Modify provisioning test to check root password is set for provisioned VM

- tests/foreman/api/test_syncplan.py
1. Products added to a SyncPlan must contain a repo in 6.14.
2. The time format was updated.
Note: The new time format is inconsistent with other time fields and will be tracked in this BZ too https://bugzilla.redhat.com/show_bug.cgi?id=2236502#c1
Until then we keep verifying the values with the new format.
> Fix Sync Plan tests

- tests/foreman/api/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12432
1. Products added to a SyncPlan must contain a repo in 6.14.
2. The time format was updated.
Note: The new time format is inconsistent with other time fields and will be tracked in this BZ too https://bugzilla.redhat.com/show_bug.cgi?id=2236502#c1
Until then we keep verifying the values with the new format.
> [6.14.z] Fix Sync Plan tests

- tests/foreman/api/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12216
There is some flakiness in this test, it sometimes fail with this error:
```
tests/foreman/api/test_capsulecontent.py:1278: in test_positive_capsule_sync_status_persists
assert sync_status['last_sync_time'] >= timestamp
E   AssertionError: assert '2023-08-23 23:03:51 UTC' >= '2023-08-23 23:04'
```
As I learned from DEVs, the designed&implemented behaviour is to fall back to audits when all old sync tasks get deleted (which happens on a regular basis on cleanup). So the caps sync time is taken from audits **only** when all sync tasks are missing. This implies that we need to change the test logic, because if we delete the most recent sync task (and keep older ones, which is the current logic) we don't fall back to audits …
> [6.13.z] Fix capsule sync status persists

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/dispatch_release.yml
- .github/workflows/pull_request.yml
- .github/workflows/update_robottelo_image.yml
- .github/workflows/weekly.yml
CherryPick of #12475 
Closes #12476
> [6.14.z] Bump actions/checkout from 3 to 4

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/pull_request.yml
- .github/workflows/update_robottelo_image.yml
- .github/workflows/weekly.yml
Cherrpick of #12475 
Fixes #12477
> [6.13.z] Bump actions/checkout from 3 to 4

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/pull_request.yml
- .github/workflows/update_robottelo_image.yml
- .github/workflows/weekly.yml
Cherrypick of #12475 
Fixes #12478
> [6.12.z] Bump actions/checkout from 3 to 4

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/pull_request.yml
- .github/workflows/update_robottelo_image.yml
- .github/workflows/weekly.yml
Cherrypick of #12475 
Fixes #12479
> [6.11.z] Bump actions/checkout from 3 to 4 

- tests/foreman/cli/test_container_management.py
- BZ Close loop #2127470
- Verify that long name CV publish when CV & docker repo both have larger name
> content with longer name

- tests/foreman/cli/test_container_management.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12442
- BZ Close loop #2127470
- Verify that long name CV publish when CV & docker repo both have larger name
> [6.13.z] content with longer name

- tests/foreman/cli/test_container_management.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12442
- BZ Close loop #2127470
- Verify that long name CV publish when CV & docker repo both have larger name
> [6.14.z] content with longer name

- tests/foreman/cli/test_container_management.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12442
- BZ Close loop #2127470
- Verify that long name CV publish when CV & docker repo both have larger name
> [6.12.z] content with longer name

- pytest_fixtures/component/maintain.py
- robottelo/constants/__init__.py
- robottelo/host_helpers/contenthost_mixins.py
- tests/foreman/maintain/test_advanced.py
- tests/foreman/maintain/test_health.py
- tests/foreman/maintain/test_maintenance_mode.py
- tests/foreman/maintain/test_service.py
- tests/foreman/maintain/test_upgrade.py
Fixes https://github.com/SatelliteQE/robottelo/issues/12505
Cherry-pick for https://github.com/SatelliteQE/robottelo/pull/12440
> [6.14.z] Fix foreman-maintain tests failing because of automation issues

- tests/foreman/maintain/test_health.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12446
Unstubbing and automating health check test for foreman-proxy-verify-dhcp-config-syntax as part of the foreman-maintain audit.
> [6.14.z] Add health check test for verify_dhcp_config_syntax

- tests/foreman/ui/test_organization.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12508
null
> [6.14.z] Expect exception instead of false return value

- tests/foreman/ui/test_organization.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12508
null
> [6.13.z] Expect exception instead of false return value

- tests/foreman/api/test_convert2rhel.py
Fixed Convert2RHEL test failures.
> Convert2Rhel test fixes

- tests/foreman/api/test_convert2rhel.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10840
Fixed Convert2RHEL test failures.
> [6.14.z] Convert2Rhel test fixes

- pytest_fixtures/component/maintain.py
- robottelo/constants/__init__.py
- robottelo/host_helpers/contenthost_mixins.py
- tests/foreman/maintain/test_advanced.py
- tests/foreman/maintain/test_health.py
- tests/foreman/maintain/test_maintenance_mode.py
- tests/foreman/maintain/test_service.py
- tests/foreman/maintain/test_upgrade.py
Fixes https://github.com/SatelliteQE/robottelo/issues/12503
Cherry-pick for https://github.com/SatelliteQE/robottelo/pull/12440
> [6.12.z] Fix foreman-maintain tests failing because of automation issues

- robottelo/hosts.py
Try to delete the host record even if the host is not registered to Satellite
> Delete Host record on teardown

- tests/foreman/ui/test_syncplan.py
Products added to a SyncPlan must contain a repo in 6.14.
> Fix UI SyncPlan

- tests/foreman/api/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12497
null
> [6.14.z] Add automation for BZ 2106753

- tests/foreman/api/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12497
null
> [6.13.z] Add automation for BZ 2106753

- tests/foreman/destructive/test_katello_agent.py
> [6.13.z] Fix katello-agent

- testimony.yaml
- tests/foreman/cli/test_leapp_client.py
**PR Description**
- Upgrading Rhel host to next major RHEL Realse with job templates
- Path RHEL 8.8 to 9.2
**Steps:**
1. Import a subscription manifest and enable, sync source & target repositories
2. Create CV, add repositories, create lce, ak, etc.
3. Register contenthost using ak
4. Varify target rhel repositories are enable on Satellite
5. Update all packages, install leapp tool and fix inhibitors (in advance)
6. Run Leapp Preupgrade and Leapp Upgrade job template
**Expected output:**
- Update rhel major version to another major version
> leapp scenario 8.8 to 9.2

- testimony.yaml
- tests/foreman/cli/test_leapp_client.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11553
**PR Description**
- Upgrading Rhel host to next major RHEL Realse with job templates
- Path RHEL 8.8 to 9.2
**Steps:**
1. Import a subscription manifest and enable, sync source & target repositories
2. Create CV, add repositories, create lce, ak, etc.
3. Register contenthost using ak
4. Varify target rhel repositories are enable on Satellite
5. Update all packages, install leapp tool and fix inhibitors (in advance)
6. Run Leapp Preupgrade and Leapp Upgrade job template
**Expected output:**
- Update rhel major version to another major version
> [6.13.z] leapp scenario 8.8 to 9.2

- testimony.yaml
- tests/foreman/cli/test_leapp_client.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11553
**PR Description**
- Upgrading Rhel host to next major RHEL Realse with job templates
- Path RHEL 8.8 to 9.2
**Steps:**
1. Import a subscription manifest and enable, sync source & target repositories
2. Create CV, add repositories, create lce, ak, etc.
3. Register contenthost using ak
4. Varify target rhel repositories are enable on Satellite
5. Update all packages, install leapp tool and fix inhibitors (in advance)
6. Run Leapp Preupgrade and Leapp Upgrade job template
**Expected output:**
- Update rhel major version to another major version
> [6.14.z] leapp scenario 8.8 to 9.2

- tests/foreman/destructive/test_katello_agent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12545
Manual cherry-pick of #12395
> [6.12.z] Fix katello-agent

- tests/foreman/api/test_permission.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12509
Related to https://github.com/SatelliteQE/nailgun/pull/992
> [6.14.z] AK update must contain org id, it is a required field

- tests/foreman/api/test_organization.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12498
null
> [6.13.z] Workaround the issue as long as BZ2228820 is open

- tests/foreman/api/test_organization.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12498
null
> [6.14.z] Workaround the issue as long as BZ2228820 is open

- tests/foreman/api/test_provisioningtemplate.py
Automation for [BZ 2024175](https://bugzilla.redhat.com/show_bug.cgi?id=2024175) to cover ansible_provisioning_callback snippet
> Add automation for BZ 2024175

- tests/foreman/api/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12586
Automation for [BZ 2024175](https://bugzilla.redhat.com/show_bug.cgi?id=2024175) to cover ansible_provisioning_callback snippet
> [6.14.z] Add automation for BZ 2024175

- tests/foreman/api/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12586
Automation for [BZ 2024175](https://bugzilla.redhat.com/show_bug.cgi?id=2024175) to cover ansible_provisioning_callback snippet
> [6.13.z] Add automation for BZ 2024175

- tests/upgrades/test_satellite_maintain.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12603
Refactored.
> [6.14.z] Fix satellite_maintain_upgrade_list_versions scenarios

- tests/upgrades/test_satellite_maintain.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12603
Refactored.
> [6.13.z] Fix satellite_maintain_upgrade_list_versions scenarios

- tests/upgrades/test_satellite_maintain.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12603
Refactored.
> [6.12.z] Fix satellite_maintain_upgrade_list_versions scenarios

- pytest_fixtures/component/provision_pxe.py
- tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12604
Adding iPXE provisioning test as a part of the component audit.
> [6.13.z] iPXE provisioning test

- testimony.yaml
- tests/foreman/cli/test_leapp_client.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12639
null
> [6.13.z] Update leapp component name to match ohsnap

- testimony.yaml
- tests/foreman/cli/test_leapp_client.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12639
null
> [6.14.z] Update leapp component name to match ohsnap

- tests/foreman/cli/test_hammer.py
manual cherrypick, closes #12633
- [Parent Pull Request](https://github.com/SatelliteQE/robottelo/pull/12584)
> [6.13] change in upgrade marks for hammer tests

- tests/foreman/api/test_capsule.py
- tests/foreman/cli/test_capsule.py
- tests/foreman/destructive/test_capsule.py
- tests/foreman/destructive/test_capsule_loadbalancer.py
- tests/upgrades/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12675
null
> [6.14.z] Switch ownership of Capsule to Team Platform

- tests/foreman/api/test_capsule.py
- tests/foreman/cli/test_capsule.py
- tests/foreman/destructive/test_capsule.py
- tests/foreman/destructive/test_capsule_loadbalancer.py
- tests/upgrades/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12675
null
> [6.13.z] Switch ownership of Capsule to Team Platform

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12687
Basically coverage for [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2212523) but generalized to check all content referenced in `repomd.xml` in both exports.
> [6.14.z] Add customer test case for BZ#2212523

- tests/foreman/cli/test_repository.py
Simple modification of an existing test, to cover a BZ case seen recently 
https://bugzilla.redhat.com/show_bug.cgi?id=2161209
> Add test using verify checksum on non yum repo in hammer

- tests/foreman/ui/test_subscription.py
Robottelo fix provided for `tests>foreman>ui>test_subscription.py::test_positive_end_to_end`, this test was failing due to flash message, Also uploaded manifest has sca enabled for orgnization and because of that test couldn't read subscription status from dashboard page, So added support to read subscription table.
Note: This test `test_subscription.py::test_positive_end_to_end` is depends on changes from [airgun #992](https://github.com/SatelliteQE/airgun/pull/992) to get execute successfully.
> subscription page ui failure fix in robottelo tests

- robottelo/cli/base.py
- tests/foreman/destructive/test_installer.py
Manual cherry-pick for https://github.com/SatelliteQE/robottelo/pull/12776.
> [6.12.z] Add coverage for 1964037 installer cert regen

- tests/foreman/maintain/test_upgrade.py
Unstubbing this test and modifying the docstring to be more accurate and easy to understand what is being tested.
> Add test for satellite-maintain's self updating ability

- tests/foreman/api/test_errata.py
- tests/foreman/cli/test_errata.py
This PR just removes katello-agent references from errata tests.
> Remove KA references from errata tests

- tests/foreman/maintain/test_service.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12756
The first commit here is a cherry-pick of an old PR that I accidentally removed in one of my Foreman Maintain audits. I must not have had the latest changes on that branch. I'm adding that back in and also adding coverage for 2055790.
> [6.13.z] Add coverage for 2055790 to service enable disable

- tests/foreman/api/test_errata.py
Had to enable custom repos, which are disabled by default. 
Repos were not available to the organization or contenthost, so I updated to use `function_org` and `function_lce`,
setting up the org and repos with those fixtures, using the method `setup_org_for_a_custom_repo`.
* Added a quick `sleep()` before asserting applicable_errata_count, 
as it seems there is some delay after errata install task is done, especially in prt runs.
> Fixes for stream, 6.14.z; failure ErrataManagement in api:test_errata

- tests/upgrades/test_hostcontent.py
> update case component with correct name

- tests/upgrades/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12710
Scenario test to verify that large repositories can be synced without failure after an upgrade.
Test Steps:
1. Before Satellite upgrade.
2. Enable and sync large RH repository.
3. Upgrade Satellite.
4. Enable and sync a second large repository.
> [6.14.z] [Repository Rewrite] Upgrade test for large repo sync

- robottelo/constants/__init__.py
- tests/foreman/cli/test_computeresource_vmware.py
- tests/foreman/ui/test_computeresource_vmware.py
> Fix VMware tests

- robottelo/constants/__init__.py
- tests/foreman/cli/test_computeresource_vmware.py
- tests/foreman/ui/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12883
Fixing failing VMware tests
> [6.14.z] Fix VMware tests

- Makefile
- tests/upgrades/test_activation_key.py
- tests/upgrades/test_bookmarks.py
- tests/upgrades/test_capsule.py
- tests/upgrades/test_errata.py
- tests/upgrades/test_satellitesync.py
- tests/upgrades/test_syncplan.py
- tests/upgrades/test_usergroup.py
While reviewing this PR https://github.com/SatelliteQE/robottelo/pull/12859, found this validations are missed for upgrade tests
> Validate testimony for upgrade tests

- Makefile
- tests/upgrades/test_activation_key.py
- tests/upgrades/test_bookmarks.py
- tests/upgrades/test_capsule.py
- tests/upgrades/test_errata.py
- tests/upgrades/test_satellitesync.py
- tests/upgrades/test_syncplan.py
- tests/upgrades/test_usergroup.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12878
While reviewing this PR https://github.com/SatelliteQE/robottelo/pull/12859, found this validations are missed for upgrade tests
> [6.14.z] Validate testimony for upgrade tests

- Makefile
- tests/upgrades/test_activation_key.py
- tests/upgrades/test_bookmarks.py
- tests/upgrades/test_capsule.py
- tests/upgrades/test_errata.py
- tests/upgrades/test_satellitesync.py
- tests/upgrades/test_syncplan.py
- tests/upgrades/test_usergroup.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12878
While reviewing this PR https://github.com/SatelliteQE/robottelo/pull/12859, found this validations are missed for upgrade tests
> [6.13.z] Validate testimony for upgrade tests

- Makefile
- tests/upgrades/test_activation_key.py
- tests/upgrades/test_bookmarks.py
- tests/upgrades/test_capsule.py
- tests/upgrades/test_errata.py
- tests/upgrades/test_satellitesync.py
- tests/upgrades/test_syncplan.py
- tests/upgrades/test_usergroup.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12878
While reviewing this PR https://github.com/SatelliteQE/robottelo/pull/12859, found this validations are missed for upgrade tests
> [6.12.z] Validate testimony for upgrade tests

- robottelo/hosts.py
> Fix Puppet tests

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12893
Fix failing Puppet tests
> [6.14.z] Fix Puppet tests

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12893
Fix failing Puppet tests
> [6.12.z] Fix Puppet tests

- tests/foreman/api/test_discoveredhost.py
- tests/foreman/cli/test_discoveredhost.py
Attempting to increase the timeout for the `wait_for` function to overcome `wait_for.TimedOutError`
> Fixing Discovery tests

- tests/foreman/cli/test_ldapauthsource.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12814
null
> [6.14.z] Use sAMAccountName

- tests/foreman/cli/test_ldapauthsource.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12814
null
> [6.13.z] Use sAMAccountName

- tests/foreman/ui/test_host.py
Dependant PR 
https://github.com/SatelliteQE/airgun/pull/1003
https://github.com/SatelliteQE/airgun/pull/1006
> Add automation for BZ:1994654/SAT-4845

- tests/foreman/api/test_repositories.py
- tests/foreman/api/test_subscription.py
Parent PR : https://github.com/SatelliteQE/robottelo/pull/11249
failed cherrypick issue: https://github.com/SatelliteQE/robottelo/issues/12058
> [6.12.z] Cherrypick test multiple orgs with same repo

- tests/foreman/ui/test_containerimagetag.py
This test fix covers two changes:
1. Container Image Tag page has been changed (see https://github.com/SatelliteQE/airgun/pull/999) so we need to adjust the test too.
2. Another BZ has been reported so we skip related assertions
> Fix Container Image Tag test

- tests/foreman/maintain/test_backup_restore.py
The feature of Snapshot Backup and Restore is going to be removed.
No need to implement the stub anymore
> Remove test_positive_backup_restore_snapshot stub

- tests/foreman/cli/test_computeresource_libvirt.py
Add workaround for cpu_mode when BZ:2236693 is open for EL9 Libvirt tests
> Add workaround for cpu_mode for EL9 Libvirt tests

- pytest_fixtures/component/domain.py
- tests/upgrades/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12897
null
> [6.13.z] [Upgrades] Add upgrade tests for ProvisioningTemplates

- pytest_fixtures/component/domain.py
- tests/upgrades/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12897
null
> [6.12.z] [Upgrades] Add upgrade tests for ProvisioningTemplates

- tests/foreman/cli/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12973
Add workaround for cpu_mode when BZ:2236693 is open for EL9 Libvirt tests
> [6.14.z] Add workaround for cpu_mode for EL9 Libvirt tests

- tests/foreman/cli/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12973
Add workaround for cpu_mode when BZ:2236693 is open for EL9 Libvirt tests
> [6.13.z] Add workaround for cpu_mode for EL9 Libvirt tests

- tests/foreman/ui/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12996
Add workaround for cpu_mode when BZ:2236693 is open for EL9 Libvirt tests, missed updating UI tests in https://github.com/SatelliteQE/robottelo/pull/12973
> [6.14.z] Add workaround for cpu_mode for EL9 Libvirt UI tests

- tests/foreman/ui/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12996
Add workaround for cpu_mode when BZ:2236693 is open for EL9 Libvirt tests, missed updating UI tests in https://github.com/SatelliteQE/robottelo/pull/12973
> [6.13.z] Add workaround for cpu_mode for EL9 Libvirt UI tests

- tests/foreman/ui/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12996
Add workaround for cpu_mode when BZ:2236693 is open for EL9 Libvirt tests, missed updating UI tests in https://github.com/SatelliteQE/robottelo/pull/12973
> [6.12.z] Add workaround for cpu_mode for EL9 Libvirt UI tests

- tests/foreman/api/test_convert2rhel.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10840
Fixed Convert2RHEL test failures.
> [6.12.z] Convert2Rhel test fixes

- .github/workflows/auto_cherry_pick.yml
(cherry picked from commit 1a7b56644dcd0e28bc99fb13f6ca1bd62c2f9305)
Cherry-pick of #13078
> [6.14.z] Bump actions/github-script from 6 to 7 (#13078)

- .github/workflows/auto_cherry_pick.yml
(cherry picked from commit 1a7b56644dcd0e28bc99fb13f6ca1bd62c2f9305)
Cherry-pick of #13078
> [6.12.z] Bump actions/github-script from 6 to 7 (#13078)

- tests/foreman/api/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13064
This test already passes locally, but fails for the `auth` and `unauth-proxy` parameters in CI. 
`HTTPError 500: Internal Server Error: {"displayMessage":"Task {taks_id}: RuntimeError: The repository's publication is missing. Please run a 'complete sync' on repo_name."`
There seems to be a delay after create(), where the Metadata Generate tasks is still in progress when calling repo.update(). To resolve I have the repos wait for a sync before continuing, which in theory would wait for any in-progress metadata task.
> [6.14.z] Stream fix for e2e api http_proxy failure

- tests/foreman/api/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13064
This test already passes locally, but fails for the `auth` and `unauth-proxy` parameters in CI. 
`HTTPError 500: Internal Server Error: {"displayMessage":"Task {taks_id}: RuntimeError: The repository's publication is missing. Please run a 'complete sync' on repo_name."`
There seems to be a delay after create(), where the Metadata Generate tasks is still in progress when calling repo.update(). To resolve I have the repos wait for a sync before continuing, which in theory would wait for any in-progress metadata task.
> [6.12.z] Stream fix for e2e api http_proxy failure

- robottelo/constants/__init__.py
- robottelo/host_helpers/repository_mixins.py
(cherry picked from commit 4f1652681d2ad26ee9fa0d554c07e04c1f12637e)
This PR cherry-picks the patch from #13047.
> [6.14.z] Add abstraction for debian repo

- robottelo/constants/__init__.py
- robottelo/host_helpers/repository_mixins.py
(cherry picked from commit 4f1652681d2ad26ee9fa0d554c07e04c1f12637e)
This PR cherry-picks the patch from #13047.
> [6.13.z] Add abstraction for debian repo

- robottelo/constants/__init__.py
- robottelo/host_helpers/repository_mixins.py
(cherry picked from commit 4f1652681d2ad26ee9fa0d554c07e04c1f12637e)
This PR cherry-picks the patch from #13047.
> [6.12.z] Add abstraction for debian repo

- pytest_fixtures/core/sat_cap_factory.py
- robottelo/hosts.py
Some of our deployments have hardcoded deploy arguments. These should come from the config.
Take the deployment arguments from the config.
> Parametrize Satellite and Capsule deployments

- pytest_fixtures/component/discovery.py
- tests/foreman/ui/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12991
Adding UI coverage for Discovery provisioning scenarios.
> [6.13.z] Discovery Provisioning UI coverage

- pytest_fixtures/component/activationkey.py
- tests/foreman/api/test_registration.py
- tests/foreman/ui/test_host.py
(cherry picked from commit 2e46f7e24ce7e97499a8e8064a556ee940ca9e3d)
Fixes: https://github.com/SatelliteQE/robottelo/issues/13149
> [6.13.z] Component Audit Part-2 

- tests/foreman/api/test_repositories.py
ParentPR: https://github.com/SatelliteQE/robottelo/pull/12445
issue: https://github.com/SatelliteQE/robottelo/issues/12742
> [6.14.z] Cherrypick test sync multiple large repos 6.14.z

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13198
Concurrency has been reworked in dynflow
Add a test for concurrency level being honored
pytest: tests/foreman/cli/test_remoteexecution.py::TestAnsibleREX::test_positive_run_serial
> [6.15.z] Check that concurrency level is honored

- tests/foreman/ui/test_provisioningtemplate.py
> Add test to verify supported provisioning templates

- tests/foreman/ui/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13267
> [6.13.z] Add test to verify supported provisioning templates

- tests/foreman/ui/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13267
> [6.12.z] Add test to verify supported provisioning templates

- tests/foreman/ui/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13267
> [6.14.z] Add test to verify supported provisioning templates

- tests/foreman/ui/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13267
> [6.15.z] Add test to verify supported provisioning templates

- tests/foreman/cli/test_satellitesync.py
Manual CP of #13187
Fixes #13234
> [6.15.z] Add coverage for BZ#2092039 and update few docstrings

- robottelo/host_helpers/satellite_mixins.py
- tests/foreman/cli/test_satellitesync.py
Manual CP of https://github.com/SatelliteQE/robottelo/pull/13187
Fixes https://github.com/SatelliteQE/robottelo/issues/13235
> [6.13.z] Add coverage for BZ#2092039 and update few docstrings

- robottelo/host_helpers/satellite_mixins.py
- tests/foreman/cli/test_satellitesync.py
Manual CP of https://github.com/SatelliteQE/robottelo/pull/13187
Fixes https://github.com/SatelliteQE/robottelo/issues/13232
> [6.12.z] Add coverage for BZ#2092039 and update few docstrings

- tests/foreman/cli/test_subnet.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13284
After https://github.com/SatelliteQE/robottelo/pull/12796, we identified a failure for one of negative tests is using invalid_missing_attributes dict to validate if subnet can be updated, after pytest.raises we're also validating if subnet isn't updated, there are invalid keys in use to check subnet key.
1. Fixing the negative test with using exact values to check if subnet isn't updated with invalid values
2. Updating tests to have the teardown
3. Updating tests to use fauxfactory.gen_netmask instead of fixed netmasks
> [6.15.z] Fix subnet tests

- tests/foreman/cli/test_subnet.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13284
After https://github.com/SatelliteQE/robottelo/pull/12796, we identified a failure for one of negative tests is using invalid_missing_attributes dict to validate if subnet can be updated, after pytest.raises we're also validating if subnet isn't updated, there are invalid keys in use to check subnet key.
1. Fixing the negative test with using exact values to check if subnet isn't updated with invalid values
2. Updating tests to have the teardown
3. Updating tests to use fauxfactory.gen_netmask instead of fixed netmasks
> [6.14.z] Fix subnet tests

- tests/foreman/cli/test_subnet.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13284
After https://github.com/SatelliteQE/robottelo/pull/12796, we identified a failure for one of negative tests is using invalid_missing_attributes dict to validate if subnet can be updated, after pytest.raises we're also validating if subnet isn't updated, there are invalid keys in use to check subnet key.
1. Fixing the negative test with using exact values to check if subnet isn't updated with invalid values
2. Updating tests to have the teardown
3. Updating tests to use fauxfactory.gen_netmask instead of fixed netmasks
> [6.12.z] Fix subnet tests

- tests/foreman/cli/test_remoteexecution.py
closes https://github.com/SatelliteQE/robottelo/issues/13171
> [6.14] fix for remote execution cli tests

- tests/foreman/api/test_registration.py
Adding closed loop for BZ#1841048 ->  Ability specify REX interface upon registration
> Add closed loop for BZ#1841048

- tests/foreman/api/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13282
Adding closed loop for BZ#1841048 ->  Ability specify REX interface upon registration
> [6.13.z] Add closed loop for BZ#1841048

- tests/foreman/api/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13282
Adding closed loop for BZ#1841048 ->  Ability specify REX interface upon registration
> [6.15.z] Add closed loop for BZ#1841048

- tests/foreman/ui/test_location.py
> Remove unnecessary on_premises_provisioning marker

- tests/foreman/ui/test_rhc.py
There have been new IQE tests added that requires manifest with more entitlements.  
Use `module_extra_rhel_entitlement_manifest` for `test_positive_configure_cloud_connector`.
> Use module_extra_rhel_entitlement_manifest for cloud connector test

- tests/foreman/ui/test_rhc.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13227
There have been new IQE tests added that requires manifest with more entitlements.  
Use `module_extra_rhel_entitlement_manifest` for `test_positive_configure_cloud_connector`.
> [6.15.z] Use module_extra_rhel_entitlement_manifest for cloud connector test

- tests/foreman/ui/test_rhc.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13227
There have been new IQE tests added that requires manifest with more entitlements.  
Use `module_extra_rhel_entitlement_manifest` for `test_positive_configure_cloud_connector`.
> [6.14.z] Use module_extra_rhel_entitlement_manifest for cloud connector test

- tests/foreman/ui/test_rhc.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13227
There have been new IQE tests added that requires manifest with more entitlements.  
Use `module_extra_rhel_entitlement_manifest` for `test_positive_configure_cloud_connector`.
> [6.13.z] Use module_extra_rhel_entitlement_manifest for cloud connector test

- tests/foreman/api/test_contentview.py
More fixes surrounding the recent rework to remove directly calling entity methods.
> Fixes for CV Tests

- tests/foreman/cli/test_repositories.py
Cherrypick of https://github.com/SatelliteQE/robottelo/pull/12777
Issue: https://github.com/SatelliteQE/robottelo/issues/12924
> [Cherrypick]Test for disabling rh repository with basearch 6.14.z

- tests/foreman/cli/test_repositories.py
- tests/upgrades/test_repository.py
Cherrypick of https://github.com/SatelliteQE/robottelo/pull/12777
Issue: https://github.com/SatelliteQE/robottelo/issues/12925
> [Cherrypick]Test for disabling rh repository with basearch 6.13.z

- tests/foreman/api/test_repositories.py
Cherrypick from https://github.com/SatelliteQE/robottelo/pull/12888
Issue: https://github.com/SatelliteQE/robottelo/issues/12920
> [Cherrypick][Repository Rewrite] Adding test for available_repositories endpoint

- tests/foreman/api/test_repositories.py
Cherrypick from https://github.com/SatelliteQE/robottelo/pull/12888
Issue: https://github.com/SatelliteQE/robottelo/issues/12921
> Test for available repo endpoint 6.12.z

- tests/foreman/api/test_ansible.py
Cherrypick of https://github.com/SatelliteQE/robottelo/pull/11688/commits
> [6.14] bz1699188

- tests/foreman/cli/test_location.py
probably another victim of https://github.com/SatelliteQE/robottelo/pull/11544 
_location and other helpers were not always called correctly
updated callers
> cli location test fixes

- tests/foreman/cli/test_location.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13406
probably another victim of https://github.com/SatelliteQE/robottelo/pull/11544 
_location and other helpers were not always called correctly
updated callers
> [6.14.z] cli location test fixes

- tests/foreman/cli/test_location.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13406
probably another victim of https://github.com/SatelliteQE/robottelo/pull/11544 
_location and other helpers were not always called correctly
updated callers
> [6.13.z] cli location test fixes

- tests/foreman/cli/test_location.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13406
probably another victim of https://github.com/SatelliteQE/robottelo/pull/11544 
_location and other helpers were not always called correctly
updated callers
> [6.15.z] cli location test fixes

- tests/foreman/api/test_permission.py
- tests/foreman/api/test_role.py
- tests/foreman/cli/test_role.py
fixed a bunch of test failures, mainly effects of https://github.com/SatelliteQE/robottelo/pull/12989 and https://github.com/SatelliteQE/robottelo/pull/12796 
Some tests are still affected by type error problem on entitiy init, I beleive this should be fixed on the nailgun side, filed https://github.com/SatelliteQE/nailgun/pull/1029
> users and roles test fixes

- tests/foreman/api/test_permission.py
- tests/foreman/api/test_role.py
- tests/foreman/cli/test_role.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13433
fixed a bunch of test failures, mainly effects of https://github.com/SatelliteQE/robottelo/pull/12989 and https://github.com/SatelliteQE/robottelo/pull/12796 
Some tests are still affected by type error problem on entitiy init, I beleive this should be fixed on the nailgun side, filed https://github.com/SatelliteQE/nailgun/pull/1029
> [6.15.z] users and roles test fixes

- tests/foreman/ui/test_contenthost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13162
Extend UI::test_contenthost.py::`test_positive_end_to_end`: 
- To check the new `'RHEL Lifecycle status'` of the rhel host, and check `host status`.
Two helper methods:
- `get_supported_rhel_versions()` : to get all supported rhel versions for contenthosts in satellite.
- `get_rhel_lifecycle_support(rhel_version)` : to get expected RHEL Lifecycle status string, 
based on provided `rhel_version#` vs all supported `versions#` discovered.
> [6.15.z] [RFE] Check RHEL Lifecycle status in ContentHost UI

- tests/foreman/cli/test_errata.py
Failed 6.14.z cherry-pick of #13288
Failed CP: #13449 
pytest: tests/foreman/cli/test_errata.py
> [6.14.z] CLI::Errata Refactor

- tests/foreman/installer/test_installer.py
Default Foreman cache was changed from file to redis. We have to adjust tests to reflect this change.
> Default foreman cache changed from file to redis

- tests/foreman/api/test_provisioning.py
- tests/foreman/api/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12695
SSIA
> [6.15.z] Add test coverage for provisioning with fips_enabled

- tests/foreman/installer/test_installer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13325
Default Foreman cache was changed from file to redis. We have to adjust tests to reflect this change.
> [6.15.z] Default foreman cache changed from file to redis

- tests/foreman/api/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13426
Fix discovery rule tests-> The test was failing in the teardown when trying to delete the created location, we need to delete both the hosts to run the teardown properly
> [6.13.z] Fix discovery rule tests

- tests/foreman/ui/test_registration.py
Registration Component Audit: Check org and loc change on the Global Registration form
> Component Audit: Check org and loc change on Global Registration form

- tests/foreman/ui/test_registration.py
Check for Default values on Global Registration Template
> Cherrypick : Check for Default values on Global Registration Template

- tests/foreman/ui/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13480
Fixes: #13496
> [6.14.z] Component Audit: Check org and loc change on Global Registration form

- tests/foreman/cli/test_satellitesync.py
#11544 unintentionally reverted some changes I made in #13017.
This PR brings the original changes back.
The PRT won't pass until [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2254408) is resolved. Which should happen in the next snap, looking at https://github.com/theforeman/foreman-packaging/pull/10143, if I'm not quite mistaken.
> Bring back changes reverted by #11544

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13517
#11544 unintentionally reverted some changes I made in #13017.
This PR brings the original changes back.
The PRT won't pass until [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2254408) is resolved. Which should happen in the next snap, looking at https://github.com/theforeman/foreman-packaging/pull/10143, if I'm not quite mistaken.
> [6.15.z] Bring back changes reverted by #11544

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13517
#11544 unintentionally reverted some changes I made in #13017.
This PR brings the original changes back.
The PRT won't pass until [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2254408) is resolved. Which should happen in the next snap, looking at https://github.com/theforeman/foreman-packaging/pull/10143, if I'm not quite mistaken.
> [6.14.z] Bring back changes reverted by #11544

- tests/foreman/api/test_provisioningtemplate.py
Add coverage for rex pull mode provisioning snippet "remote_execution_pull_setup"
> Add coverage for rex pull mode provisioning snippet

- tests/foreman/api/test_audit.py
- tests/foreman/ui/test_audit.py
> Corrected Req for AuditLog

- tests/foreman/api/test_audit.py
- tests/foreman/ui/test_audit.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13516
> [6.15.z] Corrected Req for AuditLog

- tests/foreman/api/test_audit.py
- tests/foreman/ui/test_audit.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13516
> [6.14.z] Corrected Req for AuditLog

- tests/foreman/api/test_audit.py
- tests/foreman/ui/test_audit.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13516
> [6.13.z] Corrected Req for AuditLog

- tests/foreman/api/test_audit.py
- tests/foreman/ui/test_audit.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13516
> [6.12.z] Corrected Req for AuditLog

- tests/foreman/cli/test_satellitesync.py
Manual cherry-pick of #13517.
Closes #13519
> [6.13.z] Bring back changes reverted by #11544

- tests/foreman/cli/test_satellitesync.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13517.
Closes #13520
> [6.12.z] Bring back changes reverted by #11544

- tests/foreman/api/test_provisioning.py
Mark Provisioning tests for upgrade
> Mark Provisioning tests for upgrade

- tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13542
Mark Provisioning tests for upgrade
> [6.15.z] Mark Provisioning tests for upgrade

- tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13542
Mark Provisioning tests for upgrade
> [6.14.z] Mark Provisioning tests for upgrade

- tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13542
Mark Provisioning tests for upgrade
> [6.13.z] Mark Provisioning tests for upgrade

- conftest.py
- pytest_fixtures/component/provision_capsule_pxe.py
- pytest_plugins/fixture_markers.py
- tests/foreman/api/test_provisioning.py
Adding a test for provisioning using an external capsule.
> Add Capsule Provisioning test

- tests/foreman/ui/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13480
Fixes: #13494
> [6.13.z] Component Audit: Check org and loc change on Global Registration form

- conftest.py
- pytest_fixtures/component/provision_capsule_pxe.py
- pytest_plugins/fixture_markers.py
- tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13241
Adding a test for provisioning using an external capsule.
> [6.15.z] Add Capsule Provisioning test

- conftest.py
- pytest_fixtures/component/provision_capsule_pxe.py
- pytest_plugins/fixture_markers.py
- tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13241
Adding a test for provisioning using an external capsule.
> [6.14.z] Add Capsule Provisioning test

- pytest_fixtures/core/sat_cap_factory.py
- robottelo/hosts.py
- tests/foreman/destructive/test_registration.py
Missing test coverage for registration with rex pull-mode against Satellite and Capsule
Add test coverage for registration with rex pull-mode against Satellite and Capsule
> Add test for registration with rex pull-mode

- tests/foreman/ui/test_settings.py
Missing test for show_unsupported_templates setting
Add test for show_unsupported_templates setting
> Add test for show_unsupported_templates setting

- tests/foreman/api/test_ansible.py
Cherry pick of https://github.com/SatelliteQE/robottelo/pull/11688/files
> [6.13] bz1699188

- tests/foreman/ui/test_settings.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13560
Missing test for show_unsupported_templates setting
Solution
Add test for show_unsupported_templates setting
> [6.14.z] Add test for show_unsupported_templates setting

- robottelo/cli/org.py
- tests/foreman/cli/test_satellitesync.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13543
Closes https://github.com/SatelliteQE/robottelo/issues/13585
> [6.14.z] Add ISS Network Sync class and basic scenario

- tests/foreman/api/test_registration.py
Missing test scenario for capsule without registration module
Add  test scenario for capsule without registration module
> Test capsule without registration module

- tests/foreman/api/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13583
Missing test scenario for capsule without registration module
Add  test scenario for capsule without registration module
> [6.14.z] Test capsule without registration module

- tests/foreman/api/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13583
Missing test scenario for capsule without registration module
Add  test scenario for capsule without registration module
> [6.15.z] Test capsule without registration module

- tests/foreman/ui/test_eol_banner.py
manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/13211
Somehow the banner stopped working on stream, so I can't get prt passing on the original PR, I will investigate further.
I have positive local results for 6.15, so I'm opening this cherry-pick manually for coverage
> [6.15] eol banner

- tests/foreman/cli/test_syncplan.py
> Small fix for SyncPlan test

- tests/foreman/cli/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13661
Syntax fix.
> [6.14.z] Small fix for SyncPlan test

- tests/foreman/cli/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13661
Syntax fix.
> [6.13.z] Small fix for SyncPlan test

- tests/foreman/cli/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13661
Syntax fix.
> [6.12.z] Small fix for SyncPlan test

- tests/foreman/cli/test_satellitesync.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13506
Closes https://github.com/SatelliteQE/robottelo/issues/13638
> [6.14.z] Add coverage for BZ#2112098

- tests/foreman/api/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13668
Removing stubbed marker
> [6.13.z] Removing stubbed marker

- tests/foreman/api/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13668
Removing stubbed marker
> [6.14.z] Removing stubbed marker

- tests/foreman/api/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13668
Removing stubbed marker
> [6.15.z] Removing stubbed marker

- tests/foreman/api/test_discoveryrule.py
https://github.com/SatelliteQE/robottelo/pull/13426
> Cherrypick discovery fixes

- tests/foreman/cli/test_satellitesync.py
Manual cherry-pick of #13506
Closes #13641
> [6.15.z] Add coverage for BZ#2112098

- tests/foreman/api/test_discoveredhost.py
- tests/foreman/cli/test_discoveredhost.py
- tests/foreman/ui/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13741
The Mac address is not getting collected properly so increasing the timeout.
> [6.15.z] Increasing the timeout for mac collection

- robottelo/cli/repository.py
- robottelo/host_helpers/cli_factory.py
Manual cherry-pick of #13738 
Closes https://github.com/SatelliteQE/robottelo/issues/13750
> [6.15.z] Fixes in cli_factory

- robottelo/cli/repository.py
- robottelo/host_helpers/cli_factory.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13738
Closes https://github.com/SatelliteQE/robottelo/issues/13752
> [6.13.z] Fixes in cli_factory

- robottelo/cli/repository.py
- robottelo/host_helpers/cli_factory.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13738
Closes https://github.com/SatelliteQE/robottelo/issues/13751
> [6.12.z] Fixes in cli_factory

- robottelo/cli/repository.py
- robottelo/host_helpers/cli_factory.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13738
Closes https://github.com/SatelliteQE/robottelo/issues/13753
> [6.14.z] Fixes in cli_factory

- tests/foreman/api/test_discoveredhost.py
- tests/foreman/cli/test_discoveredhost.py
- tests/foreman/ui/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13741
The Mac address is not getting collected properly so increasing the timeout.
> [6.14.z] Increasing the timeout for mac collection

- robottelo/cli/org.py
- tests/foreman/cli/test_satellitesync.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13506
Closes https://github.com/SatelliteQE/robottelo/issues/13639
> [6.13.z] Add coverage for BZ#2112098

- robottelo/cli/org.py
- tests/foreman/cli/test_satellitesync.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13506
Closes https://github.com/SatelliteQE/robottelo/issues/13640
> [6.12.z] Add coverage for BZ#2112098

- tests/foreman/ui/test_discoveryrule.py
Going with the API way for provisioning as the host created is a fake discovered host and its provisioning invokes a warning on the UI, as the subnet is randomly generated.
> Adding fix for discoveryrule UI

- tests/foreman/ui/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13754
Going with the API way for provisioning as the host created is a fake discovered host and its provisioning invokes a warning on the UI, as the subnet is randomly generated.
> [6.13.z] Adding fix for discoveryrule UI

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13602
null
> [6.14.z] Component Evaluation - add RHEL 8 and 9 host versions

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13602
null
> [6.15.z] Component Evaluation - add RHEL 8 and 9 host versions

- tests/foreman/cli/test_satellitesync.py
This PR just adds negative test case for ISS import of an incomplete export archive, which mocks interrupted data transfer.
> Add test case for ISS incomplete archive import

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13600
This PR just adds negative test case for ISS import of an incomplete export archive, which mocks interrupted data transfer.
> [6.15.z] Add test case for ISS incomplete archive import

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13432
Close-loop bz1784254
> [6.14.z] bz1784254

- tests/foreman/cli/test_satellitesync.py
Manual cherry-pick of #13202 
Closes #13836
> [6.15.z] Add coverage for BZ#2173756

- tests/foreman/api/test_role.py
https://github.com/SatelliteQE/robottelo/pull/12989 updated the create_domain and create_simple_user helpers to use target_sat but didn't update all the callers accordingly 
this pr
> fixes in api role helper functions

- tests/foreman/destructive/test_auth.py
The result format changed, possibly due to https://github.com/SatelliteQE/robottelo/pull/13737
adjusting
> fix in test_permission

- tests/foreman/destructive/test_auth.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13879
The result format changed, possibly due to https://github.com/SatelliteQE/robottelo/pull/13737
adjusting
> [6.13.z] fix in test_permission

- tests/foreman/destructive/test_auth.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13879
The result format changed, possibly due to https://github.com/SatelliteQE/robottelo/pull/13737
adjusting
> [6.12.z] fix in test_permission

- tests/foreman/destructive/test_installer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13694
Added new testcase to cover BZ 2221621 (and it's clone BZ 2238363)
BZ reported in Sat 6.13. Attempting to run installer with invalid certificates on existing installation causes breakage of current setup - hammer ping reports failures. After fix the installer returns error and leaves current setup (hammer ping reports OK statuses)
> [6.14.z] Adding coverage for BZ2221621

- tests/foreman/endtoend/test_api_endtoend.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13857
Updating the list of endpoints to 6.15, the changes were verified before via sat-eng list
> [6.15.z] api endpoints updated

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13929
typo, probably from https://github.com/SatelliteQE/robottelo/pull/13273 
fixed
> [6.15.z] ui_seesion > ui_session

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13929
typo, probably from https://github.com/SatelliteQE/robottelo/pull/13273 
fixed
> [6.13.z] ui_seesion > ui_session

- pytest_fixtures/component/activationkey.py
- robottelo/cli/hammer.py
- tests/foreman/cli/test_host.py
Cherrypick of https://github.com/SatelliteQE/robottelo/pull/13905
> CE-SAT-21617

- tests/foreman/cli/test_remoteexecution.py
this was requested by a stakeholder in component evaluation (SAT-21614)
> test errata application with pull-mqtt rex

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13960
this was requested by a stakeholder in component evaluation (SAT-21614)
> [6.15.z] test errata application with pull-mqtt rex

- robottelo/host_helpers/cli_factory.py
make_job_invocation_with_credentials got dropped without replacement causing test failures
> job invocation with credentials added

- conf/vmware.yaml.template
- pytest_fixtures/component/provision_vmware.py
- tests/foreman/cli/test_computeresource_vmware.py
- tests/foreman/ui/test_computeresource_vmware.py
Adding support to run VMware tests on VMware8
> Modify VMware tests to run on VMware8

- conf/vmware.yaml.template
- pytest_fixtures/component/provision_vmware.py
- tests/foreman/cli/test_computeresource_vmware.py
- tests/foreman/ui/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13877
Adding support to run VMware tests on VMware8
> [6.15.z] Modify VMware tests to run on VMware8

- tests/foreman/cli/test_errata.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13928
Some Errata action items for failing setup and some sorting tests. 
- Changed nearly all `module_entitlement_manifest_org` to `module_sca_manifest_org`, the fixture often failed setup for no manifest content. This also prepares cli testing for SCA-only orgs coming in 6.16.0.
- Changed some remaining rh repo references from RHEL7 and RHST7, to RHEL8 and RHSClient8
- Updated some expected output from `JobInvocation` being created/started, checking completed status.
- Properly reading cli output, for errata 'Issue' and 'Update' dates
> [6.15.z] fixes for CLI post-eval failures

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14058
CE request: `The test case should also include, assigning multiple compliance policy to the same content host and then unassing one of the compliance policy and veirfy if the correct compliace policy is getting unassigned.`
> [6.15.z] Test unassigning with multiple policies present

- tests/foreman/cli/test_auth.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14060
null
> [6.15.z] Make things clear in docstring

- conf/vmware.yaml.template
- pytest_fixtures/component/provision_vmware.py
- tests/foreman/cli/test_computeresource_vmware.py
- tests/foreman/ui/test_computeresource_vmware.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13877
> [6.13.z] Add support to run VMware tests on VMware8

- requirements.txt
> Bump Broker to 0.4.5

- tests/foreman/api/test_docker.py
- tests/foreman/api/test_repository.py
- tests/foreman/cli/test_repository.py
- tests/foreman/ui/test_repository.py
- tests/foreman/ui/test_sync.py
Auto CP failed for this [6.14.z] PR https://github.com/SatelliteQE/robottelo/issues/14140
Manual CP, PR raised against 6.14.z branch
> [6.14.z] deleted tc's by considering recommendation present in repositories component audit

- tests/foreman/destructive/test_auth.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14070
null
> [6.15.z] Add a new test for password reset to user-specified password

- tests/foreman/api/test_repository.py
- tests/foreman/cli/test_repository.py
- tests/foreman/ui/test_repository.py
Failed to auto cherry pick due to conflicts in Parent PR https://github.com/SatelliteQE/robottelo/pull/14179
Manual CP
NA
> [6.13] correct component names and description

- tests/foreman/api/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14195
As per PX recommendation need to add steps and update automation coverage around the test.
Jira-23358
- Add test steps in test case
- Add additional assersions at the end of test
N/A
> [6.15.z] add test steps, refresh uploaded manifest file

- tests/foreman/cli/test_host.py
> forgotten target sat in host cli tests

- requirements.txt
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14256
Closes #14190 #14124
> [6.12.z] Bump Pytest to 8.0.2

- tests/upgrades/test_virtwho.py
add verify virt-who data is uploaded on satellite post satellite upgrade
Test Cases PASS:
```
(robottelo_vv_615) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade -s
2024-03-04 09:00:13 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
platform linux -- Python 3.11.7, pytest-8.0.1, pluggy-1.4.0
Mandatory Requirements Mismatch: paramiko==3.4.0  # Temporary until Broker is back on PyPi docker==7.0.0  # Temporary until Broker is back …
```
> add verify virt-who data is uploaded on satellite post satellite upgrade

- tests/upgrades/test_virtwho.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14260
add verify virt-who data is uploaded on satellite post satellite upgrade
Test Cases PASS:
```
(robottelo_vv_615) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade -s
2024-03-04 09:00:13 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
platform linux -- Python 3.11.7, pytest-8.0.1, pluggy-1.4.0
Mandatory Requirements Mismatch: paramiko==3.4.0  # Temporary until …
```
> [6.14.z] add verify virt-who data is uploaded on satellite post satellite upgrade

- tests/foreman/api/test_permission.py
SAT-21619 (component evaluation).
Check for correct user permissions when deleting a host.
> host delete permissions test

- testimony.yaml
- tests/foreman/api/test_ansible.py
- tests/foreman/cli/test_ansible.py
- tests/foreman/cli/test_remoteexecution.py
- tests/foreman/destructive/test_ansible.py
- tests/foreman/ui/test_ansible.py
- tests/foreman/ui/test_jobinvocation.py
- tests/foreman/ui/test_remoteexecution.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/14302
Fixes https://github.com/SatelliteQE/robottelo/issues/14366
> [6.15.z] Update Ansible tests to reflect the new split Ansible components

- tests/foreman/cli/test_remoteexecution.py
Removing one expression causing flakiness in this test
> simplify time expression assertions

- testimony.yaml
- tests/foreman/api/test_ldapauthsource.py
- tests/foreman/cli/test_ldapauthsource.py
- tests/foreman/cli/test_sso.py
- tests/foreman/destructive/test_ldap_authentication.py
- tests/foreman/destructive/test_ldapauthsource.py
- tests/foreman/sys/test_dynflow.py
- tests/foreman/ui/test_ldap_authentication.py
Updated component names as needed
> component name changes

- tests/foreman/api/test_computeresource_libvirt.py
- tests/foreman/api/test_discoveryrule.py
- tests/foreman/api/test_http_proxy.py
- tests/foreman/api/test_parameters.py
- tests/foreman/cli/test_classparameters.py
- tests/foreman/cli/test_computeresource_osp.py
- tests/foreman/cli/test_discoveredhost.py
- tests/foreman/cli/test_errata.py
- tests/foreman/cli/test_hammer.py
- tests/foreman/cli/test_satellitesync.py
- tests/foreman/cli/test_subnet.py
- tests/foreman/destructive/test_capsule_loadbalancer.py
- tests/foreman/maintain/test_advanced.py
- tests/foreman/maintain/test_health.py
- tests/foreman/maintain/test_maintenance_mode.py
- tests/foreman/maintain/test_packages.py
- tests/foreman/ui/test_ansible.py
- tests/foreman/ui/test_computeresource_gce.py
- tests/foreman/ui/test_computeresource_libvirt.py
- tests/upgrades/test_contentview.py
- tests/upgrades/test_host.py
- tests/upgrades/test_provisioningtemplate.py
- tests/upgrades/test_subscription.py
- tests/upgrades/test_usergroup.py
Manual cherry pick of https://github.com/SatelliteQE/robottelo/pull/14036, closes https://github.com/SatelliteQE/robottelo/issues/14421
> [6.13] addFinalizer in test body 

- tests/foreman/destructive/test_auth.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13879
The result format changed, possibly due to https://github.com/SatelliteQE/robottelo/pull/13737
adjusting
> [6.14.z] fix in test_permission

- requirements.txt
Cherry-pick of #14399
Fixes #14458
> [6.14.z] Bump Broker to 0.4.9

- robottelo/constants/__init__.py
Some new permissions added to constants
> permission constants updated

- requirements.txt
Cherry-pick of #14399
Fixes #14455
> [6.12.z] Bump Broker to 0.4.9

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14463
Some new permissions added to constants
> [6.15.z] permission constants updated

- robottelo/constants/__init__.py
- robottelo/constants/repos.py
- tests/foreman/api/test_repositories.py
Adding a test to sync repository having zst type of compression
Closed loop BZ#2241934
> Add test to sync repo having zst compression

- robottelo/constants/__init__.py
- robottelo/constants/repos.py
- tests/foreman/api/test_repositories.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14398
Adding a test to sync repository having zst type of compression
Closed loop BZ#2241934
> [6.14.z] Add test to sync repo having zst compression

- robottelo/constants/__init__.py
- robottelo/constants/repos.py
- tests/foreman/api/test_repositories.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14398
Adding a test to sync repository having zst type of compression
Closed loop BZ#2241934
> [6.15.z] Add test to sync repo having zst compression

- pytest_fixtures/core/contenthosts.py
- pytest_plugins/fixture_markers.py
- tests/foreman/ui/test_host.py
- tests/foreman/ui/test_jobinvocation.py
- tests/foreman/ui/test_remoteexecution.py
Cherrypick of https://github.com/SatelliteQE/robottelo/pull/14512
> [6.15.z] Cherrypick of FixesForEndeavour

- tests/foreman/ui/test_errata.py
Failing setup using repo collection and DEFAULT ORG, no errata found on page (none has been synced).
Update to create separate custom rhel8 repos on two organizations.
Errata IDs needed updating too 
Fails 6.14 and 6.15 automation runs local and CI
```
pytest: tests/foreman/ui/test_errata.py::test_positive_list
```
> fix UI:Errata test_positive_list

- tests/foreman/ui/test_errata.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14514
Failing setup using repo collection and DEFAULT ORG, no errata found on page (none has been synced).
Update to create separate custom rhel8 repos on two organizations.
Errata IDs needed updating too 
Fails 6.14 and 6.15 automation runs local and CI
```
pytest: tests/foreman/ui/test_errata.py::test_positive_list
```
> [6.15.z] fix UI:Errata test_positive_list

- tests/foreman/endtoend/test_cli_endtoend.py
creating a separate pr from https://github.com/SatelliteQE/robottelo/pull/13999 as master needs additional work
> [6.15] cli e2e fix

- tests/foreman/api/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14464
Missing coverage for BZ:2187967, which verifies ansible roles inheritance functionality for host with parent/nested hostgroup
Add a end-to-end test to cover this customer scenario from BZ:2187967
> [6.14.z] Add test coverage for BZ:2187967

- tests/foreman/api/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14464
Missing coverage for BZ:2187967, which verifies ansible roles inheritance functionality for host with parent/nested hostgroup
Add a end-to-end test to cover this customer scenario from BZ:2187967
> [6.15.z] Add test coverage for BZ:2187967

- tests/foreman/endtoend/test_cli_endtoend.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14536
creating a separate pr from https://github.com/SatelliteQE/robottelo/pull/13999 as master needs additional work
> [6.13.z] [6.15] cli e2e fix

- tests/foreman/api/test_subnet.py
Update in parameter name and value from subnet component updates 
the parameter in host inheriting that subnet
Updated changes in subnet name & value reflects in host inheriting that subnet
> host name & value updated with subnet

- pytest_fixtures/core/contenthosts.py
- pytest_plugins/fixture_markers.py
- tests/foreman/destructive/test_capsule_loadbalancer.py
- tests/foreman/maintain/test_upgrade.py
manual cherry-pick https://github.com/SatelliteQE/robottelo/pull/14317
> [6.13.z] Update Platform tests that have hard coded content host versions

- pytest_fixtures/core/contenthosts.py
- pytest_plugins/fixture_markers.py
- robottelo/constants/__init__.py
- tests/foreman/destructive/test_capsule_loadbalancer.py
- tests/foreman/maintain/test_upgrade.py
manual cherry-pick for https://github.com/SatelliteQE/robottelo/pull/14317
> [6.15.z] Update Platform tests that have hard coded content host versions

- tests/foreman/api/test_errata.py
Failed CP for #14494 to 6.14.z
This case is currently passing in 6.14.z, but review comments from PR above have brought enhancements.
These should fit into 6.14 nicely as well-
```
pytest: tests/foreman/api/test_errata.py::test_errata_installation_with_swidtags
```
> [6.14.z] Repair setup for package w/ swidtag, install and modular update

- tests/foreman/api/test_repository.py
> [6.14.z] Make test parametrization more readable (#14569)

- tests/foreman/ui/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14646
Just two fixes and one extension to address the component eval goals.
pytest: tests/foreman/ui/test_http_proxy.py
airgun: 1311
> [6.15.z] HTTP Proxy UI fixes

- tests/foreman/ui/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14646
Just two fixes and one extension to address the component eval goals.
pytest: tests/foreman/ui/test_http_proxy.py
airgun: 1311
> [6.14.z] HTTP Proxy UI fixes

- tests/foreman/api/test_notifications.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14674
Users with disabled account or disabled email were still receiving notifications about long-running tasks.
New test that verifies that these users don't receive the notification.
Bugzilla: https://bugzilla.redhat.com/2245056
> [6.15.z] notifications: no long tasks email for certain users

- tests/foreman/installer/test_installer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14519
Adding a test case to cover BZ1964539
Satellite and any of it's dependencies should not require package nmap-ncat.
The test is parametrized, so it can be easily extended to test different packages.
> [6.15.z] Add coverage for BZ1964539

- tests/foreman/endtoend/test_api_endtoend.py
changes to adjust the test for  SCA being default  (SAT-24365)
> sca for api e2e

- robottelo/constants/__init__.py
- tests/foreman/longrun/test_inc_updates.py
Failed auto-CP to 6.15.z
Original Pull Request #14749 
```
pytest: tests/foreman/longrun/test_inc_updates.py::test_positive_incremental_update_time
```
> [6.15.z] Test CV incremental update & publish time

- robottelo/cli/contentview.py
- robottelo/cli/host.py
- robottelo/cli/report_template.py
- robottelo/cli/repository.py
- robottelo/cli/syncplan.py
- robottelo/cli/template_input.py
- robottelo/cli/usergroup.py
- robottelo/cli/webhook.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14861
https://github.com/SatelliteQE/robottelo/pull/14437 didn't take into account other cli objects with custom create method, kudos to @vsedmik for spotting this
adding the timeout parameter
> [6.15.z] timeout parameters added to cli create methods

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14872
dropping some rhel6 hosts remaining in host parametrization
> [6.15.z] version selection for some host tests

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14872
dropping some rhel6 hosts remaining in host parametrization
> [6.13.z] version selection for some host tests

- pytest_fixtures/component/satellite_auth.py
- tests/foreman/destructive/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14511
null
> [6.15.z] Assert commands results. Remove CA download, machines already have it. Do not install a library through pip.

- pyproject.toml
- robottelo/exceptions.py
- robottelo/host_helpers/cli_factory.py
- robottelo/hosts.py
- robottelo/utils/decorators/func_locker.py
- robottelo/utils/decorators/func_shared/shared.py
- robottelo/utils/virtwho.py
- tests/foreman/ui/test_audit.py
- tests/foreman/ui/test_dashboard.py
- tests/foreman/ui/test_hostcollection.py
- tests/foreman/ui/test_repository.py
> [6.15.z] Preparations for ruff 0.4.1 (#14885)

- pyproject.toml
- robottelo/exceptions.py
- robottelo/host_helpers/cli_factory.py
- robottelo/hosts.py
- robottelo/utils/decorators/func_locker.py
- robottelo/utils/decorators/func_shared/shared.py
- robottelo/utils/virtwho.py
- tests/foreman/ui/test_audit.py
- tests/foreman/ui/test_dashboard.py
- tests/foreman/ui/test_hostcollection.py
- tests/foreman/ui/test_repository.py
> [6.14.z] Preparations for ruff 0.4.1 (#14885)

- pyproject.toml
- robottelo/exceptions.py
- robottelo/host_helpers/cli_factory.py
- robottelo/hosts.py
- robottelo/utils/decorators/func_locker.py
- robottelo/utils/decorators/func_shared/shared.py
- robottelo/utils/virtwho.py
- tests/foreman/ui/test_audit.py
- tests/foreman/ui/test_dashboard.py
- tests/foreman/ui/test_hostcollection.py
- tests/foreman/ui/test_repository.py
> [6.13.z] Preparations for ruff 0.4.1 (#14885)

- tests/foreman/ui/test_host.py
New test for correct page redirection after editing a host.
Component evaluation - SAT-21625
https://bugzilla.redhat.com/2166303
Requires https://github.com/SatelliteQE/airgun/pull/1362
> host edit: test correct page redirection

- pytest_fixtures/component/taxonomy.py
- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14844
New test for correct page redirection after editing a host.
Component evaluation - SAT-21625
https://bugzilla.redhat.com/2166303
Requires https://github.com/SatelliteQE/airgun/pull/1362
> [6.13.z] host edit: test correct page redirection

- tests/foreman/cli/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14465
Adding Closed loop for BZ#2250397 covering host registration with custom facts
> [6.15.z] Add test coverage for BZ#2250397

- tests/foreman/api/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14451
CC Automation/Comp Eval for CV work for BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2153523
> [6.15.z] CC Automation/Comp Eval coverage - promote CCV with specific registry_name

- tests/foreman/api/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14451
CC Automation/Comp Eval for CV work for BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2153523
> [6.14.z] CC Automation/Comp Eval coverage - promote CCV with specific registry_name

- tests/foreman/api/test_ansible.py
Missing coverage for BZ:1982698, where we verified ansible playbook job template with "hosts: localhost:
Add  test coverage for BZ:1982698, to verifiy ansible-playbook job template with "hosts: localhost"
> Add test coverage for BZ:1982698

- tests/foreman/api/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15022
Missing coverage for BZ:1982698, where we verified ansible playbook job template with "hosts: localhost:
Add  test coverage for BZ:1982698, to verifiy ansible-playbook job template with "hosts: localhost"
> [6.13.z] Add test coverage for BZ:1982698

- tests/foreman/cli/test_templatesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14860
paths seem to have changed, made some amendments
> [6.15.z] templatesync test fixes

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15090
Coverage for [BZ#2233162](https://bugzilla.redhat.com/show_bug.cgi?id=2233162) is missing
This PR.
`metadata.json` is the only exception where restrictive permissions are expected
pytest: tests/foreman/cli/test_satellitesync.py -k permissions
> [6.15.z] Add test for syncable export with restrictive permissions

- pytest_fixtures/component/repository.py
- requirements-optional.txt
- robottelo/cli/base.py
- robottelo/host_helpers/repository_mixins.py
- robottelo/host_helpers/satellite_mixins.py
- robottelo/hosts.py
- robottelo/utils/datafactory.py
- robottelo/utils/report_portal/portal.py
- tests/foreman/api/test_permission.py
- tests/foreman/cli/test_oscap.py
- tests/foreman/longrun/test_oscap.py
This PR backports #15114 to 6.12.z
Closes #15118 #14847
> [6.12.z] Bump sphinx-autoapi from 3.0.0 to 3.1.0

- tests/foreman/cli/test_contentview.py
Coverage for [BZ#2153523](https://bugzilla.redhat.com/show_bug.cgi?id=2153523) is missing.
This PR.
pytest: tests/foreman/cli/test_contentview.py -k pattern
> Add test case for CCV promotion to a non-default LCE

- tests/foreman/cli/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15120
Customer scenario coverage for bz#2015344
Check if non UTC datetime is processed correctly by hammer
> [6.15.z] test syncplan creation with custom timezone

- tests/foreman/api/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15149
In the past I have created this test as a spin-off from a larger test, but I didn't include all necessary setup parts for pull-mode to work. I humbly post this fix
Note that currently there's a reported bug preventing pull mode rex from working on rhel9 backend but the next snap should carry th fix
> [6.14.z] fix in pull mode longrun test

- tests/foreman/api/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15149
In the past I have created this test as a spin-off from a larger test, but I didn't include all necessary setup parts for pull-mode to work. I humbly post this fix
Note that currently there's a reported bug preventing pull mode rex from working on rhel9 backend but the next snap should carry th fix
> [6.15.z] fix in pull mode longrun test

- tests/foreman/destructive/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15171
Currently, test_positive_import_all_roles covers only admin scenario to import all roles via UI, and as part of component audit its suggest to modify this test to cover non-admin user scenario
> [6.15.z] Modify test_positive_import_all_roles to cover non-admin scenario

- tests/foreman/destructive/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15171
Currently, test_positive_import_all_roles covers only admin scenario to import all roles via UI, and as part of component audit its suggest to modify this test to cover non-admin user scenario
> [6.13.z] Modify test_positive_import_all_roles to cover non-admin scenario

- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_contentviewfilter.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/15043
Fixes https://github.com/SatelliteQE/robottelo/issues/15239
> [6.14.z] Updates for CV component eval

- tests/foreman/destructive/test_clone.py
Map SAT-10789 automation coverage to test_positive_clone_backup.
> Map test_positive_clone_backup with 6.16 Jira RFE

- tests/foreman/api/test_errata.py
- tests/foreman/api/test_subscription.py
- tests/foreman/cli/test_contentaccess.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/15314
Fixes https://github.com/SatelliteQE/robottelo/issues/15325
> [6.15.z] Add a couple of fixes for PIT

- tests/foreman/api/test_errata.py
- tests/foreman/api/test_subscription.py
- tests/foreman/cli/test_contentaccess.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/15314
Fixes https://github.com/SatelliteQE/robottelo/issues/15326
> [6.14.z] Add a couple of fixes for PIT

- tests/foreman/installer/test_installer.py
See https://github.com/SatelliteQE/robottelo/pull/15358
> [cherry-pick] Skip assertion for test_satellite_installation if SAT-21086 is open

- tests/foreman/api/test_ansible.py
- tests/foreman/api/test_organization.py
- tests/foreman/api/test_provisioning.py
- tests/foreman/sys/test_pulp3_filesystem.py
Fixes https://github.com/SatelliteQE/robottelo/issues/15368
See https://github.com/SatelliteQE/robottelo/pull/15359
> [6.13.z] [cherry-pick] Use jira issue to get bug status (#15359)

- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_reporttemplates.py
- tests/foreman/cli/test_activationkey.py
- tests/foreman/ui/test_containerimagetag.py
- tests/foreman/ui/test_contenthost.py
- tests/upgrades/test_virtwho.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/15370
Closes https://github.com/SatelliteQE/robottelo/issues/15374
> [6.15.z] Remove old skip_if for closed BZs

- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_reporttemplates.py
- tests/foreman/cli/test_activationkey.py
- tests/foreman/ui/test_containerimagetag.py
- tests/foreman/ui/test_contenthost.py
- tests/upgrades/test_virtwho.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/15370
Closes https://github.com/SatelliteQE/robottelo/issues/15373
> [6.14.z] Remove old skip_if for closed BZs

- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_reporttemplates.py
- tests/foreman/cli/test_activationkey.py
- tests/foreman/ui/test_contenthost.py
- tests/upgrades/test_virtwho.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/15370
Closes https://github.com/SatelliteQE/robottelo/issues/15372
> [6.13.z] Remove old skip_if for closed BZs

- robottelo/cli/base.py
- tests/robottelo/test_cli.py
Picking back changes made in #14703
> [6.15.z] Cherry-pick: Fix ssh command usage (#14703)

- robottelo/cli/base.py
- tests/robottelo/test_cli.py
Picking back changes made in https://github.com/SatelliteQE/robottelo/pull/14703
> [6.14.z] Cherry-pick: Fix ssh command usage (#14703)

- robottelo/cli/base.py
- tests/robottelo/test_cli.py
Picking back changes made in https://github.com/SatelliteQE/robottelo/pull/14703
> [6.13.z] Cherry-pick: Fix ssh command usage (#14703)

- tests/foreman/api/test_operatingsystem.py
Adding  OS Parameters to  OS end to end test
Dependent Nailgun PR: https://github.com/SatelliteQE/nailgun/pull/1191
> Add OS Parameters to end to end test

- tests/foreman/api/test_operatingsystem.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15412
Adding  OS Parameters to  OS end to end test
Dependent Nailgun PR: https://github.com/SatelliteQE/nailgun/pull/1191
> [6.14.z] Add OS Parameters to end to end test

- tests/foreman/ui/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15414
Automation for this BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2026701
Requires airgun PR https://github.com/SatelliteQE/airgun/pull/1426
This area of Robottelo actually has no tests, so in a separate PR I'm going to raise at least 1 or 2 small tests for the other functionality in this area, just to get some coverage. 
pytest: tests/foreman/ui/test_contentview.py -k 'test_file_cv_display'
airgun: 1426
> [6.15.z] [CC Automation] Add test covering interaction between File screen and published Content Views

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14672
Ansible role should be added and removed for new_ui hostgroup
Dependent PR:https://github.com/SatelliteQE/airgun/pull/1424
> [6.15.z] Add remove role for hostgroup

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14672
Ansible role should be added and removed for new_ui hostgroup
Dependent PR:https://github.com/SatelliteQE/airgun/pull/1424
> [6.14.z] Add remove role for hostgroup

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15428
[CC SAT-22048](https://issues.redhat.com/browse/SAT-22048)
Registration of the client system with Capsule is successful with the below error message.
`HTTP error code 422: Validation failed: Content view environment content facets is invalid`
This PR tests both the scenarios when settings `"validate_host_lce_content_source_coherence" is set to Yes/No`
N/A
> [6.15.z] CC-client registration with capsule based on setting value

- tests/foreman/cli/test_computeresource_libvirt.py
Combining various Libvirt tests into one e2e Libvirt CLI crud test and marking it for upgrade.
> Add Libvirt CLI crud test 

- tests/foreman/cli/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15543
Combining various Libvirt tests into one e2e Libvirt CLI crud test and marking it for upgrade.
> [6.14.z] Add Libvirt CLI crud test 

- tests/foreman/cli/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15543
Combining various Libvirt tests into one e2e Libvirt CLI crud test and marking it for upgrade.
> [6.13.z] Add Libvirt CLI crud test 

- tests/foreman/cli/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15543
Combining various Libvirt tests into one e2e Libvirt CLI crud test and marking it for upgrade.
> [6.15.z] Add Libvirt CLI crud test 

- .pre-commit-config.yaml
- robottelo/host_helpers/repository_mixins.py
- robottelo/utils/decorators/func_shared/shared.py
- tests/robottelo/test_cli.py
- tests/robottelo/test_decorators.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15545
updates:
- [github.com/astral-sh/ruff-pre-commit: v0.4.10 → v0.5.0](https://github.com/astral-sh/ruff-pre-commit/compare/v0.4.10...v0.5.0)
> [6.13.z] [pre-commit.ci] pre-commit autoupdate

- .pre-commit-config.yaml
- robottelo/host_helpers/repository_mixins.py
- robottelo/utils/decorators/func_shared/shared.py
- tests/robottelo/test_cli.py
- tests/robottelo/test_decorators.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15545
updates:
- [github.com/astral-sh/ruff-pre-commit: v0.4.10 → v0.5.0](https://github.com/astral-sh/ruff-pre-commit/compare/v0.4.10...v0.5.0)
> [6.15.z] [pre-commit.ci] pre-commit autoupdate

- .pre-commit-config.yaml
- robottelo/host_helpers/repository_mixins.py
- robottelo/utils/decorators/func_shared/shared.py
- tests/robottelo/test_cli.py
- tests/robottelo/test_decorators.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15545
updates:
- [github.com/astral-sh/ruff-pre-commit: v0.4.10 → v0.5.0](https://github.com/astral-sh/ruff-pre-commit/compare/v0.4.10...v0.5.0)
> [6.14.z] [pre-commit.ci] pre-commit autoupdate

- tests/foreman/cli/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15521
Missing  test coverage for SAT-24197, to verify foreman-discovery-image is built on latest up-to-date RHEL
Add test coverage for SAT-24197, to verify foreman-discovery-image is built on latest up-to-date RHEL
> [6.15.z] Add test coverage for SAT-24197

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14276
null
> [6.15.z] Close-loop BZ2217079

- robottelo/hosts.py
- tests/foreman/cli/test_repositories.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/15631
Fixes https://github.com/SatelliteQE/robottelo/issues/15636
> [6.15.z] Add a test case for pulp tasks purge

- tests/foreman/destructive/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14645
null
> [6.15.z] Fix TOTP generation. Fix what commit a5a5cd9e5e broke.

- tests/foreman/api/test_ansible.py
- tests/foreman/api/test_computeresource_azurerm.py
- tests/foreman/api/test_computeresource_gce.py
- tests/foreman/api/test_registration.py
- tests/foreman/cli/test_ansible.py
- tests/foreman/cli/test_fact.py
- tests/foreman/destructive/test_registration.py
- tests/foreman/ui/test_registration.py
Manual cherry pick of https://github.com/SatelliteQE/robottelo/pull/15671
Fixes https://github.com/SatelliteQE/robottelo/issues/15681
> [6.15.z] Add PIT marker for Rocket team components

- tests/foreman/api/test_ansible.py
- tests/foreman/api/test_computeresource_azurerm.py
- tests/foreman/api/test_computeresource_gce.py
- tests/foreman/api/test_registration.py
- tests/foreman/cli/test_ansible.py
- tests/foreman/cli/test_fact.py
- tests/foreman/destructive/test_registration.py
- tests/foreman/ui/test_registration.py
Manual cherry pick of https://github.com/SatelliteQE/robottelo/pull/15671
Fixes https://github.com/SatelliteQE/robottelo/issues/15679
> [6.14.z] Add PIT marker for Rocket team components

- tests/foreman/api/test_ansible.py
- tests/foreman/api/test_computeresource_azurerm.py
- tests/foreman/api/test_computeresource_gce.py
- tests/foreman/api/test_registration.py
- tests/foreman/cli/test_ansible.py
- tests/foreman/destructive/test_registration.py
- tests/foreman/ui/test_registration.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/15671
Fixes https://github.com/SatelliteQE/robottelo/issues/15680
> [6.13.z] Add PIT marker for Rocket team components

- conf/vmware.yaml.template
- tests/foreman/api/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14969
Adding VMware e2e api provisioning test.
> [6.15.z] Component Audit - VMware api e2e provisioning test

- tests/foreman/ui/test_package.py
Component audit - SAT-23377
As we do not have Satellite Tools repo any more we should use another repository 
Update repo name and other details details, `RH Satellite Capsule` is another repo we can use instead of `RH Satellite Tools`
No
```
pytest: tests/foreman/ui/test_package.py -k 'test_positive_rh_repo_search_and_check_file_list'
```
> update rh satellite repo with existing repo

- pytest_plugins/jira_comments.py
- Currently, the Jira test result comment is not escaped for special characters which makes some parts of the comment to be colored red. Also, the comment is not sorted which makes it less readable.
- Make Jira comment escape special characters.
- Sort test results based on the outcome.
- Color code test result outcome.
- SAT-26353 and SAT-26352
- See SAT-25230 and SAT-24796 for results/improvements.
- Depends on https://github.com/SatelliteQE/robottelo/pull/15686 (Do not merge before it)
> Color code and sort Jira comment based on the test result.

- pytest_plugins/jira_comments.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15687
- Currently, the Jira test result comment is not escaped for special characters which makes some parts of the comment to be colored red. Also, the comment is not sorted which makes it less readable.
- Make Jira comment escape special characters.
- Sort test results based on the outcome.
- Color code test result outcome.
- SAT-26353 and SAT-26352
- See SAT-25230 and SAT-24796 for results/improvements.
- Depends on https://github.com/SatelliteQE/robottelo/pull/15686 (Do not merge before it)
> [6.14.z] Color code and sort Jira comment based on the test result.

- pytest_plugins/jira_comments.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15687
- Currently, the Jira test result comment is not escaped for special characters which makes some parts of the comment to be colored red. Also, the comment is not sorted which makes it less readable.
- Make Jira comment escape special characters.
- Sort test results based on the outcome.
- Color code test result outcome.
- SAT-26353 and SAT-26352
- See SAT-25230 and SAT-24796 for results/improvements.
- Depends on https://github.com/SatelliteQE/robottelo/pull/15686 (Do not merge before it)
> [6.15.z] Color code and sort Jira comment based on the test result.

- pytest_plugins/jira_comments.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15687
- Currently, the Jira test result comment is not escaped for special characters which makes some parts of the comment to be colored red. Also, the comment is not sorted which makes it less readable.
- Make Jira comment escape special characters.
- Sort test results based on the outcome.
- Color code test result outcome.
- SAT-26353 and SAT-26352
- See SAT-25230 and SAT-24796 for results/improvements.
- Depends on https://github.com/SatelliteQE/robottelo/pull/15686 (Do not merge before it)
> [6.13.z] Color code and sort Jira comment based on the test result.

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15734
There is a customer facing bug which needs coverage, see the Related Issues.
This PR adds it.
https://issues.redhat.com/browse/SAT-23573
https://issues.redhat.com/browse/SAT-26458
pytest: tests/foreman/cli/test_satellitesync.py -k chunk
> [6.15.z] Add test a case for chhunked ISS import

- tests/foreman/cli/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15731
Removing a duplicate test as part of the upgrades comp eval
> [6.15.z] [Comp Eval] Removing Duplicate Test From Upgrades

- tests/foreman/cli/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15731
Removing a duplicate test as part of the upgrades comp eval
> [6.14.z] [Comp Eval] Removing Duplicate Test From Upgrades

- tests/foreman/cli/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15731
Removing a duplicate test as part of the upgrades comp eval
> [6.13.z] [Comp Eval] Removing Duplicate Test From Upgrades

- tests/foreman/api/test_rhc.py
- tests/foreman/cli/test_host.py
- tests/foreman/ui/test_host.py
Adding PIT markers for interop testing
> [KatelloTracer] Adding PIT markers

- tests/foreman/ui/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15488
After provisioning a new host the assigned Ansible roles from hostgroups
are not executed on the new host
The method below assigns a role to a hostgroup, then assigns the same hostgroup to a host, and provisions the host to verify that the role is correctly assigned.
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1439
> [6.15.z] The hostgroup Ansible job schedule along with host provisioning.

- tests/foreman/ui/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15488
After provisioning a new host the assigned Ansible roles from hostgroups
are not executed on the new host
The method below assigns a role to a hostgroup, then assigns the same hostgroup to a host, and provisions the host to verify that the role is correctly assigned.
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1439
> [6.14.z] The hostgroup Ansible job schedule along with host provisioning.

- tests/foreman/cli/test_rhcloud_inventory.py
- tests/foreman/ui/test_rhcloud_insights.py
- tests/foreman/ui/test_rhcloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15666
Adding PIT markers for RHCloud
> [6.15.z] [RHCloud]Adding PIT markers for interop

- tests/foreman/ui/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15183
null
> [6.15.z] Run the test with openldap

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15756
...in addition to existing markers in rex cli module
> [6.15.z] pit marker for rex

- tests/foreman/api/test_capsulecontent.py
Manual CP of https://github.com/SatelliteQE/robottelo/pull/15779
Fixes https://github.com/SatelliteQE/robottelo/issues/15781
> [6.15.z] Harden docker/podman asserts a bit

- tests/foreman/api/test_product.py
- tests/foreman/api/test_repositories.py
- tests/foreman/api/test_repository.py
- tests/foreman/api/test_repository_set.py
- tests/foreman/api/test_rhc.py
- tests/foreman/cli/test_repositories.py
- tests/foreman/cli/test_repository_set.py
- tests/foreman/cli/test_vm_install_products_package.py
- tests/foreman/destructive/test_repository.py
- tests/foreman/ui/test_repository.py
- tests/foreman/ui/test_sync.py
- tests/upgrades/test_repository.py
Updating all repository tests to be sca only 
SAT-24356
> [RFE] Updating all Repository tests to be SCA only

- tests/foreman/ui/test_registration.py
Organization and location was not set while host registration
Set organization and location in test while registering host
> Set organization and location in end_to_end test

- tests/foreman/api/test_computeresource_vmware.py
Adding coverage for provisioning VMware with NVME controllers(SAT-23558)
> Add coverage for VMware NVME controllers

- tests/foreman/ui/test_ansible.py
Ansible tasks which make changes on a host are displayed as notices in the config report, and failed Ansible tasks are displayed as errors in the config report
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1479
> Config report following both the failed and successful job runs.

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15770
Ansible tasks which make changes on a host are displayed as notices in the config report, and failed Ansible tasks are displayed as errors in the config report
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1479
> [6.15.z] Config report following both the failed and successful job runs.

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15770
Ansible tasks which make changes on a host are displayed as notices in the config report, and failed Ansible tasks are displayed as errors in the config report
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1479
> [6.14.z] Config report following both the failed and successful job runs.

- tests/foreman/api/test_ansible.py
Missing test coverage for ansible-playbook job with nonexisting_module, which covers BZ:2107577 and BZ:2028112
Add test coverage for ansible-playbook job with nonexisting_module, which covers BZ:2107577 and BZ:2028112
> Add test coverage for ansible-playbook job with nonexisting_module

- tests/foreman/api/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15952
Missing test coverage for ansible-playbook job with nonexisting_module, which covers BZ:2107577 and BZ:2028112
Add test coverage for ansible-playbook job with nonexisting_module, which covers BZ:2107577 and BZ:2028112
> [6.14.z] Add test coverage for ansible-playbook job with nonexisting_module

- tests/foreman/api/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15952
Missing test coverage for ansible-playbook job with nonexisting_module, which covers BZ:2107577 and BZ:2028112
Add test coverage for ansible-playbook job with nonexisting_module, which covers BZ:2107577 and BZ:2028112
> [6.15.z] Add test coverage for ansible-playbook job with nonexisting_module

- tests/foreman/cli/test_host.py
https://github.com/SatelliteQE/robottelo/pull/15949
Assertion error
adapt syntax
tests/foreman/cli/test_host.py::test_hammer_host_info_output
> Fix search syntax fixes forgotten in

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15989
https://github.com/SatelliteQE/robottelo/pull/15949
Assertion error
adapt syntax
tests/foreman/cli/test_host.py::test_hammer_host_info_output
> [6.16.z] Fix search syntax fixes forgotten in

- tests/foreman/cli/test_acs.py
- tests/foreman/cli/test_satellitesync.py
Proposing to add these PIT markers.
> Add PIT markers to ACS and ISS components

- tests/foreman/cli/test_acs.py
- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15651
Proposing to add these PIT markers.
> [6.14.z] Add PIT markers to ACS and ISS components

- tests/foreman/cli/test_acs.py
- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15651
Proposing to add these PIT markers.
> [6.15.z] Add PIT markers to ACS and ISS components

- tests/foreman/cli/test_acs.py
- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15651
Proposing to add these PIT markers.
> [6.16.z] Add PIT markers to ACS and ISS components

- tests/foreman/api/test_repositories.py
`test_positive_sync_kickstart_repo` test case needs update as per eval proposal - see the Related Issue.
This PR.
https://issues.redhat.com/browse/SAT-25998
pytest: tests/foreman/api/test_repositories.py -k sync_kickstart_repo
> Update kickstart repo sync test as per eval proposal

- tests/foreman/api/test_repositories.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16042
`test_positive_sync_kickstart_repo` test case needs update as per eval proposal - see the Related Issue.
This PR.
https://issues.redhat.com/browse/SAT-25998
pytest: tests/foreman/api/test_repositories.py -k sync_kickstart_repo
> [6.16.z] Update kickstart repo sync test as per eval proposal

- tests/foreman/cli/test_repository.py
`test_positive_synchronize_auth_yum_repo`
`test_positive_create_with_auth_yum_repo`
new test case: `test_positive_create_and_sync_with_auth_yum_repo`
https://issues.redhat.com/browse/SAT-25978
pytest: tests/foreman/cli/test_repository.py -k 'test_positive_create_and_sync_with_auth_yum_repo'
> merge cli scenarios - yum repo creation & sync with auth

- tests/foreman/ui/test_remoteexecution.py
Cherry-pick of https://github.com/SatelliteQE/robottelo/pull/15980
New test for the new job invocaton details page.
Requires https://github.com/SatelliteQE/airgun/pull/1533
This is an experimantal feature/tech preview and it is still not fully completed.
Other functionality an content will be added in later phases.
> [6.16.z] test for new job invocation details page

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15976
Test exercising the new Bulk CVE assignment action in the All Hosts page.  Test is probably not perfectly formatted, but it gets the job done. Appreciate any feedback.
Requires: https://github.com/SatelliteQE/airgun/pull/1514
> [6.16.z] [6.16] Add test for All Hosts CVE Bulk action

- tests/foreman/longrun/test_oscap.py
> adding jira marker to test

- tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16107
for integration
> [6.16.z] adding jira marker to test

- tests/foreman/cli/test_host.py
- tests/foreman/ui/test_host.py
Test exercising All Hosts Bulk Errata wizard, applying an erratum to multiple hosts. 
Requires: https://github.com/SatelliteQE/airgun/pull/1526
> [6.16]Add test for All Hosts bulk errata apply

- tests/foreman/ui/test_host.py
Simple test case checking that the "New UI" button links properly to the all hosts page.
Requires: https://github.com/SatelliteQE/airgun/pull/1536
> [6.16] Small test checking out the New UI button

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16113
Simple test case checking that the "New UI" button links properly to the all hosts page.
Requires: https://github.com/SatelliteQE/airgun/pull/1536
> [6.16.z] [6.16] Small test checking out the New UI button

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16031
Test exercising All Hosts Bulk Errata wizard, applying an erratum to multiple hosts. 
Requires: https://github.com/SatelliteQE/airgun/pull/1526
> [6.16.z] [6.16]Add test for All Hosts bulk errata apply

- tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16070
null
> [6.16.z] Do not set LE and CV, it's already done. Put the scap content to the right org.

- pytest_fixtures/component/provision_pxe.py
> Update pxeless host workflows in provisioning

- robottelo/utils/virtwho.py
remove host subscription and update host_status check for sca-only
Test Case : PASS
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_deploy_configure_by_id_script --disable-pytest-warnings -q
..                                                                                                                                         [100%]
2 passed, 16 deselected, 24 warnings in 906.52s (0:15:06)
```
> remove host subscription and update host_status check for sca-only

- pytest_fixtures/component/provision_pxe.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16029
> [6.14.z] Update pxeless host workflows in provisioning

- pytest_fixtures/component/provision_pxe.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16029
> [6.16.z] Update pxeless host workflows in provisioning

- pytest_fixtures/component/provision_pxe.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16029
> [6.13.z] Update pxeless host workflows in provisioning

- pytest_fixtures/component/provision_pxe.py
> [6.15.z] Update pxeless host workflows in provisioning

- .pre-commit-config.yaml
backports #16071 to 6.16.z
fixes #16076
> [6.16.z] [pre-commit.ci] pre-commit autoupdate

- tests/foreman/ui/test_contentcredentials.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16073
null
> [6.16.z] [Comp Eval] Remove duplicate repo discovery test

- tests/foreman/ui/test_contentcredentials.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16073
null
> [6.15.z] [Comp Eval] Remove duplicate repo discovery test

- tests/foreman/ui/test_contentcredentials.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16073
null
> [6.14.z] [Comp Eval] Remove duplicate repo discovery test

- tests/foreman/ui/test_contentcredentials.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16073
null
> [6.13.z] [Comp Eval] Remove duplicate repo discovery test

- pytest_fixtures/component/taxonomy.py
- robottelo/host_helpers/cli_factory.py
- robottelo/hosts.py
- tests/foreman/api/test_subscription.py
- tests/foreman/cli/test_subscription.py
- tests/foreman/ui/test_subscription.py
- tests/upgrades/test_subscription.py
Updating Subscription Management Component to be SCA only
SAT-24357
> [RFE] Updating Subscription Management to be SCA Only

- tests/foreman/cli/test_capsulecontent.py
Failed CP of #16074 
The test (`test_positive_exported_imported_content_sync`) did not exist yet in 6.15.z, 
but I vote we include this one for n-1 or n-2.
```
pytest: tests/foreman/cli/test_capsulecontent.py::test_positive_exported_imported_content_sync
```
> [6.15.z] CP CapsuleContent Cover BZ 2186765

- pytest_fixtures/component/taxonomy.py
- robottelo/host_helpers/cli_factory.py
- robottelo/hosts.py
- tests/foreman/api/test_subscription.py
- tests/foreman/cli/test_subscription.py
- tests/foreman/ui/test_subscription.py
- tests/upgrades/test_subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15637
Updating Subscription Management Component to be SCA only
SAT-24357
> [6.16.z] [RFE] Updating Subscription Management to be SCA Only

- tests/foreman/destructive/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16170
null
> [6.16.z] Fix bind name

- tests/foreman/destructive/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16170
null
> [6.15.z] Fix bind name

- tests/foreman/api/test_docker.py
* hardcoded credentials
* no check on return value
* read credentials form settings file
* assert on successful push
tests/foreman/api/test_docker.py::TestPodman
> Small improvements for podman api tests

- tests/foreman/api/test_docker.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15959
* hardcoded credentials
* no check on return value
* read credentials form settings file
* assert on successful push
tests/foreman/api/test_docker.py::TestPodman
> [6.16.z] Small improvements for podman api tests

- tests/foreman/api/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15884
Last test for Podman push feature for 6.16, requires a new version of `smart_proxy_container_gateway` to be released.
> [6.16.z] [6.16]Add test for podman push on capsule

- tests/foreman/cli/test_remoteexecution.py
- tests/foreman/cli/test_satellitesync.py
closes https://github.com/SatelliteQE/robottelo/issues/16175
closes https://github.com/SatelliteQE/robottelo/issues/16066
> adding customerscenario tags

- pytest_fixtures/component/provision_vmware.py
- tests/foreman/api/test_computeresource_vmware.py
Component Audit: Adding test for VMware PXE discovery provisioning
> Add test for VMware PXE discovery provisioning

- pytest_fixtures/component/provision_vmware.py
- tests/foreman/api/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15927
Component Audit: Adding test for VMware PXE discovery provisioning
> [6.16.z] Add test for VMware PXE discovery provisioning

- conf/robottelo.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/maintain/test_advanced.py
Fixes https://github.com/SatelliteQE/robottelo/issues/16255 cherry-pick https://github.com/SatelliteQE/robottelo/pull/16225
> [6.16.z] Move SAT_NON_GA_VERSIONS constant to robottelo config (#16225)

- conf/robottelo.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/maintain/test_advanced.py
Fixes https://github.com/SatelliteQE/robottelo/issues/16256 cherry-pick https://github.com/SatelliteQE/robottelo/pull/16225
> [6.15.z] Move SAT_NON_GA_VERSIONS constant to robottelo config (#16225)

- conf/robottelo.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/maintain/test_advanced.py
Fixes https://github.com/SatelliteQE/robottelo/issues/16254 cherry-pick https://github.com/SatelliteQE/robottelo/pull/16225
> [6.14.z] Move SAT_NON_GA_VERSIONS constant to robottelo config (#16225)

- tests/foreman/cli/test_activationkey.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16220
Assertion errors detected but not a product bug; also different automation problems spotted.
Fix it in robottelo:
1. In `test_positive_usage_limit` we don't need assert particular result code, we need to ensure the registrations fails and we got the proper message.
2. Interference between `test_positive_add_custom_product` and `test_positive_create_content_and_check_enabled` causes fail since `content` had item from the previously run test (not only `[0]`). We can go `function_org` or sort the `content` based on `id`. I've chosen the first option though the second one worked too.
3. `conf/client.yaml` has been removed as obsoleted but one decorator using that survived, making `test_positive_update_aks_to_chost` fail. …
> [6.16.z] Fix AK tests assertion errors

- tests/foreman/ui/test_host.py
Trying out a small workaround for a manage columns bug.
> Small test fix for manage columns

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16265
Trying out a small workaround for a manage columns bug.
> [6.16.z] Small test fix for manage columns

- tests/foreman/ui/test_organization.py
> adding jira skip for org label issue

- tests/foreman/ui/test_organization.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16275
some bugkeeping
> [6.16.z] adding jira skip for org label issue

- tests/foreman/cli/test_host.py
Manual cherry-pick of @jeremylenz's #15880 
We got that merged after branching so we need to CP it back to 6.16.z.
> [6.16.z] Add tests for multiCV assignment with Hammer

- tests/foreman/data/hammer_commands.json
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16316
hammer changes found in 6.16 compared to the previous version. The list was shared with dev for check. Prt may fail in master, running anyway for automerge
> [6.16.z] hammer commands updated for 6.16

- pytest_fixtures/component/provision_pxe.py
> Fix pxeless discovery test

- pytest_fixtures/component/leapp_client.py
- tests/foreman/cli/test_leapp_client.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/15571 
https://github.com/SatelliteQE/robottelo/pull/15571
> Merge Leapp tests to single test and Refactor it (#15571)

- tests/foreman/destructive/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16353
null
> [6.15.z] Fix action order so the user is not missing when adding a role to them

- tests/foreman/api/test_remoteexecution.py
cherry pick of https://github.com/SatelliteQE/robottelo/pull/16321
closes #16451
> 6.13 changes to the capsule upgrade playbook test

- tests/foreman/api/test_remoteexecution.py
cherry pick of  #16321
closes #16454
> 6.16 changes to the capsule upgrade playbook test

- tests/foreman/destructive/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16353
null
> [6.16.z] Fix action order so the user is not missing when adding a role to them

- tests/foreman/ui/test_reporttemplates.py
Test for generating host - applied errata report with registered users
> [CompEval] test for Available errata for registered users

- tests/foreman/ui/test_reporttemplates.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15665
Test for generating host - applied errata report with registered users
> [6.15.z] [CompEval] test for Available errata for registered users

- tests/foreman/ui/test_reporttemplates.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15665
Test for generating host - applied errata report with registered users
> [6.16.z] [CompEval] test for Available errata for registered users

- tests/foreman/longrun/test_oscap.py
moved the identical parts from the tests to the common function, enabling parametrization for the remediation test
> Scap refactor

- tests/foreman/destructive/test_installer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16522
Missing test coverage for SAT-26014
Adding a destructive test to cover SAT-26014
> [6.16.z] Add test coverage for SAT-26014

- pytest_fixtures/component/satellite_auth.py
- tests/foreman/ui/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16382
null
> [6.15.z] Fix username for AD and IDM. Fix session contexts.

- pytest_fixtures/component/satellite_auth.py
- tests/foreman/ui/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16382
null
> [6.16.z] Fix username for AD and IDM. Fix session contexts.

- tests/foreman/cli/test_contentview.py
possible key error in if clause of list comprehension
see code
tests to run:
```
tests/foreman/cli/test_contentview.py::TestContentView::test_negative_promote_default_cv 
```
> Fix possible KeyError and remove debug statement

- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16548
possible key error in if clause of list comprehension
see code
tests to run:
```
tests/foreman/cli/test_contentview.py::TestContentView::test_negative_promote_default_cv 
```
> [6.16.z] Fix possible KeyError and remove debug statement

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16557
null
> [6.16.z] Fix AD setup on RHEL 9. Use packages documentation calls for in the given version.

- pytest_fixtures/component/rh_cloud.py
- robottelo/hosts.py
- tests/foreman/cli/test_http_proxy.py
Parent PR: https://github.com/SatelliteQE/robottelo/pull/16497
> [6.16.z] Cherrypick configure insights client

- pytest_fixtures/component/provision_pxe.py
- tests/foreman/api/test_discoveredhost.py
Combining discovery reboot and reboot_all test into one
> Combine discovery reboot and reboot_all test

- tests/foreman/cli/test_remoteexecution.py
SAT-28435 (occurs for all regular rex runs, not anisble or pull mode)
some negative testing
> negative test for regular rex run

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16546
SAT-28435 (occurs for all regular rex runs, not anisble or pull mode)
some negative testing
> [6.16.z] negative test for regular rex run

- .github/workflows/auto_branching.yml
- .github/workflows/auto_cherry_pick.yml
- .github/workflows/auto_cherry_pick_merged.yaml
- .github/workflows/prt_result.yml
Reverts SatelliteQE/robottelo#16631
> Revert "Bump thollander/actions-comment-pull-request from 2 to 3"

- conftest.py
- pytest_fixtures/component/leapp_client.py
- tests/foreman/ui/test_leapp_client.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15811
Automated BZ 2168494
> [6.15.z] Add automation for BZ 2168494

- conftest.py
- pytest_fixtures/component/leapp_client.py
- tests/foreman/ui/test_leapp_client.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15811
Automated BZ 2168494
> [6.13.z] Add automation for BZ 2168494

- robottelo/cli/ansible.py
- robottelo/cli/host.py
- robottelo/hosts.py
- tests/foreman/cli/test_ansible.py
- tests/foreman/ui/test_ansible.py
(cherry picked from commit d14548b5de3660496b2dfcbf50f1fe7a142547da)
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/16431/files
Fixes https://github.com/SatelliteQE/robottelo/issues/16622
> [6.14.z] Automate test_positive_ansible_variables_imported_with_roles

- tests/foreman/destructive/test_clone.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16683
Added coverage for SAT-27907.
Reordered steps to match documentation - Pulp content has to be copied to target machine before the satellite-clone is executed.
Added steps that occupy source satellite userids on target satellite server to check that satellite-clone changes ownership and permissions.
> [6.16.z] reorder and improve clone test to match docs

- tests/foreman/cli/test_registration.py
Missing test scenario for SAT-23047
Verifies : SAT-23047
> Add a test to verify default location set for registered host

- tests/foreman/cli/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16657
Missing test scenario for SAT-23047
Verifies : SAT-23047
> [6.16.z] Add a test to verify default location set for registered host

- conf/subscription.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/api/test_eol_banner.py
cherry pick of 
https://github.com/SatelliteQE/robottelo/pull/13253
> [6.13.z] eol version check (#13253)

- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16728
* FAM tests need Puppet modules for two things:
* Testing of assignment of Puppet classes to hosts and hostgroups (`host` and `hostgroup` tests)
* Testing of import of Puppet classes (`puppetclasses_import` test)
* For assignment, those Puppet classes need to be already imported into Foreman
* For importing "obviously" not
* Additionally, `puppet module install <module>` requires access to Puppet Forge, which might or might not be present during the `fam-test-setup` workflow
* Instead of handling this in the `fam-test-setup` workflow, move the whole setup to `robottelo`
* Use `puppetlabs-ntp` from https://github.com/SatelliteQE/fedorapeople-repos/, as we use parameters from that module to test parameter assignment
* …
> [6.16.z] prepare puppet classes needed for FAM tests in setup_fam

- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16728
* FAM tests need Puppet modules for two things:
* Testing of assignment of Puppet classes to hosts and hostgroups (`host` and `hostgroup` tests)
* Testing of import of Puppet classes (`puppetclasses_import` test)
* For assignment, those Puppet classes need to be already imported into Foreman
* For importing "obviously" not
* Additionally, `puppet module install <module>` requires access to Puppet Forge, which might or might not be present during the `fam-test-setup` workflow
* Instead of handling this in the `fam-test-setup` workflow, move the whole setup to `robottelo`
* Use `puppetlabs-ntp` from https://github.com/SatelliteQE/fedorapeople-repos/, as we use parameters from that module to test parameter assignment
* …
> [6.15.z] prepare puppet classes needed for FAM tests in setup_fam

- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16728
* FAM tests need Puppet modules for two things:
* Testing of assignment of Puppet classes to hosts and hostgroups (`host` and `hostgroup` tests)
* Testing of import of Puppet classes (`puppetclasses_import` test)
* For assignment, those Puppet classes need to be already imported into Foreman
* For importing "obviously" not
* Additionally, `puppet module install <module>` requires access to Puppet Forge, which might or might not be present during the `fam-test-setup` workflow
* Instead of handling this in the `fam-test-setup` workflow, move the whole setup to `robottelo`
* Use `puppetlabs-ntp` from https://github.com/SatelliteQE/fedorapeople-repos/, as we use parameters from that module to test parameter assignment
* …
> [6.14.z] prepare puppet classes needed for FAM tests in setup_fam

- tests/foreman/ui/test_discoveryrule.py
Few tests fails to do teardown, causing other tests to fail after https://github.com/SatelliteQE/robottelo/pull/15783
Fix Discovery rule tests with teardown
> Fix Discovery rule tests with teardown

- tests/foreman/ui/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16743
Few tests fails to do teardown, causing other tests to fail after https://github.com/SatelliteQE/robottelo/pull/15783
Fix Discovery rule tests with teardown
> [6.16.z] Fix Discovery rule tests with teardown

- tests/foreman/ui/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16743
Few tests fails to do teardown, causing other tests to fail after https://github.com/SatelliteQE/robottelo/pull/15783
Fix Discovery rule tests with teardown
> [6.15.z] Fix Discovery rule tests with teardown

- robottelo/constants/__init__.py
- robottelo/hosts.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/16575
Fixes https://github.com/SatelliteQE/robottelo/issues/16811
> [6.14.z] Add conditioning for pool attach

- tests/foreman/cli/test_host.py
> fixes in host asserts

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16943
some assertions fixed
> [6.16.z] fixes in host asserts

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15539
RFE `SAT-9132` adds new search options for hosts.
Two new tests were added for searching hosts with these new options:
- reported data, like, BIOS vendor, version, etc.
- new alias `configuration_status` for `status` 
Requires
~~https://github.com/SatelliteQE/airgun/pull/1453~~
https://github.com/SatelliteQE/airgun/pull/1603
https://github.com/SatelliteQE/nailgun/pull/1202
> [6.16.z] host: tests for new search options

- tests/foreman/sys/test_fam.py
cherry-pick of #16936 for 6.15.z
> [6.15.z] Create fake galaxy.yml to make the FAM Makefile happy (#16936)

- requirements.txt
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/17021
> Unpin wrapanapi version from requirements file (#17049)

- requirements.txt
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/17022
> [6.14.z]Unpin wrapanapi version from requirements file (#17049)

- tests/foreman/api/test_rhcloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16913
null
> [6.15.z] [CC Automation] Test for Scheduled insights sync job

- conf/jira.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
> Update Jira ON_QA status for Jira issue handler

- tests/foreman/destructive/test_ldapauthsource.py
pytest: tests/foreman/destructive/test_ldapauthsource.py::test_rhsso_login_using_hammer
> Fix an assert in RHSSO test

- tests/foreman/api/test_rhcloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17146
close https://github.com/SatelliteQE/robottelo/issues/17109
> [6.15.z] customerscenario tags for test_rhcloud_scheduled_insights_sync

- tests/foreman/api/test_rhcloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17146
close https://github.com/SatelliteQE/robottelo/issues/17109
> [6.16.z] customerscenario tags for test_rhcloud_scheduled_insights_sync

- tests/foreman/cli/test_reporttemplates.py
- tests/foreman/ui/test_jobtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17091
null
> [6.16.z] CVE-2024-8553

- tests/foreman/cli/test_reporttemplates.py
- tests/foreman/ui/test_jobtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17091
null
> [6.15.z] CVE-2024-8553

- pytest_fixtures/core/sat_cap_factory.py
- tests/foreman/installer/test_installer.py
(cherry picked from commit c170b84214e2ce4928af4ca744a64df6c37ee607)
> Provide better error output for test_satellite_installation (pick #17105)

- tests/foreman/endtoend/test_api_endtoend.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17238
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/16914/files
Fixes https://github.com/SatelliteQE/robottelo/issues/16950
> [6.13.z]Update API e2e test to use RegistrationCommand entity to register

- tests/foreman/endtoend/test_api_endtoend.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17238
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/16914/files
Fixes https://github.com/SatelliteQE/robottelo/issues/16949
> [6.14.z] Update API e2e test to use RegistrationCommand entity to register

- robottelo/host_helpers/satellite_mixins.py
- tests/foreman/cli/test_satellitesync.py
Currently we test the ISS export/import with one Satellite instance only, so the import is performed just in a different org on the same Satellite which does not fully exercise the pulp backend.
This PR adds second Satellite instance for import and related function_org and cleanup fixtures, extends the `move_pulp_archive` helper to move archives between instances when needed and adapts two test cases to use the new approach.
- `function_synced_docker_repo` fixture currently fails to sync, which affects one of the adapted test case. The root cause is unrelated and discussed offline.
- `test_postive_export_import_cv_with_mixed_content_repos` could be extended with `flatpak_contenthost` and content consumption could be tested aka E2E. This will be part of another PR.
- Consider …
> Split export and import SAT instances in ISS

- robottelo/constants/__init__.py
- tests/foreman/ui/test_repository.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/16930
Fixes https://github.com/SatelliteQE/robottelo/issues/17256
> [6.16.z] Fix and extend the RH recommended repos case

- robottelo/constants/__init__.py
- tests/foreman/ui/test_repository.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/16930
Fixes https://github.com/SatelliteQE/robottelo/issues/17255
> [6.15.z] Fix and extend the RH recommended repos case

- tests/foreman/cli/test_bootdisk.py
Adding test for subnet disk image download - SAT-23549
Fixes: https://github.com/SatelliteQE/robottelo/issues/17227
> [6.16.z] Add test for subnet disk image download

- tests/foreman/cli/test_bootdisk.py
Adding test for subnet disk image download - SAT-23549
Fixes: https://github.com/SatelliteQE/robottelo/issues/17225
> [6.15.z] Add test for subnet disk image download

- robottelo/host_helpers/satellite_mixins.py
- tests/upgrades/test_errata.py
- tests/upgrades/test_subscription.py
Cherrypick of PR: #17183
(cherry picked from commit caff4dd5b45db3bf6a135184053253634eebbd60)
Fixes #17259
> [6.14.z] Fix legacy errata upgrade scenario tests (#17183)

- robottelo/host_helpers/satellite_mixins.py
- tests/upgrades/test_errata.py
- tests/upgrades/test_repository.py
- tests/upgrades/test_subscription.py
Cherrypick of PR: #17183
(cherry picked from commit caff4dd5b45db3bf6a135184053253634eebbd60)
Fixes #17257
> [6.16.z] Fix legacy errata upgrade scenario tests (#17183)

- robottelo/host_helpers/satellite_mixins.py
- tests/upgrades/test_errata.py
- tests/upgrades/test_subscription.py
Cherrypick of PR: #17183
(cherry picked from commit caff4dd5b45db3bf6a135184053253634eebbd60)
Fixes #17258
> [6.15.z] Fix legacy errata upgrade scenario tests (#17183)

- conf/rhbk.yaml.template
- pytest_fixtures/component/satellite_auth.py
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- robottelo/hosts.py
- tests/foreman/destructive/test_ldap_authentication.py
- tests/foreman/destructive/test_ldapauthsource.py
Make changes so RHSSO tests become parametrized and work for both RHSSO and RHBK
Manual cherry pick.
> [6.15] RHBK support (#17338)

- tests/foreman/api/test_computeresource_vmware.py
- tests/foreman/api/test_discoveredhost.py
- tests/foreman/api/test_provisioning.py
- tests/foreman/cli/test_discoveredhost.py
- tests/foreman/ui/test_discoveredhost.py
Missed fixing some of the tests in previous pr -> https://github.com/SatelliteQE/robottelo/pull/17571
> Fix remaining provisioning tests failing due to missing _broker_facts

- tests/foreman/api/test_computeresource_vmware.py
- tests/foreman/api/test_discoveredhost.py
- tests/foreman/api/test_provisioning.py
- tests/foreman/cli/test_discoveredhost.py
- tests/foreman/ui/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17581
Missed fixing some of the tests in previous pr -> https://github.com/SatelliteQE/robottelo/pull/17571
> [6.16.z] Fix remaining provisioning tests failing due to missing _broker_facts

- pytest_fixtures/component/provision_capsule_pxe.py
- pytest_fixtures/component/provision_pxe.py
The provisioning tests are failing due to the recent sat workflow update
Fix/update the tests
> Fix failing provisioning tests due to the sat workflow update

- pytest_fixtures/component/provision_capsule_pxe.py
- pytest_fixtures/component/provision_pxe.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17595
The provisioning tests are failing due to the recent sat workflow update
Fix/update the tests
> [6.14.z] Fix failing provisioning tests due to the sat workflow update

- tests/foreman/cli/test_docker.py
close https://github.com/SatelliteQE/robottelo/issues/17655
> customerscenario tag for docker test

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17519
Trying to make a couple of problematic tests behave more predictably.
Asserting for rex status instead of result, removing some time assertions
> [6.15.z] less flakiness in rex module

- .pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17672
updates:
- [github.com/astral-sh/ruff-pre-commit: v0.9.6 → v0.9.7](https://github.com/astral-sh/ruff-pre-commit/compare/v0.9.6...v0.9.7)
- [github.com/gitleaks/gitleaks: v8.23.3 → v8.24.0](https://github.com/gitleaks/gitleaks/compare/v8.23.3...v8.24.0)
> [6.17.z] [pre-commit.ci] pre-commit autoupdate

- conf/container.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_contentview.py
- tests/foreman/api/test_contentviewfilter.py
- tests/foreman/api/test_docker.py
- tests/foreman/api/test_http_proxy.py
- tests/foreman/api/test_product.py
- tests/foreman/api/test_repository.py
- tests/foreman/cli/test_container_management.py
- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_contentviewfilter.py
- tests/foreman/cli/test_docker.py
- tests/foreman/cli/test_repository.py
- tests/foreman/cli/test_satellitesync.py
- tests/foreman/cli/test_vm_install_products_package.py
- tests/foreman/ui/test_activationkey.py
- tests/foreman/ui/test_containerimagetag.py
- tests/foreman/ui/test_contentview.py
- tests/foreman/ui/test_http_proxy.py
- tests/foreman/ui/test_repository.py
- tests/foreman/ui/test_sync.py
https://github.com/SatelliteQE/robottelo/issues/17682
> Make container content related settings configurable (#17570)

- conf/container.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_contentview.py
- tests/foreman/api/test_contentviewfilter.py
- tests/foreman/api/test_docker.py
- tests/foreman/api/test_http_proxy.py
- tests/foreman/api/test_product.py
- tests/foreman/api/test_repository.py
- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/cli/test_container_management.py
- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_contentviewfilter.py
- tests/foreman/cli/test_docker.py
- tests/foreman/cli/test_repository.py
- tests/foreman/cli/test_satellitesync.py
- tests/foreman/cli/test_vm_install_products_package.py
- tests/foreman/ui/test_activationkey.py
- tests/foreman/ui/test_containerimagetag.py
- tests/foreman/ui/test_contentview_old.py
- tests/foreman/ui/test_http_proxy.py
- tests/foreman/ui/test_repository.py
- tests/foreman/ui/test_sync.py
https://github.com/SatelliteQE/robottelo/issues/17685
> 6.15.z container settings

- tests/foreman/destructive/test_infoblox.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17340
Fixing IPv6 Infoblox tests
- Removing `isc_dhcp` as we don't really test it with infoblox integration and we don't document that as well
- The domain created is already present in the IPv6 satellite hence adding condition to check first and create it if not present
Satellite Jenkins MR: 1618
> [6.17.z] Fix IPv6 Infoblox tests

- robottelo/config/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17701
Just saw an issue in the robottelo CI where this popped up.
```python
File "/home/runner/work/robottelo/robottelo/robottelo/config/__init__.py", line 25, in get_settings
if builtins.__sphinx_build__:
^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'builtins' has no attribute '__sphinx_build__'
```
If we simply make this a getattr call, then we don't have to worry about that attribute being present.
> [6.14.z] Make the sphinx check more resilient

- robottelo/config/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17701
Just saw an issue in the robottelo CI where this popped up.
```python
File "/home/runner/work/robottelo/robottelo/robottelo/config/__init__.py", line 25, in get_settings
if builtins.__sphinx_build__:
^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'builtins' has no attribute '__sphinx_build__'
```
If we simply make this a getattr call, then we don't have to worry about that attribute being present.
> [6.17.z] Make the sphinx check more resilient

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17726
null
> [6.15.z] settings.sso does not exist

- tests/foreman/data/hammer_commands.json
Add cli changes for 6.17, those have been approved via mailing list
> hammer commands updated for 6.17

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17726
null
> [6.16.z] settings.sso does not exist

- tests/foreman/data/hammer_commands.json
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17758
Add cli changes for 6.17, those have been approved via mailing list
> [6.17.z] hammer commands updated for 6.17

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17726
null
> [6.17.z] settings.sso does not exist

- pytest_fixtures/core/contenthosts.py
- pytest_plugins/fixture_markers.py
- robottelo/hosts.py
- tests/foreman/api/test_remoteexecution.py
- tests/foreman/cli/test_leapp_client.py
- tests/foreman/cli/test_remoteexecution.py
- tests/foreman/destructive/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17551
follow up from https://github.com/SatelliteQE/robottelo/pull/16789
fixed version selection and de-duplicated it. Added rhel repos that are now needed for new versions of yggdrasil
> [6.17.z] more adjustments for pull rex on rhel10

- tests/foreman/sys/test_fam.py
The FAM test relies on galaxy.ansible.com being reachable, which it sometimes is not.
This is especially a problem in IPv6 test environments which have no direct internet access.
Fake a role instead of downloading one.
> create a fake ansible role instead of pulling one from the internet

- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17826
The FAM test relies on galaxy.ansible.com being reachable, which it sometimes is not.
This is especially a problem in IPv6 test environments which have no direct internet access.
Fake a role instead of downloading one.
> [6.16.z] create a fake ansible role instead of pulling one from the internet

- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17826
The FAM test relies on galaxy.ansible.com being reachable, which it sometimes is not.
This is especially a problem in IPv6 test environments which have no direct internet access.
Fake a role instead of downloading one.
> [6.17.z] create a fake ansible role instead of pulling one from the internet

- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17826
The FAM test relies on galaxy.ansible.com being reachable, which it sometimes is not.
This is especially a problem in IPv6 test environments which have no direct internet access.
Fake a role instead of downloading one.
> [6.15.z] create a fake ansible role instead of pulling one from the internet

- tests/foreman/ui/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17834
We have recently updated our HTTP proxy instances, but the new version stores the user in access.log as base64-encoded string. And we assert the user presence in the log.
Assert the base64-encoded user instead.
```
pytest: tests/foreman/ui/test_http_proxy.py -k test_http_proxy_containing_special_characters
```
> [6.16.z] Assert base64 encoded user in squid access.log

- tests/foreman/ui/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17834
We have recently updated our HTTP proxy instances, but the new version stores the user in access.log as base64-encoded string. And we assert the user presence in the log.
Assert the base64-encoded user instead.
```
pytest: tests/foreman/ui/test_http_proxy.py -k test_http_proxy_containing_special_characters
```
> [6.15.z] Assert base64 encoded user in squid access.log

- .github/workflows/pull_request.yml
- scripts/config_helpers.py
- scripts/customer_scenarios.py
- scripts/fixture_cli.py
- scripts/tokenize_customer_scenario.py
- scripts/validate_config.py
- setup.py
This PR backports #17878 to 6.14.z
> [6.14.z] Backport of #17878

- .github/workflows/pull_request.yml
- scripts/config_helpers.py
- scripts/customer_scenarios.py
- scripts/fixture_cli.py
- scripts/tokenize_customer_scenario.py
- scripts/validate_config.py
- setup.py
This PR backports #17878 to 6.16.z
> [6.16.z] Backport of #17878

- tests/foreman/api/test_provisioningtemplate.py
Add AAP2.5/latest parameterization along with legacy/AAP 2.4 to validate above change with existing AAP provisioning-template test
> Add AAP2.5 parameterization in AAP provisioning-template test

- tests/foreman/api/test_provisioningtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17942
Add AAP2.5/latest parameterization along with legacy/AAP 2.4 to validate above change with existing AAP provisioning-template test
> [6.17.z] Add AAP2.5 parameterization in AAP provisioning-template test

- tests/foreman/ui/test_ldap_authentication.py
Settings structure has been changed in https://github.com/SatelliteQE/robottelo/pull/16536 , fix in this test
> Fix groups setting location after #16536

- pytest_fixtures/component/http_proxy.py
Manual cherry pick of https://github.com/SatelliteQE/robottelo/pull/17950.
> [6.14.z] Remove cloned manifest fixtures from http proxy

- tests/foreman/api/test_repository.py
- tests/foreman/cli/test_repositories.py
- tests/foreman/ui/test_package.py
- tests/foreman/ui/test_sync.py
Manual cherry-pick of #17928 
Closes https://github.com/SatelliteQE/robottelo/issues/17966
> [6.16.z] Fix a couple of long-failing repo tests

- tests/foreman/api/test_repository.py
- tests/foreman/cli/test_repositories.py
- tests/foreman/ui/test_package.py
- tests/foreman/ui/test_sync.py
Manual cherry-pick of #17928 
Closes https://github.com/SatelliteQE/robottelo/issues/17968
> [6.15.z] Fix a couple of long-failing repo tests

- robottelo/host_helpers/satellite_mixins.py
ncat needs `-6` parameter to listen on ipv6
> Fix netcat on ipv6

- requirements.txt
> Bump broker to 0.6.7

- requirements.txt
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18064
That's it. That's the commit.
> [6.15.z] Bump broker to 0.6.7

- requirements.txt
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18064
That's it. That's the commit.
> [6.16.z] Bump broker to 0.6.7

- requirements.txt
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18064
That's it. That's the commit.
> [6.17.z] Bump broker to 0.6.7

- tests/foreman/ui/test_ldap_authentication.py
New test case for bug SAT-29623: User last login time is not updated when login with external authentication
Requires https://github.com/SatelliteQE/airgun/pull/1784
> [6.17.z] SAT-29623: User last login time is not updated when login with external authentication

- tests/foreman/api/test_rhcloud_inventory.py
SAT-18902
Tests the removal of the branch_id parameter as well as insights-client --compliance policies
> [Customer Case] Test for compliance policies

- tests/foreman/data/hammer_commands.json
manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/18095 
changes related to SAT-31475
> [6.17] updating hammer commands list

- tests/foreman/cli/test_reporttemplates.py
Adding additional field to ansible inventory report test 
SAT-23647
> Add content attributes to ansible inventory report

- tests/foreman/cli/test_reporttemplates.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18098
Adding additional field to ansible inventory report test 
SAT-23647
> [6.17.z] Add content attributes to ansible inventory report

- tests/foreman/cli/test_reporttemplates.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18098
Adding additional field to ansible inventory report test 
SAT-23647
> [6.16.z] Add content attributes to ansible inventory report

- tests/foreman/cli/test_reporttemplates.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18098
Adding additional field to ansible inventory report test 
SAT-23647
> [6.15.z] Add content attributes to ansible inventory report

- tests/foreman/data/hammer_commands.json
> updating hammer commands list

- pytest_fixtures/component/http_proxy.py
- tests/foreman/cli/test_http_proxy.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/18065
Closes https://github.com/SatelliteQE/robottelo/issues/18087
> [6.16.z] Fix HTTP proxy insights tests

- pytest_fixtures/component/http_proxy.py
- tests/foreman/cli/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18130
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/18065
Closes https://github.com/SatelliteQE/robottelo/issues/18087
> [6.15.z] Fix HTTP proxy insights tests

- tests/foreman/sys/test_fam.py
The redhat_manifest test needs to talk to the portal
Enable the proxy for that one test
> enable ipv6 proxy when running the redhat_manifest test

- tests/foreman/installer/test_installer.py
- A few satellite-installer tests are failing because `downloads.theforeman.org` is unreachable when running installer.
- Set HTTP proxy before installer run?
- SAT-32222
> Fix Satellite installer IPv6 tests

- tests/foreman/installer/test_installer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18105
- A few satellite-installer tests are failing because `downloads.theforeman.org` is unreachable when running installer.
- Set HTTP proxy before installer run?
- SAT-32222
> [6.17.z] Fix Satellite installer IPv6 tests

- tests/foreman/ui/test_ansible.py
After the successful completion of the Ansible job, the assertion point is updated according to the config report.
> update package name during checking config report

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17841
After the successful completion of the Ansible job, the assertion point is updated according to the config report.
> [6.17.z] update package name during checking config report

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17841
After the successful completion of the Ansible job, the assertion point is updated according to the config report.
> [6.15.z] update package name during checking config report

- tests/foreman/ui/test_http_proxy.py
https://issues.redhat.com/browse/SAT-30220 needs automation.
Check the _Test Connection_ button works on an existing proxy as expected.
```
pytest: tests/foreman/ui/test_http_proxy.py -k create_update_delete
airgun: 1787
```
> Extend http proxy test with Test Connection

- tests/foreman/ui/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18128
https://issues.redhat.com/browse/SAT-30220 needs automation.
Check the _Test Connection_ button works on an existing proxy as expected.
```
pytest: tests/foreman/ui/test_http_proxy.py -k create_update_delete
airgun: 1787
```
> [6.17.z] Extend http proxy test with Test Connection

- tests/foreman/ui/test_rhcloud_inventory.py
> [Customer Case] Test for insights global parameters

- tests/foreman/ui/test_rhcloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18145
Automation for SAT-27221
> [6.17.z] [Customer Case] Test for insights global parameters

- tests/foreman/ui/test_computeresource_vmware.py
Update the jira card in test. The first one is a duplicate and has been closed.
from SAT-23630 to SAT-31447
Fixes - https://github.com/SatelliteQE/robottelo/issues/18183
> Update the jira card in test

- tests/foreman/ui/test_host.py
Change the docstring of the test so it matches the teams properly.
> Docstring_fix_changeContentSource

- tests/foreman/api/test_ansible.py
Ansible tests were failing on teardown due to bug SAT-18656
Added a workaround for it until the issue is fixed.
> Fix Ansible tests

- tests/foreman/cli/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18287
Ansible provisioning callback is failing because the job is not completed before the next code steps are executed.
Fix the test by using wait_for to check the job status before the next code steps are executed.
> [6.16.z] Fix ansible provisioning callback test

- robottelo/host_helpers/satellite_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18308
ssh-keyscan is broken on FIPS-enabled systems (See: https://issues.redhat.com/browse/RHEL-88565)
Use `StrictHostKeyChecking accept-new` which just accepts the first seen key instead of prompting, thus eliminating the need for `ssh-keyscan`.
This PR also improves the logging of the assertion which was required to debug this issue.
> [6.17.z] use "StrictHostKeyChecking accept-new" instead of ssh-keyscan

- tests/foreman/api/test_repositories.py
Automate SAT-32622 , changing the 'Unprotected' status of any repository fails with internal sever error 500.
For Stream and 6.17.z , but will still fail in 6.17.0 latest , Awaiting next z stream
*update*: recommend we CP to 6.16.z & 6.15.z as well, since this is a PIT-like case and simple enough coverage.
```
pytest: tests/foreman/api/test_repositories.py::test_unprotected_status_repo_create_and_update
```
> [SAT-32622] Test create & update repository's 'Unprotected' status

- tests/foreman/api/test_repositories.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18334
Automate SAT-32622 , changing the 'Unprotected' status of any repository fails with internal sever error 500.
For Stream and 6.17.z , but will still fail in 6.17.0 latest , Awaiting next z stream
*update*: recommend we CP to 6.16.z & 6.15.z as well, since this is a PIT-like case and simple enough coverage.
```
pytest: tests/foreman/api/test_repositories.py::test_unprotected_status_repo_create_and_update
```
> [6.16.z] [SAT-32622] Test create & update repository's 'Unprotected' status

- .github/CODEOWNERS
- robottelo/utils/shared_resource.py
- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_errata.py
This PR converts the errata upgrade scenario to use the SharedResource framework. It converts the pre-upgrade test to a Pytest fixture, adds a shared Satellite checkout fixture, and makes several small changes to test code to address test failures.
> Convert errata upgrade scenario to new format

- tests/new_upgrades/test_activation_key.py
Manual cherry pick of https://github.com/SatelliteQE/robottelo/pull/16772.
> [6.15.z] Convert activation key upgrade scenario to new format

- .github/CODEOWNERS
- robottelo/utils/shared_resource.py
- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_errata.py
> [6.17.z] Convert errata upgrade scenario to new format

- .github/CODEOWNERS
- robottelo/utils/shared_resource.py
- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_errata.py
> [6.16.z] Convert errata upgrade scenario to new format

- tests/foreman/cli/test_oscap.py
Test that SCAP content for all supported RHEL versions is present on a freshly installed Satellite: https://issues.redhat.com/browse/SAT-19336
> Test SCAP content present

- tests/foreman/cli/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18335
Test that SCAP content for all supported RHEL versions is present on a freshly installed Satellite: https://issues.redhat.com/browse/SAT-19336
> [6.16.z] Test SCAP content present

- tests/foreman/cli/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18335
Test that SCAP content for all supported RHEL versions is present on a freshly installed Satellite: https://issues.redhat.com/browse/SAT-19336
> [6.17.z] Test SCAP content present

- tests/foreman/cli/test_reporttemplates.py
> generate report for hosts without rex interface

- tests/foreman/ui/test_rhcloud_inventory.py
We need to check the RHC Inventory behaviour with `subscription_connection_enabled` setting used.  
Generating and downloading the report with this setting set to True/False
Extend the current `test_rhcloud_inventory_e2e` test so it work with `subscription_connection_enabled` setting.
Needs https://github.com/SatelliteQE/airgun/pull/1839
```
pytest: tests/foreman/ui/test_rhcloud_inventory.py -k 'test_rhcloud_inventory_e2e'
airgun: 1839
theforeman:
foreman_rh_cloud: 978
```
> RHC Inventory E2E test extension

- tests/foreman/cli/test_subscription.py
Adding check for product-host-count in existing hammer subscription list test
> [Customer Case] Adding functionality for product-host-count

- .github/CODEOWNERS
- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_hostgroup.py
> [6.16.z ] Convert host group upgrade scenario to new format

- tests/foreman/ui/test_documentation_links.py
Test for https://issues.redhat.com/browse/SAT-20700 .
Requires https://github.com/SatelliteQE/airgun/pull/1845
> Verify presence of Satellite Upgrade links

- robottelo/hosts.py
- tests/foreman/api/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18106
[SAT-26741](https://issues.redhat.com/browse/SAT-26741) needs some automation.
This PR adds that coverage.
```
pytest: tests/foreman/api/test_http_proxy.py -k test_refresh_updates_remotes_proxy
```
> [6.17.z] Add a test case for SAT-26741

- robottelo/constants/__init__.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/18461
Closes: https://github.com/SatelliteQE/robottelo/issues/18464
> [6.14.z] Update kickstart version for RHEL9 

- tests/new_upgrades/test_hostcontent.py
> [6.16.z] Convert content host scenario to new format

- .github/CODEOWNERS
- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_remoteexecution.py
> [6.16.z] Convert REX upgrade scenario to new format

- tests/new_upgrades/test_role.py
Manual cherry pick of https://github.com/SatelliteQE/robottelo/pull/18390
> [6.15.z] Convert user role scenario to new format

- tests/new_upgrades/test_satellitesync.py
> [6.15.z] Convert Satellite Sync upgrade scenario to new format

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_capsule.py
> [6.15.z] Convert Capsule upgrade scenario to new format

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_puppet.py
> [6.16.z] Convert Puppet upgrade scenario to new format

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_puppet.py
Manual cherry pick of  #18377.
> [6.17.z] Convert Puppet upgrade scenario to new format

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_puppet.py
> [6.15.z] Convert Puppet upgrade scenario to new format

- conf/capsule.yaml.template
- conf/content_host.yaml.template
- conf/migrations.py
- conf/server.yaml.template
- pytest_fixtures/component/leapp_client.py
- pytest_fixtures/core/contenthosts.py
- pytest_fixtures/core/sat_cap_factory.py
- pytest_plugins/fixture_markers.py
- pytest_plugins/markers.py
- pytest_plugins/metadata_markers.py
- pytest_plugins/video_cleanup.py
- robottelo/config/validators.py
- robottelo/enums.py
- robottelo/host_helpers/contenthost_mixins.py
- robottelo/hosts.py
- robottelo/ssh.py
- robottelo/utils/ohsnap.py
- tests/foreman/ui/test_errata.py
- tests/robottelo/test_enum.py
This PR backports #17904 to 6.15.z
> [6.15.z] Backport of #17904

- conf/content_host.yaml.template
This PR backports #18606 to 6.15.z
> [6.15.z] Backport of #18606

- .github/CODEOWNERS
- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_remoteexecution.py
> [6.17.z] Convert REX upgrade scenario to new format

- robottelo/host_helpers/capsule_mixins.py
previously these mixins didn't account for the ipv6 variant of gitea instance that came about after they were written. As such the dig lookup returned no results and lead to an invalid firewall rule created leading to cryptic failures.
> http proxy helpers adjusted for ipv6

- robottelo/host_helpers/capsule_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18520
previously these mixins didn't account for the ipv6 variant of gitea instance that came about after they were written. As such the dig lookup returned no results and lead to an invalid firewall rule created leading to cryptic failures.
> [6.17.z] http proxy helpers adjusted for ipv6

- robottelo/utils/shared_resource.py
- tests/new_upgrades/test_errata.py
> [6.15.z] Convert errata upgrade scenario 6.15.z

- pytest_fixtures/component/provisioning_template.py
Missed this in https://github.com/SatelliteQE/robottelo/pull/18560, updating now
> Update module_sync_kickstart_content fixture

- pytest_fixtures/component/provisioning_template.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18699
Missed this in https://github.com/SatelliteQE/robottelo/pull/18560, updating now
> [6.17.z] Update module_sync_kickstart_content fixture

- requirements-optional.txt
Fixing Failed-AutoCherryPick's for 6.15.z
> [6.15.z] Sync requirements with master branch

- tests/foreman/ui/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17191
null
> [6.15.z] Fix oldap data structure in test

- tests/foreman/ui/test_rhcloud_inventory.py
Updating the key in the test
```
pytest: tests/foreman/ui/test_rhcloud_inventory.py -k 'test_subscription_connection_settings_ui_behavior'
```
> fix Subscription Connection Test

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18639
null
> [6.17.z] Fix apache id and keytab creating command for SAT-34783

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_syncplan.py
> [6.15.z] Convert sync plan upgrade scenario to new format

- tests/foreman/ui/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17191
null
> [6.17.z] Fix oldap data structure in test

- tests/foreman/api/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18754
Fixing  VMware pxe-discovery tests
> [6.17.z] Fix VMware pxe-discovery test

- tests/foreman/cli/test_discoveredhost.py
Failed auto-cherrypick : https://github.com/SatelliteQE/robottelo/issues/18741 
> [6.15.z Cherrypick] Update FDI test assertion due to Bug:SAT-34778

- tests/foreman/ui/test_host.py
IPv6 Katello-tracer UI tests failing with below error, and that was due to timeout issue and katello host tools tracer installation issue.
Error-
```
nailgun.entity_mixins.TaskFailedError
```
Based on network type we need to enable ipv6 dnf and rhsm proxy along with ipv6 system proxy on content host with fixtures `enable_ipv6_dnf_and_rhsm_proxy()` and `enable_ipv6_system_proxy()`
```
pytest: tests/foreman/ui/test_host.py -k 'test_positive_tracer_enable_reload'
```
> stream ipv6 ui fix for tracer

- tests/foreman/cli/test_computeresource_vmware.py
Updating VMware cli tests to use storage pod instead of datastore
> Update VMware cli tests to use storage pod

- tests/foreman/destructive/test_clone.py
Cherrypick of #18604
Fixes #18770
> [6.15.z] Use helper functions to setup repositories in satellite-clone (#18770)

- robottelo/hosts.py
> [6.15.z] Remove pool attachment since we are SCA now (#18826)

- tests/foreman/api/test_reporttemplates.py
- tests/foreman/cli/test_host.py
- tests/foreman/cli/test_reporttemplates.py
- tests/foreman/cli/test_satellitesync.py
- tests/foreman/ui/test_host.py
- tests/foreman/ui/test_reporttemplates.py
- tests/new_upgrades/test_satellitesync.py
- tests/upgrades/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18874
Updating team component Ownership
> [6.17.z] Update team component ownership

- tests/foreman/api/test_reporttemplates.py
- tests/foreman/cli/test_host.py
- tests/foreman/cli/test_reporttemplates.py
- tests/foreman/cli/test_satellitesync.py
- tests/foreman/ui/test_host.py
- tests/foreman/ui/test_reporttemplates.py
- tests/new_upgrades/test_satellitesync.py
- tests/upgrades/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18874
Updating team component Ownership
> [6.15.z] Update team component ownership

- tests/foreman/endtoend/test_cli_endtoend.py
Cherypick of PR https://github.com/SatelliteQE/robottelo/pull/18948
Partial Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18934
Fixes #18949
> [6.15.z] Update CLI e2e test, make it more recent, remove need for future updates

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_subscription.py
Manual cherry pick of  #18787.
> [6.16.z] Convert Subscription upgrade scenario to new format

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_subscription.py
> [6.17.z] Convert Subscription upgrade scenario to new format

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_subscription.py
Manual cherry pick of  #18787.
> [6.15.z] Convert Subscription upgrade scenario to new format

- tests/foreman/cli/test_subscription.py
- tests/foreman/ui/test_subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19074
Remove Golden Ticket related test and fixtures
> [6.17.z] Golden Ticket Removal

- tests/foreman/cli/test_subnet.py
Automated Stubbed test case to add parameter in subnet.
Fixed test Scenario for CRUD operation on subnet.
> Automate test to set parameters in subnet.

- tests/foreman/cli/test_subnet.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19035
Automated Stubbed test case to add parameter in subnet.
Fixed test Scenario for CRUD operation on subnet.
> [6.17.z] Automate test to set parameters in subnet.

- tests/foreman/cli/test_flatpak.py
Cert-based authentication for flatpak has been added in 6.18 and should be covered.
We already have an E2E test for the flatpak consumption on a host which uses the legacy `podman login` for authentication. We can parametrize this case with cert-based login, which is what this PR does.
https://issues.redhat.com/browse/SAT-33256
https://issues.redhat.com/browse/SAT-34546
https://github.com/Katello/katello/pull/11403
https://github.com/SatelliteQE/robottelo/pull/18826
```
pytest: tests/foreman/cli/test_flatpak.py -k test_sync_consume_flatpak_repo_via_cv
Katello:
katello: 11403
```
> Add cert-based login parametrization for flatpak

- pytest_plugins/marker_deselection.py
Cherry-pick https://github.com/SatelliteQE/robottelo/pull/19142
Fixes https://github.com/SatelliteQE/robottelo/pull/19179
> [6.17.z] Remove Virt-whoConfigurePlugin from non_satCI_components

- tests/foreman/api/test_jobtemplate.py
Adding a life cycle operation test for job template via API
Dependent PR: https://github.com/SatelliteQE/nailgun/pull/1324
> API test case for job-template

- .pre-commit-config.yaml
This PR backports #19187 to 6.15.z
> [6.15.z] Backport of #19187

- tests/foreman/ui/test_host.py
issues in 6.17 run of this UI tests
tried to run stream version of this test against 6.17 box, was green, so I figure a couple of cherrypicks would suffice to make things right.
This pulls in patches from https://github.com/SatelliteQE/robottelo/pull/18392 and https://github.com/SatelliteQE/robottelo/pull/18781 
requires https://github.com/SatelliteQE/airgun/pull/1954
> 6.17 tracer fixes

- tests/foreman/maintain/test_backup_restore.py
- We now have backup/restore support in foreman-maintain for Satellite Lightspeed(Insights on Prem).
- Backup/Restore tests are failing because of fixture scope mismatch.
- Add automation for backup restore of IoP-enabled Satellite.
- Fix fixture scope mismatch issue.
- https://github.com/SatelliteQE/robottelo/pull/19167
- SAT-34508
- SAT-34512
> Add backup/restore test for Insights on Prem Satellite

- .github/CODEOWNERS
- pytest_fixtures/component/usage_report.py
- robottelo/cli/sm_report.py
- robottelo/constants/__init__.py
- robottelo/host_helpers/satellite_mixins.py
- tests/foreman/cli/test_usage_report.py
- tests/foreman/data/usage_report.yml
- tests/foreman/data/usage_report_condensed.yml
tests for SAT-30439
Testing that:
- the condensed report gets generated both from full report and for scratch
- the timers and services are in place
- the max-age setting is applied
> test condensed usage report

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/auto_cherry_pick_merge.yaml
- .github/workflows/auto_cherry_pick_merged.yaml
- .github/workflows/dependency_merge.yml
- .github/workflows/pull_request.yml
- .github/workflows/update_robottelo_image.yml
- .github/workflows/weekly.yml
Some patches were not backported - #19207, #18833
backport them :)
> 6.17.z: Sync GHA dependencies with master branch

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/auto_cherry_pick_merge.yaml
- .github/workflows/auto_cherry_pick_merged.yaml
- .github/workflows/dependency_merge.yml
- .github/workflows/pull_request.yml
- .github/workflows/update_robottelo_image.yml
- .github/workflows/weekly.yml
Some patches were not backported - #19206, #18832
backport them :)
> 6.16.z: Sync GHA dependencies with master branch

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/auto_cherry_pick_merge.yaml
- .github/workflows/auto_cherry_pick_merged.yaml
- .github/workflows/dependency_merge.yml
- .github/workflows/pull_request.yml
- .github/workflows/update_robottelo_image.yml
- .github/workflows/weekly.yml
Some patches were not backported - #19205, #18834
backport them :)
> 6.15.z: Sync GHA dependencies with master branch

- robottelo/hosts.py
This PR backports #19238 to 6.15.z
> [6.15.z] Backport of #19238

- tests/foreman/ui/test_partitiontable.py
Requires https://github.com/SatelliteQE/airgun/pull/1982
> Update test for PF5 and test EditorModal

- tests/foreman/cli/test_subscription.py
Coverage is needed for SAT-32710.
Created new test `test_positive_subscription_manager_environments_set_non_admin_user` that verifies SAT-32710.
It verifies that non-admin users with proper roles can change the host LCE/CV environment using the subscription-manager environments --set command.
```
pytest: tests/foreman/cli/test_subscription.py -k "test_positive_subscription_manager_environments_set_non_admin_user"
```
> [SAT-32710] Coverage

- tests/foreman/ui/test_rhcloud_insights.py
This PR adds assertions to ensure that the errors detailed in SAT-36449 are not present. It also removes the parametrization for IOP from the RH Cloud Insights end-to-end test, as the Recommendations and Vulnerabilities pages are different enough between hosted and IOP that we will be creating separate test modules and Airgun entities/views for the on-prem scenario.
> Automate SAT-36449 and remove IOP parametrization

- tests/foreman/cli/test_satellitesync.py
There is a customer facing bug for import history in case of a syncable export/import, see the issue bellow.
We have the syncable export/import already covered, so we just need to extend it a bit.
This PR proposes such an extension.
https://issues.redhat.com/browse/SAT-32667
```
pytest: tests/foreman/cli/test_satellitesync.py -k test_postive_export_import_cv_with_mixed_content_syncable
```
> Extend ISS syncable import test with imports history check

- tests/foreman/destructive/test_auth.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19322
null
> [6.15.z] Get rid of bogus lines in output

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19334
There is a customer facing bug for import history in case of a syncable export/import, see the issue bellow.
We have the syncable export/import already covered, so we just need to extend it a bit.
This PR proposes such an extension.
https://issues.redhat.com/browse/SAT-32667
```
pytest: tests/foreman/cli/test_satellitesync.py -k test_postive_export_import_cv_with_mixed_content_syncable
```
> [6.18.z] Extend ISS syncable import test with imports history check

- robottelo/cli/job_template.py
- tests/foreman/cli/test_jobtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19412
null
> [6.18.z] SAT-20253 - hammer import keeps org and loc

- tests/foreman/cli/test_fact.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/19270
> [6.15.z] remove_check_for_mac_address

- tests/foreman/destructive/test_auth.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19322
null
> [6.16.z] Get rid of bogus lines in output

- robottelo/constants/__init__.py
- tests/foreman/sys/test_fam.py
> [6.18.z] Add new test for FAM with Kerberos (#19056)

- robottelo/hosts.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/19445
> [6.16.z] api_register_disable_insights

- tests/foreman/api/test_repositories.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19231
Let's check expected tasks are invoked after repository protection change, for this newer case recently introduced.
We have seen it can fail occasionally for one or more tasks, so we can get more insightful results.
```
pytest: tests/foreman/api/test_repositories.py::test_unprotected_status_repo_create_and_update
```
> [6.18.z] Check expected tasks for repo protection changes

- tests/foreman/destructive/test_registration.py
Since snap 122, this error has been exposed 
```
Validation failed: Content view environment content facets invalid: The content source must sync the lifecycle environment assigned to the host.
```
and registration step in the `test_host_registration_rex_pull_mode` started failing because the registration command did not end with RC:0.
It was caused by the capsule not having LCE assigned. See https://access.redhat.com/solutions/7081411, where the same problem was discussed.
Use  
```python
if module_capsule_configured_mqtt.nailgun_capsule.lifecycle_environments == []:
module_capsule_configured_mqtt.nailgun_capsule.content_add_lifecycle_environment(
data={'environment_id': module_lce.id}
)
```
to add `module_lce`, which is used in the `module_ak_with_cv` to the capsule.
It is in an …
> destructive registration test fix

- tests/foreman/api/test_repositories.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19577
The `test_unprotected_status_repo_create_and_update` is failing since #19231 introduced [this assertion](https://github.com/SatelliteQE/robottelo/pull/19231/files#diff-18095fabdf2ee2e3af4b59f78c3af8ef49d7602590d3ba37f4f0369578d41673R460-R467) with
```
AssertionError: assert 3 == 2
```
The reason behind is that the "Updating repository authentication configuration" task is not tagged with `organization_id`, so the `wait_for_tasks` returns all such tasks for _any_ organization. Unfortunately, another one seems to be created by [test_positive_create_unprotected](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/api/test_repository.py#L320).
Fallback for the time-based search.
Apart from that fix I'm …
> [6.18.z] Fix and harden test_unprotected_status_repo_create_and_update

- tests/foreman/api/test_repositories.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19577
The `test_unprotected_status_repo_create_and_update` is failing since #19231 introduced [this assertion](https://github.com/SatelliteQE/robottelo/pull/19231/files#diff-18095fabdf2ee2e3af4b59f78c3af8ef49d7602590d3ba37f4f0369578d41673R460-R467) with
```
AssertionError: assert 3 == 2
```
The reason behind is that the "Updating repository authentication configuration" task is not tagged with `organization_id`, so the `wait_for_tasks` returns all such tasks for _any_ organization. Unfortunately, another one seems to be created by [test_positive_create_unprotected](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/api/test_repository.py#L320).
Fallback for the time-based search.
Apart from that fix I'm …
> [6.16.z] Fix and harden test_unprotected_status_repo_create_and_update

- tests/foreman/destructive/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19526
> [6.18.z] Cover SAT-36783 in cockpit test (#19526)

- pytest_fixtures/component/maintain.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19599
- f-m remotedb IPv6 tests were failing because proxy was not setup
- Set up HTTP Proxy for f-m Satellite
> [6.18.z] Setup HTTP Proxy for f-m Satellite

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19532
We had a customer facing bug regarding the format inheritance which needs coverage, see the issue bellow for more details.
This PR proposes the coverage.
https://issues.redhat.com/browse/SAT-32715
```
pytest: tests/foreman/cli/test_satellitesync.py -k test_positive_export_format_inheritance
Katello:
katello: 11462
```
> [6.18.z] Add a test case for ISS export format inheritance

- tests/foreman/data/usage_report.yml
> report items renamed

- tests/foreman/data/usage_report.yml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19626
advisor_on_prem > iop
> [6.18.z] report items renamed

- tests/foreman/data/hammer_commands.json
Updating the hammer commands list
> [6.18.z] Updating hammer commands list 

- tests/foreman/cli/test_ldapauthsource.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19441
to cover  SAT-21129
> [6.18.z] coverage for posix ldap group membership

- tests/foreman/cli/test_rhcloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19717
The network protocol `https` was defined in the no-proxy, which prevented Satellite from connecting to itself through the proxy and getting below error:
`worker.go:111: [/usr/libexec/rhc/foreman-rh-cloud-worker] Post "https://satellite.example.com/api/v2/rh_cloud/cloud_request": tls: failed to verify certificate: x509: certificate signed by unknown authority`
Removed HTTPS from the proxy, and automation is covering this scenario.
> [6.18.z] Incorrect no-proxy configuration with HTTPS prevents Satellite self-connection

- tests/foreman/cli/test_remoteexecution.py
There is a bug [SAT-28485](https://issues.redhat.com/browse/SAT-28485) "Reject start-at dates in the past when a job is scheduled" and we want to have automation coverage for the bug.
Implement new test `test_negative_schedule_job_template` to cover the bug
> SAT-28485 Test to schedule a job in the past

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19789
There is a bug [SAT-28485](https://issues.redhat.com/browse/SAT-28485) "Reject start-at dates in the past when a job is scheduled" and we want to have automation coverage for the bug.
Implement new test `test_negative_schedule_job_template` to cover the bug
> [6.18.z] SAT-28485 Test to schedule a job in the past

- tests/foreman/cli/test_host.py
Manual CP of https://github.com/SatelliteQE/robottelo/pull/19823
> [6.16.z] removeOutdatedDuplicateHostCliTest

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19705
> [6.17.z] removing hosts from bookmark entities

- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19831
The `test_ccv_inc_update_autopublish` is failing flakily with this result on line L3159:
```
AssertionError: assert 'pending' == 'success'
```
It seems like the `wait_for_tasks` sometimes returns task which is still pending. In this case, two tasks are returned: `[0]` is the latest publish we are waiting for, `[1]` is the original publish.
Use `wait_for` until both of the tasks are finished. 
The second task usually takes ~2 seconds, so I set `delay=3, timeout=20`.
```
pytest: tests/foreman/cli/test_contentview.py -k test_ccv_inc_update_autopublish
```
> [6.18.z] Fix test_ccv_inc_update_autopublish

- tests/foreman/ui/test_remoteexecution.py
The new job details page has became the default one.
See RFE SAT-30756 for details
REX UI tests need to be updated to the new page structure.
Requires https://github.com/SatelliteQE/airgun/pull/1970 , https://github.com/SatelliteQE/airgun/pull/1995
```
pytest: tests/foreman/ui/test_remoteexecution.py
airgun: 1970
```
> job invocation: update for new job details page

- tests/foreman/cli/test_satellitesync.py
SAT-38691 reports that the use of destination server in incremental exports without history IDs passed regressed. A test was missing to test incremental exports with a destination server argument.
I've added parameterization to the original test for incremental export format detection. The parameterization cycles between using destination server and not.
I've removed the references to [SAT-38392](https://issues.redhat.com/browse/SAT-38392) because the test passed for me without issues. Perhaps the issue shows up only when run in a pipeline? @vsedmik might be able to help here.
SAT-38691
SAT-38392
SAT-32715 (regressor)
> Add destination server testing to ISS incremental export test

- tests/foreman/maintain/test_maintenance_mode.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19917
Before maintenance-mode is started in case of IoP test, `iop-service-vuln-vmaas-sync.timer` service is either in `Active: active (running)` or `Active: active (waiting)` state, which causes this test to fail often times.
1. Assert for both `Active: active (running)` or `Active: active (waiting)` state for `iop-service-vuln-vmaas-sync.timer` service before maintenance-mode is started.
2. Using FM commands to check `iop-service-vuln-vmaas-sync.timer` service status, instead of systemctl commands
> [6.18.z] Fix FM maintenance-mode test for IoP

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19916
Fix long failing Hosts E2E test.
```
pytest: tests/foreman/ui/test_host.py -k "test_positive_end_to_end"
```
> [6.18.z] Fix Hosts UI E2E test
