tests/foreman/api/test_syncplan.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13370
Cleaning up SyncPlan test after big refactor. This was missing an api param on the target_sat call. 
pytest: tests/foreman/api/test_syncplan.py -k 'test_positive_synchronize_rh_product_past_sync_date'

[6.13.z] Fix missing api param in target_sat call in SyncPlan test

---

tests/foreman/ui/test_acs.py

Small test covering a customer BZ, https://bugzilla.redhat.com/show_bug.cgi?id=2119112
Thanks to @LadislavVasina1 was very easy to write. Good work on the ACS airgun implementation!
Note: There are no assertions in this test, as the only thing it needs to do is succeed on creating these different ACS sources. The entity for that checks for errors, and throws appropriate errors when something goes wrong. 
pytest: tests/foreman/ui/test_acs.py -k 'test_acs_subpath_not_required'

Automation for BZ 2119112 - subpaths field is mandatory while creating ACS in the UI

---

.github/workflows/auto_cherry_pick.yml

PRT comment was not getting copied due to the change when we tried to move from GHA to curl. After looking at the challenges with curl there are a lot of validation needs to be added which is overhead 
This PR will fix the PRT comment copy to all cherry-pick branches. It will be using thollander/actions-comment-pull-request@v2 GHA to fix this. 
Verified this on own robottelo fork 
https://github.com/omkarkhatavkar/robottelo/pull/174
https://github.com/omkarkhatavkar/robottelo/pull/172

fixing the prt comment copy to cherry-pick branch

---

robottelo/hosts.py
tests/foreman/ui/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13341
LCE option is removed from registration in 6.15
Removing LCE option check registration form populate test, and also from register helper (confirmed this option isn't used by any test)
Katello PR https://github.com/Katello/katello/pull/10764
Airgun PR https://github.com/SatelliteQE/airgun/pull/1069

[6.15.z] Remove LCE option from register helper and assert in form test

---

robottelo/constants/repos.py

`rpm-zchunk` repo was removed from fixtures, which makes some ACS tests to fail:
```
"description"=>"ACS remote for url \'https://fixtures.pulpproject.org/rpm-zchunk/\' raised an error \'404: Not Found\'. Please check your ACS remote configuration."
```
Use another yum repo, preferably one with the new zst metadata compression.

Update yum repo for ACSes

---

pytest_fixtures/component/activationkey.py
tests/foreman/api/test_registration.py
tests/foreman/cli/test_registration.py
tests/foreman/ui/test_host.py

Fix Registration test cases failing because of changed activation key fixture.
There was duplicate of the fixture `module_activation_key` so removed it from test_host.py and using sca_enabled_manifest in pytest_fixtures/component/activationkey.py
Updated activation key fixture in the tests

Added SCA enabled manifest in activation key and removed duplicate fixture

---

robottelo/constants/repos.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13365
`rpm-zchunk` repo was removed from fixtures, which makes some ACS tests to fail:
```
"description"=>"ACS remote for url \'https://fixtures.pulpproject.org/rpm-zchunk/\' raised an error \'404: Not Found\'. Please check your ACS remote configuration."
```
Use another yum repo, preferably one with the new zst metadata compression.

[6.14.z] Update yum repo for ACSes

---

pytest_fixtures/component/activationkey.py
tests/foreman/api/test_registration.py
tests/foreman/cli/test_registration.py
tests/foreman/ui/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13082
Fix Registration test cases failing because of changed activation key fixture.
There was duplicate of the fixture `module_activation_key` so removed it from test_host.py and using sca_enabled_manifest in pytest_fixtures/component/activationkey.py
Updated activation key fixture in the tests

[6.13.z] Added SCA enabled manifest in activation key and removed duplicate fixture

---

pytest_fixtures/component/activationkey.py
tests/foreman/api/test_registration.py
tests/foreman/cli/test_registration.py
tests/foreman/ui/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13082
Fix Registration test cases failing because of changed activation key fixture.
There was duplicate of the fixture `module_activation_key` so removed it from test_host.py and using sca_enabled_manifest in pytest_fixtures/component/activationkey.py
Updated activation key fixture in the tests

[6.15.z] Added SCA enabled manifest in activation key and removed duplicate fixture

---

robottelo/constants/repos.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13365
`rpm-zchunk` repo was removed from fixtures, which makes some ACS tests to fail:
```
"description"=>"ACS remote for url \'https://fixtures.pulpproject.org/rpm-zchunk/\' raised an error \'404: Not Found\'. Please check your ACS remote configuration."
```
Use another yum repo, preferably one with the new zst metadata compression.

[6.15.z] Update yum repo for ACSes

---

tests/foreman/ui/test_acs.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13369
Small test covering a customer BZ, https://bugzilla.redhat.com/show_bug.cgi?id=2119112
Thanks to @LadislavVasina1 was very easy to write. Good work on the ACS airgun implementation!
Note: There are no assertions in this test, as the only thing it needs to do is succeed on creating these different ACS sources. The entity for that checks for errors, and throws appropriate errors when something goes wrong. 
pytest: tests/foreman/ui/test_acs.py -k 'test_acs_subpath_not_required'

[6.15.z] Automation for BZ 2119112 - subpaths field is mandatory while creating ACS in the UI

---

tests/foreman/ui/test_acs.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13369
Small test covering a customer BZ, https://bugzilla.redhat.com/show_bug.cgi?id=2119112
Thanks to @LadislavVasina1 was very easy to write. Good work on the ACS airgun implementation!
Note: There are no assertions in this test, as the only thing it needs to do is succeed on creating these different ACS sources. The entity for that checks for errors, and throws appropriate errors when something goes wrong. 
pytest: tests/foreman/ui/test_acs.py -k 'test_acs_subpath_not_required'

[6.14.z] Automation for BZ 2119112 - subpaths field is mandatory while creating ACS in the UI

---

tests/foreman/endtoend/test_api_endtoend.py

this path has been added to foreman_remote_execution-10.1.0 as part of https://projects.theforeman.org/issues/36751, it is also present in 6.14.z that has foreman_remote_execution-10.1.1-1
note: this also needs to change in 6.15 and master, but there is a larger bunch of api changes that are currently being consulted with dev, so the PRs will follow later

[6.14] added available_remote_execution_features apipath

---

tests/foreman/api/test_audit.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13368
```
'architecture'
'decclass'
```

[6.15.z] fixed api audit tests

---

tests/foreman/api/test_audit.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13368
```
'architecture'
'decclass'
```

[6.14.z] fixed api audit tests

---

tests/foreman/api/test_audit.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13368
```
'architecture'
'decclass'
```

[6.13.z] fixed api audit tests

---

tests/foreman/api/test_audit.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13368
```
'architecture'
'decclass'
```

[6.12.z] fixed api audit tests

---

pytest_fixtures/component/activationkey.py
tests/foreman/api/test_registration.py
tests/foreman/cli/test_registration.py
tests/foreman/ui/test_host.py

Parent PR: https://github.com/SatelliteQE/robottelo/pull/13082 
Fix Registration test cases failing because of changed activation key fixture.
There was duplicate of the fixture module_activation_key so removed it from test_host.py
Updated activation key fixture in the tests and using sca_enabled_manifest in pytest_fixtures/component/activationkey.py

[6.14.z] Using SCA enabled manifest in activation key

---

tests/foreman/cli/test_leapp_client.py

Bump EL8, EL9 versions in leapp upgrade test

---

tests/foreman/cli/test_leapp_client.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13411

[6.12.z] Bump EL8, EL9 versions in leapp upgrade test

---

tests/foreman/cli/test_leapp_client.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13411

[6.15.z] Bump EL8, EL9 versions in leapp upgrade test

---

tests/foreman/cli/test_leapp_client.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13411

[6.13.z] Bump EL8, EL9 versions in leapp upgrade test

---

robottelo/host_helpers/cli_factory.py
tests/foreman/cli/test_computeresource_libvirt.py
tests/foreman/cli/test_location.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13408
Fix libvirt/ec2 compute resource tests

[6.14.z] Fix libvirt/ec2 compute resource tests

---

robottelo/host_helpers/cli_factory.py
tests/foreman/cli/test_computeresource_libvirt.py
tests/foreman/cli/test_location.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13408
Fix libvirt/ec2 compute resource tests

[6.15.z] Fix libvirt/ec2 compute resource tests

---

tests/foreman/cli/test_leapp_client.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13411

[6.14.z] Bump EL8, EL9 versions in leapp upgrade test

---

tests/foreman/api/test_subscription.py

In 6.14.z, Subscription Managment API test were failing due to missing name of keyword argument
`TypeError: Subscription.__init__() got multiple values for argument 'server_config'`
Note: This PR was raise by considering 6.14.z stream signoff, after looking into 6.15 & stream test failures updating labels.
Provided fix will resolve this error
No

keyword argument server config required

---

robottelo/host_helpers/cli_factory.py
tests/foreman/cli/test_computeresource_libvirt.py
tests/foreman/cli/test_location.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13408
Fix libvirt/ec2 compute resource tests

[6.12.z] Fix libvirt/ec2 compute resource tests

---

tests/foreman/ui/test_rhc.py

Currently, Iqe tests are failing to install insights-client as it has a dependency on some other package. 
Enable rhel baseos to resolve issue.

SAT-21433: Enable and sync rhel8_bos repo for rhc tests

---

tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13400
Currently, Iqe tests are failing to install insights-client as it has a dependency on some other package. 
Enable rhel baseos to resolve issue.

[6.15.z] SAT-21433: Enable and sync rhel8_bos repo for rhc tests

---

tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13400
Currently, Iqe tests are failing to install insights-client as it has a dependency on some other package. 
Enable rhel baseos to resolve issue.

[6.13.z] SAT-21433: Enable and sync rhel8_bos repo for rhc tests

---

tests/foreman/api/test_permission.py
tests/foreman/api/test_role.py
tests/foreman/cli/test_role.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13433
fixed a bunch of test failures, mainly effects of https://github.com/SatelliteQE/robottelo/pull/12989 and https://github.com/SatelliteQE/robottelo/pull/12796 
Some tests are still affected by type error problem on entitiy init, I beleive this should be fixed on the nailgun side, filed https://github.com/SatelliteQE/nailgun/pull/1029

[6.14.z] users and roles test fixes

---

tests/foreman/cli/test_hostcollection.py

Fix host-collections tests

---

tests/foreman/cli/test_hostcollection.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13442
```
```

[6.14.z] Fix host-collections tests

---

tests/foreman/cli/test_hostcollection.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13442
```
```

[6.13.z] Fix host-collections tests

---

tests/foreman/cli/test_hostcollection.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13442
```
```

[6.12.z] Fix host-collections tests

---

tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13400
Currently, Iqe tests are failing to install insights-client as it has a dependency on some other package. 
Enable rhel baseos to resolve issue.

[6.14.z] SAT-21433: Enable and sync rhel8_bos repo for rhc tests

---

tests/foreman/cli/test_hostcollection.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13442
```
```

[6.15.z] Fix host-collections tests

---

tests/foreman/cli/test_organization.py

module_org can also contain default location which surprised a test before. Also, `hammer organization create` accepts `--users` not `--user` and certainly not `--pasword`. 
Somehow the previous make_organization factory method didn't fail with that (just debug statement), not so with target_sat.cli_factory. So in this case, https://github.com/SatelliteQE/robottelo/pull/11544 helped to uncover the problem
Checking just the presence of associated locations, not their count. Using correct parameters for make_org

cli org test fixes

---

tests/foreman/cli/test_organization.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13399
module_org can also contain default location which surprised a test before. Also, `hammer organization create` accepts `--users` not `--user` and certainly not `--pasword`. 
Somehow the previous make_organization factory method didn't fail with that (just debug statement), not so with target_sat.cli_factory. So in this case, https://github.com/SatelliteQE/robottelo/pull/11544 helped to uncover the problem
Checking just the presence of associated locations, not their count. Using correct parameters for make_org

[6.15.z] cli org test fixes

---

tests/foreman/cli/test_organization.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13399
module_org can also contain default location which surprised a test before. Also, `hammer organization create` accepts `--users` not `--user` and certainly not `--pasword`. 
Somehow the previous make_organization factory method didn't fail with that (just debug statement), not so with target_sat.cli_factory. So in this case, https://github.com/SatelliteQE/robottelo/pull/11544 helped to uncover the problem
Checking just the presence of associated locations, not their count. Using correct parameters for make_org

[6.14.z] cli org test fixes

---

tests/foreman/cli/test_organization.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13399
module_org can also contain default location which surprised a test before. Also, `hammer organization create` accepts `--users` not `--user` and certainly not `--pasword`. 
Somehow the previous make_organization factory method didn't fail with that (just debug statement), not so with target_sat.cli_factory. So in this case, https://github.com/SatelliteQE/robottelo/pull/11544 helped to uncover the problem
Checking just the presence of associated locations, not their count. Using correct parameters for make_org

[6.13.z] cli org test fixes

---

tests/foreman/api/test_errata.py
tests/foreman/ui/test_contenthost.py

Extend UI::test_contenthost.py::`test_positive_end_to_end`: 
- To check the new `'RHEL Lifecycle status'` of the rhel host, and check `host status`.
Two helper methods:
- `get_supported_rhel_versions()` : to get all supported rhel versions for contenthosts in satellite.
- `get_rhel_lifecycle_support(rhel_version)` : to get expected RHEL Lifecycle status string, 
based on provided `rhel_version#` vs all supported `versions#` discovered.

[RFE] Check RHEL Lifecycle status in ContentHost UI

---

tests/foreman/api/test_provisioning.py
tests/foreman/api/test_provisioningtemplate.py

Add test coverage for provisioning with fips_enabled

---

tests/foreman/cli/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13288
Fail: 13 [-18]
Pass: 29 [+18]
Skip: 0 [-1]
**All of the addressed tests pass PRT**
~Total Tests 42 vs 43, I'm not yet sure which test/param is not present anymore.~
**Solved:** It appears from most recent CI results, `test_host_errata_search_commands` runs twice, but it is not parameterized. 
Failed both in CI. In PRT we see one result for that test, now passing.
Many small updates and fixes for cli errata:
- Registered hosts through global registration (`errata_host` fixture).
- Changed to mostly fake repos and custom packages.
- Fix to `cv_publish_promote()`, which was promoting environments out of order.
- Add new errata method, to find any in-progress task `Applicability::Hosts::BulkGenerate` 
`wait_for` its …

[6.15.z] [Comp-Eval] CLI::test_errata Refactor

---

tests/foreman/cli/test_repository.py

There were some tests failing because of recently merged [PR](https://github.com/SatelliteQE/robottelo/pull/11544) of CLI helper refactor.
Fixed the test failures in this PR.

Fix test failures from cli.factory refactor

---

tests/foreman/cli/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13459
There were some tests failing because of recently merged [PR](https://github.com/SatelliteQE/robottelo/pull/11544) of CLI helper refactor.
Fixed the test failures in this PR.

[6.15.z] Fix test failures from cli.factory refactor

---

tests/foreman/cli/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13459
There were some tests failing because of recently merged [PR](https://github.com/SatelliteQE/robottelo/pull/11544) of CLI helper refactor.
Fixed the test failures in this PR.

[6.12.z] Fix test failures from cli.factory refactor

---

tests/foreman/cli/test_satellitesync.py

`mirror-on-sync` was deprecated and replaced by `mirroring-policy` in Katello 4.8.0 (see https://projects.theforeman.org/issues/36140)
However, it seems there are last two remaining occurrences in robottelo which need to be updated if we don't wish to see errors like this:
```
Error: Unrecognised option '--mirror-on-sync'.
```
Get rid of the deprecated `mirror-on-sync` option.

Get rid of deprecated mirror-on-sync

---

tests/foreman/ui/test_capsulecontent.py

UI coverage for Capsule Content Counts (new in 6.15) is missing.
This PR.
requires https://github.com/SatelliteQE/airgun/pull/1050

Add UI test for Capsule Content Counts

---

tests/foreman/api/test_provisioning.py
tests/foreman/api/test_provisioningtemplate.py

(cherry picked from commit b7ce955601e9b7bc5ffad9133ee0fdacb779fb5c)
Manual Cherrypick of https://github.com/SatelliteQE/robottelo/pull/12695

[6.13.z] Add test coverage for provisioning with fips_enabled

---

tests/foreman/api/test_provisioning.py
tests/foreman/api/test_provisioningtemplate.py

Cherrypick of https://github.com/SatelliteQE/robottelo/pull/12695
Fixes https://github.com/SatelliteQE/robottelo/issues/13455

[6.14.z] Add test coverage for provisioning with fips_enabled

---

tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13425
`mirror-on-sync` was deprecated and replaced by `mirroring-policy` in Katello 4.8.0 (see https://projects.theforeman.org/issues/36140)
However, it seems there are last two remaining occurrences in robottelo which need to be updated if we don't wish to see errors like this:
```
Error: Unrecognised option '--mirror-on-sync'.
```
Get rid of the deprecated `mirror-on-sync` option.

[6.14.z] Get rid of deprecated mirror-on-sync

---

tests/foreman/api/test_ansible.py

Cherry pick of https://github.com/SatelliteQE/robottelo/pull/11688/files

bz1699188_6.12

---

tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13425
`mirror-on-sync` was deprecated and replaced by `mirroring-policy` in Katello 4.8.0 (see https://projects.theforeman.org/issues/36140)
However, it seems there are last two remaining occurrences in robottelo which need to be updated if we don't wish to see errors like this:
```
Error: Unrecognised option '--mirror-on-sync'.
```
Get rid of the deprecated `mirror-on-sync` option.

[6.15.z] Get rid of deprecated mirror-on-sync

---

tests/foreman/api/test_contentview.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13378
More fixes surrounding the recent rework to remove directly calling entity methods.

[6.15.z] Fixes for CV Tests

---

tests/foreman/cli/test_errata.py

Installing erratum on a host-collection made a direct call to Katello-agent(removed) 
This PR removes failing outdated tests and modifies one to assert the new error message that gets returned

[Errata Comp-Eval] Removing old errata tests and adding new assertion

---

tests/foreman/api/test_discoveryrule.py

Fix discovery rule tests-> The test was failing in the teardown when trying to delete the created location, we need to delete both the hosts to run the teardown properly

Fix discovery rule tests

---

tests/foreman/api/test_provisioning.py

katello-ca-consumer is deprecated and the subscription manager is used to register hosts during provisioning
Update the provisioning test to check if hosts are registered using katello-ca-consumer.

Add Closedloop BZ#2153548

---

tests/foreman/maintain/test_health.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13379
We switched the package manager from yum to dnf. https://github.com/theforeman/foreman_maintain/blob/master/definitions/checks/package_manager/dnf/validate_dnf_config.rb#L5
Change our test from yum to dnf

[6.15.z] Change yum config to dnf

---

tests/foreman/ui/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13460
Check for Default values on Global Registration Template

[6.15.z] Audit: Check for Default values on Global Registration Template

---

tests/foreman/ui/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13480
Registration Component Audit: Check org and loc change on the Global Registration form

[6.15.z] Component Audit: Check org and loc change on Global Registration form

---

pytest_fixtures/component/repository.py
tests/foreman/destructive/test_clone.py

https://bugzilla.redhat.com/show_bug.cgi?id=2013776 details running rsync to copy pulp data from the Satellite to the target server after running satellite-clone. This is due to satellite-clone using satellite-maintain restore which runs the installer with --reset-data.
Switch satellite-clone tests that are running --skip-pulp-data for the backup to rsync the pulp data after we run the clone process.

Use rsync to copy /var/lib/pulp after satellite-clone

---

tests/foreman/api/test_role.py
tests/foreman/api/test_user.py

Few test form foreman/api for user and role were failing due to absense of `server_config` keyword argument.
Provided fix will resovle issue, adding `server_config` parameter into entity calls.

fix server config from user and role test module

---

tests/foreman/api/test_role.py
tests/foreman/api/test_user.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13465
Few test form foreman/api for user and role were failing due to absense of `server_config` keyword argument.
Provided fix will resovle issue, adding `server_config` parameter into entity calls.

[6.14.z] fix server config from user and role test module

---

tests/foreman/ui/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13351
UI coverage for Capsule Content Counts (new in 6.15) is missing.
This PR.
requires https://github.com/SatelliteQE/airgun/pull/1050

[6.15.z] Add UI test for Capsule Content Counts

---

tests/foreman/api/test_provisioning.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13466
katello-ca-consumer is deprecated and the subscription manager is used to register hosts during provisioning
Update the provisioning test to check if hosts are registered using katello-ca-consumer.

[6.15.z] Add Closedloop BZ#2153548

---

tests/foreman/api/test_role.py
tests/foreman/api/test_user.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13465
Few test form foreman/api for user and role were failing due to absense of `server_config` keyword argument.
Provided fix will resovle issue, adding `server_config` parameter into entity calls.

[6.15.z] fix server config from user and role test module

---

tests/foreman/api/test_registration.py
tests/foreman/cli/test_registration.py
tests/foreman/ui/test_registration.py

Missing negative tests for registration without AK, suggested by SD
Add negative tests for registration without AK for UI/CLI/API, as part of component audit.
https://github.com/SatelliteQE/airgun/pull/1087

Add negative tests for registration without AK

---

tests/foreman/api/test_registration.py
tests/foreman/cli/test_registration.py
tests/foreman/ui/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13490
Missing negative tests for registration without AK, suggested by SD
Add negative tests for registration without AK for UI/CLI/API, as part of component audit.
https://github.com/SatelliteQE/airgun/pull/1087

[6.15.z] Add negative tests for registration without AK

---

requirements.txt
scripts/polarion-test-case-upload.sh

The list of markers to be ignored during polarion tests collection in `markers` field is missing.
New variable `MARKERS_IGNORE_LIST`  in `betelgeuse_config.py` should ignore these markers while test collection by betelgeuse.

Configurable Ignore list of markers test field in polarion tests

---

pytest_fixtures/component/repository.py
tests/foreman/destructive/test_clone.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13443
https://bugzilla.redhat.com/show_bug.cgi?id=2013776 details running rsync to copy pulp data from the Satellite to the target server after running satellite-clone. This is due to satellite-clone using satellite-maintain restore which runs the installer with --reset-data.
Switch satellite-clone tests that are running --skip-pulp-data for the backup to rsync the pulp data after we run the clone process.

[6.15.z] Use rsync to copy /var/lib/pulp after satellite-clone

---

tests/foreman/api/test_provisioning.py

Adding a stubbed test for realm provisioning. Currently, we do not have support for running provisioning tests on destructive sat which is planned in future for provisioning improvements and this test will then be automated.

Add Stubbed test for realm provisioning

---

tests/foreman/api/test_provisioning.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13524
Adding a stubbed test for realm provisioning. Currently, we do not have support for running provisioning tests on destructive sat which is planned in future for provisioning improvements and this test will then be automated.

[6.15.z] Add Stubbed test for realm provisioning

---

tests/foreman/api/test_provisioning.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13524
Adding a stubbed test for realm provisioning. Currently, we do not have support for running provisioning tests on destructive sat which is planned in future for provisioning improvements and this test will then be automated.

[6.14.z] Add Stubbed test for realm provisioning

---

tests/foreman/api/test_provisioning.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13524
Adding a stubbed test for realm provisioning. Currently, we do not have support for running provisioning tests on destructive sat which is planned in future for provisioning improvements and this test will then be automated.

[6.13.z] Add Stubbed test for realm provisioning

---

tests/foreman/api/test_registration.py
tests/foreman/cli/test_registration.py
tests/foreman/ui/test_registration.py

(cherry picked from commit 48735b00ba4b7acbd983bd06e9f2342fbfa08163)
Manual cheryypick of https://github.com/SatelliteQE/robottelo/pull/13490
Dependant PRs:
https://github.com/SatelliteQE/airgun/pull/1095

Add negative tests for registration without AK (#13490)

---

tests/foreman/api/test_provisioningtemplate.py

(cherry picked from commit 80e6ba456b9ae6f4b6171033975d5c94429b3acd)
Cherrypick of https://github.com/SatelliteQE/robottelo/pull/13518
Fixes https://github.com/SatelliteQE/robottelo/issues/13529
Add coverage for rex pull mode provisioning snippet "remote_execution_pull_setup"

Add coverage for rex pull mode provisioning snippet

---

tests/foreman/api/test_provisioningtemplate.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13518
Add coverage for rex pull mode provisioning snippet "remote_execution_pull_setup"

[6.15.z] Add coverage for rex pull mode provisioning snippet

---

requirements.txt
scripts/polarion-test-case-upload.sh

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13492
The list of markers to be ignored during polarion tests collection in `markers` field is missing.
New variable `MARKERS_IGNORE_LIST`  in `betelgeuse_config.py` should ignore these markers while test collection by betelgeuse.

[6.14.z] Configurable Ignore list of markers test field in polarion tests

---

requirements.txt
scripts/polarion-test-case-upload.sh

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13492
The list of markers to be ignored during polarion tests collection in `markers` field is missing.
New variable `MARKERS_IGNORE_LIST`  in `betelgeuse_config.py` should ignore these markers while test collection by betelgeuse.

[6.12.z] Configurable Ignore list of markers test field in polarion tests

---

requirements.txt
scripts/polarion-test-case-upload.sh

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13492
The list of markers to be ignored during polarion tests collection in `markers` field is missing.
New variable `MARKERS_IGNORE_LIST`  in `betelgeuse_config.py` should ignore these markers while test collection by betelgeuse.

[6.15.z] Configurable Ignore list of markers test field in polarion tests

---

robottelo/host_helpers/cli_factory.py
tests/foreman/cli/test_errata.py

**Com eval -** 2 tests were failing due to cli factory method > `setup_org_for_a_rh_repo` with error mentioned below
`test_positive_list_filter_by_org_sort_by_date`
`test_positive_list_filter_by_cve`
**Error:**
> E   AttributeError: 'Manifest' object has no attribute 'path'
Basically due to old way of cloning and uploading manifest into the satellite didn't work, also as per `6.15.z` and later version of satellite `*_sca_manifest_org` fixture is supposed to be used.
With this fix above 2 tests and couple of few tests are expected to get fix.
The below 2 tests will get benifit of the change made in cli_factory and will pass accordingly.
`cli.test_activationkey.py > test_positive_subscription_quantity_attached`
`cli.test_host.py > test_negative_without_attach_with_lce`

fix cli errata tests and update cli factory method

---

robottelo/host_helpers/cli_factory.py
tests/foreman/cli/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13505
**Com eval -** 2 tests were failing due to cli factory method > `setup_org_for_a_rh_repo` with error mentioned below
`test_positive_list_filter_by_org_sort_by_date`
`test_positive_list_filter_by_cve`
**Error:**
> E   AttributeError: 'Manifest' object has no attribute 'path'
Basically due to old way of cloning and uploading manifest into the satellite didn't work, also as per `6.15.z` and later version of satellite `*_sca_manifest_org` fixture is supposed to be used.
With this fix above 2 tests and couple of few tests are expected to get fix.
The below 2 tests will get benifit of the change made in cli_factory and will pass accordingly.
`cli.test_activationkey.py > test_positive_subscription_quantity_attached` …

[6.14.z] fix cli errata tests and update cli factory method

---

robottelo/host_helpers/cli_factory.py
tests/foreman/cli/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13505
**Com eval -** 2 tests were failing due to cli factory method > `setup_org_for_a_rh_repo` with error mentioned below
`test_positive_list_filter_by_org_sort_by_date`
`test_positive_list_filter_by_cve`
**Error:**
> E   AttributeError: 'Manifest' object has no attribute 'path'
Basically due to old way of cloning and uploading manifest into the satellite didn't work, also as per `6.15.z` and later version of satellite `*_sca_manifest_org` fixture is supposed to be used.
With this fix above 2 tests and couple of few tests are expected to get fix.
The below 2 tests will get benifit of the change made in cli_factory and will pass accordingly.
`cli.test_activationkey.py > test_positive_subscription_quantity_attached` …

[6.15.z] fix cli errata tests and update cli factory method

---

robottelo/hosts.py

extra check not recording property incase of video recording is false

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13475

[6.15.z] extra check not recording property incase of video recording is false

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13475

[6.14.z] extra check not recording property incase of video recording is false

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13475

[6.13.z] extra check not recording property incase of video recording is false

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13475

[6.12.z] extra check not recording property incase of video recording is false

---

pytest_fixtures/component/provision_capsule_pxe.py

Missed in https://github.com/SatelliteQE/robottelo/pull/13241
Update `s/request.param/request.param['rhel_version']` for parametrization
Already updated and tested this in cherrypick PRs https://github.com/SatelliteQE/robottelo/pull/13557 and it works, so just need this change in master

Fix parametrization in capsule provisioning fixture

---

pytest_fixtures/core/sat_cap_factory.py
robottelo/hosts.py
tests/foreman/destructive/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13565
Missing test coverage for registration with rex pull-mode against Satellite and Capsule
Add test coverage for registration with rex pull-mode against Satellite and Capsule

[6.14.z] Add test for registration with rex pull-mode

---

pytest_fixtures/core/sat_cap_factory.py
robottelo/hosts.py
tests/foreman/destructive/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13565
Missing test coverage for registration with rex pull-mode against Satellite and Capsule
Add test coverage for registration with rex pull-mode against Satellite and Capsule

[6.15.z] Add test for registration with rex pull-mode

---

pytest_fixtures/core/sat_cap_factory.py
robottelo/hosts.py
tests/foreman/destructive/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13565
Missing test coverage for registration with rex pull-mode against Satellite and Capsule
Add test coverage for registration with rex pull-mode against Satellite and Capsule

[6.13.z] Add test for registration with rex pull-mode

---

robottelo/cli/capsule.py
tests/foreman/cli/test_capsulecontent.py

CLI coverage for Capsule Content Counts (new in 6.15) is missing.
This PR.

Add CLI tests for Capsule Content Counts

---

conftest.py
pytest_fixtures/component/provision_capsule_pxe.py
pytest_plugins/fixture_markers.py
tests/foreman/api/test_provisioning.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13241
Adding a test for provisioning using an external capsule.

[6.13.z] Add Capsule Provisioning test

---

robottelo/cli/capsule.py
tests/foreman/cli/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13163
CLI coverage for Capsule Content Counts (new in 6.15) is missing.
This PR.

[6.15.z] Add CLI tests for Capsule Content Counts

---

robottelo/cli/org.py
tests/foreman/cli/test_satellitesync.py

Network Sync functionality of ISS hasn't been automated yet, coverage is missing.
This PR adds new class with first scenario to cover Network Sync. The previous classes will be refactored in one of next PRs since they don't reflect the reality and the change should be CPed deeper than this PR is.
Covers this customer case BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2213128

Add ISS Network Sync class and basic scenario

---

tests/foreman/ui/test_settings.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13560
Missing test for show_unsupported_templates setting
Solution
Add test for show_unsupported_templates setting

[6.13.z] Add test for show_unsupported_templates setting

---

tests/foreman/ui/test_settings.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13560
Missing test for show_unsupported_templates setting
Solution
Add test for show_unsupported_templates setting

[6.12.z] Add test for show_unsupported_templates setting

---

robottelo/cli/org.py
tests/foreman/cli/test_satellitesync.py

Manual cherry-pick of #13543 
Closes https://github.com/SatelliteQE/robottelo/issues/13586

[6.15.z] Add ISS Network Sync class and basic scenario

---

pytest_plugins/metadata_markers.py
tests/foreman/virtwho/ui/test_nutanix_sca.py

Test Markers as test metadata in Polarion, RP and Ibutsu reporting tools.
These markers would be used in RP and ibutsu to filter the results based on markers !

Markers as test property in reports

---

pytest_fixtures/component/repository.py
tests/foreman/destructive/test_clone.py

Manual cherry-pick for https://github.com/SatelliteQE/robottelo/pull/13443

[6.13.z] Use rsync to copy /var/lib/pulp after satellite-clone

---

tests/foreman/api/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13282
Adding closed loop for BZ#1841048 ->  Ability specify REX interface upon registration

[6.12.z] Add closed loop for BZ#1841048

---

pytest_fixtures/core/sat_cap_factory.py
robottelo/hosts.py
tests/foreman/installer/test_installer.py

Missing test coverage for Satellite and Capsule installation with fapolicyd
Update existing test for fapolicyd
- https://issues.redhat.com/browse/SAT-20551

Add test for fapolicyd installation

---

pytest_fixtures/core/sat_cap_factory.py
robottelo/hosts.py
tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13488
Missing test coverage for Satellite and Capsule installation with fapolicyd
Update existing test for fapolicyd
- https://issues.redhat.com/browse/SAT-20551

[6.15.z] Add test for fapolicyd installation

---

pytest_plugins/metadata_markers.py
tests/foreman/virtwho/ui/test_nutanix_sca.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13043
Test Markers as test metadata in Polarion, RP and Ibutsu reporting tools.
These markers would be used in RP and ibutsu to filter the results based on markers !

[6.15.z] Markers as test property in reports

---

pytest_plugins/metadata_markers.py
tests/foreman/virtwho/ui/test_nutanix_sca.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13043
Test Markers as test metadata in Polarion, RP and Ibutsu reporting tools.
These markers would be used in RP and ibutsu to filter the results based on markers !

[6.14.z] Markers as test property in reports

---

pytest_plugins/metadata_markers.py
tests/foreman/virtwho/ui/test_nutanix_sca.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13043
Test Markers as test metadata in Polarion, RP and Ibutsu reporting tools.
These markers would be used in RP and ibutsu to filter the results based on markers !

[6.13.z] Markers as test property in reports

---

pytest_plugins/metadata_markers.py

Cherrypick failed for https://github.com/SatelliteQE/robottelo/pull/13043 to 6.12.z
Manually cherrypicking !
None

[6.12.z] Markers as test property in reports (#13043)

---

pytest_plugins/metadata_markers.py

Fixing the missing markers as independent properties

---

tests/foreman/installer/test_installer.py

https://bugzilla.redhat.com/show_bug.cgi?id=1984400 details how having an HTTP Proxy set in the settings can cause capsule installation / upgrade fail.
Add coverage here by setting an HTTP proxy before running a capsule installation to ensure we don't regress.

Add coverage for HTTP Proxy capsule install

---

tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13507
https://bugzilla.redhat.com/show_bug.cgi?id=1984400 details how having an HTTP Proxy set in the settings can cause capsule installation / upgrade fail.
Add coverage here by setting an HTTP proxy before running a capsule installation to ensure we don't regress.

[6.15.z] Add coverage for HTTP Proxy capsule install

---

tests/foreman/ui/test_host.py

Changing the team of these 2 tests to Phoenix-subscriptions to match the component, quick merge would be appreciated.

Change team to pheonix-subscriptions to match the Hosts-Content team

---

pytest_plugins/metadata_markers.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13599
No.

[6.15.z] Fixing the missing markers as independent properties

---

pytest_plugins/metadata_markers.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13599
No.

[6.14.z] Fixing the missing markers as independent properties

---

pytest_plugins/metadata_markers.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13599
No.

[6.13.z] Fixing the missing markers as independent properties

---

pytest_plugins/metadata_markers.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13599
No.

[6.12.z] Fixing the missing markers as independent properties

---

tests/upgrades/test_classparameter.py

Correct Casecomponent in upgrades/test_classparameter.py

---

tests/upgrades/test_classparameter.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13621

[6.15.z] Correct Casecomponent in upgrades/test_classparameter.py

---

tests/foreman/ui/test_organization.py

6.15 Feature automation: SAT-20201
This test is verifying that that Simple Content Access endpoints are deprecated and will be required
for all organizations in Katello 4.12
Copy of https://github.com/SatelliteQE/robottelo/pull/13045

[6.15] Prepare for SCA only deprecation 6.15

---

tests/upgrades/test_classparameter.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13621

[6.14.z] Correct Casecomponent in upgrades/test_classparameter.py

---

tests/upgrades/test_classparameter.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13621

[6.13.z] Correct Casecomponent in upgrades/test_classparameter.py

---

tests/upgrades/test_classparameter.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13621

[6.12.z] Correct Casecomponent in upgrades/test_classparameter.py

---

tests/foreman/api/test_parameters.py

Missing test to verify parameter precedence on the host
Applying the component audit feedback to cover this scenario and adding test to verify parameter precedence on the host for Global/HostGroup/Host parameters

Add a test for parameter precedence on the host

---

tests/foreman/api/test_parameters.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13620
Missing test to verify parameter precedence on the host
Applying the component audit feedback to cover this scenario and adding test to verify parameter precedence on the host for Global/HostGroup/Host parameters

[6.14.z] Add a test for parameter precedence on the host

---

tests/foreman/api/test_parameters.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13620
Missing test to verify parameter precedence on the host
Applying the component audit feedback to cover this scenario and adding test to verify parameter precedence on the host for Global/HostGroup/Host parameters

[6.15.z] Add a test for parameter precedence on the host

---

tests/foreman/cli/test_satellitesync.py

1. Custom CDN with custom ContentCredential scenario is still missing.
2. Misleading name of one fixture.
1. Add new test case to cover Custom CDN with CC.
2. Rename the fixture.
https://bugzilla.redhat.com/show_bug.cgi?id=2112098

Add coverage for BZ#2112098

---

tests/foreman/cli/test_activationkey.py

This parametrized test has been failing in 6.15 and 6.14 for some time. The error is
```
E   Warning: Option --environment is deprecated. Use --lifecycle-environment instead
E   Could not create the activation key:
E     Validation failed: Content view 'wMjLDMSyxhndvsDSHyvRFeLOBOZEhOXzLLPwsLcrCJvvAhR' is not in environment 'Library'
```
When creating an AK via UI we provide LCE first and then CV, which needs to be published/promoted to that LCE. Using that validation for CLI is right.
1. Publish the CV so that it IS in Library LCE.
2. Replace deprecated `environment` with newer `lifecycle-environment`.

Fix test AK create with CV

---

tests/foreman/cli/test_activationkey.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13642
This parametrized test has been failing in 6.15 and 6.14 for some time. The error is
```
E   Warning: Option --environment is deprecated. Use --lifecycle-environment instead
E   Could not create the activation key:
E     Validation failed: Content view 'wMjLDMSyxhndvsDSHyvRFeLOBOZEhOXzLLPwsLcrCJvvAhR' is not in environment 'Library'
```
When creating an AK via UI we provide LCE first and then CV, which needs to be published/promoted to that LCE. Using that validation for CLI is right.
1. Publish the CV so that it IS in Library LCE.
2. Replace deprecated `environment` with newer `lifecycle-environment`.

[6.15.z] Fix test AK create with CV

---

tests/foreman/api/test_permission.py
tests/foreman/api/test_role.py
tests/foreman/cli/test_role.py

manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13433
closes https://github.com/SatelliteQE/robottelo/issues/13441

[6.13] users and roles test fixes

---

tests/foreman/api/test_permission.py
tests/foreman/api/test_role.py
tests/foreman/cli/test_role.py

manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13433
closes https://github.com/SatelliteQE/robottelo/issues/13438

[6.12] users and roles test fixes

---

tests/foreman/api/test_parameters.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13620
Missing test to verify parameter precedence on the host
Applying the component audit feedback to cover this scenario and adding test to verify parameter precedence on the host for Global/HostGroup/Host parameters

[6.13.z] Add a test for parameter precedence on the host

---

tests/foreman/api/test_registration.py
tests/foreman/cli/test_registration.py

There was a conflict in manifest fixture as both sca and non-sca enabled fixture was being used in same test case. 
Updated the test case to fix the test failures.

Update manifest fixture in registration test to resolve conflict

---

tests/foreman/cli/test_remoteexecution.py

assert_job_invocation_status requires satellite as a first argument (since recent refactor), but the calls were not providing it, hence ~3 test failures
Updating the calls to include target_sat. For reason unknown, this problem occurs only in master and 6.15

fix assert_job_invocation_status calls

---

tests/foreman/cli/test_remoteexecution.py

possibly overlooked in https://github.com/SatelliteQE/robottelo/pull/11544 , causing `AttributeError: 'Satellite' object has no attribute 'make_job_invocation'`
fixed the syntax

fixing a forgotten make_job_invocaiton call

---

tests/foreman/api/test_registration.py
tests/foreman/cli/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13616
There was a conflict in manifest fixture as both sca and non-sca enabled fixture was being used in same test case. 
Updated the test case to fix the test failures.

[6.15.z] Update manifest fixture in registration test to resolve conflict

---

tests/foreman/cli/test_syncplan.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13661
Syntax fix.

[6.15.z] Small fix for SyncPlan test

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13648
possibly overlooked in https://github.com/SatelliteQE/robottelo/pull/11544 , causing `AttributeError: 'Satellite' object has no attribute 'make_job_invocation'`
fixed the syntax

[6.15.z] fixing a forgotten make_job_invocaiton call

---

tests/foreman/ui/test_host.py

Cherrypick of tests that missed the cutover from stream. 
Requires: https://github.com/SatelliteQE/airgun/pull/1121
Original PR: https://github.com/SatelliteQE/robottelo/pull/13120

Cherrypick of 6.15 tests to 6.15.z

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13648
possibly overlooked in https://github.com/SatelliteQE/robottelo/pull/11544 , causing `AttributeError: 'Satellite' object has no attribute 'make_job_invocation'`
fixed the syntax

[6.14.z] fixing a forgotten make_job_invocaiton call

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13648
possibly overlooked in https://github.com/SatelliteQE/robottelo/pull/11544 , causing `AttributeError: 'Satellite' object has no attribute 'make_job_invocation'`
fixed the syntax

[6.13.z] fixing a forgotten make_job_invocaiton call

---

pytest_fixtures/core/ui.py
tests/foreman/ui/test_activationkey.py
tests/foreman/ui/test_bookmarks.py
tests/foreman/ui/test_branding.py
tests/foreman/ui/test_contenthost.py
tests/foreman/ui/test_contentview_old.py
tests/foreman/ui/test_dashboard.py
tests/foreman/ui/test_discoveryrule.py
tests/foreman/ui/test_errata.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_ldap_authentication.py
tests/foreman/ui/test_lifecycleenvironment.py
tests/foreman/ui/test_repository.py
tests/foreman/ui/test_role.py
tests/foreman/ui/test_settings.py
tests/foreman/ui/test_subscription.py
tests/foreman/ui/test_user.py
tests/foreman/virtwho/conftest.py
tests/foreman/virtwho/ui/test_esx.py

- Remove the Airgun Imports from the Robottelo and Use `target_sat.ui_session` or `module_target_sat.ui`
- UI tests are updated to use the modified "target_sat" or "module_target_sat" for efficient management of multiple browser sessions.
- The streamlined UI tests function correctly and manage browser sessions effectively.
- Remove the nailgun entities from the UI code considering the Airgun Imports (some more PR needs to be added remove this as not wanted to do everything in single PR)

Removing the direct Airgun imports from robottelo

---

tests/foreman/api/test_discoveryrule.py

Removing stubbed marker

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13647
assert_job_invocation_status requires satellite as a first argument (since recent refactor), but the calls were not providing it, hence ~3 test failures
Updating the calls to include target_sat. For reason unknown, this problem occurs only in master and 6.15

[6.15.z] fix assert_job_invocation_status calls

---

tests/foreman/ui/test_activationkey.py
tests/foreman/ui/test_contenthost.py
tests/foreman/ui/test_organization.py
tests/foreman/ui/test_subscription.py

Cherrypick of https://github.com/SatelliteQE/robottelo/pull/13004
Issue: https://github.com/SatelliteQE/robottelo/issues/13356

[Cherrypick]Prepare for sca web ui 6.15.z

---

pytest_fixtures/component/virtwho_config.py
robottelo/utils/virtwho.py
tests/foreman/virtwho/cli/test_esx_sca.py

virtwho config hammer deploy option name organization-title and location-id support
Satellite6.15 PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_esx_sca.py  -k test_positive_deploy_configure_by_id_script_name_locationid_organizationtitle[name] --disable-pytest-warnings -q
1 passed, 37 deselected, 10 warnings in 121.35s (0:02:01)
2024-01-08 01:21:37 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest …
```

virtwho config hammer deploy option name organization-title and location-id support

---

tests/foreman/cli/test_remoteexecution.py

Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13648 closes https://github.com/SatelliteQE/robottelo/issues/13656

[6.12] fixing a forgotten make_job_invocaiton call

---

tests/foreman/ui/test_discoveredhost.py

```
tests/foreman/ui/test_discoveredhost.py:197: in test_positive_auto_provision_host_with_rule
domain_name = provisioning_hostgroup.domain.name
E   AttributeError: 'Domain' object has no attribute 'name'
```
read Domain first after that name attribute is accessible, same is present in other tests

Fix domain read in discovery auto provision test

---

tests/foreman/ui/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13708
```
tests/foreman/ui/test_discoveredhost.py:197: in test_positive_auto_provision_host_with_rule
domain_name = provisioning_hostgroup.domain.name
E   AttributeError: 'Domain' object has no attribute 'name'
```
read Domain first after that name attribute is accessible, same is present in other tests

[6.15.z] Fix domain read in discovery auto provision test

---

tests/foreman/ui/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13708
```
tests/foreman/ui/test_discoveredhost.py:197: in test_positive_auto_provision_host_with_rule
domain_name = provisioning_hostgroup.domain.name
E   AttributeError: 'Domain' object has no attribute 'name'
```
read Domain first after that name attribute is accessible, same is present in other tests

[6.14.z] Fix domain read in discovery auto provision test

---

pyproject.toml
robottelo/host_helpers/cli_factory.py
robottelo/host_helpers/satellite_mixins.py
robottelo/hosts.py

Removing changes associated with Bugbear rule B019

---

pyproject.toml
robottelo/host_helpers/cli_factory.py
robottelo/host_helpers/satellite_mixins.py
robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13715

[6.15.z] Removing changes associated with Bugbear rule B019

---

pyproject.toml
robottelo/host_helpers/cli_factory.py
robottelo/host_helpers/satellite_mixins.py
robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13715

[6.13.z] Removing changes associated with Bugbear rule B019

---

pyproject.toml
robottelo/host_helpers/cli_factory.py
robottelo/host_helpers/satellite_mixins.py
robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13715

[6.14.z] Removing changes associated with Bugbear rule B019

---

robottelo/hosts.py

fixing the incorrect recording video URL for recorded failed tests.  
This PR will fix the URL and point to the correct URL in the report portal.

fixing the incorrect recording video url

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13714
fixing the incorrect recording video URL for recorded failed tests.  
This PR will fix the URL and point to the correct URL in the report portal.

[6.14.z] fixing the incorrect recording video url

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13714
fixing the incorrect recording video URL for recorded failed tests.  
This PR will fix the URL and point to the correct URL in the report portal.

[6.15.z] fixing the incorrect recording video url

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13714
fixing the incorrect recording video URL for recorded failed tests.  
This PR will fix the URL and point to the correct URL in the report portal.

[6.13.z] fixing the incorrect recording video url

---

pyproject.toml
robottelo/host_helpers/cli_factory.py
robottelo/host_helpers/satellite_mixins.py
robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13715

[6.12.z] Removing changes associated with Bugbear rule B019

---

robottelo/cli/hammer.py

The CLI command output containing non-tabular string is not eligible for CSV conversation.
e.g:
STDOUT like 
```
stdout:
Added Rpms: 32, Errata: 4
Total steps: 84/84
--------------------------------
Associating Content: 39/39
Downloading Artifacts: 0/0
Downloading Metadata Files: 6/6
Parsed Advisories: 4/4
Parsed Comps: 3/3
Parsed Packages: 32/32
Skipping Packages: 0/0
Un-Associating Content: 0/0
```
Here zipping in csv conversion function trying to zip the first row of 2 key_value pairs `Added Rpms: 32, Errata: 4` with 1 row of key_value from next line ` Total steps: 84/84`. Since strict is set to `True` the numbe of contents from first row and second row should match which does match with the tabular format but not the above-like output. Making the the strict zipping to fail.
Returning …

Non tabular output denied for CSV conversion

---

robottelo/cli/hammer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13737
The CLI command output containing non-tabular string is not eligible for CSV conversation.
e.g:
STDOUT like 
```
stdout:
Added Rpms: 32, Errata: 4
Total steps: 84/84
--------------------------------
Associating Content: 39/39
Downloading Artifacts: 0/0
Downloading Metadata Files: 6/6
Parsed Advisories: 4/4
Parsed Comps: 3/3
Parsed Packages: 32/32
Skipping Packages: 0/0
Un-Associating Content: 0/0
```
Here zipping in csv conversion function trying to zip the first row of 2 key_value pairs `Added Rpms: 32, Errata: 4` with 1 row of key_value from next line ` Total steps: 84/84`. Since strict is set to `True` the numbe of contents from first row and second row should match which does match with the tabular format but not …

[6.15.z] Non tabular output denied for CSV conversion

---

robottelo/cli/hammer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13737
The CLI command output containing non-tabular string is not eligible for CSV conversation.
e.g:
STDOUT like 
```
stdout:
Added Rpms: 32, Errata: 4
Total steps: 84/84
--------------------------------
Associating Content: 39/39
Downloading Artifacts: 0/0
Downloading Metadata Files: 6/6
Parsed Advisories: 4/4
Parsed Comps: 3/3
Parsed Packages: 32/32
Skipping Packages: 0/0
Un-Associating Content: 0/0
```
Here zipping in csv conversion function trying to zip the first row of 2 key_value pairs `Added Rpms: 32, Errata: 4` with 1 row of key_value from next line ` Total steps: 84/84`. Since strict is set to `True` the numbe of contents from first row and second row should match which does match with the tabular format but not …

[6.14.z] Non tabular output denied for CSV conversion

---

robottelo/cli/hammer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13737
The CLI command output containing non-tabular string is not eligible for CSV conversation.
e.g:
STDOUT like 
```
stdout:
Added Rpms: 32, Errata: 4
Total steps: 84/84
--------------------------------
Associating Content: 39/39
Downloading Artifacts: 0/0
Downloading Metadata Files: 6/6
Parsed Advisories: 4/4
Parsed Comps: 3/3
Parsed Packages: 32/32
Skipping Packages: 0/0
Un-Associating Content: 0/0
```
Here zipping in csv conversion function trying to zip the first row of 2 key_value pairs `Added Rpms: 32, Errata: 4` with 1 row of key_value from next line ` Total steps: 84/84`. Since strict is set to `True` the numbe of contents from first row and second row should match which does match with the tabular format but not …

[6.13.z] Non tabular output denied for CSV conversion

---

robottelo/cli/repository.py
robottelo/host_helpers/cli_factory.py
tests/foreman/cli/test_capsulecontent.py

Try to run the `test_dummie` with and without the changes.
For the `csv` format you get:
```
E   ValueError: zip() argument 2 is shorter than argument 1
```
For the `@lru_cache` present you get:
```
E           Could not create the repository:
E             Validation failed: Name has already been taken for this product., Label has already been taken for this product., Download policy Cannot set attribute download_policy for content type file
```

Fixes in cli_factory

---

tests/foreman/api/test_discoveredhost.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/ui/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13741
The Mac address is not getting collected properly so increasing the timeout.

[6.13.z] Increasing the timeout for mac collection

---

tests/foreman/api/test_provisioning.py

Missing `on_premises_provisioning` marker for capsule provisioning test
Adding `on_premises_provisioning` marker for capsule provisioning test

Add missing on_premises_provisioning marker for capsule provisioning test

---

tests/foreman/cli/test_ping.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13489
Cache status was added to `hammer ping` output and there can be more cache servers configured so the output syntax has changed. I changed and simplified the test so it can parse current output and it also meets test description.
sample output:
```
database:         
Status:          ok
Server Response: Duration: 0ms
cache:            
servers: 
1) Status:          ok
Server Response: Duration: 0ms
candlepin:        
Status:          ok
Server Response: Duration: 23ms
...
```
PS: I'm not aware of negative scenario for this testcase (i.e. scenario when some of Satellite services report status "FAIL"). We may add it in future.

[6.15.z] Refactor and simplify ping test

---

tests/foreman/api/test_provisioning.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13760
Missing `on_premises_provisioning` marker for capsule provisioning test
Adding `on_premises_provisioning` marker for capsule provisioning test

[6.15.z] Add missing on_premises_provisioning marker for capsule provisioning test

---

tests/foreman/api/test_provisioning.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13760
Missing `on_premises_provisioning` marker for capsule provisioning test
Adding `on_premises_provisioning` marker for capsule provisioning test

[6.14.z] Add missing on_premises_provisioning marker for capsule provisioning test

---

tests/foreman/api/test_provisioning.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13760
Missing `on_premises_provisioning` marker for capsule provisioning test
Adding `on_premises_provisioning` marker for capsule provisioning test

[6.13.z] Add missing on_premises_provisioning marker for capsule provisioning test

---

tests/foreman/destructive/test_installer.py

Missing coverage for BZ 2025760.
Add new test to cover the scenario for changing the puma worker count.

Add CU scenario for puma worker count

---

tests/foreman/destructive/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13544
Missing coverage for BZ 2025760.
Add new test to cover the scenario for changing the puma worker count.

[6.14.z] Add CU scenario for puma worker count

---

pytest_fixtures/component/virtwho_config.py
robottelo/utils/virtwho.py
tests/foreman/virtwho/cli/test_esx_sca.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13632
virtwho config hammer deploy option name organization-title and location-id support
Satellite6.15 PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_esx_sca.py  -k test_positive_deploy_configure_by_id_script_name_locationid_organizationtitle[name] --disable-pytest-warnings -q
1 passed, 37 deselected, 10 warnings in 121.35s (0:02:01)
2024-01-08 01:21:37 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
(robottelo_vv) …
```

[6.15.z] virtwho config hammer deploy option name organization-title and location-id support

---

pytest_fixtures/component/virtwho_config.py
robottelo/utils/virtwho.py
tests/foreman/virtwho/cli/test_esx_sca.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13632
virtwho config hammer deploy option name organization-title and location-id support
Satellite6.15 PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_esx_sca.py  -k test_positive_deploy_configure_by_id_script_name_locationid_organizationtitle[name] --disable-pytest-warnings -q
1 passed, 37 deselected, 10 warnings in 121.35s (0:02:01)
2024-01-08 01:21:37 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
(robottelo_vv) …
```

[6.14.z] virtwho config hammer deploy option name organization-title and location-id support

---

pytest_fixtures/component/virtwho_config.py
robottelo/utils/virtwho.py
tests/foreman/virtwho/cli/test_esx_sca.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13632
virtwho config hammer deploy option name organization-title and location-id support
Satellite6.15 PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/cli/test_esx_sca.py  -k test_positive_deploy_configure_by_id_script_name_locationid_organizationtitle[name] --disable-pytest-warnings -q
1 passed, 37 deselected, 10 warnings in 121.35s (0:02:01)
2024-01-08 01:21:37 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
(robottelo_vv) …
```

[6.13.z] virtwho config hammer deploy option name organization-title and location-id support

---

pytest_fixtures/core/ui.py
tests/foreman/ui/test_activationkey.py
tests/foreman/ui/test_bookmarks.py
tests/foreman/ui/test_branding.py
tests/foreman/ui/test_contenthost.py
tests/foreman/ui/test_dashboard.py
tests/foreman/ui/test_discoveryrule.py
tests/foreman/ui/test_errata.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_ldap_authentication.py
tests/foreman/ui/test_lifecycleenvironment.py
tests/foreman/ui/test_repository.py
tests/foreman/ui/test_role.py
tests/foreman/ui/test_settings.py
tests/foreman/ui/test_subscription.py
tests/foreman/ui/test_user.py
tests/foreman/virtwho/conftest.py
tests/foreman/virtwho/ui/test_esx.py

cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13273
- Remove the Airgun Imports from the Robottelo and Use `target_sat.ui_session` or `module_target_sat.ui`
- UI tests are updated to use the modified "target_sat" or "module_target_sat" for efficient management of multiple browser sessions.
- The streamlined UI tests function correctly and manage browser sessions effectively.
- Remove the nailgun entities from the UI code considering the Airgun Imports (some more PR needs to be added remove this as not wanted to do everything in single PR)

[6.14.z] - Removing the direct Airgun imports from robottelo

---

conf/ui.yaml.template
pytest_plugins/video_cleanup.py
robottelo/hosts.py

* missing ui setting `record_video` breaks tests
* robottelo tests fail in teardwon despite `record_video` is set to false 
* Only call related functionality when `record_video` is set to true
* Add settings options to config template

Cleanup video recording

---

pytest_fixtures/core/ui.py
tests/foreman/cli/test_satellitesync.py
tests/foreman/ui/test_activationkey.py
tests/foreman/ui/test_bookmarks.py
tests/foreman/ui/test_branding.py
tests/foreman/ui/test_contenthost.py
tests/foreman/ui/test_dashboard.py
tests/foreman/ui/test_discoveryrule.py
tests/foreman/ui/test_errata.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_ldap_authentication.py
tests/foreman/ui/test_lifecycleenvironment.py
tests/foreman/ui/test_repository.py
tests/foreman/ui/test_role.py
tests/foreman/ui/test_settings.py
tests/foreman/ui/test_subscription.py
tests/foreman/ui/test_user.py
tests/foreman/virtwho/conftest.py
tests/foreman/virtwho/ui/test_esx.py

- Remove the Airgun Imports from the Robottelo and Use `target_sat.ui_session` or `module_target_sat.ui`
- UI tests are updated to use the modified "target_sat" or "module_target_sat" for efficient management of multiple browser sessions.
- The streamlined UI tests function correctly and manage browser sessions effectively.
- Remove the nailgun entities from the UI code considering the Airgun Imports (some more PR needs to be added remove this as not wanted to do everything in single PR)

[6.13.z] - Removing the direct Airgun imports from robottelo

---

conf/ui.yaml.template
pytest_plugins/video_cleanup.py
robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13713
* missing ui setting `record_video` breaks tests
* robottelo tests fail in teardwon despite `record_video` is set to false 
* Only call related functionality when `record_video` is set to true
* Add settings options to config template

[6.15.z] Cleanup video recording

---

conf/ui.yaml.template
pytest_plugins/video_cleanup.py
robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13713
* missing ui setting `record_video` breaks tests
* robottelo tests fail in teardwon despite `record_video` is set to false 
* Only call related functionality when `record_video` is set to true
* Add settings options to config template

[6.14.z] Cleanup video recording

---

conf/ui.yaml.template
pytest_plugins/video_cleanup.py
robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13713
* missing ui setting `record_video` breaks tests
* robottelo tests fail in teardwon despite `record_video` is set to false 
* Only call related functionality when `record_video` is set to true
* Add settings options to config template

[6.13.z] Cleanup video recording

---

robottelo/utils/virtwho.py
tests/foreman/virtwho/api/test_esx.py
tests/foreman/virtwho/api/test_esx_sca.py
tests/foreman/virtwho/cli/test_esx.py
tests/foreman/virtwho/cli/test_esx_sca.py
tests/foreman/virtwho/ui/test_esx.py

Fix the http proxy create without location can not find in Default Location
Realize http proxy create location option support
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k test_positive_overview_label_name --disable-pytest-warnings -q
1 passed, 33 deselected, 13 warnings in 120.91s (0:02:00)
2024-01-12 06:37:31 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k …
```

http proxy create location option support

---

tests/foreman/destructive/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13544
Missing coverage for BZ 2025760.
Add new test to cover the scenario for changing the puma worker count.

[6.13.z] Add CU scenario for puma worker count

---

robottelo/utils/virtwho.py
tests/foreman/virtwho/api/test_esx.py
tests/foreman/virtwho/api/test_esx_sca.py
tests/foreman/virtwho/cli/test_esx.py
tests/foreman/virtwho/cli/test_esx_sca.py
tests/foreman/virtwho/ui/test_esx.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13768
Fix the http proxy create without location can not find in Default Location
Realize http proxy create location option support
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k test_positive_overview_label_name --disable-pytest-warnings -q
1 passed, 33 deselected, 13 warnings in 120.91s (0:02:00)
2024-01-12 06:37:31 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ …
```

[6.15.z] http proxy create location option support

---

robottelo/utils/virtwho.py
tests/foreman/virtwho/api/test_esx.py
tests/foreman/virtwho/api/test_esx_sca.py
tests/foreman/virtwho/cli/test_esx.py
tests/foreman/virtwho/cli/test_esx_sca.py
tests/foreman/virtwho/ui/test_esx.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13768
Fix the http proxy create without location can not find in Default Location
Realize http proxy create location option support
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k test_positive_overview_label_name --disable-pytest-warnings -q
1 passed, 33 deselected, 13 warnings in 120.91s (0:02:00)
2024-01-12 06:37:31 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ …
```

[6.14.z] http proxy create location option support

---

robottelo/utils/virtwho.py
tests/foreman/virtwho/api/test_esx.py
tests/foreman/virtwho/api/test_esx_sca.py
tests/foreman/virtwho/cli/test_esx.py
tests/foreman/virtwho/cli/test_esx_sca.py
tests/foreman/virtwho/ui/test_esx.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13768
Fix the http proxy create without location can not find in Default Location
Realize http proxy create location option support
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx.py -k test_positive_overview_label_name --disable-pytest-warnings -q
1 passed, 33 deselected, 13 warnings in 120.91s (0:02:00)
2024-01-12 06:37:31 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ …
```

[6.13.z] http proxy create location option support

---

pytest_fixtures/component/provisioning_template.py
pytest_plugins/fixture_markers.py
tests/foreman/api/test_provisioningtemplate.py
tests/foreman/cli/test_bootdisk.py
tests/foreman/destructive/test_infoblox.py

Adding module_sync_kickstart_content to fixture_markers.py and updating all the tests

Add module_sync_kickstart_content to fixture_markers.py

---

tests/foreman/ui/test_discoveryrule.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13754
Going with the API way for provisioning as the host created is a fake discovered host and its provisioning invokes a warning on the UI, as the subnet is randomly generated.

[6.15.z] Adding fix for discoveryrule UI

---

tests/foreman/cli/test_activationkey.py

Adding test to check invalid release versions when updating or creating an activation key using hammer
:BZ: 1895976

[Customer Case]Adding test for invalid release version

---

pytest_plugins/video_cleanup.py

adding logic to remove passed tests video url from junit xml

---

pytest_plugins/video_cleanup.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13784

[6.15.z] adding logic to remove passed tests video url from junit xml

---

pytest_plugins/video_cleanup.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13784

[6.14.z] adding logic to remove passed tests video url from junit xml

---

pytest_plugins/video_cleanup.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13784

[6.13.z] adding logic to remove passed tests video url from junit xml

---

pytest_plugins/video_cleanup.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13784

[6.12.z] adding logic to remove passed tests video url from junit xml

---

pytest_fixtures/component/provisioning_template.py
pytest_plugins/fixture_markers.py
tests/foreman/api/test_provisioningtemplate.py
tests/foreman/cli/test_bootdisk.py
tests/foreman/destructive/test_infoblox.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13772
Adding module_sync_kickstart_content to fixture_markers.py and updating all the tests

[6.15.z] Add module_sync_kickstart_content to fixture_markers.py

---

robottelo/cli/content_export.py
tests/foreman/cli/test_satellitesync.py

Old negative stub for exports with "future datetime" was obsoleted since datetime is not used anymore. Instead the `from-history-id` option can be used, which is not covered either.
This PR adds a test case to export repo using `from-history-id`. It's not positive nor negative as it tests both. Also exercises exports listing.

Add test case for ISS export with history ID

---

tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13595
This PR just adds coverage for ISS export and import in syncable format via CV with mixed content types.

[6.14.z] Add test case for ISS syncable CV export/import

---

tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13595
This PR just adds coverage for ISS export and import in syncable format via CV with mixed content types.

[6.15.z] Add test case for ISS syncable CV export/import

---

robottelo/cli/content_export.py
tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13589
Old negative stub for exports with "future datetime" was obsoleted since datetime is not used anymore. Instead the `from-history-id` option can be used, which is not covered either.
This PR adds a test case to export repo using `from-history-id`. It's not positive nor negative as it tests both. Also exercises exports listing.

[6.14.z] Add test case for ISS export with history ID

---

robottelo/cli/content_export.py
tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13589
Old negative stub for exports with "future datetime" was obsoleted since datetime is not used anymore. Instead the `from-history-id` option can be used, which is not covered either.
This PR adds a test case to export repo using `from-history-id`. It's not positive nor negative as it tests both. Also exercises exports listing.

[6.13.z] Add test case for ISS export with history ID

---

robottelo/cli/hammer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13797
With recent changes in cli factory (I'd say both https://github.com/SatelliteQE/robottelo/pull/13491 and  https://github.com/SatelliteQE/robottelo/pull/13737 have a hand in this) a bunch of rex tests started to fail with  `box.exceptions.BoxValueError: Cannot extrapolate Box from string`
The job invocation hammer command returns something like  `'Message,Id\nJob invocation 12 created,12\n1 task(s), 1 success, 0 fail\n'`  which does not pass the is_csv check here https://github.com/jyejare/robottelo/blob/fcd09d84d933cf9e170291fac8e3c6af81f39870/robottelo/cli/hammer.py#L37 , but even if it did it would fail with the zip error as there are three lines
Checking if the output is coming from the invocation command and …

[6.13.z] cli_factory job_invocation fix

---

robottelo/cli/hammer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13797
With recent changes in cli factory (I'd say both https://github.com/SatelliteQE/robottelo/pull/13491 and  https://github.com/SatelliteQE/robottelo/pull/13737 have a hand in this) a bunch of rex tests started to fail with  `box.exceptions.BoxValueError: Cannot extrapolate Box from string`
The job invocation hammer command returns something like  `'Message,Id\nJob invocation 12 created,12\n1 task(s), 1 success, 0 fail\n'`  which does not pass the is_csv check here https://github.com/jyejare/robottelo/blob/fcd09d84d933cf9e170291fac8e3c6af81f39870/robottelo/cli/hammer.py#L37 , but even if it did it would fail with the zip error as there are three lines
Checking if the output is coming from the invocation command and …

[6.14.z] cli_factory job_invocation fix

---

robottelo/cli/hammer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13797
With recent changes in cli factory (I'd say both https://github.com/SatelliteQE/robottelo/pull/13491 and  https://github.com/SatelliteQE/robottelo/pull/13737 have a hand in this) a bunch of rex tests started to fail with  `box.exceptions.BoxValueError: Cannot extrapolate Box from string`
The job invocation hammer command returns something like  `'Message,Id\nJob invocation 12 created,12\n1 task(s), 1 success, 0 fail\n'`  which does not pass the is_csv check here https://github.com/jyejare/robottelo/blob/fcd09d84d933cf9e170291fac8e3c6af81f39870/robottelo/cli/hammer.py#L37 , but even if it did it would fail with the zip error as there are three lines
Checking if the output is coming from the invocation command and …

[6.12.z] cli_factory job_invocation fix

---

tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13600
This PR just adds negative test case for ISS import of an incomplete export archive, which mocks interrupted data transfer.

[6.14.z] Add test case for ISS incomplete archive import

---

tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13600
This PR just adds negative test case for ISS import of an incomplete export archive, which mocks interrupted data transfer.

[6.13.z] Add test case for ISS incomplete archive import

---

robottelo/cli/simple_content_access.py
tests/foreman/cli/test_subscription.py

6.15 Features automation: SAT-20202
This test is verifying that hammer notifies users that Simple Content Access will be required for all organizations in the next release
copy of https://github.com/SatelliteQE/robottelo/pull/12963

[6.15 RFE] Prepare for sca only hammer 6.15

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13432
Close-loop bz1784254

[6.15.z] bz1784254

---

tests/foreman/cli/test_contentview.py

Simple CC automation scenario testing the hammer version info command's lifecycle-environment-id and lifecycle-environment flags. 
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=2139834

Add test for BZ 2139834

---

tests/foreman/cli/test_contentview.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13699
Simple CC automation scenario testing the hammer version info command's lifecycle-environment-id and lifecycle-environment flags. 
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=2139834

[6.14.z] Add test for BZ 2139834

---

tests/foreman/cli/test_contentview.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13699
Simple CC automation scenario testing the hammer version info command's lifecycle-environment-id and lifecycle-environment flags. 
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=2139834

[6.13.z] Add test for BZ 2139834

---

tests/foreman/cli/test_contentview.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13699
Simple CC automation scenario testing the hammer version info command's lifecycle-environment-id and lifecycle-environment flags. 
BZ Link: https://bugzilla.redhat.com/show_bug.cgi?id=2139834

[6.15.z] Add test for BZ 2139834

---

tests/foreman/destructive/test_capsule_loadbalancer.py

Just adding assertion to check the host's Content Source was set to one of the load balanced capsule and is not empty as addressed in [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2254612).

Check Content Source on LBA host registration

---

tests/foreman/cli/test_reporttemplates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13808
Simple test making sure that the "Days From Now" field in the template has a default set.
Testing BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1943306

[6.15.z] Add test for BZ 1943306

---

tests/foreman/destructive/test_capsule_loadbalancer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13811
Just adding assertion to check the host's Content Source was set to one of the load balanced capsule and is not empty as addressed in [this BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2254612).

[6.15.z] Check Content Source on LBA host registration

---

pytest_plugins/factory_collection.py
pytest_plugins/requirements/update_requirements.py

Random Fixes in pytest plugins

---

pytest_plugins/factory_collection.py
pytest_plugins/requirements/update_requirements.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13820

[6.12.z] Random Fixes in pytest plugins

---

pytest_plugins/factory_collection.py
pytest_plugins/requirements/update_requirements.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13820

[6.15.z] Random Fixes in pytest plugins

---

pytest_plugins/factory_collection.py
pytest_plugins/requirements/update_requirements.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13820

[6.13.z] Random Fixes in pytest plugins

---

pytest_plugins/factory_collection.py
pytest_plugins/requirements/update_requirements.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13820

[6.14.z] Random Fixes in pytest plugins

---

tests/foreman/ui/test_capsulecontent.py

[BZ#2252450](https://bugzilla.redhat.com/show_bug.cgi?id=2252450) blocked us from asserting module streams in UI Capsule Content. Since it has been fixed recently we should be able to check them.
Uncomment the commented assertions.
For PRT to pass we need to rebase on these (or similar) changes: #13738 
Locally it passed.

Release module-streams and container-list assertions

---

tests/foreman/ui/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13746
[BZ#2252450](https://bugzilla.redhat.com/show_bug.cgi?id=2252450) blocked us from asserting module streams in UI Capsule Content. Since it has been fixed recently we should be able to check them.
Uncomment the commented assertions.
For PRT to pass we need to rebase on these (or similar) changes: #13738 
Locally it passed.

[6.15.z] Release module-streams and container-list assertions

---

pytest_fixtures/component/provision_capsule_pxe.py
robottelo/host_helpers/satellite_mixins.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_provisioning.py
tests/foreman/api/test_provisioning_puppet.py
tests/foreman/cli/test_computeresource_libvirt.py
tests/foreman/cli/test_computeresource_rhev.py
tests/foreman/cli/test_computeresource_vmware.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/ui/test_computeresource_libvirt.py
tests/foreman/ui/test_discoveredhost.py

Currently provisioning tests fails due to mentioned BZ where there are no new IPs available to offer
Restarting services after a host is removed from a server seems to work well here, Thanks to @shubhamsg199 to find this workaround. So we're now introducing one new common cleanup method which deletes and restart services for us, and update all on_prem tests to use this new method.
We have tested this with Jenkins jobs on J-MR and the results seem promising!

New provisioning cleanup method to workaround BZ:2207698

---

pytest_fixtures/component/provision_capsule_pxe.py
robottelo/host_helpers/satellite_mixins.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_provisioning.py
tests/foreman/api/test_provisioning_puppet.py
tests/foreman/cli/test_computeresource_libvirt.py
tests/foreman/cli/test_computeresource_rhev.py
tests/foreman/cli/test_computeresource_vmware.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/ui/test_computeresource_libvirt.py
tests/foreman/ui/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13818
Currently provisioning tests fails due to mentioned BZ where there are no new IPs available to offer
Restarting services after a host is removed from a server seems to work well here, Thanks to @shubhamsg199 to find this workaround. So we're now introducing one new common cleanup method which deletes and restart services for us, and update all on_prem tests to use this new method.
We have tested this with Jenkins jobs on J-MR and the results seem promising!

[6.14.z] New provisioning cleanup method to workaround BZ:2207698

---

pytest_fixtures/component/provision_capsule_pxe.py
robottelo/host_helpers/satellite_mixins.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_provisioning.py
tests/foreman/api/test_provisioning_puppet.py
tests/foreman/cli/test_computeresource_libvirt.py
tests/foreman/cli/test_computeresource_rhev.py
tests/foreman/cli/test_computeresource_vmware.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/ui/test_computeresource_libvirt.py
tests/foreman/ui/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13818
Currently provisioning tests fails due to mentioned BZ where there are no new IPs available to offer
Restarting services after a host is removed from a server seems to work well here, Thanks to @shubhamsg199 to find this workaround. So we're now introducing one new common cleanup method which deletes and restart services for us, and update all on_prem tests to use this new method.
We have tested this with Jenkins jobs on J-MR and the results seem promising!

[6.15.z] New provisioning cleanup method to workaround BZ:2207698

---

robottelo/host_helpers/satellite_mixins.py

Currently, there are many intermittent test failures like below where we use `module_sca_manifest_org` are seen in automation runs, where we don't have content property set in manifester object.
```
robottelo/host_helpers/satellite_mixins.py:149: in upload_manifest
if manifest.content is None:
E   AttributeError: 'NoneType' object has no attribute 'content'
```
Update upload_manifest to handle case where manifest.content is not set, or when manifest.content is None
**Local test results:** 
```
In [3]: manifest = Manifester(manifest_category=settings.manifest.golden_ticket)
In [4]: manifest.content …
```

Fix upload_manifest to handle case where manifest.content is not set

---

robottelo/host_helpers/satellite_mixins.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13819
Currently, there are many intermittent test failures like below where we use `module_sca_manifest_org` are seen in automation runs, where we don't have content property set in manifester object.
```
robottelo/host_helpers/satellite_mixins.py:149: in upload_manifest
if manifest.content is None:
E   AttributeError: 'NoneType' object has no attribute 'content'
```
Update upload_manifest to handle case where manifest.content is not set, or when manifest.content is None
**Local test results:** 
```
In [3]: manifest = Manifester(manifest_category=settings.manifest.golden_ticket) …
```

[6.14.z] Fix upload_manifest to handle case where manifest.content is not set

---

robottelo/host_helpers/satellite_mixins.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13819
Currently, there are many intermittent test failures like below where we use `module_sca_manifest_org` are seen in automation runs, where we don't have content property set in manifester object.
```
robottelo/host_helpers/satellite_mixins.py:149: in upload_manifest
if manifest.content is None:
E   AttributeError: 'NoneType' object has no attribute 'content'
```
Update upload_manifest to handle case where manifest.content is not set, or when manifest.content is None
**Local test results:** 
```
In [3]: manifest = Manifester(manifest_category=settings.manifest.golden_ticket) …
```

[6.13.z] Fix upload_manifest to handle case where manifest.content is not set

---

robottelo/host_helpers/satellite_mixins.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13819
Currently, there are many intermittent test failures like below where we use `module_sca_manifest_org` are seen in automation runs, where we don't have content property set in manifester object.
```
robottelo/host_helpers/satellite_mixins.py:149: in upload_manifest
if manifest.content is None:
E   AttributeError: 'NoneType' object has no attribute 'content'
```
Update upload_manifest to handle case where manifest.content is not set, or when manifest.content is None
**Local test results:** 
```
In [3]: manifest = Manifester(manifest_category=settings.manifest.golden_ticket) …
```

[6.15.z] Fix upload_manifest to handle case where manifest.content is not set

---

tests/foreman/cli/test_satellitesync.py

This PR just adds coverage for [BZ#2173756](https://bugzilla.redhat.com/show_bug.cgi?id=2173756) - export/import RH yum repo incrementally (via CV) and consume it on a content host.

Add coverage for BZ#2173756

---

tests/foreman/api/test_provisioningtemplate.py

Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/13160
Recent 6.14.z introduced change in vlan interface notation in https://github.com/theforeman/foreman/pull/9700

[6.14.z] Update vlan paramater template test for BZ:2075358

---

tests/foreman/cli/test_satellitesync.py

Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/13202
Closes https://github.com/SatelliteQE/robottelo/issues/13837

[6.14.z] Add coverage for BZ#2173756

---

tests/foreman/longrun/test_oscap.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13841
https://github.com/SatelliteQE/robottelo/pull/11544 altered  `fetch_scap_and_profile_id` to use satellite, but the function defines it as the last parameter, while callers use it as the first one, hence `AttributeError: 'str' object has no attribute 'cli'`
changing the order of parameters

[6.15.z] oscap helper function fix

---

tests/foreman/longrun/test_oscap.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13841
https://github.com/SatelliteQE/robottelo/pull/11544 altered  `fetch_scap_and_profile_id` to use satellite, but the function defines it as the last parameter, while callers use it as the first one, hence `AttributeError: 'str' object has no attribute 'cli'`
changing the order of parameters

[6.13.z] oscap helper function fix

---

tests/foreman/longrun/test_oscap.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13841
https://github.com/SatelliteQE/robottelo/pull/11544 altered  `fetch_scap_and_profile_id` to use satellite, but the function defines it as the last parameter, while callers use it as the first one, hence `AttributeError: 'str' object has no attribute 'cli'`
changing the order of parameters

[6.14.z] oscap helper function fix

---

.github/workflows/auto_cherry_pick_merge.yaml
.github/workflows/dependency_merge.yml

Our GHA automation failed to backport some of the patches. They were not backported till today.
Backport missing patches - this PR.
* https://github.com/SatelliteQE/robottelo/issues/13726

[6.15.z] Sync project dependencies

---

.github/workflows/auto_assignment.yaml
.github/workflows/auto_cherry_pick_merge.yaml
.github/workflows/dependency_merge.yml
.github/workflows/pull_request.yml
.github/workflows/weekly.yml
requirements.txt

Our GHA automation failed to backport some of the patches. They were not backported till today.
Backport missing patches - this PR.
* https://github.com/SatelliteQE/robottelo/issues/13304
* https://github.com/SatelliteQE/robottelo/issues/13553
* https://github.com/SatelliteQE/robottelo/issues/13579
* https://github.com/SatelliteQE/robottelo/issues/13704
* https://github.com/SatelliteQE/robottelo/issues/13725

[6.13.z] Sync project dependencies

---

.github/workflows/auto_cherry_pick_merge.yaml
.github/workflows/dependency_merge.yml
.github/workflows/pull_request.yml
.github/workflows/weekly.yml
requirements.txt

Our GHA automation failed to backport some of the patches. They were not backported till today.
Backport missing patches - this PR.
* https://github.com/SatelliteQE/robottelo/issues/13306
* https://github.com/SatelliteQE/robottelo/issues/13549
*  #13581
* https://github.com/SatelliteQE/robottelo/issues/13727

[6.12.z] Sync project dependencies

---

tests/foreman/cli/test_oscap.py

some tests were relying on the default factory title for the newly created scap contents, which caused a bunch of 'name already taken' failures for parametrized tests
just create the title within the test body

cli oscap fix name already taken

---

tests/foreman/cli/test_oscap.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13856
some tests were relying on the default factory title for the newly created scap contents, which caused a bunch of 'name already taken' failures for parametrized tests
just create the title within the test body

[6.14.z] cli oscap fix name already taken

---

tests/foreman/cli/test_oscap.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13856
some tests were relying on the default factory title for the newly created scap contents, which caused a bunch of 'name already taken' failures for parametrized tests
just create the title within the test body

[6.15.z] cli oscap fix name already taken

---

tests/foreman/api/test_role.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13849
https://github.com/SatelliteQE/robottelo/pull/12989 updated the create_domain and create_simple_user helpers to use target_sat but didn't update all the callers accordingly 
this pr

[6.15.z] fixes in api role helper functions

---

tests/foreman/api/test_role.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13849
https://github.com/SatelliteQE/robottelo/pull/12989 updated the create_domain and create_simple_user helpers to use target_sat but didn't update all the callers accordingly 
this pr

[6.14.z] fixes in api role helper functions

---

tests/foreman/api/test_permission.py

https://github.com/SatelliteQE/robottelo/pull/12989 swapped `entities` for `target_sat.api` but:
```
(Pdb) entities.ActivationKey
<class 'nailgun.entities.ActivationKey'>
(Pdb) target_sat.api.ActivationKey
<class 'robottelo.hosts.Satellite.api.<locals>.inject_config.<locals>.DecClass'>
```
which breaks the if condition in this test
Swapping back to entities, as it is still heavily used in that module. Deferring further changes to component evaluation

fix in test_permission

---

tests/foreman/api/test_permission.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13871
https://github.com/SatelliteQE/robottelo/pull/12989 swapped `entities` for `target_sat.api` but:
```
(Pdb) entities.ActivationKey
<class 'nailgun.entities.ActivationKey'>
(Pdb) target_sat.api.ActivationKey
<class 'robottelo.hosts.Satellite.api.<locals>.inject_config.<locals>.DecClass'>
```
which breaks the if condition in this test
Swapping back to entities, as it is still heavily used in that module. Deferring further changes to component evaluation

[6.15.z] fix in test_permission

---

.github/workflows/auto_cherry_pick.yml

There have been occurrences where the PR issue was created for passed cherrypicks as well. There has to be a check before creating an issue. The discussion and further details point to these comments  https://github.com/SatelliteQE/robottelo/pull/13831#issuecomment-1900151508  
An additional check is added to this PR, it will try to check if the PR exists with that branch name, if yes then it will not raise any concerns or create issues.    
https://github.com/SatelliteQE/robottelo/pull/13831#issuecomment-1900151508

additional check before create issue for failed cherrypick

---

.github/workflows/auto_cherry_pick.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13858
There have been occurrences where the PR issue was created for passed cherrypicks as well. There has to be a check before creating an issue. The discussion and further details point to these comments  https://github.com/SatelliteQE/robottelo/pull/13831#issuecomment-1900151508  
An additional check is added to this PR, it will try to check if the PR exists with that branch name, if yes then it will not raise any concerns or create issues.    
https://github.com/SatelliteQE/robottelo/pull/13831#issuecomment-1900151508

[6.15.z] additional check before create issue for failed cherrypick

---

tests/foreman/longrun/test_oscap.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13841
https://github.com/SatelliteQE/robottelo/pull/11544 altered  `fetch_scap_and_profile_id` to use satellite, but the function defines it as the last parameter, while callers use it as the first one, hence `AttributeError: 'str' object has no attribute 'cli'`
changing the order of parameters

[6.12.z] oscap helper function fix

---

robottelo/host_helpers/capsule_mixins.py
tests/upgrades/test_capsule.py

Fix waiting for upgrade capsule sync

---

robottelo/host_helpers/capsule_mixins.py
tests/upgrades/test_capsule.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13870

[6.13.z] Fix waiting for upgrade capsule sync

---

robottelo/host_helpers/capsule_mixins.py
tests/upgrades/test_capsule.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13870

[6.12.z] Fix waiting for upgrade capsule sync

---

robottelo/host_helpers/capsule_mixins.py
tests/upgrades/test_capsule.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13870

[6.15.z] Fix waiting for upgrade capsule sync

---

robottelo/host_helpers/capsule_mixins.py
tests/upgrades/test_capsule.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13870

[6.14.z] Fix waiting for upgrade capsule sync

---

tests/foreman/destructive/test_katello_certs_check.py

Katello-certs-check tests fail when checking for 8 services reporting 'ok' status.
Change to 9 services since we now report the default redis cache in hammer ping.

Update ping call for certs check

---

tests/foreman/destructive/test_installer.py

Added new testcase to cover BZ 2221621 (and it's clone BZ 2238363)
BZ reported in Sat 6.13. Attempting to run installer with invalid certificates on existing installation causes breakage of current setup - hammer ping reports failures. After fix the installer returns error and leaves current setup (hammer ping reports OK statuses)

Adding coverage for BZ2221621

---

tests/foreman/cli/test_organization.py

Default location can be assigned to the organization, causing test flakiness
Adjusting assertions to this possibility

cli org test fix

---

tests/foreman/cli/test_organization.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13887
Default location can be assigned to the organization, causing test flakiness
Adjusting assertions to this possibility

[6.14.z] cli org test fix

---

tests/foreman/cli/test_organization.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13887
Default location can be assigned to the organization, causing test flakiness
Adjusting assertions to this possibility

[6.15.z] cli org test fix

---

tests/foreman/destructive/test_katello_certs_check.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13880
Katello-certs-check tests fail when checking for 8 services reporting 'ok' status.
Change to 9 services since we now report the default redis cache in hammer ping.

[6.15.z] Update ping call for certs check

---

tests/foreman/destructive/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13694
Added new testcase to cover BZ 2221621 (and it's clone BZ 2238363)
BZ reported in Sat 6.13. Attempting to run installer with invalid certificates on existing installation causes breakage of current setup - hammer ping reports failures. After fix the installer returns error and leaves current setup (hammer ping reports OK statuses)

[6.15.z] Adding coverage for BZ2221621

---

.github/workflows/auto_cherry_pick.yml

after running https://github.com/SatelliteQE/robottelo/pull/13858 with production to realised that the matrix branch is not a direct branch we need the sha with the branch name.
This will fix the whole thing with the correct branching name. Tested Here https://github.com/omkarkhatavkar/robottelo/actions/runs/7629781738/job/20783989147.

adding the missing sha with branch name in gha

---

tests/foreman/ui/test_errata.py

- to standards for 6.15.0 for setup w/ global registration, and new host UI views
- depends on [airgun#1152](https://github.com/SatelliteQE/airgun/pull/1152)
- use of registered host fixture, setup w/ global registration, subscribed to content.
- method to publish and promote cv, wait for any task(s).
- migrate Airgun UI view; from `legacy contenthost UI > errata page` ,
to `new host UI > content > errata tab` .
- Sometimes, `applicable_errata_count` for the host has already updated after some install, but pagination on the table remains the same as before. I used `wait_for` to give the `new host>content>errata tab` time to reload with updated entries /total_items/total_pages etc. Timeout set for 30s on the tab loading new table and pagination, in case satellite is slow.
- …

[comp-eval] UI>content>errata tab, Pagination testing

---

pytest_fixtures/component/taxonomy.py
tests/foreman/ui/test_rhc.py

- test_positive_configure_cloud_connector currently uses entitlement mode manifest.
- Create module_extra_rhel_sca_manifest to create sca mode manifest.

Use sca enabled manifest for test_positive_configure_cloud_connector

---

pytest_fixtures/component/taxonomy.py
tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13908
- test_positive_configure_cloud_connector currently uses entitlement mode manifest.
- Create module_extra_rhel_sca_manifest to create sca mode manifest.

[6.13.z] Use sca enabled manifest for test_positive_configure_cloud_connector

---

pytest_fixtures/component/taxonomy.py
tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13908
- test_positive_configure_cloud_connector currently uses entitlement mode manifest.
- Create module_extra_rhel_sca_manifest to create sca mode manifest.

[6.15.z] Use sca enabled manifest for test_positive_configure_cloud_connector

---

pytest_fixtures/component/taxonomy.py
tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13908
- test_positive_configure_cloud_connector currently uses entitlement mode manifest.
- Create module_extra_rhel_sca_manifest to create sca mode manifest.

[6.14.z] Use sca enabled manifest for test_positive_configure_cloud_connector

---

tests/foreman/cli/test_capsulecontent.py

BZ#2251019 blocked us from testing ansible collection content counts via CLI.
The BZ has been resolved so we can test it now.

Release AC and docker content counts testing

---

tests/foreman/cli/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13903
BZ#2251019 blocked us from testing ansible collection content counts via CLI.
The BZ has been resolved so we can test it now.

[6.15.z] Release AC and docker content counts testing

---

tests/foreman/ui/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13767
- to standards for 6.15.0 for setup w/ global registration, and new host UI views
- depends on [airgun#1152](https://github.com/SatelliteQE/airgun/pull/1152)
- use of registered host fixture, setup w/ global registration, subscribed to content.
- method to publish and promote cv, wait for any task(s).
- migrate Airgun UI view; from `legacy contenthost UI > errata page` ,
to `new host UI > content > errata tab` .
- Sometimes, `applicable_errata_count` for the host has already updated after some install, but pagination on the table remains the same as before. I used `wait_for` to give the `new host>content>errata tab` time to reload with updated entries /total_items/total_pages etc. Timeout set for 30s on the tab loading …

[6.15.z] [comp-eval] UI>content>errata tab, Pagination testing

---

pytest_fixtures/component/activationkey.py
robottelo/cli/hammer.py
tests/foreman/cli/test_host.py

Make this run on real, non-fake hosts so that we can test whether the content source is REALLY used, not just set.

CE - test CS being used

---

tests/foreman/cli/test_classparameters.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13902
test_positive_test_hidden_parameter_value is failing due to no teardown present for the host in test_positive_list
Add teardown for the host deletion

[6.14.z] Add host teardown for smart classparameters test

---

tests/foreman/cli/test_classparameters.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13902
test_positive_test_hidden_parameter_value is failing due to no teardown present for the host in test_positive_list
Add teardown for the host deletion

[6.13.z] Add host teardown for smart classparameters test

---

tests/foreman/cli/test_classparameters.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13902
test_positive_test_hidden_parameter_value is failing due to no teardown present for the host in test_positive_list
Add teardown for the host deletion

[6.15.z] Add host teardown for smart classparameters test

---

tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13924
- `test_positive_configure_cloud_connector` currently uses `module_extra_rhel_sca_manifest` which deletes the manifest after test execution causing the dependent Iqe tests to fail later in pipeline execution.
- don't use context manager.

[6.13.z] Update test_positive_configure_cloud_connector

---

tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13924
- `test_positive_configure_cloud_connector` currently uses `module_extra_rhel_sca_manifest` which deletes the manifest after test execution causing the dependent Iqe tests to fail later in pipeline execution.
- don't use context manager.

[6.15.z] Update test_positive_configure_cloud_connector

---

tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13924
- `test_positive_configure_cloud_connector` currently uses `module_extra_rhel_sca_manifest` which deletes the manifest after test execution causing the dependent Iqe tests to fail later in pipeline execution.
- don't use context manager.

[6.14.z] Update test_positive_configure_cloud_connector

---

tests/foreman/api/test_remoteexecution.py
tests/foreman/cli/test_remoteexecution.py

With global proxy setting on, it is possible that if the mqtt capsule is not reached, the default one is used instead. In such case we wouldn't find out there is a problem. 
This PR forces the registered through capsule for the tests using external capsule

ensure mqtt capsule is not bypassed

---

tests/foreman/api/test_remoteexecution.py
tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13817
With global proxy setting on, it is possible that if the mqtt capsule is not reached, the default one is used instead. In such case we wouldn't find out there is a problem. 
This PR forces the registered through capsule for the tests using external capsule

[6.15.z] ensure mqtt capsule is not bypassed

---

tests/foreman/ui/test_host.py

typo, probably from https://github.com/SatelliteQE/robottelo/pull/13273 
fixed

ui_seesion > ui_session

---

tests/foreman/ui/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13929
typo, probably from https://github.com/SatelliteQE/robottelo/pull/13273 
fixed

[6.14.z] ui_seesion > ui_session

---

tests/foreman/api/test_capsulecontent.py

- test_positive_insights_puppet_package_availability is no longer required as the old insights plugin was removed from Satellite a few versions back.
- Remove the test.
- https://issues.redhat.com/browse/SAT-22936 
- https://issues.redhat.com/browse/SAT-22935

Remove test_positive_insights_puppet_package_availability test

---

tests/foreman/api/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13936
- test_positive_insights_puppet_package_availability is no longer required as the old insights plugin was removed from Satellite a few versions back.
- Remove the test.
- https://issues.redhat.com/browse/SAT-22936 
- https://issues.redhat.com/browse/SAT-22935

[6.14.z] Remove test_positive_insights_puppet_package_availability test

---

tests/foreman/api/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13936
- test_positive_insights_puppet_package_availability is no longer required as the old insights plugin was removed from Satellite a few versions back.
- Remove the test.
- https://issues.redhat.com/browse/SAT-22936 
- https://issues.redhat.com/browse/SAT-22935

[6.13.z] Remove test_positive_insights_puppet_package_availability test

---

tests/foreman/api/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13936
- test_positive_insights_puppet_package_availability is no longer required as the old insights plugin was removed from Satellite a few versions back.
- Remove the test.
- https://issues.redhat.com/browse/SAT-22936 
- https://issues.redhat.com/browse/SAT-22935

[6.15.z] Remove test_positive_insights_puppet_package_availability test

---

tests/foreman/cli/test_registration.py

Component evaluation, CE-SAT-21616, suggests close-looping BZ1361309.
This PR. Create a new test, the original suggestion was for an unrelated test.
pytest: tests/foreman/cli/test_registration.py::test_positive_force_register_twice

CE-SAT-21616 and close-loop BZ1361309

---

pytest_fixtures/core/ui.py
tests/foreman/ui/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13554
https://bugzilla.redhat.com/show_bug.cgi?id=2220965
We need to change the UI test sesison fixture to be able to run with non-admin user.

[6.14.z] bz2220965

---

pytest_fixtures/core/ui.py
tests/foreman/ui/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13554
https://bugzilla.redhat.com/show_bug.cgi?id=2220965
We need to change the UI test sesison fixture to be able to run with non-admin user.

[6.15.z] bz2220965

---

tests/foreman/cli/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13807
Component evaluation, CE-SAT-21616, suggests close-looping BZ1361309.
This PR. Create a new test, the original suggestion was for an unrelated test.
pytest: tests/foreman/cli/test_registration.py::test_positive_force_register_twice

[6.15.z] CE-SAT-21616 and close-loop BZ1361309

---

tests/foreman/api/test_repository.py

2 tests from `foreman/api/test_repository.py` were failing due to TyepError
Test cases name: `test_positive_cancel_docker_repo_sync` and `test_positive_bulk_cancel_sync`
> TypeError: ForemanTask.poll() got an unexpected keyword argument 'canceled'
`Poll()` from `ForemaTask` of nailgun entities return status of task and the argument `must_succeed` would raised error if tasks finishes with other than success result, as we are cancelling sync so `poll` would raise error so passing `False` will resolve this error.
No

small fix related to repo sync bulk canceled scenario

---

tests/foreman/api/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13951
2 tests from `foreman/api/test_repository.py` were failing due to TyepError
Test cases name: `test_positive_cancel_docker_repo_sync` and `test_positive_bulk_cancel_sync`
> TypeError: ForemanTask.poll() got an unexpected keyword argument 'canceled'
`Poll()` from `ForemaTask` of nailgun entities return status of task and the argument `must_succeed` would raised error if tasks finishes with other than success result, as we are cancelling sync so `poll` would raise error so passing `False` will resolve this error.
No

[6.15.z] small fix related to repo sync bulk canceled scenario

---

tests/foreman/api/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13951
2 tests from `foreman/api/test_repository.py` were failing due to TyepError
Test cases name: `test_positive_cancel_docker_repo_sync` and `test_positive_bulk_cancel_sync`
> TypeError: ForemanTask.poll() got an unexpected keyword argument 'canceled'
`Poll()` from `ForemaTask` of nailgun entities return status of task and the argument `must_succeed` would raised error if tasks finishes with other than success result, as we are cancelling sync so `poll` would raise error so passing `False` will resolve this error.
No

[6.13.z] small fix related to repo sync bulk canceled scenario

---

tests/foreman/cli/test_repository.py

1. Test `TestAnsibleCollectionRepository::test_positive_sync_ansible_collection_from_satellite[ansible_galaxy]` was failing due to wrong option passed to hammer command.
Applicable only for `6.14.z`, `6.15.z` and `stream`
>Error: Unrecognised option '--ansible-collection-reqirements'.
2. Also in **6.14.2** test run build no 33 of **Phoenix-content > foreman/cli/test/** detected one regression for test module / test case `test_repository.py::TestAnsibleCollectionRepository::test_positive_sync_ansible_collection[ansible_hub]` and error was related to repository synchronize. When tested locally test passed, wanted to make sure this test passes or not in CI so I would run separate PRT comment for that.
> trigger: test-robottelo
> pytest: …

small correction in hammer repository create command

---

tests/foreman/cli/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13956
1. Test `TestAnsibleCollectionRepository::test_positive_sync_ansible_collection_from_satellite[ansible_galaxy]` was failing due to wrong option passed to hammer command.
Applicable only for `6.14.z`, `6.15.z` and `stream`
>Error: Unrecognised option '--ansible-collection-reqirements'.
2. Also in **6.14.2** test run build no 33 of **Phoenix-content > foreman/cli/test/** detected one regression for test module / test case `test_repository.py::TestAnsibleCollectionRepository::test_positive_sync_ansible_collection[ansible_hub]` and error was related to repository synchronize. When tested locally test passed, wanted to make sure this test passes or not in CI so I would run separate PRT comment for that.
> trigger: …

[6.15.z] small correction in hammer repository create command

---

tests/foreman/cli/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13956
1. Test `TestAnsibleCollectionRepository::test_positive_sync_ansible_collection_from_satellite[ansible_galaxy]` was failing due to wrong option passed to hammer command.
Applicable only for `6.14.z`, `6.15.z` and `stream`
>Error: Unrecognised option '--ansible-collection-reqirements'.
2. Also in **6.14.2** test run build no 33 of **Phoenix-content > foreman/cli/test/** detected one regression for test module / test case `test_repository.py::TestAnsibleCollectionRepository::test_positive_sync_ansible_collection[ansible_hub]` and error was related to repository synchronize. When tested locally test passed, wanted to make sure this test passes or not in CI so I would run separate PRT comment for that.
> trigger: …

[6.13.z] small correction in hammer repository create command

---

tests/foreman/cli/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13956
1. Test `TestAnsibleCollectionRepository::test_positive_sync_ansible_collection_from_satellite[ansible_galaxy]` was failing due to wrong option passed to hammer command.
Applicable only for `6.14.z`, `6.15.z` and `stream`
>Error: Unrecognised option '--ansible-collection-reqirements'.
2. Also in **6.14.2** test run build no 33 of **Phoenix-content > foreman/cli/test/** detected one regression for test module / test case `test_repository.py::TestAnsibleCollectionRepository::test_positive_sync_ansible_collection[ansible_hub]` and error was related to repository synchronize. When tested locally test passed, wanted to make sure this test passes or not in CI so I would run separate PRT comment for that.
> trigger: …

[6.14.z] small correction in hammer repository create command

---

tests/foreman/api/test_notifications.py

Notifications: fix for long funning tasks
For some reason, rake command in form `<ENV_VAR> foreman-rake ...`
started to ignore the ENV_VAR and the fix is to pass the ENV_VAR *after* the command,
i.e. - `foreman-rake ... <ENV_VAR>`.

Notifications: fix for long funning tasks

---

tests/foreman/api/test_notifications.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13955
Notifications: fix for long funning tasks
For some reason, rake command in form `<ENV_VAR> foreman-rake ...`
started to ignore the ENV_VAR and the fix is to pass the ENV_VAR *after* the command,
i.e. - `foreman-rake ... <ENV_VAR>`.

[6.15.z] Notifications: fix for long funning tasks

---

tests/foreman/api/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13951
2 tests from `foreman/api/test_repository.py` were failing due to TyepError
Test cases name: `test_positive_cancel_docker_repo_sync` and `test_positive_bulk_cancel_sync`
> TypeError: ForemanTask.poll() got an unexpected keyword argument 'canceled'
`Poll()` from `ForemaTask` of nailgun entities return status of task and the argument `must_succeed` would raised error if tasks finishes with other than success result, as we are cancelling sync so `poll` would raise error so passing `False` will resolve this error.
No

[6.14.z] small fix related to repo sync bulk canceled scenario

---

pytest_fixtures/core/ui.py

https://github.com/SatelliteQE/robottelo/pull/13554 breaks every unparametrized session fixture with `AttributeError: 'SubRequest' object has no attribute 'param'`
request.param is not expected at all times

fix in ui_host fixture

---

pytest_fixtures/core/ui.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13962
https://github.com/SatelliteQE/robottelo/pull/13554 breaks every unparametrized session fixture with `AttributeError: 'SubRequest' object has no attribute 'param'`
request.param is not expected at all times

[6.14.z] fix in ui_host fixture

---

pytest_fixtures/core/ui.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13962
https://github.com/SatelliteQE/robottelo/pull/13554 breaks every unparametrized session fixture with `AttributeError: 'SubRequest' object has no attribute 'param'`
request.param is not expected at all times

[6.15.z] fix in ui_host fixture

---

tests/foreman/cli/test_repository.py
tests/foreman/cli/test_satellitesync.py

Source RPMs label returned by `hammer repository info` has changed from `source-rpms` to `SRPMs` in 6.15.0 snap 8.0
```
[root@jwst ~]# hammer repository info --id 1474
Id:                 1474
Name:               Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.9
...
Content Counts:     
Packages:       5230
SRPMs:          0   <---- this used to be called 'source-rpms'
Module Streams: 0
Package Groups: 76
Errata:         0
```
making several ISS and Repository tests to fail like this
```
tests/foreman/cli/test_repository.py:1246: in test_positive_synchronize_rpm_repo_ignore_SRPM
assert repo['content-counts']['source-rpms'] == '0', 'content not ignored correctly'
E   KeyError: 'source-rpms'
```
Since the change doesn't feel like product issue I tend to fix it on the test side.
Also …

Fix SRPMs label in hammer repository info

---

tests/foreman/cli/test_repository.py
tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13971
Source RPMs label returned by `hammer repository info` has changed from `source-rpms` to `SRPMs` in 6.15.0 snap 8.0
```
[root@jwst ~]# hammer repository info --id 1474
Id:                 1474
Name:               Red Hat Enterprise Linux 7 Server Kickstart x86_64 7.9
...
Content Counts:     
Packages:       5230
SRPMs:          0   <---- this used to be called 'source-rpms'
Module Streams: 0
Package Groups: 76
Errata:         0
```
making several ISS and Repository tests to fail like this
```
tests/foreman/cli/test_repository.py:1246: in test_positive_synchronize_rpm_repo_ignore_SRPM
assert repo['content-counts']['source-rpms'] == '0', 'content not ignored correctly'
E   KeyError: 'source-rpms'
```
Since the change …

[6.15.z] Fix SRPMs label in hammer repository info

---

tests/foreman/cli/test_reporttemplates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13973
Both of these tests are failing due to an unrecognised option --content. 
```Could not create the report template:
Error: Unrecognised option '--content'.
```
Replace 'content' with 'file'
Looks like it was related to these two PRs
https://github.com/SatelliteQE/robottelo/pull/8441
https://github.com/SatelliteQE/robottelo/pull/9324

[6.15.z] [TestFix] Replacing 'content' with 'file' option in reporttemplate create

---

tests/foreman/cli/test_reporttemplates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13973
Both of these tests are failing due to an unrecognised option --content. 
```Could not create the report template:
Error: Unrecognised option '--content'.
```
Replace 'content' with 'file'
Looks like it was related to these two PRs
https://github.com/SatelliteQE/robottelo/pull/8441
https://github.com/SatelliteQE/robottelo/pull/9324

[6.14.z] [TestFix] Replacing 'content' with 'file' option in reporttemplate create

---

tests/foreman/virtwho/conftest.py

UI cases failed for the error
```  @pytest.fixture
def virtwho_config_ui(form_data_ui, target_sat, org_session):
name = gen_string('alpha')
form_data_ui['name'] = name
with org_session:
>           org_session.virtwho_configure.create(form_data_ui)
E           AttributeError: '_GeneratorContextManager' object has no attribute 'virtwho_configure'
pytest_fixtures/component/virtwho_config.py:262: AttributeError
_ ERROR at setup of TestVirtwhoConfigforLibvirt.test_positive_hypervisor_id_option _
```
Cases  : PASS
```
(robottelo_vv_615) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest  ./tests/foreman/virtwho/ui/test_hyperv.py --disable-pytest-warnings -q
... …
```

Fix virtwho UI cases failed for _GeneratorContextManager object has no attribute virtwho_configure

---

tests/foreman/ui/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13980
It seems I have broken one UI test in #13068 by [this change](https://github.com/SatelliteQE/robottelo/pull/13068/files#diff-9a55ae74469aa91ad5efb2b9068f73174467cd0c00d45abf7d35f9f2277a7632R225) since CLI/API use it with `_` but UI does not.
Just replace the `_` in test. I think that defining new "UI only" constant would be even uglier.
Closing #13921

[6.15.z] Fix UI AC repo test

---

tests/foreman/virtwho/conftest.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13981
UI cases failed for the error
```  @pytest.fixture
def virtwho_config_ui(form_data_ui, target_sat, org_session):
name = gen_string('alpha')
form_data_ui['name'] = name
with org_session:
>           org_session.virtwho_configure.create(form_data_ui)
E           AttributeError: '_GeneratorContextManager' object has no attribute 'virtwho_configure'
pytest_fixtures/component/virtwho_config.py:262: AttributeError
_ ERROR at setup of TestVirtwhoConfigforLibvirt.test_positive_hypervisor_id_option _
```
Cases  : PASS
```
(robottelo_vv_615) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest  ./tests/foreman/virtwho/ui/test_hyperv.py --disable-pytest-warnings -q
... …
```

[6.15.z] Fix virtwho UI cases failed for _GeneratorContextManager object has no attribute virtwho_configure

---

tests/foreman/virtwho/conftest.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13981
UI cases failed for the error
```  @pytest.fixture
def virtwho_config_ui(form_data_ui, target_sat, org_session):
name = gen_string('alpha')
form_data_ui['name'] = name
with org_session:
>           org_session.virtwho_configure.create(form_data_ui)
E           AttributeError: '_GeneratorContextManager' object has no attribute 'virtwho_configure'
pytest_fixtures/component/virtwho_config.py:262: AttributeError
_ ERROR at setup of TestVirtwhoConfigforLibvirt.test_positive_hypervisor_id_option _
```
Cases  : PASS
```
(robottelo_vv_615) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest  ./tests/foreman/virtwho/ui/test_hyperv.py --disable-pytest-warnings -q
... …
```

[6.14.z] Fix virtwho UI cases failed for _GeneratorContextManager object has no attribute virtwho_configure

---

tests/foreman/installer/test_installer.py

This test is failing on stream because hammer ping now has a couple new lines that are nested for the cache
Simplify the assertion so it's much easier.

Fix and update installer ping test

---

tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13614
This test is failing on stream because hammer ping now has a couple new lines that are nested for the cache
Simplify the assertion so it's much easier.

[6.15.z] Fix and update installer ping test

---

tests/foreman/longrun/test_oscap.py

just marking the bz for traceability

added bz tag to oscap longrun test

---

pytest_fixtures/component/activationkey.py
tests/foreman/api/test_registration.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_registration.py

Registration tests are failing with manifest conflict.
Fixed manifest conflict

Fix registration test cases

---

tests/foreman/longrun/test_oscap.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13982
just marking the bz for traceability

[6.15.z] added bz tag to oscap longrun test

---

robottelo/host_helpers/cli_factory.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13987
make_job_invocation_with_credentials got dropped without replacement causing test failures

[6.15.z] job invocation with credentials added

---

tests/foreman/ui/test_repositories.py

Adding customer case automation for overriding repos without using the select all method

[Customer Case] Adding test for overriding repos no select all

---

tests/foreman/ui/test_architecture.py
tests/foreman/ui/test_audit.py
tests/foreman/ui/test_computeprofiles.py
tests/foreman/ui/test_computeresource.py
tests/foreman/ui/test_computeresource_ec2.py
tests/foreman/ui/test_computeresource_vmware.py
tests/foreman/ui/test_containerimagetag.py
tests/foreman/ui/test_domain.py
tests/foreman/ui/test_hardwaremodel.py
tests/foreman/ui/test_hostgroup.py
tests/foreman/ui/test_location.py
tests/foreman/ui/test_modulestreams.py
tests/foreman/ui/test_organization.py
tests/foreman/ui/test_oscappolicy.py
tests/foreman/ui/test_oscaptailoringfile.py
tests/foreman/ui/test_package.py
tests/foreman/ui/test_product.py
tests/foreman/ui/test_reporttemplates.py
tests/foreman/ui/test_sync.py
tests/foreman/ui/test_syncplan.py
tests/foreman/ui/test_templatesync.py
tests/foreman/ui/test_usergroup.py

We are using the direct imports from the nailgun rather than directly using from target_sat 
Direct Imports Removed: We've cleaned up our codebase by eliminating direct imports from the Nailgun package.
Using target_sat, module_target_sat, class_target_sat: Modified the API calls and using the target_sat.api. pattern for all API calls.

remove the all nailgun imports from UI folder

---

robottelo/host_helpers/cli_factory.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13987
make_job_invocation_with_credentials got dropped without replacement causing test failures

[6.14.z] job invocation with credentials added

---

conf/vmware.yaml.template
pytest_fixtures/component/provision_vmware.py
tests/foreman/cli/test_computeresource_vmware.py
tests/foreman/ui/test_computeresource_vmware.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13877
Adding support to run VMware tests on VMware8

[6.14.z] Modify VMware tests to run on VMware8

---

tests/foreman/ui/test_user.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13922
in foreman 3.9 (6.15.z) 'en' was changed to 'English (United States)'

[6.15.z] Fix language setting

---

tests/foreman/cli/test_errata.py

Some Errata action items for failing setup and some sorting tests. 
- Changed nearly all `module_entitlement_manifest_org` to `module_sca_manifest_org`, the fixture often failed setup for no manifest content. This also prepares cli testing for SCA-only orgs coming in 6.16.0.
- Changed some remaining rh repo references from RHEL7 and RHST7, to RHEL8 and RHSClient8
- Updated some expected output from `JobInvocation` being created/started, checking completed status.
- Properly reading cli output, for errata 'Issue' and 'Update' dates

fixes for CLI post-eval failures

---

.github/workflows/auto_cherry_pick.yml

Some cherrypicks are failing and issues are also not being created.  https://github.com/SatelliteQE/robottelo/actions/runs/7459156590
We were missing the `always()` expression that led to this problem. This PR will fix that issue  
https://github.com/SatelliteQE/robottelo/actions/runs/7459156590

always expression was missing in the PR checking

---

tests/foreman/api/test_provisioning.py

Skipping Capsule provisioning test as this test needs to be run on destructive sat and in the provisioning pipeline, we use one VLAN for the satellite whereas in the Capsule test, we need one more VLAN which directly affects the other tests

Skip Capsule provisioning test

---

tests/foreman/api/test_provisioning.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14005
Skipping Capsule provisioning test as this test needs to be run on destructive sat and in the provisioning pipeline, we use one VLAN for the satellite whereas in the Capsule test, we need one more VLAN which directly affects the other tests

[6.15.z] Skip Capsule provisioning test

---

tests/foreman/api/test_provisioning.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14005
Skipping Capsule provisioning test as this test needs to be run on destructive sat and in the provisioning pipeline, we use one VLAN for the satellite whereas in the Capsule test, we need one more VLAN which directly affects the other tests

[6.14.z] Skip Capsule provisioning test

---

tests/foreman/api/test_provisioning.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14005
Skipping Capsule provisioning test as this test needs to be run on destructive sat and in the provisioning pipeline, we use one VLAN for the satellite whereas in the Capsule test, we need one more VLAN which directly affects the other tests

[6.13.z] Skip Capsule provisioning test

---

tests/foreman/ui/test_repositories.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13596
Adding customer case automation for overriding repos without using the select all method

[6.15.z] [Customer Case] Adding test for overriding repos no select all

---

.github/workflows/pull_request.yml
.github/workflows/weekly.yml
requirements.txt
robottelo/cli/base.py
robottelo/cli/subscription.py
tests/robottelo/test_cli.py
tests/robottelo/test_cli_method_calls.py

Python 3.12 is out and should be supported by Robottelo. Also switched the weekly workflow to use Python 3.12 instead of 3.11.

Add Python 3.12 to supported versions

---

.github/workflows/dependency_merge.yml

as dependency_merge.yml using same configuration as the master causing failure in the automerge.   
making dependency_merge.yml same as other z-stream branches
https://github.com/SatelliteQE/robottelo/actions/runs/7720921376

making dependency_merge.yml same as other z-stream branches

---

tests/foreman/api/test_registration.py

Global Registration using an new user with "Register Hosts" role ignores all the setup options.
Provided solution will fix the global registration problem with non-admin user
No
<!-- ### PRT test Cases example
pytest: tests/foreman/api/test_registration.py::test_positive_host_registration_with_non_admin_user

added test_positive_host_registration_with_non_admin_user

---

tests/foreman/api/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13915
Global Registration using an new user with "Register Hosts" role ignores all the setup options.
Provided solution will fix the global registration problem with non-admin user
No
<!-- ### PRT test Cases example
pytest: tests/foreman/api/test_registration.py::test_positive_host_registration_with_non_admin_user

[6.15.z] added test_positive_host_registration_with_non_admin_user

---

tests/foreman/api/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13915
Global Registration using an new user with "Register Hosts" role ignores all the setup options.
Provided solution will fix the global registration problem with non-admin user
No
<!-- ### PRT test Cases example
pytest: tests/foreman/api/test_registration.py::test_positive_host_registration_with_non_admin_user

[6.14.z] added test_positive_host_registration_with_non_admin_user

---

tests/foreman/virtwho/ui/test_esx_sca.py

Coverage [Bug 2158702](https://bugzilla.redhat.com/show_bug.cgi?id=2158702)
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest  ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_hypervisor_password_option --disable-pytest-warnings -q
2024-01-11 02:00:13 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
============================================================================ 1 passed, 35 deselected, 13 warnings in 169.65s (0:02:49) …
```

Coverage:Bug 2158702

---

pytest_fixtures/component/provision_vmware.py

VMware provisioning tests are failing due to scope mismatch error in `vmware` fixture
Updating the `vmware` fixture to module scope to fix the issue

Fix scope mismatch issue for VMware tests

---

tests/foreman/virtwho/ui/test_esx_sca.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13735
Coverage [Bug 2158702](https://bugzilla.redhat.com/show_bug.cgi?id=2158702)
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest  ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_hypervisor_password_option --disable-pytest-warnings -q
2024-01-11 02:00:13 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
============================================================================ 1 passed, 35 …
```

[6.15.z] Coverage:Bug 2158702

---

pytest_fixtures/component/provision_vmware.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14010
VMware provisioning tests are failing due to scope mismatch error in `vmware` fixture
Updating the `vmware` fixture to module scope to fix the issue

[6.14.z] Fix scope mismatch issue for VMware tests

---

pytest_fixtures/component/provision_vmware.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14010
VMware provisioning tests are failing due to scope mismatch error in `vmware` fixture
Updating the `vmware` fixture to module scope to fix the issue

[6.15.z] Fix scope mismatch issue for VMware tests

---

tests/foreman/virtwho/ui/test_esx_sca.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13735
Coverage [Bug 2158702](https://bugzilla.redhat.com/show_bug.cgi?id=2158702)
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest  ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_hypervisor_password_option --disable-pytest-warnings -q
2024-01-11 02:00:13 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
============================================================================ 1 passed, 35 …
```

[6.14.z] Coverage:Bug 2158702

---

tests/foreman/virtwho/ui/test_esx_sca.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13735
Coverage [Bug 2158702](https://bugzilla.redhat.com/show_bug.cgi?id=2158702)
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest  ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_hypervisor_password_option --disable-pytest-warnings -q
2024-01-11 02:00:13 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
============================================================================ 1 passed, 35 …
```

[6.13.z] Coverage:Bug 2158702

---

requirements.txt

Temporarily add docker and paramiko deps

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14020

[6.12.z] Temporarily add docker and paramiko deps

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14020

[6.13.z] Temporarily add docker and paramiko deps

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14020

[6.14.z] Temporarily add docker and paramiko deps

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14020

[6.15.z] Temporarily add docker and paramiko deps

---

.github/workflows/prt_result.yml

Currently, the PRT result gets clean after a new commit and there is no way for PR to know what happened with the result.  PRT passed/failed labels also need to be added automatically this helps in reviewing the PR quickly and merging them 
Add the dispatch workflow that takes care of this thing from the Jenkins CI update the GitHub comment with all details and apply the filter.  
I was able to test this on the my fork of robottelo here https://github.com/omkarkhatavkar/robottelo/actions/runs/7755989443/job/21152444058

preserving PRT result as part of github comment & PRT pass/fail label

---

tests/foreman/api/test_provisioningtemplate.py

Missing coverage for BZ:2193010 
Add check in existing test to cover  BZ:2193010

Add test for BZ:2193010 in provisioning templates

---

robottelo/hosts.py
tests/foreman/cli/test_report.py

Missing test coverage for BZ:2192939, which verifies config report generated for host gets Puppet origin correctly, when reports are without any messages.
1. Add test to validate config reports gets generated for host and has Puppet origin set correctly, when reports are without any messages.
2. Updating configure_puppet helper to not run puppet agent if run_puppet_agent=False, after we sign agent's certificate.
3. Furthermore, additional validation is added for the 'puppetmaster_fqdn' host fact, when puppetmaster is Sat/Cap server, and existing tests are updated accordingly.

Add test coverage for BZ:2192939

---

robottelo/hosts.py
tests/foreman/cli/test_report.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14025
Missing test coverage for BZ:2192939, which verifies config report generated for host gets Puppet origin correctly, when reports are without any messages.
1. Add test to validate config reports gets generated for host and has Puppet origin set correctly, when reports are without any messages.
2. Updating configure_puppet helper to not run puppet agent if run_puppet_agent=False, after we sign agent's certificate.
3. Furthermore, additional validation is added for the 'puppetmaster_fqdn' host fact, when puppetmaster is Sat/Cap server, and existing tests are updated accordingly.

[6.13.z] Add test coverage for BZ:2192939

---

robottelo/hosts.py
tests/foreman/cli/test_report.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14025
Missing test coverage for BZ:2192939, which verifies config report generated for host gets Puppet origin correctly, when reports are without any messages.
1. Add test to validate config reports gets generated for host and has Puppet origin set correctly, when reports are without any messages.
2. Updating configure_puppet helper to not run puppet agent if run_puppet_agent=False, after we sign agent's certificate.
3. Furthermore, additional validation is added for the 'puppetmaster_fqdn' host fact, when puppetmaster is Sat/Cap server, and existing tests are updated accordingly.

[6.15.z] Add test coverage for BZ:2192939

---

robottelo/hosts.py
tests/foreman/cli/test_report.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14025
Missing test coverage for BZ:2192939, which verifies config report generated for host gets Puppet origin correctly, when reports are without any messages.
1. Add test to validate config reports gets generated for host and has Puppet origin set correctly, when reports are without any messages.
2. Updating configure_puppet helper to not run puppet agent if run_puppet_agent=False, after we sign agent's certificate.
3. Furthermore, additional validation is added for the 'puppetmaster_fqdn' host fact, when puppetmaster is Sat/Cap server, and existing tests are updated accordingly.

[6.14.z] Add test coverage for BZ:2192939

---

tests/foreman/sys/test_pulp3_filesystem.py

The BZ in the test case has been migrated to jira so the check doesn't work.
The older BZ is entirely unrelated to the test  case so removed it but we ran into another issue and raised a BZ for it -> BZ#2263294
Removing the check from the test.

Remove BZ check which is migrated to Jira and Add new BZ check causing selinux denials

---

.github/workflows/prt_result.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13979
Currently, the PRT result gets clean after a new commit and there is no way for PR to know what happened with the result.  PRT passed/failed labels also need to be added automatically this helps in reviewing the PR quickly and merging them 
Add the dispatch workflow that takes care of this thing from the Jenkins CI update the GitHub comment with all details and apply the filter.  
I was able to test this on the my fork of robottelo here https://github.com/omkarkhatavkar/robottelo/actions/runs/7755989443/job/21152444058

[6.14.z] preserving PRT result as part of github comment & PRT pass/fail label

---

.github/workflows/prt_result.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13979
Currently, the PRT result gets clean after a new commit and there is no way for PR to know what happened with the result.  PRT passed/failed labels also need to be added automatically this helps in reviewing the PR quickly and merging them 
Add the dispatch workflow that takes care of this thing from the Jenkins CI update the GitHub comment with all details and apply the filter.  
I was able to test this on the my fork of robottelo here https://github.com/omkarkhatavkar/robottelo/actions/runs/7755989443/job/21152444058

[6.13.z] preserving PRT result as part of github comment & PRT pass/fail label

---

tests/foreman/ui/test_host.py
tests/foreman/ui/test_registration.py

Automatic cherrypick failed for https://github.com/SatelliteQE/robottelo/issues/14051
Manual cherrypick of https://github.com/SatelliteQE/robottelo/issues/14051

[6.14.z Cherrypick PR#13450] Move Registration test cases

---

tests/foreman/sys/test_pulp3_filesystem.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13923
The BZ in the test case has been migrated to jira so the check doesn't work.
The older BZ is entirely unrelated to the test  case so removed it but we ran into another issue and raised a BZ for it -> BZ#2263294
Removing the check from the test.

[6.13.z] Remove BZ check which is migrated to Jira and Add new BZ check causing selinux denials

---

tests/foreman/sys/test_pulp3_filesystem.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13923
The BZ in the test case has been migrated to jira so the check doesn't work.
The older BZ is entirely unrelated to the test  case so removed it but we ran into another issue and raised a BZ for it -> BZ#2263294
Removing the check from the test.

[6.14.z] Remove BZ check which is migrated to Jira and Add new BZ check causing selinux denials

---

tests/foreman/api/test_errata.py

- Add coverage for incremental update, that it is available when expected, and 
- that the expected host's content-view and environment(s) are are updated as expected, and
- the available errata/packages to host are updated by the incremental version as expected.
- we can install updated packages and see the expected (filtered-security only) applicable errata/count drops, and 
the applicable packages count drops.
- modification to helper method `cv_publish_promote`, which did not always filter environment ids for promotion as expected.
We already have some testing for if any incremental update is needed on a single view/environment, `test_positive_incremental_update_required`:
- But the existing test doesn't check the successful update and new CV version itself (contained errata/content). …

Errata coverage for CV Incremental Update

---

tests/foreman/cli/test_realm.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14063
null

[6.15.z] Rename test to reflect it tests proxy id

---

tests/foreman/api/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13994
- Add coverage for incremental update, that it is available when expected, and 
- that the expected host's content-view and environment(s) are are updated as expected, and
- the available errata/packages to host are updated by the incremental version as expected.
- we can install updated packages and see the expected (filtered-security only) applicable errata/count drops, and 
the applicable packages count drops.
- modification to helper method `cv_publish_promote`, which did not always filter environment ids for promotion as expected.
We already have some testing for if any incremental update is needed on a single view/environment, `test_positive_incremental_update_required`:
- But the existing test doesn't check the …

[6.15.z] Errata coverage for CV Incremental Update

---

tests/foreman/ui/test_host.py

CE request: `The test case should also include, assigning multiple compliance policy to the same content host and then unassing one of the compliance policy and veirfy if the correct compliace policy is getting unassigned.`

Test unassigning with multiple policies present

---

robottelo/host_helpers/cli_factory.py

```
AttributeError: 'Manifest' object has no attribute 'path'
```
Follow idiom of creating a temporary file and into it, copying an in-memory object, then using it as a file.
I'm not sure how and when it got broken, I hit it when looking at the results of `test_negative_without_attach_with_lce`. I haven't yet tested extensively to make sure this doesn't break function `_setup_org_for_a_rh_repo` in other cases but it seems like it couldn't have worked.

setup_org_for_a_rh_repo fix

---

tests/foreman/ui/test_search.py

New module and test case for vertical menu search functionality.
TC: `test_positive_vertical_navigation_search_end_to_end`
Requires: https://github.com/SatelliteQE/airgun/pull/1076

Vertical menu search test

---

testimony.yaml
tests/foreman/api/test_http_proxy.py
tests/foreman/cli/test_http_proxy.py
tests/foreman/ui/test_http_proxy.py

While HTTP Proxy does exist in BZ as a unique component and robotello has `{api|cli|ui}/http_proxy.py` modules too, the test cases still belong under the `Repository` component for some reason.
This doesn't seem logical and makes it more difficult to do TFA, so I believe we should create a separate component in robottelo and CI and flip the tests there.
This PR (and another one in CI).

Move HTTP Proxy tests under correct component

---

robottelo/constants/repos.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13365
`rpm-zchunk` repo was removed from fixtures, which makes some ACS tests to fail:
```
"description"=>"ACS remote for url \'https://fixtures.pulpproject.org/rpm-zchunk/\' raised an error \'404: Not Found\'. Please check your ACS remote configuration."
```
Use another yum repo, preferably one with the new zst metadata compression.

[6.13.z] Update yum repo for ACSes

---

testimony.yaml
tests/foreman/api/test_http_proxy.py
tests/foreman/cli/test_http_proxy.py
tests/foreman/ui/test_http_proxy.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14074
While HTTP Proxy does exist in BZ as a unique component and robotello has `{api|cli|ui}/http_proxy.py` modules too, the test cases still belong under the `Repository` component for some reason.
This doesn't seem logical and makes it more difficult to do TFA, so I believe we should create a separate component in robottelo and CI and flip the tests there.
This PR (and another one in CI).

[6.15.z] Move HTTP Proxy tests under correct component

---

testimony.yaml
tests/foreman/api/test_http_proxy.py
tests/foreman/cli/test_http_proxy.py
tests/foreman/ui/test_http_proxy.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14074
While HTTP Proxy does exist in BZ as a unique component and robotello has `{api|cli|ui}/http_proxy.py` modules too, the test cases still belong under the `Repository` component for some reason.
This doesn't seem logical and makes it more difficult to do TFA, so I believe we should create a separate component in robottelo and CI and flip the tests there.
This PR (and another one in CI).

[6.14.z] Move HTTP Proxy tests under correct component

---

testimony.yaml
tests/foreman/api/test_http_proxy.py
tests/foreman/cli/test_http_proxy.py
tests/foreman/ui/test_http_proxy.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14074
While HTTP Proxy does exist in BZ as a unique component and robotello has `{api|cli|ui}/http_proxy.py` modules too, the test cases still belong under the `Repository` component for some reason.
This doesn't seem logical and makes it more difficult to do TFA, so I believe we should create a separate component in robottelo and CI and flip the tests there.
This PR (and another one in CI).

[6.13.z] Move HTTP Proxy tests under correct component

---

tests/foreman/cli/test_reporttemplates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14068
test_negative_generate_hostpkgcompare_nonexistent_host is failing due to our of date attributes in assertion 
Change cm.exeption.stderr to cm.value.stderr

[6.15.z] [Test Fix] test_negative_generate_hostpkgcompare_nonexistent_host

---

tests/foreman/cli/test_reporttemplates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14068
test_negative_generate_hostpkgcompare_nonexistent_host is failing due to our of date attributes in assertion 
Change cm.exeption.stderr to cm.value.stderr

[6.14.z] [Test Fix] test_negative_generate_hostpkgcompare_nonexistent_host

---

tests/foreman/cli/test_auth.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14061
null

[6.15.z] Make docstring more understandable. Lower importance.

---

pytest_fixtures/component/provision_pxe.py
tests/foreman/api/test_discoveredhost.py

Missing `indirect=True` in parametrization  for provision_multiple_hosts fixture which causes,
```
tests/foreman/api/test_discoveredhost.py:427: in test_positive_reboot_all_pxe_hosts
for host in provision_multiple_hosts:
E   TypeError: 'int' object is not iterable
```
using getattr to set count as default for this fixture, and removing `@pytest.mark.parametrize` for this fixture, along with mark for pxe_loader fixture which also has bios set as default.

Fix parametrization in test_positive_reboot_all_pxe_hosts

---

tests/foreman/api/test_reporttemplates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14035
Create template report with blank name
Given solution will not create template report without name, it should give error.
No

[6.14.z] create report template w/o name

---

tests/foreman/api/test_reporttemplates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14035
Create template report with blank name
Given solution will not create template report without name, it should give error.
No

[6.13.z] create report template w/o name

---

tests/foreman/api/test_reporttemplates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14035
Create template report with blank name
Given solution will not create template report without name, it should give error.
No

[6.15.z] create report template w/o name

---

pytest_fixtures/component/provision_pxe.py
tests/foreman/api/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13949
Missing `indirect=True` in parametrization  for provision_multiple_hosts fixture which causes,
```
tests/foreman/api/test_discoveredhost.py:427: in test_positive_reboot_all_pxe_hosts
for host in provision_multiple_hosts:
E   TypeError: 'int' object is not iterable
```
using getattr to set count as default for this fixture, and removing `@pytest.mark.parametrize` for this fixture, along with mark for pxe_loader fixture which also has bios set as default.

[6.15.z] Fix parametrization in test_positive_reboot_all_pxe_hosts

---

pytest_fixtures/component/provision_pxe.py
tests/foreman/api/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13949
Missing `indirect=True` in parametrization  for provision_multiple_hosts fixture which causes,
```
tests/foreman/api/test_discoveredhost.py:427: in test_positive_reboot_all_pxe_hosts
for host in provision_multiple_hosts:
E   TypeError: 'int' object is not iterable
```
using getattr to set count as default for this fixture, and removing `@pytest.mark.parametrize` for this fixture, along with mark for pxe_loader fixture which also has bios set as default.

[6.14.z] Fix parametrization in test_positive_reboot_all_pxe_hosts

---

pytest_fixtures/component/provision_pxe.py
tests/foreman/api/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13949
Missing `indirect=True` in parametrization  for provision_multiple_hosts fixture which causes,
```
tests/foreman/api/test_discoveredhost.py:427: in test_positive_reboot_all_pxe_hosts
for host in provision_multiple_hosts:
E   TypeError: 'int' object is not iterable
```
using getattr to set count as default for this fixture, and removing `@pytest.mark.parametrize` for this fixture, along with mark for pxe_loader fixture which also has bios set as default.

[6.13.z] Fix parametrization in test_positive_reboot_all_pxe_hosts

---

robottelo/hosts.py
tests/foreman/ui/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14004
Create a test for the change host's content source feature.
Fixture and test were created.
The fixture does the necessary setup on the satellite, host, and capsule.
Test exercises different ways how to change the host's content source.
Needs [Airgun#1226](https://github.com/SatelliteQE/airgun/pull/1226).

[6.14.z] Test for the change host's content source feature

---

tests/foreman/api/test_repository.py

(https://github.com/Katello/katello/pull/10875) `/katello/api/organizations/6/simple_content_access/disable` is being removed from stream/6.16
need to move from module_entitlement_manifest_org to module_sca_manifest_org in code base

moving from module_entitlement_manifest_org to module_sca_manifest_org

---

tests/foreman/api/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14096
(https://github.com/Katello/katello/pull/10875) `/katello/api/organizations/6/simple_content_access/disable` is being removed from stream/6.16
need to move from module_entitlement_manifest_org to module_sca_manifest_org in code base

[6.15.z] moving from module_entitlement_manifest_org to module_sca_manifest_org

---

tests/foreman/ui/test_errata.py

- Occasional e2e failure in one or two parameters for `UI::Errata::test_end_to_end[rhel7, 8, 9]`.
- Upon asserting one applicable errata, after installing an outdated applicable package.
```
tests/foreman/ui/test_errata.py:396: in test_end_to_end
assert (applicable_errata == 1)
E   AssertionError: Expected 1 applicable errata: RHSA-2012:0055, after setup. Got 0
E   assert 0 == 1
```
- Follow-up after resolving `AssertionError`, now failing to navigate to `[Details]` 
at [Ln405](https://github.com/SatelliteQE/robottelo/pull/14095/files#:~:text=assert%20session.errata.search_content_hosts): `assert session.contenthost.search_content_hosts(...)`
```
navmazing._errors.NavigationTriesExceeded: Navigation failed to reach [Details] in the specified tries
>           raise …
```

[E2E] Recalculate applicability before UI session, fix navigation failure

---

tests/foreman/ui/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14095
- Occasional e2e failure in one or two parameters for `UI::Errata::test_end_to_end[rhel7, 8, 9]`.
- Upon asserting one applicable errata, after installing an outdated applicable package.
```
tests/foreman/ui/test_errata.py:396: in test_end_to_end
assert (applicable_errata == 1)
E   AssertionError: Expected 1 applicable errata: RHSA-2012:0055, after setup. Got 0
E   assert 0 == 1
```
- Follow-up after resolving `AssertionError`, now failing to navigate to `[Details]` 
at [Ln405](https://github.com/SatelliteQE/robottelo/pull/14095/files#:~:text=assert%20session.errata.search_content_hosts): `assert session.contenthost.search_content_hosts(...)`
```
navmazing._errors.NavigationTriesExceeded: Navigation failed to reach …
```

[6.15.z] [E2E] Recalculate applicability before UI session, fix navigation failure

---

tests/foreman/api/test_repositories.py

Pulp test is failing on stream as it was using sca disabled manifest.
Updated test to use sca-enabled test.

Update test to use sca enabled manifest

---

tests/foreman/api/test_repositories.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14130
Pulp test is failing on stream as it was using sca disabled manifest.
Updated test to use sca-enabled test.

[6.15.z] Update test to use sca enabled manifest

---

tests/foreman/destructive/test_installer.py
tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14099
Fixing assertions that were always True and therefore useless.
Note: `bool("any string with non-zero length")` is True, `True or False` is True

[6.14.z] Fix useless asserts in installer tests

---

tests/foreman/destructive/test_installer.py
tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14099
Fixing assertions that were always True and therefore useless.
Note: `bool("any string with non-zero length")` is True, `True or False` is True

[6.15.z] Fix useless asserts in installer tests

---

tests/foreman/destructive/test_installer.py
tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14099
Fixing assertions that were always True and therefore useless.
Note: `bool("any string with non-zero length")` is True, `True or False` is True

[6.13.z] Fix useless asserts in installer tests

---

tests/foreman/ui/test_search.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13421
New module and test case for vertical menu search functionality.
TC: `test_positive_vertical_navigation_search_end_to_end`
Requires: https://github.com/SatelliteQE/airgun/pull/1076

[6.15.z] Vertical menu search test

---

robottelo/host_helpers/contenthost_mixins.py

Remove enable_tools_repo and enable_rhel_repo methods

---

robottelo/host_helpers/contenthost_mixins.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14134

[6.12.z] Remove enable_tools_repo and enable_rhel_repo methods

---

robottelo/host_helpers/contenthost_mixins.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14134

[6.14.z] Remove enable_tools_repo and enable_rhel_repo methods

---

robottelo/host_helpers/contenthost_mixins.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14134

[6.13.z] Remove enable_tools_repo and enable_rhel_repo methods

---

robottelo/host_helpers/contenthost_mixins.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14134

[6.15.z] Remove enable_tools_repo and enable_rhel_repo methods

---

tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14142
CVV sorting issue hits again ([BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2209758) for reference)
Use CVV with highest id.
pytest: tests/foreman/cli/test_satellitesync.py -k export_import_filtered_cvv

[6.14.z] ISS fix for CVV sorting issue

---

tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14142
CVV sorting issue hits again ([BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2209758) for reference)
Use CVV with highest id.
pytest: tests/foreman/cli/test_satellitesync.py -k export_import_filtered_cvv

[6.13.z] ISS fix for CVV sorting issue

---

tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14142
CVV sorting issue hits again ([BZ](https://bugzilla.redhat.com/show_bug.cgi?id=2209758) for reference)
Use CVV with highest id.
pytest: tests/foreman/cli/test_satellitesync.py -k export_import_filtered_cvv

[6.15.z] ISS fix for CVV sorting issue

---

tests/foreman/api/test_docker.py
tests/foreman/api/test_repository.py
tests/foreman/cli/test_repository.py
tests/foreman/ui/test_repository.py
tests/foreman/ui/test_sync.py

Auto CP failed for this [6.15.z] PR https://github.com/SatelliteQE/robottelo/issues/14141
Manual CP, PR raised against 6.15.z branch

[6.15.z] deleted tc's by considering recommendation present in repositories component audit

---

robottelo/host_helpers/api_factory.py
tests/foreman/api/test_http_proxy.py

As 6.16 is SCA-only we need to get rid of entitlements and subscriptions related logic in our tests but keep the approach user take for this or similar scenario.
Get rid of entitlements/subscriptions. Also I propose to change this test case to `e2e` since it syncs a RH repo, publishes and promotes it to an LCE, registers a content host via AK and consumes the content in it. Case remain parametrized to run with authenticated, unauthenticated and without (this param could be probably omited) HTTP proxy.
One minor update in `enable_sync_redhat_repo` so that we can use repos from constants which define `arch` key instead of `basearch` or even no arch at all.
**Open question:** Should the test id be changed since it doesn't cover the subscription manipulation at all? …

SCA refactor of Subscription HTTP proxy test

---

tests/foreman/api/test_discoveryrule.py

[test_positive_end_to_end_crud](https://github.com/SatelliteQE/robottelo/blob/96b7d330097b138e1f850a725c0c088124d509e5/tests/foreman/api/test_discoveryrule.py#L41) is failing during creation of discoveryrule due to not returning the hostgroup required from the fixture.
Fix the module_hostgroup fixture to yield hostgroup as it was missing.

[6.13.z] Fix discovery rule test

---

pytest_fixtures/component/templatesync.py
tests/foreman/cli/test_templatesync.py

a bunch or templatesync tests failing with `Host key verification failed` when exporting templates to gitea. Turns out that ssh-keyscan opts for ipv6 connenction, where it gets no response
Force ssh-keyscan to go via ipv6. Also updated filter to use existing template

Force keyscan to use ipv4

---

tests/foreman/api/test_repository.py
tests/foreman/cli/test_repository.py
tests/foreman/ui/test_repository.py

There seems few tests which doesn't match with it's associated BZ information, some tests have steps missing in it, some have wrong descriptions and steps.
Update test information - steps/description/component name or shift test under another component's test module.
N/A

correct component names and description

---

tests/foreman/api/test_repository.py
tests/foreman/cli/test_repository.py
tests/foreman/ui/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14179
There seems few tests which doesn't match with it's associated BZ information, some tests have steps missing in it, some have wrong descriptions and steps.
Update test information - steps/description/component name or shift test under another component's test module.
N/A

[6.14.z] correct component names and description

---

tests/foreman/api/test_repository.py
tests/foreman/cli/test_repository.py
tests/foreman/ui/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14179
There seems few tests which doesn't match with it's associated BZ information, some tests have steps missing in it, some have wrong descriptions and steps.
Update test information - steps/description/component name or shift test under another component's test module.
N/A

[6.15.z] correct component names and description

---

tests/foreman/installer/test_installer.py

Previously we had to use a workaround to run the installation on specified RHEL version. We had to use the _pit_client_ marker and test the satellite installation on a client (content_host).
Thanks to #13177 we no longer need to do that.

Fix pit marker in installer

---

tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14180
Previously we had to use a workaround to run the installation on specified RHEL version. We had to use the _pit_client_ marker and test the satellite installation on a client (content_host).
Thanks to #13177 we no longer need to do that.

[6.15.z] Fix pit marker in installer

---

pytest_fixtures/component/templatesync.py
tests/foreman/cli/test_templatesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14017
a bunch or templatesync tests failing with `Host key verification failed` when exporting templates to gitea. Turns out that ssh-keyscan opts for ipv6 connenction, where it gets no response
Force ssh-keyscan to go via ipv6. Also updated filter to use existing template

[6.14.z] Force keyscan to use ipv4

---

pytest_fixtures/component/templatesync.py
tests/foreman/cli/test_templatesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14017
a bunch or templatesync tests failing with `Host key verification failed` when exporting templates to gitea. Turns out that ssh-keyscan opts for ipv6 connenction, where it gets no response
Force ssh-keyscan to go via ipv6. Also updated filter to use existing template

[6.15.z] Force keyscan to use ipv4

---

pytest_fixtures/component/templatesync.py
tests/foreman/cli/test_templatesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14017
a bunch or templatesync tests failing with `Host key verification failed` when exporting templates to gitea. Turns out that ssh-keyscan opts for ipv6 connenction, where it gets no response
Force ssh-keyscan to go via ipv6. Also updated filter to use existing template

[6.12.z] Force keyscan to use ipv4

---

tests/foreman/ui/test_eol_banner.py

testing end of life banner 
requires https://github.com/SatelliteQE/airgun/pull/1049

eol banner

---

tests/foreman/ui/test_eol_banner.py

All newly opened PR was unable to pass their checks due to unexpected testimony tokens present in file ui > test_eol_banner.py:38 eol banner [#13211](https://github.com/SatelliteQE/robottelo/pull/13211/files)
```
* Unexpected tokens:
Caselevel: Acceptance
Testtype: Functional
Upstream: No
```
Basically above metadata is not present in rebottelo>testimony.yaml so removing these 3 tokens will help to fix issue and Robottelo - CI / Code Quality checks would pass.
eol banner https://github.com/SatelliteQE/robottelo/pull/13211

remove unexpected tokens from ui test_eol_banner.py

---

tests/foreman/api/test_convert2rhel.py

(cherry picked from commit 9f42080d00d9ac3fec70474cc3d276b4a5f8d07b)
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/13236
OEL Convert2Rhel tests failing
Use UBI repos required for subman packages, while registration instead of syncing.
Fix OEL tests by adding and modifying remediations for the inhibitors.
Replacing existing register_host() method with API method to generate register command - Fixes https://github.com/SatelliteQE/robottelo/issues/11876

[6.15.z] Fix OEL Convert2Rhel tests

---

tests/foreman/installer/test_installer.py

(cherry picked from commit b5bbc224c88a164c3be2cab906645518d9dbc84d)
backport of #14180
closes #14188

[6.14.z] Fix pit marker in installer (#14180)

---

tests/foreman/api/test_convert2rhel.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14194
(cherry picked from commit 9f42080d00d9ac3fec70474cc3d276b4a5f8d07b)
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/13236
OEL Convert2Rhel tests failing
Use UBI repos required for subman packages, while registration instead of syncing.
Fix OEL tests by adding and modifying remediations for the inhibitors.
Replacing existing register_host() method with API method to generate register command - Fixes https://github.com/SatelliteQE/robottelo/issues/11876

[6.14.z] Fix OEL Convert2Rhel tests

---

tests/foreman/ui/test_registration.py

Applying the component evaluation feedback to cover 1955421
Adding a nested hostgroup to the global registration test to check the values are populated correctly

global registration with nested hostgroup

---

tests/foreman/api/test_repository.py

As per PX recommendation need to add steps and update automation coverage around the test.
Jira-23358
- Add test steps in test case
- Add additional assersions at the end of test
N/A

add test steps, refresh uploaded manifest file

---

tests/foreman/api/test_repository.py

As per comment on original PR https://github.com/SatelliteQE/robottelo/pull/14195#discussion_r1503974136 from @shweta83 we are suppose to use sca-disable org for 6.14.z and lower version.
I talked with Phoenix team and we decided to use function scope fixture instead of module scope just to avoid any future failure with module scope org
CC: @vsedmik @synkd 
NA

[6.14.z & 6.13.z] add test steps, refresh uploaded manifest file

---

robottelo/cli/hammer.py

host package_list fix

---

tests/foreman/api/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14208
As per comment on original PR https://github.com/SatelliteQE/robottelo/pull/14195#discussion_r1503974136 from @shweta83 we are suppose to use sca-disable org for 6.14.z and lower version.
I talked with Phoenix team and we decided to use function scope fixture instead of module scope just to avoid any future failure with module scope org
CC: @vsedmik @synkd 
NA

[6.13.z] [6.14.z & 6.13.z] add test steps, refresh uploaded manifest file

---

robottelo/cli/hammer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13989

[6.13.z] host package_list fix

---

robottelo/cli/hammer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13989

[6.14.z] host package_list fix

---

robottelo/cli/hammer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13989

[6.12.z] host package_list fix

---

robottelo/cli/hammer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13989

[6.15.z] host package_list fix

---

pytest_fixtures/component/repository.py

As 6.16 is SCA-only we need to flip from `entitlement` to `SCA` mode. This fixture is still using entitlement, breaking all tests that use it in setup.
Flip it to SCA.

Flip repos_collection fixture to SCA

---

tests/foreman/ui/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13617
Applying the component evaluation feedback to cover 1955421
Adding a nested hostgroup to the global registration test to check the values are populated correctly

[6.15.z] global registration with nested hostgroup

---

tests/foreman/ui/test_ansible.py

Add pit marker to ansible test

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14227

[6.12.z] Add pit marker to ansible test

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14227

[6.14.z] Add pit marker to ansible test

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14227

[6.13.z] Add pit marker to ansible test

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14227

[6.15.z] Add pit marker to ansible test

---

tests/foreman/api/test_convert2rhel.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14194
(cherry picked from commit 9f42080d00d9ac3fec70474cc3d276b4a5f8d07b)
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/13236
OEL Convert2Rhel tests failing
Use UBI repos required for subman packages, while registration instead of syncing.
Fix OEL tests by adding and modifying remediations for the inhibitors.
Replacing existing register_host() method with API method to generate register command - Fixes https://github.com/SatelliteQE/robottelo/issues/11876

[6.13.z] Fix OEL Convert2Rhel tests

---

tests/foreman/api/test_subscription.py

During z-stream sign-off I noticed that `api/test_subscription.py/test_positive_delete_manifest_as_another_user` is failing with
```
E   TypeError: Subscription.init() got multiple values for argument 'server_config'
```
since [this entities refactor](https://github.com/SatelliteQE/robottelo/pull/13067/files#diff-d2c6c44eb9940dcd63eac12c534c75d8785ede8592528e64f0c927582cdcd2d5R212).
Pass the `server_config` as named parameter.
```
pytest: tests/foreman/api/test_subscription.py -k delete_manifest_as_another_user
```

Fix server_config in subscription test

---

tests/foreman/api/test_subscription.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14226
During z-stream sign-off I noticed that `api/test_subscription.py/test_positive_delete_manifest_as_another_user` is failing with
```
E   TypeError: Subscription.init() got multiple values for argument 'server_config'
```
since [this entities refactor](https://github.com/SatelliteQE/robottelo/pull/13067/files#diff-d2c6c44eb9940dcd63eac12c534c75d8785ede8592528e64f0c927582cdcd2d5R212).
Pass the `server_config` as named parameter.
```
pytest: tests/foreman/api/test_subscription.py -k delete_manifest_as_another_user
```

[6.15.z] Fix server_config in subscription test

---

tests/foreman/api/test_subscription.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14226
During z-stream sign-off I noticed that `api/test_subscription.py/test_positive_delete_manifest_as_another_user` is failing with
```
E   TypeError: Subscription.init() got multiple values for argument 'server_config'
```
since [this entities refactor](https://github.com/SatelliteQE/robottelo/pull/13067/files#diff-d2c6c44eb9940dcd63eac12c534c75d8785ede8592528e64f0c927582cdcd2d5R212).
Pass the `server_config` as named parameter.
```
pytest: tests/foreman/api/test_subscription.py -k delete_manifest_as_another_user
```

[6.13.z] Fix server_config in subscription test

---

tests/foreman/api/test_subscription.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14226
During z-stream sign-off I noticed that `api/test_subscription.py/test_positive_delete_manifest_as_another_user` is failing with
```
E   TypeError: Subscription.init() got multiple values for argument 'server_config'
```
since [this entities refactor](https://github.com/SatelliteQE/robottelo/pull/13067/files#diff-d2c6c44eb9940dcd63eac12c534c75d8785ede8592528e64f0c927582cdcd2d5R212).
Pass the `server_config` as named parameter.
```
pytest: tests/foreman/api/test_subscription.py -k delete_manifest_as_another_user
```

[6.12.z] Fix server_config in subscription test

---

tests/foreman/api/test_role.py

affected tests:
tests/foreman/api/test_role.py::TestCannedRole::test_positive_taxonomies_control_to_superadmin_without_org_admin 
tests/foreman/api/test_role.py::TestCannedRole::test_positive_taxonomies_control_to_superadmin_with_org_admin 
```
TypeError: Domain.__init__() got multiple values for argument 'server_config'
```
see PR

Call function parameters by key-value

---

tests/foreman/api/test_role.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14225
affected tests:
tests/foreman/api/test_role.py::TestCannedRole::test_positive_taxonomies_control_to_superadmin_without_org_admin 
tests/foreman/api/test_role.py::TestCannedRole::test_positive_taxonomies_control_to_superadmin_with_org_admin 
```
TypeError: Domain.__init__() got multiple values for argument 'server_config'
```
see PR

[6.15.z] Call function parameters by key-value

---

tests/foreman/api/test_role.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14225
affected tests:
tests/foreman/api/test_role.py::TestCannedRole::test_positive_taxonomies_control_to_superadmin_without_org_admin 
tests/foreman/api/test_role.py::TestCannedRole::test_positive_taxonomies_control_to_superadmin_with_org_admin 
```
TypeError: Domain.__init__() got multiple values for argument 'server_config'
```
see PR

[6.13.z] Call function parameters by key-value

---

tests/foreman/api/test_role.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14225
affected tests:
tests/foreman/api/test_role.py::TestCannedRole::test_positive_taxonomies_control_to_superadmin_without_org_admin 
tests/foreman/api/test_role.py::TestCannedRole::test_positive_taxonomies_control_to_superadmin_with_org_admin 
```
TypeError: Domain.__init__() got multiple values for argument 'server_config'
```
see PR

[6.14.z] Call function parameters by key-value

---

tests/foreman/api/test_webhook.py

TestWebhook::test_positive_valid_event[user_updated] 
instead of
TestWebhook::test_positive_valid_event[1]

More meaningful parametrization id

---

tests/foreman/api/test_webhook.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14223
TestWebhook::test_positive_valid_event[user_updated] 
instead of
TestWebhook::test_positive_valid_event[1]

[6.15.z] More meaningful parametrization id

---

tests/foreman/api/test_webhook.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14223
TestWebhook::test_positive_valid_event[user_updated] 
instead of
TestWebhook::test_positive_valid_event[1]

[6.14.z] More meaningful parametrization id

---

tests/foreman/installer/test_installer.py

(cherry picked from commit b5bbc224c88a164c3be2cab906645518d9dbc84d)
backport #14180
closes #14186

[6.13.z] Fix pit marker in installer (#14180)

---

tests/foreman/installer/test_installer.py

(cherry picked from commit b5bbc224c88a164c3be2cab906645518d9dbc84d)
backport #14180
closes #14187

[6.12.z] Fix pit marker in installer (#14180)

---

tests/foreman/api/test_http_proxy.py
tests/foreman/cli/test_http_proxy.py
tests/foreman/ui/test_http_proxy.py

During the HTTP proxy component evaluation PX/SD/QE agreed to make several changes. This PR addresses those related to the E2E tests, in particular:
- extends `test_positive_end_to_end` to sync other content type repos via HTTP proxy
- decreases CaseImportance of some 
Some other changes improve docstings - remove redundant fields and adds more information.
SAT-23276

Update HTTP Proxy e2e test cases

---

tests/foreman/cli/test_host.py

Fix the test. CV is already published and promoted by setup_org_for_a_rh_repo. Also, don't use 2 LCEs needlessly.

[6.15.z] CV already published + single LCE

---

tests/foreman/cli/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14237

[6.13.z] forgotten target sat in host cli tests

---

tests/foreman/cli/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14237

[6.15.z] forgotten target sat in host cli tests

---

tests/foreman/cli/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14237

[6.14.z] forgotten target sat in host cli tests

---

tests/foreman/cli/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14237

[6.12.z] forgotten target sat in host cli tests

---

requirements.txt

[6.15.z] Bump cryptography from 42.0.2 to 42.0.5

---

requirements.txt

[6.14.z] Bump Pytest to 8.0.2

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14255
Closes #14115 #14151 #14173

[6.14.z] Bump cryptography from 42.0.2 to 42.0.5

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14255
Closes #14115 #14151 #14173

[6.13.z] Bump cryptography from 42.0.2 to 42.0.5

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14255
Closes #14115 #14151 #14173

[6.12.z] Bump cryptography from 42.0.2 to 42.0.5

---

tests/foreman/api/test_registration.py

Customer was trying to register client using global registration template and while executing curl command the client was registered but it failed at one point and the echo $? showed exit status as 0.
Giving status code 0 if passed else 1

Fail curl command registration

---

tests/foreman/api/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14069
Customer was trying to register client using global registration template and while executing curl command the client was registered but it failed at one point and the echo $? showed exit status as 0.
Giving status code 0 if passed else 1

[6.15.z] Fail curl command registration

---

robottelo/constants/__init__.py
robottelo/host_helpers/repository_mixins.py
tests/foreman/api/test_http_proxy.py
tests/foreman/cli/test_http_proxy.py
tests/foreman/ui/test_http_proxy.py
tests/foreman/ui/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14215
During the HTTP proxy component evaluation PX/SD/QE agreed to make several changes. This PR addresses those related to the E2E tests, in particular:
- extends `test_positive_end_to_end` to sync other content type repos via HTTP proxy
- decreases CaseImportance of some 
Some other changes improve docstings - remove redundant fields and adds more information.
SAT-23276

[6.14.z] Update HTTP Proxy e2e test cases

---

robottelo/constants/__init__.py
robottelo/host_helpers/repository_mixins.py
tests/foreman/api/test_http_proxy.py
tests/foreman/cli/test_http_proxy.py
tests/foreman/ui/test_http_proxy.py
tests/foreman/ui/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14215
During the HTTP proxy component evaluation PX/SD/QE agreed to make several changes. This PR addresses those related to the E2E tests, in particular:
- extends `test_positive_end_to_end` to sync other content type repos via HTTP proxy
- decreases CaseImportance of some 
Some other changes improve docstings - remove redundant fields and adds more information.
SAT-23276

[6.13.z] Update HTTP Proxy e2e test cases

---

tests/upgrades/test_virtwho.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14260
add verify virt-who data is uploaded on satellite post satellite upgrade
Test Cases PASS:
```
(robottelo_vv_615) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade -s
2024-03-04 09:00:13 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
platform linux -- Python 3.11.7, pytest-8.0.1, pluggy-1.4.0
Mandatory Requirements Mismatch: paramiko==3.4.0  # Temporary until …
```

[6.15.z] add verify virt-who data is uploaded on satellite post satellite upgrade

---

pytest_fixtures/component/host.py
pytest_fixtures/component/puppet.py
pytest_fixtures/component/satellite_auth.py
tests/foreman/api/test_contentview.py
tests/foreman/cli/test_computeresource_libvirt.py
tests/foreman/cli/test_host.py
tests/foreman/destructive/test_ldap_authentication.py

Applying a mark to a fixture function never had any effect but is a common user error.
see: https://docs.pytest.org/en/stable/deprecations.html#applying-a-mark-to-a-fixture-function

Fix pytest deprecation warning

---

tests/foreman/cli/test_http_proxy.py

CLI `test_positive_assign_http_proxy_to_products` is flaky, it looks like the repo properties were not set in time (of assertion).
Wait for the Update repo tasks to finish.

Wait for product HTTP Proxy update to finish

---

tests/foreman/api/test_ansible.py

As part of component audit, it was suggested to cover a test for ansible roles assign/add/remove on nested host group, like normal or parent host group
Extend existing ansible-roles assign/add/remove test for nested hostgroups, similar to normal or parent host group in API

Extend ansible-roles add/remove test for nested HG

---

tests/foreman/destructive/test_contenthost.py

- `test_content_access_after_stopped_foreman` is failing at `org.sca_disable()` for Stream. 
- Also move the test to `Hosts-Content` component.
- Remove `org.sca_disable()` as 6.16 is SCA-only. 
- SAT-23522

Fix test_content_access_after_stopped_foreman

---

pytest_fixtures/component/host.py
pytest_fixtures/component/puppet.py
pytest_fixtures/component/satellite_auth.py
tests/foreman/api/test_contentview.py
tests/foreman/cli/test_computeresource_libvirt.py
tests/foreman/cli/test_host.py
tests/foreman/destructive/test_ldap_authentication.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14205
Applying a mark to a fixture function never had any effect but is a common user error.
see: https://docs.pytest.org/en/stable/deprecations.html#applying-a-mark-to-a-fixture-function

[6.14.z] Fix pytest deprecation warning

---

pytest_fixtures/component/host.py
pytest_fixtures/component/puppet.py
pytest_fixtures/component/satellite_auth.py
tests/foreman/api/test_contentview.py
tests/foreman/cli/test_computeresource_libvirt.py
tests/foreman/cli/test_host.py
tests/foreman/destructive/test_ldap_authentication.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14205
Applying a mark to a fixture function never had any effect but is a common user error.
see: https://docs.pytest.org/en/stable/deprecations.html#applying-a-mark-to-a-fixture-function

[6.13.z] Fix pytest deprecation warning

---

tests/foreman/cli/test_http_proxy.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14269
CLI `test_positive_assign_http_proxy_to_products` is flaky, it looks like the repo properties were not set in time (of assertion).
Wait for the Update repo tasks to finish.

[6.14.z] Wait for product HTTP Proxy update to finish

---

tests/foreman/cli/test_http_proxy.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14269
CLI `test_positive_assign_http_proxy_to_products` is flaky, it looks like the repo properties were not set in time (of assertion).
Wait for the Update repo tasks to finish.

[6.15.z] Wait for product HTTP Proxy update to finish

---

tests/foreman/cli/test_http_proxy.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14269
CLI `test_positive_assign_http_proxy_to_products` is flaky, it looks like the repo properties were not set in time (of assertion).
Wait for the Update repo tasks to finish.

[6.13.z] Wait for product HTTP Proxy update to finish

---

tests/foreman/api/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14272
As part of component audit, it was suggested to cover a test for ansible roles assign/add/remove on nested host group, like normal or parent host group
Extend existing ansible-roles assign/add/remove test for nested hostgroups, similar to normal or parent host group in API

[6.15.z] Extend ansible-roles add/remove test for nested HG

---

tests/foreman/cli/test_host.py

Fix the test. CV is already published and promoted by setup_org_for_a_rh_repo. Also, don't use 2 LCEs needlessly.

CV already published + single LCE

---

.github/workflows/prt_labels.yml

To address this issue, we propose implementing a solution using GitHub Actions (GHA). The solution involves periodically checking the GitHub status API to monitor for new commits on the pull request. Upon detecting a new commit, the workflow will automatically remove the `PRT-Passed` and `PRT-Failed` labels from the pull request. This ensures that the labels accurately reflect the current status of the pull request, reducing confusion and …

remove the PRT labels for new commits

---

robottelo/host_helpers/satellite_mixins.py

```
robottelo/host_helpers/satellite_mixins.py:151: in upload_manifest
or manifest.content is None
E   AttributeError: 'bytes' object has no attribute 'content'
```
After applying valid bracket scope it will run the test successfully

fixed sanity suite, AttributeError due to not matching scope

---

requirements.txt

Fixes https://github.com/SatelliteQE/robottelo/issues/14292
Manual Cherrypick of https://github.com/SatelliteQE/robottelo/pull/14243

[6.15.z] Bump pytest from 8.0.2 to 8.1.0

---

.github/workflows/prt_labels.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14093
To address this issue, we propose implementing a solution using GitHub Actions (GHA). The solution involves periodically checking the GitHub status API to monitor for new commits on the pull request. Upon detecting a new commit, the workflow will automatically remove the `PRT-Passed` and `PRT-Failed` labels from the pull request. This ensures that the labels accurately reflect …

[6.15.z] remove the PRT labels for new commits

---

tests/foreman/cli/test_satellitesync.py

In ISS one test is failing due to timing issue, one due to pending BZ.
Wait for the CV remove task to finish in first case and skip the second.

Fix failing ISS tests

---

tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14315
In ISS one test is failing due to timing issue, one due to pending BZ.
Wait for the CV remove task to finish in first case and skip the second.

[6.14.z] Fix failing ISS tests

---

tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14315
In ISS one test is failing due to timing issue, one due to pending BZ.
Wait for the CV remove task to finish in first case and skip the second.

[6.13.z] Fix failing ISS tests

---

tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14315
In ISS one test is failing due to timing issue, one due to pending BZ.
Wait for the CV remove task to finish in first case and skip the second.

[6.15.z] Fix failing ISS tests

---

tests/foreman/api/test_permission.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14207
SAT-21619 (component evaluation).
Check for correct user permissions when deleting a host.

[6.15.z] host delete permissions test

---

pytest_fixtures/component/taxonomy.py
tests/foreman/ui/test_host.py

hosts: run test_positive_manage_table_columns also with non-admin user
The test for hosts 'Manage Columns' feature now runs also for a non-admin user.
Resolves this customer BZ: https://bugzilla.redhat.com/2212499

Hosts: run 'Manage columns' RFE test also for non-admin user

---

conf/capsule.yaml.template
conf/dynaconf_hooks.py
conftest.py
pytest_fixtures/core/sat_cap_factory.py
pytest_plugins/capsule_n-minus.py
robottelo/exceptions.py
robottelo/hosts.py
tests/foreman/api/test_capsule.py
tests/foreman/api/test_capsulecontent.py
tests/foreman/destructive/test_registration.py

Changes include:
- A new pytest plugin for Capsule N-minus testing that would smart collect all capsule specific tests excluding few.
- New option of `--n-minus` for collecting only capsule specific tests
- tests using the caspule_factory are collected
- destructive, maintain and puppet tests are excluded since they need a separate satellite
- Introduces new setting `hostname` in capsule conf to take capsule hostname given from CI.
- **_target_capsule_host context manager now returns the cached capsule taken from CI instead of spinning of new capsule for everytime**. 
- The CI capsule is registered once/cached to CDN for RHEL contents needed by some tests at the start of the n-minus testing and would be unregistered at the end of test session.
- Since we are using single capsule already …

Capsule N-Minus testing

---

pytest_fixtures/component/taxonomy.py
tests/foreman/ui/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14247
hosts: run test_positive_manage_table_columns also with non-admin user
The test for hosts 'Manage Columns' feature now runs also for a non-admin user.
Resolves this customer BZ: https://bugzilla.redhat.com/2212499

[6.15.z] Hosts: run 'Manage columns' RFE test also for non-admin user

---

tests/foreman/sys/test_fam.py

The file transfer in `setup_fam` was failing in CI. This came from an untested change on my last PR.
Convert PosixPath objects to strings.

Fix manifest file transer for fam

---

robottelo/cli/syncplan.py
robottelo/host_helpers/cli_factory.py
tests/foreman/cli/test_syncplan.py

Some CLI SyncPlan tests are failing randomly. The reason is that `cli_factory` takes random `interval` (when not provided explicitly) in options and ignores that `custom cron` needs additional `cron-interval` option, so the tests fail on validation.
```
robottelo.exceptions.CLIFactoryError: Failed to create SyncPlan with data:
{ 'description': 'QpRNvtrDBf',
'enabled': 'false',
'interval': 'custom cron',
'name': 'KwgvwcaNvc',
'sync-date': '2024-03-07 01:33:04'}
Command "sync-plan create" finished with status 70
Could not create the sync plan:
Cron expression is not valid!
```
Plus one small param fix forgotten in CLI refactor.
Do not pick `custom cron` randomly from factory and check the `cron-interval` is provided when `custom cron` is used.
trigger: …

Fix flaky SyncPlans in cli_factory

---

robottelo/cli/syncplan.py
robottelo/host_helpers/cli_factory.py
tests/foreman/cli/test_syncplan.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14337
Some CLI SyncPlan tests are failing randomly. The reason is that `cli_factory` takes random `interval` (when not provided explicitly) in options and ignores that `custom cron` needs additional `cron-interval` option, so the tests fail on validation.
```
robottelo.exceptions.CLIFactoryError: Failed to create SyncPlan with data:
{ 'description': 'QpRNvtrDBf',
'enabled': 'false',
'interval': 'custom cron',
'name': 'KwgvwcaNvc',
'sync-date': '2024-03-07 01:33:04'}
Command "sync-plan create" finished with status 70
Could not create the sync plan:
Cron expression is not valid!
```
Plus one small param fix forgotten in CLI refactor.
Do not pick `custom cron` randomly from factory and …

[6.15.z] Fix flaky SyncPlans in cli_factory

---

robottelo/cli/syncplan.py
robottelo/host_helpers/cli_factory.py
tests/foreman/cli/test_syncplan.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14337
Some CLI SyncPlan tests are failing randomly. The reason is that `cli_factory` takes random `interval` (when not provided explicitly) in options and ignores that `custom cron` needs additional `cron-interval` option, so the tests fail on validation.
```
robottelo.exceptions.CLIFactoryError: Failed to create SyncPlan with data:
{ 'description': 'QpRNvtrDBf',
'enabled': 'false',
'interval': 'custom cron',
'name': 'KwgvwcaNvc',
'sync-date': '2024-03-07 01:33:04'}
Command "sync-plan create" finished with status 70
Could not create the sync plan:
Cron expression is not valid!
```
Plus one small param fix forgotten in CLI refactor.
Do not pick `custom cron` randomly from factory and …

[6.14.z] Fix flaky SyncPlans in cli_factory

---

tests/robottelo/test_dependencies.py

Internal pre-commit hook complains on this line. It assumes that we are revealing a secret.
Add a comment at the end of the line to tell the hook that it is not a secret.

Mark fake secret as "notsecret"

---

.github/workflows/prt_labels.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14093
To address this issue, we propose implementing a solution using GitHub Actions (GHA). The solution involves periodically checking the GitHub status API to monitor for new commits on the pull request. Upon detecting a new commit, the workflow will automatically remove the `PRT-Passed` and `PRT-Failed` labels from the pull request. This ensures that the labels accurately reflect …

[6.14.z] remove the PRT labels for new commits

---

.github/workflows/prt_labels.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14093
To address this issue, we propose implementing a solution using GitHub Actions (GHA). The solution involves periodically checking the GitHub status API to monitor for new commits on the pull request. Upon detecting a new commit, the workflow will automatically remove the `PRT-Passed` and `PRT-Failed` labels from the pull request. This ensures that the labels accurately reflect …

[6.13.z] remove the PRT labels for new commits

---

.github/workflows/prt_labels.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14093
To address this issue, we propose implementing a solution using GitHub Actions (GHA). The solution involves periodically checking the GitHub status API to monitor for new commits on the pull request. Upon detecting a new commit, the workflow will automatically remove the `PRT-Passed` and `PRT-Failed` labels from the pull request. This ensures that the labels accurately reflect …

[6.12.z] remove the PRT labels for new commits

---

tests/robottelo/test_dependencies.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14336
Internal pre-commit hook complains on this line. It assumes that we are revealing a secret.
Add a comment at the end of the line to tell the hook that it is not a secret.

[6.14.z] Mark fake secret as "notsecret"

---

tests/robottelo/test_dependencies.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14336
Internal pre-commit hook complains on this line. It assumes that we are revealing a secret.
Add a comment at the end of the line to tell the hook that it is not a secret.

[6.13.z] Mark fake secret as "notsecret"

---

testimony.yaml
tests/foreman/api/test_capsule.py
tests/foreman/api/test_rhc.py
tests/foreman/api/test_rhcloud_inventory.py
tests/foreman/cli/test_capsule.py
tests/foreman/cli/test_installer.py
tests/foreman/cli/test_rhcloud_inventory.py
tests/foreman/destructive/test_capsule.py
tests/foreman/destructive/test_capsule_loadbalancer.py
tests/foreman/destructive/test_installer.py
tests/foreman/destructive/test_katello_certs_check.py
tests/foreman/destructive/test_packages.py
tests/foreman/destructive/test_rename.py
tests/foreman/installer/test_installer.py
tests/foreman/maintain/test_advanced.py
tests/foreman/maintain/test_backup_restore.py
tests/foreman/maintain/test_health.py
tests/foreman/maintain/test_maintenance_mode.py
tests/foreman/maintain/test_offload_DB.py
tests/foreman/maintain/test_packages.py
tests/foreman/maintain/test_service.py
tests/foreman/maintain/test_upgrade.py
tests/foreman/sys/test_katello_certs_check.py
tests/foreman/ui/test_rhc.py
tests/foreman/ui/test_rhcloud_insights.py
tests/foreman/ui/test_rhcloud_inventory.py
tests/upgrades/test_capsule.py
tests/upgrades/test_performance_tuning.py
tests/upgrades/test_satellite_maintain.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14268
The component names are updated, split and removed in ohsnap. Collection of updated components would be broken based on those updated names as CI will have all those components in unaligned pipelines.
The docstrings and tokens for those components needs to be updated to match with the ohsnap tokens.
GitlabURL/satellite/ohsnap/-/merge_requests/1066
Please dont merge this PR until that is merged!

[6.15.z] [Component Refresh] Component Names are updated

---

testimony.yaml
tests/foreman/api/test_capsule.py
tests/foreman/api/test_rhc.py
tests/foreman/api/test_rhcloud_inventory.py
tests/foreman/cli/test_capsule.py
tests/foreman/cli/test_installer.py
tests/foreman/cli/test_rhcloud_inventory.py
tests/foreman/destructive/test_capsule.py
tests/foreman/destructive/test_capsule_loadbalancer.py
tests/foreman/destructive/test_installer.py
tests/foreman/destructive/test_katello_certs_check.py
tests/foreman/destructive/test_packages.py
tests/foreman/destructive/test_rename.py
tests/foreman/installer/test_installer.py
tests/foreman/maintain/test_advanced.py
tests/foreman/maintain/test_backup_restore.py
tests/foreman/maintain/test_health.py
tests/foreman/maintain/test_maintenance_mode.py
tests/foreman/maintain/test_offload_DB.py
tests/foreman/maintain/test_packages.py
tests/foreman/maintain/test_service.py
tests/foreman/maintain/test_upgrade.py
tests/foreman/sys/test_katello_certs_check.py
tests/foreman/ui/test_rhc.py
tests/foreman/ui/test_rhcloud_insights.py
tests/foreman/ui/test_rhcloud_inventory.py
tests/upgrades/test_capsule.py
tests/upgrades/test_performance_tuning.py
tests/upgrades/test_satellite_maintain.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14268
The component names are updated, split and removed in ohsnap. Collection of updated components would be broken based on those updated names as CI will have all those components in unaligned pipelines.
The docstrings and tokens for those components needs to be updated to match with the ohsnap tokens.
GitlabURL/satellite/ohsnap/-/merge_requests/1066
Please dont merge this PR until that is merged!

[6.13.z] [Component Refresh] Component Names are updated

---

testimony.yaml
tests/foreman/api/test_capsule.py
tests/foreman/api/test_rhc.py
tests/foreman/api/test_rhcloud_inventory.py
tests/foreman/cli/test_capsule.py
tests/foreman/cli/test_installer.py
tests/foreman/cli/test_rhcloud_inventory.py
tests/foreman/destructive/test_capsule.py
tests/foreman/destructive/test_capsule_loadbalancer.py
tests/foreman/destructive/test_installer.py
tests/foreman/destructive/test_katello_certs_check.py
tests/foreman/destructive/test_packages.py
tests/foreman/destructive/test_rename.py
tests/foreman/installer/test_installer.py
tests/foreman/maintain/test_advanced.py
tests/foreman/maintain/test_backup_restore.py
tests/foreman/maintain/test_health.py
tests/foreman/maintain/test_maintenance_mode.py
tests/foreman/maintain/test_offload_DB.py
tests/foreman/maintain/test_packages.py
tests/foreman/maintain/test_service.py
tests/foreman/maintain/test_upgrade.py
tests/foreman/sys/test_katello_certs_check.py
tests/foreman/ui/test_rhc.py
tests/foreman/ui/test_rhcloud_insights.py
tests/foreman/ui/test_rhcloud_inventory.py
tests/upgrades/test_capsule.py
tests/upgrades/test_performance_tuning.py
tests/upgrades/test_satellite_maintain.py

Automatic Cherrypick failed for https://github.com/SatelliteQE/robottelo/pull/14268 for 6.14.z branch.
Manaully cherrypicking the changes !
Closes #14357

[6.14.z][Component Refresh] Component Names are updated (#14268)

---

testimony.yaml
tests/foreman/api/test_ansible.py
tests/foreman/cli/test_ansible.py
tests/foreman/cli/test_remoteexecution.py
tests/foreman/destructive/test_ansible.py
tests/foreman/ui/test_ansible.py
tests/foreman/ui/test_jobinvocation.py
tests/foreman/ui/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14302
Ansible component name is going to be split in ohsnap into "Ansible - Configuration Management " and "Ansible - Remote Execution" components
Pytest collection of updated components would be broken based on those updated names as CI will have all those components in unaligned pipelines.
The docstrings and tokens for those components needs to be updated to match with the ohsnap tokens.
1. https://github.com/SatelliteQE/robottelo/pull/14268
2. GitlabURL/satellite/ohsnap/-/merge_requests/1066
Please dont merge this PR until that is merged!

[6.14.z] Update Ansible tests to reflect the new split Ansible components

---

conf/capsule.yaml.template
conf/dynaconf_hooks.py
conftest.py
pytest_fixtures/core/sat_cap_factory.py
pytest_plugins/capsule_n-minus.py
robottelo/exceptions.py
robottelo/hosts.py
tests/foreman/api/test_capsule.py
tests/foreman/api/test_capsulecontent.py
tests/foreman/destructive/test_registration.py

Auto Cherrypic of https://github.com/SatelliteQE/robottelo/pull/12939 failed to 6.13.z
Manual Cherrypicking !
Closes #14346

[6.13.z] Capsule N-Minus testing (#12939)

---

conf/capsule.yaml.template
conf/dynaconf_hooks.py
conftest.py
pytest_fixtures/core/sat_cap_factory.py
pytest_plugins/capsule_n-minus.py
robottelo/exceptions.py
robottelo/hosts.py

Auto Cherrypick of https://github.com/SatelliteQE/robottelo/pull/12939 failed to 6.12.z
Manual Cherrypicking !
Closes #14345

[6.12.z] Capsule N-Minus testing (#12939)

---

conf/capsule.yaml.template
conf/dynaconf_hooks.py
conftest.py
pytest_fixtures/core/sat_cap_factory.py
pytest_plugins/capsule_n-minus.py
robottelo/exceptions.py
robottelo/hosts.py
tests/foreman/api/test_capsule.py
tests/foreman/api/test_capsulecontent.py
tests/foreman/destructive/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12939
Changes include:
- A new pytest plugin for Capsule N-minus testing that would smart collect all capsule specific tests excluding few.
- New option of `--n-minus` for collecting only capsule specific tests
- tests using the caspule_factory are collected
- destructive, maintain and puppet tests are excluded since they need a separate satellite
- Introduces new setting `hostname` in capsule conf to take capsule hostname given from CI.
- **_target_capsule_host context manager now returns the cached capsule taken from CI instead of spinning of new capsule for everytime**. 
- The CI capsule is registered once/cached to CDN for RHEL contents needed by some tests at the start of the n-minus testing and would be unregistered at …

[6.14.z] Capsule N-Minus testing

---

testimony.yaml
tests/foreman/api/test_ansible.py
tests/foreman/cli/test_ansible.py
tests/foreman/cli/test_remoteexecution.py
tests/foreman/destructive/test_ansible.py
tests/foreman/ui/test_ansible.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_jobinvocation.py
tests/foreman/ui/test_remoteexecution.py

Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/14302
Fixes https://github.com/SatelliteQE/robottelo/issues/14363

[6.12.z] Update Ansible tests to reflect the new split Ansible components

---

requirements.txt

This backport resolves some missed/failed cherry-picks, bringing requirements back in line with master.
fixes #14101

[6.15.z] Updates to requirements.txt

---

requirements.txt

This backport resolves some missed/failed cherry-picks, bringing requirements back in line with master.
fixes #14102

[6.14.z] Updates to requirements.txt

---

requirements.txt

This backport resolves some missed/failed cherry-picks, bringing requirements back in line with master.
fixes #14103

[6.13.z] Updates to requirements.txt

---

requirements.txt

This backport resolves some missed/failed cherry-picks, bringing requirements back in line with master.
fixes #14104

[6.12.z] Updates to requirements.txt

---

requirements.txt

Broker dependency updated to resolve ssh2-python limitation/packagever issue

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14275

[6.15.z] Broker dependency updated to resolve ssh2-python limitation/packagever issue

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14275

[6.14.z] Broker dependency updated to resolve ssh2-python limitation/packagever issue

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14275

[6.13.z] Broker dependency updated to resolve ssh2-python limitation/packagever issue

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14275

[6.12.z] Broker dependency updated to resolve ssh2-python limitation/packagever issue

---

robottelo/utils/datafactory.py
tests/foreman/ui/test_jobinvocation.py

Close-loop bz2209968

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14379
Removing one expression causing flakiness in this test

[6.15.z] simplify time expression assertions

---

testimony.yaml
tests/foreman/api/test_ldapauthsource.py
tests/foreman/cli/test_ldapauthsource.py
tests/foreman/cli/test_sso.py
tests/foreman/destructive/test_ldap_authentication.py
tests/foreman/destructive/test_ldapauthsource.py
tests/foreman/sys/test_dynflow.py
tests/foreman/ui/test_ldap_authentication.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14380
Updated component names as needed

[6.13.z] component name changes

---

testimony.yaml
tests/foreman/api/test_ldapauthsource.py
tests/foreman/cli/test_ldapauthsource.py
tests/foreman/cli/test_sso.py
tests/foreman/destructive/test_ldap_authentication.py
tests/foreman/destructive/test_ldapauthsource.py
tests/foreman/sys/test_dynflow.py
tests/foreman/ui/test_ldap_authentication.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14380
Updated component names as needed

[6.15.z] component name changes

---

testimony.yaml
tests/foreman/api/test_ldapauthsource.py
tests/foreman/cli/test_ldapauthsource.py
tests/foreman/cli/test_sso.py
tests/foreman/destructive/test_ldap_authentication.py
tests/foreman/destructive/test_ldapauthsource.py
tests/foreman/sys/test_dynflow.py
tests/foreman/ui/test_ldap_authentication.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14380
Updated component names as needed

[6.14.z] component name changes

---

tests/foreman/api/test_subscription.py

test `test_positive_async_endpoint_for_manifest_refresh` was failing due to manifest issue inside `module_entitlement_manifest_org > upload_manifest`
Basically unable to upload manifest and return org, as per current feature we are supposed to use sca enabled organization
This PR would fix the issue
N/A

update fixture name as per expected feature

---

tests/foreman/api/test_subscription.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14375
test `test_positive_async_endpoint_for_manifest_refresh` was failing due to manifest issue inside `module_entitlement_manifest_org > upload_manifest`
Basically unable to upload manifest and return org, as per current feature we are supposed to use sca enabled organization
This PR would fix the issue
N/A

[6.15.z] update fixture name as per expected feature

---

tests/foreman/cli/test_remoteexecution.py

Katello-agent is long deprecated, though as per my discussion with team phoenix it still makes sense to test module_capsule_configured_mqtt conversion as it might be used to convert hosts re-registered from older versions.
The context is now different from the time this test was created, so I'm making some changes. Insisting on deprecated goferd running is a source of potential flakiness in the future. I also stopped using ansible rex here as it clashes with the `remote_execution_global_proxy=False` setting -- the setting takes priority as it ensures that we don't get false positive result in case of any mqtt capsule issue.

changes in test_positive_run_job_on_host_converted_to_pull_provider

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14394
Katello-agent is long deprecated, though as per my discussion with team phoenix it still makes sense to test module_capsule_configured_mqtt conversion as it might be used to convert hosts re-registered from older versions.
The context is now different from the time this test was created, so I'm making some changes. Insisting on deprecated goferd running is a source of potential flakiness in the future. I also stopped using ansible rex here as it clashes with the `remote_execution_global_proxy=False` setting -- the setting takes priority as it ensures that we don't get false positive result in case of any mqtt capsule issue.

[6.15.z] changes in test_positive_run_job_on_host_converted_to_pull_provider

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14394
Katello-agent is long deprecated, though as per my discussion with team phoenix it still makes sense to test module_capsule_configured_mqtt conversion as it might be used to convert hosts re-registered from older versions.
The context is now different from the time this test was created, so I'm making some changes. Insisting on deprecated goferd running is a source of potential flakiness in the future. I also stopped using ansible rex here as it clashes with the `remote_execution_global_proxy=False` setting -- the setting takes priority as it ensures that we don't get false positive result in case of any mqtt capsule issue.

[6.14.z] changes in test_positive_run_job_on_host_converted_to_pull_provider

---

tests/foreman/installer/test_installer.py

Removing the common assertions from fixture teardown. Current setup lead to an error in last test of a test module, when some error appeared in logs during testing.
Example:
```
test_a
...
test_n PASSED or FAILED but creates error entries in logs
...
test_z PASSED or FAILED but throws an ERROR due to error entries in logs
```

remove log check causing false negatives

---

tests/foreman/sys/test_webpack.py

Webpack 5 is now used during packaging. Test it has indeed been used.

Add test for Webpack 5 presence

---

tests/foreman/api/test_repository.py

**Regression-** In repository api tests, content was uploaded as a file named `content` (can see on web ui) but unabled to search uploaded file content using api call.
**Error-**
```
tests/foreman/api/test_repository.py:2304: in test_positive_upload_file_to_file_repo
assert filesearch[0].name == constants.RPM_TO_UPLOAD
E   IndexError: list index out of range
```
By using open context manager able to upload content and search using api call.
N/A

change a way to upload content into satellite

---

tests/foreman/api/test_capsulecontent.py

Orphan cleanup test case should be skipped for n_minus scenario but run in normal runs.
Flip the logic.

Skip orphan cleanup case for n_minus scenario

---

tests/foreman/api/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14371
Orphan cleanup test case should be skipped for n_minus scenario but run in normal runs.
Flip the logic.

[6.14.z] Skip orphan cleanup case for n_minus scenario

---

tests/foreman/api/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14371
Orphan cleanup test case should be skipped for n_minus scenario but run in normal runs.
Flip the logic.

[6.13.z] Skip orphan cleanup case for n_minus scenario

---

robottelo/host_helpers/capsule_mixins.py
tests/foreman/api/test_capsulecontent.py

4 Failures in recent runs of API::CapsuleContent, for `AssertionError`:
```
tests/foreman/api/test_capsulecontent.py:190: in test_positive_checksum_sync
module_capsule_configured.wait_for_sync()
robottelo/host_helpers/capsule_mixins.py:75: in wait_for_sync
or datetime.strptime(sync_status['last_sync_time'], '%Y-%m-%d %H:%M:%S UTC')
E   AssertionError
```
Locally I can see the `last_sync_time` format from logs as:  
```
nailgun.client - DEBUG - Received HTTP 200 response: {"last_sync_time":"2024-02-13 15:05:10 UTC", ...
```
- Split the assertions checking `last_sync_time` (check if None /Falsey first), then checking length of any in-progress sync tasks, avoiding possibly ambiguous assertion- where `last_sync_time` has not updated with a recent task, and is still an old sync time/None. 
The …

Assertion Error, time delta/format in 'wait_for_sync()', of capsule content 'last_sync_time'

---

tests/foreman/api/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14371
Orphan cleanup test case should be skipped for n_minus scenario but run in normal runs.
Flip the logic.

[6.15.z] Skip orphan cleanup case for n_minus scenario

---

pytest_plugins/markers.py
tests/foreman/conftest.py

Add posibility to filter tests that require manifester

---

tests/foreman/api/test_computeresource_libvirt.py
tests/foreman/api/test_discoveryrule.py
tests/foreman/api/test_http_proxy.py
tests/foreman/api/test_parameters.py
tests/foreman/cli/test_classparameters.py
tests/foreman/cli/test_computeresource_osp.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/cli/test_errata.py
tests/foreman/cli/test_hammer.py
tests/foreman/cli/test_satellitesync.py
tests/foreman/cli/test_subnet.py
tests/foreman/destructive/test_capsule_loadbalancer.py
tests/foreman/maintain/test_advanced.py
tests/foreman/maintain/test_health.py
tests/foreman/maintain/test_maintenance_mode.py
tests/foreman/maintain/test_packages.py
tests/foreman/ui/test_ansible.py
tests/foreman/ui/test_computeresource_gce.py
tests/foreman/ui/test_computeresource_libvirt.py
tests/upgrades/test_contentview.py
tests/upgrades/test_host.py
tests/upgrades/test_provisioningtemplate.py
tests/upgrades/test_subscription.py
tests/upgrades/test_usergroup.py

Turns out that `@request.addFinalizer` when used in test body (not in fixture) is dependent on the execution order, so basically when some assertion defined in the test before the finalizer part fails, finalizer is not added and so not executed.
This exactly happened in `test_positive_disable_hammer_defaults` in upgrades, breaking a lot of other tests in the same run. Big kudos to @lpramuk for isolating the issue there.
Moving the addFinalizer part to the start of the test, fixes the problem. Prt run won't reveal much in this case, but running the previous version of the test with induced assertion error leaves satellite with:
```
~]# hammer defaults list
----------------|------
PARAMETER       | VALUE
----------------|------
organization_id | 41   
----------------|------
```
...which …

addFinalizer in test body

---

testimony.yaml
tests/foreman/api/test_ldapauthsource.py
tests/foreman/cli/test_ldapauthsource.py
tests/foreman/cli/test_sso.py
tests/foreman/destructive/test_ldap_authentication.py
tests/foreman/destructive/test_ldapauthsource.py
tests/foreman/sys/test_dynflow.py
tests/foreman/ui/test_ldap_authentication.py

manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/14380
closes https://github.com/SatelliteQE/robottelo/issues/14390

[6.12.z] component name changes

---

tests/foreman/api/test_computeresource_libvirt.py
tests/foreman/api/test_discoveryrule.py
tests/foreman/api/test_http_proxy.py
tests/foreman/api/test_parameters.py
tests/foreman/cli/test_classparameters.py
tests/foreman/cli/test_computeresource_osp.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/cli/test_errata.py
tests/foreman/cli/test_hammer.py
tests/foreman/cli/test_satellitesync.py
tests/foreman/cli/test_subnet.py
tests/foreman/destructive/test_capsule_loadbalancer.py
tests/foreman/maintain/test_advanced.py
tests/foreman/maintain/test_health.py
tests/foreman/maintain/test_maintenance_mode.py
tests/foreman/maintain/test_packages.py
tests/foreman/ui/test_ansible.py
tests/foreman/ui/test_computeresource_gce.py
tests/foreman/ui/test_computeresource_libvirt.py
tests/upgrades/test_contentview.py
tests/upgrades/test_host.py
tests/upgrades/test_provisioningtemplate.py
tests/upgrades/test_subscription.py
tests/upgrades/test_usergroup.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14036
Turns out that `@request.addFinalizer` when used in test body (not in fixture) is dependent on the execution order, so basically when some assertion defined in the test before the finalizer part fails, finalizer is not added and so not executed.
This exactly happened in `test_positive_disable_hammer_defaults` in upgrades, breaking a lot of other tests in the same run. Big kudos to @lpramuk for isolating the issue there.
Moving the addFinalizer part to the start of the test, fixes the problem. Prt run won't reveal much in this case, but running the previous version of the test with induced assertion error leaves satellite with:
```
~]# hammer defaults list
----------------|------
PARAMETER       | VALUE …
```

[6.15.z] addFinalizer in test body

---

pytest_plugins/markers.py
tests/foreman/conftest.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14270

[6.15.z] Add posibility to filter tests that require manifester

---

pytest_plugins/markers.py
tests/foreman/conftest.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14270

[6.14.z] Add posibility to filter tests that require manifester

---

pytest_plugins/markers.py
tests/foreman/conftest.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14270

[6.13.z] Add posibility to filter tests that require manifester

---

pytest_plugins/markers.py
tests/foreman/conftest.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14270

[6.12.z] Add posibility to filter tests that require manifester

---

tests/foreman/installer/test_installer.py

cherrypick of c76295b12c3788f602c0d82277bf34d8fe10a810
backport of #14314
closes #14402

[6.14.z] remove log check causing false negatives

---

tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14314
Removing the common assertions from fixture teardown. Current setup lead to an error in last test of a test module, when some error appeared in logs during testing.
Example:
```
test_a
...
test_n PASSED or FAILED but creates error entries in logs
...
test_z PASSED or FAILED but throws an ERROR due to error entries in logs
```

[6.15.z] remove log check causing false negatives

---

tests/foreman/api/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14393
**Regression-** In repository api tests, content was uploaded as a file named `content` (can see on web ui) but unabled to search uploaded file content using api call.
**Error-**
```
tests/foreman/api/test_repository.py:2304: in test_positive_upload_file_to_file_repo
assert filesearch[0].name == constants.RPM_TO_UPLOAD
E   IndexError: list index out of range
```
By using open context manager able to upload content and search using api call.
N/A

[6.14.z] change a way to upload content into satellite

---

pytest_fixtures/component/satellite_auth.py
tests/foreman/cli/test_ldapauthsource.py

Workaround for some ext auth tests for [PR13737](https://github.com/SatelliteQE/robottelo/pull/13737) which broke CSV handling

Workaround for some ext auth tests for PR13737 which broke CSV handling

---

tests/foreman/cli/test_contentview.py

CU Case - Test cv promote shows warning of 'force promotion' for out of sequence LCE
BZ 2125728
Added automation coverage
NA

validate that cv warning to force promote

---

tests/foreman/cli/test_contentview.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14316
CU Case - Test cv promote shows warning of 'force promotion' for out of sequence LCE
BZ 2125728
Added automation coverage
NA

[6.15.z] validate that cv warning to force promote

---

tests/foreman/api/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14424
There was a bug where a non-admin user could not list particular Capsule but was able to list all Capsules, without any permissions. He should be able to list both when provided with `Reader` permissions and prevented to do so without them.
Covers [BZ#2096930](https://bugzilla.redhat.com/show_bug.cgi?id=2096930)
Test both cases in one test case.
pytest: tests/foreman/api/test_capsulecontent.py -k non_admin_user

[6.15.z] Add a test case to read Capsules via non-admin user

---

robottelo/host_helpers/capsule_mixins.py
tests/foreman/api/test_capsulecontent.py

Parent pull request: #14066 
Fixes to `capsule_mixins` method `wait_for_sync`, adjust conditionals and assertions to 
verify any recently invoked sync task(s). Record and pass a start timestamp in the tests calling this method.
- `capsule_mixins.py::118-124` ([link](https://github.com/SatelliteQE/robottelo/blob/dc2203f432979e907f0d88fb31731f03ca8d94c8/robottelo/host_helpers/capsule_mixins.py#L118)): 
After polling, when checking that the final active sync task's `end_time` is the same as capsule's `last_sync_time`, 
in 6.14.z, `capsule.content_get_sync()` does not return `['last_sync_task']` info, yields `keyError`.
I instead now save the `ended_at` time from reading the final active task by `:id`. Then assert the times match.
```
pytest: …
```

[6.14.z] Eval CapsuleContent::API Assertion Errors, time delta/format in 'wait_for_sync()'

---

pytest_fixtures/component/satellite_auth.py
tests/foreman/cli/test_ldapauthsource.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14423
Workaround for some ext auth tests for [PR13737](https://github.com/SatelliteQE/robottelo/pull/13737) which broke CSV handling

[6.15.z] Workaround for some ext auth tests for PR13737 which broke CSV handling

---

tests/foreman/api/test_discoveryrule.py

Hostgroup fixture doesn't return anything.
Fixed hostgroup fixture .

Fix module_hostgroup fixture

---

tests/foreman/api/test_computeresource_libvirt.py
tests/foreman/api/test_parameters.py
tests/foreman/cli/test_computeresource_osp.py
tests/foreman/cli/test_errata.py
tests/foreman/cli/test_hammer.py
tests/foreman/cli/test_satellitesync.py
tests/foreman/cli/test_subnet.py
tests/foreman/maintain/test_advanced.py
tests/foreman/maintain/test_health.py
tests/foreman/maintain/test_maintenance_mode.py
tests/foreman/maintain/test_packages.py
tests/foreman/ui/test_ansible.py
tests/foreman/ui/test_computeresource_gce.py
tests/foreman/ui/test_computeresource_libvirt.py
tests/upgrades/test_contentview.py
tests/upgrades/test_host.py
tests/upgrades/test_provisioningtemplate.py
tests/upgrades/test_subscription.py
tests/upgrades/test_usergroup.py

Manual cherry pick of https://github.com/SatelliteQE/robottelo/pull/14036, closes https://github.com/SatelliteQE/robottelo/issues/14419

[6.12.z] addFinalizer in test body 

---

tests/foreman/cli/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14438
There are currently uncovered two similar BZs related to ISS export/import of entities with long names:
https://bugzilla.redhat.com/show_bug.cgi?id=2124275
https://bugzilla.redhat.com/show_bug.cgi?id=2053329
This PR covers them.
pytest: tests/foreman/cli/test_satellitesync.py -k test_postive_export_import_with_long_name

[6.15.z] Add a case to export/import entities with long names

---

robottelo/host_helpers/capsule_mixins.py
tests/foreman/api/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14066
4 Failures in recent runs of API::CapsuleContent, for `AssertionError`:
```
tests/foreman/api/test_capsulecontent.py:190: in test_positive_checksum_sync
module_capsule_configured.wait_for_sync()
robottelo/host_helpers/capsule_mixins.py:75: in wait_for_sync
or datetime.strptime(sync_status['last_sync_time'], '%Y-%m-%d %H:%M:%S UTC')
E   AssertionError
```
Locally I can see the `last_sync_time` format from logs as:  
```
nailgun.client - DEBUG - Received HTTP 200 response: {"last_sync_time":"2024-02-13 15:05:10 UTC", ...
```
- Split the assertions checking `last_sync_time` (check if None /Falsey first), then checking length of any in-progress sync tasks, avoiding possibly ambiguous assertion- where `last_sync_time` has …

[6.15.z] Eval CapsuleContent::API Assertion Errors, time delta/format in 'wait_for_sync()'

---

requirements.txt

Now that Broker is back on PyPI, let's clean up the requirements

Bump Broker to 0.4.9

---

.github/workflows/auto_cherry_pick.yml

Previously, community GitHub actions were encountering issues where they persisted in identifying base issues even after they had been merged, failing to trigger issue creation as intended. Despite thorough testing, these issues persisted, prompting a reassessment of the underlying logic.
To address this recurring problem, I have implemented a custom bash script to ensure accurate behavior and resolve the persistence of identifying merged base issues. By relying on our bash script, I aim to mitigate these issues effectively. Further testing is required to validate the efficacy of this solution thoroughly. 
many cherrypicks are not getting raised : 
https://github.com/SatelliteQE/robottelo/actions/workflows/auto_cherry_pick.yml?query=is%3Afailure …

[6.13.z]-fixed the auto-cherry-picking issue cause due github action 

---

.github/workflows/prt_labels.yml

moving to use pull_request_target for prt_label.yml GHA

---

.github/workflows/prt_labels.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14467

[6.14.z] moving to use pull_request_target for prt_label.yml GHA

---

.github/workflows/prt_labels.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14467

[6.12.z] moving to use pull_request_target for prt_label.yml GHA

---

.github/workflows/prt_labels.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14467

[6.15.z] moving to use pull_request_target for prt_label.yml GHA

---

tests/foreman/api/test_host.py

i.e.
['content_view_id'] is now a separate dict
['content_view']['id']
tests/foreman/api/test_host.py::test_positive_create_and_update_with_content_view
tests/foreman/api/test_host.py::test_positive_create_inherit_lce_cv
tests are failing for foreman 3.9 (6.15.z) because `*_id` keys are not found
access `id` as key from parent dict

Fix content_facet_attributes attributes

---

.github/workflows/prt_labels.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14467

[6.13.z] moving to use pull_request_target for prt_label.yml GHA

---

tests/foreman/destructive/test_ansible.py

Missing upgrade marker on ansible destructive tests which run installer, suggested by SD in audit
Add upgrade marker on ansible destructive tests to run these in upgrade job

Add upgrade marker on ansible destructive tests

---

tests/foreman/ui/test_eol_banner.py

manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/13211 
The feature is awaited in downstream build, prt run should verify bz 2266113

[6.14] eol banner

---

tests/foreman/api/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14224
i.e.
['content_view_id'] is now a separate dict
['content_view']['id']
tests/foreman/api/test_host.py::test_positive_create_and_update_with_content_view
tests/foreman/api/test_host.py::test_positive_create_inherit_lce_cv
tests are failing for foreman 3.9 (6.15.z) because `*_id` keys are not found
access `id` as key from parent dict

[6.15.z] Fix content_facet_attributes attributes

---

tests/foreman/destructive/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14488
Missing upgrade marker on ansible destructive tests which run installer, suggested by SD in audit
Add upgrade marker on ansible destructive tests to run these in upgrade job

[6.15.z] Add upgrade marker on ansible destructive tests

---

tests/foreman/destructive/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14488
Missing upgrade marker on ansible destructive tests which run installer, suggested by SD in audit
Add upgrade marker on ansible destructive tests to run these in upgrade job

[6.14.z] Add upgrade marker on ansible destructive tests

---

robottelo/constants/__init__.py
tests/foreman/ui/test_computeresource_vmware.py

Modifying the VMware compute profile test by making it end-to-end and removing redundant test as a part of Component Audit

Modify VMware compute profile test

---

robottelo/constants/__init__.py
tests/foreman/ui/test_computeresource_vmware.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14202
Modifying the VMware compute profile test by making it end-to-end and removing redundant test as a part of Component Audit

[6.14.z] Modify VMware compute profile test

---

robottelo/constants/__init__.py
tests/foreman/ui/test_computeresource_vmware.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14202
Modifying the VMware compute profile test by making it end-to-end and removing redundant test as a part of Component Audit

[6.15.z] Modify VMware compute profile test

---

tests/upgrades/test_virtwho.py

when the virt-who upgrade tests failed for some issues, delete virt-who config will failed, then rerun the upgrade testing, it will create another virt-who config in other org, but when list or check info the config, it will list the first virt-who config.
Use auto name to fix it.
```
(robottelo_vv_615) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade --disable-pytest-warnings -q
1 passed, 1 deselected, 20 warnings in 188.91s (0:03:08)
(robottelo_vv_615) [root@dell-per740-68-vm-05 robottelo]# …
```

virt-who config upgrade duplicate config issue fix

---

tests/upgrades/test_virtwho.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14378
when the virt-who upgrade tests failed for some issues, delete virt-who config will failed, then rerun the upgrade testing, it will create another virt-who config in other org, but when list or check info the config, it will list the first virt-who config.
Use auto name to fix it.
```
(robottelo_vv_615) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade --disable-pytest-warnings -q
1 passed, 1 deselected, 20 warnings in 188.91s …
```

[6.14.z] virt-who config upgrade duplicate config issue fix

---

tests/upgrades/test_virtwho.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14378
when the virt-who upgrade tests failed for some issues, delete virt-who config will failed, then rerun the upgrade testing, it will create another virt-who config in other org, but when list or check info the config, it will list the first virt-who config.
Use auto name to fix it.
```
(robottelo_vv_615) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade --disable-pytest-warnings -q
1 passed, 1 deselected, 20 warnings in 188.91s …
```

[6.15.z] virt-who config upgrade duplicate config issue fix

---

tests/foreman/api/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14393
**Regression-** In repository api tests, content was uploaded as a file named `content` (can see on web ui) but unabled to search uploaded file content using api call.
**Error-**
```
tests/foreman/api/test_repository.py:2304: in test_positive_upload_file_to_file_repo
assert filesearch[0].name == constants.RPM_TO_UPLOAD
E   IndexError: list index out of range
```
By using open context manager able to upload content and search using api call.
N/A

[6.15.z] change a way to upload content into satellite

---

pytest_fixtures/core/contenthosts.py
pytest_plugins/fixture_markers.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_jobinvocation.py
tests/foreman/ui/test_remoteexecution.py

SAT-20041
Some endeavor tests were failing. 
Investigation and finding fixes were needed.
I fixed those issues, via refactoring, refreshing fixtures used in the test, or via some airgun changes.
`test_rex_new_ui` moved and renamed  from test_hosts to test_jobinvocation after discussion with @pondrejk .
Needs: https://github.com/SatelliteQE/airgun/pull/1295

Test fixes for the Endeavour team

---

pytest_fixtures/core/contenthosts.py
pytest_plugins/fixture_markers.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_jobinvocation.py
tests/foreman/ui/test_remoteexecution.py

Cherrypick of https://github.com/SatelliteQE/robottelo/pull/14512

[6.14.z] Cherrypick of FixesForEndeavour

---

requirements.txt
robottelo/hosts.py
tests/foreman/api/test_capsulecontent.py

A test case (and nailgun support) to trigger the Reclaim space task was missing. Also a BZ complained about wrong endpoint being referenced in apidoc.
This PR adds one.
pytest: tests/foreman/api/test_capsulecontent.py -k 'reclaim_space'
nailgun: 1111

Add test case to trigger the reclaim_space task

---

requirements.txt
robottelo/hosts.py
tests/foreman/api/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14397
A test case (and nailgun support) to trigger the Reclaim space task was missing. Also a BZ complained about wrong endpoint being referenced in apidoc.
This PR adds one.
pytest: tests/foreman/api/test_capsulecontent.py -k 'reclaim_space'
nailgun: 1111

[6.15.z] Add test case to trigger the reclaim_space task

---

tests/foreman/endtoend/test_cli_endtoend.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14536
creating a separate pr from https://github.com/SatelliteQE/robottelo/pull/13999 as master needs additional work

[6.14.z] [6.15] cli e2e fix

---

requirements.txt

Need to solve https://github.com/SatelliteQE/robottelo/issues/14331
This PR will solve that.  
https://github.com/SatelliteQE/robottelo/issues/14331

[6.14.z] Bump pytest from 8.1.0 to 8.1.1 

---

requirements.txt

Need to solve https://github.com/SatelliteQE/robottelo/issues/14328
This PR will solve that.  
https://github.com/SatelliteQE/robottelo/issues/14328

[6.13.z] Bump pytest from 8.1.0 to 8.1.1

---

requirements.txt

Need to solve https://github.com/SatelliteQE/robottelo/issues/14329
This PR will solve that.  
https://github.com/SatelliteQE/robottelo/issues/14329

[6.12.z] Bump pytest from 8.1.0 to 8.1.1

---

tests/foreman/api/test_ansible.py

Missing coverage for BZ:2187967, which verifies ansible roles inheritance functionality for host with parent/nested hostgroup
Add a end-to-end test to cover this customer scenario from BZ:2187967

Add test coverage for BZ:2187967

---

pytest_fixtures/component/http_proxy.py
robottelo/hosts.py
tests/foreman/ui/test_http_proxy.py

We are missing coverage for a [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1844840) where the HTTP proxy is created with a user containing special characters in his password.
Not only we need to create the proxy at the Satellite side, we also need to create the user at the proxy side to verify the content operations actually work. In the end I decided to create such users dynamically during the test run, so I needed to add a new `ProxyHost` class with a few functions to handle that. The class is instantiated in a session-scoped fixture and used in test and other fixture.
pytest: tests/foreman/ui/test_http_proxy.py -k special

Add case for special chars in HTTP proxy password

---

robottelo/utils/virtwho.py

when the network is poor, it will not enough time to get the correct message and mapping info. so extend the timeout

extend the timeout for poor network

---

robottelo/utils/virtwho.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14573
when the network is poor, it will not enough time to get the correct message and mapping info. so extend the timeout

[6.13.z] extend the timeout for poor network

---

robottelo/utils/virtwho.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14573
when the network is poor, it will not enough time to get the correct message and mapping info. so extend the timeout

[6.15.z] extend the timeout for poor network

---

robottelo/utils/virtwho.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14573
when the network is poor, it will not enough time to get the correct message and mapping info. so extend the timeout

[6.14.z] extend the timeout for poor network

---

robottelo/constants/__init__.py

`capsule_setup` requires a constant defined for RHEL9 that was missing. See https://github.com/SatelliteQE/robottelo/blob/64815689ecffae197b099099338324bc56931fc5/robottelo/hosts.py#L1638.
Add RHEL9 constant

Add ohsnap repos for rhel9

---

tests/foreman/api/test_rhc.py
tests/foreman/api/test_rhcloud_inventory.py
tests/foreman/cli/test_rhcloud_inventory.py
tests/foreman/ui/test_rhc.py
tests/foreman/ui/test_rhcloud_insights.py
tests/foreman/ui/test_rhcloud_inventory.py

Move RHCloud tests to team Phoenix-subscriptions

---

tests/foreman/api/test_rhc.py
tests/foreman/api/test_rhcloud_inventory.py
tests/foreman/cli/test_rhcloud_inventory.py
tests/foreman/ui/test_rhc.py
tests/foreman/ui/test_rhcloud_insights.py
tests/foreman/ui/test_rhcloud_inventory.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14567

[6.13.z] Move RHCloud tests to team Phoenix-subscriptions

---

tests/foreman/api/test_rhc.py
tests/foreman/api/test_rhcloud_inventory.py
tests/foreman/cli/test_rhcloud_inventory.py
tests/foreman/ui/test_rhc.py
tests/foreman/ui/test_rhcloud_insights.py
tests/foreman/ui/test_rhcloud_inventory.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14567

[6.14.z] Move RHCloud tests to team Phoenix-subscriptions

---

tests/foreman/api/test_rhc.py
tests/foreman/api/test_rhcloud_inventory.py
tests/foreman/cli/test_rhcloud_inventory.py
tests/foreman/ui/test_rhc.py
tests/foreman/ui/test_rhcloud_insights.py
tests/foreman/ui/test_rhcloud_inventory.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14567

[6.12.z] Move RHCloud tests to team Phoenix-subscriptions

---

tests/foreman/api/test_rhc.py
tests/foreman/api/test_rhcloud_inventory.py
tests/foreman/cli/test_rhcloud_inventory.py
tests/foreman/ui/test_rhc.py
tests/foreman/ui/test_rhcloud_insights.py
tests/foreman/ui/test_rhcloud_inventory.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14567

[6.15.z] Move RHCloud tests to team Phoenix-subscriptions

---

tests/foreman/api/test_subnet.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14143
Update in parameter name and value from subnet component updates 
the parameter in host inheriting that subnet
Updated changes in subnet name & value reflects in host inheriting that subnet

[6.14.z] host name & value updated with subnet

---

tests/foreman/api/test_subnet.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14143
Update in parameter name and value from subnet component updates 
the parameter in host inheriting that subnet
Updated changes in subnet name & value reflects in host inheriting that subnet

[6.15.z] host name & value updated with subnet

---

.github/workflows/pull_request.yml
.github/workflows/weekly.yml
robottelo/cli/base.py
robottelo/cli/subscription.py
tests/robottelo/test_cli.py
tests/robottelo/test_cli_method_calls.py

Code Checks for Python 3.12 were missing from zStream branches.
Adding python 3.12 into Pull Request checks.

zStream Checks for Python 3.12

---

tests/foreman/ui/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14520
- `test_positive_show_count_on_host_pages`: Update setup to use newer `registered_contenthost` fixture. 
Adjust assertions, check New Host UI > Errata tab counts, expand docstrings.
- `test_host_content_errata_tab_pagination` (Ln ~658): Remove assertions checking `pagination per_page_value`, after installing some errata. The page reloads a few seconds after install task finishes, and `per_page_value` is reset to 20 (default), failing the check.
```
pytest: tests/foreman/ui/test_errata.py -k 'test_positive_show_count_on_host_pages or test_host_content_errata_tab_pagination'
```

[6.15.z] ErrataManagement UI: Update show_count, and errata_tab_pagination cases

---

pytest_fixtures/component/http_proxy.py
robottelo/host_helpers/api_factory.py
robottelo/hosts.py
tests/foreman/ui/test_http_proxy.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14538
We are missing coverage for a [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1844840) where the HTTP proxy is created with a user containing special characters in his password.
Not only we need to create the proxy at the Satellite side, we also need to create the user at the proxy side to verify the content operations actually work. In the end I decided to create such users dynamically during the test run, so I needed to add a new `ProxyHost` class with a few functions to handle that. The class is instantiated in a session-scoped fixture and used in test and other fixture.
pytest: tests/foreman/ui/test_http_proxy.py -k special

[6.14.z] Add case for special chars in HTTP proxy password

---

tests/foreman/maintain/test_service.py

After turning off the foreman service, the `check-tftp-storage` requires the user to input the admin password since the foreman service isn't running. This causes the command to time out while waiting for input.
Let's whitelist the tftp storage check since it's not necessary for the test.

Fix foreman service test

---

.github/workflows/pull_request.yml
.github/workflows/weekly.yml
robottelo/cli/base.py
robottelo/cli/subscription.py
tests/robottelo/test_cli.py
tests/robottelo/test_cli_method_calls.py

Failed Cherrypick of https://github.com/SatelliteQE/robottelo/pull/14558 to 6.14.z
Closes #14589

[6.14.z] zStream Checks for Python 3.12 (#14558)

---

tests/foreman/maintain/test_service.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14583
After turning off the foreman service, the `check-tftp-storage` requires the user to input the admin password since the foreman service isn't running. This causes the command to time out while waiting for input.
Let's whitelist the tftp storage check since it's not necessary for the test.

[6.14.z] Fix foreman service test

---

tests/foreman/maintain/test_service.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14583
After turning off the foreman service, the `check-tftp-storage` requires the user to input the admin password since the foreman service isn't running. This causes the command to time out while waiting for input.
Let's whitelist the tftp storage check since it's not necessary for the test.

[6.15.z] Fix foreman service test

---

.github/workflows/pull_request.yml
.github/workflows/weekly.yml
robottelo/cli/base.py
robottelo/cli/subscription.py
tests/robottelo/test_cli.py
tests/robottelo/test_cli_method_calls.py

Failed Cherrypick of https://github.com/SatelliteQE/robottelo/pull/14558 to 6.13.z
Closes #14587

[6.13.z] zStream Checks for Python 3.12 (#14558)

---

tests/foreman/maintain/test_service.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14583
After turning off the foreman service, the `check-tftp-storage` requires the user to input the admin password since the foreman service isn't running. This causes the command to time out while waiting for input.
Let's whitelist the tftp storage check since it's not necessary for the test.

[6.13.z] Fix foreman service test

---

.github/workflows/pull_request.yml
.github/workflows/weekly.yml
robottelo/cli/base.py
robottelo/cli/subscription.py
tests/robottelo/test_cli.py
tests/robottelo/test_cli_method_calls.py

Failed Cherrypick of https://github.com/SatelliteQE/robottelo/pull/14558 to 6.12.z
Closes #14588

[6.12.z] zStream Checks for Python 3.12 (#14558)

---

tests/foreman/cli/test_ansible.py
tests/foreman/cli/test_remoteexecution.py

Ansible-RemoteExecution tests present in REX module under TestAnsibleREX class in CLI 
- Move Ansible-RemoteExecution tests present in REX module to Ansible Module in TestAnsibleREX class, to track this tests in correct component module
- Move Ansible-ConfigurationManagement tests present in Ansible to module to new TestAnsibleCfgMgmt class for consistency in CLI test module.
- And few other minor fixes.

Move TestAnsibleREX CLI tests to Ansible module
