SatelliteQE/robottelo

- tests/foreman/api/test_repository.py
for katello >= 4.4  (should be part of 6.15.z) docker supports on demand policy
https://github.com/Katello/katello/commit/d2c20af6911adb02ca9005350a9f2c1ad1f8140b
add exception for docker repos
tests/foreman/api/test_repository.py::TestRepository::test_negative_create_non_yum_with_download_policy
> Docker repos now support on demand policy

- tests/foreman/api/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14608
for katello >= 4.4  (should be part of 6.15.z) docker supports on demand policy
https://github.com/Katello/katello/commit/d2c20af6911adb02ca9005350a9f2c1ad1f8140b
add exception for docker repos
tests/foreman/api/test_repository.py::TestRepository::test_negative_create_non_yum_with_download_policy
> [6.15.z] Docker repos now support on demand policy

- pytest_fixtures/core/contenthosts.py
- pytest_plugins/fixture_markers.py
- tests/foreman/destructive/test_capsule_loadbalancer.py
- tests/foreman/maintain/test_upgrade.py
PIT isn't running some of Platform's tests because they are hard coded to older rhel versions (7 or 8). 
Update tests to be future-proof and run on whatever the test suite decides (ie: use settings file).
> Update Platform tests that have hard coded content host versions

- pytest_fixtures/core/contenthosts.py
- pytest_plugins/fixture_markers.py
- tests/foreman/destructive/test_capsule_loadbalancer.py
- tests/foreman/maintain/test_upgrade.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14317
PIT isn't running some of Platform's tests because they are hard coded to older rhel versions (7 or 8). 
Update tests to be future-proof and run on whatever the test suite decides (ie: use settings file).
> [6.14.z] Update Platform tests that have hard coded content host versions

- tests/foreman/api/test_errata.py
Setup for contenthost of `api::test_errata_installation_with_swidtags` uses some outdated repositories and makes use of deprecated method `repo_collection.setup_virtual_machine()`. Has failed in most recent automation runs for 6.15, 6.14.3
Setup host with global registration to published CV and AK, with synced repos containing prereqs and module stream with swidtag attached, promoted CVV with all content. Also using SCA-only org fixture
- Failing contenthost setup or prereq install commands in recent 6.15 and 6.14 CI.
- ~these fixes have been included in an open CP for `API::Errata-Management` , which is not merged due to this failing test.~ This is now merged into 6.14.z (#13832) 
^ We should CP to 6.14.z still, because review comments have brought enhancements to these fixes.
``` …
```
> Errata with swidtags setup and modular update

- tests/foreman/api/test_errata.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14494
Setup for contenthost of `api::test_errata_installation_with_swidtags` uses some outdated repositories and makes use of deprecated method `repo_collection.setup_virtual_machine()`. Has failed in most recent automation runs for 6.15, 6.14.3
Setup host with global registration to published CV and AK, with synced repos containing prereqs and module stream with swidtag attached, promoted CVV with all content. Also using SCA-only org fixture
- Failing contenthost setup or prereq install commands in recent 6.15 and 6.14 CI.
- ~these fixes have been included in an open CP for `API::Errata-Management` , which is not merged due to this failing test.~ This is now merged into 6.14.z (#13832) 
^ We should CP to 6.14.z still, …
> [6.15.z] Errata with swidtags setup and modular update

- tests/foreman/cli/test_ansible.py
- tests/foreman/cli/test_remoteexecution.py
(cherry picked from commit 9687508361e085b41c512128b3f3183fc26f1249)
Not sure why cherrypick action didn't ran for https://github.com/SatelliteQE/robottelo/pull/14577
Manually cherrypicking  https://github.com/SatelliteQE/robottelo/pull/14577
> [6.15.z] Move TestAnsibleREX CLI tests to Ansible module

- tests/foreman/ui/test_ansible.py
We are missing scenario for creating and adding variable to the host.
Automated BZ: 2170727
Added the scenario
> Verify a variable created and added to the host

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14477
We are missing scenario for creating and adding variable to the host.
Automated BZ: 2170727
Added the scenario
> [6.15.z] Verify a variable created and added to the host

- tests/foreman/cli/test_errata.py
cc automation coverage
https://bugzilla.redhat.com/show_bug.cgi?id=2249736
`"Actions::Katello::Applicability::Hosts::BulkGenerate"` tasks are processed in the default queue instead of hosts_queue causing congestion.
As per verification steps, we are looking into (`systemctl` or `journalctl` log or `/var/log/messages`) and conclude that `worker-hosts-queue-1.service` proceed when errata recalculate command runs.
N/A
> cu-case-verify-worker-hosts-queue-1-service-has-proceed

- tests/foreman/cli/test_errata.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14621
cc automation coverage
https://bugzilla.redhat.com/show_bug.cgi?id=2249736
`"Actions::Katello::Applicability::Hosts::BulkGenerate"` tasks are processed in the default queue instead of hosts_queue causing congestion.
As per verification steps, we are looking into (`systemctl` or `journalctl` log or `/var/log/messages`) and conclude that `worker-hosts-queue-1.service` proceed when errata recalculate command runs.
N/A
> [6.15.z] cu-case-verify-worker-hosts-queue-1-service-has-proceed

- tests/foreman/api/test_ansible.py
Ansible tests are mixed in API ansible module, which need to be consistent as CLI/UI module
Move Ansible API tests to Ansible-ConfigurationManagement and Ansible-RemoteExecution classes, And few other minor fixes.
> Move ansible API tests to Ansible-Cfgmgmt and REX classes

- tests/foreman/api/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14626
Ansible tests are mixed in API ansible module, which need to be consistent as CLI/UI module
Move Ansible API tests to Ansible-ConfigurationManagement and Ansible-RemoteExecution classes, And few other minor fixes.
> [6.14.z] Move ansible API tests to Ansible-Cfgmgmt and REX classes

- tests/foreman/api/test_repository.py
> Make test parametrization more readable

- tests/foreman/api/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14569
[yum] [docker]
vs
[2] [1]
> [6.15.z] Make test parametrization more readable

- pytest_fixtures/component/activationkey.py
- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14477
We are missing scenario for creating and adding variable to the host.
Automated BZ: 2170727
Added the scenario
> [6.13.z] Verify a variable created and added to the host

- pytest_fixtures/component/activationkey.py
- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14477
We are missing scenario for creating and adding variable to the host.
Automated BZ: 2170727
Added the scenario
> [6.14.z] Verify a variable created and added to the host

- tests/foreman/api/test_registration.py
Manual cherrypick of  https://github.com/SatelliteQE/robottelo/pull/13583
> [6.13.z] Test capsule without registration module

- robottelo/constants/__init__.py
- tests/foreman/api/test_bookmarks.py
- tests/foreman/ui/test_bookmarks.py
- tests/upgrades/test_bookmarks.py
Let's face it, running 730 tests on a component like this didn't bring us that much value. I'd say we don't need to parametrize with everything that exists.
This pr attemps on a representative selection (old ui, new ui, required setup, session name vs controller mismatch) taking entity traffic into consideration
> bookmark entities reduced parametrization

- tests/foreman/endtoend/test_cli_endtoend.py
e2e failing with key error
updating the assert
> cli e2e fix

- tests/foreman/api/test_notifications.py
This new test verifies that endpoint `/notification_recipients` works and returns correct data structure.
It covers bug https://bugzilla.redhat.com/2249970 where this broken endpoint caused some web UI pages to fail to load.
> notifications: new test for notification_recipients endpoint

- robottelo/constants/__init__.py
- tests/foreman/api/test_bookmarks.py
- tests/foreman/ui/test_bookmarks.py
- tests/upgrades/test_bookmarks.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14542
Let's face it, running 730 tests on a component like this didn't bring us that much value. I'd say we don't need to parametrize with everything that exists.
This pr attemps on a representative selection (old ui, new ui, required setup, session name vs controller mismatch) taking entity traffic into consideration
> [6.15.z] bookmark entities reduced parametrization

- conf/oscap.yaml.template
- pytest_fixtures/component/oscap.py
- robottelo/config/validators.py
> Make oscap profile configurable in settings file

- robottelo/constants/__init__.py
- tests/foreman/api/test_bookmarks.py
- tests/foreman/ui/test_bookmarks.py
- tests/upgrades/test_bookmarks.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14542
Let's face it, running 730 tests on a component like this didn't bring us that much value. I'd say we don't need to parametrize with everything that exists.
This pr attemps on a representative selection (old ui, new ui, required setup, session name vs controller mismatch) taking entity traffic into consideration
> [6.13.z] bookmark entities reduced parametrization

- tests/foreman/ui/test_http_proxy.py
Just two fixes and one extension to address the component eval goals.
pytest: tests/foreman/ui/test_http_proxy.py
airgun: 1311
> HTTP Proxy UI fixes

- conf/oscap.yaml.template
- pytest_fixtures/component/oscap.py
- robottelo/config/validators.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14535
> [6.15.z] Make oscap profile configurable in settings file

- conf/oscap.yaml.template
- pytest_fixtures/component/oscap.py
- robottelo/config/validators.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14535
> [6.14.z] Make oscap profile configurable in settings file

- conf/oscap.yaml.template
- pytest_fixtures/component/oscap.py
- robottelo/config/validators.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14535
> [6.13.z] Make oscap profile configurable in settings file

- conf/oscap.yaml.template
- pytest_fixtures/component/oscap.py
- robottelo/config/validators.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14535
> [6.12.z] Make oscap profile configurable in settings file

- tests/foreman/api/test_registration.py
- tests/foreman/cli/test_logging.py
Satellite is in SCA mode by default with 6.16. Few tests are not adhering SCA-compliance.
Updated the tests for Logging and Registration Component
> Make tests SCA-Compliant

- pytest_plugins/markers.py
- tests/foreman/conftest.py
> Add filter for ldap related tests

- tests/foreman/api/test_notifications.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14592
This new test verifies that endpoint `/notification_recipients` works and returns correct data structure.
It covers bug https://bugzilla.redhat.com/2249970 where this broken endpoint caused some web UI pages to fail to load.
> [6.15.z] notifications: new test for notification_recipients endpoint

- pytest_plugins/markers.py
- tests/foreman/conftest.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14540
> [6.12.z] Add filter for ldap related tests

- tests/foreman/ui/test_remoteexecution.py
(cherry picked from commit 41a3949007928b8b9365eda469550d875bb56d50)
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/14550
test_positive_matcher_field_highlight & test_positive_roles_import_in_background is being removed, as part of component audit
> [6.12.z] Remove test_positive_matcher_field_highlight

- tests/foreman/ui/test_remoteexecution.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/14550
test_positive_matcher_field_highlight & test_positive_roles_import_in_background is being removed, as part of component audit
> [6.13.z] Remove test_positive_matcher_field_highlight

- tests/foreman/ui/test_remoteexecution.py
(cherry picked from commit 8c2a4c6acecc379e9ddbf196d36f5c86d622c738)
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/14550
test_positive_matcher_field_highlight & test_positive_roles_import_in_background is being removed, as part of component audit
> [6.14.z] Remove test_positive_matcher_field_highlight

- tests/foreman/ui/test_remoteexecution.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/14550
test_positive_matcher_field_highlight & test_positive_roles_import_in_background is being removed, as part of component audit
> [6.15.z] Remove test_positive_matcher_field_highlight

- pytest_plugins/markers.py
- tests/foreman/conftest.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14540
> [6.15.z] Add filter for ldap related tests

- pytest_plugins/markers.py
- tests/foreman/conftest.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14540
> [6.13.z] Add filter for ldap related tests

- .pre-commit-config.yaml
ruff-pre-commit v0.0.277 is almost 1year old and I experienced some sort of module imports re-order hell with this version.
Safely bump ruff-pre-commit to < 0.3.1 (no breaking changes)
> Safely bump ruff-pre-commit to v0.3.0

- .pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14692
ruff-pre-commit v0.0.277 is almost 1year old and I experienced some sort of module imports re-order hell with this version.
Safely bump ruff-pre-commit to < 0.3.1 (no breaking changes)
> [6.15.z] Safely bump ruff-pre-commit to v0.3.0

- tests/foreman/api/test_notifications.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14592
Fixes issue: https://github.com/SatelliteQE/robottelo/issues/14662
This new test verifies that endpoint /notification_recipients works and returns correct data structure.
It covers bug https://bugzilla.redhat.com/2249970 where this broken endpoint caused some web UI pages to fail to load.
> [6.14.z] notifications: new test for notification_recipients endpoint

- tests/foreman/api/test_notifications.py
Users with disabled account or disabled email were still receiving notifications about long-running tasks.
New test that verifies that these users don't receive the notification.
Bugzilla: https://bugzilla.redhat.com/2245056
> notifications: no long tasks email for certain users

- tests/foreman/cli/test_bootdisk.py
If first test for rhel7 fails, rhel8 and rhel9 fails as well with error as media path is already taken
Use request.addfinalizer for teardown to delete media and hosts in bootdisk tests
> Fix teardown of bootdisk tests with request.addfinalizer

- .pre-commit-config.yaml
Cherrypicks https://github.com/SatelliteQE/robottelo/pull/14692
(cherry picked from commit 590e1758f9cc6f8100277e49d9d7345904c0442c)
https://github.com/SatelliteQE/robottelo/issues/14695
> [6.13.z] Safely bump ruff-pre-commit to v0.3.0

- tests/foreman/cli/test_bootdisk.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14701
If first test for rhel7 fails, rhel8 and rhel9 fails as well with error as media path is already taken
Use request.addfinalizer for teardown to delete media and hosts in bootdisk tests
> [6.15.z] Fix teardown of bootdisk tests with request.addfinalizer

- tests/foreman/cli/test_bootdisk.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14701
If first test for rhel7 fails, rhel8 and rhel9 fails as well with error as media path is already taken
Use request.addfinalizer for teardown to delete media and hosts in bootdisk tests
> [6.13.z] Fix teardown of bootdisk tests with request.addfinalizer

- tests/foreman/cli/test_bootdisk.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14701
If first test for rhel7 fails, rhel8 and rhel9 fails as well with error as media path is already taken
Use request.addfinalizer for teardown to delete media and hosts in bootdisk tests
> [6.14.z] Fix teardown of bootdisk tests with request.addfinalizer

- .pre-commit-config.yaml
Cherrypicks https://github.com/SatelliteQE/robottelo/pull/14692
(cherry picked from commit 590e1758f9cc6f8100277e49d9d7345904c0442c)
Fixes https://github.com/SatelliteQE/robottelo/issues/14696
> [6.14.z] Safely bump ruff-pre-commit to v0.3.0

- robottelo/hosts.py
- tests/foreman/api/test_capsule.py
`Capsule.install()` fails with ` TypeError: 'NoneType' object is not iterable` when used w/o kwargs
Some contributors already introduced misplaced workaround for this `Capsule.run_installer_arg()`
Fix `Capsule.install()` instead of implementing yet another installer method `Capsule.run_installer_arg()`
> Fix Capsule.install when used w/o kwargs

- robottelo/hosts.py
- tests/foreman/api/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14693
`Capsule.install()` fails with ` TypeError: 'NoneType' object is not iterable` when used w/o kwargs
Some contributors already introduced misplaced workaround for this `Capsule.run_installer_arg()`
Fix `Capsule.install()` instead of implementing yet another installer method `Capsule.run_installer_arg()`
> [6.14.z] Fix Capsule.install when used w/o kwargs

- robottelo/hosts.py
- tests/foreman/api/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14693
`Capsule.install()` fails with ` TypeError: 'NoneType' object is not iterable` when used w/o kwargs
Some contributors already introduced misplaced workaround for this `Capsule.run_installer_arg()`
Fix `Capsule.install()` instead of implementing yet another installer method `Capsule.run_installer_arg()`
> [6.13.z] Fix Capsule.install when used w/o kwargs

- .github/workflows/pull_request.yml
- .pre-commit-config.yaml
pre-commit.ci [is enabled](https://results.pre-commit.ci/repo/github/4000279) for robottelo repository, the GH Action that runs pre-commit is now redundant.
Remove the pre-commit GitHub Action from our CI/CQ workflow. Also [disable PR autofix](https://pre-commit.ci/#configuration-autofix_prs) if pre-commit auto fixes files.
> Remove pre-commit GitHub Action from our CI/CQ

- .github/workflows/pull_request.yml
- .pre-commit-config.yaml
(cherry picked from commit 4f5c857c73f5815d83f178f1f18a28bcce8de60d)
This PR backports #14717
> [6.15.z] Remove pre-commit GitHub Action from our CI/CQ (#14717)

- .github/workflows/pull_request.yml
- .pre-commit-config.yaml
(cherry picked from commit 4f5c857c73f5815d83f178f1f18a28bcce8de60d)
This PR backports #14717
> [6.14.z] Remove pre-commit GitHub Action from our CI/CQ (#14717)

- .github/workflows/pull_request.yml
- .pre-commit-config.yaml
(cherry picked from commit 4f5c857c73f5815d83f178f1f18a28bcce8de60d)
This PR backports #14717
> [6.13.z] Remove pre-commit GitHub Action from our CI/CQ (#14717)

- pytest_fixtures/core/sat_cap_factory.py
- tests/foreman/installer/test_installer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14658
Adding coverage of BZ#2245081 ansible callback on capsule that was delivered in `6.15.0`
Merge #14692 and #14693 first please
SAT-24477
> [6.15.z] Coverage of BZ#2245081 ansible callback on capsule

- pytest_fixtures/component/activationkey.py
- tests/foreman/ui/test_registration.py
The test cases for registration component are failing and it is moved from ui/test_host.py in [PR](https://github.com/SatelliteQE/robottelo/pull/13450)
Addressed all the test failures in this PR.
> Test failures fixes for ui/test_registration.py

- pytest_fixtures/component/activationkey.py
- tests/foreman/ui/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14001
The test cases for registration component are failing and it is moved from ui/test_host.py in [PR](https://github.com/SatelliteQE/robottelo/pull/13450)
Addressed all the test failures in this PR.
> [6.15.z] Test failures fixes for ui/test_registration.py

- pytest_fixtures/core/sat_cap_factory.py
- robottelo/hosts.py
- tests/foreman/destructive/test_clone.py
- tests/foreman/installer/test_installer.py
- tests/foreman/sys/test_katello_certs_check.py
- Robottelo tests that enable satellite/capsule modules are failing on RHEL9. We're not using modules for RHEL9 atm but this may change in the future. 
- Don't try to enable satellite/capsule modules on RHEL9
- SAT-24336
> Fix tests failing on enabling satellite/capsule module

- .github/workflows/prt_labels.yml
When a PRT runs on a PR, it adds a PRT-Passed or PRT-Failed label to it. When we push a new commit to the PR, the labels are removed and the PR looks all green even if the PRT failed earlier.
Updated the workflow to only remove the PRT-label on new commit to the PR if the PRT was passed in previous run, and keep it as it is otherwise.
> Update PRT Label Remove

- .github/workflows/prt_labels.yml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14707
When a PRT runs on a PR, it adds a PRT-Passed or PRT-Failed label to it. When we push a new commit to the PR, the labels are removed and the PR looks all green even if the PRT failed earlier.
Updated the workflow to only remove the PRT-label on new commit to the PR if the PRT was passed in previous run, and keep it as it is otherwise.
> [6.15.z] Update PRT Label Remove

- .github/workflows/prt_labels.yml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14707
When a PRT runs on a PR, it adds a PRT-Passed or PRT-Failed label to it. When we push a new commit to the PR, the labels are removed and the PR looks all green even if the PRT failed earlier.
Updated the workflow to only remove the PRT-label on new commit to the PR if the PRT was passed in previous run, and keep it as it is otherwise.
> [6.14.z] Update PRT Label Remove

- .github/workflows/prt_labels.yml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14707
When a PRT runs on a PR, it adds a PRT-Passed or PRT-Failed label to it. When we push a new commit to the PR, the labels are removed and the PR looks all green even if the PRT failed earlier.
Updated the workflow to only remove the PRT-label on new commit to the PR if the PRT was passed in previous run, and keep it as it is otherwise.
> [6.12.z] Update PRT Label Remove

- tests/foreman/cli/test_repository.py
Component Audit: SAT-23364
Test `test_positive_accessible_content_status` were using deprecated consumer CA cert RPM, 
change content host registration method to global registration template/method
No
> comp audit - use global registration method

- tests/foreman/api/test_notifications.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14674
Users with disabled account or disabled email were still receiving notifications about long-running tasks.
New test that verifies that these users don't receive the notification.
Bugzilla: https://bugzilla.redhat.com/2245056
> [6.14.z] notifications: no long tasks email for certain users

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14738
Component Audit: SAT-23364
Test `test_positive_accessible_content_status` were using deprecated consumer CA cert RPM, 
change content host registration method to global registration template/method
No
> [6.15.z] comp audit - use global registration method

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14738
Component Audit: SAT-23364
Test `test_positive_accessible_content_status` were using deprecated consumer CA cert RPM, 
change content host registration method to global registration template/method
No
> [6.14.z] comp audit - use global registration method

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14738
Component Audit: SAT-23364
Test `test_positive_accessible_content_status` were using deprecated consumer CA cert RPM, 
change content host registration method to global registration template/method
No
> [6.13.z] comp audit - use global registration method

- tests/foreman/api/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14626
Ansible tests are mixed in API ansible module, which need to be consistent as CLI/UI module
Move Ansible API tests to Ansible-ConfigurationManagement and Ansible-RemoteExecution classes, And few other minor fixes.
> [6.15.z] Move ansible API tests to Ansible-Cfgmgmt and REX classes

- tests/foreman/api/test_contentview.py
API Automation coverage for [RFE] SAT-2927 and BZ# 1957144
Target Milestone is 6.15.0, no CP to 6.14.z
- Add repository to content-view
- Perform asynchronous repository sync
- Attempt to publish a version of the content-view, while repo sync ongoing.
- _Assert:_ Raised HTTP exception, publish task failed, repo sync `task_id` found in humanized error, CV versions unchanged.
```
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync
```
> [RFE] Should not be able to publish the content-view, while repository sync in-progress

- tests/foreman/api/test_parameters.py
the host was not deleted before the hostgroup
see: https://github.com/pytest-dev/pytest/issues/10023#issuecomment-1148514756
Execute host finalizer after hostgroup finalizer
This should replace https://github.com/SatelliteQE/robottelo/pull/14568
> Ensure correct finalizer order

- tests/foreman/api/test_parameters.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14620
the host was not deleted before the hostgroup
see: https://github.com/pytest-dev/pytest/issues/10023#issuecomment-1148514756
Execute host finalizer after hostgroup finalizer
This should replace https://github.com/SatelliteQE/robottelo/pull/14568
> [6.14.z] Ensure correct finalizer order

- tests/foreman/api/test_parameters.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14620
the host was not deleted before the hostgroup
see: https://github.com/pytest-dev/pytest/issues/10023#issuecomment-1148514756
Execute host finalizer after hostgroup finalizer
This should replace https://github.com/SatelliteQE/robottelo/pull/14568
> [6.13.z] Ensure correct finalizer order

- tests/foreman/api/test_parameters.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14620
the host was not deleted before the hostgroup
see: https://github.com/pytest-dev/pytest/issues/10023#issuecomment-1148514756
Execute host finalizer after hostgroup finalizer
This should replace https://github.com/SatelliteQE/robottelo/pull/14568
> [6.15.z] Ensure correct finalizer order

- tests/foreman/virtwho/ui/test_esx_sca.py
hypervisor guest register to satellite server,  the guest is in the Default Location, so locate to Default Location then can list in the content host page
Case :  PASS
```
(robottelo_615) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_last_checkin_status --disable-pytest-warnings -q
1 passed, 35 deselected, 5 warnings in 282.19s (0:04:42)
```
> content host set location to Default Location

- tests/foreman/virtwho/ui/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14497
hypervisor guest register to satellite server,  the guest is in the Default Location, so locate to Default Location then can list in the content host page
Case :  PASS
```
(robottelo_615) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_last_checkin_status --disable-pytest-warnings -q
1 passed, 35 deselected, 5 warnings in 282.19s (0:04:42)
```
> [6.15.z] content host set location to Default Location

- tests/foreman/virtwho/ui/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14497
hypervisor guest register to satellite server,  the guest is in the Default Location, so locate to Default Location then can list in the content host page
Case :  PASS
```
(robottelo_615) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_last_checkin_status --disable-pytest-warnings -q
1 passed, 35 deselected, 5 warnings in 282.19s (0:04:42)
```
> [6.14.z] content host set location to Default Location

- tests/foreman/virtwho/ui/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14497
hypervisor guest register to satellite server,  the guest is in the Default Location, so locate to Default Location then can list in the content host page
Case :  PASS
```
(robottelo_615) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_last_checkin_status --disable-pytest-warnings -q
1 passed, 35 deselected, 5 warnings in 282.19s (0:04:42)
```
> [6.13.z] content host set location to Default Location

- robottelo/cli/base.py
- tests/robottelo/test_cli.py
The `Base.execute()` method, which is used to run hammer CLI commands via broker's ssh client, currently encodes the hammer command as a `bytes` object before sending it to broker. Broker and its current ssh library (`ssh2-python312`) expect a `str` instead, although the library silently accepts the `bytes` object and runs the command successfully.
With support for other ssh libraries being added to broker in https://github.com/SatelliteQE/broker/pull/282, passing in a `bytes` object won't work anymore:
```
09:29:43  robottelo/cli/settings.py:29: in set
09:29:43      return cls.execute(cls._construct_command(options))
09:29:43  robottelo/cli/base.py:202: in execute
09:29:43      response = ssh.command(
09:29:43  robottelo/ssh.py:51: in command
09:29:43      result = client.execute(cmd, …
```
> Fix ssh command usage

- tests/foreman/api/test_ansible.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/14626
> [6.13.z] Move ansible API tests to Ansible-Cfgmgmt and REX classes

- tests/foreman/api/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14755
#14693 missed to address changes in installer status check
Add installer status check in a form of an assertion.
> [6.13.z] Assert installer status when enabling OpenSCAP

- tests/foreman/api/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14755
#14693 missed to address changes in installer status check
Add installer status check in a form of an assertion.
> [6.14.z] Assert installer status when enabling OpenSCAP

- tests/foreman/data/hammer_commands.json
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14760
updated commands tree for the current state in 6.15, opening master PR first to have these changes there too
local result against 6.15:
```
pytest tests/foreman/cli/test_hammer.py -k all_options
===================================== test session starts =====================================
tests/foreman/cli/test_hammer.py .                                                      [100%]
> [6.15.z] updated hammer commands tree

- tests/foreman/api/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14755
#14693 missed to address changes in installer status check
Add installer status check in a form of an assertion.
> [6.15.z] Assert installer status when enabling OpenSCAP

- robottelo/hosts.py
Cherrypicks #14693
(cherry picked from commit d37f76c3c9b6be2a49922f960015e70c5aa68202)
Fixes #14714
> [6.12.z] Fix Capsule.install when used w/o kwargs

- tests/foreman/destructive/test_katello_certs_check.py
The original qpid RPM being used to validate the capsule certs in `test_positive_validate_capsule_certificate` was removed recently.
Remove the `rpm2cpio` line and use the apache cert that was generated. Also clean up old code that relied on the BZ.
pytest: tests/foreman/destructive/test_katello_certs_check.py::test_positive_validate_capsule_certificate
> Fix and update capsule certificate validation

- tests/foreman/destructive/test_capsulecontent.py
Entitlement mode got deprecated and removed from 6.16
Flip to SCA.
pytest: tests/foreman/destructive/test_capsulecontent.py
> Flip entitlement to SCA in destructive caps content

- tests/upgrades/test_virtwho.py
virt-who config SCA-compliant
update the org to module_sca_manifest_org
remove virtual sku attache check step
update check status to "Simple Content Access"
Cases : PASS
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade --disable-pytest-warnings -q
.                                                                                                                                          [100%]
1 passed, 1 deselected, 3 warnings in 164.29s (0:02:44)
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m post_upgrade --disable-pytest-warnings -q. …
```
> virt-who config SCA-compliant

- tests/upgrades/test_virtwho.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14775
virt-who config SCA-compliant
update the org to module_sca_manifest_org
remove virtual sku attache check step
update check status to "Simple Content Access"
Cases : PASS
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade --disable-pytest-warnings -q
.                                                                                                                                          [100%]
1 passed, 1 deselected, 3 warnings in 164.29s (0:02:44)
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m post_upgrade --disable-pytest-warnings -q. …
```
> [6.15.z] virt-who config SCA-compliant

- tests/upgrades/test_virtwho.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14775
virt-who config SCA-compliant
update the org to module_sca_manifest_org
remove virtual sku attache check step
update check status to "Simple Content Access"
Cases : PASS
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade --disable-pytest-warnings -q
.                                                                                                                                          [100%]
1 passed, 1 deselected, 3 warnings in 164.29s (0:02:44)
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m post_upgrade --disable-pytest-warnings -q. …
```
> [6.14.z] virt-who config SCA-compliant

- tests/foreman/api/test_syncplan.py
- tests/foreman/cli/test_syncplan.py
Four SyncPlans tests are still using `entitlement` mode, which was deprecated and removed in 6.16. They need to be flipped to SCA mode.
This PR.
pytest: tests/foreman/api/test_syncplan.py tests/foreman/cli/test_syncplan.py -k 'synchronize_rh_product_past_sync_date or synchronize_rh_product_future_sync_date'
> Flip SyncPlan tests to SCA

- tests/foreman/api/test_convert2rhel.py
- tests/foreman/cli/test_registration.py
We had subscription status code for 6.15 and older versions, with 6.16, SCA is enabled by default and subscription status code are no more valid. This PR removes the assertion to check the subscription code and subscription_status_label.
The second issue was with the registration test where I have updated the output format to json.
Fixes the tests failing with the above issues.
> Remove the sub-man status

- tests/foreman/destructive/test_contentview.py
In CV eval it was suggested to add some randomness into the CV publish interruption so that we cover different phases of the publish task and go more real-life.
Add some sleep and few other adjustments.
pytest: tests/foreman/destructive/test_contentview.py
> Add some randomness to CV publish break down

- tests/foreman/cli/test_registration.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/14783 
pytest: tests/foreman/cli/test_registration.py -k 'test_positive_force_register_twice'
> 6.15.z Cherrypick Test_Fixes_and_SCA_enbaled_manifest 

- robottelo/cli/sm_advanced.py
- robottelo/cli/sm_backup.py
- tests/foreman/maintain/test_backup_restore.py
- Snapshot backup has been removed from foreman-maintain in 6.16
- Remove foreman-maintain snapshot backup-related code
- SAT-20641
> Remove foreman-maintain snapshot backup related code

- robottelo/constants/__init__.py
- tests/foreman/api/test_permission.py
API permission tests failing for upstream
* add more checks for installed rpm packages
* speedup by querying rpm -qa ony once
* some tests were not updated with this commit https://github.com/SatelliteQE/robottelo/commit/6651dd63b4c308b3f7f3601f0e69d76b4c602b29#diff-9a55ae74469aa91ad5efb2b9068f73174467cd0c00d45abf7d35f9f2277a7632
Relevant tests:
```
tests/foreman/cli/test_role.py
tests/foreman/api/test_role.py
```
> Fix upstream api permission tests

- robottelo/constants/__init__.py
- tests/foreman/api/test_permission.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14475
API permission tests failing for upstream
* add more checks for installed rpm packages
* speedup by querying rpm -qa ony once
* some tests were not updated with this commit https://github.com/SatelliteQE/robottelo/commit/6651dd63b4c308b3f7f3601f0e69d76b4c602b29#diff-9a55ae74469aa91ad5efb2b9068f73174467cd0c00d45abf7d35f9f2277a7632
Relevant tests:
```
tests/foreman/cli/test_role.py
tests/foreman/api/test_role.py
```
> [6.15.z] Fix upstream api permission tests

- tests/foreman/destructive/test_katello_agent.py
KA removal warning test is failing since `6.15` scenario has been removed from foreman-maintain nightly.
Use 6.15 version of foreman-maintain instead.
pytest: tests/foreman/destructive/test_katello_agent.py -k test_positive_upgrade_warning
> [6.14.z] Fix KA check

- tests/foreman/cli/test_repository.py
```
Error: Unrecognised option '--content_type'.
E             
E             See: 'hammer repository create --help'.
```
fix typo: content_type --> content-type
```
tests/foreman/cli/test_repository.py::TestRepository::test_positive_sync_third_party_repo
tests/foreman/cli/test_repository.py::TestRepository::test_positive_sync_sha_repo
```
> Fix typo for hammer cli create repo

- tests/foreman/cli/test_registration.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/14783
> Remove the sub-man status (#14783)

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14801
```
Error: Unrecognised option '--content_type'.
E             
E             See: 'hammer repository create --help'.
```
fix typo: content_type --> content-type
```
tests/foreman/cli/test_repository.py::TestRepository::test_positive_sync_third_party_repo
tests/foreman/cli/test_repository.py::TestRepository::test_positive_sync_sha_repo
```
> [6.15.z] Fix typo for hammer cli create repo

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14801
```
Error: Unrecognised option '--content_type'.
E             
E             See: 'hammer repository create --help'.
```
fix typo: content_type --> content-type
```
tests/foreman/cli/test_repository.py::TestRepository::test_positive_sync_third_party_repo
tests/foreman/cli/test_repository.py::TestRepository::test_positive_sync_sha_repo
```
> [6.13.z] Fix typo for hammer cli create repo

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14801
```
Error: Unrecognised option '--content_type'.
E             
E             See: 'hammer repository create --help'.
```
fix typo: content_type --> content-type
```
tests/foreman/cli/test_repository.py::TestRepository::test_positive_sync_third_party_repo
tests/foreman/cli/test_repository.py::TestRepository::test_positive_sync_sha_repo
```
> [6.14.z] Fix typo for hammer cli create repo

- robottelo/constants/__init__.py
- tests/foreman/longrun/test_inc_updates.py
Implement backlogged desired coverage - PR #9991 , authored by @latran
- Automation for incremental update duration coverage, for [BZ 2117760](https://bugzilla.redhat.com/show_bug.cgi?id=2117760) and [BZ 1829266](https://bugzilla.redhat.com/show_bug.cgi?id=1829266)
- **Steps**: 
- On an existing CV with decent amount of content, perform incremental update with only one errata. 
- Publish the entire content view. 
- _Expect:_ The duration of the incremental update should almost always be shorter than the CV publish. To cover the BZs fully, if the update does take longer, check that it was close, that update did not take significantly longer.
- _Original issue raised in BZs_: CV publish would only take a few minutes as expected, but incremental update with one or a couple errata was taking …
> Test CV incremental update & publish time

- tests/foreman/cli/test_contentview.py
```
TypeError: create_object() got an unexpected keyword argument 'cached'
```
remove `cached` parameter
```
tests/foreman/cli/test_contentview.py::TestContentView::test_negative_user_with_no_create_view_cv_permissions
```
> Remove broken cached parameter

- robottelo/constants/__init__.py
- tests/foreman/longrun/test_inc_updates.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14749
Implement backlogged desired coverage - PR #9991 , authored by @latran
- Automation for incremental update duration coverage, for [BZ 2117760](https://bugzilla.redhat.com/show_bug.cgi?id=2117760) and [BZ 1829266](https://bugzilla.redhat.com/show_bug.cgi?id=1829266)
- **Steps**: 
- On an existing CV with decent amount of content, perform incremental update with only one errata. 
- Publish the entire content view. 
- _Expect:_ The duration of the incremental update should almost always be shorter than the CV publish. To cover the BZs fully, if the update does take longer, check that it was close, that update did not take significantly longer.
- _Original issue raised in BZs_: CV publish would only take a few minutes as …
> [6.14.z] Test CV incremental update & publish time

- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14807
```
TypeError: create_object() got an unexpected keyword argument 'cached'
```
remove `cached` parameter
```
tests/foreman/cli/test_contentview.py::TestContentView::test_negative_user_with_no_create_view_cv_permissions
```
> [6.13.z] Remove broken cached parameter

- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14807
```
TypeError: create_object() got an unexpected keyword argument 'cached'
```
remove `cached` parameter
```
tests/foreman/cli/test_contentview.py::TestContentView::test_negative_user_with_no_create_view_cv_permissions
```
> [6.15.z] Remove broken cached parameter

- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14807
```
TypeError: create_object() got an unexpected keyword argument 'cached'
```
remove `cached` parameter
```
tests/foreman/cli/test_contentview.py::TestContentView::test_negative_user_with_no_create_view_cv_permissions
```
> [6.14.z] Remove broken cached parameter

- .github/workflows/pull_request.yml
- .github/workflows/weekly.yml
- conf/jira.yaml.template
- pytest_plugins/metadata_markers.py
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- robottelo/utils/issue_handlers/README.md
- robottelo/utils/issue_handlers/__init__.py
- robottelo/utils/issue_handlers/bugzilla.py
- robottelo/utils/issue_handlers/jira.py
- testimony.yaml
- tests/robottelo/test_issue_handlers.py
-  Missing support for Jira issue handling in Robottelo.
- Add `BlockedBy` doc field: If the issue is open, the test will be skipped/deselected. Override behavior with `--blocked-by false`.
- Add `Verifies` doc field: Used with `--verifies-issues` pytest option.
- `--verifies-issues`: Comma-separated list of Jiras to collect tests matching the `Verifies` testimony marker. If no issue is provided, all tests with the `Verifies` testimony marker will be selected.
- `--blocked-by`: Comma-separated list of Jiras to collect tests matching the `BlockedBy` testimony marker. If no issue is provided, all tests with the `BlockedBy` testimony marker will be processed and deselected if any issue is open.
- `is_open_jira`: Function to check if a specific Jira is open.
- SAT-22761
> Add support for Jira Issue handler

- tests/foreman/api/test_organization.py
updating for SCA as a default (SAT-24364)
> sca fix for api org test

- robottelo/host_helpers/satellite_mixins.py
There is a problem with capsule tunnel error handling. It throws `TypeError: 'int' object is not subscriptable`.  By checking [ssh2.channel.Channel.get_exit_status](https://ssh2-python.readthedocs.io/en/latest/channel.html#ssh2.channel.Channel.get_exit_status) documentation it is obvious that `channel.get_exit_status()[1]` could never work since it was added. 
Replace `channel.get_exit_status()` by `channel.get_exit_signal()` which is way more verbose providing not only return code but also error message and exit signal.
> Fix getting exit code on capsule tunnel error

- robottelo/host_helpers/satellite_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14821
There is a problem with capsule tunnel error handling. It throws `TypeError: 'int' object is not subscriptable`.  By checking [ssh2.channel.Channel.get_exit_status](https://ssh2-python.readthedocs.io/en/latest/channel.html#ssh2.channel.Channel.get_exit_status) documentation it is obvious that `channel.get_exit_status()[1]` could never work since it was added. 
Replace `channel.get_exit_status()` by `channel.get_exit_signal()` which is way more verbose providing not only return code but also error message and exit signal.
> [6.15.z] Fix getting exit code on capsule tunnel error

- robottelo/host_helpers/satellite_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14821
There is a problem with capsule tunnel error handling. It throws `TypeError: 'int' object is not subscriptable`.  By checking [ssh2.channel.Channel.get_exit_status](https://ssh2-python.readthedocs.io/en/latest/channel.html#ssh2.channel.Channel.get_exit_status) documentation it is obvious that `channel.get_exit_status()[1]` could never work since it was added. 
Replace `channel.get_exit_status()` by `channel.get_exit_signal()` which is way more verbose providing not only return code but also error message and exit signal.
> [6.13.z] Fix getting exit code on capsule tunnel error

- tests/foreman/api/test_provisioningtemplate.py
Assertion was failing due to incorrect rendering of the template.
Updated the assertion
> Update the test for the assertion failure

- tests/foreman/installer/test_installer.py
- Fix `test_content_guarded_distributions_option` failing with `assert "403: [('PEM routines', 'get_name', 'no start line')]" in "403: [('PEM routines', '', 'no start line')]"` on RHEL9.
- Update assertion to only check `403` error code
- SAT-24616
> Fix test_content_guarded_distributions_option

- tests/foreman/maintain/test_upgrade.py
- test_negative_pre_upgrade_tuning_profile_check is failing because the test tries to find a nonexisting RHEL9 repo for Satellite 6.15. 
- As RHEL9 is only supported from 6.16 onwards, update the test to do a z-stream upgrade till 6.16 is GA and the next version is available for testing.
- SAT-24576
> Update test_negative_pre_upgrade_tuning_profile_check for RHEL9

- robottelo/hosts.py
- tests/foreman/destructive/test_clone.py
- `test_positive_clone_backup` is failing with `Satellite is already installed. Satellite-clone should be run on a clean RHEL machine.` error.
- Only enable the Satellite module but do not install the package.
- SAT-24576
> Fix test_positive_clone_backup

- tests/foreman/cli/test_remoteexecution.py
covers bz# 2258968
testing rex with effective user with non-ascii password
> effective user with non-ascii password

- tests/foreman/ui/test_organization.py
updating for SCA as a default (SAT-24364)
> sca fixes for ui organization

- tests/foreman/ui/test_ansible.py
Ansible role should be added and removed for new_ui host
Removed `test_positive_assign_role_in_new_ui` , because single test case is covering add and remove scenario.
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1347
> add & remove ansible role

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14556
Ansible role should be added and removed for new_ui host
Removed `test_positive_assign_role_in_new_ui` , because single test case is covering add and remove scenario.
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1347
> [6.14.z] add & remove ansible role

- .github/workflows/pull_request.yml
- .github/workflows/weekly.yml
- conf/jira.yaml.template
- pytest_plugins/metadata_markers.py
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- robottelo/utils/issue_handlers/README.md
- robottelo/utils/issue_handlers/__init__.py
- robottelo/utils/issue_handlers/bugzilla.py
- robottelo/utils/issue_handlers/jira.py
- testimony.yaml
- tests/robottelo/test_issue_handlers.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14728
-  Missing support for Jira issue handling in Robottelo.
- Add `BlockedBy` doc field: If the issue is open, the test will be skipped/deselected. Override behavior with `--blocked-by false`.
- Add `Verifies` doc field: Used with `--verifies-issues` pytest option.
- `--verifies-issues`: Comma-separated list of Jiras to collect tests matching the `Verifies` testimony marker. If no issue is provided, all tests with the `Verifies` testimony marker will be selected.
- `--blocked-by`: Comma-separated list of Jiras to collect tests matching the `BlockedBy` testimony marker. If no issue is provided, all tests with the `BlockedBy` testimony marker will be processed and deselected if any issue is open.
- `is_open_jira`: Function …
> [6.15.z] Add support for Jira Issue handler

- .github/workflows/pull_request.yml
- .github/workflows/weekly.yml
- conf/jira.yaml.template
- pytest_plugins/metadata_markers.py
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- robottelo/utils/issue_handlers/README.md
- robottelo/utils/issue_handlers/__init__.py
- robottelo/utils/issue_handlers/bugzilla.py
- robottelo/utils/issue_handlers/jira.py
- testimony.yaml
- tests/robottelo/test_issue_handlers.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14728
-  Missing support for Jira issue handling in Robottelo.
- Add `BlockedBy` doc field: If the issue is open, the test will be skipped/deselected. Override behavior with `--blocked-by false`.
- Add `Verifies` doc field: Used with `--verifies-issues` pytest option.
- `--verifies-issues`: Comma-separated list of Jiras to collect tests matching the `Verifies` testimony marker. If no issue is provided, all tests with the `Verifies` testimony marker will be selected.
- `--blocked-by`: Comma-separated list of Jiras to collect tests matching the `BlockedBy` testimony marker. If no issue is provided, all tests with the `BlockedBy` testimony marker will be processed and deselected if any issue is open.
- `is_open_jira`: Function …
> [6.14.z] Add support for Jira Issue handler

- .github/workflows/pull_request.yml
- .github/workflows/weekly.yml
- conf/jira.yaml.template
- pytest_plugins/metadata_markers.py
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- robottelo/utils/issue_handlers/README.md
- robottelo/utils/issue_handlers/__init__.py
- robottelo/utils/issue_handlers/bugzilla.py
- robottelo/utils/issue_handlers/jira.py
- testimony.yaml
- tests/robottelo/test_issue_handlers.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14728
-  Missing support for Jira issue handling in Robottelo.
- Add `BlockedBy` doc field: If the issue is open, the test will be skipped/deselected. Override behavior with `--blocked-by false`.
- Add `Verifies` doc field: Used with `--verifies-issues` pytest option.
- `--verifies-issues`: Comma-separated list of Jiras to collect tests matching the `Verifies` testimony marker. If no issue is provided, all tests with the `Verifies` testimony marker will be selected.
- `--blocked-by`: Comma-separated list of Jiras to collect tests matching the `BlockedBy` testimony marker. If no issue is provided, all tests with the `BlockedBy` testimony marker will be processed and deselected if any issue is open.
- `is_open_jira`: Function …
> [6.13.z] Add support for Jira Issue handler

- pytest_fixtures/core/xdist.py
There were situations in the past where I would be more than grateful for a context of what is happening in `align_to_satellite` fixture.
This PR adds logging to the fixture. That should help during the log investigation.
none
> Add logging to Satellite-xdist worker assignment process

- pytest_fixtures/core/xdist.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14539
There were situations in the past where I would be more than grateful for a context of what is happening in `align_to_satellite` fixture.
This PR adds logging to the fixture. That should help during the log investigation.
none
> [6.14.z] Add logging to Satellite-xdist worker assignment process

- pytest_fixtures/core/xdist.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14539
There were situations in the past where I would be more than grateful for a context of what is happening in `align_to_satellite` fixture.
This PR adds logging to the fixture. That should help during the log investigation.
none
> [6.13.z] Add logging to Satellite-xdist worker assignment process

- robottelo/cli/job_invocation.py
- robottelo/host_helpers/cli_factory.py
- tests/foreman/longrun/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14437
Rex jobs killed after 10 minutes
https://github.com/theforeman/foreman-tasks/pull/746
This PR runs a longer job to verify ^, unfortunately there is no reproduction shortcut that we could use
> [6.15.z] rex longrun job

- tests/foreman/cli/test_partitiontable.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14808
in `hammer partition-table create` the  `--content` parameter is no longer around, one needs to supply file
tests updated
> [6.13.z] partition table fix

- tests/foreman/destructive/test_clone.py
Stream/6.16 supports both el8 and el9 versions. We need to ensure that customers are able to upgrade underlying OS using `satellite-clone` tool
If we are running for el8 then parametrize target `sat_ready_rhel`  to be both 8 and 9 extending matrix of testing datapoints. 
SAT-24714
> Add coverage for clone from el8 to el9

- tests/foreman/cli/test_partitiontable.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14808
in `hammer partition-table create` the  `--content` parameter is no longer around, one needs to supply file
tests updated
> [6.15.z] partition table fix

- pytest_fixtures/component/provision_vmware.py
- tests/foreman/cli/test_computeresource_vmware.py
- tests/foreman/ui/test_computeresource_vmware.py
There wasn't any proper teardown of vmwareclient. we see `DEBUG - vCenter keep-alive: 2024-04-14 07:51:45.515419+00:00`  in the logs
Add a fixture which handles the proper teardown
> Add proper teardown of VMware client

- conf/oscap.yaml.template
- pytest_fixtures/component/oscap.py
- robottelo/constants/__init__.py
- tests/foreman/cli/test_oscap.py
- tests/foreman/ui/test_oscapcontent.py
Part of the oscap tests were too rhel8 backend specific and didn't run on rhel9 sat
Making the tests more flexible
Requires satelliteqe-jenkins mr 1300
Results form local rhel9 sat run:
```
pytest tests/foreman/cli/test_oscap.py 
...
============ 68 passed, 3 deselected, 35 warnings in 971.49s (0:16:11) =============
```
> make oscap tests run on rhel9 backend

- pytest_fixtures/component/provision_vmware.py
- tests/foreman/cli/test_computeresource_vmware.py
- tests/foreman/ui/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14799
There wasn't any proper teardown of vmwareclient. we see `DEBUG - vCenter keep-alive: 2024-04-14 07:51:45.515419+00:00`  in the logs
Add a fixture which handles the proper teardown
> [6.14.z] Add proper teardown of VMware client

- pytest_fixtures/component/provision_vmware.py
- tests/foreman/cli/test_computeresource_vmware.py
- tests/foreman/ui/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14799
There wasn't any proper teardown of vmwareclient. we see `DEBUG - vCenter keep-alive: 2024-04-14 07:51:45.515419+00:00`  in the logs
Add a fixture which handles the proper teardown
> [6.15.z] Add proper teardown of VMware client

- robottelo/hosts.py
Omitting credentials doesn't work when CLI has already been instantiated
If it's been instantiated, set its omitting attribute to `True` for all the classes
> Fix omitting credentials when CLI has already been instantiated

- tests/foreman/ui/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14303
null
> [6.15.z] Fix expected user name

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14449
Omitting credentials doesn't work when CLI has already been instantiated
If it's been instantiated, set its omitting attribute to `True` for all the classes
> [6.15.z] Fix omitting credentials when CLI has already been instantiated

- pytest_fixtures/component/os.py
- pytest_fixtures/component/provision_azure.py
- pytest_fixtures/component/provision_gce.py
- pytest_fixtures/component/puppet.py
- robottelo/constants/__init__.py
- robottelo/host_helpers/api_factory.py
- tests/foreman/ui/test_contentview_old.py
When EL9 is default OS for Foreman, *_default_os fixtures returns below error 
```
pytest_fixtures/component/os.py:24: in default_os
os = entities.OperatingSystem().search(query={'search': search_string})[0].read()
E   IndexError: list index out of range
```
Add  EL9 in search_string for *_default_os fixtures
Move default os search query to constants and delete unused session_default_os fixture (from review)
> Extend search in *_default_os fixtures for EL9 as default OS

- pyproject.toml
- robottelo/exceptions.py
- robottelo/host_helpers/cli_factory.py
- robottelo/hosts.py
- robottelo/utils/decorators/func_locker.py
- robottelo/utils/decorators/func_shared/shared.py
- robottelo/utils/virtwho.py
- tests/foreman/ui/test_audit.py
- tests/foreman/ui/test_computeprofiles.py
- tests/foreman/ui/test_dashboard.py
- tests/foreman/ui/test_hostcollection.py
- tests/foreman/ui/test_repository.py
#14781 attempts to update ruff to a newer version, but it fails because there are some fixes required before the bump can be made. Also, new version of ruff requires different paths in the config. 
Fix linter failures, make sure that ruff 0.4.1 does not complain. Modify the config to silence ruff's warnings.
none
> Preparations for ruff 0.4.1

- tests/foreman/cli/test_remoteexecution.py
location mismatch prevented users from finding the target hosts
> fixes in rex infrahost tests

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14874
location mismatch prevented users from finding the target hosts
> [6.15.z] fixes in rex infrahost tests

- tests/foreman/cli/test_host.py
dropping some rhel6 hosts remaining in host parametrization
> version selection for some host tests

- tests/foreman/longrun/test_inc_updates.py
`longrun/test_inc_updates.py` has 2 tests, module scope fixture creates one organization and same organization has been used in two test cases, after uploading manifest second time test was failing due to below error message
**test name:** test_positive_incremental_update_time
**Error:**
`['Owner has already imported from another subscription management application. The following conflicts were found: [ DISTRIBUTOR_CONFLICT ]']`
changed scope of fixture of one test case so it will not use previously created organization from same test session.
N/A
pytest: tests/foreman/longrun/test_inc_updates.py
> update scope of fixtures from hosts-content longrun test_inc_updates

- .pre-commit-config.yaml
- pyproject.toml
- robottelo/exceptions.py
- robottelo/host_helpers/cli_factory.py
- robottelo/hosts.py
- robottelo/utils/decorators/func_locker.py
- robottelo/utils/decorators/func_shared/shared.py
- robottelo/utils/virtwho.py
- tests/foreman/ui/test_audit.py
- tests/foreman/ui/test_dashboard.py
- tests/foreman/ui/test_hostcollection.py
- tests/foreman/ui/test_repository.py
> [6.12.z] Preparations for ruff 0.4.1 (#14885)

- tests/foreman/api/test_discoveredhost.py
- tests/foreman/api/test_operatingsystem.py
- tests/foreman/api/test_provisioning.py
- tests/foreman/sys/test_katello_certs_check.py
- tests/upgrades/test_role.py
- Deletes certificate-related tests as part of the component audit.
- Fixes `CaseAutomation`, as some of the tests are marked as `NotAutomated` even though they are automated and should be run in automation.
- SAT-23021
> Fix CaseAutomation for tests and delete Certificates related tests as part of component audit.

- tests/foreman/api/test_discoveredhost.py
- tests/foreman/api/test_operatingsystem.py
- tests/foreman/api/test_provisioning.py
- tests/foreman/sys/test_katello_certs_check.py
- tests/upgrades/test_role.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14873
- Deletes certificate-related tests as part of the component audit.
- Fixes `CaseAutomation`, as some of the tests are marked as `NotAutomated` even though they are automated and should be run in automation.
- SAT-23021
> [6.14.z] Fix CaseAutomation for tests and delete Certificates related tests as part of component audit.

- tests/foreman/api/test_discoveredhost.py
- tests/foreman/api/test_operatingsystem.py
- tests/foreman/api/test_provisioning.py
- tests/foreman/sys/test_katello_certs_check.py
- tests/upgrades/test_role.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14873
- Deletes certificate-related tests as part of the component audit.
- Fixes `CaseAutomation`, as some of the tests are marked as `NotAutomated` even though they are automated and should be run in automation.
- SAT-23021
> [6.13.z] Fix CaseAutomation for tests and delete Certificates related tests as part of component audit.

- robottelo/hosts.py
- tests/foreman/cli/test_leapp_client.py
Missing scenario of Leapp client upgrade from non-admin user
We need sca enabled manifest because test is failing with VDC subscription we use from manifest.yaml.
Added test scenario to test BZ#2257302
> [6.15.z]Leapp client upgrade from non-admin user

- robottelo/hosts.py
- tests/foreman/cli/test_leapp_client.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14671
Missing scenario of Leapp client upgrade from non-admin user
We need sca enabled manifest because test is failing with VDC subscription we use from manifest.yaml.
Added test scenario to test BZ#2257302
> [6.14.z] [6.15.z]Leapp client upgrade from non-admin user

- tests/foreman/api/test_contentview.py
`test_negative_publish_during_repo_sync`: Sometimes, more than one content-view publish task is present, 
so we should search that there are > 0, and get most recent task from search, [index 0].
- The reason seems to be because in this module, when the full session is run, an associated composite content-view still exists from another test, which will generate extra task(s).
CI failure for stream, 6.15.z combined sessions, because occasionally we find 2 or 3 matching tasks, instead of exactly 1.
```
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_negative_publish_during_repo_sync
```
> Quick fix- CI failure- for number of found CV publish tasks

- tests/foreman/ui/test_architecture.py
- tests/foreman/ui/test_audit.py
- tests/foreman/ui/test_computeprofiles.py
- tests/foreman/ui/test_computeresource.py
- tests/foreman/ui/test_computeresource_ec2.py
- tests/foreman/ui/test_computeresource_vmware.py
- tests/foreman/ui/test_containerimagetag.py
- tests/foreman/ui/test_domain.py
- tests/foreman/ui/test_hardwaremodel.py
- tests/foreman/ui/test_hostgroup.py
- tests/foreman/ui/test_location.py
- tests/foreman/ui/test_modulestreams.py
- tests/foreman/ui/test_organization.py
- tests/foreman/ui/test_oscappolicy.py
- tests/foreman/ui/test_oscaptailoringfile.py
- tests/foreman/ui/test_package.py
- tests/foreman/ui/test_product.py
- tests/foreman/ui/test_reporttemplates.py
- tests/foreman/ui/test_sync.py
- tests/foreman/ui/test_syncplan.py
- tests/foreman/ui/test_templatesync.py
- tests/foreman/ui/test_usergroup.py
We are using the direct imports from the nailgun rather than directly using from target_sat
Solution
Direct Imports Removed: We've cleaned up our codebase by eliminating direct imports from the Nailgun package.
Using target_sat, module_target_sat, class_target_sat: Modified the API calls and using the target_sat.api. pattern for all API calls.
> [6.15.z] - remove the all nailgun imports from UI folder

- tests/foreman/api/test_contentview.py
CC Automation/Comp Eval for CV work for BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2153523
> CC Automation/Comp Eval coverage - promote CCV with specific registry_name

- tests/foreman/ui/test_errata.py
Initial PR #14773 raised by @LadislavVasina1, for 3 errata UI test fixes/updates.
- troubleshoot PRT failures in combined session, running the 3 tests from above PR.
Error in setup for `test_positive_check_errata_counts_by_type_on_host_details_page `:
Locally have intermittently reproduced issue with the `registered_contenthost` UI fixture with adding repos to cv, and promotion of cv to lce, in between parameters of combined session. Issues with some associated activation keys not being deleted in cleanup.
```
pytest: tests/foreman/ui/test_errata.py -k 'test_positive_check_errata or test_positive_errata_search_type or test_positive_check_errata_counts_by_type_on_host_details_page or test_positive_list and not test_positive_list_permission'
```
- We run the 3 …
> [stream] fixes for combined session failures, Errata UI

- tests/foreman/ui/test_errata.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14822
Initial PR #14773 raised by @LadislavVasina1, for 3 errata UI test fixes/updates.
- troubleshoot PRT failures in combined session, running the 3 tests from above PR.
Error in setup for `test_positive_check_errata_counts_by_type_on_host_details_page `:
Locally have intermittently reproduced issue with the `registered_contenthost` UI fixture with adding repos to cv, and promotion of cv to lce, in between parameters of combined session. Issues with some associated activation keys not being deleted in cleanup.
```
pytest: tests/foreman/ui/test_errata.py -k 'test_positive_check_errata or test_positive_errata_search_type or test_positive_check_errata_counts_by_type_on_host_details_page or …
```
> [6.15.z] [stream] fixes for combined session failures, Errata UI

- tests/foreman/ui/test_errata.py
- outdated setup using old fixtures and deprecated methods.
- **Resolved conflict with newly introduced case** from ([recently merged commit](https://github.com/SatelliteQE/robottelo/pull/14822/commits/00ca2968fd58007ca19160cbdcd00589031fa1b8#)).
^ Above commit renamed `test_positive_content_host_library` to `test_positive_check_errata`, 
and rewrote as a fundamental quick check of New Host > content > errata details. 
So `test_positive_check_errata` it could be a new smaller case, I gave it a unique :id, and made `tier2` importance.
I think it's still good to retain this PRs changes for  `test_positive_host_content_library`, which is searching and reading the full errata tables displayed in UI, for new host and legacy chost.
- rename to `test_positive_host_content_library`, to reflect …
> [Stream] Errata-UI: Fix test_positive_host_content_library

- tests/foreman/ui/test_errata.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14926
- outdated setup using old fixtures and deprecated methods.
- **Resolved conflict with newly introduced case** from ([recently merged commit](https://github.com/SatelliteQE/robottelo/pull/14822/commits/00ca2968fd58007ca19160cbdcd00589031fa1b8#)).
^ Above commit renamed `test_positive_content_host_library` to `test_positive_check_errata`, 
and rewrote as a fundamental quick check of New Host > content > errata details. 
So `test_positive_check_errata` it could be a new smaller case, I gave it a unique :id, and made `tier2` importance.
I think it's still good to retain this PRs changes for  `test_positive_host_content_library`, which is searching and reading the full errata tables displayed in UI, for new host and legacy …
> [6.15.z] Errata-UI: Fix test_positive_host_content_library

- tests/foreman/cli/test_registration.py
Adding Closed loop for BZ#2250397 covering host registration with custom facts
> Add test coverage for BZ#2250397

- robottelo/hosts.py
- tests/foreman/cli/test_leapp_client.py
Missing scenario of Leapp client upgrade from non-admin user
Added test scenario to test BZ#2257302
This PR only aims for stream as this is blocked by SAT-24023 and another PR raised for 6.15.z and below branches https://github.com/SatelliteQE/robottelo/pull/14671
> Test leapp upgrade with non-admin user BZ#2257302

- robottelo/utils/datafactory.py
This PR removes an escaped quotation mark in a datafactory method used exclusively in content view CLI tests. 
This always fails, as even when escaped, the clifactory errors out when faced with this particular string. Open to better choices for a fix here.
> [Stream Fix] Remove escaped quotation mark from valid_name list

- robottelo/utils/datafactory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14941
This PR removes an escaped quotation mark in a datafactory method used exclusively in content view CLI tests. 
This always fails, as even when escaped, the clifactory errors out when faced with this particular string. Open to better choices for a fix here.
> [6.15.z] [Stream Fix] Remove escaped quotation mark from valid_name list

- robottelo/utils/datafactory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14941
This PR removes an escaped quotation mark in a datafactory method used exclusively in content view CLI tests. 
This always fails, as even when escaped, the clifactory errors out when faced with this particular string. Open to better choices for a fix here.
> [6.14.z] [Stream Fix] Remove escaped quotation mark from valid_name list

- robottelo/utils/datafactory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14941
This PR removes an escaped quotation mark in a datafactory method used exclusively in content view CLI tests. 
This always fails, as even when escaped, the clifactory errors out when faced with this particular string. Open to better choices for a fix here.
> [6.13.z] [Stream Fix] Remove escaped quotation mark from valid_name list

- tests/foreman/destructive/test_ansible.py
Missing coverage for BZ:2166466/BZ:2242915, where we verified pagination on hostgroup edit page as per entries_per_page setting
Add coverage for BZ:2166466/BZ:2242915 to verify pagination on hostgroup create and edit page as per entries_per_page setting
Airgun PR https://github.com/SatelliteQE/airgun/pull/1372
> Add test coverage for BZ:2166466

- tests/foreman/destructive/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14914
Missing coverage for BZ:2166466/BZ:2242915, where we verified pagination on hostgroup edit page as per entries_per_page setting
Add coverage for BZ:2166466/BZ:2242915 to verify pagination on hostgroup create and edit page as per entries_per_page setting
Airgun PR https://github.com/SatelliteQE/airgun/pull/1372
> [6.15.z] Add test coverage for BZ:2166466

- tests/foreman/destructive/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14914
Missing coverage for BZ:2166466/BZ:2242915, where we verified pagination on hostgroup edit page as per entries_per_page setting
Add coverage for BZ:2166466/BZ:2242915 to verify pagination on hostgroup create and edit page as per entries_per_page setting
Airgun PR https://github.com/SatelliteQE/airgun/pull/1372
> [6.14.z] Add test coverage for BZ:2166466

- tests/foreman/destructive/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14914
Missing coverage for BZ:2166466/BZ:2242915, where we verified pagination on hostgroup edit page as per entries_per_page setting
Add coverage for BZ:2166466/BZ:2242915 to verify pagination on hostgroup create and edit page as per entries_per_page setting
Airgun PR https://github.com/SatelliteQE/airgun/pull/1372
> [6.13.z] Add test coverage for BZ:2166466

- conf/supportability.yaml
- pytest_fixtures/component/os.py
- robottelo/config/validators.py
default os is hardcoded in fixture
* make default os configurable
Why is a new instance of `OperatingSystem` created [here](https://github.com/ATIX-AG/robottelo/blob/master/pytest_fixtures/component/os.py#L29) instead of returning the one create above?
tests/foreman/ui/test_registration.py::test_global_registration_form_populate
> Make default_os name and major versions configurable

- tests/foreman/longrun/test_inc_updates.py
`longrun/test_inc_updates.py` has 2 tests, module scope fixture creates one organization and same organization has been used in two test cases, after uploading manifest second time test was failing due to below error message
**test name:** test_positive_incremental_update_time
**Error:**
`['Owner has already imported from another subscription management application. The following conflicts were found: [ DISTRIBUTOR_CONFLICT ]']
`
changed scope of fixture of one test case so it will not use previously created organization from same test session.
6.14.z PR https://github.com/SatelliteQE/robottelo/pull/14842
pytest: tests/foreman/longrun/test_inc_updates.py
> 6.15.z update scope of fixtures from hosts-content longrun test_inc_updates

- conf/fam.yaml.template
- robottelo/constants/__init__.py
- robottelo/hosts.py
- tests/foreman/sys/test_fam.py
Some tests are failing in production because we are missing live config settings for them. We also created some tech debt on the last PR, because we were doing inline config replacement with `sed`.
Host the config files ourselves and evaluate them with dynaconf before sending them to the server.
I won't be able to test this in PRT at the moment, but will open a jenkins PR for the right config settings. The current templates I copied into here are directly from https://github.com/theforeman/foreman-ansible-modules/tree/develop/tests/test_playbooks/vars
> Copy config files for FAM to server

- conf/fam.yaml.template
- robottelo/constants/__init__.py
- robottelo/hosts.py
- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14866
Some tests are failing in production because we are missing live config settings for them. We also created some tech debt on the last PR, because we were doing inline config replacement with `sed`.
Host the config files ourselves and evaluate them with dynaconf before sending them to the server.
I won't be able to test this in PRT at the moment, but will open a jenkins PR for the right config settings. The current templates I copied into here are directly from https://github.com/theforeman/foreman-ansible-modules/tree/develop/tests/test_playbooks/vars
> [6.15.z] Copy config files for FAM to server

- conf/fam.yaml.template
- robottelo/constants/__init__.py
- robottelo/hosts.py
- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14866
Some tests are failing in production because we are missing live config settings for them. We also created some tech debt on the last PR, because we were doing inline config replacement with `sed`.
Host the config files ourselves and evaluate them with dynaconf before sending them to the server.
I won't be able to test this in PRT at the moment, but will open a jenkins PR for the right config settings. The current templates I copied into here are directly from https://github.com/theforeman/foreman-ansible-modules/tree/develop/tests/test_playbooks/vars
> [6.14.z] Copy config files for FAM to server

- conf/oscap.yaml.template
- pytest_fixtures/component/oscap.py
- robottelo/constants/__init__.py
- tests/foreman/cli/test_oscap.py
- tests/foreman/ui/test_oscapcontent.py
Cherry picking https://github.com/SatelliteQE/robottelo/pull/14716, event though rhel9 backend is not a thing for this branch, some config changes require backport, which I didn't realize before
> [6.13.z] make oscap tests run on rhel9 backend (#14716)

- conf/oscap.yaml.template
- pytest_fixtures/component/oscap.py
- robottelo/constants/__init__.py
- tests/foreman/cli/test_oscap.py
- tests/foreman/ui/test_oscapcontent.py
Cherry picking https://github.com/SatelliteQE/robottelo/pull/14716, event though rhel9 backend is not a thing for this branch, some config changes require backport, which I didn't realize before
> [6.15.z] make oscap tests run on rhel9 backend (#14716)

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14921
with recent changes in oscap related fixtures, the lack of the rhel9 variant in constants causes key error
added an item into constants
> [6.13.z] added scap constant

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14921
with recent changes in oscap related fixtures, the lack of the rhel9 variant in constants causes key error
added an item into constants
> [6.15.z] added scap constant

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14921
with recent changes in oscap related fixtures, the lack of the rhel9 variant in constants causes key error
added an item into constants
> [6.14.z] added scap constant

- robottelo/constants/__init__.py
We are seeing an error here https://github.com/SatelliteQE/robottelo/actions/runs/8990989538/job/24697560722?pr=14702
this could be because of the how Sphinx render the html code
This object in the constant was not used hence I tried to removed that.
> removed the non-used Colored box object

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14991
We are seeing an error here https://github.com/SatelliteQE/robottelo/actions/runs/8990989538/job/24697560722?pr=14702
this could be because of the how Sphinx render the html code
This object in the constant was not used hence I tried to removed that.
> [6.13.z] removed the non-used Colored box object

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14991
We are seeing an error here https://github.com/SatelliteQE/robottelo/actions/runs/8990989538/job/24697560722?pr=14702
this could be because of the how Sphinx render the html code
This object in the constant was not used hence I tried to removed that.
> [6.14.z] removed the non-used Colored box object

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14991
We are seeing an error here https://github.com/SatelliteQE/robottelo/actions/runs/8990989538/job/24697560722?pr=14702
this could be because of the how Sphinx render the html code
This object in the constant was not used hence I tried to removed that.
> [6.12.z] removed the non-used Colored box object

- tests/foreman/cli/test_leapp_client.py
- tests/foreman/ui/test_computeprofiles.py
- tests/foreman/ui/test_computeresource.py
- tests/foreman/ui/test_computeresource_azurerm.py
- tests/foreman/ui/test_computeresource_ec2.py
- tests/foreman/ui/test_computeresource_gce.py
- tests/foreman/ui/test_computeresource_libvirt.py
- tests/foreman/ui/test_config_group.py
- tests/foreman/ui/test_discoveryrule.py
- tests/foreman/ui/test_operatingsystem.py
- tests/foreman/ui/test_puppetclass.py
- tests/foreman/ui/test_puppetenvironment.py
- tests/foreman/ui/test_smartclassparameter.py
- tests/foreman/ui/test_subnet.py
Some of the rocket team components missing e2e markers for UI tests.
Add the marker which were covering end-to-end scenarios of the respective components.
> Mark UI tests as end-to-end for Rocket Team Components

- .pre-commit-config.yaml
- tests/foreman/cli/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14781
updates:
- [github.com/pre-commit/pre-commit-hooks: v4.4.0 → v4.6.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.4.0...v4.6.0)
- [github.com/astral-sh/ruff-pre-commit: v0.4.1 → v0.4.3](https://github.com/astral-sh/ruff-pre-commit/compare/v0.4.1...v0.4.3)
- [github.com/gitleaks/gitleaks: v8.18.0 → v8.18.2](https://github.com/gitleaks/gitleaks/compare/v8.18.0...v8.18.2)
> [6.14.z] [pre-commit.ci] pre-commit autoupdate

- .pre-commit-config.yaml
- tests/foreman/cli/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14781
updates:
- [github.com/pre-commit/pre-commit-hooks: v4.4.0 → v4.6.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.4.0...v4.6.0)
- [github.com/astral-sh/ruff-pre-commit: v0.4.1 → v0.4.3](https://github.com/astral-sh/ruff-pre-commit/compare/v0.4.1...v0.4.3)
- [github.com/gitleaks/gitleaks: v8.18.0 → v8.18.2](https://github.com/gitleaks/gitleaks/compare/v8.18.0...v8.18.2)
> [6.15.z] [pre-commit.ci] pre-commit autoupdate

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14321
hammer host create did not previously support --lifecycle-environment options, only --lifecycle-environment-id
Now users should be able to create a host with --lifecycle-environment ['name'] set
Automation to create a host using the --lifecycle-environment option
> [6.15.z] [Customer Case] Test for creating a host with lce specified

- robottelo/host_helpers/cli_factory.py
- tests/foreman/api/test_reporttemplates.py
- tests/foreman/cli/test_reporttemplates.py
Tests failures due to trying to promote a content view version out of sequential order. Adding functionality to test on multiple hosts, and adding pytest fixture to tests due to consuming content on containers. 
RHSAT6-45564 test_positive_generate_job_report
RHSAT6-44204 test_positive_generate_entitlements_report_multiple_formats
RHSAT6-44455 test_positive_generate_hostpkgcompare
> [Comp Eval] Updating to test on multiple hosts and fixing test failures

- robottelo/host_helpers/cli_factory.py
- tests/foreman/api/test_reporttemplates.py
- tests/foreman/cli/test_reporttemplates.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14704
Tests failures due to trying to promote a content view version out of sequential order. Adding functionality to test on multiple hosts, and adding pytest fixture to tests due to consuming content on containers. 
RHSAT6-45564 test_positive_generate_job_report
RHSAT6-44204 test_positive_generate_entitlements_report_multiple_formats
RHSAT6-44455 test_positive_generate_hostpkgcompare
> [6.15.z] [Comp Eval] Updating to test on multiple hosts and fixing test failures

- tests/foreman/cli/test_host.py
> fix typo in test_host

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15013
> [6.12.z] fix typo in test_host

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15013
> [6.14.z] fix typo in test_host

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15013
> [6.13.z] fix typo in test_host

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15013
> [6.15.z] fix typo in test_host

- robottelo/utils/vault.py
```
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> Gracious message when vault is not reachable

- robottelo/utils/vault.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14942
``` …
```
> [6.14.z] Gracious message when vault is not reachable

- robottelo/utils/vault.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14942
``` …
```
> [6.15.z] Gracious message when vault is not reachable

- robottelo/utils/vault.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14942
``` …
```
> [6.12.z] Gracious message when vault is not reachable

- robottelo/utils/vault.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14942
``` …
```
> [6.13.z] Gracious message when vault is not reachable

- .pre-commit-config.yaml
- robottelo/host_helpers/api_factory.py
- tests/foreman/cli/test_computeresource_libvirt.py
> [6.12.z] [pre-commit.ci] pre-commit autoupdate (#14781)

- .pre-commit-config.yaml
- robottelo/host_helpers/api_factory.py
- tests/foreman/cli/test_computeresource_libvirt.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14781
updates:
- [github.com/pre-commit/pre-commit-hooks: v4.4.0 → v4.6.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.4.0...v4.6.0)
- [github.com/astral-sh/ruff-pre-commit: v0.4.1 → v0.4.3](https://github.com/astral-sh/ruff-pre-commit/compare/v0.4.1...v0.4.3)
- [github.com/gitleaks/gitleaks: v8.18.0 → v8.18.2](https://github.com/gitleaks/gitleaks/compare/v8.18.0...v8.18.2)
> [6.13.z] [pre-commit.ci] pre-commit autoupdate

- tests/foreman/ui/test_reporttemplates.py
Many tests were failing in the UI due to several issues including outdated code, old non-sca fixtures, and more.
The associated issues were addressed and now passing 
RHSAT6-45606: test_positive_generate_all_installed_packages_report
RHSAT6-44209: test_positive_gen_entitlements_reports_multiple_formats
RHSAT6-40833: test_positive_generate_registered_hosts_report
Update setup_content fixture to use SCA and enabled the custom repo on the Activation Key
docstring changes and manual org.disable for subscription-entitlements report
Rewrite outdated test using new rhel_content fixture
> [Comp Eval] Updating fixture to SCA and Fixing failing tests

- tests/foreman/api/test_contentview.py
- tests/foreman/cli/test_contentview.py
CV API/CLI tests still contained old manifest org usage
Change all usages of entitlement manifest orgs to sca manifest orgs
> [Comp Eval] Change CV CLI/API tests to use SCA Org

- pytest_fixtures/component/activationkey.py
- pytest_fixtures/component/contentview.py
- robottelo/hosts.py
- tests/foreman/api/test_convert2rhel.py
- tests/foreman/api/test_hostcollection.py
- tests/foreman/api/test_registration.py
- tests/foreman/api/test_reporttemplates.py
- tests/foreman/api/test_subscription.py
- tests/foreman/cli/test_activationkey.py
- tests/foreman/cli/test_host.py
- tests/foreman/cli/test_hostcollection.py
- tests/foreman/cli/test_registration.py
- tests/foreman/cli/test_reporttemplates.py
- tests/foreman/cli/test_subscription.py
- tests/foreman/destructive/test_registration.py
- tests/foreman/ui/test_activationkey.py
- tests/foreman/ui/test_ansible.py
- tests/foreman/ui/test_reporttemplates.py
- tests/foreman/ui/test_subscription.py
Robottelo is still using old method of registration using katello-ca certs which is deprecated.
With this PR, all the instances of old method of registration will be replaced with global registration.
> Replace old method of registration with global registration in robottelo

- tests/foreman/api/test_convert2rhel.py
We have pre-conversion check for convert2rhel but missing automation for it.
Added pre-convesion check.
> Add preconversion check for convert2rhel

- robottelo/utils/virtwho.py
- tests/foreman/virtwho/api/test_nutanix.py
- tests/foreman/virtwho/cli/test_esx_sca.py
- tests/foreman/virtwho/cli/test_nutanix.py
- tests/foreman/virtwho/ui/test_nutanix.py
- tests/foreman/virtwho/ui/test_nutanix_sca.py
Code coverage bug2063218, it is a new [RFE]
Test case : PASS
```
(robottelo_vv_615) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/cli/test_esx_sca.py -k test_positive_rhsm_username_option --disable-pytest-warnings -q
1 passed, 39 deselected, 23 warnings in 450.60s (0:07:30)
```
> code coverage bug2063218

- robottelo/utils/virtwho.py
- tests/foreman/virtwho/api/test_nutanix.py
- tests/foreman/virtwho/cli/test_esx_sca.py
- tests/foreman/virtwho/cli/test_nutanix.py
- tests/foreman/virtwho/ui/test_nutanix.py
- tests/foreman/virtwho/ui/test_nutanix_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14308
Code coverage bug2063218, it is a new [RFE]
Test case : PASS
```
(robottelo_vv_615) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/cli/test_esx_sca.py -k test_positive_rhsm_username_option --disable-pytest-warnings -q
1 passed, 39 deselected, 23 warnings in 450.60s (0:07:30)
```
> [6.15.z] code coverage bug2063218

- robottelo/cli/sm_update.py
- tests/foreman/maintain/test_upgrade.py
https://github.com/theforeman/foreman_maintain/pull/802 introduces the `update` command which will replace z stream upgrades.
Update robottelo tests that do a z stream upgrade.
> Update tests for satellite-maintain update command

- robottelo/cli/sm_update.py
- tests/foreman/destructive/test_fm_upgrade.py
Customers are hitting an upgrade issue when ipv6.disable=1 is present in boot options. https://github.com/theforeman/foreman_maintain/pull/847 adds an upgrade check for ipv6.disable.
Add a destructive test to check if this upgrade check is working.
Requires changes from https://github.com/SatelliteQE/robottelo/pull/14883
> Add negative test case for ipv6 enabled in boot options

- tests/foreman/destructive/test_fm_upgrade.py
6.15 cherry-pick for https://github.com/SatelliteQE/robottelo/pull/15062.
> [6.15.z] Add negative test for ipv6 update check

- tests/foreman/ui/test_host.py
The "Export" button in "All Hosts" page does not exports the visible columns as expected.
(https://bugzilla.redhat.com/show_bug.cgi?id=2167146)
New test for exporting only the selected columns in the web UI.
SAT-21626 (component evaluation)
> hosts export selectable columns

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14977
The "Export" button in "All Hosts" page does not exports the visible columns as expected.
(https://bugzilla.redhat.com/show_bug.cgi?id=2167146)
New test for exporting only the selected columns in the web UI.
SAT-21626 (component evaluation)
> [6.15.z] hosts export selectable columns

- tests/foreman/cli/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15049
null
> [6.15.z] Automate BZ 2250732

- tests/foreman/api/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15022
Missing coverage for BZ:1982698, where we verified ansible playbook job template with "hosts: localhost:
Add  test coverage for BZ:1982698, to verifiy ansible-playbook job template with "hosts: localhost"
> [6.15.z] Add test coverage for BZ:1982698

- robottelo/cli/contentview.py
- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14400
Customer Case/CV Eval Automation for https://bugzilla.redhat.com/show_bug.cgi?id=2141421
Also includes a new CLI endpoint "hammer content-view list" to support it.
> [6.15.z] Customer Case Automation - repo ids not being displayed

- tests/foreman/api/test_ansible.py
Missing coverage for BZ:1931489, where we verified timeout to kill/execution_timeout_interval setting is honored by long running ansible-playbook job
Add test coverage for BZ:1931489, to verify long running ansible-playbook job along with timeout to kill/execution_timeout_interval setting
> Add test coverage for BZ:1931489

- robottelo/utils/virtwho.py
- tests/foreman/virtwho/cli/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14273
Code coverage Bug2173870
Test Case : PASS
```
(robottelo_vv_615) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/cli/test_esx_sca.py -k test_positive_post_hypervisors_with_fake_different_org_simultaneous --disable-pytest-warnings -q
1 passed, 39 deselected, 23 warnings in 421.21s (0:07:01)
2024-03-06 23:04:35 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
```
> [6.15.z] codecoverage bug2173870

- tests/foreman/api/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15035
Missing coverage for BZ:1931489, where we verified timeout to kill/execution_timeout_interval setting is honored by long running ansible-playbook job
Add test coverage for BZ:1931489, to verify long running ansible-playbook job along with timeout to kill/execution_timeout_interval setting
> [6.15.z] Add test coverage for BZ:1931489

- tests/foreman/api/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15035
Missing coverage for BZ:1931489, where we verified timeout to kill/execution_timeout_interval setting is honored by long running ansible-playbook job
Add test coverage for BZ:1931489, to verify long running ansible-playbook job along with timeout to kill/execution_timeout_interval setting
> [6.14.z] Add test coverage for BZ:1931489

- tests/foreman/endtoend/test_api_endtoend.py
SAT-22502
All tests under `tests/foreman/endtoend/` now use nailgun through the satellite instance's `api` attribute, and imports of `nailgun.entities` have been removed.
> Remove nailgun.entities imports in tests/foreman/endtoend

- tests/foreman/endtoend/test_api_endtoend.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15083
SAT-22502
All tests under `tests/foreman/endtoend/` now use nailgun through the satellite instance's `api` attribute, and imports of `nailgun.entities` have been removed.
> [6.15.z] Remove nailgun.entities imports in tests/foreman/endtoend

- tests/foreman/endtoend/test_api_endtoend.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15083
SAT-22502
All tests under `tests/foreman/endtoend/` now use nailgun through the satellite instance's `api` attribute, and imports of `nailgun.entities` have been removed.
> [6.13.z] Remove nailgun.entities imports in tests/foreman/endtoend

- pytest_fixtures/component/http_proxy.py
- tests/foreman/cli/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14513
- adds a case for insights client registration via HTTP proxy
- removes old stub covered in foreman-maintain
- updates http_proxy fixture to remove the proxy on teardown
pytest:  tests/foreman/cli/test_http_proxy.py -k insights
> [6.15.z] HTTP Proxy customer cases update

- pytest_fixtures/component/http_proxy.py
- tests/foreman/cli/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14513
- adds a case for insights client registration via HTTP proxy
- removes old stub covered in foreman-maintain
- updates http_proxy fixture to remove the proxy on teardown
pytest:  tests/foreman/cli/test_http_proxy.py -k insights
> [6.14.z] HTTP Proxy customer cases update

- tests/foreman/endtoend/test_api_endtoend.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15083
SAT-22502
All tests under `tests/foreman/endtoend/` now use nailgun through the satellite instance's `api` attribute, and imports of `nailgun.entities` have been removed.
> [6.14.z] Remove nailgun.entities imports in tests/foreman/endtoend

- tests/foreman/cli/test_subnet.py
> Update tests to use fixed mask

- conf/supportability.yaml
> Remove RHEL6 supportability from robottelo

- tests/foreman/cli/test_subnet.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15091
> [6.14.z] Update tests to use fixed mask

- tests/foreman/cli/test_subnet.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15091
> [6.13.z] Update tests to use fixed mask

- conf/supportability.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15012
> [6.13.z] Remove RHEL6 supportability from robottelo

- conf/supportability.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15012
> [6.15.z] Remove RHEL6 supportability from robottelo

- conf/supportability.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15012
> [6.14.z] Remove RHEL6 supportability from robottelo

- conf/supportability.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15012
> [6.12.z] Remove RHEL6 supportability from robottelo

- tests/foreman/sys/test_pulp3_filesystem.py
In parametrize section line '/var/lib/pulp' was redundant.
In remaining parametrize path it is already covering the above path.
Removing redundant line which is no longer required.
> removed unnecessary line

- tests/foreman/cli/test_subnet.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15091
> [6.15.z] Update tests to use fixed mask

- tests/foreman/sys/test_pulp3_filesystem.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15092
In parametrize section line '/var/lib/pulp' was redundant.
In remaining parametrize path it is already covering the above path.
Removing redundant line which is no longer required.
> [6.15.z] removed unnecessary line

- tests/foreman/sys/test_pulp3_filesystem.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15092
In parametrize section line '/var/lib/pulp' was redundant.
In remaining parametrize path it is already covering the above path.
Removing redundant line which is no longer required.
> [6.14.z] removed unnecessary line

- tests/foreman/cli/test_subnet.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15091
> [6.12.z] Update tests to use fixed mask

- conf/supportability.yaml
- pytest_fixtures/component/os.py
- robottelo/config/validators.py
FIxes failed cherry pick https://github.com/SatelliteQE/robottelo/issues/14968
> [6.15.z] Make default_os name and major versions configurable

- robottelo/constants/__init__.py
- tests/foreman/api/test_templatesync.py
The number of total templates and templates
containing robottelo should match this repo and branch https://github.com/SatelliteQE/foreman_templates/tree/automation
I have no idea why it was once changed to a wrong number without further explanation:
https://github.com/SatelliteQE/robottelo/commit/95434f5e3b184732fe963874d19b747a02241edb
> Fix number of imported templates

- robottelo/constants/__init__.py
- tests/foreman/api/test_templatesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14376
The number of total templates and templates
containing robottelo should match this repo and branch https://github.com/SatelliteQE/foreman_templates/tree/automation
I have no idea why it was once changed to a wrong number without further explanation:
https://github.com/SatelliteQE/robottelo/commit/95434f5e3b184732fe963874d19b747a02241edb
> [6.15.z] Fix number of imported templates

- robottelo/cli/host.py
- tests/foreman/cli/test_host.py
sca default in 6.16
rid of sca_disable
> katello_host_tools_host no disable sca

- tests/foreman/cli/test_satellitesync.py
Coverage for [BZ#2233162](https://bugzilla.redhat.com/show_bug.cgi?id=2233162) is missing
This PR.
`metadata.json` is the only exception where restrictive permissions are expected
pytest: tests/foreman/cli/test_satellitesync.py -k permissions
> Add test for syncable export with restrictive permissions

- pytest_fixtures/component/repository.py
- requirements-optional.txt
- robottelo/cli/base.py
- robottelo/host_helpers/api_factory.py
- robottelo/host_helpers/repository_mixins.py
- robottelo/host_helpers/satellite_mixins.py
- robottelo/hosts.py
- robottelo/utils/datafactory.py
- robottelo/utils/report_portal/portal.py
- tests/foreman/api/test_notifications.py
- tests/foreman/api/test_permission.py
- tests/foreman/cli/test_oscap.py
- tests/foreman/longrun/test_oscap.py
This PR backports #15114 to 6.15.z
Closes #14848 #15116
> [6.15.z] Bump sphinx-autoapi from 3.0.0 to 3.1.0

- pytest_fixtures/component/repository.py
- requirements-optional.txt
- robottelo/cli/base.py
- robottelo/host_helpers/api_factory.py
- robottelo/host_helpers/repository_mixins.py
- robottelo/host_helpers/satellite_mixins.py
- robottelo/hosts.py
- robottelo/utils/datafactory.py
- robottelo/utils/report_portal/portal.py
- tests/foreman/api/test_notifications.py
- tests/foreman/api/test_permission.py
- tests/foreman/cli/test_oscap.py
- tests/foreman/longrun/test_oscap.py
This PR backports #15114 to 6.14.z
Closes #14846  #15119
> [6.14.z] Bump sphinx-autoapi from 3.0.0 to 3.1.0

- pytest_fixtures/component/computeprofile.py
- pytest_fixtures/component/host.py
- pytest_fixtures/component/hostgroup.py
- pytest_fixtures/component/os.py
- pytest_fixtures/component/oscap.py
- pytest_fixtures/component/provisioning_template.py
- pytest_fixtures/component/repository.py
- pytest_fixtures/component/satellite_auth.py
- pytest_fixtures/component/subnet.py
- pytest_fixtures/component/user.py
- pytest_fixtures/component/user_role.py
SAT-22530
All fixtures under `pytest_fixtures/` now use nailgun through the satellite instance's `api` attribute, and imports of `nailgun.entities` have been removed.
Test results are the same before and after these changes.
PRT job #6979:
```
18:53:58  =========================== short test summary info ============================
18:53:58  FAILED tests/foreman/api/test_host.py::test_positive_create_and_update_with_user [...]
18:53:58  FAILED tests/foreman/ui/test_ldap_authentication.py::test_verify_group_permissions [...]
18:53:58  ERROR tests/foreman/api/test_oscappolicy.py::TestOscapPolicy::test_positive_crud_scap_policy [...]
18:53:58  = 2 failed, 13 passed, 1 skipped, 617 warnings, 1 …
```
> Remove nailgun.entities imports in pytest_fixtures

- pytest_fixtures/component/repository.py
- requirements-optional.txt
- robottelo/cli/base.py
- robottelo/host_helpers/api_factory.py
- robottelo/host_helpers/repository_mixins.py
- robottelo/host_helpers/satellite_mixins.py
- robottelo/hosts.py
- robottelo/utils/datafactory.py
- robottelo/utils/report_portal/portal.py
- tests/foreman/api/test_permission.py
- tests/foreman/cli/test_oscap.py
- tests/foreman/longrun/test_oscap.py
This PR backports #15114 to 6.13.z
Closes #14849 #15117
> [6.13.z] Bump sphinx-autoapi from 3.0.0 to 3.1.0

- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15068
Coverage for [BZ#2153523](https://bugzilla.redhat.com/show_bug.cgi?id=2153523) is missing.
This PR.
pytest: tests/foreman/cli/test_contentview.py -k pattern
> [6.15.z] Add test case for CCV promotion to a non-default LCE

- tests/foreman/cli/test_repository.py
Several file-repo tests have been failing too long for a wrong assertion message.
Fix them all with this PR in a near term.
pytest: tests/foreman/cli/test_repository.py -k 'upload_remove_srpm_content or upload_file_to_file_repo or remove_file or file_repo_contains_only_newer_file'
> Fix assertions in file repo tests

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15138
Several file-repo tests have been failing too long for a wrong assertion message.
Fix them all with this PR in a near term.
pytest: tests/foreman/cli/test_repository.py -k 'upload_remove_srpm_content or upload_file_to_file_repo or remove_file or file_repo_contains_only_newer_file'
> [6.15.z] Fix assertions in file repo tests

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15138
Several file-repo tests have been failing too long for a wrong assertion message.
Fix them all with this PR in a near term.
pytest: tests/foreman/cli/test_repository.py -k 'upload_remove_srpm_content or upload_file_to_file_repo or remove_file or file_repo_contains_only_newer_file'
> [6.13.z] Fix assertions in file repo tests

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15138
Several file-repo tests have been failing too long for a wrong assertion message.
Fix them all with this PR in a near term.
pytest: tests/foreman/cli/test_repository.py -k 'upload_remove_srpm_content or upload_file_to_file_repo or remove_file or file_repo_contains_only_newer_file'
> [6.14.z] Fix assertions in file repo tests

- tests/foreman/api/test_reporttemplates.py
- tests/foreman/cli/test_reporttemplates.py
Reporting component eval. Adding cloning to end to end tests, fixing failing tests, and adding new tests for installing errata by search
RHSAT6-44110
RHSAT6-44106
RHSAT6-40840
RHSAT6-45564
> [Comp Eval]  Fixing tests and adding support for errata install by search

- tests/foreman/cli/test_syncplan.py
Customer scenario coverage for bz#2015344
Check if non UTC datetime is processed correctly by hammer
> test syncplan creation with custom timezone

- tests/foreman/ui/test_jobtemplate.py
request from the component evaluation -- to check if cloned template can be exported successfully.  
extending the UI test as we don't have the clone functionality in hammer job-template right now
> test export of cloned template

- robottelo/constants/__init__.py
> Fix constant for cloudinit image in Azure

- robottelo/hosts.py
If a UI test is using the new session approach via `target_sat.ui_session()`,
the browser window is not closed at the end of the test.
Also the screenshot is not taken if the test fails.
`Satellite.ui_session()` method needs to return the airgun `Session` as a context manager,
so the `__exit__` method is called, which handles screenshot capture and closing the browser window.
> ui_session: return airgun session as a context manager

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15139
> [6.15.z] Fix constant for cloudinit image in Azure

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15139
> [6.13.z] Fix constant for cloudinit image in Azure

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15139
> [6.14.z] Fix constant for cloudinit image in Azure

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15139
> [6.12.z] Fix constant for cloudinit image in Azure

- tests/foreman/ui/test_jobtemplate.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15130
request from the component evaluation -- to check if cloned template can be exported successfully.  
extending the UI test as we don't have the clone functionality in hammer job-template right now
> [6.15.z] test export of cloned template

- tests/foreman/api/test_remoteexecution.py
In the past I have created this test as a spin-off from a larger test, but I didn't include all necessary setup parts for pull-mode to work. I humbly post this fix
Note that currently there's a reported bug preventing pull mode rex from working on rhel9 backend but the next snap should carry th fix
> fix in pull mode longrun test

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14977
The "Export" button in "All Hosts" page does not exports the visible columns as expected.
(https://bugzilla.redhat.com/show_bug.cgi?id=2167146)
New test for exporting only the selected columns in the web UI.
SAT-21626 (component evaluation)
> [6.14.z] hosts export selectable columns

- tests/foreman/cli/test_contentview.py
Fix missing self call forgotten in https://github.com/SatelliteQE/robottelo/pull/14678
tests/foreman/cli/test_contentview.py::TestContentView::test_positive_update_composite_with_component_ids
> Fix missing self

- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15184
Fix missing self call forgotten in https://github.com/SatelliteQE/robottelo/pull/14678
tests/foreman/cli/test_contentview.py::TestContentView::test_positive_update_composite_with_component_ids
> [6.15.z] Fix missing self

- tests/foreman/ui/test_contenthost.py
The `test_positive_check_ignore_facts_os_setting` fails in teardown with
```
failed on teardown with "TypeError: set_ignore_facts_for_os() missing 1 required positional argument: 'module_target_sat'"
```
This PR, hopefully.
pytest: tests/foreman/ui/test_contenthost.py -k test_positive_check_ignore_facts_os_setting
> Fix content host finalizer

- tests/foreman/ui/test_contenthost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15186
The `test_positive_check_ignore_facts_os_setting` fails in teardown with
```
failed on teardown with "TypeError: set_ignore_facts_for_os() missing 1 required positional argument: 'module_target_sat'"
```
This PR, hopefully.
pytest: tests/foreman/ui/test_contenthost.py -k test_positive_check_ignore_facts_os_setting
> [6.15.z] Fix content host finalizer

- tests/upgrades/test_contentview.py
It looks like the previous reorder done in https://github.com/SatelliteQE/robottelo/pull/14036 on Mar 15 has broken the test teardown since we now attempt to destroy the repo before we destroy the CV where it is published in, so we get 500:
```
DEBUG    nailgun.client:client.py:105 Making HTTP DELETE request to https://satellite.redhat.com/katello/api/v2/repositories/1118 with options {'auth': None, 'verify': None, 'headers': {'content-type': 'application/json'}}, no params and no data.
WARNING  nailgun.client:client.py:126 Received HTTP 500 response: {"displayMessage":"Repository cannot be deleted since it has already been included in a published Content View. Please delete all Content View versions containing this repository before attempting to delete it.","errors":["Repository cannot …
```
> Reorder finalizers in CV upgrade test

- pytest_fixtures/core/contenthosts.py
- tests/foreman/api/test_capsulecontent.py
- tests/foreman/cli/test_container_management.py
Some of our tests are failing to pull docker images with OCI artifacts using obsolete version of docker client provided by RHEL7 extras repo.
(see [BZ#2262793](https://bugzilla.redhat.com/show_bug.cgi?id=2262793))
Let's move forward to RHEL8 and newer version of podman/docker.
Proposed changes in this PR:
1. Use RHEL8 with newer podman/docker client.
2. Rescope `container_contenthost` fixture to module. This speeds up current tests from ~45 minutes to ~15 minutes. The downside is we need to ensure `podman logout` is performed on teardown (via `request.addfinalizer`).
With the new podman new issue was identified (which has not been hit with the old docker client): https://issues.redhat.com/browse/SAT-25328
Since the [fix PR](https://github.com/Katello/katello/pull/11006) is up already, …
> Use RHEL8 for container contenthost

- tests/upgrades/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15185
It looks like the previous reorder done in https://github.com/SatelliteQE/robottelo/pull/14036 on Mar 15 has broken the test teardown since we now attempt to destroy the repo before we destroy the CV where it is published in, so we get 500:
```
DEBUG    nailgun.client:client.py:105 Making HTTP DELETE request to https://satellite.redhat.com/katello/api/v2/repositories/1118 with options {'auth': None, 'verify': None, 'headers': {'content-type': 'application/json'}}, no params and no data.
WARNING  nailgun.client:client.py:126 Received HTTP 500 response: {"displayMessage":"Repository cannot be deleted since it has already been included in a published Content View. Please delete all Content View versions containing this …
```
> [6.15.z] Reorder finalizers in CV upgrade test

- tests/upgrades/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15185
It looks like the previous reorder done in https://github.com/SatelliteQE/robottelo/pull/14036 on Mar 15 has broken the test teardown since we now attempt to destroy the repo before we destroy the CV where it is published in, so we get 500:
```
DEBUG    nailgun.client:client.py:105 Making HTTP DELETE request to https://satellite.redhat.com/katello/api/v2/repositories/1118 with options {'auth': None, 'verify': None, 'headers': {'content-type': 'application/json'}}, no params and no data.
WARNING  nailgun.client:client.py:126 Received HTTP 500 response: {"displayMessage":"Repository cannot be deleted since it has already been included in a published Content View. Please delete all Content View versions containing this …
```
> [6.13.z] Reorder finalizers in CV upgrade test

- tests/foreman/ui/test_contenthost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15186
The `test_positive_check_ignore_facts_os_setting` fails in teardown with
```
failed on teardown with "TypeError: set_ignore_facts_for_os() missing 1 required positional argument: 'module_target_sat'"
```
This PR, hopefully.
pytest: tests/foreman/ui/test_contenthost.py -k test_positive_check_ignore_facts_os_setting
> [6.14.z] Fix content host finalizer

- tests/foreman/virtwho/ui/test_esx_sca.py
- tests/foreman/virtwho/ui/test_hyperv_sca.py
- tests/foreman/virtwho/ui/test_kubevirt_sca.py
- tests/foreman/virtwho/ui/test_libvirt_sca.py
- tests/foreman/virtwho/ui/test_nutanix_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15064
add hypervisor host and guest subscription status and mapping check mapping
Cases PASS:
```
robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_deploy_configure_by_id_script --disable-pytest-warnings -q
2 passed, 34 deselected, 29 warnings in 539.09s (0:08:59)
2024-05-21 00:27:04 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest …
```
> [6.14.z] add hypervisor host and guest subscription status and mapping check mapping

- tests/foreman/virtwho/ui/test_esx_sca.py
- tests/foreman/virtwho/ui/test_hyperv_sca.py
- tests/foreman/virtwho/ui/test_kubevirt_sca.py
- tests/foreman/virtwho/ui/test_libvirt_sca.py
- tests/foreman/virtwho/ui/test_nutanix_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15064
add hypervisor host and guest subscription status and mapping check mapping
Cases PASS:
```
robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_deploy_configure_by_id_script --disable-pytest-warnings -q
2 passed, 34 deselected, 29 warnings in 539.09s (0:08:59)
2024-05-21 00:27:04 - robottelo - WARNING - missing grid_url or session_id. unable to clean video files.
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest …
```
> [6.15.z] add hypervisor host and guest subscription status and mapping check mapping

- requirements.txt
- tests/foreman/ui/test_syncplan.py
The sleeps in these tests result in inconsistent behavior and the cron expression is malformed, leading to 2 seperate faliures. This PR will fix both.
Removed the sleep by setting max_tries to 20 on the task poll, reformatted the cron expression to always accurately set the sync time to 5 minutes after the plan is created. 5 minutes is required here due to slow interactions with the UI sometimes resulting in the product not being added until after the sync time had passed.
pytest: tests/foreman/ui/test_contenthost.py -k 'test_positive_synchronize_custom_product_custom_cron_real_time'
> Remove sleeps and make cron expression more accurate

- tests/foreman/ui/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15172
The sleeps in these tests result in inconsistent behavior and the cron expression is malformed, leading to 2 seperate faliures. This PR will fix both.
Removed the sleep by setting max_tries to 20 on the task poll, reformatted the cron expression to always accurately set the sync time to 5 minutes after the plan is created. 5 minutes is required here due to slow interactions with the UI sometimes resulting in the product not being added until after the sync time had passed.
pytest: tests/foreman/ui/test_contenthost.py -k 'test_positive_synchronize_custom_product_custom_cron_real_time'
> [6.14.z] Remove sleeps and make cron expression more accurate

- tests/foreman/ui/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15172
The sleeps in these tests result in inconsistent behavior and the cron expression is malformed, leading to 2 seperate faliures. This PR will fix both.
Removed the sleep by setting max_tries to 20 on the task poll, reformatted the cron expression to always accurately set the sync time to 5 minutes after the plan is created. 5 minutes is required here due to slow interactions with the UI sometimes resulting in the product not being added until after the sync time had passed.
pytest: tests/foreman/ui/test_contenthost.py -k 'test_positive_synchronize_custom_product_custom_cron_real_time'
> [6.15.z] Remove sleeps and make cron expression more accurate

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15050
If a UI test is using the new session approach via `target_sat.ui_session()`,
the browser window is not closed at the end of the test.
Also the screenshot is not taken if the test fails.
`Satellite.ui_session()` method needs to return the airgun `Session` as a context manager,
so the `__exit__` method is called, which handles screenshot capture and closing the browser window.
> [6.12.z] ui_session: return airgun session as a context manager

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15050
If a UI test is using the new session approach via `target_sat.ui_session()`,
the browser window is not closed at the end of the test.
Also the screenshot is not taken if the test fails.
`Satellite.ui_session()` method needs to return the airgun `Session` as a context manager,
so the `__exit__` method is called, which handles screenshot capture and closing the browser window.
> [6.15.z] ui_session: return airgun session as a context manager

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15050
If a UI test is using the new session approach via `target_sat.ui_session()`,
the browser window is not closed at the end of the test.
Also the screenshot is not taken if the test fails.
`Satellite.ui_session()` method needs to return the airgun `Session` as a context manager,
so the `__exit__` method is called, which handles screenshot capture and closing the browser window.
> [6.13.z] ui_session: return airgun session as a context manager

- tests/foreman/api/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15149
In the past I have created this test as a spin-off from a larger test, but I didn't include all necessary setup parts for pull-mode to work. I humbly post this fix
Note that currently there's a reported bug preventing pull mode rex from working on rhel9 backend but the next snap should carry th fix
> [6.13.z] fix in pull mode longrun test

- tests/foreman/cli/test_contentaccess.py
- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_discoveryrule.py
- tests/foreman/cli/test_hostgroup.py
- tests/foreman/cli/test_ldapauthsource.py
- tests/foreman/cli/test_oscap.py
- tests/foreman/cli/test_ostreebranch.py
- tests/foreman/cli/test_repository.py
- tests/foreman/cli/test_subscription.py
- tests/foreman/cli/test_syncplan.py
- tests/foreman/cli/test_templatesync.py
- tests/foreman/cli/test_user.py
SAT-22500
All tests under tests/foreman/cli/ now use nailgun through the satellite instance's `api` attribute, and imports of `nailgun.entities` have been removed.
PRT results are the same before and after these changes:
PRT job #6928:
```
16:11:32  =========================== short test summary info ============================
16:11:32  FAILED tests/foreman/cli/test_ldapauthsource.py::TestIPAAuthSource::test_usergroup_sync_with_refresh - robottelo.hosts.IPAHostError: Failed to add the user to usergroup
16:11:32  FAILED tests/foreman/cli/test_repository.py::TestFileRepository::test_positive_upload_file_to_file_repo[0] - assert "Successfully uploaded file 'which-2.19-6.el6.x86_64.rpm'" in …
```
> Remove nailgun.entities imports in tests/foreman/cli

- tests/foreman/cli/test_leapp_client.py
- tests/foreman/ui/test_computeprofiles.py
- tests/foreman/ui/test_computeresource.py
- tests/foreman/ui/test_computeresource_azurerm.py
- tests/foreman/ui/test_computeresource_ec2.py
- tests/foreman/ui/test_computeresource_gce.py
- tests/foreman/ui/test_computeresource_libvirt.py
- tests/foreman/ui/test_config_group.py
- tests/foreman/ui/test_discoveryrule.py
- tests/foreman/ui/test_operatingsystem.py
- tests/foreman/ui/test_puppetclass.py
- tests/foreman/ui/test_puppetenvironment.py
- tests/foreman/ui/test_smartclassparameter.py
- tests/foreman/ui/test_subnet.py
Manual Cherrypick of https://github.com/SatelliteQE/robottelo/pull/14702
> [6.15.z Cherrypick]Mark UI tests as end-to-end for Rocket Team Components

- tests/foreman/cli/test_contentcredentials.py
In Stream runs, for ContentCredentials, we see some occasional failures in several tests, 
that attempt to add/update gpg key associated to repo/product with repo(s), then read info of the product/repo and assert the key name:
```
... setup custom repo, GPG key, add key to repo or repo's product,
or update a GPG key already added to repo(s)
repo = target_sat.cli.Repository.info({'id': repo['id']}) 
assert repo['gpg-key'].get('name') == new_name
E   KeyError: 'gpg-key'
```
We need to wait for an in-progress _**Repository Metadata Generate task**_, 
that is not handled synchronously by cli `.update` or cli `.info`. Else, the GPG key is not yet present in repo/product.
In any CLI tests adding/updating a GPG key associated to repo, or adding the key to a product containing repos, 
we should …
> ContentCredentials CLI fix for stream

- tests/foreman/cli/test_contentcredentials.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15165
In Stream runs, for ContentCredentials, we see some occasional failures in several tests, 
that attempt to add/update gpg key associated to repo/product with repo(s), then read info of the product/repo and assert the key name:
```
... setup custom repo, GPG key, add key to repo or repo's product,
or update a GPG key already added to repo(s)
repo = target_sat.cli.Repository.info({'id': repo['id']}) 
assert repo['gpg-key'].get('name') == new_name
E   KeyError: 'gpg-key'
```
We need to wait for an in-progress _**Repository Metadata Generate task**_, 
that is not handled synchronously by cli `.update` or cli `.info`. Else, the GPG key is not yet present in repo/product.
In any CLI tests adding/updating a GPG key associated …
> [6.16.z] ContentCredentials CLI fix for stream

- pytest_plugins/metadata_markers.py
We need case insensitive test collection component-wise
Added marker for component-wise test collection
result:
pytest tests/foreman/ --component auditlog
collected 5434 items / 5426 deselected / 8 selected                                                                                              
```
tests/foreman/api/test_audit.py ✓✓✓                                                                                                38% ███▊      
tests/foreman/ui/test_audit.py ✓✓✓✓✓                                                                                              100% ██████████
```
=======================================================
> Add marker for case insensitive test collection by component and importance

- pytest_fixtures/component/http_proxy.py
In #14513 I overlooked that `http_proxy` can be even `None` which does not implement the `delete()` method so the teardown fails with
```
pytest_fixtures/component/http_proxy.py:32: in setup_http_proxy
http_proxy.delete()
E   AttributeError: 'NoneType' object has no attribute 'delete'
```
Delete only existing objects.
> Fix HTTP proxy teardown

- pytest_fixtures/component/http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15229
In #14513 I overlooked that `http_proxy` can be even `None` which does not implement the `delete()` method so the teardown fails with
```
pytest_fixtures/component/http_proxy.py:32: in setup_http_proxy
http_proxy.delete()
E   AttributeError: 'NoneType' object has no attribute 'delete'
```
Delete only existing objects.
> [6.16.z] Fix HTTP proxy teardown

- pytest_fixtures/component/http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15229
In #14513 I overlooked that `http_proxy` can be even `None` which does not implement the `delete()` method so the teardown fails with
```
pytest_fixtures/component/http_proxy.py:32: in setup_http_proxy
http_proxy.delete()
E   AttributeError: 'NoneType' object has no attribute 'delete'
```
Delete only existing objects.
> [6.14.z] Fix HTTP proxy teardown

- pytest_fixtures/component/http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15229
In #14513 I overlooked that `http_proxy` can be even `None` which does not implement the `delete()` method so the teardown fails with
```
pytest_fixtures/component/http_proxy.py:32: in setup_http_proxy
http_proxy.delete()
E   AttributeError: 'NoneType' object has no attribute 'delete'
```
Delete only existing objects.
> [6.15.z] Fix HTTP proxy teardown

- tests/foreman/cli/test_contentaccess.py
- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_discoveryrule.py
- tests/foreman/cli/test_hostgroup.py
- tests/foreman/cli/test_ldapauthsource.py
- tests/foreman/cli/test_oscap.py
- tests/foreman/cli/test_ostreebranch.py
- tests/foreman/cli/test_repository.py
- tests/foreman/cli/test_subscription.py
- tests/foreman/cli/test_syncplan.py
- tests/foreman/cli/test_templatesync.py
- tests/foreman/cli/test_user.py
SAT-22500
All tests under tests/foreman/cli/ now use nailgun through the satellite instance's `api` attribute, and imports of `nailgun.entities` have been removed.
> [6.14.z] Remove nailgun.entities imports in tests/foreman/cli

- tests/foreman/cli/test_contentaccess.py
- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_discoveryrule.py
- tests/foreman/cli/test_hostgroup.py
- tests/foreman/cli/test_ldapauthsource.py
- tests/foreman/cli/test_oscap.py
- tests/foreman/cli/test_ostreebranch.py
- tests/foreman/cli/test_repository.py
- tests/foreman/cli/test_subscription.py
- tests/foreman/cli/test_syncplan.py
- tests/foreman/cli/test_templatesync.py
- tests/foreman/cli/test_user.py
SAT-22500
All tests under tests/foreman/cli/ now use nailgun through the satellite instance's `api` attribute, and imports of `nailgun.entities` have been removed.
> [6.15.z] Remove nailgun.entities imports in tests/foreman/cli

- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_contentviewfilter.py
- tests/foreman/ui/test_contentview_old.py
CV component eval proposes several changes to be done for content view tests.
This PR addresses some of them, mostly merges and some minor modifications. In particular:
1. `test_positive_remove_cv_version_from_env` is merged with `test_positive_remove_cv_version_from_multi_env`
2. `test_positive_promote_with_docker_repo_composite` is merged with `test_positive_promote_multiple_with_docker_repo_composite`
3. `test_positive_add_custom_repo_by_name` is parametrized for adding repo by `id` and incorrect BZ reference is removed
4. `test_negative_update_with_name` another test case where incorrect BZ reference is removed
5. `test_positive_arbitrary_file_sync_over_capsule` is removed since it is already implemented in [test_positive_sync_file_repo](https://github.com/SatelliteQE/robottelo/blob/ac …
> Updates for CV component eval

- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_contentviewfilter.py
- tests/foreman/ui/test_contentview_old.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15043
CV component eval proposes several changes to be done for content view tests.
This PR addresses some of them, mostly merges and some minor modifications. In particular:
1. `test_positive_remove_cv_version_from_env` is merged with `test_positive_remove_cv_version_from_multi_env`
2. `test_positive_promote_with_docker_repo_composite` is merged with `test_positive_promote_multiple_with_docker_repo_composite`
3. `test_positive_add_custom_repo_by_name` is parametrized for adding repo by `id` and incorrect BZ reference is removed
4. `test_negative_update_with_name` another test case where incorrect BZ reference is removed
5. `test_positive_arbitrary_file_sync_over_capsule` is removed since it is already implemented in …
> [6.16.z] Updates for CV component eval

- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_contentviewfilter.py
- tests/foreman/ui/test_contentview_old.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15043
CV component eval proposes several changes to be done for content view tests.
This PR addresses some of them, mostly merges and some minor modifications. In particular:
1. `test_positive_remove_cv_version_from_env` is merged with `test_positive_remove_cv_version_from_multi_env`
2. `test_positive_promote_with_docker_repo_composite` is merged with `test_positive_promote_multiple_with_docker_repo_composite`
3. `test_positive_add_custom_repo_by_name` is parametrized for adding repo by `id` and incorrect BZ reference is removed
4. `test_negative_update_with_name` another test case where incorrect BZ reference is removed
5. `test_positive_arbitrary_file_sync_over_capsule` is removed since it is already implemented in …
> [6.15.z] Updates for CV component eval

- .github/CODEOWNERS
- robottelo/cli/contentview.py
- robottelo/cli/product.py
- robottelo/cli/repository.py
- tests/foreman/cli/test_artifacts.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/14976
> [6.16.z] Add test case to verify artifacts repair at the Satellite side

- robottelo/config/__init__.py
- tests/foreman/destructive/test_discoveredhost.py
Remove nailgun entity_mixin import from discovery tests, and replace entity_mixins.DEFAULT_SERVER_CONFIG 
Replacing entity_mixins.DEFAULT_SERVER_CONFIG with new default_nailgun_config method, which is same as existing user_nailgun_config method
And, we don't have any automated tests under this module, verifying default_nailgun_config() method in https://github.com/SatelliteQE/robottelo/pull/15163
> Remove nailgun entity_mixin import from discovery tests

- robottelo/config/__init__.py
- tests/foreman/destructive/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15164
Remove nailgun entity_mixin import from discovery tests, and replace entity_mixins.DEFAULT_SERVER_CONFIG 
Replacing entity_mixins.DEFAULT_SERVER_CONFIG with new default_nailgun_config method, which is same as existing user_nailgun_config method
And, we don't have any automated tests under this module, verifying default_nailgun_config() method in https://github.com/SatelliteQE/robottelo/pull/15163
> [6.15.z] Remove nailgun entity_mixin import from discovery tests

- robottelo/config/__init__.py
- tests/foreman/destructive/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15164
Remove nailgun entity_mixin import from discovery tests, and replace entity_mixins.DEFAULT_SERVER_CONFIG 
Replacing entity_mixins.DEFAULT_SERVER_CONFIG with new default_nailgun_config method, which is same as existing user_nailgun_config method
And, we don't have any automated tests under this module, verifying default_nailgun_config() method in https://github.com/SatelliteQE/robottelo/pull/15163
> [6.14.z] Remove nailgun entity_mixin import from discovery tests

- robottelo/config/__init__.py
- tests/foreman/destructive/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15164
Remove nailgun entity_mixin import from discovery tests, and replace entity_mixins.DEFAULT_SERVER_CONFIG 
Replacing entity_mixins.DEFAULT_SERVER_CONFIG with new default_nailgun_config method, which is same as existing user_nailgun_config method
And, we don't have any automated tests under this module, verifying default_nailgun_config() method in https://github.com/SatelliteQE/robottelo/pull/15163
> [6.13.z] Remove nailgun entity_mixin import from discovery tests

- tests/foreman/destructive/test_clone.py
We missed a satellite-clone breaking bug when upgrading to RHEL 8.10. See SAT-25484
Let's run the actual cloning process on PIT server
> Add PIT marker to clone tests

- tests/foreman/destructive/test_clone.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15243
We missed a satellite-clone breaking bug when upgrading to RHEL 8.10. See SAT-25484
Let's run the actual cloning process on PIT server
> [6.14.z] Add PIT marker to clone tests

- tests/foreman/destructive/test_clone.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15243
We missed a satellite-clone breaking bug when upgrading to RHEL 8.10. See SAT-25484
Let's run the actual cloning process on PIT server
> [6.13.z] Add PIT marker to clone tests

- tests/foreman/destructive/test_ansible.py
Currently, test_positive_import_all_roles covers only admin scenario to import all roles via UI, and as part of component audit its suggest to modify this test to cover non-admin user scenario
> Modify test_positive_import_all_roles to cover non-admin scenario

- tests/foreman/destructive/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15171
Currently, test_positive_import_all_roles covers only admin scenario to import all roles via UI, and as part of component audit its suggest to modify this test to cover non-admin user scenario
> [6.14.z] Modify test_positive_import_all_roles to cover non-admin scenario

- tests/foreman/longrun/test_inc_updates.py
- tests/foreman/longrun/test_oscap.py
SAT-22504
All tests under `tests/foreman/longrun/` now use nailgun through the satellite instance's `api` attribute, and imports of `nailgun.entities` have been removed.
Test results are the same before and after these changes, and the test failure is unrelated.
PRT:
job/robottelo-pr-testing/7183/console
```
14:59:31  =========================== short test summary info ============================
14:59:31  ERROR tests/foreman/longrun/test_oscap.py::test_positive_oscap_run_via_ansible[rhel7] - robottelo.exceptions.CLIReturnCodeError: CLIReturnCodeError(status=70, stderr='Error: scap_content not found.\n', msg='Command "scap-content info" finished with status 70\nstderr contains:\nError: …
```
> Remove nailgun.entities imports in tests/foreman/longrun

- tests/foreman/destructive/test_clone.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15243
We missed a satellite-clone breaking bug when upgrading to RHEL 8.10. See SAT-25484
Let's run the actual cloning process on PIT server
> [6.15.z] Add PIT marker to clone tests

- tests/foreman/ui/test_ansible.py
Currently, test_positive_ansible_custom_role covers only admin scenario, and as part of component audit its suggest to modify this test to cover non-admin user scenario
> Modify test_positive_ansible_custom_role to cover non-admin user scenario

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15163
Currently, test_positive_ansible_custom_role covers only admin scenario, and as part of component audit its suggest to modify this test to cover non-admin user scenario
> [6.15.z] Modify test_positive_ansible_custom_role to cover non-admin user scenario

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15163
Currently, test_positive_ansible_custom_role covers only admin scenario, and as part of component audit its suggest to modify this test to cover non-admin user scenario
> [6.14.z] Modify test_positive_ansible_custom_role to cover non-admin user scenario

- tests/foreman/longrun/test_inc_updates.py
- tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15220
SAT-22504
All tests under `tests/foreman/longrun/` now use nailgun through the satellite instance's `api` attribute, and imports of `nailgun.entities` have been removed.
> [6.13.z] Remove nailgun.entities imports in tests/foreman/longrun

- tests/foreman/longrun/test_inc_updates.py
- tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15220
SAT-22504
All tests under `tests/foreman/longrun/` now use nailgun through the satellite instance's `api` attribute, and imports of `nailgun.entities` have been removed.
> [6.14.z] Remove nailgun.entities imports in tests/foreman/longrun

- tests/foreman/longrun/test_inc_updates.py
- tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15220
SAT-22504
All tests under `tests/foreman/longrun/` now use nailgun through the satellite instance's `api` attribute, and imports of `nailgun.entities` have been removed.
> [6.15.z]  Remove nailgun.entities imports in tests/foreman/longrun

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15163
Currently, test_positive_ansible_custom_role covers only admin scenario, and as part of component audit its suggest to modify this test to cover non-admin user scenario
> [6.13.z] Modify test_positive_ansible_custom_role to cover non-admin user scenario

- pytest_plugins/metadata_markers.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15005
We need case insensitive test collection component-wise
Added marker for component-wise test collection
result:
pytest tests/foreman/ --component auditlog
collected 5434 items / 5426 deselected / 8 selected                                                                                              
```
tests/foreman/api/test_audit.py ✓✓✓                                                                                                38% ███▊      
tests/foreman/ui/test_audit.py ✓✓✓✓✓                                                                                              100% ██████████
```
=======================================================
> [6.15.z] Add marker for case insensitive test collection by component and importance

- conf/subscription.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/api/test_eol_banner.py
This supplements tests for the EOL banner feature. The eol date for the version is defined in the satellite-lifecycle package (so that there is the same solution for connected and disconnected sats). This test aims to check the date in the package is correctly updated. 
Comparing the date from the package with the date from the lifecycle api.
Keeping in draft state, as the EOL banner just got to 6.15, but not yet to older releases and the lifecycle api contains data only for released versions
satellite-jenkins MR 1185
> eol version check

- conf/subscription.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/api/test_eol_banner.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13253
This supplements tests for the EOL banner feature. The eol date for the version is defined in the satellite-lifecycle package (so that there is the same solution for connected and disconnected sats). This test aims to check the date in the package is correctly updated. 
Comparing the date from the package with the date from the lifecycle api.
Keeping in draft state, as the EOL banner just got to 6.15, but not yet to older releases and the lifecycle api contains data only for released versions
satellite-jenkins MR 1185
> [6.14.z] eol version check

- tests/foreman/ui/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14949
Test for CV Version table, as well as for this CC BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1911545
(Reopening of an older PR)
Requires: https://github.com/SatelliteQE/airgun/pull/1083
> [6.15.z] [CV Eval] CV Version Test

- pytest_fixtures/core/contenthosts.py
- tests/foreman/api/test_capsulecontent.py
- tests/foreman/cli/test_container_management.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15179
Some of our tests are failing to pull docker images with OCI artifacts using obsolete version of docker client provided by RHEL7 extras repo.
(see [BZ#2262793](https://bugzilla.redhat.com/show_bug.cgi?id=2262793))
Let's move forward to RHEL8 and newer version of podman/docker.
Proposed changes in this PR:
1. Use RHEL8 with newer podman/docker client.
2. Rescope `container_contenthost` fixture to module. This speeds up current tests from ~45 minutes to ~15 minutes. The downside is we need to ensure `podman logout` is performed on teardown (via `request.addfinalizer`).
With the new podman new issue was identified (which has not been hit with the old docker client): https://issues.redhat.com/browse/SAT-25328
Since the [fix …
> [6.15.z] Use RHEL8 for container contenthost

- pytest_fixtures/core/contenthosts.py
- tests/foreman/api/test_capsulecontent.py
- tests/foreman/cli/test_container_management.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15179
Some of our tests are failing to pull docker images with OCI artifacts using obsolete version of docker client provided by RHEL7 extras repo.
(see [BZ#2262793](https://bugzilla.redhat.com/show_bug.cgi?id=2262793))
Let's move forward to RHEL8 and newer version of podman/docker.
Proposed changes in this PR:
1. Use RHEL8 with newer podman/docker client.
2. Rescope `container_contenthost` fixture to module. This speeds up current tests from ~45 minutes to ~15 minutes. The downside is we need to ensure `podman logout` is performed on teardown (via `request.addfinalizer`).
With the new podman new issue was identified (which has not been hit with the old docker client): https://issues.redhat.com/browse/SAT-25328
Since the [fix …
> [6.14.z] Use RHEL8 for container contenthost

- pytest_fixtures/core/contenthosts.py
- tests/foreman/api/test_capsulecontent.py
- tests/foreman/cli/test_container_management.py
Manual cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15179
Fixes https://github.com/SatelliteQE/robottelo/issues/15204
> [6.13.z] fix container content host

- conf/jira.yaml.template
- conftest.py
- pytest_plugins/jira_comments.py
- robottelo/config/validators.py
- robottelo/utils/issue_handlers/jira.py
- tests/foreman/ui/test_rhc.py
- This PR adds support for reporting/commenting test results to Jira based on issues referenced in the `Verifies` or `BlockedBy` doc fields.
1. Add a `Verifies` or `BlockedBy` doc field to the test, mapping it to a Jira RFE/Bug. For example, `:Verifies: SAT-25230` or `:BlockedBy: SAT-24796`.
- For `BlockedBy`, the test will be collected only if the corresponding Jira issue is in the `Review` (ON_QA) state. This behavior can be overridden by using the `--blocked-by SAT-25230` option.
2. Set `ENABLE_COMMENT` to `true` in the `jira.yaml` configuration file.
3. Use the `--jira-comments` pytest option.
Note: 
- To prevent accidental usage of this functionality, the user is required to perform both steps 2 and 3.(Open to suggestions)
-  By default, the comment will be added on issues in …
> Add support for reporting/commenting test results to the Jira issue

- conf/subscription.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/api/test_eol_banner.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/13253
This supplements tests for the EOL banner feature. The eol date for the version is defined in the satellite-lifecycle package (so that there is the same solution for connected and disconnected sats). This test aims to check the date in the package is correctly updated. 
Comparing the date from the package with the date from the lifecycle api.
Keeping in draft state, as the EOL banner just got to 6.15, but not yet to older releases and the lifecycle api contains data only for released versions
satellite-jenkins MR 1185
> [6.15.z] eol version check

- conf/jira.yaml.template
- conftest.py
- pytest_plugins/jira_comments.py
- robottelo/config/validators.py
- robottelo/utils/issue_handlers/jira.py
- tests/foreman/ui/test_rhc.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15104
- This PR adds support for reporting/commenting test results to Jira based on issues referenced in the `Verifies` or `BlockedBy` doc fields.
1. Add a `Verifies` or `BlockedBy` doc field to the test, mapping it to a Jira RFE/Bug. For example, `:Verifies: SAT-25230` or `:BlockedBy: SAT-24796`.
- For `BlockedBy`, the test will be collected only if the corresponding Jira issue is in the `Review` (ON_QA) state. This behavior can be overridden by using the `--blocked-by SAT-25230` option.
2. Set `ENABLE_COMMENT` to `true` in the `jira.yaml` configuration file.
3. Use the `--jira-comments` pytest option.
Note: 
- To prevent accidental usage of this functionality, the user is required to perform both steps 2 and 3.(Open to …
> [6.14.z] Add support for reporting/commenting test results to the Jira issue

- conf/jira.yaml.template
- conftest.py
- pytest_plugins/jira_comments.py
- robottelo/config/validators.py
- robottelo/utils/issue_handlers/jira.py
- tests/foreman/ui/test_rhc.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15104
- This PR adds support for reporting/commenting test results to Jira based on issues referenced in the `Verifies` or `BlockedBy` doc fields.
1. Add a `Verifies` or `BlockedBy` doc field to the test, mapping it to a Jira RFE/Bug. For example, `:Verifies: SAT-25230` or `:BlockedBy: SAT-24796`.
- For `BlockedBy`, the test will be collected only if the corresponding Jira issue is in the `Review` (ON_QA) state. This behavior can be overridden by using the `--blocked-by SAT-25230` option.
2. Set `ENABLE_COMMENT` to `true` in the `jira.yaml` configuration file.
3. Use the `--jira-comments` pytest option.
Note: 
- To prevent accidental usage of this functionality, the user is required to perform both steps 2 and 3.(Open to …
> [6.13.z] Add support for reporting/commenting test results to the Jira issue

- tests/foreman/cli/test_oscap.py
- tests/foreman/sys/test_webpack.py
adding some feature jiras for tracking as requested by jameer
> marking some 6.16 feature JIRAs

- pytest_fixtures/component/computeprofile.py
- pytest_fixtures/component/host.py
- pytest_fixtures/component/hostgroup.py
- pytest_fixtures/component/os.py
- pytest_fixtures/component/oscap.py
- pytest_fixtures/component/provisioning_template.py
- pytest_fixtures/component/repository.py
- pytest_fixtures/component/satellite_auth.py
- pytest_fixtures/component/subnet.py
- pytest_fixtures/component/user.py
- pytest_fixtures/component/user_role.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15084
SAT-22530
All fixtures under `pytest_fixtures/` now use nailgun through the satellite instance's `api` attribute, and imports of `nailgun.entities` have been removed.
Test results are the same before and after these changes.
PRT job #6979:
```
18:53:58  =========================== short test summary info ============================
18:53:58  FAILED tests/foreman/api/test_host.py::test_positive_create_and_update_with_user [...]
18:53:58  FAILED tests/foreman/ui/test_ldap_authentication.py::test_verify_group_permissions [...]
18:53:58  ERROR tests/foreman/api/test_oscappolicy.py::TestOscapPolicy::test_positive_crud_scap_pol …
```
> [6.15.z] Remove nailgun.entities imports in pytest_fixtures

- conf/supportability.yaml
- pytest_fixtures/component/os.py
- robottelo/config/validators.py
also enable searching for os names other than redhat os
(cherry picked from commit 56441e096da498084b3831ac72c98faeb363a5a1)
Fix failed cherry-pick https://github.com/SatelliteQE/robottelo/issues/14966
> [6.14.z] Make default_os name and major versions configurable

- .pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15278
updates:
- [github.com/astral-sh/ruff-pre-commit: v0.4.5 → v0.4.7](https://github.com/astral-sh/ruff-pre-commit/compare/v0.4.5...v0.4.7)
- [github.com/gitleaks/gitleaks: v8.18.2 → v8.18.3](https://github.com/gitleaks/gitleaks/compare/v8.18.2...v8.18.3)
> [6.16.z] [pre-commit.ci] pre-commit autoupdate

- .github/dependabot.yml
- conf/robottelo.yaml.template
- robottelo/constants/__init__.py
- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/installer/test_installer.py
New 6.16.z downstream and master points to stream that is 6.17
- Dependabot.yaml cherrypicks to 6.16.z
- Robottelo conf and constants now uses 6.17 and 6.16.z satellite versions
> [master]: Changes for new 6.16.z branch

- tests/foreman/ui/test_contentview_old.py
As part of CV Eval, it's time to clean up this old test file - these tests haven't passed in several versions, as this whole set of screens has been removed. Functionality to test the new CV UI is ongoing as part of eval work.
> Remove old CV UI tests

- pytest_plugins/metadata_markers.py
Fix the indention issue in handle_verification_issues that is causing problems collecting tests with --verifies-issues option.
Fix indentation
> Fix test selection issue for --verifies-issues option

- pytest_plugins/metadata_markers.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15297
Fix the indention issue in handle_verification_issues that is causing problems collecting tests with --verifies-issues option.
Fix indentation
> [6.13.z] Fix test selection issue for --verifies-issues option

- pytest_plugins/metadata_markers.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15297
Fix the indention issue in handle_verification_issues that is causing problems collecting tests with --verifies-issues option.
Fix indentation
> [6.15.z] Fix test selection issue for --verifies-issues option

- tests/foreman/ui/test_contentview_old.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14989
As part of CV Eval, it's time to clean up this old test file - these tests haven't passed in several versions, as this whole set of screens has been removed. Functionality to test the new CV UI is ongoing as part of eval work.
> [6.15.z] Remove old CV UI tests

- tests/foreman/ui/test_contentview_old.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14989
As part of CV Eval, it's time to clean up this old test file - these tests haven't passed in several versions, as this whole set of screens has been removed. Functionality to test the new CV UI is ongoing as part of eval work.
> [6.16.z] Remove old CV UI tests

- pytest_fixtures/component/computeprofile.py
- pytest_fixtures/component/host.py
- pytest_fixtures/component/hostgroup.py
- pytest_fixtures/component/os.py
- pytest_fixtures/component/oscap.py
- pytest_fixtures/component/provisioning_template.py
- pytest_fixtures/component/repository.py
- pytest_fixtures/component/satellite_auth.py
- pytest_fixtures/component/subnet.py
- pytest_fixtures/component/user.py
- pytest_fixtures/component/user_role.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15084
SAT-22530
All fixtures under `pytest_fixtures/` now use nailgun through the satellite instance's `api` attribute, and imports of `nailgun.entities` have been removed.
Test results are the same before and after these changes.
PRT job #6979:
```
18:53:58  =========================== short test summary info ============================
18:53:58  FAILED tests/foreman/api/test_host.py::test_positive_create_and_update_with_user [...]
18:53:58  FAILED tests/foreman/ui/test_ldap_authentication.py::test_verify_group_permissions [...]
18:53:58  ERROR tests/foreman/api/test_oscappolicy.py::TestOscapPolicy::test_positive_crud_scap_pol …
```
> [6.13.z] Remove nailgun.entities imports in pytest_fixtures

- .github/dependency_tests.yaml
> updated the manifestor test for dependabot

- .github/dependency_tests.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15309
> [6.14.z] updated the manifestor test for dependabot

- .github/dependency_tests.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15309
> [6.15.z] updated the manifestor test for dependabot

- .github/dependency_tests.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15309
> [6.13.z] updated the manifestor test for dependabot

- .github/dependency_tests.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15309
> [6.16.z] updated the manifestor test for dependabot

- tests/foreman/api/test_reporttemplates.py
- tests/foreman/cli/test_reporttemplates.py
- tests/foreman/ui/test_reporttemplates.py
SCA is now the default in 6.16. This PR is for updating all tests under the Reporting Component
SAT-24355
> [Reporting] Updating reporting tests to be sca compliant

- tests/foreman/api/test_errata.py
- tests/foreman/api/test_subscription.py
- tests/foreman/cli/test_contentaccess.py
Proposed changes:
1. Use `test_positive_install_multiple_in_host` instead of `test_errata_installation_with_swidtags` for PIT testing.
2. When updating CV in `content_facet_atttributes` we need to provide LCE too.
3. In 6.16 `subscription_status` was removed. Assert host registration via uuid instead.
> Add a couple of fixes for PIT

- robottelo/cli/repository.py
- tests/foreman/cli/test_repositories.py
Test for following BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2164997
Also adds the associated CLI endpoint to enable the test. 
pytest: tests/foreman/cli/test_repositories.py -k 'test_positive_reclaim_space'
> CC Automation - reclaim-space CLI test

- robottelo/host_helpers/satellite_mixins.py
> Poll ncat tunnel pid

- robottelo/host_helpers/satellite_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15056
> [6.15.z] Poll ncat tunnel pid

- robottelo/host_helpers/satellite_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15056
> [6.14.z] Poll ncat tunnel pid

- robottelo/host_helpers/satellite_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15056
> [6.13.z] Poll ncat tunnel pid

- robottelo/host_helpers/satellite_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15056
> [6.12.z] Poll ncat tunnel pid

- tests/foreman/cli/test_leapp_client.py
- tests/foreman/ui/test_computeprofiles.py
- tests/foreman/ui/test_computeresource.py
- tests/foreman/ui/test_computeresource_azurerm.py
- tests/foreman/ui/test_computeresource_ec2.py
- tests/foreman/ui/test_computeresource_gce.py
- tests/foreman/ui/test_computeresource_libvirt.py
- tests/foreman/ui/test_config_group.py
- tests/foreman/ui/test_discoveryrule.py
- tests/foreman/ui/test_operatingsystem.py
- tests/foreman/ui/test_puppetclass.py
- tests/foreman/ui/test_puppetenvironment.py
- tests/foreman/ui/test_smartclassparameter.py
- tests/foreman/ui/test_subnet.py
Manual  cherrypick of https://github.com/SatelliteQE/robottelo/pull/14702
> [6.13.z] Mark UI tests as end-to-end for Rocket Team Components

- tests/foreman/destructive/test_leapp_satellite.py
`test_positive_leapp` covers only RHEL7 -> RHEL8 upgrade path. We need to update this test to run Satellite LEAPP upgrade from RHEL8 -> RHEL9 for 6.16
Update the test to run Satellite LEAPP upgrade from RHEL8 -> RHEL9 for 6.16
[SAT-25527](https://issues.redhat.com/browse/SAT-25527)
[SAT-25168](https://issues.redhat.com/browse/SAT-25527) (SatLab)
pytest: tests/foreman/destructive/test_leapp_satellite.py
> Update test_positive_leapp for 6.16

- .github/workflows/pull_request.yml
- robottelo/config/validators.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15340
> [6.15.z] removed server.hostname validator for resolve rhel 8.10 formatting issue

- .github/workflows/pull_request.yml
- robottelo/config/validators.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15340
> [6.13.z] removed server.hostname validator for resolve rhel 8.10 formatting issue

- .github/workflows/pull_request.yml
- robottelo/config/validators.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15340
> [6.14.z] removed server.hostname validator for resolve rhel 8.10 formatting issue

- pytest_fixtures/core/xdist.py
Sanity is failing with `server.hostname` attribute not found. Earlier the dynaconf validator was setting it as a default value and attribute but that Is removed in PR https://github.com/SatelliteQE/robottelo/pull/15340.
Setting the hostname attribute to server for sanity.
```
In [2]: settings.server.hostname
---------------------------------------------------------------------------
BoxKeyError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 settings.server.hostname
File ~/venv/robottelo312/src/dynaconf/dynaconf/utils/boxing.py:18, in evaluate_lazy_format.<locals>.evaluate(dynabox, item, *args, **kwargs)
16 @wraps(f)
17 def evaluate(dynabox, item, *args, **kwargs):
---> 18     value = f(dynabox, item, *args, **kwargs)
19     settings = …
```
> Setting sanity hostname attr initially

- pytest_fixtures/core/xdist.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15350
Sanity is failing with `server.hostname` attribute not found. Earlier the dynaconf validator was setting it as a default value and attribute but that Is removed in PR https://github.com/SatelliteQE/robottelo/pull/15340.
Setting the hostname attribute to server for sanity.
```
In [2]: settings.server.hostname
---------------------------------------------------------------------------
BoxKeyError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 settings.server.hostname
File ~/venv/robottelo312/src/dynaconf/dynaconf/utils/boxing.py:18, in evaluate_lazy_format.<locals>.evaluate(dynabox, item, *args, **kwargs)
16 @wraps(f)
17 def evaluate(dynabox, item, *args, **kwargs):
---> 18 …
```
> [6.13.z] Setting sanity hostname attr initially

- pytest_fixtures/core/xdist.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15350
Sanity is failing with `server.hostname` attribute not found. Earlier the dynaconf validator was setting it as a default value and attribute but that Is removed in PR https://github.com/SatelliteQE/robottelo/pull/15340.
Setting the hostname attribute to server for sanity.
```
In [2]: settings.server.hostname
---------------------------------------------------------------------------
BoxKeyError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 settings.server.hostname
File ~/venv/robottelo312/src/dynaconf/dynaconf/utils/boxing.py:18, in evaluate_lazy_format.<locals>.evaluate(dynabox, item, *args, **kwargs)
16 @wraps(f)
17 def evaluate(dynabox, item, *args, **kwargs):
---> 18 …
```
> [6.15.z] Setting sanity hostname attr initially

- pytest_fixtures/core/xdist.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15350
Sanity is failing with `server.hostname` attribute not found. Earlier the dynaconf validator was setting it as a default value and attribute but that Is removed in PR https://github.com/SatelliteQE/robottelo/pull/15340.
Setting the hostname attribute to server for sanity.
```
In [2]: settings.server.hostname
---------------------------------------------------------------------------
BoxKeyError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 settings.server.hostname
File ~/venv/robottelo312/src/dynaconf/dynaconf/utils/boxing.py:18, in evaluate_lazy_format.<locals>.evaluate(dynabox, item, *args, **kwargs)
16 @wraps(f)
17 def evaluate(dynabox, item, *args, **kwargs):
---> 18 …
```
> [6.14.z] Setting sanity hostname attr initially

- tests/foreman/installer/test_installer.py
- test_satellite_installation is failing on assertion as we have migrated to Jira and the BZ is now closed without being actually resolved causing is_open to report false status.
- Use SAT-21086 to check the bug status and skip assertion accordingly.
> Skip assertion for test_satellite_installation if SAT-21086 is open

- tests/foreman/api/test_ansible.py
- tests/foreman/api/test_organization.py
- tests/foreman/api/test_provisioning.py
- tests/foreman/sys/test_pulp3_filesystem.py
- tests/foreman/ui/test_computeresource_vmware.py
We have migrated to Jira and some of the bz have been closed without being fixed/resolved. It's causing is_open function to return false status and we're now running the assertion which fails.
- Use Jira issues to get the bug status
> Use jira issue to get bug status

- tests/foreman/api/test_ansible.py
- tests/foreman/api/test_organization.py
- tests/foreman/api/test_provisioning.py
- tests/foreman/sys/test_pulp3_filesystem.py
- tests/foreman/ui/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15359
We have migrated to Jira and some of the bz have been closed without being fixed/resolved. It's causing is_open function to return false status and we're now running the assertion which fails.
- Use Jira issues to get the bug status
> [6.15.z] Use jira issue to get bug status

- tests/foreman/installer/test_installer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15360
See https://github.com/SatelliteQE/robottelo/pull/15358
> [6.14.z] [cherry-pick] Skip assertion for test_satellite_installation if SAT-21086 is open

- tests/foreman/api/test_ansible.py
- tests/foreman/api/test_organization.py
- tests/foreman/api/test_provisioning.py
- tests/foreman/sys/test_pulp3_filesystem.py
- tests/foreman/ui/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15359
We have migrated to Jira and some of the bz have been closed without being fixed/resolved. It's causing is_open function to return false status and we're now running the assertion which fails.
- Use Jira issues to get the bug status
> [6.14.z] Use jira issue to get bug status

- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_reporttemplates.py
- tests/foreman/cli/test_activationkey.py
- tests/foreman/ui/test_containerimagetag.py
- tests/foreman/ui/test_contenthost.py
- tests/upgrades/test_virtwho.py
These BZs were already closed so we don't need to skip `if open` them anymore:
https://bugzilla.redhat.com/show_bug.cgi?id=1802395
https://bugzilla.redhat.com/show_bug.cgi?id=1789028
https://bugzilla.redhat.com/show_bug.cgi?id=2112320
https://bugzilla.redhat.com/show_bug.cgi?id=1680458
https://bugzilla.redhat.com/show_bug.cgi?id=2148813
Remove the `skip_if` conditioning.
pytest: tests/foreman/api/test_reporttemplates.py::test_positive_lock_clone_nodelete_unlock_report tests/foreman/cli/test_activationkey.py::test_create_ak_with_syspurpose_set tests/foreman/ui/test_containerimagetag.py::test_positive_search
> Remove old skip_if for closed BZs

- tests/foreman/ui/test_subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15237
- Test case `test_positive_access_with_non_admin_user_with_manifest` from UI > test_subscription.py was failing due to wrong (empty search) result, search box xpath was incorrect and gave below error.
- Airgun PR [[Link]](https://github.com/SatelliteQE/airgun/pull/1405) will fix xpath
**Error:**
`E   TypeError: 'NoneType' object is not subscriptable`
- This alernate solution will search for all subscriptions and iterate over it, break the for loop once it matches with DEFAULT_SUBSCRIPTION_NAME
- `session.subscription.search(f'name = "{DEFAULT_SUBSCRIPTION_NAME}"')[0]['Name']` this part searches correctly but returns all present subsriptions from Subscription page instead of `Red Hat Enterprise Linux Server, Premium …
> [6.14.z] 6.15.z-alernative solution for default subscription search option

- .github/dependency_tests.yaml
- requirements.txt
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15221
This requirement update also adds in the podman and hussh dependency groups.
> [6.15.z] Bump broker to 0.5

- tests/foreman/cli/test_leapp_client.py
- tests/foreman/ui/test_computeprofiles.py
- tests/foreman/ui/test_computeresource.py
- tests/foreman/ui/test_computeresource_azurerm.py
- tests/foreman/ui/test_computeresource_ec2.py
- tests/foreman/ui/test_computeresource_gce.py
- tests/foreman/ui/test_computeresource_libvirt.py
- tests/foreman/ui/test_config_group.py
- tests/foreman/ui/test_discoveryrule.py
- tests/foreman/ui/test_operatingsystem.py
- tests/foreman/ui/test_puppetclass.py
- tests/foreman/ui/test_puppetenvironment.py
- tests/foreman/ui/test_smartclassparameter.py
- tests/foreman/ui/test_subnet.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/issues/14997
> [6.14.z] Mark UI tests as end-to-end for Rocket Team Components

- tests/foreman/cli/test_oscap.py
SAT-19502 describes the issue, https://github.com/theforeman/foreman_openscap/pull/568/files provides the upstream fix
Extending an existing test to check the policy behavior after hostgroup removal
> policy list should work after associated hg removal

- tests/foreman/cli/test_ping.py
automation failures with `IndexError: string index out of range`
this pr
note to self: prt  won't run atm, rerun later with:
pytest: tests/foreman/cli/test_ping.py -k test_positive_ping[non-root]
> updated in hammer ping stderr parsing

- pytest_fixtures/component/activationkey.py
- pytest_fixtures/component/contentview.py
- robottelo/hosts.py
- tests/foreman/api/test_convert2rhel.py
- tests/foreman/api/test_hostcollection.py
- tests/foreman/api/test_registration.py
- tests/foreman/api/test_reporttemplates.py
- tests/foreman/api/test_subscription.py
- tests/foreman/cli/test_activationkey.py
- tests/foreman/cli/test_host.py
- tests/foreman/cli/test_hostcollection.py
- tests/foreman/cli/test_registration.py
- tests/foreman/cli/test_reporttemplates.py
- tests/foreman/cli/test_subscription.py
- tests/foreman/destructive/test_registration.py
- tests/foreman/ui/test_activationkey.py
- tests/foreman/ui/test_ansible.py
- tests/foreman/ui/test_reporttemplates.py
- tests/foreman/ui/test_subscription.py
> [6.15.z] Replace old method of registration with global registration in robotlelo

- pytest_fixtures/component/activationkey.py
- pytest_fixtures/component/contentview.py
- robottelo/hosts.py
- tests/foreman/api/test_convert2rhel.py
- tests/foreman/api/test_hostcollection.py
- tests/foreman/api/test_registration.py
- tests/foreman/api/test_reporttemplates.py
- tests/foreman/api/test_subscription.py
- tests/foreman/cli/test_activationkey.py
- tests/foreman/cli/test_host.py
- tests/foreman/cli/test_hostcollection.py
- tests/foreman/cli/test_registration.py
- tests/foreman/cli/test_reporttemplates.py
- tests/foreman/cli/test_subscription.py
- tests/foreman/destructive/test_registration.py
- tests/foreman/ui/test_activationkey.py
- tests/foreman/ui/test_ansible.py
- tests/foreman/ui/test_reporttemplates.py
- tests/foreman/ui/test_subscription.py
> [6.14.z] Replace old method of registration with global registration in robottelo

- .github/dependency_tests.yaml
- requirements.txt
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15221
This requirement update also adds in the podman and hussh dependency groups.
> [6.14.z] Bump broker to 0.5

- .github/dependency_tests.yaml
- requirements.txt
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15221
This requirement update also adds in the podman and hussh dependency groups.
> [6.13.z] Bump broker to 0.5

- robottelo/hosts.py
- tests/foreman/destructive/test_ldapauthsource.py
IPA domain isn't necessarily the same as DNS domain so connect using DNS domain and there detect the actual IPA domain.
RHSSO used nonexistent ssh_session methods, perhaps this has changed over time. I made it use the execute method and workarounded bug that happens when calling 'hammer auth login oauth' non-interactively by faking tty.
> Fix IPA and RHSSO.

- robottelo/hosts.py
- tests/foreman/destructive/test_ldapauthsource.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15357
IPA domain isn't necessarily the same as DNS domain so connect using DNS domain and there detect the actual IPA domain.
RHSSO used nonexistent ssh_session methods, perhaps this has changed over time. I made it use the execute method and workarounded bug that happens when calling 'hammer auth login oauth' non-interactively by faking tty.
> [6.15.z] Fix IPA and RHSSO.

- tests/foreman/api/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15035
Missing coverage for BZ:1931489, where we verified timeout to kill/execution_timeout_interval setting is honored by long running ansible-playbook job
Add test coverage for BZ:1931489, to verify long running ansible-playbook job along with timeout to kill/execution_timeout_interval setting
> [6.13.z] Add test coverage for BZ:1931489

- tests/foreman/destructive/test_packages.py
Failing in automation because it's grabbing the second character in the stderr. Not sure why this changed but this should do the trick.
pytest: tests/foreman/destructive/test_packages.py::test_negative_remove_satellite_packages[capsule]
> Fix remove satellite packages test

- robottelo/utils/virtwho.py
- tests/foreman/virtwho/ui/test_esx_sca.py
- tests/foreman/virtwho/ui/test_hyperv_sca.py
- tests/foreman/virtwho/ui/test_kubevirt_sca.py
- tests/foreman/virtwho/ui/test_libvirt_sca.py
- tests/foreman/virtwho/ui/test_nutanix_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15288
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/ui/test_hyperv_sca.py  -k test_positive_deploy_configure_by_id_script[id] --disable-pytest-warnings -q
1 passed, 17 deselected, 11 warnings in 461.63s (0:07:41)
=============================================================================
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/ui/test_esx_sca.py  -k test_positive_deploy_configure_by_id_script[id] …
```
> [6.15.z] Check Hypervisor host subscription status and hypervisor host and virtual guest mapping in UI

- tests/foreman/cli/test_registration.py
When a host is registered, its Owner is not set to the admin that generated the registration command. It stays set to a hidden API user, Owner is displayed as Anonymous Admin.
The user who actually ran the registration process should be set as owner.
The following automation script is designed to verify that the host is registered correctly and that it is assigned the expected owner name as specified.
> verify host owner name after host registration

- conf/capsule.yaml.template
- conf/dynaconf_hooks.py
- conf/server.yaml.template
- pytest_fixtures/component/maintain.py
- pytest_fixtures/core/broker.py
- pytest_fixtures/core/sat_cap_factory.py
- pytest_fixtures/core/xdist.py
- robottelo/config/__init__.py
- robottelo/config/validators.py
- robottelo/host_helpers/contenthost_mixins.py
- robottelo/hosts.py
- robottelo/utils/ohsnap.py
- robottelo/utils/url.py
- tests/foreman/installer/test_installer.py
Enabling IPv6 switching in Robottelo Automation 
- Added the IPV6 switch and IPV6 proxy config that would switch ON and OFF the IPv6 Testing for robottelo tests via CI or local
- Added setup of Satellite HTTP Proxy by default to all satellite spinned as/by broker workers, factory, directly from Broker context manager
- Adder teardown of Satellite HTTP Proxy by default to all satellite spinned as/by broker workers, factory, directly from Broker context manager
- Added setup of Capsule HTTP Proxy by default to all capsules spinned by factory, directly from Broker context manager to speak to CDN for content access
- Adder teardown of Capsule HTTP Proxy by default to all capsules spinned by factory, directly from Broker context manager
- Deploy Arguments switches satellite / capsule spin up …
> Enabling Robottelo for IPv6 Testing

- robottelo/utils/virtwho.py
- tests/foreman/virtwho/ui/test_esx_sca.py
- tests/foreman/virtwho/ui/test_hyperv_sca.py
- tests/foreman/virtwho/ui/test_kubevirt_sca.py
- tests/foreman/virtwho/ui/test_libvirt_sca.py
- tests/foreman/virtwho/ui/test_nutanix_sca.py
fixed the cherrypick failed https://github.com/SatelliteQE/robottelo/issues/15401
Test Cases : PASS
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/ui/test_hyperv_sca.py  -k test_positive_deploy_configure_by_id_script[id] --disable-pytest-warnings -q
1 passed, 17 deselected, 11 warnings in 461.63s (0:07:41)
=============================================================================
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/ui/test_esx_sca.py  -k …
```
> [6.14.z]-Check Hypervisor host subscription status and hypervisor host and virtual guest mapping in UI #15401

- tests/foreman/ui/test_architecture.py
- tests/foreman/ui/test_audit.py
- tests/foreman/ui/test_computeprofiles.py
- tests/foreman/ui/test_computeresource.py
- tests/foreman/ui/test_computeresource_ec2.py
- tests/foreman/ui/test_computeresource_vmware.py
- tests/foreman/ui/test_containerimagetag.py
- tests/foreman/ui/test_domain.py
- tests/foreman/ui/test_hardwaremodel.py
- tests/foreman/ui/test_hostgroup.py
- tests/foreman/ui/test_location.py
- tests/foreman/ui/test_modulestreams.py
- tests/foreman/ui/test_organization.py
- tests/foreman/ui/test_oscappolicy.py
- tests/foreman/ui/test_oscaptailoringfile.py
- tests/foreman/ui/test_package.py
- tests/foreman/ui/test_product.py
- tests/foreman/ui/test_reporttemplates.py
- tests/foreman/ui/test_sync.py
- tests/foreman/ui/test_syncplan.py
- tests/foreman/ui/test_templatesync.py
- tests/foreman/ui/test_usergroup.py
We are using the direct imports from the nailgun rather than directly using from target_sat
Direct Imports Removed: We've cleaned up our codebase by eliminating direct imports from the Nailgun package.
Using target_sat, module_target_sat, class_target_sat: Modified the API calls and using the target_sat.api. pattern for all API calls.
> [6.13.z] - remove the all nailgun imports from UI folder

- tests/foreman/ui/test_architecture.py
- tests/foreman/ui/test_audit.py
- tests/foreman/ui/test_computeprofiles.py
- tests/foreman/ui/test_computeresource.py
- tests/foreman/ui/test_computeresource_ec2.py
- tests/foreman/ui/test_computeresource_vmware.py
- tests/foreman/ui/test_containerimagetag.py
- tests/foreman/ui/test_domain.py
- tests/foreman/ui/test_hardwaremodel.py
- tests/foreman/ui/test_hostgroup.py
- tests/foreman/ui/test_location.py
- tests/foreman/ui/test_modulestreams.py
- tests/foreman/ui/test_organization.py
- tests/foreman/ui/test_oscappolicy.py
- tests/foreman/ui/test_oscaptailoringfile.py
- tests/foreman/ui/test_package.py
- tests/foreman/ui/test_product.py
- tests/foreman/ui/test_reporttemplates.py
- tests/foreman/ui/test_sync.py
- tests/foreman/ui/test_syncplan.py
- tests/foreman/ui/test_templatesync.py
- tests/foreman/ui/test_usergroup.py
We are using the direct imports from the nailgun rather than directly using from target_sat
Direct Imports Removed: We've cleaned up our codebase by eliminating direct imports from the Nailgun package.
Using target_sat, module_target_sat, class_target_sat: Modified the API calls and using the target_sat.api. pattern for all API calls.
> [6.14.z] - remove the all nailgun imports from UI folder

- conf/capsule.yaml.template
- conf/dynaconf_hooks.py
- conf/server.yaml.template
- pytest_fixtures/component/maintain.py
- pytest_fixtures/core/broker.py
- pytest_fixtures/core/sat_cap_factory.py
- pytest_fixtures/core/xdist.py
- robottelo/config/validators.py
- robottelo/host_helpers/contenthost_mixins.py
- robottelo/hosts.py
- robottelo/utils/ohsnap.py
- robottelo/utils/url.py
- tests/foreman/installer/test_installer.py
* Enabling Robottelo for IPv6 Testing
Failed Automatic cherry-pick of https://github.com/SatelliteQE/robottelo/pull/14160 
Manual cherrypick of PR after conflicts were resolved.
> [6.15.z] Enabling Robottelo for IPv6 Testing (#14160)

- robottelo/config/validators.py
Using latest robottelo, including the IPv6-related changes, I am running into
```
dynaconf.validator.ValidationError: server.http_proxy_ipv6_url must is_type_of <class 'str'> but it is None in env main
```
This error is caused by a validator that enforces string type, but it is setting the value to None itself. :meow_shrugs:
```
Validator('server.http_proxy_ipv6_url', is_type_of=str, default=None),
```
Utilize conditional validation - validate the IPv6 proxy URL setting only when IS_IPV6 is set to True
https://www.dynaconf.com/validation/#conditional-validation
This should be fixed before #15289 goes in
> Fix validation: validate IPv6 proxy URL only when IS_IPV6 is set to True

- robottelo/config/validators.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15413
Using latest robottelo, including the IPv6-related changes, I am running into
```
dynaconf.validator.ValidationError: server.http_proxy_ipv6_url must is_type_of <class 'str'> but it is None in env main
```
This error is caused by a validator that enforces string type, but it is setting the value to None itself. :meow_shrugs:
```
Validator('server.http_proxy_ipv6_url', is_type_of=str, default=None),
```
Utilize conditional validation - validate the IPv6 proxy URL setting only when IS_IPV6 is set to True
https://www.dynaconf.com/validation/#conditional-validation
This should be fixed before #15289 goes in
> [6.15.z] Fix validation: validate IPv6 proxy URL only when IS_IPV6 is set to True

- robottelo/config/validators.py
> [6.14.z] Fix validation: validate IPv6 proxy URL only when IS_IPV6 is set to True

- robottelo/config/validators.py
> [6.13.z] Fix validation: validate IPv6 proxy URL only when IS_IPV6 is set to True

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15416
Currently, ansible variable test covers only admin scenario, and as part of component audit its suggest to modify this test to cover non-admin user scenario as well, and delete the duplicate test which test create delete
- Parametrizing the existing test to cover both admin and non-admin user scenarios with few more fixes
- Deleting the test test_positive_create_and_delete_variable which tests create delete which is covered already in other test.
> [6.15.z] Modify ansible variable test to cover non-admin scenario

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15416
Currently, ansible variable test covers only admin scenario, and as part of component audit its suggest to modify this test to cover non-admin user scenario as well, and delete the duplicate test which test create delete
- Parametrizing the existing test to cover both admin and non-admin user scenarios with few more fixes
- Deleting the test test_positive_create_and_delete_variable which tests create delete which is covered already in other test.
> [6.13.z] Modify ansible variable test to cover non-admin scenario

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15416
Currently, ansible variable test covers only admin scenario, and as part of component audit its suggest to modify this test to cover non-admin user scenario as well, and delete the duplicate test which test create delete
- Parametrizing the existing test to cover both admin and non-admin user scenarios with few more fixes
- Deleting the test test_positive_create_and_delete_variable which tests create delete which is covered already in other test.
> [6.14.z] Modify ansible variable test to cover non-admin scenario

- tests/upgrades/test_virtwho.py
fixed https://github.com/SatelliteQE/robottelo/issues/14498
```
robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade  --disable-pytest-warnings -q                                                                                                                                                           
tests/upgrades/test_virtwho.py .
.
============================================================================= 1 passed, 1 deselected, 3 warnings in 221.69s (0:03:41) =============================================================================
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m post_upgrade  -s …
```
> virt-who config upgrade duplicate config issue fix #14498

- tests/foreman/api/test_capsulecontent.py
SHA1 is no longer supported by Pulp (see https://projects.theforeman.org/issues/37522) which renders one test failing. But the scenario seems still valid to me. It discovered a regression a few times ago, so I would like to keep it.
just run it with another supported checksum type. 
pytest: tests/foreman/api/test_capsulecontent.py -k test_positive_checksum_sync
> Update repo checksum with one supported

- tests/foreman/api/test_capsulecontent.py
New setting to disable automatic content count update has been introduced and we should test how it works, since it's customer facing.
This PR adds just such a case.
https://bugzilla.redhat.com/show_bug.cgi?id=2284027
needs https://github.com/Katello/katello/pull/11014 
```
pytest: tests/foreman/api/test_capsulecontent.py -k test_automatic_content_counts_update_toggle
Katello:
katello: 11014
```
> Add test case for automatic content counts update toggling

- tests/foreman/ui/test_discoveredhost.py
Missing coverage for BZ:2238952 and BZ:2268544, where we verified Customize host button works to provision a discovered host with a few customizations.
Add test coverage for BZ:2238952 and BZ:2268544, to verify functionality of discovery provisioning with Customize host button with a few customizations, and also covering BZ:2025523 where we've validated the assigned Ansible roles to a HostGroup gets auto executed when host is provisioned.
Also, verifying new test and modifying existing test to validate if provisioning is sucessfull on new host UI instead of old UI
https://github.com/SatelliteQE/airgun/pull/1397
> Add test coverage for BZ:2238952 and BZ:2025523

- tests/foreman/ui/test_syncplan.py
The timediff was increased to 5 minutes.
On 'fast' UIs this can lead to poll timeouts.
Increasing the search rate to 15 fixes this:
15 * 20 / 60 = 5
https://github.com/SatelliteQE/robottelo/pull/15172
tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_real_time
tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_past_sync_date
> Increase search rate for syncplan polling

- tests/foreman/ui/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15452
The timediff was increased to 5 minutes.
On 'fast' UIs this can lead to poll timeouts.
Increasing the search rate to 15 fixes this:
15 * 20 / 60 = 5
https://github.com/SatelliteQE/robottelo/pull/15172
tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_real_time
tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_past_sync_date
> [6.15.z] Increase search rate for syncplan polling

- pytest_plugins/metadata_markers.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15005
We need case insensitive test collection component-wise
Added marker for component-wise test collection
result:
pytest tests/foreman/ --component auditlog
collected 5434 items / 5426 deselected / 8 selected                                                                                              
```
tests/foreman/api/test_audit.py ✓✓✓                                                                                                38% ███▊      
tests/foreman/ui/test_audit.py ✓✓✓✓✓                                                                                              100% ██████████
```
=======================================================
> [6.14.z] Add marker for case insensitive test collection by component and importance

- pytest_plugins/metadata_markers.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15005
We need case insensitive test collection component-wise
Added marker for component-wise test collection
result:
pytest tests/foreman/ --component auditlog
collected 5434 items / 5426 deselected / 8 selected                                                                                              
```
tests/foreman/api/test_audit.py ✓✓✓                                                                                                38% ███▊      
tests/foreman/ui/test_audit.py ✓✓✓✓✓                                                                                              100% ██████████
```
=======================================================
> [6.13.z] Add marker for case insensitive test collection by component and importance

- pytest_plugins/jira_comments.py
- pytest_plugins/metadata_markers.py
- robottelo/utils/__init__.py
- robottelo/utils/issue_handlers/jira.py
- We have a `--jira-comments` pytest option that we use to add comments to Jira issues for tests marked with `Verifies` or `BlockedBy` doc fields. Atm, this can't be overridden, and one has to mark each test with these fields. 
- The JPL team has requested this enhancement so that we can use it in standalone PRT runs.
- Update logic for `--jira-comments` to override issues to comment test results on. 
- `pytest tests/foreman/api/test_ping.py --jira-comments` Comment test results on issues mentioned in `Verifies` and `BlockedBy` doc fields(No change, this is primary use case).
- `pytest tests/foreman/api/test_ping.py --jira-comments 'SAT-24796,SAT-25230'` Comment test results on `SAT-24796` and `SAT-25230`.
- SAT-25884
- https://github.com/SatelliteQE/robottelo/pull/15104
> Add support for overriding jira issues to comment on.

- pytest_fixtures/core/sat_cap_factory.py
The assertion failure in the installer test helper blocks the installation of the satellite itself in the installer test and mainly in sanity testing making all the other tests unable to reach out to the satellite as it's not installed.
- Removing the assertion from helper function as its already under the context of the test assertions.
- Now we don't unblock installer execution and the rest of the tests should validate the build from sanity execution.
Refer build sanity failure of 6.15.2 and the related thread in the automation slack channel.
> Installer Assertions in test context rather than in helper

- pytest_fixtures/core/sat_cap_factory.py
Failed Cherrypick of #15461 
Closes #15463
> Installer Assertions in test context rather than in helper (#15461)

- pytest_fixtures/core/sat_cap_factory.py
- robottelo/hosts.py
Failed AutoCherrypick of #15461 
Closes #15462
> [6.14.z] Installer Assertions in test context rather than in helper (#15461)

- pytest_fixtures/core/sat_cap_factory.py
- robottelo/hosts.py
Failed AutoCherrypick of #15461 
Closes #15464
> [6.13.z] Installer Assertions in test context rather than in helper (#15461)

- tests/foreman/api/test_repositories.py
- tests/upgrades/test_subscription.py
Tests that do not use manifester fixture cannot be filtered by https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/conftest.py#L33
Add simple pytest mark.
https://github.com/SatelliteQE/robottelo/pull/14405
> Mark manifester tests that do not use manifester fixtures

- pytest_plugins/jira_comments.py
- pytest_plugins/metadata_markers.py
- robottelo/utils/__init__.py
- robottelo/utils/issue_handlers/jira.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15427
- We have a `--jira-comments` pytest option that we use to add comments to Jira issues for tests marked with `Verifies` or `BlockedBy` doc fields. Atm, this can't be overridden, and one has to mark each test with these fields. 
- The JPL team has requested this enhancement so that we can use it in standalone PRT runs.
- Update logic for `--jira-comments` to override issues to comment test results on. 
- `pytest tests/foreman/api/test_ping.py --jira-comments` Comment test results on issues mentioned in `Verifies` and `BlockedBy` doc fields(No change, this is primary use case).
- `pytest tests/foreman/api/test_ping.py --jira-comments 'SAT-24796,SAT-25230'` Comment test results on `SAT-24796` and `SAT-25230`.
- SAT-25884
- …
> [6.15.z] Add support for overriding jira issues to comment on.

- pytest_plugins/jira_comments.py
- pytest_plugins/metadata_markers.py
- robottelo/utils/__init__.py
- robottelo/utils/issue_handlers/jira.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15427
- We have a `--jira-comments` pytest option that we use to add comments to Jira issues for tests marked with `Verifies` or `BlockedBy` doc fields. Atm, this can't be overridden, and one has to mark each test with these fields. 
- The JPL team has requested this enhancement so that we can use it in standalone PRT runs.
- Update logic for `--jira-comments` to override issues to comment test results on. 
- `pytest tests/foreman/api/test_ping.py --jira-comments` Comment test results on issues mentioned in `Verifies` and `BlockedBy` doc fields(No change, this is primary use case).
- `pytest tests/foreman/api/test_ping.py --jira-comments 'SAT-24796,SAT-25230'` Comment test results on `SAT-24796` and `SAT-25230`.
- SAT-25884
- …
> [6.14.z] Add support for overriding jira issues to comment on.

- pytest_plugins/jira_comments.py
- pytest_plugins/metadata_markers.py
- robottelo/utils/__init__.py
- robottelo/utils/issue_handlers/jira.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15427
- We have a `--jira-comments` pytest option that we use to add comments to Jira issues for tests marked with `Verifies` or `BlockedBy` doc fields. Atm, this can't be overridden, and one has to mark each test with these fields. 
- The JPL team has requested this enhancement so that we can use it in standalone PRT runs.
- Update logic for `--jira-comments` to override issues to comment test results on. 
- `pytest tests/foreman/api/test_ping.py --jira-comments` Comment test results on issues mentioned in `Verifies` and `BlockedBy` doc fields(No change, this is primary use case).
- `pytest tests/foreman/api/test_ping.py --jira-comments 'SAT-24796,SAT-25230'` Comment test results on `SAT-24796` and `SAT-25230`.
- SAT-25884
- …
> [6.13.z] Add support for overriding jira issues to comment on.

- tests/foreman/api/test_repositories.py
- tests/upgrades/test_subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14521
Tests that do not use manifester fixture cannot be filtered by https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/conftest.py#L33
Add simple pytest mark.
https://github.com/SatelliteQE/robottelo/pull/14405
> [6.15.z] Mark manifester tests that do not use manifester fixtures

- tests/foreman/cli/test_satellitesync.py
Default umask settings defined in `/etc/bashrc` (used for non-login shell, which is what robottelo use for `target_sat.execute(...)`) is different in RHEL8 and RHEL9.
In RHEL8 we can find:
```
if [ $UID -gt 199 ] && [ "`/usr/bin/id -gn`" = "`/usr/bin/id -un`" ]; then
umask 002
else
umask 022
fi
```
while in RHEL9:
```
[ `umask` -eq 0 ] && umask 022
```
That `[ ]` test is important there, since it prevents umask setting if it's non-zero already (yes it is) and thus blocks the fixture to set it more restrictively with `sed` (as used before) when running against RHEL9 based Satellite.
Override it no matter what previous code is and return it back on tear-down.
pytest: tests/foreman/cli/test_satellitesync.py -k with_permissions
> Fix umask setting fixture

- tests/foreman/cli/test_satellitesync.py
> Replace skip_if with BlockedBy for migrated BZ

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15479
This PR.
> [6.15.z] Replace skip_if with BlockedBy for migrated BZ

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15479
This PR.
> [6.13.z] Replace skip_if with BlockedBy for migrated BZ

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15479
This PR.
> [6.14.z] Replace skip_if with BlockedBy for migrated BZ

- tests/foreman/cli/test_host.py
This test covers two customer cases: SAT-23576 and SAT-22677.
The first part checks that CV and LCE are returned when using the hammer host list command. The second part checks that users can specify the CV and LCE fields explicitly on the hammer host list command.
> [CC Automation] Test for hammer host list command with cv and lce fields 

- tests/foreman/api/test_reporttemplates.py
Customer case automation for generating an applied errata report after applying an invalid errata. 
All we need to test here is to make sure the report is generated without failure. However, because we never actually apply any errata, the report is an empty list. We can just assume it generated if there are no failures, but if anyone has any ideas on a potential assert that can be made im open to suggestions.
> [Customer Case] Applied Errata report with invalid errata

- robottelo/host_helpers/satellite_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15442
Since version 0.5 broker accesses the list and
decodes the stderr
https://github.com/SatelliteQE/broker/blob/master/broker/helpers.py#L512
Simple code adaptation
https://github.com/SatelliteQE/robottelo/pull/15394
tests/foreman/api/test_location.py::TestLocation::test_positive_create_update_and_remove_capsule
tests/foreman/cli/test_organization.py::test_positive_add_and_remove_capsules
> [6.14.z] Adapt to changes in broker stderr handling

- robottelo/host_helpers/satellite_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15442
Since version 0.5 broker accesses the list and
decodes the stderr
https://github.com/SatelliteQE/broker/blob/master/broker/helpers.py#L512
Simple code adaptation
https://github.com/SatelliteQE/robottelo/pull/15394
tests/foreman/api/test_location.py::TestLocation::test_positive_create_update_and_remove_capsule
tests/foreman/cli/test_organization.py::test_positive_add_and_remove_capsules
> [6.13.z] Adapt to changes in broker stderr handling

- robottelo/host_helpers/satellite_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15442
Since version 0.5 broker accesses the list and
decodes the stderr
https://github.com/SatelliteQE/broker/blob/master/broker/helpers.py#L512
Simple code adaptation
https://github.com/SatelliteQE/robottelo/pull/15394
tests/foreman/api/test_location.py::TestLocation::test_positive_create_update_and_remove_capsule
tests/foreman/cli/test_organization.py::test_positive_add_and_remove_capsules
> [6.15.z] Adapt to changes in broker stderr handling

- robottelo/cli/ansible.py
- tests/foreman/ui/test_ansible.py
As per suggestions provided in component audit-2, we need to add a test to verify roles assignment with variables on host, and also cover multiple roles with webUI
We had this test to verify roles assignment with variables on host, just modifying the existing test to cover multiple roles, and verifying roles assigned on details page with few more changes
> Modify test_positive_assign_ansible_role_variable_on_host to verify roles

- robottelo/cli/ansible.py
- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15477
As per suggestions provided in component audit-2, we need to add a test to verify roles assignment with variables on host, and also cover multiple roles with webUI
We had this test to verify roles assignment with variables on host, just modifying the existing test to cover multiple roles, and verifying roles assigned on details page with few more changes
> [6.15.z] Modify test_positive_assign_ansible_role_variable_on_host to verify roles

- robottelo/cli/ansible.py
- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15477
As per suggestions provided in component audit-2, we need to add a test to verify roles assignment with variables on host, and also cover multiple roles with webUI
We had this test to verify roles assignment with variables on host, just modifying the existing test to cover multiple roles, and verifying roles assigned on details page with few more changes
> [6.14.z] Modify test_positive_assign_ansible_role_variable_on_host to verify roles

- robottelo/cli/ansible.py
- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15477
As per suggestions provided in component audit-2, we need to add a test to verify roles assignment with variables on host, and also cover multiple roles with webUI
We had this test to verify roles assignment with variables on host, just modifying the existing test to cover multiple roles, and verifying roles assigned on details page with few more changes
> [6.13.z] Modify test_positive_assign_ansible_role_variable_on_host to verify roles

- tests/foreman/cli/test_fact.py
- tests/foreman/ui/test_fact.py
Missing following test scenarios for Facts:
- Update facts for client (CLI and UI)
Added test scenario for update client facts
> Add tests for Facts component

- tests/foreman/ui/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15452
The timediff was increased to 5 minutes.
On 'fast' UIs this can lead to poll timeouts.
Increasing the search rate to 15 fixes this:
15 * 20 / 60 = 5
https://github.com/SatelliteQE/robottelo/pull/15172
tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_real_time
tests/foreman/ui/test_syncplan.py::test_positive_synchronize_custom_product_custom_cron_past_sync_date
> [6.14.z] Increase search rate for syncplan polling

- tests/foreman/cli/test_fact.py
- tests/foreman/ui/test_fact.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14933
Missing following test scenarios for Facts:
- Update facts for client (CLI and UI)
Added test scenario for update client facts
> [6.15.z] Add tests for Facts component

- tests/foreman/ui/test_ansible.py
Ansible role should be added and removed for new_ui hostgroup
Dependent PR:https://github.com/SatelliteQE/airgun/pull/1424
> Add remove role for hostgroup

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15484
This test covers two customer cases: SAT-23576 and SAT-22677.
The first part checks that CV and LCE are returned when using the hammer host list command. The second part checks that users can specify the CV and LCE fields explicitly on the hammer host list command.
> [6.15.z] [CC Automation] Test for hammer host list command with cv and lce fields 

- tests/foreman/api/test_hostcollection.py
- tests/foreman/ui/test_contenthost.py
- tests/foreman/ui/test_hostcollection.py
Updating Host-Content and Host Collections to be sca only.
https://github.com/SatelliteQE/airgun/pull/1425
> [RFE] Updating HostCollections and HostContent to be SCA Only

- tests/foreman/api/test_http_proxy.py
- tests/foreman/api/test_syncplan.py
- tests/foreman/cli/test_activationkey.py
- tests/foreman/cli/test_contentaccess.py
- tests/foreman/cli/test_repository.py
- tests/foreman/ui/test_repository.py
- tests/upgrades/test_syncplan.py
During component eval some changes were proposed by PX/SD/QE for upgrade tests (scenario and all-tiers).
This PR just implements a few of them, mostly related to @SatelliteQE/phoenix 
For reference check the _Component feedback sheet - Team Platform_ g-sheet
Split into a bunch of tiny commits, one per each g-sheet line 
pytest: tests/foreman/cli/test_activationkey.py -k test_positive_update_aks_to_chost
> Updates for upgrades component eval

- tests/foreman/ui/test_ansible.py
The test is a customer BZ but we missed to add the docstring.
Added the docstring for customer scenario and BZ.
> Set customer scenario to True

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15513
The test is a customer BZ but we missed to add the docstring.
Added the docstring for customer scenario and BZ.
> [6.15.z] Set customer scenario to True

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15513
The test is a customer BZ but we missed to add the docstring.
Added the docstring for customer scenario and BZ.
> [6.14.z] Set customer scenario to True

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15513
The test is a customer BZ but we missed to add the docstring.
Added the docstring for customer scenario and BZ.
> [6.13.z] Set customer scenario to True

- tests/foreman/api/test_http_proxy.py
- tests/foreman/api/test_syncplan.py
- tests/foreman/cli/test_activationkey.py
- tests/foreman/cli/test_contentaccess.py
- tests/foreman/cli/test_repository.py
- tests/foreman/ui/test_repository.py
- tests/upgrades/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15415
During component eval some changes were proposed by PX/SD/QE for upgrade tests (scenario and all-tiers).
This PR just implements a few of them, mostly related to @SatelliteQE/phoenix 
For reference check the _Component feedback sheet - Team Platform_ g-sheet
Split into a bunch of tiny commits, one per each g-sheet line 
pytest: tests/foreman/cli/test_activationkey.py -k test_positive_update_aks_to_chost
> [6.15.z] Updates for upgrades component eval

- tests/foreman/api/test_http_proxy.py
- tests/foreman/api/test_syncplan.py
- tests/foreman/cli/test_activationkey.py
- tests/foreman/cli/test_contentaccess.py
- tests/foreman/cli/test_repository.py
- tests/foreman/ui/test_repository.py
- tests/upgrades/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15415
During component eval some changes were proposed by PX/SD/QE for upgrade tests (scenario and all-tiers).
This PR just implements a few of them, mostly related to @SatelliteQE/phoenix 
For reference check the _Component feedback sheet - Team Platform_ g-sheet
Split into a bunch of tiny commits, one per each g-sheet line 
pytest: tests/foreman/cli/test_activationkey.py -k test_positive_update_aks_to_chost
> [6.14.z] Updates for upgrades component eval

- tests/foreman/cli/test_contentview.py
Adds coverage for https://bugzilla.redhat.com/show_bug.cgi?id=1974225 / https://issues.redhat.com/browse/SATQE-17141
There is one usage of time.sleep(2) - this is to allow the incremental update to propagate, and trigger the CCV publish, but there's probably a better way for this to be done. 
pytest: tests/foreman/cli/test_contentview.py -k 'test_ccv_inc_update_autopublish'
> [CV Eval] Test Coverage for ccv interaction with incremental update

- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15525
Adds coverage for https://bugzilla.redhat.com/show_bug.cgi?id=1974225 / https://issues.redhat.com/browse/SATQE-17141
There is one usage of time.sleep(2) - this is to allow the incremental update to propagate, and trigger the CCV publish, but there's probably a better way for this to be done. 
pytest: tests/foreman/cli/test_contentview.py -k 'test_ccv_inc_update_autopublish'
> [6.14.z] [CV Eval] Test Coverage for ccv interaction with incremental update

- robottelo/cli/acs.py
- tests/foreman/api/test_acs.py
- tests/foreman/cli/test_acs.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15451
Adds test coverage for: https://bugzilla.redhat.com/show_bug.cgi?id=2126420 / https://issues.redhat.com/browse/SAT-18199
Also updates robottelo CLI to support `hammer alternate-content-source bulk` actions, and the API test to cover the endpoint added in https://github.com/SatelliteQE/nailgun/pull/1086
PRT test Cases example
pytest: tests/foreman/api/test_acs.py -k 'test_positive_run_bulk_actions'
pytest: tests/foreman/cli/test_acs.py -k 'test_bulk_actions'
> [6.15.z] [CC Automation] Update API test to use refresh-all and add CLI test for bulk actions

- tests/foreman/cli/test_host.py
[CC SAT-22048](https://issues.redhat.com/browse/SAT-22048)
Registration of the client system with Capsule is successful with the below error message.
`HTTP error code 422: Validation failed: Content view environment content facets is invalid`
This PR tests both the scenarios when settings `"validate_host_lce_content_source_coherence" is set to Yes/No`
N/A
> CC-client registration with capsule based on setting value

- tests/foreman/cli/test_host.py
Small mistake in PR https://github.com/SatelliteQE/robottelo/pull/15428 related to paramerization. So test will only run for rhel9. @damoore044 notice this when 6.15.z CP PR ran only one test case.
Update marker for test
pytest: tests/foreman/cli/test_host.py -k 'test_host_registration_with_capsule_using_content_coherence'
@damoore044 Please Ack and merge this PR once PRT pass for all 6 rhel versions.
> fix parameterisation issue to run test for rhel7/8/9

- conf/vmware.yaml.template
- tests/foreman/api/test_computeresource_vmware.py
Adding VMware e2e api provisioning test.
> Component Audit - VMware api e2e provisioning test

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15537
Small mistake in PR https://github.com/SatelliteQE/robottelo/pull/15428 related to paramerization. So test will only run for rhel9. @damoore044 notice this when 6.15.z CP PR ran only one test case.
Update marker for test
pytest: tests/foreman/cli/test_host.py -k 'test_host_registration_with_capsule_using_content_coherence'
@damoore044 Please Ack and merge this PR once PRT pass for all 6 rhel versions.
> [6.15.z] fix parameterisation issue to run test for rhel7/8/9

- tests/foreman/longrun/test_oscap.py
https://issues.redhat.com/browse/SAT-23240
Add an entity in airgun and test through WebUI (this is a WebUI-only feature). Create a host, run a scan, remediate an issue.
Requires https://github.com/SatelliteQE/airgun/pull/1441
> Add a scap remediation feature test

- robottelo/constants/__init__.py
These parametrize into our FAM tests but don't actually exist. Not sure how they got copied over.
Remove them since they are not real modules.
Note: This doesn't really need any testing, it will just no longer parametrize these.
> Remove non-existing ansible modules

- conftest.py
- pytest_plugins/select_random_tests.py
- The Automation team requested to add support for pytest option to randomly select and run number/percentage of tests from the collection.
- Add pytest option `--select-random-tests`: Number/Percentage of tests to randomly select and run from selected test collection.
- Add pytest option `--random-seed`: Seed value for random test collection. It should be used with --select-random-tests option.
- To rerun the same test collection use the same seed value, check robottelo.log for seed value generated(if it was not provided before).
- `pytest tests/foreman/ --select-random-tests '5%'`
- `pytest tests/foreman/ --select-random-tests 4 --random-seed fsdaxv` 
- See SAT-20829
> Add pytest option to randomly select and run number/percentage of tests from the collection.

- robottelo/constants/__init__.py
- tests/foreman/api/test_repository.py
- tests/upgrades/test_repository.py
We need a test case to verify that docker manifest labels, annotations and other flags are indexed
- after 6.15 -> 6.16 upgrade in the post-upgrade task.
- during repo sync at 6.16
This PR adds such cases.
Needs https://github.com/SatelliteQE/nailgun/pull/1188
For upgrade scenario (delivered in f-m 1.6.8):
PRE:
```
Launching pytest with arguments -m pre_upgrade -k test_pre_container_repo_sync tests/upgrades/test_repository.py --no-header --no-summary -q in /home/vsedmik/PycharmProjects/robottelo
collecting ... collected 10 items / 9 deselected / 1 selected
tests/upgrades/test_repository.py::TestScenarioContainerRepoSync::test_pre_container_repo_sync 
======================= 1 passed, 9 deselected in 47.61s …
```
> Add upgrade scenario test for docker manifest indexing

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15549
These parametrize into our FAM tests but don't actually exist. Not sure how they got copied over.
Remove them since they are not real modules.
Note: This doesn't really need any testing, it will just no longer parametrize these.
> [6.15.z] Remove non-existing ansible modules

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15549
These parametrize into our FAM tests but don't actually exist. Not sure how they got copied over.
Remove them since they are not real modules.
Note: This doesn't really need any testing, it will just no longer parametrize these.
> [6.14.z] Remove non-existing ansible modules

- tests/foreman/sys/test_fam.py
The `luna_hostgroup` test playbook fails in CI because we are missing an ansible role that the hostgroup is trying to use.
Install and import the role as part of the setup for the machine.
> Add setup for luna_hostgroup test playbook

- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15550
The `luna_hostgroup` test playbook fails in CI because we are missing an ansible role that the hostgroup is trying to use.
Install and import the role as part of the setup for the machine.
> [6.15.z] Add setup for luna_hostgroup test playbook

- tests/foreman/cli/test_ping.py
```
tests/foreman/cli/test_ping.py:40: in test_positive_ping
assert result.stderr[1].decode() == ''
E   IndexError: string index out of range
```
6.15 branch only
> test ping fix for 6.15

- tests/foreman/cli/test_leapp_client.py
BZ for leapp test has been fixed and in review state, so it can be removed.
Also,  RHEL8 is updated to 8.10.
Removed the fixed BZ and reverted the target version change.
> Remove fixed BZ from leapp tests and update RHEL8 to 8.10

- tests/foreman/cli/test_leapp_client.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15137
BZ for leapp test has been fixed and in review state, so it can be removed.
Also,  RHEL8 is updated to 8.10.
Removed the fixed BZ and reverted the target version change.
> [6.15.z] Remove fixed BZ from leapp tests and update RHEL8 to 8.10

- tests/foreman/cli/test_leapp_client.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15137
BZ for leapp test has been fixed and in review state, so it can be removed.
Also,  RHEL8 is updated to 8.10.
Removed the fixed BZ and reverted the target version change.
> [6.14.z] Remove fixed BZ from leapp tests and update RHEL8 to 8.10

- tests/foreman/cli/test_discoveredhost.py
Missing  test coverage for SAT-24197, to verify foreman-discovery-image is built on latest up-to-date RHEL
Add test coverage for SAT-24197, to verify foreman-discovery-image is built on latest up-to-date RHEL
> Add test coverage for SAT-24197

- tests/foreman/cli/test_fact.py
- tests/foreman/ui/test_fact.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14933
Missing following test scenarios for Facts:
- Update facts for client (CLI and UI)
Added test scenario for update client facts
> [6.14.z] Add tests for Facts component

- tests/foreman/api/test_convert2rhel.py
Data telemetry input/option is removed from convert2rhel job templates in https://github.com/theforeman/foreman_ansible/pull/710
Remove Data telemetry input/option from convert2rhel tests
Also, Adding check to vefify convert2rhel conversion facts to cover SAT-24654
> Remove Data telemetry option from convert2rhel tests

- robottelo/constants/__init__.py
We are still using RHEL7 in GCE which needs to be updated for latest RHEL.
Updated to use RHEL9 in GCE tests for provisioning.
> Update RHEL version for GCE

- tests/foreman/destructive/test_ansible.py
Ansible Roles pagination test was failing due to `no widget name Pagination` error while editing the hostgroup
Dependent Airgun PR: https://github.com/SatelliteQE/airgun/pull/1455
> Fix Ansible Roles pagination test

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15576
We are still using RHEL7 in GCE which needs to be updated for latest RHEL.
Updated to use RHEL9 in GCE tests for provisioning.
> [6.14.z] Update RHEL version for GCE

- tests/foreman/destructive/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15575
Ansible Roles pagination test was failing due to `no widget name Pagination` error while editing the hostgroup
Dependent Airgun PR: https://github.com/SatelliteQE/airgun/pull/1455
> [6.15.z] Fix Ansible Roles pagination test

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15576
We are still using RHEL7 in GCE which needs to be updated for latest RHEL.
Updated to use RHEL9 in GCE tests for provisioning.
> [6.13.z] Update RHEL version for GCE

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15576
We are still using RHEL7 in GCE which needs to be updated for latest RHEL.
Updated to use RHEL9 in GCE tests for provisioning.
> [6.15.z] Update RHEL version for GCE

- tests/foreman/destructive/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15575
Ansible Roles pagination test was failing due to `no widget name Pagination` error while editing the hostgroup
Dependent Airgun PR: https://github.com/SatelliteQE/airgun/pull/1455
> [6.14.z] Fix Ansible Roles pagination test

- tests/foreman/ui/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15205
Missing coverage for BZ:2238952 and BZ:2268544, where we verified Customize host button works to provision a discovered host with a few customizations.
Add test coverage for BZ:2238952 and BZ:2268544, to verify functionality of discovery provisioning with Customize host button with a few customizations, and also covering BZ:2025523 where we've validated the assigned Ansible roles to a HostGroup gets auto executed when host is provisioned.
Also, verifying new test and modifying existing test to validate if provisioning is sucessfull on new host UI instead of old UI
https://github.com/SatelliteQE/airgun/pull/1397
> [6.15.z] Add test coverage for BZ:2238952 and BZ:2025523

- robottelo/constants/__init__.py
- tests/foreman/api/test_repository.py
- tests/foreman/cli/test_repository.py
- tests/foreman/ui/test_repository.py
SHA1 is no longer supported by Pulp (see https://projects.theforeman.org/issues/37522) which renders even more tests failing in validation for `sha1` in stream builds:
```
WARNING  nailgun.client:client.py:126 Received HTTP 422 response: {"displayMessage":"Validation failed: Checksum type is not included in the list","errors":{"checksum_type":["is not included in the list"]}}
```
Define the supported checksums in constants and use them.
pytest: tests/foreman/api/test_repository.py tests/foreman/cli/test_repository.py -k checksum
> Update repository tests with supported checksums

- tests/foreman/endtoend/test_api_endtoend.py
API endpoint for facts values : /api/hosts/:host_id/facts was incorrectly placed causing test failure.
Updated.
> Update API endpoint for host facts

- tests/foreman/cli/test_fact.py
Added BZ# 2004158 [https://bugzilla.redhat.com/show_bug.cgi?id=2004158 
](url)
> Update customer BZ in docstring

- robottelo/cli/host.py
test failures on stream with `TypeError: Host.info() got an unexpected keyword argument 'output_format'`
made host info method configurable
> host info issues fix

- tests/foreman/ui/test_repository.py
Component audit - SAT-23363
Removed testcase `test_positive_sync_repo_and_verify_checksum`
Merged into `test_positive_sync_custom_repo_yum`
Updated testcase name `test_positive_sync_yum_repo_and_verify_content_checksum`
NA
```
pytest: tests/foreman/ui//test_repository.py -k 'test_positive_sync_yum_repo_and_verify_content_checksum'
```
> CA-merge repo UI tests scenarios, sync and check content checksum

- tests/foreman/cli/test_fact.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15593
Added BZ# 2004158 [https://bugzilla.redhat.com/show_bug.cgi?id=2004158 
](url)
> [6.15.z] Update customer BZ in docstring

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15594
`http_proxy_ipv6_url` is accessed despite ipv6 is set to false on default.
```
pytest_fixtures/core/broker.py:55: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.11/contextlib.py:137: in __enter__
return next(self.gen)
pytest_fixtures/core/broker.py:37: in _target_sat_imp
_default_sat.enable_ipv6_http_proxy()
robottelo/hosts.py:1829: in enable_ipv6_http_proxy
if not all([settings.server.is_ipv6, settings.server.http_proxy_ipv6_url]):
../../../.virtualenvs/robottelo/lib/python3.11/site-packages/dynaconf/utils/boxing.py:18: in evaluate
value = f(dynabox, item, …
```
> [6.15.z] Fix ipv6 proxy url validation

- conftest.py
- pytest_plugins/select_random_tests.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15450
- The Automation team requested to add support for pytest option to randomly select and run number/percentage of tests from the collection.
- Add pytest option `--select-random-tests`: Number/Percentage of tests to randomly select and run from selected test collection.
- Add pytest option `--random-seed`: Seed value for random test collection. It should be used with --select-random-tests option.
- To rerun the same test collection use the same seed value, check robottelo.log for seed value generated(if it was not provided before).
- `pytest tests/foreman/ --select-random-tests '5%'`
- `pytest tests/foreman/ --select-random-tests 4 --random-seed fsdaxv` 
- See SAT-20829
> [6.14.z] Add pytest option to randomly select and run number/percentage of tests from the collection.

- conftest.py
- pytest_plugins/select_random_tests.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15450
- The Automation team requested to add support for pytest option to randomly select and run number/percentage of tests from the collection.
- Add pytest option `--select-random-tests`: Number/Percentage of tests to randomly select and run from selected test collection.
- Add pytest option `--random-seed`: Seed value for random test collection. It should be used with --select-random-tests option.
- To rerun the same test collection use the same seed value, check robottelo.log for seed value generated(if it was not provided before).
- `pytest tests/foreman/ --select-random-tests '5%'`
- `pytest tests/foreman/ --select-random-tests 4 --random-seed fsdaxv` 
- See SAT-20829
> [6.15.z] Add pytest option to randomly select and run number/percentage of tests from the collection.

- conftest.py
- pytest_plugins/select_random_tests.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15450
- The Automation team requested to add support for pytest option to randomly select and run number/percentage of tests from the collection.
- Add pytest option `--select-random-tests`: Number/Percentage of tests to randomly select and run from selected test collection.
- Add pytest option `--random-seed`: Seed value for random test collection. It should be used with --select-random-tests option.
- To rerun the same test collection use the same seed value, check robottelo.log for seed value generated(if it was not provided before).
- `pytest tests/foreman/ --select-random-tests '5%'`
- `pytest tests/foreman/ --select-random-tests 4 --random-seed fsdaxv` 
- See SAT-20829
> [6.13.z] Add pytest option to randomly select and run number/percentage of tests from the collection.

- tests/foreman/cli/test_host.py
assertion error
reacting to change in netw interfaces object
> host interface crud tests

- tests/foreman/cli/test_docker.py
- tests/foreman/cli/test_repository.py
1. Name for container image tags was unified with API some time ago but we haven't update our tests.
2. The `container-image-tags-filter` has been deprecated and is not printed by hammer. It will be replaced win `included-tags` and `excluded-tags`.
This PR fixes 1. and skips 2. until the bugjira is closed
https://issues.redhat.com/browse/SAT-26322
pytest: tests/foreman/cli/test_docker.py::TestDockerRepository::test_positive_sync tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_set_tags_later_additive tests/foreman/cli/test_repository.py::TestRepository::test_positive_synchronize_docker_repo_set_tags_later_content_only tests/foreman/cli/test_repository.py::TestRepository::test_negative_synchronize_docker_repo_with_mix_valid_ …
> Fix container tags related failures

- tests/foreman/ui/test_location.py
- tests/foreman/ui/test_organization.py
bz closed as migrated, tests no longer skipped
> adding :BlockedBy to org/loc tests

- tests/foreman/ui/test_location.py
- tests/foreman/ui/test_organization.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15608
bz closed as migrated, tests no longer skipped
> [6.15.z] adding :BlockedBy to org/loc tests

- tests/foreman/ui/test_location.py
- tests/foreman/ui/test_organization.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15608
bz closed as migrated, tests no longer skipped
> [6.14.z] adding :BlockedBy to org/loc tests

- tests/foreman/ui/test_location.py
- tests/foreman/ui/test_organization.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15608
bz closed as migrated, tests no longer skipped
> [6.13.z] adding :BlockedBy to org/loc tests

- robottelo/cli/contentview.py
- tests/foreman/cli/test_contentview.py
Test Coverage for https://bugzilla.redhat.com/show_bug.cgi?id=2137318/https://issues.redhat.com/browse/SAT-15185
Added Test + support for `content view version purge`
pytest: tests/foreman/cli/test_contentview.py -k 'test_cv_version_purge'
> [CV Eval] Test for CV Eval/BZ

- tests/foreman/virtwho/api/test_esx_sca.py
As the default no_proxy is not enabled in /etc/virt-who.conf , if the no_proxy is not set, it will also not enable in /etc/virt-who.conf , so remove the default check
[system_environment]
#http_proxy=
#https_proxy=
#no_proxy=
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/api/test_esx_sca.py -k test_positive_proxy_option --disable-pytest-warnings -q
1 passed, 12 deselected, 3 warnings in 174.34s (0:02:54)
```
> remove no_proxy default check in /etc/virt-who.conf

- tests/foreman/cli/test_repository.py
Component audit - SAT-23366
Merged into `test_positive_export_ansible_collection`
Removed testcase `test_positive_sync_ansible_collection`
Updated testcase name `test_positive_sync_and_export_ansible_collection`
NA
```
pytest: tests/foreman/cli/test_repository.py -k 'test_positive_sync_and_export_ansible_collection'
```
**Note:**
As per [comment](https://github.com/SatelliteQE/robottelo/pull/15621#pullrequestreview-2171140024) from @vsedmik updating file as export and import scenario is already covered in ISS tests
> CA- merge repo cli test scenarios, ansible collection repo sync and export

- robottelo/constants/__init__.py
"actions.remote_execution.run_host_job_ansible_run_insights_plan_succeeded" no longer around in stream 
confirmed with dev that this is an intentional change, related to https://github.com/theforeman/foreman_ansible/pull/712
> removed outdated webhook action from parametrization

- tests/foreman/cli/test_host.py
assertion error
reacting to change in param object
> fix in hosts param crud test

- tests/foreman/cli/test_artifacts.py
For the artifacts repair test we need to identify the particular artifacts to repair. For yum and file repos we do so through published files/urls, but for docker and AC repos we do so based on the artifact creation time, which must be newer than the repo sync time. And since all repos from all organizations on a Satellite share the artifacts based on their checksum (their actual content), we need to ensure that the artifacts were synced for the very first time in that test, not earlier by another test.
My previous assumption was that the module-scoped `module_target_sat` would provide a brand new Satellite for the module with no repos previously synced, but the recent failures prove the assumption was wrong and the repos were synced somewhere else before:
``` …
```
> Use unique repos for artifacts repair tests

- robottelo/cli/contentview.py
- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15519
Test Coverage for https://bugzilla.redhat.com/show_bug.cgi?id=2137318/https://issues.redhat.com/browse/SAT-15185
Added Test + support for `content view version purge`
pytest: tests/foreman/cli/test_contentview.py -k 'test_cv_version_purge'
> [6.15.z] [CV Eval] Test for CV Eval/BZ

- robottelo/utils/url.py
- Confs having integer type setting complaints when migrating all the settings that contain Ipv4 string to convert to Ipv6 even though the int setting does not have Ipv4 containing value .
Stacktrace:
```
dotted_settings = '.'.join(setting_major)
for _key, _val in settings_list.items():
TypeError: sequence item 6: expected str instance, int found
```
- Altering the settings to string just when setting the converted value which should not change the type of any integer setting.
- The solution currently works for us because we don't have any IPV4-specific URLs under integer type setting. 
- But if we do in the future we will face the  issue of `converting the key from an integer type parent or key as dynaconf assists it to be string` for which the issue …
> Handle int type conf key for dynaconf ipv6 migration

- robottelo/hosts.py
- tests/foreman/cli/test_repositories.py
New setting and functionality to purge successfully completed pulp tasks was added to the stream and backported to `6.15.z` and we should test it.
This PR adds:
- a test case to cover the functionality
- a helper to run orphan cleanup
https://issues.redhat.com/browse/SAT-25155
pytest: tests/foreman/cli/test_repositories.py -k purge
> Add a test case for purge of pulp tasks

- robottelo/utils/url.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15630
- Confs having integer type setting complaints when migrating all the settings that contain Ipv4 string to convert to Ipv6 even though the int setting does not have Ipv4 containing value .
Stacktrace:
```
dotted_settings = '.'.join(setting_major)
for _key, _val in settings_list.items():
TypeError: sequence item 6: expected str instance, int found
```
- Altering the settings to string just when setting the converted value which should not change the type of any integer setting.
- The solution currently works for us because we don't have any IPV4-specific URLs under integer type setting. 
- But if we do in the future we will face the  issue of `converting the key from an integer type parent or key as dynaconf assists it …
> [6.15.z] Handle int type conf key for dynaconf ipv6 migration

- tests/foreman/virtwho/api/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15592
As the default no_proxy is not enabled in /etc/virt-who.conf , if the no_proxy is not set, it will also not enable in /etc/virt-who.conf , so remove the default check
[system_environment]
#http_proxy=
#https_proxy=
#no_proxy=
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/api/test_esx_sca.py -k test_positive_proxy_option --disable-pytest-warnings -q
1 passed, 12 deselected, 3 warnings in 174.34s (0:02:54)
```
> [6.15.z] remove no_proxy default check in /etc/virt-who.conf

- tests/foreman/virtwho/api/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15592
As the default no_proxy is not enabled in /etc/virt-who.conf , if the no_proxy is not set, it will also not enable in /etc/virt-who.conf , so remove the default check
[system_environment]
#http_proxy=
#https_proxy=
#no_proxy=
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/api/test_esx_sca.py -k test_positive_proxy_option --disable-pytest-warnings -q
1 passed, 12 deselected, 3 warnings in 174.34s (0:02:54)
```
> [6.14.z] remove no_proxy default check in /etc/virt-who.conf

- .github/workflows/auto_cherry_pick_merged.yaml
Following are the scenarios when we were not able to rerun the Merged PRs AutoCherrypick:
- Autocherrypicking failed due to OOM/unidentified_abort during ACP GHA run
- Missed adding the version label while autocherrypicking for a specific version
- Retry of AutoCherrypicking of a big PR when failed with conflicts due to others didn't cherry-pick the changes. Now we could ask others to fix their cherrypicks and simply retry the big PRs ACP from this GHA.
- Bulk PRs cherry-pick in about to depreciate branch, but need the branch for immediate testing or for multiple reasons
- etc
- We should be able to handle all the above scenarios now with the new standalone `Retry Merged PRs AutoCherryPick`
- https://github.com/jyejare/github-cherry-pick-action/pull/42 Allows to take PR number as an input …
> Retry/Rerun PR Autocherrypick post merge

- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15550
The `luna_hostgroup` test playbook fails in CI because we are missing an ansible role that the hostgroup is trying to use.
Install and import the role as part of the setup for the machine.
> [6.14.z] Add setup for luna_hostgroup test playbook

- tests/foreman/cli/test_repository.py
Component audit - SAT-23370
Removed testcase `test_negative_synchronize_docker_repo_with_invalid_tags`
Scenario already exists in testcase `test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags`
NA
```
pytest: tests/foreman/cli/test_repository.py -k test_negative_synchronize_docker_repo_with_mix_valid_invalid_tags
```
> CA merge test scenario, sync docker repo valid invalid tags

- tests/foreman/cli/test_capsule.py
This test is failing but the API version which is very similar isn't.
Add missing fixture setup.
pytest: tests/foreman/cli/test_capsule.py::test_positive_import_puppet_classes
> Fix CLI import puppet class test

- tests/foreman/cli/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15650
This test is failing but the API version which is very similar isn't.
Add missing fixture setup.
pytest: tests/foreman/cli/test_capsule.py::test_positive_import_puppet_classes
> [6.15.z] Fix CLI import puppet class test

- tests/foreman/cli/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15521
Missing  test coverage for SAT-24197, to verify foreman-discovery-image is built on latest up-to-date RHEL
Add test coverage for SAT-24197, to verify foreman-discovery-image is built on latest up-to-date RHEL
> [6.14.z] Add test coverage for SAT-24197

- tests/foreman/cli/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15650
This test is failing but the API version which is very similar isn't.
Add missing fixture setup.
pytest: tests/foreman/cli/test_capsule.py::test_positive_import_puppet_classes
> [6.13.z] Fix CLI import puppet class test

- tests/foreman/cli/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15650
This test is failing but the API version which is very similar isn't.
Add missing fixture setup.
pytest: tests/foreman/cli/test_capsule.py::test_positive_import_puppet_classes
> [6.14.z] Fix CLI import puppet class test

- tests/foreman/cli/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15521
Missing  test coverage for SAT-24197, to verify foreman-discovery-image is built on latest up-to-date RHEL
Add test coverage for SAT-24197, to verify foreman-discovery-image is built on latest up-to-date RHEL
> [6.13.z] Add test coverage for SAT-24197

- conf/fam.yaml.template
the password field is protected, so the API doesn't return it and thus we always detect a change, failing tests
don't set the password field
> FAM: don't set a password for auth_source_ldap tests

- conf/fam.yaml.template
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15647
the password field is protected, so the API doesn't return it and thus we always detect a change, failing tests
don't set the password field
> [6.15.z] FAM: don't set a password for auth_source_ldap tests

- conf/fam.yaml.template
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15647
the password field is protected, so the API doesn't return it and thus we always detect a change, failing tests
don't set the password field
> [6.14.z] FAM: don't set a password for auth_source_ldap tests

- tests/foreman/ui/test_ansible.py
With user which is non-admin but it is in usergroup which should give him administrator role is possible to access lot of pages, but giving Permission denied
It verifies if a non-admin user in the user group can access the WebUI.
> non-admin user acess with usergroup

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15489
With user which is non-admin but it is in usergroup which should give him administrator role is possible to access lot of pages, but giving Permission denied
It verifies if a non-admin user in the user group can access the WebUI.
> [6.14.z] non-admin user acess with usergroup

- tests/foreman/cli/test_repository.py
PIT marker missing for repositories component.
This PR changes
Proposing new `default_rhel_version`, changes made into the gitlab `MR-1413`
> add PIT marker for repositories test

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15655
PIT marker missing for repositories component.
This PR changes
Proposing new `default_rhel_version`, changes made into the gitlab `MR-1413`
> [6.15.z] add PIT marker for repositories test

- tests/foreman/cli/test_http_proxy.py
Product update with HTTP proxy now runs `Actions::Katello::Repository::Update` synchronously - shows the "dot progress bar" instead of printing 'Product proxy updated' message and running the task async as we are used to in previous versions.
```
[root@sat ~]# hammer product update-proxy --ids=5,6 --http-proxy-policy='use_selected_http_proxy' --http-proxy-id=2
[..........................................................................................................] [100%]
[root@sat ~]# 
```
Remove the assertion for that message and just keep testing the result.
> Remove deprecated assertions for HTTP Proxy CLI

- tests/foreman/api/test_ansible.py
- tests/foreman/api/test_computeresource_azurerm.py
- tests/foreman/api/test_computeresource_gce.py
- tests/foreman/api/test_registration.py
- tests/foreman/cli/test_ansible.py
- tests/foreman/cli/test_fact.py
- tests/foreman/destructive/test_registration.py
- tests/foreman/ui/test_registration.py
Adding PIT marker to Rocket team components
> Add PIT marker for Rocket team components

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15489
With user which is non-admin but it is in usergroup which should give him administrator role is possible to access lot of pages, but giving Permission denied
It verifies if a non-admin user in the user group can access the WebUI.
> [6.15.z] non-admin user acess with usergroup

- tests/foreman/api/test_provisioning.py
Replace skip_if with BlockedBy for migrated BZ
> Replace skip_if with BlockedBy for migrated httpboot BZ

- tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15673
Replace skip_if with BlockedBy for migrated BZ
> [6.14.z] Replace skip_if with BlockedBy for migrated httpboot BZ

- tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15673
Replace skip_if with BlockedBy for migrated BZ
> [6.13.z] Replace skip_if with BlockedBy for migrated httpboot BZ

- robottelo/hosts.py
- tests/foreman/cli/test_host.py
There is no test coverage for existing features around multi-CV.
Add tests covering existing functionality. This PR adds the first test, covering the downstream Setting that is not exposed.
> Add test for host multi-CV

- tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15673
Replace skip_if with BlockedBy for migrated BZ
> [6.15.z] Replace skip_if with BlockedBy for migrated httpboot BZ

- tests/foreman/api/test_provisioningtemplate.py
ntp uses chronyd instead of ntpdate which is deprecated.
RHEL9 uses timesource when ntp-server host param is used.
Added a check to verify chronyd is getting installed in rendered template
Added a check for timesource option in rendered template
> Add check for chronyd install and timesource option for RHEL9  in rendered template

- pytest_plugins/jira_comments.py
- robottelo/constants/__init__.py
- robottelo/utils/issue_handlers/jira.py
- Reduce the frequency of commenting test results on Jira. 
Take action based on labels
- Initially set a Pass/Fail label based on the test result
- If the state changes add a comment
- If the state is already failing, and test is failing, still add a comment
- If the state is already passing, and the test passes, don’t add a comment
- SAT-26505 and SAT-26504
> Add jira comments based on Jira labels

- pytest_fixtures/core/sat_cap_factory.py
- tests/foreman/maintain/test_backup_restore.py
- https://github.com/theforeman/foreman_maintain/pull/893 affects the list of files generated during offline backup. 
- Update the `OFFLINE_SAT_FILES` to reflect changes.
- Remove `test_positive_backup_offline_logical`
- Remove unwanted code
> Update offline backup files list

- pytest_plugins/jira_comments.py
- robottelo/constants/__init__.py
- robottelo/utils/issue_handlers/jira.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15686
- Reduce the frequency of commenting test results on Jira. 
Take action based on labels
- Initially set a Pass/Fail label based on the test result
- If the state changes add a comment
- If the state is already failing, and test is failing, still add a comment
- If the state is already passing, and the test passes, don’t add a comment
- SAT-26505 and SAT-26504
> [6.13.z] Add jira comments based on Jira labels

- pytest_plugins/jira_comments.py
- robottelo/constants/__init__.py
- robottelo/utils/issue_handlers/jira.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15686
- Reduce the frequency of commenting test results on Jira. 
Take action based on labels
- Initially set a Pass/Fail label based on the test result
- If the state changes add a comment
- If the state is already failing, and test is failing, still add a comment
- If the state is already passing, and the test passes, don’t add a comment
- SAT-26505 and SAT-26504
> [6.14.z] Add jira comments based on Jira labels

- pytest_plugins/jira_comments.py
- robottelo/constants/__init__.py
- robottelo/utils/issue_handlers/jira.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15686
- Reduce the frequency of commenting test results on Jira. 
Take action based on labels
- Initially set a Pass/Fail label based on the test result
- If the state changes add a comment
- If the state is already failing, and test is failing, still add a comment
- If the state is already passing, and the test passes, don’t add a comment
- SAT-26505 and SAT-26504
> [6.15.z] Add jira comments based on Jira labels

- tests/foreman/api/test_capsulecontent.py
New setting referred in https://github.com/SatelliteQE/robottelo/pull/15371 has been backported to 6.15.3 and needs to be verified.
Backport the related test too.
https://issues.redhat.com/browse/SAT-26622
pytest: tests/foreman/api/test_capsulecontent.py -k test_automatic_content_counts_update_toggle
> [6.15.z] Add test case for automatic content counts update toggling

- tests/foreman/ui/test_computeresource_vmware.py
After provisioning a new host the assigned Ansible roles from hostgroups
are not executed on the new host
The method below assigns a role to a hostgroup, then assigns the same hostgroup to a host, and provisions the host to verify that the role is correctly assigned.
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1439
> The hostgroup Ansible job schedule along with host provisioning.

- tests/foreman/cli/test_host.py
- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15752
Adding PIT markers for interop testing
> [6.15.z] [KatelloTracer] Adding PIT markers

- tests/foreman/cli/test_host.py
- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15752
Adding PIT markers for interop testing
> [6.13.z] [KatelloTracer] Adding PIT markers

- pytest_fixtures/core/xdist.py
- tests/foreman/cli/test_computeresource_azurerm.py
Encountering an assertion error that is causing three test cases to fail.
Fixed the error, update the assertion
> Tfa fix compute resources azure

- tests/foreman/api/test_product.py
Component audit - SAT-23547
Merge 4 related scenarios
```
- Scenario 1: 
- test_positive_update_gpg
- test_positive_create_with_gpg
- new name: test_positive_create_product_and_update_gpg
- Scenario 2:
- test_positive_update_name_to_original
- test_positive_update_name
```
NA
```
pytest: tests/foreman/api/test_product.py -k 'test_positive_create_product_and_update_gpg' or 'test_positive_update_name_to_original'
```
> merged api test product scenarios

- pytest_fixtures/component/contentview.py
- robottelo/host_helpers/satellite_mixins.py
There is a "Multi-CV" feature partially implemented into 6.16 as a tech preview and we need to deliver related coverage for the implemented bits. For this reason we need to enable the feature in a non-standard way until it's released.
This PR just adds a helper to enable related setting (to be used with any Satellite) and a session-scoped fixture which would provide Satellite with that setting enabled and set.
> Add multi-cv enable helper and fixture

- pytest_fixtures/core/sat_cap_factory.py
- robottelo/hosts.py
We have removed `config_sat.j2` from our internal repository. The promtail configuration that made promtail watch for changes in Satellite-related log files was merged to a general config file, therefore we do not need to specify the file anymore.
Remove the `promtail_config_template_file` broker argument, use the default (the only one we now have) promtail configuration file.
* satlab-tower!1090 (merged)
> Remove promtail configuration option

- tests/foreman/api/test_repository.py
Component audit - SAT-23548
1. test_positive_update_unprotected
2. test_positive_update_url
New test name: test_positive_update_repo_url_and_unprotected_flag
NA
```
pytest: tests/foreman/api/test_repository.py -k 'test_positive_update_repo_url_and_unprotected_flag'
```
> merged possible test from api repositories

- pytest_fixtures/core/sat_cap_factory.py
- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15763
We have removed `config_sat.j2` from our internal repository. The promtail configuration that made promtail watch for changes in Satellite-related log files was merged to a general config file, therefore we do not need to specify the file anymore.
Remove the `promtail_config_template_file` broker argument, use the default (the only one we now have) promtail configuration file.
* satlab-tower!1090 (merged)
> [6.14.z] Remove promtail configuration option

- pytest_fixtures/core/sat_cap_factory.py
- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15763
We have removed `config_sat.j2` from our internal repository. The promtail configuration that made promtail watch for changes in Satellite-related log files was merged to a general config file, therefore we do not need to specify the file anymore.
Remove the `promtail_config_template_file` broker argument, use the default (the only one we now have) promtail configuration file.
* satlab-tower!1090 (merged)
> [6.15.z] Remove promtail configuration option

- pytest_fixtures/core/sat_cap_factory.py
- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15763
We have removed `config_sat.j2` from our internal repository. The promtail configuration that made promtail watch for changes in Satellite-related log files was merged to a general config file, therefore we do not need to specify the file anymore.
Remove the `promtail_config_template_file` broker argument, use the default (the only one we now have) promtail configuration file.
* satlab-tower!1090 (merged)
> [6.13.z] Remove promtail configuration option

- tests/upgrades/test_capsule.py
PX recommends to consider adding check for refreshing capsule feature to make sure we have same features enabled before and after upgrade. 
New upgrade-scenarios test
> Upgrade Capsule features test

- tests/upgrades/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15726
PX recommends to consider adding check for refreshing capsule feature to make sure we have same features enabled before and after upgrade. 
New upgrade-scenarios test
> [6.13.z] Upgrade Capsule features test

- tests/upgrades/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15726
PX recommends to consider adding check for refreshing capsule feature to make sure we have same features enabled before and after upgrade. 
New upgrade-scenarios test
> [6.15.z] Upgrade Capsule features test

- tests/upgrades/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15726
PX recommends to consider adding check for refreshing capsule feature to make sure we have same features enabled before and after upgrade. 
New upgrade-scenarios test
> [6.14.z] Upgrade Capsule features test

- pytest_fixtures/core/xdist.py
- tests/foreman/cli/test_discoveredhost.py
As we now have the latest version, 8.10, the test included an older version, which caused the issue.
I have updated the version, and it is now working as expected.
> Updating the FDI image to correct discovery issue.

- tests/foreman/cli/test_errata.py
- tests/foreman/ui/test_errata.py
_SAT-25213_: has been resolved, automation (1 LegacyUI test) is failing now that it is no longer skipped
- The host setup had a small logic issue (sca manifest org), and was not being updated to use the `new_lce`, 
so prior env was incorrectly found to be `Library` instead of `module_lce.name`
- Also includes small docstring clarifications, for fixture `registered_contenthost`
- Fixed one `cli/errata` test name from eval, "_registerd_" to "_registered_"
```
pytest: tests/foreman/ui/test_errata.py::test_positive_content_host_previous_env
```
> Errata::UI test_positive_content_host_previous_env

- tests/foreman/cli/test_errata.py
- tests/foreman/ui/test_errata.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15548
_SAT-25213_: has been resolved, automation (1 LegacyUI test) is failing now that it is no longer skipped
- The host setup had a small logic issue (sca manifest org), and was not being updated to use the `new_lce`, 
so prior env was incorrectly found to be `Library` instead of `module_lce.name`
- Also includes small docstring clarifications, for fixture `registered_contenthost`
- Fixed one `cli/errata` test name from eval, "_registerd_" to "_registered_"
```
pytest: tests/foreman/ui/test_errata.py::test_positive_content_host_previous_env
```
> [6.15.z] Errata::UI test_positive_content_host_previous_env

- tests/foreman/cli/test_remoteexecution.py
...in addition to existing markers in rex cli module
> pit marker for rex

- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_repository.py
We are testing `docker/podman search` against capsule already but we just check the status, not what is actually returned in stdout. And of course an issue appeared where the search returns nothing but 0 result code. (see bellow)
Check if the image is returned by the search.
Also check if `docker/podman pull` actually pulled the image.
https://issues.redhat.com/browse/SAT-25813
pytest: tests/foreman/api/test_capsulecontent.py -k sync_container_repo_end_to_end
> Harden docker/podman asserts a bit

- tests/foreman/api/test_activationkey.py
- tests/foreman/cli/test_activationkey.py
- tests/foreman/ui/test_activationkey.py
SCA is now the default in 6.16. This PR is for updating all tests under the Activation Key Component
SAT-24352
> [RFE] [ActivationKeys] Update tests to be SCA-compliant 

- tests/foreman/api/test_operatingsystem.py
- tests/foreman/api/test_provisioning.py
- tests/foreman/cli/test_operatingsystem.py
In upstream, we've recently changed the default password hashing algorithm from sha256 to sha512
https://github.com/theforeman/foreman/pull/10206
Updating the OS tests so that the default password hashing is tested, and updating the provisioning test to ensure the password hashing is verified on provisioned hosts
> Update OS tests for password hashing default from sha256 to sha512

- tests/foreman/api/test_provisioningtemplate.py
As part of fix in network configuration SAT-23034, ifcfg created during provisioning of host has been removed and keyfile created by anaconda will be the only path for configuring network.
Updated tests of provisioning to remove ifcfg and update it with keyfile created by anaconda.
> Update tests for change in network configuration

- tests/foreman/api/test_registration.py
- tests/foreman/ui/test_registration.py
Few tests failing in registration 
Fixed the tests
> Fix failing registration tests

- tests/foreman/api/test_registration.py
- tests/foreman/ui/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15778
Few tests failing in registration 
Fixed the tests
> [6.15.z] Fix failing registration tests

- robottelo/constants/__init__.py
- tests/foreman/destructive/test_capsulecontent.py
Update to rhel9 repos/content
Resolve intermittent failures for destructive tests (Stream and 6.15.z):
- test_positive_sync_without_deadlock
- test_positive_sync_without_deadlock_after_rpm_trim_changelog
There are in-progress tasks for some components, lots of actions are performed too early inside an SCA org
```
pytest: tests/foreman/destructive/test_capsulecontent.py
```
> CapsuleContent [CompEval] Destructive tests SCA fixes

- tests/foreman/cli/test_capsulecontent.py
Cover customer scenario in CapsuleContent:
- Add repo w/ synced content to CV in Library, export-complete Library content,
- import the exported Library content, promote/add to Capsule's LCE, sync the Capsule
BZ: 2043726, 2059385
> CapsuleContent [CompEval] - Cx Case

- tests/foreman/api/test_convert2rhel.py
This is part of convert2Rhel improvement : SAT-25720
Automated SAT-24655 as part of SAT-25720
> Verify CONVERT2RHEL_THROUGH_FOREMAN is set to 1 in convert2rhel facts

- tests/foreman/destructive/test_capsulecontent.py
Quick follow up to PR #15619 
- Requested by QE to use a larger repository, or multiple, for `test_positive_sync_without_deadlock`
- The current repository, `rhel9_bos`, has about 7000 rpms&erratas, we need over 10,000 to test deadlock.
- Replaced with `rhel9_aps` (21,000+ rpms&errata)
```
pytest: tests/foreman/destructive/test_capsulecontent.py::test_positive_sync_without_deadlock
```
> [CompEval] Quick change: CapsuleContent _deadlock (larger RH Repo)

- tests/foreman/cli/test_remoteexecution.py
timeout to kill setting should cancel the rex job if it takes too long
adding test
> test timeout_to_kill

- tests/foreman/cli/test_host.py
these tests no longer apply to 6.16 environment
> removing attach and auto-attach related items from cli hosts

- robottelo/cli/hammer.py
- tests/foreman/cli/test_ldapauthsource.py
- tests/foreman/destructive/test_auth.py
Previously, CLI commands run with `hammer --output csv [COMMAND]` would in some cases return non-CSV output. Over time, robottelo's `parse_csv` method has developed several workarounds to handle these bugs.
-  Remove outdated workarounds from `parse_csv`.
-  Replace the workaround for [Hammer "job-invocation create" does not produce clean CSV/JSON format if requested](https://projects.theforeman.org/issues/37264) with a regular expression substitution.
- Add warning-level logging if the above workaround was used.
- Add error-level logging if parsing of the CSV output fails.
SAT-26483
> [6.14.z] CSV formatting fixes

- pytest_fixtures/component/satellite_auth.py
- robottelo/cli/hammer.py
- tests/foreman/cli/test_ldapauthsource.py
- tests/foreman/destructive/test_auth.py
Previously, CLI commands run with `hammer --output csv [COMMAND]` would in some cases return non-CSV output. Over time, robottelo's `parse_csv` method has developed several workarounds to handle these bugs.
-  Remove outdated workarounds from `parse_csv`.
-  Replace the workaround for [Hammer "job-invocation create" does not produce clean CSV/JSON format if requested](https://projects.theforeman.org/issues/37264) with a regular expression substitution.
- Add warning-level logging if the above workaround was used.
- Add error-level logging if parsing of the CSV output fails.
SAT-26483
> [6.15.z] CSV formatting fixes

- pytest_fixtures/component/provision_vmware.py
- tests/foreman/cli/test_computeresource_vmware.py
Component Audit: Adding a test for VMware image based provisioning
Dependent Nailgun PR: https://github.com/SatelliteQE/nailgun/pull/1204
> Add test for VMware image based provisioning

- conftest.py
- pytest_fixtures/component/leapp_client.py
- tests/foreman/ui/test_leapp_client.py
> Add automation for BZ 2168494

- .gitignore
Manifester's inventory file shows up in the "Untracked files"  list. This file should never be put in SCM.
put the manifester inventory file path in the `.gitignore` file.
> Add manifester_inventory to ignored files

- tests/upgrades/test_capsule.py
In #15726 I provided results of testing however I forgot to push very last change from local to my origin/PR resulting in failed test:
```
AttributeError: 'DecClass' object has no attribute 'refresh'
```
Push missing change for #15726
> Fix PR #15726 for missing unpushed changes

- .gitignore
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15842
Manifester's inventory file shows up in the "Untracked files"  list. This file should never be put in SCM.
put the manifester inventory file path in the `.gitignore` file.
> [6.15.z] Add manifester_inventory to ignored files

- tests/foreman/api/test_repository.py
- tests/foreman/cli/test_repository.py
Component audit - SAT-25972
Fix test case- yum and docker repositories support download policy, api and cli tests need to be updated
Updated test name: `test_negative_create_repos_with_download_policy`
NA
```
pytest: tests/foreman/api/test_repository.py -k 'test_negative_create_repos_with_download_policy'
```
```
pytest: tests/foreman/cli/test_repository.py -k 'test_negative_create_repos_with_download_policy'
```
> CE-yum and docker repos support download policy

- tests/foreman/api/test_remoteexecution.py
Upgrade check `non-rh-packages` fails when promtail is installed
adding a whitelist option to make the upgrade playbook run pass
> capsule upgrade playbook test adjustments

- tests/foreman/api/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15862
Upgrade check `non-rh-packages` fails when promtail is installed
adding a whitelist option to make the upgrade playbook run pass
> [6.15.z] capsule upgrade playbook test adjustments

- tests/foreman/api/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15862
Upgrade check `non-rh-packages` fails when promtail is installed
adding a whitelist option to make the upgrade playbook run pass
> [6.13.z] capsule upgrade playbook test adjustments

- tests/upgrades/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15846
In #15726 I provided results of testing however I forgot to push very last change from local to my origin/PR resulting in failed test:
```
AttributeError: 'DecClass' object has no attribute 'refresh'
```
Push missing change for #15726
> [6.15.z] Fix PR #15726 for missing unpushed changes

- tests/upgrades/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15846
In #15726 I provided results of testing however I forgot to push very last change from local to my origin/PR resulting in failed test:
```
AttributeError: 'DecClass' object has no attribute 'refresh'
```
Push missing change for #15726
> [6.14.z] Fix PR #15726 for missing unpushed changes

- tests/upgrades/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15846
In #15726 I provided results of testing however I forgot to push very last change from local to my origin/PR resulting in failed test:
```
AttributeError: 'DecClass' object has no attribute 'refresh'
```
Push missing change for #15726
> [6.13.z] Fix PR #15726 for missing unpushed changes

- .gitignore
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15842
Manifester's inventory file shows up in the "Untracked files"  list. This file should never be put in SCM.
put the manifester inventory file path in the `.gitignore` file.
> [6.14.z] Add manifester_inventory to ignored files

- .gitignore
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15842
Manifester's inventory file shows up in the "Untracked files"  list. This file should never be put in SCM.
put the manifester inventory file path in the `.gitignore` file.
> [6.13.z] Add manifester_inventory to ignored files

- pytest_plugins/metadata_markers.py
The Satellite Network Type Attribute in results json is needed for test results filtering.
The attribute is added to results and the value is based on `is_ipv6` configuration.
**Ipv4 Value:**
```
<property name="SatelliteNetworkType" value="ipv4" />
```
**Ipv6 Value:**
```
<property name="SatelliteNetworkType" value="ipv6" />
```
> Add Satellite Network Type Attribute to Results

- pytest_plugins/metadata_markers.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15824
The Satellite Network Type Attribute in results json is needed for test results filtering.
The attribute is added to results and the value is based on `is_ipv6` configuration.
**Ipv4 Value:**
```
<property name="SatelliteNetworkType" value="ipv4" />
```
**Ipv6 Value:**
```
<property name="SatelliteNetworkType" value="ipv6" />
```
> [6.15.z] Add Satellite Network Type Attribute to Results

- pytest_fixtures/component/rh_cloud.py
- robottelo/hosts.py
- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_http_proxy.py
- tests/foreman/destructive/test_capsule_loadbalancer.py
- tests/foreman/endtoend/test_api_endtoend.py
- tests/foreman/endtoend/test_cli_endtoend.py
- tests/foreman/installer/test_installer.py
- tests/upgrades/test_errata.py
- tests/upgrades/test_hostcontent.py
- tests/upgrades/test_repository.py
- tests/upgrades/test_subscription.py
We will be removing the katello-ca-consumer RPM by default. Our automation should only use global registration anyway.
Swap uses of `install_katello_ca` and `register_contenthost` to the `register` method which uses global registration. Use default location and a basic activation key where needed.
pytest: tests/foreman/cli/test_host.py::test_positive_install_package_via_rex tests/foreman/cli/test_http_proxy.py::test_insights_client_registration_with_http_proxy tests/foreman/ui/test_subscription.py::test_positive_view_vdc_subscription_products tests/foreman/destructive/test_host.py::TestHostCockpit::test_positive_cockpit tests/foreman/cli/test_contentview.py::TestContentView::test_positive_sub_host_with_restricted_user_perm_at_custom_loc …
> Remove use of install_katello_ca with register_contenthost

- robottelo/host_helpers/contenthost_mixins.py
- tests/foreman/cli/test_fact.py
Missing end-to-end scenario for facts
Existing implementation of get_facts() method splits the string on colon. With RHEL9, we have fact values which contains colon like 'lscpu.vulnerability_spec_rstack_overflow: Vulnerable: Safe RET, no microcode'. This raises Value error ``ValueError: too many values to unpack (expected 2)`.
Added e2e for facts 
Updated the code to split the string on the first colon and treat the first half as key and rest of it as value.
> Add end-to-end test for facts

- robottelo/host_helpers/contenthost_mixins.py
- tests/foreman/cli/test_fact.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15818
Missing end-to-end scenario for facts
Existing implementation of get_facts() method splits the string on colon. With RHEL9, we have fact values which contains colon like 'lscpu.vulnerability_spec_rstack_overflow: Vulnerable: Safe RET, no microcode'. This raises Value error ``ValueError: too many values to unpack (expected 2)`.
Added e2e for facts 
Updated the code to split the string on the first colon and treat the first half as key and rest of it as value.
> [6.14.z] Add end-to-end test for facts

- robottelo/host_helpers/contenthost_mixins.py
- tests/foreman/cli/test_fact.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15818
Missing end-to-end scenario for facts
Existing implementation of get_facts() method splits the string on colon. With RHEL9, we have fact values which contains colon like 'lscpu.vulnerability_spec_rstack_overflow: Vulnerable: Safe RET, no microcode'. This raises Value error ``ValueError: too many values to unpack (expected 2)`.
Added e2e for facts 
Updated the code to split the string on the first colon and treat the first half as key and rest of it as value.
> [6.15.z] Add end-to-end test for facts

- .gitignore
`full_upgrade` and `upgrade_highlights` are traces of satellite6-upgrade.
remove them from .gitignore
They should have been removed from .gitignore in #11331.
> Remove satellite6-upgrade traces from .gitignore

- .gitignore
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15891
`full_upgrade` and `upgrade_highlights` are traces of satellite6-upgrade.
remove them from .gitignore
They should have been removed from .gitignore in #11331.
> [6.15.z] Remove satellite6-upgrade traces from .gitignore

- .gitignore
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15891
`full_upgrade` and `upgrade_highlights` are traces of satellite6-upgrade.
remove them from .gitignore
They should have been removed from .gitignore in #11331.
> [6.14.z] Remove satellite6-upgrade traces from .gitignore

- .gitignore
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15891
`full_upgrade` and `upgrade_highlights` are traces of satellite6-upgrade.
remove them from .gitignore
They should have been removed from .gitignore in #11331.
> [6.13.z] Remove satellite6-upgrade traces from .gitignore

- requirements.txt
This mostly fixes an issue with the way the docker bind is handled, but also includes a nice cli fix.
```
```
> Bump broker to 0.5.3

- tests/foreman/cli/test_computeresource_rhev.py
It was unable to fetch the name because the output was coming in dictionary format due to changes in the info() method. Please refer to the PR - https://github.com/SatelliteQE/robottelo/pull/15599
Small changes have been made here to fetch the name from the dictionary during the assertion.
> fix in computeresource_rhev

- requirements.txt
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15896
This mostly fixes an issue with the way the docker bind is handled, but also includes a nice cli fix.
```
```
> [6.15.z] Bump broker to 0.5.3

- requirements.txt
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15896
This mostly fixes an issue with the way the docker bind is handled, but also includes a nice cli fix.
```
```
> [6.13.z] Bump broker to 0.5.3

- requirements.txt
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15896
This mostly fixes an issue with the way the docker bind is handled, but also includes a nice cli fix.
```
```
> [6.14.z] Bump broker to 0.5.3

- .github/workflows/dependency_merge.yml
Depedanbot auto-merge GHA is not raising the PRT comment in case of dependency has extras  e.g.  broker[docker,hussh,podman]
Adding eval is solving this issue and tested locally 
```bash
> ls
CODEOWNERS               PULL_REQUEST_TEMPLATE.md auto_assign.yml          dependabot.yml           dependency_tests.yaml    workflows
> yq eval '.["pyotp"]' dependency_tests.yaml
tests/foreman/ui/test_ldap_authentication.py -k 'test_positive_login_user_password_otp'
> yq eval '.["broker[docker,podman,hussh]"]' dependency_tests.yaml
> yq eval '.["dynaconf[vault]"]' dependency_tests.yaml
tests/foreman/api/test_ldapauthsource.py -k 'test_positive_endtoend'```
> updated the gha to handle extras e.g. broker[docker,hussh,podman]

- tests/foreman/ui/test_registration.py
Existing test installs vim and mlocate during host registration, when we run this test in interop pipeline, we enable only baseos and it provides vim-minimal but not vim. 
To avoid this issue, we are using zsh in place of vim which is provided by baseos.
> Update package install in registration test

- tests/foreman/ui/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15886
Existing test installs vim and mlocate during host registration, when we run this test in interop pipeline, we enable only baseos and it provides vim-minimal but not vim. 
To avoid this issue, we are using zsh in place of vim which is provided by baseos.
> [6.15.z] Update package install in registration test

- robottelo/utils/datafactory.py
- tests/foreman/api/test_product.py
- tests/foreman/api/test_repository.py
1. Component audit - SAT-25973 Merge all possible product related scenarios into on test case
Initially targeted 3 test cases (`test_positive_create_with_name`, `test_positive_create_with_label`, `test_positive_create_with_description`)
Other tests can be merge along with above
`test_positive_update_description`
`test_positive_update_name_to_original`
`test_positive_delete`
`test_positive_update_organization` need to remove as it has skipped during execution due to BZ-1310422 (Current status CLOSE WONTFIX)
2. Component audit - SAT-25974 Merge 2 negative scenarios into on test function
`test_negative_create_url`
`test_negative_create_with_url_with_special_characters`
1. commit 1st - New test case name `test_positive_product_end_to_end`
2. commit 2nd - New test case name …
> Comp Eval-Combine all possible scenarios from api product and api repository

- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_computeresource_vmware.py
- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/cli/test_discoveredhost.py
- tests/foreman/cli/test_errata.py
- tests/foreman/cli/test_oscap.py
- tests/foreman/cli/test_registration.py
- tests/foreman/cli/test_remoteexecution.py
- tests/foreman/cli/test_report.py
- tests/foreman/destructive/test_clone.py
- tests/foreman/destructive/test_fm_upgrade.py
- tests/foreman/longrun/test_oscap.py
- tests/foreman/ui/test_computeresource_vmware.py
- tests/foreman/ui/test_discoveredhost.py
- tests/foreman/ui/test_errata.py
- tests/foreman/ui/test_location.py
- tests/foreman/ui/test_organization.py
- tests/foreman/ui/test_subscription.py
The customer scenario check is based on the Bugzilla today, but since bug management is moved to Jira and the bugs have been closed as `CLOSED MIGRATED`, the customer scenario check is broken.
Also, the new bugs are being created on the Jira, hence it's vital to update the test docstrings to have the details from Jira instead.
- Migrate all the bugs closed as `CLOSED MIGRATED` to get their latest updates from Jira as a new destination.
Also,
The BZs which are not migrated are kept for reference 
Some of the tests have already covered the verified token and hence only the BZ reference is removed.
- Step 2 / Next PR would switch the logic of customer scenario checks from BZ to Jira.
Why are we linking to the parent Jira to the automated test even though there are clones an subtasks?
- The …
> [Task 1 - Customer Scenario Checks] Replacing Migrated BZs docstrings token to Jira based 

- tests/foreman/cli/test_oscap_tailoringfiles.py
- tests/foreman/longrun/test_oscap.py
adding pit marker for scap client test, removed marker from stubbed test (leaving the unstubbing/removal decision for component evaluation)
> pit marker for oscap

- tests/foreman/api/test_rhc.py
- tests/foreman/ui/test_repository.py
Removing extra test for docker repo. This test is not needed, and is a dupe
Foreman/ui/test_sync.py/test_positive_sync_docker_via_sync_status is the main test
> [Comp Eval] Remove extra docker test

- tests/foreman/api/test_registration.py
Adding coverage for katello-ca certificate refresh
> Add coverage for katello-ca certificate refresh

- docs/code_standards.rst
- docs/committing.rst
- requirements-optional.txt
- tests/foreman/endtoend/test_api_endtoend.py
flake8 is long gone from robottelo, see #12621. 
Let's remove its traces in the repository.
> Remove flake8

- docs/code_standards.rst
- docs/committing.rst
- requirements-optional.txt
- tests/foreman/endtoend/test_api_endtoend.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15877
flake8 is long gone from robottelo, see #12621. 
Let's remove its traces in the repository.
> [6.15.z] Remove flake8

- docs/code_standards.rst
- docs/committing.rst
- requirements-optional.txt
- tests/foreman/endtoend/test_api_endtoend.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15877
flake8 is long gone from robottelo, see #12621. 
Let's remove its traces in the repository.
> [6.14.z] Remove flake8
