SatelliteQE/robottelo

docs/code_standards.rst
docs/committing.rst
requirements-optional.txt
tests/foreman/endtoend/test_api_endtoend.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15877
flake8 is long gone from robottelo, see #12621. 
Let's remove its traces in the repository.

[6.13.z] Remove flake8

---

tests/foreman/ui/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15912
Removing extra test for docker repo. This test is not needed, and is a dupe
Foreman/ui/test_sync.py/test_positive_sync_docker_via_sync_status is the main test

[6.15.z] [Comp Eval] Remove extra docker test

---

tests/foreman/ui/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15912
Removing extra test for docker repo. This test is not needed, and is a dupe
Foreman/ui/test_sync.py/test_positive_sync_docker_via_sync_status is the main test

[6.14.z] [Comp Eval] Remove extra docker test

---

conf/repos.yaml.template
tests/foreman/cli/test_satellitesync.py

ISS export of a CV with more than 2^16 files was causing errors (see the issue below). It was fixed in product and needs coverage since it is customer facing.
This PR adds a test case to test both, export and import, of such a large repo.
https://issues.redhat.com/browse/SAT-25194
https://github.com/SatelliteQE/fedorapeople-repos/pull/15
sat-qe jenkins MR#1440 (config related)
(both dependencies need to be merged first)
pytest: tests/foreman/cli/test_satellitesync.py -k test_postive_export_import_large_cv

Add a test case for export/import large file repo

---

pytest_fixtures/core/contenthosts.py
pytest_plugins/fixture_markers.py
tests/foreman/ui/test_host.py

This Robottelo PR adds test coverage for the Manage Packages wizard. 
It is a new 6.16 feature with which users can manage packages.
`test_positive_manage_packages` is parametrized and the test cases are defined by the combination of the following parameters:
- `number_of_hosts`: 1 or 2
-  `package_management_action`: install_1_pckg, install_2_pckgs, upgrade_1_pckg, upgrade_all_pckgs, remove_1_pckg, remove_2_pckgs
- `finish_via`: rex or custom_rex
All this leads to 2 * 6 * 2 = 24 test cases in total.
Visual representation of the test matrix:
Depends on https://github.com/SatelliteQE/airgun/pull/1489
```
pytest: tests/foreman/ui/test_host.py -k 'test_positive_manage_packages'
env:
ROBOTTELO_server__version__snap: '69.0' …
```

Add test coverage for Manage packages feature

---

tests/foreman/api/test_capsulecontent.py
tests/foreman/cli/test_capsulecontent.py
tests/foreman/ui/test_capsulecontent.py

Proposing PIT markers added to these CapsuleContent tests

PIT markers for Interoperability Testing: CapsuleContent

---

tests/foreman/installer/test_installer.py

This has two problems. First of all, HDM is a new plugin that recently started shipping upstream, but don't ship downstream.
The second problem is that the diff is hard to read. On the right hand side it is `dict_keys() - set()` which results in a set. While you can compare `dict_keys` and `set`, the resulting diff isn't very useful because pytest doesn't diff the elements.
For the first problem, hdm is added to installer's `UPSTREAM_SPECIFIC_MODULES`.
The second problem is solved by converting the left hand side into a set so it's comparing two sets. Technically that's also correct because for us the order doesn't matter either; it's only about the elements.
https://github.com/theforeman/foreman-installer/commit/de26c75efc9e6a6224dc0bd8dadee762faf2f163 added HDM to the upstream …

Add hdm to installer's UPSTREAM_SPECIFIC_MODULES & fix comparison

---

tests/foreman/api/test_capsulecontent.py
tests/foreman/cli/test_capsulecontent.py
tests/foreman/ui/test_capsulecontent.py

Failed CP of #15892
Expect `API::test_positive_sync_container_repo_end_to_end` to fail, while [SAT-25813](https://issues.redhat.com/browse/SAT-25813) is still open.

[6.15.z] PIT markers for Interoperability Testing: CapsuleContent (#15892)

---

tests/foreman/installer/test_installer.py

- Verify port 8443 is disabled on default capsule installation
- Update test_capsule_installation
- SAT-24520

Verify port 8443 is disabled on default capsule installation

---

conf/ui.yaml.template

Current `ui.yaml.template` does not support minimal UI testing setup.
Updating the UI config to support minimal setup referenced in [Advanced setup - airgun development
](https://github.com/SatelliteQE/robottelo/wiki/Robottelo-Setup#ui-testing-setup)

Update ui.yaml.template to match the production config

---

tests/foreman/cli/test_webhook.py

adding pit marker for webhook test

pit marker for webhook test

---

tests/foreman/cli/test_webhook.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15940
adding pit marker for webhook test

[6.15.z] pit marker for webhook test

---

tests/foreman/cli/test_webhook.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15940
adding pit marker for webhook test

[6.14.z] pit marker for webhook test

---

tests/foreman/cli/test_webhook.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15940
adding pit marker for webhook test

[6.13.z] pit marker for webhook test

---

robottelo/constants/__init__.py
tests/foreman/sys/test_fam.py

FAM: only setup libvirt for tests that need them

---

pytest_fixtures/component/contentview.py
robottelo/host_helpers/satellite_mixins.py
robottelo/hosts.py
tests/foreman/cli/test_host.py

Test coverage for multi-CV functionality is needed
Add tests for multi-CV:
1. basic multi-CV registration (positive)
2. multi-CV assignment with sub-man environments & repo access
3. ~~multi-CV assignment via hammer (not working yet)~~ I moved this to [another PR](https://github.com/SatelliteQE/robottelo/pull/15880) so I am marking this PR as ready for review.

Add tests for multi-CV hosts

---

tests/foreman/cli/test_ansible.py
tests/foreman/ui/test_ansible.py

We've stubbed test - test_positive_install_ansible_collection_via_job_invocation, which we need to automate as part of component audit
1. Automating the stubbed test to verify install of ansible collection with user inputted collection list and collection path
2. Updating tests to use rhel_contenthost fixtures instead of rex_contenthost
3. Add upgrade marker to existing cli test to install ansible collection

Automate a stubbed test to install Ansible collection from galaxy

---

pytest_plugins/video_cleanup.py
robottelo/hosts.py

To successfully establish IPv6 SSH connections, the ipv6 parameter must be set to true for the Host class. This configuration is necessary for the SSH provider, apart from hussh module. It is partly required for direct access to the Host object using broker imports.
This PR passing the IPV6 setting as param to host object

passing ipv6 params valued for direct Host calls

---

tests/foreman/cli/test_host.py

search syntax fixes in host tests

---

tests/foreman/cli/test_host.py

Need test coverage for host multiCV assignment with Hammer.
Add tests covering [new Hammer params](https://github.com/Katello/katello/pull/11085). 
https://github.com/Katello/katello/pull/11085

Add tests for multiCV assignment with Hammer

---

tests/foreman/ui/test_ansible.py

Ansible tasks which make changes on a host are displayed as notices in the config report, and failed Ansible tasks are displayed as errors in the config report
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1501
Fixes - https://github.com/SatelliteQE/robottelo/issues/15930

[6.13.z cp] Config report following both the failed and successful job runs.

---

pytest_plugins/video_cleanup.py
robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15964
To successfully establish IPv6 SSH connections, the ipv6 parameter must be set to true for the Host class. This configuration is necessary for the SSH provider, apart from hussh module. It is partly required for direct access to the Host object using broker imports.
This PR passing the IPV6 setting as param to host object

[6.15.z] passing ipv6 params valued for direct Host calls

---

pytest_plugins/video_cleanup.py
robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15964
To successfully establish IPv6 SSH connections, the ipv6 parameter must be set to true for the Host class. This configuration is necessary for the SSH provider, apart from hussh module. It is partly required for direct access to the Host object using broker imports.
This PR passing the IPV6 setting as param to host object

[6.14.z] passing ipv6 params valued for direct Host calls

---

.github/workflows/auto_cherry_pick_merged.yaml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15535
Following are the scenarios when we were not able to rerun the Merged PRs AutoCherrypick:
- Autocherrypicking failed due to OOM/unidentified_abort during ACP GHA run
- Missed adding the version label while autocherrypicking for a specific version
- Retry of AutoCherrypicking of a big PR when failed with conflicts due to others didn't cherry-pick the changes. Now we could ask others to fix their cherrypicks and simply retry the big PRs ACP from this GHA.
- Bulk PRs cherry-pick in about to depreciate branch, but need the branch for immediate testing or for multiple reasons
- etc
- We should be able to handle all the above scenarios now with the new standalone `Retry Merged PRs AutoCherryPick`
- …

[6.14.z] Retry/Rerun PR Autocherrypick post merge

---

.github/workflows/auto_cherry_pick_merged.yaml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15535
Following are the scenarios when we were not able to rerun the Merged PRs AutoCherrypick:
- Autocherrypicking failed due to OOM/unidentified_abort during ACP GHA run
- Missed adding the version label while autocherrypicking for a specific version
- Retry of AutoCherrypicking of a big PR when failed with conflicts due to others didn't cherry-pick the changes. Now we could ask others to fix their cherrypicks and simply retry the big PRs ACP from this GHA.
- Bulk PRs cherry-pick in about to depreciate branch, but need the branch for immediate testing or for multiple reasons
- etc
- We should be able to handle all the above scenarios now with the new standalone `Retry Merged PRs AutoCherryPick`
- …

[6.13.z] Retry/Rerun PR Autocherrypick post merge

---

.github/workflows/auto_cherry_pick_merged.yaml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15535
Following are the scenarios when we were not able to rerun the Merged PRs AutoCherrypick:
- Autocherrypicking failed due to OOM/unidentified_abort during ACP GHA run
- Missed adding the version label while autocherrypicking for a specific version
- Retry of AutoCherrypicking of a big PR when failed with conflicts due to others didn't cherry-pick the changes. Now we could ask others to fix their cherrypicks and simply retry the big PRs ACP from this GHA.
- Bulk PRs cherry-pick in about to depreciate branch, but need the branch for immediate testing or for multiple reasons
- etc
- We should be able to handle all the above scenarios now with the new standalone `Retry Merged PRs AutoCherryPick`
- …

[6.15.z] Retry/Rerun PR Autocherrypick post merge

---

tests/foreman/maintain/test_backup_restore.py

- Bug#SAT-23093 caused Backup command on Capsule to not collect the certificate tar file.
- Update backup test and check for certificate tar file in Capsule backup.
- SAT-23093, SAT-27318

Check for certs tar existence in Capsule backup

---

tests/foreman/maintain/test_backup_restore.py

cherry-pick of https://github.com/SatelliteQE/robottelo/pull/15983

[6.16.z] Check for certs tar existence in Capsule backup (#15983)

---

tests/foreman/ui/test_registration.py

Activation key does not get auto-selected on org change or browser refresh
Add a workaround for SAT-27348 while selecting activation key
https://github.com/SatelliteQE/airgun/pull/1483

Select activation key explicitly because of SAT-27348

---

tests/foreman/ui/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15990
Activation key does not get auto-selected on org change or browser refresh
Add a workaround for SAT-27348 while selecting activation key
https://github.com/SatelliteQE/airgun/pull/1483

[6.16.z] Select activation key explicitly because of SAT-27348

---

.github/workflows/weekly.yml
Makefile
conf/dynaconf_hooks.py
robottelo/utils/issue_handlers/jira.py
scripts/customer_scenarios.py

```
tests/foreman/cli/test_remoteexecution.py ['test_positive_timeout_to_kill', 'SAT-25243'] …
```

Jira replacing bz for customer scenarios check

---

.github/workflows/pull_request.yml
conf/capsule.yaml.template
conf/gce.yaml.template
conf/rh_cloud.yaml.template
robottelo/config/__init__.py
settings.sample.yaml

1. Dynaconf validation fails when the `.template` configuration files are used
2. `settings.local.yaml` is not loaded by Dynaconf due to its [settings loading policy](https://www.dynaconf.com/settings_files/?h=root_path#loading-setting-files)
3. If `2.` is fixed, config sections specified in `settings.local.yaml` override the preloaded settings (the YAML files in `conf/`)
1. fix the `.template` configuration files to satisfy validation and stop ignoring validation errors in GH Actions
2. initialize the settings object with `root_path`
3. use [Dynaconf's merge functionality](https://www.dynaconf.com/merging/?h=mer#merging-existing-data-structures) to merge preloaded settings with `settings.local.yaml`
This change allows us to have all configuration files in the `conf/` directory symlinked …

Satisfy validators, enable template config validation

---

pytest_fixtures/core/contenthosts.py
pytest_plugins/fixture_markers.py
robottelo/hosts.py
robottelo/ssh.py

Currently, Content-Host-based test-cases/fixtures are not taking an input/param for network type so that the ipv6 / ipv4 satellite can connect with the ipv6 / ipv4 content host.
But, since broker and Tower support provide the param for choosing the network type, we have to alter the content host tests cases/fixtures to take the argument for the network type parameter.
As discussed in the brainstorming call on 31st July 2024, we will choose to parameterise tests to provide the network type parameter. That looks like:
`@pytest.mark.network_type(['ipv4', 'ipv6'])` that as value can also take the regex very similar as rhel_ver_list / rhel_Ver_match implementation.
1439 
Network Marker | Satellite VM/Container | Network Configuration | Tests to Run | Expected Result
-- | -- | -- | -- | --
ipv4 …

adding the support for ipv4 and ipv6 parameterization for Container and VM

---

robottelo/host_helpers/contenthost_mixins.py
tests/foreman/cli/test_fact.py
tests/foreman/ui/test_fact.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14933
Missing following test scenarios for Facts:
- Update facts for client (CLI and UI)
Added test scenario for update client facts

[6.13.z] Add tests for Facts component

---

tests/foreman/ui/test_ansible.py

- The two stubbed test cases are no longer required because both scenarios have been covered in this - https://github.com/SatelliteQE/robottelo/pull/14556.
- Therefore, I'm removing these unnecessary stubbed test cases

Remove ansible role assign and remove stubbed tests

---

robottelo/constants/__init__.py
tests/foreman/sys/test_fam.py

- Fixes https://github.com/SatelliteQE/robottelo/issues/15969

[6.15.z] FAM: only setup libvirt for tests that need them (#15958)

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15996
- The two stubbed test cases are no longer required because both scenarios have been covered in this - https://github.com/SatelliteQE/robottelo/pull/14556.
- Therefore, I'm removing these unnecessary stubbed test cases

[6.16.z] Remove ansible role assign and remove stubbed tests

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15996
- The two stubbed test cases are no longer required because both scenarios have been covered in this - https://github.com/SatelliteQE/robottelo/pull/14556.
- Therefore, I'm removing these unnecessary stubbed test cases

[6.14.z] Remove ansible role assign and remove stubbed tests

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15996
- The two stubbed test cases are no longer required because both scenarios have been covered in this - https://github.com/SatelliteQE/robottelo/pull/14556.
- Therefore, I'm removing these unnecessary stubbed test cases

[6.13.z] Remove ansible role assign and remove stubbed tests

---

robottelo/constants/__init__.py
tests/foreman/sys/test_fam.py

[6.16.z] FAM: only setup libvirt for tests that need them (#15958)

---

robottelo/constants/__init__.py
tests/foreman/sys/test_fam.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15958

[6.14.z] FAM: only setup libvirt for tests that need them

---

.github/workflows/auto_cherry_pick_merged.yaml

Fixing the sha field

---

.github/workflows/auto_cherry_pick_merged.yaml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16013

[6.15.z] Fixing the sha field

---

.github/workflows/auto_cherry_pick_merged.yaml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16013

[6.14.z] Fixing the sha field

---

.github/workflows/auto_cherry_pick_merged.yaml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16013

[6.13.z] Fixing the sha field

---

.github/workflows/auto_cherry_pick_merged.yaml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16013

[6.16.z] Fixing the sha field

---

tests/foreman/api/test_registration.py
tests/foreman/ui/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15778
Few tests failing in registration 
Fixed the tests

[6.14.z] Fix failing registration tests

---

tests/foreman/cli/test_reporttemplates.py

api changes
access name property
tests/foreman/cli/test_reporttemplates.py::test_positive_generate_report_sanitized

Fix reporttemplate test

---

tests/foreman/cli/test_host.py

Test failing with TypeError: list indices must be integers or slices, not str
Apply fix form similar test (see also https://github.com/SatelliteQE/robottelo/pull/11544)
tests/foreman/cli/test_host.py::test_negative_edit_parameter_by_non_admin_user
tests/foreman/cli/test_host.py::test_positive_view_parameter_by_non_admin_user

Fix cli host tests by applying pattern from similar test

---

pytest_fixtures/core/contenthosts.py
robottelo/hosts.py

Katello-ca is going to be removed from 6.16 and we should use GR everywhere. The last place where is has been used is `module_container_contenthost`.
Update `module_container_contenthost` to use GR and remove the `install_katello_ca` for good.
https://issues.redhat.com/browse/SAT-25401
pytest: tests/foreman/cli/test_container_management.py -k pull_image

Remove install_katello_ca for good

---

pytest_fixtures/core/contenthosts.py
robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15931
Katello-ca is going to be removed from 6.16 and we should use GR everywhere. The last place where is has been used is `module_container_contenthost`.
Update `module_container_contenthost` to use GR and remove the `install_katello_ca` for good.
https://issues.redhat.com/browse/SAT-25401
pytest: tests/foreman/cli/test_container_management.py -k pull_image

[6.16.z] Remove install_katello_ca for good

---

tests/foreman/api/test_capsulecontent.py
tests/foreman/api/test_computeresource_vmware.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/cli/test_errata.py
tests/foreman/cli/test_registration.py
tests/foreman/cli/test_report.py
tests/foreman/destructive/test_clone.py
tests/foreman/destructive/test_fm_upgrade.py
tests/foreman/longrun/test_oscap.py
tests/foreman/ui/test_computeresource_vmware.py
tests/foreman/ui/test_discoveredhost.py
tests/foreman/ui/test_errata.py
tests/foreman/ui/test_location.py
tests/foreman/ui/test_organization.py

Replacing Migrated BZs docstrings token to verifies
Failed AutoCherrypick of #15812 
Manual cherry-pick of the same.
Closes #15903

[6.15.z][Task 1 - Customer Scenario Checks] Replacing Migrated BZs docstrings token to Jira based

---

robottelo/utils/issue_handlers/jira.py

- https://github.com/SatelliteQE/robottelo/pull/15878 introduced `sanitized_issue_data` that is causing BlockedBy to fail
- Fix sanitized_issue_data

Fix sanitized_issue_data helper of jira issue handler

---

tests/foreman/cli/test_discoveredhost.py
tests/foreman/cli/test_errata.py
tests/foreman/cli/test_registration.py
tests/foreman/cli/test_report.py
tests/foreman/destructive/test_clone.py
tests/foreman/longrun/test_oscap.py
tests/foreman/ui/test_computeresource_vmware.py
tests/foreman/ui/test_errata.py
tests/foreman/ui/test_location.py
tests/foreman/ui/test_organization.py

Replacing Migrated BZs docstrings token to verifies
Failed AutoCherrypick of #15812 
Manual cherry-pick of the same.
Closes #15904

[6.14.z][Task 1 - Customer Scenario Checks] Replacing Migrated BZs docstrings token to Jira based

---

tests/foreman/cli/test_discoveredhost.py
tests/foreman/cli/test_errata.py
tests/foreman/cli/test_registration.py
tests/foreman/cli/test_report.py
tests/foreman/destructive/test_clone.py
tests/foreman/longrun/test_oscap.py
tests/foreman/ui/test_errata.py
tests/foreman/ui/test_location.py
tests/foreman/ui/test_organization.py

Replacing Migrated BZs docstrings token to verifies
Failed AutoCherrypick of #15812 
Manual cherry-pick of the same.
Closes #15905

[6.13.z][Task 1 - Customer Scenario Checks] Replacing Migrated BZs docstrings token to Jira based

---

.github/workflows/pull_request.yml
conf/capsule.yaml.template
conf/gce.yaml.template
conf/rh_cloud.yaml.template
robottelo/config/__init__.py
settings.sample.yaml

Backport of #15932.
* Satisfy validators, enable template config validation
Plus make the local settings file work by adding dynaconf_merge and root_path
* Update conf/rh_cloud.yaml.template
---------
(cherry picked from commit 81071b3a049ee5b0337524142c67ba0b5632dd13)

[6.16.z] Satisfy validators, enable template config validation (#15932)

---

.github/workflows/pull_request.yml
conf/capsule.yaml.template
conf/gce.yaml.template
conf/rh_cloud.yaml.template
robottelo/config/__init__.py
settings.sample.yaml

Backport of #15932.
* Satisfy validators, enable template config validation
Plus make the local settings file work by adding dynaconf_merge and root_path
* Update conf/rh_cloud.yaml.template
---------
(cherry picked from commit 81071b3a049ee5b0337524142c67ba0b5632dd13)

[6.15.z] Satisfy validators, enable template config validation (#15932)

---

.github/workflows/pull_request.yml
conf/capsule.yaml.template
conf/gce.yaml.template
conf/rh_cloud.yaml.template
robottelo/config/__init__.py
settings.sample.yaml

Backport of #15932.
* Satisfy validators, enable template config validation
Plus make the local settings file work by adding dynaconf_merge and root_path
* Update conf/rh_cloud.yaml.template
---------
(cherry picked from commit 81071b3a049ee5b0337524142c67ba0b5632dd13)

[6.14.z] Satisfy validators, enable template config validation (#15932)

---

.github/workflows/pull_request.yml
conf/capsule.yaml.template
conf/gce.yaml.template
conf/rh_cloud.yaml.template
robottelo/config/__init__.py
settings.sample.yaml

Backport of #15932.
* Satisfy validators, enable template config validation
Plus make the local settings file work by adding dynaconf_merge and root_path
* Update conf/rh_cloud.yaml.template
---------
(cherry picked from commit 81071b3a049ee5b0337524142c67ba0b5632dd13)

[6.13.z] Satisfy validators, enable template config validation (#15932)

---

tests/foreman/api/test_repository_set.py

Comp Eval-SAT-25977 Merge api reposet scenarios 
`test_positive_reposet_disable`
`test_positive_reposet_enable`
New test case - `test_positive_reposet_enable_and_disable`
N/A
pytest: tests/foreman/api/test_repository_set.py -k 'test_positive_reposet_enable_and_disable'

merge reposet scenarios

---

.github/workflows/weekly.yml
Makefile
conf/dynaconf_hooks.py
robottelo/utils/issue_handlers/jira.py
scripts/customer_scenarios.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15878
``` …
```

[6.15.z] Jira replacing bz for customer scenarios check

---

.github/workflows/weekly.yml
Makefile
conf/dynaconf_hooks.py
robottelo/utils/issue_handlers/jira.py
scripts/customer_scenarios.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15878
``` …
```

[6.14.z] Jira replacing bz for customer scenarios check

---

.github/workflows/weekly.yml
Makefile
conf/dynaconf_hooks.py
robottelo/utils/issue_handlers/jira.py
scripts/customer_scenarios.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15878
``` …
```

[6.13.z] Jira replacing bz for customer scenarios check

---

.github/workflows/weekly.yml
Makefile
conf/dynaconf_hooks.py
robottelo/utils/issue_handlers/jira.py
scripts/customer_scenarios.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15878
``` …
```

[6.16.z] Jira replacing bz for customer scenarios check

---

tests/foreman/cli/test_repository.py

As per repos component eval we should merge repo create and delete test cases.
This PR.
https://issues.redhat.com/browse/SAT-25997
pytest: tests/foreman/cli/test_repository.py -k create_delete_with_name_label

Merge repo create and delete test cases

---

tests/foreman/api/test_repository_set.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16044
Comp Eval-SAT-25977 Merge api reposet scenarios 
`test_positive_reposet_disable`
`test_positive_reposet_enable`
New test case - `test_positive_reposet_enable_and_disable`
N/A
pytest: tests/foreman/api/test_repository_set.py -k 'test_positive_reposet_enable_and_disable'

[6.16.z] merge reposet scenarios

---

tests/foreman/cli/test_repository_set.py

As per repos component eval we should merge enable/disable repo test-cases.
This PR.
I did one step further and merged all the `test_..._by_*` cases into one parametrized test case.
https://issues.redhat.com/browse/SAT-25991
https://issues.redhat.com/browse/SAT-25992
https://issues.redhat.com/browse/SAT-25993
pytest: tests/foreman/cli/test_repository_set.py -k by_param

Merge enable/disable_by cases into one parametrized

---

tests/foreman/cli/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16072
`test_positive_synchronize_auth_yum_repo`
`test_positive_create_with_auth_yum_repo`
new test case: `test_positive_create_and_sync_with_auth_yum_repo`
https://issues.redhat.com/browse/SAT-25978
pytest: tests/foreman/cli/test_repository.py -k 'test_positive_create_and_sync_with_auth_yum_repo'

[6.16.z] merge cli scenarios - yum repo creation & sync with auth

---

tests/foreman/cli/test_ping.py

pit marker for hammer ping test

---

tests/upgrades/test_provisioningtemplate.py

The upgrade tests are failing with JSON decode error as data saved is in dictionary format instead of json format.
Updated tests to convert to json before saving pre-upgrade data

Fix tests post Upgrade Fabric Removal from Rocket Team

---

tests/upgrades/test_provisioningtemplate.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15985
The upgrade tests are failing with JSON decode error as data saved is in dictionary format instead of json format.
Updated tests to convert to json before saving pre-upgrade data

[6.16.z] Fix tests post Upgrade Fabric Removal from Rocket Team

---

tests/upgrades/test_provisioningtemplate.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15985
The upgrade tests are failing with JSON decode error as data saved is in dictionary format instead of json format.
Updated tests to convert to json before saving pre-upgrade data

[6.15.z] Fix tests post Upgrade Fabric Removal from Rocket Team

---

tests/upgrades/test_provisioningtemplate.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15985
The upgrade tests are failing with JSON decode error as data saved is in dictionary format instead of json format.
Updated tests to convert to json before saving pre-upgrade data

[6.14.z] Fix tests post Upgrade Fabric Removal from Rocket Team

---

tests/foreman/cli/test_ping.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15939

[6.15.z] pit marker for hammer ping test

---

tests/foreman/cli/test_ping.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15939

[6.14.z] pit marker for hammer ping test

---

tests/foreman/cli/test_ping.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15939

[6.13.z] pit marker for hammer ping test

---

pytest_plugins/markers.py
tests/foreman/sanity/test_bvt.py

No Compose Sanity Test with its marker

---

pytest_plugins/markers.py
tests/foreman/sanity/test_bvt.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16052

[6.14.z] No Compose Sanity Test with its marker

---

pytest_plugins/markers.py
tests/foreman/sanity/test_bvt.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16052

[6.15.z] No Compose Sanity Test with its marker

---

pytest_plugins/markers.py
tests/foreman/sanity/test_bvt.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16052

[6.13.z] No Compose Sanity Test with its marker

---

pytest_plugins/markers.py
tests/foreman/sanity/test_bvt.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16052

[6.16.z] No Compose Sanity Test with its marker

---

tests/foreman/cli/test_ldapauthsource.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16092
```
tests/foreman/cli/test_ldapauthsource.py:137: in test_positive_refresh_usergroup_with_ad
assert LOGGEDIN_MSG.format(ad_data['ldap_user_name']) in result[0]['message']
E   assert "Using configured credentials for user 'foobar'." in "Session exists, currently logged in as 'admin'."
E    +  where "Using configured credentials for user 'foobar'." = <built-in method format of str object at 0x7fa687146010>('foobar')
E    +    where <built-in method format of str object at 0x7fa687146010> = "Using configured credentials for user '{0}'.".format
```
Logout before attemting to login

[6.16.z] Logout first before attempting login

---

tests/foreman/cli/test_ldapauthsource.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16092
```
tests/foreman/cli/test_ldapauthsource.py:137: in test_positive_refresh_usergroup_with_ad
assert LOGGEDIN_MSG.format(ad_data['ldap_user_name']) in result[0]['message']
E   assert "Using configured credentials for user 'foobar'." in "Session exists, currently logged in as 'admin'."
E    +  where "Using configured credentials for user 'foobar'." = <built-in method format of str object at 0x7fa687146010>('foobar')
E    +    where <built-in method format of str object at 0x7fa687146010> = "Using configured credentials for user '{0}'.".format
```
Logout before attemting to login

[6.15.z] Logout first before attempting login

---

tests/foreman/cli/test_ping.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15939

[6.16.z] pit marker for hammer ping test

---

tests/foreman/maintain/test_backup_restore.py

Unify obtaining instance name

---

tests/foreman/ui/test_sync.py

Comp Eval - Instead of custom docker repo can we use any repo from Docker Hub or quay.io as many customers use it to sync docker repos. 
Update registry hub url, upstream username, etc
https://issues.redhat.com/browse/SAT-25986
pytest: tests/foreman/ui/test_sync.py -k 'test_positive_sync_docker_via_sync_status'

Comp Eval-update docker repo test

---

tests/foreman/ui/test_sync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16111
Comp Eval - Instead of custom docker repo can we use any repo from Docker Hub or quay.io as many customers use it to sync docker repos. 
Update registry hub url, upstream username, etc
https://issues.redhat.com/browse/SAT-25986
pytest: tests/foreman/ui/test_sync.py -k 'test_positive_sync_docker_via_sync_status'

[6.16.z] Comp Eval-update docker repo test

---

tests/foreman/ui/test_host.py

Fix the test that is deleting the host via the new All Host UI. It was failing due to a variance in the table header.
This PR fixes that by setting the table header to just `Name` and then returning it back to the state at the beginning.

Fix delete host test through new All host page

---

tests/foreman/ui/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16115
Fix the test that is deleting the host via the new All Host UI. It was failing due to a variance in the table header.
This PR fixes that by setting the table header to just `Name` and then returning it back to the state at the beginning.

[6.16.z] Fix delete host test through new All host page

---

tests/foreman/ui/test_host.py

Add Rhel 9 to the test matrix of the change content source test.

Add rhel9 to the change content source test

---

tests/foreman/maintain/test_backup_restore.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15813
Duplicate code
see PR

[6.16.z] Unify obtaining instance name

---

tests/foreman/maintain/test_backup_restore.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15813
Duplicate code
see PR

[6.15.z] Unify obtaining instance name

---

tests/foreman/maintain/test_backup_restore.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15813
Duplicate code
see PR

[6.14.z] Unify obtaining instance name

---

tests/foreman/maintain/test_backup_restore.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15813
Duplicate code
see PR

[6.13.z] Unify obtaining instance name

---

tests/foreman/ui/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16118
Add Rhel 9 to the test matrix of the change content source test.

[6.16.z] Add rhel9 to the change content source test

---

tests/foreman/ui/test_discoveryrule.py

The failure occurred because the code was deleting the discovery rule, and then attempting to read from the deleted table using the `read_all()` method. To resolve this issue, I added the `read_after_del()` method, which reads the page message after a rule is deleted or if there are no more tables.
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1480

TFA fix for discovery plugin

---

tests/foreman/api/test_computeresource_azurerm.py
tests/foreman/cli/test_computeresource_azurerm.py
tests/foreman/ui/test_computeresource_azurerm.py

update azure subnet network to default

---

tests/foreman/ui/test_discoveryrule.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15783
The failure occurred because the code was deleting the discovery rule, and then attempting to read from the deleted table using the `read_all()` method. To resolve this issue, I added the `read_after_del()` method, which reads the page message after a rule is deleted or if there are no more tables.
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1480

[6.16.z] TFA fix for discovery plugin

---

tests/foreman/api/test_computeresource_azurerm.py
tests/foreman/cli/test_computeresource_azurerm.py
tests/foreman/ui/test_computeresource_azurerm.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16023

[6.16.z] update azure subnet network to default

---

tests/foreman/api/test_computeresource_azurerm.py
tests/foreman/cli/test_computeresource_azurerm.py
tests/foreman/ui/test_computeresource_azurerm.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16023

[6.15.z] update azure subnet network to default

---

robottelo/hosts.py
tests/foreman/cli/test_ldapauthsource.py

This test fails in automation with:
```
tests/foreman/cli/test_ldapauthsource.py:246: in test_usergroup_sync_with_refresh
default_ipa_host.add_user_to_usergroup(member_username, member_group)
robottelo/hosts.py:2594: in add_user_to_usergroup
raise IPAHostError('Failed to add the user to usergroup')
E   robottelo.hosts.IPAHostError: Failed to add the user to usergroup
```
After fixing it by adding said user and group in our IPA instance, it fails on repeated runs because the user is already a member.
After fixing that by checking failure reason, it fails with an error known already from https://github.com/SatelliteQE/robottelo/pull/16092

Check ipa command failure reason, improve logging. Logout first before attempting login.

---

robottelo/hosts.py
tests/foreman/cli/test_ldapauthsource.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16109
This test fails in automation with:
```
tests/foreman/cli/test_ldapauthsource.py:246: in test_usergroup_sync_with_refresh
default_ipa_host.add_user_to_usergroup(member_username, member_group)
robottelo/hosts.py:2594: in add_user_to_usergroup
raise IPAHostError('Failed to add the user to usergroup')
E   robottelo.hosts.IPAHostError: Failed to add the user to usergroup
```
After fixing it by adding said user and group in our IPA instance, it fails on repeated runs because the user is already a member.
After fixing that by checking failure reason, it fails with an error known already from https://github.com/SatelliteQE/robottelo/pull/16092

[6.16.z] Check ipa command failure reason, improve logging. Logout first before attempting login.

---

tests/foreman/ui/test_discoveryrule.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15783
The failure occurred because the code was deleting the discovery rule, and then attempting to read from the deleted table using the `read_all()` method. To resolve this issue, I added the `read_after_del()` method, which reads the page message after a rule is deleted or if there are no more tables.
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1480

[6.15.z] TFA fix for discovery plugin

---

tests/foreman/api/test_computeresource_azurerm.py
tests/foreman/cli/test_computeresource_azurerm.py
tests/foreman/ui/test_computeresource_azurerm.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16023

[6.14.z] update azure subnet network to default

---

tests/foreman/cli/test_contentview.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16135
For RFE [SAT-20281](https://issues.redhat.com/browse/SAT-20281): _Should not be able to publish CV while syncing contained repo_ (6.16.0+)
Small failure in new CLI coverage, non-product issue.
The repo_task is now a list of tasks, with dictionary containing 'message' and 'id'. 
No need to split the id from message anymore.
```
pytest: tests/foreman/cli/test_contentview.py::TestContentView::test_negative_publish_during_repo_sync
```

[6.16.z] RFE for 6.16 Coverage, small issue with splitting repo_task for id

---

robottelo/utils/virtwho.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16106
remove host subscription and update host_status check for sca-only
Test Case : PASS
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/foreman/virtwho/ui/test_esx_sca.py -k test_positive_deploy_configure_by_id_script --disable-pytest-warnings -q
..                                                                                                                                         [100%]
2 passed, 16 deselected, 24 warnings in 906.52s (0:15:06)
```

[6.16.z] remove host subscription and update host_status check for sca-only

---

tests/foreman/cli/test_errata.py

CLI Failure for `test_positive_check_errata_dates`, the result from `CLI.Erratum.list`, we do not need to split the CLI output anymore. We now get a list of all the errata's issue/install dates.
- Note the expected keywords "issued" and "updated" are all lowercase now.
```
pytest: tests/foreman/cli/test_errata.py::test_positive_check_errata_dates
```

Fix CLI::ErrataManagement case, no longer need to split CLI results

---

tests/foreman/cli/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16136
CLI Failure for `test_positive_check_errata_dates`, the result from `CLI.Erratum.list`, we do not need to split the CLI output anymore. We now get a list of all the errata's issue/install dates.
- Note the expected keywords "issued" and "updated" are all lowercase now.
```
pytest: tests/foreman/cli/test_errata.py::test_positive_check_errata_dates
```

[6.15.z] Fix CLI::ErrataManagement case, no longer need to split CLI results

---

tests/foreman/cli/test_capsulecontent.py

Cover older BZ: 2186765, was to be combined with another (BZ: 2148813) but that is covered elsewhere.
- Enhanced the existing test some.
- At the end of `export_import` content capsule sync, we add 'Library' lce to the Capsule, 
which contains both the exported and imported CVs, which are identical. 
- We sync the capsule again to Library, to ensure the repositories/sync tasks do not collide with each other, does not occur redundantly as reported in the BZ.
```
pytest: tests/foreman/cli/test_capsulecontent.py::test_positive_exported_imported_content_sync
```

Customer Case- Cover BZ: 2186765

---

tests/foreman/cli/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16136
CLI Failure for `test_positive_check_errata_dates`, the result from `CLI.Erratum.list`, we do not need to split the CLI output anymore. We now get a list of all the errata's issue/install dates.
- Note the expected keywords "issued" and "updated" are all lowercase now.
```
pytest: tests/foreman/cli/test_errata.py::test_positive_check_errata_dates
```

[6.16.z] Fix CLI::ErrataManagement case, no longer need to split CLI results

---

tests/foreman/cli/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16074
Cover older BZ: 2186765, was to be combined with another (BZ: 2148813) but that is covered elsewhere.
- Enhanced the existing test some.
- At the end of `export_import` content capsule sync, we add 'Library' lce to the Capsule, 
which contains both the exported and imported CVs, which are identical. 
- We sync the capsule again to Library, to ensure the repositories/sync tasks do not collide with each other, does not occur redundantly as reported in the BZ.
```
pytest: tests/foreman/cli/test_capsulecontent.py::test_positive_exported_imported_content_sync
```

[6.16.z] Customer Case- Cover BZ: 2186765

---

tests/foreman/api/test_computeresource_azurerm.py
tests/foreman/cli/test_computeresource_azurerm.py
tests/foreman/ui/test_computeresource_azurerm.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16023

[6.13.z] update azure subnet network to default

---

tests/foreman/cli/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16150
Just need to pass the CVV id/label or LCE id/label for command (not required for 6.15.z and earlier).
```
robottelo.exceptions.CLIReturnCodeError: CLIReturnCodeError(status=64, stderr="Error: At least one of options 
--content-view-version-id, --content-view-version, --environment-id, --lifecycle-environment is required.\n\n
See: 'hammer erratum <list|index> --help'.\n",
```
```
pytest: tests/foreman/cli/test_errata.py::test_errata_list_by_contentview_filter
```

[6.16.z] 6.16.0 Quickfix: CV filter, Errata list cmd

---

tests/foreman/api/test_errata.py

Swid tools and dnf-plugin-swidtags rpms are both unsigned.
Causes failure on yum install of these packages.
- We can use `--nogpgcheck` flag to install the unsigned prereqs. 
- OR we can remove this test case from 6.15, `test_errata_installation_with_swidtags`, 
as it is non-critical and was already removed from 6.16+
```
pytest: tests/foreman/api/test_errata.py::test_errata_installation_with_swidtags
```

[6.15.z] Unsigned Install for swid-tools & dnf-plugin-swidtags

---

tests/foreman/cli/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16055
As per repos component eval we should merge repo create and delete test cases.
This PR.
https://issues.redhat.com/browse/SAT-25997
pytest: tests/foreman/cli/test_repository.py -k create_delete_with_name_label

[6.16.z] Merge repo create and delete test cases

---

tests/foreman/cli/test_artifacts.py

Sometimes (only in CI and only for RHEL8-based Satellite and only for file-type repo) the published repo files are not available at the `published_at` url fast enough so the test fails in `url = random.choice(sat_files_urls)` since `sat_files_urls` is empty.
This PR just adds wait until the published files are available.

Add wait_for to see published repo files

---

tests/foreman/cli/test_artifacts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16185
Sometimes (only in CI and only for RHEL8-based Satellite and only for file-type repo) the published repo files are not available at the `published_at` url fast enough so the test fails in `url = random.choice(sat_files_urls)` since `sat_files_urls` is empty.
This PR just adds wait until the published files are available.

[6.16.z] Add wait_for to see published repo files

---

tests/foreman/cli/test_remoteexecution.py

additional parametrization to cover su method for effective user selection in rex
SAT-23229
https://github.com/theforeman/smart_proxy_remote_execution_ssh/pull/116

test rex with su password

---

robottelo/hosts.py
tests/foreman/api/test_remoteexecution.py
tests/foreman/cli/test_ansible.py
tests/foreman/cli/test_registration.py
tests/foreman/cli/test_remoteexecution.py

Host registration command have new option "repo-data" which combines "repo" and "repo-gpg-key-url" option(both are deprecated now).
Updated hammer host registration method to accept new option and removed older deprecated options.
Created a test to test repo-data option

Update host registration hammer command to use repo_data option over deprecated repo and repo_gpg_key_url option and test the new option

---

robottelo/hosts.py
tests/foreman/api/test_remoteexecution.py
tests/foreman/cli/test_ansible.py
tests/foreman/cli/test_registration.py
tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16090
Host registration command have new option "repo-data" which combines "repo" and "repo-gpg-key-url" option(both are deprecated now).
Updated hammer host registration method to accept new option and removed older deprecated options.
Created a test to test repo-data option

[6.16.z] Update host registration hammer command to use repo_data option over deprecated repo and repo_gpg_key_url option and test the new option

---

robottelo/cli/contentview.py
tests/foreman/longrun/test_inc_updates.py

1. Content view version incremental update command run via robottelo, it executed successfully but doesn't return anything in stdout.
2. Content view version Incremental update took longer time than publish of entire content-view, Update took significantly more time, 20% or longer, than publish. 
```
update duration: 19.336696 s.
publish duration: 16.057788 s.
Encountering an assertion error for this  
assert ((19.336696 - 16.057788) / 16.057788) <= 0.2
0.20419425141246114 != 0.2
Expected :0.2
Actual   :0.20419425141246114
```
1. Used content view version list and check incremental version number
2. Update significance value by 0.05 (on trial and error basis)
- now comparison will happen with `0.25` instread of `0.2`
Jira - https://issues.redhat.com/browse/SAT-27517
```
trigger: …
```

cvv incremental update and cv publish duration fix

---

robottelo/cli/contentview.py
tests/foreman/longrun/test_inc_updates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16169
1. Content view version incremental update command run via robottelo, it executed successfully but doesn't return anything in stdout.
2. Content view version Incremental update took longer time than publish of entire content-view, Update took significantly more time, 20% or longer, than publish. 
```
update duration: 19.336696 s.
publish duration: 16.057788 s.
Encountering an assertion error for this  
assert ((19.336696 - 16.057788) / 16.057788) <= 0.2
0.20419425141246114 != 0.2
Expected :0.2
Actual   :0.20419425141246114
```
1. Used content view version list and check incremental version number
2. Update significance value by 0.05 (on trial and error basis)
- now comparison will happen with `0.25` instread of `0.2` …

[6.15.z] cvv incremental update and cv publish duration fix

---

conf/capsule.yaml.template
conf/robottelo.yaml.template
conf/server.yaml.template
pytest_fixtures/core/sat_cap_factory.py
robottelo/config/validators.py
robottelo/host_helpers/contenthost_mixins.py
robottelo/hosts.py
tests/foreman/installer/test_installer.py

This change improves compatibility with PIT testing.
- added RHEL_SOURCE variable to robottelo.conf to choose which repositories to use. ga - use released RHEL, internal - use custom RHEL (e.g. release candidate)
- removed 'beta' from available sources of satellite and capsule as we don't use beta releases any more
- updated validators
We can choose source repositories for RHEL and Satellite. Following combinations of sat@rhel are possible:
internal@internal - pre-release testing
ga@internal - PIT testing
internal@ga - common testing
ga@ga - invalid combination (we don't care about retesting already published products)
The same applies for Capsule. It's also possible to use different version of Capsule and Satellite (e.g. n-1 testing)
- reworked satellite installation - use RHEL and …

improve installer tests compatibility with pit

---

pytest_fixtures/core/contenthosts.py
pytest_plugins/fixture_markers.py
robottelo/hosts.py
robottelo/ssh.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15881
Currently, Content-Host-based test-cases/fixtures are not taking an input/param for network type so that the ipv6 / ipv4 satellite can connect with the ipv6 / ipv4 content host.
But, since broker and Tower support provide the param for choosing the network type, we have to alter the content host tests cases/fixtures to take the argument for the network type parameter.
As discussed in the brainstorming call on 31st July 2024, we will choose to parameterise tests to provide the network type parameter. That looks like:
`@pytest.mark.network_type(['ipv4', 'ipv6'])` that as value can also take the regex very similar as rhel_ver_list / rhel_Ver_match implementation.
1439 
Network Marker | Satellite VM/Container | Network …

[6.16.z] adding the support for ipv4 and ipv6 parameterization for Container and VM

---

tests/foreman/maintain/test_health.py

test_positive_health_check_by_tags is failing as the code to get the tag names is broken.
- Update the code logic
- SAT-27378

Fix test_positive_health_check_by_tags

---

tests/foreman/maintain/test_health.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16022
test_positive_health_check_by_tags is failing as the code to get the tag names is broken.
- Update the code logic
- SAT-27378

[6.16.z] Fix test_positive_health_check_by_tags

---

conf/capsule.yaml.template
conf/robottelo.yaml.template
conf/server.yaml.template
pytest_fixtures/core/sat_cap_factory.py
robottelo/config/validators.py
robottelo/host_helpers/contenthost_mixins.py
robottelo/hosts.py
tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15308
This change improves compatibility with PIT testing.
- added RHEL_SOURCE variable to robottelo.conf to choose which repositories to use. ga - use released RHEL, internal - use custom RHEL (e.g. release candidate)
- removed 'beta' from available sources of satellite and capsule as we don't use beta releases any more
- updated validators
We can choose source repositories for RHEL and Satellite. Following combinations of sat@rhel are possible:
internal@internal - pre-release testing
ga@internal - PIT testing
internal@ga - common testing
ga@ga - invalid combination (we don't care about retesting already published products)
The same applies for Capsule. It's also possible to use different version of Capsule and Satellite …

[6.16.z] improve installer tests compatibility with pit

---

robottelo/hosts.py

https://github.com/SatelliteQE/robottelo/pull/15931 broke teardown of tests which use contenthosts registered through a Capsule because the registration target (where the host is registered to, Capsule in this case) was assigned to the host's `self.satellite` [here](https://github.com/SatelliteQE/robottelo/blob/8dfeed3304a5f6cd3183654855ab19a326d231ec/robottelo/hosts.py#L694), and in teardown we try to search and delete the host [here](https://github.com/SatelliteQE/robottelo/blob/fee2d1413959dd9b71f24eeabb7641dc51424126/robottelo/hosts.py#L178), which fails since Capsule has no API
```
"error during teardown:\n'Capsule' object has no attribute 'api'"
```
As per @ogajduse++ proposal, provide the Satellite instance in host's `self.satellite` instead of the registration target (Capsule) so …

Fix for teardown failures

---

robottelo/hosts.py
tests/foreman/cli/test_ldapauthsource.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16109
This test fails in automation with:
```
tests/foreman/cli/test_ldapauthsource.py:246: in test_usergroup_sync_with_refresh
default_ipa_host.add_user_to_usergroup(member_username, member_group)
robottelo/hosts.py:2594: in add_user_to_usergroup
raise IPAHostError('Failed to add the user to usergroup')
E   robottelo.hosts.IPAHostError: Failed to add the user to usergroup
```
After fixing it by adding said user and group in our IPA instance, it fails on repeated runs because the user is already a member.
After fixing that by checking failure reason, it fails with an error known already from https://github.com/SatelliteQE/robottelo/pull/16092

[6.15.z] Check ipa command failure reason, improve logging. Logout first before attempting login.

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16211
https://github.com/SatelliteQE/robottelo/pull/15931 broke teardown of tests which use contenthosts registered through a Capsule because the registration target (where the host is registered to, Capsule in this case) was assigned to the host's `self.satellite` [here](https://github.com/SatelliteQE/robottelo/blob/8dfeed3304a5f6cd3183654855ab19a326d231ec/robottelo/hosts.py#L694), and in teardown we try to search and delete the host [here](https://github.com/SatelliteQE/robottelo/blob/fee2d1413959dd9b71f24eeabb7641dc51424126/robottelo/hosts.py#L178), which fails since Capsule has no API
```
"error during teardown:\n'Capsule' object has no attribute 'api'"
```
As per @ogajduse++ proposal, provide the Satellite instance in …

[6.16.z] Fix for teardown failures

---

tests/foreman/cli/test_host.py

Well, I forgot to add 6.16 tag to https://github.com/SatelliteQE/robottelo/pull/15949 as it was open while we brached

[6.16] search syntax fixes in host tests

---

pytest_fixtures/core/contenthosts.py

Host registration command have new option "repo-data" which combines "repo" and "repo-gpg-key-url" option(both are deprecated now).
Follow-up on https://github.com/SatelliteQE/robottelo/pull/16090 
Updated hammer host registration method to accept new option and removed older deprecated options.
Created a test to test repo-data option

Update occurences of repo option in register to use repo_data

---

pytest_fixtures/core/contenthosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16215
Host registration command have new option "repo-data" which combines "repo" and "repo-gpg-key-url" option(both are deprecated now).
Follow-up on https://github.com/SatelliteQE/robottelo/pull/16090 
Updated hammer host registration method to accept new option and removed older deprecated options.
Created a test to test repo-data option

[6.16.z] Update occurences of repo option in register to use repo_data

---

tests/foreman/cli/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15984
Test failing with TypeError: list indices must be integers or slices, not str
Apply fix form similar test (see also https://github.com/SatelliteQE/robottelo/pull/11544)
tests/foreman/cli/test_host.py::test_negative_edit_parameter_by_non_admin_user
tests/foreman/cli/test_host.py::test_positive_view_parameter_by_non_admin_user

[6.16.z] Fix cli host tests by applying pattern from similar test

---

robottelo/constants/__init__.py

`SATELLITE_VERSION` and `SAT_NON_GA_VERSIONS` constants are wrongly set as 6.16 is not GA yet. This is causing `test_positive_capsule_repositories_setup` and `test_positive_satellite_repositories_setup` to fail and probably some other tests too.
Fix `SATELLITE_VERSION` and `SAT_NON_GA_VERSIONS` in constants
- SAT-27753

Fix SATELLITE_VERSION and SAT_NON_GA_VERSIONS in constants

---

.github/workflows/pull_request.yml
.github/workflows/weekly.yml
Dockerfile
scripts/config_helpers.py
scripts/customer_scenarios.py
scripts/fixture_cli.py
scripts/tokenize_customer_scenario.py
scripts/validate_config.py

Start using uv

---

.github/workflows/pull_request.yml
.github/workflows/weekly.yml
Dockerfile
scripts/config_helpers.py
scripts/customer_scenarios.py
scripts/fixture_cli.py
scripts/tokenize_customer_scenario.py
scripts/validate_config.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16203

[6.13.z] Start using uv

---

.github/workflows/pull_request.yml
.github/workflows/weekly.yml
Dockerfile
scripts/config_helpers.py
scripts/customer_scenarios.py
scripts/fixture_cli.py
scripts/tokenize_customer_scenario.py
scripts/validate_config.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16203

[6.14.z] Start using uv

---

.github/workflows/pull_request.yml
.github/workflows/weekly.yml
Dockerfile
scripts/config_helpers.py
scripts/customer_scenarios.py
scripts/fixture_cli.py
scripts/tokenize_customer_scenario.py
scripts/validate_config.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16203

[6.15.z] Start using uv

---

.github/workflows/pull_request.yml
.github/workflows/weekly.yml
Dockerfile
scripts/config_helpers.py
scripts/customer_scenarios.py
scripts/fixture_cli.py
scripts/tokenize_customer_scenario.py
scripts/validate_config.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16203

[6.16.z] Start using uv

---

robottelo/cli/contentview.py
tests/foreman/longrun/test_inc_updates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16169
1. Content view version incremental update command run via robottelo, it executed successfully but doesn't return anything in stdout.
2. Content view version Incremental update took longer time than publish of entire content-view, Update took significantly more time, 20% or longer, than publish. 
```
update duration: 19.336696 s.
publish duration: 16.057788 s.
Encountering an assertion error for this  
assert ((19.336696 - 16.057788) / 16.057788) <= 0.2
0.20419425141246114 != 0.2
Expected :0.2
Actual   :0.20419425141246114
```
1. Used content view version list and check incremental version number
2. Update significance value by 0.05 (on trial and error basis)
- now comparison will happen with `0.25` instread of `0.2` …

[6.16.z] cvv incremental update and cv publish duration fix

---

tests/foreman/cli/test_contentview.py

if a key's value is zero the key is not displayed anymore but removed.
adapt assertion to check absence of key
tests/foreman/cli/test_contentview.py::TestContentView::test_positive_remove_repository_by_id
tests/foreman/cli/test_contentview.py::TestContentView::test_positive_remove_repository_by_name
tests/foreman/cli/test_contentview.py::TestContentView::test_positive_republish_after_content_removed
tests/foreman/cli/test_contentview.py::TestContentView::test_positive_remove_lce_by_id_and_reassign_ak
tests/foreman/cli/test_contentview.py::TestContentView::test_positive_remove_component_by_name
tests/foreman/cli/test_contentview.py::TestContentView::test_positive_create_composite_with_component_ids

Fix cli contenthost tests

---

tests/foreman/cli/test_contentview.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15991
if a key's value is zero the key is not displayed anymore but removed.
adapt assertion to check absence of key
tests/foreman/cli/test_contentview.py::TestContentView::test_positive_remove_repository_by_id
tests/foreman/cli/test_contentview.py::TestContentView::test_positive_remove_repository_by_name
tests/foreman/cli/test_contentview.py::TestContentView::test_positive_republish_after_content_removed
tests/foreman/cli/test_contentview.py::TestContentView::test_positive_remove_lce_by_id_and_reassign_ak
tests/foreman/cli/test_contentview.py::TestContentView::test_positive_remove_component_by_name
tests/foreman/cli/test_contentview.py::TestContentView::test_positive_create_composite_with_component_ids

[6.16.z] Fix cli contenthost tests

---

tests/foreman/cli/test_subscription.py

Did not delete `expired manifest` from the organization after it's use in test `test_negative_check_katello_reimport`, when test unable to execute succesfully it then it was creating problem with other test defined in UI > test_subscription.py
Both test uses same xdist worker to run.
With the help of finalizer, delete manifest and organization from test case after it's use, it will depends on test execution result.
N/A
pytest: tests/foreman/cli/test_subscription.py -k 'test_negative_check_katello_reimport'

add teardown condition to execute other test seamlessly

---

tests/foreman/cli/test_subscription.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16219
Did not delete `expired manifest` from the organization after it's use in test `test_negative_check_katello_reimport`, when test unable to execute succesfully it then it was creating problem with other test defined in UI > test_subscription.py
Both test uses same xdist worker to run.
With the help of finalizer, delete manifest and organization from test case after it's use, it will depends on test execution result.
N/A
pytest: tests/foreman/cli/test_subscription.py -k 'test_negative_check_katello_reimport'

[6.16.z] add teardown condition to execute other test seamlessly

---

tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16239
Missing PIT coverage for RH Cloud Connector
Mark test_positive_configure_cloud_connector for PIT

[6.16.z] Mark test_positive_configure_cloud_connector for PIT

---

tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16239
Missing PIT coverage for RH Cloud Connector
Mark test_positive_configure_cloud_connector for PIT

[6.15.z] Mark test_positive_configure_cloud_connector for PIT

---

tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16239
Missing PIT coverage for RH Cloud Connector
Mark test_positive_configure_cloud_connector for PIT

[6.14.z] Mark test_positive_configure_cloud_connector for PIT

---

tests/foreman/ui/test_hostgroup.py

bz closed as migrated but the problem didn't go away

updated bz skip to jira skip

---

tests/foreman/ui/test_hostgroup.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16240
bz closed as migrated but the problem didn't go away

[6.15.z] updated bz skip to jira skip

---

tests/foreman/ui/test_hostgroup.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16240
bz closed as migrated but the problem didn't go away

[6.16.z] updated bz skip to jira skip

---

tests/foreman/ui/test_hostgroup.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16240
bz closed as migrated but the problem didn't go away

[6.13.z] updated bz skip to jira skip

---

Dockerfile

```text
Installed 282 packages in 428ms
+ adal==1.2.7
+ aenum==3.1.15
+ …
```

Base robottelo image on fedora/python-312

---

Dockerfile

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16248
```text …
```

[6.16.z] Base robottelo image on fedora/python-312

---

Dockerfile

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16248
```text …
```

[6.15.z] Base robottelo image on fedora/python-312

---

Dockerfile

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16248
```text …
```

[6.14.z] Base robottelo image on fedora/python-312

---

Dockerfile

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16248
```text …
```

[6.13.z] Base robottelo image on fedora/python-312

---

tests/foreman/api/test_reporttemplates.py

The following system related host status were removed (https://docs.theforeman.org/3.10/Release_Notes/index-katello.html#_removed_system_purpose_related_host_statuses)
Subscription Status (this column has also been removed from the All Hosts table)
System Purpose Status
SLA Status
Role Status
Usage Status
Addon Status
adapt and unify expected values
tests/foreman/api/test_reporttemplates.py::test_positive_generate_report_filter
tests/foreman/api/test_reporttemplates.py::test_positive_generate_report_nofilter

Adapt api reporttemplate tests to removal of host statuses

---

tests/foreman/api/test_reporttemplates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15960
The following system related host status were removed (https://docs.theforeman.org/3.10/Release_Notes/index-katello.html#_removed_system_purpose_related_host_statuses)
Subscription Status (this column has also been removed from the All Hosts table)
System Purpose Status
SLA Status
Role Status
Usage Status
Addon Status
adapt and unify expected values
tests/foreman/api/test_reporttemplates.py::test_positive_generate_report_filter
tests/foreman/api/test_reporttemplates.py::test_positive_generate_report_nofilter

[6.16.z] Adapt api reporttemplate tests to removal of host statuses

---

.github/workflows/auto_branching.yml
conf/robottelo.yaml.template
robottelo/config/validators.py
robottelo/constants/__init__.py
tests/foreman/maintain/test_advanced.py

- With the current approach we have to maintain the `SAT_NON_GA_VERSIONS` across other branches
- Move `SAT_NON_GA_VERSIONS` constant to robottelo config
- SAT-27753
- Depend on satellite-jenkins#1465

Move SAT_NON_GA_VERSIONS constant to robottelo config

---

tests/foreman/cli/test_activationkey.py

Assertion errors detected but not a product bug; also different automation problems spotted.
Fix it in robottelo:
1. In `test_positive_usage_limit` we don't need assert particular result code, we need to ensure the registrations fails and we got the proper message.
2. Interference between `test_positive_add_custom_product` and `test_positive_create_content_and_check_enabled` causes fail since `content` had item from the previously run test (not only `[0]`). We can go `function_org` or sort the `content` based on `id`. I've chosen the first option though the second one worked too.
3. `conf/client.yaml` has been removed as obsoleted but one decorator using that survived, making `test_positive_update_aks_to_chost` fail. Removing the last survivor here.
1.
pytest: …

Fix AK tests assertion errors

---

pytest_fixtures/component/rh_cloud.py
tests/foreman/api/test_rhc.py

As part of the [Remove use of install_katello_ca with register_contenthost](https://github.com/SatelliteQE/robottelo/pull/15395) effort. The attribute "label" was removed from rhcloud_manifest_org. 
In recent automation runs, we are seeing some left over attributes that I THINK need to be removed.
I am removing .name from rhcloud_activation_key and will be doing prt testing

Fixing rh cloud rhai failures

---

tests/foreman/cli/test_organization.py

the test failed kind of mysteriously on module_org not found when associating the user. Local runs are ok, I suspect some interference with other tests from module. 
Trying out a version with custom org

using custom org for user timezone test

---

tests/foreman/cli/test_organization.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16261
the test failed kind of mysteriously on module_org not found when associating the user. Local runs are ok, I suspect some interference with other tests from module. 
Trying out a version with custom org

[6.16.z] using custom org for user timezone test

---

tests/foreman/ui/test_host.py

Small adjustment to test on RHEL8 instead of RHEL9, like the rest of the testing suite.

Adjust rhel version under test

---

tests/foreman/ui/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16290
Small adjustment to test on RHEL8 instead of RHEL9, like the rest of the testing suite.

[6.16.z] Adjust rhel version under test

---

tests/foreman/ui/test_host.py

There is a small inconsistency seen rarely in local testing, but seemingly consistently in CI where the Manage Columns button is only appearing upon refresh, as opposed to when first navigating to the page. 
This would be something that I'd like to get resolved in the future if this issue with the page is resolved. 
This is a somewhat clumsy attempt to fix this issues for testing, as the issue isn't seen locally, so is hard to reproduce. This simply "navigates" to the page, reloads, and then attempts to run the actual test. 
https://github.com/SatelliteQE/robottelo/issues/16292
https://issues.redhat.com/browse/SAT-27868 (Bug in question)
pytest: tests/foreman/ui/test_host.py -k 'test_all_hosts_manage_columns'

[6.16] Small Workaround for Manage Columns test for All Hosts page

---

tests/foreman/ui/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16293
There is a small inconsistency seen rarely in local testing, but seemingly consistently in CI where the Manage Columns button is only appearing upon refresh, as opposed to when first navigating to the page. 
This would be something that I'd like to get resolved in the future if this issue with the page is resolved. 
This is a somewhat clumsy attempt to fix this issues for testing, as the issue isn't seen locally, so is hard to reproduce. This simply "navigates" to the page, reloads, and then attempts to run the actual test. 
https://github.com/SatelliteQE/robottelo/issues/16292
https://issues.redhat.com/browse/SAT-27868 (Bug in question)
pytest: tests/foreman/ui/test_host.py -k …

[6.16.z] [6.16] Small Workaround for Manage Columns test for All Hosts page

---

tests/foreman/cli/test_organization.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16261
the test failed kind of mysteriously on module_org not found when associating the user. Local runs are ok, I suspect some interference with other tests from module. 
Trying out a version with custom org

[6.13.z] using custom org for user timezone test

---

tests/foreman/destructive/test_rename.py

Avoid calling decode on str

---

tests/foreman/destructive/test_rename.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16214

[6.14.z] Avoid calling decode on str

---

tests/foreman/destructive/test_rename.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16214

[6.15.z] Avoid calling decode on str

---

tests/foreman/destructive/test_rename.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16214

[6.16.z] Avoid calling decode on str

---

tests/foreman/destructive/test_rename.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16214

[6.13.z] Avoid calling decode on str

---

tests/foreman/cli/test_activationkey.py

Manual cherry-pick of #16220 
Closes #16262

[6.15.z] Fix AK tests assertion errors (#16220)

---

tests/foreman/endtoend/test_api_endtoend.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16307
Api changes found in 6.16 compared to the previous version. The list was shared with dev for check. Prt may fail in master, running anyway for automerge

[6.16.z] api changes for 6.16

---

tests/foreman/cli/test_host.py

The `test_negative_multi_cv_registration` uses `module_activation_key` which uses `module_sca_manifest_org` which uploads a manifest to the `module_org` (which we don't actually need for the test case).
And there is another test in this module, `test_syspurpose_end_to_end`, which uses `default_subscription` fixture which uploads a manifest to the `module_org` too and here is where the interference happens since the second manifest upload fails with 
```
['Owner has already imported from another subscription management application. The following conflicts were found: [ DISTRIBUTOR_CONFLICT ]']
```
Use `module_ak_with_cv` instead of `module_activation_key` - it does not upload any manifest and thus can't interfere with the other test.
pytest: …

Fix test interference

---

tests/foreman/data/hammer_commands.json

hammer changes found in 6.16 compared to the previous version. The list was shared with dev for check. Prt may fail in master, running anyway for automerge

hammer commands updated for 6.16

---

tests/foreman/cli/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16267
The `test_negative_multi_cv_registration` uses `module_activation_key` which uses `module_sca_manifest_org` which uploads a manifest to the `module_org` (which we don't actually need for the test case).
And there is another test in this module, `test_syspurpose_end_to_end`, which uses `default_subscription` fixture which uploads a manifest to the `module_org` too and here is where the interference happens since the second manifest upload fails with 
```
['Owner has already imported from another subscription management application. The following conflicts were found: [ DISTRIBUTOR_CONFLICT ]']
```
Use `module_ak_with_cv` instead of `module_activation_key` - it does not upload any manifest and thus can't interfere with …

[6.16.z] Fix test interference

---

tests/foreman/ui/test_hostcollection.py

pytest: tests/foreman/ui/test_hostcollection.py -k 'test_positive_end_to_end'

Fix hostCollection UI e2e test

---

tests/foreman/ui/test_hostcollection.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16318
pytest: tests/foreman/ui/test_hostcollection.py -k 'test_positive_end_to_end'

[6.15.z] Fix hostCollection UI e2e test

---

tests/foreman/ui/test_hostcollection.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16318
pytest: tests/foreman/ui/test_hostcollection.py -k 'test_positive_end_to_end'

[6.16.z] Fix hostCollection UI e2e test

---

tests/foreman/ui/test_hostcollection.py

Same Issue as in https://github.com/SatelliteQE/robottelo/pull/16318
pytest: tests/foreman/ui/test_hostcollection.py -k 'test_negative_hosts_limit'

Fix long failing hostCollection test_negative_hosts_limit test

---

robottelo/constants/__init__.py

removing repository entity from bookmarks tests

---

tests/foreman/ui/test_hostcollection.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16322
Same Issue as in https://github.com/SatelliteQE/robottelo/pull/16318
pytest: tests/foreman/ui/test_hostcollection.py -k 'test_negative_hosts_limit'

[6.15.z] Fix long failing hostCollection test_negative_hosts_limit test

---

tests/foreman/ui/test_hostcollection.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16322
Same Issue as in https://github.com/SatelliteQE/robottelo/pull/16318
pytest: tests/foreman/ui/test_hostcollection.py -k 'test_negative_hosts_limit'

[6.16.z] Fix long failing hostCollection test_negative_hosts_limit test

---

robottelo/constants/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16300

[6.15.z] removing repository entity from bookmarks tests

---

robottelo/constants/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16300

[6.14.z] removing repository entity from bookmarks tests

---

robottelo/constants/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16300

[6.13.z] removing repository entity from bookmarks tests

---

robottelo/constants/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16300

[6.16.z] removing repository entity from bookmarks tests

---

tests/foreman/api/test_hostcollection.py

By default new orgs in 6.15 are SCA-enabled and this test fails due to that.
Disable the SCA to that `module_org`. It is the last test in the module so no interference is expected.
pytest: tests/foreman/api/test_hostcollection.py -k test_positive_add_remove_subscription

Disable SCA for test using subscriptions

---

.github/workflows/update_robottelo_image.yml

Github `checkout` action stores an authentication token by default in `.git/config`.
```ini
[http "https://github.com/"]
extraheader = AUTHORIZATION: basic sometoken==
```
That causes auth issues when using robottelo image from quay.io when the auth token expires.
Do not store the auth token in the git config.

Do not store extraheader http auth in git config

---

tests/foreman/ui/test_host.py

I was seeing issues sharing module level fixtures with other tests in the class
Change the module fixture to function level fixtures, to better work in CI.
pytest: tests/foreman/ui/test_host.py -k 'test_all_hosts_manage_errata'

Change from module to function fixtures

---

.github/workflows/update_robottelo_image.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16339
Github `checkout` action stores an authentication token by default in `.git/config`.
```ini
[http "https://github.com/"]
extraheader = AUTHORIZATION: basic sometoken==
```
That causes auth issues when using robottelo image from quay.io when the auth token expires.
Do not store the auth token in the git config.

[6.14.z] Do not store extraheader http auth in git config

---

.github/workflows/update_robottelo_image.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16339
Github `checkout` action stores an authentication token by default in `.git/config`.
```ini
[http "https://github.com/"]
extraheader = AUTHORIZATION: basic sometoken==
```
That causes auth issues when using robottelo image from quay.io when the auth token expires.
Do not store the auth token in the git config.

[6.16.z] Do not store extraheader http auth in git config

---

.github/workflows/update_robottelo_image.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16339
Github `checkout` action stores an authentication token by default in `.git/config`.
```ini
[http "https://github.com/"]
extraheader = AUTHORIZATION: basic sometoken==
```
That causes auth issues when using robottelo image from quay.io when the auth token expires.
Do not store the auth token in the git config.

[6.13.z] Do not store extraheader http auth in git config

---

tests/foreman/ui/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16345
I was seeing issues sharing module level fixtures with other tests in the class
Change the module fixture to function level fixtures, to better work in CI.
pytest: tests/foreman/ui/test_host.py -k 'test_all_hosts_manage_errata'

[6.16.z] Change from module to function fixtures

---

pytest_fixtures/component/provision_pxe.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16340
Solution
Related Issues

[6.16.z] Fix pxeless discovery test

---

pytest_fixtures/component/provision_pxe.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16340
Solution
Related Issues

[6.15.z] Fix pxeless discovery test

---

pytest_fixtures/component/provision_pxe.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16340
Solution
Related Issues

[6.14.z] Fix pxeless discovery test

---

pytest_fixtures/component/provision_pxe.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16340
Solution
Related Issues

[6.13.z] Fix pxeless discovery test

---

tests/foreman/api/test_computeresource_gce.py

tests/foreman/api/test_computeresource_gce.py::test_positive_gce_host_provisioned test is failing on IPv6 Satellite with 500 error. This test is marked for sanity and thus causing sanity pipeline to fail. 
Until we fix this issue on IPv6, we are  removing sanity marker from the test.

Remove sanity marker from GCE test until issue is fixed on IPv6 satellite

---

pytest_fixtures/component/leapp_client.py
tests/foreman/cli/test_leapp_client.py

1. The module for leapp testing had different tests for testing with admin and non-admin permissions which can be merged into one.
2.  When we run multiple tests(or single parameterized test), all_repos list returns empty with previous implementation which creates content view without repos.  
1. Merge the tests for admin and non-admin to single test.
2. Fetch the repo ids and update all_repos list so that content view will have all the repos.

Merge Leapp tests to single test and Refactor it

---

tests/foreman/cli/test_ansible.py
tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15595
We've stubbed test - test_positive_install_ansible_collection_via_job_invocation, which we need to automate as part of component audit
1. Automating the stubbed test to verify install of ansible collection with user inputted collection list and collection path
2. Updating tests to use rhel_contenthost fixtures instead of rex_contenthost
3. Add upgrade marker to existing cli test to install ansible collection

[6.15.z] Automate a stubbed test to install Ansible collection from galaxy

---

tests/foreman/cli/test_ansible.py
tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15595
We've stubbed test - test_positive_install_ansible_collection_via_job_invocation, which we need to automate as part of component audit
1. Automating the stubbed test to verify install of ansible collection with user inputted collection list and collection path
2. Updating tests to use rhel_contenthost fixtures instead of rex_contenthost
3. Add upgrade marker to existing cli test to install ansible collection

[6.14.z] Automate a stubbed test to install Ansible collection from galaxy

---

tests/foreman/cli/test_fact.py

Names of few fact values have been changed causing test failures
uptime -> system_uptime
uptime_seconds -> system_uptime::seconds
memorysize -> memory::system::total
ipaddress -> networking::ip
Updated the fact values

Update fact names changed in 6.16

---

tests/upgrades/test_contentview.py

One particular `pre_upgrade` test makes the upgrade fail, which blocks other `post_upgrade` tests run.
Skip the test until the issue is fixed
https://issues.redhat.com/browse/SAT-28048

Skip CV upgrade test until SAT-28048 is resolved

---

tests/upgrades/test_contentview.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16383
One particular `pre_upgrade` test makes the upgrade fail, which blocks other `post_upgrade` tests run.
Skip the test until the issue is fixed
https://issues.redhat.com/browse/SAT-28048

[6.16.z] Skip CV upgrade test until SAT-28048 is resolved

---

tests/foreman/cli/test_fact.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16217
Names of few fact values have been changed causing test failures
uptime -> system_uptime
uptime_seconds -> system_uptime::seconds
memorysize -> memory::system::total
ipaddress -> networking::ip
Updated the fact values

[6.16.z] Update fact names changed in 6.16

---

tests/foreman/ui/test_computeresource_vmware.py

The VLAN has been changed, requiring an update in this test. Previously, the `VLAN was set to 1001`, but it has now been updated to `VLAN 400`

update network VLAN1001 to VLAN400

---

tests/foreman/ui/test_computeresource_vmware.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16377
The VLAN has been changed, requiring an update in this test. Previously, the `VLAN was set to 1001`, but it has now been updated to `VLAN 400`

[6.16.z] update network VLAN1001 to VLAN400

---

tests/foreman/ui/test_hostcollection.py

This PR fixes 2 hostCollection tests that are failing due to not selecting correct organization.
Master and 6.16.z needs: https://github.com/SatelliteQE/airgun/pull/1563
6.15.z needs: https://github.com/SatelliteQE/airgun/pull/1564
pytest: tests/foreman/ui/test_hostcollection.py -k 'test_negative_install_via_remote_execution or test_negative_install_via_custom_remote_execution'
airgun: 1563

Fix hostCollection install tests

---

tests/foreman/ui/test_computeresource_vmware.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16377
The VLAN has been changed, requiring an update in this test. Previously, the `VLAN was set to 1001`, but it has now been updated to `VLAN 400`

[6.14.z] update network VLAN1001 to VLAN400

---

tests/foreman/ui/test_hostcollection.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16379
This PR fixes 2 hostCollection tests that are failing due to not selecting correct organization.
Master and 6.16.z needs: https://github.com/SatelliteQE/airgun/pull/1563
6.15.z needs: https://github.com/SatelliteQE/airgun/pull/1564
pytest: tests/foreman/ui/test_hostcollection.py -k 'test_negative_install_via_remote_execution or test_negative_install_via_custom_remote_execution'
airgun: 1563

[6.16.z] Fix hostCollection install tests

---

tests/foreman/cli/test_bootstrap_script.py
tests/foreman/cli/test_capsule.py
tests/foreman/destructive/test_leapp_satellite.py

- Pit markers for some of the Platform team components are missing.
- Evaluate tests and add pit markers accordingly.

Update pit coverage for Platform teams components

---

tests/foreman/ui/test_computeresource_vmware.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16377
The VLAN has been changed, requiring an update in this test. Previously, the `VLAN was set to 1001`, but it has now been updated to `VLAN 400`

[6.15.z] update network VLAN1001 to VLAN400

---

tests/foreman/ui/test_hostcollection.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16379
This PR fixes 2 hostCollection tests that are failing due to not selecting correct organization.
Master and 6.16.z needs: https://github.com/SatelliteQE/airgun/pull/1563
6.15.z needs: https://github.com/SatelliteQE/airgun/pull/1564
pytest: tests/foreman/ui/test_hostcollection.py -k 'test_negative_install_via_remote_execution or test_negative_install_via_custom_remote_execution'
airgun: 1563

[6.15.z] Fix hostCollection install tests

---

tests/upgrades/test_activation_key.py

One particular `pre_upgrade` test makes the upgrade fail, which blocks other `post_upgrade` tests run.
Skip the test until the issue is fixed
https://issues.redhat.com/browse/SAT-28048

Skip AK upgrade test until SAT-28048 is resolved

---

tests/upgrades/test_activation_key.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16398
One particular `pre_upgrade` test makes the upgrade fail, which blocks other `post_upgrade` tests run.
Skip the test until the issue is fixed
https://issues.redhat.com/browse/SAT-28048

[6.16.z] Skip AK upgrade test until SAT-28048 is resolved

---

pytest_fixtures/core/sat_cap_factory.py
tests/foreman/installer/test_installer.py

[Combined Jenkins Ask] Capsule testing for sanity

---

tests/foreman/api/test_product.py
tests/foreman/api/test_repositories.py

[6.16.0] TFA -  Compoenent repositories has few tests failing with minor issue, DISTRIBUTOR_CONFLICT , Assertion Error, etc
`api/test_product.py::test_positive_filter_product_list`
`api/test_repositories.py::test_negative_upload_expired_manifest`
`api/test_repositories.py::test_positive_sync_mulitple_large_repos`
This PR will address those failures
N/A
```
pytest: tests/foreman/api/test_product.py::test_positive_filter_product_list
```
```
pytest: tests/foreman/api/test_repositories.py::test_negative_upload_expired_manifest
```
```
pytest: tests/foreman/api/test_repositories.py::test_positive_sync_mulitple_large_repos
```

fix tests from repositories component

---

Dockerfile

1. uv cache bloats the image and also causes issues in the downstream image build
2. during the image build, in the RUN step, the shell environment is not sourced, the python environment in `$APP_ROOT` is not activated and therefore `VIRTUAL_ENV` env variable is not defined. That causes uv not to discover the venv interpreter and it creates its env in `.venv` and installs robottelo in it.
1. as the upstream fedora/python-312 image forces `pip` to not create the cache, we should mimic it for `uv` too
* set `UV_NO_CACHE=1`
2. Tell uv to use Python from the existing virtual env 
* set `UV_PYTHON="${APP_ROOT}/bin/python3"`

Do not store uv cache, uv to use venv interpreter

---

tests/foreman/api/test_product.py
tests/foreman/api/test_repositories.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16227
[6.16.0] TFA -  Compoenent repositories has few tests failing with minor issue, DISTRIBUTOR_CONFLICT , Assertion Error, etc
`api/test_product.py::test_positive_filter_product_list`
`api/test_repositories.py::test_negative_upload_expired_manifest`
`api/test_repositories.py::test_positive_sync_mulitple_large_repos`
This PR will address those failures
N/A
```
pytest: tests/foreman/api/test_product.py::test_positive_filter_product_list
```
```
pytest: tests/foreman/api/test_repositories.py::test_negative_upload_expired_manifest
```
```
pytest: tests/foreman/api/test_repositories.py::test_positive_sync_mulitple_large_repos
```

[6.16.z] fix tests from repositories component

---

robottelo/host_helpers/contenthost_mixins.py

We are creating all product repofiles with `dogfood.repo` name and it's causing capsule n-1 to test to fail with `"Satellite_Engineering_Satellite_6_15_Composes_Satellite_Capsule_6_15_RHEL8" is already defined, cannot redefine (file: /etc/yum.repos.d/dogfood.repo)` as the workflow used in the pipeline create the same repofiles too, but with specific product name, for example `satellite.repo`. This causes installer to fail as repo is now defined more than once in the configuration.
- Update `download_repofile` helper to download repo to repofile named after the product.
- SAT-27944

Update download_repofile helper to create repo file with product name

---

robottelo/host_helpers/contenthost_mixins.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16410
We are creating all product repofiles with `dogfood.repo` name and it's causing capsule n-1 to test to fail with `"Satellite_Engineering_Satellite_6_15_Composes_Satellite_Capsule_6_15_RHEL8" is already defined, cannot redefine (file: /etc/yum.repos.d/dogfood.repo)` as the workflow used in the pipeline create the same repofiles too, but with specific product name, for example `satellite.repo`. This causes installer to fail as repo is now defined more than once in the configuration.
- Update `download_repofile` helper to download repo to repofile named after the product.
- SAT-27944

[6.15.z] Update download_repofile helper to create repo file with product name

---

robottelo/host_helpers/contenthost_mixins.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16410
We are creating all product repofiles with `dogfood.repo` name and it's causing capsule n-1 to test to fail with `"Satellite_Engineering_Satellite_6_15_Composes_Satellite_Capsule_6_15_RHEL8" is already defined, cannot redefine (file: /etc/yum.repos.d/dogfood.repo)` as the workflow used in the pipeline create the same repofiles too, but with specific product name, for example `satellite.repo`. This causes installer to fail as repo is now defined more than once in the configuration.
- Update `download_repofile` helper to download repo to repofile named after the product.
- SAT-27944

[6.16.z] Update download_repofile helper to create repo file with product name

---

tests/foreman/cli/test_bootstrap_script.py
tests/foreman/cli/test_capsule.py
tests/foreman/destructive/test_leapp_satellite.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15938
- Pit markers for some of the Platform team components are missing.
- Evaluate tests and add pit markers accordingly.

[6.16.z] Update pit coverage for Platform teams components

---

tests/foreman/cli/test_bootstrap_script.py
tests/foreman/cli/test_capsule.py
tests/foreman/destructive/test_leapp_satellite.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15938
- Pit markers for some of the Platform team components are missing.
- Evaluate tests and add pit markers accordingly.

[6.15.z] Update pit coverage for Platform teams components

---

Dockerfile

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16396
1. uv cache bloats the image and also causes issues in the downstream image build
2. during the image build, in the RUN step, the shell environment is not sourced, the python environment in `$APP_ROOT` is not activated and therefore `VIRTUAL_ENV` env variable is not defined. That causes uv not to discover the venv interpreter and it creates its env in `.venv` and installs robottelo in it.
1. as the upstream fedora/python-312 image forces `pip` to not create the cache, we should mimic it for `uv` too
* set `UV_NO_CACHE=1`
2. Tell uv to use Python from the existing virtual env 
* set `UV_PYTHON="${APP_ROOT}/bin/python3"`

[6.13.z] Do not store uv cache, uv to use venv interpreter

---

Dockerfile

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16396
1. uv cache bloats the image and also causes issues in the downstream image build
2. during the image build, in the RUN step, the shell environment is not sourced, the python environment in `$APP_ROOT` is not activated and therefore `VIRTUAL_ENV` env variable is not defined. That causes uv not to discover the venv interpreter and it creates its env in `.venv` and installs robottelo in it.
1. as the upstream fedora/python-312 image forces `pip` to not create the cache, we should mimic it for `uv` too
* set `UV_NO_CACHE=1`
2. Tell uv to use Python from the existing virtual env 
* set `UV_PYTHON="${APP_ROOT}/bin/python3"`

[6.16.z] Do not store uv cache, uv to use venv interpreter

---

Dockerfile

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16396
1. uv cache bloats the image and also causes issues in the downstream image build
2. during the image build, in the RUN step, the shell environment is not sourced, the python environment in `$APP_ROOT` is not activated and therefore `VIRTUAL_ENV` env variable is not defined. That causes uv not to discover the venv interpreter and it creates its env in `.venv` and installs robottelo in it.
1. as the upstream fedora/python-312 image forces `pip` to not create the cache, we should mimic it for `uv` too
* set `UV_NO_CACHE=1`
2. Tell uv to use Python from the existing virtual env 
* set `UV_PYTHON="${APP_ROOT}/bin/python3"`

[6.15.z] Do not store uv cache, uv to use venv interpreter

---

tests/upgrades/test_errata.py
tests/upgrades/test_repository.py

1. Errata upgrade scenario is failing in 6.16.z for two reasons 
- in 6.15 (pre_upgrade) new orgs are SCA-enabled by default.
- Custom products are disabled by default.
2. Custom repo check scenario is failing because custom products are disabled by default.
1. Add subscriptions only if SCA is disabled in the pre_upgrade test (on 6.15).
2. Override AK custom repos to enabled.
Pre:
```
(venv) [vsedmik@localhost robottelo]$ pytest -m pre_upgrade tests/upgrades/test_errata.py -k test_pre_scenario_generate_errata_for_client[rhel7-ipv4]
collected 6 items / 5 deselected / 1 selected …
```

Fix upgrade scenarios tests

---

tests/upgrades/test_errata.py
tests/upgrades/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16432
1. Errata upgrade scenario is failing in 6.16.z for two reasons 
- in 6.15 (pre_upgrade) new orgs are SCA-enabled by default.
- Custom products are disabled by default.
2. Custom repo check scenario is failing because custom products are disabled by default.
1. Add subscriptions only if SCA is disabled in the pre_upgrade test (on 6.15).
2. Override AK custom repos to enabled.
Pre:
```
(venv) [vsedmik@localhost robottelo]$ pytest -m pre_upgrade tests/upgrades/test_errata.py -k test_pre_scenario_generate_errata_for_client[rhel7-ipv4]
collected 6 items / 5 deselected / 1 selected …
```

[6.16.z] Fix upgrade scenarios tests

---

tests/foreman/api/test_remoteexecution.py

We are not really equipped to test the full capsule upgrade in the regular automation and I wouldn't say it's necessary. Meanwhile there came also an *update* playbook, that will be covered with https://github.com/SatelliteQE/robottelo/pull/15863 (awaits packaging)
This pr changes the *upgrade* playbook tests to merely check that the playbook is around

changes to the capsule upgrade playbook test

---

tests/foreman/ui/test_remoteexecution.py

...then expected by the test design
extend the collection of possible states

scheduled job can succeed sooner

---

tests/foreman/ui/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15564
...then expected by the test design
extend the collection of possible states

[6.15.z] scheduled job can succeed sooner

---

tests/foreman/ui/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15564
...then expected by the test design
extend the collection of possible states

[6.16.z] scheduled job can succeed sooner

---

pytest_fixtures/core/sat_cap_factory.py
tests/foreman/installer/test_installer.py

[6.15.z][Combined Jenkins Ask] Capsule testing for sanity (#15948)

---

pytest_fixtures/core/sat_cap_factory.py
tests/foreman/installer/test_installer.py

[6.14.z][Combined Jenkins Ask] Capsule testing for sanity (#15948)

---

pytest_fixtures/core/sat_cap_factory.py
tests/foreman/installer/test_installer.py

[6.13.z][Combined Jenkins Ask] Capsule testing for sanity (#15948)

---

tests/foreman/api/test_role.py

The previous skip if open on 1825698 evaluated as bz still open (it was closed as wontfix -- not sure if that was intended behavior or is_open), the conditional was removed in 
https://github.com/SatelliteQE/robottelo/commit/cc2518de45bb3f1a262fb97211c76e78975d3fb6#diff-a592fe4f270d817114eaa8fdeb69888f79909778460bffcb24c062166681654fL1425
hence test failures
remove assertions on action that won't be fixed

adjusting test_positive_create_user_by_org_admin

---

tests/foreman/api/test_remoteexecution.py

I should have rebased https://github.com/SatelliteQE/robottelo/pull/16321/files differently, I re-added skip_if section that was already obsoleted
This pr, failed cherry-picks of 16321 will be treated manually

remove accidentally re-added is_open

---

tests/foreman/api/test_role.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16460
The previous skip if open on 1825698 evaluated as bz still open (it was closed as wontfix -- not sure if that was intended behavior or is_open), the conditional was removed in 
https://github.com/SatelliteQE/robottelo/commit/cc2518de45bb3f1a262fb97211c76e78975d3fb6#diff-a592fe4f270d817114eaa8fdeb69888f79909778460bffcb24c062166681654fL1425
hence test failures
remove assertions on action that won't be fixed

[6.15.z] adjusting test_positive_create_user_by_org_admin

---

tests/foreman/api/test_role.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16460
The previous skip if open on 1825698 evaluated as bz still open (it was closed as wontfix -- not sure if that was intended behavior or is_open), the conditional was removed in 
https://github.com/SatelliteQE/robottelo/commit/cc2518de45bb3f1a262fb97211c76e78975d3fb6#diff-a592fe4f270d817114eaa8fdeb69888f79909778460bffcb24c062166681654fL1425
hence test failures
remove assertions on action that won't be fixed

[6.14.z] adjusting test_positive_create_user_by_org_admin

---

tests/foreman/api/test_remoteexecution.py

cherry pick of https://github.com/SatelliteQE/robottelo/pull/16321
closes #16452

6.14 changes to the capsule upgrade playbook test

---

tests/foreman/api/test_remoteexecution.py

cherry pick of https://github.com/SatelliteQE/robottelo/pull/16321
closes #16453

6.15 changes to the capsule upgrade playbook test

---

.github/dependency_tests.yaml

depndabot select the list dependancies in alphabetical order, does not match the correct test key 
fixing the order for broker depedancy to select the tests
```
(robottelo-env) omkarkhatavkar@Omkars-MacBook-Pro robottelo % yq eval '.["broker[docker,hussh,podman]"]' .github/dependency_tests.yaml
```

fixing the order for broker dependancy to select the tests

---

tests/foreman/destructive/test_host.py

adding verifies tag for cockpit test

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16274
DNF on the IPv6-only Satellite host can not download metadata as the download mirror/host has only `A` DNS record.
Proxy setting for DNF is being set in the `enable_satellite_or_capsule_module_for_rhel8` method. However, this method executes its steps only on RHEL 8, as is stated in its name. 
Setting proxy for DNF needs to be moved elsewhere.
Remove setting DNF proxy from `enable_satellite_or_capsule_module_for_rhel8` and move it to a separate method. Call this method from `Satellite.register_contenthost` method right after we enable the proxy for subscription-manager.
[SAT-27846](https://issues.redhat.com/browse/SAT-27846)

[6.16.z] Set DNF proxy for IPv6 runs

---

tests/foreman/destructive/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16471
just for tracability

[6.16.z] adding verifies tag for cockpit test

---

tests/foreman/api/test_role.py

This was long skipped on 1825698 that ended as wontfix. https://github.com/SatelliteQE/robottelo/pull/16321 unskipped this, hence failures

removing unskipped test

---

.github/dependency_tests.yaml
.github/workflows/dependency_merge.yml

Currently, the keys inside `dependency_tests.yaml` file need to *exactly* match the relevant dependencies in order for the GHA step to produce a positive match.
this requires extra maintenance, e.g.
https://github.com/SatelliteQE/robottelo/pull/16469
where the ordering of the listed modules didn't match and thus the GHA did not trigger the correct action.
Since we don't take any special action based on the listed dependency modules, we might loose the matching pattern a bit to completely ignore it.
this is achieved by simply chaining one more `jq` function behind the selector, that splits the string by `[` char and takes the first part of the resulting array.
```
$ yq eval '.["broker"|split("[")[0]]' dependency_tests.yaml
yq eval '.["broker[docker,hussh,podman]"|split("[")[0]]' …
```

ignore dependency modules during prt execution rule matching

---

.github/dependency_tests.yaml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16469
depndabot select the list dependancies in alphabetical order, does not match the correct test key 
fixing the order for broker depedancy to select the tests
```
(robottelo-env) omkarkhatavkar@Omkars-MacBook-Pro robottelo % yq eval '.["broker[docker,hussh,podman]"]' .github/dependency_tests.yaml
```

[6.15.z] fixing the order for broker dependancy to select the tests

---

.github/dependency_tests.yaml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16469
depndabot select the list dependancies in alphabetical order, does not match the correct test key 
fixing the order for broker depedancy to select the tests
```
(robottelo-env) omkarkhatavkar@Omkars-MacBook-Pro robottelo % yq eval '.["broker[docker,hussh,podman]"]' .github/dependency_tests.yaml
```

[6.16.z] fixing the order for broker dependancy to select the tests

---

tests/foreman/api/test_role.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16478
This was long skipped on 1825698 that ended as wontfix. https://github.com/SatelliteQE/robottelo/pull/16321 unskipped this, hence failures

[6.16.z] removing unskipped test

---

tests/foreman/api/test_role.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16478
This was long skipped on 1825698 that ended as wontfix. https://github.com/SatelliteQE/robottelo/pull/16321 unskipped this, hence failures

[6.15.z] removing unskipped test

---

tests/foreman/api/test_role.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16478
This was long skipped on 1825698 that ended as wontfix. https://github.com/SatelliteQE/robottelo/pull/16321 unskipped this, hence failures

[6.14.z] removing unskipped test

---

.github/dependency_tests.yaml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16469
depndabot select the list dependancies in alphabetical order, does not match the correct test key 
fixing the order for broker depedancy to select the tests
```
(robottelo-env) omkarkhatavkar@Omkars-MacBook-Pro robottelo % yq eval '.["broker[docker,hussh,podman]"]' .github/dependency_tests.yaml
```

[6.14.z] fixing the order for broker dependancy to select the tests

---

tests/foreman/cli/test_leapp_client.py

Missed in https://github.com/SatelliteQE/robottelo/pull/15571, so non-admin condition will fail always
Fix condition in Leapp test for non-admin user

Fix condition in Leapp test for non-admin user

---

Dockerfile

Running `git status` gives us the following output.
```
fatal: detected dubious ownership in repository at '/opt/app-root/src/robottelo'
To add an exception for this directory, call:
git config --global --add safe.directory /opt/app-root/src/robottelo
```
Add the directory to the list of safe directories to the global git config.

Build: Add  to safe directories

---

Dockerfile

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16491
Running `git status` gives us the following output.
```
fatal: detected dubious ownership in repository at '/opt/app-root/src/robottelo'
To add an exception for this directory, call:
git config --global --add safe.directory /opt/app-root/src/robottelo
```
Add the directory to the list of safe directories to the global git config.

[6.14.z] Build: Add  to safe directories

---

Dockerfile

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16491
Running `git status` gives us the following output.
```
fatal: detected dubious ownership in repository at '/opt/app-root/src/robottelo'
To add an exception for this directory, call:
git config --global --add safe.directory /opt/app-root/src/robottelo
```
Add the directory to the list of safe directories to the global git config.

[6.16.z] Build: Add  to safe directories

---

Dockerfile

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16491
Running `git status` gives us the following output.
```
fatal: detected dubious ownership in repository at '/opt/app-root/src/robottelo'
To add an exception for this directory, call:
git config --global --add safe.directory /opt/app-root/src/robottelo
```
Add the directory to the list of safe directories to the global git config.

[6.13.z] Build: Add  to safe directories

---

tests/foreman/cli/test_leapp_client.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16433
Missed in https://github.com/SatelliteQE/robottelo/pull/15571, so non-admin condition will fail always
Fix condition in Leapp test for non-admin user

[6.16.z] Fix condition in Leapp test for non-admin user

---

robottelo/cli/contentview.py
tests/foreman/api/test_contentview.py
tests/foreman/cli/test_contentview.py
tests/foreman/cli/test_docker.py

Several CV tests are failing for various reasons:
1. Ostree cases used to be skipped since hooked on a CLOSED_WONT_FIX BZ. The `skip_if_open` has been removed [here](https://github.com/SatelliteQE/robottelo/pull/16347/files#diff-b03329885851f0dc9923b776b4b70c4b716e716615b21cbf57f9b3247905060c)
2. Repo removal test cases are failing for a long time with key error since the `file-repositories` nor `yum-repositories` are returned by hammer if there are no repos to be listed.
3. `sat.cli.version_incremental_update(output_format='csv')` does not return anything when CSV format is requested since there is nothing to be listed in that format.
4. CV versions listing changed. There was an old sorting issue which was fixed but affected test cases were not.
1. I had to choose if to stub or remove …

Several ContentView test fixes

---

tests/foreman/ui/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15564
...then expected by the test design
extend the collection of possible states

[6.14.z] scheduled job can succeed sooner

---

robottelo/cli/contentview.py
tests/foreman/api/test_contentview.py
tests/foreman/cli/test_contentview.py
tests/foreman/cli/test_docker.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16486
Several CV tests are failing for various reasons:
1. Ostree cases used to be skipped since hooked on a CLOSED_WONT_FIX BZ. The `skip_if_open` has been removed [here](https://github.com/SatelliteQE/robottelo/pull/16347/files#diff-b03329885851f0dc9923b776b4b70c4b716e716615b21cbf57f9b3247905060c)
2. Repo removal test cases are failing for a long time with key error since the `file-repositories` nor `yum-repositories` are returned by hammer if there are no repos to be listed.
3. `sat.cli.version_incremental_update(output_format='csv')` does not return anything when CSV format is requested since there is nothing to be listed in that format.
4. CV versions listing changed. There was an old sorting issue which was fixed but …

[6.16.z] Several ContentView test fixes

---

tests/foreman/longrun/test_oscap.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16503
moved the identical parts from the tests to the common function, enabling parametrization for the remediation test

[6.16.z] Scap refactor

---

robottelo/host_helpers/satellite_mixins.py

Fix failing provisioning tests

---

robottelo/host_helpers/satellite_mixins.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16414

[6.16.z] Fix failing provisioning tests

---

robottelo/host_helpers/satellite_mixins.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16414

[6.15.z] Fix failing provisioning tests

---

robottelo/host_helpers/satellite_mixins.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16414

[6.14.z] Fix failing provisioning tests

---

robottelo/host_helpers/satellite_mixins.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16414

[6.13.z] Fix failing provisioning tests

---

tests/foreman/ui/test_ansible.py

Dependent PR: https://github.com/SatelliteQE/airgun/pull/1522

Check dynflow console for expected host

---

tests/foreman/endtoend/test_api_endtoend.py

a bunch of new api endpont added for 6.16

further api changes for 6.16

---

tests/foreman/installer/test_installer.py

Sanity is failing in `test_capsule_installation` since AK creation needs both, LCE and CV to be provided at the creation time since snap 73.
Use `Deafult_org_view` since it was used before anyway.
https://issues.redhat.com/browse/SAT-28353
pytest: tests/foreman/installer/test_installer.py -k test_capsule_installation

Add CV to the AK creation as a new requirement

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15918
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1522

[6.15.z] Check dynflow console for expected host

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15918
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1570

[6.16.z] Check dynflow console for expected host

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15918
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1522

[6.13.z] Check dynflow console for expected host

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15918
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1576

[6.14.z] Check dynflow console for expected host

---

tests/foreman/destructive/test_installer.py

Missing test coverage for SAT-26014
Adding a destructive test to cover SAT-26014

Add test coverage for SAT-26014

---

conf/dynaconf_hooks.py

Reverts SatelliteQE/robottelo#16409
(revert 6.16.z cherrypick only)
There are not yet **client tests** identified therefore we cannot cover both client-1 and client-2 repos w/o duplicating whole test matrix
Temporary solution is to use **client-1** repo against Satellite **6.16** and use **client-2** repo against Satellite **Stream** so that we don't duplicate whole matrix while we have coverage for both client repos.
(We are missing testing specific client repo across multiple satellite versions anyway.)

[6.16.z] Switch back to client-1 repo against Satellite 6.16

---

.github/workflows/dependency_merge.yml

dependancy-merge GHA using same configuration as the master causing failure in the automerge.
Update dependancy-merge workflow as for other z-stream branches
Skipped workflow - https://github.com/SatelliteQE/robottelo/actions/runs/11045045674/job/30681991976?pr=16500
Previously handled for 6.15.z in - https://github.com/SatelliteQE/robottelo/pull/13947

[6.16.z] Update dependancy-merge workflow as for other z-stream branches

---

tests/upgrades/conftest.py

During TFA I've seen several `post_upgrade` failures for "`rhel_contenthost`-parametrized" upgrade scenario tests where the pre-data could not be fetched from the `scenario_entities` file:
```
failed on setup with "Failed: Invalid test parameter: rhel7. Test data not found."
```
The reason is that the pre-upgrade test names are now suffixed with `-ipv4` or `-ipv6` so the `scenario_entities` hold items like this:
```
{"tests/upgrades/test_repository.py::TestSimpleContentAccessOnly::test_pre_simple_content_access_only[rhel7-ipv4]": {...}}
```
while [this piece of code](https://github.com/SatelliteQE/robottelo/blob/master/tests/upgrades/conftest.py#L267) requires the exact param, which is just `rhel7`, `rhel8`, `rhel9`.
There are probably more than one solution and I'm not sure which one …

Fetch pre_upgrade data based on node properties

---

tests/upgrades/conftest.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16423
During TFA I've seen several `post_upgrade` failures for "`rhel_contenthost`-parametrized" upgrade scenario tests where the pre-data could not be fetched from the `scenario_entities` file:
```
failed on setup with "Failed: Invalid test parameter: rhel7. Test data not found."
```
The reason is that the pre-upgrade test names are now suffixed with `-ipv4` or `-ipv6` so the `scenario_entities` hold items like this:
```
{"tests/upgrades/test_repository.py::TestSimpleContentAccessOnly::test_pre_simple_content_access_only[rhel7-ipv4]": {...}}
```
while [this piece of code](https://github.com/SatelliteQE/robottelo/blob/master/tests/upgrades/conftest.py#L267) requires the exact param, which is just `rhel7`, `rhel8`, `rhel9`. …

[6.16.z] Fetch pre_upgrade data based on node properties

---

robottelo/cli/hammer.py
robottelo/cli/repository.py

A previous PR https://github.com/SatelliteQE/robottelo/pull/15823 removed outdated code from robottelo's hammer CSV output handling. This PR removes the last workaround, now that the fix for https://projects.theforeman.org/issues/37264  is included in 6.15 with rubygem-hammer_cli_foreman_tasks-0.0.21-1.el8sat.noarch.
Remove the workaround that scans for non-CSV patterns in the output.
SAT-27296

[6.15.z] Remove CSV parser workaround

---

pytest_fixtures/component/rh_cloud.py
robottelo/hosts.py
tests/foreman/cli/test_http_proxy.py

Registering a host with insights client was failing. 
After further investigation, It appears that we were are not actually syncing rhel 6 - 9 repos but instead "mocking" them to be enabled...which are needed for insights setup.
This process must have started failing during our update to global registration across components?
My solution to this is to simply move the registration portion of ```confiure_rhai_client``` to be executed AFTER we setup the correct "mock" repositories needed and packages installed.
The other option in my mind was to manually register insights after we setup the repos using 
```insights-client --register```
But the first way allows us to register insights upon Satellite registration (which is the expected behavior)

[RHCloud] Update configure_rhai_client registration

---

tests/foreman/installer/test_installer.py

The current pytest parameterization exposes sensitive host details, such as proxy URLs, in the test results. This can lead to unintended exposure of confidential information in logs or reports, which is undesirable when sharing test results over PRT
To address this, we will update the pytest parameterization to use a custom ID (un_auth_proxy) instead of displaying the actual proxy URL. By doing so, we ensure that the test results are cleaner and more secure, as sensitive host details are hidden.

avoiding host details will be seen in the test result

---

tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16553
The current pytest parameterization exposes sensitive host details, such as proxy URLs, in the test results. This can lead to unintended exposure of confidential information in logs or reports, which is undesirable when sharing test results over PRT
To address this, we will update the pytest parameterization to use a custom ID (un_auth_proxy) instead of displaying the actual proxy URL. By doing so, we ensure that the test results are cleaner and more secure, as sensitive host details are hidden.

[6.16.z] avoiding host details will be seen in the test result

---

tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16553
The current pytest parameterization exposes sensitive host details, such as proxy URLs, in the test results. This can lead to unintended exposure of confidential information in logs or reports, which is undesirable when sharing test results over PRT
To address this, we will update the pytest parameterization to use a custom ID (un_auth_proxy) instead of displaying the actual proxy URL. By doing so, we ensure that the test results are cleaner and more secure, as sensitive host details are hidden.

[6.15.z] avoiding host details will be seen in the test result

---

tests/foreman/api/test_contentview.py

Test case covering 6.16 Bug surrounding database data types. This is currently in the Content View test suite as it presents itself when publishing Content Views with the repository contained, open to moving this to repository suite.
https://issues.redhat.com/browse/SAT-24878
pytest: tests/foreman/api/test_contentview.py -k 'test_repository_rpm_size'

Customer Case testing for database issues

---

tests/foreman/ui/test_hostcollection.py

6 UI host collection tests require that the reposets which are assigned to the hosts are enabled by the test setup which is not happening at the moment in 6.15.z.
Add repository override parameter to the `setup_content` function which is part of the `module_repos_collection` fixture that is used by the failing tests.
```
pytest: tests/foreman/ui/test_hostcollection.py -k 'test_positive_install_package or test_positive_remove_package or test_positive_upgrade_package or test_positive_install_package_group or test_positive_install_remove_package_group or test_positive_install_errata'
```

Enable repos for long failing hostCollection UI tests

---

robottelo/utils/issue_handlers/jira.py

- `fix_version` doesn't have to be part of `is_open_jira` and is actually giving false positive result
- Remove the condition.

Update is_open_jira issue handler functionality

---

tests/foreman/cli/test_rhcloud_inventory.py

Customer Case automation for SAT-24805. Sync inventory status with missing IP

[Customer Case] Adding test for syncing inventory with missing ip

---

tests/foreman/cli/test_rhcloud_inventory.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16547
Customer Case automation for SAT-24805. Sync inventory status with missing IP

[6.16.z] [Customer Case] Adding test for syncing inventory with missing ip

---

conf/capsule.yaml.template
conf/dynaconf_hooks.py
conf/server.yaml.template
pytest_fixtures/core/sat_cap_factory.py
robottelo/config/validators.py
tests/foreman/installer/test_installer.py

This PR aims to decouple the sanity tests from "Oh Snap" by introducing a more flexible approach for handling repository URLs. Instead of relying exclusively on "Oh Snap" to fetch the URLs, we will modify the behaviour to allow passing the repository URLs directly through a repos file. This approach provides more control and adaptability, …

changes to use the beaker urls for running upstream sanity

---

pytest_fixtures/component/provision_pxe.py
tests/foreman/api/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16572
Combining discovery reboot and reboot_all test into one

[6.14.z] Combine discovery reboot and reboot_all test

---

pytest_fixtures/component/provision_pxe.py
tests/foreman/api/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16572
Combining discovery reboot and reboot_all test into one

[6.15.z] Combine discovery reboot and reboot_all test

---

conf/capsule.yaml.template
conf/robottelo.yaml.template
conf/server.yaml.template
pytest_fixtures/core/sat_cap_factory.py
robottelo/config/validators.py
robottelo/host_helpers/contenthost_mixins.py
robottelo/hosts.py
tests/foreman/installer/test_installer.py

cherrypick of #15308 
closes #16200

[6.15.z] improve installer tests compatibility with pit (#15308)

---

robottelo/cli/ansible.py
robottelo/cli/host.py
robottelo/hosts.py
tests/foreman/cli/test_ansible.py
tests/foreman/ui/test_ansible.py

1. test_positive_ansible_variables_imported_with_roles is stubbed/Manual test.
1. Automate test_positive_ansible_variables_imported_with_roles for admin and non-admin users
2. Remove unrelated tests

Automate test_positive_ansible_variables_imported_with_roles

---

robottelo/cli/ansible.py
robottelo/cli/host.py
robottelo/hosts.py
tests/foreman/cli/test_ansible.py
tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16431
1. test_positive_ansible_variables_imported_with_roles is stubbed/Manual test.
1. Automate test_positive_ansible_variables_imported_with_roles for admin and non-admin users
2. Remove unrelated tests

[6.16.z] Automate test_positive_ansible_variables_imported_with_roles

---

tests/foreman/cli/test_fact.py

* Update customer BZ in docstring
* Update tests/foreman/cli/test_fact.py
* Manual cherrypick of https://github.com/SatelliteQE/robottelo/issues/15515  and https://github.com/SatelliteQE/robottelo/issues/15593

[6.13.z] Update customer BZ in docstring

---

conf/dynaconf_hooks.py
robottelo/hosts.py
tests/foreman/cli/test_report.py

We're missing test coverage for puppet-agent8 testing which is provided by new client-2 repository
Automate puppet-agent8 testing by parametrizing existing puppet tests with puppet-agent7
satellite-jenkins MR#1480

Automate puppet-agent8 testing by parametrizing existing puppet tests

---

tests/foreman/cli/test_fact.py

* Update customer BZ in docstring
* Update tests/foreman/cli/test_fact.py
* Manual cherrypick of https://github.com/SatelliteQE/robottelo/issues/15606 and https://github.com/SatelliteQE/robottelo/pull/15593

[6.14.z] Update customer BZ in docstring

---

tests/foreman/cli/test_ansible.py
tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16489
1. test_positive_ansible_variables_installed_with_collection is stubbed/Manual test.
1. Automate test_positive_ansible_variables_imported_with_roles for admin and non-admin users
Remove unrelated tests
This PR includes changes from https://github.com/SatelliteQE/robottelo/pull/16431, this needs to be rebased after merge

[6.16.z] Automate test_positive_ansible_variables_installed_with_collection

---

tests/foreman/installer/test_installer.py

Test `test_installer_modules_check` is never going to pass in Upgrades Automation which bases off of Upgrade Templates where `katello-answers.yaml` was created since Satellite 6.10 times. Once you lock in to satellite scenario this answer file gets never changed.
I don't think that current test implementation understands how these answer files work.
Diffing between various scenarios answer files is useless.
Sanitize `test_installer_modules_check` test so it does only sane testing
[SAT-28425](https://issues.redhat.com/browse/SAT-28425)

Sanitize test_installer_modules_check

---

tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16505
Test `test_installer_modules_check` is never going to pass in Upgrades Automation which bases off of Upgrade Templates where `katello-answers.yaml` was created since Satellite 6.10 times. Once you lock in to satellite scenario this answer file gets never changed.
I don't think that current test implementation understands how these answer files work.
Diffing between various scenarios answer files is useless.
Sanitize `test_installer_modules_check` test so it does only sane testing
[SAT-28425](https://issues.redhat.com/browse/SAT-28425)

[6.16.z] Sanitize test_installer_modules_check

---

conf/capsule.yaml.template
conf/dynaconf_hooks.py
conf/server.yaml.template
pytest_fixtures/core/sat_cap_factory.py
robottelo/config/validators.py
tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16549
This PR aims to decouple the sanity tests from "Oh Snap" by introducing a more flexible approach for handling repository URLs. Instead of relying exclusively on "Oh Snap" to fetch the URLs, we will modify the behaviour to allow passing the repository URLs directly through a …

[6.16.z] changes to use the beaker urls for running upstream sanity

---

conftest.py
pytest_fixtures/component/leapp_client.py
tests/foreman/ui/test_leapp_client.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15811
Automated BZ 2168494

[6.14.z] Add automation for BZ 2168494

---

robottelo/hosts.py
tests/foreman/cli/test_report.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16556
We're missing test coverage for puppet-agent8 testing which is provided by new client-2 repository
Automate puppet-agent8 testing by parametrizing existing puppet tests with puppet-agent7
satellite-jenkins MR#1480

[6.16.z] Automate puppet-agent8 testing by parametrizing existing puppet tests

---

tests/foreman/api/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15952
Missing test coverage for ansible-playbook job with nonexisting_module, which covers BZ:2107577 and BZ:2028112
Add test coverage for ansible-playbook job with nonexisting_module, which covers BZ:2107577 and BZ:2028112

[6.13.z] Add test coverage for ansible-playbook job with nonexisting_module

---

tests/foreman/cli/test_ansible.py
tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16489
1. test_positive_ansible_variables_installed_with_collection is stubbed/Manual test.
1. Automate test_positive_ansible_variables_imported_with_roles for admin and non-admin users
Remove unrelated tests
This PR includes changes from https://github.com/SatelliteQE/robottelo/pull/16431, this needs to be rebased after merge

[6.14.z] Automate test_positive_ansible_variables_installed_with_collection

---

pytest_fixtures/component/leapp_client.py
tests/foreman/ui/test_errata.py

Host checkout failing for IPv6 because we are missing parameter "deploy_network_type" while checking out host.
Added parameter "deploy_network_type" while host checkout.

Add network type option for Host checkout 

---

conf/capsule.yaml.template
conf/dynaconf_hooks.py
conf/server.yaml.template
pytest_fixtures/core/sat_cap_factory.py
robottelo/config/validators.py
tests/foreman/installer/test_installer.py

This PR aims to decouple the sanity tests from "Oh Snap" by introducing a more flexible approach for handling repository URLs. Instead of relying exclusively on "Oh Snap" to fetch the URLs, we will modify the behaviour to allow passing the repository URLs directly through a repos file. This approach provides more control and adaptability, …

 [6.15.z] - changes to use the beaker urls for running upstream sanity (#16549)

---

conf/capsule.yaml.template
conf/dynaconf_hooks.py
conf/server.yaml.template
pytest_fixtures/core/sat_cap_factory.py
robottelo/config/validators.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16549
This PR aims to decouple the sanity tests from "Oh Snap" by introducing a more flexible approach for handling repository URLs. Instead of relying exclusively on "Oh Snap" to fetch the URLs, we will modify the behaviour to allow passing the repository URLs directly through a …

[6.14.z ] - changes to use the beaker urls for running upstream sanity (#16549)

---

conf/capsule.yaml.template
conf/dynaconf_hooks.py
conf/server.yaml.template
pytest_fixtures/core/sat_cap_factory.py
robottelo/config/validators.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16549
This PR aims to decouple the sanity tests from "Oh Snap" by introducing a more flexible approach for handling repository URLs. Instead of relying exclusively on "Oh Snap" to fetch the URLs, we will modify the behaviour to allow passing the repository URLs directly through a …

[6.13.z] - changes to use the beaker urls for running upstream sanity (#16549)

---

tests/upgrades/test_virtwho.py

update subscription_status_label to subscription_facet_attribute, as there is no subscription_status_label 
Test Cases :  PASS
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade --disable-pytest-warnings
============================================================== test session starts ===============================================================
platform linux -- Python 3.11.7, pytest-8.3.2, pluggy-1.5.0
Mandatory Requirements Mismatch: cryptography==43.0.1 broker[docker,podman,hussh]==0.5.7 pytest-reportportal==5.4.2 nailgun @ git+https://github.com/SatelliteQE/nailgun.git@master#egg=nailgun deepdiff==8.0.1 pytest==8.3.3 productmd==1.40 manifester==0.2.8 airgun @ …
```

update subscription_status_label to subscription_facet_attribute

---

tests/upgrades/test_virtwho.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16516
update subscription_status_label to subscription_facet_attribute, as there is no subscription_status_label 
Test Cases :  PASS
```
(robottelo_vv_master) [root@dell-per740-68-vm-05 robottelo]# pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade --disable-pytest-warnings
============================================================== test session starts ===============================================================
platform linux -- Python 3.11.7, pytest-8.3.2, pluggy-1.5.0
Mandatory Requirements Mismatch: cryptography==43.0.1 broker[docker,podman,hussh]==0.5.7 pytest-reportportal==5.4.2 nailgun @ git+https://github.com/SatelliteQE/nailgun.git@master#egg=nailgun deepdiff==8.0.1 pytest==8.3.3 productmd==1.40 …
```

[6.16.z] update subscription_status_label to subscription_facet_attribute

---

tests/foreman/installer/test_installer.py

avoiding the oh-snap repo url in case of nightly, This was missed in my previous work related to upstream sanity  
Nightly checks will be added to the satellite repos based on the environment.

avoiding the ohsnap repo url incase of nightly

---

robottelo/host_helpers/cli_factory.py
tests/foreman/ui/test_package.py

Customer Case - SAT-26967 - When clicking on the page in the web interface showing the details of a package, there are hyperlinks for "Installed On", "Applicable To" and "Upgradable For".  When you click on any of those three links, they open search pages with a search term like this:
`applicable_rpms=httpd-2.4.37-65.module+el8.10.0 22069 b47f5c72.1.x86_64`
Provided fix along with airgun changes would solve this problem and parse link correctly
`installed_package=httpd-2.4.37-65.module+el8.10.0+22069+b47f5c72.1.x86_64`
Airgun PR - https://github.com/SatelliteQE/airgun/pull/1593
pytest: tests/foreman/ui/test_package.py -k 'test_positive_parse_package_name_url'
airgun: 1593

parse package details page link and validate plus sign

---

tests/foreman/installer/test_installer.py
tests/foreman/ui/test_host.py

This is testing a case where hosts assigned a domain ending in .ics cause Satellite to error out on old and new UI when navigating to the details page. 
https://issues.redhat.com/browse/SAT-26202
pytest: tests/foreman/ui/test_host.py -k 'test_read_host_with_ics_domain'

Add test for host with .ics domain name

---

tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16672
avoiding the oh-snap repo url in case of nightly, This was missed in my previous work related to upstream sanity  
Nightly checks will be added to the satellite repos based on the environment.

[6.16.z] avoiding the ohsnap repo url incase of nightly

---

tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16672
avoiding the oh-snap repo url in case of nightly, This was missed in my previous work related to upstream sanity  
Nightly checks will be added to the satellite repos based on the environment.

[6.15.z] avoiding the ohsnap repo url incase of nightly

---

robottelo/utils/issue_handlers/jira.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16594
- `fix_version` doesn't have to be part of `is_open_jira` and is actually giving false positive result
- Remove the condition.

[6.16.z] Update is_open_jira issue handler functionality

---

robottelo/utils/issue_handlers/jira.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16594
- `fix_version` doesn't have to be part of `is_open_jira` and is actually giving false positive result
- Remove the condition.

[6.15.z] Update is_open_jira issue handler functionality

---

robottelo/utils/issue_handlers/jira.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16594
- `fix_version` doesn't have to be part of `is_open_jira` and is actually giving false positive result
- Remove the condition.

[6.14.z] Update is_open_jira issue handler functionality

---

.github/workflows/auto_branching.yml
.github/workflows/auto_cherry_pick.yml
.github/workflows/auto_cherry_pick_merged.yaml
.github/workflows/prt_result.yml

After upgrade to from version 2 to 3 for thollander/actions-comment-pull-request@v3 causing issues in PRT and other GHA's after looking at closely https://github.com/SatelliteQE/robottelo/actions/runs/11361084949/job/31600069885#step:2:2 I believe this mostly because of the changes in the parameters 
updated the GHA to use the updated parameters

Actions comment pull request bump fix

---

pytest_fixtures/component/leapp_client.py
tests/foreman/ui/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16639
Host checkout failing for IPv6 because we are missing parameter "deploy_network_type" while checking out host.
Added parameter "deploy_network_type" while host checkout.

[6.16.z] Add network type option for Host checkout 

---

tests/foreman/cli/test_discoveredhost.py

SAT-25275 was closed in favor of SAT-27541, which caused this test to fail for EL9
Removing SAT-25275 used in is_open, and updating it to use SAT-27541

Update verifies jira in FDI validation test

---

tests/foreman/cli/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16698
SAT-25275 was closed in favor of SAT-27541, which caused this test to fail for EL9
Removing SAT-25275 used in is_open, and updating it to use SAT-27541

[6.16.z] Update verifies jira in FDI validation test

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/14556
Ansible role should be added and removed for new_ui host
Solution
Additional info
Removed test_positive_assign_role_in_new_ui , because single test case is covering add and remove scenario.
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1534

[6.13.z] add & remove ansible role

---

tests/foreman/ui/test_contentview.py

Adds 2 tests, converted from the old CV UI tests, and updated for modern behavior. E2E testing for Composite and Component CV workflows. 
Requires: https://github.com/SatelliteQE/airgun/pull/939

CV UI - E2E Testing for regular and Composite CVs 

---

tests/foreman/sys/test_fam.py

The current FAM test setup relies on being able to reach the Internet, which is "bad design"™ but also actually broken in IPv6-only environments because our lab network has IPv6, but no route to the broader Internet.
Instead of installing test dependencies via `pip` from the Internet, install them via `dnf` from the RH CDN and use them in the tests here.
There is an accompanying PR against the repo that carries the setup playbooks.

use packaged pytest, not some venv

---

tests/upgrades/conftest.py

Reverting **"halfway solution"** that causes all upgrade-scenarios tests to be red.
Reverts SatelliteQE/robottelo#16423

Revert "Fetch pre_upgrade data based on node properties"

---

tests/foreman/sys/test_fam.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16694
The current FAM test setup relies on being able to reach the Internet, which is "bad design"™ but also actually broken in IPv6-only environments because our lab network has IPv6, but no route to the broader Internet.
Instead of installing test dependencies via `pip` from the Internet, install them via `dnf` from the RH CDN and use them in the tests here.
There is an accompanying PR against the repo that carries the setup playbooks.

[6.16.z] use packaged pytest, not some venv

---

tests/foreman/sys/test_fam.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16694
The current FAM test setup relies on being able to reach the Internet, which is "bad design"™ but also actually broken in IPv6-only environments because our lab network has IPv6, but no route to the broader Internet.
Instead of installing test dependencies via `pip` from the Internet, install them via `dnf` from the RH CDN and use them in the tests here.
There is an accompanying PR against the repo that carries the setup playbooks.

[6.15.z] use packaged pytest, not some venv

---

tests/upgrades/conftest.py

Reverting **"halfway solution"** that causes all upgrade-scenarios tests to be red.
Reverts SatelliteQE/robottelo#16550

Revert "[6.16.z] Fetch pre_upgrade data based on node properties"

---

tests/upgrades/conftest.py

Reverting "halfway solution" that causes all upgrade-scenarios tests to be red.
Reverts SatelliteQE/robottelo#16552

Revert "[6.15.z] Fetch pre_upgrade data based on node properties"

---

tests/foreman/destructive/test_clone.py

Added coverage for SAT-27907.
Reordered steps to match documentation - Pulp content has to be copied to target machine before the satellite-clone is executed.
Added steps that occupy source satellite userids on target satellite server to check that satellite-clone changes ownership and permissions.

reorder and improve clone test to match docs

---

tests/upgrades/test_discovery.py
tests/upgrades/test_provisioningtemplate.py

Provisioning Template and Foreman Discovery Upgrade Scenario tests are failing with JSON parse error. 
- Updated  `test_pre_scenario_provisioning_templates` to save hostname instead of host id in pre_upgrade_data file. 
- Saving FDI version in string format in `test_pre_upgrade_fdi_version`  as Version type data is not supported to be stored.

Fix Upgrade scenarios

---

tests/upgrades/test_discovery.py
tests/upgrades/test_provisioningtemplate.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16477
Provisioning Template and Foreman Discovery Upgrade Scenario tests are failing with JSON parse error. 
- Updated  `test_pre_scenario_provisioning_templates` to save hostname instead of host id in pre_upgrade_data file. 
- Saving FDI version in string format in `test_pre_upgrade_fdi_version`  as Version type data is not supported to be stored.

[6.16.z] Fix Upgrade scenarios

---

tests/upgrades/test_discovery.py
tests/upgrades/test_provisioningtemplate.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16477
Provisioning Template and Foreman Discovery Upgrade Scenario tests are failing with JSON parse error. 
- Updated  `test_pre_scenario_provisioning_templates` to save hostname instead of host id in pre_upgrade_data file. 
- Saving FDI version in string format in `test_pre_upgrade_fdi_version`  as Version type data is not supported to be stored.

[6.13.z] Fix Upgrade scenarios

---

tests/upgrades/test_discovery.py
tests/upgrades/test_provisioningtemplate.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16477
Provisioning Template and Foreman Discovery Upgrade Scenario tests are failing with JSON parse error. 
- Updated  `test_pre_scenario_provisioning_templates` to save hostname instead of host id in pre_upgrade_data file. 
- Saving FDI version in string format in `test_pre_upgrade_fdi_version`  as Version type data is not supported to be stored.

[6.15.z] Fix Upgrade scenarios

---

tests/foreman/api/test_operatingsystem.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15412
Adding  OS Parameters to  OS end to end test
Dependent Nailgun PR: https://github.com/SatelliteQE/nailgun/pull/1191

[6.15.z] Add OS Parameters to end to end test

---

tests/foreman/ui/test_eol_banner.py

Cherry pick of https://github.com/SatelliteQE/robottelo/pull/13211
to cover SAT-21483
airgun prerequisite merged some time ago https://github.com/SatelliteQE/airgun/pull/1058

[6.13.z] eol banner 

---

tests/foreman/installer/test_installer.py

We have dropped support for port 8443 as a reverse proxy in Stream and it's causing test_capsule_installation to fail.
- Remove code for reverse proxy

Remove reverse proxy assertion code from test_capsule_installation

---

tests/foreman/installer/test_installer.py

Satellite version validation is failing as the full version is not being seeded in UMB. But while comparing the UMB satellite version with the installed satellite rpm, it fails.
Skipping the version comparison until we have a proper solution from Delivery.

Satellite version validation skip for nightly

---

tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16754
Satellite version validation is failing as the full version is not being seeded in UMB. But while comparing the UMB satellite version with the installed satellite rpm, it fails.
Skipping the version comparison until we have a proper solution from Delivery.

[6.16.z] Satellite version validation skip for nightly

---

tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16754
Satellite version validation is failing as the full version is not being seeded in UMB. But while comparing the UMB satellite version with the installed satellite rpm, it fails.
Skipping the version comparison until we have a proper solution from Delivery.

[6.14.z] Satellite version validation skip for nightly

---

tests/foreman/api/test_remoteexecution.py

Adjusting to the recent changes in satellite-maintain, for the test's scenario (upgrade from stream to stream) it no longer makes sense to specify the target version.
https://github.com/SatelliteQE/robottelo/pull/15862 is also needed to make this work, but that change is meant to be cherrypickes, while this should be master only

add test for capsule update playbook 

---

tests/foreman/sys/test_fam.py

* FAM tests need Puppet modules for two things:
* Testing of assignment of Puppet classes to hosts and hostgroups (`host` and `hostgroup` tests)
* Testing of import of Puppet classes (`puppetclasses_import` test)
* For assignment, those Puppet classes need to be already imported into Foreman
* For importing "obviously" not
* Additionally, `puppet module install <module>` requires access to Puppet Forge, which might or might not be present during the `fam-test-setup` workflow
* Instead of handling this in the `fam-test-setup` workflow, move the whole setup to `robottelo`
* Use `puppetlabs-ntp` from https://github.com/SatelliteQE/fedorapeople-repos/, as we use parameters from that module to test parameter assignment
* Fake `puppet-prometheus` as we don't use anything of the module, just the …

prepare puppet classes needed for FAM tests in setup_fam

---

tests/foreman/cli/test_acs.py

1. ACS validation messages have changed (just the case).
2. The original `or` was used in the beginnings when it differed in stream and z-streams and we wanted both to pass. Now only the second one is appropriate.
Update the messages to what we have in stream today.
pytest: tests/foreman/cli/test_acs.py -k 'test_negative_check_custom_rhui_validations or test_negative_check_simplified_validations'

Update ACS validation messages

---

conf/upgrade.yaml.template
robottelo/host_helpers/satellite_mixins.py
robottelo/hosts.py
robottelo/utils/shared_resource.py
tests/new_upgrades/conftest.py
tests/new_upgrades/test_contentview.py
tests/new_upgrades/test_repository.py
tests/robottelo/test_shared_resource.py

SharedResource:
- Added the ability to validate the result of a given action function via an action_validator function.
- Made an improvement to exiting under error conditions that improved tracking file cleanup.
upgrades/conftest:
- Removed the requirement for all upgrade tests to be marked as pre/post
- Introduced fixtures that coordinate checkout/checkin actions between multiple xdist workers.
- Introduced a fixture that performs an upgrade on a target satellite
- Introduced a fixture that is used for two test conversions in different modules.
test conversions:
- test_cv_upgrade_scenario and test_scenario_custom_repo_check converted
- pre-upgrade tests are now pre-upgrade fixtures that perform setup and yield their data in Box objects instead of saving to disk
- post-upgrade tests can …

[POC] New-Style Upgrade Tests

---

tests/foreman/ui/test_contentview.py
tests/foreman/ui/test_contentview_old.py

- Migrate upgrade case from `test_contentview_old.py` (not collected during test sessions)
- Promoted CVV in multiple environments, using UI to Delete the CVV and/or CV, removes it from the environments.
- Needs [Airgun 1592](https://github.com/SatelliteQE/airgun/pull/1592))
```
pytest: tests/foreman/ui/test_contentview.py::test_positive_delete_cv_promoted_to_multi_env
airgun: 1592
env:
ROBOTTELO_server__deploy_workflow: 'deploy-satellite-upgrade'
ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '9'
ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.16'
ROBOTTELO_server__deploy_arguments__deploy_snap_version: 'ystream'
BROKER_AnsibleTower__inventory: 'osp-rhos01-satellite-upgrade'
```

Migrate Old CV UI coverage (Upgrade)

---

pytest_plugins/requirements/req_updater.py
pytest_plugins/requirements/update_requirements.py

Logs:
```
Updated https://github.com/SatelliteQE/airgun.git (98c53e4)
Updated …
```

New improvements and fixes to pytest req updates plugin

---

pytest_plugins/requirements/req_updater.py
pytest_plugins/requirements/update_requirements.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16692
Logs:
```
Updated …
```

[6.14.z] New improvements and fixes to pytest req updates plugin

---

pytest_plugins/requirements/req_updater.py
pytest_plugins/requirements/update_requirements.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16692
Logs:
```
Updated …
```

[6.16.z] New improvements and fixes to pytest req updates plugin

---

pytest_plugins/requirements/req_updater.py
pytest_plugins/requirements/update_requirements.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16692
Logs:
```
Updated …
```

[6.15.z] New improvements and fixes to pytest req updates plugin

---

pytest_plugins/requirements/req_updater.py
pytest_plugins/requirements/update_requirements.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16692
Logs:
```
Updated …
```

[6.13.z] New improvements and fixes to pytest req updates plugin

---

pytest_fixtures/core/sat_cap_factory.py
pytest_fixtures/core/xdist.py
robottelo/hosts.py
tests/foreman/api/test_capsulecontent.py
tests/foreman/installer/test_installer.py

[Sanity Testing] Capsule Sanity Testing for capsule sync

---

tests/foreman/api/test_reporttemplates.py

Regex pattern for the returned rake tasks has change in the later versions of satellite. 
Updating the pattern to account for the \n newline that is in-between "name" and "cp_product_id"

Update regex pattern for installed products report

---

tests/foreman/api/test_reporttemplates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16696
Regex pattern for the returned rake tasks has change in the later versions of satellite. 
Updating the pattern to account for the \n newline that is in-between "name" and "cp_product_id"

[6.16.z] Update regex pattern for installed products report

---

robottelo/constants/__init__.py
robottelo/hosts.py

The default RH-Sat-QE account will be flipped to the SCA mode soon (currently the SCA is disabled there). As a result pools manipulation like attach/auto-attach won't be applicable when registering hosts via that account.
We should get rid of using pools. But before we do so and before we really flip for SCA, we could check the subscription status of the host being registered and attach pool only when it is still in the entitlement mode.
I tested the dummie bellow locally and ensured the registration succeeds for both account modes, SCA and entitlement.
Also tried Manifester using the offline token from my SCA account and worked well.
```
def test_dummie(target_sat, rhel_contenthost, module_sca_manifest_org):
rhel_contenthost.register_to_cdn()
rhel_contenthost.unregister()
```
Result:
``` …
```

Add conditioning for pool attach

---

tests/foreman/ui/test_capsulecontent.py

A tiny RFE sneaked in the 6.16.0 and we should rather test its functionality. It's just about hiding the Reclaim space warning on the internal capsule details page via settings.
This PR proposes a test case for that.
https://issues.redhat.com/browse/SAT-18549
Requires https://github.com/SatelliteQE/airgun/pull/1615
```
pytest: tests/foreman/ui/test_capsulecontent.py -k reclaim_space_warning
airgun: 1615
```

Add a test case for the reclaim space warning hiding

---

robottelo/constants/__init__.py
robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16575
The default RH-Sat-QE account will be flipped to the SCA mode soon (currently the SCA is disabled there). As a result pools manipulation like attach/auto-attach won't be applicable when registering hosts via that account.
We should get rid of using pools. But before we do so and before we really flip for SCA, we could check the subscription status of the host being registered and attach pool only when it is still in the entitlement mode.
I tested the dummie bellow locally and ensured the registration succeeds for both account modes, SCA and entitlement.
Also tried Manifester using the offline token from my SCA account and worked well.
```
def test_dummie(target_sat, rhel_contenthost, module_sca_manifest_org): …
```

[6.16.z] Add conditioning for pool attach

---

tests/foreman/ui/test_documentation_links.py

Historically, after a Satellite release, we have found that the documentation links on Satellite pages were broken, causing bugs and customer cases to be filed, resulting in a poor user experience.
- Add airgun support to get documentation links from a Satellite page. See https://github.com/SatelliteQE/airgun/pull/1611 
- Add Robottelo tests to verify that the documentation links on Satellite pages are working.
- See SAT-27552
- Depends on https://github.com/SatelliteQE/airgun/pull/1611

Add test to check Satellite documention links for GA'ed Satellite

---

pytest_fixtures/component/activationkey.py
robottelo/host_helpers/api_factory.py
robottelo/host_helpers/cli_factory.py
tests/foreman/cli/test_errata.py

Since 6.17 Activation keys create and update ops need both - CV and LCE, or none of them.
This new reality broke a couple of tests.
This PR fixes CLI errata tests accordingly. Others will follow.
https://issues.redhat.com/browse/SAT-28577
There is another fix in katello still missing in stream snap 76 (`--name` is required when `--id` is provided for AK update), that's why I used packit/PRT bellow
```
pytest: tests/foreman/cli/test_errata.py
Katello:
katello: 11166
```

Fix AK for errata CLI tests

---

tests/foreman/ui/test_documentation_links.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16812
Historically, after a Satellite release, we have found that the documentation links on Satellite pages were broken, causing bugs and customer cases to be filed, resulting in a poor user experience.
- Add airgun support to get documentation links from a Satellite page. See https://github.com/SatelliteQE/airgun/pull/1611 
- Add Robottelo tests to verify that the documentation links on Satellite pages are working.
- See SAT-27552
- Depends on https://github.com/SatelliteQE/airgun/pull/1611

[6.16.z] Add test to check Satellite documention links for GA'ed Satellite

---

tests/foreman/destructive/test_host.py
tests/foreman/ui/test_capsulecontent.py

adding customerscenario tags

---

tests/foreman/api/test_provisioningtemplate.py

removing cloned_from_id key from template object

---

tests/foreman/api/test_provisioningtemplate.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16813

[6.16.z] removing cloned_from_id key from template object

---

tests/foreman/api/test_provisioningtemplate.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16813

[6.15.z] removing cloned_from_id key from template object

---

tests/foreman/api/test_provisioningtemplate.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16813

[6.13.z] removing cloned_from_id key from template object

---

tests/foreman/destructive/test_host.py
tests/foreman/ui/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16842
closes #16836

[6.16.z] adding customerscenario tags

---

tests/foreman/destructive/test_installer.py

Test seemed to randomly fail on assertion at https://github.com/SatelliteQE/robottelo/blob/952b960381ce5817ffdd5598c3d9fc4ef8b9fff0/tests/foreman/destructive/test_installer.py#L109
After some investigation I found out that the domain is being generated randomly and for some domains (e.g. _test.com_, _test.biz_) the output of `hostname --fqdn` returns FQDN, not just "shortname" as we expected.
Removing nameservers from /etc/resolv.conf solves the issue.
```
> hostnamectl set-hostname testname # set test hostname
> echo "search example.info" > /etc/resolv.conf # set search domain to example.info
> hostname --fqdn # hostname prints only hostname without domain name
testname
> sed -i "s/^search.*/search test.biz/" /etc/resolv.conf # set search domain to test.biz
> hostname --fqdn # for some …
```

Fix test_positive_mismatched_satellite_fqdn

---

tests/foreman/api/test_provisioningtemplate.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16813

[6.14.z] removing cloned_from_id key from template object

---

tests/foreman/destructive/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16796
Test seemed to randomly fail on assertion at https://github.com/SatelliteQE/robottelo/blob/952b960381ce5817ffdd5598c3d9fc4ef8b9fff0/tests/foreman/destructive/test_installer.py#L109
After some investigation I found out that the domain is being generated randomly and for some domains (e.g. _test.com_, _test.biz_) the output of `hostname --fqdn` returns FQDN, not just "shortname" as we expected.
Removing nameservers from /etc/resolv.conf solves the issue.
```
> hostnamectl set-hostname testname # set test hostname
> echo "search example.info" > /etc/resolv.conf # set search domain to example.info
> hostname --fqdn # hostname prints only hostname without domain name
testname
> sed -i "s/^search.*/search test.biz/" …
```

[6.16.z] Fix test_positive_mismatched_satellite_fqdn

---

tests/foreman/destructive/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16796
Test seemed to randomly fail on assertion at https://github.com/SatelliteQE/robottelo/blob/952b960381ce5817ffdd5598c3d9fc4ef8b9fff0/tests/foreman/destructive/test_installer.py#L109
After some investigation I found out that the domain is being generated randomly and for some domains (e.g. _test.com_, _test.biz_) the output of `hostname --fqdn` returns FQDN, not just "shortname" as we expected.
Removing nameservers from /etc/resolv.conf solves the issue.
```
> hostnamectl set-hostname testname # set test hostname
> echo "search example.info" > /etc/resolv.conf # set search domain to example.info
> hostname --fqdn # hostname prints only hostname without domain name
testname
> sed -i "s/^search.*/search test.biz/" …
```

[6.14.z] Fix test_positive_mismatched_satellite_fqdn

---

pytest_fixtures/component/provision_pxe.py
pytest_fixtures/component/provision_vmware.py
tests/foreman/api/test_computeresource_vmware.py
tests/foreman/api/test_provisioning.py

Missing test for baremetal secureboot provisioning
Add test for baremetal secureboot provisioning

Add test for baremetal secureboot provisioning

---

tests/foreman/api/test_capsulecontent.py

We are missing coverage for the customer case listed bellow
This PR proposes a test case to ensure that the complete capsule sync repairs the repository metadata.
https://issues.redhat.com/browse/SAT-28575
Requires https://github.com/Katello/katello/pull/11168
```
pytest: tests/foreman/api/test_capsulecontent.py -k complete_sync_fixes_metadata
Katello:
katello: 11168
```

Add a test case for metadata repair on capsule complete sync

---

tests/foreman/ui/test_ansible.py

role should ignore while import

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16873

[6.14.z] role should ignore while import

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16873

[6.15.z] role should ignore while import

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16873

[6.16.z] role should ignore while import

---

pytest_fixtures/core/sat_cap_factory.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16665
Add missing deployment arguments for host deployment by merging with proper settings. This should fix PIT Installer scenarios. Credits @ogajduse

[6.16.z] add missing arguments for PIT scenarios

---

pytest_fixtures/core/sat_cap_factory.py
robottelo/host_helpers/satellite_mixins.py
robottelo/hosts.py

IPv6 proxy isn't configured for subscription manager and DNF, causing tests to fail where we register or with installer when run for IPv6
Enable IPv6 proxy when settings.server.is_ipv6=True in IPv6 runs

Enable IPv6 proxy when settings.server.is_ipv6=True in IPv6 runs

---

pytest_fixtures/core/sat_cap_factory.py
robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16795
IPv6 proxy isn't configured for subscription manager and DNF, causing tests to fail where we register or with installer when run for IPv6
Enable IPv6 proxy when settings.server.is_ipv6=True in IPv6 runs

[6.16.z] Enable IPv6 proxy when settings.server.is_ipv6=True in IPv6 runs

---

pytest_fixtures/core/sat_cap_factory.py
pytest_fixtures/core/xdist.py
robottelo/hosts.py
tests/foreman/api/test_capsulecontent.py
tests/foreman/installer/test_installer.py

[6.14.z][Sanity Testing] Capsule Sanity Testing for capsule sync (#16558)

---

tests/foreman/ui/test_ansible.py

Fixes - https://github.com/SatelliteQE/robottelo/issues/16876

[6.13.z cp] role should ignore while import

---

pytest_fixtures/core/sat_cap_factory.py
robottelo/hosts.py

Manual cherrypick of #16795 
Fixes https://github.com/SatelliteQE/robottelo/issues/16881
IPv6 proxy isn't configured for subscription manager and DNF, causing tests to fail where we register or with installer when run for IPv6
Enable IPv6 proxy when settings.server.is_ipv6=True in IPv6 runs

[6.15.z] Enable IPv6 proxy when settings.server.is_ipv6=True in IPv6 runs

---

pytest_fixtures/core/sat_cap_factory.py
tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15948

[6.16.z] [Combined Jenkins Ask] Capsule testing for sanity

---

pytest_fixtures/core/sat_cap_factory.py
pytest_fixtures/core/xdist.py
robottelo/hosts.py
tests/foreman/api/test_capsulecontent.py
tests/foreman/installer/test_installer.py

[6.13.z][Sanity Testing] Capsule Sanity Testing for capsule sync (#16558)

---

pytest_fixtures/core/sat_cap_factory.py
pytest_fixtures/core/xdist.py
robottelo/hosts.py
tests/foreman/api/test_capsulecontent.py
tests/foreman/installer/test_installer.py

[6.15.z][Sanity Testing] Capsule Sanity Testing for capsule sync (#16558)

---

pytest_fixtures/core/sat_cap_factory.py
pytest_fixtures/core/xdist.py
robottelo/hosts.py
tests/foreman/api/test_capsulecontent.py
tests/foreman/installer/test_installer.py

[6.16.z][Sanity Testing] Capsule Sanity Testing for capsule sync (#16558)

---

tests/foreman/installer/test_installer.py

There is a bug (https://issues.redhat.com/browse/SAT-29311) in fapolicyd, which freezes the machine and our tests didn't catch it. While this change will probably not surface that bug (we are still unsure how to reliably trigger it), it should at least assert fapolicyd is actually running (and didn't crash, which it sometimes does!) after policy loading.
assert systemd things fapolicyd is running
https://issues.redhat.com/browse/SAT-29311

assert fapolicyd is running after setup finished

---

tests/foreman/ui/test_activationkey.py

SAT-28981 introduced a bug when creating a new AK which had Library and Default Content view assigned during its creation, it did not have it assigned after its creation.
Adding UI automation for this bug that tests that LCE and CV assignment went through.
```
pytest: tests/foreman/ui/test_activationkey.py -k 'test_positive_new_ak_lce_cv_assignment'
Katello:
katello: 11191
```

[UI] Test LCE and CV assignment of newly created AK

---

tests/foreman/ui/test_activationkey.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16880
SAT-28981 introduced a bug when creating a new AK which had Library and Default Content view assigned during its creation, it did not have it assigned after its creation.
Adding UI automation for this bug that tests that LCE and CV assignment went through.
```
pytest: tests/foreman/ui/test_activationkey.py -k 'test_positive_new_ak_lce_cv_assignment'
Katello:
katello: 11191
```

[6.16.z] [UI] Test LCE and CV assignment of newly created AK

---

pytest_fixtures/component/provision_pxe.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_provisioning.py

Discovery tests were failing with hussh backend as the shell didn't have stdout attribute and also because of a bug in hussh: https://github.com/JacobCallahan/Hussh/issues/26 
Updated the tests to exit the shell contextmanager and read shell.result.stdout. Also, because of the bug, we need to explicitly close the shell before exiting contextmanager.

Fix Discovery Tests

---

conf/ansible.yaml.template
pytest_fixtures/component/provision_pxe.py
tests/foreman/cli/test_ansible.py

Missing test coverage for ansible-tower/AAP integration with Satellite
Add tests for ansible-tower/AAP integration with Satellite

Add tests for ansible-tower/AAP integration with Satellite

---

robottelo/constants/__init__.py
tests/foreman/api/test_permission.py

permission tests are failing with foreman_scc_manager plugin installed
adapt permission tests
relevant tests: tests/foreman/api/test_permission.py

Add permission tests for foreman_scc_manager

---

pytest_fixtures/component/provision_pxe.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_provisioning.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16605
Discovery tests were failing with hussh backend as the shell didn't have stdout attribute and also because of a bug in hussh: https://github.com/JacobCallahan/Hussh/issues/26 
Updated the tests to exit the shell contextmanager and read shell.result.stdout. Also, because of the bug, we need to explicitly close the shell before exiting contextmanager.

[6.16.z] Fix Discovery Tests

---

pytest_fixtures/component/provision_pxe.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_provisioning.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16605
Discovery tests were failing with hussh backend as the shell didn't have stdout attribute and also because of a bug in hussh: https://github.com/JacobCallahan/Hussh/issues/26 
Updated the tests to exit the shell contextmanager and read shell.result.stdout. Also, because of the bug, we need to explicitly close the shell before exiting contextmanager.

[6.13.z] Fix Discovery Tests

---

pytest_fixtures/component/provision_pxe.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_provisioning.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16605
Discovery tests were failing with hussh backend as the shell didn't have stdout attribute and also because of a bug in hussh: https://github.com/JacobCallahan/Hussh/issues/26 
Updated the tests to exit the shell contextmanager and read shell.result.stdout. Also, because of the bug, we need to explicitly close the shell before exiting contextmanager.

[6.14.z] Fix Discovery Tests

---

conf/dynaconf_hooks.py
robottelo/config/__init__.py
robottelo/utils/url.py

The proposed solution is to shift to a different approach - from mutating settings by an algorithm in robottelo to creating a self-contained …

Rely on dynaconf to render the config based on is_ipv6 setting

---

tests/foreman/api/test_provisioningtemplate.py

Manual Cherry pick of https://github.com/SatelliteQE/robottelo/pull/15719

[6.15.z] Update tests for change in network configuration

---

tests/foreman/cli/test_ostreebranch.py

Ostree content type is not supported in downstream since 6.10. Ostree tests used to be been skipped based on the BZ status (CLOSED_WONTFIX) until #16347 was merged and now they are failing with validation error.
Stub the tests until the ostree is supported again.

Stub out the ostree tests

---

tests/foreman/cli/test_ostreebranch.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16922
Ostree content type is not supported in downstream since 6.10. Ostree tests used to be been skipped based on the BZ status (CLOSED_WONTFIX) until #16347 was merged and now they are failing with validation error.
Stub the tests until the ostree is supported again.

[6.16.z] Stub out the ostree tests

---

tests/foreman/cli/test_ostreebranch.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16922
Ostree content type is not supported in downstream since 6.10. Ostree tests used to be been skipped based on the BZ status (CLOSED_WONTFIX) until #16347 was merged and now they are failing with validation error.
Stub the tests until the ostree is supported again.

[6.15.z] Stub out the ostree tests

---

tests/foreman/cli/test_ostreebranch.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16922
Ostree content type is not supported in downstream since 6.10. Ostree tests used to be been skipped based on the BZ status (CLOSED_WONTFIX) until #16347 was merged and now they are failing with validation error.
Stub the tests until the ostree is supported again.

[6.14.z] Stub out the ostree tests

---

tests/foreman/longrun/test_oscap.py

no longer possible to create an AK with LCE only, both LCE and CV need to be supplied

changed requirements for activation keys

---

tests/foreman/sys/test_fam.py

The upstream FAM Makefile expects a `galaxy.yml` to read some data from it, as it exists in git.
A release doesn't include `galaxy.yml` (it's the input to the release process).
But we call the Makefile on a released version, and this produces irritating output on stderr (without being an actual error).
The data in the file is unused, but not being able to load it produces
errors in the logs and is confusing when searching for an actual problem
during testing. Fake a file to silence the errors.

Create fake galaxy.yml to make the FAM Makefile happy

---

tests/foreman/sys/test_fam.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16936
The upstream FAM Makefile expects a `galaxy.yml` to read some data from it, as it exists in git.
A release doesn't include `galaxy.yml` (it's the input to the release process).
But we call the Makefile on a released version, and this produces irritating output on stderr (without being an actual error).
The data in the file is unused, but not being able to load it produces
errors in the logs and is confusing when searching for an actual problem
during testing. Fake a file to silence the errors.

[6.16.z] Create fake galaxy.yml to make the FAM Makefile happy

---

tests/foreman/endtoend/test_api_endtoend.py

API e2e test to use hammer to register instead of API/nailgun
- Update API e2e test to use RegistrationCommand entity to register
- Also cover the package install during registration process with RegistrationCommand entity
https://github.com/SatelliteQE/nailgun/pull/1225

Update API e2e test to use RegistrationCommand entity to register

---

tests/foreman/endtoend/test_api_endtoend.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16914
API e2e test to use hammer to register instead of API/nailgun
- Update API e2e test to use RegistrationCommand entity to register
- Also cover the package install during registration process with RegistrationCommand entity
https://github.com/SatelliteQE/nailgun/pull/1225

[6.16.z] Update API e2e test to use RegistrationCommand entity to register

---

.github/CODEOWNERS
robottelo/constants/__init__.py
tests/foreman/api/test_repository.py
tests/new_upgrades/test_repository.py
tests/upgrades/test_repository.py

1. Manifest labels, annotations and other flags were added to manifest lists too (previously they were added to manifests only). After container-type repo sync they should be indexed and returned by API.
2. Also the labels and flags should be indexed during upgrade from 6.16 to 6.17.
3. We are going to have a new-style approach to the upgrade scenarios.
1. We already have a test case to check the fields in manifests. This PR extends the test case to check the same in manifest lists too.
2. We already have similar test case in upgrade scenarios. This PR extends the test case, and
3. adds new one as an upgrade new-styler using the `share_resource` approach.
4. Here we also update the `CODEOWNERS` file with the new upgrade files.
https://issues.redhat.com/browse/SAT-27490
Requires …

Extend manifest labels test case with manifest_lists

---

tests/foreman/api/test_subscription.py
tests/foreman/ui/test_subscription.py

This PR fixes 2 long failing subscription tests.
One of them was missing the required function parameter (lce_id) thus was failing.
For second UI test I have upgraded the fixture and UI test logic to used legacy content host's UI.
```
pytest: tests/foreman/ui/test_subscription.py::test_positive_subscription_status_disabled_golden_ticket  tests/foreman/api/test_subscription.py::test_sca_end_to_end
```

[6.15.z] Fix some long failing subscription tests

---

conf/dynaconf_hooks.py
robottelo/config/__init__.py
robottelo/utils/url.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16886
The proposed solution is to shift to a different approach - from mutating …

[6.16.z] Rely on dynaconf to render the config based on is_ipv6 setting

---

robottelo/config/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16886
The proposed solution is to shift to a different approach - from mutating …

[6.13.z] Rely on dynaconf to render the config based on is_ipv6 setting

---

robottelo/config/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16886
The proposed solution is to shift to a different approach - from mutating …

[6.14.z] Rely on dynaconf to render the config based on is_ipv6 setting

---

conf/dynaconf_hooks.py
robottelo/config/__init__.py
robottelo/utils/url.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16886
The proposed solution is to shift to a different approach - from mutating …

[6.15.z] Rely on dynaconf to render the config based on is_ipv6 setting

---

tests/foreman/ui/test_host.py

RFE `SAT-9132` adds new search options for hosts.
Two new tests were added for searching hosts with these new options:
- reported data, like, BIOS vendor, version, etc.
- new alias `configuration_status` for `status` 
Requires
~~https://github.com/SatelliteQE/airgun/pull/1453~~
https://github.com/SatelliteQE/airgun/pull/1603
https://github.com/SatelliteQE/nailgun/pull/1202

host: tests for new search options

---

tests/foreman/ui/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15539
RFE `SAT-9132` adds new search options for hosts.
Two new tests were added for searching hosts with these new options:
- reported data, like, BIOS vendor, version, etc.
- new alias `configuration_status` for `status` 
Requires
~~https://github.com/SatelliteQE/airgun/pull/1453~~
https://github.com/SatelliteQE/airgun/pull/1603
https://github.com/SatelliteQE/nailgun/pull/1202

[6.15.z] host: tests for new search options

---

tests/foreman/ui/test_ansible.py
tests/foreman/ui/test_leapp_client.py
tests/foreman/ui/test_remoteexecution.py

since snap 78
```
AssertionError: assert 'Succeeded' == 'success'
- success
+ Succeeded
```
this PR

success > Succeeded status change in host table

---

tests/foreman/sys/test_fam.py

pytest by default tries to load all plugins it finds on a system.
pulpcore ships with own pytest plugins, but we do not install their
dependencies (as we don't want to run pulpcore tests), which leads to
pytest failing to load those plugins and breaking overall execution:
File "/usr/bin/pytest-3.11", line 33, in <module>
sys.exit(load_entry_point('pytest==7.2.0', 'console_scripts', 'pytest')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/_pytest/config/__init__.py", line 190, in console_main
code = main()
^^^^^^
File "/usr/lib/python3.11/site-packages/_pytest/config/__init__.py", line 148, in main
config = _prepareconfig(args, plugins)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …

disable pytest plugin autoloading when running FAM tests

---

tests/foreman/sys/test_fam.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16975
pytest by default tries to load all plugins it finds on a system.
pulpcore ships with own pytest plugins, but we do not install their
dependencies (as we don't want to run pulpcore tests), which leads to
pytest failing to load those plugins and breaking overall execution:
File "/usr/bin/pytest-3.11", line 33, in <module>
sys.exit(load_entry_point('pytest==7.2.0', 'console_scripts', 'pytest')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/_pytest/config/__init__.py", line 190, in console_main
code = main()
^^^^^^
File "/usr/lib/python3.11/site-packages/_pytest/config/__init__.py", line 148, in main
config = …

[6.16.z] disable pytest plugin autoloading when running FAM tests

---

conf/http_proxy.yaml.template
conf/migrations.py
conf/server.yaml.template
pytest_fixtures/component/maintain.py
pytest_fixtures/core/broker.py
pytest_fixtures/core/sat_cap_factory.py
robottelo/config/validators.py
robottelo/host_helpers/contenthost_mixins.py
robottelo/hosts.py
tests/foreman/api/test_http_proxy.py
tests/foreman/installer/test_installer.py

- The current design of `enable_ipv6_http_proxy` and `disable_ipv6_http_proxy` is incorrect and confusing. 
- `Satellite` and `Capsule` classes of `robottelo/hosts.py` have `enable_ipv6_http_proxy`. The one present in Satellite is for setting HTTP proxy in Satellite settings(content and general HTTP proxy). And the one in Capsule is for enabling HTTP proxy for dnf and rhsm.
- This design doesn't allow Satellite to set dnf and rhsm proxies.
- Remove`enable_ipv6_http_proxy` and `disable_ipv6_http_proxy` from `Satellite` and `Capsule` classes.
- Add `enable_satellite_http_proxy` and `disable_satellite_http_proxy` to enable/disable ipv4/ipv6 HTTP proxy.  
- Add `enable_satellite_ipv6_http_proxy` in `Satellite` class to set Ipv6 HTTP proxy in Satellite settings, rhsm, and dnf.
- Add …

Refactor ipv6 http_proxy code

---

conf/http_proxy.yaml.template
conf/migrations.py
conf/server.yaml.template
pytest_fixtures/component/maintain.py
pytest_fixtures/core/broker.py
pytest_fixtures/core/sat_cap_factory.py
robottelo/config/validators.py
robottelo/host_helpers/contenthost_mixins.py
robottelo/hosts.py
tests/foreman/api/test_http_proxy.py
tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16928
The current design of enable_ipv6_http_proxy and disable_ipv6_http_proxy is incorrect and confusing.
Satellite and Capsule classes of robottelo/hosts.py have enable_ipv6_http_proxy. The one present in Satellite is for setting HTTP proxy in Satellite settings(content and general HTTP proxy). And the one in Capsule is for enabling HTTP proxy for dnf and rhsm.
This design doesn't allow Satellite to set dnf and rhsm proxies.
Solution
Removeenable_ipv6_http_proxy and disable_ipv6_http_proxy from Satellite and Capsule classes.
Add enable_satellite_http_proxy and disable_satellite_http_proxy to enable/disable ipv4/ipv6 HTTP proxy.
Add enable_satellite_ipv6_http_proxy in Satellite class to set Ipv6 HTTP proxy …

[6.16.z] Refactor ipv6 http_proxy code 

---

conf/http_proxy.yaml.template
conf/migrations.py
conf/server.yaml.template
pytest_fixtures/component/maintain.py
pytest_fixtures/core/broker.py
pytest_fixtures/core/sat_cap_factory.py
robottelo/config/validators.py
robottelo/host_helpers/contenthost_mixins.py
robottelo/hosts.py
tests/foreman/api/test_http_proxy.py
tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16928
- The current design of `enable_ipv6_http_proxy` and `disable_ipv6_http_proxy` is incorrect and confusing. 
- `Satellite` and `Capsule` classes of `robottelo/hosts.py` have `enable_ipv6_http_proxy`. The one present in Satellite is for setting HTTP proxy in Satellite settings(content and general HTTP proxy). And the one in Capsule is for enabling HTTP proxy for dnf and rhsm.
- This design doesn't allow Satellite to set dnf and rhsm proxies.
- Remove`enable_ipv6_http_proxy` and `disable_ipv6_http_proxy` from `Satellite` and `Capsule` classes.
- Add `enable_satellite_http_proxy` and `disable_satellite_http_proxy` to enable/disable ipv4/ipv6 HTTP proxy.  
- Add `enable_satellite_ipv6_http_proxy` in `Satellite` class to set …

[6.15.z] Refactor ipv6 http_proxy code

---

tests/foreman/data/haproxy.cfg

Port 8443 was removed as reverse proxy from capsule. Clients should use port 443 for RHSM and others.
The modified haproxy.cfg is being used in tests of Load Balancer

remove port 8443

---

pytest_fixtures/component/contentview.py
robottelo/host_helpers/satellite_mixins.py
tests/foreman/cli/test_host.py

MultiCV has become available in 6.17 via setting, no hacks are needed anymore.
Just remove the helper from mixins and fixture.
pytest: tests/foreman/cli/test_host.py -k _multi_cv_

Remove the MultiCV hack since it's become available

---

tests/foreman/sys/test_fam.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16980
The command we use to execute FAM tests is complicated and uses shell chaining which is not well readable
- we don't need to export vars, setting them should be sufficient
- make can change directories for us, no need to cd

[6.16.z] simplify FAM test command

---

tests/foreman/installer/test_installer.py

- `test_installer_modules_check` doesn't need to be a separate test
- `test_satellite_installation_on_ipv6`, `test_capsule_installation_on_ipv6` and `test_installer_check_on_ipv6` are not required as we now have IPv6 matrix.
- Remove `test_satellite_installation_on_ipv6`, `test_capsule_installation_on_ipv6` and `test_installer_check_on_ipv6`.
- Move test code of `test_installer_modules_check` to `test_installer_modules_check`

Remove test_installer_modules_check and stubbed IPv6 tests

---

tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16963
- `test_installer_modules_check` doesn't need to be a separate test
- `test_satellite_installation_on_ipv6`, `test_capsule_installation_on_ipv6` and `test_installer_check_on_ipv6` are not required as we now have IPv6 matrix.
- Remove `test_satellite_installation_on_ipv6`, `test_capsule_installation_on_ipv6` and `test_installer_check_on_ipv6`.
- Move test code of `test_installer_modules_check` to `test_installer_modules_check`

[6.16.z] Remove test_installer_modules_check and stubbed IPv6 tests

---

tests/foreman/api/test_repository.py

deb repos allow on_deman download policy
Exclude deb repo from negative test
This was alread fixed in cli tests https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_repository.py#L662
relevant tests tests/foreman/api/test_repository.py::TestRepository::test_negative_create_repos_with_download_policy

On demand download policy is supported for deb

---

tests/foreman/api/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16961
deb repos allow on_deman download policy
Exclude deb repo from negative test
This was alread fixed in cli tests https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/cli/test_repository.py#L662
relevant tests tests/foreman/api/test_repository.py::TestRepository::test_negative_create_repos_with_download_policy

[6.16.z] On demand download policy is supported for deb

---

tests/foreman/maintain/test_upgrade.py

- `satellite-maintain update` command's output has changed because of https://github.com/theforeman/foreman_maintain/pull/944 causing `test_positive_self_update_maintain_package` to fail with assertion error.
- Updated the assertion
- SAT-29668

Fix assertion error for test_positive_self_update_maintain_package

---

tests/foreman/sys/test_fam.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16997
The ntp module in the fixtures is too old, but we also only need a few params from it.
Drop the install code and use the fake code to create a module as the tests expect

[6.16.z] create a fake ntp module for FAM tests

---

tests/foreman/cli/test_activationkey.py

Automation coverage for SAT-27863
Adds support for multi environment activation keys.
new test case "test_positive_multi_cv_info"
No
```
pytest: tests/foreman/cli/test_activationkey.py -k 'test_positive_multi_cv_info'
```

multi cv ak displays content view environments information

---

tests/foreman/sys/test_fam.py

The output of FAM tests is mangled due to how pytest tries to print the big `result` object.
There are no linebreaks and it's super hard to find the failure.
Additionally the double assert is pointless, as it asserts twice the same thing: the result is successful.
Stop asserting `PASSED` in stdout (additionally saves the case where there is the string `PASSED` in the output for some reason, but the test actually failed).
Pass a custom error output to the `status == 0` assertion, including stdout, stderr and the status code.

better logging of fam failures

---

tests/foreman/api/test_repository.py
tests/foreman/cli/test_repository.py

see https://github.com/Katello/katello/pull/11184
see title
adapt tests
relevant tests
tests/foreman/cli/test_repository.py::TestRepository::test_negative_create_repos_with_download_policy
tests/foreman/api/test_repository.py::TestRepository::test_negative_create_repos_with_download_policy

Donwload policy on_demand supported for file type repository

---

.github/dependabot.yml
requirements.txt

This reverts commit cfce89a7f496405837d0514fe2cc3f4e806a5424.
Updating cryptography to 44.0.0 causes the following error:
```
11:03:30  _ ERROR at setup of TestGCEHostProvisioningTestCase.test_positive_gce_host_provisioned[sat] _
11:03:30  pytest_fixtures/component/provision_gce.py:92: in gce_latest_rhel_uuid
11:03:30      templates = googleclient.find_templates(
11:03:30  ../../lib64/python3.12/site-packages/wrapanapi/systems/google.py:721: in find_templates
11:03:30      return self._list_templates(
11:03:30  ../../lib64/python3.12/site-packages/wrapanapi/systems/google.py:664: in _list_templates
11:03:30      .execute()
11:03:30  ../../lib64/python3.12/site-packages/googleapiclient/_helpers.py:130: in positional_wrapper
11:03:30      return wrapped(*args, **kwargs)
11:03:30 …
```

Revert "Bump cryptography from 43.0.3 to 44.0.0 (#17004)"

---

tests/foreman/ui/test_capsulecontent.py

In 6.17 capsule content counts will be updated separately for each CV when it is synced to the capsule and we should have a test case to cover that.
There is currently a bug discovered by this test case, so the PRT is expected to fail on 2 assertions until the issue is resolved:
https://issues.redhat.com/browse/SAT-29679 
This PR just adds UI coverage, more functional testing is added in CLI counterpart.
Requires
https://github.com/Katello/katello/pull/11176 (merged, in snap)
https://github.com/Katello/katello/pull/11187 (merged, in snap)
https://github.com/Katello/katello/pull/11235
https://github.com/SatelliteQE/airgun/pull/1605
```
pytest: tests/foreman/ui/test_capsulecontent.py -k granular
airgun: 1605
Katello:
katello: 11235
```

Add an UI test case for capsule content counts granularity

---

tests/foreman/sys/test_fam.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16967
The output of FAM tests is mangled due to how pytest tries to print the big `result` object.
There are no linebreaks and it's super hard to find the failure.
Additionally the double assert is pointless, as it asserts twice the same thing: the result is successful.
Stop asserting `PASSED` in stdout (additionally saves the case where there is the string `PASSED` in the output for some reason, but the test actually failed).
Pass a custom error output to the `status == 0` assertion, including stdout, stderr and the status code.

[6.16.z] better logging of fam failures

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17019
Sanity GCE Test is failing with depreciated sign function in pyopenssl new version.
The wrapanAPI version 3.6.3 has pinned pyopenssl. So pin the package to 3.6.3

[6.13.z] update WrapanAPI dependency

---

tests/foreman/maintain/test_health.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17025
- https://yum.theforeman.org/releases/nightly/el8/x86_64/ is no longer available causing `test_negative_health_check_upstream_repository` to fail with assertion error.
- Update URLs (EL version doesn't matter for the test)
- SAT-29867

[6.16.z] Update test_negative_health_check_upstream_repository

---

tests/foreman/maintain/test_health.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17025
- https://yum.theforeman.org/releases/nightly/el8/x86_64/ is no longer available causing `test_negative_health_check_upstream_repository` to fail with assertion error.
- Update URLs (EL version doesn't matter for the test)
- SAT-29867

[6.15.z] Update test_negative_health_check_upstream_repository

---

tests/foreman/maintain/test_health.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17025
- https://yum.theforeman.org/releases/nightly/el8/x86_64/ is no longer available causing `test_negative_health_check_upstream_repository` to fail with assertion error.
- Update URLs (EL version doesn't matter for the test)
- SAT-29867

[6.14.z] Update test_negative_health_check_upstream_repository

---

pytest_fixtures/component/leapp_client.py
tests/foreman/cli/test_leapp_client.py
tests/foreman/ui/test_leapp_client.py

RHEL 9.5 is released but leapp tests were still using RHEL9.4 
RHEL 9 is updated to 9.5

Update RHEL9 version for Leapp client

---

pytest_fixtures/component/leapp_client.py
tests/foreman/cli/test_leapp_client.py
tests/foreman/ui/test_leapp_client.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17010
RHEL 9.5 is released but leapp tests were still using RHEL9.4 
RHEL 9 is updated to 9.5

[6.16.z] Update RHEL9 version for Leapp client

---

pytest_fixtures/component/leapp_client.py
tests/foreman/cli/test_leapp_client.py
tests/foreman/ui/test_leapp_client.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17010
RHEL 9.5 is released but leapp tests were still using RHEL9.4 
RHEL 9 is updated to 9.5

[6.14.z] Update RHEL9 version for Leapp client

---

requirements.txt

Robottelo uses wrapanapi and currently it is pinned to version 3.6.4. Since we are always using latest version of wrapanapi so pinning to version needs to be updated whenever wrapanapi releases a new version.  
Unpinned wrapanapi to always use the latest version in robottelo.

Unpin wrapanapi version from requirements file

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17049
Robottelo uses wrapanapi and currently it is pinned to version 3.6.4. Since we are always using latest version of wrapanapi so pinning to version needs to be updated whenever wrapanapi releases a new version.  
Unpinned wrapanapi to always use the latest version in robottelo.

[6.13.z] Unpin wrapanapi version from requirements file

---

tests/foreman/sys/test_katello_certs_check.py

-  `test_katello_certs_check_output_invalid_input[error0-certs/invalid.crt-certs/invalid.key-certs/ca.crt]` is failing with AssertionError because the error message has changed.
- Fix assertion
- SAT-29725

Fix assertion for test_katello_certs_check_output_invalid_input

---

tests/foreman/sys/test_katello_certs_check.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17002
-  `test_katello_certs_check_output_invalid_input[error0-certs/invalid.crt-certs/invalid.key-certs/ca.crt]` is failing with AssertionError because the error message has changed.
- Fix assertion
- SAT-29725

[6.16.z] Fix assertion for test_katello_certs_check_output_invalid_input

---

tests/foreman/cli/test_remoteexecution.py

assertion fix for rex time expressions test

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17059

[6.15.z] assertion fix for rex time expressions test

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17059

[6.16.z] assertion fix for rex time expressions test

---

requirements.txt

This reverts commit 3f8eb05a7c977f032e7a41c217fb97ec2d6d399e.
Apply the same fix that we did for #17011
Reverting to 43.0.3 makes sanity jobs work again.

Revert "[6.16.z] Bump cryptography from 43.0.3 to 44.0.0 (#17008)"

---

requirements.txt

Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/17023

 [6.15.z]Unpin wrapanapi version from requirements file

---

conf/fam.yaml.template

This was originally removed in c390a27ea411b8701383f2214b6848b6c287f71e
as always setting the password broke idempotency.
But with https://github.com/theforeman/foreman-ansible-modules/pull/1806
we can now set the password for creation, but avoid trying to update it.

FAM: set a password for LDAP Auth sources at creation

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17059

[6.14.z] assertion fix for rex time expressions test

---

conf/repos.yaml.template
robottelo/hosts.py

Repo addition requested for insights client to work using RHEL10: https://github.com/SatelliteQE/robottelo/pull/17044#issuecomment-2514429160 
Also to get RHEL10 param working for Stream testing of MR #16913 
Also needs ~Satellite-Jenkins MR 1568~ (merged) , adding RHEL10 BASEOS and APPSTREAM to `repos.yaml`

RHEL10 OS repository for Insights Client

---

tests/foreman/api/test_rhcloud_inventory.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16913
David: Since RHEL10 clients are only in stream, we do not expect a RHEL10 param in 6.16.z. 
All prior RHEL distros (up to rhel9) should pass PRT

[6.16.z] [CC Automation] Test for Scheduled insights sync job

---

tests/foreman/cli/test_rhcloud_inventory.py

`$ insights-client --ansible-host=foo.example.com`  fails when execute
BZ - SAT-28695
This PR will test this BZ scenario in 6.16.z and 6.15.z
https://issues.redhat.com/browse/SAT-28695
```
```

automation coverage for SAT-28695

---

tests/foreman/cli/test_rhcloud_inventory.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17044
`$ insights-client --ansible-host=foo.example.com`  fails when execute
BZ - SAT-28695
This PR will test this BZ scenario in 6.16.z and 6.15.z
https://issues.redhat.com/browse/SAT-28695
```
```

[6.15.z] automation coverage for SAT-28695

---

tests/foreman/cli/test_rhcloud_inventory.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17044
`$ insights-client --ansible-host=foo.example.com`  fails when execute
BZ - SAT-28695
This PR will test this BZ scenario in 6.16.z and 6.15.z
https://issues.redhat.com/browse/SAT-28695
```
```

[6.16.z] automation coverage for SAT-28695

---

conf/jira.yaml.template
robottelo/config/validators.py
robottelo/constants/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16721

[6.16.z] Update Jira ON_QA status for Jira issue handler

---

conf/jira.yaml.template
robottelo/config/validators.py
robottelo/constants/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16721

[6.15.z] Update Jira ON_QA status for Jira issue handler

---

conf/jira.yaml.template
robottelo/config/validators.py
robottelo/constants/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16721

[6.14.z] Update Jira ON_QA status for Jira issue handler

---

conf/jira.yaml.template
robottelo/config/validators.py
robottelo/constants/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16721

[6.13.z] Update Jira ON_QA status for Jira issue handler

---

pytest_fixtures/core/xdist.py

- Currently, Capsule host in build sanity job gets checked in even when there are test failures. This makes it hard to debug test failures, especially in the case of nightly and snap templatization jobs.
- Preserve Capsule for debugging

Preserve Capsule host for build sanity failures

---

tests/foreman/api/test_multiple_paths.py

Changed the test so it doesn't just check the first perm, associated a related JIRA

permission read test skipped

---

tests/foreman/destructive/test_ldapauthsource.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17089
pytest: tests/foreman/destructive/test_ldapauthsource.py::test_rhsso_login_using_hammer

[6.16.z] Fix an assert in RHSSO test

---

tests/foreman/destructive/test_ldapauthsource.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17089
pytest: tests/foreman/destructive/test_ldapauthsource.py::test_rhsso_login_using_hammer

[6.15.z] Fix an assert in RHSSO test

---

tests/foreman/installer/test_installer.py

test_capsule_installation is failing because of SAT-29982
- Skip the assertion till the issue is resolved as it shouldn't affect other functionalities and continue with the rest of the code.
- SAT-29982
- SAT-29984

Skip /var/log/foreman-proxy/ log assertion for capsule installation

---

pytest_plugins/fixture_markers.py
pytest_plugins/markers.py

Partial cherry-pick of #16807 , adding ('N-x') format to parametrize marker `rhel_ver_match` for rhel contenthosts/clients.
Just CPing the fixture changes, as some new tests are also being CP'd to 6.16/6.15.z, with the N-x marker format.
Otherwise, the format is invalid for regex, so all distros are picked including fips.
_Note_: In 6.15.z and 6.16.z , RHEL9 is N (newest) in `supportability.yaml`. RHEL10 is only in Stream (6.17)
Example: 
```
@pytest.mark.rhel_ver_match('N-2') # rhel9, 8, and 7  in 6.16 and 6.15
def test_case(rhel_contenthost, target_sat, ...):
```
```
or tests/foreman/api/test_rhcloud_inventory.py -k 'test_rhcloud_scheduled_insights_sync'
```

[6.16.z] CP: rhel_ver_match(N-x) Optional Format

---

tests/foreman/installer/test_installer.py

This reverts commit b8890f951682019b1de38ae4b19571fd16bc4905.
It's not required once gitlab MR satellite-packaging/#8552 is merged
Note: Do not merge before

Revert "Skip /var/log/foreman-proxy/ log assertion for capsule installation"

---

pytest_plugins/fixture_markers.py
pytest_plugins/markers.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17090
Partial cherry-pick of #16807 , adding ('N-x') format to parametrize marker `rhel_ver_match` for rhel contenthosts/clients.
Just CPing the fixture changes, as some new tests are also being CP'd to 6.16/6.15.z, with the N-x marker format.
Otherwise, the format is invalid for regex, so all distros are picked including fips.
_Note_: In 6.15.z and 6.16.z , RHEL9 is N (newest) in `supportability.yaml`. RHEL10 is only in Stream (6.17)
Example: 
```
@pytest.mark.rhel_ver_match('N-2') # rhel9, 8, and 7  in 6.16 and 6.15
def test_case(rhel_contenthost, target_sat, ...):
```
```
or …
```

[6.15.z] [6.16.z] CP: rhel_ver_match(N-x) Optional Format

---

tests/foreman/api/test_provisioningtemplate.py

The output of the variable rex_snippet has changed. For example:
- Before: `yggdrasild`
- After: `$YGGDRASIL_SERVICE`
The assertion has been updated accordingly to reflect this change.

Updated the assertion to align with the 'rex_snippet' var.

---

conf/robottelo.yaml.template
robottelo/config/validators.py
tests/foreman/ui/test_documentation_links.py

Currently `test_positive_documentation_links` doesn't check the links for unreleased Satellite doc links.
- Update `test_positive_documentation_links` to make it work with stage docs
- SAT-27552

Update test_positive_documentation_links to test stage doc links

---

tests/foreman/ui/test_ansible.py

I extended the existing test case to include the following steps:
1. Create an Ansible variable with a default value and an overridden key.
2. Update the value of the Ansible variable at the host level.
3. After updating, delete the value, ensuring that it reverts to the default value.
Dependent PR: https://github.com/SatelliteQE/airgun/pull/1643

variable value should del after update

---

pytest_fixtures/core/sat_cap_factory.py
tests/foreman/installer/test_installer.py

The current output of `test_satellite_installation` is useless. Because the output is so long, pytest truncates it which hides the relevant error.
As a first step, it does a trivial cleanup for readability. The next commit stops using `len(x) == 0` and instead uses `not x` to assert there is no output. I haven't tested this, but I believe this allows pytest to skip a layer of output and hopefully also provide better output.
The real change is that it asserts the exit code of the installer to be 0 or 2. In practice I'd always expect 2, but 0 is also valid. See https://github.com/theforeman/kafo?tab=readme-ov-file#exit-code for more information. Since foreman-installer 3.8.0 (https://github.com/theforeman/foreman-installer/commit/0d2fb671ea579bf1f44b93dded089c0db159b536) it also displays …

Provide better error output for test_satellite_installation

---

pytest_fixtures/core/xdist.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17083
- Currently, Capsule host in build sanity job gets checked in even when there are test failures. This makes it hard to debug test failures, especially in the case of nightly and snap templatization jobs.
- Preserve Capsule for debugging

[6.16.z] Preserve Capsule host for build sanity failures

---

pytest_fixtures/core/xdist.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17083
- Currently, Capsule host in build sanity job gets checked in even when there are test failures. This makes it hard to debug test failures, especially in the case of nightly and snap templatization jobs.
- Preserve Capsule for debugging

[6.15.z] Preserve Capsule host for build sanity failures

---

pytest_fixtures/core/sat_cap_factory.py
tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17105
The current output of `test_satellite_installation` is useless. Because the output is so long, pytest truncates it which hides the relevant error.
As a first step, it does a trivial cleanup for readability. The next commit stops using `len(x) == 0` and instead uses `not x` to assert there is no output. I haven't tested this, but I believe this allows pytest to skip a layer of output and hopefully also provide better output.
The real change is that it asserts the exit code of the installer to be 0 or 2. In practice I'd always expect 2, but 0 is also valid. See https://github.com/theforeman/kafo?tab=readme-ov-file#exit-code for more information. Since foreman-installer 3.8.0 …

[6.16.z] Provide better error output for test_satellite_installation

---

pytest_fixtures/core/sat_cap_factory.py
tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17105
The current output of `test_satellite_installation` is useless. Because the output is so long, pytest truncates it which hides the relevant error.
As a first step, it does a trivial cleanup for readability. The next commit stops using `len(x) == 0` and instead uses `not x` to assert there is no output. I haven't tested this, but I believe this allows pytest to skip a layer of output and hopefully also provide better output.
The real change is that it asserts the exit code of the installer to be 0 or 2. In practice I'd always expect 2, but 0 is also valid. See https://github.com/theforeman/kafo?tab=readme-ov-file#exit-code for more information. Since foreman-installer 3.8.0 …

[6.15.z] Provide better error output for test_satellite_installation

---

tests/foreman/ui/test_reporttemplates.py

There were multiple outdated Reporting UI tests that did not work correctly with 6.16.
This PR fixes these issues.
```
pytest: tests/foreman/ui/test_reporttemplates.py -k "test_positive_generate_subscriptions_report_json or test_positive_schedule_generation_and_get_mail"
```

Fix outdated 6.16 reporting tests

---

robottelo/host_helpers/cli_factory.py
tests/foreman/ui/test_reporttemplates.py

There were multiple outdated Reporting UI tests that did not work correctly with stream.
This PR fixes these issues.
```
pytest: tests/foreman/ui/test_reporttemplates.py -k "test_positive_schedule_generation_and_get_mail or test_positive_installable_errata_with_user or test_positive_generate_subscriptions_report_json or test_positive_generate_all_installed_packages_report"
```

Reporting test fixes for stream

---

tests/foreman/api/test_subscription.py

- `test_sca_end_to_end` and `test_positive_expired_SCA_cert_handling` tests are failing imported manifest issue.
- **Error:** This subscription management application has already been imported by another owner
- I guess `test_positive_create` test uses mdoule_manifest_org fixture and it is creating issue while importing manifest
Delete `test_positive_create` test, as it uses `module_sca_manifest` fixture and which is used inside any `*_sca_manifest_org fixture` that executed on so many places.
```
collecting ... 2024-12-10 22:29:23 - robottelo.collection - INFO - Processing test items to add testimony token markers
collected 11 items / 8 deselected / 3 selected …
```

delete subscription manifest so it can re imported again

---

tests/foreman/api/test_subscription.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17142
- `test_sca_end_to_end` and `test_positive_expired_SCA_cert_handling` tests are failing imported manifest issue.
- **Error:** This subscription management application has already been imported by another owner
- I guess `test_positive_create` test uses mdoule_manifest_org fixture and it is creating issue while importing manifest
Delete `test_positive_create` test, as it uses `module_sca_manifest` fixture and which is used inside any `*_sca_manifest_org fixture` that executed on so many places.
```
collecting ... 2024-12-10 22:29:23 - robottelo.collection - INFO - Processing test items to add testimony token markers
collected 11 items / 8 …
```

[6.16.z] delete subscription manifest so it can re imported again

---

tests/foreman/destructive/test_ldap_authentication.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17149
null

[6.16.z] Only the second call should raise an exception

---

tests/foreman/api/test_capsulecontent.py

Fix for the issue linked bellow has been backported to `6.16.1`. We already have test coverage for this in `stream` and could have the same in `6.16.z`.
`git cherry-pick <id> && git push 6.16.z`
https://issues.redhat.com/browse/SAT-29702
```
pytest: tests/foreman/api/test_capsulecontent.py -k test_complete_sync_fixes_metadata
```

[6.16.z] Add a test case for metadata repair on capsule complete sync (#16835)

---

.github/CODEOWNERS
robottelo/cli/flatpak_remote.py
robottelo/constants/__init__.py
tests/foreman/cli/test_flatpak.py

Satellite 6.17 introduces support for Flatpak content. We should introduce some automation around.
This PR just adds one test case for CRUD + scan and one test case to verify the scan finds all repos available in the remote index.
https://issues.redhat.com/browse/SAT-28471
```
pytest: tests/foreman/cli/test_flatpak.py
Katello:
katello: 11223
hammer-cli-katello: 971
```

Add Flatpak CLI support and CRUD case

---

requirements.txt

[airgun bumped the selenium dep](https://github.com/SatelliteQE/airgun/commit/d5285d4c56a26aebe21118433f62c285a5001cc2), which updates [websocket-client](https://github.com/SeleniumHQ/selenium/blob/selenium-4.27.1-python/py/pyproject.toml#L35) to a version that's not compatible with the [ancient openshift/kubernetes used by wrapanapi](https://github.com/RedHatQE/wrapanapi/blob/3.6.6/pyproject.toml#L57) (https://github.com/openshift/openshift-restclient-python/blob/release-0.3.4/requirements.txt#L3, https://github.com/kubernetes-client/python/blob/release-3.0/requirements.txt#L9).
as we don't pin wrapanapi, the depsolver tries to find a version that works, and picks one that has azure unpinned (2.7.0!).
this gets us azure 5.0.0, but azure 5.0.0 deprecated the `azure` meta package in favor …

pin wrapnapi to force dependency errors to become more visible

---

tests/foreman/sys/test_fam.py

Fixes happened for 6.16.z and master, but were not backported to 6.15.z, even tho they are applicable
Cherry pick things :)

cherry-picks of FAM test fixes for 6.15.z

---

tests/foreman/sys/test_fam.py

Fixes happened for 6.16.z and master, but were not backported to 6.14.z, even tho they are applicable
Cherry pick things :)

cherry-picks of FAM test fixes for 6.14.z

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17166
[airgun bumped the selenium dep](https://github.com/SatelliteQE/airgun/commit/d5285d4c56a26aebe21118433f62c285a5001cc2), which updates [websocket-client](https://github.com/SeleniumHQ/selenium/blob/selenium-4.27.1-python/py/pyproject.toml#L35) to a version that's not compatible with the [ancient openshift/kubernetes used by wrapanapi](https://github.com/RedHatQE/wrapanapi/blob/3.6.6/pyproject.toml#L57) (https://github.com/openshift/openshift-restclient-python/blob/release-0.3.4/requirements.txt#L3, https://github.com/kubernetes-client/python/blob/release-3.0/requirements.txt#L9).
as we don't pin wrapanapi, the depsolver tries to find a version that works, and picks one that has azure unpinned (2.7.0!).
this gets us …

[6.15.z] pin wrapnapi to force dependency errors to become more visible

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17166
[airgun bumped the selenium dep](https://github.com/SatelliteQE/airgun/commit/d5285d4c56a26aebe21118433f62c285a5001cc2), which updates [websocket-client](https://github.com/SeleniumHQ/selenium/blob/selenium-4.27.1-python/py/pyproject.toml#L35) to a version that's not compatible with the [ancient openshift/kubernetes used by wrapanapi](https://github.com/RedHatQE/wrapanapi/blob/3.6.6/pyproject.toml#L57) (https://github.com/openshift/openshift-restclient-python/blob/release-0.3.4/requirements.txt#L3, https://github.com/kubernetes-client/python/blob/release-3.0/requirements.txt#L9).
as we don't pin wrapanapi, the depsolver tries to find a version that works, and picks one that has azure unpinned (2.7.0!).
this gets us …

[6.16.z] pin wrapnapi to force dependency errors to become more visible

---

tests/foreman/cli/test_activationkey.py
tests/foreman/ui/test_activationkey.py

Two RHEL6 based scenarios found, as rhel-6 is EOL hence removing the test cases
Remove tests from stream, 6.16.z and 6.15.z
N/A

removing scenario, rhel6 with custom product

---

tests/foreman/cli/test_activationkey.py
tests/foreman/ui/test_activationkey.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17167
Two RHEL6 based scenarios found, as rhel-6 is EOL hence removing the test cases
Remove tests from stream, 6.16.z and 6.15.z
N/A

[6.16.z] removing scenario, rhel6 with custom product

---

tests/foreman/cli/test_activationkey.py
tests/foreman/ui/test_activationkey.py

Auto-Cherry-Pick WorkFlow Failure:
Manual CP to 6.15.z
https://github.com/SatelliteQE/robottelo/issues/17174

Failed AutoCP 6.15.z-removing scenario, rhel6 with custom product

---

robottelo/hosts.py
tests/foreman/cli/test_bootstrap_script.py

test_positive_register bootstrap test is failing because the subscription manager is unable to connect to cdn-ubi.redhat.com
- Enable IPv6 rhsm proxy for the host
SAT-30100

Enable IPv6 rhsm proxy for test_positive_register bootstrap test

---

tests/foreman/cli/test_repositories.py

The `test_purge_pulp_tasks` fails with
```
AssertionError: Pulp tasks were unexpectedly purged
assert 25 > 25
```
because `pulp task list` command uses pagination, so it returns only 25 tasks event when there are more tasks to be listed.
The command offers `--limit` option for pagination control. Let's use it.
```
```

Fix pulp tasks purge test case

---

tests/foreman/cli/test_repositories.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17190
The `test_purge_pulp_tasks` fails with
```
AssertionError: Pulp tasks were unexpectedly purged
assert 25 > 25
```
because `pulp task list` command uses pagination, so it returns only 25 tasks event when there are more tasks to be listed.
The command offers `--limit` option for pagination control. Let's use it.
```
```

[6.15.z] Fix pulp tasks purge test case

---

tests/foreman/cli/test_repositories.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17190
The `test_purge_pulp_tasks` fails with
```
AssertionError: Pulp tasks were unexpectedly purged
assert 25 > 25
```
because `pulp task list` command uses pagination, so it returns only 25 tasks event when there are more tasks to be listed.
The command offers `--limit` option for pagination control. Let's use it.
```
```

[6.16.z] Fix pulp tasks purge test case

---

tests/foreman/ui/test_ldap_authentication.py

Test `tests/foreman/ui/test_ldap_authentication.py::test_positive_add_katello_role` fails with the following error message:
```
AssertionError: assert 'givenName sn' in 'Foreman User'
```
The reason is that instead of comparing expected value of the name field, verbatim _names of those fields_ are used instead - `givenName` and `sn` of course aren't names of the user but names of the fields where that info is stored.
Use `user shown name` config field that is meant specifically for this, it specifies the expected display name of the user in config file.
This is consistent with changes in other similar tests as per https://github.com/SatelliteQE/robottelo/pull/16382
Similar failures fixed in https://github.com/SatelliteQE/robottelo/pull/16382

Fix expected user name

---

tests/foreman/ui/test_ldap_authentication.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17161
Test `tests/foreman/ui/test_ldap_authentication.py::test_positive_add_katello_role` fails with the following error message:
```
AssertionError: assert 'givenName sn' in 'Foreman User'
```
The reason is that instead of comparing expected value of the name field, verbatim _names of those fields_ are used instead - `givenName` and `sn` of course aren't names of the user but names of the fields where that info is stored.
Use `user shown name` config field that is meant specifically for this, it specifies the expected display name of the user in config file.
This is consistent with changes in other similar tests as per https://github.com/SatelliteQE/robottelo/pull/16382
Similar failures fixed in …

[6.16.z] Fix expected user name

---

pytest_fixtures/component/satellite_auth.py
tests/foreman/ui/test_ldap_authentication.py

Cherrypick of https://github.com/SatelliteQE/robottelo/pull/17161 and also of https://github.com/SatelliteQE/robottelo/pull/16382 because it hasn't been previously cherrypicked to 6.14.

[6.14] Fix expected user name

---

tests/foreman/ui/test_leapp_client.py

Customer bug #SAT-28216
Automates customer bug #SAT-28216
Airgun support: https://github.com/SatelliteQE/airgun/pull/1677

Test Leapp preupgrade report generate

---

tests/foreman/api/test_provisioning.py

Existing test for bare-metal secure boot provisioning is only for RHEL9 
Parametrize existing test for bare-metal secure boot provisioning for all supported RHEL versions

Parametrize test for baremetal secureboot provisioning

---

tests/foreman/api/test_ansible.py
tests/foreman/api/test_registration.py
tests/foreman/cli/test_ansible.py
tests/foreman/cli/test_registration.py
tests/foreman/cli/test_report.py
tests/foreman/ui/test_ansible.py
tests/foreman/ui/test_registration.py

Fix failing IPv6 ansible and registration tests.
The test is failing because the custom repos are created with download.devel url to download packages which can't be reached over IPv6

Fix IPv6 ansible and registration tests

---

tests/foreman/api/test_docker.py

Few tests from `tests/foreman/api/test_docker.py` are failing due to pending tasks issue in repositories of cv.
**Error:** 
`"errors":["Pending tasks detected in repositories of this content view. Please wait for the tasks: - https://satellite-ip.redhat.com/foreman_tasks/tasks/207e977b-d3df-4daa-94ba-27a7b7cbdc69 before publishing." `
Affected test cases:
```
TestDockerActivationKey::test_positive_add_docker_repo_cv
TestDockerActivationKey::test_positive_remove_docker_repo_cv
TestDockerActivationKey::test_positive_add_docker_repo_ccv
TestDockerActivationKey::test_positive_remove_docker_repo_ccv
```
add wait_for_tasks to wait for resource type  Katello::Repository while repo creating. 
N/A
```
pytest: tests/foreman/api/test_docker.py::TestDockerActivationKey
```

added wait for tasks for repo creation

---

tests/foreman/api/test_docker.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17171
Few tests from `tests/foreman/api/test_docker.py` are failing due to pending tasks issue in repositories of cv.
**Error:** 
`"errors":["Pending tasks detected in repositories of this content view. Please wait for the tasks: - https://satellite-ip.redhat.com/foreman_tasks/tasks/207e977b-d3df-4daa-94ba-27a7b7cbdc69 before publishing." `
Affected test cases:
```
TestDockerActivationKey::test_positive_add_docker_repo_cv
TestDockerActivationKey::test_positive_remove_docker_repo_cv
TestDockerActivationKey::test_positive_add_docker_repo_ccv
TestDockerActivationKey::test_positive_remove_docker_repo_ccv
```
add wait_for_tasks to wait for resource type  Katello::Repository while repo creating. 
N/A
``` …
```

[6.16.z] added wait for tasks for repo creation

---

tests/foreman/cli/test_satellitesync.py

Satellite 6.17 introduces support for Flatpak content.
In #17013 (this PR is based on that) we add basic support and cases for flatpaks.
As per the issue linked bellow we also need to ensure that ISS export and import work for flatpaks the same as for standard container-type repositories.
We already have a test case for mixed content-types export (including container) so I've decided to extend it with a flatpak repo and the import portion (which we needed anyway).
Flatpak repo creation somewhat differs from other repos (it can be created only by mirroring of a _remote-repo_ after a _flatpak-remote_ scans the remote index), but that's handled by the `function_synced_flatpak_repo` fixture. O
Some additional minor fixes:
- removed the extra product for the container-repo (all repos share …

Extend ISS mixed content export case with flatpak and import

---

tests/foreman/ui/test_eol_banner.py

EOL banner takes a long time to show up (half year before EOL), links contained in the banner can become outdated 
Add checks that links work
awaits SAT-29427
needs 
https://github.com/SatelliteQE/airgun/pull/1644

check links on EOL banner

---

pytest_fixtures/component/leapp_client.py
tests/foreman/ui/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16639
Host checkout failing for IPv6 because we are missing parameter "deploy_network_type" while checking out host.
Added parameter "deploy_network_type" while host checkout.

[6.15.z] Add network type option for Host checkout 

---

tests/foreman/api/test_registration.py
tests/foreman/cli/test_fact.py
tests/foreman/cli/test_registration.py
tests/foreman/ui/test_fact.py
tests/foreman/ui/test_registration.py

Missing support for RHEL10 for Registration and Facts
Added support of RHEL10

Add rhel10 support in registration tests

---

tests/foreman/endtoend/test_api_endtoend.py

Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/16914/files
Fixes https://github.com/SatelliteQE/robottelo/issues/16951

[6.15.z] Update API e2e test to use RegistrationCommand entity to register

---

pytest_fixtures/component/http_proxy.py
robottelo/cli/base.py
robottelo/host_helpers/capsule_mixins.py
tests/foreman/api/test_templatesync.py
tests/foreman/cli/test_templatesync.py
tests/foreman/ui/test_templatesync.py

Tests for of SAT-27349.
UI part requires https://github.com/SatelliteQE/airgun/pull/1621
Draft because it contains a workaround for discovered regressions and because the feature hasn't been merged yet.

Test template sync using proxy

---

robottelo/constants/__init__.py
tests/foreman/ui/test_repository.py

The "recommended repos" test case has been failing for a while, blocking us from seeing product bugs. Also some of the recommended repos has changed over a time.
This PR updates and extends the test case. It could be backported with minor changes in the constants to `6.16.z` and `6.15.z`, I would handle the changes in the cherry-picks.
At this time it is expected to fail in stream. It must keep failing until https://github.com/Katello/katello/pull/11205 is baked in stream AND the 6.17 repos are added to match the Satellite version.
https://issues.redhat.com/browse/SAT-29446
https://issues.redhat.com/browse/SAT-29448 
requires https://github.com/SatelliteQE/airgun/pull/1631
```
pytest: tests/foreman/ui/test_repository.py -k recommended_repos
```

Fix and extend the RH recommended repos case

---

robottelo/host_helpers/satellite_mixins.py
tests/upgrades/test_errata.py
tests/upgrades/test_repository.py
tests/upgrades/test_subscription.py

1. We have seen several `post_upgrade` failures for "`rhel_contenthost`-parametrized" upgrade scenario tests where the pre-data could not be fetched from the `scenario_entities` file:
```
failed on setup with "Failed: Invalid test parameter: rhel7. Test data not found."
```
The reason is that the pre-upgrade test names are now suffixed with `-ipv4` so the `scenario_entities` hold items like this:
```
{"tests/upgrades/test_repository.py::TestSimpleContentAccessOnly::test_pre_simple_content_access_only[rhel7-ipv4]": {...}}
```
2. #14111 extended the `ContentInfo.publish_content_view()` method of with the `name` parameter without updating tests in the legacy upgrade scenarios, so now they cry:
```
TypeError: ContentInfo.publish_content_view() missing 1 required positional argument: 'name' …
```

Fix legacy errata upgrade scenario tests

---

robottelo/constants/__init__.py
tests/foreman/api/test_capsulecontent.py
tests/foreman/cli/test_flatpak.py

After 6.17.0 install (or upgrade) the pulpcore flatpak endpoint should be up at the Satellite and/or Capsule and we should verify it.
This PR adds a test case for both.
Needs https://github.com/theforeman/puppet-pulpcore/pull/363 in stream snap.
```
pytest: tests/foreman -k test_flatpak_pulpcore_enpoint
```

Add test cases for pulpcore flatpak endpoint

---

robottelo/hosts.py

The set_infrastructure_set helper function was not actually setting the infrastructure type. After Speaking with Dev and Insights, I have rewritten the function to set these facts properly. This should fix failing tests in RHCloud

Update set_infrastructure _type for RHCloud

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17196
The set_infrastructure_set helper function was not actually setting the infrastructure type. After Speaking with Dev and Insights, I have rewritten the function to set these facts properly. This should fix failing tests in RHCloud

[6.15.z] Update set_infrastructure _type for RHCloud

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17196
The set_infrastructure_set helper function was not actually setting the infrastructure type. After Speaking with Dev and Insights, I have rewritten the function to set these facts properly. This should fix failing tests in RHCloud

[6.14.z] Update set_infrastructure _type for RHCloud

---

conf/rh_cloud.yaml.template
tests/foreman/ui/test_rhc.py

- Satellite RH Cloud tests uses name of `module_rhc_org` as manifest name. This works fine with automation but if someone runs the test manually and has not set `settings.rh_cloud.organization`, a manifest with a random name gets created.
- Add `satqe-rhc-org` prefix to the code that sets random name and update `conf/rh_cloud.yaml.template`.
- SAT-30336

Update rhc tests to use manifest with satqe prefix

---

tests/foreman/cli/test_registration.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/15178
When a host is registered, its Owner is not set to the admin that generated the registration command. It stays set to a hidden API user, Owner is displayed as Anonymous Admin.
The user who actually ran the registration process should be set as owner.
The following automation script is designed to verify that the host is registered correctly and that it is assigned the expected owner name as specified.

[6.15.z] verify host owner name after host registration

---

tests/foreman/api/test_classparameters.py

When we provide a string value as input in YAML, it is accepting the value. Ideally, it should not accept an invalid value. The value provided in the YAML is incorrect and should be rejected.
Updated the value for yaml parameter to ensure it works for the negative test case.

Correction in yaml value

---

tests/foreman/api/test_classparameters.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17229
When we provide a string value as input in YAML, it is accepting the value. Ideally, it should not accept an invalid value. The value provided in the YAML is incorrect and should be rejected.
Updated the value for yaml parameter to ensure it works for the negative test case.

[6.16.z] Correction in yaml value

---

tests/foreman/api/test_computeresource_gce.py

VPC network created in Google cloud causing tests for GCE to fail. 
Skipping the test until we fix the issue either on automation end or on Google Cloud.

Skip GCE test

---

conf/rh_cloud.yaml.template
tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17264
- Satellite RH Cloud tests uses name of `module_rhc_org` as manifest name. This works fine with automation but if someone runs the test manually and has not set `settings.rh_cloud.organization`, a manifest with a random name gets created.
- Add `satqe-rhc-org` prefix to the code that sets random name and update `conf/rh_cloud.yaml.template`.
- SAT-30336

[6.16.z] Update rhc tests to use manifest with satqe prefix

---

conf/rh_cloud.yaml.template
tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17264
- Satellite RH Cloud tests uses name of `module_rhc_org` as manifest name. This works fine with automation but if someone runs the test manually and has not set `settings.rh_cloud.organization`, a manifest with a random name gets created.
- Add `satqe-rhc-org` prefix to the code that sets random name and update `conf/rh_cloud.yaml.template`.
- SAT-30336

[6.13.z] Update rhc tests to use manifest with satqe prefix

---

conf/rh_cloud.yaml.template
tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17264
- Satellite RH Cloud tests uses name of `module_rhc_org` as manifest name. This works fine with automation but if someone runs the test manually and has not set `settings.rh_cloud.organization`, a manifest with a random name gets created.
- Add `satqe-rhc-org` prefix to the code that sets random name and update `conf/rh_cloud.yaml.template`.
- SAT-30336

[6.15.z] Update rhc tests to use manifest with satqe prefix

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17196
The set_infrastructure_set helper function was not actually setting the infrastructure type. After Speaking with Dev and Insights, I have rewritten the function to set these facts properly. This should fix failing tests in RHCloud

[6.16.z] Update set_infrastructure _type for RHCloud

---

tests/foreman/cli/test_bootdisk.py

Adding test for subnet disk image download - SAT-23549
fixes: https://github.com/SatelliteQE/robottelo/issues/17226

[6.14.z] Add test for subnet disk image download 

---

pytest_fixtures/component/provision_pxe.py
pytest_fixtures/component/provision_vmware.py
tests/foreman/api/test_computeresource_libvirt.py
tests/foreman/cli/test_computeresource_libvirt.py
tests/foreman/ui/test_computeresource_libvirt.py

Missing test coverage for new feature of Libvirt UEFI and secureboot provisioning
Add and update existing tests to include Libvirt UEFI and secureboot provisioning
https://issues.redhat.com/browse/SAT-25808

Add tests for Libvirt secureboot provisioning

---

tests/foreman/api/test_computeresource_gce.py

Failed auto-cherrypick https://github.com/SatelliteQE/robottelo/issues/17277 

[6.15.z cherrypick]Skip GCE test

---

tests/foreman/api/test_computeresource_gce.py

Failed auto-cherrypick https://github.com/SatelliteQE/robottelo/issues/17278 

[6.16.z cherrypick]Skip GCE test

---

tests/foreman/api/test_computeresource_gce.py

Failed auto-cherrypick https://github.com/SatelliteQE/robottelo/issues/17279

[6.14.z cherrypick]Skip GCE test

---

tests/foreman/ui/test_registration.py

The host is successfully registering using the label/name instead of the ID, and this applies to the following parameters:
- Organization
- Location
- Host group
- Operating System

updated curl to register host with name param instead id

---

conf/ansible.yaml.template
pytest_fixtures/component/provision_pxe.py
tests/foreman/cli/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16555
Missing test coverage for ansible-tower/AAP integration with Satellite
Add tests for ansible-tower/AAP integration with Satellite

[6.16.z] Add tests for ansible-tower/AAP integration with Satellite

---

tests/foreman/api/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17296
Reboot functionality is not working for the discovery host and is throwing an error. Therefore, the reboot step is being skipped for now until a fix is available.

[6.16.z] reboot not working for discovery host, added workaround

---

tests/foreman/ui/test_fact.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17308
Assertion failing on host fqdn while fetching the fact.
Updated the fact name .

[6.16.z] Update fact name for fetching fqdn fact

---

tests/foreman/ui/test_fact.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17308
Assertion failing on host fqdn while fetching the fact.
Updated the fact name .

[6.14.z] Update fact name for fetching fqdn fact

---

tests/foreman/ui/test_fact.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17308
Assertion failing on host fqdn while fetching the fact.
Updated the fact name .

[6.15.z] Update fact name for fetching fqdn fact

---

pytest_fixtures/component/satellite_auth.py
tests/foreman/destructive/test_ldapauthsource.py

RHSSO needs some packages shipped by RHEL that we expect to change, we should interop test it. The test will probably never run in older z-streams without it. The test is destructive though, it runs an installer. Debate on allowing destructive tests in PIT is in the corresponding PR in our config repo.

Mark one RHSSO test for PIT server

---

pytest_fixtures/component/satellite_auth.py
tests/foreman/destructive/test_ldapauthsource.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17204
RHSSO needs some packages shipped by RHEL that we expect to change, we should interop test it. The test will probably never run in older z-streams without it. The test is destructive though, it runs an installer. Debate on allowing destructive tests in PIT is in the corresponding PR in our config repo.

[6.16.z] Mark one RHSSO test for PIT server

---

pytest_fixtures/component/satellite_auth.py
tests/foreman/destructive/test_ldapauthsource.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17204
RHSSO needs some packages shipped by RHEL that we expect to change, we should interop test it. The test will probably never run in older z-streams without it. The test is destructive though, it runs an installer. Debate on allowing destructive tests in PIT is in the corresponding PR in our config repo.

[6.15.z] Mark one RHSSO test for PIT server

---

tests/foreman/ui/test_eol_banner.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16990
EOL banner takes a long time to show up (half year before EOL), links contained in the banner can become outdated 
Add checks that links work
awaits SAT-29427
needs 
https://github.com/SatelliteQE/airgun/pull/1644

[6.16.z] check links on EOL banner

---

tests/foreman/installer/test_installer.py

Package _foreman-redis_ is now installed in earlier stage as a requirement, not by satellite-installer. It is installed even if different cache provider is set, so we have to remove the test step.

Fix rails cache store test in installer

---

tests/foreman/ui/test_computeresource_vmware.py

The VMware test is failing due to a recent change of secure boot in stream. Radio button `EFI` has been changed to `UEFI`
Update the test to fix above issue

Fix VMware compute profile test

---

robottelo/utils/issue_handlers/__init__.py
tests/foreman/api/test_convert2rhel.py

Auto-cherrypick failed in https://github.com/SatelliteQE/robottelo/issues/17320 
Manully cherrypicked.

[6.16.z] Update target os name due to RHELC-1737

---

tests/foreman/api/test_reporttemplates.py

Some API reporting tests did not work in the stream due to multi-CV changes.
The main goal is to get rid of `Environment ID and content view ID must be provided together` errors which appear due to outdated test composition.
Let the `setup_org_for_a_custom_repo` function create and promote CV and create AK
```
pytest: tests/foreman/api/test_reporttemplates.py -k "test_positive_applied_errata or test_positive_applied_errata_report_with_invalid_errata or test_positive_applied_errata_by_search"
```

Fix long failing reporting API tests

---

tests/foreman/api/test_computeresource_vmware.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/cli/test_discoveredhost.py

The Lambda timeout was insufficient to fetch the discovered host's MAC address.Added retries to allow additional time for execution, ensuring better handling of delays and transient issues.

Added retries ensuring better handling of delays

---

robottelo/hosts.py

Tests using enable_ipv6_dnf_and_rhsm_proxy for RHEL 7 content host fails ar it configures proxy for dnf.conf whereas RHEL7 recognizes yum.conf
Update the function to configure proxy for yum.conf

Fix failing IPv6 puppet tests for RHEL7 host

---

tests/foreman/api/test_computeresource_vmware.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/cli/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17297
The Lambda timeout was insufficient to fetch the discovered host's MAC address.Added retries to allow additional time for execution, ensuring better handling of delays and transient issues.

[6.16.z] Added retries ensuring better handling of delays

---

pytest_fixtures/core/contenthosts.py
tests/foreman/api/test_capsulecontent.py
tests/foreman/cli/test_flatpak.py

In Satellite 6.17 we are going to support full path for host setup and flatpak app installation on a content host, including REX templates to make it more user-friendly. We should have an E2E test case to cover all of that too.
This PR adds such a test case (and fixes two typos).
https://issues.redhat.com/browse/SAT-28557
https://issues.redhat.com/browse/SAT-4420
https://github.com/Katello/katello/pull/11223 (in snap)
https://github.com/Katello/hammer-cli-katello/pull/971 (in snap)
https://github.com/Katello/katello/pull/11264
```
pytest: tests/foreman/cli/test_flatpak.py -k test_sync_consume_flatpak_repo_via_library
Katello:
katello: 11264
```

Add e2e test case for flatpak

---

tests/foreman/api/test_discoveredhost.py
tests/foreman/cli/test_discoveredhost.py

The Lambda timeout was insufficient to fetch the discovered host's MAC address.Added retries to allow additional time for execution, ensuring better handling of delays and transient issues.
Fixes - https://github.com/SatelliteQE/robottelo/issues/17336

[cp 6.15] Extend search time for discoveryhost mac6.15

---

tests/foreman/api/test_discoveredhost.py
tests/foreman/cli/test_discoveredhost.py

The Lambda timeout was insufficient to fetch the discovered host's MAC address.Added retries to allow additional time for execution, ensuring better handling of delays and transient issues.
Fixes - https://github.com/SatelliteQE/robottelo/issues/17334

[cp 6.14] Added retries ensuring better handling of delays

---

tests/foreman/cli/test_activationkey.py

Remove all content view environments from the activation key
Add support in existiting test case and update name
test_positive_multi_cv_info => test_positive_multi_cv_info_and_remove_all_cv_envs
No
```
pytest: tests/foreman/cli/test_activationkey.py -k 'test_positive_multi_cv_info_and_remove_all_cv_envs'
```

add new scenario - remove all cv envs from ak

---

pytest_fixtures/component/provisioning_template.py

Provisioning template tests are failing with `failed on setup with "KeyError: 'rhel10_bos'"`
Right now we have RHEL10 public beta repos only
Updating the fixture to handle the key error

Fix key error for RHEL 10 provisioning template tests

---

tests/foreman/ui/test_contentview.py

Test supporting this Customer Issue: https://issues.redhat.com/browse/SAT-28271
Adds a test validating this issue+
Requires Airgun PR: https://github.com/SatelliteQE/airgun/pull/1653

Add test checking needs publish banner on cv index page

---

robottelo/hosts.py

It looks like the host's `subscribed()` property can potentially return wrong value from sys-purpose status.
```
System Purpose Status: Unknown
```
**All credit goes to @jeremylenz who noticed this!**
We should check the `Overall Status` specifically.
```
pytest: tests/foreman/cli/test_host.py -k test_positive_list_by_last_checkin
```

Narrow down host's subscription status check

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17378
It looks like the host's `subscribed()` property can potentially return wrong value from sys-purpose status.
```
System Purpose Status: Unknown
```
**All credit goes to @jeremylenz who noticed this!**
We should check the `Overall Status` specifically.
```
pytest: tests/foreman/cli/test_host.py -k test_positive_list_by_last_checkin
```

[6.16.z] Narrow down host's subscription status check

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17378
It looks like the host's `subscribed()` property can potentially return wrong value from sys-purpose status.
```
System Purpose Status: Unknown
```
**All credit goes to @jeremylenz who noticed this!**
We should check the `Overall Status` specifically.
```
pytest: tests/foreman/cli/test_host.py -k test_positive_list_by_last_checkin
```

[6.14.z] Narrow down host's subscription status check

---

robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17378
It looks like the host's `subscribed()` property can potentially return wrong value from sys-purpose status.
```
System Purpose Status: Unknown
```
**All credit goes to @jeremylenz who noticed this!**
We should check the `Overall Status` specifically.
```
pytest: tests/foreman/cli/test_host.py -k test_positive_list_by_last_checkin
```

[6.15.z] Narrow down host's subscription status check

---

tests/foreman/installer/test_installer.py

Prevent false negative (There is a bug but test does not detect it) of installer by checking its return code.

Prevent satellite-installer false negative

---

tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17384
Prevent false negative (There is a bug but test does not detect it) of installer by checking its return code.

[6.16.z] Prevent satellite-installer false negative

---

tests/foreman/api/test_remoteexecution.py
tests/foreman/cli/test_remoteexecution.py
tests/foreman/destructive/test_registration.py

SAT-27476
template changes and a different service name on rhel 10 and 9.6+
this pr
awaits https://github.com/theforeman/foreman/pull/10340

preparation for new yggdrasil

---

tests/foreman/cli/test_remoteexecution.py

Adding some negative assertions for rex effective user tests on ssh and pull provider

negative assertions for rex effective user tests

---

conftest.py
pytest_fixtures/component/permissions.py
tests/foreman/api/test_permission.py
tests/foreman/ui/test_host.py

Some permission comparison happens also outside of the test_permission module. With https://github.com/SatelliteQE/robottelo/pull/16962 not all perms are sat specific, which caused failures in host module as the context-based permission filtering was not done there
moving the permission filtering part to a separate fixture to make it reusable across modules

fixture to get expected permissions

---

tests/foreman/api/test_capsulecontent.py

The `test_positive_read_with_non_admin_user` fails when run before the Default org/loc is assigned to the Capsule (search won't find it in that case).
```
tests/foreman/api/test_capsulecontent.py:1983: in test_positive_read_with_non_admin_user
assert len(res) >= 2, 'Expected at least one internal and one or more external Capsule(s).'
E   AssertionError: Expected at least one internal and one or more external Capsule(s).
E   assert 1 >= 2
```
Assign it to defaults before we try to search.
```
pytest: tests/foreman/api/test_capsulecontent.py -k test_positive_read_with_non_admin_user
```

Fix Capsule test case for non-admin user

---

tests/foreman/api/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17422
The `test_positive_read_with_non_admin_user` fails when run before the Default org/loc is assigned to the Capsule (search won't find it in that case).
```
tests/foreman/api/test_capsulecontent.py:1983: in test_positive_read_with_non_admin_user
assert len(res) >= 2, 'Expected at least one internal and one or more external Capsule(s).'
E   AssertionError: Expected at least one internal and one or more external Capsule(s).
E   assert 1 >= 2
```
Assign it to defaults before we try to search.
```
pytest: tests/foreman/api/test_capsulecontent.py -k test_positive_read_with_non_admin_user
```

[6.16.z] Fix Capsule test case for non-admin user

---

tests/foreman/api/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17422
The `test_positive_read_with_non_admin_user` fails when run before the Default org/loc is assigned to the Capsule (search won't find it in that case).
```
tests/foreman/api/test_capsulecontent.py:1983: in test_positive_read_with_non_admin_user
assert len(res) >= 2, 'Expected at least one internal and one or more external Capsule(s).'
E   AssertionError: Expected at least one internal and one or more external Capsule(s).
E   assert 1 >= 2
```
Assign it to defaults before we try to search.
```
pytest: tests/foreman/api/test_capsulecontent.py -k test_positive_read_with_non_admin_user
```

[6.15.z] Fix Capsule test case for non-admin user

---

robottelo/constants/__init__.py
tests/foreman/ui/test_package.py

Upgrade test was failing due to unavailability of `Red Hat Satellite Capsule 6.16 for RHEL 7 Server RPMs x86_64` repository, as Satellite is running on RHEL8 & RHEL9, no RHSC RHEL7 repo present in reposet
Update test case and pass rhsc rhel9 details to fetch correct details.
No
```
pytest: tests/foreman/ui/test_package.py -k 'test_positive_rh_repo_search_and_check_file_list'
```

update rh satellite capsule version to rhel9 from rhel7

---

tests/foreman/ui/test_sync.py

There is a z-stream bug which needs to be automated, see the issue bellow for details.
**TLDR:** We need to verify the functionality of the _Active only_ check-box on the _Sync Status_ page.
This PR adds such UI test case.
It needs [some Airgun changes](https://github.com/SatelliteQE/airgun/pull/1708) too.
https://issues.redhat.com/browse/SAT-30291
```
pytest: tests/foreman/ui/test_sync.py -k test_sync_active_only
airgun: 1708
```

Add a case for active_only box on the sync_status page

---

conftest.py
pytest_fixtures/component/permissions.py
tests/foreman/api/test_permission.py
tests/foreman/ui/test_host.py

closes https://github.com/SatelliteQE/robottelo/issues/17416

[6.14] fixture to get expected permissions

---

conftest.py
pytest_fixtures/component/permissions.py
tests/foreman/api/test_permission.py
tests/foreman/ui/test_host.py

manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/17412
closes #17418

[6.15] fixture to get expected permissions

---

robottelo/constants/__init__.py
tests/foreman/longrun/test_oscap.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17419
The "PCI-DSS v4.0 Control Baseline for Red Hat Enterprise Linux 9" scap profile contains the version number in its title, once it is updated, cause test failure with a need of a constant update
Changing from "PCI-DSS v4.0 Control Baseline for Red Hat Enterprise Linux 9" to "Protection Profile for General Purpose Operating Systems", both are present in rhel9 default content.

[6.16.z] more future-proof scap profile selected

---

conftest.py
pytest_fixtures/component/global_params.py
pytest_fixtures/component/settings.py
tests/foreman/cli/test_remoteexecution.py

mostly to cover SAT-28443, but also to check global params usage
~~note: It turned out the scenario needs global params and not global settings, but since I already wrote the  multi_setting_update fixture, I left it there for potential future use 
also stream has hickups with AKs, so holding of prt for now~~
update: I added another test, so both global parameters and global settings are used, but the glob settings version is blocked by SAT-30443
SAT-28443

test rex using values from global parameters

---

tests/foreman/ui/test_sync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17413
There is a z-stream bug which needs to be automated, see the issue bellow for details.
**TLDR:** We need to verify the functionality of the _Active only_ check-box on the _Sync Status_ page.
This PR adds such UI test case.
It needs [some Airgun changes](https://github.com/SatelliteQE/airgun/pull/1708) too.
https://issues.redhat.com/browse/SAT-30291
```
pytest: tests/foreman/ui/test_sync.py -k test_sync_active_only
airgun: 1708
```

[6.16.z] Add a case for active_only box on the sync_status page

---

robottelo/constants/__init__.py
robottelo/host_helpers/cli_factory.py
robottelo/hosts.py
tests/foreman/ui/test_package.py

rhsc7 repo is removed from constants.py as it is no longer supported in [PR](https://github.com/SatelliteQE/robottelo/pull/17421) but missed removing its check from code.
Removed the check for rhsc7 and added for rhsc9.
https://github.com/SatelliteQE/robottelo/pull/17421

Remove rhsc7 check from robottelo

---

robottelo/host_helpers/cli_factory.py
robottelo/hosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17443
rhsc7 repo is removed from constants.py as it is no longer supported in [PR](https://github.com/SatelliteQE/robottelo/pull/17421) but missed removing its check from code.
Removed the check for rhsc7 and added for rhsc9.
https://github.com/SatelliteQE/robottelo/pull/17421

[6.16.z] Remove rhsc7 check from robottelo

---

.github/workflows/auto_branching.yml
.github/workflows/pull_request.yml

Python 3.13 was released on October 7, 2024, and we're not covering this in the PR checks in GHA yet
Add Python 3.13 for PR checks in GHA

Add Python 3.13 for PR checks in GHA

---

pytest_fixtures/component/provisioning_template.py

The support for `rhel10_bos_beta` was not added, which caused the test to fail. Update the code to include a condition in the if statement that handles `rhel10_bos_beta`, ensuring the data is fetched correctly for `rhel10` so the test can run successfully.

Updated the fixture for rhel_ver to correctly fetch the appropriate kickstart repository

---

tests/foreman/api/test_provisioningtemplate.py

Provisioning Template test was failing due to incorrect comparison for RHEL10.
Fixed the test.

Fix ProvisioningTemplate test for RHEL10

---

tests/foreman/api/test_ansible.py
tests/foreman/cli/test_ansible.py

ansible-galaxy is unreachable from IPv6 sat
Fix ansible tests by using proxy for connecting to ansible-galaxy

Fix ansible tests by using proxy for connecting to ansible-galaxy

---

tests/foreman/cli/test_remoteexecution.py

closes https://github.com/SatelliteQE/robottelo/issues/17477

missing customerscenario tag for rex

---

tests/foreman/cli/test_host.py

adding blocked-by for negative host test

---

tests/foreman/cli/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17481
Skipping on a reported Jira

[6.15.z] adding blocked-by for negative host test

---

tests/foreman/cli/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17481
Skipping on a reported Jira

[6.14.z] adding blocked-by for negative host test

---

tests/foreman/cli/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17481
Skipping on a reported Jira

[6.16.z] adding blocked-by for negative host test

---

pytest_fixtures/component/provision_pxe.py
tests/foreman/api/test_computeresource_vmware.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_provisioning.py
tests/foreman/api/test_provisioning_puppet.py
tests/foreman/cli/test_ansible.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/ui/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17492
`_broker_facts` is used to fetch the host-specific facts in broker v0.6.x, and we're still using `_broker_args` 
Use _broker_facts instead of _broker_args for provisioning tests
MR: satlab-tower#1237

[6.16.z] Use _broker_facts instead of _broker_args for provisioning tests

---

pytest_fixtures/component/provision_pxe.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_provisioning.py
tests/foreman/api/test_provisioning_puppet.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/ui/test_discoveredhost.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17492
_broker_facts is used to fetch the host-specific facts in broker v0.6.x, and we're still using _broker_args
Use _broker_facts instead of _broker_args for provisioning tests
MR: satlab-tower#1237

[6.15.z] Use _broker_facts instead of _broker_args for provisioning tests

---

tests/foreman/ui/test_location.py
tests/foreman/ui/test_organization.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17437
SAT-25386 won't be fixed, but its still valuable that the user appears under the org/loc context even if that org/loc isn't written to its params

[6.16.z] org/loc create with all users tests adjusted

---

tests/foreman/ui/test_location.py
tests/foreman/ui/test_organization.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17437
SAT-25386 won't be fixed, but its still valuable that the user appears under the org/loc context even if that org/loc isn't written to its params

[6.15.z] org/loc create with all users tests adjusted

---

tests/foreman/ui/test_location.py
tests/foreman/ui/test_organization.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17437
SAT-25386 won't be fixed, but its still valuable that the user appears under the org/loc context even if that org/loc isn't written to its params

[6.14.z] org/loc create with all users tests adjusted

---

robottelo/exceptions.py
robottelo/host_helpers/api_factory.py

create_role_permissions factory function started to fail as a side-effect of https://github.com/SatelliteQE/robottelo/pull/16962 (I'll be posting a fix in a separate PR). This uncovered that satellite.api.APIResponseError is no longer around (not sure how long)
creating our own error class

non existent APIResponseError

---

pytest_fixtures/component/provision_pxe.py

_broker_args for target_vm_firmware fact was replaced with _broker_facts mistakenly in PR: https://github.com/SatelliteQE/robottelo/pull/17492
Fix _broker_args for target_vm_firmware fact (Already fixed in the cherrypick PRs)

Fix _broker_args for target_vm_firmware fact

---

tests/foreman/cli/test_activationkey.py

Some CLI AK tests did not work in the stream due to multi-CV changes.
The main goal is to get rid of Environment ID and content view ID.
Also some outdated asserts are fixed.
Mostly using module_promoted_cv fixture helps.
SAT-28579
```
pytest: tests/foreman/cli/test_activationkey.py -k "test_positive_create_with_default_lce_by_id or test_positive_create_with_non_default_lce or test_positive_create_with_default_lce_by_name or test_positive_create_with_cv or test_positive_delete_with_lce or test_positive_update_lce or test_positive_remove_host_collection_by_id or test_positive_remove_host_collection_by_name or test_positive_update_autoattach_toggle"
```

Fix long failing AK CLI tests
