- robottelo/exceptions.py
- robottelo/host_helpers/api_factory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17406
create_role_permissions factory function started to fail as a side-effect of https://github.com/SatelliteQE/robottelo/pull/16962 (I'll be posting a fix in a separate PR). This uncovered that satellite.api.APIResponseError is no longer around (not sure how long)
creating our own error class
> [6.16.z] non existent APIResponseError

- robottelo/exceptions.py
- robottelo/host_helpers/api_factory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17406
create_role_permissions factory function started to fail as a side-effect of https://github.com/SatelliteQE/robottelo/pull/16962 (I'll be posting a fix in a separate PR). This uncovered that satellite.api.APIResponseError is no longer around (not sure how long)
creating our own error class
> [6.14.z] non existent APIResponseError

- tests/foreman/cli/test_domain.py
Change in case in error message causes test failure 
this PR
> less fragile string comparison in negative domain test

- tests/foreman/cli/test_domain.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17511
Change in case in error message causes test failure 
this PR
> [6.15.z] less fragile string comparison in negative domain test

- tests/foreman/cli/test_domain.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17511
Change in case in error message causes test failure 
this PR
> [6.14.z] less fragile string comparison in negative domain test

- conf/rhbk.yaml.template
- pytest_fixtures/component/satellite_auth.py
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- robottelo/hosts.py
- tests/foreman/api/test_templatesync.py
- tests/foreman/cli/test_templatesync.py
- tests/foreman/destructive/test_ldap_authentication.py
- tests/foreman/destructive/test_ldapauthsource.py
- tests/foreman/ui/test_templatesync.py
Make changes so RHSSO tests become parametrized and work for both RHSSO and RHBK, limit TemplateSync tests
> RHBK support

- tests/foreman/api/test_ansible.py
- tests/foreman/cli/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17467
ansible-galaxy is unreachable from IPv6 sat
Fix ansible tests by using proxy for connecting to ansible-galaxy
> [6.16.z] Fix ansible tests by using proxy for connecting to ansible-galaxy

- pytest_fixtures/component/satellite_auth.py
- robottelo/config/validators.py
- tests/foreman/destructive/test_ldapauthsource.py
6.14.z cherrypick of https://github.com/SatelliteQE/robottelo/pull/17204
Note that I've had to add validator:
```
Validator('robottelo.rhel_source', default='ga', is_in=['ga', 'internal']),
```
> [6.14] Mark one RHSSO test for PIT server

- tests/foreman/api/test_convert2rhel.py
We missed adding related issue in convert2rhel tests in https://github.com/SatelliteQE/robottelo/pull/17143
Add issue SAT-26076 to convert2rhel tests
> Add issue SAT-26076 to convert2rhel tests

- tests/foreman/ui/test_activationkey.py
Since 6.17 Activation keys create and update ops need both - CV and LCE, or none of them.
This new reality broke a couple of tests.
This PR fixes UI tests in activationkey.py
SAT-28577
> [Pheonix Subs] Fix AK creation in ui/test_activationkey.py

- robottelo/constants/__init__.py
- tests/foreman/longrun/test_oscap.py
needs changes in conf/repos.yml
> adjusting oscap tests for rhel10

- .github/workflows/pull_request.yml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17522
(cherry picked from commit e2d0259660c64faeef6c4206c38c8a7f846da3c8)
Cherrypick failed for https://github.com/SatelliteQE/robottelo/pull/17405 because of auto-branching GHA changes 
Remove auto-branching GHA changes , and cherrypick only Py3.13 related changes
> [6.14.z] Add Python 3.13 for PR checks in GHA

- .github/workflows/pull_request.yml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17522
(cherry picked from commit e2d0259660c64faeef6c4206c38c8a7f846da3c8)
Cherrypick failed for https://github.com/SatelliteQE/robottelo/pull/17405 because of auto-branching GHA changes 
Remove auto-branching GHA changes , and cherrypick only Py3.13 related changes
> [6.15.z] Add Python 3.13 for PR checks in GHA

- tests/foreman/ui/test_user.py
Add support for Invalidate JWT feature : SAT-27385
Added support for it.
https://github.com/SatelliteQE/airgun/pull/1721
> Add support for invalidating users JWTs

- tests/foreman/api/test_ansible.py
**Problem -** 
When creating another user with a specific role and adding resources in the filter with the 'view_facts' permission, an error occurred ('PG::ForeignKeyViolation: ERROR:  update or delete on table "hosts" violates foreign key constraint "fact_values_host_id_fk" on table "fact_values"') during the teardown process while deleting the host. This happened because a user with only view permissions existed for the host and making it impossible to update or delete the user associated with the fact.
**Solution -**
To prevent this error, the user was removed before the teardown process.
> remove user to prevent ForeignKeyViolation

- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/cli/test_flatpak.py
Flatpak REX templates names have been changed in https://github.com/Katello/katello/pull/11297 and https://github.com/Katello/katello/pull/11300, so we need to update them too.
This PR.
https://issues.redhat.com/browse/SAT-30815
```
pytest: tests/foreman/cli/test_flatpak.py -k test_sync_consume_flatpak_repo_via_library
Katello:
katello: 11300
```
> Update flatpak REX templates names

- pytest_fixtures/component/provision_vmware.py
- tests/foreman/api/test_computeresource_vmware.py
- tests/foreman/cli/test_computeresource_vmware.py
- tests/foreman/ui/test_computeresource_vmware.py
Missing test coverage for new feature of VMware secureboot provisioning
Update existing tests to include VMware UEFI secureboot provisioning
> Add tests for VMware secureboot provisioning

- tests/foreman/ui/test_computeresource.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17442
null
> [6.16.z] adding blocked-by in RHV tests for SAT-30627

- tests/foreman/ui/test_computeresource.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17442
null
> [6.15.z] adding blocked-by in RHV tests for SAT-30627

- tests/foreman/ui/test_computeresource.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17442
null
> [6.14.z] adding blocked-by in RHV tests for SAT-30627

- conf/rhbk.yaml.template
- pytest_fixtures/component/satellite_auth.py
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- robottelo/hosts.py
- tests/foreman/destructive/test_ldap_authentication.py
- tests/foreman/destructive/test_ldapauthsource.py
Make changes so RHSSO tests become parametrized and work for both RHSSO and RHBK
Manual cherry pick.
> [6.16] RHBK support (#17338)

- tests/foreman/destructive/test_fm_upgrade.py
- test_negative_ipv6_update_check is failing because of change in assertion message.
- Update assertion
- SAT-30972
- SAT-30154
> Fix test_negative_ipv6_update_check

- tests/foreman/cli/test_host.py
Test for re-registering a host once consumer certs are removed 
Customer Case for SAT-27875
> [Customer Case]Reregister Host with removed consumer certs

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17552
Test for re-registering a host once consumer certs are removed 
Customer Case for SAT-27875
> [6.16.z] [Customer Case]Reregister Host with removed consumer certs

- tests/foreman/cli/test_remoteexecution.py
Strange error needs a bit of investigation (filed SAT-30898), adding some skip to prevent unnecessary failures while that happens
> assertion skip for SAT-30898

- .github/workflows/auto_cherry_pick_merge.yaml
- .github/workflows/dependency_merge.yml
- requirements-optional.txt
Fixing Failed-AutoCherryPick's for 6.15.z
> [6.15.z] Sync requirements with master branch

- .pre-commit-config.yaml
- requirements-optional.txt
- requirements.txt
Fixing Failed-AutoCherryPick's for 6.16.z
> [6.16.z] Sync requirements with master branch

- tests/foreman/ui/test_registration.py
The global registration method of registration started behaving oddly. The entire process completes but the Host remains in build mode
`Automation`: The host has been successfully registered and is no longer in build mode. Additionally, the facts for the host have been processed
> host should successfully reg with setup_insights=true

- tests/foreman/cli/test_ansible.py
When a non-admin user is created with only an organization, and we set Satellite to a specific organization the host registers successfully but does not appears on Satellite. 
To resolve this issue, a non-admin user was created with both an organization and a default location. This ensures that when the host is registered with the user, it remains visible. Additionally, when we select only the organization in Satellite, the host becomes visible, allowing it to identify the proxy ID and execute the Ansible sync role. This fix prevents post-upgrade failure.
> Add a default location to the non-admin user to support Ansible role synchronization.

- tests/foreman/cli/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17556
When a non-admin user is created with only an organization, and we set Satellite to a specific organization the host registers successfully but does not appears on Satellite. 
To resolve this issue, a non-admin user was created with both an organization and a default location. This ensures that when the host is registered with the user, it remains visible. Additionally, when we select only the organization in Satellite, the host becomes visible, allowing it to identify the proxy ID and execute the Ansible sync role. This fix prevents post-upgrade failure.
> [6.14.z] Add a default location to the non-admin user to support Ansible role synchronization.

- tests/foreman/cli/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17556
When a non-admin user is created with only an organization, and we set Satellite to a specific organization the host registers successfully but does not appears on Satellite. 
To resolve this issue, a non-admin user was created with both an organization and a default location. This ensures that when the host is registered with the user, it remains visible. Additionally, when we select only the organization in Satellite, the host becomes visible, allowing it to identify the proxy ID and execute the Ansible sync role. This fix prevents post-upgrade failure.
> [6.15.z] Add a default location to the non-admin user to support Ansible role synchronization.

- robottelo/constants/__init__.py
- tests/foreman/cli/test_flatpak.py
New `content_type` field has been added to the container manifests and container manifests list so that users can differentiate between flatpaks and other container images. We should check the field is set properly for the flatpak manifests.
This PR extends `test_sync_consume_flatpak_repo_via_library` with this assertion.
Apart from that it also leverages the `function_flatpak_remote` fixture.
https://issues.redhat.com/browse/SAT-21691
```
pytest: tests/foreman/cli/test_flatpak.py -k 'test_scan_flatpak_remote or test_flatpak_pulpcore_endpoint or test_sync_consume_flatpak_repo_via_library'
Katello:
katello: 11300
```
> Verify the content type of flatpak manifests

- pytest_fixtures/component/provision_pxe.py
- tests/foreman/api/test_discoveredhost.py
- tests/foreman/api/test_provisioning.py
- tests/foreman/api/test_provisioning_puppet.py
- tests/foreman/cli/test_ansible.py
- tests/foreman/cli/test_discoveredhost.py
- tests/foreman/ui/test_discoveredhost.py
Provisioning tests are failing with `AttributeError: 'ContentHost' object has no attribute '_broker_facts'. Did you mean: '_broker_args'?` 
Fix the test
> Fix provisioning tests

- pytest_fixtures/component/provision_pxe.py
- tests/foreman/api/test_discoveredhost.py
- tests/foreman/api/test_provisioning.py
- tests/foreman/api/test_provisioning_puppet.py
- tests/foreman/cli/test_ansible.py
- tests/foreman/cli/test_discoveredhost.py
- tests/foreman/ui/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17571
Provisioning tests are failing with `AttributeError: 'ContentHost' object has no attribute '_broker_facts'. Did you mean: '_broker_args'?` 
Fix the test
> [6.16.z] Fix provisioning tests

- robottelo/hosts.py
- tests/foreman/cli/test_ansible.py
- tests/foreman/ui/test_ansible.py
In SAT-30807, "Ansible Collection - Install from Galaxy" job times out when run on IPv6 host
Add workaround for SAT-30807 to use proxy for connecting to ansible-galaxy
> Add workaround for SAT-30807 to use proxy for connecting to ansible-galaxy

- tests/foreman/api/test_registration.py
Add support for JWT invalidate via API: [SAT-30383](https://issues.redhat.com/browse/SAT-30383)
Added API support 
https://github.com/SatelliteQE/nailgun/pull/1260
> Add support for Registration Tokens

- conf/robottelo.yaml.template
- robottelo/config/validators.py
- robottelo/utils/shared_resource.py
It would be beneficial to drop this lower for tests.
> Add a configurable wait period for shared resource

- tests/foreman/cli/test_activationkey.py
There were still some tests failing in the AK component
This PR fixes them
```
pytest: tests/foreman/cli/test_activationkey.py -k "test_update_ak_with_syspurpose_values or test_positive_list_by_cv_id or test_positive_delete_with_cv"
```
> Another set of AK CLI fixes

- tests/foreman/cli/test_docker.py
Some docker tests were outdated, thus failing
This PR fixes them
```
pytest: tests/foreman/cli/test_docker.py -k "test_positive_add_docker_repo_cv or test_positive_remove_docker_repo_cv"
```
> Fix some Docker CLI tests

- robottelo/cli/user.py
- tests/foreman/cli/test_registration.py
Hammer support for invalidating JWTs : SAT-30385
Added support for JWT invalidate in CLI
> Add Hammer support for invalidating users JWTs

- pytest_fixtures/component/provision_capsule_pxe.py
- pytest_fixtures/component/provision_pxe.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17595
The provisioning tests are failing due to the recent sat workflow update
Fix/update the tests
> [6.15.z] Fix failing provisioning tests due to the sat workflow update

- pytest_fixtures/component/provision_capsule_pxe.py
- pytest_fixtures/component/provision_pxe.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17595
The provisioning tests are failing due to the recent sat workflow update
Fix/update the tests
> [6.16.z] Fix failing provisioning tests due to the sat workflow update

- tests/foreman/cli/test_capsulecontent.py
Test fails in CI in `wait_for_sync`
```
tests/foreman/cli/test_capsulecontent.py:855: in test_sync_consume_flatpak_repo_via_library
module_capsule_configured.wait_for_sync(start_time=timestamp)
robottelo/host_helpers/capsule_mixins.py:105: in wait_for_sync
assert len(sync_status['active_sync_tasks']) or (
E   AssertionError: No active or recent sync found for capsule ...
```
It looks like the autosync was turned OFF.
For now turn the autosync ON explicitly and see what happens.
Optionally we could trigger the sync from test.
```
pytest: tests/foreman/cli/test_capsulecontent.py -k test_sync_consume_flatpak_repo_via_library
```
> Set Capsule autosync explicitly

- conftest.py
- pytest_fixtures/component/global_params.py
- pytest_fixtures/component/settings.py
- tests/foreman/cli/test_remoteexecution.py
cherrypick of https://github.com/SatelliteQE/robottelo/pull/17043, verifies SAT-30293
> [6.16] test rex using values from global parameters

- tests/foreman/cli/test_computeresource_vmware.py
automation reported this, closes 
https://github.com/SatelliteQE/robottelo/issues/17554
https://github.com/SatelliteQE/robottelo/issues/17603
> vmware provision test, missing customerscenario tag

- tests/foreman/ui/test_remoteexecution.py
Requires https://github.com/SatelliteQE/airgun/pull/1743
This PR extends the new job invocations detail page testing
with new widgets that have been added as part of SAT-26605 RFE.
Namely the expandable sections `Target Hosts` and `User Inputs`.
The expandable hosts table will be added in a separate PR,
see more details why in the linked airgun PR above.
> RFE: extended test for new job_invocations detail page, vol. 2

- .pre-commit-config.yaml
- tests/foreman/api/test_errata.py
Covers CustomerCase: SAT-24725 ([BZ: 2160804](https://bugzilla.redhat.com/show_bug.cgi?id=2160804))
- We use the EPEL 10 repository to sync real Erratum of types that fall under 'Other' (ie newpackage , unspecified)
- We need to fetch a dynamically created PGP key from https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-10
- Syncing EPEL version 10, because it matches the newest RHEL version from supportability
Closely following DEV Testing Steps from Katello MR: https://github.com/Katello/katello/pull/11188
GET request to receive a new PGP key from FedoraProject.
Create a GPG key on satellite from the PGP key received, create product with the GPG assigned.
Use the GPG key to create and sync, large EPEL 10 (x86_64 - everything) as a custom repository.
Publish the 1st CV version with …
> [CustomerCase] Test Errata type "Other", with inclusive CV Filter, verify content counts

- pytest_fixtures/component/leapp_client.py
- pytest_fixtures/core/sat_cap_factory.py
- robottelo/constants/__init__.py
- tests/foreman/cli/test_leapp_client.py
- tests/foreman/ui/test_leapp_client.py
check that pull-rex mode setup survives leapp upgrade, preparation for SAT-28315, SAT-27476
> pull mode rex survives leapp upgrade

- tests/foreman/cli/test_satellitesync.py
We need to ensure the disconnected workflow (export/import) works fine for flatpak.
We have already covered the export/import part of mixed content types (flatpak is just one of them), but we still need to ensure the flatpak registry at the importing SAT serves the imported content properly. Basically we need to extend the case with host registration and ensure the content is consumable.
https://issues.redhat.com/browse/SAT-29562
Also, for this test to pass we need https://issues.redhat.com/browse/SAT-30342 fixed in snap (hopefully snap 88)
```
pytest: tests/foreman/cli/test_satellitesync.py -k test_postive_export_import_cv_with_mixed_content_repos
Katello:
katello: 11300
```
> Extend mixed content export import with consume

- tests/foreman/cli/test_docker.py
Adding test coverage for this customer case issue: https://issues.redhat.com/browse/SAT-21359
After being not very supported for a while, with podman push integration, hammer repository upload-content explicitly no longer works with docker type repositories, so this makes sure that remains the case. 
pytest: tests/foreman/cli/test_docker.py -k 'test_docker_upload_content'
> Add coverage checking that upload-content doesn't work with docker

- pytest_fixtures/component/http_proxy.py
- robottelo/host_helpers/api_factory.py
- tests/foreman/ui/test_http_proxy.py
Missing test coverage for new feature SAT-28860
Add test coverage for new feature SAT-28860
https://github.com/SatelliteQE/airgun/pull/1636
https://github.com/SatelliteQE/nailgun/pull/1254
> Add test coverage for SAT-28860

- robottelo/hosts.py
puppet forgeapis FQDN is unreachable from IPv6 sat
Fix puppet tests by using proxy for connecting to puppet forgeapis
> Fix puppet tests by using proxy for connecting to puppet forgeapis

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17613
puppet forgeapis FQDN is unreachable from IPv6 sat
Fix puppet tests by using proxy for connecting to puppet forgeapis
> [6.16.z] Fix puppet tests by using proxy for connecting to puppet forgeapis

- pytest_fixtures/component/provision_pxe.py
- pytest_plugins/infra_dependent_markers.py
- pytest_plugins/marker_deselection.py
- robottelo/host_helpers/satellite_mixins.py
- tests/foreman/api/test_provisioning.py
Provisioning tests are not updated to run on IPv6 satellite
Update the tests to run on IPv6 satellite
> Update provisioning tests for IPv6 provisoning

- tests/foreman/cli/test_registration.py
The assertion at installing rpm on host is not properly done.
Updated the assertion for rpm command and using rhel_contenthost fixture along with default_rhel_version.
> Fix assertion for installing katello-ca cert and updating rhel_contenthost fixture to test default rhel version

- pytest_fixtures/core/sat_cap_factory.py
- robottelo/hosts.py
- tests/foreman/installer/test_installer.py
Various fixes of Installer tests that were failing during Interop testing
- using server deploy arguments (instead of content_host)
- ensuring that firewall is installed before it's configuration (firewalld is not installed on compose rhel images)
- setting up rhel and satellite repositories
> Fix deployment in Interop testing

- tests/foreman/cli/test_registration.py
Failed auto-cherrypick https://github.com/SatelliteQE/robottelo/issues/17624
Manually cherrypick of https://github.com/SatelliteQE/robottelo/pull/17612
> [6.14.z cherrypick] Fix assertion for installing katello-ca cert and updating rhel_contenthost fixture to test default rhel version]

- pytest_fixtures/core/sat_cap_factory.py
- robottelo/hosts.py
- tests/foreman/installer/test_installer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17489
Various fixes of Installer tests that were failing during Interop testing
- using server deploy arguments (instead of content_host)
- ensuring that firewall is installed before it's configuration (firewalld is not installed on compose rhel images)
- setting up rhel and satellite repositories
> [6.16.z] Fix deployment in Interop testing

- tests/foreman/cli/test_registration.py
…updating rhel_contenthost fixture to test default rhel version]
Failed auto-cherrypick https://github.com/SatelliteQE/robottelo/issues/17626
Manually cherrypicked.
> [6.15.z Cherrypick]Fix assertion for installing katello-ca cert and updating rhel_contenthost fixture to test default rhel version

- tests/foreman/cli/test_registration.py
Failed auto-cherrypick https://github.com/SatelliteQE/robottelo/issues/17625
Manually cherrypicked.
> [6.16.z Cherrypick]Fix assertion for installing katello-ca cert and updating rhel_contenthost fixture to test default rhel version

- conf/repos.yaml.template
- pytest_fixtures/component/provision_pxe.py
- robottelo/constants/__init__.py
With RHEL10 beta repos, provisioning fails because of SAT-29721, and it will be fixed when it becomes GA
Use custom content for RHEL10 until SAT-29721 is resolved
> Use custom content for RHEL10 until SAT-29721 is resolved

- tests/foreman/api/test_subscription.py
Cover [SAT-30636], which adds `rhel-10` option to the Repository OS Restrict flag.
- 3 repos restricted to `RHEL-10/9/8` , using one matching registered host of one the selected rhel versions.
- in `6.16.z` and `6.15.z`, implicitly selected RHEL versions will be `9/8/7` (N-2) from supportability.yaml.
Implement stubbed coverage, that could have discovered this missing option during initial automation runs.
```
pytest: tests/foreman/api/test_subscription.py::test_positive_os_restriction_on_repos
```
> [RHEL10,9,8] Cover restrict repos by host OS, RHEL major versions

- tests/foreman/ui/test_activationkey.py
One AK UI test was failing due to outdated airgun and test composition
This PR and Related Airgun PR fixes this test
This PR needs https://github.com/SatelliteQE/airgun/pull/1744
RHEL9 test fails with, 
`500 Server Error: Internal Server Error (can only create exec sessions on running containers: container state improper)`
thus not related to this PR.
```
pytest: tests/foreman/ui/test_activationkey.py -k 'test_negative_usage_limit'
airgun: 1744
```
> AK UI test fix

- tests/foreman/ui/test_http_proxy.py
We missed adding related issue in `test_positive_set_default_http_proxy` in PR https://github.com/SatelliteQE/robottelo/pull/17153
Add issue SAT-5118 in test_positive_set_default_http_proxy
> Add issue SAT-5118 to test_positive_set_default_http_proxy

- robottelo/constants/__init__.py
- tests/foreman/api/test_capsulecontent.py
- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/cli/test_flatpak.py
- tests/foreman/cli/test_satellitesync.py
Satellite implements second endpoint for flatpak registry index which is org/CV scoped, while the default pulpcore endpoint is system-wide. We already have test cases for the pulpcore system-wide EP, but we need to test the CV scoped one too. It will probably become the default users would want to use.
This PR add an E2E test case for that CV scoped endpoint.
https://issues.redhat.com/browse/SAT-28677
```
pytest: tests/foreman/cli/test_flatpak.py -k test_sync_consume_flatpak_repo_via_cv
Katello:
katello: 11300
```
> Add a test case for flatpak CV scoping

- .github/dependabot.yml
- conf/robottelo.yaml.template
- robottelo/constants/__init__.py
New 6.17.z downstream and master points to stream that is 6.18
- Dependabot.yaml cherrypicks to 6.17.z
- Robottelo conf and constants now uses 6.18 and 6.17.z satellite versions
> [master]: Changes for new 6.17.z branch

- conf/content_host.yaml.template
We've seen some occasional issues where containers are exiting prematurely. This may be to our config not qualifying the image name as the one located on localhost.
With this change, we're being more explicit with that qualification. I've also updated some of the changes in the config where our CI is ahead.
> Qualify the container image names to localhost

- robottelo/hosts.py
Recent change in PR https://github.com/SatelliteQE/robottelo/pull/17489 updated `capsule_setup` helper, which now fails with below error
```
failed on setup with "dynaconf.vendor.box.exceptions.BoxKeyError: "'DynaBox' object has no attribute 'rhelsource'". Did you mean: 'rhel_source'?"
```
Fix typo in capsule_setup helper
> Fix typo in capsule_setup helper

- pytest_fixtures/component/provision_pxe.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17656
When setup `configure_kea_dhcp6_server` fixture is run for IPv4, it fails with "failed on setup with "ValueError: configure_kea_dhcp6_server did not yield a value"
Fix configure_kea_dhcp6_server fixture for IPv4 by yielding None value since this fixture intended for IPv6 only
> [6.17.z] Fix configure_kea_dhcp6_server fixture for IPv4

- tests/foreman/cli/test_remoteexecution.py
Trying to make a couple of problematic tests behave more predictably.
Asserting for rex status instead of result, removing some time assertions
> less flakiness in rex module

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17657
Recent change in PR https://github.com/SatelliteQE/robottelo/pull/17489 updated `capsule_setup` helper, which now fails with below error
```
failed on setup with "dynaconf.vendor.box.exceptions.BoxKeyError: "'DynaBox' object has no attribute 'rhelsource'". Did you mean: 'rhel_source'?"
```
Fix typo in capsule_setup helper
> [6.17.z] Fix typo in capsule_setup helper

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17519
Trying to make a couple of problematic tests behave more predictably.
Asserting for rex status instead of result, removing some time assertions
> [6.16.z] less flakiness in rex module

- pytest_fixtures/core/contenthosts.py
- tests/foreman/api/test_convert2rhel.py
Centos/Oracle Host checkout for IPv6 failing due to no option for ipv6.
Update Centos/Oracle Host checkout for IPv6.
> Add IPv6 support in  Centos/Oracle Host checkout

- tests/foreman/api/test_reporttemplates.py
- tests/foreman/cli/test_reporttemplates.py
- tests/foreman/ui/test_reporttemplates.py
Add parametrization for RHEL10, for the `rhel_contenthost`'s in these ReportTemplates cases.
Some RT tests are already running with a RHEL10 contenthost param, but found a few more we would want also covered.
Also fix AK creation issue seen locally and in Stream, for `api/test_reporttemplates.py::test_positive_installable_errata`
```
pytest: tests/foreman/api/test_reporttemplates.py tests/foreman/cli/test_reporttemplates.py -k 'rhel10'
```
> ReportTemplates Coverage for RHEL10 hosts

- pytest_fixtures/core/contenthosts.py
- tests/foreman/api/test_convert2rhel.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17367
Centos/Oracle Host checkout for IPv6 failing due to no option for ipv6.
Update Centos/Oracle Host checkout for IPv6.
> [6.17.z] Add IPv6 support in  Centos/Oracle Host checkout

- tests/foreman/api/test_subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17415
Cover [SAT-30636], which adds `rhel-10` option to the Repository OS Restrict flag.
- 3 repos restricted to `RHEL-10/9/8` , using one matching registered host of one the selected rhel versions.
- in `6.16.z` and `6.15.z`, implicitly selected RHEL versions will be `9/8/7` (N-2) from supportability.yaml.
Implement stubbed coverage, that could have discovered this missing option during initial automation runs.
```
pytest: tests/foreman/api/test_subscription.py::test_positive_os_restriction_on_repos
```
> [6.16.z] [RHEL10,9,8] Cover restrict repos by host OS, RHEL major versions

- tests/foreman/api/test_subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17415
Cover [SAT-30636], which adds `rhel-10` option to the Repository OS Restrict flag.
- 3 repos restricted to `RHEL-10/9/8` , using one matching registered host of one the selected rhel versions.
- in `6.16.z` and `6.15.z`, implicitly selected RHEL versions will be `9/8/7` (N-2) from supportability.yaml.
Implement stubbed coverage, that could have discovered this missing option during initial automation runs.
```
pytest: tests/foreman/api/test_subscription.py::test_positive_os_restriction_on_repos
```
> [6.15.z] [RHEL10,9,8] Cover restrict repos by host OS, RHEL major versions

- conf/container.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_contentview.py
- tests/foreman/api/test_contentviewfilter.py
- tests/foreman/api/test_docker.py
- tests/foreman/api/test_http_proxy.py
- tests/foreman/api/test_product.py
- tests/foreman/api/test_repository.py
- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/cli/test_container_management.py
- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_contentviewfilter.py
- tests/foreman/cli/test_docker.py
- tests/foreman/cli/test_repository.py
- tests/foreman/cli/test_satellitesync.py
- tests/foreman/cli/test_vm_install_products_package.py
- tests/foreman/ui/test_activationkey.py
- tests/foreman/ui/test_containerimagetag.py
- tests/foreman/ui/test_contentview_old.py
- tests/foreman/ui/test_http_proxy.py
- tests/foreman/ui/test_repository.py
- tests/foreman/ui/test_sync.py
- tests/new_upgrades/test_repository.py
- tests/upgrades/test_repository.py
container related settings cannot be configured via settings file
Move container related settings to yaml settings file
> Make container content related settings configurable

- conf/container.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_contentview.py
- tests/foreman/api/test_contentviewfilter.py
- tests/foreman/api/test_docker.py
- tests/foreman/api/test_http_proxy.py
- tests/foreman/api/test_product.py
- tests/foreman/api/test_repository.py
- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/cli/test_container_management.py
- tests/foreman/cli/test_contentview.py
- tests/foreman/cli/test_contentviewfilter.py
- tests/foreman/cli/test_docker.py
- tests/foreman/cli/test_repository.py
- tests/foreman/cli/test_satellitesync.py
- tests/foreman/cli/test_vm_install_products_package.py
- tests/foreman/ui/test_activationkey.py
- tests/foreman/ui/test_containerimagetag.py
- tests/foreman/ui/test_contentview_old.py
- tests/foreman/ui/test_http_proxy.py
- tests/foreman/ui/test_repository.py
- tests/foreman/ui/test_sync.py
- tests/new_upgrades/test_repository.py
- tests/upgrades/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17570
container related settings cannot be configured via settings file
Move container related settings to yaml settings file
> [6.17.z] Make container content related settings configurable

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17519
Trying to make a couple of problematic tests behave more predictably.
Asserting for rex status instead of result, removing some time assertions
> [6.17.z] less flakiness in rex module

- tests/foreman/api/test_reporttemplates.py
- tests/foreman/cli/test_reporttemplates.py
Cherry-pick of #17635 to 6.17.z
```
pytest: tests/foreman/api/test_reporttemplates.py tests/foreman/cli/test_reporttemplates.py -k 'rhel10'
```
> [6.17.z] CP ReportTemplates Coverage for RHEL10 hosts

- tests/foreman/cli/test_remoteexecution.py
manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/17519
closes https://github.com/SatelliteQE/robottelo/issues/17666
> [6.14] less flakiness in rex module

- tests/foreman/destructive/test_infoblox.py
Fixing IPv6 Infoblox tests
- Removing `isc_dhcp` as we don't really test it with infoblox integration and we don't document that as well
- The domain created is already present in the IPv6 satellite hence adding condition to check first and create it if not present
Satellite Jenkins MR: 1618
> Fix IPv6 Infoblox tests

- tests/foreman/installer/test_installer.py
cherrypick of #17384
fix false negative
(cherry picked from commit https://github.com/SatelliteQE/robottelo/commit/c251f4678dc06401046a66aa5d8c16b7d3fe55e9)
closes #17386
> [6.14.z] Prevent satellite-installer false negative (#17384)

- tests/foreman/installer/test_installer.py
cherrypick of #17384
fix false negative
(cherry picked from commit c251f4678dc06401046a66aa5d8c16b7d3fe55e9)
closes #17389
> [6.15.z] Prevent satellite-installer false negative (#17384)

- tests/foreman/api/test_activationkey.py
- tests/foreman/api/test_reporttemplates.py
- tests/foreman/cli/test_activationkey.py
- tests/foreman/cli/test_docker.py
There were still some outdated tests in our test framework which were failing for a while
This PR fixes some of those tests
```
pytest: tests/foreman/cli/test_docker.py::TestDockerActivationKey::test_positive_add_docker_repo_ccv tests/foreman/cli/test_docker.py::TestDockerActivationKey::test_positive_remove_docker_repo_ccv tests/foreman/cli/test_activationkey.py::test_positive_update_cv  tests/foreman/api/test_reporttemplates.py::test_positive_installed_products
```
Tests passed locally
```
tests/foreman/cli/test_docker.py ..                                          [ 33%]
tests/foreman/cli/test_activationkey.py .                                [ 50%]
tests/foreman/api/test_reporttemplates.py ...                          [100%]
...
6 passed
```
> Multiple PhoenixSubs test fixes

- tests/foreman/api/test_activationkey.py
- tests/foreman/api/test_reporttemplates.py
- tests/foreman/cli/test_activationkey.py
- tests/foreman/cli/test_docker.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17705
There were still some outdated tests in our test framework which were failing for a while
This PR fixes some of those tests
```
pytest: tests/foreman/cli/test_docker.py::TestDockerActivationKey::test_positive_add_docker_repo_ccv tests/foreman/cli/test_docker.py::TestDockerActivationKey::test_positive_remove_docker_repo_ccv tests/foreman/cli/test_activationkey.py::test_positive_update_cv  tests/foreman/api/test_reporttemplates.py::test_positive_installed_products
```
Tests passed locally
```
tests/foreman/cli/test_docker.py ..                                          [ 33%]
tests/foreman/cli/test_activationkey.py .                                [ 50%] …
```
> [6.17.z] Multiple PhoenixSubs test fixes

- tests/foreman/api/test_http_proxy.py
The `test_positive_install_content_with_http_proxy` fails to install ansible due to changed dependency.
```
AssertionError: ansible installation failed with: Error: 
Problem: cannot install the best candidate for the job
- nothing provides python3-PyYAML needed by ansible-2.9.27-1.el8ae.noarch from ansible-2.9-for-rhel-8-x86_64-rpms
- nothing provides python3-cryptography needed by ansible-2.9.27-1.el8ae.noarch from ansible-2.9-for-rhel-8-x86_64-rpms
- nothing provides python3-jinja2 needed by ansible-2.9.27-1.el8ae.noarch from ansible-2.9-for-rhel-8-x86_64-rpms
```
Use some different repo/pkg without dependency.
```
```
> Use k-h-t from client repo for http proxy testing

- tests/foreman/api/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17714
The `test_positive_install_content_with_http_proxy` fails to install ansible due to changed dependency.
```
AssertionError: ansible installation failed with: Error: 
Problem: cannot install the best candidate for the job
- nothing provides python3-PyYAML needed by ansible-2.9.27-1.el8ae.noarch from ansible-2.9-for-rhel-8-x86_64-rpms
- nothing provides python3-cryptography needed by ansible-2.9.27-1.el8ae.noarch from ansible-2.9-for-rhel-8-x86_64-rpms
- nothing provides python3-jinja2 needed by ansible-2.9.27-1.el8ae.noarch from ansible-2.9-for-rhel-8-x86_64-rpms
```
Use some different repo/pkg without dependency.
```
pytest: tests/foreman/api/test_http_proxy.py -k …
```
> [6.17.z] Use k-h-t from client repo for http proxy testing

- tests/foreman/api/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17714
The `test_positive_install_content_with_http_proxy` fails to install ansible due to changed dependency.
```
AssertionError: ansible installation failed with: Error: 
Problem: cannot install the best candidate for the job
- nothing provides python3-PyYAML needed by ansible-2.9.27-1.el8ae.noarch from ansible-2.9-for-rhel-8-x86_64-rpms
- nothing provides python3-cryptography needed by ansible-2.9.27-1.el8ae.noarch from ansible-2.9-for-rhel-8-x86_64-rpms
- nothing provides python3-jinja2 needed by ansible-2.9.27-1.el8ae.noarch from ansible-2.9-for-rhel-8-x86_64-rpms
```
Use some different repo/pkg without dependency.
```
pytest: tests/foreman/api/test_http_proxy.py -k …
```
> [6.16.z] Use k-h-t from client repo for http proxy testing

- tests/foreman/longrun/test_oscap.py
SAT-19505 now in testing, the test failed on scap installation from client repo.  The scenario precludes using non-signed repo which is what we have.
Revert the effect of manual policy run for the one specific repo
> allow applying a scap policy after manual hardening

- robottelo/config/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17701
Just saw an issue in the robottelo CI where this popped up.
```python
File "/home/runner/work/robottelo/robottelo/robottelo/config/__init__.py", line 25, in get_settings
if builtins.__sphinx_build__:
^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'builtins' has no attribute '__sphinx_build__'
```
If we simply make this a getattr call, then we don't have to worry about that attribute being present.
> [6.15.z] Make the sphinx check more resilient

- tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17681
SAT-19505 now in testing, the test failed on scap installation from client repo.  The scenario precludes using non-signed repo which is what we have.
Revert the effect of manual policy run for the one specific repo
> [6.16.z] allow applying a scap policy after manual hardening

- tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17681
SAT-19505 now in testing, the test failed on scap installation from client repo.  The scenario precludes using non-signed repo which is what we have.
Revert the effect of manual policy run for the one specific repo
> [6.17.z] allow applying a scap policy after manual hardening

- tests/foreman/cli/test_contentview.py
The `test_positive_sub_host_with_restricted_user_perm_at_default_loc` fails due to improved error message and needs a small fix.
```
tests/foreman/cli/test_contentview.py:2183: in test_positive_sub_host_with_restricted_user_perm_at_default_loc
assert '403 Forbidden' in str(context)
E   assert '403 Forbidden' in '<ExceptionInfo CLIReturnCodeError(status=77, stderr=\'Access denied\\nMissing one of the required permissions: view_roles\\n\', msg=\'Comm... info" finished with status 77\\nstderr contains:\\nAccess denied\\nMissing one of the required permissions: view_roles\\n\' tblen=4>'
```
This PR updates the message but it turned out it needed also `AK.create` update and also I used this opportunity to replace `rhel7_contenthost` with default `rhel_contenthost`.
``` …
```
> Fix CV perm restricted tests

- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17727
The `test_positive_sub_host_with_restricted_user_perm_at_default_loc` fails due to improved error message and needs a small fix.
```
tests/foreman/cli/test_contentview.py:2183: in test_positive_sub_host_with_restricted_user_perm_at_default_loc
assert '403 Forbidden' in str(context)
E   assert '403 Forbidden' in '<ExceptionInfo CLIReturnCodeError(status=77, stderr=\'Access denied\\nMissing one of the required permissions: view_roles\\n\', msg=\'Comm... info" finished with status 77\\nstderr contains:\\nAccess denied\\nMissing one of the required permissions: view_roles\\n\' tblen=4>'
```
This PR updates the message but it turned out it needed also `AK.create` update and also I used this opportunity to replace …
> [6.16.z] Fix CV perm restricted tests

- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17727
The `test_positive_sub_host_with_restricted_user_perm_at_default_loc` fails due to improved error message and needs a small fix.
```
tests/foreman/cli/test_contentview.py:2183: in test_positive_sub_host_with_restricted_user_perm_at_default_loc
assert '403 Forbidden' in str(context)
E   assert '403 Forbidden' in '<ExceptionInfo CLIReturnCodeError(status=77, stderr=\'Access denied\\nMissing one of the required permissions: view_roles\\n\', msg=\'Comm... info" finished with status 77\\nstderr contains:\\nAccess denied\\nMissing one of the required permissions: view_roles\\n\' tblen=4>'
```
This PR updates the message but it turned out it needed also `AK.create` update and also I used this opportunity to replace …
> [6.17.z] Fix CV perm restricted tests

- tests/foreman/endtoend/test_api_endtoend.py
Add api changes for 6.17, those have been approved via mailing list
> api updated for 6.17

- tests/foreman/api/test_docker.py
- tests/foreman/cli/test_contentview.py
There are some tests failing for a bit and I felt I could fix them till I remember what's going on there
- several tests due to publish blocked by metadata generate
- one test due to attempts to promote CV instead of CV version
This PR.
```
pytest: tests/foreman -k 'test_version_info_by_lce or add_docker_repos_to_ccv'
```
> Fix couple of CV tests

- tests/foreman/api/test_docker.py
- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17742
There are some tests failing for a bit and I felt I could fix them till I remember what's going on there
- several tests due to publish blocked by metadata generate
- one test due to attempts to promote CV instead of CV version
This PR.
```
pytest: tests/foreman -k 'test_version_info_by_lce or add_docker_repos_to_ccv'
```
> [6.16.z] Fix couple of CV tests

- tests/foreman/api/test_registration.py
- tests/foreman/cli/test_registration.py
Negative test to verify users permission for JWT invalidate
Negative test added to for users permission
Update tests to use containers
> Add a negative test for JWT invalidate through hammer

- tests/foreman/api/test_docker.py
- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17742
There are some tests failing for a bit and I felt I could fix them till I remember what's going on there
- several tests due to publish blocked by metadata generate
- one test due to attempts to promote CV instead of CV version
This PR.
```
pytest: tests/foreman -k 'test_version_info_by_lce or add_docker_repos_to_ccv'
```
> [6.17.z] Fix couple of CV tests

- tests/upgrades/test_repository.py
The `test_post_simple_content_access_only` fails in 6.16.z due to typo.
```
AssertionError: assert 'True' in 'Loading production environment (Rails 6.1.7.8)\nSwitch to inspect mode.\nOrganization.find(21).simple_content_access?\ntrue\n\n'
+  where 'Loading production environment (Rails 6.1.7.8)\nSwitch to inspect mode.\nOrganization.find(21).simple_content_access?\ntrue\n\n' = stdout:\nLoading production environment (Rails 6.1.7.8)\nSwitch to inspect mode.\nOrganization.find(21).simple_content_access?\ntrue\n\n\nstderr:\n\nstatus: 0.stdout
```
The rake console always returns bool value with lowercase
```
[root@sat ~]# foreman-rake console
Loading production environment (Rails 6.1.7.8)
irb(main):001:0> Organization.find(1).simple_content_access?
=> true
irb(main):002:0> …
```
> [6.16.z] Fix typo in SCA-only upgrade scenario

- tests/foreman/api/test_repository.py
Downstream tests were failing due to wrong assertion message. I'm not sure if this also happens on upstream.
If PRT fails I would close the PR.
Fix assertion message
tests/foreman/api/test_repository.py::TestDockerRepository::test_negative_synchronize_private_registry_no_passwd
> Fix assertion in docker test

- tests/foreman/api/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17728
Downstream tests were failing due to wrong assertion message. I'm not sure if this also happens on upstream.
If PRT fails I would close the PR.
Fix assertion message
tests/foreman/api/test_repository.py::TestDockerRepository::test_negative_synchronize_private_registry_no_passwd
> [6.17.z] Fix assertion in docker test

- pytest_fixtures/core/contenthosts.py
- robottelo/constants/__init__.py
- tests/foreman/api/test_host.py
- tests/foreman/cli/test_host.py
- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17634
Adds tests for CLI/UI/API for bootc, using dummy facts
Relies on: https://github.com/SatelliteQE/airgun/pull/1745 and https://github.com/SatelliteQE/nailgun/pull/1277
> [6.17.z] Add Cli/API/UI tests for bootc

- tests/foreman/api/test_registration.py
- tests/foreman/cli/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17525
Negative test to verify users permission for JWT invalidate
Negative test added to for users permission
Update tests to use containers
> [6.17.z] Add a negative test for JWT invalidate through hammer

- conf/container.yaml.template
- robottelo/config/validators.py
- tests/foreman/cli/test_docker.py
Some docker upstream names were still ahrdcoded
Make them configurable
pytest -s -vvv tests/foreman/cli/test_docker.py::TestDockerContentView
> Read leftover container upstream names from settings

- conf/container.yaml.template
- robottelo/config/validators.py
- tests/foreman/cli/test_docker.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17729
Some docker upstream names were still ahrdcoded
Make them configurable
pytest -s -vvv tests/foreman/cli/test_docker.py::TestDockerContentView
> [6.16.z] Read leftover container upstream names from settings

- conf/container.yaml.template
- robottelo/config/validators.py
- tests/foreman/cli/test_docker.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17729
Some docker upstream names were still ahrdcoded
Make them configurable
pytest -s -vvv tests/foreman/cli/test_docker.py::TestDockerContentView
> [6.15.z] Read leftover container upstream names from settings

- conf/container.yaml.template
- robottelo/config/validators.py
- tests/foreman/cli/test_docker.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17729
Some docker upstream names were still ahrdcoded
Make them configurable
pytest -s -vvv tests/foreman/cli/test_docker.py::TestDockerContentView
> [6.17.z] Read leftover container upstream names from settings

- tests/foreman/ui/test_discoveryrule.py
Previously, there was only one column for `IP Address`. However, starting from `version 6.17`, both `IPv4` and `IPv6` networks are used. When a discovery host is created, two separate columns are displayed for `IPv4` and `IPv6`. To prevent assertion failures, the IP address will be fetched based on the respective network.
`Prior -
`![image](https://github.com/user-attachments/assets/21525a7e-431f-4f2e-9409-a955832e5952)
`Latest - 
`![image](https://github.com/user-attachments/assets/0374a8ec-9994-4318-bcca-3bde9f26f488)
> update assertion for discovery plugin test as per IPv4/Ipv6 ip address

- tests/foreman/longrun/test_oscap.py
manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/17681
closes https://github.com/SatelliteQE/robottelo/issues/17733
> 6.15 allow applying a scap policy after manual hardening

- tests/foreman/cli/test_rhcloud_inventory.py
- tests/foreman/ui/test_rhcloud_insights.py
Automation for SAT-30227 was needed.
It needs to check that the RHCloud auto-sync setting is set to true by default
This PR
```
pytest: tests/foreman/cli/test_rhcloud_inventory.py::test_positive_check_report_autosync_setting
```
> Check RHCloud auto-sync setting

- tests/foreman/cli/test_rhcloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17790
Automation for SAT-30227 was needed.
It needs to check that the RHCloud auto-sync setting is set to true by default
This PR
```
pytest: tests/foreman/cli/test_rhcloud_inventory.py::test_positive_check_report_autosync_setting
```
> [6.17.z] Check RHCloud auto-sync setting

- tests/foreman/ui/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17633
Previously, there was only one column for `IP Address`. However, starting from `version 6.17`, both `IPv4` and `IPv6` networks are used. When a discovery host is created, two separate columns are displayed for `IPv4` and `IPv6`. To prevent assertion failures, the IP address will be fetched based on the respective network.
`Prior -
`![image](https://github.com/user-attachments/assets/21525a7e-431f-4f2e-9409-a955832e5952)
`Latest - 
`![image](https://github.com/user-attachments/assets/0374a8ec-9994-4318-bcca-3bde9f26f488)
> [6.17.z] update assertion for discovery plugin test as per IPv4/Ipv6 ip address

- tests/foreman/ui/test_contenthost.py
This PR fixes long failing Host-content test
```
pytest: tests/foreman/ui/test_contenthost.py -k 'test_syspurpose_attributes_empty'
```
> Fix long failing host-content test

- tests/foreman/ui/test_contenthost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17791
This PR fixes long failing Host-content test
```
pytest: tests/foreman/ui/test_contenthost.py -k 'test_syspurpose_attributes_empty'
```
> [6.17.z] Fix long failing host-content test

- pytest_fixtures/core/contenthosts.py
- pytest_plugins/fixture_markers.py
- robottelo/hosts.py
- tests/foreman/api/test_remoteexecution.py
- tests/foreman/cli/test_leapp_client.py
- tests/foreman/cli/test_remoteexecution.py
- tests/foreman/destructive/test_registration.py
follow up from https://github.com/SatelliteQE/robottelo/pull/16789
fixed version selection and de-duplicated it. Added rhel repos that are now needed for new versions of yggdrasil
> more adjustments for pull rex on rhel10

- pytest_fixtures/component/leapp_client.py
- pytest_fixtures/core/contenthosts.py
- pytest_fixtures/core/sat_cap_factory.py
- pytest_plugins/fixture_markers.py
- robottelo/constants/__init__.py
- robottelo/hosts.py
- tests/foreman/api/test_remoteexecution.py
- tests/foreman/cli/test_leapp_client.py
- tests/foreman/cli/test_remoteexecution.py
- tests/foreman/destructive/test_registration.py
- tests/foreman/ui/test_leapp_client.py
This PR collects the work done on pull-mode rex tests in stream, for the purpose for easier testing of the backported cheanges on 6.16
> [6.16] changes related to the new yggdrasil package 

- pytest_fixtures/core/contenthosts.py
Several tests fail in host setup in IPv6 pipeline since they are unaware of IPV context and spawn on IPv4 infra.
```
pytest_fixtures/core/contenthosts.py:235: in module_flatpak_contenthost
with Broker(**host_conf(request), host_class=ContentHost) as host:
...
sock.connect((host, port))
E   socket.gaierror: [Errno -5] No address associated with hostname
```
Deploy them properly per IPV settings.
```
pytest: tests/foreman/cli/test_flatpak.py -k sync_consume_flatpak_repo_via_library
```
> Make container and flatpak hosts ipv6 aware

- pytest_fixtures/component/leapp_client.py
- tests/foreman/cli/test_leapp_client.py
Leapp tests were failing intermittently due to connection error with host.
Added wait_for_connection() to ensure it doesn't fail.
> Fix intermittent connection timeout on host reboot

- pytest_fixtures/component/permissions.py
- robottelo/constants/__init__.py
Missing permissions for snapshot management plugin
see code
> Add permission tests for snapshot management plugin

- pytest_fixtures/component/permissions.py
- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17764
Missing permissions for snapshot management plugin
see code
> [6.16.z] Add permission tests for snapshot management plugin

- pytest_fixtures/component/permissions.py
- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17764
Missing permissions for snapshot management plugin
see code
> [6.17.z] Add permission tests for snapshot management plugin

- tests/foreman/destructive/test_fm_upgrade.py
- Add Customer case automation for SAT-26758 - satellite installation in ipv6 disabled environment.
- Update `test_negative_ipv6_update_check` and add scenario to test that satellite-installer will fail when kernel contains ipv6.disable=1.
- SAT-26758
- SAT-31232
> Customer case automation - satellite installation in ipv6 disabled environment.

- tests/foreman/destructive/test_fm_upgrade.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17823
- Add Customer case automation for SAT-26758 - satellite installation in ipv6 disabled environment.
- Update `test_negative_ipv6_update_check` and add scenario to test that satellite-installer will fail when kernel contains ipv6.disable=1.
- SAT-26758
- SAT-31232
> [6.17.z] Customer case automation - satellite installation in ipv6 disabled environment.

- tests/foreman/sys/test_fam.py
some test playbook have a "foreman" host defined, but that's not in the
inventory and thus generates warnings
tell ansible to ignore this
pytest: tests/foreman/sys/test_fam.py::test_positive_run_modules_and_roles[host]
> ignore warnings from Ansible when a host can't be found

- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17827
some test playbook have a "foreman" host defined, but that's not in the
inventory and thus generates warnings
tell ansible to ignore this
pytest: tests/foreman/sys/test_fam.py::test_positive_run_modules_and_roles[host]
> [6.17.z] ignore warnings from Ansible when a host can't be found

- tests/foreman/api/test_reporttemplates.py
`test_positive_applied_errata_for_specific_hosts` covers SAT-30611 for report filtered by hostname, 
but also reported  was a perceived discrepancy with the date fields, I found we don't yet test the dates for the Hosts - Applied Errata ReportTemplate.
- New coverage (nice-to-have) `test_positive_applied_errata_by_install_date` 
now tests the '_Since_' and '_Up to_' date fields. (Seperate PR #17713 ).
```
pytest: tests/foreman/api/test_reporttemplates.py -k '_specific_hosts' or ::test_positive_applied_errata_for_specific_hosts
```
> [SAT-30611] Test Applied Errata report by hostname

- conf/repos.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/api/test_repository.py
Missing python content type
Add python as content type and add simple happy flow test for sync
tests/foreman/api/test_repository.py::TestPythonRepository::test_positive_sync
-->
> Add tests for python content type

- pytest_fixtures/core/contenthosts.py
In #17690 we moved container constants to settings but forgot about `container_contentohst`, so we get these failures
```
pytest_fixtures/core/contenthosts.py:234: in module_container_contenthost
for client in constants.CONTAINER_CLIENTS:
E   AttributeError: module 'robottelo.constants' has no attribute 'CONTAINER_CLIENTS'
```
Update the fixture.
```
pytest: tests/foreman -k test_negative_pull_content_with_longer_name
```
> Fix container contenthost

- conf/repos.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/api/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17704
Missing python content type
Add python as content type and add simple happy flow test for sync
tests/foreman/api/test_repository.py::TestPythonRepository::test_positive_sync
-->
> [6.17.z] Add tests for python content type

- conf/repos.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/api/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17704
Missing python content type
Add python as content type and add simple happy flow test for sync
tests/foreman/api/test_repository.py::TestPythonRepository::test_positive_sync
-->
> [6.15.z] Add tests for python content type

- conf/repos.yaml.template
- robottelo/config/validators.py
- robottelo/constants/__init__.py
- tests/foreman/api/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17704
Missing python content type
Add python as content type and add simple happy flow test for sync
tests/foreman/api/test_repository.py::TestPythonRepository::test_positive_sync
-->
> [6.16.z] Add tests for python content type

- pytest_fixtures/core/contenthosts.py
- tests/foreman/cli/test_container_management.py
The default registry name pattern has been changed from `-` to `/` in 6.17.0 and `test_negative_pull_content_with_longer_name` seems to be the last left forgotten.
Update the pattern.
```
pytest: tests/foreman/cli/test_container_management.py -k test_negative_pull_content_with_longer_name
```
> Fix container path pattern

- tests/foreman/cli/test_container_management.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17828
The default registry name pattern has been changed from `-` to `/` in 6.17.0 and `test_negative_pull_content_with_longer_name` seems to be the last left forgotten.
Update the pattern.
```
pytest: tests/foreman/cli/test_container_management.py -k test_negative_pull_content_with_longer_name
```
> [6.17.z] Fix container path pattern

- pytest_fixtures/core/contenthosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17825
In #17690 we moved container constants to settings but forgot about `container_contentohst`, so we get these failures
```
pytest_fixtures/core/contenthosts.py:234: in module_container_contenthost
for client in constants.CONTAINER_CLIENTS:
E   AttributeError: module 'robottelo.constants' has no attribute 'CONTAINER_CLIENTS'
```
Update the fixture.
```
pytest: tests/foreman -k test_negative_pull_content_with_longer_name
```
> [6.17.z] Fix container contenthost

- tests/foreman/ui/test_http_proxy.py
We have recently updated our HTTP proxy instances, but the new version stores the user in access.log as base64-encoded string. And we assert the user presence in the log.
Assert the base64-encoded user instead.
```
pytest: tests/foreman/ui/test_http_proxy.py -k test_http_proxy_containing_special_characters
```
> Assert base64 encoded user in squid access.log

- tests/foreman/ui/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17834
We have recently updated our HTTP proxy instances, but the new version stores the user in access.log as base64-encoded string. And we assert the user presence in the log.
Assert the base64-encoded user instead.
```
pytest: tests/foreman/ui/test_http_proxy.py -k test_http_proxy_containing_special_characters
```
> [6.17.z] Assert base64 encoded user in squid access.log

- tests/foreman/api/test_reporttemplates.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17702
`test_positive_applied_errata_for_specific_hosts` covers SAT-30611 for report filtered by hostname, 
but also reported  was a perceived discrepancy with the date fields, I found we don't yet test the dates for the Hosts - Applied Errata ReportTemplate.
- New coverage (nice-to-have) `test_positive_applied_errata_by_install_date` 
now tests the '_Since_' and '_Up to_' date fields. (Seperate PR #17713 ).
```
pytest: tests/foreman/api/test_reporttemplates.py -k '_specific_hosts' or ::test_positive_applied_errata_for_specific_hosts
```
> [6.16.z] [SAT-30611] Test Applied Errata report by hostname

- tests/foreman/api/test_reporttemplates.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17702
`test_positive_applied_errata_for_specific_hosts` covers SAT-30611 for report filtered by hostname, 
but also reported  was a perceived discrepancy with the date fields, I found we don't yet test the dates for the Hosts - Applied Errata ReportTemplate.
- New coverage (nice-to-have) `test_positive_applied_errata_by_install_date` 
now tests the '_Since_' and '_Up to_' date fields. (Seperate PR #17713 ).
```
pytest: tests/foreman/api/test_reporttemplates.py -k '_specific_hosts' or ::test_positive_applied_errata_for_specific_hosts
```
> [6.17.z] [SAT-30611] Test Applied Errata report by hostname

- tests/foreman/sys/test_fam.py
some tests (most notably the ones that involve content), sometimes take
longer than the default 10 minutes that robottelo allows them to run.
let's give them a bit more time to finish.
> set the execution timeout for FAM tests to 30 minutes

- .github/workflows/auto_branching.yml
- .github/workflows/pull_request.yml
- scripts/config_helpers.py
- scripts/customer_scenarios.py
- scripts/fixture_cli.py
- scripts/tokenize_customer_scenario.py
- scripts/validate_config.py
- setup.py
We can not update the Sphinx library without dropping Python 3.10 - SatelliteQE/robottelo#17638.
Drop Python 3.10 suport.
SatelliteQE/robottelo#17638
SatelliteQE/robottelo#17666
SatelliteQE/robottelo#17557
> Remove Python 3.10 support

- tests/foreman/ui/test_subscription.py
The test was failing due to a missing column that needed to be managed.
This easy fix adds a missing column and removes one not-ideal assert.
```
pytest: tests/foreman/ui/test_subscription.py -k 'test_select_customizable_columns_uncheck_and_checks_all_checkboxes'
```
> Fix subscriptions UI test

- robottelo/hosts.py
- tests/foreman/cli/test_registration.py
newly added download utility option missing https://github.com/theforeman/foreman/pull/9808
Add field
dependency https://github.com/SatelliteQE/nailgun/pull/1257
> Add possibility to specify download-utility

- tests/foreman/ui/test_subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17862
The test was failing due to a missing column that needed to be managed.
This easy fix adds a missing column and removes one not-ideal assert.
```
pytest: tests/foreman/ui/test_subscription.py -k 'test_select_customizable_columns_uncheck_and_checks_all_checkboxes'
```
> [6.16.z] Fix subscriptions UI test

- .pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17906
updates:
- [github.com/astral-sh/ruff-pre-commit: v0.9.10 → v0.11.0](https://github.com/astral-sh/ruff-pre-commit/compare/v0.9.10...v0.11.0)
> [6.17.z] [pre-commit.ci] pre-commit autoupdate

- pytest_fixtures/core/contenthosts.py
introduced in https://github.com/SatelliteQE/robottelo/pull/17551, request param version can be a string (oddly, this is the case for fips variants only), hence type error
> fix type error in contenthost fixture

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/auto_cherry_pick_merged.yaml
The process around a PR backport - `git cherry-pick` is set up in as a job matrix.
The [fail-fast](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) param
is set to `true` by default. That causes jobs from the same matrix, that are still running, to fail in case any job in the matrix fails.
As a result of this, a PR with the backported patch gets created, same as an GitHub Issue stating that `git cherry-pick` failed.
* Set `fail-fast` to `false`
> ci: do not fail running backports fast

- pytest_fixtures/core/contenthosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17876
introduced in https://github.com/SatelliteQE/robottelo/pull/17551, request param version can be a string (oddly, this is the case for fips variants only), hence type error
> [6.17.z] fix type error in contenthost fixture

- pytest_fixtures/core/contenthosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17876
introduced in https://github.com/SatelliteQE/robottelo/pull/17551, request param version can be a string (oddly, this is the case for fips variants only), hence type error
> [6.16.z] fix type error in contenthost fixture

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/auto_cherry_pick_merged.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17929
The process around a PR backport - `git cherry-pick` is set up in as a job matrix.
The [fail-fast](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) param
is set to `true` by default. That causes jobs from the same matrix, that are still running, to fail in case any job in the matrix fails.
As a result of this, a PR with the backported patch gets created, same as an GitHub Issue stating that `git cherry-pick` failed.
* Set `fail-fast` to `false`
> [6.17.z] ci: do not fail running backports fast

- robottelo/hosts.py
- tests/foreman/cli/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16912
newly added download utility option missing https://github.com/theforeman/foreman/pull/9808
Add field
dependency https://github.com/SatelliteQE/nailgun/pull/1257
> [6.17.z] Add possibility to specify download-utility

- tests/foreman/api/test_activationkey.py
API test for AK Creation was failing with below error
Error-
```
requests.exceptions.HTTPError: ('404 Client Error: Not Found for url: https://satellite.redhat.com/katello/api/v2/activation_keys', {'displayMessage': "Couldn't find content view environment with content view ID '30' and environment ID 'yywhcYLvgOI'", 'errors': ["Couldn't find content view environment with content view ID '30' and environment ID 'yywhcYLvgOI'"]})
```
update input parameters, environment need env_id
N/A
```
pytest: tests/foreman/api/test_activationkey.py -k 'test_positive_fetch_product_content'
```
> small fix for API AK creation in upgrade tests

- tests/foreman/api/test_activationkey.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17939
API test for AK Creation was failing with below error
Error-
```
requests.exceptions.HTTPError: ('404 Client Error: Not Found for url: https://satellite.redhat.com/katello/api/v2/activation_keys', {'displayMessage': "Couldn't find content view environment with content view ID '30' and environment ID 'yywhcYLvgOI'", 'errors': ["Couldn't find content view environment with content view ID '30' and environment ID 'yywhcYLvgOI'"]})
```
update input parameters, environment need env_id
N/A
```
pytest: tests/foreman/api/test_activationkey.py -k 'test_positive_fetch_product_content'
```
> [6.17.z] small fix for API AK creation in upgrade tests

- pytest_fixtures/component/http_proxy.py
One of our fixture definition files used an org fixture that was removed by https://github.com/SatelliteQE/robottelo/pull/17808. This PR replaces those uses with a Manifester-based org fixture.
> Remove fake manifest usage from http proxy fixtures

- pytest_fixtures/component/http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17950
One of our fixture definition files used an org fixture that was removed by https://github.com/SatelliteQE/robottelo/pull/17808. This PR replaces those uses with a Manifester-based org fixture.
> [6.17.z] Remove fake manifest usage from http proxy fixtures

- robottelo/constants/__init__.py
- tests/foreman/maintain/test_backup_restore.py
- tests/foreman/maintain/test_upgrade.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17888
Add customer case automation for: 
- Backups do not take a backup of Ansible configuration files under /etc/ansible - SAT-19933
- satellite-maintain backup command does not include custom answers file in the backup archive - SAT-25949 
- SAT-19933
- SAT-31843
- SAT-25949
- SAT-31861
> [6.17.z] Customer case automation for SAT-19933 and SAT-25949

- tests/foreman/api/test_repository.py
- tests/foreman/cli/test_repositories.py
- tests/foreman/ui/test_package.py
- tests/foreman/ui/test_sync.py
There are some repo tests failing since forever, making every sign-off somewhat annoying.
This PR fixes a couple of them, one fix per commit:
1. test_positive_check_package_details - tiny change in date format
2. ostree content type is disabled since pulp3, let's stub out those forgotten tests
3. test_positive_sync_rh_repos - we just need to enable two repos, no (outdated) cli_factory constructs
4. test_negative_update_label - the underlying bug has never been fixed, remove the test
5. test_negative_synchronize_auth_yum_repo - validation failures in repo creation, provide only creds subset which pass the create validation
6. test_positive_disable_rh_repo_with_basearch - I haven't been able to reproduce the failure in single run, but there might be interference from the other test, since …
> Fix a couple of long-failing repo tests

- tests/foreman/ui/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17947
Settings structure has been changed in https://github.com/SatelliteQE/robottelo/pull/16536 , fix in this test
> [6.16.z] Fix groups setting location after #16536

- tests/foreman/ui/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17947
Settings structure has been changed in https://github.com/SatelliteQE/robottelo/pull/16536 , fix in this test
> [6.17.z] Fix groups setting location after #16536

- pytest_fixtures/core/contenthosts.py
- robottelo/cli/host.py
- tests/foreman/cli/test_host.py
- tests/foreman/ui/test_host.py
Adds 2 tests to the UI suite for Bootc (Testing REX Template/bootc actions, and checking the bootc information via the Host Details UI). Also updates a CLI test to include the `hammer host bootc images` command, as well as tweaks the bootc_host fixture to use the 10.0 template, which is the one that will continue to be updated in CI.
Requires: https://github.com/SatelliteQE/airgun/pull/1757
> [6.17] Bootc UI Tests + CLI Test improvement, and some fixes

- pytest_fixtures/core/contenthosts.py
- robottelo/cli/host.py
- tests/foreman/cli/test_host.py
- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17836
Adds 2 tests to the UI suite for Bootc (Testing REX Template/bootc actions, and checking the bootc information via the Host Details UI). Also updates a CLI test to include the `hammer host bootc images` command, as well as tweaks the bootc_host fixture to use the 10.0 template, which is the one that will continue to be updated in CI.
Requires: https://github.com/SatelliteQE/airgun/pull/1757
> [6.17.z] [6.17] Bootc UI Tests + CLI Test improvement, and some fixes

- pytest_fixtures/component/http_proxy.py
Manual cherry pick of https://github.com/SatelliteQE/robottelo/pull/17950.
> [6.15.z] Remove fake manifest usage from http proxy fixtures

- pytest_fixtures/component/http_proxy.py
Manual cherry pick of https://github.com/SatelliteQE/robottelo/pull/17950.
> [6.16.z] Remove fake manifest usage from http proxy fixtures

- pyproject.toml
- pytest_fixtures/core/reporting.py
- pytest_plugins/metadata_markers.py
- robottelo/host_helpers/capsule_mixins.py
- robottelo/hosts.py
- robottelo/utils/decorators/func_shared/shared.py
- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_contentview.py
- tests/foreman/api/test_syncplan.py
- tests/foreman/cli/test_artifacts.py
- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/cli/test_errata.py
- tests/foreman/cli/test_remoteexecution.py
- tests/foreman/cli/test_rhcloud_inventory.py
- tests/foreman/cli/test_syncplan.py
- tests/foreman/cli/test_user.py
- tests/foreman/destructive/test_capsulecontent.py
- tests/foreman/longrun/test_inc_updates.py
- tests/foreman/sys/test_pulp3_filesystem.py
- tests/foreman/ui/test_capsulecontent.py
- tests/foreman/ui/test_contenthost.py
- tests/foreman/ui/test_errata.py
- tests/foreman/ui/test_repository.py
- tests/foreman/ui/test_rhc.py
- tests/foreman/ui/test_rhcloud_insights.py
- tests/foreman/ui/test_rhcloud_inventory.py
- tests/foreman/ui/test_syncplan.py
- tests/foreman/virtwho/ui/test_esx_sca.py
> Fix DeprecationWarning: datetime.datetime.utcnow() is deprecated

- pyproject.toml
- pytest_fixtures/core/reporting.py
- pytest_plugins/metadata_markers.py
- robottelo/host_helpers/capsule_mixins.py
- robottelo/hosts.py
- robottelo/utils/decorators/func_shared/shared.py
- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_contentview.py
- tests/foreman/api/test_syncplan.py
- tests/foreman/cli/test_artifacts.py
- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/cli/test_errata.py
- tests/foreman/cli/test_remoteexecution.py
- tests/foreman/cli/test_rhcloud_inventory.py
- tests/foreman/cli/test_syncplan.py
- tests/foreman/cli/test_user.py
- tests/foreman/destructive/test_capsulecontent.py
- tests/foreman/longrun/test_inc_updates.py
- tests/foreman/sys/test_pulp3_filesystem.py
- tests/foreman/ui/test_capsulecontent.py
- tests/foreman/ui/test_contenthost.py
- tests/foreman/ui/test_errata.py
- tests/foreman/ui/test_repository.py
- tests/foreman/ui/test_rhc.py
- tests/foreman/ui/test_rhcloud_insights.py
- tests/foreman/ui/test_rhcloud_inventory.py
- tests/foreman/ui/test_syncplan.py
- tests/foreman/virtwho/ui/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17766
> [6.17.z] Fix DeprecationWarning: datetime.datetime.utcnow() is deprecated

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17972
ISS file had an older way of uploading manifest and it was failing on getting the Response object as manifest
Adding .content to the manifest fixes this issue
> [6.17.z] Fix ISS manifest upload

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17972
ISS file had an older way of uploading manifest and it was failing on getting the Response object as manifest
Adding .content to the manifest fixes this issue
> [6.16.z] Fix ISS manifest upload

- pyproject.toml
- pytest_fixtures/core/reporting.py
- pytest_plugins/metadata_markers.py
- robottelo/host_helpers/capsule_mixins.py
- robottelo/hosts.py
- robottelo/utils/decorators/func_shared/shared.py
- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_contentview.py
- tests/foreman/api/test_syncplan.py
- tests/foreman/cli/test_artifacts.py
- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/cli/test_errata.py
- tests/foreman/cli/test_remoteexecution.py
- tests/foreman/cli/test_rhcloud_inventory.py
- tests/foreman/cli/test_syncplan.py
- tests/foreman/cli/test_user.py
- tests/foreman/destructive/test_capsulecontent.py
- tests/foreman/longrun/test_inc_updates.py
- tests/foreman/sys/test_pulp3_filesystem.py
- tests/foreman/ui/test_contenthost.py
- tests/foreman/ui/test_errata.py
- tests/foreman/ui/test_repository.py
- tests/foreman/ui/test_rhc.py
- tests/foreman/ui/test_rhcloud_insights.py
- tests/foreman/ui/test_rhcloud_inventory.py
- tests/foreman/ui/test_syncplan.py
- tests/foreman/virtwho/ui/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17766
Fixes #17975
> [6.16.z] Fix DeprecationWarning: datetime.datetime.utcnow() is deprecated

- tests/foreman/api/test_usergroup.py
- tests/foreman/cli/test_usergroup.py
> fixes in usergroup tests

- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17864
some tests (most notably the ones that involve content), sometimes take
longer than the default 10 minutes that robottelo allows them to run.
let's give them a bit more time to finish.
> [6.17.z] set the execution timeout for FAM tests to 30 minutes

- tests/foreman/api/test_usergroup.py
- tests/foreman/cli/test_usergroup.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17971
some longer failing issues
> [6.16.z] fixes in usergroup tests

- robottelo/host_helpers/cli_factory.py
Writing other automation, I discovered a bug in cli_factory `setup_org_for_a_custom_repo`, which is widely used.
if there is already a promoted Version to the LCE (ie Version 1.0) , then any subsequent Versions made will not be promoted to the LCE, they only exist in Library, promotion is skipped (see screenshots Before changes).
Instead of checking LCEs for the CV Version (which is what needs promotion), it only checks LCEs for the entire CV.
**Effect:** Any subsequent Version (2.0, 3.0 etc) won't get promoted to LCE, as Version 1.0 was promoted prior,
and therefore the LCE is also in the whole CV's info.
> CLI_Factory setup fix, promote current Version to Environment

- pyproject.toml
- pytest_fixtures/core/reporting.py
- pytest_plugins/metadata_markers.py
- robottelo/host_helpers/capsule_mixins.py
- robottelo/hosts.py
- robottelo/utils/decorators/func_shared/shared.py
- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_syncplan.py
- tests/foreman/cli/test_errata.py
- tests/foreman/cli/test_remoteexecution.py
- tests/foreman/cli/test_rhcloud_inventory.py
- tests/foreman/cli/test_syncplan.py
- tests/foreman/cli/test_user.py
- tests/foreman/longrun/test_inc_updates.py
- tests/foreman/sys/test_pulp3_filesystem.py
- tests/foreman/ui/test_contenthost.py
- tests/foreman/ui/test_errata.py
- tests/foreman/ui/test_repository.py
- tests/foreman/ui/test_rhc.py
- tests/foreman/ui/test_rhcloud_insights.py
- tests/foreman/ui/test_rhcloud_inventory.py
- tests/foreman/ui/test_syncplan.py
- tests/foreman/virtwho/ui/test_esx.py
- tests/foreman/virtwho/ui/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17766
Fixes #17976
> [6.15.z] Fix DeprecationWarning: datetime.datetime.utcnow() is deprecated

- pyproject.toml
- pytest_fixtures/core/reporting.py
- pytest_plugins/metadata_markers.py
- robottelo/host_helpers/capsule_mixins.py
- robottelo/hosts.py
- robottelo/utils/decorators/func_shared/shared.py
- tests/foreman/api/test_capsulecontent.py
- tests/foreman/api/test_syncplan.py
- tests/foreman/cli/test_errata.py
- tests/foreman/cli/test_remoteexecution.py
- tests/foreman/cli/test_rhcloud_inventory.py
- tests/foreman/cli/test_syncplan.py
- tests/foreman/cli/test_user.py
- tests/foreman/longrun/test_inc_updates.py
- tests/foreman/sys/test_pulp3_filesystem.py
- tests/foreman/ui/test_contenthost.py
- tests/foreman/ui/test_repository.py
- tests/foreman/ui/test_rhc.py
- tests/foreman/ui/test_rhcloud_insights.py
- tests/foreman/ui/test_rhcloud_inventory.py
- tests/foreman/ui/test_syncplan.py
- tests/foreman/virtwho/ui/test_esx.py
- tests/foreman/virtwho/ui/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17766
Fixes #17974
> [6.14.z] Fix DeprecationWarning: datetime.datetime.utcnow() is deprecated

- robottelo/host_helpers/cli_factory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18001
Writing other automation, I discovered a bug in cli_factory `setup_org_for_a_custom_repo`, which is widely used.
if there is already a promoted Version to the LCE (ie Version 1.0) , then any subsequent Versions made will not be promoted to the LCE, they only exist in Library, promotion is skipped (see screenshots Before changes).
Instead of checking LCEs for the CV Version (which is what needs promotion), it only checks LCEs for the entire CV.
**Effect:** Any subsequent Version (2.0, 3.0 etc) won't get promoted to LCE, as Version 1.0 was promoted prior,
and therefore the LCE is also in the whole CV's info.
> [6.17.z] CLI_Factory setup fix, promote current Version to Environment

- robottelo/host_helpers/cli_factory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18001
Writing other automation, I discovered a bug in cli_factory `setup_org_for_a_custom_repo`, which is widely used.
if there is already a promoted Version to the LCE (ie Version 1.0) , then any subsequent Versions made will not be promoted to the LCE, they only exist in Library, promotion is skipped (see screenshots Before changes).
Instead of checking LCEs for the CV Version (which is what needs promotion), it only checks LCEs for the entire CV.
**Effect:** Any subsequent Version (2.0, 3.0 etc) won't get promoted to LCE, as Version 1.0 was promoted prior,
and therefore the LCE is also in the whole CV's info.
> [6.16.z] CLI_Factory setup fix, promote current Version to Environment

- robottelo/host_helpers/cli_factory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18001
Writing other automation, I discovered a bug in cli_factory `setup_org_for_a_custom_repo`, which is widely used.
if there is already a promoted Version to the LCE (ie Version 1.0) , then any subsequent Versions made will not be promoted to the LCE, they only exist in Library, promotion is skipped (see screenshots Before changes).
Instead of checking LCEs for the CV Version (which is what needs promotion), it only checks LCEs for the entire CV.
**Effect:** Any subsequent Version (2.0, 3.0 etc) won't get promoted to LCE, as Version 1.0 was promoted prior,
and therefore the LCE is also in the whole CV's info.
> [6.15.z] CLI_Factory setup fix, promote current Version to Environment

- robottelo/constants/__init__.py
- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17998
This PR fixes flaky ISS test that now uses the newly added Satellite 6.16 repo which is used as a bigger repo instead of the Ansible repo used previously.
```
pytest: tests/foreman/cli/test_satellitesync.py -k "test_positive_export_rerun_failed_import"
```
> [6.16.z] Add Sat616 Rhel9 repo && fix flaky ISS test

- robottelo/constants/__init__.py
- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17998
This PR fixes flaky ISS test that now uses the newly added Satellite 6.16 repo which is used as a bigger repo instead of the Ansible repo used previously.
```
pytest: tests/foreman/cli/test_satellitesync.py -k "test_positive_export_rerun_failed_import"
```
> [6.17.z] Add Sat616 Rhel9 repo && fix flaky ISS test

- tests/foreman/destructive/test_capsule_loadbalancer.py
Add assertion to check the content host is registered against the load balancer.
```
pytest: tests/foreman/destructive/test_capsule_loadbalancer.py -k test_client_register_through_lb
```
> Add a check for registration server in LB setup

- tests/foreman/destructive/test_capsule_loadbalancer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17611
Add assertion to check the content host is registered against the load balancer.
```
pytest: tests/foreman/destructive/test_capsule_loadbalancer.py -k test_client_register_through_lb
```
> [6.17.z] Add a check for registration server in LB setup

- tests/foreman/destructive/test_capsule_loadbalancer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17611
Add assertion to check the content host is registered against the load balancer.
```
pytest: tests/foreman/destructive/test_capsule_loadbalancer.py -k test_client_register_through_lb
```
> [6.16.z] Add a check for registration server in LB setup

- robottelo/host_helpers/repository_mixins.py
Build says it's regression. Few tests were failing due to below error, it is failing in `robottelo/host_helpers/repository_mixins.py` 
Back trace-
`robottelo/host_helpers/repository_mixins.py:769: in setup_content`
**Error** 
```
Pending tasks detected in repositories of this content view. Please wait for the tasks
```
**Stack Trace** 
```
pytest_fixtures/component/repository.py:246: in module_repos_collection_with_manifest
_repos_collection.setup_content(module_sca_manifest_org.id, module_lce.id)
robottelo/host_helpers/repository_mixins.py:769: in setup_content
content_view, lce = self.setup_content_view(org_id, lce_id)
robottelo/host_helpers/repository_mixins.py:656: in setup_content_view
self.satellite.cli.ContentView.publish({'id': content_view['id']}) …
```
> use wait_for_tasks after generate metadata for repos

- robottelo/constants/__init__.py
RHEL10 repos become recommended in 6.17.0.
Further the Capsule, maintenance and utils repos are only supported for RHEL9 since it's the only base OS for 6.17.0.
We should update them accordingly.
This PR.
Expect the PRT to fail until all of the repos are GA'ed. 
```
pytest: tests/foreman/ui/test_repository.py -k test_recommended_repos
```
> Update RH recommended repos for 6.17

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18022
RHEL10 repos become recommended in 6.17.0.
Further the Capsule, maintenance and utils repos are only supported for RHEL9 since it's the only base OS for 6.17.0.
We should update them accordingly.
This PR.
Expect the PRT to fail until all of the repos are GA'ed. 
```
pytest: tests/foreman/ui/test_repository.py -k test_recommended_repos
```
> [6.17.z] Update RH recommended repos for 6.17

- tests/foreman/ui/test_oscappolicy.py
updated policy reference to one that exists across systems
> fixes in scap policy tests

- tests/foreman/ui/test_oscappolicy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17973
updated policy reference to one that exists across systems
> [6.16.z] fixes in scap policy tests

- tests/foreman/api/test_reporttemplates.py
We don't yet test the _"Since"_ and _"Up to"_ date fields (install time of erratum), for the Applied Errata Report.
**_Note:_** if this case is run locally, it will likely fail unless `datetime.now(UTC)` lines are changed to `datetime.now()` , 
I've specified UTC as that is what CI testing uses, but local sats will usually use local timezone unless the setting is changed.
Parametrize by `N-2` for fixture `module_rhel_contenthost` :
- in Stream and 6.17.z : [RHEL8, 9, 10]
- in 6.16.z and 6.15.z : [RHEL7, 8, 9]
```
pytest: tests/foreman/api/test_reporttemplates.py::test_positive_applied_errata_by_install_date
```
> Applied Errata Report by Install Dates: 'Since' and 'Up to'

- tests/foreman/api/test_reporttemplates.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17713
We don't yet test the _"Since"_ and _"Up to"_ date fields (install time of erratum), for the Applied Errata Report.
**_Note:_** if this case is run locally, it will likely fail unless `datetime.now(UTC)` lines are changed to `datetime.now()` , 
I've specified UTC as that is what CI testing uses, but local sats will usually use local timezone unless the setting is changed.
Parametrize by `N-2` for fixture `module_rhel_contenthost` :
- in Stream and 6.17.z : [RHEL8, 9, 10]
- in 6.16.z and 6.15.z : [RHEL7, 8, 9]
```
pytest: tests/foreman/api/test_reporttemplates.py::test_positive_applied_errata_by_install_date
```
> [6.17.z] Applied Errata Report by Install Dates: 'Since' and 'Up to'

- robottelo/host_helpers/repository_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17835
Build says it's regression. Few tests were failing due to below error, it is failing in `robottelo/host_helpers/repository_mixins.py` 
Back trace-
`robottelo/host_helpers/repository_mixins.py:769: in setup_content`
**Error** 
```
Pending tasks detected in repositories of this content view. Please wait for the tasks
```
**Stack Trace** 
```
pytest_fixtures/component/repository.py:246: in module_repos_collection_with_manifest
_repos_collection.setup_content(module_sca_manifest_org.id, module_lce.id)
robottelo/host_helpers/repository_mixins.py:769: in setup_content
content_view, lce = self.setup_content_view(org_id, lce_id)
robottelo/host_helpers/repository_mixins.py:656: in setup_content_view …
```
> [6.17.z] use wait_for_tasks after generate metadata for repos

- pytest_fixtures/component/leapp_client.py
- tests/foreman/cli/test_leapp_client.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17800
Leapp tests were failing intermittently due to connection error with host.
Added wait_for_connection() to ensure it doesn't fail.
> [6.17.z] Fix intermittent connection timeout on host reboot

- tests/foreman/cli/test_ansible.py
- tests/foreman/ui/test_ansible.py
Workaround for SAT-30807 to use proxy conditionally for connecting to ansible-galaxy was added in https://github.com/SatelliteQE/robottelo/pull/17575 ; since now SAT-30807 is closed a notabug, proxy doesn't get configured on host
Remove is_open for SAT-30807 from ansible tests and configure http proxy to connect to ansible-galaxy
> Remove is_open for SAT-30807 from ansible tests

- tests/foreman/cli/test_ansible.py
- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18018
Workaround for SAT-30807 to use proxy conditionally for connecting to ansible-galaxy was added in https://github.com/SatelliteQE/robottelo/pull/17575 ; since now SAT-30807 is closed a notabug, proxy doesn't get configured on host
Remove is_open for SAT-30807 from ansible tests and configure http proxy to connect to ansible-galaxy
> [6.17.z] Remove is_open for SAT-30807 from ansible tests

- tests/foreman/cli/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18044
The `test_positive_exported_imported_content_sync` test fails flakily with
```
AssertionError: A repeated, pending task was found for repository or capsule, after capsule sync completed:[robottelo.hosts.DecClass(cli_example=None, ended_at=None, humanized={'action': 'Update Content Counts', ...
```
AFAIK the `Update Content Counts` task _is_ expected to run after Capsule sync. The flakiness probably relates to task speed.
Remove the task from `unexpected_tasks`.
```
pytest: tests/foreman/cli/test_capsulecontent.py -k test_positive_exported_imported_content_sync
```
> [6.16.z] Fix capsule expected post-sync tasks

- tests/foreman/cli/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18044
The `test_positive_exported_imported_content_sync` test fails flakily with
```
AssertionError: A repeated, pending task was found for repository or capsule, after capsule sync completed:[robottelo.hosts.DecClass(cli_example=None, ended_at=None, humanized={'action': 'Update Content Counts', ...
```
AFAIK the `Update Content Counts` task _is_ expected to run after Capsule sync. The flakiness probably relates to task speed.
Remove the task from `unexpected_tasks`.
```
pytest: tests/foreman/cli/test_capsulecontent.py -k test_positive_exported_imported_content_sync
```
> [6.15.z] Fix capsule expected post-sync tasks

- tests/foreman/api/test_provisioning_puppet.py
puppet-agent packages are missing from EL10 client repo, causing puppet provisioning test to fail
Skip puppet provisioning test until SAT-30237 is resolved
> Skip puppet provisioning test until SAT-30237 is resolved

- tests/foreman/longrun/test_oscap.py
this solves an issue with reaching non ipv6 resources required in tests
> adjusting oscap longrun tests for ipv6 run

- tests/foreman/api/test_provisioning_puppet.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18047
puppet-agent packages are missing from EL10 client repo, causing puppet provisioning test to fail
Skip puppet provisioning test until SAT-30237 is resolved
> [6.17.z] Skip puppet provisioning test until SAT-30237 is resolved

- tests/foreman/api/test_provisioning.py
Provisioning tests are failing because of  SAT-32007 and SAT-32006
Add workfaround for SAT-32007 and SAT-32006 in provisioning tests
> Add workfaround for SAT-32007 and SAT-32006 in provisioning tests

- robottelo/host_helpers/capsule_mixins.py
#17766 made our datetimes "timezone-aware". As such, their `str` cast returns the timezone offset in `+hh:mm` format: 
```
>>> str(datetime.datetime.now(datetime.UTC))
'2025-03-25 19:15:03.671290+00:00'
```
In 12 out of 24 paramterizations of the `test_positive_artifact_repair` test we depend on the artifact creation time. For that we used `UTC` timezone specification, which does not work together with `+hh:mm` timezone specification: https://github.com/SatelliteQE/robottelo/blob/master/robottelo/host_helpers/capsule_mixins.py#L160 
Use just one timezone specification, preferably the one provided in datetime.
```
pytest: tests/foreman/cli/test_artifacts.py
```
> Fix artifact repair tests

- tests/foreman/cli/test_ansible.py
Add AAP2.5/latest parameterization along with legacy/AAP 2.3 to validate above change with AAP dynamic inventory and provisioning callback tests
satellite-jenkins MR#1638
> Add AAP2.5 parameterization in AAP provisioning callback tests

- robottelo/host_helpers/capsule_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18040
#17766 made our datetimes "timezone-aware". As such, their `str` cast returns the timezone offset in `+hh:mm` format: 
```
>>> str(datetime.datetime.now(datetime.UTC))
'2025-03-25 19:15:03.671290+00:00'
```
In 12 out of 24 paramterizations of the `test_positive_artifact_repair` test we depend on the artifact creation time. For that we used `UTC` timezone specification, which does not work together with `+hh:mm` timezone specification: https://github.com/SatelliteQE/robottelo/blob/master/robottelo/host_helpers/capsule_mixins.py#L160 
Use just one timezone specification, preferably the one provided in datetime.
```
pytest: tests/foreman/cli/test_artifacts.py
```
> [6.17.z] Fix artifact repair tests

- tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18046
this solves an issue with reaching non ipv6 resources required in tests
> [6.17.z] adjusting oscap longrun tests for ipv6 run

- tests/foreman/cli/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18041
Add AAP2.5/latest parameterization along with legacy/AAP 2.3 to validate above change with AAP dynamic inventory and provisioning callback tests
satellite-jenkins MR#1638
> [6.17.z] Add AAP2.5 parameterization in AAP provisioning callback tests

- pytest_fixtures/core/contenthosts.py
this solves an issue with reaching non ipv6 resources required in tests
> pull mode rex tests adjusted for ipv6

- robottelo/host_helpers/satellite_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18059
ncat needs `-6` parameter to listen on ipv6
> [6.17.z] Fix netcat on ipv6

- pytest_fixtures/core/contenthosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18060
this solves an issue with reaching non ipv6 resources required in tests
> [6.17.z] pull mode rex tests adjusted for ipv6

- robottelo/host_helpers/cli_factory.py
- tests/foreman/cli/test_errata.py
Failed auto-CP to 6.14.z of #18001 
Also discovered a spelling mistake in a test's name, which only exists in 6.14.z :
`cli/test_errata.py :: test_install_applicable_package_to_registerd_host` << 'registerd' spelling corrected
```
pytest: tests/foreman/cli/test_errata.py::test_apply_errata_using_default_content_view tests/foreman/cli/test_errata.py::test_update_applicable_package_using_default_content_view tests/foreman/cli/test_errata.py::test_downgrade_applicable_package_using_default_content_view tests/foreman/cli/test_errata.py::test_install_applicable_package_to_registerd_host tests/foreman/cli/test_errata.py::test_downgrading_package_shows_errata_from_library tests/foreman/cli/test_activationkey.py::test_positive_create_content_and_check_enabled …
```
> [6.14.z] Check Version is promoted to lce, instead of entire CV

- conf/upgrade.yaml.template
- robottelo/config/validators.py
- tests/upgrades/test_capsule.py
> Clean up upgrade settings

- conf/upgrade.yaml.template
- robottelo/config/validators.py
- tests/upgrades/test_capsule.py
> [6.15.z] Clean up upgrade settings

- conf/upgrade.yaml.template
- robottelo/config/validators.py
- tests/upgrades/test_capsule.py
> [6.17.z] Clean up upgrade settings

- conf/upgrade.yaml.template
- robottelo/config/validators.py
- tests/upgrades/test_capsule.py
> [6.16.z] Clean up upgrade settings

- conf/upgrade.yaml.template
- robottelo/config/validators.py
- tests/upgrades/test_capsule.py
> [6.14.z] Clean up upgrade settings

- conf/upgrade.yaml.template
- robottelo/config/validators.py
- tests/upgrades/test_capsule.py
> [6.13.z] Clean up upgrade settings

- tests/foreman/cli/test_fact.py
`networking::ip` fact is missing for IPv6 sat, which causes tests/foreman/cli/test_fact.py::test_positive_list_by_name to fail
Fix networking fact parametrization for IPv6 run by using `networking::ip6` fact for IPv6 sat, and `networking::ip` for IPv4 sat
> Fix networking fact parametrization for IPv6 run

- tests/foreman/cli/test_fact.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18071
`networking::ip` fact is missing for IPv6 sat, which causes tests/foreman/cli/test_fact.py::test_positive_list_by_name to fail
Fix networking fact parametrization for IPv6 run by using `networking::ip6` fact for IPv6 sat, and `networking::ip` for IPv4 sat
> [6.17.z] Fix networking fact parametrization for IPv6 run

- pytest_fixtures/component/repository.py
- pytest_fixtures/component/subscription.py
This PR removes lingering references to a fixture that used the fake manifest from two other pytest fixtures. The test is still failing locally for me, but the failure is unrelated to manifester. With these changes, the test successfully completes its setup.
> Remove remaining references to module_org_with_manifest

- pytest_fixtures/component/repository.py
- pytest_fixtures/component/subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18078
This PR removes lingering references to a fixture that used the fake manifest from two other pytest fixtures. The test is still failing locally for me, but the failure is unrelated to manifester. With these changes, the test successfully completes its setup.
> [6.17.z] Remove remaining references to module_org_with_manifest

- pytest_fixtures/component/repository.py
- pytest_fixtures/component/subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18078
This PR removes lingering references to a fixture that used the fake manifest from two other pytest fixtures. The test is still failing locally for me, but the failure is unrelated to manifester. With these changes, the test successfully completes its setup.
> [6.15.z] Remove remaining references to module_org_with_manifest

- pytest_fixtures/component/http_proxy.py
- tests/foreman/cli/test_http_proxy.py
We have a test for insights host registration through an HTTP proxy and it's started to fail since several recent changes.
1. After https://github.com/SatelliteQE/robottelo/pull/17950 merge the test fails in `module_sca_manifest_org` (called from `setup_http_proxy`) because `rhcloud_manifest_org` uploads the same `module_sca_manifest` into another org.
```
{'action': 'Import Manifest', 'input': "for organization 'gIMSSfWssDXj'", 'output': '', 'errors': ['org.candlepin.async.JobExecutionException: This subscription management application has already been imported by another owner.']}
```
2. In https://github.com/SatelliteQE/robottelo/pull/17342 the `rhcloud_manifest_org` and `rhcloud_activation_key` fixtures were re-targeted to `module_target_sat_insights`.
3. The test case is currently …
> Fix HTTP proxy insights tests

- pytest_fixtures/component/http_proxy.py
- tests/foreman/cli/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18065
We have a test for insights host registration through an HTTP proxy and it's started to fail since several recent changes.
1. After https://github.com/SatelliteQE/robottelo/pull/17950 merge the test fails in `module_sca_manifest_org` (called from `setup_http_proxy`) because `rhcloud_manifest_org` uploads the same `module_sca_manifest` into another org.
```
{'action': 'Import Manifest', 'input': "for organization 'gIMSSfWssDXj'", 'output': '', 'errors': ['org.candlepin.async.JobExecutionException: This subscription management application has already been imported by another owner.']}
```
2. In https://github.com/SatelliteQE/robottelo/pull/17342 the `rhcloud_manifest_org` and `rhcloud_activation_key` fixtures were …
> [6.17.z] Fix HTTP proxy insights tests

- pytest_plugins/logging_hooks.py
User needs to switch context during the test failure analysis. `robottelo.log` does not contain the actual failure the test failed with
Use one of the pytest hooks to log the exception. Take the actual failure/traceback from the [`longrepr`](https://docs.pytest.org/en/stable/reference/reference.html#pytest.TestReport.longrepr) attribute.
Adding this might bloat our log files a little depending on how long the functions in the call stack are.
Adding the following
```diff
diff --git a/tests/foreman/api/test_ping.py b/tests/foreman/api/test_ping.py
index 06d19678f..b62274693 100644
--- a/tests/foreman/api/test_ping.py
+++ b/tests/foreman/api/test_ping.py
@@ -14,6 +14,7 @@
import pytest
+from robottelo.config import settings
@pytest.mark.e2e
@pytest.mark.build_sanity
@@ -39,3 +40,4 @@ def …
```
> Log traceback in case a test phase fails

- pytest_plugins/logging_hooks.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18079
User needs to switch context during the test failure analysis. `robottelo.log` does not contain the actual failure the test failed with
Use one of the pytest hooks to log the exception. Take the actual failure/traceback from the [`longrepr`](https://docs.pytest.org/en/stable/reference/reference.html#pytest.TestReport.longrepr) attribute.
Adding this might bloat our log files a little depending on how long the functions in the call stack are.
Adding the following
```diff
diff --git a/tests/foreman/api/test_ping.py b/tests/foreman/api/test_ping.py
index 06d19678f..b62274693 100644
--- a/tests/foreman/api/test_ping.py
+++ b/tests/foreman/api/test_ping.py
@@ -14,6 +14,7 @@
import pytest
+from robottelo.config import …
```
> [6.14.z] Log traceback in case a test phase fails

- pytest_plugins/logging_hooks.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18079
User needs to switch context during the test failure analysis. `robottelo.log` does not contain the actual failure the test failed with
Use one of the pytest hooks to log the exception. Take the actual failure/traceback from the [`longrepr`](https://docs.pytest.org/en/stable/reference/reference.html#pytest.TestReport.longrepr) attribute.
Adding this might bloat our log files a little depending on how long the functions in the call stack are.
Adding the following
```diff
diff --git a/tests/foreman/api/test_ping.py b/tests/foreman/api/test_ping.py
index 06d19678f..b62274693 100644
--- a/tests/foreman/api/test_ping.py
+++ b/tests/foreman/api/test_ping.py
@@ -14,6 +14,7 @@
import pytest
+from robottelo.config import …
```
> [6.15.z] Log traceback in case a test phase fails

- pytest_fixtures/component/permissions.py
- robottelo/constants/__init__.py
Missing permissions for https://github.com/theforeman/foreman_statistics
Add tests
```
```
> Add permissions for foreman_statistics plugin

- pytest_fixtures/component/leapp_client.py
- robottelo/hosts.py
- tests/foreman/cli/test_leapp_client.py
Leapp tests are intermittently failing after reboot as it sometime takes more time to reboot the host and connect again.
Increase the timeout on wait_for_connection()
> Increase wait_for_connection timeout for leapp hosts on reboot

- tests/foreman/cli/test_remoteexecution.py
> test task search by start date

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17945
to cover SAT-29062
> [6.17.z] test task search by start date

- pytest_fixtures/component/leapp_client.py
- robottelo/hosts.py
- tests/foreman/cli/test_leapp_client.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18057
Leapp tests are intermittently failing after reboot as it sometime takes more time to reboot the host and connect again.
Increase the timeout on wait_for_connection()
> [6.17.z] Increase wait_for_connection timeout for leapp hosts on reboot

- pytest_fixtures/component/leapp_client.py
- robottelo/hosts.py
- tests/foreman/cli/test_leapp_client.py
Leapp tests are intermittently failing after reboot as it sometime takes more time to reboot the host and connect again.
Failed auto-cherrypick: https://github.com/SatelliteQE/robottelo/issues/18099 
Increase the timeout on wait_for_connection()
Parent PR: https://github.com/SatelliteQE/robottelo/pull/18057
> [6.16.z Cherrypick] Increase wait_for_connection timeout for leapp hosts on reboot

- tests/foreman/data/openssl.cnf
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17987
The custom certificates that are generated in testing should match documentation and that is being updated here: https://github.com/theforeman/foreman-documentation/pull/3700#discussion_r1990398927
> [6.17.z] Update certificate key usage to match documentation

- tests/foreman/ui/test_oscappolicy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17973
updated policy reference to one that exists across systems
> [6.15.z] fixes in scap policy tests

- pytest_fixtures/component/permissions.py
- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18086
Missing permissions for https://github.com/theforeman/foreman_statistics
Add tests
```
```
> [6.16.z] Add permissions for foreman_statistics plugin

- pytest_fixtures/component/permissions.py
- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18086
Missing permissions for https://github.com/theforeman/foreman_statistics
Add tests
```
```
> [6.17.z] Add permissions for foreman_statistics plugin

- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18139
The redhat_manifest test needs to talk to the portal
Enable the proxy for that one test
> [6.17.z] enable ipv6 proxy when running the redhat_manifest test

- pytest_fixtures/component/virtwho_config.py
- tests/foreman/virtwho/cli/test_esx_sca.py
Customer Case: SAT-28552
Use esx hyper-v and rhel content host as a guest
N/A
Satellite-jenkins: `satellite-jenkins/merge_requests/1649`
```
pytest: tests/foreman/virtwho/cli/test_esx_sca.py -k 'test_positive_change_system_puropse_SLA_for_hypervisor'
```
```
Testing started at 12:47 am ...
Launching pytest with arguments -k test_positive_change_system_puropse_SLA_for_hypervisor -vvs /home/visawant/Desktop/workspace/robottelo/tests/foreman/virtwho/cli/test_esx_sca.py --no-header --no-summary -q in /home/visawant/Desktop/workspace/robottelo
collecting ... 2025-04-03 00:49:31 - robottelo.collection - INFO - Processing test items to add testimony token markers
collected 22 items / 21 …
```
> SAT-28552 system purpose SLA attribute

- pytest_fixtures/component/virtwho_config.py
- tests/foreman/virtwho/cli/test_esx_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18122
Customer Case: SAT-28552
Use esx hyper-v and rhel content host as a guest
N/A
Satellite-jenkins: `satellite-jenkins/merge_requests/1649`
```
pytest: tests/foreman/virtwho/cli/test_esx_sca.py -k 'test_positive_change_system_puropse_SLA_for_hypervisor'
```
```
Testing started at 12:47 am ...
Launching pytest with arguments -k test_positive_change_system_puropse_SLA_for_hypervisor -vvs /home/visawant/Desktop/workspace/robottelo/tests/foreman/virtwho/cli/test_esx_sca.py --no-header --no-summary -q in /home/visawant/Desktop/workspace/robottelo
collecting ... 2025-04-03 00:49:31 - robottelo.collection - INFO - Processing …
```
> [6.17.z] SAT-28552 system purpose SLA attribute

- tests/foreman/ui/test_oscappolicy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17973
updated policy reference to one that exists across systems
> [6.14.z] fixes in scap policy tests

- pytest_fixtures/component/taxonomy.py
- tests/foreman/ui/test_subscription.py
Future date subscription doesn't populated on Subscription page
https://issues.redhat.com/browse/SAT-29203
1. Add subscription with custom validity period to stage account
2. in `robottelo/conf/manifest.yaml`, add a new manifest block
3. New fixture to create manifest with future date subscription
https://gitlab.cee.redhat.com/satelliteqe/satellite-jenkins/-/merge_requests/1612
```
pytest: tests/foreman/ui/test_subscription.py -k 'test_positive_populate_future_date_subcription'
```
> populate future date subscription in satellite

- tests/foreman/api/test_provisioning.py
In the past there were issues with build status (the value that is stored in the db) not being updated once the provisioning is done. This issue seems to have been resolved since then, it would be nice to have an automated test that verifies it.
Add an assertion that checks the in-db value rather than just relying on what host details show as that value is calculated dynamically.
- https://issues.redhat.com/browse/SAT-27869
- https://issues.redhat.com/browse/SAT-20739
> Add post-provisioning build status assertion

- pytest_fixtures/component/taxonomy.py
- tests/foreman/ui/test_subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17550
Future date subscription doesn't populated on Subscription page
https://issues.redhat.com/browse/SAT-29203
1. Add subscription with custom validity period to stage account
2. in `robottelo/conf/manifest.yaml`, add a new manifest block
3. New fixture to create manifest with future date subscription
https://gitlab.cee.redhat.com/satelliteqe/satellite-jenkins/-/merge_requests/1612
```
pytest: tests/foreman/ui/test_subscription.py -k 'test_positive_populate_future_date_subcription'
```
> [6.17.z] populate future date subscription in satellite

- tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18140
In the past there were issues with build status (the value that is stored in the db) not being updated once the provisioning is done. This issue seems to have been resolved since then, it would be nice to have an automated test that verifies it.
Add an assertion that checks the in-db value rather than just relying on what host details show as that value is calculated dynamically.
- https://issues.redhat.com/browse/SAT-27869
- https://issues.redhat.com/browse/SAT-20739
> [6.16.z] Add post-provisioning build status assertion

- tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18140
In the past there were issues with build status (the value that is stored in the db) not being updated once the provisioning is done. This issue seems to have been resolved since then, it would be nice to have an automated test that verifies it.
Add an assertion that checks the in-db value rather than just relying on what host details show as that value is calculated dynamically.
- https://issues.redhat.com/browse/SAT-27869
- https://issues.redhat.com/browse/SAT-20739
> [6.17.z] Add post-provisioning build status assertion

- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17841
After the successful completion of the Ansible job, the assertion point is updated according to the config report.
> [6.16.z] update package name during checking config report

- tests/foreman/cli/test_remoteexecution.py
https://docs.theforeman.org/nightly/Managing_Hosts/index-katello.html#setting-an-alternative-directory-for-remote-execution-jobs-in-pull-mode_managing-hosts
> custom workdir procedure adjusted for the new yggdrasil

- tests/foreman/ui/test_computeresource_vmware.py
Require below 2 changes -
1. Update the jira card in test. The first one is a duplicate and has been closed.
`from SAT-23630 to SAT-31447`
2. Others variable have three parameters, while firmware has four. Since they are used with zip, this mismatch is causing a conflict.
> Update the jira card in test and firmware_type.

- tests/foreman/cli/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18041
Add AAP2.5/latest parameterization along with legacy/AAP 2.3 to validate above change with AAP dynamic inventory and provisioning callback tests
satellite-jenkins MR#1638
> [6.16.z] Add AAP2.5 parameterization in AAP provisioning callback tests

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18189
Change the docstring of the test so it matches the teams properly.
> [6.14.z] Docstring_fix_changeContentSource

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18189
Change the docstring of the test so it matches the teams properly.
> [6.15.z] Docstring_fix_changeContentSource

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18189
Change the docstring of the test so it matches the teams properly.
> [6.17.z] Docstring_fix_changeContentSource

- tests/foreman/maintain/test_service.py
- Add coverage for SAT-30970:  verify f-m service restart works after enabling debug mode on Satellite
- [SAT-30970](https://issues.redhat.com/browse/SAT-30970)
> SAT-30970 - verify f-m service restart works after enabling debug mode on Satellite

- tests/foreman/maintain/test_service.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18188
- Add coverage for SAT-30970:  verify f-m service restart works after enabling debug mode on Satellite
- [SAT-30970](https://issues.redhat.com/browse/SAT-30970)
> [6.17.z] SAT-30970 - verify f-m service restart works after enabling debug mode on Satellite

- pytest_fixtures/component/virtwho_config.py
- tests/foreman/virtwho/api/test_esx_sca.py
- tests/foreman/virtwho/api/test_hyperv_sca.py
- tests/foreman/virtwho/api/test_libvirt_sca.py
- tests/foreman/virtwho/cli/test_esx_sca.py
- tests/foreman/virtwho/cli/test_hyperv_sca.py
- tests/foreman/virtwho/cli/test_libvirt_sca.py
- tests/foreman/virtwho/ui/test_esx_sca.py
- tests/foreman/virtwho/ui/test_hyperv_sca.py
- tests/foreman/virtwho/ui/test_libvirt_sca.py
Virt-who test suite is failing in setup while executing, because the function level fixture `deploy_type_*` internally execute deploy by mechanism which ultimately install virtwho package on satellite server, due to missing appstream repo test execution failing in setup part.
Use of predefined fixture `register_sat_and_enable_aps_repo` in test definition where `deploy_type_*` fixture is being used.
Updated - **Apr 9th 2025**: As per suggestion, we are using `register_sat_and_enable_aps_repo` as a module scope fixture inside `deploy_type_*` fixture.
No
Test are not passing 100 % but using fixture test failure count drop, so I not expecting to run PRT over this partial fix as this is very first step towrds fixting broken test suite. Attaching local test execution result for sample.
``` …
```
> neccessary fixture in test definition

- pytest_fixtures/component/virtwho_config.py
- tests/foreman/virtwho/api/test_esx_sca.py
- tests/foreman/virtwho/api/test_hyperv_sca.py
- tests/foreman/virtwho/api/test_libvirt_sca.py
- tests/foreman/virtwho/cli/test_esx_sca.py
- tests/foreman/virtwho/cli/test_hyperv_sca.py
- tests/foreman/virtwho/cli/test_libvirt_sca.py
- tests/foreman/virtwho/ui/test_esx_sca.py
- tests/foreman/virtwho/ui/test_hyperv_sca.py
- tests/foreman/virtwho/ui/test_libvirt_sca.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18172
Virt-who test suite is failing in setup while executing, because the function level fixture `deploy_type_*` internally execute deploy by mechanism which ultimately install virtwho package on satellite server, due to missing appstream repo test execution failing in setup part.
Use of predefined fixture `register_sat_and_enable_aps_repo` in test definition where `deploy_type_*` fixture is being used.
Updated - **Apr 9th 2025**: As per suggestion, we are using `register_sat_and_enable_aps_repo` as a module scope fixture inside `deploy_type_*` fixture.
No
Test are not passing 100 % but using fixture test failure count drop, so I not expecting to run PRT over this partial fix as this is very first step towrds fixting broken …
> [6.17.z] neccessary fixture in test definition

- robottelo/constants/__init__.py
- robottelo/host_helpers/api_factory.py
- tests/foreman/api/test_errata.py
- tests/foreman/cli/test_errata.py
- tests/foreman/ui/test_errata.py
_UI_: From #18037 (wait_for applicability recalculate tasks)
- `test_end_to_end` , `test_positive_apply_for_all_hosts` , `test_positive_filtered_errata_status_installable_param`
_CLI_: Address failures in helper method (find/invoke/wait_for applicability recalculate tasks):
- 15+ failing cases in  `start_and_wait_errata_recalculate()`
_API_: one test failing in setup, and enhanced another already impacted by changes
- `test_positive_get_diff_for_cv_envs`: Use module fixtures instead of incorrectly setup components
- minor enhancements to `test_positive_filter_errata_type_other`
--------------------------------------------------------------------------------------------------------------------
**UI / test_errata.py** :: test_end_to_end , …
> Errata 6.17.0 signoff fixes

- pytest_fixtures/component/rh_cloud.py
- tests/foreman/ui/test_rhcloud_insights.py
- Add tests to verify simultaneous remediation of 2 Insights hosts via the UI:
- `test_rhcloud_insights_remediate_multiple_hosts[rhel10-hosted]`
- `test_rhcloud_insights_remediate_multiple_hosts[rhel10-local]`
- Added new `rhel_insights_vms` fixture, used by the new tests, to return two registered Insights hosts registered to the Satellite.
- Add `insights-client --diagnosis` and `insights-client --version` checks to the e2e tests.
SAT-32473
In the PRT test results below, 1 test failed during broker checkout, which is unrelated to the changes in this PR.
> Insights e2e test updates

- .github/CODEOWNERS
Component fixtures are managed by component teams, but they require tier-2 reviews for some reason, which shouldn't be necessary.
Scope the component fixtures for tier-1 (equals team reviews) while keeping tier-2 for core fixtures.
> Relax component fixtures tiering

- .github/CODEOWNERS
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18143
Component fixtures are managed by component teams, but they require tier-2 reviews for some reason, which shouldn't be necessary.
Scope the component fixtures for tier-1 (equals team reviews) while keeping tier-2 for core fixtures.
> [6.15.z] Relax component fixtures tiering

- .github/CODEOWNERS
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18143
Component fixtures are managed by component teams, but they require tier-2 reviews for some reason, which shouldn't be necessary.
Scope the component fixtures for tier-1 (equals team reviews) while keeping tier-2 for core fixtures.
> [6.16.z] Relax component fixtures tiering

- conf/ldap.yaml.template
- pytest_fixtures/component/satellite_auth.py
- robottelo/config/validators.py
- robottelo/hosts.py
Fixed issues with SSSD on ipv4-only hosts and too long hostnames on ipv6 machines for AD to handle.
> Fix IPv6 issues in IDM and AD setup

- conf/ldap.yaml.template
- pytest_fixtures/component/satellite_auth.py
- robottelo/config/validators.py
- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18166
Fixed issues with SSSD on ipv4-only hosts and too long hostnames on ipv6 machines for AD to handle.
> [6.17.z] Fix IPv6 issues in IDM and AD setup

- tests/foreman/destructive/test_rename.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18142
`test_positive_rename_satellite` test fails with AssertionError:
```
tests/foreman/destructive/test_rename.py:117: in test_positive_rename_satellite
assert result.status != 0, 'there are remaining instances of the old hostname'
E   AssertionError: there are remaining instances of the old hostname
E   assert 0 != 0
E    +  where 0 = stdout:\n/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt:# satellite.redhat.com\n/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem:# satellite.redhat.com\n\nstderr:\n\nstatus: 0.status 
```
Refine the assert so it doesn't trigger false alerts
[SAT-32220](https://issues.redhat.com/browse/SAT-32220)
> [6.14.z] Fix test_positive_rename_satellite to assert old hostname absence better

- .github/CODEOWNERS
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18143
Component fixtures are managed by component teams, but they require tier-2 reviews for some reason, which shouldn't be necessary.
Scope the component fixtures for tier-1 (equals team reviews) while keeping tier-2 for core fixtures.
> [6.17.z] Relax component fixtures tiering

- tests/foreman/ui/test_http_proxy.py
In 6.17 the HTTP proxy was generally lower-cased, which makes related UI tests to fail.
This PR updates the tests.
Requires https://github.com/SatelliteQE/airgun/pull/1797
```
pytest: tests/foreman/ui/test_http_proxy.py -k 'check_http_proxy_value_repository_details or assign_http_proxy_to_products_repositories'
airgun: 1797
env:
ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.17.0'
ROBOTTELO_server__deploy_arguments__deploy_snap_version: '7.0'
```
> Lowercase HTTP proxy in UI tests

- tests/foreman/destructive/test_rename.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18142
`test_positive_rename_satellite` test fails with AssertionError:
```
tests/foreman/destructive/test_rename.py:117: in test_positive_rename_satellite
assert result.status != 0, 'there are remaining instances of the old hostname'
E   AssertionError: there are remaining instances of the old hostname
E   assert 0 != 0
E    +  where 0 = stdout:\n/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt:# satellite.redhat.com\n/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem:# satellite.redhat.com\n\nstderr:\n\nstatus: 0.status 
```
Refine the assert so it doesn't trigger false alerts
[SAT-32220](https://issues.redhat.com/browse/SAT-32220)
> [6.15.z] Fix test_positive_rename_satellite to assert old hostname absence better

- tests/foreman/cli/test_repositories.py
It looks like the latest RHEL8 templates of 6.16 do not include the `jq` utility anymore
(comparing `tpl-satellite-6.16.5-1.0-rhel-8.10` vs `tpl-satellite-6.16.4-1.0-rhel-8.10`)
which makes this test to fail with `ValueError: invalid literal for int() with base 10: ''` since stdout returns `''` and stderr `bash: jq: command not found`.
We should not rely on the `jq` presence and use `json.loads` instead.
```
env:
ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.16.5'
ROBOTTELO_server__deploy_arguments__deploy_snap_version: '1.0'
ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
```
> Fix test_purge_pulp_tasks by removing jq dependency

- tests/foreman/cli/test_repositories.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18213
It looks like the latest RHEL8 templates of 6.16 do not include the `jq` utility anymore
(comparing `tpl-satellite-6.16.5-1.0-rhel-8.10` vs `tpl-satellite-6.16.4-1.0-rhel-8.10`)
which makes this test to fail with `ValueError: invalid literal for int() with base 10: ''` since stdout returns `''` and stderr `bash: jq: command not found`.
We should not rely on the `jq` presence and use `json.loads` instead.
```
env:
ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.16.5'
ROBOTTELO_server__deploy_arguments__deploy_snap_version: '1.0'
ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
```
> [6.16.z] Fix test_purge_pulp_tasks by removing jq dependency

- tests/foreman/ui/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18222
In 6.17 the HTTP proxy was generally lower-cased, which makes related UI tests to fail.
This PR updates the tests.
Requires https://github.com/SatelliteQE/airgun/pull/1797
```
pytest: tests/foreman/ui/test_http_proxy.py -k 'check_http_proxy_value_repository_details or assign_http_proxy_to_products_repositories'
airgun: 1797
env:
ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.17.0'
ROBOTTELO_server__deploy_arguments__deploy_snap_version: '7.0'
```
> [6.17.z] Lowercase HTTP proxy in UI tests

- tests/foreman/cli/test_repositories.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18213
It looks like the latest RHEL8 templates of 6.16 do not include the `jq` utility anymore
(comparing `tpl-satellite-6.16.5-1.0-rhel-8.10` vs `tpl-satellite-6.16.4-1.0-rhel-8.10`)
which makes this test to fail with `ValueError: invalid literal for int() with base 10: ''` since stdout returns `''` and stderr `bash: jq: command not found`.
We should not rely on the `jq` presence and use `json.loads` instead.
```
env:
ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.16.5'
ROBOTTELO_server__deploy_arguments__deploy_snap_version: '1.0'
ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '8'
```
> [6.17.z] Fix test_purge_pulp_tasks by removing jq dependency

- robottelo/constants/__init__.py
- robottelo/host_helpers/api_factory.py
- tests/foreman/api/test_errata.py
- tests/foreman/cli/test_errata.py
- tests/foreman/ui/test_errata.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18058
_UI_: From #18037 (wait_for applicability recalculate tasks)
- `test_end_to_end` , `test_positive_apply_for_all_hosts` , `test_positive_filtered_errata_status_installable_param`
_CLI_: Address failures in helper method (find/invoke/wait_for applicability recalculate tasks):
- 15+ failing cases in  `start_and_wait_errata_recalculate()`
_API_: one test failing in setup, and enhanced another already impacted by changes
- `test_positive_get_diff_for_cv_envs`: Use module fixtures instead of incorrectly setup components
- minor enhancements to `test_positive_filter_errata_type_other`
--------------------------------------------------------------------------------------------------------------------
**UI / test_errata.py** :: …
> [6.17.z] Errata 6.17.0 signoff fixes

- robottelo/hosts.py
this reflects the change of plan, previously new ygg was expected to be in rhel 9.6+ versions, now it is rhel10 only
> new yggdrasil rhel10 only

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18215
this reflects the change of plan, previously new ygg was expected to be in rhel 9.6+ versions, now it is rhel10 only
> [6.17.z] new yggdrasil rhel10 only

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18215
this reflects the change of plan, previously new ygg was expected to be in rhel 9.6+ versions, now it is rhel10 only
> [6.16.z] new yggdrasil rhel10 only

- tests/foreman/destructive/test_rename.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18142
`test_positive_rename_satellite` test fails with AssertionError:
```
tests/foreman/destructive/test_rename.py:117: in test_positive_rename_satellite
assert result.status != 0, 'there are remaining instances of the old hostname'
E   AssertionError: there are remaining instances of the old hostname
E   assert 0 != 0
E    +  where 0 = stdout:\n/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt:# satellite.redhat.com\n/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem:# satellite.redhat.com\n\nstderr:\n\nstatus: 0.status 
```
Refine the assert so it doesn't trigger false alerts
[SAT-32220](https://issues.redhat.com/browse/SAT-32220)
> [6.17.z] Fix test_positive_rename_satellite to assert old hostname absence better

- pytest_fixtures/component/rh_cloud.py
- tests/foreman/ui/test_rhcloud_insights.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18133
- Add tests to verify simultaneous remediation of 2 Insights hosts via the UI:
- `test_rhcloud_insights_remediate_multiple_hosts[rhel10-hosted]`
- `test_rhcloud_insights_remediate_multiple_hosts[rhel10-local]`
- Added new `rhel_insights_vms` fixture, used by the new tests, to return two registered Insights hosts registered to the Satellite.
- Add `insights-client --diagnosis` and `insights-client --version` checks to the e2e tests.
SAT-32473
In the PRT test results below, 1 test failed during broker checkout, which is unrelated to the changes in this PR.
> [6.17.z] Insights e2e test updates

- tests/foreman/api/test_acs.py
- tests/foreman/cli/test_acs.py
Since sometime in 6.13.z or perhaps prior, CLI & API `test_positive_CRUD_all_types` has been skipping 2 cases,
for invalid parametrization combination ('rhui-file'). Suggest we remove, as it can be ignored rather than collected and skipped, which has always prevented 100% pass rate in CI.
use list comprehension in parametrization of ACS type and Content type, ignoring if combination is ('rhui', 'file')
```
pytest: tests/foreman/api/test_acs.py::test_positive_CRUD_all_types tests/foreman/cli/test_acs.py::test_positive_CRUD_all_types
```
> ACS - remove invalid parametrization combination (rhui-file)

- tests/foreman/api/test_acs.py
- tests/foreman/cli/test_acs.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18247
Since sometime in 6.13.z or perhaps prior, CLI & API `test_positive_CRUD_all_types` has been skipping 2 cases,
for invalid parametrization combination ('rhui-file'). Suggest we remove, as it can be ignored rather than collected and skipped, which has always prevented 100% pass rate in CI.
use list comprehension in parametrization of ACS type and Content type, ignoring if combination is ('rhui', 'file')
```
pytest: tests/foreman/api/test_acs.py::test_positive_CRUD_all_types tests/foreman/cli/test_acs.py::test_positive_CRUD_all_types
```
> [6.17.z] ACS - remove invalid parametrization combination (rhui-file)

- tests/foreman/api/test_acs.py
- tests/foreman/cli/test_acs.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18247
Since sometime in 6.13.z or perhaps prior, CLI & API `test_positive_CRUD_all_types` has been skipping 2 cases,
for invalid parametrization combination ('rhui-file'). Suggest we remove, as it can be ignored rather than collected and skipped, which has always prevented 100% pass rate in CI.
use list comprehension in parametrization of ACS type and Content type, ignoring if combination is ('rhui', 'file')
```
pytest: tests/foreman/api/test_acs.py::test_positive_CRUD_all_types tests/foreman/cli/test_acs.py::test_positive_CRUD_all_types
```
> [6.16.z] ACS - remove invalid parametrization combination (rhui-file)

- tests/foreman/api/test_acs.py
- tests/foreman/cli/test_acs.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18247
Since sometime in 6.13.z or perhaps prior, CLI & API `test_positive_CRUD_all_types` has been skipping 2 cases,
for invalid parametrization combination ('rhui-file'). Suggest we remove, as it can be ignored rather than collected and skipped, which has always prevented 100% pass rate in CI.
use list comprehension in parametrization of ACS type and Content type, ignoring if combination is ('rhui', 'file')
```
pytest: tests/foreman/api/test_acs.py::test_positive_CRUD_all_types tests/foreman/cli/test_acs.py::test_positive_CRUD_all_types
```
> [6.15.z] ACS - remove invalid parametrization combination (rhui-file)

- tests/foreman/destructive/test_rename.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18142
`test_positive_rename_satellite` test fails with AssertionError:
```
tests/foreman/destructive/test_rename.py:117: in test_positive_rename_satellite
assert result.status != 0, 'there are remaining instances of the old hostname'
E   AssertionError: there are remaining instances of the old hostname
E   assert 0 != 0
E    +  where 0 = stdout:\n/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt:# satellite.redhat.com\n/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem:# satellite.redhat.com\n\nstderr:\n\nstatus: 0.status 
```
Refine the assert so it doesn't trigger false alerts
[SAT-32220](https://issues.redhat.com/browse/SAT-32220)
> [6.16.z] Fix test_positive_rename_satellite to assert old hostname absence better

- tests/foreman/api/test_permission.py
If there are more than 20 permissions for a certain resource type they are not found
get all permissions for certain resource type
> Ensure all permissions for certain resource type are found

- tests/foreman/ui/test_dashboard.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18042
diffrent message on 6.17 and on ipv6 as well
> [6.17.z] dashboard asserts updated

- tests/foreman/cli/test_ansible.py
closes https://github.com/SatelliteQE/robottelo/issues/18147
closes https://github.com/SatelliteQE/robottelo/issues/18085
> missing cs tags

- tests/foreman/api/test_permission.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18245
If there are more than 20 permissions for a certain resource type they are not found
get all permissions for certain resource type
> [6.16.z] Ensure all permissions for certain resource type are found

- tests/foreman/api/test_permission.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18245
If there are more than 20 permissions for a certain resource type they are not found
get all permissions for certain resource type
> [6.17.z] Ensure all permissions for certain resource type are found

- tests/foreman/cli/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18260
closes https://github.com/SatelliteQE/robottelo/issues/18147
closes https://github.com/SatelliteQE/robottelo/issues/18085
> [6.16.z] missing cs tags

- tests/foreman/cli/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18260
closes https://github.com/SatelliteQE/robottelo/issues/18147
closes https://github.com/SatelliteQE/robottelo/issues/18085
> [6.17.z] missing cs tags

- tests/foreman/cli/test_ansible.py
Added `?search=` to the endpoint to retrieve the particular host, allowing us to perform assertions against our specific host.
This change was made to address a failure occurring during the upgrade test. In upgrade scenarios, multiple hosts may already exist, leading to conflicts. Previously, the test only fetched hosts from the first page, and if the expected host was on a subsequent page, it would not be found. By specifying the `search` parameter, we ensure our specific host will fetch from across the page, which should prevent such issues.
> Retrieve the correct host info from the inventories.

- tests/foreman/cli/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18251
Added `?search=` to the endpoint to retrieve the particular host, allowing us to perform assertions against our specific host.
This change was made to address a failure occurring during the upgrade test. In upgrade scenarios, multiple hosts may already exist, leading to conflicts. Previously, the test only fetched hosts from the first page, and if the expected host was on a subsequent page, it would not be found. By specifying the `search` parameter, we ensure our specific host will fetch from across the page, which should prevent such issues.
> [6.17.z] Retrieve the correct host info from the inventories.

- tests/foreman/ui/test_rhcloud_inventory.py
When `subscription_connection_enabled` setting is set to `false` the 
- Automatic inventory upload switch
- Configure cloud connector button
- Sync all inventory status button
and these descriptions 
```
To enable this reporting for all Foreman organizations, set Automatic inventory upload to on. The data will be reported automatically once per day.
To manually upload the data for a specific organization, select an organization and click Generate and upload report.
```
are hidden.
This test checks that the `subscription_connection_enabled` setting is properly reflected in the Satellite UI.
Related Airgun PR: https://github.com/SatelliteQE/airgun/pull/1800
Related foreman PR: https://github.com/theforeman/foreman_rh_cloud/pull/976
```
pytest: …
```
> Check UI reaction to subscription_connection_enabled setting

- tests/foreman/sys/test_fam.py
oVirt/RHV is not properly set up in IPv6 environment
Skip related tests
> Skip oVirt/RHV tests on IPv6 setups

- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18284
oVirt/RHV is not properly set up in IPv6 environment
Skip related tests
> [6.17.z] Skip oVirt/RHV tests on IPv6 setups

- tests/foreman/longrun/test_oscap.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18262
checking that the cron file is created as expected during smart proxy openscap setup and that the openscap send comand executes
> [6.17.z] add coverage for SAT-28826

- .github/CODEOWNERS
- tests/new_upgrades/test_activation_key.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16772
The activation key upgrade scenario is currently failing and uses the old upgrade test format.
Convert the test to the new format using the `shared_resource` framework and converting the pre-upgrade test to a pytest fixture.
Remove entitlement-related steps as entitlement mode has been removed from Satellite 6.16+. 
This test currently fails on the final `org.delete()` step due to SAT-28990.
> [6.17.z] Convert activation key upgrade scenario to new format

- tests/foreman/destructive/test_capsule_loadbalancer.py
In `6.18` we are going to support the container content available through a load-balanced setup (HA proxy + several capsules). We already have load-balanced setup for host registration and rpm installation and we could extend it to cover the container content.
This PR introduces this extension and adds an E2E test case for that.
https://issues.redhat.com/browse/SAT-30741
```
pytest: tests/foreman/destructive/test_capsule_loadbalancer.py -k test_loadbalancer_container
```
> Add a test case for loadbalanced container content

- pytest_fixtures/core/contenthosts.py
- tests/foreman/api/test_capsulecontent.py
When running `podman login` at a host in an interactive shell via TTY, the login succeeds even when no credentials are provided (see the related issue below).
Now, I would like to add a test coverage for this case, but it seems the robottelo's interactive shell (uses `ssh2_python` by default, but behaves the same with `hussh`) works differently - it fails with a different error (while it is expected to succeed on unfixed snap 95 or fail on fixed snap 96 with `invalid username/password`):
```
Error: getting username and password: reading password: inappropriate ioctl for device
```
Which is basically the same validation error we get when we pipe the password with:
```
```
Fortunately there is a better way to check the interactive login using the `expect` command (thanks @ianballou for that …
> Add a test case for podman login without password

- tests/foreman/api/test_ansible.py
Currently `test_positive_ansible_job_on_multiple_host` uses  `rhel9_contenthost`, `rhel8_contenthost`, `rhel7_contenthost` fixtures which aren't parametrized for IPv6 run, which fails while communicating to the hosts that checkouts which is IPv4, and I found this old issue https://github.com/SatelliteQE/robottelo/issues/11568 which advises to use `Broker.multi_manager` here for parallel host checkouts to improve test execution, so looking to resolve this too with this fix.
Using `Broker.multi_manager` to fix ansible test checkout for multiple hosts, along with `deploy_network_type` arg for host checkout as per `settings.server.is_ipv6` setting
Fixes https://github.com/SatelliteQE/robottelo/issues/11568
> Using Broker.multi_manager to fix ansible test checkout for multiple hosts

- tests/foreman/cli/test_ansible.py
Ansible provisioning callback is failing because the job is not completed before the next code steps are executed.
Fix the test by using wait_for to check the job status before the next code steps are executed.
> Fix ansible provisioning callback test

- tests/foreman/api/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18231
Currently `test_positive_ansible_job_on_multiple_host` uses  `rhel9_contenthost`, `rhel8_contenthost`, `rhel7_contenthost` fixtures which aren't parametrized for IPv6 run, which fails while communicating to the hosts that checkouts which is IPv4, and I found this old issue https://github.com/SatelliteQE/robottelo/issues/11568 which advises to use `Broker.multi_manager` here for parallel host checkouts to improve test execution, so looking to resolve this too with this fix.
Using `Broker.multi_manager` to fix ansible test checkout for multiple hosts, along with `deploy_network_type` arg for host checkout as per `settings.server.is_ipv6` setting
Fixes https://github.com/SatelliteQE/robottelo/issues/11568
> [6.17.z] Using Broker.multi_manager to fix ansible test checkout for multiple hosts

- pytest_fixtures/core/contenthosts.py
- tests/foreman/ui/test_ansible.py
Currently, `test_positive_ansible_job_with_verbose_stdout ` uses hosts checkout from `registered_hosts` fixture which isn't parametrized for IPv6 run, which fails while communicating to the hosts that checkouts which is IPv4, and after checking I found this is a only test using this fixture and we've similar `rex_contenthosts` fixture with same logic but with IPv6 parametrization support, so it would be great to get rid of this redundant fixture. 
Use rex_contenthosts fixture in ansible verbosity test, and get rid of `registered_hosts` fixture which is redundant
https://github.com/SatelliteQE/airgun/pull/1801
> Use rex_contenthosts fixture in ansible verbosity test

- tests/foreman/cli/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18287
Ansible provisioning callback is failing because the job is not completed before the next code steps are executed.
Fix the test by using wait_for to check the job status before the next code steps are executed.
> [6.17.z] Fix ansible provisioning callback test

- pytest_fixtures/core/contenthosts.py
- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18253
Fixes: #18313 
Currently, test_positive_ansible_job_with_verbose_stdout  uses hosts checkout from registered_hosts fixture which isn't parametrized for IPv6 run, which fails while communicating to the hosts that checkouts which is IPv4, and after checking I found this is a only test using this fixture and we've similar rex_contenthosts fixture with same logic but with IPv6 parametrization support, so it would be great to get rid of this redundant fixture.
Use rex_contenthosts fixture in ansible verbosity test, and get rid of registered_hosts fixture which is redundant
https://github.com/SatelliteQE/airgun/pull/1801
> [6.14.z] Use rex_contenthosts fixture in ansible verbosity test

- pytest_fixtures/core/contenthosts.py
- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18253
Currently, `test_positive_ansible_job_with_verbose_stdout ` uses hosts checkout from `registered_hosts` fixture which isn't parametrized for IPv6 run, which fails while communicating to the hosts that checkouts which is IPv4, and after checking I found this is a only test using this fixture and we've similar `rex_contenthosts` fixture with same logic but with IPv6 parametrization support, so it would be great to get rid of this redundant fixture. 
Use rex_contenthosts fixture in ansible verbosity test, and get rid of `registered_hosts` fixture which is redundant
https://github.com/SatelliteQE/airgun/pull/1801
> [6.16.z] Use rex_contenthosts fixture in ansible verbosity test

- pytest_fixtures/core/contenthosts.py
- tests/foreman/ui/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18253
Currently, `test_positive_ansible_job_with_verbose_stdout ` uses hosts checkout from `registered_hosts` fixture which isn't parametrized for IPv6 run, which fails while communicating to the hosts that checkouts which is IPv4, and after checking I found this is a only test using this fixture and we've similar `rex_contenthosts` fixture with same logic but with IPv6 parametrization support, so it would be great to get rid of this redundant fixture. 
Use rex_contenthosts fixture in ansible verbosity test, and get rid of `registered_hosts` fixture which is redundant
https://github.com/SatelliteQE/airgun/pull/1801
> [6.17.z] Use rex_contenthosts fixture in ansible verbosity test

- robottelo/host_helpers/satellite_mixins.py
ssh-keyscan is broken on FIPS-enabled systems (See: https://issues.redhat.com/browse/RHEL-88565)
Use `StrictHostKeyChecking accept-new` which just accepts the first seen key instead of prompting, thus eliminating the need for `ssh-keyscan`.
This PR also improves the logging of the assertion which was required to debug this issue.
> use "StrictHostKeyChecking accept-new" instead of ssh-keyscan

- tests/foreman/ui/test_contenthost.py
This PR verifies SAT-22655.
It tests that the 'true'/'false' string is also
interpreted as a boolean true/false as it is happening for 't'/'f' string\
pytest: tests/foreman/ui/test_contenthost.py -k 'test_content_hosts_bool_in_query'
> [SAT-22655] Test ContentHost query with Bool

- pytest_fixtures/component/provision_pxe.py
- robottelo/host_helpers/satellite_mixins.py
- tests/foreman/api/test_computeresource_libvirt.py
- tests/foreman/api/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18285
EL10 Secureboot provisioning tests are currently failing as it require changes suggested in RHEL-75490
Fix EL10 Secureboot provisioning tests as per changes suggested in RHEL-75490
> [6.17.z] Fix EL10 Secureboot provisioning tests as per RHEL-75490

- tests/foreman/ui/test_ansible.py
- tests/foreman/ui/test_leapp_client.py
- tests/foreman/ui/test_remoteexecution.py
job template select now allows typing in for search, airgun being confused
the easiest way to solve this is to use the existing job_template_text_input structure from airgun when creating jobs
> rex tests adjusted for pf5 changes

- tests/foreman/ui/test_rhcloud_insights.py
When the test clicks "Remediate" or "Sync remediations" (hosted Insights only), the button submits a POST API call to Satellite, to create a Satellite Task or Job that will perform the actual action. If the test exits the session context manager too soon after clicking the button, however, then the API call gets canceled, and the task or job doesn't get created.
Add UI verification that the remediation or sync is completed, instead of exiting the UI session and calling the API.
Plus a few other small fixes:
- Remove `silent_failure=True` from `wait_for` calls. If these verification steps fail, the test should also fail at that point.
- Add checks on the length of returned results, so that empty results will fail the test.
- Don't run `dnf` commands on RHEL 7 hosts.
SAT-33262
> Fix UI Insights remediation tests

- tests/foreman/api/test_repositories.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18334
Automate SAT-32622 , changing the 'Unprotected' status of any repository fails with internal sever error 500.
For Stream and 6.17.z , but will still fail in 6.17.0 latest , Awaiting next z stream
*update*: recommend we CP to 6.16.z & 6.15.z as well, since this is a PIT-like case and simple enough coverage.
```
pytest: tests/foreman/api/test_repositories.py::test_unprotected_status_repo_create_and_update
```
> [6.15.z] [SAT-32622] Test create & update repository's 'Unprotected' status

- .github/CODEOWNERS
- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_discovery.py
As part of the current upgrade scenarios refactor, this PR converts the Discovery pre-upgrade scenario to a Pytest fixture and modifies the pre- and post-upgrade scenarios to use the `SharedResource` framework.
> Convert Discovery upgrade scenario to new format

- .github/CODEOWNERS
- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_discovery.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16898
As part of the current upgrade scenarios refactor, this PR converts the Discovery pre-upgrade scenario to a Pytest fixture and modifies the pre- and post-upgrade scenarios to use the `SharedResource` framework.
> [6.16.z] Convert Discovery upgrade scenario to new format

- pytest_fixtures/component/permissions.py
https://github.com/SatelliteQE/robottelo/pull/18246 breaks perms tests for satellites without  rubygem-foreman_snapshot_management
adding the needed changes to perm fixture
> amend expected perms for snapshot mgmt permissions

- pytest_fixtures/component/permissions.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18363
https://github.com/SatelliteQE/robottelo/pull/18246 breaks perms tests for satellites without  rubygem-foreman_snapshot_management
adding the needed changes to perm fixture
> [6.16.z] amend expected perms for snapshot mgmt permissions

- pytest_fixtures/component/permissions.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18363
https://github.com/SatelliteQE/robottelo/pull/18246 breaks perms tests for satellites without  rubygem-foreman_snapshot_management
adding the needed changes to perm fixture
> [6.17.z] amend expected perms for snapshot mgmt permissions

- tests/foreman/ui/test_rhcloud_inventory.py
Extension of https://github.com/SatelliteQE/robottelo/pull/18319
We also need to check generate button label.
Needs: https://github.com/SatelliteQE/airgun/pull/1838
```
pytest: tests/foreman/ui/test_rhcloud_inventory.py -k 'test_subscription_connection_settings_ui_behavior'
airgun: 1838
theforeman:
foreman_rh_cloud: 980
```
> Extension Of SubsConn Test

- tests/foreman/api/test_provisioning.py
EL10 Fips provisioning tests are failing due to `fips_mode_setup` command not found.
Update the test to assert directly in the `/proc/sys/crypto/fips_enabled` for check the fips status for all RHEL versions
> Fix fips provisioning test

- robottelo/cli/insights.py
- tests/foreman/cli/test_rhcloud_inventory.py
https://github.com/theforeman/hammer-cli-foreman-rh-cloud/tree/master
hammer cli foreman rhcloud recently got added to the sat stream. We needed tests for the following commands
- `hammer insights inventory generate-report --organization-id=100`
- `hammer insights inventory generate-report --organization-id=100 --no-upload`
- `hammer insights inventory download-report --organization-id=100 `
- `hammer insights inventory sync--organization-id=100 `
- `hammer insights cloud-connector enable`
This PR attempts to address that
> Add cli tests for the new hammer insights commands

- tests/foreman/api/test_provisioning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18333
EL10 Fips provisioning tests are failing due to `fips_mode_setup` command not found.
Update the test to assert directly in the `/proc/sys/crypto/fips_enabled` for check the fips status for all RHEL versions
> [6.17.z] Fix fips provisioning test

- tests/foreman/maintain/test_advanced.py
- tests/foreman/ui/test_documentation_links.py
- `test_positive_satellite_repositories_setup` and `test_positive_capsule_repositories_setup` are failing because of the wrong code block being run.
- Fix the code logic
- SAT-33469
> Fix foreman-maintain repository setup tests

- pytest_fixtures/component/provision_pxe.py
- pytest_fixtures/core/broker.py
- robottelo/cli/discoveredhost.py
- tests/foreman/api/test_computeresource_vmware.py
- tests/foreman/api/test_discoveredhost.py
- tests/foreman/cli/test_discoveredhost.py
Discovery provisioning tests failing with host not found error.
FIxed few issues.
> Discovery CLI fixes

- pytest_fixtures/component/provision_pxe.py
- pytest_fixtures/core/broker.py
- robottelo/cli/discoveredhost.py
- tests/foreman/api/test_computeresource_vmware.py
- tests/foreman/api/test_discoveredhost.py
- tests/foreman/cli/test_discoveredhost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18297
Discovery provisioning tests failing with host not found error.
FIxed few issues.
> [6.17.z] Discovery CLI fixes

- tests/foreman/ui/test_host.py
The `test_positive_tracer_enable_reload ` was failing due to some UI issues
While fixing this, I also did a small refactor.
Before the test was trying to
a) wait for `Traces are being enabled` string to appear and then disappear
b) and then just check that `No applications to restart` is present
imo `a)` is not necessary to check in the UI and it was not reliable, thus I changed it for wait_for_tasks which waits for the task to finish before continuing.
Needs Airgun: https://github.com/SatelliteQE/airgun/pull/1843
```
pytest: tests/foreman/ui/test_host.py -k 'test_positive_tracer_enable_reload'
airgun: 1843
```
> Tracer UI test refactor

- tests/foreman/maintain/test_advanced.py
- tests/foreman/ui/test_documentation_links.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18383
- `test_positive_satellite_repositories_setup` and `test_positive_capsule_repositories_setup` are failing because of the wrong code block being run.
- Fix the code logic
- SAT-33469
> [6.17.z] Fix foreman-maintain repository setup tests

- .github/CODEOWNERS
- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_hostgroup.py
As part of the current upgrade scenarios refactor, this PR converts the host group upgrade scenario to use the `SharedResource` framework, converts the pre-upgrade test to a Pytest fixture, and adds a Satellite upgrade fixture to support these changes.
> Convert host group upgrade scenario to new format

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_performance_tuning.py
As part of the current upgrade scenarios refactor, this PR converts the performance tuning scenario to use the `SharedResource` framework, converts the pre-upgrade test to a Pytest fixture, and adds a Satellite upgrade fixture for this scenario.
> Convert perf tuning upgrade scenario to new format

- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/cli/test_flatpak.py
- tests/foreman/cli/test_satellitesync.py
In https://github.com/Katello/katello/pull/11372 the `Flatpak - Install application on host` template has been extended with a new option to run against a GUI or GUI-less system and uses a different dbus command under the hood. We need to update existing tests using this job template accordingly.
This PR.
https://issues.redhat.com/browse/SAT-31357
```
pytest: tests/foreman/cli/test_flatpak.py -k 'via_library or via_cv'
```
> Update Flatpak install REX job parameter

- pytest_fixtures/component/permissions.py
- robottelo/constants/__init__.py
missing permissions for foreman_monitoring plugin
https://github.com/theforeman/foreman_monitoring/blob/master/lib/foreman_monitoring/engine.rb#L46
add permissions
> Add permissions for formean_monitoring plugin

- pytest_fixtures/component/permissions.py
- robottelo/constants/__init__.py
missing foreman_salt permission
https://github.com/theforeman/foreman_salt/blob/master/lib/foreman_salt/plugin.rb#L110
add permissions
> Add missing permissions for foreman_salt plugin

- tests/new_upgrades/test_hostcontent.py
This PR converts the content host upgrade scenario to use the shared_resource framework. It removes the existing class structure of the module, converts the pre-upgrade test to a fixture, and moves existing fixtures inherited by the old tests to the body of the pre-upgrade fixture to ensure isolation from the main Robottelo fixture stack.
> Convert content host scenario to new format

- tests/new_upgrades/test_hostcontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18294
This PR converts the content host upgrade scenario to use the shared_resource framework. It removes the existing class structure of the module, converts the pre-upgrade test to a fixture, and moves existing fixtures inherited by the old tests to the body of the pre-upgrade fixture to ensure isolation from the main Robottelo fixture stack.
> [6.17.z] Convert content host scenario to new format

- pytest_fixtures/component/permissions.py
- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18435
missing permissions for foreman_monitoring plugin
https://github.com/theforeman/foreman_monitoring/blob/master/lib/foreman_monitoring/engine.rb#L46
add permissions
> [6.16.z] Add permissions for formean_monitoring plugin

- robottelo/hosts.py
- tests/foreman/api/test_http_proxy.py
[SAT-26741](https://issues.redhat.com/browse/SAT-26741) needs some automation.
This PR adds that coverage.
```
pytest: tests/foreman/api/test_http_proxy.py -k test_refresh_updates_remotes_proxy
```
> Add a test case for SAT-26741

- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18461
RHEL9 kickstart version was updated to RHEL 9.6, we currently have 9.5 in the constants
Updating the RHEL9 Kickstart version to 9.6
> [6.17.z] Update kickstart version for RHEL9

- pytest_fixtures/core/sat_cap_factory.py
- robottelo/hosts.py
- tests/foreman/installer/test_installer.py
We have multiple tests which setup RHEL and Satellite/Capsule repositories. There are various test scenarios and various different sources. Mainly:
- Regular product testing (GA RHEL, internal product)
- Interop testing (internal RHEL, GA product)
The sources are configured based on settings and there are more places (tests/fixtures) where the logic is implemented.
These helper functions unify the logic of setting up installation sources
> Helper functions for enabling source repositories for Satellite and Capsule installation

- pytest_fixtures/core/sat_cap_factory.py
- robottelo/hosts.py
- tests/foreman/installer/test_installer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18129
We have multiple tests which setup RHEL and Satellite/Capsule repositories. There are various test scenarios and various different sources. Mainly:
- Regular product testing (GA RHEL, internal product)
- Interop testing (internal RHEL, GA product)
The sources are configured based on settings and there are more places (tests/fixtures) where the logic is implemented.
These helper functions unify the logic of setting up installation sources
> [6.17.z] Helper functions for enabling source repositories for Satellite and Capsule installation

- .github/CODEOWNERS
- tests/new_upgrades/test_role.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18390
This PR converts the user role upgrade scenario to use the `shared_resource` framweork. It converts the pre-upgrade tests to fixtures, removes the existing class structure for the non-stubbed tests, and moves the non-stubbed tests to the top of the module above the stubbed tests to improve readability.
> [6.16.z] Convert user role scenario to new format

- .github/CODEOWNERS
- tests/new_upgrades/test_role.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18390
This PR converts the user role upgrade scenario to use the `shared_resource` framweork. It converts the pre-upgrade tests to fixtures, removes the existing class structure for the non-stubbed tests, and moves the non-stubbed tests to the top of the module above the stubbed tests to improve readability.
> [6.17.z] Convert user role scenario to new format

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_performance_tuning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16929
As part of the current upgrade scenarios refactor, this PR converts the performance tuning scenario to use the `SharedResource` framework, converts the pre-upgrade test to a Pytest fixture, and adds a Satellite upgrade fixture for this scenario.
> [6.15.z] Convert perf tuning upgrade scenario to new format

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_performance_tuning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16929
As part of the current upgrade scenarios refactor, this PR converts the performance tuning scenario to use the `SharedResource` framework, converts the pre-upgrade test to a Pytest fixture, and adds a Satellite upgrade fixture for this scenario.
> [6.16.z] Convert perf tuning upgrade scenario to new format

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_performance_tuning.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16929
As part of the current upgrade scenarios refactor, this PR converts the performance tuning scenario to use the `SharedResource` framework, converts the pre-upgrade test to a Pytest fixture, and adds a Satellite upgrade fixture for this scenario.
> [6.17.z] Convert perf tuning upgrade scenario to new format

- robottelo/constants/__init__.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/18461
Closes: https://github.com/SatelliteQE/robottelo/issues/18465
> [6.16.z] Update kickstart version for RHEL9

- robottelo/constants/__init__.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/18461
Closes: https://github.com/SatelliteQE/robottelo/issues/18462
> [6.15.z] Update kickstart version for RHEL9

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_puppet.py
This PR converts the Puppet upgrade scenario to use the shared resource framework. It adds a pre-upgrade fixture to ensure that the test can be run concurrently with other upgrade scenario modules that require Puppet-enabled Satellites and adds fixtures for the Satellite, Capsule, and a Sat/Cap integration fixture that ensures Puppet is enabled on the Capsule after it has already been set up for operation with the Satellite.
> Convert Puppet scenario to new format

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_classparameter.py
This PR converts the Puppet class parameter upgrade scenario to use the SharedResource framework. It adds a fixture for a Puppet-enabled Satellite, converts the pre-upgrade test to a fixture, removes a cleanup helper function, adds a splay to ensure the `import_puppet` API endpoint is not overloaded, and makes some additional small changes to ensure that the test passes with the new framework.
> Convert classparameter upgrade scenario

- pytest_fixtures/component/permissions.py
- robottelo/constants/__init__.py
Missing permissions for resource quota
Added permissions https://github.com/ATIX-AG/foreman_resource_quota/blob/main/lib/foreman_resource_quota/register.rb#L13
> Add permissions for resource quota

- pytest_fixtures/component/permissions.py
- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18491
Missing permissions for resource quota
Added permissions https://github.com/ATIX-AG/foreman_resource_quota/blob/main/lib/foreman_resource_quota/register.rb#L13
> [6.16.z] Add permissions for resource quota

- pytest_fixtures/component/rh_cloud.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18480
IoP tests on IPv6 fail when logging in to and pulling container images from the registry:
```
17:34:14  ________ ERROR at setup of test_rhcloud_insights_e2e[rhel7-ipv6-local] _________
[...]
17:34:14  
17:34:14      @pytest.fixture(scope='module')
17:34:14      def module_target_sat_insights(request, module_target_sat, satellite_factory):
[...]
17:34:14          if not hosted_insights:
17:34:14              iop_settings = settings.rh_cloud.iop_advisor_engine
17:34:14              script = (iop_settings.setup_script or '').splitlines()
17:34:14      
17:34:14              # Log in to container registry
17:34:14              if iop_settings.registry and iop_settings.username and iop_settings.token:
17:34:14 …
```
> [6.17.z] Use http proxy to reach container registry for IoP tests on IPv6

- tests/foreman/cli/test_templatesync.py
- tests/foreman/ui/test_templatesync.py
atomic no longer around by default
> template export filter more future proof

- tests/foreman/cli/test_templatesync.py
- tests/foreman/ui/test_templatesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17999
atomic no longer around by default
> [6.17.z] template export filter more future proof

- tests/foreman/cli/test_templatesync.py
- tests/foreman/ui/test_templatesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17999
atomic no longer around by default
> [6.16.z] template export filter more future proof

- tests/foreman/cli/test_templatesync.py
- tests/foreman/ui/test_templatesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17999
atomic no longer around by default
> [6.15.z] template export filter more future proof

- tests/foreman/ui/test_rhcloud_inventory.py
When executing the end2end `test_rhcloud_inventory_e2e` with SAT 6.16, it is failing only with RHEL 8 and RHEL 9 containers.
After a thorough investigation, there seems to be an issue with the interaction between SAT 6.16 and these RHEL8/9 containers. (It works well in 6.17)
The action that executed by this test (generating and downloading a report) is working perfectly when we don't use containers.
Issue reported here: SAT-34253
Needs Airgun: https://github.com/SatelliteQE/airgun/pull/1860
As this is an end2end test, and SAT should mainly interact with real hosts, I made a change to the test, so it does not use containers (which is also the workaround for this issue).
```
pytest: tests/foreman/ui/test_rhcloud_inventory.py -k 'test_rhcloud_inventory_e2e'
airgun: …
```
> Cloud Inventory UI Test Fix

- tests/foreman/ui/test_templatesync.py
```
<Module test_templatesync.py>
<Function test_positive_import_templates[auth_http_proxy-use_proxy]>
<Function test_positive_import_templates[unauth_http_proxy-use_proxy]>
<Function test_positive_import_templates[auth_http_proxy-do_not_use_proxy]>
```
> Remove unnecessary skip test, it was a leftover from development

- tests/foreman/ui/test_templatesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18519
```
<Module test_templatesync.py>
<Function test_positive_import_templates[auth_http_proxy-use_proxy]>
<Function test_positive_import_templates[unauth_http_proxy-use_proxy]>
<Function test_positive_import_templates[auth_http_proxy-do_not_use_proxy]>
```
> [6.17.z] Remove unnecessary skip test, it was a leftover from development

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18547
Test `test_positive_export_import_consume_incremental_yum_repo` was failing because Package count available on the host did not meet the expectation. 
This was happening for client scenario, Unavailability of GA product certs in `/etc/pki` for componse build.
In `/etc/pki` we have cert for `Red Hat Enterprise Linux for x86_64 Beta` instead of `Red Hat Enterprise Linux for x86_64`.
**Error:**
```
AssertionError: Package count available on the host did not meet the expectation
```
1. use different repo for the test case(s), custom or some from DF
2. get the cert to the compose host
Option 1 is looks better than option 2. 
Thanks to @vsedmik for sharing communication slack thread.
N/A
```
pytest: …
```
> [6.17.z] export import increamental yum repo

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18534
This is causing Puppet failures - https://github.com/SatelliteQE/robottelo/pull/18129
Updated the position of `self._satellite` initialization because during Capsule CDN registration (via `register_to_cdn`), the method `self.reset_rhsm()` is called, which sets `self._satellite` to None. This leads to issues in correctly identifying the Satellite instance. To resolve this, the Capsule is re-initialized with the Satellite after registration to ensure smooth execution of subsequent tasks.
> [6.15.z] update_sat_to_avoid_issues_after_Capsule_CDN_regis

- tests/foreman/cli/test_computeresource_vmware.py
vTPM option doesn't work for VMware image-based provisioning, and SAT-30594 fixes this issue
Update existing VMware image-based provisioning test to cover SAT-30594
https://github.com/theforeman/foreman/pull/10524
https://github.com/fog/fog-vsphere/pull/309
> Update VMware image-based provisioning test to cover SAT-30594

- robottelo/constants/__init__.py
- robottelo/hosts.py
- tests/foreman/cli/test_container_management.py
In 6.18 the podman cert-based authentication is being implemented for registered hosts. When using this authentication, only the content tied to the particular AK -> LCE/CV will be accessible to the host registered with the AK.
We should enable and test this auth type too.
This PR proposes support and a test case for that authentication type. In future we could E2E this test case with product-based ways for the certs setup (not implemented yet in the product) and perhaps move the other test cases to this auth type.
https://issues.redhat.com/browse/SAT-33255
```
pytest: tests/foreman/cli/test_container_management.py -k podman_cert_auth
```
> Add support and test case for podman cert-based authentication

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_capsule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17343
As part of the current upgrade scenarios refactor, this PR converts the Capsule upgrade scenario tests to use the SharedResource framework, converts the pre-upgrade test to a Pytest fixture, and adds Satellite and Capsule fixtures to support these changes.
> [6.16.z] Convert capsule upgrade scenarios to new format

- tests/foreman/api/test_templatesync.py
- tests/foreman/cli/test_templatesync.py
> make example_template.erb downloadable on IPv6

- tests/foreman/cli/test_satellitesync.py
Test `test_positive_export_import_consume_incremental_yum_repo` was failing because Package count available on the host did not meet the expectation.
This was happening for client scenario, Unavailability of GA product certs in /etc/pki for componse build.
In `/etc/pki` we have cert for `Red Hat Enterprise Linux for x86_64 Beta` instead of `Red Hat Enterprise Linux for x86_64`.
**Note:** In `6.15.z` and `6.14.z` Clinet scenarios test is failing while uploading manifest. But looking at repo we are using doesn't need any manifest to upload. So I would recommend to use same solution for 6.15.z and 6.14.z Clinet scenarios as well
Use different repo for the test case(s), custom or some from DF
NA
```
pytest: tests/foreman/cli/test_satellitesync.py -k …
```
> 6.16.z - export import increamental yum repo

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18565
Test `test_positive_export_import_consume_incremental_yum_repo` was failing because Package count available on the host did not meet the expectation.
This was happening for client scenario, Unavailability of GA product certs in /etc/pki for componse build.
In `/etc/pki` we have cert for `Red Hat Enterprise Linux for x86_64 Beta` instead of `Red Hat Enterprise Linux for x86_64`.
**Note:** In `6.15.z` and `6.14.z` Clinet scenarios test is failing while uploading manifest. But looking at repo we are using doesn't need any manifest to upload. So I would recommend to use same solution for 6.15.z and 6.14.z Clinet scenarios as well
Use different repo for the test case(s), custom or some from DF
NA
``` …
```
> [6.15.z] 6.16.z - export import increamental yum repo

- tests/foreman/cli/test_activationkey.py
The test was using `hammer subscription unregister` within itself, which is long gone from satellite
Switch it for `rhel_contenthost.unregister()`
```
pytest: tests/foreman/cli/test_activationkey.py -k 'test_syspurpose_end_to_end'
```
> sys_purpose test fix

- pytest_fixtures/component/provision_pxe.py
- robottelo/constants/__init__.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18560
As RHEL10 is GA, updating kickstart and content repos required for provisioning tests and some logic update
> [6.17.z] Update Provisioning tests to use RHEL10 GA repos

- tests/new_upgrades/test_classparameter.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17863
This PR converts the Puppet class parameter upgrade scenario to use the SharedResource framework. It adds a fixture for a Puppet-enabled Satellite, converts the pre-upgrade test to a fixture, removes a cleanup helper function, adds a splay to ensure the `import_puppet` API endpoint is not overloaded, and makes some additional small changes to ensure that the test passes with the new framework.
> [6.15.z] Convert classparameter upgrade scenario

- robottelo/hosts.py
- tests/foreman/cli/test_container_management.py
In https://github.com/Katello/katello/pull/11402 we add the cert setup for container access in Global Registration. 
We already have a test case to test the cert-based auth with manual setup. This PR extends/parametrizes the case with global registration.
```
pytest: tests/foreman/cli/test_container_management.py -k test_podman_cert_auth
Katello:
katello: 11402
theforeman:
foreman: 10554
```
> Add support and parametrization for GR based cert setup

- tests/new_upgrades/test_classparameter.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/17863
This PR converts the Puppet class parameter upgrade scenario to use the SharedResource framework. It adds a fixture for a Puppet-enabled Satellite, converts the pre-upgrade test to a fixture, removes a cleanup helper function, adds a splay to ensure the `import_puppet` API endpoint is not overloaded, and makes some additional small changes to ensure that the test passes with the new framework.
> [6.17.z] Convert classparameter upgrade scenario

- tests/foreman/ui/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18619
Due to the interface change in RHEL 10, registering the host with `eth0` caused it to use the default location, leading to incorrect org/loc mapping and `job_invocation` failure.
Interface name in RHEL 10 is now `enp3s0`, so updated the code to fetch the interface based on RHEL version to avoid future issues.
> [6.17.z] [Interop fix] Fetch interface as per rhel version

- tests/foreman/api/test_ansible.py
New feature to validate ansible check mode feature introduced in SAT-32223 is missing test coverage
Add test coverage to validate ansible check mode feature SAT-32223
https://github.com/SatelliteQE/nailgun/pull/1307
> Add test coverage to validate ansible check mode feature

- pytest_fixtures/core/contenthosts.py
- pytest_plugins/fixture_markers.py
- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/cli/test_flatpak.py
- tests/foreman/cli/test_satellitesync.py
In 6.18 there are some Flatpak-related features (like cert-based login) which will be only available on RHEL10+ instances.
For this reason we should be able to parametrize our test cases with different RHEL contenthosts. Also, we should be testing with multiple (supported) RHEL versions.
This PR just makes our `module_flatpak_contenthost` parametrizable with different RHEL versions (similarly to `rhel_contenthost`).
For now I'll keep the test parametrization with `9` until we resolve the right way to have RHEL10 set up with appropriate flatpak clients.
```
pytest: tests/foreman/cli/test_flatpak.py -k consume
```
> Make flatpak_contenthost parametrizable

- tests/foreman/api/test_computeresource_vmware.py
Bootdisk+Secureboot provisioning for VMware fails intermittently
Skipping Bootdisk+Secureboot provisioning for VMware as its not supported yet, see SAT-24052
> Skip Bootdisk+Secureboot provisioning for VMware

- tests/foreman/api/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18640
Bootdisk+Secureboot provisioning for VMware fails intermittently
Skipping Bootdisk+Secureboot provisioning for VMware as its not supported yet, see SAT-24052
> [6.17.z] Skip Bootdisk+Secureboot provisioning for VMware

- tests/foreman/installer/test_installer.py
Ovirt has been removed and bootdisk added to Downstream modules
This has been removed from installer options: https://github.com/theforeman/foreman-installer/commit/b14cca6a1cd0cb4ad357762188036a0e2a3e3d19
Remove `'foreman::compute::ovirt',` from DOWNSTREAM_MODULES
> Remove ovirt from downstream foreman installer modules

- .github/dependabot.yml
6.14 became unsupported. Dependabot still labels its PRs with 6.14.z label.
configure dependabot to not add the 6.14.z label to it's PRs
> Remove 6.14.z from dependabot PR labels

- testimony.yaml
- tests/foreman/api/test_convert2rhel.py
Convert2RHEL tests are part of Registration component currently, which is incorrect
Using Conversionsappliance component for Convert2RHEL tests
[SAT-34794](https://issues.redhat.com/browse/SAT-34794)
> Use Conversionsappliance component for Convert2RHEL tests

- testimony.yaml
- tests/foreman/api/test_convert2rhel.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18641
Convert2RHEL tests are part of Registration component currently, which is incorrect
Using Conversionsappliance component for Convert2RHEL tests
[SAT-34794](https://issues.redhat.com/browse/SAT-34794)
> [6.16.z] Use Conversionsappliance component for Convert2RHEL tests

- testimony.yaml
- tests/foreman/api/test_convert2rhel.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18641
Convert2RHEL tests are part of Registration component currently, which is incorrect
Using Conversionsappliance component for Convert2RHEL tests
[SAT-34794](https://issues.redhat.com/browse/SAT-34794)
> [6.15.z] Use Conversionsappliance component for Convert2RHEL tests

- tests/upgrades/test_errata.py
- tests/upgrades/test_subscription.py
Post upgrade test failing due to network type ip-version with below error
```
failed on setup with "Failed: Invalid test parameter: rhel7-ipv4. Test data not found."
```
```
failed on setup with "Failed: Invalid test parameter: rhel8-ipv4. Test data not found."
```
```
failed on setup with "Failed: Invalid test parameter: rhel9-ipv4. Test data not found."
```
fetching network type from server.yaml
```
pytest: tests/upgrades/test_subscription.py::TestSubscriptionAutoAttach
env:
ROBOTTELO_server__deploy_workflow: 'deploy-satellite-upgrade'
ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '9'
ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.17.1'
```
> fix ipv6 test version selection

- tests/foreman/cli/test_hammer.py
these tests are exhibiting flakiness in upgrade runs that is not product-related. Given that we have plenty of cli scenarios in the upgrade run, I don't thing theses are worth keeping in the set given the maintenance load
> hammer upgrade testset reduced

- tests/foreman/cli/test_hammer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18646
these tests are exhibiting flakiness in upgrade runs that is not product-related. Given that we have plenty of cli scenarios in the upgrade run, I don't thing theses are worth keeping in the set given the maintenance load
> [6.15.z] hammer upgrade testset reduced

- tests/foreman/cli/test_hammer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18646
these tests are exhibiting flakiness in upgrade runs that is not product-related. Given that we have plenty of cli scenarios in the upgrade run, I don't thing theses are worth keeping in the set given the maintenance load
> [6.17.z] hammer upgrade testset reduced

- tests/foreman/cli/test_remoteexecution.py
in regular runs the sat and capsule hosts are included in default location (which the test implicitly counted on), not so on the upgraded sat image, causing test failures in upgrade runs
making location membership for infrastructure hosts explicit
passing locally on upgraded sat, adding prt for non-upgaded one to see there's no regression caused
> adding infra hosts to default location

- tests/foreman/api/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18660
https://github.com/SatelliteQE/robottelo/pull/18560 removed `rhel10_bos_beta` and `rhel10_aps_beta` from constants, but one occurrence survived and should be replaced.
This PR
```
pytest: tests/foreman/api/test_capsulecontent.py -k sync_kickstart_repo
```
> [6.17.z] Fix capsule KS test with non-beta RHEL10

- tests/upgrades/test_errata.py
- tests/upgrades/test_subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18643
Post upgrade test failing due to network type ip-version with below error
```
failed on setup with "Failed: Invalid test parameter: rhel7-ipv4. Test data not found."
```
```
failed on setup with "Failed: Invalid test parameter: rhel8-ipv4. Test data not found."
```
```
failed on setup with "Failed: Invalid test parameter: rhel9-ipv4. Test data not found."
```
fetching network type from server.yaml
```
pytest: tests/upgrades/test_subscription.py::TestSubscriptionAutoAttach
env:
ROBOTTELO_server__deploy_workflow: 'deploy-satellite-upgrade'
ROBOTTELO_server__deploy_arguments__deploy_rhel_version: '9'
ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.17.1'
```
> [6.17.z] fix ipv6 test version selection

- tests/new_upgrades/test_hostcontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18294
This PR converts the content host upgrade scenario to use the shared_resource framework. It removes the existing class structure of the module, converts the pre-upgrade test to a fixture, and moves existing fixtures inherited by the old tests to the body of the pre-upgrade fixture to ensure isolation from the main Robottelo fixture stack.
> [6.15.z] Convert content host scenario to new format

- tests/foreman/cli/test_rhcloud_inventory.py
iop-advisor-engine should work when custom SSL certificates have also been installed on the Satellite.
Create a test to install Satellite with IoP and custom SSL certificates, then verify successful insights-client registration and upload.
SAT-34214
> [6.17.z] Add test_positive_install_iop_custom_certs to test IoP with custom SSL certs

- tests/new_upgrades/test_bookmarks.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/16856
As part of the upgrade scenarios conversion effort, this PR changes the bookmarks upgrade scenario tests to use the shared resource framework and converts the pre-upgrade scenarios to pytest fixtures. It also adds a new shared Satellite fixture for search component tests.
> [6.16.z] Convert bookmarks upgrade scenarios to new format

- pytest_fixtures/component/provision_pxe.py
Most of the provisioning tests are failing due to not having capsule in tftp and template when we create the Subnet. It was removed here - https://github.com/SatelliteQE/robottelo/pull/17904
Adding capsule to required parameter to work provisioning properly
> adding capsule to tftp and template

- .github/workflows/prt_labels.yml
Previously, there would be a step that would wait, for a very short period of time, for the PRT job to finish before failing. Now, instead of waiting, let's just strip the label if needed and let the new PRT run set the label correctly when it finishes.
```
pytest: tests/foreman/ui/test_organization.py -k 'test_positive_create'
```
> Simplify the PRT-Passed label removal

- .github/workflows/prt_labels.yml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18672
Previously, there would be a step that would wait, for a very short period of time, for the PRT job to finish before failing. Now, instead of waiting, let's just strip the label if needed and let the new PRT run set the label correctly when it finishes.
```
pytest: tests/foreman/ui/test_organization.py -k 'test_positive_create'
```
> [6.16.z] Simplify the PRT-Passed label removal

- .github/workflows/prt_labels.yml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18672
Previously, there would be a step that would wait, for a very short period of time, for the PRT job to finish before failing. Now, instead of waiting, let's just strip the label if needed and let the new PRT run set the label correctly when it finishes.
```
pytest: tests/foreman/ui/test_organization.py -k 'test_positive_create'
```
> [6.17.z] Simplify the PRT-Passed label removal

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18286
This PR converts the host upgrade scenario to use the shared_resource framework. It removes the existing class structure of the current host upgrade module, converts the pre-upgrade test to a fixture, adds some GCE-related fixtures to the local conftest file, and reworks some other GCE-related fixtures into the new pre-upgrade fixture.
> [6.17.z] Convert host upgrade scenario to new format

- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18286
This PR converts the host upgrade scenario to use the shared_resource framework. It removes the existing class structure of the current host upgrade module, converts the pre-upgrade test to a fixture, adds some GCE-related fixtures to the local conftest file, and reworks some other GCE-related fixtures into the new pre-upgrade fixture.
> [6.16.z] Convert host upgrade scenario to new format

- pytest_fixtures/component/provision_pxe.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18671
Most of the provisioning tests are failing due to not having capsule in tftp and template when we create the Subnet. It was removed here - https://github.com/SatelliteQE/robottelo/pull/17904
Adding capsule to required parameter to work provisioning properly
> [6.17.z] adding capsule to tftp and template

- tests/foreman/cli/test_errata.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18689
Errata CLI tests using the local fixture `hosts` , are failing to checkout IPV6 hosts in IPV6 pipelines.
They are defaulting to IPV4 since no `deploy_network_type` is defined in Broker checkout. 
Set them to use the defined network type for content hosts (ipv4 or ipv6).
```
pytest: tests/foreman/cli/test_errata.py --uses-fixtures hosts
```
> [6.17.z] Errata CLI hosts dualstack environment: use defined host network type

- tests/foreman/cli/test_satellitesync.py
Updating the repo used in test_positive_export_rerun_failed_import to use larger repo to ensure import failure occurs while repo is still importing
> [Test Fix][ISS]Add rhel9 appstream repo to test

- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18700
Updating the repo used in test_positive_export_rerun_failed_import to use larger repo to ensure import failure occurs while repo is still importing
> [6.16.z] [Test Fix][ISS]Add rhel9 appstream repo to test

- tests/foreman/api/test_ansible.py
Teardown of the test is failing due to bug: SAT-18656
Failing test: tests/foreman/api/test_ansible.py::test_positive_read_facts_with_filter
Adding a workaround for the test.
> Fix ansible  test teardown - test_positive_read_facts_with_filter

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18623
in regular runs the sat and capsule hosts are included in default location (which the test implicitly counted on), not so on the upgraded sat image, causing test failures in upgrade runs
making location membership for infrastructure hosts explicit
passing locally on upgraded sat, adding prt for non-upgaded one to see there's no regression caused
> [6.17.z] adding infra hosts to default location

- tests/foreman/api/test_ansible.py
Failed autocherrypick https://github.com/SatelliteQE/robottelo/issues/18730 
> [6.16.z Cherrypick]Fix ansible  test teardown - test_positive_read_facts_with_filter

- tests/foreman/cli/test_discoveredhost.py
FDI test is failing because it is built on older version of RHEL which is 9.5 instead of 9.6
Assertion in the test is updated until the bug is fixed.
> Update FDI test assertion due to Bug:SAT-34778

- robottelo/constants/__init__.py
- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/cli/test_flatpak.py
- tests/foreman/cli/test_satellitesync.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18721
The repositories served at the RH index have been changed and we need to update them.
As per the latest info they are going to be changed _around_ the major RHEL release times. The older versions (`rhel9/app_name`) are to be removed and only the latest ones (`rhel10/app_name`) should be used, even for the older RHEL versions (that's why we can't hook it on `host.os_version.major`).
This PR.
```
pytest: tests/foreman/cli/test_flatpak.py::test_sync_consume_flatpak_repo_via_cv tests/foreman/cli/test_capsulecontent.py::test_sync_consume_flatpak_repo_via_library tests/foreman/cli/test_satellitesync.py::TestContentViewSync::test_postive_export_import_cv_with_mixed_content_repos
```
> [6.17.z] Fix Flatpak repos provided by RH index

- tests/foreman/ui/test_contenthost.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18725
The test `test_pagination_multiple_hosts_multiple_pages` was failing since forever and I could not stand it hanging there anymore.
It required a small refactor, so it is up to date and checks relevant stuff.
```
pytest: tests/foreman/ui/test_contenthost.py -k 'test_pagination_multiple_hosts_multiple_pages'
```
> [6.17.z] Pagination Test Refactor

- pytest_fixtures/component/hostgroup.py
- pytest_fixtures/component/provisioning_template.py
- tests/foreman/ui/test_hostgroup.py
Verifies: SAT-30138
New test case for bug SAT-30138: A 'Media' field is unexpectedly showing up in Red Hat Satellite's web UI on the 'Operating System' tab of a child host group
> SAT-30138: Media drop-down is visible in child host group with synced content

- .github/CODEOWNERS
- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_syncplan.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18698
This PR converts the sync plan upgrade scenario to use the `shared_resource` framework. It converts the pre-upgrade scenario to a fixture and makes some minor changes to include required API parameters.
> [6.16.z] Convert sync plan upgrade scenario to new format

- tests/foreman/api/test_reporttemplates.py
The `test_positive_applied_errata_by_install_date` is quite flaky within the automation, local testing did not achieve that high flakiness as in automation.
In this case, idk why, but the approach with sleep via target_sat.execute from previous [PR](https://github.com/SatelliteQE/robottelo/pull/18735) did not help with flakiness locally but time.sleep(10) did.
Let's see how it behaves in CI.
The goal is at least to pass over the job execution and fail further than on `Install errata` task.
```
pytest: tests/foreman/api/test_reporttemplates.py -k 'test_positive_applied_errata_by_install_date'
```
> Try to fix flaky reporting test #2

- tests/foreman/cli/test_discoveredhost.py
Failed autocherrypick: https://github.com/SatelliteQE/robottelo/issues/18728
> [6.15.z Cherrypick] Fix Discovery Provisioning Tests

- tests/foreman/destructive/test_katello_certs_check.py
Fix test_positive_generate_capsule_certs_using_absolute_path failing because of the wrong assertion.
- Update the assertion to check `foreman-proxy-client.crt`.
- SAT-35205
> Fix test_positive_generate_capsule_certs_using_absolute_path

- tests/foreman/api/test_acs.py
- tests/foreman/cli/test_acs.py
Some ACS tests (those running Refresh) fail in IPv6 pipeline since they can't reach out to the IPv4 source, because ACSes have the HTTP proxy set separately for the capsule they are using.
Set the ACS HTTP proxy on the Capsule used by ACS to the IPv6 proxy and create the ACS with `use_http_proxies` option.
https://issues.redhat.com/browse/SAT-34801
Requires https://github.com/SatelliteQE/nailgun/pull/1314
```
pytest: tests/foreman -k CRUD_all_types
nailgun: 1314
```
> Fix ACS IPv6 tests with ACS HTTP proxy

- tests/foreman/api/test_acs.py
- tests/foreman/cli/test_acs.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18767
Some ACS tests (those running Refresh) fail in IPv6 pipeline since they can't reach out to the IPv4 source, because ACSes have the HTTP proxy set separately for the capsule they are using.
Set the ACS HTTP proxy on the Capsule used by ACS to the IPv6 proxy and create the ACS with `use_http_proxies` option.
https://issues.redhat.com/browse/SAT-34801
Requires https://github.com/SatelliteQE/nailgun/pull/1314
```
pytest: tests/foreman -k CRUD_all_types
nailgun: 1314
```
> [6.17.z] Fix ACS IPv6 tests with ACS HTTP proxy

- pytest_fixtures/core/contenthosts.py
- tests/foreman/cli/test_host.py
Katello-tracer tests for ipv6 was failing with below error.  Unable to install "katello-host-tools-tracer" package on content host due to missing repository "Satellite Client". 
Error-
```
failed on setup with "robottelo.hosts.ContentHostError: There was an error installing katello-host-tools-tracer"
```
Additionally due to ipv6 network type while installing katello-host-tools-tracer package test was failing with below error
Error-
```
Curl error (7): Couldn't connect to server for http://.............repodata/repomd.xml []
Error: Failed to download metadata for repo 'foreman_register2': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
Note: We need to remove support for rhel-10, because `MOCK_SERVICE_REPO` for RHEL10 is not present in repos.yaml …
> fix katello-tracer ipv6 for rhel version 7,8,9

- pytest_fixtures/core/contenthosts.py
- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18777
Katello-tracer tests for ipv6 was failing with below error.  Unable to install "katello-host-tools-tracer" package on content host due to missing repository "Satellite Client". 
Error-
```
failed on setup with "robottelo.hosts.ContentHostError: There was an error installing katello-host-tools-tracer"
```
Additionally due to ipv6 network type while installing katello-host-tools-tracer package test was failing with below error
Error-
```
Curl error (7): Couldn't connect to server for http://.............repodata/repomd.xml []
Error: Failed to download metadata for repo 'foreman_register2': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
Note: We need to remove support for …
> [6.17.z] fix katello-tracer ipv6 for rhel version 7,8,9

- robottelo/hosts.py
- tests/foreman/destructive/test_ldap_authentication.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18612
`tests/foreman/destructive/test_ldap_authentication.py::test_permissions_external_ldap_mapped_rhsso_group` fails due to 3 reasons:
1) changed external user group dropdown locator, fixed in the Airgun PR
2) RHSSO not actually set up on the machine, fixed in this PR
3) RHSSO <-> AD federation configured in a way that didn't sync group membership, fixed manually
This PR together with https://github.com/SatelliteQE/airgun/pull/1865 and fixing of federation setup
> [6.17.z] Setup RHSSO for the test

- tests/foreman/ui/test_activationkey.py
The `test_positive_end_to_end_register` was outdated and failing for a long time.
This PR is doing a little refactoring of this test so it starts working again.
```
pytest: tests/foreman/ui/test_activationkey.py -k 'test_positive_end_to_end_register'
```
> AK E2E UI test fix

- robottelo/constants/__init__.py
- tests/foreman/ui/test_subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18797
VDC subscription is no longer available.
Remove tests testing just this VDC subscription.
> [6.17.z] Remove VDC Tests

- tests/foreman/ui/test_activationkey.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18786
The `test_positive_end_to_end_register` was outdated and failing for a long time.
This PR is doing a little refactoring of this test so it starts working again.
```
pytest: tests/foreman/ui/test_activationkey.py -k 'test_positive_end_to_end_register'
```
> [6.17.z] AK E2E UI test fix

- tests/foreman/cli/test_computeresource_vmware.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18785
Updating VMware cli tests to use storage pod instead of datastore
> [6.17.z] Update VMware cli tests to use storage pod

- tests/foreman/api/test_ansible.py
We were using UI as workaround to clone a JobTemplate until SAT-34617 is fixed
Remove workaround for JobTemplate clone for Ansible check-mode test to validate https://github.com/theforeman/foreman_remote_execution/pull/979
> Remove workaround for JobTemplate clone for ansible tests

- tests/foreman/cli/test_activationkey.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18580
The test was using `hammer subscription unregister` within itself, which is long gone from satellite
Switch it for `rhel_contenthost.unregister()`
```
pytest: tests/foreman/cli/test_activationkey.py -k 'test_syspurpose_end_to_end'
```
> [6.15.z] sys_purpose test fix

- .github/CODEOWNERS
- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_usergroup.py
This PR converts the usergroup upgrade scenario to use the `SharedResource` framework. It converts the pre-upgrade test to a fixture, adds a `SharedResource` fixture to manage the checkout of the Satellite, and makes some minor changes to ensure that the test passes.
> Convert usergroup upgrade scenario to new format

- tests/foreman/api/test_convert2rhel.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18789
Oracle 8 test was failing because C2R couldn't get RHEL kernel to boot, instead OEL kernel was set resulting in failure while trying to convert an OEL 8 host to RHEL host.
1. Install only OEL kernel so removed *.
2. On yum update, the changes were not reflected so needs reboot.
3. On addition to set RHEL kernel as default, we need to set RHEL kernel for boot so added steps to remove OEL kernel.
> [6.17.z] Fix Oracle8 test : Set RHEL kernel 

- robottelo/constants/__init__.py
- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18826
Our Sat QE org used to be in the entlitlement mode, but it seems it has been flipped to SCA recently.
In #16575 we added some conditioning for pool attachment based on the sub-man status. It worked well for RHEL 7, 8, 9, since they return
```
```
However, for RHEL 10 it fails since it returns
```
Overall Status: Registered
```
Because our org is now SCA …
> [6.17.z] Remove pool attachment since we are SCA now

- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18756
Some FAM tests relies on setups that are not set up anywhere
Skip crazy FAM tests
[SAT-35471](https://issues.redhat.com/browse/SAT-35471)
> [6.17.z] Skip FAM tests relying on non-existent setups

- tests/foreman/sys/test_fam.py
Cherrypicks #18756 to `6.16.z`
(cherry picked from commit 4ab2c3cabee53740ff16318ae8e1a401cf2676ad)
Fixes #18841
[SAT-35471](https://issues.redhat.com/browse/SAT-35471)
> [6.16.z] Skip FAM tests relying on non-existent setups (#18756)

- tests/foreman/sys/test_fam.py
Cherrypicks #18756 to `6.15.z`
(cherry picked from commit 4ab2c3cabee53740ff16318ae8e1a401cf2676ad)
Fixes #18840
[SAT-35471](https://issues.redhat.com/browse/SAT-35471)
> [6.15.z] Skip FAM tests relying on non-existent setups (#18756)

- tests/foreman/sys/test_fam.py
Downstream has removed support for RHV/oVirt in 6.18 but related tests cannot be removed since upstream continues to support oVirt.
The `compute_profile_ovirt` test has to be kept for upstream testing in FAM so the solution is to skip running the test within robottelo for 6.18 onwards.
[SAT-35492](https://issues.redhat.com/browse/SAT-35492)
> Skip FAM compute_profile_ovirt due to removed support in 6.18+

- tests/foreman/ui/test_activationkey.py
`rhel7_contenthost` is not working with ipv6 infrastructure
use `rhel_contenthost` instead
```
pytest: tests/foreman/ui/test_activationkey.py -k 'test_positive_service_level_subscription_with_custom_product'
```
> IPv6 AK UI test fix

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18869
We have to  use CAPSULE_CDN_REPOS when setting up Capsule repos
> [6.17.z] Fix capsule repos constant name

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18869
We have to  use CAPSULE_CDN_REPOS when setting up Capsule repos
> [6.16.z] Fix capsule repos constant name

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18869
We have to  use CAPSULE_CDN_REPOS when setting up Capsule repos
> [6.15.z] Fix capsule repos constant name

- .github/CODEOWNERS
- tests/new_upgrades/conftest.py
- tests/new_upgrades/test_subscription.py
This PR converts the subscription upgrade scenario to use the `SharedResource` framework. It changes the pre-upgrade scenario tests to Pytest fixtures, adds a `SharedResource` fixture for the Satellite deployment, and makes some minor changes to ensure that the tests pass.
> Convert Subscription upgrade scenario to new format

- tests/foreman/api/test_http_proxy.py
- tests/foreman/cli/test_http_proxy.py
- tests/foreman/ui/test_http_proxy.py
(cherry picked from commit 620a8128a395abbe58131c10217a3fc36bfe051c)
Parent PR https://github.com/SatelliteQE/robottelo/pull/18893
Endeavor team is going to own the Http Proxy component.
Update component ownership accordingly
> [6.15.z] Update team component ownership: Phoenix-content -> Endeavor

- tests/foreman/api/test_http_proxy.py
- tests/foreman/cli/test_http_proxy.py
- tests/foreman/ui/test_http_proxy.py
(cherry picked from commit 620a8128a395abbe58131c10217a3fc36bfe051c)
Parent PR https://github.com/SatelliteQE/robottelo/pull/18893
Endeavor team is going to own the Http Proxy component.
Update component ownership accordingly
> [6.16.z] Update team component ownership: Phoenix-content -> Endeavor

- tests/foreman/api/test_http_proxy.py
- tests/foreman/cli/test_http_proxy.py
- tests/foreman/ui/test_http_proxy.py
(cherry picked from commit 620a8128a395abbe58131c10217a3fc36bfe051c)
Parent PR https://github.com/SatelliteQE/robottelo/pull/18893
Endeavor team is going to own the Http Proxy component.
Update component ownership accordingly
> [6.17.z] Update team component ownership: Phoenix-content -> Endeavor

- pytest_fixtures/component/leapp_client.py
- tests/foreman/cli/test_leapp_client.py
RHEL 9 to RHEL 10 Leapp upgrade support is added in 6.17.z and 6.18.
Added support of RHEL 9.6 to RHEL 10.0 leapp client update.
> Add support of RHEL9 to RHEL10 Leapp client upgrade

- pytest_fixtures/component/leapp_client.py
- tests/foreman/cli/test_leapp_client.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18878
RHEL 9 to RHEL 10 Leapp upgrade support is added in 6.17.z and 6.18.
Added support of RHEL 9.6 to RHEL 10.0 leapp client update.
> [6.17.z] Add support of RHEL9 to RHEL10 Leapp client upgrade

- robottelo/host_helpers/capsule_mixins.py
this slipped trough in https://github.com/SatelliteQE/robottelo/pull/18520 humbly offering this fix
> fixing a typo in capsule mixins

- robottelo/host_helpers/capsule_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18902
this slipped trough in https://github.com/SatelliteQE/robottelo/pull/18520 humbly offering this fix
> [6.17.z] fixing a typo in capsule mixins

- tests/foreman/api/test_architecture.py
- tests/foreman/api/test_host.py
- tests/foreman/api/test_hostgroup.py
- tests/foreman/api/test_media.py
- tests/foreman/api/test_partitiontable.py
- tests/foreman/cli/test_architecture.py
- tests/foreman/cli/test_domain.py
- tests/foreman/cli/test_hammer.py
- tests/foreman/cli/test_host.py
- tests/foreman/cli/test_hostgroup.py
- tests/foreman/cli/test_medium.py
- tests/foreman/cli/test_model.py
- tests/foreman/cli/test_partitiontable.py
- tests/foreman/cli/test_ping.py
- tests/foreman/destructive/test_host.py
- tests/foreman/destructive/test_ping.py
- tests/foreman/endtoend/test_cli_endtoend.py
- tests/foreman/ui/test_architecture.py
- tests/foreman/ui/test_domain.py
- tests/foreman/ui/test_hardwaremodel.py
- tests/foreman/ui/test_host.py
- tests/foreman/ui/test_hostgroup.py
- tests/foreman/ui/test_media.py
- tests/foreman/ui/test_partitiontable.py
manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/18868
close https://github.com/SatelliteQE/robottelo/issues/18905
> [6.17] former Endeavour components moved to new owners

- tests/foreman/cli/test_host.py
Assertions in host tests started to fail when https://github.com/Katello/hammer-cli-katello/pull/994 was merged, and needed a update to the existing CV and LCE fields
some assertions fixed as per new change
It works for https://github.com/SatelliteQE/robottelo/pull/18934
> Fix host asserts for CV and LCE

- pytest_plugins/infra_dependent_markers.py
- pytest_plugins/marker_deselection.py
- tests/foreman/cli/test_organization.py
- tests/foreman/longrun/test_oscap.py
We started seeing pytest warnings related to `libvirt_discovery` after a missing comma in `pytest_plugins/infra_dependent_markers.py`, my bad! Upon investigation, I realized that a few of existing pytest markers are obsolete or no longer in use.
And, use of `tier` markers were removed in https://github.com/SatelliteQE/robottelo/pull/17809 already.
```
21:26:20  tests/foreman/cli/test_organization.py:263
21:26:20    /opt/app-root/src/robottelo/tests/foreman/cli/test_organization.py:263: PytestUnknownMarkWarning: Unknown pytest.mark.libvirt_discovery - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
21:26:20      @pytest.mark.libvirt_discovery
21:26:20  
21:26:20 …
```
> Remove obsolete or unused pytest markers

- tests/foreman/destructive/test_fm_upgrade.py
Currently, we add `ipv6.disable=1` to grub boot options as part of `test_negative_ipv6_update_check` and reboot, where setup would never boot again and causes test to fail
Skipping FM upgrade test as IPv6 can't be disabled on IPv6-only setup
> Skip FM upgrade test as IPv6 can't be disabled on IPv6-only setup

- tests/foreman/destructive/test_fm_upgrade.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18946
Currently, we add `ipv6.disable=1` to grub boot options as part of `test_negative_ipv6_update_check` and reboot, where setup would never boot again and causes test to fail
Skipping FM upgrade test as IPv6 can't be disabled on IPv6-only setup
> [6.17.z] Skip FM upgrade test as IPv6 can't be disabled on IPv6-only setup

- tests/foreman/cli/test_host.py
The test `test_positive_host_list_with_cv_and_lce` was failing for a long time because it was using just CV and now we use content view environments.
Rename the test to `test_positive_host_list_with_cve` so it fits the test content properly and refactor it so it tests the content view environment.
```
pytest: tests/foreman/cli/test_host.py -k 'test_positive_host_list_with_cve'
```
> Fix of test_host CLI test

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18967
The test `test_positive_host_list_with_cv_and_lce` was failing for a long time because it was using just CV and now we use content view environments.
Rename the test to `test_positive_host_list_with_cve` so it fits the test content properly and refactor it so it tests the content view environment.
```
pytest: tests/foreman/cli/test_host.py -k 'test_positive_host_list_with_cve'
```
> [6.17.z] Fix of test_host CLI test

- pytest_plugins/fixture_markers.py
Capsule LB setup on IPv6 is failing to correctly parametrize `module_rhel_contenthost` for IPv6 so IPv4 host is created instead:
```
[Errno -5] No address associated with hostname
```
If there are multiple fixtures for the test to be parametrized they are not recognized and all parametrization is skipped.
Fix ContentHost fixtures parametrization logic and allow multiple fixtures to be parametrized
[SAT-35599](https://issues.redhat.com/browse/SAT-35599)
> Fix parametrization of multiple content host fixtures

- pytest_plugins/fixture_markers.py
Cherrypicks #18935 to `6.17.z`
(cherry picked from commit 63ea564537647ac3af618e5073c19cff65f68b46)
Fixes  #18974
> [6.17.z] Fix parametrization of multiple content host fixtures (#18935)

- pytest_plugins/fixture_markers.py
Cherrypicks #18935 to `6.16.z`
(cherry picked from commit 63ea564537647ac3af618e5073c19cff65f68b46)
Fixes  #18973
> [6.16.z] Fix parametrization of multiple content host fixtures (#18935)

- .github/CODEOWNERS
- tests/foreman/data/usage_report.yml
Adding items from SAT-30441 and from 
https://github.com/theforeman/foreman_maintain/pull/986 that went trough without jira but passed revies
> new items in the usage report

- tests/foreman/cli/test_flatpak.py
In 6.18 we are scoping the flatpak-remotes listing to their orgs (originally and in 6.17.z it's Satellite-wide).
Due to this change one related test started to fail since snap 108.
Scope the remote listing with the org so it can fail properly (for the right reason).
```
pytest: tests/foreman/cli/test_flatpak.py -k test_CRUD_and_sync
```
> Fix flatpak-remote organization scoping

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18194
Currently, the Satellite and Capsule classes do not allow their objects to have their specific `setup` and `teardown` methods which would have a consistent inheritance flow. We currently run ContentHost.setup on all host objects, there is no differentiation between setup and teardown of individual host types.
Implemented a proper cascading inheritance flow for the `setup` and `teardown` methods throughout the host class hierarchy:
1. For `setup` methods:
- Parent class setup runs FIRST (base to derived)
- Then class-specific setup runs
- This ensures a proper initialization sequence: ContentHost → Capsule → Satellite
2. For `teardown` methods:
- Class-specific teardown runs FIRST
- Then parent class teardown runs …
> [6.16.z] Add setup and teardown for Capsule and Satellite objects

- pytest_fixtures/component/lce.py
- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18990
`test_host_status_honors_taxonomies` was outdated and was failing for a long time on AK creation, not having a proper content-view-environment set.
This PR creates the needed content-view-environment and introduces a new fixture `default_org_lce`, which helps with this testcase and might even help someone in the future. This fixture creates a new LCE for the default ORG.
```
pytest: tests/foreman/ui/test_host.py -k 'test_host_status_honors_taxonomies'
```
> [6.17.z] test_host_status_honors_taxonomies fix

- tests/foreman/ui/test_settings.py
Composite CV test in settings is failing because it was using old contentview page
Update the test to use new contentview page and few other updates in it as per the new implementation of CV
https://github.com/SatelliteQE/airgun/pull/1734
> Fix Composite CV

- testimony.yaml
- tests/foreman/api/test_repository.py
- tests/foreman/cli/test_container_management.py
- tests/foreman/ui/test_containerimagetag.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19017
Component names changed. This patch is to reflect those changes.
> [6.16.z] Rename ContainerManagement-Content to ContainerImageManagement

- tests/foreman/api/test_computeresource_gce.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19021
this doesn't need to be here.
> [6.17.z] remove gce test form build sanity tests

- tests/foreman/api/test_computeresource_gce.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19021
this doesn't need to be here.
> [6.16.z] remove gce test form build sanity tests

- tests/foreman/ui/test_host.py
This PR adds 2 new tests:
- `test_positive_change_hosts_owner` coverage for `change the owner of multiple hosts` (https://issues.redhat.com/browse/SAT-31026)
- `test_positive_change_hosts_org_loc` coverage for `change the location and organization of multiple hosts` (https://issues.redhat.com/browse/SAT-31030)
(@vijaysawant needed a backup with finishing the robottelo coverage for this feature, so the test is inspired and refactored from this PR https://github.com/SatelliteQE/robottelo/pull/18980/files) 
Needs Airgun: https://github.com/SatelliteQE/airgun/pull/1933
Needs upstream foreman: https://github.com/theforeman/foreman/pull/10591
```
pytest: tests/foreman/ui/test_host.py -k 'test_positive_change_hosts_owner or test_positive_change_hosts_org_loc'
airgun: 1933 …
```
> Change Owner/Org/Loc test coverage

- robottelo/constants/__init__.py
- tests/foreman/api/test_repository.py
- tests/foreman/api/test_settings.py
Tests are missing for the new default mirroring policy settings.
Adds tests for the default yum and non-yum mirroring policy settings.
https://projects.theforeman.org/issues/38433
> Test new default mirroring policy options

- tests/foreman/cli/test_rhcloud_inventory.py
Output that is checked sometimes shows unrelated warning
Update the assertion
```
pytest: tests/foreman/cli/test_rhcloud_inventory.py -k "test_positive_inventory_recommendation_sync[rhel10-ipv4]"
```
> recommendation sync CLI test fix

- pytest_fixtures/component/http_proxy.py
- robottelo/hosts.py
- tests/foreman/ui/test_http_proxy.py
When testing HTTP proxy there is no sense to test w/o HTTP proxy and more importantly such testing is failing for our internal corporate IPv6 setup.
Remove parameter `no_http_proxy` used for `setup_http_proxy` proxy
[SAT-36170](https://issues.redhat.com/browse/SAT-36170)
> Remove no_http_proxy parameter in HTTP Proxy testing

- tests/foreman/ui/test_settings.py
1) The settings field contains "Version $VERSION" and $VERSION should be replaced by actual version, e.g. 6.18.0. When the test compares "Version $VERSION" - the content of the field - with the actually shown footer text, it fails.
For some mysterious reason not yet known to me, the test sometimes got actual text "Version 6.18.0" instead of the unexpanded variable so this actually passed pre-6.18. I don't understand, but this fix should work for both cases.
2) The test somehow presumes the original value to be Yes, even though it doesn't need to be. Fixed.
> Two Settings UI test fixes

- conf/repos.yaml.template
- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19079
Companion to https://github.com/SatelliteQE/fedorapeople-repos/pull/16 . Opening as a draft until that goes in.
Tracer tests were not running against EL10 due to the mock service package not being built for that platform.
Build the package for EL10, enable the test.
https://issues.redhat.com/browse/SAT-35945
```
pytest: tests/foreman/cli/test_host.py -k 'test_positive_tracer_list_and_resolve'
```
> [6.17.z] Run tracer tests against el10

- pytest_fixtures/component/http_proxy.py
- robottelo/hosts.py
- tests/foreman/ui/test_http_proxy.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19046
When testing HTTP proxy there is no sense to test w/o HTTP proxy and more importantly such testing is failing for our internal corporate IPv6 setup.
Remove parameter `no_http_proxy` used for `setup_http_proxy` proxy
[SAT-36170](https://issues.redhat.com/browse/SAT-36170)
> [6.17.z] Remove no_http_proxy parameter in HTTP Proxy testing

- tests/foreman/ui/test_host.py
`test_positive_change_hosts_owner` was failing due to the Owner column not being shown and also due to some airgun issues.
Ensure column is displayed,
Airgun fix: https://github.com/SatelliteQE/airgun/pull/1940
```
pytest: tests/foreman/ui/test_host.py -k 'test_positive_change_hosts_owner'
airgun: 1940
```
> Test Change Owner Fix

- tests/foreman/ui/test_host.py
Remove now obsolete `new_host_ui` fixture used in the `ui/test_host.py` file.
This fixture is no longer needed in stream as the New All host page is now set as default. 
(For reference, see SAT-35177 and https://github.com/SatelliteQE/airgun/pull/1935)
To demonstrate that the change I am introducing does not break the test flow, I will run `test_positive_change_hosts_owner` in PRT, which used this fixture.
```
pytest: tests/foreman/ui/test_host.py -k 'test_positive_change_hosts_owner'
```
> Remove new_host_ui fixture

- tests/foreman/api/test_http_proxy.py
CDN is not accessible from Red Hat's internal IPv6 network and setting `http_proxy_policy='none'` makes repository sync to fail:
```
E   nailgun.entity_mixins.TaskFailedError: Task 7508be1d-bd0f-4f6d-bd4e-374dc8116de1 did not succeed. Task information: {'id': '7508be1d-bd0f-4f6d-bd4e-374dc8116de1', 'label': 'Actions::Katello::Repository::Sync'
...
'errors': ['Cannot connect to host cdn.redhat.com:443 ssl:default [Network is unreachable]']
...
```
Omit setting `http_proxy_policy='none'` for repository on IPv6
[SAT-36461](https://issues.redhat.com/browse/SAT-36461)
> Omit http_proxy_policy='none' for repository on IPv6

- pytest_fixtures/component/maintain.py
- tests/foreman/maintain/test_backup_restore.py
- Backup/Restore tests are failing because of fixture scope mismatch.
- Fix the test
- SAT-36445
> Fix backup/restore tests for mismatched fixture issue

- pytest_fixtures/core/sys.py
Fixture `block_fake_repo_access` used in HTTP Proxy testing is lacking IPv6 support
```
pytest_fixtures/core/sys.py:91: in block_fake_repo_access
raise SatelliteHostError(f'Error, port {repo_server_name} {repo_server_port} not blocked.')
E   robottelo.hosts.SatelliteHostError: Error, port infra-podman-ipv6.example.com 50123 not blocked.
```
Implement IPv6 support in non-proxy traffic blocking fixture (`block_fake_repo_access`)
[SAT-36407](https://issues.redhat.com/browse/SAT-36407)
> Make non-proxy traffic blocking fixture IPv6 ready

- pytest_fixtures/core/sys.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19109
Fixture `block_fake_repo_access` used in HTTP Proxy testing is lacking IPv6 support
```
pytest_fixtures/core/sys.py:91: in block_fake_repo_access
raise SatelliteHostError(f'Error, port {repo_server_name} {repo_server_port} not blocked.')
E   robottelo.hosts.SatelliteHostError: Error, port infra-podman-ipv6.example.com 50123 not blocked.
```
Implement IPv6 support in non-proxy traffic blocking fixture (`block_fake_repo_access`)
[SAT-36407](https://issues.redhat.com/browse/SAT-36407)
> [6.17.z] Make non-proxy traffic blocking fixture IPv6 ready

- robottelo/utils/virtwho.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19151
- Test which configures Virtwho with scripts fails because `deploy_configure_by_script` fail to put the script on satellite.
```
../../lib64/python3.12/site-packages/pytest_asyncio/plugin.py:681: in pytest_fixture_setup
return (yield)
^^^^^
tests/foreman/conftest.py:74: in ui_session_record_property
request.getfixturevalue(fixture), Satellite
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../lib64/python3.12/site-packages/pytest_asyncio/plugin.py:681: in pytest_fixture_setup
return (yield)
^^^^^
pytest_fixtures/component/virtwho_config.py:345: in deploy_type_ui
hypervisor_name, guest_name = deploy_configure_by_script(
robottelo/utils/virtwho.py:357: in deploy_configure_by_script
raise VirtWhoError(f"Failed to deploy configure by …
```
> [6.16.z] Fix deploy_configure_by_script for Virtwho tests

- robottelo/utils/virtwho.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19151
- Test which configures Virtwho with scripts fails because `deploy_configure_by_script` fail to put the script on satellite.
```
../../lib64/python3.12/site-packages/pytest_asyncio/plugin.py:681: in pytest_fixture_setup
return (yield)
^^^^^
tests/foreman/conftest.py:74: in ui_session_record_property
request.getfixturevalue(fixture), Satellite
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../lib64/python3.12/site-packages/pytest_asyncio/plugin.py:681: in pytest_fixture_setup
return (yield)
^^^^^
pytest_fixtures/component/virtwho_config.py:345: in deploy_type_ui
hypervisor_name, guest_name = deploy_configure_by_script(
robottelo/utils/virtwho.py:357: in deploy_configure_by_script
raise VirtWhoError(f"Failed to deploy configure by …
```
> [6.15.z] Fix deploy_configure_by_script for Virtwho tests

- pytest_fixtures/component/virtwho_config.py
- robottelo/utils/virtwho.py
- Currently, some of the virtwho tests are failing on subscription-manager registration for host with `This system is already registered. Use --force to override` error.
- Also, the satellite doesn't have base repos enabled, causing test failure on virt-who package install.
- Use the `--force` option during host registration.
- Register Satellite with CDN.
- SAT-36522
> Fix virtwho tests failing on subscription-manager registration

- pytest_fixtures/component/virtwho_config.py
- robottelo/utils/virtwho.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19163
- Currently, some of the virtwho tests are failing on subscription-manager registration for host with `This system is already registered. Use --force to override` error.
- Also, the satellite doesn't have base repos enabled, causing test failure on virt-who package install.
- Use the `--force` option during host registration.
- Register Satellite with CDN.
- SAT-36522
> [6.17.z] Fix virtwho tests failing on subscription-manager registration

- pytest_fixtures/component/flatpak.py
- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/cli/test_flatpak.py
Capsule support for flatpak and cert-based authentication has been added and we should have a test case for that.
This PR proposes such a test case.
https://issues.redhat.com/browse/SAT-33261
```
pytest: tests/foreman/cli/test_capsulecontent.py -k test_sync_consume_flatpak_repo_via_cv
```
> Add a test case for flatpak app install via Capsule and CV

- tests/foreman/ui/test_flatpak.py
In 6.18 we are adding/extending the Flatpak-related UI and we need to cover it.
This PR just extends the basic test case with a check for the flatpak remote details page and adds coverage for the basic actions.
https://issues.redhat.com/browse/SAT-30904
https://github.com/SatelliteQE/airgun/pull/1924
https://github.com/Katello/katello/pull/11424
https://github.com/Katello/katello/pull/11452
https://github.com/Katello/katello/pull/11461
```
pytest: tests/foreman/ui/test_flatpak.py
airgun: 1924
Katello:
katello: 11461
```
> Extend flatpak remotes test with remote details page inspection

- pytest_fixtures/component/rh_cloud.py
- pytest_fixtures/core/sat_cap_factory.py
- robottelo/host_helpers/satellite_mixins.py
- robottelo/hosts.py
- Foreman mantain tests are failing on registry login because `Podman` is not installed.
- There have been changes in ansible playbook that configure IoP Satellite, it now doesn't work with pre-installed Satellite.
- Make sure `Podman` is installed.
- Get an unconfigured satellite using `deploy-unconfigured-satellite` to configure IoP Satellite.
> Fix IoP foreman-maintain tests failing on podman login

- pytest_fixtures/component/mcp.py
- tests/foreman/sys/test_mcp.py
MCP server can pass credentials from client to satellite
Test basic scenario for clients with different viewer roles
> test mcp client authentication

- tests/foreman/cli/test_container_management.py
In 6.18 also the support for cert-based login to the Capsule has been added. We already have such a test case for Satellite, so we can parametrize it to test both.
This PR proposes such extension.
I've moved the moste of the setup to the module-scoped `stage_setup` fixture so we can exercise the host registration and podman search/pull part in the test itself.
https://issues.redhat.com/browse/SAT-33260
```
pytest: tests/foreman/cli/test_container_management.py -k test_podman_cert_auth
```
> Extend the podman cert auth test case for capsules

- pytest_fixtures/component/maintain.py
- tests/foreman/maintain/test_maintenance_mode.py
- test_positive_maintenance_mode sets ':manage_crond: true' in /etc/foreman-maintain/foreman_maintain.yml But with since https://github.com/theforeman/foreman_maintain/pull/910 we don't need to do that.
- Remove manage_crond setup code from the test
- SAT-36764
> Remove manage_crond setup from test_positive_maintenance_mode

- tests/foreman/api/test_subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19246
Update outdated `test_sca_end_to_end`.
This PR should also fix some PIT and upgrade test failures.
```
pytest: tests/foreman/api/test_subscription.py -k "test_sca_end_to_end"
```
> [6.17.z] sca E2E fix

- tests/foreman/api/test_subscription.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19246
Update outdated `test_sca_end_to_end`.
This PR should also fix some PIT and upgrade test failures.
```
pytest: tests/foreman/api/test_subscription.py -k "test_sca_end_to_end"
```
> [6.16.z] sca E2E fix

- tests/foreman/api/test_acs.py
- tests/foreman/cli/test_acs.py
There are still some ACS bulk tests which fail in IPv6 pipeline since they can't reach out to the IPv4 source, because ACSes have the HTTP proxy set separately for the capsule they are using.
Set the ACS HTTP proxy on the Capsule used by ACS to the IPv6 proxy and create the ACS with `use_http_proxies` option.
```
pytest:  tests/foreman/api/test_acs.py -k bulk_actions
```
```
pytest:  tests/foreman/cli/test_acs.py -k bulk_actions
```
> Fix ACS IPv6 bulk tests with ACS HTTP proxy

- tests/foreman/api/test_acs.py
- tests/foreman/cli/test_acs.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19245
There are still some ACS bulk tests which fail in IPv6 pipeline since they can't reach out to the IPv4 source, because ACSes have the HTTP proxy set separately for the capsule they are using.
Set the ACS HTTP proxy on the Capsule used by ACS to the IPv6 proxy and create the ACS with `use_http_proxies` option.
```
pytest:  tests/foreman/api/test_acs.py -k bulk_actions
```
```
pytest:  tests/foreman/cli/test_acs.py -k bulk_actions
```
> [6.17.z] Fix ACS IPv6 bulk tests with ACS HTTP proxy

- tests/foreman/cli/test_fact.py
There was a check on the mac address as a part of [SAT-27056 ](https://issues.redhat.com/browse/SAT-27056) but that issue has been closed saying not going to implement. which start failing check for mac address.
Removing that check as its no longer valid
SAT-27056
pytest:  tests/foreman/cli/test_fact.py -k 'test_positive_facts_end_to_end'
> Removing check for mac-address as its no longer valid use case as per SAT-27056

- tests/foreman/cli/test_fact.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19270
There was a check on the mac address as a part of [SAT-27056 ](https://issues.redhat.com/browse/SAT-27056) but that issue has been closed saying not going to implement. which start failing check for mac address.
Removing that check as its no longer valid
SAT-27056
pytest:  tests/foreman/cli/test_fact.py -k 'test_positive_facts_end_to_end'
> [6.17.z] Removing check for mac-address as its no longer valid use case as per SAT-27056

- conf/server.yaml.template
- pytest_fixtures/core/sat_cap_factory.py
Due to incorrect use of workflow arg in module_unconfigured_satellite fixture, it fails currently with below error
```
pytest_fixtures/core/sat_cap_factory.py:85: in factory
vmb = Broker(
E   TypeError: broker.broker.Broker() got multiple values for keyword argument 'workflow'
```
1. Using workflow arg for passing workflow in module_unconfigured_satellite
2. Adding unconfigured sat workflow to deploy_workflows in server config
satellite-jenkins MR#1760 and see test results on Jenkins MR
> Fix use of workflow arg in module_unconfigured_satellite

- robottelo/cli/settings.py
- tests/foreman/cli/test_settings.py
Missing test for hammer settings info command
Added test for hammer settings info
pytest tests/foreman/cli/test_settings.py -k 'test_positive_existing_setting_info or test_negative_non_existing_setting_info'
> Added test for Settings info CLI command

- tests/foreman/ui/test_hostcollection.py
Fields on Job invocation detail page has been changed 
Added fix to fetch details as per new page
New details are coming in below format 
`{'menu': ['NlDDexjLMl', 'oIEnrYtkKyi'], 'menu_search': '', 'flash': [], 'logout': 'Log Out', 'current_user': 'Admin User', 'account_menu': 'Admin User', 'product': 'foreman', 'breadcrumb': 'Install package(s) bear', 'title': 'Install package(s) bear', 'create_report': 'Create report', 'actions': '', 'rerun_all': 'Rerun all', 'overall_status': {'succeeded_hosts': 0, 'total_hosts': 2, 'is_success': False}, 'status': {'Succeeded': 0, 'Failed': 2, 'In Progress': 0, 'Cancelled': 0}, 'overview': {'Effective user': 'root', 'Started at': 'Aug 29, 2025, 14:39 GMT+5:30', 'SSH user': 'Not available', 'Template': 'Install Package - Katello Script Default'}, …
> Details from job invocation page has been changed

- tests/foreman/cli/test_capsulecontent.py
- tests/foreman/cli/test_flatpak.py
- tests/foreman/cli/test_satellitesync.py
1. I've bumped into a test interference during `6.17.z` FTA. In short - the `flatpak remote-ls` lists all installable apps regardless the remote source they come from. Thus in case of parallel tests run there can be more remotes created on the _module-scoped_ contenthost, resulting in false positive assertion error where the tested app is offered by another remote, not the tested one.
```
tests/foreman/cli/test_flatpak.py:479: in test_sync_consume_flatpak_repo_via_cv
assert 'firefox' not in res.stdout
E   AssertionError: assert 'firefox' not in 'firefox\tor...dplQDawbeD\n'
E     
E     'firefox' is contained here:
E       firefox	org.mozilla.firefox		stable	x86_64	SAT-remote-lVctwtBNnI
E     ? +++++++
E       redhat platform	com.redhat.Platform		el10	x86_64	SAT-remote-lVctwtBNnI
E …
```
> Scope flatpak remote-ls for particular remote and fix uninstall

- tests/foreman/cli/test_repository.py
There was a `KeyError: 'included-container-image-tags'` and bug `SAT-26322` has been closed with Won't Do status so need to remove if condition 
Removed the if condition block
[SAT-26322](https://issues.redhat.com/browse/SAT-26322)
```
pytest: tests/foreman/cli/test_repository.py -k 'test_positive_synchronize_docker_repo_set_tags_later_content_only'
```
> fix KeyError included container image tags

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19301
There was a `KeyError: 'included-container-image-tags'` and bug `SAT-26322` has been closed with Won't Do status so need to remove if condition 
Removed the if condition block
[SAT-26322](https://issues.redhat.com/browse/SAT-26322)
```
pytest: tests/foreman/cli/test_repository.py -k 'test_positive_synchronize_docker_repo_set_tags_later_content_only'
```
> [6.16.z] fix KeyError included container image tags

- tests/foreman/sys/test_fam.py
repos.fedorapeople.org/pulp is gone and the tests that tried to sync content from there fail.
However, that host is used in the test files that FAM ships (will be updated in https://github.com/theforeman/foreman-ansible-modules/pull/1899)
Replace the use of repos.fedorapeople.org with fixtures.pulpproject.org like in https://github.com/theforeman/foreman-ansible-modules/pull/1899
This workaround can be dropped once the change in FAM is present in all supported Satellite branches.
```
pytest: -v tests/foreman/sys/test_fam.py::test_positive_run_modules_and_roles[content_view_filter_info]
```
> Use fixtures.pulpproject.org instead of repos.fedorapeople.org for FAM

- tests/foreman/endtoend/test_cli_endtoend.py
(cherry picked from commit 2a4bf7ad8eac8de6a01db74aa8e5c7022f13816f)
Earlier we cherrypicked https://github.com/SatelliteQE/robottelo/pull/18945 to 6.17.z, which didn't incorporate changes from SAT-35580, which is fixed recently in 6.17.z
Fixing CLI e2e test, by incorporating changes from SAT-35580
> [6.17.z] Fix CLI e2e test, by incorporating changes from SAT-35580

- tests/foreman/sys/test_fam.py
FAM tests require data from the internet, but during ipv6-only tests we need a proxy to do so
enable the Satellite proxy
> enable Satellite proxy if we have no ipv4 networking

- tests/foreman/ui/test_rhcloud_insights.py
Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/19287
```
pytest: tests/foreman/ui/test_rhcloud_insights.py -k "test_rhcloud_insights_remediate_multiple_hosts[rhel10-ipv4]"
```
> [6.17.z] remediate multiple hosts extension and IOP parametrization removal

- tests/foreman/ui/test_discoveryrule.py
Discovery rule test `test_positive_list_host_based_on_rule_search_query` fails as no hosts gets discovered on the IPv6-only setups.
Skipping Discovery rule test for IPv6-only run, as Discovery isn't supported for IPv6
> Skip Discovery rule test for IPv6-only run

- tests/foreman/ui/test_discoveryrule.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19330
Discovery rule test `test_positive_list_host_based_on_rule_search_query` fails as no hosts gets discovered on the IPv6-only setups.
Skipping Discovery rule test for IPv6-only run, as Discovery isn't supported for IPv6
> [6.17.z] Skip Discovery rule test for IPv6-only run

- .github/dependabot.yml
- conf/robottelo.yaml.template
- robottelo/constants/__init__.py
New 6.18.z downstream and master points to stream that is 6.19
- Dependabot.yaml cherrypicks to 6.18.z
- Robottelo conf and constants now uses 6.19 and 6.18.z satellite versions
> [master]: Changes for new 6.18.z branch

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19301
There was a `KeyError: 'included-container-image-tags'` and bug `SAT-26322` has been closed with Won't Do status so need to remove if condition 
Removed the if condition block
[SAT-26322](https://issues.redhat.com/browse/SAT-26322)
```
pytest: tests/foreman/cli/test_repository.py -k 'test_positive_synchronize_docker_repo_set_tags_later_content_only'
```
> [6.15.z] fix KeyError included container image tags

- .github/workflows/auto_branching.yml
- .github/workflows/dependency_merge_zstream.yml
We've dependency_merge GHA which is specific to master branch, and every time we branch using auto-branching workflow, we require to update the workflow in zstream branches for auto-merging like https://github.com/SatelliteQE/robottelo/pull/19344
- Add new dependency_merge_zstream GHA for zstream branches in master
- Remove dependency_merge GHA which is master specific while auto-branching
> Add new dependency_merge_zstream GHA for zstream branches

- tests/foreman/maintain/test_health.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19329
1. After applying https://github.com/SatelliteQE/robottelo/pull/12796, the assertions were incorrectly changed
2. foreman-maintain test to validate DHCP config fails for IPv6 run in installer
1. Fixed the existing assertions, and added assertions for checking RC of f-m commands
2. Skipping the test as DHCPv6 is not managed on IPv6-only setup, so it doesn't makes sense to test this scenario on IPv6.
> [6.17.z] Fix assertions and skip IPv6 in FM DHCP config test

- tests/foreman/destructive/test_installer.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19307
test_negative_installer_invalid_dns_forwarder fails on jenkins because of Output handling difference between local and Jenkins environments.
Jenkins captures the error in stderr instead of stdout.
Combine both stdout and stderr before assertion.
• Updated assertion:
> [6.18.z] Fix for test_negative_installer_invalid_dns_forwarder failure on jenkins

- tests/foreman/cli/test_settings.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19320
Hostname facts setting test was stubbed
Automate stubbed test for Hostname facts setting
pytest: tests/foreman/cli/test_settings.py -k 'test_positive_update_hostname_default_facts'
> [6.18.z] Automate stubbed test for Hostname facts setting

- robottelo/host_helpers/cli_factory.py
- tests/foreman/api/test_contentview.py
API coverage for RFE 6.18.0 [SAT-28495], Rolling ContentViews (19 unique cases, 2 stubbed)
Extensive initial api foundation, to cover almost all RollingCV cases.
Hammer coverage to come will be linked (10-12 cases)
^ related: `cli_factory`: new setup method - override repo(s) for activation key.
```
pytest: tests/foreman/api/test_contentview.py::TestRollingContentView
```
> [SAT-28495] Rolling ContentViews API automation

- tests/foreman/cli/test_rhcloud_inventory.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/19066
```
pytest: tests/foreman/cli/test_rhcloud_inventory.py -k "test_positive_inventory_recommendation_sync[rhel10-ipv4]"
```
> [6.17.z] recommendation sync CLI test fix

- robottelo/host_helpers/cli_factory.py
- tests/foreman/api/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19262
API coverage for RFE 6.18.0 [SAT-28495], Rolling ContentViews (19 unique cases, 2 stubbed)
Extensive initial api foundation, to cover almost all RollingCV cases.
Hammer coverage to come will be linked (10-12 cases)
^ related: `cli_factory`: new setup method - override repo(s) for activation key.
```
pytest: tests/foreman/api/test_contentview.py::TestRollingContentView
```
> [6.18.z] [SAT-28495] Rolling ContentViews API automation

- tests/foreman/ui/test_hostgroup.py
Fix loooong failing `test_positive_clone_host_groups`.
Change asserts,
update airgun.
Needs: https://github.com/SatelliteQE/airgun/pull/2021
```
pytest: tests/foreman/ui/test_hostgroup.py -k 'test_positive_clone_host_groups'
airgun: 2021 
```
> Host Group Test Fix 

- tests/foreman/ui/test_hostgroup.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19418
Fix loooong failing `test_positive_clone_host_groups`.
Change asserts,
update airgun.
Needs: https://github.com/SatelliteQE/airgun/pull/2022
```
pytest: tests/foreman/ui/test_hostgroup.py -k 'test_positive_clone_host_groups'
airgun: 2022
```
> [6.17.z] Host Group Test Fix 

- tests/foreman/api/test_reporttemplates.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19367
QE coverage for exporting report is missing for report template
Adding Coverage for exporting report in report template
Dependent PR: https://github.com/SatelliteQE/nailgun/pull/1349
> [6.17.z] Automate stubbed testcase to export report

- tests/foreman/cli/test_errata.py
Some of the errata tests fail in setup with
```
'errors': ["It's not possible to provide environment_ids for anything other than a rolling content view."]
```
since with https://github.com/Katello/katello/pull/11489 the LCE assignment on CV create is possible only for the rolling CVs.
Get rid of the `environment` param on create, the setup is done further in the `setup_org_for_a_custom_repo` anyway.
```
pytest: tests/foreman/cli/test_errata.py -k test_apply_errata_using_default_content_view
```
> Get rid of direct LCE assign on CV create

- robottelo/hosts.py
At this moment, there is a difference between `rhel_contenthost.register()` and `rhel_contenthost.api_register()`.
`rhel_contenthost.register()` explicitly says `setup_insights=False,`
and
`rhel_contenthost.api_register()` does not.
Not every test needs insights to be set up so I am making this change for us to be consistent in the registration procedure which we use in robottelo.
Add `kwargs['setup_insights'] = kwargs.get('setup_insights', False)` to `api_regiter()`
This change also fixes several tests which fail while running the registration command with RC:1 due to the repos not being enabled. 
Currently, `api_register()` is not used in any RHCloudInsights tests.
```
pytest: tests/foreman/api/test_registration.py -k …
```
> disable insights in api_register() so it is the same as in register()

- tests/foreman/ui/test_fact.py
Change the registration procedure in the test.
```
pytest: tests/foreman/ui/test_fact.py -k "test_positive_upload_host_facts"
```
> facts test fix

- tests/foreman/ui/test_fact.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19443
Change the registration procedure in the test.
```
pytest: tests/foreman/ui/test_fact.py -k "test_positive_upload_host_facts"
```
> [6.18.z] facts test fix

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19445
At this moment, there is a difference between `rhel_contenthost.register()` and `rhel_contenthost.api_register()`.
`rhel_contenthost.register()` explicitly says `setup_insights=False,`
and
`rhel_contenthost.api_register()` does not.
Not every test needs insights to be set up so I am making this change for us to be consistent in the registration procedure which we use in robottelo.
Add `kwargs['setup_insights'] = kwargs.get('setup_insights', False)` to `api_regiter()`
This change also fixes several tests which fail while running the registration command with RC:1 due to the repos not being enabled. 
Currently, `api_register()` is not used in any RHCloudInsights tests.
```
pytest: …
```
> [6.17.z] disable insights in api_register() so it is the same as in register()

- robottelo/hosts.py
Now the `subscribed` property reports falsely on the hosts that present their Unregistered state by this message `'Overall Status: Not registered'`
Use the status of `subscription-manager identity` which works like this:
RC:0 registered
RC:1 not registered
RC:anythingElse error
This approach should be future-proof of different subscription-manager status outputs
How did I test this change?
```python
@pytest.mark.rhel_ver_list([7, 8, 9, 10])
@pytest.mark.no_containers
def test_subscribed_property(
rhel_contenthost,
target_sat,
module_ak,
module_org,
):
rhel_contenthost.execute(r'subscription-manager unregister')
rhel_contenthost.execute(r'subscription-manager clean')
assert not rhel_contenthost.subscribed
rhel_contenthost.api_register(
target_sat,
organization=module_org, …
```
> hosts subscribed property extension

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19436
Now the `subscribed` property reports falsely on the hosts that present their Unregistered state by this message `'Overall Status: Not registered'`
Use the status of `subscription-manager identity` which works like this:
RC:0 registered
RC:1 not registered
RC:anythingElse error
This approach should be future-proof of different subscription-manager status outputs
How did I test this change?
```python
@pytest.mark.rhel_ver_list([7, 8, 9, 10])
@pytest.mark.no_containers
def test_subscribed_property(
rhel_contenthost,
target_sat,
module_ak,
module_org,
):
rhel_contenthost.execute(r'subscription-manager unregister')
rhel_contenthost.execute(r'subscription-manager clean')
assert not rhel_contenthost.subscribed …
```
> [6.15.z] hosts subscribed property extension

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19436
Now the `subscribed` property reports falsely on the hosts that present their Unregistered state by this message `'Overall Status: Not registered'`
Use the status of `subscription-manager identity` which works like this:
RC:0 registered
RC:1 not registered
RC:anythingElse error
This approach should be future-proof of different subscription-manager status outputs
How did I test this change?
```python
@pytest.mark.rhel_ver_list([7, 8, 9, 10])
@pytest.mark.no_containers
def test_subscribed_property(
rhel_contenthost,
target_sat,
module_ak,
module_org,
):
rhel_contenthost.execute(r'subscription-manager unregister')
rhel_contenthost.execute(r'subscription-manager clean')
assert not rhel_contenthost.subscribed …
```
> [6.17.z] hosts subscribed property extension

- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19436
Now the `subscribed` property reports falsely on the hosts that present their Unregistered state by this message `'Overall Status: Not registered'`
Use the status of `subscription-manager identity` which works like this:
RC:0 registered
RC:1 not registered
RC:anythingElse error
This approach should be future-proof of different subscription-manager status outputs
How did I test this change?
```python
@pytest.mark.rhel_ver_list([7, 8, 9, 10])
@pytest.mark.no_containers
def test_subscribed_property(
rhel_contenthost,
target_sat,
module_ak,
module_org,
):
rhel_contenthost.execute(r'subscription-manager unregister')
rhel_contenthost.execute(r'subscription-manager clean')
assert not rhel_contenthost.subscribed …
```
> [6.18.z] hosts subscribed property extension

- robottelo/constants/__init__.py
- robottelo/host_helpers/satellite_mixins.py
- robottelo/hosts.py
For enabling IoP in tests, Sat needs to be able to pull images from the quay.io on internet, but during ipv6-only tests we'll need a proxy to do so
Configure IPv6 system proxy to reach container registry to enable IoP in tests
> Configure IPv6 system proxy to reach container registry to enable IoP

- tests/foreman/ui/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19478
Set setup_insights to false as it is not needed in this test.
Similar to https://github.com/SatelliteQE/robottelo/pull/19465
```
pytest: tests/foreman/ui/test_registration.py -k "test_subscription_manager_install_from_repository[rhel10-ipv4]"
```
> [6.18.z] API Registration Test Install from repo fix

- robottelo/constants/__init__.py
- robottelo/host_helpers/satellite_mixins.py
- robottelo/hosts.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19331
For enabling IoP in tests, Sat needs to be able to pull images from the quay.io on internet, but during ipv6-only tests we'll need a proxy to do so
Configure IPv6 system proxy to reach container registry to enable IoP in tests
> [6.18.z] Configure IPv6 system proxy to reach container registry to enable IoP

- tests/foreman/api/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19475
Removed scenarios are already covered in `test_provisioning.py::test_rhel_pxe_provisioning`
https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/api/test_provisioning.py#L67
Remove them.
> [6.18.z] Remove stubb tests covered with test_provisioning.py::test_rhel_pxe_provisioning

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19501
Fix failure due to different  organization/location assignment 
pytest: tests/foreman/ui/test_host.py -k  test_read_host_with_ics_domain
airgun: 1980
> [6.18.z] Fix failure due to different  organization/location assignment 

- tests/foreman/sys/test_fam.py
this test requires a setup with a dedicated host that has unapplied errata, and we do not have such a setup available right now
skip the test for now
> skip host_errata_info test for FAM

- tests/foreman/sys/test_fam.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19529
this test requires a setup with a dedicated host that has unapplied errata, and we do not have such a setup available right now
skip the test for now
> [6.18.z] skip host_errata_info test for FAM

- tests/foreman/destructive/test_host.py
SAT-36783 states that remote execution cockpit integration fails if wide characters are present anywhere in the communication. This can typically happen in passwords. This PR extends the existing cockpit test to cover this situation.
Set a password on the test host as a parameter. Its value should get propagated to the communication, making the test fail until the bug is resolved.
https://issues.redhat.com/browse/SAT-36783
Companion to https://github.com/theforeman/foreman_remote_execution/pull/1004
> Cover SAT-36783 in cockpit test

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19551
The issue bellow has been closed as "Won't do", but we already have some assertions hooked on that bug resolution.
Since they "Won't do" the fix, just remove the conditioned assertions.
https://issues.redhat.com/browse/SAT-26322
```
pytest:  tests/foreman/cli/test_repository.py -k 'set_tags_later_additive or set_tags_later_content_only or with_mix_valid_invalid_tags'
```
> [6.18.z] Remove conditions for an unfixed bug

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19551
The issue bellow has been closed as "Won't do", but we already have some assertions hooked on that bug resolution.
Since they "Won't do" the fix, just remove the conditioned assertions.
https://issues.redhat.com/browse/SAT-26322
```
pytest:  tests/foreman/cli/test_repository.py -k 'set_tags_later_additive or set_tags_later_content_only or with_mix_valid_invalid_tags'
```
> [6.16.z] Remove conditions for an unfixed bug

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19243
Host details test case was not updated as per latest UI page. 
Updated all conditions to assert details  as per new host details page
```
pytest: tests/foreman/ui/test_host.py -k "test_positive_search_by_parameter_with_different_values or test_positive_search_by_parameter or test_negative_remove_parameter_non_admin_user or test_positive_assign_taxonomies or test_positive_read_from_details_page"
```
> [6.18.z] Fix to read all details page

- tests/foreman/api/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19571
RHEL10 has been added to the `supportability.yaml` and constants. However, without the [minor version](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/constants/__init__.py#L625), which was unexpected by `test_positive_sync_kickstart_check_os`.
Fix the test to handle any version, use `0` when minor is not provided.
https://issues.redhat.com/browse/SAT-37889
```
pytest: tests/foreman/api/test_repository.py -k test_positive_sync_kickstart_check_os
```
> [6.16.z] Fix test_positive_sync_kickstart_check_os

- conf/fam.yaml.template
The `conf/fam.yaml.template` did not define `image_uuid` values for libvirt,
causing issues when running compute resource and image-related tests that
expect multiple images.
Added `image_uuid` and `image_uuid_2` entries under the libvirt
`compute_resource` section to support multiple image paths
> Add multiple libvirt image UUIDs to fam.yaml template

- conf/fam.yaml.template
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19592
The `conf/fam.yaml.template` did not define `image_uuid` values for libvirt,
causing issues when running compute resource and image-related tests that
expect multiple images.
Added `image_uuid` and `image_uuid_2` entries under the libvirt
`compute_resource` section to support multiple image paths
> [6.18.z] Add multiple libvirt image UUIDs to fam.yaml template

- conf/fam.yaml.template
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19592
The `conf/fam.yaml.template` did not define `image_uuid` values for libvirt,
causing issues when running compute resource and image-related tests that
expect multiple images.
Added `image_uuid` and `image_uuid_2` entries under the libvirt
`compute_resource` section to support multiple image paths
> [6.15.z] Add multiple libvirt image UUIDs to fam.yaml template

- tests/foreman/cli/test_ansible.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18251
Added `?search=` to the endpoint to retrieve the particular host, allowing us to perform assertions against our specific host.
This change was made to address a failure occurring during the upgrade test. In upgrade scenarios, multiple hosts may already exist, leading to conflicts. Previously, the test only fetched hosts from the first page, and if the expected host was on a subsequent page, it would not be found. By specifying the `search` parameter, we ensure our specific host will fetch from across the page, which should prevent such issues.
> [6.16.z] Retrieve the correct host info from the inventories.

- tests/foreman/api/test_contentview.py
This PR adds a test for the content view environment endpoint. This test ensures that results in responses from this endpoint contain a top-level `id` field for the content view environment and that a search query to the endpoint scoped to the `label` field is successful.
> Add test for content view environment endpoint

- tests/foreman/cli/test_computeresource_libvirt.py
Libvirt image create test failing with `Error making a connection to libvirt URI qemu+ssh://root@env-libvirt.redhat.com/system:\n  Call to virConnectOpen failed: Cannot recv data: Host key verification failed.: Connection reset by peer`  after upstream fix for v6.18+
1. Use configure_libvirt_cr() helper to fix above error
2. Improve existing test to extend for CRUD operations on image
3. Use teardown to delete CR with finalizer
> Fix and improve libvirt image CRUD test

- tests/foreman/cli/test_repository_set.py
This test contains several operations with hammer command, like enable repositories, list available repositories, disable repositories, etc. Due to [SAT-38447](https://issues.redhat.com/browse/SAT-38447)  `hammer repository-set disable` command is failing
Skip the test till bug get fix
N/A
```
pytest: tests/foreman/cli/test_repository_set.py -k 'test_positive_list_available_repositories'
```
> skip list available repositories test case due to Jira SAT-38447

- tests/foreman/cli/test_satellitesync.py
We had a customer facing bug regarding the format inheritance which needs coverage, see the issue bellow for more details.
This PR proposes the coverage.
https://issues.redhat.com/browse/SAT-32715
```
pytest: tests/foreman/cli/test_satellitesync.py -k test_positive_export_format_inheritance
Katello:
katello: 11462
```
> Add a test case for ISS export format inheritance

- tests/foreman/api/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19625
The `test_negative_synchronize_private_registry_wrong_repo` is failing since as far as I can see in history, most probably since the age of pulp2. With pulp3, however, for any repo sync error we get just a "Pulp task error" without any details. Finer error granularization would mean a new RFE.
Just update the expected error message so it matches the reality.
```
pytest: tests/foreman/api/test_repository.py -k test_negative_synchronize_private_registry_wrong_repo
```
> [6.18.z] Fix test_negative_synchronize_private_registry_wrong_repo

- tests/foreman/api/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19665
We should avoid `is_open` conditions in build_sanity tests (there is an offline/email thread).
Remove it since the issue has been resolved.
https://issues.redhat.com/browse/SAT-25813
```
pytest: tests/foreman/api/test_capsulecontent.py -k test_positive_sync_container_repo_end_to_end
```
> [6.18.z] Remove is_open from api/test_capsulecontent

- tests/foreman/api/test_capsulecontent.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19665
We should avoid `is_open` conditions in build_sanity tests (there is an offline/email thread).
Remove it since the issue has been resolved.
https://issues.redhat.com/browse/SAT-25813
```
pytest: tests/foreman/api/test_capsulecontent.py -k test_positive_sync_container_repo_end_to_end
```
> [6.17.z] Remove is_open from api/test_capsulecontent

- conf/ansible.yaml.template
- robottelo/config/validators.py
- tests/foreman/api/test_ansible.py
- tests/foreman/cli/test_ansible.py
ansible role names are hardcoded
Make ansible  role names configurable as setting
```
tests/foreman/api/test_ansible.py::TestAnsibleCfgMgmt::test_add_and_remove_ansible_role_hostgroup
tests/foreman/api/test_ansible.py::TestAnsibleCfgMgmt::test_positive_ansible_roles_inherited_from_hostgroup
tests/foreman/cli/test_ansible.py::TestAnsibleCfgMgmt::test_add_and_remove_ansible_role_hostgroup
```
> Add possibility to configure ansible role names in settings

- tests/foreman/ui/test_host.py
Make `test_positive_apply_erratum` more stable.
``` 
pytest: tests/foreman/ui/test_host.py -k "test_positive_apply_erratum" 
```
> applyErratum Fix

- pytest_fixtures/component/rh_cloud.py
- tests/foreman/ui/test_rhcloud_insights_vulnerability.py
Missing e2e test for new IoP vulnerability service
Add e2e test for new IoP vulnerability service
https://github.com/SatelliteQE/airgun/pull/1978
> Add e2e test for IoP vulnerability service

- pytest_fixtures/component/rh_cloud.py
- tests/foreman/ui/test_rhcloud_insights_vulnerability.py
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/19272
Missing e2e test for new IoP vulnerability service
Add e2e test for new IoP vulnerability service
https://github.com/SatelliteQE/airgun/pull/2033
> [6.18.z] Add e2e test for IoP vulnerability service

- tests/new_upgrades/conftest.py
Missed to update network parameter in https://github.com/SatelliteQE/robottelo/pull/19543 for capsule, which causes the capsule checkout only to happens with default network
Added missing network parameter in the new upgrade's capsule checkout module.
> Fixing remaining changes of PR-19543

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19693
Make `test_positive_apply_erratum` more stable.
``` 
pytest: tests/foreman/ui/test_host.py -k "test_positive_apply_erratum" 
```
> [6.18.z] applyErratum Fix

- tests/foreman/ui/test_host.py
So the `Hosts` component UI tests are kinda messy, let's say...
In the `test_host.py` file there are combined tests for the legacy all hosts page and the new all hosts page.
This PR adds `BlockedBy` to the tests, which have been broken for a while. 
They test some of the features that were available in the legacy all hosts page, but are not yet available in the new all hosts page. 
Addition of these features is planned here https://issues.redhat.com/browse/SAT-38425, thus fixing these tests for the legacy page now, just to be rewritten in the near future, does not make sense.
This PR also removes `test_positive_bulk_delete_host` as we already have a working `test_all_hosts_bulk_delete` and 
it also removes `test_positive_inherit_puppet_env_from_host_group_when_action` which uses some …
>  Cleanup of UI tests for Hosts component

- tests/foreman/cli/test_logging.py
grepping yielded no results due to format change in cli task output
> different task description parsing

- tests/foreman/cli/test_logging.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19701
grepping yielded no results due to format change in cli task output
> [6.18.z] different task description parsing

- robottelo/constants/__init__.py
- tests/foreman/ui/test_repository.py
No support presented for  recommended kickstart repositories in robottelo constants and in web ui test module
Update existing test, used parameterised options with kickstart and rpm as ids
**Note:** Test will work on 6.17.0 for both kickstart and rpm options but it will not execute for 6.18.0 as Sat version is not GA'ed and test uses satellite version to check repositories.
```
pytest: tests/foreman/ui/test_repository.py -k 'test_recommended_repos'
airgun: 2049
```
> parameterisation for recommended repository test

- tests/foreman/cli/test_host.py
In RHEL10 the container isn't sending a package profile on dnf transaction.
This change forces a package profile upload by running subscription-manager repos --list command
pytest: tests/foreman/cli/test_host.py -k "test_positive_report_package_installed_removed\[rhel10-ipv4\] or  test_positive_package_applicability\[rhel10-ipv4\] or test_positive_apply_security_erratum\[rhel10-ipv4\]"
> Changes to force a package profile upload

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19721
In RHEL10 the container isn't sending a package profile on dnf transaction.
This change forces a package profile upload by running subscription-manager repos --list command
pytest: tests/foreman/cli/test_host.py -k "test_positive_report_package_installed_removed\[rhel10-ipv4\] or  test_positive_package_applicability\[rhel10-ipv4\] or test_positive_apply_security_erratum\[rhel10-ipv4\]"
> [6.18.z] Changes to force a package profile upload

- tests/foreman/cli/test_host.py
The CLI hosts tests (`test_positive_report_package_installed_removed` and `test_positive_package_applicability`) used outdated `katello_host_tools_host` fixtures and it also used katello_host_tools_host.
Use the same test structure as we use in other tests, i.e. `ui/test_positive_update_delete_package`
``` 
pytest: tests/foreman/cli/test_host.py -k "test_positive_report_package_installed_removed or test_positive_package_applicability" 
```
> Refactor Hosts CLI PackageApplicability Tests

- tests/new_upgrades/conftest.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19671
Missed to update network parameter in https://github.com/SatelliteQE/robottelo/pull/19543 for capsule, which causes the capsule checkout only to happens with default network
Added missing network parameter in the new upgrade's capsule checkout module.
> [6.16.z] Fixing remaining changes of PR-19543

- robottelo/utils/shared_resource.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19578
New upgrade scenarios test cases sometimes stuck infinitely in case of failures happens around main worker's action and test cases abnormal exit. 
Added the `wait_for` retry mechanism to the `act` method and included `self.unregister` in the` __exit__` block to ensure processes are cleaned up reliably after any failure.
> [6.17.z] Fixing scenarios test cases hanging issues

- tests/foreman/cli/test_host.py
The CLI hosts tests (`test_positive_erratum_applicability` and `test_positive_apply_security_erratum`) used outdated `katello_host_tools_host` fixtures, and it also used `katello_host_tools_host`.
Use the same test structure as we use in other tests, i.e., `ui/test_positive_update_delete_package`.
``` 
pytest: tests/foreman/cli/test_host.py -k "test_positive_erratum_applicability or test_positive_apply_security_erratum" 
```
> Refactor CLI Errata Tests for Hosts component

- tests/foreman/sys/test_pulp3_filesystem.py
The `test_content_validation_on_download` is failing on IPv6 network since `localhost` is not recognized.
```
"503, message='Service Unavailable', url='http://localhost/pub/test_YwatxMDDCC'"
```
Provide FQDN instead.
```
pytest: tests/foreman/sys/test_pulp3_filesystem.py -k test_content_validation_on_download
```
> Fix test_content_validation_on_download

- tests/new_upgrades/test_capsulecontent.py
- tests/new_upgrades/test_computeresource_gce.py
- tests/new_upgrades/test_hostgroup.py
- tests/upgrades/test_capsulecontent.py
- tests/upgrades/test_computeresource_gce.py
- tests/upgrades/test_hostgroup.py
* Change ownership of capsule sync upgrades to Artemis
* Change ownership of provisioning upgrades to Rocket
* Change ownership of hostgroup upgrades to Proton
(cherry picked from commit 955750374de872cac968d3f2c6fb18381c4788f6)
Fixes https://github.com/SatelliteQE/robottelo/issues/19758
> Reflect team changes in upgrades test ownership (#19573)

- tests/foreman/cli/test_repository.py
Searching error `nil:NilClass (NoMethodError)` using grep command from production.log was failing
**Error**
```
AssertionError: assert 2 == 1
+  where 2 = stdout:\n\nstderr:\nbash: -c: line 1: unexpected EOF while looking for matching ``'\nbash: -c: line 2: syntax error: unexpected end of file\n\nstatus: 2.status
```
Added escape charactor will fix this issue
PRT test Cases example
```
pytest: tests/foreman/cli/test_repository.py -k 'test_positive_create_repo_with_new_organization_and_location'
```
> fix grep commmand

- tests/foreman/cli/test_repository.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19769
Searching error `nil:NilClass (NoMethodError)` using grep command from production.log was failing
**Error**
```
AssertionError: assert 2 == 1
+  where 2 = stdout:\n\nstderr:\nbash: -c: line 1: unexpected EOF while looking for matching ``'\nbash: -c: line 2: syntax error: unexpected end of file\n\nstatus: 2.status
```
Added escape charactor will fix this issue
PRT test Cases example
```
pytest: tests/foreman/cli/test_repository.py -k 'test_positive_create_repo_with_new_organization_and_location'
```
> [6.17.z] fix grep commmand

- tests/foreman/cli/test_host.py
This is from PR https://github.com/SatelliteQE/robottelo/pull/18936  as it was not cherry picked.
pytest: tests/foreman/cli/test_host.py -k "test_positive_create_with_lce_and_cv or test_positive_create_and_delete or test_positive_create_inherit_lce_cv or test_positive_list_with_nested_hostgroup"
> [6.17.z] Fix for host cli lce and cv as those name changed in output

- tests/foreman/cli/test_rhcloud_inventory.py
The test `test_positive_generate_reports_job_cli_disconnected` is failing because of [SAT-38836](https://issues.redhat.com/browse/SAT-38836)
Block the test from running until the issue is resolved
> Block test_positive_generate_reports_job_cli_disconnected from running bcs of BZ

- tests/foreman/cli/test_rhcloud_inventory.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19774
The test `test_positive_generate_reports_job_cli_disconnected` is failing because of [SAT-38836](https://issues.redhat.com/browse/SAT-38836)
Block the test from running until the issue is resolved
> [6.18.z] Block test_positive_generate_reports_job_cli_disconnected from running bcs of BZ

- tests/foreman/cli/test_rhcloud_inventory.py
The network protocol `https` was defined in the no-proxy, which prevented Satellite from connecting to itself through the proxy and getting below error:
`worker.go:111: [/usr/libexec/rhc/foreman-rh-cloud-worker] Post "https://satellite.example.com/api/v2/rh_cloud/cloud_request": tls: failed to verify certificate: x509: certificate signed by unknown authority`
Removed HTTPS from the proxy, and automation is covering this scenario.
> Incorrect no-proxy configuration with HTTPS prevents Satellite self-connection

- .pre-commit-config.yaml
This PR backports #19770 to 6.18.z
> [6.18.z] Backport of #19770

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19788
Make `test_positive_update_delete_package` more stable.
Needs https://github.com/SatelliteQE/airgun/pull/2116
``` 
pytest: tests/foreman/ui/test_host.py -k "test_positive_update_delete_package"
airgun: 2116
```
> [6.18.z] More stable updateDeletePackage test

- tests/foreman/ui/test_contenthost.py
Remove tests that test the deprecated `package group install` & `package group remove` feature on soon to be deprecated ContentHosts page.
> remove PackageGroup Tests

- tests/foreman/ui/test_dashboard.py
empty table looks differently now
> assertion fix on dashboard test

- tests/foreman/ui/test_hardwaremodel.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19799
Test `ui/test_hardwaremodel.py/test_positive_end_to_end` is failing because of SAT-38893. 
Let's not run it until it is resolved.
> [6.17.z] block HWmodel test bcs of SAT-38893

- tests/foreman/ui/test_hardwaremodel.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19799
Test `ui/test_hardwaremodel.py/test_positive_end_to_end` is failing because of SAT-38893. 
Let's not run it until it is resolved.
> [6.18.z] block HWmodel test bcs of SAT-38893

- tests/foreman/api/test_capsulecontent.py
The `test_cleanup_orphaned_content` has been failing for a while. Per local testing the `add_proxy_cli_config` does not work as expected, it fails to add the capsule profile to the pulp's `cli.toml`.
This PR proposes a fix.
```
pytest: tests/foreman/api/test_capsulecontent.py -k test_cleanup_orphaned_content
```
> Fix test_cleanup_orphaned_content

- .github/CODEOWNERS
- tests/foreman/sys/test_pulp3_filesystem.py
The `test_selinux_status` is occasionally failing with avc denials unrelated to pulp.
Since this test should be ensuring correct context of pulp, we should narrow down the test case.
Also, it seems the test file is mentioned twice in the `.CODEOWNERS` file.
This PR proposes a fix for both problems.
https://issues.redhat.com/browse/SAT-23121
```
pytest: tests/foreman/sys/test_pulp3_filesystem.py -k test_selinux_status
```
> Narrow down test_selinux_status for pulp services only

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19814
Remove looong (almost always :)) failing `test_positive_install_package_via_rex` from `Hosts` component.
There is no need to test this (REX installation) in `Hosts` component, when it is thoroughly tested in the `REX` component here https://github.com/SatelliteQE/robottelo/blob/365c992c434f08ab68214b5312d81fadb900f4d4/tests/foreman/cli/test_remoteexecution.py#L619
> [6.18.z] Remove CLI REX test from Hosts

- tests/foreman/cli/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19823
Remove long failing, outdated `test_positive_without_attach_with_lce`.
Checking enabled repos is tested in https://github.com/SatelliteQE/robottelo/blob/31ff1e01ec1081ad31011b65c6b2626adb15053e/tests/foreman/cli/test_host.py#L2178
> [6.18.z] Remove outdated  duplicate Host CLI test

- tests/foreman/cli/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19831
The `test_ccv_inc_update_autopublish` is failing flakily with this result on line L3159:
```
AssertionError: assert 'pending' == 'success'
```
It seems like the `wait_for_tasks` sometimes returns task which is still pending. In this case, two tasks are returned: `[0]` is the latest publish we are waiting for, `[1]` is the original publish.
Use `wait_for` until both of the tasks are finished. 
The second task usually takes ~2 seconds, so I set `delay=3, timeout=20`.
```
pytest: tests/foreman/cli/test_contentview.py -k test_ccv_inc_update_autopublish
```
> [6.17.z] Fix test_ccv_inc_update_autopublish

- tests/foreman/cli/test_remoteexecution.py
since katello-agent is not shipped in rhel10 client repo, there is nothing to convert from
> conversion to pull provider not for rhel10

- .pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19860
Spellcheck reports a spelling error when we specify `astroid` as a dependency.
exclude requirements from spellchecking as it has close to 0 value there
> [6.17.z] Exclude requirements from spellcheck

- .pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19860
Spellcheck reports a spelling error when we specify `astroid` as a dependency.
exclude requirements from spellchecking as it has close to 0 value there
> [6.16.z] Exclude requirements from spellcheck

- requirements-optional.txt
Astroid 4.0.0 introduced breaking API changes that cause sphinx-autoapi to crash with:
```
TypeError: AstroidBuilder.__init__() missing 1 required positional argument: 'manager'
```
This pins astroid to versions below 4.0.0 until sphinx-autoapi releases a compatible version.
Related:
- https://github.com/readthedocs/sphinx-autoapi/issues/536
- https://github.com/readthedocs/sphinx-autoapi/pull/538
- https://issues.redhat.com/browse/SAT-38967
> Pin astroid to <4.0.0 to fix sphinx-autoapi compatibility

- requirements-optional.txt
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19858
Astroid 4.0.0 introduced breaking API changes that cause sphinx-autoapi to crash with:
```
TypeError: AstroidBuilder.__init__() missing 1 required positional argument: 'manager'
```
This pins astroid to versions below 4.0.0 until sphinx-autoapi releases a compatible version.
Related:
- https://github.com/readthedocs/sphinx-autoapi/issues/536
- https://github.com/readthedocs/sphinx-autoapi/pull/538
- https://issues.redhat.com/browse/SAT-38967
> [6.16.z] Pin astroid to <4.0.0 to fix sphinx-autoapi compatibility

- requirements-optional.txt
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19858
Astroid 4.0.0 introduced breaking API changes that cause sphinx-autoapi to crash with:
```
TypeError: AstroidBuilder.__init__() missing 1 required positional argument: 'manager'
```
This pins astroid to versions below 4.0.0 until sphinx-autoapi releases a compatible version.
Related:
- https://github.com/readthedocs/sphinx-autoapi/issues/536
- https://github.com/readthedocs/sphinx-autoapi/pull/538
- https://issues.redhat.com/browse/SAT-38967
> [6.18.z] Pin astroid to <4.0.0 to fix sphinx-autoapi compatibility

- tests/foreman/cli/test_host.py
Due to change about exposing true error code of the registration we are getting status code as 1 in case of **Validation failed.**
Added try-finally block to reset setting in case of failure
Change status code to 1 in case we are getting **Validation failed.**
pytest: tests/foreman/cli/test_host.py -k  test_host_registration_with_capsule_using_content_coherence
> Fix status code while Validation failed with content host registration

- tests/foreman/cli/test_auth.py
no need for this to fail until SAT-38951 gets resolved
> skip session tests on SAT-38951

- tests/foreman/api/test_registration.py
Similar changes to https://github.com/SatelliteQE/robottelo/pull/19850 and 
https://github.com/SatelliteQE/robottelo/pull/19870.
The Validation error is exposed in new stream snaps 
``` 
Validation failed: Content view environment content facets invalid: The content source must sync the lifecycle environment assigned to the host. See the logs for more information. (HTTP error code 422: Unprocessable Entity) 
```
This error was previously hidden.
It is expected when `validate_host_lce_content_source_coherence` setting is set to true (default).
Add  
```
@pytest.mark.parametrize(
'setting_update',
['validate_host_lce_content_source_coherence=false'],
indirect=True,
)
```
to the test and add assertions checking the subscription state of the host.
 
``` 
pytest: …
```
> Fix Registration API E2E test

- tests/foreman/cli/test_registration.py
Coverage for https://issues.redhat.com/browse/SAT-34258
Test (`test_negative_register_host_when_sat_has_port_80_blocked`) that registration fails with non 0 RC when there is port 80 blocked on Satellite.
```
pytest: tests/foreman/cli/test_registration.py -k 'test_negative_register_host_when_sat_has_port_80_blocked'
```
> SAT-34258 Coverage

- tests/foreman/cli/test_auth.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19852
no need for this to fail until SAT-38951 gets resolved
> [6.18.z] skip session tests on SAT-38951

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19849
since katello-agent is not shipped in rhel10 client repo, there is nothing to convert from
> [6.17.z] conversion to pull provider not for rhel10

- tests/foreman/cli/test_remoteexecution.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19849
since katello-agent is not shipped in rhel10 client repo, there is nothing to convert from
> [6.18.z] conversion to pull provider not for rhel10

- tests/foreman/api/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19859
Similar changes to https://github.com/SatelliteQE/robottelo/pull/19850 and 
https://github.com/SatelliteQE/robottelo/pull/19870.
The Validation error is exposed in new stream snaps 
``` 
Validation failed: Content view environment content facets invalid: The content source must sync the lifecycle environment assigned to the host. See the logs for more information. (HTTP error code 422: Unprocessable Entity) 
```
This error was previously hidden.
It is expected when `validate_host_lce_content_source_coherence` setting is set to true (default).
Add  
```
@pytest.mark.parametrize(
'setting_update',
['validate_host_lce_content_source_coherence=false'],
indirect=True,
)
```
to the test and add assertions checking the …
> [6.18.z] Fix Registration API E2E test

- tests/foreman/cli/test_registration.py
Similar changes to  https://github.com/SatelliteQE/robottelo/pull/19850 and https://github.com/SatelliteQE/robottelo/pull/19859.
The Validation error is exposed in new stream snaps 
``` 
Validation failed: Content view environment content facets invalid: The content source must sync the lifecycle environment assigned to the host. See the logs for more information. (HTTP error code 422: Unprocessable Entity) 
```
This error was previously hidden.
It is expected when `validate_host_lce_content_source_coherence` setting is set to true (default).
Add  
```
@pytest.mark.parametrize(
'setting_update',
['validate_host_lce_content_source_coherence=false'],
indirect=True,
)
```
to the test and add assertions checking the subscription state of the host.
```
pytest: …
```
> Fix Registration CLI E2E test

- tests/foreman/cli/test_registration.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19870
Similar changes to  https://github.com/SatelliteQE/robottelo/pull/19850 and https://github.com/SatelliteQE/robottelo/pull/19859.
The Validation error is exposed in new stream snaps 
``` 
Validation failed: Content view environment content facets invalid: The content source must sync the lifecycle environment assigned to the host. See the logs for more information. (HTTP error code 422: Unprocessable Entity) 
```
This error was previously hidden.
It is expected when `validate_host_lce_content_source_coherence` setting is set to true (default).
Add  
```
@pytest.mark.parametrize(
'setting_update',
['validate_host_lce_content_source_coherence=false'],
indirect=True,
)
```
to the test and add assertions checking the …
> [6.18.z] Fix Registration CLI E2E test

- tests/foreman/ui/test_settings.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19043
1) The settings field contains "Version $VERSION" and $VERSION should be replaced by actual version, e.g. 6.18.0. When the test compares "Version $VERSION" - the content of the field - with the actually shown footer text, it fails.
For some mysterious reason not yet known to me, the test sometimes got actual text "Version 6.18.0" instead of the unexpanded variable so this actually passed pre-6.18. I don't understand, but this fix should work for both cases.
2) The test somehow presumes the original value to be Yes, even though it doesn't need to be. Fixed.
> [6.17.z] Two Settings UI test fixes

- .pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19878
updates:
- [github.com/astral-sh/ruff-pre-commit: v0.13.2 → v0.13.3](https://github.com/astral-sh/ruff-pre-commit/compare/v0.13.2...v0.13.3)
> [6.18.z] [pre-commit.ci] pre-commit autoupdate

- tests/foreman/ui/test_host.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/19895
`test_positive_update_delete_package` is flaky in the automation.
Try to add a page refresh to the test.
```
pytest: tests/foreman/ui/test_host.py -k "test_positive_update_delete_package"
```
> [6.18.z] Fix flaky UI updateDeletePackage Test

- pytest_fixtures/component/repository.py
- tests/foreman/api/test_contentview.py
Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/18687
*Note: The Version being incrementally updated is not a Version of the Composite, but a version of a filtered CV previously added to the composite (one of its components).
New fixture `fake_yum_repos` (core: contenthosts.py)
4 custom yum repositories in module org/product, that could be useful for many current and future test cases using custom repos.
```
pytest: tests/foreman/api/test_contentview.py::TestContentViewPublishPromote::test_inc_update_composite_updated_expected_version
Katello:
katello: 11411
```
> [6.17.z] [SAT-26559] Incremental Update on a Version contained in a CompositeCV
