robottelo/ui/base.py
* User tests fail for some weird reason only when triggered via
the jenkins, but works locally.
* Added scroll to the top of the page, if this is what's causing
the issue.
=> Fix for the user tests.

tests/foreman/ui/test_template.py
* Removed the old bz-id in the doc-strings
* Added bz-id to skip `test_remove_template`
* Other miscellaneous fixes.
=> Update the UI template tests.

robottelo/ui/activationkey.py, robottelo/ui/locators.py, tests/foreman/ui/test_activationkey.py
This test simply creates a new activation key, then copies it with
a valid name.
Results
-------
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key and copy it ... ok
@Test: Create Activation key …
=> Added UI test for Activation Key copy

tests/foreman/ui/test_subnet.py
Subnet test is failing with utf8 data, so blocked it with bz-id.
=> Subnet_test: Blocked specific utf8 data with bz_id

tests/foreman/ui/test_activationkey.py
I also added a base activation key to reduce extra work, cut test
time from both copy tests by ~120 seconds.
Results
-------
@Test: Create Activation key and fail copying it ... ok
@Test: Create Activation key and fail copying it ... ok
@Test: Create Activation key and fail copying it ... ok
@Test: Create Activation key and fail copying it ... ok
@Test: Create Activation key and fail copying it ... ok
@Test: Create Activation key and fail copying it ... ok
@Test: Create Activation key and fail copying it ... ok
Ran 7 tests in 188.598s
=> Added UI test for an invalid activaiton key copy

robottelo/test.py, robottelo/ui/session.py
The code works but need to add proper comments, docstring , commit message.
Currently just raised as the code is working and for people to take a look at the approach.
=> Added support for taking screenshot of failed and errored testcases

tests/foreman/ui/test_discovery.py
This feature is growing with other components too. I'll add/update more tests stubs as and when I got to know more about this feature..
=> Test stubs for auto provisioning using discovery feature

tests/foreman/cli/test_abrt.py
=> Added stubs for abrt

tests/foreman/ui/test_capsule.py
Additional new UI test cases for capsule isolation.
=> New UI test cases for capsule isolation

docs/api/tests.foreman.ui.rst, tests/foreman/ui/test_capsule.py
Also remove an extra space from test_capsule module in order to generate
consistent docs for its functions.
=> Add UI test_capsule module to the docs

tests/foreman/smoke/test_api_smoke.py
Foreman does not return a correct set of external_usergroup paths when running
on a RHEL 7 system. Give API smoke test `test_get_links` a workaround for this
issue.
Against a RHEL 66 system:
$ nosetests tests/foreman/smoke/test_api_smoke.py -m test_get_links
.
Ran 1 test in 2.077s
OK
Against a RHEL 7 system:
$ nosetests tests/foreman/smoke/test_api_smoke.py -m test_get_links
S
Ran 1 test in 1.851s
OK (SKIP=1)
=> Fix test that is failing due to BZ 1184170

tests/foreman/cli/test_os.py
Method `TestOperatingSystem.test_add_ptable` in module
`tests.foreman.cli.test_os` has been failing in Jenkins for ~100 test runs. Fix
that failure. The root cause is that a command like this is being executed:
hammer os add-ptable --id <os_id> --ptable <ptable_name>
However, the `--ptable` flag does not exist. This accomplishes the same end goal
and is valid:
hammer os add-ptable --id <os_id> --partition-table <ptable_name>
Make that change. Also, streamline the test itself. The test is slightly
lengthier, but should be easier to skim through due to better variable names,
better chunking of code, comments, etc.
=> Fix failing CLI test `test_add_ptable`

tests/foreman/cli/test_org.py
Refactor the following methods:
* `tests.foreman.cli.test_org.TestOrg.test_add_environment`
* `tests.foreman.cli.test_org.TestOrg.test_remove_environment`
Make the tests significantly more compact and readable. Rewrite the assertions
so that, when those assertions fail, more useful information is emitted. Getting
better failure information out of Jenkins is important because those tests have
each been failing in Jenkins for 100+ test runs each, and reproducing the
failures locally is problematic.
=> Make two CLI tests give better failure messages

tests/foreman/ui/test_discovery.py
- Updated existing test stubs with correct test descriptions and removed typos at few places
- Added few more test stubs related to permissions and some invalid scenarios.
=> Added few more test stubs for discovery feature

tests/foreman/cli/test_activationkey.py, tests/foreman/cli/test_contenthost.py, tests/foreman/cli/test_contentviews.py, tests/foreman/cli/test_environment.py, tests/foreman/cli/test_host_collection.py, tests/foreman/cli/test_lifecycleenvironment.py, tests/foreman/cli/test_medium.py, tests/foreman/cli/test_org.py, tests/foreman/cli/test_os.py, tests/foreman/cli/test_partitiontable.py, tests/foreman/cli/test_product.py, tests/foreman/cli/test_proxy.py, tests/foreman/cli/test_roles.py, tests/foreman/cli/test_scparam.py, tests/foreman/cli/test_template.py, tests/foreman/cli/test_user.py
These checks are consuming a significant amount of time, during test runs.
I also removed one test that is not valid.
See https://bugzilla.redhat.com/show_bug.cgi?id=1176600#c3
=> Removed checks for BZs that have been closed for 2+ months

tests/foreman/ui/test_activationkey.py, tests/foreman/ui/test_contentviews.py
- Explicitly creating new org for all manifest import test
- made changes in existing functions and tests to use the `Id` of newly created org instead of default from setUpClass. 
Tested thoroughly  all CV and activation-key tests and hope this should drop the count of failures too.
=> Creating new org to import manifest for all those CV and ak tests which are using RH contents.

tests/foreman/cli/test_activationkey.py
A few other fixes and changes thrown in, but functionality
remains the same. Ran test suite with same results.
=> Fixed activation key CLI test formatting

tests/foreman/ui/test_computeresource.py, tests/foreman/ui/test_settings.py
- updated two param names and removed signo related params
- updated test numbers in test_name as two tests have been removed
- saving and reverting the default value after test execution
=> fixed tests related to param under settings menu

Makefile, docs/index.rst, scripts/graph_entities.py, scripts/lint.py
Cherry picking Makefile improvements. Let's start profiling zstream builds.
=> Cherry pick Makefile improvements

tests/foreman/ui/test_openscap.py
* Initial OpenScap Tests.
* Currently no setup and steps, as the exact steps are not yet
known.
=> Added OpenScap test stubs with various testcases.

robottelo/common/constants.py
See:
* https://github.com/theforeman/foreman-tasks/pull/92
* http://projects.theforeman.org/issues/4450/
=> Add new ForemanTasks permissions

robottelo/cli/factory.py, scripts/graph_entities.py, tests/foreman/api/test_contentview.py
Flake8 started complaining about the position of binary operators `and`
and `or`, fix that.
=> Fix flake8 W503 line break before binary operator

robottelo/ui/contentviews.py, robottelo/ui/factory.py, robottelo/ui/locators.py, tests/foreman/smoke/test_ui_smoke.py
*) Temporarily disabled success and error notifications for smoke
tests.
*) Updated few locators
*) Updated ui/factory `force_context` as Admin User is now placed
in Default_Organization org by default..
*) added timeout for `check_progress_bar_status` method in
ui/contentviews.py
*) Other miscellaneous fixes.
=> Fixes UI smoke tests for sat6.1 compose builds.

tests/foreman/cli/test_computeresource.py
Merge similar update tests into one. In the merge was dropped an invalid
data (provider update is not allowed).
Fix test_create_positive_libvirt data to avoid bash complaining about
the generated command. Also update data entries string interpolation to
string formatting.
Test results:
```
$ py.test tests/foreman/cli/test_computeresource.py -k "test_update_positive or test_create_positive_libvirt"
================================ test session starts ================================
collected 29 items
tests/foreman/cli/test_computeresource.py ............
== 17 tests deselected by '-ktest_update_positive or test_create_positive_libvirt' ==
==================== 12 passed, 17 deselected in 156.60 seconds =====================
```
=> Update CLI compute resource tests

tests/foreman/cli/test_discovery.py, tests/foreman/ui/test_discovery.py
Test stubs for hammer-cli-discovery-plugin
=> discovery test stubs for hammer-cli

robottelo/entities.py
If a repository is being created with a content_type of "docker", then mark the
"docker_upstream_name" field as required. Also, provide a default value for
field `Repository.docker_upstream_name`.
With the changes:
>>> from robottelo import entities
>>> entities.Repository(content_type='docker').create_json()['docker_upstream_name']
u'busybox'
>>> entities.Repository(content_type='docker', docker_upstream_name='foo').create_json()['docker_upstream_name']
u'foo'
Without the changes:
>>> entities.Repository(content_type='docker').create_raw().text
u'{"displayMessage":"Validation failed: Docker upstream name cannot be blank. …
=> Update the `Repository` entity class

tests/foreman/api/test_discovery.py
API Test stubs for foreman discovery feature
=> Foreman discovery API test stubs

tests/foreman/api/test_repository.py
From the bug description:
> When updating a repository, I should be able to provide just the attributes that
> are being changed. For example, this is a valid JSON payload:
>
>     {"name": "some repository name"}
>
> This is valid too:
>
>     {"url": "http://example.com"}
>
> However, if the content-type of a repository is "docker" and I am updating its
> name, then I must pass in other attributes too. This is no longer valid:
>
>     {"name": "some repository name"}
>
> This is the message returned:
>
>     u'{"displayMessage":"Validation failed: Url cannot be blank. Either provide
>     all or no sync information., Repository URL or Upstream Name is empty. Both
>     are required for syncing from the upstream.","errors":{"url":["cannot be
>     blank. Either provide all or no sync …
=> Test BZ 1194476

tests/foreman/ui/test_multinetwork.py
Added test stubs for multi-net support feature.
=> UI test stubs for multi-net support feature

tests/foreman/cli/test_activationkey.py
Added test for content-override, covering both acceptable values.
Also added a function that will perform all the steps needed to
create an activation key and the content needed to populate it.
The new function takes approximately 1430 seconds to run, but will
allow many more tests to use the new public key.
Ran the tests 15 times with no errors.
=> Add tests for Activation Key content-override

docs/api/tests.foreman.smoke.rst, robottelo/common/constants.py, tests/foreman/api/test_multiple_paths.py, tests/foreman/cli/test_capsule.py, tests/foreman/cli/test_errata.py, tests/foreman/cli/test_hostgroup.py, tests/foreman/ui/test_email.py
* Add module `tests.foreman.smoke.test_ui_smoke` to the API documentation.
* Docstring tweaks: fix syntactic issues with some reST text, add some missing
docstrings, tweak some others to make them nicer.
* Make several logging calls (e.g. to `logging.debug`) more idiomatic.
=> Make a variety of nit-picky improvements

tests/foreman/ui/test_isodownload.py
=> Added test stubs for ISO download feature

robottelo/ui/org.py, tests/foreman/ui/test_org.py, tests/foreman/ui/test_puppet_classes.py
This will fix `test_create_repo_2` from ui/test_repository.py
=> Fixed indentation for `create` org function

robottelo/entities.py
Updated ``entities.SyncPlan`` with ``orm.EntityReadMixin``,
``orm.EntityDeleteMixin`` and ``orm.EntityCreateMixin`` so we can start
writing automated tests for ``Sync Plans`` via API.
The implementation does not follow the standard format for most other
available ``entities`` and it closely mimics what we currently do with
``entities.OperatingSystemParameter``, where an existing organization ID
is required in order to perform CRUD actions.
```python
In [1]: from robottelo import entities
In [2]: from fauxfactory import gen_datetime
In [3]: entities.SyncPlan(organization=1).create_json()
Out[3]:
{u'created_at': u'2015-02-28T17:39:19Z',
u'description': None,
u'enabled': False,
u'id': 30,
u'interval': u'weekly',
u'name': u'\u1eec\u3119\u72f6\u61f3\u19c6\u76f1\ube77\u6905\u995c\u182b\u6632\ud4 …
```
=> Updated ``entities.SyncPlan`` code.

tests/foreman/api/test_syncplan.py
Covers many different test cases for ``Sync Plans``.
=> Added stubbed tests for Sync Plans via API.

tests/foreman/ui/test_adusergroups.py, tests/foreman/ui/test_openscap.py
*) OpenScap: Added deletion testcases
*) OpenScap: Removed irrlevant testcases.
*) ADUserGroup: Added deletion testcase.
*) Updated stubs and added @steps for various testcases.
=> Updated AD UserGroup and OpenScap Tests appropriately.

robottelo/entities.py
From the docstring:
> Work around a bug with reading the ``admin`` attribute.
>
> An HTTP GET request to ``path('self')`` does not return the ``admin``
> attribute, even though it should. Work around this issue. See:
>
> * http://projects.theforeman.org/issues/9594
> * https://bugzilla.redhat.com/show_bug.cgi?id=1197871
Tested against nightly:
$ nosetests tests/foreman/api/test_multiple_paths.py:EntityReadTestCase -m UserGroup
.
Ran 1 test in 1.463s
OK
=> Make the `UserGroup.admin` attribute readable

robottelo/entities.py, tests/foreman/api/test_operatingsystem.py
Add a test for [BZ 1125003](https://bugzilla.redhat.com/show_bug.cgi?id=1125003). Polish an existing test so that it fails more gracefully. See individual commit messages for more details.
=> BZ 1125003, polish existing test

tests/foreman/cli/test_capsule.py
Test case to validate BZ:1198015
=> test case to enable BMC feature on smart-proxy

robottelo/ui/locators.py, tests/foreman/ui/test_gpgkey.py
- fixed gpg_key_edit locator on product and repo details page
- blocked gpgkey test with bz-id '1204602'
- fixed content-view locator to locate created CV name
- fixed manifest upload button locator
=> Fixed few UI tests

tests/foreman/cli/test_user.py
=> fixed the failing user tests - negative create, test_user_list

robottelo/ui/activationkey.py, robottelo/ui/locators.py
Update locator for enabling activation key and increase the timeout to
wait for it enables.
=> Fix UI end to end smoke test

robottelo/cli/docker.py, robottelo/cli/factory.py
Also finish DockerContainer class. It have been sent unfinished in #1959
PR, and that PR was supposed to just contain CLI JSON output related
changes.
PS.: I was not able to really test the factory because the server was giving me error 500. Will update the factory in the future if needed.
=> Add container CLI factory

tests/foreman/cli/test_environment.py
Implemented CLI test cases covering two new
parameters in factory.make_environments method
=> Resolve #1720

tests/foreman/cli/test_medium.py
Added CLI tests for two new parameters in factory.make_medium
=> Resolve #1719

robottelo/cli/factory.py, tests/foreman/cli/test_lifecycleenvironment.py
Added CLI tests for three new parameters in
factory.make_lifecycle_environment
Modified factory.make_lifecycle_environment to accept
organization Name, Label or ID
=> Add CLI tests for 3 new parameters - issue #1721

tests/foreman/cli/test_template.py
Implemented CLI test cases covering three new
parameters in factory.make_template method.
Added special verification for exception message
for locked property functionality
=> Resolve #1722

robottelo/ui/factory.py, robottelo/ui/locators.py, robottelo/ui/repository.py, tests/foreman/ui/test_gpgkey.py, tests/foreman/ui/test_repository.py, tests/foreman/ui/test_settings.py, tests/foreman/ui/test_user.py
- blocked test_key_associate_11 with bz-id 1210180
- updated param names for two tests
- Fixed `test_delete_user`: Here we are searching the entity after deletion and success notification too. But test sometime fails when selenium unable to capture the success notification.
=> Fixed UI tests

robottelo/ui/locators.py, robottelo/ui/syncplan.py
Changed Sync Plan locators and increased timeout for searching sp in syncplan.
=> fixed some ui tests

tests/foreman/ui/test_operatingsys.py
Updated code for verification of test test_remove_os
=> Updated verification code for UI test_remove_os

tests/foreman/api/test_contentview.py
Added API test case to Resolve #772
=> Test adding a normal cv to composite-cv

tests/foreman/api/test_contentview.py
Added API test case to Resolve #1266
=> Add Positive test cases for Content Views via API - Part 3

tests/foreman/api/test_organization.py
Initial version covers mentioned issue for organization part only.
Once approved - will continue with locations.
Provided code will give an exception as our task was to prove that
Foreman overwrites compute resources for organization which is
incorrect behavior
=> Resolve #1123

tests/foreman/cli/test_user.py
Cover two more parameters in order to
Close #1714 issue
=> Adding coverage for make_user method

robottelo/common/constants.py, tests/foreman/cli/test_subnet.py
Cover three more parameters in order to
Close #1712 issue
=> Adding coverage for make_subnet method

robottelo/ui/base.py
Especially, that fix should be applicable
for empty foreman entities list situations
Closes #2091
=> Fix for search_entity functionality

tests/foreman/cli/test_computeresource.py
Added CLI tests for two new parameters in factory.make_compute_resource:
```
--location-ids LOCATION_IDS   REPLACE locations with given ids
--set-console-password        SET_CONSOLE_PASSWORD for Libvirt and Vmware only
One of true/false,
yes/no, 1/0.
```
Resolves #1715
=> Add CLI tests for 2 parameters in factory.make_compute_resource - issue #1715

robottelo/cli/contentview.py, tests/foreman/cli/test_contentviews.py
Implemented test to delete content-view version via hammer-cli
=> Test: Delete content-view version from CLI

robottelo/ui/contentviews.py, robottelo/ui/locators.py, tests/foreman/ui/test_contentviews.py
Implemented test to remove CV version from UI.
=> Test: Delete published content-view version from UI

robottelo/common/helpers.py
The class STR is not being used anymore and can be dropped.
=> Drop unused class from the helpers

.gitignore, requirements.txt, setup.py
The setup file allow to install Robottelo in the current virtual
environment and will easy the use of scripts. Also as soon as Robottelo
evolve as a 100% solid framework we can publish it on PyPI with minimal
adjustments.
This also make code completion work better if you use a tool like Rope.
=> Add setup.py file

robottelo/ui/login.py
This should address an issue: #2089
Note that by calling this method, the sessions `idle_timeout` is being reset as server treats the HTTP GET request as an activity from the users side, so one should reconsider using this method to test `idle_timeout` functionality.
=> Modify - UI is_logged() refactored

tests/foreman/api/test_contentview.py
Add necessary coverage for content view functionality
Closes #1267 issue
=> Add test cases for Content Views via API - Part 4

tests/foreman/cli/test_environment.py
Added tests for `location-ids` and `organization-ids` parameters only as `name` parameter was already covered in the past. As a bonus - added tests for negative scenario
Closes #1711 
```
$ nosetests tests/foreman/cli/test_environment.py -m test_update_negative -s
.....
Ran 5 tests in 90.886s
OK
$ nosetests tests/foreman/cli/test_environment.py -m test_update_organization -s
.
Ran 1 test in 39.432s
OK
$ nosetests tests/foreman/cli/test_environment.py -m test_update_location -s
.
Ran 1 test in 31.577s
OK
```
=> Adding coverage for environment update functionality

tests/foreman/api/test_docker.py
Test valid and invalid docker upstream names according to the regex used
to validate them. The regex is the following
`/^([a-z0-9\-_]{4,30}\/)?[a-z0-9\-_\.]{3,30}$/`.
Closes #1665 
Test results:
```
$ py.test tests/foreman/api/test_docker.py -k test_create_docker_repo_
================================== test session starts ==================================
collected 110 items
tests/foreman/api/test_docker.py ..............
================== 96 tests deselected by '-ktest_create_docker_repo_' ==================
======================= 14 passed, 96 deselected in 82.30 seconds =======================
```
=> Add API tests for docker upstream name

tests/foreman/ui/test_activationkey.py
Added UI test, which updates activation key with another content view 
with RH products.
Closes #717
Test results:
```
$ nosetests tests/foreman/ui/test_activationkey.py -m test_positive_update_activation_key_with_rh_product
......
Ran 6 tests in 2335.140s
OK
```
=> Add UI test to update activation key with CV with RH product - issue #717

tests/foreman/cli/test_hammer.py
Now the test will collect all the differences: added commands, removed
commands, added subcommands and removed subcommands. This gives a more
complete report than the previous one.
Sample output:
```python
py.test --pdb tests/foreman/cli/test_hammer.py
================================== test session starts ==================================
collected 1 items
tests/foreman/cli/test_hammer.py F
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
self = <tests.foreman.cli.test_hammer.HammerCommandsTestCase testMethod=test_hammer_options>
def test_hammer_options(self):
"""@Test: check all provided options for every hammer command
@Feature: Hammer
@Assert: All expected options are present
""" …
```
=> Improve test_hammer_options

robottelo/cli/activationkey.py, tests/foreman/cli/test_activationkey.py
Fixes #1705
```
@Test: Positive delete activation key ... ok
Ran 1 test in 21.752s
OK
```
=> Add CLI test for activation-key delete

tests/foreman/api/test_repository.py
Test results against an upstream RHEL 6.6 system:
$ nosetests tests/foreman/api/test_repository.py
......F.SE......................................
Ran 48 tests in 219.579s
FAILED (SKIP=1, errors=1, failures=1)
These test results are identical to what the test suite currently produces.
=> Refactor module tests.foreman.api.test_repository

tests/foreman/cli/test_activationkey.py
Adding coverage for activation key delete using different
approaches
Closes #1705
=> Add CLI tests for activation key delete

robottelo/cli/activationkey.py, tests/foreman/cli/test_activationkey.py
Already investigated mentioned issue. Will add more coverage and remove unnecessary code duplication
=> Revert "Add CLI test for activation-key delete"

tests/foreman/cli/test_activationkey.py
Slightly increase coverage for activation key remove host collection functionality.
Fixed previous coverage to correspond more to our code style
Closes #1706
=> Add CLI test for activation-key remove-host-collection

tests/foreman/ui/test_activationkey.py
Automated test ui/activation_key/test_associate_host.
=> Automated test ui/activation_key/test_associate_host closes #2170

tests/foreman/cli/test_hammer.py, tests/foreman/data/hammer_commands.json
Update the expected hammer commands and options to match the current
status.
Also check for some known bugs and deal with the related commands
accordingly.
Closes #2150
=> Update the expected hammer commands and options

robottelo/ui/contentviews.py
Fix the `find_element` calls on `select_package_version_value`.
Closes #2189
=> Fix UI Content View select_package_version_value

robottelo/ui/contentviews.py, robottelo/ui/locators.py, robottelo/ui/sync.py, tests/foreman/ui/test_computeresource.py, tests/foreman/ui/test_domain.py, tests/foreman/ui/test_user.py
- Fixed test_positive_update_user_1 test by assigning 'viewer' role
- Fixed test_update_compute_resource test by removing html, multi-string data
- Blocked 'html' data in test_update_domain by bz-id
- Increased timeout value from 100 to 120 while selecting the RH repos.
=> Fixed UI test failures

robottelo/ui/puppetclasses.py, tests/foreman/ui/test_puppet_classes.py
UI Fixes and Code Improvement.
=> UI Fixes and Code Improvement closes #2192

robottelo/common/constants.py
Fix tests corresponding to new parameters in payload
Closes #2172
=> Fix tests.foreman.api.test_permission.PermissionsTestCase.test_search_by_resource_type_13_Host method

tests/foreman/api/test_subscription.py
Fix tests corresponding to a new exception handling approach after code migration to nailgun
Closes #2167
=> Fix tests.foreman.api.test_subscription.SubscriptionsTestCase.test_negative_create_1

tests/foreman/ui/test_user.py
It seems that 'is_logged' functionality was improved. Fixed UI test, so it passes
Closes #2223
=> Fix UI issue for create new user functionality

tests/foreman/api/test_host.py
=> Remove unnecessary coverage

tests/foreman/api/test_user.py
Users can be associated with roles via the API. Unfortunately, the API docs
don't make mention of this. BZ 1216239 outlines this shortcoming, and this PR
provides proof positive that users can be associated with roles via the API.
Test results against an upstream system:
$ nosetests tests/foreman/api/test_user.py -m _with_role
..
Ran 2 tests in 4.558s
OK
This test depends on the "role" field being added to the User entity. See
SatelliteQE/nailgun#57.
=> Add test demonstrating User → Role associations

tests/foreman/data/hammer_commands.json
`docker` command and its subcommands was added to hammer. Update the
expected commands and options.
Closes #2227
```
$ py.test tests/foreman/cli/test_hammer.py
================================== test session starts ===================================
collected 1 items
============================== 1 passed in 1262.17 seconds ===============================
```
=> Update expected hammer commands and options

robottelo/cli/contentview.py, robottelo/common/constants.py, tests/foreman/api/test_contentview.py
=> Implemented tests for Content View association via API

tests/foreman/cli/test_contentviews.py
Update test_cv_associate_composite_dupe_modules_negative in order to
check for all puppet modules returned and also for the number of
available puppet modules. This will ensure in the future that BZ
1222118 will happen again. Also skip the test due to the mentioned BZ.
Closes #2100
```
py.test tests/foreman/cli/test_contentviews.py -ktest_cv_associate_composite_dupe_modules_negative
=================================== test session starts ====================================
collected 57 items
tests/foreman/cli/test_contentviews.py s
======= 56 tests deselected by '-ktest_cv_associate_composite_dupe_modules_negative' =======
======================== 1 skipped, 56 deselected in 32.46 seconds =========================
```
=> Update content view CLI test

tests/foreman/cli/test_subscription.py
The changes are the following:
* Drop unused class attributes
* Drop not necessary assertion messages
* Update the formatting to match the current one
* Create a brand new organization in the setUp method instead of using a
cached one. This closes #2228.
* Create a helper method to upload a manifest file and import it into an
organization in order to reuse code and make test methods cleaner.
=> Update CLI test_subscription module

robottelo/common/constants.py, robottelo/test.py, robottelo/ui/factory.py, robottelo/ui/locators.py, robottelo/ui/trend.py, tests/foreman/ui/test_trend.py
Closes #127
```
nosetests tests/foreman/ui/test_trend.py
...
Ran 3 tests in 161.157s
OK
```
=> Implement CRUD for Trends functionality

tests/foreman/cli/test_contentviews.py
Covered all variation mentioned in stub comments
Closes #681 
```
nosetests tests/foreman/cli/test_contentviews.py -m test_cv_subscribe_system
......
Ran 6 tests in 686.940s
OK
```
=> Implemented tests for Content View registration via CLI

robottelo/cli/factory.py, robottelo/vm.py, tests/foreman/cli/test_contenthost.py
Modularized #1708 tests for simple re-use in other katello-agent- or errata- related tests.
The task idea is fully described [here (comment to PR #2186)](https://github.com/SatelliteQE/robottelo/pull/2186#issuecomment-100028625).
Test results:
```
nosetests tests/foreman/cli/test_contenthost.py -m test_contenthost_
..
Ran 2 tests in 721.204s
OK
```
Resolves #2199
=> CLI: Modularize katello-agent and errata tests - issue #2199

tests/foreman/cli/test_hammer.py, tests/foreman/data/hammer_commands.json
Update the information being tested to match the latest compose.
=> Update hammer_commands and test_hammer_options

robottelo/common/ssh.py
* Remove color codes character from the stderr.
* Differentiate on logging stdout from stderr.
=> Improve ssh.command

robottelo/common/decorators.py
Create an specific logger for the module and log when skipping bugs.
Logging when a test is skipped will allow generate a report showing all
skipped tests due to bugs.
=> Improve logging for the decorators module

tests/foreman/ui/test_activationkey.py, tests/foreman/ui/test_gpgkey.py
Fixed String formatting issue.
Logs:
```
[root@jyejare robottelo]# nosetests -m test_multiple_activation_keys_to_system ./tests/foreman/ui/test_activationkey.py
.
Ran 1 test in 539.167s
OK
```
=> Fixed String Formatting issue closes #2343, #2345, #2347

tests/foreman/api/test_hostgroup.py
Covering BZ 1107708
Closes #1159
```
nosetests tests/foreman/api/test_hostgroup.py -m test_bz_1107708
.
Ran 1 test in 125.191s
OK
```
=> Added first case for HostGroup API flow

tests/foreman/smoke/test_api_smoke.py
* Finish test_smoke test as now all entities are provided by NailGun.
Closes #1138.
* Update test_end_to_end to use create and read methods instead of the
create_json and read_json. By using those methods now is not needed to
instantiate a new entity for every operation, the created entity can
be reused. Also update the client section to make code cleaner.
Test results:
```
$ py.test tests/foreman/smoke/test_api_smoke.py -ktest_smoke
================================== test session starts ===================================
collected 8 items
tests/foreman/smoke/test_api_smoke.py .
========================== 7 tests deselected by '-ktest_smoke' ==========================
======================== 1 passed, 7 deselected in 296.90 …
```
=> Finish/Update API smoke tests

tests/foreman/api/test_hostgroup.py
Removing unnecessary code and dependencies. Added one more verification to reduce amount of possible root causes for initial failure
=> Implemented possible fix for #2370

robottelo/common/constants.py, robottelo/ui/hosts.py, robottelo/ui/locators.py, tests/foreman/ui/test_host.py
Added dependency creation for UI host tests. Updated ```Hosts.create()``` and  ```Hosts.update()``` with all required parameters.
Applied changes to stubbed ```test_create_host()``` and ```test_delete_host()``` tests.
Resolves #748
Tests results:
```
nosetests tests/foreman/ui/test_host.py
..
Ran 2 tests in 245.594s
OK
```
=> UI: Add dependency creation for host tests - issue #748

robottelo/test.py, robottelo/ui/base.py, robottelo/ui/contentsearch.py, robottelo/ui/locators.py, tests/foreman/ui/test_contentsearch.py
Covering necessary framework elements for Content Search functionality and added first test case in that area
Implemented fundamental part of #1735
=> Added base functionality for Content Search UI flow

robottelo/cli/factory.py, tests/foreman/cli/test_subnet.py
Added deeper level of verification as per BZ1226828
Fixed subnet factory entity as per changes in hammer
Closes #2097
```
nosetests tests/foreman/cli/test_subnet.py -m test_create_subnet_with_some_domains
.
Ran 1 test in 37.971s
OK
```
=> Add CLI test for factory.make_subnet (multiple values scenario)

tests/foreman/api/test_hostgroup.py
=> Found an issue that can randomly fail current test

tests/foreman/cli/test_import.py
3 general changes:
- 1 added test (`test_import_orgs_manifests`)
- the test utilizes the `robottelo.cli.manifests.clone()` method to generate fake manifests, renames them to match organization names (needed for `import` subcommand to be able to assign them to the appropriate orgs)
- 1 added method (`build_csv_file`)
- generates a temporary file and feeds it by a header and records
- more tests are coming up, where we need to craft custom csv files (we can possibly move the method to `common.helpers` or `cli.import_`)
- 1 modified method (`csv_to_dataset`)
- the method now accepts the path to the csv instead of csv string itself. It now takes care of reading the file and parsing it.
```bash
$ nosetests -m test_import_orgs_manifests test_import.py
. …
```
=> Add CLI test - cli.import - test upload manifest

tests/foreman/api/test_location.py
Implemented most of necessary cases for create location functionality
Closes #2426
```
nosetests tests/foreman/api/test_location.py
.................
Ran 17 tests in 76.922s
```
=> Add coverage for create location functionality for API

robottelo/ui/org.py, tests/foreman/ui/test_org.py
- Unblocked Test_Delete_Organization
- Added the Test for BZ1225588
=> Test Delete Org and BZ1225588 closes #2371

robottelo/test.py, robottelo/ui/discoveryrules.py, robottelo/ui/factory.py, robottelo/ui/locators.py, robottelo/ui/navigator.py, tests/foreman/ui/test_discoveryrule.py
- Implemented:
- create, search, delete discovery rule functions
- `make_discoveryrule` factory function
- webUI locators
- few basic tests around discovery rules
=> Discovery rule tests with create/delete functions

tests/foreman/api/test_product.py
Added coverage for ```/katello/api/products/:product_id/repository_sets/:id/enable```
Closes #2436
Test results:
```
nosetests tests/foreman/api/test_product.py -m test_repositoryset_enable
.
Ran 1 test in 81.427s
OK
```
```[DO NOT MERGE]``` tag until SatelliteQE/nailgun#122 gets merged and released.
=> API: Added coverage for repository-set enable

tests/foreman/api/test_product.py
Similar to PR #2474
Added coverage for ```/katello/api/products/:product_id/repository_sets/:id/disable```
Closes #2437
Test results:
```
nosetests tests/foreman/api/test_product.py -m test_repositoryset_disable
.
Ran 1 test in 79.246s
OK
```
=> API: Added coverage for repository-set disable

tests/foreman/cli/test_import.py
- created `modify_csv_values` function for replacing the key values with keeping the entity mapping of the original data set. This allows us to implement the tests for `hammer import` feature with generated strings the same way as other features.
```bash
$ nosetests test_import.py
.....
Ran 5 tests in 194.780s
OK
```
- swapped two tests to keep organization-related tests grouped.
- fixed the cleanup (added removal of the locally-generated files)
=> Created update_csv_values() for randomizing dataset

tests/foreman/cli/test_location.py
Closes #2421 
```
>nosetests tests/foreman/cli/test_location.py -m test_update_location
......................
Ran 22 tests in 463.378s
OK
```
Continue to work in a way to add more scenarios that really make sense rather than create redundant test cases (like tests per each parameter)
=> Add coverage for create update functionality for CLI

tests/foreman/cli/test_import.py
Added a test to excercise `--into-org-id` option of `hammer import organization`
To verify mapping is being performed correctly, the test attempts to import some users originally belonging to different organizations in `Satellite 5` and verifying they all appear under a single organization in `Satellite 6`
```bash
$ nosetests -m test_merge_orgs test_import.py
.
Ran 1 test in 43.342s
OK
```
=> CLI Import test added - test_merge_orgs

docs/api/robottelo.ui.rst, robottelo.properties.sample, robottelo/common/constants.py, robottelo/test.py, robottelo/ui/factory.py, robottelo/ui/ldapusergroups.py, robottelo/ui/locators.py, tests/foreman/ui/test_adusergroups.py
*) Added LDAP Authentication CRUD functions
*) Added creation and deletion tests related to LDAP Authentication
*) Added locators for LDAP Auth
*) All LDAP Information will be pulled in from the robottelo.properties
file and the needed conf entries has been added
=> Added Initial LDAP Auth CRUD functions and few tests

tests/foreman/ui/test_location.py
Closes #2423 
```
nosetests tests/foreman/ui/test_location.py -m test_positive_delete
.......
Ran 7 tests in 381.081s
OK
```
=> Add coverage for delete location functionality for UI

tests/foreman/cli/test_contentviews.py
Closes #2470 
```
nosetests tests/foreman/cli/test_contentviews.py -m test_delete_cv_version
...
Ran 3 tests in 183.839s
OK
```
=> Add coverage for content view version delete functionality for CLI

tests/foreman/api/test_contentviewversion.py
Closes #2471
```
nosetests tests/foreman/api/test_contentviewversion.py -m test_delete
...
Ran 3 tests in 160.507s
OK
```
Not sure whether that code can be merged right now as I am using latest Nailgun version from repository
=> Add coverage for content view version delete functionality for API

tests/foreman/cli/test_import.py
Resolves #2524 and #2529
- added tests to cover `--recover` strategies of `hammer import organization` and `hammer import user` subcommands.
```bash
$ nosetests -m recover test_import.py
..
Ran 2 tests in 114.682s
OK
```
- added test to cover `--merge-users` option of `hammer import user` subcommand
```bash
$ nosetests -m users_merge test_import.py --nocapture
.
Ran 1 test in 35.596s
OK
```
=> CLI Import - added recovery and merge-users tests

robottelo/common/constants.py, tests/foreman/smoke/test_api_smoke.py
Update API smoke tests to use the latest available tools from NailGun.
Now we can work on a higher level of abstraction.
```
$ nosetests --nologcapture tests/foreman/smoke/test_api_smoke.py
........
Ran 8 tests in 443.280s
OK
```
This PR depends on ~~#2576~~ and new NailGun version.
=> [DONOTMERGE] Update API smoke tests

tests/foreman/smoke/test_ui_smoke.py
- by reusing vm functions instead of custom code to register a client
This fixes a UI smoke test which failed in the last 35 runs.
=> Fixes a UI encode issue

tests/foreman/cli/test_host_collection.py
- 1. the parameter change from max-content-hosts to limit is updated
- 2. the test is blocked on a new bug
=> Update to host-collection update test

tests/foreman/api/test_contentview.py
Drop all references to NailGun's `client.get` method. Make use of higher level
methods instead. Run as much of test `test_subscribe_system_to_cv` as possible,
on the theory that it is better to run part of a test than no test at all. Test
results:
$ nosetests tests/foreman/api/test_contentview.py -m test_subscribe_system_to_cv
.
Ran 1 test in 38.156s
OK
=> Simplify API content view test

tests/foreman/api/test_filter.py, tests/foreman/api/test_gpgkey.py, tests/foreman/api/test_hostgroup.py, tests/foreman/api/test_lifecycleenvironment.py, tests/foreman/api/test_multiple_paths.py, tests/foreman/api/test_organization.py, tests/foreman/api/test_permission.py, tests/foreman/api/test_user.py, tests/foreman/smoke/test_api_smoke.py
Refactor numerous modules to make use of the new `EntitySearchMixin`. Each individual commit contains proof of its validity - see the commit messages for details.
I am marking this PR as "DO NOT MERGE" because it depends on <del>FIXME: Fetch information from the future</del> <ins>SatelliteQE/nailgun#157</ins>. However, I am putting up this PR now to keep track of it and collect feedback
=> EntitySearchMixin

tests/foreman/data/hammer_commands.json
Match the currently available commands and options.
Closes #2227
```
$ py.test tests/foreman/cli/test_hammer.py
================================= test session starts =================================
platform linux2 -- Python 2.7.5 -- py-1.4.30 -- pytest-2.7.2
rootdir: /home/elyezer/robottelo, inifile:
collected 1 items
============================= 1 passed in 659.42 seconds ==============================
```
=> Update test_hammer_options data

tests/foreman/ui/test_adusergroups.py
*) Verify whether adding roles to user-group as well as to user
for an external ad user is successful.
=> Added another ad-usergroup testcase.

robottelo/ui/org.py, tests/foreman/ui/test_org.py
Made changes according to our style and new click method implementation mentioned in #2562 issue.
```
nosetests tests/foreman/ui/test_org.py
.......S......S...S..E.......S...
ERROR: @test: Create Organization with valid values and upload manifest.
File "/usr/lib/python2.7/site-packages/ddt.py", line 146, in wrapper
return func(self, *args, **kwargs)
File "/home/oshtaier/Desktop/robottelo/robottelo/common/decorators.py", line 372, in wrapper_func
return func(*args, **kwargs)
File "/home/oshtaier/Desktop/robottelo/tests/foreman/ui/test_org.py", line 244, in test_positive_delete_bz1225588
path=manifests.clone()) …
```
=> Introduce some improvements to organization class

robottelo.properties.sample, robottelo/ui/rhai.py, tests/foreman/rhai/test_rhai.py
* Added setUpClass in test_rhai.py
* Added method for registering client to RHAI in 'rhai' module
=> Refactoring code

robottelo/api/utils.py, tests/foreman/api/test_contentview.py, tests/foreman/api/test_hostgroup.py, tests/foreman/api/test_product.py, tests/foreman/api/test_repository.py, tests/foreman/api/test_syncplan.py, tests/foreman/ui/test_activationkey.py, tests/foreman/ui/test_contentviews.py
This pull request supercedes #2632. @abalakh is not currently available, so it is unfeasible to review his PR and ask for updates. I've taken what he did, rebased his work (and fixed a merge conflict in the process), and added a few additional fixes on top of his work.
Andrii modified the following files in his commit:
* `robottelo/api/utils.py`
* `tests/foreman/api/test_contentview.py`
* `tests/foreman/api/test_hostgroup.py`
* `tests/foreman/api/test_product.py`
* `tests/foreman/api/test_repository.py`
* `tests/foreman/api/test_syncplan.py`
* `tests/foreman/ui/test_activationkey.py`
* `tests/foreman/ui/test_contentviews.py`
I've reviewed the first six, but have not touched the two modules in
`tests/foreman/ui/`.
=> Fix for nailgun beta

robottelo/cli/factory.py, robottelo/common/constants.py, tests/foreman/cli/test_contenthost.py
As @abalakh is on PTO I have rebased #2649 and applied #2653 on top of it.
This PR is the same as both PRs but rebased and with conflict resolution.
=> Join #2649 and #2653

tests/foreman/api/test_hostgroup.py
That is probably last fix for Robottelo that was necessary to introduce according SatelliteQE/nailgun#41 changes
=> Issue fix corresponding new nailgun model

robottelo/common/constants.py, tests/foreman/smoke/test_ui_smoke.py
Use the VirtualMachine methods to install katello cert RPM and register
the vm as a content host.
Improve formatting and drop single use variables. Also use constants
whenever possible.
=> Update UI smoke tests

robottelo/api/utils.py
If BZ #1252101 status is open, the helper will sleep and do some tries
in order to wait for results.
Closes #2662
=> Add workaround for enable_rhrepo_and_fetchid

tests/foreman/api/test_docker.py
1) Add 13 more test cases according to #2642
2) Fix one issue in test logic for ```test_publish_once_docker_repo_composite_content_view``` method
```
nosetests tests/foreman/api/test_docker.py -m test_add_multiple_docker_repos_to_content_view
.
Ran 1 test in 34.018s
OK
```
```
nosetests tests/foreman/api/test_docker.py -m test_publish_multiple_docker_repo_content_view
.
Ran 1 test in 67.226s
OK
```
```
nosetests tests/foreman/api/test_docker.py -m test_publish_multiple_docker_repo_composite_content_view
.
Ran 1 test in 83.757s
OK
```
```
nosetests tests/foreman/api/test_docker.py …
```
=> Increase docker functionality coverage

robottelo/ui/base.py, robottelo/ui/configgroups.py, robottelo/ui/domain.py, robottelo/ui/environment.py, robottelo/ui/gpgkey.py, robottelo/ui/locators.py, tests/foreman/ui/test_config_groups.py, tests/foreman/ui/test_domain.py, tests/foreman/ui/test_environment.py
Continue to work on UI part of Robottelo improvements. Introduces some fixes to get closer to our overall style and add necessary changes according to #2562 issue.
Also, add one more helper method ```wait_until_element_is_not_visible``` to be able to wait till some object disappeared from DOM of our application. Used it once in gpg_key method to make run more stable on different environments (despite that functionality works properly on Jenkins)
```
nosetests tests/foreman/ui/test_environment.py
......................
Ran 22 tests in 404.677s
OK
```
```
nosetests tests/foreman/ui/test_domain.py -m test_negative_create_domain
..........
Ran 10 tests …
```
=> Some changes according to our new click method implementation

robottelo/ui/architecture.py, robottelo/ui/login.py, robottelo/ui/medium.py, tests/foreman/ui/test_architecture.py, tests/foreman/ui/test_login.py, tests/foreman/ui/test_medium.py
Adding more changes according to our new click method implementation mentioned in #2562 issue.
```
nosetests tests/foreman/ui/test_architecture.py -e test_remove_architecture
...................................
Ran 35 tests in 734.029s
OK
```
```
nosetests tests/foreman/ui/test_architecture.py -m test_remove_architecture
.......
Ran 7 tests in 268.237s
OK
```
```
nosetests tests/foreman/ui/test_login.py
......
Ran 6 tests in 77.250s
OK
```
```
nosetests tests/foreman/ui/test_medium.py
...............
Ran 15 …
```
=> Improved ui.login, ui.architecture and ui.medium modules

tests/foreman/api/test_discovery.py
Added a test to create discovered host. For now, I defined a fn `_create_discovered_host` to create discovered host with required facts. We can add more facts later in same function. 
The idea behind defining the `_create_discovered_host` to use it for further tests like `test_delete_discovered_host`.
=> Implemented test to create a discovered_host via uploading facts

robottelo/cli/import_.py, tests/foreman/cli/test_import.py
every instance of `Import.whatever` will contain `.transition_data` attribute containing a dictionary or a list of dictionaries containing the current Sat5 -> Sat6 entity mappings taken from `${HOME}/.transition_data/whatever*.csv`
The transition_data is a natural part of every executed import and having the data accessible via the object attribute will add much more readability to our unit tests.
=> CLI/Import - extending the returned instances by transition_data

tests/foreman/ui/test_gpgkey.py
Use tools like the `setUp` function and for loops to reduce the repetitiveness
of tests. Use modern NailGun methods, doing things like replacing `create_json`
and `client.put` calls with `create` and `update` calls, respectively. These
changes make the module slightly longer, by about 10 lines. However, they also
drop the number of statements from 454 to 378, indicating much lower code
density.
Test results:
(robottelo2)[ichimonji10@beech:robottelo]$ nosetests tests/foreman/ui/test_gpgkey.py
.SSSS................S.S..S...S...S..S..S..
Ran 43 tests in 2144.077s
OK (SKIP=11)
=> Refactor module tests.foreman.ui.test_gpgkey

robottelo.properties.sample, robottelo/vm.py
wget.
*) As we now have a rhel repo with updates to it and
*) The repo file also uses the mirrorlist, so it will fetch
accordingly.
=> modified the `configure_rhel_repo` method to accept the repo to wget

tests/foreman/api/test_docker.py
Depends on SatelliteQE/nailgun#180
```
nosetests tests/foreman/api/test_docker.py -m test_create_container_local_compute_resource
...
Ran 3 tests in 42.375s
OK
```
```
nosetests tests/foreman/api/test_docker.py -m test_create_container_external_compute_resource
...
Ran 3 tests in 41.279s
OK
```
```
nosetests tests/foreman/api/test_docker.py -m test_delete_container
..
Ran 2 tests in 29.400s
OK
```
=> Adding 8 more test cases to overall docker functionality coverage according to #2642

robottelo/common/constants.py
We need the latest manifest for our automation, once we have that in place this PR can be merged.
=> Update Repos and Reposets for lastest sat6.1 GA manifest.

tests/foreman/cli/test_import.py
Yet another set of `Import` tests. This time for importing `Content View`s.
```bash
$ nosetests -m import_cv test_import.py -vs
@test: Import and enable all Content Views from the default data set ... ok
@test: Try to Import Content Views with the same name to invoke ... ok
@test: Import and enable all Content Views from the default data set ... ok
Random data for Content View Import tests ... ok
Ran 4 tests in 429.452s
OK
```
=> CLI/Import - test import Content Views

tests/foreman/api/test_docker.py, tests/foreman/cli/test_docker.py
Implemented some CLI stubs for Docker functionality.
Part of #2705
Tests results:
```
nosetests tests/foreman/cli/test_docker.py
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.....SSSSSSSS.SSSSSS...................
Ran 72 tests in 1215.860s
OK (SKIP=47)
```
As a bonus, slightly updated some API Docker tests - fixed `range()` calls, moved `@run_only_on` decorator, removed some single-use variables etc.
=> Added first 14 tests for Docker CLI

robottelo/cli/import_.py
let's use a function. that's what is it for.
=> reuse code - DRY principle

robottelo/ui/repository.py, robottelo/ui/role.py, tests/foreman/ui/test_repository.py, tests/foreman/ui/test_role.py
Improved ui.role and ui.repository corresponding to #2562 issue and our style in general
```
nosetests tests/foreman/ui/test_repository.py
.......................E................................................................
ERROR: @Test: Create repository via repo-discovery under existing product
File "/home/oshtaier/Desktop/robottelo/robottelo/common/decorators.py", line 372, in wrapper_func
return func(*args, **kwargs)
File "/home/oshtaier/Desktop/robottelo/tests/foreman/ui/test_repository.py", line 433, in test_discover_repo_via_existing_product
product=product.name,
File …
```
=> Added improvements for ui.role and ui.repository

tests/foreman/cli/test_import.py
The modification of this test unit was necessary to mimic the new behavior of the `import config-file` command (see [BZ1226981](https://bugzilla.redhat.com/show_bug.cgi?id=1226981#c4))
```bash
$ nosetests -m test_bz1160847_translate_macros test_import.py -vs
@test: Check whether all supported Sat5 macros are being ... 
ok
Ran 1 test in 27.507s
OK
```
=> CLI/Import - test_bz1160847_translate_macros fixed

tests/foreman/data/hammer_commands.json
Update the data in order to match the current hammer commands and
options.
```
$ py.test tests/foreman/cli/test_hammer.py 
================================ test session starts ================================
platform linux2 -- Python 2.7.5 -- py-1.4.30 -- pytest-2.7.2
rootdir: /home/elyezer/robottelo, inifile: 
collected 1 items 
============================ 1 passed in 634.49 seconds =============================
```
=> Update hammer command options data

robottelo/ui/base.py, robottelo/ui/hardwaremodel.py, robottelo/ui/location.py, robottelo/ui/products.py, robottelo/ui/sync.py, robottelo/ui/user.py, tests/foreman/ui/test_hw_model.py, tests/foreman/ui/test_location.py, tests/foreman/ui/test_products.py, tests/foreman/ui/test_sync.py, tests/foreman/ui/test_user.py
Fixes refer to `ui.hardwaremodel`, `ui.location`, `ui.products`, `ui.sync` and `ui.user` modules.
Most work done around #2562 issue and our style in general
Closes #2309. That defect was reproducing on Jenkins for last 6 months. (at least)
=> Added more UI improvements

tests/foreman/api/test_docker.py, tests/foreman/cli/test_docker.py
Add remaining Docker CLI tests for adding docker repos to content views and publishing/promoting those CVs.
Slightly updated corresponding API tests as well.
Part of #2705
Depends on SatelliteQE/nailgun#195
=> Add remaining DockerContentViewTests for Docker CLI

tests/foreman/ui/test_discoveryrule.py
Some time ago we had only few DiscoveryRule tests and they were passing successfully. Lately new DiscoveryRule tests were introduced (#2701). Tests started failing because pagination appeared and some of the DiscoveryRules appeared on the second page.
Some bad news there:
1) All the Discovery Rules are shown on UI regardless of organization/location selected, making it impossible to fix by selecting different organization
2) There's no searchbar on DiscoveryRule page, so searching for specific discovery rule is not an option either
The only option left is to set `entries_per_page` setting to some huge value while DiscoveryRule tests are running and return it to the previous value after the tests finished execution.
UI was not an option here - setting should be changed in `setUpClass` and …
=> Fix UI DiscoveryRule tests

robottelo/ui/contentsearch.py, robottelo/ui/contentviews.py, robottelo/ui/hostgroup.py, robottelo/ui/hosts.py, robottelo/ui/locators.py, robottelo/ui/puppetclasses.py, robottelo/ui/subnet.py, robottelo/ui/subscription.py, robottelo/ui/syncplan.py, robottelo/ui/template.py, robottelo/ui/trend.py, robottelo/ui/usergroup.py, tests/foreman/ui/test_contentviews.py, tests/foreman/ui/test_domain.py, tests/foreman/ui/test_host.py, tests/foreman/ui/test_hostgroup.py, tests/foreman/ui/test_org.py, tests/foreman/ui/test_puppet_classes.py, tests/foreman/ui/test_subnet.py, tests/foreman/ui/test_subscription.py, tests/foreman/ui/test_syncplan.py, tests/foreman/ui/test_trend.py, tests/foreman/ui/test_usergroup.py
Improving style and use new click method for ui.subnet, ui.hostgroup, ui.contentsearch, ui.syncplan, ui.subscription, ui.contentviews, ui.trend, ui.puppetclasses and ui.usergroup modules
Closes #2712
Closes #2697
Closes #2741
=> [Merge before tagging] Add more improvements to UI and fix few issues on CI

tests/foreman/api/test_contentviewversion.py
Test results:
$ nosetests tests/foreman/api/test_contentviewversion.py -m test_incremental_update --nocapture
.
Ran 1 test in 66.369s
OK
=> Test CVV incremental updates w/puppet modules

tests/foreman/api/test_environment.py
Test results:
$ nosetests tests/foreman/api/test_environment.py:MissingAttrTestCase
S
Ran 1 test in 0.548s
OK (SKIP=1)
Test result without `skip_if_bug_open` decorator:
$ nosetests tests/foreman/api/test_environment.py:MissingAttrTestCase
EE
ERROR: @Test: Update an environment. Inspect the server's response.
File "/home/ichimonji10/code/robottelo/tests/foreman/api/test_environment.py", line 94, in test_location
_get_entity_ids('location', self.env_attrs)
File "/home/ichimonji10/code/nailgun/nailgun/entity_mixins.py", line 280, in _get_entity_ids …
=> Add tests for BZ 1262029

robottelo/constants.py, robottelo/test.py, robottelo/ui/base.py, robottelo/ui/factory.py, robottelo/ui/hostgroup.py, robottelo/ui/locators.py, robottelo/ui/navigator.py, robottelo/ui/oscapcontent.py, robottelo/ui/oscappolicy.py, robottelo/ui/oscapreports.py, robottelo/vm.py, tests/foreman/smoke/test_ui_smoke.py, tests/robottelo/test_vm.py
Added most of the oscap pre-requesites related to policy, content
and reports.
*) Added OSCAP constant related to content, profile, period, e.t.c
*) Added new function `select` to base module.
*) Added `make_oscappolicy` to factory module.
*) Refactored the ui/hostgroup module and added new code to
populate content_source, puppet_ca and puppet_master.
*) Added oscap and new hostgroup locators.
*) Added oscap_policy, oscap_content, oscap_reports page
navigation.
=> Added oscap stuff

robottelo/ui/oscapcontent.py, robottelo/ui/oscappolicy.py
Some missing updates on imports.
=> Update imports that still using common package

tests/foreman/cli/test_host.py
Drop the test as it is not valid and add a new one to check if is it
possible to create a libvirt host without providing a MAC address.
The initial changes were made at PR #2731 by @ares.
=> Drop CLI host test_bz_1177570

tests/foreman/api/test_contentviewfilter.py
Test results:
$ nosetests tests/foreman/api/test_contentviewfilter.py
...........................S..
Ran 30 tests in 201.065s
OK (SKIP=1)
=> Drop DDT from API content view filter tests

tests/foreman/api/test_contentview.py
Test results:
$ nosetests tests/foreman/api/test_contentview.py:ContentViewTestCase
.......
Ran 7 tests in 272.206s
OK
$ nosetests tests/foreman/api/test_contentview.py:ContentViewUpdateTestCase
..
Ran 2 tests in 5.527s
OK
=> Update API tests for content views

robottelo/cli/base.py, tests/foreman/cli/test_puppetmodule.py
There are two commits in this PR.
* First commit adds json support to hammer base cli - this is mainly updated because of https://github.com/SatelliteQE/robottelo/issues/2788
* Second commit updates hammer puppet-module tests - by removing an old invalid test and adding two new tests
=> Fix for Bug1127382

tests/foreman/api/test_discoveredhost.py
Update module `tests.foreman.api.test_discoveredhost`:
* Drop DDT. (Part of #2769.)
* Add functions that generate randomized data.
* Rename method `test_upload_facts_for_discovered_host` to `test_upload_facts`.
The test is in a module of tests for discovered hosts, so mentioning
discovered hosts in the name is redundant; this is in line with the other
method named `test_refresh_facts`; and this lets pylint lint the entire module
with no complaints.
Test results:
$ nosetests tests/foreman/api/test_discoveredhost.py
SSSSSSSSSSSSSSS.
Ran 16 tests in 3.168s
OK (SKIP=15)
=> Update API tests for discovered hosts

tests/foreman/api/test_environment.py
Update module `tests.foreman.api.test_environment`:
* Drop DDT. (Part of #2769.)
* Split the negative creation test in to two parts to better reflect the
different semantics of the tests and to make each of the two tests more
concise.
Test results:
$ nosetests tests/foreman/api/test_environment.py
...
Ran 3 tests in 6.449s
OK
=> Update API tests for environments

tests/foreman/longrun/test_oscap.py
*) Runs rhel6 and rhel7 oscap scans on respective vm's and uploads
the reports to satellite6.
=> Added oscap End_to_End testcase to foreman.longrun

robottelo/cli/import_.py, tests/foreman/cli/test_import.py
- Got rid of redundant code (for preparing the data)
- `csv_to_dataset()` moved to `Import` class (separate commit)
- added tests for testing `hammer import repository-enable`
- manifest import tests adjusted to reflect BZ#1260722
```bash
$ nosetests test_import.py
.............................
Ran 29 tests in 4454.522s
OK
```
=> CLI/Import - Test import en repos

tests/foreman/ui/test_partitiontable.py
Skipping HTML case till corresponding BZ will be fixed
```
nosetests tests/foreman/ui/test_partitiontable.py -m test_remove_partition_table
...S..
Ran 6 tests in 162.749s
OK (SKIP=1)
```
=> Fix for partition table issue

tests/foreman/ui/test_hw_model.py
Closes #2742 
```
nosetests tests/foreman/ui/test_hw_model.py -m test_delete_positive
...S..
Ran 6 tests in 108.454s
OK (SKIP=1)
```
=> Skipping HTML case for hw models till corresponding BZ will be fixed

robottelo/cli/import_.py
Modify method `csv_to_dataset` - the method now uses native csv module
and correctly parses multiline records (Fixes #2803)
It also properly downloads the csv file to parse it instead of abusing the `ssh.command('cat {}')` command.
=> CLI/Import - optimized csv_to_dataset() method

tests/foreman/cli/test_partitiontable.py
Part of #2776 
Tests results:
```
nosetests tests/foreman/cli/test_partitiontable.py
......
Ran 6 tests in 102.969s
OK
```
Depends on #2778
=> Refactor partitiontable tests according to #2776

robottelo/cli/metatest/template_methods.py, tests/foreman/cli/test_activationkey.py, tests/foreman/cli/test_architecture.py, tests/foreman/cli/test_computeresource.py, tests/foreman/cli/test_contenthost.py, tests/foreman/cli/test_contentviewfilter.py
Part of #2776
Updated following CLI tests:
* activationkey
* architecture
* computeresource
* contenthost
* contentviewfilter
* metatest template_methods
=> Update 6 test modules according to #2776

robottelo/cli/metatest/template_methods.py, tests/foreman/cli/test_contentviews.py, tests/foreman/cli/test_docker.py, tests/foreman/cli/test_domain.py, tests/foreman/cli/test_environment.py, tests/foreman/cli/test_fact.py, tests/foreman/cli/test_globalparam.py, tests/foreman/cli/test_gpgkey.py, tests/foreman/cli/test_host.py, tests/foreman/cli/test_host_collection.py, tests/foreman/cli/test_hostgroup.py, tests/foreman/cli/test_lifecycleenvironment.py
Part of #2776
Updated following CLI tests:
* contentviews
* docker
* domain
* environment
* fact
* globalparam
* gpgkey
* host
* host_collection
* hostgroup
* lifecycleenvironment
=> Update another 11 test modules according to #2776

tests/foreman/cli/test_org.py
This PR also:
* Removes closed bugzilla references
* Made pylint 100%
* optimized/renamed test data
=> ddt removal in cli org tests

tests/foreman/cli/test_activationkey.py
This PR also:
* Removes closed bugzilla references
* Made pylint 100%
* optimized/renamed test data
=> ddt removal in cli activation key tests

tests/foreman/cli/test_architecture.py, tests/foreman/cli/test_computeresource.py
Also made:
* Made pylint 100%
* optimized/renamed test data
=> ddt removal in cli architecture and compute resource tests

tests/foreman/cli/test_contentviewfilter.py
This PR also:
* Made pylint 100%
* optimized the tests to remove redundant setup calls to improve test execution time
=> ddt removal in cli content view filter tests

tests/foreman/cli/test_location.py, tests/foreman/cli/test_medium.py, tests/foreman/cli/test_model.py, tests/foreman/cli/test_org.py, tests/foreman/cli/test_os.py, tests/foreman/cli/test_product.py, tests/foreman/cli/test_proxy.py, tests/foreman/cli/test_report.py, tests/foreman/cli/test_repository.py, tests/foreman/cli/test_roles.py, tests/foreman/cli/test_scparam.py, tests/foreman/cli/test_subnet.py, tests/foreman/cli/test_subscription.py, tests/foreman/cli/test_syncplan.py, tests/foreman/cli/test_template.py, tests/foreman/cli/test_user.py
Part of #2776
Updated following CLI tests:
* location
* medium
* model
* org
* os
* product
* proxy
* report
* repository
* roles
* scparam
* subnet
* subscription
* syncplan
* template
* user
=> Update another 16 test modules according to #2776

robottelo/ui/activationkey.py, robottelo/ui/base.py, robottelo/ui/contentsearch.py, robottelo/ui/contentviews.py, robottelo/ui/discoveryrules.py, robottelo/ui/ldapauthsource.py, robottelo/ui/oscappolicy.py, robottelo/ui/systemgroup.py, tests/foreman/api/test_discoveryrule.py, tests/foreman/ui/test_activationkey.py, tests/foreman/ui/test_ldapauthsource.py
That is last piece of code related to and Closed #2562.
Also, removing completely redundant tests and lowering coverage a bit (which is redundant from my point of view as well). Removing useless text in test descriptions
```
nosetests tests/foreman/ui/test_ldapauthsource.py 
..............
Ran 14 tests in 262.340s
OK
```
```
nosetests tests/foreman/ui/test_discoveryrule.py
..............................
Ran 30 tests in 679.930s
OK
```
```
nosetests tests/foreman/ui/test_activationkey.py
E....SE.S...S.........S...E.......E
Ran 35 tests in 3575.817s
FAILED (SKIP=4, errors=4)
``` …
=> Last part of improvements related to new click method and our general style

robottelo/cli/repository.py, robottelo/performance/pulp.py, robottelo/test.py, tests/foreman/cli/test_import.py, tests/foreman/cli/test_puppetmodule.py, tests/foreman/cli/test_repository_set.py, tests/foreman/longrun/test_inc_updates.py, tests/foreman/performance/test_candlepin_concurrent_subscription_ak.py, tests/foreman/performance/test_standard_prep.py, tests/foreman/smoke/test_cli_smoke.py
Part of #2776
Updated following CLI tests:
* import
* puppetmodule
* repository_set
* longrun/test_inc_updates
* performance/test_candlepin_concurrent_subscription_ak
* performance/test_standard_prep
* smoke/test_cli_smoke
=> Update remaining CLI test modules according to #2776

tests/foreman/api/test_docker.py
Updated all Docker API tests to use `subTest` for all data-driven test
cases, and removed the `ddt` and `data` decorators.
There has not been any gain in the time it takes to run all tests but
they all passed against a Satellite 6.1.2 system, with a total of 48
tests with 1 of them skipped due to it not being implemented yet.
=> Updated Docker API tests to use subTest.

tests/foreman/api/test_role.py, tests/foreman/api/test_user.py
user tests:
```sh
Ran 5 tests in 112.880s
OK
```
role tests:
```sh
Ran 3 tests in 10.469s
OK
```
=> ddt removal in api user and role tests

tests/foreman/cli/test_docker.py
Updated all Docker CLI tests to use `subTest` for all data-driven test
cases, and removed the `ddt` and `data` decorators.
Out of the 49 tests that were executed, 17 were skipped due to the fact
that they are not yet implemented. All other tests passed and the entire
suite was run under 38 minutes.
=> Updated Docker CLI tests to use subTest.

tests/foreman/api/test_multiple_paths.py, tests/foreman/api/test_syncplan.py
- Also optimized the usage of test data in test_multiple_paths.py by creating single entities list and excluding necessary entities as required.
=> ddt removal in sync plan and test_multiple_paths tests

robottelo/cli/import_.py, tests/foreman/cli/test_import.py
Update class `robottelo.cli.import_.Import`:
* Add method `content_host_with_tr_data` to Import class
Add tests `tests.foreman.cli.test_import`:
* Add tests to cover importing of the Content Hosts
```bash
$ nosetests -m _content_hosts_ test_import.py -vs
@test: Import all content hosts from ... ok
@test: Try to invoke usage of a recovery strategy ... SKIP: Skipping test due to open Bugzilla bug #1267224.
@test: Repetitive Import of all content hosts from ... ok
Ran 3 tests in 410.564s
OK (SKIP=1)
```
=>     Update class `robottelo.cli.import_.Import`:

tests/foreman/cli/test_contenthost.py, tests/foreman/cli/test_contentviews.py, tests/foreman/cli/test_fact.py, tests/foreman/cli/test_gpgkey.py
Also this PR
* optimized the usage of setUpClass() and setUp() which decreased the run time
* All modules in this PR are pylint 100% now
* 435 additions and 1,039 deletions. - shows that code is signifcantly optimized
* Many test names are renamed to suit the pylint requirements
=> ddt removal in 4 cli modules

robottelo/cli/import_.py, tests/foreman/cli/test_import.py
Updated 'robottelo.cli.import_.Import', Updated 'tests.foreman.cli.test_import.TestImport'
+ added new methods for handling import of template snippets
+ added default positive test exercising import of template snippets
=> added template snippets import 

tests/foreman/cli/test_import.py
No herbicides. (Part of #2769.)
=> Drop DDT from CLI Import tests

robottelo/helpers.py, tests/foreman/cli/test_os.py, tests/foreman/cli/test_product.py, tests/foreman/cli/test_proxy.py, tests/foreman/cli/test_repository.py
This PR also
* removes old bugzilla references
* optimized test data usage by introducing new data helper methods and reusing existing helper methods
=> ddt removal in another 4 cli modules

robottelo/ui/computeresource.py, robottelo/ui/contentviews.py, robottelo/ui/locators.py, robottelo/ui/repository.py, tests/foreman/api/test_docker.py, tests/foreman/ui/test_activationkey.py, tests/foreman/ui/test_contentviews.py, tests/foreman/ui/test_docker.py, tests/foreman/ui/test_repository.py
Related to #2850 
```
nosetests tests/foreman/ui/test_docker.py
..SS...SS..SSSSSSSSS.............SSSSSS.........S
Ran 49 tests in 4461.365s
OK (SKIP=20)
```
=> Implemented some WebUI Docker stubs (30) and few framework fixes

tests/foreman/smoke/test_api_smoke.py
Closes #2867
```
nosetests tests/foreman/smoke/test_api_smoke.py -m test_get_links
.
Ran 1 test in 4.791s
OK
```
=> Quick fix for issue with new entities in server API

tests/foreman/cli/test_location.py
Test results:
```
Ran 33 tests in 360.011s
OK (skipped=2)
```
=> Fix location max length as 246

tests/foreman/cli/test_syncplan.py, tests/foreman/cli/test_user.py
test_syncplan.py
```py
Ran 9 tests in 274.052s
OK (skipped=1)
```
test_user.py
```py
Ran 91 tests in 516.598s
OK (skipped=60)
```
=> ddt removal - final set of changes for cli tests

tests/foreman/ui/test_computeresource.py
Test result:
```sh
Ran 10 tests in 437.450s
OK
```
=> ddt removal for ui compute resource tests

docs/api/robottelo.ui.rst, robottelo/constants.py, robottelo/test.py, robottelo/ui/factory.py, robottelo/ui/locators.py, robottelo/ui/navigator.py, robottelo/ui/registry.py, tests/foreman/ui/test_docker.py
```
nosetests tests/foreman/ui/test_docker.py:DockerRegistriesTestCase
......
Ran 6 tests in 283.862s
OK
```
=> Adding coverage for Registry entity in WebUI

robottelo/helpers.py
valid_data_list() helper function is widely used to create valid data set for different attributes.  Although this works great in most entities, there are few entities which don't honor these standards and they should not use this helper function.  This docstring text will help future coders to be aware of this issue.
=> Adding documentation for valid_data_list() helper function

tests/foreman/ui/test_config_groups.py
Test result:
```
Ran 4 tests in 332.130s
OK
```
=> ddt removal in ui config groups tests

tests/foreman/rhci/test_rhci.py
I do not have test setup for rhci.  @anarang can you please review this PR and test these changes in your local setup? Thanks!
=> ddt removal in rhci tests

tests/foreman/data/hammer_commands.json
Update hammer commands and options data based on current build.
Closes #2864 
Test results (modified locally the test to traverse from hammer filter instead of entire possibilities):
```
py.test tests/foreman/cli/test_hammer.py -k test_hammer_options
========================= test session starts ==========================
platform linux2 -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.2
rootdir: /home/elyezer/code/robottelo, inifile: 
plugins: cov
collected 1 items 
====================== 1 passed in 30.33 seconds =======================
```
=> Update hammer commands and options data

robottelo/config/settings.py
=> fix settings for virtual_display evaluation

tests/foreman/ui/test_ldapauthsource.py
```sh
Ran 14 tests in 191.462s
OK
```
=> config fix for ui ldap auth source tests

tests/foreman/cli/test_import.py
CLI/Import - AKs import
+ added default positive test exersizing import of activation keys
=> CLI/Import - tests for importing AKs

robottelo/config/settings.py
Add missing default value for the screenshots path and cast to boolean
upstream option.
=> Update settings default values and cast

tests/foreman/ui/test_environment.py
Test results:
```py
.....
Ran 5 tests in 141.879s
OK
```
=> ddt removal in ui environment tests

tests/foreman/ui/test_hostgroup.py
Test results:
```py
......
Ran 6 tests in 155.283s
OK
```
=> ddt removal in ui hostgroup tests

tests/foreman/ui/test_ldapauthsource.py
Test results:
```sh
Ran 2 tests in 125.062s
OK
```
=> ddt removal in ui ldap auth source tests

tests/foreman/ui/test_login.py
Test results:
```sh
Ran 2 tests in 34.811s
OK
```
=> ddt removal in ui login tests

tests/foreman/ui/test_usergroup.py
Test results:
```sh
.
Ran 6 tests in 37.036s
OK (skipped=5)
```
=> ddt removal in ui usergroups tests

tests/foreman/ui/test_template.py
Test results:
```sh
Ran 11 tests in 256.942s
OK
```
=> ddt removal in ui template tests

tests/foreman/ui/test_settings.py
```sh
Ran 29 tests in 296.042s
OK (skipped=9)
```
=> ddt removal in ui settings tests

tests/foreman/ui/test_sync.py
test results:
```sh
Ran 1 test in 189.690s
OK
```
=> ddt removal for ui sync tests

docs/api/robottelo.ui.rst, robottelo/constants.py, robottelo/test.py, robottelo/ui/base.py, robottelo/ui/container.py, robottelo/ui/factory.py, robottelo/ui/locators.py, robottelo/ui/navigator.py, tests/foreman/ui/test_docker.py
@omaciel @elyezer Implementing idea that was proposed on a Friday demo. I know that we have a lot of things that need to be discussed (I remember that), but here we have increase of coverage, not the re-factor procedure and anyway current approach is much better than old one. I created separate issue https://github.com/SatelliteQE/robottelo/issues/2916 where we can track improvement process exclusively.
```
nosetests tests/foreman/ui/test_docker.py:DockerContainersTestCase
..S.
Ran 4 tests in 354.710s
OK (SKIP=1)
```
=> Adding coverage for Container entity in WebUI

robottelo/helpers.py, tests/foreman/cli/test_import.py
CLI Import - prepare_import_data() refactor
* move prepare_import_data() out of helpers (very specific to be there)
* move all dataset preparations into prepare_import_data()
* fix misnomer for custom-channels
=> CLI Import - prepare_import_data() refactor

tests/foreman/ui/test_hw_model.py
Test results:
```sh 
Ran 6 tests in 224.933s
OK (skipped=1)
```
=> ddt removal in ui hardware models

tests/foreman/ui/test_syncplan.py
Test results:
```
Ran 11 tests in 688.541s
OK (skipped=1)
```
=> ddt removal in ui sync plan tests

tests/foreman/ui/test_subnet.py
Test result:
```sh
.
Ran 1 test in 36.537s
OK
.
Ran 1 test in 27.644s
OK
.
Ran 1 test in 32.575s
OK
.
Ran 1 test in 49.108s
OK
.
Ran 1 test in 37.237s
```
=> ddt removal for ui subnet tests

tests/foreman/ui/test_partitiontable.py
```sh
Ran 6 tests in 158.268s
OK (skipped=2)
```
=> ddt removal in ui partitiontable tests

tests/foreman/cli/test_contentviews.py
Added `test_bz1184442` to verify deleting content-view actually deletes files from hard drive.
Closes #2911 
Test results:
```
nosetests tests/foreman/cli/test_contentviews.py -m test_bz1184442
.
Ran 1 test in 74.263s
OK
```
=> Automate BZ1184442 for CLI

robottelo/cli/task.py
+ added hammer task subcommand
=> CLI hammer task subcommand

tests/foreman/smoke/test_cli_smoke.py, tests/foreman/smoke/test_ui_smoke.py
*Note*:
None of the tests are affected so no testing necessary.
=> ddt removal in smoke tests

tests/foreman/ui/test_role.py
```sh
......
Ran 6 tests in 158.524s
OK
```
=> ddt removal in ui role tests

tests/foreman/ui/test_contentviews.py
Test results:
```sh
.
Ran 1 test in 49.488s
OK
.
Ran 1 test in 147.374s
OK
.
Ran 1 test in 51.800s
OK
.
Ran 1 test in 142.940s
OK
.
Ran 1 test in 41.104s
OK
.
Ran 1 test in 173.289s
OK
```
=> ddt removal in ui content views tests

tests/foreman/ui/test_products.py
~~Any ui test folks out there:
Does anybody know why these 2 tests failed locally in my box? This seem to be unrelated to my changes.~~
I fixed the errors now. Please see my newer comments for new test results.
```sh
....E..F
ERROR: @Test: Create Content Product with same name but in another org
File "/home/suresh/hacking/framework/robottelo/robottelo/decorators.py", line 136, in wrapper
return func(*args, **kwargs)
File "/home/suresh/hacking/framework/robottelo/tests/foreman/ui/test_products.py", line 72, in test_positive_create_in_different_orgs
force_context=True,
....
....
--------------------- >> end captured …
```
=> ddt removal in ui products tests

tests/foreman/ui/test_domain.py
test results:
```sh
.
Ran 1 test in 32.009s
OK
.
Ran 1 test in 32.329s
OK
S
Ran 1 test in 33.316s
OK (SKIP=1)
.
Ran 1 test in 36.820s
OK
.
Ran 1 test in 61.225s
OK
.
Ran 1 test in 82.572s
OK
```
=> ddt removal in ui domain tests

tests/foreman/ui/test_location.py
```sh
......................E....
ERROR: @test: Remove environment by using location name & environment name
nailgun.client: WARNING: Received HTTP 422 response: {
"error": {"id":null,"errors":{"name":["is alphanumeric and cannot contain spaces"]},"full_messages":["Name is alphanumeric and cannot contain spaces"]}
}
--------------------- >> end captured logging << ---------------------
Ran 27 tests in 3637.678s
FAILED (errors=1)
```
=> ddt removal in ui location tests

tests/foreman/ui/test_operatingsys.py
Test results:
```sh
.
Ran 1 test in 50.558s
OK
.
Ran 1 test in 31.597s
OK
.
Ran 1 test in 53.988s
OK
.
Ran 1 test in 69.869s
OK
]
.
Ran 1 test in 49.198s
OK
.
Ran 1 test in 36.440s
OK
.
Ran 1 test in 58.329s
OK
```
=> ddt removal in ui operating system tests

tests/foreman/ui/test_repository.py
```sh
E..........F..
ERROR: @Test: Create repository with minimal input parameters
File "/home/sthirugn/workspace/robottelo/robottelo/decorators.py", line 136, in wrapper
return func(*args, **kwargs)
File "/home/sthirugn/workspace/robottelo/tests/foreman/ui/test_repository.py", line 99, in test_create_repo_basic
url=FAKE_1_YUM_REPO,
FAIL: @Test: Create Custom docker repos and sync it via the repos page.
File …
```
=> ddt removal in ui repo tests

tests/foreman/ui/test_puppet_classes.py
=> ddt removal in ui puppet classes tests

tests/foreman/cli/test_domain.py
```sh
...................
Ran 19 tests in 194.480s
OK
```
=> ddt removal in cli domain tests

tests/foreman/cli/test_environment.py
```sh
.
Ran 1 test in 12.654s
OK
.
Ran 1 test in 19.724s
OK
```
=> ddt removal in cli env tests

tests/foreman/ui/test_gpgkey.py
=> ddt removal in ui gpgkey tests

robottelo/ui/base.py
=> Use search instead of search_entity in Base class functions

robottelo/ui/architecture.py, robottelo/ui/base.py, robottelo/ui/gpgkey.py
Removing search functionality from entity level and moving all logic on base level
```
nosetests tests/foreman/ui/test_architecture.py
..........................................F.
```
One failure due well-known issue with entity length (#2913)
=> Change search method in base class to re-use in all entities classes

robottelo/ui/architecture.py, robottelo/ui/base.py, robottelo/ui/gpgkey.py
Reverts SatelliteQE/robottelo#2981
gpg key tests are failing, need first to fix them.
=> Revert 3094ad813d8f4bb680601f1cddb3a8427957ce34

robottelo/ui/architecture.py, robottelo/ui/base.py, robottelo/ui/gpgkey.py, robottelo/ui/products.py, tests/foreman/ui/test_gpgkey.py
Removing search functionality from entity level and moving all logic on base level
Fixed Architecture:
```
nosetests tests/foreman/ui/test_architecture.py
..........................................F.
```
One failure due well-known issue with entity length (#2913)
Fixed GPG Key:
```
nosetests tests/foreman/ui/test_gpgkey.py
.SSSS.....E........S..S...EESE.ES.S..SE.
Ran 40 tests in 5164.793s
FAILED (SKIP=10, errors=6)
```
Re-run after few more fixes:
```
nosetests tests/foreman/ui/test_gpgkey.py -m test_key_associate_15
.
Ran 1 test in 150.347s
OK
nosetests tests/foreman/ui/test_gpgkey.py -m test_key_associate_16
. …
```
=> Change search method in base class

robottelo/ui/base.py, robottelo/ui/contentviews.py, robottelo/ui/domain.py, robottelo/ui/hostgroup.py, tests/foreman/ui/test_domain.py
a) Updated the base `search` function to use common_locator when
foreman entity and it's length more than 30 chars
b) Updated delete domain test from `test_remove_domain` to
`test_delete_domain` for consistency.
=> Updated the cv, domain, host_group to use updated base search function

robottelo/ui/user.py, tests/foreman/smoke/test_ui_smoke.py, tests/foreman/ui/test_user.py, tests/foreman/ui/test_usergroup.py
Part of #2930 
Test results:
```
nosetests tests/foreman/ui/test_user.py
ESSSSSSSSSSSSSSSS.....SSSSSSSSSSSSSSSSSSSSSSSSSSSSS.S.....S.....SSSSSSSSSSSSSSSSSSSSSSSSSSSS.SSSSS..
ERROR: @Test: Delete a User
Ran 100 tests in 1322.898s
FAILED (SKIP=80, errors=1)
```
Fixed and re-ran the failed test:
```
nosetests tests/foreman/ui/test_user.py -m test_delete_user
.
Ran 1 test in 170.012s
OK
```
Affected modules:
```
nosetests tests/foreman/smoke/test_ui_smoke.py -m test_find_admin_user
.
Ran 1 test in 20.365s
OK …
```
=> UI: Update user search according to #2930

robottelo/ui/trend.py, tests/foreman/ui/test_trend.py
Part of #2930
Test results:
```
nosetests tests/foreman/ui/test_trend.py    
...
Ran 3 tests in 78.283s
OK
```
=> UI: Update trend search according to #2930

robottelo/ui/usergroup.py
Part of #2930 
Test results:
```
nosetests tests/foreman/ui/test_usergroup.py        
S.SSSS
Ran 6 tests in 74.088s
OK (SKIP=5)
```
=> UI: Update usergroup search according to #2930

robottelo/ui/activationkey.py, robottelo/ui/computeprofile.py, robottelo/ui/computeresource.py, robottelo/ui/configgroups.py, robottelo/ui/partitiontable.py, robottelo/ui/products.py, tests/foreman/ui/test_activationkey.py, tests/foreman/ui/test_config_groups.py, tests/foreman/ui/test_docker.py
**Activation key:**
```
nosetests tests/foreman/ui/test_activationkey.py
E....SE.S...S............E.......E
Ran 34 tests in 5919.913s
FAILED (SKIP=3, errors=4)
```
Four failures happened due VirtualMachineError and don't have references to my changes
```
nosetests tests/foreman/ui/test_docker.py -m test_add_docker_repo_to_activation_key
.
Ran 1 test in 106.718s
OK
```
```
nosetests tests/foreman/ui/test_docker.py -m test_add_docker_repo_composite_view_to_activation_key
.
Ran 1 test in 188.408s
OK
```
**Compute Profile:**
```
nosetests tests/foreman/ui/test_computeresource.py -m …
```
=> Fixing 6 entities according to new search approach

robottelo/datafactory.py, tests/foreman/api/test_partitiontable.py, tests/foreman/ui/test_config_groups.py, tests/foreman/ui/test_discoveryrule.py, tests/foreman/ui/test_domain.py, tests/foreman/ui/test_hostgroup.py, tests/foreman/ui/test_location.py, tests/foreman/ui/test_partitiontable.py, tests/foreman/ui/test_puppet_classes.py, tests/foreman/ui/test_role.py, tests/foreman/ui/test_subnet.py, tests/foreman/ui/test_template.py
=> Rename len1 to length in generate_strings_list

tests/foreman/longrun/test_inc_updates.py, tests/foreman/rhci/test_rhci.py
=> Drop print statements on tests

robottelo/datafactory.py, tests/foreman/cli/test_architecture.py, tests/foreman/cli/test_domain.py, tests/foreman/cli/test_environment.py, tests/foreman/cli/test_hostgroup.py, tests/foreman/cli/test_model.py, tests/robottelo/test_datafactory.py
=> Updated invalid_id_list() to be a general data function.

robottelo/ui/org.py
UI: Org search refactor
(Part of #2930)
=> UI: Org search refactor

robottelo/ui/operatingsys.py, tests/foreman/ui/test_operatingsys.py
UI: OperatingSys search refactor
(Part of #2930)
=> UI: OperatingSys search refactor

robottelo/ui/discoveryrules.py
*) Currently searchbox is not implemented for discovery_rule.
*) Hence we still use the search function here.
=> Updated discovery_rule entity to use the new search approach.

robottelo.properties.sample, robottelo/ui/contentenv.py, robottelo/ui/ldapauthsource.py, robottelo/ui/location.py, robottelo/ui/settings.py, robottelo/ui/subnet.py, robottelo/ui/systemgroup.py, tests/foreman/smoke/test_ui_smoke.py, tests/foreman/ui/test_contentenv.py, tests/foreman/ui/test_ldapauthsource.py, tests/foreman/ui/test_subnet.py
**Subnet:**
```
nosetests tests/foreman/ui/test_subnet.py
....S.....
Ran 10 tests in 405.892s
OK (SKIP=1)
```
**Location:**
```
nosetests tests/foreman/ui/test_location.py
.E..................E......
Ran 27 tests in 4338.874s
FAILED (errors=2)
```
```
nosetests tests/foreman/ui/test_location.py -m test_add_configtemplate
.
Ran 1 test in 239.159s
OK
```
```
nosetests tests/foreman/ui/test_location.py -m test_remove_configtemplate
.
Ran 1 test in 365.310s
OK
```
**Lifecycle Environment:**
```
nosetests …
```
=> Fixing 5 entities according to new search approach

robottelo/ui/base.py, robottelo/ui/medium.py
```
nosetests tests/foreman/ui/test_medium.py
........
Ran 8 tests in 293.721s
OK
```
=> Fixing medium class for new search procedure

robottelo/ui/factory.py, robottelo/ui/locators.py, robottelo/ui/oscapcontent.py, robottelo/ui/oscappolicy.py, robottelo/ui/oscapreports.py, tests/foreman/longrun/test_oscap.py
=> UI: Update searching of oscap entities according to #2930

robottelo/constants.py, robottelo/ui/base.py, robottelo/ui/container.py, robottelo/ui/contentenv.py, robottelo/ui/discoveryrules.py, robottelo/ui/ldapauthsource.py, robottelo/ui/repository.py, tests/foreman/smoke/test_ui_smoke.py, tests/foreman/ui/test_docker.py
Fixing container class for new search procedure. Also fixing general search procedure for long strings. Add description for custom search methods
=> Fix last entity for new search procedure

robottelo/datafactory.py, tests/foreman/cli/test_environment.py, tests/foreman/cli/test_roles.py, tests/foreman/cli/test_user.py, tests/foreman/ui/test_environment.py, tests/robottelo/test_datafactory.py
Test results:
```sh
Ran 14 tests in 152.948s
OK (skipped=2)
Ran 4 tests in 1.393s
OK (skipped=4)
Ran 91 tests in 509.287s
OK (skipped=60)
Ran 5 tests in 166.457s
OK
....
Ran 4 tests in 0.024s
OK
```
=> Moving more data functions to datafactory

tests/foreman/data/hammer_commands.json
Our automation shows that two new subcommands were added to `hammer source-auth ldap`:
```bash
Error Message
{
"hammer auth-source ldap create": {
"added_command": false,
"added_options": [
"usergroup-sync"
]
},
"hammer auth-source ldap update": {
"added_command": false,
"added_options": [
"usergroup-sync"
]
}
}
```
I have updated `hammer_commands.json` with these 2 new subcommands and tested it:
```bash
(robottelo)┌[omaciel☮Ogs-MacBook-Pro.local]-(~/hacking/robottelo)-[git://master ✗]-
└> nosetests -v tests/foreman/cli/test_hammer.py:HammerCommandsTestCase.test_hammer_options
@Test: check all provided options for every hammer command ... ok
Ran 1 test in 1142.590s
OK
```
=> Added new subcommands to `hammer_commands.json`.

tests/foreman/api/test_multiple_paths.py
Update the entities checked on the test to include just entities which
are possible to post on its path.
```python
nosetests tests/foreman/api/test_multiple_paths.py -m test_post_unauthorized
.
Ran 1 test in 36.721s
OK
```
Closes #3020
=> Update test_post_unauthorized API test

tests/foreman/api/test_activationkey.py
Added 4 new tests to perform more 'CRUD' against Activation Keys via the API.
=> Added more 'CRUD' tests for Activation Keys via API.

tests/foreman/api/test_architecture.py
Added 5 new basic 'CRUD' tests for Architecture via the API.
=> Added 'CRUD' tests to Architecture via API.

tests/foreman/api/test_config_template.py
I have added 5 new 'CRUD' tests to exercise Configuration Templates via the API.
=> Added 5 new CRUD tests for Config Template via API.

tests/foreman/api/test_contentview.py
This PR does the following:
* Adds a couple of new 'CRUD' test cases for ContentView via the API interface;
* Renames existing test case names for more user friendly names;
* Removes extra blank lines from docstrings;
All tests have been run and passed.
=> Added 'CRUD' tests to ContentView via API.

tests/foreman/api/test_lifecycleenvironment.py
Closes #3043 
```
nosetests tests/foreman/api/test_lifecycleenvironment.py
.........
Ran 9 tests in 220.313s
OK
```
=> Add CRUD tests for Lifecycle Environment entity

tests/foreman/cli/test_docker.py
Closes #3047 
Test result after commenting `skip_if_bug_open` and manual downgrade of `docker` package to valid version:
```
py.test tests/foreman/cli/test_docker.py -k test_create_container_content_view
======================================== test session starts =========================================
platform linux2 -- Python 2.7.5, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/andriy/Downloads/robottelo, inifile: 
collected 51 items 
tests/foreman/cli/test_docker.py .
=================== 50 tests deselected by '-ktest_create_container_content_view' ====================
============================= 1 passed, 50 deselected in 344.08 seconds ==============================
```
=> CLI: Automate docker container creation using content view

robottelo/constants.py, tests/foreman/api/test_media.py
Closes #3046
```
nosetests tests/foreman/api/test_media.py
..............
Ran 14 tests in 151.060s
OK
```
=> Add CRUD tests for Media entity

robottelo.properties.sample, robottelo/config/settings.py, robottelo/test.py
UI: config option to specify firefox binary location
(Issue #3021)
=> UI: config option to specify firefox binary location

tests/foreman/ui/test_architecture.py
In addition to ddt removal,
~~This PR also fixes the architecture name bug if it had html names.~~
=> ddt removal in ui architecture tests

robottelo.properties.sample, robottelo/config/settings.py
This is required to cover step 1) in issue #3063
=> Added params for libvirt_host

tests/foreman/api/test_media.py
=> Update os media to medium to reflect nailgun update

robottelo/config/settings.py
- Placed `LibvirtHostSettings` class in alphabetical order.
- updated missing entry for vlan_networking and compute_resources under settings main class
=> Updated missing entry for vlan_networking and compute_resources under settings main class

robottelo/config/settings.py
I missed that to update in my earlier PR #3074
=> Updated compute_resources and vlan_networking features under configure method

tests/foreman/api/test_operatingsystem.py
```
nosetests tests/foreman/api/test_operatingsystem.py
.S.................................
Ran 35 tests in 208.382s
OK (SKIP=1)
```
=> Add CRUD tests for operating system entity for API part

robottelo/cli/factory.py, robottelo/cli/usergroup.py
CLI automate usergroup subcommand
+ class representing own hammer user-group sub-command
+ factory methods make_usergroup(), make_usergroup_external()
(Part of #3072)
Test class is still to be implemented....but that's another PR
=> CLI automate usergroup subcommand

tests/foreman/cli/test_gpgkey.py
Automated some of CLI gpg key stub and updated existing tests.
Closes #2480
Closes #2481 
```python
py.test tests/foreman/cli/test_gpgkey.py
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
collected 64 items 
tests/foreman/cli/test_gpgkey.py sss...s..s...s...sssssssss.ssssssssssssss..s..ss..ss.sss.s..ss.s
====================== 23 passed, 41 skipped in 1033.30 seconds ======================
```
=> Automate some of CLI gpg key stubs

tests/foreman/api/test_environment.py
```
nosetests tests/foreman/api/test_environment.py
..........
Ran 10 tests in 79.076s
OK
```
Closes #3076
=> Add CRUD tests for Environment entity for API part

.coveragerc, .gitignore, .travis.yml, Makefile, README.rst, requirements-optional.txt, tox.ini
Add target to make file to locally check coverage and enable coverage
checking to Travis.
=> Add coverage checking

tests/foreman/ui/test_discoveredhosts.py
First PR SatelliteQE/automation-tools/pull/271 needs to be merged before this. I'll test this and paste the test results..
=> Fixed discovery tests to use new infra with external libvirt

robottelo/decorators.py, tests/robottelo/test_datafactory.py, tests/robottelo/test_decorators.py
Add tests to ensure 100% coverage for tests.robottelo.test_decorators.
Bonus: Cover robottelo.datafactory with 100%.
=> Cover robottelo.decorators with 100%

docs/api/tests.foreman.ui.rst, robottelo.properties.sample, robottelo/cli/factory.py, robottelo/config/settings.py, robottelo/ui/container.py, robottelo/ui/factory.py, robottelo/ui/locators.py, robottelo/ui/oscapcontent.py, tests/foreman/ui/test_oscapcontent.py
a) Create oscap_content.
b) Check whether Default oscap_content exists.
c) Delete oscap_content.
=> Added oscap_content related tests.

tests/foreman/ui/test_puppet_classes.py
Closes #2966 
Borrowed CI machine for testing:
```
nosetests tests/foreman/ui/test_puppet_classes.py
..
Ran 2 tests in 398.909s
OK
```
=> Use better data for tests in puppet class module of WebUI functionality

robottelo/test.py
In order to better identify the screen shots now the path have the class
name as a component. The new name will be
screenshots_path/YYYY-MM-DD/ClassName/test_method_name/filename.png.
Closes #3115
=> Update take_screenshot method

tests/foreman/cli/test_installer.py
All test cases have been renamed as per #3083
=> Renamed tests for cli/test_installer.py.

tests/foreman/cli/test_lifecycleenvironment.py
=> Renamed tests for cli/test_lifecycleenvironment.py.

tests/foreman/cli/test_location.py
=> Renamed tests for cli/test_location.py.

tests/foreman/cli/test_medium.py
=> Renamed tests for tests/foreman/cli/test_medium.py.

tests/foreman/cli/test_model.py
=> Renamed tests for cli/test_model.py.

docs/api/tests.foreman.ui.rst, tests/foreman/ui/test_contentview.py, tests/foreman/ui/test_discoveredhost.py, tests/foreman/ui/test_discoveryrule.py, tests/foreman/ui/test_docker.py, tests/foreman/ui/test_domain.py, tests/foreman/ui/test_email.py, tests/foreman/ui/test_environment.py, tests/foreman/ui/test_errata.py, tests/foreman/ui/test_gpgkey.py, tests/foreman/ui/test_host.py, tests/foreman/ui/test_host_system_unification.py, tests/foreman/ui/test_hostgroup.py, tests/foreman/ui/test_hw_model.py, tests/foreman/ui/test_isodownload.py, tests/foreman/ui/test_ldap_auth.py, tests/foreman/ui/test_ldapauthsource.py, tests/foreman/ui/test_location.py, tests/foreman/ui/test_login.py, tests/foreman/ui/test_medium.py
Tests for module that has more than cosmetic changes (don't know why I did that, but just wanted to improve it :smile: )
```
nosetests tests/foreman/ui/test_discoveryrule.py
........
Ran 8 tests in 501.615s
OK
```
=> Fix UI test names according to new naming conventions (part 1)

tests/foreman/cli/test_myaccount.py
=> Renamed tests for cli/test_myaccount.py.

robottelo/ui/base.py, robottelo/ui/navigator.py
Closes #3124
Run few random tests to make sure that we do not brake anything:
```
nosetests tests/foreman/ui/test_location.py -m test_remove_environment
.
Ran 1 test in 79.179s
OK
```
```
nosetests tests/foreman/ui/test_contentviews.py -m test_cv_create
..
Ran 2 tests in 287.527s
OK
```
```
nosetests tests/foreman/ui/test_products.py -m test_positive_create_basic
.
Ran 1 test in 123.422s
OK
```
=> Makes set context functionality more reliable

tests/foreman/cli/test_operatingsystem.py
Updated all test cases names as per #3038.
=> Renamed tests cli/tests_operatingsystem.py.

tests/foreman/cli/test_partitiontable.py
Updated all test cases names as per #3038.
=> Renamed tests for cli/test_partitiontable.py.

tests/foreman/cli/test_product.py
Test case naming follows #3038 conventions.
=> Renamed tests for cli/test_product.py.

docs/api/robottelo.ui.rst, docs/api/tests.foreman.ui.rst, robottelo/test.py, robottelo/ui/factory.py, robottelo/ui/lifecycleenvironment.py, tests/foreman/api/test_activationkey.py, tests/foreman/api/test_architecture.py, tests/foreman/api/test_config_template.py, tests/foreman/api/test_contentview.py, tests/foreman/api/test_contentviewfilter.py, tests/foreman/api/test_discoveryrule.py, tests/foreman/api/test_docker.py, tests/foreman/api/test_lifecycleenvironment.py, tests/foreman/api/test_media.py, tests/foreman/api/test_operatingsystem.py, tests/foreman/api/test_organization.py, tests/foreman/api/test_partitiontable.py, tests/foreman/api/test_subscription.py, tests/foreman/api/test_syncplan.py, tests/foreman/smoke/test_ui_smoke.py, tests/foreman/ui/test_activationkey.py, tests/foreman/ui/test_adusergroup.py, tests/foreman/ui/test_architecture.py, tests/foreman/ui/test_capsule.py, tests/foreman/ui/test_computeresource.py, tests/foreman/ui/test_config_group.py, tests/foreman/ui/test_contentsearch.py, tests/foreman/ui/test_lifecycleenvironment.py
Also updated some negative API tests
=> Fix UI test names according to new naming conventions (part 3)

robottelo/datafactory.py, tests/foreman/cli/test_hostgroup.py, tests/robottelo/test_datafactory.py
=> Fix max name length for CLI hostgroup tests

tests/foreman/cli/test_abrt.py
=> Rename abrt tests

tests/foreman/cli/test_contenthost.py, tests/foreman/cli/test_system_registration.py
**Note:** 
Once this PR is merged, I will remove test_system_registration.py module and move its tests to test_contenthost.py.  I did not do that in this PR in order to show what tests are being removed/kept in test_system_registration.py
=> Rename cli contenthost as per issue #3083

tests/foreman/cli/test_user.py, tests/foreman/ui/test_user.py
Closes #3162
Remove a lot of unnecessary stubs and implement new tests
Re-reviewed tiers
Updated all names to our new conventions (https://github.com/SatelliteQE/robottelo/issues/3083)
```
nosetests tests/foreman/cli/test_user.py
SS...........SSS.S................SS......SS...SS
Ran 49 tests in 1155.877s
OK (SKIP=12)
```
=> Add more coverage for User entity for CLI

docs/api/tests.foreman.cli.rst, docs/api/tests.foreman.ui.rst, robottelo/ui/locators.py, robottelo/ui/oscappolicy.py, tests/foreman/cli/test_activationkey.py, tests/foreman/ui/test_oscapcontent.py, tests/foreman/ui/test_oscappolicy.py
a) This also includes few doc-strings fix.
=> Added oscap_policy related test-cases

tests/foreman/api/test_hostcollection.py
Test results:
```python
py.test -v tests/foreman/api/test_hostcollection.py
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1 -- /home/andrii/env/bin/python
plugins: xdist-1.13.1
collected 17 items 
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_negative_create_with_invalid_name PASSED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_add_system PASSED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_add_systems PASSED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_create_with_description PASSED …
```
=> Implemented API Host Collection CRUDs

robottelo/vm.py
Make sure to have the expected configuration before proceeding with RHAI
client setup.
=> Improve VM configure_rhai_client

robottelo/manifests.py, tests/foreman/ui/test_organization.py
Make sure to download the template when using the original manifest.
Also fix a missing refactor line where is using the original manifest.
=> Fix original manifest generation

tests/foreman/cli/test_host.py
Fix: CLI test_host/test_positive_create_using_libvirt_without_mac
+ use setup external libvirt instead of blindly expecting libvirt of SAT6 machine
+ added creation assert
+ added cleanup (Host.delete)
(Part of #2931.)
=> Fix: CLI test_host/test_positive_create_using_libvirt_without_mac

tests/foreman/api/test_contentview.py
```
nosetests tests/foreman/api/test_contentview.py -m test_positive_promote_out_of_sequence
.
Ran 1 test in 103.879s
OK
```
```
nosetests tests/foreman/api/test_contentview.py -m test_negative_update_label
S
Ran 1 test in 9.693s
OK (SKIP=1)
```
```
nosetests tests/foreman/api/test_contentview.py -m test_positive_publish_rh
..
Ran 2 tests in 128.481s
OK
```
```
nosetests tests/foreman/api/test_contentview.py -m test_positive_promote_rh
..
Ran 2 tests in 172.624s
OK
```
=> Implemented few more stubs for Content View functionality in API

tests/foreman/cli/test_myaccount.py
Closes #3228
```
nosetests tests/foreman/cli/test_myaccount.py
..S...S..
Ran 9 tests in 82.546s
OK (SKIP=2)
```
=> Implement some stubs for my account functionality for CLI

robottelo/decorators.py, tests/foreman/longrun/test_oscap.py, tests/foreman/ui/test_sync.py
features
This covers the following areas:
a) oscap hardening
b) disconnected to connected RedHat Repo syncs
c) oscap email reporting
=> Added test stubs for oscap hardening, disconnected to connected

docs/api/tests.foreman.ui.rst, robottelo/ui/computeprofile.py, robottelo/ui/factory.py, robottelo/ui/locators.py, tests/foreman/ui/test_computeprofile.py
Closes #2605
```
nosetests tests/foreman/ui/test_computeprofile.py
.....
Ran 5 tests in 929.732s
OK
```
Used `generate_strings_list(length=8)` constructs as per https://github.com/SatelliteQE/robottelo/issues/3101
=> Implement CRUD methods and tests for Compute Profile for WebUI

tests/foreman/ui/test_classparameters.py
This is an initial draft of TestCases for feature 'Smart Class Parameters'.
In upstream, Smart Class Parameters appears under following path:
1. Configure -> Classes -> (class_name) -> 'Smart Class Parameter' tab.
2. Configure -> Smart Class Parameters.
=> Initial Draft of Smart Class Parameter TestCases

tests/foreman/ui/test_dashboard.py, tests/foreman/ui/test_user.py
please review it
thanks
$ flake8 test_user.py 
gives clean output
$ flake8 test_dashboard.py
gives clean output
=> Added test stubs for - user timezone and Dashboard UI

Makefile, tests/foreman/longrun/test_inc_updates.py
a) Marked the long running tests as tier4
b) Updated the needed changes in Makefile for tier4 testing.
=> Marked tests and Updated the needed changes for tier4 testing

robottelo/ui/locators.py, tests/foreman/ui/test_host.py
Setup part is working fine. However, we need to fixes `create` method for creating host via webUI. Selenium is unable to find elements which are not visible on screen. Planning to fix that in next PR as it requires extensive testing since there are so many tabs and options for host create from webUI.
=> Updated subnet, netmask and libvirthost settings as per new infra

docs/api/robottelo.ui.rst, docs/api/tests.foreman.ui.rst, robottelo/test.py, robottelo/ui/activationkey.py, robottelo/ui/base.py, robottelo/ui/factory.py, robottelo/ui/hostcollection.py, robottelo/ui/locators.py, tests/foreman/ui/test_activationkey.py, tests/foreman/ui/test_hostcollection.py
Closes #3252
```
nosetests tests/foreman/ui/test_hostcollection.py
..S.............
Ran 16 tests in 1013.353s
OK (SKIP=1)
```
=> Implement base interfaces and CRUD tests for host collection entity

tests/foreman/ui/test_contentview.py, tests/foreman/ui/test_repository.py, tests/foreman/ui/test_sync.py, tests/foreman/ui/test_syncplan.py
=> UI test stubs on ostree feature

tests/foreman/ui/test_classparameters.py
Adding more stubs for 'Smart Class Parameter' feature based on scenarios.
These are the final test stubs from my scenarios list.
Next PR: 
I will be adding stubs on bugs that I logged for this feature in upstream.
=> More stubs for Smart Class Parameters

tests/foreman/api/test_computeprofile.py
```
nosetests tests/foreman/api/test_computeprofile.py
.....
Ran 5 tests in 90.875s
OK
```
=> Adding CRUD tests for Compute Profile

tests/foreman/ui/test_host.py
A few basic tests around atomic hosts for now. Will add more once I get better idea what will be in next release.
=> Added few tests on atomic host

tests/foreman/api/test_bookmarks.py
Initial API CRUD test stubs for Bookmark entity.
=> Bookmarks - API - initial stubs for the API tests

robottelo/ui/base.py, robottelo/ui/sync.py
Fixing around 10 failures for test_user entity on UI. Issue is fixed after we scroll screen up, so necessary button is visible. Also, put few if-conditions on a proper level as there are no dependency between, for example, `authorized_by` and `locale` fields.
```
nosetests tests/foreman/ui/test_user.py
.SS......S....S...SSSSS.............S..SSSSS.............
Ran 57 tests in 4098.904s
OK (SKIP=15)
```
=> Fixing UI issues found on CI for test user entity

docs/api/tests.foreman.ui.rst, tests/foreman/ui/test_remoteexecution.py
The Remote Execution (Management) feature is currently confined to UI.
These initial test stubs are the current manual testing cases.
=> Add initial test stubs for Remote Execution

tests/foreman/cli/test_syncplan.py
Adding some Product synchronization via SyncPlan tests.
Main idea was to address [BZ1301909](https://bugzilla.redhat.com/show_bug.cgi?id=1301909) as well as improve coverage in general.
Similar to #3274, but for CLI.
=> Added some CLI SyncPlan synchronization tests

tests/foreman/ui/test_repository.py
=> Added UI test for deleting a puppet repo associated with a content view

robottelo/ui/discoveryrules.py, robottelo/ui/factory.py, tests/foreman/ui/test_discoveryrule.py
Closes #2491 
```
nosetests tests/foreman/ui/test_discoveryrule.py
.....S..................
Ran 24 tests in 1173.517s
OK (SKIP=1)
```
=> Increase test coverage for Discovery Rules for WebUI

Makefile
adding -s option to make test-foreman-rhai in Makefile
=> adding -s option to make test-foreman-rhai in Makefile

tests/foreman/api/test_syncplan.py, tests/foreman/cli/test_syncplan.py
These tests should basically target regression found in https://bugzilla.redhat.com/show_bug.cgi?id=1301909 or at least put basis for upcoming tests in that area
```
nosetests tests/foreman/api/test_syncplan.py -m test_positive_synchronize
..
Ran 2 tests in 266.362s
OK
```
=> Adding coverage for Product synchronization through SyncPlan procedure

tests/foreman/api/test_product.py
Closes #3303
```
nosetests tests/foreman/api/test_product.py
..............S
Ran 15 tests in 353.803s
OK (SKIP=1)
```
=> Increase test coverage for Product entity in API

tests/foreman/cli/test_classparameters.py
Few more stubs for sub-commands:
1. list
2. remove
3. value hiding
=> Some more CLI stubs into Smart Class Parameter

tests/foreman/ui/test_capsule.py
*) These are the initial test scenarios for the capsule mgmt ux.
*) Currently the tests scenarios are related to overiview, services
puppet, puppet-ca and pulp.
=> Added test-stubs for Capsule Management UX feature.

tests/foreman/ui/test_docker.py
=> Cover 1266842 BZ functionality

tests/foreman/api/test_classparameters.py
All and Final set of API stubs for Smart Class Parameter Feature.
Includes below sub-components :
1. List
2. Override
3. Puppet Default
4.  Parameter Type
5. Optional Validation
6. Validation
7. Matcher
8.  Outside Impact
9. Value Hiding
Thanks !
=> All API stubs for Smart Class Parameter Feature

robottelo/ui/base.py, robottelo/ui/operatingsys.py
Fixed operating system entity according to new approach
Part of #3308
```
nosetests tests/foreman/ui/test_operatingsystem.py
...S..........F...
FAIL: Update OS name, major_version, minor_version, os_family
Ran 18 tests in 1124.711s
FAILED (SKIP=1, failures=1)
```
```
nosetests tests/foreman/ui/test_operatingsystem.py -m test_positive_update
....
Ran 4 tests in 232.967s
OK
```
=> Improvement to click helper method to be able to handle elements directly

robottelo/constants.py, robottelo/ui/base.py, robottelo/ui/locators.py, robottelo/ui/login.py, robottelo/ui/navigator.py, robottelo/ui/repository.py, robottelo/ui/user.py, tests/foreman/ui/test_user.py
First fundamental fixes for new WebUI for 6.2. Current improvement should fix at least 42 tests.
All other modules are coming up.
```
nosetests tests/foreman/ui/test_user.py
.SS......S....S...SSSSS.............S.ESSSSS.............
ERROR: Delete an existing User
Ran 57 tests in 3382.800s
FAILED (SKIP=15, errors=1)
```
One failure is refer to Satellite 6.2 defect: https://bugzilla.redhat.com/show_bug.cgi?id=1314894
=> Add important fixes for WebUI for 6.2. Fix User tests.

Makefile, tests/foreman/rhai/test_rhai.py
adding try finally block to vm.get() in order to fetch the log files from VM irrespective of pass/fail of the tests.
=> adding try finally block to vm.get() in order to fetch the log files from VM

tests/foreman/api/test_repository.py, tests/foreman/ui/test_contentview.py
Update some test names to match the new naming convention.
=> Update test names

robottelo/ui/locators.py, robottelo/ui/products.py, robottelo/ui/repository.py, tests/foreman/api/test_syncplan.py, tests/foreman/cli/test_syncplan.py, tests/foreman/ui/test_syncplan.py
Similar to #3277 and #3274, UI part.
Closes #3276
=> Add UI SyncPlan synchronization tests

robottelo/ui/activationkey.py, robottelo/ui/contentviews.py, robottelo/ui/discoveryrules.py, robottelo/ui/domain.py, robottelo/ui/gpgkey.py, robottelo/ui/hosts.py, robottelo/ui/ldapauthsource.py, robottelo/ui/location.py, robottelo/ui/locators.py, robottelo/ui/medium.py, tests/foreman/ui/test_gpgkey.py
Part of #3329 
Part of #3308
I was able to run most of cases, but we still have a lot of new issues that are blocking successful run for our automation (at least #3331, #3333)
```
nosetests tests/foreman/ui/test_activationkey.py -m test_positive_create_with_name
.
Ran 1 test in 426.076s
OK
```
```
nosetests tests/foreman/ui/test_contentview.py -m test_positive_add_package_filter
.
Ran 1 test in 342.878s
OK
```
```
nosetests tests/foreman/ui/test_discoveryrule.py
.....F..................
FAIL: Create Discovery Rule with too long host limit value …
```
=> Fix more modules according to new select method in 6.2

robottelo/ui/locators.py, robottelo/ui/subnet.py, tests/foreman/ui/test_subnet.py
Closes #3338
```
nosetests tests/foreman/ui/test_subnet.py
....F.....
FAIL: Create new subnet with 255 characters in name
Ran 10 tests in 739.402s
FAILED (failures=1)
```
Part of #3308
=> Fixes Subnet entity for 6.2

tests/foreman/ui/test_variables.py
This includes all the Smart Variable UI stubs. This feature has all the functions similar to Smart Class Parameters but has its own added/removed functions, those are following:
1. Smart Variable can be created unlike Smart class parameters.
2. Override option is not available in Smart Variables.
3. 'Use Puppet Default' option is not supported in Smart Variables.
=> UI Stubs for Smart Variables

tests/foreman/cli/test_satellitesync.py, tests/foreman/ui/test_satellitesync.py
InterSatellite Sync UI and CLI stubs.
This covers most of the scenarios for ISS excluding Redhat content sync.
The stubs for Redhat contents inter satellite sync will be added in next PR.
=> InterSatellite Sync CLI and UI stubs

robottelo/ui/base.py, robottelo/ui/factory.py, robottelo/ui/hosts.py, robottelo/ui/locators.py, tests/foreman/longrun/test_oscap.py, tests/foreman/smoke/test_ui_smoke.py, tests/foreman/ui/test_host.py
Part of #3331
Part of #2916 
It is not possible to provide test results as host functionality still has few critical issues that blocking entire process.
Tested as much as I can in debug mode and proposed approach seems work as planned. There is a chance that code will require few fixes and updates once functionality will be accessible, but they will affect only some slight details
=> Re-implement framework methods for Host entity

robottelo/ui/base.py
Saw some UIError errors showing up due to unicode messages being used by our framework.
=> Fixing UIError exceptions due to unicoded messages.

robottelo/cli/proxy.py, robottelo/constants.py, robottelo/datafactory.py, tests/foreman/api/test_user.py, tests/foreman/ui/test_gpgkey.py, tests/foreman/ui/test_location.py, tests/foreman/ui/test_user.py, tests/robottelo/test_datafactory.py
Bz: https://bugzilla.redhat.com/show_bug.cgi?id=1144162
PR: https://github.com/theforeman/foreman/pull/2952
User creation is now accepting/enforcing utf-8 for fisrtname, lastname, login
=> Accepting utf-8 for user data

docs/api/robottelo.cli.rst, docs/api/tests.foreman.cli.rst, robottelo/cli/factory.py, robottelo/cli/usergroup.py, tests/foreman/cli/test_usergroup.py
Closes #3072 
```
nosetests tests/foreman/cli/test_usergroup.py
..............................
Ran 30 tests in 1488.954s
OK
```
=> Add coverage for user group entity in CLI

robottelo/constants.py
```
nosetests tests/foreman/ui/test_user.py -m test_positive_create_with_language
.
Ran 1 test in 122.996s
OK
```
=> Fix locale settings for user entity

robottelo/datafactory.py
* ~~repository auth does not allow utf8 credentials~~ (Allow but needs to be quoted)
* ~~url cannot be longer than 255~~  (Now it is allowing 1024)
* positive and negative auth tests passed locally
=> Repository URL limit increased to 1024 chars

tests/foreman/api/test_contentviewfilter.py, tests/foreman/cli/test_contentview.py, tests/foreman/cli/test_contentviewfilter.py, tests/foreman/ui/test_docker.py, tests/foreman/ui/test_hostcollection.py, tests/foreman/ui/test_user.py
Update the docstrings to match the new testimony expected format.
=> Update test docstrings

docs/api/tests.foreman.api.rst, tests/foreman/api/test_usergroup.py
Closes #3372
```
nosetests tests/foreman/api/test_usergroup.py
.................
Ran 17 tests in 184.778s
OK
```
=> Adding coverage for usergroup entity for API

robottelo/constants.py, tests/foreman/api/test_filter.py
```
nosetests tests/foreman/api/test_filter.py
...
Ran 3 tests in 10.427s
OK
```
Depends on https://github.com/SatelliteQE/nailgun/pull/273
=> Fixing Filter tests according to new API in 6.2

robottelo/cli/base.py, robottelo/cli/docker.py, tests/foreman/api/test_docker.py, tests/foreman/api/test_repository.py, tests/foreman/cli/test_docker.py, tests/foreman/data/hammer_commands.json, tests/foreman/smoke/test_api_smoke.py, tests/foreman/ui/test_docker.py
docker image was renamed to docker manifest
(Fixes #3381)
=> docker image was renamed to docker manifest

tests/foreman/api/test_hostcollection.py
```python
py.test -v tests/foreman/api/test_hostcollection.py
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1 -- /home/andrii/env/bin/python
collected 17 items 
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_negative_create_with_invalid_name PASSED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_add_host <- robottelo/decorators.py SKIPPED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCase::test_positive_add_hosts <- robottelo/decorators.py SKIPPED
tests/foreman/api/test_hostcollection.py::HostCollectionTestCas …
```
=> Update API Host Collection tests according to sat6.2 changes

tests/foreman/cli/test_import.py
test_positive_import_ak_default()
- https://bugzilla.redhat.com/show_bug.cgi?id=1325124
test_positive_import_chosts_default()
- https://bugzilla.redhat.com/show_bug.cgi?id=1325497
=> CLI Import - decorate for open bugs

robottelo/ui/base.py, robottelo/ui/locators.py, tests/foreman/ui/test_operatingsystem.py
```
nosetests tests/foreman/ui/test_operatingsystem.py
....S......F......
FAIL: Remove selected OS parameter
Ran 18 tests in 969.026s
FAILED (SKIP=1, failures=1)
nosetests tests/foreman/ui/test_operatingsystem.py -m test_positive_remove_parameter
.
Ran 1 test in 38.102s
OK
```
```
nosetests tests/foreman/ui/test_domain.py -m parameter
......
Ran 6 tests in 576.917s
OK
```
=> Fixing OS and Domain tests according to 6.2

robottelo/ui/factory.py, robottelo/ui/locators.py, robottelo/ui/user.py, robottelo/ui/usergroup.py, tests/foreman/ui/test_adusergroup.py, tests/foreman/ui/test_usergroup.py
```
nosetests tests/foreman/ui/test_usergroup.py
.......
Ran 7 tests in 1000.061s
OK
```
=> Fix user group issues for 6.2

tests/foreman/ui/test_remoteexecution.py
Add test cases specifically for provisioned hosts.
=> Expand Remote Execution test cases

tests/foreman/cli/test_satellitesync.py, tests/foreman/ui/test_satellitesync.py
This PR includes stubs for Redhat and mixed(Redhat+custom) contents import and export testcases.
Earlier added testcases/stubs were custom contents related stubs.
=> ISS stubs for Redhat Contents

robottelo/ui/locators.py, tests/foreman/ui/test_docker.py
Just stupid copy-paste issue introduced by me few weeks ago
=> Fix typo in locators for docker

robottelo/ui/hostcollection.py, robottelo/ui/locators.py, tests/foreman/ui/test_hostcollection.py
```python
py.test tests/foreman/ui/test_hostcollection.py -m tier3
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
collected 16 items 
tests/foreman/ui/test_hostcollection.py ..
======================== 14 tests deselected by "-m 'tier3'" =========================
===================== 2 passed, 14 deselected in 152.33 seconds ======================
```
=> Fixed UI Host Collection with Host association tests

robottelo/ui/navigator.py
Just very plausible idea on fixing our 'Docker browser' issue for user and probably some other functionality areas.
@abalakh performed all the testings on the local Docker containers interfaces. Seems that current fix helped to resolve our problem
Let's try to submit current PR and trigger the job on CI as we do not have consistent failures locally even without the fix
=> Fixing menu navigation procedure

robottelo/ui/activationkey.py, robottelo/ui/locators.py, tests/foreman/ui/test_activationkey.py
```
nosetests tests/foreman/ui/test_activationkey.py -m limit
......
Ran 6 tests in 893.233s
OK
```
=> Fixing UI part for Activations Key entity according to 6.2 GA

tests/foreman/data/hammer_commands.json
Closes #3439
```
nosetests tests/foreman/cli/test_hammer.py
.
Ran 1 test in 1810.676s
OK
```
=> Fixing hammer commands information according to GA fixes

robottelo/ui/locators.py, robottelo/ui/navigator.py
added waiter for navbar.spinner element to menu_click()
=> added waiter for navbar.spinner element to menu_click()

tests/foreman/data/hammer_commands.json
```
nosetests tests/foreman/cli/test_hammer.py
.
Ran 1 test in 2048.822s
OK
```
=> Update hammer commands information according to 6.2 GA

tests/foreman/api/test_puppetmodule.py
```
nosetests tests/foreman/api/test_puppetmodule.py
....
Ran 4 tests in 54.299s
OK
```
=> Fixing issues with puppet module functionality

robottelo/ui/template.py, tests/foreman/ui/test_template.py
```
nosetests tests/foreman/ui/test_template.py
...........
Ran 11 tests in 780.355s
OK
```
=> Fix provisioning template test cases according 6.2

tests/foreman/ui/test_setting.py
Thanks @abalakh for help with decorator idea
```
nosetests tests/foreman/ui/test_setting.py
..............S.............
Ran 28 tests in 729.562s
OK (SKIP=1)
```
=> Decorating issue for settings entity

robottelo/constants.py, robottelo/ui/locators.py, robottelo/ui/oscapcontent.py, robottelo/ui/oscappolicy.py, tests/foreman/ui/test_oscapcontent.py, tests/foreman/ui/test_oscappolicy.py
```
nosetests tests/foreman/ui/test_oscappolicy.py
S...
Ran 4 tests in 745.940s
OK (SKIP=1)
```
```
nosetests tests/foreman/ui/test_oscapcontent.py
S...
Ran 4 tests in 482.233s
OK (SKIP=1)
```
=> Fixing oscap related issues according to 6.2

tests/foreman/cli/test_syncplan.py
New regression happened - [BZ1336790](https://bugzilla.redhat.com/show_bug.cgi?id=1336790)
=> Skip CLI sync plan sync_date test according to open BZ

tests/foreman/ui/test_docker.py
Skipping all Docker Registry UI tests due to BZ 1338071
=> Skipping UI tests due to BZ 1333805

robottelo/ui/base.py, robottelo/ui/locators.py
Basically, it was problem with locator. Should fix both tests for locations and organizations
```
nosetests tests/foreman/ui/test_location.py -m test_positive_auto_search
.
Ran 1 test in 40.654s
OK
```
```
nosetests tests/foreman/ui/test_organization.py -m test_positive_search_autocomplete
.
Ran 1 test in 45.565s
OK
```
=> Fixing auto complete functionality for search operation

robottelo/constants.py, robottelo/ui/hosts.py, robottelo/ui/locators.py, tests/foreman/ui/test_host.py
Tests were failing since the start of Sat6.2 development. Applying various fixes to make them pass again.
Many thanks to @rplevka, @sghai and @sthirugn for help in debugging and configuring environment for `test_positive_create_libvirt`.
=> Various fixes for UI Host tests

robottelo/test.py
Fixes #3479 opened by @abalakh
=> Fix #3479 exception handler for session_user teardown

tests/foreman/ui/test_user.py
`Remote Execution` is optional plug-in for Satellite application, so it doesn't seem so critical to support testing roles for that feature
```
nosetests tests/foreman/ui/test_user.py -m all_roles
..
Ran 2 tests in 331.002s
OK
```
=> Remove roles related to remote execution feature from user test cases

robottelo/test.py
set default_organization to have faster login and dashboard load
=> Set default organization for admin users to address #3502

robottelo/ui/locators.py
```
nosetests tests/foreman/ui/test_product.py -m test_positive_delete
.
Ran 1 test in 228.070s
OK
```
=> Fix locator for product delete button

robottelo/ui/hostcollection.py
```
nosetests tests/foreman/ui/test_hostcollection.py -m test_positive_add_host
.
Ran 1 test in 86.286s
OK
nosetests tests/foreman/ui/test_hostcollection.py -m test_negative_hosts_limit
.
Ran 1 test in 125.276s
OK
```
=> Fix host collection test cases

robottelo/ui/container.py, robottelo/ui/contentviews.py, tests/foreman/api/test_docker.py, tests/foreman/cli/test_docker.py, tests/foreman/endtoend/test_ui_endtoend.py, tests/foreman/ui/test_docker.py
Fixed a bunch of issues with docker tests. Locally all the docker tests are passing (-53 failures)
On jenkins results should be the same after we solve #3508
=> Fix various issues with docker tests

tests/foreman/endtoend/test_api_endtoend.py, tests/foreman/endtoend/test_cli_endtoend.py, tests/foreman/endtoend/test_ui_endtoend.py
The RHEL repository should not be enabled if the `fake_manifest` is not set.
Update the end to end modules to reflect it.
Test results for API and CLI:
```
$ py.test tests/foreman/endtoend/test_api_endtoend.py
========================== test session starts ===========================
platform linux -- Python 3.4.3, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/elyezer/code/robottelo, inifile: 
plugins: xdist-1.14, cov-2.2.1
collected 7 items 
tests/foreman/endtoend/test_api_endtoend.py .......
======================= 7 passed in 106.30 seconds =======================
$ py.test tests/foreman/endtoend/test_cli_endtoend.py
========================== test session starts ===========================
platform linux -- Python 3.4.3, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: …
```
=> Skip RHEL repository enabling on end to end tests

robottelo/ui/activationkey.py, robottelo/ui/locators.py, tests/foreman/ui/test_activationkey.py
```
nosetests tests/foreman/ui/test_activationkey.py -m test_positive_add_host
.
Ran 1 test in 144.192s
OK
```
=> Fixes activation keys issues

robottelo/ui/base.py
Add more logger DEBUG info into UI form operations.
Now UI logs should log field content filling info like this:
```bash
17:06:44 - robottelo.ui.locators - DEBUG - Accessing locator "login.username" by id: "login_login"
17:06:44 - robottelo.ui.base - DEBUG - Filling field: login.username with: CgEWJZZrNB
17:06:45 - robottelo.ui.locators - DEBUG - Accessing locator "login.password" by id: "login_password"
17:06:45 - robottelo.ui.base - DEBUG - Filling field: login.password with: changeme
```
=> Add more debug log info into UI form operations

robottelo/test.py
It depends on nailgun PR https://github.com/SatelliteQE/nailgun/pull/298  to use Host search to get organization assigned hosts
```bash
py.test -s tests/foreman/api/test_host.py -k with_name
....
2016-06-03 13:43:59 - robottelo - DEBUG - Org 1073 can't be deleted as it has 1 hosts
2016-06-03 13:43:59 - robottelo - DEBUG - Cleanup deleted 1 entities
=== 1 passed, 44 deselected in 24.36 seconds ===
```
=> Clean only orgs with no hosts, using Host.search()

robottelo/constants.py
```
nosetests tests/foreman/api/test_permission.py
.......
Ran 7 tests in 341.445s
OK
```
=> Fixing permissions for snap14.1

robottelo/test.py
Before cleaning up the Orgs.
- reassign hosts to default_org
- reassign host groups to default org
```bash
py.test -s tests/foreman/api/test_hostgroup.py -k create_with_lce
=== 1 passed, 39 deselected in 23.19 seconds ===
```
=> Before deleting orgs, assign its hostgroup and hosts to default_org

robottelo/ui/locators.py
Test  ~~in progress~~ completed
=> Fix new gpg key locator

tests/foreman/data/hammer_commands.json
The changes are tested in $jenkins/job/satellite6-standalone-automation/120.
The failures in this job are valid bugs and are being tracked in:
https://bugzilla.redhat.com/show_bug.cgi?id=1343551
https://bugzilla.redhat.com/show_bug.cgi?id=1344095
https://bugzilla.redhat.com/show_bug.cgi?id=1344096
=> Fix hammer commands as per recent snap

robottelo/test.py
With multithreading it is becoming very difficult to identify the tests looking
a the robottelo logs.  This improves the logging by adding more useful logs.
CLI test:
```
2016-06-09 15:47:31 - robottelo - DEBUG - Started setUpClass: ActivationKeyTestCase
...
...
2016-06-09 15:47:37 - robottelo - DEBUG - Started Test: ActivationKeyTestCase/test_positive_create_with_name
...
2016-06-09 15:47:43 - robottelo - DEBUG - Finished Test: ActivationKeyTestCase/test_positive_create_with_name
...
2016-06-09 15:47:43 - robottelo - DEBUG - Started tearDownClass: ActivationKeyTestCase
2016-06-09 15:47:43 - robottelo - DEBUG - Cleanup got 0 entities to update
2016-06-09 15:47:43 - robottelo - DEBUG - Cleanup got 0 entities to update
2016-06-09 …
```
=> Improving logging for tests

robottelo/cli/subscription.py, robottelo/ui/subscription.py
Original BZ1339696 had been closed, BZ1340229 was opened instead.
=> Update BZ ids for manifest upload

tests/foreman/api/test_discoveryrule.py, tests/foreman/api/test_permission.py, tests/foreman/api/test_puppetmodule.py, tests/foreman/longrun/test_inc_updates.py, tests/foreman/ui/test_bookmark.py
Add missing super().setUp() calls to fix #3534
=> Add missing super() calls to setUp to #fix 3534

tests/foreman/data/hammer_commands.json
```python
py.test tests/foreman/cli/test_hammer.py -k 'test_positive_all_options'
platform linux2 -- Python 2.7.10, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
collected 1 items 
============================ 1 passed in 2922.24 seconds =============================
```
=> Update hammer commands according to recent changes

robottelo/ui/locators.py, robottelo/ui/packages.py, tests/foreman/ui/test_packages.py
```
nosetests tests/foreman/ui/test_packages.py
...
Ran 3 tests in 218.705s
OK
```
=> Add more coverage for packages UI

tests/foreman/cli/test_operatingsystem.py
Closes #3396 
```python
py.test tests/foreman/cli/test_operatingsystem.py -k 'test_positive_search or test_negative_delete_by_id'
platform linux2 -- Python 2.7.10, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
collected 15 items 
tests/foreman/cli/test_operatingsystem.py ...
=== 12 tests deselected by '-ktest_positive_search or test_negative_delete_by_id' ====
====================== 3 passed, 12 deselected in 75.69 seconds ======================
```
=> Add test for CLI OS search by title

robottelo/cli/template.py, tests/foreman/api/test_template.py, tests/foreman/cli/test_template.py
Closes #1547
```
nosetests tests/foreman/api/test_template.py -m test_positive_clone
.
Ran 1 test in 13.040s
OK
```
```
nosetests tests/foreman/cli/test_template.py -m test_positive_clone
.
Ran 1 test in 18.203s
OK
```
Depends on https://github.com/SatelliteQE/nailgun/pull/300
=> Add coverage for provisioning templates cloning functionality

tests/foreman/api/test_template.py
```
nosetests tests/foreman/api/test_template.py -m test_positive_clone
.
Ran 1 test in 13.528s
OK
```
=> Quick fix for template cloning procedure

robottelo/cli/hostcollection.py, tests/foreman/cli/test_host_collection.py, tests/foreman/data/hammer_commands.json
```
nosetests tests/foreman/cli/test_hammer.py -m test_positive_all_options
.
Ran 1 test in 2032.416s
OK
```
```
nosetests tests/foreman/cli/test_host_collection.py -m test_positive_list_hosts
.
Ran 1 test in 89.932s
OK
```
=> Fixes functionality related to host collection hosts sub-command in CLI

robottelo.properties.sample, robottelo/cleanup.py, robottelo/config/settings.py, robottelo/test.py
- Cleanup is now disabled by default
- All the logic was moved in to cleanup.py module (because in the future when bugs are fixed it may be useful again)
=> Cleanup is disabled by default, all logic moved out to cleanup.py

tests/foreman/endtoend/test_api_endtoend.py, tests/foreman/endtoend/test_cli_endtoend.py, tests/foreman/endtoend/test_ui_endtoend.py, tests/foreman/endtoend/utils.py, tests/foreman/longrun/test_inc_updates.py, tests/foreman/longrun/test_oscap.py, tests/foreman/performance/test_candlepin_concurrent_delete.py, tests/foreman/performance/test_candlepin_concurrent_subscription_ak.py, tests/foreman/performance/test_candlepin_concurrent_subscription_attach.py, tests/foreman/performance/test_pulp_sync.py, tests/foreman/performance/test_standard_prep.py, tests/foreman/rhai/test_rhai.py, tests/foreman/rhai/test_rhai_client.py, tests/foreman/rhci/test_rhci.py
Pass the right values to the Testimony tokens.
=> Fix test docstrings

robottelo/constants.py
```
nosetests tests/foreman/api/test_permission.py
.......
Ran 7 tests in 363.620s
OK
```
=> Add one more permission to the list

tests/foreman/api/test_docker.py, tests/foreman/cli/test_docker.py
```python
py.test tests/foreman/api/test_docker.py tests/foreman/cli/test_docker.py -k 'test_positive_pull_image or test_positive_upload_image or test_positive_create_with_external_registry'
platform linux2 -- Python 2.7.10, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
collected 96 items 
tests/foreman/api/test_docker.py .
tests/foreman/cli/test_docker.py ...
92 tests deselected by '-ktest_positive_pull_image or test_positive_upload_image or test_positive_create_with_external_registry' 
===================== 4 passed, 92 deselected in 229.09 seconds ======================
```
=> Implement CLI and API docker stubs

robottelo/constants.py, robottelo/ui/factory.py, robottelo/ui/locators.py, robottelo/ui/user.py, tests/foreman/ui/test_user.py
```
nosetests tests/foreman/ui/test_user.py
..............................S..SSSS..............
Ran 51 tests in 2664.197s
OK (SKIP=5)
```
=> Refactor and add coverage for user entity

robottelo/ui/locators.py, robottelo/ui/sync.py
```
nosetests tests/foreman/ui/test_sync.py
S.S.
Ran 4 tests in 273.604s
OK (SKIP=2)
```
=> Fixing sync entity locators

robottelo/constants.py
```
nosetests tests/foreman/ui/test_user.py -m test_positive_set_timezone
.
Ran 1 test in 60.197s
OK
```
=> Fix timezone constant

robottelo/ui/activationkey.py, robottelo/ui/locators.py, tests/foreman/ui/test_activationkey.py
```
nosetests tests/foreman/ui/test_activationkey.py -m test_positive_delete_manifest
.
Ran 1 test in 94.608s
OK
```
=> Fix delete manifest from activation key test

robottelo/cli/factory.py, tests/foreman/cli/test_hostgroup.py
Closes #3591 
I see some issues when creating hostgroup via hammer. So based on those issues, new tests have been added. They are currently blocked by bz's.
=> Implemented some hostgroup tests based on known bugs

tests/foreman/ui/test_user.py
Could not reproduce the bug but have written 2 test stubs asserting the correct behavior.
=> Create test stub for bz 1354572

tests/foreman/endtoend/test_api_endtoend.py
Also set maxDiff to None in order to get full diff when a failure happens.
=> Update API end to end URLs

tests/foreman/ui/test_hostcollection.py
Closes #3622 
```python
py.test tests/foreman/ui/test_hostcollection.py::HostCollectionPackageManagementTest -v
platform linux2 -- Python 2.7.10, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /home/andrii/env/bin/python
collecting ... collected 5 items
tests/foreman/ui/test_hostcollection.py::HostCollectionPackageManagementTest::test_positive_install_package PASSED
tests/foreman/ui/test_hostcollection.py::HostCollectionPackageManagementTest::test_positive_install_package_group PASSED
tests/foreman/ui/test_hostcollection.py::HostCollectionPackageManagementTest::test_positive_remove_package PASSED …
```
=> Implement UI host collection remote package management tests

robottelo/decorators/host.py, robottelo/helpers.py, setup.py, tests/robottelo/decorators/test_host.py
Discussion on  #3610 originated this changes
Close #3605 
@rochacbruno  @elyezer can you guys check it, once you were on original discussion?
=> Refactored decorators.host

tests/foreman/data/hammer_commands.json
Fixes #3633 
2016-07-21 18:46:58 - robottelo - DEBUG - Finished Test: HammerCommandsTestCase/test_positive_all_options
========================= 1 passed in 4004.04 seconds ==========================
=> Added new cli options to hammer_commands.json

docs/api/robottelo.ui.rst, robottelo/test.py, robottelo/ui/base.py, robottelo/ui/factory.py, robottelo/ui/job_template.py, robottelo/ui/locators.py, robottelo/ui/navigator.py, tests/foreman/ui/test_remoteexecution.py
```
nosetests tests/foreman/ui/test_remoteexecution.py
........SSSSSS..
Ran 16 tests in 326.166s
OK (SKIP=6)
```
=> Add coverage for job templates functionality

tests/foreman/cli/test_contentview.py, tests/foreman/cli/test_docker.py
=> Skipped all tests related to cv update by bz id 1359665

docs/Makefile, robottelo/cli/host.py, robottelo/cli/hostgroup.py, tests/foreman/api/test_environment.py, tests/foreman/api/test_hostgroup.py, tests/foreman/api/test_smartproxy.py
Also fix docstrings in order to get a documentation build 100% working.
Close 3587
=> Fail travis build if building docs raise warnings

docs/api/robottelo.decorators.rst, docs/api/robottelo.rst, docs/features/decorators.rst, docs/features/index.rst, docs/index.rst, robottelo/decorators/host.py
Close: #3674
stubbed, skip_if_bug_open and skip_if_os were documented
Created a new section "Features" on documentation to
describe features from a high level point of view
=> Documented robottelo decorators

tests/foreman/ui/test_host.py
Closes #3643
```
nosetests tests/foreman/ui/test_host.py
S.FS.SSSSSS.S
FAIL: Create a new Host on libvirt compute resource
Ran 13 tests in 431.825s
FAILED (SKIP=9, failures=1)
```
Libvirt test case is still failing. Tried to investigate, but seems problem is configuration one. More details here - https://github.com/SatelliteQE/robottelo/issues/3661
=> Make host tests more robust

docs/api/robottelo.ui.rst, robottelo/test.py, robottelo/ui/hosts.py, robottelo/ui/job.py, robottelo/ui/locators.py, robottelo/ui/navigator.py, tests/foreman/endtoend/test_ui_endtoend.py, tests/foreman/longrun/test_oscap.py, tests/foreman/ui/test_remoteexecution.py
Closes#3624
```
nosetests tests/foreman/ui/test_remoteexecution.py
............SSS..
Ran 17 tests in 1121.663s
OK (SKIP=3)
```
=> Add more coverage for remote execution feature

tests/foreman/cli/test_host_collection.py
Closes #3676
Test Result:
12 tests deselected by '-k HostCollectionTestCase and test_positive_host_collection_host_pagination' 
================== 1 passed, 12 deselected in 151.92 seconds ===================
Process finished with exit code 0
=> Added automated test for host_collection pagination on hammer

tests/foreman/ui/test_computeresource_rhev.py
Addition of new module for rhev compute resource testcases.
Addition of rhev test class to incorporate rhev compute resource testcases.
Addition of several stubs for compute resource of type rhev.
=> Addition of test_computeresource_rhev.py module with rhev CR stubs

robottelo/cli/contentview.py, robottelo/constants.py, tests/foreman/longrun/test_inc_updates.py
1) Fixed the test logic itself to make it work at all
2) Separate setup procedure per test to make tests isolated
3) Finds smaller repository for incremental update procedure and find proper package, so we can install errata for it
Decreased overall execution time from ~6000 seconds to ~560 seconds
```
nosetests tests/foreman/longrun/test_inc_updates.py
..
Ran 2 tests in 555.803s
OK
```
=> Fixing incremental update tests logic and use smaller repo for sync

docs/features/decorators.rst, docs/features/index.rst, docs/features/ssh.rst
=> Added documentation about ssh module

robottelo/helpers.py, robottelo/ssh.py, tests/robottelo/test_ssh.py
=> Made ssh.get_connection public

docs/index.rst
=> Add gcc requirements

tests/foreman/cli/test_variables.py
Write stubs for Smart Variables CLI in robotello.
=> Stubs for Smart Variables CLI closes #3678

tests/foreman/data/hammer_commands.json
Added new `admin` subcommand. 
Test result:
```
/home/qui/code/robottelo/venv2/bin/python /usr/share/java/pycharm-community/helpers/pycharm/pytestrunner.py -p pytest_teamcity /home/qui/code/robottelo/tests/foreman/cli/test_hammer.py "-k HammerCommandsTestCase and test_positive_all_options"
Testing started at 2:33 PM ...
platform linux2 -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/qui/code/robottelo, inifile: 
plugins: cov-2.3.1, xdist-1.14
========================= 1 passed in 2470.68 seconds ==========================
=> Update list of hammer commands.

docs/api/robottelo.ui.rst, robottelo/constants.py, robottelo/test.py, robottelo/ui/contenthost.py, robottelo/ui/errata.py, robottelo/ui/locators/base.py, robottelo/ui/locators/common.py, robottelo/ui/locators/tab.py, tests/foreman/ui/test_contenthost.py, tests/foreman/ui/test_errata.py, tests/foreman/ui/test_hostcollection.py
=> Implement UI errata tests

robottelo/constants.py, robottelo/decorators/host.py, robottelo/host_info.py, tests/robottelo/decorators/test_host.py, tests/robottelo/test_host_info.py
closes #3698
Refactoring:
Host information unified on host_info
=> Repos loaded accordingly to sat version

robottelo/constants.py, robottelo/ui/hostgroup.py, robottelo/ui/locators/base.py, robottelo/ui/navigator.py, tests/foreman/longrun/test_oscap.py
Waiting for https://github.com/SatelliteQE/robottelo/issues/3698 to be implemented
```
nosetests tests/foreman/longrun/test_oscap.py
.
Ran 1 test in 771.578s
OK
```
=> Fix tier4 OSCAP test

tests/foreman/cli/test_contentview.py
Implemented 
* Update a composite content-view with --component-ids option
* Remove content-view version from composite-view
Test results: 
helgie$ py.test tests/foreman/cli/test_contentview.py -k test_positive_remove_version_by_id_from_composite
========= test session starts =========
platform darwin -- Python 2.7.10, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /Users/helgie/robottelo, inifile: 
plugins: cov-2.3.0, xdist-1.14
collected 52 items 
tests/foreman/cli/test_contentview.py .
======= 51 tests deselected by '-k test_positive_remove_version_by_id_from_composite' ========== 1 passed, 51 deselected in 96.82 seconds 
helgie$ py.test tests/foreman/cli/test_contentview.py -k test_positive_update_composite_with_component_ids
========= test session starts ==========
platform darwin -- …
=> Should fix #3600 : added 2 more CV-related tests

docs/api/tests.foreman.ui.rst, tests/foreman/ui/test_computeresource_openstack.py
Addition of new module for openstack compute resource testcases.
Addition of openstack test class to incorporate openstack compute resource testcases.
Addition of several stubs for compute resource of type openstack.
=> Addition of test_computeresource_openstack.py module with openstack CR stubs

tests/foreman/ui/test_contentview.py
OSTree Content-view tests with RH Contents.
=> Added few more tests with RH ostree repo

docs/api/tests.foreman.api.rst, tests/foreman/api/test_variables.py
41 API stubs for Smart Variables feature.
=> API stubs for Smart Variables feature

docs/api/tests.foreman.ui.rst, tests/foreman/ui/test_computeresource_rhev.py
Added some formatting
1. A empty line after @steps 
2. caseautomation => Caseautomation 
3. Added entry in docs rst file to generate documentation.
=> Added some formatting to stubs and added entry in rst to create docs

robottelo/cli/factory.py, robottelo/cli/repository.py, robottelo/constants.py, tests/foreman/cli/test_repository.py
=> 3728 repo dw policy cli

robottelo/cli/base.py, robottelo/test.py, tests/foreman/cli/test_activationkey.py, tests/robottelo/test_cli.py
close #3716
Improved:
CLIReturnError setting Exception message attribute. See #3717
=> Negative test_activationkey.py improved with error msg assertions

tests/foreman/cli/test_user.py
close #3733
Missing only default roles which need more info
Refactored test which depends on only one user to
UserTestWithCleaningUp so user got deleted on tearDown
Refactored also Roles so they are created and destroyed
on once for all tests
=> Automated Tests regarding user roles

tests/foreman/api/test_contentview.py, tests/foreman/api/test_repository.py
Test results:
```console
robottelo]$ py.test -v tests/foreman/api/test_contentview.py::OstreeContentViewTestCase
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.5, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
rootdir: /home/sghai/QE/robottelo, inifile: 
plugins: cov-2.3.1, xdist-1.15.0
collected 4 items 
tests/foreman/api/test_contentview.py::OstreeContentViewTestCase::test_positive_add_custom_ostree_content <- robottelo/decorators/__init__.py PASSED
tests/foreman/api/test_contentview.py::OstreeContentViewTestCase::test_positive_promote_custom_ostree PASSED
tests/foreman/api/test_contentview.py::OstreeContentViewTestCase::test_pos …
```
=> Added tests around custom, RH ostree repo, sync and cv publish, promote via api

docs/api/tests.foreman.ui.rst, tests/foreman/ui/test_computeresource_vmware.py
1. Added new module for stubs of vmware testcases
2. Edited the rst file , to support documentation for newly created file.
=> Addition of test_computeresource_vmware.py module with vmware CR stubs

robottelo/config/base.py
=> Added return validation_errors on FakeCapsuleSettings

robottelo/constants.py
close #3757
6.2.z branch must contain only 6.2 sat repos
=> Set Up Sat 6.2 REPOS and REPOSET

tests/foreman/api/test_user.py
close #3750
Problem solved with conditional until name change
affects all sat versions current under test
=> Anonymous changed to Default role in upstream

docs/api/robottelo.cli.rst, robottelo/cli/factory.py, robottelo/cli/host.py, robottelo/cli/hostgroup.py, robottelo/cli/smart_variable.py, tests/foreman/cli/test_variables.py
```
nosetests tests/foreman/cli/test_variables.py
..SSSS....S..S......SSSSS.................S......
Ran 48 tests in 648.574s
OK (SKIP=12)
```
=> Adding coverage for Smart Variable functionality in CLI

robottelo.properties.sample, robottelo/config/base.py, tests/foreman/ui/test_host.py
- Includes two tests around atomic host
a) Provision atomic host on libvirt
b) delete provisioned atomic host
Since kickstart installer for atomic is not available via CDN so defined a setting in properties file. Will update the jenkins with this change.
`Test results:`
```console
robottelo]$ py.test -v  tests/foreman/ui/test_host.py::AtomicHostTestCase -k test_positive_delete_atomic_host
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.5, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
rootdir: /home/sghai/QE/robottelo, inifile: 
plugins: cov-2.3.1, xdist-1.15.0
collected 7 items …
```
=> Tests around Atomic host Provisioning on external libvirt

robottelo/ui/contentviews.py, robottelo/ui/locators/base.py
Tested both on downstream and upstream builds:
```
nosetests tests/foreman/ui/test_contentview.py -m test_positive_promote_with_custom_content
.
Ran 1 test in 144.838s
OK
```
Needs also be merged into 6.2.z
=> Fixing locator for CV publish

tests/foreman/data/hammer_commands.json
backporting from - https://github.com/SatelliteQE/robottelo/pull/3807
=> updated hammer command tree (#3807)

robottelo/cli/base.py, tests/robottelo/test_cli.py
=> Created different classes of CLI errors

robottelo/ui/computeresource.py, robottelo/ui/locators/base.py, tests/foreman/ui/test_computeresource_rhev.py
nosetests tests.foreman.ui.test_computeresource_rhev
```
..S.....SSSS...
Ran 15 tests in 615.541s
OK (SKIP=5)
```
=> Automated tier1 and tier2 tests for compute resource rhev

tests/foreman/cli/test_contentview.py
test results:
```console
robottelo]$ py.test -v tests/foreman/cli/test_contentview.py::OstreeContentViewTestCase -k ostree
================================================================ test session starts =================================================================
platform linux2 -- Python 2.7.5, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
rootdir: /home/sghai/QE/robottelo, inifile: 
plugins: cov-2.3.1, xdist-1.15.0
collected 4 items 
tests/foreman/cli/test_contentview.py::OstreeContentViewTestCase::test_positive_add_custom_ostree_content <- robottelo/decorators/__init__.py PASSED
tests/foreman/cli/test_contentview.py::OstreeContentViewTestCase::test_positive_promote_custom_ostree PASSED
tests/foreman/cli/test_contentview.py::OstreeContentViewTestCase …
```
=> Added content-view publish, promote with custom ostree and RH atomic content tests

docs/api/tests.foreman.cli.rst, tests/foreman/api/test_discoveredhost.py, tests/foreman/api/test_discoveryrule.py, tests/foreman/cli/test_discoveryrule.py, tests/foreman/ui/test_discoveredhost.py, tests/foreman/ui/test_discoveryrule.py
- Added test stubs based on changes/bug fixes in discovery7.0
- Added all tests for discovery-rules from CLI
=> Added stubs for discovery7.0 feature from UI/CLI/API

.travis.yml, Makefile, robottelo/test.py
Backporting Makefile rules that gathers log files from automation.
=> Add log-related tasks to Makefile.

tests/robottelo/test_cli.py
=> Increased coverage over base cli

tests/foreman/api/test_variables.py, tests/foreman/cli/test_variables.py
Depends on SatelliteQE/nailgun#315
```
% nosetests tests/foreman/api/test_variables.py
.....S..S..SSSSSS........S............SSSSS
Ran 43 tests in 114.762s
OK (SKIP=14)
```
=> Implemented tests for Smart Variables

tests/foreman/installer/test_infoblox.py, tests/foreman/ui/test_capsule.py
=> Created stubs for Infoblox plugin

tests/foreman/api/test_classparameters.py
```
% nosetests tests/foreman/api/test_classparameters.py
SSSS.............SSSSSS.....S..S..............
Ran 46 tests in 105.130s
OK (SKIP=12)
```
=> Quickfix for API/Smart Class Parameters.

Makefile
`make can-i-push?`
It will check flake8, docstrings, uuids and also run test-robottelo
run
`make install-commit-hook`  
> NOTE:  run the above this only once! it will write contents to `.git/hooks/pre-commit` locally
And then the checks will be automatically fired before each commit and you dont have to run it manually.
=> Added "make can-i-push?" and "make install-commit-hook"

robottelo/ui/factory.py, robottelo/ui/locators/base.py, robottelo/ui/settings.py, tests/foreman/ui/test_setting.py
Closes #3837 
```
nosetests tests/foreman/ui/test_setting.py
............................
Ran 28 tests in 708.118s
OK
```
=> Fix settings page coverage for 6.3

tests/foreman/api/test_role.py, tests/foreman/cli/test_role.py, tests/foreman/ui/test_role.py
Test Stubs for Satellite 6.3 feature Canned Role Org Admin
For all forms,
UI,
CLI,
API
They are 40 stubs for all forms.
=> Test Stubs for 6.3 feature Canned Role

docs/api/tests.foreman.ui.rst, tests/foreman/ui/test_computeresource_azure.py
Added some test stubs for tier1, tier2 , tier3
Added the new file to rst to create documentation.
=> Addition of test_computeresource_azure.py module with azure CR stubs

robottelo/ui/contentviews.py, robottelo/ui/locators/base.py, tests/foreman/ui/test_contentview.py
```
nosetests tests/foreman/ui/test_contentview.py -m positive_delete
....
Ran 4 tests in 582.663s
OK
```
=> Fix Content View Version functionality for 6.3

Makefile, docs/api/tests.foreman.rst, docs/api/tests.foreman.sys.rst, tests/foreman/sys/test_hot_backup.py
Closes #3809
-Hotbackup test stubs
-New directory for system tests (tests/foreman/sys) see #3804
-Required .rst files for docs
=> HotBackup Tests stubs and sys directory

tests/foreman/ui/test_ansible.py
The feature is not fully ready yet and so test cases are written with lot of assumptions.  Once more info about this feature is available and testable, the test cases will be updated accordingly.
=> Initial set of test stubs for Ansible integration

robottelo/test.py
cherry-picking: https://github.com/SatelliteQE/robottelo/pull/3884
=> logging - added py.test worker information to the log

robottelo/api/utils.py, tests/foreman/api/test_classparameters.py, tests/foreman/api/test_variables.py, tests/foreman/cli/test_classparameters.py, tests/foreman/cli/test_variables.py, tests/foreman/ui/test_variables.py
Sometitimes it was not possible to remove puppet class because it was associated with hosts/hostgroups, however these testcases depend on puppet class state. Closes #3863
Changes:
* Improved tearDownClass methods
* Updated CLI/SmartVariables tests according to changes in 6.3
* Updated CLI/SmartClassParameters tests according to changes in 6.3
TearDown in CLI uses nailgun and API calls for several reasons:
1. Looks like it is not possible to delete specific puppet class from host/hostgroup using hammer. Asking on #theforeman I've found that it is possible only to replace old list of classes wih new list which doesn't include class that should be removed using `host/hostgroup update`. But in case of empty list this is does not work.
2. Due to opend BZ `hostgroup update` does not work in …
=> Improved tearDown methods for SmartClass/SmartVariables tests.

docs/api/tests.foreman.cli.rst, tests/foreman/cli/test_oscap.py
Added stubs for Oscap-cli hammer plugin
Tier1, Tier2, Tier3 stubs added.
Added the new test_oscap cli test module to rst file , to generated documentation
=> Oscap CLI hammer plugin tests stubs

robottelo/cli/factory.py, tests/foreman/cli/test_remoteexecution.py
Test results:
```
nosetests tests/foreman/cli/test_remoteexecution.py:RemoteExecutionTestCase
...
Ran 3 tests in 118.839s
OK
```
=> tests for hammer job-invocation, fixes #3822

tests/foreman/ui/test_errata.py
* The `nested` from `contextlib` is not available anymore on Python 3. And, basically, as we do not support python2.6 we don't need `nested`at all so i've removed it.
Closes #3726
* Implemented another stub, although it appears to be blocked by a BZ.
=> Added another UI errata test and fixed compatibility with Python 3

robottelo/constants.py, robottelo/ui/base.py, robottelo/ui/factory.py, robottelo/ui/locators.py, robottelo/ui/repository.py, tests/foreman/ui/test_repository.py
- UI improvements
- Logging improvements
- Download Policy test cases
=> Cherry Pick - UI tests for download policy to 6.2.z

robottelo/ui/computeresource.py, robottelo/ui/locators/base.py, tests/foreman/ui/test_computeresource_rhev.py
Added single power function to power on/off vm's across compute resources.
Added relevant testcases for compute resource of type RHEV.
Removed the previous implementation of power functions.
=> Fixes issue #3754, added support for handling power status in computeresource.py

robottelo/constants.py, robottelo/datafactory.py, robottelo/test.py, robottelo/ui/locators/model.py, robottelo/ui/my_account.py, tests/foreman/ui/test_myaccount.py, tests/foreman/ui/test_user.py, tests/robottelo/test_datafactory.py
close #3862
Test results:
```console
tests/foreman/ui/test_myaccount.py ssssss.....
=================== 5 passed, 6 skipped in 1131.85 seconds =======================
```
=> Implemented positive ui.test_myaccount.py tests

robottelo/constants.py, robottelo/decorators/__init__.py, robottelo/ssh.py, tests/foreman/sys/test_hot_backup.py
- Automated 3 cases
- Waiting to resolve #3905 
- Waiting to clarify FAQs from feature
[6.3 feature is in "back burner" right now, but I want to merge those 3 cases automated and then in future when we got back to 6.3 I can continue on this]
=> Hot Backup Automation

tests/foreman/api/test_puppet.py, tests/foreman/cli/test_puppet.py, tests/foreman/longrun/test_puppet_upgrade.py, tests/foreman/ui/test_puppet.py
[stub] Puppet scenario tests and Puppet4 upgrade tests
- API, CLI, UI variants of puppet test scenario
- Puppet upgrade tests for Satellite/Capsule
=> [stub] Puppet scenario tests and Puppet4 upgrade tests

tests/foreman/cli/test_import.py
=> [6.1.z cherrypick] decorating chost-related tests due to BZ#1238247

tests/foreman/cli/test_import.py
=> [6.2.z cherrypick] decorating chost-related tests due to BZ#1238247

tests/foreman/cli/test_import.py
addresses https://github.com/SatelliteQE/robottelo/issues/3964
=> decorating chost-related tests due to BZ#1238247

robottelo/test.py
=> fixes #3979 - wrong logic in the TestCase logger setup causes duplicate messages

robottelo/libvirt_discovery.py, robottelo/ui/discoveredhosts.py, robottelo/ui/locators/base.py, tests/foreman/ui/test_discoveredhost.py
Implemented following tests:
- test_positive_pxe_less_multi_nic_with_dhcp_unattended
- test_positive_pxe_multi_nic_unattended
- test_positive_refresh_facts_pxe_less
- test_positive_reboot
- test_positive_update_default_org
Fixed:
- test_positive_delete_multiple
- few other changes around `libvirt_discovery.py`
=> Implemented discovered host tests from UI with helper funtions and fixed existing tests

robottelo/helpers.py, robottelo/system_facts.py, scripts/graph_entities.py, scripts/hammer_command_tree.py, scripts/lint.py
New version of flake8 is out -- new errors are found :)
=> Make travis happy again.

tests/foreman/ui/test_contentview.py
```bash
============================================== 203 passed in 0.73 seconds ==============================================
"!!! Congratulations your changes are good to fly, make a great PR! dlezz++ !!!"
(2.7) dlezz@elysion:~/projects/robottelo-fork$ py.test tests/foreman/ui/test_contentview.py -v -k 'test_positive_clone_within_diff_env'
platform linux2 -- Python 2.7.12, pytest-3.0.3, py-1.4.31, pluggy-0.4.0 -- /home/dlezz/bin/redhat/python/2.7/bin/python
plugins: cov-2.4.0, xdist-1.15.0
collected 64 items 
tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_clone_within_d …
```
=> #3586-UI-CV-est_positive_clone_within_diff_env

tests/foreman/cli/test_host.py
=> Automated host listing its own errata

robottelo/ui/locators/base.py, tests/foreman/ui/test_contentview.py
Issue https://github.com/SatelliteQE/robottelo/issues/3586
=> #3586-UI-CV-test_positive_publish_version_changes_in_target-source_env

robottelo/constants.py
```bash
$ nosetests -m test_positive_search test_permission.py 
...
Ran 3 tests in 256.669s
OK
```
=> fixes #4006 - permission constants need to be updated

robottelo/ui/discoveredhosts.py, tests/foreman/ui/test_discoveredhost.py
Some comments were given earlier on PR #3935. However PR got closed by other reviewers so just incorporated those comments here. Please take a look if it looks good now.
=> Addressed comments given in PR #3935

robottelo/libvirt_discovery.py, robottelo/ui/discoveredhosts.py, robottelo/ui/locators.py, tests/foreman/ui/test_discoveredhost.py
Cherry-picked the commit from master that includes some fixes around discovery tests and new tests implemented around discovered host. There were some comments given after PR got merged.
I'll raise another PR later to fix those comments but would like to have these changes merged in 6.2.z branch first.
=> [6.2.z] implemented discovered host tests from UI with helper funtions and fixed existing tests

robottelo.properties.sample, robottelo/cli/discoveredhost.py, robottelo/cli/factory.py, robottelo/config/base.py, robottelo/constants.py, tests/foreman/cli/test_discoveredhost.py
Sorry for delay with that PR. Functionality requires a lot of testing, debugging and investigating different materials.
```
nosetests tests/foreman/cli/test_discoveredhost.py
SSSSS...S....SSSS
Ran 17 tests in 1754.933s
OK (SKIP=10)
```
=> Add more coverage for Discovery feature

robottelo.properties.sample, robottelo/config/base.py, robottelo/decorators/__init__.py, tests/robottelo/test_decorators.py
closes #4045
Before merging this, I have to add BZ configuration on jenkins.
[Edit]
Configuration added: https://github.com/SatelliteQE/robottelo-ci/pull/421. PR good to go.
=> Bugzilla credentials moved to config

tests/foreman/api/test_architecture.py
=> Skip invalid_name test because of BZ 1401519

tests/foreman/ui/test_contentview.py
```bash
"!!! Congratulations your changes are good to fly, make a great PR! dlezz++ !!!"
```
issue: #1938
=> Adding content view version removal stubs

tests/foreman/api/test_contentview.py
Closes #3934
```
nosetests tests/foreman/api/test_contentview.py
...............................E..........SS.S.......
ERROR: test suite for <class 'tests.foreman.api.test_contentview.ContentViewRedHatOstreeContent'>
---------------------------------------------------------------------
Ran 52 tests in 2009.239s
FAILED (SKIP=3, errors=1)
```
One failure is not connected to committed code, but more to environment itself
All necessary Nailgun PRs already merged
Two stubs that are left related to destructive testing and has very low priority, so closing the issue
=> Implement more stubs for CV

tests/foreman/cli/test_repository.py, tests/foreman/ui/test_repository.py
Add stubs for git puppet repositories. Part of issue #400. Cherry-pick of #4062
=> [6.2.z] Cherry-pick - Add stubs for git puppet repositories. (#4062)

tests/foreman/api/test_contentviewversion.py, tests/foreman/cli/test_contentview.py
same tests stubs as for UI PR #4071 of issue #1938
=> #1938-Adding content view version removal stubs

robottelo.properties.sample, robottelo/config/settings.py, robottelo/decorators/__init__.py, robottelo/host_info.py, tests/foreman/cli/test_host.py, tests/robottelo/test_decorators.py, tests/robottelo/test_host_info.py
=> [Cherry pick to 6.2.z] Improved skip_if_bz logic

robottelo/ui/locators/model.py
```bash
(2.7) dlezz@elysion:~/projects/robottelo-fork$ py.test tests/robottelo/test_ui_locators.py -v -k "LocatorTestCase"
platform linux2 -- Python 2.7.12, pytest-3.0.3, py-1.4.31, pluggy-0.4.0 -- /home/dlezz/bin/redhat/python/2.7/bin/python
plugins: cov-2.4.0, xdist-1.15.0
collected 24 items 
tests/robottelo/test_ui_locators.py::LocatorTestCase::test_add_new_locator_node_by_attr PASSED
tests/robottelo/test_ui_locators.py::LocatorTestCase::test_add_new_locator_node_by_attr_using_tuple PASSED
tests/robottelo/test_ui_locators.py::LocatorTestCase::test_add_new_locator_node_by_key PASSED …
```
=> Fix LocatorValue unicode issue #4072

docs/api/robottelo.ui.rst, docs/api/tests.foreman.ui.rst, robottelo/test.py, robottelo/ui/locators/base.py, robottelo/ui/locators/tab.py, robottelo/ui/puppetmodule.py, tests/foreman/ui/test_puppetmodule.py
Closes #3496 
Adding basic coverage that can be expanded in future (however not sure what scenarios can be added)
```
nosetests tests/foreman/ui/test_puppetmodule.py
...
Ran 3 tests in 100.951s
OK
```
=> Add coverage for Puppet Module content search functionality

robottelo/constants.py
```
nosetests tests/foreman/api/test_permission.py
.......
Ran 7 tests in 417.109s
OK
```
=> Fix permissions list according to new build

robottelo/ui/base.py, robottelo/ui/domain.py, robottelo/ui/locators/common.py, tests/foreman/ui/test_domain.py
Fix issue with locator for error message
Bonus: Some refactoring according to our code style
```
nosetests tests/foreman/ui/test_domain.py
..........S
Ran 11 tests in 515.690s
OK (SKIP=1)
```
=> Fix domain issue with error message

robottelo/config/settings.py, robottelo/decorators/__init__.py, tests/robottelo/test_decorators.py
close #4235
(cherry picked from commit 27a3cec)
=> [6.2.z]Ignored flags if bz section is not present on robottelo.properties

robottelo/config/base.py
=> (easiest review ever)Ignored flags if bz section is not present on robottelo.properties 

tests/foreman/api/test_contentviewversion.py
```bash
"!!! Congratulations your changes are good to fly, make a great PR! dlezz++ !!!"
(2.7) dlezz@elysion:~/projects/robottelo-fork$ py.test tests/foreman/api/test_contentviewversion.py -v -k "test_positive_remove_cv_version_from_multi_env or test_positive_remove_cv_version_from_env or test_positive_remove_prod_promoted_cv_version_from_default_env or test_positive_remove_qe_promoted_cv_version_from_default_env or test_positive_remove_renamed_cv_version_from_default_env or test_positive_delete_cv_promoted_to_multi_env"
platform linux2 -- Python 2.7.12, pytest-3.0.3, py-1.4.31, pluggy-0.4.0 -- /home/dlezz/bin/redhat/python/2.7/bin/python
rootdir: …
```
=> #4101-API-Implement CV version removal

Makefile, scripts/fix_uuids.sh, tests/foreman/cli/test_hostgroup.py, tests/foreman/ui/test_contenthost.py, tests/foreman/ui/test_hostcollection.py, tests/foreman/ui/test_remoteexecution.py, tests/foreman/ui/test_repository.py
=> [6.2.z] pulled Makefile from master

robottelo/constants.py
Closes #4158
Closes #4159 
```
nosetests tests/foreman/api/test_permission.py
.......
Ran 7 tests in 347.064s
OK
```
=> Fix api permissions according 6.2.7

tests/foreman/data/hammer_commands.json
=> [6.2.z] Update Hammer options for new additions

robottelo/ui/factory.py, robottelo/ui/hostgroup.py, robottelo/ui/locators/base.py, tests/foreman/ui/test_hostgroup.py
Closes #4171 
Added a test case to show the working of functionality.
=> Added support to add oscap capsule to Hostgroup isuue #4171

tests/foreman/cli/test_repository.py, tests/foreman/ui/test_repository.py
Connected to #4040 
Closes #4154
=> [6.2.z]ostree repo type shouldn't be checked for rhel6

robottelo/libvirt_discovery.py
generate a standalone wrapper function since the gen_mac is being used on multiple places across the Class
```python
In [4]: host = LibvirtGuest(extra_nic = True)
In [5]: host.create()
2017-01-17 15:50:58 - robottelo.ssh - INFO - Instantiated Paramiko client 0x7f3c13fe5750
2017-01-17 15:50:58 - robottelo.ssh - DEBUG - Connected to [libvirt1.com]
2017-01-17 15:50:58 - robottelo.ssh - DEBUG - >>> virt-install --hvm --network=bridge:downstream_el6 --mac=8e:22:2c:9f:15:76 --name=mac8e222c9f1576.satellite.com --ram=1024 --vcpus=1 --os-type=linux --os-variant=rhel7 --disk path=/var/lib/libvirt/images/mac8e222c9f1576.satellite.com.img,size=8 --noautoconsole --pxe --network=bridge:downstream_el6 --mac=c6:3b:39:5c:a7:5b
2017-01-17 15:51:01 - robottelo.ssh - DEBUG - <<< stdout
Starting install... …
```
=> productize _gen_mac_for_libvirt()

docs/api/robottelo.ui.rst, robottelo/test.py, robottelo/ui/my_account.py, tests/foreman/ui/test_user.py
Cover corresponding BZ
```
nosetests tests/foreman/ui/test_user.py -m test_positive_create_with_multiple_roles_and_login
.
Ran 1 test in 67.315s
OK
```
=> Add coverage for BZs 1392513/1399840

.mention-bot
trying to fix by forcing the requestPotentialReviewers and
removing the auto creation of review requests.
=> Mention bot is not working since the addition of this config

robottelo/cli/subscription.py, robottelo/ui/locators.py, robottelo/ui/subscription.py
Closes #4206 
Putting correct BZ id and fixing regression with locator
```
nosetests tests/foreman/ui/test_subscription.py 
.
Ran 1 test in 136.512s
OK
```
```
nosetests tests/foreman/cli/test_subscription.py -m test_positive_manifest_upload
.
Ran 1 test in 96.777s
OK
```
=> [High]Fixing subscription issue from UI/CLI side

robottelo/libvirt_discovery.py
a cherry-pick of https://github.com/SatelliteQE/robottelo/pull/4175
=> [6.2.z] Making the attach_nic work on a running domain

robottelo/libvirt_discovery.py
cherry-pick of https://github.com/SatelliteQE/robottelo/pull/4175
=> [6.1.z] Making the attach_nic work on a running domain

tests/foreman/api/test_hostcollection.py
```
nosetests tests/foreman/api/test_hostcollection.py -m test_positive_list
..
Ran 2 tests in 37.335s
OK
```
=> Test coverage around host collection list for api (BZ 1331875)

tests/foreman/ui/test_remoteexecution.py
=> updtated provider type for UI rex test (run custom job template)

docs/api/robottelo.ui.rst, robottelo/test.py, robottelo/ui/dashboard.py, robottelo/ui/locators/base.py, tests/foreman/ui/test_dashboard.py
```
nosetests tests/foreman/ui/test_dashboard.py
SSSSSSSSSSSSSSSSSSS.S.SSS
Ran 25 tests in 44.119s
OK (SKIP=23)
```
=> Test coverage around dashboard (BZ 1391365)

tests/foreman/cli/test_import.py
6.2 Cherrypick of PR https://github.com/SatelliteQE/robottelo/pull/4168
=> [6.2.z] Before CV reimport wait for publish

tests/foreman/cli/test_import.py
6.1 Cherrypick of PR https://github.com/SatelliteQE/robottelo/pull/4168
=> [6.1.z] Before CV reimport wait for publish

tests/foreman/ui/test_host.py
Cherry pick for https://github.com/SatelliteQE/robottelo/pull/3766
Didn't have right process in place in Aug
=> [High]Fix typo for host ui tests

.coveragerc, requirements.txt, robottelo/performance/stat.py
=> [6.2.z] Numpy should not be a requirement Fix #4247

.coveragerc, requirements.txt, robottelo/performance/stat.py
=> [6.1.z] Numpy should not be a requirement Fix #4247

tests/foreman/ui/test_packages.py
https://bugzilla.redhat.com/show_bug.cgi?id=1384673
Test is skipped because of BZ 1394390 but it is possible to run it with workaround, so test results with passed test:
```python
% pytest -v tests/foreman/ui/test_packages.py -k 'check_custom'
===================================================================== test session starts =====================================================================
platform linux2 -- Python 2.7.12, pytest-3.0.4, py-1.4.31, pluggy-0.4.0 -- /home/qui/code/venv/2/bin/python2
rootdir: /home/qui/code/robottelo, inifile: 
plugins: xdist-1.15.0, html-1.12.0, cov-2.4.0
collected 6 items 
tests/foreman/ui/test_packages.py::PackagesTestCase::test_positive_check_custom_package_details PASSED …
```
=> Automate BZ 1384673

docs/api/tests.foreman.ui.rst, robottelo/ui/locators.py, tests/foreman/ui/test_login.py, tests/foreman/ui/test_navigation.py
Current PR already showed great value by find out an error in basic navigation locator
```
nosetests tests/foreman/ui/test_navigation.py
.S
Ran 2 tests in 192.053s
OK (SKIP=1)
```
=> [6.2.z]Add sanity test for navigation functionality and cover BZ1394974

robottelo/vm.py
a) This is required to provision a capsule for testcases which
requires DNS resolution both via sat6 and the provisioned vm's.
b) With this change we would need to provide both hostname and
domain, while creating the vm instance.
c) Then we can use DDNS so that sat6 too can resolve the VM's
on the ginger host.
=> Added support to provision using separate target_image and hostname

.mention-bot
Hopefully this will avoid the mentions people are receiving for this branch.
=> Add mention-bot blacklist for the 6.2.z branch

robottelo/constants.py, robottelo/ui/factory.py, robottelo/ui/locators.py, robottelo/ui/template.py, tests/foreman/ui/test_template.py
BZ should be fixed in 6.2.8. It will be interesting to test the fix right away
```
nosetests tests/foreman/ui/test_template.py
.....S......
Ran 12 tests in 407.125s
OK (SKIP=1)
```
=> Add coverage for BZ1386334 and improved provisioning template logic

robottelo/constants.py, robottelo/ui/base.py, robottelo/ui/factory.py, robottelo/ui/locators/base.py, robottelo/ui/locators/tab.py, robottelo/ui/template.py, tests/foreman/ui/test_template.py
```
nosetests tests/foreman/ui/test_template.py
............
Ran 12 tests in 503.896s
OK
```
=> [Cherry-pick]Add coverage for BZ1386334

robottelo/constants.py, robottelo/decorators/__init__.py, tests/robottelo/test_decorators.py
=> Fix RHBugzilla instantiation as new version requires url to be passed

robottelo/bz_helpers.py, tests/foreman/conftest.py, tests/robottelo/test_bz_helpers.py
renamed helper
added proper docstring
added DEFERRED as resolution to be removed
=> Fix #4347 exclude DEFERRED resolution from test collection

robottelo/vm.py
```console
(sat-6.2.z) dlezz@elysion:~/projects/robottelo-fork$ py.test tests/foreman/cli/test_host.py -v -k "KatelloAgentTestCase" 
platform linux2 -- Python 2.7.13, pytest-2.9.2, py-1.4.32, pluggy-0.3.1 -- /home/dlezz/.pyenv/versions/sat-6.2.z/bin/python
plugins: cov-2.3.1
collected 40 items 
2017-02-17 11:46:45 - conftest - DEBUG - Found WONTFIX in decorated tests ['1269196', '1103157', '1156555', '1230902', '1245334', '1204686', '1267224', '1226425', '1217635', '1079482', '1214312']
2017-02-17 11:46:45 - conftest - DEBUG - Collected 40 test cases …
```
=> [6.2.z][cherry-pick] VirtualMachine with custom hostname and domain

tests/foreman/cli/test_lifecycleenvironment.py
with lifecycle_environments_count = 19 and without  per_page
```console
(2.7) dlezz@elysion:~/projects/robottelo-fork$  py.test tests/foreman/cli/test_lifecycleenvironment.py -v -k "test_positive_list_all_with_per_page"
====================================================== test session starts =======================================================
platform linux2 -- Python 2.7.12, pytest-3.0.6, py-1.4.31, pluggy-0.4.0 -- /home/dlezz/bin/redhat/python/2.7/bin/python2.7
plugins: xdist-1.15.0, cov-2.3.1
collected 12 items 
2017-02-16 11:35:43 - conftest - DEBUG - Found WONTFIX in decorated tests ['1269196', '1245334', '1217635', '1226425', '1156555', '1204686', '1267224', '1103157', '1230902', '1214312', '1079482'] …
```
=> [6.3][chery-pick]-add-bug-coverage-1420503

robottelo/vm.py
issue: https://github.com/SatelliteQE/robottelo/issues/4372
The main idea is to not rewrite the initialization arguments, as they are needed in all virtual machine life usage.
python console log without hostname: http://pastebin.test.redhat.com/457666
python console log with hostname: http://pastebin.test.redhat.com/457667
```console
(sat-6.2.z) dlezz@elysion:~/projects/robottelo-fork$ py.test tests/foreman/cli/test_host.py -v -k "KatelloAgentTestCase" 
platform linux2 -- Python 2.7.13, pytest-2.9.2, py-1.4.32, pluggy-0.3.1 -- /home/dlezz/.pyenv/versions/sat-6.2.z/bin/python
plugins: cov-2.3.1 …
```
=> [6.2.z] fix image not destroyed at provisioning server when using custom hostname

tests/foreman/api/test_product.py
https://bugzilla.redhat.com/show_bug.cgi?id=1389543
```python
pytestrunner.py -p pytest_teamcity tests/foreman/api/test_product.py "-k ProductTestCase and test_positive_sync"
Testing started at 8:12 PM ...
2017-02-21 20:12:01 - conftest - DEBUG - Registering custom pytest_namespace
platform linux2 -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/qui/code/robottelo, inifile: 
plugins: xdist-1.14, cov-2.3.1
collected 16 items
====== 15 tests deselected by '-k ProductTestCase and test_positive_sync' ======
=================== 1 passed, 15 deselected in 37.80 seconds ===================
=> Automate BZ 1389543

tests/foreman/api/test_product.py
Cherry-picked from #4373
https://bugzilla.redhat.com/show_bug.cgi?id=1389543
```python
% py.test -v tests/foreman/api/test_product.py -k "sync" 
===================================================================== test session starts =====================================================================
platform linux2 -- Python 2.7.12, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /home/qui/code/venv/6.2.z/bin/python2
2017-02-24 14:50:50 - conftest - DEBUG - Collected 17 test cases
tests/foreman/api/test_product.py::ProductTestCase::test_positive_sync PASSED
tests/foreman/api/test_product.py::ProductTestCase::test_positive_sync_several_repos PASSED
=============================================================== 15 tests deselected by '-ksync' …
```
=> [6.2.z] Cherry-pick - Automate BZ 1389543

tests/foreman/cli/test_hostgroup.py
```python
% py.test -v tests/foreman/cli/test_hostgroup.py -k 'update_puppet or update_multiple' 
===================================================================== test session starts =====================================================================
platform linux2 -- Python 2.7.12, pytest-2.9.2, py-1.4.32, pluggy-0.3.1 -- /home/qui/code/venv/2/bin/python2
collected 30 items 
2017-02-24 20:00:59 - conftest - DEBUG - Found WONTFIX in decorated tests ['1269196', '1245334', '1217635', '1226425', '1156555', '1204686', '1267224', '1103157', '1230902', '1214312', '1079482']
2017-02-24 20:00:59 - conftest - DEBUG - Collected 30 test cases
tests/foreman/cli/test_hostgroup.py::HostGroupTestCase::test_positive_update_multiple_puppet_classes PASSED …
```
=> Automate 1264163

robottelo/ui/base.py, robottelo/ui/dashboard.py, robottelo/ui/locators/base.py, robottelo/ui/locators/common.py, tests/foreman/ui/test_dashboard.py
+16 tests
```
nosetests tests/foreman/ui/test_dashboard.py
.S.S..S...SS.....S..S....
Ran 25 tests in 1010.052s
OK (SKIP=7)
```
=> Add test coverage for Dashboard entity

robottelo/datafactory.py, tests/foreman/api/test_host.py, tests/robottelo/test_datafactory.py
https://bugzilla.redhat.com/show_bug.cgi?id=1285669
* Implement CRUDs for API Host interface and cover BZ1285669
* Added status code assertion for negative tests and small stylish changes
=> [6.2.z] [Cherry-pick] Implemented CRUDs for API Host interface and covered BZ1285669 (#4336)

robottelo/ui/hosts.py, robottelo/ui/locators/base.py, robottelo/ui/locators/tab.py, tests/foreman/ui/test_errata.py
```
nosetests tests/foreman/ui/test_errata.py:FilteredErrataTestCase
.
Ran 1 test in 1162.573s
OK
```
=> Add test coverage for filtered errata functionality (BZ1368254)

robottelo/vm.py
issue: #4372 
and issue: https://github.com/SatelliteQE/robottelo/issues/4386
python console log without hostname: http://pastebin.test.redhat.com/459804
python console log with hostname: http://pastebin.test.redhat.com/459808
original PR on 6.2.z branch: https://github.com/SatelliteQE/robottelo/pull/4364
=> [6.3][cherry-pick]fix image not destroyed at provisioning server when using custom hostname

tests/foreman/cli/test_host.py
Related to bz1420671 https://bugzilla.redhat.com/show_bug.cgi?id=1420671
raised in issue #4324 
Currently skipped as the bug is the new state
=>  [6.2.z] apply security erratum to client, bz#1420671

robottelo/api/utils.py, robottelo/constants.py, robottelo/ui/locators/base.py, tests/foreman/longrun/test_oscap.py
Fixed a delete locator for oscap report.
Added a test case to cover https://bugzilla.redhat.com/show_bug.cgi?id=1420439
=> Fixes issue #4323, bugzilla automation long-run oscap testcase added.

tests/foreman/cli/test_remoteexecution.py
=> fix setUpClass in remote execution CLI tests

Makefile
Make sure to run flake8 only on .py files
=> Update can-i-push? make target

docs/api/robottelo.ui.rst, robottelo/test.py, robottelo/ui/base.py, robottelo/ui/dashboard.py, robottelo/ui/locators.py, tests/foreman/ui/test_dashboard.py
```
nosetests tests/foreman/ui/test_dashboard.py
.S.S..S...SS.....S..S....
Ran 25 tests in 654.286s
OK (SKIP=7)
```
=> Migrating Dashboard code into 6.2

Makefile
Also fix help text for make help.
=> Add token-prefix-editor make target

robottelo/ui/dashboard.py, tests/foreman/ui/test_dashboard.py
```
nosetests tests/foreman/ui/test_dashboard.py
.S.S..S...SS......S..S....
Ran 26 tests in 806.176s
OK (SKIP=7)
```
=> Add coverage for BZ1361793

robottelo/ui/dashboard.py, tests/foreman/ui/test_dashboard.py
```
nosetests tests/foreman/ui/test_dashboard.py -m test_positive_rendering_after_env_removed
.
Ran 1 test in 62.374s
OK
```
=> [Cherry-pick]Coverage for BZ1361793

robottelo/vm.py
cherry-pick of https://github.com/SatelliteQE/robottelo/commit/3726b805a6b9ec6c17febfd76c95bb7edd6f8eb0
- without the workaround
=> [6.2.z][cherrypick] add goferd service check to katello_agent_install()

docs/api/tests.foreman.installer.rst, docs/api/tests.foreman.longrun.rst, docs/api/tests.foreman.rhai.rst, docs/api/tests.foreman.upgrade.rst, tests/foreman/api/test_host.py, tests/foreman/cli/test_host.py, tests/foreman/ui/test_capsule.py, tests/foreman/ui/test_host.py
Also improve some docstrings of host tests.
=> Add missing api docs

tests/foreman/cli/test_remoteexecution.py
- use internal/CDN Tools according to cdn setting
(addresses #4429 for master)
=> REX: Use internal/CDN Tools appropriately

tests/foreman/cli/test_remoteexecution.py
- use internal/CDN Tools according to cdn setting
(addresses #4429 for 6.2.z)
=> [6.2.z] REX: Use internal/CDN Tools appropriately

robottelo/vm.py
cherry-pick of: https://github.com/SatelliteQE/robottelo/commit/3726b805a6b9ec6c17febfd76c95bb7edd6f8eb0
=> [6.1.z][cherrypick] add goferd service check to katello_agent_install()

robottelo/ui/dashboard.py, robottelo/ui/locators/base.py, robottelo/ui/locators/common.py, tests/foreman/ui/test_dashboard.py
```
nosetests tests/foreman/ui/test_dashboard.py -m test_positive_content_host_subscription_status
.
Ran 1 test in 421.973s
OK
```
=> Adding coverage for Content Hosts Subscription status widget in Dashboard (BZ1405524)

robottelo/ui/dashboard.py, robottelo/ui/locators.py, tests/foreman/ui/test_dashboard.py
Basically, cannot provide results as katello-agent is not starting properly at that moment
=> [Cherry-pick]Adding coverage for CHS status widget in Dashboard (BZ1180573)

tests/foreman/cli/test_remoteexecution.py
Related to #4402 
Backporting improvements suggested by reviewers in pr #4421 to the code added to 6.2.z in pr #4408
=> [6.2.z] improved checking job invocation output

robottelo/ui/locators.py, tests/foreman/ui/test_dashboard.py
```
nosetests tests/foreman/ui/test_dashboard.py -m test_positive_user_access_with_host_filter
.
Ran 1 test in 29.361s
OK
```
=> [Cherry pick] Coverage for Errata Widget

tests/foreman/ui/test_gpgkey.py
```
nosetests tests/foreman/ui/test_gpgkey.py
.......SS....S......S....S.S....S.S....
Ran 39 tests in 3588.641s
OK (SKIP=8)
```
=> Skip tests because of defect

tests/foreman/cli/test_hostgroup.py
seems some lines was missed from last automatic changes, Travis mark all PRs as failed because of this
=> [6.2.z] correct missing token from @Assert: to @expectedresults:

tests/foreman/data/hammer_commands.json
=> Update Hammer options for new additions

robottelo/ssh.py, robottelo/test.py
some tuning regarding log levels
=> tuning logging levels

robottelo/ssh.py, robottelo/test.py
cherry-picking dc6bd708d620796dd9d0cbc1517a0f310d8cfb8f form master
=> [6.2.z] tuning logging levels (#4530)

docs/api/robottelo.ui.rst, robottelo/cli/factory.py, robottelo/test.py, robottelo/ui/locators/base.py, robottelo/ui/locators/menu.py, robottelo/ui/navigator.py, robottelo/ui/scparams.py, tests/foreman/api/test_classparameters.py, tests/foreman/cli/test_classparameters.py, tests/foreman/ui/test_classparameters.py
```
nosetests tests/foreman/ui/test_classparameters.py
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS..SSSSSSSSSSSSSSS
Ran 57 tests in 186.862s
OK (SKIP=55)
```
```
nosetests tests/foreman/cli/test_classparameters.py -m test_positive_list_with_non_admin_user
.
Ran 1 test in 160.771s
OK
```
```
nosetests tests/foreman/api/test_classparameters.py -m test_positive_list_with_non_admin_user
.
Ran 1 test in 87.613s
OK
```
=> Cover interaction with smart class parameters using non admin user

robottelo.properties.sample, robottelo/ui/browser.py
I tested the new support of Microsoft Edge and it works on SauceLabs
So this PR Add missing `edge` support to saucelabs
=> [6.2.z] Add missing `edge` support to saucelabs

tests/foreman/installer/test_installer.py
Cherry pick from PR #4469
Test result on 6.3:
```
nosetests tests/foreman/installer/test_installer.py
...
Ran 3 tests in 36.466s
OK
```
=> [6.3] cherry-pick updates to test_installer.py

tests/foreman/cli/test_remoteexecution.py, tests/foreman/ui/test_remoteexecution.py
=> add rex capsule to subnet

tests/foreman/cli/test_remoteexecution.py, tests/foreman/ui/test_remoteexecution.py
Cherry pick from #4528 
Related to issue  #4501
=> 6.3 cherry-pick add rex capsule to subnet

robottelo/vm.py
http://pastebin.test.redhat.com/470695
This PR is necessary if we want to change the constants content and to not break the tests
=> fix vm to use by default the distro constants

robottelo/ui/locators/base.py, robottelo/ui/scparams.py, tests/foreman/ui/test_classparameters.py
```
nosetests tests/foreman/ui/test_classparameters.py
....SS..S.S....S.......SS.SS..S......S.S.SS.......
Ran 50 tests in 1982.254s
OK (SKIP=14)
```
=> Added basic coverage for Smart Class Parameters for UI (part1)

docs/api/tests.foreman.ui.rst, tests/foreman/ui/test_computeresource_ec2.py
Added stubs for tier1 , tier2 and tier3 test cases for EC2 Compute resource
=> Added stubs/testcases for compute resource of type EC2

robottelo/ui/base.py
Fixes #4560.
See https://github.com/SatelliteQE/robottelo/pull/4565#issuecomment-294938174 for test results.
=> Fix #4560 / Handle unicode locators if element not found

docs/api/robottelo.ui.rst, robottelo/cli/factory.py, robottelo/test.py, robottelo/ui/locators.py, robottelo/ui/navigator.py, robottelo/ui/scparams.py, tests/foreman/api/test_classparameters.py, tests/foreman/cli/test_classparameters.py, tests/foreman/ui/test_classparameters.py
```
nosetests tests/foreman/ui/test_classparameters.py
....SS..S.S....S.......SS.SS..S......S.S.SS.......
Ran 50 tests in 1366.779s
OK(SKIP=14)
```
=> [cherry-pick] Smart Class Parameters Implementation for UI

tests/foreman/ui/test_docker.py
Previous BZ was for 6.2.z branch, updating with 6.3 clone
=> Updated BZ id for ui docker test

tests/foreman/cli/test_host.py
original PR https://github.com/SatelliteQE/robottelo/pull/4538
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1385814
```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test -v tests/foreman/cli/test_host.py::KatelloAgentTestCase::test_positive_register_host_ak_with_host_collection
============================================================== test session starts ===============================================================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.32, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
plugins: xdist-1.15.0, services-1.1.14, cov-2.4.0
collected 11 items 
2017-04-20 19:35:51 - conftest - DEBUG - Found WONTFIX in decorated tests …
```
=> [6.3][cherry-pick] qe_test_coverage_1438798

tests/foreman/ui/test_remoteexecution.py
Related to  issue #4402
Cherry pick from PR #4430
Testing is currently prevented by https://bugzilla.redhat.com/show_bug.cgi?id=1406315
=> [6.3] cherry-pick UI get job-invocation ouput with asserts

tests/foreman/cli/test_host.py
Cherry picking from #4406
Related to issue  #4324
Sadly, testing is prevented by https://bugzilla.redhat.com/show_bug.cgi?id=1406315 just raising the PR so that I don't forget about it later.
NTS: squash later, or clone the bz for 6.3 depending on the test result
=> 6.3 cherry pick test cve apply

tests/foreman/cli/test_host.py
=> Fix wrong Assert token

robottelo/ui/my_account.py, tests/foreman/ui/test_myaccount.py
close #4602
Test results:
```console
tests/foreman/ui/test_myaccount.py ssssss.....
========================================================== 0 tests deselected ===========================================================
================================================= 5 passed, 6 skipped in 828.85 seconds =================================================
(robottelo) [renzo@note robottelo]$ 
```
=> Refactored ui/test_myaccount.py

tests/foreman/sys/test_hot_backup.py
Automating https://bugzilla.redhat.com/show_bug.cgi?id=1323607
Related issue #4607
Please also note the 6.2 cherry-pick
=> katello-backup test exit status

tests/foreman/ui/test_role.py
https://bugzilla.redhat.com/show_bug.cgi?id=1315580
```python
py.test tests/foreman/ui/test_role.py -k test_positive_create_filter_admin_user_with_locs
platform darwin -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
plugins: xdist-1.15.0, services-1.1.14, cov-2.3.1
collected 23 items
2017-04-27 15:50:01 - conftest - DEBUG - Found WONTFIX in decorated tests ['1110476', '1269196', '1378009', '1245334', '1221971', '1217635', '1226425', '1156555', '1199150', '1204686', '1267224', '1103157', '1230902', '1214312', '1079482']
2017-04-27 15:50:01 - conftest - DEBUG - Collected 23 test cases
tests/foreman/ui/test_role.py .
============================= 22 …
```
=> Automate BZ1315580

tests/foreman/sys/test_hot_backup.py
Automating https://bugzilla.redhat.com/show_bug.cgi?id=1323607
Related issue #4607
=> [cherry-pick] 6.2 katello-backup test exit status

tests/robottelo/ui/test_location.py
close #4592
Coverage decreased on #4643
=> Increased coverage on ui.Location.create

robottelo/decorators/func_locker.py, tests/robottelo/test_func_locker.py
- Locked function name resolved properly in any classes and ensure to be the same 
lock decorator with the with context manager 
- When using the with context manager to try to make locking of not locked function it raise exception.
- unittest covered
=> [6.2.z] locked function name resolved in any class

tests/foreman/sys/test_hot_backup.py
Cherry pick from #4640 
Tracked in issue #4456
One test skipped due to https://bugzilla.redhat.com/show_bug.cgi?id=1447619
```
py.test tests/foreman/sys/test_hot_backup.py -k negative
========================================= test session starts ==========================================
platform linux2 -- Python 2.7.11, pytest-2.9.2, py-1.4.33, pluggy-0.3.1
rootdir: /home/pondrejk/Documents/robottelo, inifile: 
plugins: xdist-1.15.0, services-1.1.14, html-1.10.0, cov-2.3.1
collected 18 items 
2017-05-03 12:47:07 - conftest - DEBUG - Found WONTFIX in decorated tests ['1110476', '1156555', '1269196', '1402826', '1245334', '1221971', '1217635', '1226425', '1199150', '1204686', '1267224', '1103157', '1230902', '1214312', '1079482']
2017-05-03 12:47:07 - conftest - DEBUG - Collected 18 test …
```
=> [6.2] cherry-pick katello-backup basic negative tests

robottelo/cli/recurring_logic.py, tests/foreman/cli/test_remoteexecution.py
Related to issue #4300 
Tests:
```
nosetests -v tests/foreman/cli/test_remoteexecution.py:RemoteExecutionTestCase.test_positive_run_job_effective_user
Run default job template as effective user against a single host ... ok
nosetests -v tests/foreman/cli/test_remoteexecution.py:RemoteExecutionTestCase.test_positive_run_default_job_template_multiple_hosts
Run default job template against multiple hosts ... ok
nosetests -v tests/foreman/cli/test_remoteexecution.py:RemoteExecutionTestCase.test_positive_install_multiple_packages_with_a_job
Run job to install several packages on host ... ok
nosetests -v tests/foreman/cli/test_remoteexecution.py:RemoteExecutionTestCase.test_positive_run_recurring_job_with_max_iterations
Run default job template multiple times with max iteration ... ok
```
=> more cli rex tests

robottelo.properties.sample, robottelo/api/utils.py, robottelo/config/settings.py, robottelo/constants.py, robottelo/libvirt_discovery.py, robottelo/ui/discoveredhosts.py, robottelo/ui/discoveryrules.py, robottelo/ui/factory.py, robottelo/ui/locators.py, tests/foreman/ui/test_discoveredhost.py, tests/foreman/ui/test_discoveryrule.py
Discovery tests have been failing since long w/ zstream jobs.. This PR should fix all of them. I tried to pull changes/enhancements from master and those are relevant to zstream. 
These  changes not only fix the existing tests but also allow us to expand the coverage.
=> Fixed discovery tests

tests/foreman/sys/test_hot_backup.py
Related to issue #4638
and bug https://bugzilla.redhat.com/show_bug.cgi?id=1445989
Interestingly, tests pass, so this check probably isn't bullet-proof, in this case the second backup is still smaller than the first one:
```py.test tests/foreman/sys/test_hot_backup.py -k incremental
========================================== test session starts ==========================================
platform linux2 -- Python 2.7.11, pytest-2.9.2, py-1.4.33, pluggy-0.3.1
rootdir: /home/pondrejk/Documents/robottelo, inifile: 
plugins: xdist-1.15.0, services-1.1.14, html-1.10.0, cov-2.3.1
collected 14 items 
2017-05-05 14:32:08 - conftest - DEBUG - Found WONTFIX in decorated tests ['1110476', '1269196', '1378009', '1245334', '1221971', '1217635', '1226425', '1156555', '1199150', '1204686', '1267224', …
```
=> check incremental backup size

tests/foreman/api/test_hostcollection.py
Doesn't seem that functionality connected to Hosts or Host Collections works at all on 6.3 nightly, so submitting only to 6.2 branch at that moment
```
nosetests tests/foreman/api/test_hostcollection.py
...........S........
Ran 20 tests in 141.944s
OK (SKIP=1)
```
=> Add host to host collection by non admin user(BZ1390919)

tests/foreman/data/hammer_commands.json
hammer content-view publish
Added options:
* force-yum-metadata-regeneration
hammer content-view version promote
Added options:
* force-yum-metadata-regeneration
* description
* environment-ids
hammer repository synchronize
Added options:
* validate-contents
* skip-metadata-check
(Fixes #4614)
=> Add new hammer options

.travis.yml
https://github.com/kennethreitz/requests/issues/4006
=> Upgrade pip before running installations due to requests issue

.travis.yml
https://github.com/kennethreitz/requests/issues/4006
=> [6.2.z] Upgrade pip before running installations due to requests issue 

.travis.yml
https://github.com/kennethreitz/requests/issues/4006
=> [6.1.z] Upgrade pip before running installations due to requests issue

robottelo/decorators/__init__.py, tests/robottelo/test_decorators.py
Check discussion #4263 
Using bellow code to test:
```python
if __name__ == '__main__':
settings.configure()
for bug in [1351040, 1416690]:
print(bug, bz_bug_is_open(bug))
```
By the time of this run 1351040 BZ has status VERIFIED and "sat-6.3.0" flag set to "+". On the other hand 1416690 BZ, clone of previous one, has status POST and "sat-6.2.z" flag set to "+". 
So testing with a bz and its clone on sat 6.2: should return True (bz is open) for both BZs:
```console
/home/renzo/PycharmProjects/venvs/robottelo/bin/python /home/renzo/PycharmProjects/robottelo/robottelo/decorators/__init__.py
2017-04-24 10:00:19 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f66745acb10
2017-04-24 10:00:19 - robottelo.ssh - INFO - >>> rpm -q satellite
2017-04-24 10:00:20 - robottelo.ssh - INFO - …
```
=> Fixed BZ workflow

robottelo/vm.py, tests/foreman/cli/test_remoteexecution.py, tests/foreman/ui/test_remoteexecution.py
Required in  #4578, pending tests
=> pass bridge to snap-guest vm

robottelo/constants.py, robottelo/ui/my_account.py, tests/foreman/ui/test_myaccount.py, tests/foreman/ui/test_user.py
* Refactored ui/test_myaccount.py
close #4602
* Refactored ui/test_myaccount.py
close #4602
* Refactored ui/test_myaccount.py
close #4602
(cherry picked from commit e3dbf29)
test results: 
```console
py.test tests/foreman/ui/test_myaccount.py -k "MyAccountTestCase"
========================================================== test session starts ==========================================================
platform linux2 -- Python 2.7.12, pytest-3.0.7, py-1.4.32, pluggy-0.4.0
rootdir: /home/renzo/PycharmProjects/robottelo, inifile:
plugins: xdist-1.15.0, services-1.1.14, cov-2.4.0
collected 11 items 
2017-05-09 14:36:28 - conftest - DEBUG - Found WONTFIX in decorated tests ['1110476', '1156555', '1269196', '1402826', '1245334', '1221971', '1217635', '1226425', '1199150', '1204686', '1267224', …
```
=> [6.2.z] Refactored ui/test_myaccount.py (#4606)

robottelo/decorators/__init__.py, tests/robottelo/test_decorators.py
cherry-pick of: https://github.com/SatelliteQE/robottelo/pull/4673
this addresses: https://github.com/SatelliteQE/robottelo/issues/4672
=>  implement skip_if_true decorator - fixes #4672

docs/api/robottelo.ui.rst, docs/api/tests.foreman.ui.rst, robottelo/test.py, robottelo/ui/base.py, robottelo/ui/locators/common.py, robottelo/ui/locators/menu.py, robottelo/ui/navigator.py, robottelo/ui/task.py, tests/foreman/ui/test_task.py
```
nosetests tests/foreman/ui/test_task.py
S
Ran 1 test in 15.027s
OK (SKIP=1)
```
=> Add one basic scenario for tasks functionality(BZ1440157)

robottelo/vm_capsule.py
close issue https://github.com/SatelliteQE/robottelo/issues/4677
for rhel6 capsule , test log: http://pastebin.test.redhat.com/483866
```console
(sat-6.2.z) dlezz@elysion:~/projects/robottelo-fork$ py.test tests/foreman/cli/test_contentview.py -v -k "test_positive_remove_cv_version_from_multi_env_capsule_scenario"
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.32, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.2.z/bin/python
shared_function enabled - ON - scope:  - storage: file
plugins: xdist-1.15.0, services-1.1.14, cov-2.3.1
collected 67 items 
2017-05-12 14:17:43 - conftest - DEBUG - …
```
=> Fix capsule vm ddns package setup issue for RHEL6

tests/foreman/ui/test_host.py
```
nosetests tests/foreman/ui/test_host.py -m test_positive_search
.S.
Ran 3 tests in 171.927s
OK (SKIP=1)
```
=> Test search functionality for hosts (BZ1392422)

docs/api/robottelo.ui.rst, docs/api/tests.foreman.ui.rst, robottelo/test.py, robottelo/ui/base.py, robottelo/ui/locators.py, robottelo/ui/navigator.py, robottelo/ui/task.py, tests/foreman/ui/test_task.py
Functionality failing as expected
```
nosetests tests/foreman/ui/test_task.py
S
Ran 1 test in 29.907s
OK (SKIP=1)
```
=> [cherry-pick]Add one basic scenario for tasks functionality(BZ1440157)

.travis.yml, README.rst, requirements-optional.txt
#4570 
Codecov has been enabled by @omaciel and more tests were made
so we are moving from coveralls to https://codecov.io/gh/SatelliteQE/robottelo
=> Goodbye coveralls, Hello Codecov Fix #4570

.travis.yml, README.rst, requirements-optional.txt, requirements.txt
=> [6.2.z] Goodbye coveralls, Hello Codecov

.travis.yml, README.rst, requirements-optional.txt, requirements.txt
=> [6.1.z] Goodbye coveralls, Hello Codecov

tests/foreman/ui/test_host.py
Initial PR: https://github.com/SatelliteQE/robottelo/pull/4667
```
nosetests tests/foreman/ui/test_host.py -m test_positive_search
..S.
Ran 4 tests in 227.538s
OK (SKIP=1)
```
=> [cherry-pick] Test search functionality for hosts (BZ1392422)

tests/foreman/cli/test_satellitesync.py, tests/foreman/performance/test_pulp_sync.py, tests/foreman/ui/test_computeresource_azure.py
Properly indent list items with multiple lines.
=> Improve some test docstrings

robottelo/ui/hosts.py, robottelo/ui/locators/base.py, tests/foreman/endtoend/test_ui_endtoend.py, tests/foreman/ui/test_host.py, tests/foreman/ui/test_remoteexecution.py
```
nosetests tests/foreman/ui/test_host.py -m test_positive_bulk_
S.
Ran 2 tests in 277.897s
OK (SKIP=1)
```
=> [cherry-pick]Test Bulk Host Delete action (BZ1368026)

robottelo.properties.sample, robottelo/cli/factory.py, robottelo/config/base.py, robottelo/vm.py
Depends on:
- (ready) https://github.com/SatelliteQE/robottelo-ci/pull/612
- (ready) satelliteqe/jenkins-configs/merge_requests/65
Fixes https://github.com/SatelliteQE/robottelo-ci/issues/563 within robottelo on master branch
=> Add both RHELs' Satellite Tools repos

robottelo.properties.sample, robottelo/cli/factory.py, robottelo/config/settings.py, robottelo/vm.py
Depends on:
- (ready) https://github.com/SatelliteQE/robottelo-ci/pull/612
- (ready) satelliteqe/jenkins-configs/merge_requests/65
Fixes https://github.com/SatelliteQE/robottelo-ci/issues/563 within robottelo on 6.2.z branch
=> [6.2] Add both RHELs' Satellite Tools repos

.travis.yml, robottelo.properties.sample, robottelo/bz_helpers.py, robottelo/config/settings.py, robottelo/decorators/__init__.py, tests/foreman/conftest.py
=> [6.2.z] Added option `wontfix_lookup=false` for testing locally

tests/foreman/installer/test_installer.py
=> Add --disable-resolve-mismatches to installer options

robottelo/ui/base.py
Example with custom query:
```
In [3]: session.ui.products.delete('123', search_query='name = 123 and  organization_id = 1')
2017-06-07 18:51:50 - robottelo.ui.base - DEBUG - Deleting entity 123
2017-06-07 18:51:50 - robottelo.ui.base - DEBUG - Searching for: 123
017-06-07 18:51:50 - robottelo.ui.browser - DEBUG - findElement: id: {8cc89d00-6394-4646-acdb-d09ac774d800} {'using': 'xpath', 'value': u"//input[@ng-model='table.searchTerm']"}
2017-06-07 18:51:50 - robottelo.ui.browser - DEBUG - sendKeysToElement:  {'id': u'{8cc89d00-6394-4646-acdb-d09ac774d800}', 'value': 'name = 123 and  organization_id = 1'}
2017-06-07 18:51:50 - robottelo.ui.browser - DEBUG - findElement: id: {bcc09161-e2a5-418a-9821-3de51c6385b2} {'using': 'xpath', 'value': …
```
=> Provide custom search queries from base search method for delete

tests/foreman/ui/test_subscription.py
+ cover bug: https://bugzilla.redhat.com/show_bug.cgi?id=1333219
+ remove bug skip as bug resolved and test functional
```
(sat-6.2.z) dlezz@elysion:~/projects/robottelo-fork$ pytest tests/foreman/ui/test_subscription.py -v -k "test_positive_access"
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.2.z/bin/python
shared_function enabled - ON - scope:  - storage: file
plugins: xdist-1.15.0, services-1.1.14, cov-2.3.1
collected 3 items 
2017-05-31 12:54:58 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings …
```
=> [6.2.z] qe_test_coverage 1333219

tests/foreman/api/test_repository.py, tests/foreman/cli/test_repository.py
tests affected by this bugs:
https://bugzilla.redhat.com/show_bug.cgi?id=1459845
https://bugzilla.redhat.com/show_bug.cgi?id=1459874
=> [6.3] skip tests when bugs 1459845, 1459874 open

robottelo/cli/factory.py, robottelo/cli/host.py, tests/foreman/cli/test_host.py
```
nosetests tests/foreman/cli/test_host.py -m interface
...
Ran 3 tests in 226.605s
OK
```
```
nosetests tests/foreman/cli/test_host.py
.....................F............E...............S..E
Ran 52 tests in 2823.573s
FAILED (SKIP=1, errors=2, failures=1)
```
=> Add coverage for host interface functionality(BZ1384497)

robottelo/cli/hostcollection.py, tests/foreman/cli/test_errata.py
affected by https://bugzilla.redhat.com/show_bug.cgi?id=1457977
all the negative tests passed, all the positive tests failed due to the bug
portion of a test failed (log file is too big) (all the failed with the same symptom): 
http://pastebin.test.redhat.com/490075
=> [6.3] Port host-collection erratum install + cover bug 1457977

tests/foreman/ui/test_navigation.py
https://github.com/SatelliteQE/robottelo/issues/4851
=> Run navigation test in different org. Issue #4851

robottelo/ui/locators.py, robottelo/ui/login.py, robottelo/ui/syncplan.py, tests/foreman/api/test_syncplan.py, tests/foreman/cli/test_syncplan.py, tests/foreman/ui/test_syncplan.py
=> [6.2.z] cherry-pick removed outdated stub decorators

tests/foreman/cli/test_errata.py
bug: https://bugzilla.redhat.com/show_bug.cgi?id=1457938
test log http://pastebin.test.redhat.com/490019
host collection erratum install has been affected by many bugs and after all the bugs was resolved, we were in need to fix the tests and an other bug https://bugzilla.redhat.com/show_bug.cgi?id=1457938 raised.
=> [6.2.z] Fix host collection erratum install and cover 1457938

tests/foreman/api/test_permission.py
Now 
>  Only administrator can choose empty taxonomies or taxonomies that they aren't assigned to,
>  other users can select only taxonomies they are granted to assign
>  and they can't leave the selection empty (which would mean global resource)
so it is needed to specify same org and loc for non-admin user and created entity. Also I've added one katello entity to increase coverage.
Thanks to @ldjebran for the idea how to handle both types of entities (with loc and org and without them). :)
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1464137
Test results:
```
λ pytest -v tests/foreman/api/test_permission.py -k 'UserRoleTestCase'
===================================================================================== test session starts …
```
=> Update API/Permissions tests to follow new org/loc taxonomies logic

tests/foreman/cli/test_contentview.py
fixed test as per new filter rules:
and filled a bug that is affecting this tests https://bugzilla.redhat.com/show_bug.cgi?id=1464414
skipped as test fail as per the bug description
=> [6.3] FIX+SKIP cli_test_positive_user_with_all_cv_permissions

robottelo.properties.sample
fixed robottelo.properties - vmware hostname key
=> fixed robottelo.properties - vmware hostname key

robottelo/ui/location.py, robottelo/ui/locators/base.py, robottelo/ui/org.py, tests/foreman/ui/test_host.py, tests/robottelo/ui/test_location.py
```
nosetests tests/foreman/ui/test_host.py -m test_positive_search_with_org_and_loc_context
.
Ran 1 test in 71.520s
OK
```
=> Add coverage for host search procedure(BZ1405496)

tests/foreman/sys/test_hot_backup.py
Fixes #4868 
Applies to 6.3 only, test result:
```
nosetests -v -s tests/foreman/sys/test_hot_backup.py:HotBackupTestCase.test_positive_logical_db_backup
...
Ran 1 test in 125.250s
OK
```
=> test --logical-db-backup

tests/foreman/ui/test_role.py
```
nosetests tests/foreman/ui/test_role.py -m test_positive_create_filter_admin_user_with_orgs
.
Ran 1 test in 122.811s
OK
```
=> Add coverage for user with multiple orgs functionality(BZ1389795)

robottelo/ui/locators/base.py, robottelo/ui/packages.py, tests/foreman/ui/test_packages.py
Fixed issue with locator and optimized approach to have easier way to make similar fixes in future
```
nosetests tests/foreman/ui/test_packages.py
..F...
Ran 6 tests in 415.937s
FAILED (failures=1)
```
One failure that is left will require some efforts for search procedure as repository name that we selected is reset after we do re-navigation to the package page
=> Fix packages test cases

robottelo/ui/location.py, robottelo/ui/locators.py, robottelo/ui/org.py, tests/foreman/ui/test_host.py, tests/robottelo/ui/test_location.py
* [cherry-pick] Add coverage for host search procedure(BZ1405496)
* Fix according 6.2
```
nosetests tests/foreman/ui/test_host.py -m test_positive_search_with_org_and_loc_context
.
Ran 1 test in 96.917s
OK
```
```
nosetests tests/foreman/ui/test_host.py:HostTestCase
.S.SSSSS..F..S.S.
Ran 17 tests in 948.079s
FAILED (SKIP=8, failures=1)
```
=> [6.2] Add coverage for host search procedure(BZ1372757)

docs/api/tests.foreman.sys.rst, docs/api/tests.robottelo.rst, logging.conf, requirements.txt, robottelo/decorators/__init__.py, tests/robottelo/test_datafactory.py, tests/robottelo/test_decorators.py
This depends on merging the https://github.com/SatelliteQE/robozilla/pull/28 and also release to PyPI
And will unblock https://github.com/SatelliteQE/satellite6-upgrade/issues/43 
Once merged will be Cpicked to 6.2 branch (but open to discussion if really needed as code is backwards compatible)
=> Moving bug related decorators to robozilla

tests/foreman/api/test_permission.py
```
λ pytest -v tests/foreman/api/test_permission.py -k 'UserRoleTestCase'
===================================================================================== test session starts =====================================================================================
platform linux2 -- Python 2.7.13, pytest-3.1.0, py-1.4.33, pluggy-0.4.0 -- /home/qui/code/venv/2/bin/python2
metadata: {'Python': '2.7.13', 'Platform': 'Linux-4.11.3-1-ARCH-x86_64-with-glibc2.2.5', 'Packages': {'py': '1.4.33', 'pytest': '3.1.0', 'pluggy': '0.4.0'}, 'Plugins': {'cov': '2.5.1', 'xdist': '1.16.0', 'html': '1.15.1', 'services': '1.2.1', 'mock': '1.6.0', 'metadata': '1.5.0'}}
rootdir: /home/qui/code/robottelo, inifile:
plugins: xdist-1.16.0, services-1.2.1, mock-1.6.0, metadata-1.5.0, html-1.15.1, …
```
=> Update API/Permissions tests / Move common code parts to helper

robottelo/ui/locators/tab.py, tests/foreman/ui/test_hostunification.py
```
nosetests tests/foreman/ui/test_hostunification.py -m test_positive_rename_content_host
..
Ran 2 tests in 311.316s
OK
```
=> Add coverage for content host rename procedure(BZ1417953)

tests/foreman/ui/test_user.py
```
nosetests tests/foreman/ui/test_user.py -m test_positive_search_by_usergroup
.
Ran 1 test in 59.560s
OK
```
=> Add coverage for user search functionality (BZ1395667)

tests/foreman/cli/test_contentviewfilter.py
```
nosetests tests/foreman/cli/test_contentviewfilter.py -m test_positive_create_with_default_taxonomies
.
Ran 1 test in 118.617s
OK
```
=> Add coverage for content view filter with default taxonomies functionality (BZ1369609)

tests/foreman/ui/test_activationkey.py
`test_positive_host_associations` and `test_positive_list_hosts` are testing basically the same. The confusion was introduced by 3 (!) BZs describing the same issue: BZ1344033, BZ1372826, BZ1394388.
Removing `test_positive_list_hosts` as it's more complicated, slower and is not cherry-picked to 6.2.z (`test_positive_host_associations` is present in both branches)
=> Removed duplicated test & updated associated BZs

tests/foreman/cli/test_lifecycleenvironment.py
https://bugzilla.redhat.com/show_bug.cgi?id=1368590
```python
py.test -v tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentPaginationTestCase
platform darwin -- Python 2.7.13, pytest-3.0.7, py-1.4.34, pluggy-0.4.0 -- /Users/andrii/workspace/env/bin/python
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.0, cov-2.3.1
collected 2 items
2017-07-04 14:13:24 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings
tests/foreman/cli/test_lifecycleenvironment.py::LifeCycleEnvironmentPaginationTestCase::test_positive_list_all_with_per_page <- robottelo/decorators/__init__.py PASSED …
```
=> Implemented test for BZ1368590 and fixed existing lce pagination test

tests/foreman/api/test_permission.py
BZ #1464137 not a bug after all but rather additional permissions now are needed.
```
λ pytest -n 4 -v tests/foreman/api/test_permission.py -k 'UserRoleTestCase'                                                              master +6/-6 * 5dc3091a
===================================================================================== test session starts =====================================================================================
platform linux2 -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0 -- /home/qui/code/venv/2/bin/python2
metadata: {'Python': '2.7.13', 'Platform': 'Linux-4.11.6-3-ARCH-x86_64-with-glibc2.2.5', 'Packages': {'py': '1.4.34', 'pytest': '3.1.2', 'pluggy': '0.4.0'}, 'Plugins': {'cov': '2.5.1', 'xdist': '1.18.0', 'html': '1.15.1', 'services': …
```
=> Update API/test_permission / Grant more required permissions

tests/foreman/ui/test_subnet.py
UI stubs for 6.3 feature 'Parameterized Subnets'
=> [6.3 Feature - Parameterized Subnets] UI Stubs

robottelo/ui/contentviews.py, robottelo/ui/locators/common.py, tests/foreman/ui/test_hostgroup.py
```
nosetests tests/foreman/ui/test_hostgroup.py -m test_positive_redirection_for_multiple_hosts
.
Ran 1 test in 86.594s
OK
```
=> Add coverage for hostgroup redirection functionality(BZ1402390)

tests/foreman/ui/test_syncplan.py
Decided to make validation with more accurate correspondance to the issue
```
nosetests tests/foreman/ui/test_syncplan.py -m test_positive_update_interval
.
Ran 1 test in 86.680s
OK
```
=> Slight update for syncplan update procedure(BZ1387543)

requirements-optional.txt, requirements.txt
=> Added sauceclient so that pass/fail status is known to saucelabs

tests/foreman/ui/test_repository.py
#4931
https://bugzilla.redhat.com/show_bug.cgi?id=1398574
```python
py.test -v tests/foreman/ui/test_repository.py -k test_positive_upload_rpm_non_admin
platform darwin -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0 -- /Users/andrii/workspace/env62z/bin/python
plugins: xdist-1.15.0, services-1.1.14, cov-2.3.1
collected 58 items
2017-07-10 11:46:16 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings
tests/foreman/ui/test_repository.py::RepositoryTestCase::test_positive_upload_rpm_non_admin PASSED
============================= 57 tests deselected …
```
=> [6.2.z][Cherry-pick] Implemented test for BZ1398574

robottelo/ui/dockertag.py
```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test -v tests/foreman/ui/test_docker.py::DockerTagTestCase
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.34, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.0, cov-2.4.0
collected 1 items 
2017-07-12 16:10:05 - conftest - DEBUG - Found WONTFIX in decorated tests ['1269196', '1378009', '1245334', '1217635', '1226425', '1156555', '1199150', '1204686', '1267224', '1221971', '1103157', '1230902', '1214312', '1079482']
2017-07-12 16:10:05 - conftest - DEBUG - …
```
=> [6.3] FIX UI DockerTagTestCase

tests/foreman/ui/test_setting.py
Added stub for company specific message on login page
=> [sat6.3 Feature- Company specific message on login page] UI stub

robottelo/ui/factory.py, robottelo/ui/locators/base.py, robottelo/ui/user.py, tests/foreman/ui/test_user.py
=> Automated description field feature for user

tests/foreman/ui/test_computeresource_rhev.py
Automated https://bugzilla.redhat.com/show_bug.cgi?id=1467664
pytest tests/foreman/ui/test_computeresource_rhev.py::RhevComputeResourceTestCase::test_positive_create_rhev_with_existing_name
tests/foreman/ui/test_computeresource_rhev.py s
1 skipped in 11.47 seconds
=> Added coverage for bugzilla 1467664

robottelo/cli/factory.py, tests/foreman/cli/test_repository.py
```
nosetests tests/foreman/cli/test_repository.py -m test_positive_create_with_mirror_on_sync
.
Ran 1 test in 54.943s
OK
```
=> Add coverage for repository functionality (BZ1383258)

tests/foreman/cli/test_contentview.py
```
nosetests tests/foreman/cli/test_contentview.py -m test_positive_remove_version_by_name
.
Ran 1 test in 79.201s
OK
```
=> Cover remove cvv by name functionality (BZ1416862)

robottelo/ui/lifecycleenvironment.py, robottelo/ui/locators/base.py, robottelo/ui/locators/tab.py, tests/foreman/ui/test_lifecycleenvironment.py
```
nosetests tests/foreman/ui/test_lifecycleenvironment.py
...S....
Ran 8 tests in 568.410s
OK (SKIP=1)
```
=> Add coverage for lce puppet env functionality (BZ1408264)

tests/foreman/ui/test_activationkey.py
Default locked Viewer role does not contain "view_content_views" and "view_lifecycle_environments"
created an issue for this https://github.com/SatelliteQE/robottelo/issues/4917
```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test tests/foreman/ui/test_activationkey.py -v -k "host_collection_non_admin"
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.34, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.0, cov-2.4.0
collected 39 items 
2017-07-03 16:12:14 - conftest - DEBUG - Found WONTFIX in decorated tests …
```
=> [6.3] FIX test_activationkey host_collection_non_admin

robottelo/ui/base.py, robottelo/ui/factory.py, robottelo/ui/hostgroup.py, robottelo/ui/locators/base.py, robottelo/ui/locators/tab.py, tests/foreman/ui/test_hostgroup.py
```
nosetests tests/foreman/ui/test_hostgroup.py
......F....
Ran 11 tests in 821.341s
FAILED (failures=1)
```
One failure related to environment issue
=> Hostgroup code improvement + coverage(BZ1372917)

tests/foreman/ui/test_setting.py
=> Added stubs to Email Settings through UI

robottelo.properties.sample, robottelo/cli/capsule.py, robottelo/cli/factory.py, robottelo/config/base.py, robottelo/constants.py, robottelo/vm_capsule.py, tests/foreman/cli/test_contentview.py
test log: http://pastebin.test.redhat.com/491756
```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test -v tests/foreman/cli/test_contentview.py::ContentViewTestCase::test_positive_remove_cv_version_from_multi_env_capsule_scenario
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.32, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.0, cov-2.4.0
collected 73 items 
2017-06-07 10:13:44 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings
tests/foreman/cli/test_contentview.py::ContentViewTestCase::te …
```
=> [6.3] Port external capsule + RFT

robottelo/api/utils.py, robottelo/helpers.py, robottelo/ui/computeresource.py, robottelo/ui/hosts.py, robottelo/ui/locators/base.py, robottelo/ui/locators/common.py, robottelo/ui/locators/tab.py, tests/foreman/ui/test_computeresource_rhev.py
```
 pytest tests/foreman/ui/test_computeresource_rhev.py::RhevComputeResourceHostTestCase::test_positive_provision_rhev_with_compute_profile
=================================================================================
tests/foreman/ui/test_computeresource_rhev.py s
================================================================================= 1 skipped in 52.93 seconds =================================================================================
pytest tests/foreman/ui/test_computeresource_rhev.py::RhevComputeResourceHostTestCase::test_positive_provision_rhev_with_custom_compute_settings
=================================================================================tests/foreman/ui/test_computeresource_rhev.py s
============================================================== …
```
=> Automation of tier3 tests for Rhev CR

robottelo/ui/base.py, robottelo/ui/factory.py, robottelo/ui/hostgroup.py, robottelo/ui/locators.py, tests/foreman/ui/test_hostgroup.py
Sometimes cherry-pick is not smart enough, so did some manual comparisons. Please, review PR as usual one as I can miss something
Original PR: https://github.com/SatelliteQE/robottelo/pull/4943
1 failure related to infrastructure
```
nosetests tests/foreman/ui/test_hostgroup.py
......F...
Ran 10 tests in 846.491s
FAILED (failures=1)
```
=> [6.2]Hostgroup code improvement + coverage(BZ1372917)

tests/foreman/ui/test_variables.py
```
nosetests tests/foreman/ui/test_variables.py -m test_positive_override
..
Ran 2 tests in 145.362s
OK
```
=> Add test coverage for smart variable functionality (BZ1405118)

docs/api/tests.foreman.cli.rst, tests/foreman/cli/test_discoveredhost.py, tests/foreman/cli/test_setting.py, tests/foreman/ui/test_discoveredhost.py, tests/foreman/ui/test_setting.py
Test cases around two new discovery settings for hostname change.
=> Test stubs around discovery settings to control hostname change

robottelo/vm.py
There was a bug in `vm.create()` where we bailed out without destroying & undefining the libvirt domain, if the `create()` failed during obtaining the VM IP or testing the SSH connectivity.
This led to 'dead souls' running on the libvirt CR.
=> vm.py - create() - implement proper cleanup if unable to reach the VM

tests/foreman/api/test_user.py
Do not merge until following nailgun PR gets merged
https://github.com/SatelliteQE/nailgun/pull/431
=> [6.3]Added coverage for User entity- API automation

tests/foreman/ui/test_contentview.py
=> Added stubs around File Repository with Content View

tests/foreman/ui/test_variables.py
```
nosetests tests/foreman/ui/test_variables.py -m test_positive_override_default_value_from_attribute
.
Ran 1 test in 140.200s
OK
```
=> [Cherry-pick]Add test coverage for smart variable functionality (BZ1405118) (#5022)

tests/foreman/ui/test_contentview.py
```
nosetests tests/foreman/ui/test_contentview.py -m test_positive_delete_version_without_refresh
.
Ran 1 test in 103.994s
OK
```
=> Add coverage for content view delete procedure (BZ1374134)

tests/foreman/api/test_contentview.py, tests/foreman/api/test_repository.py, tests/foreman/cli/test_contentview.py, tests/foreman/cli/test_repository.py
=> Added stubs for Arbitrary File & Content View on API/CLI

tests/foreman/ui/test_repository.py
=> [6.3] Added stubs around File Repository feature

Makefile
This support is required so that standalone-automation can only
run these tests.
=> Added support to run only sys tests to Makefile

docs/api/tests.foreman.cli.rst, tests/foreman/cli/test_computeresource_rhev.py
```
pytest tests/foreman/cli/test_computeresource_rhev.py
test session starts 
tests/foreman/cli/test_computeresource_rhev.py ssssssssssssssss
=============================================16 skipped in 0.19 seconds 
```
=> Added CLI test-cases stubs for RHEV compute resource

tests/foreman/ui/test_remoteexecution.py
```
nosetests tests/foreman/ui/test_remoteexecution.py -m test_positive_preview_job_template_with_foreman_url
.
Ran 1 test in 57.039s
OK
```
=> Add test coverage for job template functionality (BZ1374344)

robottelo/constants.py, robottelo/ui/factory.py, robottelo/ui/ldapauthsource.py, tests/foreman/ui/test_ldapauthsource.py
"""
pytest tests/foreman/ui/test_ldapauthsource.py::LDAPAuthSourceTestCase::test_positive_create_withad_org_and_loc
========================== test session starts ===================================
collected 5 items
tests/foreman/ui/test_ldapauthsource.py .
================================= 1 passed ===================================
"""
=> Added coverage for LDAP auth source

scripts/fix_uuids.sh, tests/foreman/api/test_repository.py
Closes #5078
thanks to @svtkachenko for the solution
luckly only found a single duplication across files.
=> Fix uuid fix scripts to consider duplicates in multiple files

requirements.txt
Tests run on saucelabs
```
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test tests/foreman/ui -v -m 'tier1 and run_in_one_thread and not stubbed'
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.34, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.0, cov-2.4.0
collected 1275 items 
2017-08-01 15:07:47 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings
tests/foreman/ui/test_adusergroup.py::ActiveDirectoryUserGroupTestCase::test_negative_create_external_with_invalid_name PASSED …
```
=> [6.3]  change selenium 2.53.1

tests/foreman/api/test_user.py
=> [6.3 Feature] SSH Key in User Templates API Stubs

tests/foreman/api/test_subnet.py
=> [6.3 Feature] Parameterized Subnets API stubs

scripts/fix_uuids.sh, tests/foreman/api/test_repository.py
=> [6.2] Fix uuid fix scripts to consider duplicates in multiple files

tests/foreman/cli/test_setting.py
=> Added stubs for email settings through CLI

Makefile
This support is required so that standalone-automation can only
run these tests.
=> Added support to run sys tests to Makefile

tests/foreman/ui/test_role.py
=> [6.3 Feature] Canned Role Org Admin feature UI Stubs

tests/foreman/api/test_role.py
=> [6.3 Feature] Canned Role Org Admin API stubs

tests/foreman/ui/test_user.py
These are the complete stubs for this feature from UI except stubs to be fetched from the doubts developer would clear regarding public/private key deletion from satellite.
The stubs for those doubts will be raised separately.
=> [6.3 Feature] SSH Key in User Template UI Stubs

requirements.txt
idna version got update recently to 2.6 and hence the failures.
=> pinned idna version to 2.5 which solves the job failures.

tests/foreman/cli/test_role.py
=> [6.3 Feature] Canned Role Org Admin CLI stubs

robottelo/decorators/__init__.py, tests/foreman/api/test_activationkey.py, tests/foreman/api/test_architecture.py, tests/foreman/api/test_classparameters.py, tests/foreman/api/test_contentview.py, tests/foreman/api/test_contentviewversion.py, tests/foreman/api/test_docker.py, tests/foreman/api/test_errata.py, tests/foreman/api/test_host.py, tests/foreman/cli/test_oscap.py, tests/foreman/installer/test_installer.py, tests/foreman/longrun/test_oscap.py, tests/foreman/ui/test_computeresource_rhev.py, tests/foreman/ui/test_computeresource_vmware.py, tests/foreman/ui/test_oscap_tailoringfiles.py
Some of the, cherry-picked tests to run after upgrade.
=> Selecting tests with upgrade mark

tests/foreman/ui/test_gpgkey.py
PR https://github.com/SatelliteQE/robottelo/pull/5143 was merged without BZ in doc strings
=> [6.3] FIX  UI test_gpgkey add bz to doc
