tests/foreman/api/test_classparameters.py
tests/foreman/api/test_role.py
tests/foreman/api/test_subnet.py
tests/foreman/api/test_user.py
tests/foreman/api/test_variables.py

Adding upgrade tests for 5 new files:
-  tests/foreman/api/test_classparameters.py
-  tests/foreman/api/test_role.py
-  tests/foreman/api/test_subnet.py
-  tests/foreman/api/test_user.py
-  tests/foreman/api/test_variables.py

Filter Robotello Tests for upgrade

---

robottelo/constants.py
robottelo/ui/factory.py
robottelo/ui/globalparameters.py
robottelo/ui/locators/base.py
robottelo/ui/session.py
tests/foreman/ui/test_globalparameters.py

UI test_bookmark failed because of a bug (https://bugzilla.redhat.com/show_bug.cgi?id=1456833) state changed to ON_QA, when the bug was released, the infra to handle Global Parameters entity was not in place.
This PR implement the base helper to fix the test_bookmark and implement base functional tests for Global Parameters, waiting for other stubs tests to be implemented to close issue https://github.com/SatelliteQE/robottelo/issues/5138.
```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test -v tests/foreman/ui/test_bookmark.py::BookmarkTestCase
platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- …
```

[6.3] FIX  UI test_bookmark + implement Global Parameters helper + base tests

---

tests/foreman/cli/test_host.py

```
pytestrunner.py -p pytest_teamcity /home/qui/code/robottelo/tests/foreman/cli/test_host.py "-k KatelloAgentTestCase and test_positive_apply_security_erratum"
============================= 77 tests deselected ==============================
================== 1 passed, 77 deselected in 724.22 seconds ===================
```

Fix cli.host.test_positive_apply_security_erratum

---

tests/foreman/sys/test_restore.py

Fixes #5148 
```
pytest tests/foreman/sys/test_restore.py
=========================================== test session starts ============================================
platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/pondrejk/Documents/robottelo, inifile:
plugins: xdist-1.19.1, services-1.2.1, mock-1.6.2, forked-0.2, cov-2.5.1
collected 5 items 
2017-08-16 17:14:33 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings
tests/foreman/sys/test_restore.py ...ss
=================================== 3 passed, 2 skipped in 36.14 seconds ===================================
```

updates to katello-restore

---

tests/foreman/cli/test_host.py

```
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test -v tests/foreman/cli/test_host.py::HostSubscriptionTestCase================================================= test session starts ==================================================
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.2, cov-2.4.0
collected 8 items 
2017-08-17 09:08:31 - conftest - DEBUG - Found WONTFIX in decorated tests ['1147100', '1269208', '1269196', '1378009', '1245334', '1217635', '1226425', '1156555', '1311113', '1199150', '1238247', '1204686', '1267224', '1221971', '1103157', '1230902', '1230865', '1214312', …
```

[6.3] FIX  CLI HostSubscriptionTestCase

---

docs/api/robottelo.ui.rst
robottelo.properties.sample
robottelo/config/base.py
robottelo/constants.py
robottelo/ui/factory.py
robottelo/ui/locators/base.py
robottelo/ui/locators/menu.py
robottelo/ui/navigator.py
robottelo/ui/oscap_tailoringfile.py
robottelo/ui/session.py
tests/foreman/ui/test_oscap_tailoringfiles.py

Test Results 
```
pytest tests/foreman/ui/test_oscap_tailoringfiles.py::TailoringFilesTestCase::test_positive_create
=========================== test session starts ==================================
collected 14 items
tests/foreman/ui/test_oscap_tailoringfiles.py .
============================== 1 passed ======================================
```

Added support for tailoring file UI

---

tests/foreman/api/test_hostcollection.py
tests/foreman/api/test_hostgroup.py
tests/foreman/api/test_lifecycleenvironment.py
tests/foreman/api/test_media.py
tests/foreman/api/test_operatingsystem.py
tests/foreman/api/test_organization.py
tests/foreman/api/test_permission.py
tests/foreman/api/test_product.py
tests/foreman/api/test_puppetmodule.py
tests/foreman/api/test_usergroup.py
tests/foreman/ui/test_adusergroup.py
tests/foreman/ui/test_architecture.py
tests/foreman/ui/test_contenthost.py
tests/foreman/ui/test_contentview.py
tests/foreman/ui/test_dashboard.py
tests/foreman/ui/test_domain.py

Added tests to be run with upgrade decorator

---

tests/foreman/ui/test_classparameters.py
tests/foreman/ui/test_computeprofile.py
tests/foreman/ui/test_config_group.py
tests/foreman/ui/test_environment.py
tests/foreman/ui/test_globalparameters.py
tests/foreman/ui/test_hostcollection.py
tests/foreman/ui/test_hw_model.py
tests/foreman/ui/test_ldapauthsource.py
tests/foreman/ui/test_lifecycleenvironment.py
tests/foreman/ui/test_medium.py
tests/foreman/ui/test_myaccount.py
tests/foreman/ui/test_navigation.py
tests/foreman/ui/test_operatingsystem.py
tests/foreman/ui/test_organization.py
tests/foreman/ui/test_partitiontable.py
tests/foreman/ui/test_product.py
tests/foreman/ui/test_puppetclass.py
tests/foreman/ui/test_role.py
tests/foreman/ui/test_satellitesync.py
tests/foreman/ui/test_subnet.py
tests/foreman/ui/test_subscription.py
tests/foreman/ui/test_sync.py
tests/foreman/ui/test_user.py
tests/foreman/ui/test_variables.py

24 UI robotello test files updated to filter the upgrade tests

Filtered robotello UI tests for Upgrade

---

tests/foreman/cli/test_classparameters.py
tests/foreman/cli/test_globalparam.py
tests/foreman/cli/test_location.py
tests/foreman/cli/test_organization.py
tests/foreman/cli/test_partitiontable.py
tests/foreman/cli/test_ping.py
tests/foreman/cli/test_puppet.py
tests/foreman/cli/test_puppetclass.py
tests/foreman/cli/test_puppetmodule.py
tests/foreman/cli/test_remoteexecution.py
tests/foreman/cli/test_report.py
tests/foreman/cli/test_repository.py
tests/foreman/cli/test_repository_set.py
tests/foreman/cli/test_role.py
tests/foreman/cli/test_satellitesync.py
tests/foreman/cli/test_subnet.py
tests/foreman/cli/test_subscription.py
tests/foreman/cli/test_template.py
tests/foreman/cli/test_user.py
tests/foreman/cli/test_usergroup.py
tests/foreman/cli/test_variables.py
tests/foreman/installer/test_infoblox.py
tests/foreman/longrun/test_inc_updates.py

Test Files updated with upgrade decorator in :
1 installer file
2 longrun files
20 CLI files

Filtered CLI, Installer and Longrun tests for upgrade

---

tests/foreman/ui/test_activationkey.py
tests/foreman/ui/test_ansible.py
tests/foreman/ui/test_bootdisk.py
tests/foreman/ui/test_capsule.py
tests/foreman/ui/test_computeresource.py
tests/foreman/ui/test_computeresource_azure.py
tests/foreman/ui/test_computeresource_ec2.py
tests/foreman/ui/test_computeresource_openstack.py
tests/foreman/ui/test_discoveredhost.py
tests/foreman/ui/test_discoveryrule.py
tests/foreman/ui/test_docker.py
tests/foreman/ui/test_email.py
tests/foreman/ui/test_errata.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_hostgroup.py
tests/foreman/ui/test_hostunification.py
tests/foreman/ui/test_isodownload.py
tests/foreman/ui/test_ldap_auth.py
tests/foreman/ui/test_location.py
tests/foreman/ui/test_multinetwork.py
tests/foreman/ui/test_puppet.py
tests/foreman/ui/test_remoteexecution.py
tests/foreman/ui/test_repository.py
tests/foreman/ui/test_setting.py
tests/foreman/ui/test_sso.py
tests/foreman/ui/test_syncplan.py
tests/foreman/ui/test_system_registration.py

Selected UI tests decorated w/ `upgrade` decorator to run them post upgrade.

Updated tests with upgrade decorator

---

robottelo/decorators/__init__.py
tests/foreman/ui/test_classparameters.py
tests/foreman/ui/test_computeprofile.py
tests/foreman/ui/test_config_group.py
tests/foreman/ui/test_environment.py
tests/foreman/ui/test_hostcollection.py
tests/foreman/ui/test_hw_model.py
tests/foreman/ui/test_ldapauthsource.py
tests/foreman/ui/test_lifecycleenvironment.py
tests/foreman/ui/test_medium.py
tests/foreman/ui/test_myaccount.py
tests/foreman/ui/test_navigation.py
tests/foreman/ui/test_operatingsystem.py
tests/foreman/ui/test_organization.py
tests/foreman/ui/test_partitiontable.py
tests/foreman/ui/test_product.py
tests/foreman/ui/test_puppetclass.py
tests/foreman/ui/test_role.py
tests/foreman/ui/test_satellitesync.py
tests/foreman/ui/test_subnet.py
tests/foreman/ui/test_subscription.py
tests/foreman/ui/test_sync.py
tests/foreman/ui/test_user.py
tests/foreman/ui/test_variables.py

Cherry picking the master PR 'Filtered robotello UI tests for Upgrade #5175' into 6.2.z

CherryPick of master PR 'Filtered robotello UI tests for Upgrade #5175'

---

tests/foreman/api/test_repository.py
tests/foreman/api/test_repository_set.py
tests/foreman/api/test_setting.py
tests/foreman/api/test_smartproxy.py
tests/foreman/api/test_subscription.py
tests/foreman/api/test_syncplan.py
tests/foreman/api/test_template.py
tests/foreman/api/test_template_combination.py

More Filtered robotello API tests for upgrade

---

tests/foreman/api/test_classparameters.py
tests/foreman/api/test_role.py
tests/foreman/api/test_user.py
tests/foreman/api/test_variables.py

CherryPicked master PR 'Filter Robotello Tests for upgrade  #5157'

---

tests/foreman/cli/test_abrt.py
tests/foreman/cli/test_activationkey.py
tests/foreman/cli/test_architecture.py
tests/foreman/cli/test_bootstrap_script.py
tests/foreman/cli/test_capsule.py
tests/foreman/cli/test_capsule_installer.py
tests/foreman/cli/test_contentview.py
tests/foreman/cli/test_docker.py
tests/foreman/cli/test_domain.py
tests/foreman/cli/test_environment.py
tests/foreman/cli/test_errata.py
tests/foreman/cli/test_filter.py
tests/foreman/cli/test_gpgkey.py
tests/foreman/cli/test_hammer.py
tests/foreman/cli/test_host.py
tests/foreman/cli/test_host_collection.py
tests/foreman/cli/test_hostgroup.py
tests/foreman/cli/test_installer.py
tests/foreman/cli/test_lifecycleenvironment.py
tests/foreman/cli/test_medium.py
tests/foreman/cli/test_model.py
tests/foreman/cli/test_myaccount.py
tests/foreman/cli/test_operatingsystem.py
tests/foreman/cli/test_ostreebranch.py

Updated selected tests w/ `upgrade` decorator.

updated CLI tests with upgrade decorator

---

Makefile
tests/foreman/ui/test_notification_drawer.py

Created stubs for Notification Drawer

---

robottelo/cli/recurring_logic.py
tests/foreman/api/test_repository.py
tests/foreman/api/test_repository_set.py
tests/foreman/api/test_smartproxy.py
tests/foreman/api/test_subscription.py
tests/foreman/api/test_syncplan.py
tests/foreman/api/test_template.py

CherryPicked master PR 'More Filtered robotello API tests for upgrade #5173'

---

tests/foreman/cli/test_classparameters.py
tests/foreman/cli/test_globalparam.py
tests/foreman/cli/test_location.py
tests/foreman/cli/test_organization.py
tests/foreman/cli/test_partitiontable.py
tests/foreman/cli/test_ping.py
tests/foreman/cli/test_puppetclass.py
tests/foreman/cli/test_puppetmodule.py
tests/foreman/cli/test_remoteexecution.py
tests/foreman/cli/test_report.py
tests/foreman/cli/test_repository.py
tests/foreman/cli/test_repository_set.py
tests/foreman/cli/test_role.py
tests/foreman/cli/test_satellitesync.py
tests/foreman/cli/test_subnet.py
tests/foreman/cli/test_subscription.py
tests/foreman/cli/test_template.py
tests/foreman/cli/test_user.py
tests/foreman/cli/test_usergroup.py
tests/foreman/cli/test_variables.py
tests/foreman/longrun/test_inc_updates.py

CherryPicked master PR 'Filtered CLI, Installer and Longrun tests for upgrade #5182'

---

tests/foreman/ui/test_activationkey.py
tests/foreman/ui/test_capsule.py
tests/foreman/ui/test_computeresource.py
tests/foreman/ui/test_discoveredhost.py
tests/foreman/ui/test_discoveryrule.py
tests/foreman/ui/test_docker.py
tests/foreman/ui/test_email.py
tests/foreman/ui/test_errata.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_hostgroup.py
tests/foreman/ui/test_hostunification.py
tests/foreman/ui/test_isodownload.py
tests/foreman/ui/test_ldap_auth.py
tests/foreman/ui/test_location.py
tests/foreman/ui/test_multinetwork.py
tests/foreman/ui/test_remoteexecution.py
tests/foreman/ui/test_repository.py
tests/foreman/ui/test_setting.py
tests/foreman/ui/test_sso.py
tests/foreman/ui/test_syncplan.py
tests/foreman/ui/test_system_registration.py

(cherry picked from commit b35f69c3e025ee76f91e69ee0e7203db95b75aff)

[6.2.z] cherry-picked Updated tests with upgrade decorator

---

tests/foreman/api/test_contentmanagement.py

Depends on SatelliteQE/nailgun#438
6.3 introduced separate download policy for each capsule.
Thus `test_positive_update_with_immediate_sync` should update capsule's
download policy altogether with repository's one as otherwise repo's change
will be ignored and overridden by capsule's default 'on_demand' policy.
Test results:
```python
/Users/andrii/workspace/env/bin/python /Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py --multiproc --qt-support --client 127.0.0.1 --port 61216 --file /Applications/PyCharm.app/Contents/helpers/pycharm/pytestrunner.py -p pytest_teamcity /Users/andrii/workspace/robottelo/tests/foreman/api/test_contentmanagement.py "-k CapsuleContentManagementTestCase and test_positive_update_with_immediate_sync"
Testing started at 6:10 PM ...
pydev debugger: …
```

Update content management test according to latest 6.3 changes

---

tests/foreman/ui/test_classparameters.py

```
nosetests tests/foreman/ui/test_classparameters.py -m test_positive_view_yaml_output
..
Ran 2 tests in 206.873s
OK
```

Add coverage for smart class parameters yaml functionality (BZ1241249)

---

tests/foreman/ui/test_lifecycleenvironment.py

```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test -v tests/foreman/ui/test_lifecycleenvironment.py::LifeCycleEnvironmentTestCase::test_positive_custom_user_view_lce
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.2, cov-2.4.0
collected 1 item 
2017-08-30 14:51:48 - conftest - DEBUG - Found WONTFIX in decorated tests ['1147100', '1269196', '1378009', '1245334', '1217635', '1226425', '1156555', '1311113', '1199150', '1204686', '1221971', '1103157', …
```

[6.3] FIX UI  test_positive_custom_user_view_lce

---

tests/foreman/ui/test_repository.py

```
nosetests tests/foreman/ui/test_repository.py -m test_positive_reposet_disable_after_manifest_deleted
.
Ran 1 test in 180.629s
OK
```

Add coverage for repository disable functionality (BZ1344391)

---

tests/foreman/cli/test_variables.py

lock the setupClass as can conflict when running in parallel 
```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ pytest -v -n 8 tests/foreman/cli/test_variables.py
[gw0] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw1] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw2] linux2 Python 2.7.13 cwd: …
```

[6.3] FIX CLI  test_variables

---

tests/foreman/cli/test_satellitesync.py

depend on https://github.com/SatelliteQE/nailgun/pull/439
```
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ pytest -v tests/foreman/cli/test_satellitesync.py::RepositoryExportTestCase -v -k "test_positive_export_custom_product or test_positive_export_rh_product"
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.2, cov-2.4.0
collected 2 items 
2017-08-30 19:07:43 - conftest - DEBUG - Found WONTFIX in decorated tests ['1147100', '1269196', '1378009', '1245334', '1217635', …
```

[6.3] FIX CLI  test_satellitesync

---

tests/foreman/cli/test_lifecycleenvironment.py

```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ pytest -v -n 8 tests/foreman/cli/test_lifecycleenvironment.py
[gw0] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw1] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw2] linux2 Python 2.7.13 cwd: /home/dlezz/projects/robottelo-fork
[gw3] linux2 Python 2.7.13 cwd: …
```

[6.3] FIX CLI  test_lifecycleenvironment

---

robottelo.properties.sample
robottelo/config/base.py
tests/foreman/ui/test_ldapauthsource.py

Test results
```
pytest tests/foreman/ui/test_ldapauthsource.py::LDAPAuthSourceTestCase::test_positive_create_withidm_org_and_loc
============================================================= test session starts =================================================================
collected 5 items
tests/foreman/ui/test_ldapauthsource.py .
================================================================= 1 passed =================================================================
```

Added coverage for freeIPA LDAP auth

---

robottelo/ui/hosts.py
robottelo/ui/locators/base.py
robottelo/ui/locators/common.py
tests/foreman/ui/test_host.py

```
nosetests tests/foreman/ui/test_host.py -m test_positive_inherit_puppet
..
Ran 2 tests in 139.838s
OK
```

Add coverage for hostgroup inheritance functionality (BZ1414914)

---

tests/foreman/ui/test_hostgroup.py

https://bugzilla.redhat.com/show_bug.cgi?id=1254102
```python
py.test -v tests/foreman/ui/test_hostgroup.py -k test_negative_delete_with_discovery_rule
platform darwin -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /Users/andrii/workspace/env/bin/python
plugins: xdist-1.18.1, services-1.2.1, mock-1.6.2, cov-2.5.1
collected 12 items
2017-09-07 18:30:19 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings
tests/foreman/ui/test_hostgroup.py::HostgroupTestCase::test_negative_delete_with_discovery_rule <- robottelo/decorators/__init__.py PASSED
============================= 11 tests deselected …
```

Added UI test for deleting hostgroup with discovery rule assigned (BZ1254102)

---

tests/foreman/endtoend/test_ui_endtoend.py

issue #5253 
Test result 
```
pytest tests/foreman/endtoend/test_ui_endtoend.py::EndToEndTe
stCase::test_positive_puppet_install
========================================================== test session starts ==========================================================
====================================================== 1 passed in 607.81 seconds ======================================================
```

[6.2.z] Fix test_positive_puppet_install

---

tests/foreman/cli/test_organization.py
tests/foreman/ui/test_activationkey.py
tests/foreman/ui/test_contentview.py
tests/foreman/ui/test_gpgkey.py
tests/foreman/ui/test_hostcollection.py
tests/foreman/ui/test_organization.py
tests/foreman/ui/test_puppetmodule.py
tests/foreman/ui/test_syncplan.py

```
nosetests tests/foreman/ui/test_activationkey.py -m test_positive_search_scoped
.
Ran 1 test in 114.180s
OK
nosetests tests/foreman/ui/test_contentview.py -m test_positive_search_composite
.
Ran 1 test in 138.675s
OK
nosetests tests/foreman/ui/test_gpgkey.py -m test_positive_search_scoped
.
Ran 1 test in 56.132s
OK
nosetests tests/foreman/ui/test_hostcollection.py -m test_positive_add_host
.
Ran 1 test in 111.725s
OK
nosetests tests/foreman/ui/test_organization.py -m test_positive_search_scoped
. …
```

Add test coverage for scoped search functionality (BZ1259374)

---

robottelo/ui/locators/base.py
tests/foreman/ui/test_contentview.py

removed test covering not a bug https://bugzilla.redhat.com/show_bug.cgi?id=1367123
(new feature introduced and this bug and test are not needed any more)

[6.3] FIX UI content view add unpublished to composite

---

docs/api/tests.foreman.api.rst
tests/foreman/api/test_audit.py

```
nosetests tests/foreman/api/test_audit.py
...
Ran 3 tests in 176.453s
OK
```

Add basic audit test coverage

---

tests/foreman/ui/test_docker.py

[6.2.z] skip test BZ 1347658

---

tests/foreman/cli/test_host.py

cover: https://bugzilla.redhat.com/show_bug.cgi?id=1296662
```console
(sat-6.3) dl@DL:~/projects/redhat/robottelo$ pytest -v tests/foreman/cli/test_host.py::HostParameterTestCase
platform linux2 -- Python 2.7.13, pytest-3.2.2, py-1.4.34, pluggy-0.4.0 -- /home/dl/.pyenv/versions/2.7.13/envs/sat-6.3/bin/python2.7
rootdir: /home/dl/projects/redhat/robottelo, inifile:
collected 11 items                                                                                                      
2017-09-18 17:52:26 - conftest - DEBUG - Found WONTFIX in decorated tests ['1156555', '1269196', …
```

[6.3] Permission Parameter::view_params (BZ1296662)

---

tests/foreman/ui/test_docker.py

cherry-pick skip test BZ 1347658

---

robottelo/constants.py
robottelo/ui/locators/base.py
robottelo/ui/role.py
tests/foreman/ui/test_role.py

The locked roles have no link to click to view their resources and permissions, the only possible solution is to push the filters button to be redirected to Filters role page to get data from there.
test_positive_clone_builtin was randomly passing when selecting a non locked role, but when randomly select a locked one it fail, the test was refactored to choose randomly one locked and one unlocked role.
```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test -v tests/foreman/ui/test_role.py::RoleTestCase
rootdir: …
```

[6.3] FIX UI test_role locked

---

tests/foreman/ui/test_classparameters.py
tests/foreman/ui/test_variables.py

```
nosetests tests/foreman/ui/test_classparameters.py -m test_positive_update_with_long_priority_list
.
Ran 1 test in 160.010s
OK
```
```
nosetests tests/foreman/ui/test_variables.py -m test_positive_create_with_long_priority_list
.
Ran 1 test in 95.172s
OK
```

Verify that long priority list can be used for smart variables (BZ1458817)

---

robottelo/ui/base.py
robottelo/ui/locators/common.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_medium.py
tests/foreman/ui/test_subnet.py

```
nosetests tests/foreman/ui/test_host.py -m sort
.....
Ran 5 tests in 843.679s
OK
nosetests tests/foreman/ui/test_subnet.py -m sort
.S
Ran 2 tests in 103.232s
OK (SKIP=1)
nosetests tests/foreman/ui/test_medium.py -m sort
.
Ran 1 test in 79.717s
OK
```

Add test coverage for sorting functionality (BZ1268085)

---

robottelo/ui/repository.py
tests/foreman/ui/test_contentview.py

```
nosetests tests/foreman/ui/test_contentview.py -m test_positive_publish_with_repo_with_disabled_http
.
Ran 1 test in 144.374s
OK
```

Add coverage for cv publish procedure(BZ1355752)

---

tests/foreman/ui/test_syncplan.py

added skip on 1498793 for weekly ui syncplan test

---

robottelo/ui/base.py
tests/foreman/ui/test_host.py

```
nosetests tests/foreman/ui/test_host.py:LibvirtHostTestCase
..
Ran 2 tests in 320.889s
OK
```

Add test coverage for host with libvirt delete functionality (BZ1243223)

---

robottelo/vm.py

Lets finish the changes in automation-tools, avahi discovery is now running on Satellite (was on hypervisor)
Let me run some tests first ....

Discover VM's IP from Satellite (not from hypervisor)

---

robottelo/constants.py
robottelo/ui/environment.py
robottelo/ui/factory.py
robottelo/ui/locators/base.py
tests/foreman/ui/test_environment.py
tests/foreman/ui/test_location.py
tests/foreman/ui/test_organization.py

```
nosetests tests/foreman/ui/test_environment.py
......
Ran 6 tests in 336.294s
OK
```
All other tests were executed using debugger and some manual interactions as BZs are in assigned state

Add test coverage for organization, location and env entities (BZ1479736)

---

robottelo/cli/hostcollection.py
tests/foreman/cli/test_host_collection.py

```
nosetests tests/foreman/cli/test_host_collection.py
...S.................S....
Ran 26 tests in 1295.115s
OK (SKIP=2)
```

Improve host collection module and add some coverage (BZ1328925)

---

robottelo/constants.py
robottelo/ui/hostcollection.py
robottelo/ui/locators/base.py
robottelo/ui/locators/tab.py
tests/foreman/ui/test_hostcollection.py

cover : https://bugzilla.redhat.com/show_bug.cgi?id=1315280
```
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ pytest -v tests/foreman/ui/test_hostcollection.py::HostCollectionPackageManagementTest::test_positive_change_assigned_content
collected 1 item 
2017-09-29 12:06:51 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings …
```

[6.3] host collection change assigned content (BZ1315280)

---

tests/foreman/cli/test_remoteexecution.py

Based on the discussion on last friday, decorating by-hostname rex tests in cli, as they have working by-ip equivalents, are not currently supported by infrastructure and have expensive setups.

limiting rex tests to by_ip, cli phase

---

robottelo/ui/base.py
robottelo/ui/computeresource.py
robottelo/ui/gpgkey.py
robottelo/ui/locators/base.py
tests/foreman/ui/test_computeresource_rhev.py
tests/foreman/ui/test_contentview.py

```
nosetests tests/foreman/ui/test_computeresource_rhev.py -m test_positive_access_rhev_with_custom_profile
..
Ran 2 tests in 182.868s
OK
```
```
nosetests tests/foreman/ui/test_gpgkey.py -m test_positive_delete_key_for_product_with_repo
..
Ran 2 tests in 281.357s
OK
```
```
nosetests tests/foreman/ui/test_contentview.py -m test_positive_check_composite_cv_addition_list_versions
.
Ran 1 test in 135.030s
OK
```

Add get_element_value method to base class and add coverage(BZ1286033)

---

tests/foreman/cli/test_host.py

```
nosetests tests/foreman/cli/test_host.py -m test_positive_list_with_nested_hostgroup
.
Ran 1 test in 197.533s
OK
```

Add test coverage for host list functionality(BZ1427554)

---

robottelo/cli/factory.py
robottelo/cli/virt_who_config.py
robottelo/constants.py
robottelo/ui/locators/base.py
robottelo/ui/subscription.py
tests/foreman/ui/test_subscription.py

- Implement hypervisor Virtual Machine virt-who service config setup 
- qe_test_coverage:  https://bugzilla.redhat.com/show_bug.cgi?id=1395788
```
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ pytest -v tests/foreman/ui/test_subscription.py::SubscriptionTestCase::test_positive_view_VDC_guest_subscription_products
collected 1 item 
2017-10-09 17:59:13 - conftest - DEBUG - Deselect of WONTFIX BZs …
```

[6.3] VM virt-who config + BZ1395788 VDC guest subscriptions list of provided products and content

---

robottelo/constants.py
robottelo/ui/environment.py
robottelo/ui/factory.py
robottelo/ui/hostgroup.py
robottelo/ui/locators/base.py
tests/foreman/ui/test_computeresource_vmware.py

```
nosetests tests/foreman/ui/test_computeresource_vmware.py -m test_positive_apply_vmware_with_custom_profile_to_host
.
Ran 1 test in 105.428s
OK
```
```
nosetests tests/foreman/ui/test_environment.py
......
Ran 6 tests in 437.348s
OK
```

Add test coverage for vmware compute resource(BZ1249744)

---

robottelo/ui/contenthost.py
robottelo/ui/hostcollection.py
robottelo/ui/locators/base.py
robottelo/ui/locators/tab.py
tests/foreman/ui/test_hostcollection.py

Closes #5365
```
% pytest -v tests/foreman/ui/test_hostcollection.py -k 'HostCollectionPackageManagementTest' --html=/tmp/report.html
=============================================================== test session starts ===============================================================
platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /home/qui/code/venv/2/bin/python2
rootdir: /home/qui/code/robottelo, inifile:
plugins: xdist-1.18.1, services-1.2.1, mock-1.6.2, html-1.12.0, cov-2.3.1
collected 25 items 
2017-10-26 01:16:18 - conftest - DEBUG - Deselect of WONTFIX BZs is disabled in settings
tests/foreman/ui/test_hostcollection.py::HostCollectionPackageManagementTest::test_positive_add_subscription <- …
```

Fix UI/hostcollection tests

---

robottelo/ui/errata.py

Closes #5401 
```
pytestrunner.py -p pytest_teamcity /home/qui/code/robottelo/tests/foreman/ui/test_errata.py "-k ErrataTestCase and test_positive_filter"
============================= 17 tests deselected ==============================
================== 1 passed, 17 deselected in 818.17 seconds ===================
```

Update locators for errata UI helper.

---

tests/foreman/cli/test_classparameters.py

Fixes Integer random values should not start with zero

---

tests/foreman/cli/test_contentview.py

This test case must be refactored later on #5366

Moved test to destructuve tier as a workaround to #5366

---

tests/foreman/ui/test_contentview.py

```
nosetests tests/foreman/ui/test_contentview.py -m puppet_env
...
Ran 3 tests in 403.981s
OK
```

Add test coverage for content view puppet functionality(BZ1437110)

---

robottelo/constants.py

issue #5303 
Test results 
```
pytest tests/foreman/api/test_permission.py::PermissionTestCase::test_positive_search
========================================================== test session starts ==========================================================
tests/foreman/api/test_permission.py .
======================================================= 1 passed in 18.33 seconds ===========================================
```

Fixes new permission added - strata_api

---

docs/api/robottelo.ui.rst
docs/api/tests.foreman.ui.rst
robottelo/ui/audit.py
robottelo/ui/locators/base.py
robottelo/ui/session.py
tests/foreman/ui/test_audit.py

```
nosetests tests/foreman/ui/test_audit.py
....
Ran 4 tests in 382.144s
OK
```

Add test coverage for audit entity (BZ1425977)

---

robottelo/cleanup.py
robottelo/ssh.py
robottelo/ui/locators/base.py
tests/foreman/ui/test_contenthost.py
tests/foreman/ui/test_host.py

depends on https://github.com/SatelliteQE/nailgun/pull/452
```
nosetests tests/foreman/ui/test_host.py:LibvirtHostTestCase
..
Ran 2 tests in 1511.745s
OK
```
```
nosetests tests/foreman/ui/test_contenthost.py -m test_positive_check_ignore_facts_os_setting
.
Ran 1 test in 1103.312s
OK
```

Implement working end-to-end provisioning flow and add coverage for BZ1155704

---

tests/foreman/cli/test_setting.py

close #5552
Those can be done to achieve QE release criteria for 6.3 GA

Added low priority to test around email config through cli

---

robottelo/ui/hostgroup.py
robottelo/ui/locators/base.py
tests/foreman/ui/test_contentview.py

```
nosetests tests/foreman/ui/test_contentview.py -m test_positive_delete_with_kickstart_repo_and_host_group
.
Ran 1 test in 474.401s
OK
```

Add test coverage for cv delete procedure (BZ1417072)

---

tests/foreman/cli/test_computeresource_rhev.py

Test Results
```
pytest tests/foreman/cli/test_computeresource_rhev.py -m tier1
========================================================== test session starts ==========================================================
collected 16 items
tests/foreman/cli/test_computeresource_rhev.py .......
========================================================== 9 tests deselected ===========================================================
=============================================== 7 passed, 9 deselected  ===========================================
```

[6.3]Automated RHEV compute resource tier1

---

robottelo/cli/factory.py
tests/foreman/cli/test_hostgroup.py

```
nosetests tests/foreman/cli/test_hostgroup.py -m test_positive_create_with_synced_content
.
Ran 1 test in 461.746s
OK
```

Add test coverage for kickstart repository in host group functionality (BZ1415707)

---

robottelo/ui/locators/base.py
robottelo/ui/role.py
tests/foreman/ui/test_role.py

```
nosetests tests/foreman/ui/test_role.py -m permission
S...
Ran 4 tests in 295.474s
OK (SKIP=1)
```

Add test coverage for role permission functionality (BZ1360191)

---

tests/foreman/cli/test_oscap.py
tests/foreman/ui/test_oscapcontent.py

[6.3]Added coverage for BZ 1474172

---

robottelo/ui/computeresource.py
robottelo/ui/factory.py
robottelo/ui/hosts.py
robottelo/ui/locators/base.py
tests/foreman/ui/test_computeresource_rhev.py

See issue #5342 
```
pytest tests/foreman/ui/test_computeresource_rhev.py::RhevComputeResourceHostTestCase
platform linux2 -- Python 2.7.12, pytest-3.1.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/sjagtap/PycharmProjects/robottelo, inifile:
plugins: cov-2.3.1, xdist-1.15.0, services-1.2.1, wait-for-1.0.9, mock-1.6.2
collected 4 items 
2017-11-22 13:05:53 - conftest - DEBUG - Collected 4 test cases
tests/foreman/ui/test_computeresource_rhev.py ssss
=============================================================================================== 0 tests deselected …
```

Fixes all locator and changes to rhev compute profile. Fixes #5342

---

tests/foreman/ui/test_contentview.py

Close #5332 
```
(sat-6.3.0) odovz@bueno:~/projects/robottelo$ pytest -v tests/foreman/ui/test_contentview.py::ContentViewTestCase::test_positive_repo_count_for_composite_cv
======================================================================================= test session starts ========================================================================================
platform linux2 -- Python 2.7.12, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /home/odovz/venv/sat-6.3.0/bin/python2.7
rootdir: /home/odovz/projects/robottelo, inifile:
plugins: xdist-1.20.1, services-1.2.1, mock-1.6.3, forked-0.2, cov-2.5.1 …
```

Fix repositories count in composite content view test

---

tests/foreman/api/test_subnet.py

This PR is raised as a duplicate of PR #5426 as the branch from which PR is raised is no more accessible. And that happened due to fork on which the branch created has been deleted.
This also fixes the comments from the last PR #5426

[6.3 Feature] Parameterized Subnets API CRUDs automated

---

tests/foreman/cli/test_contentview.py

Close https://github.com/SatelliteQE/robottelo/issues/5396
```
(sat-6.3.0) odovz@bueno:~/projects/robottelo$ pytest -v tests/foreman/cli/test_contentview.py::ContentViewTestCase::test_positive_create_composite_with_component_ids tests/foreman/cli/test_contentview.py::ContentViewTestCase::test_negative_create_composite_with_component_ids
======================================================================================= test session starts ========================================================================================
platform linux2 -- Python 2.7.12, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /home/odovz/venv/sat-6.3.0/bin/python2.7
rootdir: /home/odovz/projects/robottelo, inifile:
plugins: xdist-1.20.1, services-1.2.1, mock-1.6.3, forked-0.2, cov-2.5.1 …
```

Fix create_composite_with_component_ids

---

tests/foreman/api/test_role.py
tests/foreman/ui/test_host.py

```
nosetests tests/foreman/ui/test_host.py -m test_positive_check_permissions_affect_create_procedure
.
Ran 1 test in 145.831s
OK
```
```
nosetests tests/foreman/api/test_role.py
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS...
Ran 48 tests in 46.451s
OK (SKIP=45)
```

Add test coverage for host permission functionality (BZ1293716)

---

tests/foreman/sys/test_hot_backup.py

[6.2.z] cherry-pick removing outdated stubs in backup

---

docs/api/tests.foreman.sys.rst
tests/foreman/sys/test_katello_certs_check.py

Added test stubs for Katello-certs-check utility

---

tests/foreman/cli/test_host.py

Fixed CaseImportance of test_negative_view_parameter_by_non_admin_user

---

tests/foreman/ui/test_contenthost.py

Fixed BZ id for test_positive_provisioning_host_link

---

tests/foreman/ui/test_contenthost.py

Changed bugzilla id test_positive_search_by_subscription_status

---

tests/foreman/sys/test_hot_backup.py
tests/foreman/sys/test_restore.py

[6.2.z] cherry-pick sync repo before backup

---

tests/foreman/cli/test_host.py
tests/foreman/cli/test_subscription.py
tests/foreman/cli/test_virt_who_config.py

close #5642 
@omaciel told me to merge this without review

Fixed Betelgeuse Token Values

---

tests/foreman/ui/test_activationkey.py

```
nosetests tests/foreman/ui/test_activationkey.py -m test_positive_access_non_admin_user
.
Ran 1 test in 269.997s
OK
```

Add test coverage for activation keys roles functionality (BZ1463813)

---

tests/foreman/data/hammer_commands.json

Issue #5224 
Test results
```
pytest tests/foreman/cli/test_hammer.py
=============================================================== test session starts ===============================================================
collected 1 item s
============================================================ 1 passed in 7.32 seconds =====================================================
```
```
E           AssertionError:
E           hammer bootdisk
E             Added subcommands:
E               * subnet
E
E           hammer bootdisk subnet (new command)
E             Added options:
E               * subnet
E               * force
E               * help
E               * sudo
E               * subnet-id
E               * file
``` …

Fix new cli hammer options

---

tests/foreman/sys/test_katello_certs_check.py

close #5684
I am merging this PR because it has not code impact and PQI must be updated.

Fixed CaseComponent token

---

robottelo/ui/hosts.py
robottelo/ui/locators/tab.py
tests/foreman/ui/test_remoteexecution.py

adding by ip versions of the ui remote execution tests and changing the provisioning server
related tp #4624

ui-rex-connect-by-ip

---

tests/foreman/cli/test_remoteexecution.py

rex cli fixed assertions

---

robottelo/decorators/__init__.py
tests/foreman/conftest.py

close #5644 
Marking @elyezer since he was curious about how to get the a marked bug on test collection. @omaciel  maybe interested as well ;)
I've added bugzilla ids as attribute to all decorated functions (see add_bugzilla_id) and introspected this attribute on test collection (see _extract_setup_class_ids).
Result on test to be deselected:
```console
(robottelo) [renzo@note robottelo]$ pytest tests/foreman/api/test_repository.py -k 'test_positive_sync'
=============================================== test session starts ===============================================
platform linux2 -- Python 2.7.14, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/renzo/PycharmProjects/robottelo, inifile:
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.3, cov-2.4.0
collected 72 items …
```

Fixed deselection of tests with skip_if_bug_open on setUpClass

---

robottelo/constants.py
tests/foreman/cli/test_repository.py

`+ few fixes`
```
nosetests tests/foreman/cli/test_repository.py -m file_repo
S...
Ran 4 tests in 87.327s
OK (SKIP=1)
```

Add test coverage for file repo functionality (BZ1446975)

---

tests/foreman/ui/test_login.py

```
nosetests tests/foreman/ui/test_login.py -m test_positive_login_with_different_passwords
.
Ran 1 test in 362.424s
OK
```
```
nosetests tests/foreman/ui/test_login.py -m test_positive_login_with_different_usernames
.
Ran 1 test in 314.140s
OK
```

Add more test coverage for login functionality

---

robottelo/ui/base.py
robottelo/ui/scparams.py
robottelo/ui/smart_variable.py

Close #5617 
Executed on saucelab:
```
nosetests tests/foreman/ui/test_variables.py -m matcher_attribute_priority
..
Ran 2 tests in 1003.962s
OK
```
```
nosetests tests/foreman/ui/test_classparameters.py -m matcher_attribute_priority
..
Ran 2 tests in 953.688s
OK
```

Fix issue with onchange event not triggered on saucelab

---

tests/foreman/ui/test_packages.py

Close #5719
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1514457 (Thanks Oleg for it:) )

skip package test because of the bug

---

robottelo/api/utils.py
robottelo/config/base.py
robottelo/constants.py
robottelo/ui/computeresource.py
tests/foreman/ui/test_computeresource_rhev.py

```
pytest tests/foreman/ui/test_computeresource_rhev.py::RhevComputeResourceHostTestCase -k test_positive_provision_rhev_with_
platform linux2 -- Python 2.7.12, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/sjagtap/PycharmProjects/robottelo, inifile:
plugins: cov-2.3.1, xdist-1.15.0, mock-1.6.3, services-1.2.1, wait-for-1.0.9 …
```

Fixes issues with rhev provisioning

---

tests/robottelo/test_decorators.py

Depends on SatelliteQE/robozilla#38 , new robozilla release and updated requirements file.
Test results with changes from SatelliteQE/robozilla#38:
```python
pytest tests/robottelo/test_decorators.py -k test_complete_bug_workflow
platform darwin -- Python 2.7.13, pytest-3.2.3, py-1.5.2, pluggy-0.4.0
plugins: xdist-1.20.1, services-1.2.1, mock-1.6.3, forked-0.2, cov-2.5.1
collected 51 items
tests/robottelo/test_decorators.py .
============================= 50 tests deselected ==============================
=================== 1 passed, 50 deselected in 0.45 seconds ====================
```

Add new scenario to BZ workflow test

---

tests/foreman/cli/test_contentview.py

Create two variants from this test influenced by bug: https://bugzilla.redhat.com/show_bug.cgi?id=1470765
* one with default location
* one with custom location
```
(sat-6.3) dlezz@dlezz:~/projects/robottelo-fork$ pytest tests/foreman/cli/test_contentview.py -v -k "test_positive_sub_host_with_restricted_user_perm"
=================================================================================================== test session starts ====================================================================================================
platform linux2 -- Python 2.7.14, pytest-3.2.3, py-1.5.2, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/2.7.14/envs/sat-6.3/bin/python2.7
shared_function enabled - ON - scope: ffff - storage: file
rootdir: /home/dlezz/projects/robottelo-fork, …
```

[6.3] fix test_positive_subscribe_host_with_restricted_user_permissions

---

tests/foreman/sys/test_restore.py

Previous cherry-pick caused some trouble, plus restore messages changed a bit,  fixing in this PR. Tests:
```
tests/foreman/sys/test_restore.py::RestoreTestCase::test_negative_restore_no_directory PASSED
tests/foreman/sys/test_restore.py::RestoreTestCase::test_negative_restore_nonexistent_directory PASSED
tests/foreman/sys/test_restore.py::RestoreTestCase::test_negative_restore_with_empty_directory PASSED
tests/foreman/sys/test_restore.py::RestoreTestCase::test_positive_restore_from_offline_backup PASSED
tests/foreman/sys/test_restore.py::RestoreTestCase::test_positive_restore_from_online_and_incremental FAILED
```
The one failure is a product problem, being discussed in bz 1509425#c18

6.2 restore -- fix file check

---

tests/foreman/sys/test_hot_backup.py
tests/foreman/sys/test_restore.py

1. Increased timeout for `satellite-backup` command as it takes around 3 mins locally on fresh satellite, so no surprise tests are failing on jenkins with
```
SSHCommandTimeoutError: ssh command: satellite-backup -y /tmp/RzYtzVsIcA --logical-db-backup   did not respond in the predefined time (timeout=300)
```
error
2. Replaced tearDownClass with tearDown, this way we'll ensure services are started after each test and will fix failures like
```
ConnectionError: HTTPSConnectionPool(host='example.com', port=443): Max retries exceeded with url: /api/v2/users (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f685c474f90>: Failed to establish a new connection: [Errno 111] Connection refused',))
```
3. Incremental online backup is not working for 6.3 per …

Fix hot backup/restore tests

---

tests/foreman/ui/test_discoveredhost.py

One more failing test due to #5662
Missed in #5734

Skip test_positive_update_name

---

tests/foreman/data/hammer_commands.json

close #5744
Test Result:
```console
=============================================== test session starts ===============================================
platform linux2 -- Python 2.7.14, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /home/renzo/PycharmProjects/robottelo, inifile:
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.3, cov-2.4.0
collected 1 item                                                                                                   
2018-01-03 14:35:56 - conftest - DEBUG - BZ deselect is disabled in settings
============================================ 1 passed in 9.37 seconds =============================================
```
This PR can be reviewed but I am just confirmed the …

Fixed Hammer Options

---

tests/foreman/sys/test_rename.py

Some stubbed tests appeared as passing in automation results, fixing

stubbed tests incorectly green

---

robottelo/cli/factory.py
tests/foreman/cli/test_ostreebranch.py

close #5769
related to #5305
Test Results:
```console
$ pytest tests/foreman/cli/test_ostreebranch.py
=============================================== test session starts ===============================================
platform linux2 -- Python 2.7.14, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/renzo/PycharmProjects/robottelo, inifile:
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.3, cov-2.4.0
collected 6 items                                                                                                 
2018-01-10 15:55:58 - conftest - DEBUG - BZ deselect is disabled in settings
tests/foreman/cli/test_ostreebranch.py ......                                                               [100%] …
```

Fixed OSTree Cli Tests to use isolated user

---

tests/foreman/installer/test_installer.py

Added installer options from satellite 6.3

---

tests/foreman/sys/test_rename.py

issue #5529 
test result (standalone job 1062):
```
platform linux2 -- Python 2.7.13, pytest-3.4.0, py-1.5.2, pluggy-0.6.0 -- /home/jenkins/shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/bin/python2.7
rootdir: /home/jenkins/workspace/satellite6-standalone-automation, inifile:
plugins: xdist-1.22.0, services-1.2.1, mock-1.6.3, forked-0.2
collecting ... collected 5 items
2018-02-14 08:44:41 - conftest - DEBUG - Collected 5 test cases
tests/foreman/sys/test_rename.py::RenameHostTestCase::test_positive_rename_satellite PASSED [100%]
generated xml file: /home/jenkins/workspace/satellite6-standalone-automation/foreman-results.xml …
```

test for katello-change-hostname

---

tests/foreman/sys/test_rename.py

cherry picking from #5824  to make it run against 6.3.z
test result (standalone job 1062):
```
platform linux2 -- Python 2.7.13, pytest-3.4.0, py-1.5.2, pluggy-0.6.0 -- /home/jenkins/shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/bin/python2.7
rootdir: /home/jenkins/workspace/satellite6-standalone-automation, inifile:
plugins: xdist-1.22.0, services-1.2.1, mock-1.6.3, forked-0.2
collecting ... collected 5 items
2018-02-14 08:44:41 - conftest - DEBUG - Collected 5 test cases
tests/foreman/sys/test_rename.py::RenameHostTestCase::test_positive_rename_satellite PASSED [100%]
generated xml file: …
```

[6.3.z] cherry-pick test for katello-change-hostname (#5824)

---

robottelo/api/utils.py
tests/foreman/ui/test_activationkey.py

Few API helpers were implemented inside activation keys test class, moved them to api utils as i need them in different module. Also resolved few small issues with them like too small default timeout for rh repo sync etc.
Test results (forgot to install fake manifest at first):
```python
pytest -v tests/foreman/ui/test_activationkey.py
platform darwin -- Python 2.7.13, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- /Users/andrii/workspace/env/bin/python
plugins: wait-for-1.0.9, xdist-1.21.0, services-1.2.1, mock-1.6.3, forked-0.2, cov-2.5.1
collected 41 items
2018-03-16 11:44:18 - conftest - …
```

Moved API helpers from AK test class to utils, resolved few issues

---

robottelo/ssh.py

Python 3 is coming

---

robottelo/config/base.py
robottelo/datafactory.py
robottelo/ssh.py
tests/robottelo/test_settings.py

Just cherry-picks from master for python3

Py3 sat63z

---

tests/foreman/cli/test_lifecycleenvironment.py

cherry-pick of https://github.com/SatelliteQE/robottelo/pull/5879

[6.3.z] fixes test_positive_list_with_pagination test for py3.6

---

.travis.yml
setup.py
tox.ini

Removed Python 2 references on Travis, Tox and setup.py

---

tests/foreman/cli/test_contentview.py
tests/foreman/cli/test_errata.py

Fix test for py3 #5884

---

tests/foreman/data/hammer_commands.json

Add locations/organizations options to hammer architecture subcommands

---

robottelo/config/base.py

Signed-off-by: Kedar Bidarkar <kbidarka@redhat.com>

make use of six.iteritems

---

tests/foreman/api/test_template.py
tests/foreman/cli/test_template.py

API and CLI Stubs for 6.4 feature - Foreman Templates out of Tech Preview

[6.4 Feature] Foreman Templates out of Tech Preview Stubs

---

robottelo/constants.py
tests/foreman/ui/test_user.py
tests/foreman/ui_airgun/test_user.py

```
py.test /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_user.py 
platform linux2 -- Python 2.7.14, pytest-3.4.0, py-1.5.3, pluggy-0.6.0
collected 6 items                                                                                                                                                                            
2018-04-27 16:39:04 - conftest - DEBUG - BZ deselect is disabled in settings …
```

Move some User tests to new framework

---

robottelo/ui/contenthost.py
tests/foreman/ui/test_hostcollection.py

Fix: TypeError: 'float' object cannot be interpreted as an integer

---

tests/foreman/ui_airgun/test_activationkey.py

Per SatelliteQE/airgun#80
```python
pytest -v tests/foreman/ui_airgun/test_activationkey.py
platform darwin -- Python 3.6.4, pytest-3.4.0, py-1.5.3, pluggy-0.6.0 -- /Users/andrii/workspace/py3a/bin/python3.6
plugins: wait-for-1.0.9, xdist-1.22.0, services-1.2.1, mock-1.6.3, forked-0.2, env-0.6.2
collected 25 items
2018-05-03 14:08:05 - conftest - DEBUG - BZ deselect is disabled in settings
tests/foreman/ui_airgun/test_activationkey.py::test_positive_create PASSED [  4%]
tests/foreman/ui_airgun/test_activationkey.py::test_positive_delete PASSED [  8%] …
```

Updated UI AK tests according to latest airgun changes

---

tests/foreman/cli/test_remoteexecution.py
tests/foreman/ui/test_remoteexecution.py

UI/CLI 
(Devs: API is tested by CLI test anyway)

Ansible REX stubs

---

robottelo/test.py
tests/foreman/api/test_classparameters.py
tests/foreman/cli/test_contentview.py
tests/foreman/cli/test_docker.py
tests/foreman/cli/test_domain.py
tests/foreman/cli/test_host.py
tests/foreman/cli/test_subnet.py
tests/foreman/installer/test_installer.py
tests/foreman/ui/test_activationkey.py
tests/foreman/ui/test_classparameters.py
tests/foreman/ui/test_contentview.py
tests/foreman/ui/test_setting.py
tests/foreman/ui/test_template.py

Fixes #5883 for 6.3.z
Cherry pick https://github.com/SatelliteQE/robottelo/pull/5903 and https://github.com/SatelliteQE/robottelo/pull/5898

[6.3.z] AttributeError: 'dict' object has no attribute 'iteritems'

---

tests/foreman/ui/test_computeresource_rhev.py

[6.3] Fix missing decode() in python3 for requests content being bytes

---

tests/foreman/cli/test_role.py

[6.3.z] fix invalid value for Integer

---

tests/foreman/ui/test_computeresource_rhev.py

Test Results: /view/Satellite 6/job/satellite6-standalone-automation/1165/console

Rhev testcase fixes issue #5971

---

tests/foreman/rhai/test_rhai.py

- TCs related to feature - Insights via Ansible
- TCs filling gap in testing Insights generally

Insights Deployment via Ansible stubs

---

robottelo/constants.py

Fixes #5983 
```
pytest tests/foreman/api/test_permission.py::PermissionTestCase::test_positive_search
=============================================================== test session starts ===============================================================
tests/foreman/api/test_permission.py .                                                                                                      [100%]
============================================================ 1 passed in 13.63 seconds ===========================================================
```

Added new types and permissions

---

tests/foreman/cli/test_auth.py

[6.3] cherry-pick hammer auth test for upgrade

---

tests/foreman/rhai/test_rhai.py

Signed-off-by: Kedar Bidarkar <kbidarka@redhat.com>

Fixed the stubbed import typo

---

tests/foreman/api/test_contentview.py

Signed-off-by: Kedar Bidarkar <kbidarka@redhat.com>

Add the bug_type arg to skip_if_bug_open decorator

---

tests/foreman/ui/test_product.py
tests/foreman/ui_airgun/test_product.py

```
py.test /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_product.py 
platform linux2 -- Python 2.7.14, pytest-3.4.0, py-1.5.3, pluggy-0.6.0
collected 1 item                                                                                                                                                                             
2018-05-08 12:48:48 - conftest - DEBUG - BZ deselect is disabled in settings …
```

Move one product test to new framework

---

Makefile

Cherry pick of https://github.com/SatelliteQE/robottelo/pull/5938

[6.3.z] cherry-pick adding make test-foreman-upgrade

---

Makefile

[6.2.z] cherry-pick adding make test-foreman-upgrade

---

robottelo/api/utils.py
tests/foreman/api/test_syncplan.py
tests/foreman/cli/test_syncplan.py
tests/foreman/ui/test_syncplan.py

Fixes the task timeout caused in Syncplan tests

---

tests/foreman/longrun/test_inc_updates.py

Aims to prevent the corner case from #6012

test inc update - added errata applicability

---

tests/foreman/ui_airgun/test_computeresource.py

First attempt to implement tests for compute resource

---

tests/foreman/ui/test_repository.py
tests/foreman/ui_airgun/test_repository.py

```
py.test /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_repository.py 
collected 4 items                                                                                                                                                                            
2018-06-08 15:43:21 - conftest - DEBUG - BZ deselect is disabled in settings …
```

Port repo discovery tests

---

tests/foreman/cli/test_subscription.py

https://github.com/SatelliteQE/satellite6-upgrade/pull/174

Removing upgrade marker in-favor of upgrade scenario test

---

tests/foreman/longrun/test_inc_updates.py

[6.3.z] cherry pick - test inc update - added errata applicability

---

tests/foreman/api/test_operatingsystem.py

See upstream commit:
https://github.com/theforeman/foreman/commit/133bba3f20853efe4add97225901fab8b76e167a

MD5 hashed password is not supported now

---

tests/foreman/api/test_contentaccess.py
tests/foreman/api/test_foremantask.py
tests/foreman/api/test_role.py
tests/foreman/api/test_subnet.py
tests/foreman/api/test_subscription.py
tests/foreman/cli/test_capsule.py
tests/foreman/cli/test_capsule_installer.py
tests/foreman/cli/test_computeresource_ec2.py
tests/foreman/cli/test_computeresource_osp.py
tests/foreman/cli/test_computeresource_rhev.py
tests/foreman/cli/test_computeresource_vmware.py
tests/foreman/cli/test_contentaccess.py
tests/foreman/cli/test_ldapauthsource.py
tests/foreman/cli/test_satellitesync.py
tests/foreman/longrun/test_oscap.py
tests/foreman/ui/test_syncplan.py

Tests that are removed are covered by real entities on upgrade framework, eg: like Fake manifest, Capsules.
Tests that are added are either newly automated or part of new feature

Added and removed tests to/from upgrade

---

robottelo/constants.py

TemplateInvocation -> view_template_invocations

New permission in 6.4.0 snap 9

---

tests/foreman/api/test_contentview.py

[6.3] cherry-pick fix test long name CV publish

---

robottelo/constants.py

[cherry pick 6.3.z] updated rhel-server repo

---

tests/foreman/ui/test_host.py
tests/foreman/ui_airgun/test_host.py

Depends on:
https://github.com/SatelliteQE/airgun/pull/117
and
https://github.com/SatelliteQE/nailgun/pull/507
```
py.test /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_repository.py::test_positive_resynchronize_rpm_repo …
```

Port few host tests

---

robottelo/constants.py

Successful runs:
[PermissionTestCase.log](https://github.com/SatelliteQE/robottelo/files/2190418/PermissionTestCase.log)

More permissions were changed

---

tests/foreman/data/hammer_commands.json

```
$ py.test -k test_positive_all_options test_hammer.py 
===================================== test session starts ======================================
platform linux -- Python 3.6.5, pytest-3.6.1, py-1.5.3, pluggy-0.6.0
rootdir: /home/rplevka/work/rplevka/robottelo, inifile:
plugins: wait-for-1.0.9, xdist-1.22.2, services-1.2.1, mock-1.6.3, forked-0.2
collecting 1 item                                                                              2018-07-17 11:10:45 - conftest - DEBUG - BZ deselect is disabled in settings
collected 1 item                                                                               
test_hammer.py .                                                                         [100%] …
```

added ovirt-quota options to test_hammer_all_options test

---

tests/foreman/cli/test_contentview.py
tests/foreman/cli/test_docker.py
tests/robottelo/test_hammer.py

Snap10:
```
Content Counts:            
Docker Manifest Lists: 0
Docker Manifests:      0
Docker Tags:           0
```
Snap11:
```
Content Counts:            
Container Image Manifest Lists: 0
Container Image Manifests:      0
Container Image Tags:           0
```

String changed - KeyError: 'docker-manifests'

---

tests/foreman/ui/test_usergroup.py
tests/foreman/ui_airgun/test_usergroup.py

Port tier2 tests to AirGun.
Requires [AirGun PR #148](https://github.com/SatelliteQE/airgun/pull/148) to be merged.

Port User Groups test to AirGun

---

tests/foreman/ui_airgun/test_puppetclass.py
tests/foreman/ui_airgun/test_smartvariable.py

```
py.test /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_puppetclass.py 
collected 1 item                                                                                                                                                                             
2018-07-17 15:01:34 - conftest - DEBUG - BZ deselect is disabled in settings …
```

Add puppet class and smart variable functionality

---

robottelo/constants.py
tests/foreman/ui_airgun/test_operatingsystem.py

```
py.test /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_operatingsystem.py 
collected 4 items                                                                                                                                                                            
2018-07-19 21:16:08 - conftest - DEBUG - BZ deselect is disabled in settings …
```

Change OS module according to new standard

---

tests/foreman/ui_airgun/test_computeresource.py

API doesn't support manually specifying cert so it's necessary to do it through WebUI.

Workarounding the issue with our automation where the RHEV instance supplies incorrect cert so the connection fails.

---

robottelo/ui/locators/base.py
robottelo/ui/locators/menu.py
robottelo/ui/navigator.py
robottelo/ui/rhai.py
robottelo/ui/session.py
tests/foreman/rhai/test_rhai.py

Added model pages for RHAI Rules, Planner, Actions and Help. Extended `test_navigation` for all pages in RHAI.

New RHAI pages

---

robottelo/constants.py
tests/foreman/api/test_template.py

This PR contains:
1. The 3 Tier1 tests of import and export to test that basic functionality works. These will be deleted ones those tests will be ported to minitest.
2. Tier2 and Tier3 tests are automated.

[6.4 Feature] Automate Foreman Templates API

---

tests/foreman/cli/test_setting.py

Fixes #5557 
Fixes #5558 
Fixes #5559 
Result:
```
$ pytest tests/foreman/cli/test_setting.py -k test_positive_update_email_reply_address 
========================================================================================================================= test session starts ==========================================================================================================================
collecting 18 items                                                                                                                                                                                                                                                   
collected 18 items / 17 deselected …
```

automated few test cases in test_setting:

---

tests/foreman/cli/test_computeresource_rhev.py

More Info: https://bugzilla.redhat.com/show_bug.cgi?id=1602835

Skip the CLI RHV testcases due to BZ 1602835

---

Pipfile
Pipfile.lock
robottelo/ssh.py
tests/foreman/cli/robottelo.log

**Fixed the keyword nad positional arguments mismatch issue**
**Test Result :** 
```
root@okhatavk robottelo (fix_get_sftp_session) $ pytest tests/foreman/cli/test_contentview.py -v -k "test_positive_delete_version_by_name"
platform linux -- Python 3.4.8, pytest-3.6.1, py-1.5.4, pluggy-0.6.0 -- /root/.local/share/virtualenvs/robottelo-3y-ct8Zt/bin/python3.4m
rootdir: /home/okhatavk/Satellite/robottelo, inifile:
plugins: wait-for-1.0.9, xdist-1.22.5, services-1.2.1, mock-1.6.3, forked-0.2, cov-2.5.1
collecting 100 items …
```

Fixed the keyword nad positional arguments mismatch issue

---

tests/foreman/ui_airgun/test_jobtemplate.py

```
py.test /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_jobtemplate.py 
collected 3 items                                                                                                                                                                            
2018-08-10 16:51:23 - conftest - DEBUG - BZ deselect is disabled in settings …
```

Add few tests for Job Template

---

tests/foreman/ui_airgun/test_operatingsystem.py

```
py.test /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_operatingsystem.py 
collected 5 items                                                                                                                                                                            
2018-08-15 13:23:40 - conftest - DEBUG - BZ deselect is disabled in settings …
```

Add test for OS template functionality

---

robottelo/ssh.py

Fixed the keyword and positional arguments mismatch issue.

fixed keyword and positional arguments mismatch issue

---

tests/foreman/api/test_host.py

fixes #6160 
result:
```pytest tests/foreman/api/test_host.py -v -k "test_positive_create_with_inherited_params"
============================================================= test session starts =============================================================
platform linux -- Python 3.6.6, pytest-3.4.0, py-1.5.3, pluggy-0.6.0 -- /home/pondrejk/Envs/robottelo-py3-master/bin/python3
rootdir: /home/pondrejk/Documents/robottelo, inifile:
collected 78 items                                                                                                                            
2018-08-13 19:09:23 - conftest - DEBUG - BZ deselect is disabled in settings …
```

test for inherited parameters now understands global params

---

tests/foreman/cli/test_discoveredhost.py

- Collecting discovery tests from CLI as we are not running UI tests for sat 6.4.

Added discovery tests for upgrade

---

tests/foreman/ui/test_oscapcontent.py
tests/foreman/ui_airgun/test_oscapcontent.py

@oshtaier  or @abalakh  please review.

adding test to OpenSCAP content entity in Airgun

---

tests/foreman/ui/test_subnet.py
tests/foreman/ui_airgun/test_subnet.py

```
py.test /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_subnet.py 
collected 3 items                                                                                                                                                                            
2018-08-21 13:56:38 - conftest - DEBUG - BZ deselect is disabled in settings …
```

Port subnet test

---

docs/conf.py
robottelo/products.py
tests/foreman/ui/test_dashboard.py
tests/foreman/ui_airgun/test_dashboard.py

```
py.test /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_dashboard.py 
collected 8 items                                                                                                                                                                            
2018-09-11 17:13:53 - conftest - DEBUG - BZ deselect is disabled in settings …
```

Port dashboard tests

---

robottelo/vm.py
tests/foreman/ui_airgun/conftest.py
tests/foreman/ui_airgun/test_rhai.py

Requires ~~https://github.com/SatelliteQE/airgun/pull/181~~ and ~~https://github.com/SatelliteQE/airgun/pull/187~~

test_positive_register_client_to_rhai ported to airgun

---

tests/foreman/endtoend/test_api_endtoend.py

Fixes #6277 
Test Result:
```
$ pytest tests/foreman/endtoend/test_api_endtoend.py::AvailableURLsTestCase::test_positive_get_links 
collecting 1 item                                                                                                                                                      
collected 1 item                                                                                                                                                       
tests/foreman/endtoend/test_api_endtoend.py . …
```

Fixes endtoend.test_api_endtoend.AvailableURLsTestCase

---

tests/foreman/cli/test_remoteexecution.py

Test Result:
```
$ pytest tests/foreman/cli/test_remoteexecution.py::AnsibleREXTestCase -k test_positive_run_job 
collecting 9 items                                                                                                                                                     
collected 9 items / 8 deselected                                                                                                                                       
tests/foreman/cli/test_remoteexecution.py .                                                                                                                      [100%] …
```

test_remoteexecution.py::AnsibleREXTestCase::test_positive_run_job

---

tests/foreman/cli/test_vm_install_products_package.py
tests/foreman/ui/test_ansible.py

Fixes "Update test to have case Importance #6261"

---

tests/foreman/ui_airgun/test_computeresource.py
tests/foreman/ui_airgun/test_ldap_authentication.py
tests/foreman/ui_airgun/test_partitiontable.py
tests/foreman/ui_airgun/test_rhai.py
tests/foreman/ui_airgun/test_smartvariable.py
tests/foreman/ui_airgun/test_usergroup.py

Partially resolve https://github.com/SatelliteQE/robottelo/issues/6291
testimony --tokens="bz, caseautomation, casecomponent, caseimportance, caselevel, caseposneg, customerscenario, expectedresults, id, requirement, setup, subtype1, steps, teardown, testtype, upstream" --minimum-tokens="id, requirement, caseautomation, caselevel, casecomponent, testtype, caseimportance, upstream" validate tests/foreman/ui_airgun
Total number of tests: 237
Total number of invalid docstrings: 52 (21.94%)
Test cases with no docstrings: 52 (21.94%)
Test cases missing minimal docstrings: 52 (21.94%)
About so called "tier1 tests" - we need to think in other PR
```
py.test -v /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_computeresource.py -k _resource_ …
```

fixing docstrings and compute resource tests

---

tests/foreman/ui/test_oscappolicy.py
tests/foreman/ui_airgun/test_oscappolicy.py

test results 
```
platform linux -- Python 3.6.6, pytest-3.4.0, py-1.5.3, pluggy-0.6.0
rootdir: /home/tstrych/Documents/robottelo, inifile:
collected 4 items2018-09-04 18:09:09 - conftest - DEBUG - Collected 4 test cases
test_oscappolicy.py                                                  [100%]
============================== 0 tests deselected ==============================
========================== 4 passed in 447.02 seconds ==========================
```

tests to OSCAP Policy entity - Airgun

---

tests/foreman/ui/test_ansible.py

cherry picked "Update test to have case Importance #6261" to 6.3.z

---

tests/foreman/ui/test_docker.py
tests/foreman/ui_airgun/test_containerimagetag.py

@oshtaier please review,
test results:
```
platform linux -- Python 3.6.6, pytest-3.4.0, py-1.5.3, pluggy-0.6.0
rootdir: /home/tstrych/Documents/robottelo, inifile:
collected 2 items2018-10-03 15:50:14 - conftest - DEBUG - Collected 2 test cases
test_containerimagetag.py                                              [100%]
============================== 0 tests deselected ==============================
========================== 2 passed in 271.89 seconds ==========================
```

test to container image tag entity, Airgun

---

tests/foreman/api/test_template.py

Fix Template Import and Export logging issue

---

tests/foreman/api/test_host.py

Fixes #6272 
Test Result:
```
$ pytest tests/foreman/api/test_host.py -k test_positive_update_puppet_class
collected 78 items / 77 deselected                                                                                                                                     
tests/foreman/api/test_host.py .                                                                                                                                 [100%]
============================================================== 1 passed, 77 deselected in 108.87 seconds ===============================================================
```

Fixes "api/test_host.py::HostTestCase::test_positive_update_puppet_class"

---

tests/upgrade/test_role.py

This adds 2 scenarios from :
Bug#comment  -> https://bugzilla.redhat.com/show_bug.cgi?id=1621029#c11

Add Default Role update fails upgrade scenario

---

tests/foreman/ui_airgun/test_jobinvocation.py

```
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v tests/foreman/ui_airgun/test_jobinvocation.py
============================================ test session starts =============================================
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.5.4, pluggy-0.6.0 -- /home/dlezz/.pyenv/versions/3.6.6/envs/robottelo/bin/python
shared_function enabled - ON - scope: ffff - storage: file
plugins: wait-for-1.0.9, xdist-1.22.5, services-1.3.0, mock-1.10.0, forked-0.2, cov-2.5.1
collecting 2 items                                                                                           2018-10-08 18:40:16 - conftest - DEBUG - BZ deselect is disabled in settings
collected 2 items …
```

[6.4] FIX UI airgun job_invocation

---

tests/foreman/cli/test_activationkey.py

Fixes #5989 
Test Result:
```
$ pytest tests/foreman/cli/test_activationkey.py -k "test_negative_create_with_usage_limit_with_not_integers or test_negative_create_with_invalid_name"
collecting 52 items                                                                                                                                                    
collected 52 items / 50 deselected                                                                                                                                     
tests/foreman/cli/test_activationkey.py .. …
```

Fixes assertion errors of CLI test_activationkey.py

---

Makefile

[DNM] untill all the errors are fixed.

Added ui_airgun to testimony check

---

robottelo/constants.py
tests/foreman/ui/test_bookmark.py
tests/foreman/ui_airgun/test_bookmark.py

```python
pytest -v tests/foreman/ui_airgun/test_bookmark.py
platform darwin -- Python 3.6.4, pytest-3.6.1, py-1.6.0, pluggy-0.6.0 -- /Users/andrii/workspace/py3a/bin/python3.6
plugins: xdist-1.22.0, services-1.2.1, mock-1.10.0, forked-0.2, env-0.6.2
collecting 1 item                                                              2018-10-08 17:00:35 - conftest - DEBUG - BZ deselect is disabled in settings
tests/foreman/ui_airgun/test_bookmark.py::test_positive_create_bookmark_public PASSED [100%]
========================== 1 passed in 141.74 seconds …
```

Ported first airgun Bookmarks test

---

requirements.txt
robottelo/api/utils.py
robottelo/helpers.py
robottelo/ui/computeresource.py
tests/foreman/cli/test_computeresource_rhev.py
tests/foreman/longrun/test_provisioning_computeresource.py

1. Adds a new requirement https://github.com/ManageIQ/wrapanapi
2. Added e2e Test for RHV and Vmware 
3. Wrapanapi will help validate the created VM's on RHV and Vmware

Add t3 tests for provisioning for RHV and Vmware

---

tests/foreman/api/test_role.py

Pr includes; 
1. Helper functions to reduce the repetitive code, where the code is prerequisites for test
2. Automated remaining API tests, totaling 17

[6.3] Canned Role API remaining tests Automated

---

tests/foreman/ui_airgun/test_dashboard.py

```
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v tests/foreman/ui_airgun/test_dashboard.py::test_positive_host_configuration_status 
============================================ test session starts =============================================
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.5.4, pluggy-0.6.0 -- /home/dlezz/.pyenv/versions/3.6.6/envs/robottelo/bin/python
shared_function enabled - ON - scope: ffff - storage: file
plugins: wait-for-1.0.9, xdist-1.22.5, services-1.2.1, mock-1.10.0, forked-0.2, cov-2.5.1
collecting 1 item                                                                                            2018-09-28 11:05:09 - conftest - DEBUG - BZ deselect is disabled in …
```

[6.4] FIX UI Dashboard test_positive_host_configuration_status

---

tests/foreman/sys/test_rename.py

rename command name updated

---

requirements.txt

Upgrade 64less requirement for robottelo < = 6.4.z

---

robottelo/cli/virt_who_config.py

Added deploy method to cli.VirtWhoConfig

---

tests/upgrades/test_client.py

Async key error fix 6.2.z

---

tests/upgrades/test_client.py

Fix async key error in 6.3.z

---

tests/foreman/cli/test_remoteexecution.py

makes the setupClass for ansible rex tests the same as for regular rex, should fix #6312

ansible rex setupclass update

---

robottelo/api/utils.py
tests/foreman/ui/test_discoveredhost.py
tests/foreman/ui_airgun/conftest.py
tests/foreman/ui_airgun/test_discoveredhost.py

```bash
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v tests/foreman/ui_airgun/test_discoveredhost.py 
============================================ test session starts =============================================
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.5.4, pluggy-0.6.0 -- /home/dlezz/.pyenv/versions/3.6.6/envs/robottelo/bin/python
shared_function enabled - ON - scope: ffff - storage: file
plugins: wait-for-1.0.9, xdist-1.22.5, services-1.2.1, mock-1.6.3, forked-0.2, cov-2.5.1
collecting 10 items                                                                                          2018-09-06 13:21:47 - conftest - DEBUG - BZ deselect is disabled in settings
collected 10 items …
```

[6.5] UI port airgun discovered hosts tests

---

robottelo.properties.sample
robottelo/config/base.py

No need for these settings as hammer import was removed since Sat6.3
Fixes #5061

Remove Transitions settings

---

requirements.txt

Automation tools requirement as Upgrade dependency

---

tests/foreman/ui_airgun/test_product.py

Closes #6391
```
py.test -v /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_product.py 
platform linux -- Python 3.6.5, pytest-3.4.0, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python3.6
collected 2 items                                                                                                                                                                            
2018-11-15 11:41:51 - conftest - DEBUG - BZ deselect is …
```

Add product end to end scenario

---

tests/foreman/cli/test_oscap.py

Test result:
Automation of https://bugzilla.redhat.com/show_bug.cgi?id=1485805

Added one test for compliance policies

---

tests/foreman/cli/test_oscap.py

Reverts SatelliteQE/robottelo#6264
Initial PR had DO NOT MERGE label and not resolved comment
@alda519 any reason you do that?

Revert "Added one test for compliance policies"

---

tests/foreman/ui/test_lifecycleenvironment.py
tests/foreman/ui_airgun/test_lifecycleenvironment.py

Closes #6383
```
py.test -v /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_lifecycleenvironment.py 
platform linux -- Python 3.6.5, pytest-3.4.0, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python3.6
collected 6 items                                                                                                                                                                            
2018-11-19 18:47:21 - conftest - DEBUG - BZ …
```

Add lce end to end scenario + 1 port

---

tests/foreman/ui_airgun/test_dashboard.py
tests/foreman/ui_airgun/test_subnet.py

```
py.test -v /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_subnet.py 
platform linux -- Python 3.6.5, pytest-3.4.0, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python3.6
collected 1 item                                                                                                                                                                             
2018-11-27 16:52:50 - conftest - DEBUG - BZ deselect is disabled in …
```

More loc fixes

---

robottelo/cli/contentview.py
tests/foreman/cli/test_satellitesync.py

[6.5 Feature] [ETE] Content View Export Import Automated

---

tests/foreman/cli/test_discoveredhost.py

cherry-pick of https://github.com/SatelliteQE/robottelo/pull/6506

[6.4.z] fixes #6257 - fixing the sed expression

---

tests/upgrades/test_user.py

(test) [root@vijsingh robottelo]# pytest -v tests/upgrades/test_user.py::Test_scenario_positive_create_sshkey_in_existing_users============================================================================ test session starts ============================================================================
platform linux2 -- Python 2.7.5, pytest-3.6.1, py-1.7.0, pluggy-0.6.0 -- /home/vijsingh/my_projects/test/bin/python2
rootdir: /home/vijsingh/my_projects/robottelo, inifile:
plugins: services-1.3.0, mock-1.10.0
collected 2 items                                                                                                                                                           
tests/upgrades/test_user.py::Test_scenario_positive_create_sshkey_in_existing_users::test_pr …

Automated 'tests/upgrades/test_user.py' for scenario_positive_create_sshkey_in_existing_users

---

tests/foreman/ui_airgun/test_dashboard.py
tests/foreman/ui_airgun/test_host.py
tests/foreman/ui_airgun/test_hostcollection.py
tests/foreman/ui_airgun/test_hostgroup.py

That should cover most of the issues in that direction. Few that are left blocked by other issues:
```
py.test -v /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_host.py::test_positive_inherit_puppet_env_from_host_group_when_action
platform linux -- Python 3.6.5, pytest-3.4.0, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python3.6 …
```

Add more loc fixes

---

tests/foreman/cli/test_setting.py

Fixes issue #6505 
Test Result:
```
$ pytest tests/foreman/cli/test_setting.py -k test_positive_failed_login_attempts_limit -svvv
2018-11-29 18:49:43 - conftest - DEBUG - Registering custom pytest_namespace
collected 19 items                                                                                                                                                     
tests/foreman/cli/test_setting.py::SettingTestCase::test_positive_failed_login_attempts_limit 2018-11-29 18:49:43 - robottelo - INFO - Started setUpClass: tests.foreman.cli.test_setting/SettingTestCase
2018-11-29 18:49:43 - robottelo - INFO - Entities …
```

automated brute force protection limit configurable function: failed_login_attempts_limit

---

tests/foreman/cli/test_hostgroup.py

Fixes HostGroupTestCase::test_positive_create_with_multiple_entities_ids

---

tests/foreman/ui_airgun/test_product.py

**Objective** 
1. To verify that sync plan creation and assignment working if it getting created from Product Create Page.
2. Intention to create this test to make sure that UI workflow works fine, this is something cannot be verified in CLI or API level. 
**Test Result** 
```
root@okhatavk robottelo (product_create_sync_plan) $ pytest tests/foreman/ui_airgun/test_product.py -v -k "sync_plan"
======================================================================== test session starts =========================================================================
platform linux -- Python 3.4.8, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/okhatavk/Satellite/robottelo/env/bin/python3.4
rootdir: …
```

test to create and assignment of sync plan form product page

---

tests/foreman/cli/test_remoteexecution.py

test results:
```
platform linux -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/[*******]/shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/bin/python3.6
rootdir: /home/[*******]/workspace/satellite6-standalone-automation, inifile:
plugins: xdist-1.24.1, services-1.3.1, mock-1.10.0, forked-0.2, env-0.6.2
collecting ... 2018-12-11 12:33:35 - conftest - DEBUG - Collected 7 test cases
collected 7 items / 4 deselected
tests/foreman/cli/test_remoteexecution.py::AnsibleREXTestCase::test_positive_run_effective_user_job PASSED [ 33%]
tests/foreman/cli/test_remoteexecution.py::AnsibleREXTestCase::test_positive_run_packages_and …
```

some ansible rex tests unstubbed

---

tests/foreman/ui_airgun/test_computeresource.py

VM Import test. While creating an entirely new host on RHEV works, importing an existing one does not (bz1636067). Therefore, this test currently fails as true positive and is marked to be skipped.
This test depends on https://github.com/SatelliteQE/airgun/pull/225.

Test RHEV VM Import (bz1636067)

---

robottelo/constants.py
tests/foreman/cli/test_role.py

```
pytest tests/foreman/cli/test_role.py::SystemAdminTestCases::test_system_admin_role_end_to_end
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.6.0, pluggy-0.6.0
rootdir: /home/sjagtap/PycharmProjects/robottelo/tests/foreman, inifile: pytest.ini
collecting 1 item                                                                                                                                                                                                 2018-12-17 19:54:55 - conftest - …
```

End to End Scenario for System Admin role

---

robottelo/api/utils.py
tests/upgrades/test_client.py

Below Scenarios moved to nailgun from hammer:
1. test_client.py
- Scenario_upgrade_old_client_and_package_installation
- Scenario_upgrade_new_client_and_package_installation
Note: Testing is pending for these above.

Ported hammer based secnario to Nailgun

---

robottelo/api/utils.py
tests/upgrades/test_client.py

6.3.z [Cherry-Pick] Ported hammer based secnario to Nailgun

---

robottelo/api/utils.py
tests/upgrades/test_client.py

6.2.z[Cherry-pick] Ported hammer based secnario to Nailgun

---

robottelo.properties.sample

fix duplicate distro option in rob.properties

---

tests/foreman/cli/test_user.py

Fixes #6153 
Cherry pick #6509

[cherry-pick] removing cli.test_user - test_positive_update_all_roles

---

tests/upgrades/test_client.py

Updated the call_entity_method_with_timeout as per robottelo

---

tests/upgrades/test_capsule.py

Below Scenario moved to nailgun from hammer:
2. test_capsule.py
- Scenario_capsule_sync
****Note**: Testing is pending for these above.**

Ported hammer based secnario to Nailgun capsule-sync

---

requirements.txt
tests/upgrades/test_client.py

[Cherry-pick 6.3.z] Updated the call_entity_method_with_timeout as per robottelo

---

tests/foreman/cli/test_contentview.py

Update cli testcases where setUpClass functionality is emulated within
setUp #5085 
* I have replaced the def setUp(self) and the series of if statements with a def setUpClass(cls).
* I have removed env1 and env2 variables (env2 variable was not used anywhere).
I ran pytest tests/foreman/cli/test_contentview.py::ContentViewTestCase
Some tests skipped or failed because I do not have a Capsule set up. Also no provisioning_server configured.
tests/foreman/cli/test_contentview.py::ContentViewTestCase::test_positive_remove_cv_version_from_env_with_host_registered SKIPPED
tests/foreman/cli/test_contentview.py::ContentViewTestCase::test_positive_delete_cv_multi_env_promoted_with_host_registered SKIPPED
tests/foreman/cli/test_contentview.py::ContentViewTestCase::test_positive_remove_cv_version_fro …

Change def setUp to def setUpClass

---

tests/foreman/api/test_repository.py

**- Fixed #6621** 
**- Test result:**
++++++++++++++++++++++++++++++
(py36test) [root@vijsingh robottelo]# pytest -v tests/foreman/api/test_repository.py -k test_positive_update_gpg
platform linux -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/vijsingh/my_projects/py36test/bin/python3.6
rootdir: /home/vijsingh/my_projects/ROBO/master/robottelo, inifile:
plugins: services-1.3.1, mock-1.10.0
collecting ... 2019-01-09 10:42:05 - conftest - DEBUG - Collected 81 test cases
2019-01-09 10:42:05 - conftest - DEBUG - Deselected test …

Fixed test_positive_update_gpg TypeError

---

tests/foreman/cli/test_repository_set.py

**- Added skip_if_bug_open for Bugzilla 1655239**.
**- Fixed #6625**

Added skip_if_bug_open for 1655239

---

robottelo/vm.py

**- Helper to configure the puppet-agent with external capsule host.**
**- It would work in below way:**
i.e.
use case:
+++++++++++++++++++++++++++
self.client = VirtualMachine(
distro=DISTRO_RHEL7,
provisioning_server=settings.compute_resources.libvirt_hostname,
bridge=settings.vlan_networking.bridge)
self.addCleanup(vm_cleanup, self.client)
self.client.create()
self.client.install_katello_capsule_ca(capsule='test.example.com')
self.client.register_contenthost(
org=self.org.label,
lce='Library'
)
**self.client.configure_puppet(capsule='test.example.com')**
++++++++++++++++++++++++++++++++

Configure the puppet-agent with external capsule host

---

robottelo/cli/factory.py
robottelo/products.py
tests/foreman/ui/test_contenthost.py
tests/foreman/ui_airgun/conftest.py
tests/foreman/ui_airgun/test_bookmark.py
tests/foreman/ui_airgun/test_contenthost.py

Depends on SatelliteQE/airgun#238

Ported UI content host tests

---

robottelo/datafactory.py

cron in Linux does not support the use of seconds #6633

Fixes list of valid cron expressions

---

tests/foreman/cli/test_repository.py

**- Bugzilla raised:** https://bugzilla.redhat.com/show_bug.cgi?id=1664631
**- Fixed #6627** 
**- Test result:**
++++++++++++++++++++++++++++++++++++++
(py36test) [root@vijsingh robottelo]# pytest -v tests/foreman/cli/test_repository.py -k test_positive_synchronize_docker_repo_set_tags_later
platform linux -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0 -- /home/vijsingh/my_projects/py36test/bin/python3.6
rootdir: /home/vijsingh/my_projects/ROBO/master/robottelo, inifile:
plugins: services-1.3.1, mock-1.10.0
collecting ... 2019-01-09 …

Added sleep to load repoinfo

---

tests/upgrades/test_capsule.py

**- Updated env id as per AK_env:**
**- Below as per log:**
+++++++++++++++++++++
Organization","label":"Default_Organization","id":1},"created_at":"2019-01-11 16:20:52 UTC","updated_at":"2019-01-11 16:20:52 UTC","environments":[{"id":1,"name":"Library","label":"Library","permissions":{"readable":true}},{"id":3,"name":"Dev","label":"Dev","permissions":{"readable":true}}],"repositories":
+++++++++++++++++++++

updated env id as per ak env

---

tests/upgrades/test_capsule.py

- Cherry-pick of #6640
- Fixed #6639

[Cherry-pick 6.4.z ] updated env id as per ak env

---

tests/upgrades/test_capsule.py

- Cherry-pick of #6640
- Fixed #6639

[Cherry-pick 6.3.z ]updated env id as per ak env

---

tests/upgrades/test_client.py
tests/upgrades/test_contentview.py

[CherryPicked - 6.3.z] ListFixes: Python2to3 Upgrade Scenarios

---

robottelo/vm.py

- **Helper to install\remove external Capsule katello-ca on client.**
- **It would work in below way:**
i.e. 
**use case:**
++++++++++++++++
self.client = VirtualMachine(
distro=DISTRO_RHEL7,
provisioning_server=settings.compute_resources.libvirt_hostname,
bridge=settings.vlan_networking.bridge)
self.addCleanup(vm_cleanup, self.client)
self.client.create()
**self.client.install_katello_capsule_ca(capsule='test.example.com')**
self.client.register_contenthost(
org=self.org.label,
lce='Library'
)
++++++++++++++++
output: 
+++++++++++++++++
**Install:**
2019-01-02 18:31:20 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f50ec6b3048
2019-01-02 18:32:15 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f50fea68780
2019-01-02 18:32:15 - robottelo.ssh - INFO - Connected to …

Helper to install\remove external Capsule katello-ca

---

tests/foreman/api/test_reporttemplates.py
tests/foreman/cli/test_reporttemplates.py
tests/foreman/ui_airgun/test_reporttemplates.py

Stubs of tests for Reporting 6.5 feature. Wait for devel ACK before reviewing.

Reporting stubs

---

robottelo/helpers.py
tests/upgrades/test_remoteexecution.py

- Cherry-pick of #6647
- Fixed #6646

[cherry-pick 6.4.z]Automated secnario to cover REX with external Capsule

---

tests/foreman/cli/test_oscap.py

Fixes issue #6670 tests.foreman.cli.test_oscap.OpenScapTestCase.test_positive_associate_scap_policy_with_hostgroups

Fixes test_positive_associate_scap_policy_with_hostgroups

---

robottelo/helpers.py
tests/upgrades/test_remoteexecution.py

- Cherry-pick of #6647
- Fixed #6646

[cherry-pick 6.3.z]Automated secnario to cover REX with external Capsule

---

tests/foreman/cli/test_remoteexecution.py

reduce occasional timeouts in ansible rex recurring job test

---

tests/foreman/api/test_syncplan.py

"custom" is not by itself a valid sync interval #6663

Fixes sync plan create loop (#6663)

---

robottelo/config/base.py

Removed redundant and deprecated call to configparser.readpf

---

robottelo/api/utils.py
robottelo/helpers.py
robottelo/ui/medium.py
tests/foreman/cli/test_vm_install_products_package.py
tests/foreman/ui/test_computeresource_ec2.py
tests/foreman/ui/test_navigation.py
tests/foreman/ui_airgun/test_hostcollection.py
tests/robottelo/test_func_locker.py

This is a Travis flake8 fix
No change to code logic only over-indented blocks and one int vars compare that should be "==" and not "is"

Fixes flake8 E117 and F632

---

tests/foreman/cli/test_satellitesync.py

Automated 9 more tests cases apart from ETE.

[6.5 Feature] Content View Export Import - Part 1 - automated

---

tests/upgrades/test_remoteexecution.py

[Cherry-pick 6.4.z] Automated REX Satellite-Client scenario

---

tests/foreman/ui_airgun/test_usergroup.py

Closes #6400
```
pytest tests/foreman/ui_airgun/test_usergroup.py 
platform linux -- Python 3.6.5, pytest-4.0.1, py-1.5.3, pluggy-0.8.0
collecting ... 2019-01-29 20:42:42 - conftest - DEBUG - BZ deselect is disabled in settings
collected 2 items                                                                                                                                                                            
tests/foreman/ui_airgun/test_usergroup.py .. …
```

Add end to end scenario to user groups entity

---

tests/upgrades/test_repository.py

Updated assertion

---

tests/upgrades/test_subscription.py

- Fixed organization miss-match fixed #6710 .
- Updated assertion logic.
- Organization screenshot after test ran.
- Test result
```
(myenv3) [root@vijsingh robottelo]# pytest -v tests/upgrades/test_subscription.py -k test_pre_subscription_scenario_autoattach -s
platform linux -- Python 3.6.6, pytest-3.6.1, py-1.7.0, pluggy-0.6.0 -- /home/vijsingh/my_projects/myenv3/bin/python36
rootdir: /home/vijsingh/my_projects/ROBO/robottelo, inifile:
plugins: services-1.3.0, mock-1.10.0
collecting 0 items …
```

Updated test auto-attach

---

tests/upgrades/test_repository.py

- Updated the foreman rakes for repo as per 6.4 Satellite
- Fixed #6711

Updated the foreman rakes

---

tests/upgrades/test_remoteexecution.py

[Cherry-pick 6.3.z] Automated REX Satellite-Client scenario

---

tests/foreman/cli/test_repository.py

- Updated Bugzilla[1] for ostree repo.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1672491

Updated test ostree Bug 1672491

---

tests/foreman/ui_airgun/test_domain.py

Closes #6375
```
pytest tests/foreman/ui_airgun/test_domain.py 
platform linux -- Python 3.6.5, pytest-4.0.1, py-1.5.3, pluggy-0.8.0
collecting ... 2019-02-06 13:02:12 - conftest - DEBUG - BZ deselect is disabled in settings
collected 6 items                                                                                                                                                                            
tests/foreman/ui_airgun/test_domain.py ...... …
```

Add end to end scenario to domain entity

---

robottelo.properties.sample
robottelo/config/base.py

https://github.com/SatelliteQE/robottelo/pull/6724

addressing minor nitpicks from PR#6724 review (multi-manifest support)

---

tests/foreman/cli/test_satellitesync.py

CV Export tests were failing due to the recent changes and Bugzilla fixes.

Fix all CV Export tests

---

tests/foreman/ui_airgun/test_repository.py

- Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1670125
- Added skip_if_bug_open

Added skip_if_bug_open of 1670125

---

tests/foreman/api/test_syncplan.py

Fix test_positive_create_with_interval for custom cron #6745

Fix to handle interval custom cron (#6745)

---

tests/foreman/api/test_syncplan.py

fix to handle create with custom cron
simplify to not use sample()
================================
I will remove the "from random import sample" in another commit after test completes

Fix test_positive_update_interval (#6679)

---

robottelo/virt_who_configure.py
tests/foreman/api/test_virt_who_config.py
tests/foreman/longrun/test_virtwho_config.py

Added 2 basic test cases that create virt-who-configs, and verify the config files.

Basic Virt-Who testcases

---

tests/upgrades/test_activation_key.py
tests/upgrades/test_hostgroup.py

```
pytest tests/upgrades/test_activation_key.py -m pre_upgrade
============================================================== test session starts =============================================
platform linux -- Python 3.6.3, pytest-4.0.2, py-1.7.0, pluggy-0.8.1
plugins: xdist-1.24.1, services-1.3.1, mock-1.10.0, forked-0.2, cov-2.6.0
collected 2 items / 1 deselected                                                                                                                 
tests/upgrades/test_activation_key.py .                                                                                                    [100%]
============================================== 1 passed, 1 deselected in 78.71 seconds =========================================
```
```
pytest …
```

Added activation key and hostgroup scenario tests

---

tests/upgrades/test_errata.py

```
(env) [root@okhatavk robottelo]# pytest tests/upgrades/ -v -k "test_pre_scenario_generate_errata_for_client"
=========================================================== warnings summary ===========================================================
tests/upgrades/test_errata.py::Scenario_errata_count::test_pre_scenario_generate_errata_for_client
/home/okhatavk/Satellite/robottelo/env/lib/python3.4/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning)
/home/okhatavk/Satellite/robottelo/env/lib/python3.4/site-packages/bugzilla/base.py:114: DeprecationWarning: The SafeConfigParser …
```

Added Errata count/apply scenario for satellite upgrade

---

tests/foreman/ui_airgun/test_repository.py

- added skip_if_bug_open of bug https://bugzilla.redhat.com/show_bug.cgi?id=1670125

add skip_if_bug_open of bug 1670125

---

tests/upgrades/test_contentview.py

Test Result:
```
$ pytest tests/upgrades/test_contentview.py::CVUpgradeScenario
collected 2 items                                                                                                                                                      
tests/upgrades/test_contentview.py ..                                                                                                                            [100%]
====================================================================== 2 passed in 678.80 seconds ======================================================================
```

content-view upgrade scenario

---

tests/upgrades/test_yum_plugins.py

- Fixed https://github.com/SatelliteQE/satellite6-upgrade/issues/288
> [root@vijsingh robottelo]# pytest tests/upgrades/ -v -k "test_pre_scenario_yum_plugins_count" -s
> =========================================================== warnings summary ===========================================================
> tests/upgrades/test_yum_plugins.py::Scenario_yum_plugins_count::test_pre_scenario_yum_plugins_count
>   /home/vijsingh/Satellite/robottelo/env/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>     InsecureRequestWarning)
> …

Added loaded yum plugins count scenario

---

robottelo/products.py
tests/foreman/cli/test_vm_install_products_package.py

```
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v tests/foreman/cli/test_vm_install_products_package.py 
============================================ test session starts =============================================
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.5.4, pluggy-0.8.0 -- /home/dlezz/.pyenv/versions/robottelo/bin/python3.6
shared_function enabled - ON - scope: ffff - storage: redis
plugins: xdist-1.26.0, timeout-1.3.3, services-1.3.1, mock-1.10.0, forked-0.2, cov-2.6.1
collecting ... 2019-03-05 15:41:11 - conftest - DEBUG - BZ deselect is disabled in settings
collected 4 items …
```

Extend product with Docker, Puppet, OSTree repos

---

tests/foreman/api/test_syncplan.py

Change interval from hourly to daily (#6794)

---

tests/upgrades/test_errata.py

Fixed https://github.com/SatelliteQE/robottelo/issues/6777 and https://github.com/SatelliteQE/robottelo/issues/6780
```
PASSED2019-03-09 14:53:44 - robottelo - INFO - Started tearDownClass: tests.upgrades.test_errata/Scenario_errata_count
=========================================================== warnings summary ===========================================================
tests/upgrades/test_errata.py::Scenario_errata_count::test_pre_scenario_generate_errata_for_client
/home/okhatavk/Satellite/robottelo/env/lib/python3.4/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning) …
```

Twisting the test a bit, fixed the goferd issue

---

tests/foreman/api/test_syncplan.py

Proposed fix to problem of intermittent fail, see issue #6792 for more details.
I tested this change by running 3 tests in parallel 3 times.

Remove section to prevent intermittent fail (#6792)

---

tests/foreman/ui/test_user.py
tests/foreman/ui_airgun/test_ldap_authentication.py
tests/foreman/ui_airgun/test_user.py

Closes #6399
```
pytest tests/foreman/ui_airgun/test_user.py::test_positive_end_to_end
platform linux -- Python 3.6.5, pytest-4.0.1, py-1.5.3, pluggy-0.8.0
collecting ... 2019-03-07 11:57:11 - conftest - DEBUG - BZ deselect is disabled in settings …
```

Port user test cases

---

tests/foreman/cli/test_activationkey.py

Fix tests.foreman.cli.test_activationkey.ActivationKeyTestCase#test_positive_delete_subscription

---

tests/foreman/api/test_syncplan.py

Re-instate the 4 minute future sync but remove the section that updates the sync time just as its about to sync.
Make test more consistent with similar tests.
See issue #6792 and https://github.com/SatelliteQE/robottelo/pull/6793 for background info.

Optimize custom_product_weekly_recurrence (#6812)

---

tests/foreman/ui/test_bookmark.py
tests/foreman/ui_airgun/test_bookmark.py

Closes #6363
```
pytest tests/foreman/ui_airgun/test_bookmark.py
platform linux -- Python 3.6.5, pytest-4.0.1, py-1.5.3, pluggy-0.8.0
collecting ... 2019-03-19 17:39:32 - conftest - DEBUG - BZ deselect is disabled in settings
collected 4 items                                                                                                                                                                            
tests/foreman/ui_airgun/test_bookmark.py .... …
```

Port bookmark entity

---

tests/foreman/api/test_repository.py
tests/foreman/cli/test_repository.py
tests/foreman/ui_airgun/test_repository.py

- As per Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1664288 PR https://github.com/Katello/katello/pull/7932 now a new repo can not create with checksum.
- Updated below tests with enhancement.
```
UI
test_positive_end_to_end_custom_yum_crud
CLI
test_positive_create_yum_repo_with_checksum_type
test_positive_update_checksum_type
API
test_negative_create_checksum
test_positive_create_checksum
test_positive_update_checksum
```
- Added below tests to increase the coverage:
```
API: test_negative_create_checksum_with_on_demand_policy
CLI:  test_negative_create_checksum_with_on_demand_policy
```
- test results:
```
UI
tests/foreman/ui_airgun/test_repository.py::test_positive_end_to_end_custom_yum_crud PASSED                                                                      [100%] …
```

Updated and added checksum tests

---

tests/foreman/api/test_repository.py

- Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1689504
- fixed #6830

skip-bug-1689504 for test_positive_sync_rh_atomic

---

tests/foreman/cli/test_satellitesync.py

Part 2 is here:
- 7 more tests are automated

[6.5 Feature] Content View Export Import - Part 2 - automated

---

tests/foreman/ui_airgun/test_dashboard.py

```
(myenv3) [vijsingh@vijsingh robottelo]$ pytest -v tests/foreman/ui_airgun/test_dashboard.py -k test_positive_virtwho_configs_widget
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.7.0, pluggy-0.8.1 -- /home/vijsingh/my_projects/myenv3/bin/python36
rootdir: /home/vijsingh/my_projects/PR_Proj/robottelo, inifile:
plugins: services-1.3.1, mock-1.10.0
collecting ... 2019-04-04 13:35:02 - conftest - DEBUG - BZ deselect is disabled in settings
collected 14 items / 13 deselected …
```

added dashboard virtwho widgettest

---

tests/foreman/ui_airgun/test_oscappolicy.py

Fixes dashboard oscap policy test

---

tests/foreman/ui_airgun/test_reporttemplates.py

This depends on https://github.com/SatelliteQE/airgun/pull/298

Reporting feature - first few tests implemented

---

requirements.txt
tests/foreman/longrun/test_provisioning_computeresource.py

Fixes #6852 
```
In [1]: from wrapanapi import RHEVMSystem
In [2]: from robottelo.config import settings
In [3]: settings.configure()
In [4]: bridge = settings.vlan_networking.bridge
...:         # RHV Settings
...: rhev_url = settings.rhev.hostname
...: rhev_password = settings.rhev.password
...: rhev_username = settings.rhev.username
...: rhev_datacenter = settings.rhev.datacenter
...: rhev_img_name = settings.rhev.image_name
...: rhev_img_arch = settings.rhev.image_arch
...: rhev_img_os = settings.rhev.image_os
...: rhev_img_user = settings.rhev.image_username
...: rhev_img_pass = settings.rhev.image_password
...: rhev_vm_name = settings.rhev.vm_name
...: rhev_storage_domain = settings.rhev.storage_domain
...: rhv_api = RHEVMSystem(hostname=rhev_url.split('/')[2],
...: …
```

Used released wrapanapi and pin it with tested version

---

requirements.txt

**Before:**
```
pip list -| grep urllib3
urllib3                               1.25          
root  ⓔ env1   master {26} ?:6  /home/sjagtap/PycharmProjects/robottelo  pip list | grep pytest-services
pytest-services                       1.3.1         
```
```
pytest tests/foreman/cli/test_ping.py 
File "/root/.virtualenvs/env1/lib/python3.6/site-packages/pluggy/manager.py", line 274, in load_setuptools_entrypoints
plugin = ep.load()
File "/root/.virtualenvs/env1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2433, in load
self.require(*args, **kwargs)
File "/root/.virtualenvs/env1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in require
items = working_set.resolve(reqs, env, installer, extras=self.extras)
File …
```

Pin urllib3 to stable version

---

tests/upgrades/test_activation_key.py
tests/upgrades/test_capsule.py
tests/upgrades/test_classparameter.py
tests/upgrades/test_client.py
tests/upgrades/test_contentview.py
tests/upgrades/test_errata.py
tests/upgrades/test_hostgroup.py
tests/upgrades/test_remoteexecution.py
tests/upgrades/test_role.py
tests/upgrades/test_subscription.py
tests/upgrades/test_syncplan.py
tests/upgrades/test_yum_plugins.py

[Cherry-pick] Added portupgrade depend_on

---

requirements.txt

Use 6.5.z branch of Airgun instead of master.

Use Airgun 6.5.z branch

---

tests/foreman/cli/test_contentview.py

Code commits related changes of SATQE-3456 and fixed duplicate org and product creation

Code commits related changes of SATQE-3456 and fixed duplicate org and product.

---

tests/foreman/cli/test_repository.py

PR for merge to master branch.
- Updated file_to_file_upload test case.
- Removed duplicate reads - as per @oshtaier comment in previous PR #6899.
- Test run is successful on both 6.5.z / 6.6 version of Sat 6.
- Added check for file by name in repository - @oshtaier
- Minor change in Docstring - @vijay8451

Automate_upload_file_to_file_repo

---

robottelo.properties.sample
robottelo/config/base.py

This is going to be needed for the true provisioning.

add dns_zone to vlan_settings

---

tests/foreman/api/test_repository.py
tests/foreman/cli/test_repository.py

- Updated the test cases metadata around repositories component.

Updated metadata of few repo tests

---

robottelo/constants.py
tests/foreman/rhai/conftest.py
tests/foreman/sys/test_rename.py
tests/foreman/ui_airgun/test_computeresource.py
tests/upgrades/test_client.py
tests/upgrades/test_remoteexecution.py

Default org and loc changed ID in 6.6

---

tests/foreman/api/test_contentview.py
tests/foreman/api/test_repository.py
tests/foreman/cli/test_contentview.py
tests/foreman/cli/test_ostreebranch.py
tests/foreman/cli/test_repository.py
tests/foreman/ui_airgun/test_contentview.py
tests/foreman/ui_airgun/test_sync.py

Fixes #6925.
Also removed some older skip_if_bug_open for bugs that have been closed.

Add @skip_if_bug_open to all OSTree testcases that sync the repo

---

tests/foreman/endtoend/test_api_endtoend.py

Fixes issue #6898 
Test Result:
```
$ pytest -v tests/foreman/endtoend/test_api_endtoend.py::AvailableURLsTestCase::test_positive_get_links 
collected 1 item                                                                                                                                                                                                  
tests/foreman/endtoend/test_api_endtoend.py::AvailableURLsTestCase::test_positive_get_links PASSED                                                                                                          [100%] …
```

Fixes issue #6898 Updating API end-point.

---

robottelo.properties.sample
robottelo/config/base.py
tests/upgrades/test_capsule.py
tests/upgrades/test_errata.py

cherrypick - https://github.com/SatelliteQE/robottelo/pull/6908

Environment Variables for upgrade scenarios are now robottelo properties Phase -1

---

robottelo.properties.sample
robottelo/config/base.py
tests/upgrades/test_capsule.py

Cherrypicked - https://github.com/SatelliteQE/robottelo/pull/6908

Environment Variables for upgrade scenarios are now robottelo properties Phase - 1

---

robottelo.properties.sample
robottelo/api/utils.py
robottelo/config/base.py
robottelo/helpers.py
robottelo/ui/medium.py
robottelo/ui/rhai.py
tests/foreman/ui/test_computeresource_ec2.py
tests/foreman/ui/test_errata.py
tests/foreman/ui/test_navigation.py
tests/robottelo/test_func_locker.py
tests/upgrades/test_capsule.py

Cherrypicked - https://github.com/SatelliteQE/robottelo/pull/6908
and Flake8 issues are fixed.

Environment Variables for upgrade scenarios are now robottelo properties, phase - 1

---

tests/foreman/api/test_setting.py
tests/foreman/cli/test_setting.py

Update the metadata for the component  Settings and validate against the testimony
```
(env) [root@okhatavk robottelo]# check_testimony 
Total number of tests: 8
Total number of invalid docstrings: 0 (00.00%)
Test cases with no docstrings: 0 (0.00%)
Test cases missing minimal docstrings: 0 (0.00%)
Test cases with unexpected tags: 0 (0.00%)
Test cases with unexpected token values in docstrings: 0 (0.00%)
Test cases with unparseable docstrings: 0 (0.00%)
Total number of tests: 19
Total number of invalid docstrings: 0 (00.00%)
Test cases with no docstrings: 0 (0.00%)
Test cases missing minimal docstrings: 0 (0.00%)
Test cases with unexpected tags: 0 (0.00%)
Test cases with unexpected token values in docstrings: 0 (0.00%)
Test cases with unparseable docstrings: 0 (0.00%)  
```
```
(env) …
```

updated matadata for Settings component

---

tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_discoveryrule.py
tests/foreman/api/test_template.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/cli/test_discoveryrule.py
tests/foreman/cli/test_template.py
tests/foreman/ui/test_discoveredhost.py
tests/foreman/ui_airgun/test_discoveredhost.py
tests/foreman/ui_airgun/test_discoveryrule.py

Metadata Update for Components:
1. Discovery Plugin / Discovery Image
2. Templates Plugin

Update metadata for Components Discovery and Templates

---

robottelo/cleanup.py
robottelo/constants.py
robottelo/test.py
tests/foreman/rhai/conftest.py
tests/foreman/sys/test_rename.py
tests/foreman/ui/test_remoteexecution.py
tests/foreman/ui_airgun/conftest.py
tests/foreman/ui_airgun/test_computeresource.py
tests/foreman/ui_airgun/test_computeresource_ec2.py
tests/foreman/ui_airgun/test_jobinvocation.py
tests/foreman/ui_airgun/test_smartclassparameter.py
tests/foreman/ui_airgun/test_smartvariable.py
tests/upgrades/test_client.py
tests/upgrades/test_remoteexecution.py

1. Fixed #6937
2. Recently hit bug[https://bugzilla.redhat.com/show_bug.cgi?id=1713269] due to which automation failed because of hardcoded org/loc IDs.

Remove org/loc IDs dependency

---

tests/foreman/api/test_puppetmodule.py

based on discussion with jomitsch, the test failure relates to bz#1711929

skipping puppetmodule api test

---

tests/foreman/api/test_gpgkey.py
tests/foreman/api/test_repository.py
tests/foreman/api/test_repository_set.py
tests/foreman/cli/test_gpgkey.py
tests/foreman/cli/test_ping.py
tests/foreman/cli/test_repository.py
tests/foreman/cli/test_repository_set.py
tests/foreman/ui_airgun/test_repository.py

- Updated tests metadata.
- testimony results:
```
(testimony) [root@vijsingh testimony]# testimony -c ../PR_Proj/robottelo/testimony.yaml validate ../PR_Proj/robottelo/tests/foreman/api/test_repository.py 
Total number of tests: 86
Total number of invalid docstrings: 0 (00.00%)
Test cases with no docstrings: 0 (0.00%)
Test cases missing minimal docstrings: 0 (0.00%)
Test cases with unexpected tags: 0 (0.00%)
Test cases with unexpected token values in docstrings: 0 (0.00%)
Test cases with unparseable docstrings: 0 (0.00%)
(testimony) [root@vijsingh testimony]# testimony -c ../PR_Proj/robottelo/testimony.yaml validate ../PR_Proj/robottelo/tests/foreman/api/test_repository_set.py 
Total number of tests: 2
Total number of invalid docstrings: 0 (00.00%)
Test cases with no docstrings: 0 …
```

Updated metadata

---

tests/foreman/api/test_docker.py
tests/foreman/api/test_hostgroup.py
tests/foreman/cli/test_docker.py
tests/foreman/cli/test_hostgroup.py
tests/foreman/cli/test_repository.py
tests/foreman/ui_airgun/test_container.py
tests/foreman/ui_airgun/test_containerimagetag.py
tests/foreman/ui_airgun/test_hostgroup.py

Update Hostgroup and Docker/Containers test metadata. `testimony validate` clean; `testimony tiers` complains a bit, but only in tests that are part of Container Management - feature that is removed in Satellite 6.6. These tests will be removed before 6.6 GA.
Also cleaned up decorators a bit (removed `skip_if_bug_open` for bugs fixed long time ago), and changed order of imports where local linter complained.
```
$ for i in tests/foreman/api/test_docker.py tests/foreman/cli/test_docker.py tests/foreman/cli/test_repository.py tests/foreman/ui_airgun/test_container.py tests/foreman/ui_airgun/test_containerimagetag.py tests/foreman/api/test_hostgroup.py tests/foreman/cli/test_hostgroup.py tests/foreman/ui_airgun/test_hostgroup.py ; do testimony -c testimony.yaml validate "$i" ; done
Total …
```

Update Hostgroup and Docker/Containers test metadata

---

tests/foreman/installer/test_installer.py

fixes https://github.com/SatelliteQE/robottelo/issues/4738
This test doesn't comply with the current testing strategy as it is designed to be written just after the installer finishes.
It checks for errors in the logfile, but since the order of the test is not guaranteed, it interferes with the rest of the tests, that get executed sooner and potentially feed logs with error/warn log messages (many of which are valid ones).

fixes #4738 - removing the installer log test entirely

---

tests/foreman/cli/test_satellitesync.py

This testcase is added to test whether CV export/import works well with huge contents or not.

Adds testcase test_positive_export_import_redhat_cv_with_huge_contents

---

tests/upgrades/test_subscription.py
tests/upgrades/test_yum_plugins.py

Cherry-pick added wait for host status and location

---

tests/foreman/api/test_computeresource_libvirt.py

TODO: remove it from all API tests.

Docker support dropped, removing it from my API tests.

---

requirements.txt

Test Results:
Tests selected : tests/foreman/api/test_multiple_paths.py tests/foreman/api/test_template.py tests/foreman/api/test_product.py
See : /view/Satellite 6/job/satellite6-standalone-automation/1561/testReport/
The failures in the job are not related to this change.

Update idna and requests

---

requirements.txt

- Update pytest-mock version from `1.10.0` to `1.10.4`
```
(pmenv) [root@vijsingh robottelo]# pip3 list|grep pytest-mock
pytest-mock                           1.10.4                             <<<<<==========
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(pmenv) [root@vijsingh robottelo]# 
(pmenv) [root@vijsingh robottelo]# pytest -v ./tests/robottelo/test_cli_method_calls.py ./tests/robottelo/test_cli.py ./tests/robottelo/test_helpers.py ./tests/robottelo/test_datafactory.py
platform linux -- Python 3.6.8, …
```

tested and updated pytest-mock version 1.10.4

---

requirements.txt

- Updated mock from `2.0.0` to `3.0.5`
- Testing results:
```
(libtest) [root@vijsingh robottelo]# pip3 list |grep mock
mock                                  3.0.5                  <<<<<==== 
pytest-mock                           1.10.0        
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(libtest) [root@vijsingh robottelo]# 
(libtest) [root@vijsingh robottelo]# pytest -v tests/robottelo/test_cli.py tests/robottelo/test_ui.py tests/robottelo/test_decorators.py tests/robottelo/test_ssh.py tests/robottelo/test_helpers.py tests/robottelo/test_host_info.py tests/robottelo/ui/test_location.py tests/robottelo/decorators/test_host.py tests/robottelo/test_config_settings.py …
```

Updated and tested mock mod/lib

---

requirements.txt

```
(env) [root@okhatavk robottelo]# pytest tests/foreman/ -v -k 'test_negative_get_with_no_args or test_positive_access_protected_repository or test_verify_bugzilla_1114640 or test_positive_all_options or test_positive_ping' > test_result.txt
====== 5 passed, 4196 deselected, 9 warnings in 186.31 seconds =======
```

updated six to 1.12.0 and rebased with master

---

requirements.txt

- Tested and updated cryptography to version 2.7
- Test result:
```
(cryptoenv) [root@vijsingh robottelo]# pip3 list |grep cryptography
cryptography                          2.7           
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(cryptoenv) [root@vijsingh robottelo]# pytest -v ./tests/foreman/api/test_repository_set.py ./tests/foreman/api/test_subscription.py
platform linux -- Python 3.6.8, pytest-4.0.2, py-1.8.0, pluggy-0.12.0 -- /home/vijsingh/my_projects/.venv/cryptoenv/bin/python3.6
shared_function …
```

tested and updated cryptography to version 2.7

---

tests/foreman/api/test_subscription.py
tests/foreman/cli/test_subscription.py
tests/foreman/ui_airgun/test_subscription.py

Update to what I believe best matches the currently outlined criteria.

Update test metadata and tier levels for test_subscription files

---

tests/foreman/ui/test_contentcredential.py
tests/foreman/ui/test_errata.py
tests/foreman/ui/test_hostgroup.py
tests/foreman/ui/test_ldap_authentication.py
tests/foreman/ui/test_organization.py

```
py.test /home/ashtayer/Desktop/robottelo/tests/foreman/ui_airgun/test_contentcredential.py::test_positive_add_product_and_search
platform linux -- Python 3.6.5, pytest-4.0.2, py-1.5.3, pluggy-0.11.0
plugins: services-1.3.1, mock-1.10.0
collecting ... 2019-06-04 13:16:44 - conftest - DEBUG - BZ deselect is disabled in settings …
```

Port more test cases

---

tests/foreman/cli/test_syncplan.py

make CLI tests similar to API tests
This pull request for branch 6812-3.1 has the updates for the CLI tests to match changes in API tests in #6825

Optimize CLI tests for sync plans (#6812)

---

tests/foreman/api/test_syncplan.py

Ref: change in projects.theforeman.org/issues/26417

Change format of syncdate (#7024)

---

tests/upgrades/test_client.py
tests/upgrades/test_remoteexecution.py
tests/upgrades/test_repository.py
tests/upgrades/test_subscription.py
tests/upgrades/test_syncplan.py
tests/upgrades/test_yum_plugins.py

[6.5.z] Environment Variables for upgrade scenarios are now robottelo properties - Phase 2

---

tests/upgrades/test_client.py
tests/upgrades/test_remoteexecution.py
tests/upgrades/test_subscription.py

[6.4.z] Environment Variables for upgrade scenarios are now robottelo properties - Phase 2

---

tests/upgrades/test_client.py
tests/upgrades/test_remoteexecution.py
tests/upgrades/test_subscription.py

[6.3.z] Environment Variables for upgrade scenarios are now robottelo properties - Phase 2

---

tests/foreman/ui_airgun/test_settings.py

Migrate Satellite settings component tests from ui to ui_airgun, currently, there is no coverage running tests from UI front.    
```
(env) [root@okhatavk robottelo]# pytest tests/foreman/ui_airgun/test_settings.py -v
========================================================= test session starts ==========================================================
platform linux -- Python 3.4.8, pytest-4.0.2, py-1.7.0, pluggy-0.9.0 -- /home/okhatavk/Satellite/robottelo/env/bin/python3.4
rootdir: /home/okhatavk/Satellite/robottelo, inifile:
plugins: xdist-1.26.1, services-1.3.1, mock-1.10.0, forked-1.0.2, cov-2.6.1
collecting ... 2019-06-04 11:24:11 - conftest - DEBUG - Collected 24 test cases
collected 24 items …
```

migrated some tests of settings from ui to ui_airgun

---

tests/foreman/api/test_syncplan.py
tests/foreman/cli/test_syncplan.py
tests/foreman/ui/test_syncplan.py

Hello
I have read through the metadata and docstrings for the API and CLI tests and made some changes.
Please review.
Thank you

Update Sync Plan test metadata (#6872)

---

tests/foreman/api/test_hostgroup.py

- Added test around hostgroup rebuild config
- Pending to merge and cherry-pick PR https://github.com/SatelliteQE/nailgun/pull/641
- Fixed #7028
- Test result:
```
tests/foreman/api/test_hostgroup.py::HostGroupTestCase::test_rebuild_config PASSED                                                                                    [100%]
================================================================= 1 passed, 46 deselected in 88.67 seconds ==================================================================
```

Added test around hostgroup rebuild config

---

tests/foreman/api/test_contentview.py
tests/foreman/cli/test_contentview.py
tests/foreman/ui/test_contentview.py

Add and updated any outdated metadata info for test cases in api, cli
and ui for contentview for my component.
For some weird reason, pyup-bot is included with my commit.

Metadata contentview updates

---

tests/foreman/sys/test_katello_certs_check.py

Just case component and some text changes.

Update metadata for katello-certs-check

---

tests/foreman/ui/test_reporttemplates.py

Depends on https://github.com/SatelliteQE/nailgun/pull/629

Implementing some stubbed reporting tests

---

tests/foreman/ui/test_dashboard.py

Part of metadata cleanup - corrected CaseComponent for WebUI dashboard tests.

Metadata cleanup - fixed Casecomponent for dashboard tests

---

tests/foreman/api/test_contentmanagement.py
tests/foreman/api/test_contentviewfilter.py
tests/foreman/api/test_contentviewversion.py
tests/foreman/cli/test_contentviewfilter.py

Add more metadata update from my component ownership for content view and content management.

Metadata update for content view and content management

---

tests/foreman/ui/test_ldap_authentication.py

Depends on https://github.com/SatelliteQE/airgun/pull/343
Fixes https://github.com/SatelliteQE/robottelo/issues/6687
We have only one server and ldap auth configured in any other org in satellite was causing the test failure. The solution implemented will delete all ldap auth before test starts.

Fixes ldap authentication UI tests

---

tests/foreman/cli/test_fact.py

Update CaseComponent for Facts CLI tests

---

tests/foreman/sys/test_hooks.py

Metadata cleanup - CaseComponent for Hooks Plugin tests

Update CaseComponent for Hooks Plugin tests

---

tests/foreman/api/test_email.py

Part of metadata review. As its a stubbed test I just fixed case component.
Thank you

Fix CaseComponent Email

---

tests/foreman/api/test_hostcollection.py
tests/foreman/cli/test_host_collection.py
tests/foreman/ui/test_hostcollection.py

Metadata cleanup - Host Collections

Update metadata - Host Collections

---

tests/foreman/cli/test_bootstrap_script.py

Part of metadata review. As its a stubbed test I just fixed case component and added the full name of the script in case someone greps for that.
Thank you

Fix Bootstrap casecomponent

---

tests/foreman/rhai/test_rhai.py
tests/foreman/rhai/test_rhai_client.py

Update metadata - RHAI

---

tests/foreman/api/test_foremantask.py
tests/foreman/api/test_host.py
tests/foreman/cli/test_host.py
tests/foreman/sys/test_rename.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_jobinvocation.py

Updated CaseComponents, CaseLevels, CaseImportance and tiers to match the new metadata guidelines.

Metadata cleanup

---

tests/foreman/ui_airgun/test_contenthost.py

* Test the Update All Packages button on Update Packages dialogue
* Use the Host Collection view to get to it.

test_positive_end_to_end_bulk_update (#6956)

---

tests/foreman/ui/test_host.py

Adding skip decorator to skip host search tests by parameter based on bug  https://bugzilla.redhat.com/show_bug.cgi?id=1725686

hosts search tests by parameter are failing

---

tests/foreman/api/test_contentaccess.py
tests/foreman/api/test_operatingsystem.py
tests/foreman/api/test_product.py
tests/foreman/cli/test_operatingsystem.py
tests/foreman/cli/test_product.py
tests/foreman/longrun/test_inc_updates.py
tests/foreman/ui/test_contentcredential.py
tests/foreman/ui/test_operatingsystem.py
tests/foreman/ui/test_package.py
tests/foreman/ui/test_product.py

Case component update and corrected URLs to API docs.

Fix metadata CaseComponent Hosts-Content

---

tests/foreman/api/test_rhsm.py

One CaseComponent fix and fix format of bugzilla reference.

Fix metadata CaseComponent ContentManagement

---

tests/upgrades/test_yum_plugins.py

- Increased timeout due to #7104

Increased timeout for reposync

---

robottelo/vm.py
tests/robottelo/test_vm.py

fixes https://github.com/SatelliteQE/robottelo/issues/5349, https://github.com/SatelliteQE/robottelo/issues/7013
this now implicitly uses qemu-guest-agent to query ip address info. Also, to maintain backward compatibility, the script falls back to the standard ping (Avahi) method in case the guest-agent is not configured or the script fails to source the info in time.
```
Starting install...
Domain creation completed.
2019-06-11 18:10:29 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f630584ef28
2019-06-11 18:10:30 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f630584ef98
2019-06-11 18:10:30 - robottelo.ssh - INFO - Connected to [***]
2019-06-11 18:10:30 - robottelo.ssh - INFO - >>> virsh qemu-agent-command adfxkkdmawd6joql.foo.bar.com …
```

add support for qemu-guest-agent in vm.py

---

tests/upgrades/test_subscription.py

- Fixed https://github.com/SatelliteQE/satellite6-upgrade/issues/332
- Test result:
```
PASSED2019-07-04 16:12:53 - robottelo - INFO - Started tearDownClass: tests.upgrades.test_subscription/Scenario_manifest_refresh
```

reverted the manifest_clone

---

tests/foreman/api/test_bookmarks.py
tests/foreman/ui/test_bookmark.py

Metadata cleanup. Not sure where to put bookmarks exactly, but I thing Usability component is best suited for this.

Metadat cleanup - bookmarks, usability

---

tests/foreman/api/test_filter.py
tests/foreman/api/test_permission.py
tests/foreman/api/test_role.py
tests/foreman/api/test_user.py
tests/foreman/api/test_usergroup.py
tests/foreman/cli/test_filter.py
tests/foreman/cli/test_myaccount.py
tests/foreman/cli/test_role.py
tests/foreman/cli/test_user.py
tests/foreman/cli/test_usergroup.py
tests/foreman/ui/test_role.py
tests/foreman/ui/test_user.py
tests/foreman/ui/test_usergroup.py

Metadata updates for the Users&Roles component

Metadata cleanup - Users and Roles

---

tests/foreman/endtoend/test_cli_endtoend.py
tests/foreman/longrun/test_puppet_upgrade.py
tests/foreman/longrun/test_virtwho_config.py
tests/foreman/sys/test_sat_clone.py
tests/foreman/virtwho/test_api_virtwho.py
tests/foreman/virtwho/test_cli_virtwho.py

Mostly update metadata, but also RST parsing errors in virtwho

Fix testimony validate errors outside of {api,cli,ui}

---

tests/upgrades/test_containers_removal.py

The problem is that due to changes in registry.access.redhat.com, Satellite is no longer able to pull in content from that registry. See [bz#1703397](https://bugzilla.redhat.com/show_bug.cgi?id=1703397), especially comment # 5. There are couple of possible solutions, each with their own problems:
registry.redhat.io is new Red Hat registry that will eventually deprecate registry.access.redhat.com. The thing is, it requires authentication to pull content in. Portal credentials can be used, and while we do have QE account there, it is not public and out tests never use it. Robottelo **could** use it, if robottelo-ci is modified to get secret credentials from Jenkins and modify certain placeholders in robottelo.properties before running test. Which sounds like a lot of work for test that will …

Fix containers removal upgrade tests

---

robottelo.properties.sample
robottelo/config/base.py
robottelo/constants.py
tests/foreman/ui/test_computeresource_gce.py

Test Result:
```
$ py.test -s tests/foreman/ui/test_computeresource_gce.py
2019-06-18 20:41:54 - conftest - DEBUG - Registering custom pytest_namespace
========================================== test session starts ==========================================
platform linux -- Python 3.6.8, pytest-4.0.2, py-1.7.0, pluggy-0.8.1
rootdir: /home/jitendrayejare/Desktop/RedHat/RoboTelloNew/robottelo, inifile:
plugins: xdist-1.26.1, services-1.3.1, mock-1.10.4, forked-1.0.2, cov-2.6.1
collecting ... 2019-06-18 20:41:54 - conftest - DEBUG - BZ deselect is disabled in settings
collected 1 item 
================================ 1 passed, 2 warnings in 524.81 seconds =================================
```

[6.6 Feature] GCE CR End To End Scenario

---

tests/foreman/ui/test_contentview.py

Fix all tests because of #7121

fixed UI tests failed because of #7121

---

tests/foreman/ui/test_hardwaremodel.py

```bash
$ testimony -c testimony.yaml validate tests/foreman/ui/test_hardwaremodel.py 
Total number of tests: 1
Total number of invalid docstrings: 0 (00.00%)
Test cases with no docstrings: 0 (0.00%)
Test cases missing minimal docstrings: 0 (0.00%)
Test cases with unexpected tags: 0 (0.00%)
Test cases with unexpected token values in docstrings: 0 (0.00%)
Test cases with unparseable docstrings: 0 (0.00%)
```

update metadata for hw_model test cases

---

tests/foreman/ui/test_discoveredhost.py

UI Discovered Host tests blokced with bug

---

tests/foreman/ui/test_remoteexecution.py

```
Testing started at 5:25 PM ...
/home/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 34444 --file /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --target test_remoteexecution.py::test_positive_run_default_job_template_by_ip
pydev debugger: process 8707 is connecting
Connected to pydev debugger (build 181.5087.37)
Launching py.test with arguments test_remoteexecution.py::test_positive_run_default_job_template_by_ip in /home/okhatavk/Satellite/robottelo/tests/foreman/ui
2019-07-17 17:25:49 - conftest - DEBUG - Registering custom pytest_configure
2019-07-17 17:25:49 - conftest - DEBUG - Fetching BZs to deselect... …
```

fixed ui tests for remote_execution

---

tests/foreman/cli/test_operatingsystem.py

- https://bugzilla.redhat.com/show_bug.cgi?id=1713553
- Test Result:
```
tests/foreman/cli/test_operatingsystem.py::OperatingSystemTestCase::test_positive_update_parameters_attributes PASSED                                            [100%]
```

Added automation around BZ#1713553

---

robottelo/helpers.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/ui/test_discoveredhost.py
tests/foreman/ui/test_discoveryrule.py

Bugs affecting Test Failures:
1709761:
- Content Management API Tests
1731112:
- Discovered Hosts and Discovery Rules Tests

Skip Discovered Hosts and Discovery Rules tests and Fix Content Management tests

---

tests/foreman/ui/test_subscription.py

The test was failing because of not seeing the table, currently, it was looking at the default organisation. I have added code to the new organisation.

fix_ui test : added manifest code to see tables

---

tests/foreman/cli/test_satellitesync.py

Test Result:
```
$ pytest tests/foreman/cli/test_satellitesync.py -k test_positive_export_import_redhat_cv_with_huge_contents -svvv
=================================================================================== test session starts ===================================================================================
collecting ... [2019-06-19 15:28:29 - conftest - DEBUG - Collected 61 test cases
collected 61 items / 60 deselected                                                                                                                                                        
tests/foreman/cli/test_satellitesync.py::ContentViewSync::test_positive_export_import_redhat_cv_with_huge_contents 2019-06-19 15:28:29 - robottelo - INFO - Started setUpClass: …
```

Fixes test_positive_export_import_redhat_cv_with_huge_contents

---

tests/foreman/cli/test_repository.py

- https://bugzilla.redhat.com/show_bug.cgi?id=1716429

Added skip for bug#1716429

---

tests/foreman/cli/test_subnet.py

Fixes #7195 
Before refactoring tests run for 330 seconds. 
```==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
collecting ... 2019-07-22 09:58:22 - conftest - DEBUG - BZ deselect is disabled in settings
collected 24 items …
```

test create and update refacor

---

tests/foreman/api/test_contentmanagement.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/ui/test_discoveredhost.py

- Continue with https://github.com/SatelliteQE/robottelo/pull/7202 , and
- Capsule checksum sync bug

More Tests skipped with bug 1731112 and new checksum sync bug

---

tests/foreman/ui/test_hostcollection.py
tests/foreman/ui/test_remoteexecution.py

- Currently location was overwriting with existing assigned capsule locations hence moved to append to avoid that.
- Fixed #7215

Updated the smart-proxy location append update

---

tests/foreman/cli/test_hostgroup.py

Before refactoring:
```
tests/foreman/cli/test_hostgroup.py .................................                                                                                                                  [100%]
========================================================================== 33 passed, 0 warnings in 1207.39 seconds ==========================================================================
```
After refactoring:
```
tests/foreman/cli/test_hostgroup.py .......                                                                                                                                            [100%]
=========================================================================== 7 passed, 0 warnings in 267.61 seconds =============================================================== …
```

Deleted duplicated tests in test_hostgroup, some tests merged into one

---

Makefile
docs/api/tests.foreman.virtwho.rst
robottelo.properties.sample
robottelo/config/base.py
tests/foreman/virtwho/test_ui_virtwho.py
tests/foreman/virtwho/utils.py

The end to end testcase should be including the following steps:
1. register the virtual machine to satellite
2. create virtwho configure in UI and return the deploy command line
3. execute the command line and start to deploy
4. check the deploy status
5. attach physical VDC sku to hypervisor and check the subscription status
6. attach virtual VDC sku to virtual machine and check the subscription status
7. clean up

Enhancement of testcases test_positive_deploy_configure_by_id

---

tests/foreman/ui/test_host.py

I do not know why it worked from time to time before. Anyway, now we have installation media and also VM is created with 2 GB RAM which is needed by RHEL7 (it won't boot with 1 GB).

RHEL7 needs 2GB RAM and install media is needed

---

robottelo.properties.sample
robottelo/cli/factory.py
robottelo/config/base.py
tests/foreman/cli/test_computeresource_osp.py

add new options for using v3 api + fix bad use of decorator skip_if_not_set

repair computeresource_osp tests

---

robottelo/config/base.py

+ add old one which was also missing and remove redundant one

add new option to validation error msg

---

tests/foreman/cli/test_discoveredhost.py

Discovery Provision with parameters bug #1572947 automated

---

tests/foreman/cli/test_product.py

Before:
```
=========================================== test session starts ============================================
platform linux -- Python 3.7.4, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
collecting ... 2019-08-08 11:54:45 - conftest - DEBUG - BZ deselect is disabled in settings
collected 18 items                                                                                         
test_product.py ..................                                                                   [100%]
======================================= 18 passed in 1746.51 seconds =======================================
```
After:
``` …
```

cli/test_product.py tests merged into one CRUD test

---

tests/foreman/ui/test_contentview.py

Created 4 test cases for depSolving: 2 for conservative and 2 for greedy.

6.6 Feature Area - DepSolving

---

tests/foreman/ui/test_organization.py

Grouped some add and remove entity tests to the end-to-end test so that they reuse the org and session.
It relies on  https://github.com/SatelliteQE/airgun/pull/383 to function (on some webdriver versions I guess)
Test result:
```pytest tests/foreman/ui/test_organization.py -k end_to_end
2019-07-31 13:00:08 - conftest - DEBUG - Registering custom pytest_configure
================================================================= test session starts ==================================================================
platform linux -- Python 3.7.3, pytest-4.6.3, py-1.7.0, pluggy-0.12.0
collecting ... 2019-07-31 13:00:08 - …
```

some ui org tests refactored

---

robottelo/helpers.py
tests/foreman/cli/test_oscap.py
tests/foreman/cli/test_oscap_tailoringfiles.py
tests/foreman/ui/test_oscapcontent.py
tests/foreman/ui/test_oscappolicy.py
tests/foreman/ui/test_oscaptailoringfile.py

fixes tests related to scap content

---

robottelo/api/utils.py

- Added helper to update content in template -> Special going to use around GCE/Azure/EC2 
- Use as below:
```
update = update_provisioning_template(name="Kickstart default finish",
old="yum update -t -y",
new="#yum update -t -y",
org_id=1)
if update:
... continue further
```

Added helper to update content in template

---

tests/foreman/ui/test_smartclassparameter.py

some cleanup for smartclass parameters ui tests. This testclass is much similar to smartvariables tests handled in
results:
```
pytest tests/foreman/ui/test_smartclassparameter.py 
2019-08-13 13:21:39 - conftest - DEBUG - Registering custom pytest_configure
================= test session starts ===============================
platform linux -- Python 3.7.4, pytest-4.6.3, py-1.7.0, pluggy-0.12.0
collecting ... 2019-08-13 13:21:39 - conftest - DEBUG - BZ deselect is disabled in settings …
```

refactor smart class params ui tests

---

tests/foreman/ui/test_puppetenvironment.py

no need for separate testcase with two additional orgs to test hosgroup availability, merged with host test. Addd widget_names to read where possible, updated some asserts.
```
pytest tests/foreman/ui/test_puppetenvironment.py -k test_positive_availability_for_host_and_hostgroup_in_multiple_orgs
2019-08-14 14:41:26 - conftest - DEBUG - Registering custom pytest_configure
====================================================== test session starts ======================================================
platform linux -- Python 3.7.4, pytest-4.6.3, py-1.7.0, pluggy-0.12.0
collecting ... 2019-08-14 14:41:26 - conftest - …
```

puppet environment review

---

tests/foreman/ui/test_organization.py

revisited org tests, added skip on bz, made asserts more robust, and tried to optimize widget read a bit:
``` pytest tests/foreman/ui/test_organization.py -k test_positive_end_to_end
2019-08-14 10:04:47 - conftest - DEBUG - Registering custom pytest_configure
====================================================================== test session starts =======================================================================
platform linux -- Python 3.7.4, pytest-4.6.3, py-1.7.0, pluggy-0.12.0
collecting ... 2019-08-14 10:04:47 - conftest - DEBUG - BZ deselect is disabled in settings
collected 6 items / 5 deselected / 1 …
```

org ui tests added skip, improved read and asserts

---

tests/foreman/ui/test_location.py

Grouped some add and remove entity tests to the end-to-end test so that they reuse the location and session.

some ui location tests merged

---

tests/foreman/ui/test_repository.py

failing because of issue https://bugzilla.redhat.com/show_bug.cgi?id=1743271

failing because of issue bugzilla-1743271

---

tests/foreman/ui/test_location.py

Some options were in collision and caused automation failure. Moved part of test to another. 
```
platform linux -- Python 3.7.4, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
collecting ... 2019-08-21 13:15:10 - conftest - DEBUG - Collected 4 test cases
2019-08-21 13:15:10 - conftest - DEBUG - Deselected test tests.foreman.ui.test_location.test_positive_update_with_all_users
collected 4 …
```

part of test moved to another

---

tests/foreman/ui/test_smartvariable.py

adding a skip to the smartvariable test to check only yaml until https://bugzilla.redhat.com/show_bug.cgi?id=1745938 gets resolved
```
pytest tests/foreman/ui/test_smartvariable.py::test_positive_create_matcher_prioritize_and_delete
========================================================= test session starts ==========================================================
platform linux -- Python 3.7.4, pytest-4.6.3, py-1.7.0, pluggy-0.12.0
collecting ... 2019-08-27 09:51:52 - conftest - DEBUG - Collected 1 test cases …
```

fix-assert-test-create-matcher

---

tests/foreman/virtwho/test_api_virtwho.py
tests/foreman/virtwho/utils.py

1. Add one API testcase for virt-who-configure plugin testing
2. Update deploy_validation() in utils.py so that there will have enough time for virt-who restart process

Add API testcase for virt-who-configure plugin testing

---

tests/foreman/ui/test_host.py

Fixes automation result test, test_positive_assign_compliance_policy.

openscap security from v6 to v7

---

tests/foreman/cli/test_host_collection.py

Before:
```
platform linux -- Python 3.7.4, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
collecting ... 2019-08-22 08:38:02 - conftest - DEBUG - Collected 26 test cases
collected 26 items …
```

tests merged into one end to end test

---

robottelo/api/utils.py
tests/foreman/ui/test_host.py

1. $subject
2. Context Manager that lock unlocks the template for the update.
Currently, this test is failing due to host bug [1] when host group is selected it renders finish template instead of user data one.
[1] : https://bugzilla.redhat.com/show_bug.cgi?id=1746775

GCE Host Provisioning - CloudInit

---

tests/foreman/ui/test_dashboard.py

```
platform linux -- Python 3.7.4, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
collecting ... 2019-09-04 10:31:51 - conftest - DEBUG - Collected 5 test cases
collected 5 items / 4 deselected / 1 selected …
```

ui test dashboard failure

---

tests/foreman/ui/test_host.py

Some tests merged into one end to end test. Failing test wasn't affected with this change.
Merging just 6 tests reduced total execution time by 10 minutes. 
Before:
```
======================================================================================== 2 failed, 26 passed, 14 warnings, 5 error in 4351.58 seconds ========================================================================================
```
After:
```
======================================================================================== 2 failed, 21 passed, 12 warnings, 5 error in 3727.49 seconds ========================================================================================
```

ui hosts test refactoring

---

tests/upgrades/test_errata.py

Refactor the upgrade errata scenario #7230 
```
(env) [root@okhatavk robottelo]# pytest -v -m 'pre_upgrade' tests/upgrades/test_errata.py --capture=no 
2019-09-10 18:29:05 - robottelo - INFO - Started setUpClass: robottelo.test/TestCase
platform linux -- Python 3.4.8, pytest-4.0.2, py-1.7.0, pluggy-0.9.0 -- /home/okhatavk/Satellite/robottelo/env/bin/python3.4
rootdir: /home/okhatavk/Satellite/robottelo, inifile:
plugins: xdist-1.26.1, services-1.3.1, mock-1.10.0, forked-1.0.2, cov-2.6.1
collected 4 items / 2 deselected …
```

refactor the upgrade scenario errata

---

tests/foreman/data/hammer_commands.json

- Newly added/removed/updated options around recent snaps:
```
E           AssertionError: 
E           hammer content-view create
E             Removed options:
E               * product-id
E               * repositories
E               * product
E           
E           hammer content-view update
E             Removed options:
E               * product-id
E               * repositories
E               * product
E           
E           hammer discovery auto-provision
E             Added options:
E               * all
E           
E           hammer discovery reboot
E             Added options:
E               * all
E           
E           hammer host update
E             Added options:
E               * new-location-id
E               * new-organization-id
E               * …
```

Updated the hammer added/removed options

---

robottelo/constants.py

Fixed Issue #7342 
```
Testing started at 4:49 PM ...
/home/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --target test_repository.py::RepositoryTestCase.test_module_stream_list_validation
Launching py.test with arguments test_repository.py::RepositoryTestCase::test_module_stream_list_validation in /home/okhatavk/Satellite/robottelo/tests/foreman/cli
2019-09-11 11:19:22 - conftest - DEBUG - Registering custom pytest_configure
platform linux -- Python 3.4.8, pytest-4.0.2, py-1.7.0, pluggy-0.9.0
rootdir: /home/okhatavk/Satellite/robottelo, inifile:
plugins: xdist-1.26.1, …
```

updated the repo url

---

tests/upgrades/test_capsule.py

- Added coverage around https://bugzilla.redhat.com/show_bug.cgi?id=1746589
- Test result:
```
tests/upgrades/test_capsule.py::Scenario_capsule_sync_3::test_post_user_scenario_capsule_sync_3 2019-09-11 12:36:26 
PASSED2019-09-11 12:39:54 - robottelo - INFO - Started tearDownClass: tests.upgrades.test_capsule/Scenario_capsule_sync_3
```

add post upgrade test around Bug #1746589

---

robottelo/cleanup.py
tests/upgrades/test_containers_removal.py
tests/upgrades/test_remoteexecution.py

Created a common function for all test cases to destroy the VM.

Created a common function for vm cleanup

---

tests/foreman/ui/test_host.py

Fixes test test_positive_assign_compliance_policy

---

robottelo/cleanup.py
robottelo/upgrade_utility.py
tests/upgrades/test_capsule.py
tests/upgrades/test_containers_removal.py
tests/upgrades/test_errata.py
tests/upgrades/test_remoteexecution.py
tests/upgrades/test_repository.py
tests/upgrades/test_subscription.py
tests/upgrades/test_yum_plugins.py

code refactor of upgrade test cases

---

tests/foreman/ui/test_oscapcontent.py
tests/foreman/ui/test_oscappolicy.py

Fixes #7367 - File not found error for Scap UI tests

---

robottelo/constants.py
tests/foreman/ui/test_repository.py

- Added test around 'Recommended Repositories'
- Test result
```
tests/foreman/ui/test_repository.py::test_positive_recommended_repos PASSED                                                                                      [100%]
============================================================== 1 passed, 20 deselected in 149.54 seconds ===============================================================
```

added test around 'Recommended Repositories'

---

tests/foreman/ui/test_contenthost.py

Added a navigation to go to dashboard to grab necessary value for the assertion.

Report Portal assertion failure fix

---

tests/foreman/ui/test_dashboard.py

waiting on SatelliteQE/airgun/pull/399
resolving: #7273 
test result:
```
tests/foreman/ui/test_dashboard.py .                                                                                                                                                                                                   [100%]
================================================================================================== 1 passed, 4 deselected in 144.64 seconds ==================================================================================================
```

add test for tasks dashboard

---

robottelo/constants.py
tests/foreman/api/test_contentview.py

Add test to verify that one can sync repositories with sha512
checksum.

Add test to verify sync of sha512 RPM

---

tests/foreman/cli/test_host.py

Adding test coverage for https://bugzilla.redhat.com/show_bug.cgi?id=1679300
```
=========================================================================================== 1 passed, 61 deselected, 1 warnings in 106.90 seconds ============================================================================================
```

test on updating host location via hammer

---

docs/index.rst

https://github.com/SatelliteQE/robottelo/pull/7205#issuecomment-514227541

Doc for headless browseroption

---

tests/foreman/cli/test_satellitesync.py

each test gets its own directory that it creates and deletes.
Fixed #7255 
See also #7384 
Test results
```
platform linux -- Python 3.6.6, pytest-4.6.3, py-1.8.0, pluggy-0.13.0 -- /home/[*******]/shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/bin/python3.6
rootdir: /home/[*******]/workspace/satellite6-standalone-automation
plugins: xdist-1.25.0, services-1.3.1, forked-1.0.2, mock-1.10.4, env-0.6.2
collecting ... 2019-10-02 20:10:32 - conftest - DEBUG - Collected 61 test cases
collected 61 items / 43 deselected / 18 selected
tests/foreman/cli/test_satellitesync.py::ContentViewSync::test_negative_export_cv_with_background_policy_re …
```

Create separate directories for contentview export tests

---

tests/foreman/api/test_contentview.py

Add test to publish content_view with multiple RPM repos.

Add test to publish content_view with multiple repos

---

requirements.txt
robottelo/decorators/__init__.py
tests/foreman/conftest.py
tests/robottelo/test_decorators.py
tests/upgrades/conftest.py

[Cherry Pick] Updated pytest version from 4.0.2 to 4.6.3

---

tests/foreman/cli/test_host.py

Moving skip if bg open to comment, as bugzilla was closed long time ago.

bz has been closed long ago

---

tests/upgrades/test_errata.py

Fixed the post-upgrade fix, added the latest host get the call to verify the result

fixed test_post_scenario_errata_count_installtion scenario

---

tests/upgrades/test_errata.py

cherry pick for 7410

---

tests/foreman/api/test_product.py

- BZ 1667129
```
tests/foreman/api/test_product.py::ProductTestCase::test_positive_filter_product_list PASSED                                                                          [100%]
================================================================= 1 passed, 17 deselected in 42.32 seconds ==================================================================
```

Added test around BZ#1667129

---

tests/foreman/cli/test_logging.py

Hello
one test (Candlepin) is still unfinished, the test for manifest load, but I wanted more time to get feedback.
Edit: Candlepin test now works with own org.
Edit: Done:  Candlepin test working just with manifest upload event.

Simple CLI Test For logging

---

tests/foreman/sys/test_katello_certs_check.py

Hello
I added test for installing custom certs to running Satellite; to replace stubbed test.
I have also added  @skip_if_not_set('certs') and fixed up the docstrings to make them reflect reality rather than some long ago proposal.

Added test for custom katello certs

---

tests/foreman/cli/test_discoveredhost.py

Discovery Provision with parameters bug #1756042 automated

---

robottelo/cli/factory.py
robottelo/cli/report_template.py
robottelo/cli/template_input.py
robottelo/constants.py
tests/foreman/cli/test_reporttemplates.py
tests/foreman/data/report_template.txt

cli tests are implemented for report templates together with template input class and with changes in factory and constants
TODO report-template report_data and schedule are not covered in tests

report templates cli tests 

---

tests/foreman/virtwho/test_ui_virtwho.py
tests/foreman/virtwho/utils.py

**2 new testcases:**
1.`test_positive_delete_config_delete_user`
2.`test_positive_virt_who_roles_permissions`
**2 new functions in `utils.py`**
1.`restart_virt_who_service`
2.`create_etc_d_file`

Add 2 testcases for virt-who automation

---

tests/foreman/api/test_syncplan.py
tests/foreman/cli/test_syncplan.py

Reduce CLI Syncplan setup times (#7415)
* Reduce setup times from 4 to 2 mins
* Reduce some max_tries settings
* move some product and repo steps to before start_date
* remove skip_if_bug_open 1655595
Reduce API Syncplan test times (#7415)
* Reduce setup times from 4 to 2 mins
* Reduce some max_tries settings
* move some product and repo steps to before start_date
* remove skip_if_bug_open 1396647
* remove skip_if_bug_open 1655595

Issue#7415

---

tests/foreman/cli/test_subscription.py
tests/foreman/ui/test_settings.py

Added automation coverage for Bugzilla's 1686916 and 1677282

Closed Loop: added qe coverage for bugzilla 1686916 and 1677282

---

robottelo/cli/task.py
tests/foreman/cli/test_remoteexecution.py

test coverage for https://bugzilla.redhat.com/show_bug.cgi?id=1647582
```
=========================================================================================== 1 passed, 17 deselected, 1 warnings in 135.04 seconds ============================================================================================
```

add test coverage for task list search

---

robottelo/constants.py
tests/foreman/api/test_repository.py

Add tests related to ignorable_content for SRPM.

Add tests related to ignorable_content for SRPM

---

robottelo/cli/srpm.py
tests/foreman/cli/test_repository.py

Added SRPM CLIs tests

---

tests/foreman/cli/test_contentview.py

Added repo sync to docker repo

Fix repo sync on multi env capsule

---

tests/foreman/ui/test_jobtemplate.py

Depends on:
- [Airgun PR](https://github.com/SatelliteQE/airgun/pull/414)
- [skip if open PR](https://github.com/SatelliteQE/robottelo/pull/7404)
Adding test coverage for [BZ 1705866](https://bugzilla.redhat.com/show_bug.cgi?id=1705866)

test for cloning job templates with foreign input

---

robottelo/issue_handlers/bugzilla.py

Make `get_data_bz` able to deal with empty `bz_number`.

Make get_data_bz more robust

---

tests/foreman/api/test_role.py

Adding an assert to cover https://bugzilla.redhat.com/show_bug.cgi?id=1760701
update: edited to add new style skipping, therefore this is blocked by #7404

add coverage for 1760701

---

robottelo/constants.py
tests/foreman/api/test_contentmanagement.py

Add test to verify encode gzip error for kickstart repositories.

Add test related to kickstart encode error

---

tests/foreman/sys/test_katello_certs_check.py

Closed loop: BZ#1747581
Test creates a Capsule cert, extracts the data from the RPM that contains the cert, and then validates that data.
Thank you

Add test_positive_validate_capsule_certificate

---

tests/foreman/cli/test_organization.py

```
tests/foreman/cli/test_organization.py .                                                                                                                                                                                               [100%]
================================================================================================== 1 passed, 17 deselected in 52.09 seconds ==================================================================================================
```

test coverage for BZ 1644586

---

tests/foreman/api/test_reporttemplates.py

To avoid polarion test case job failure

Remove f-string to make it compatible with py2

---

tests/foreman/cli/test_subscription.py
tests/foreman/ui/test_subscription.py

Adding test for the above bug.
Also, removing a test for a bug that is wontfix

Coverage for BZ 1669241

---

robottelo/constants.py
tests/foreman/api/test_repository.py

Added SRPMs APIs tests

---

tests/foreman/ui/test_errata.py

An added scenario for Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1655130
Needs Airgun PR  https://github.com/SatelliteQE/airgun/pull/420

added scenario for bugzilla_1655130

---

robottelo/api/utils.py
robottelo/helpers.py
tests/foreman/api/test_discoveredhost.py

Automated:
- test_positive_provision_pxe_host
```
=============================== 1 passed, 19 deselected in 807.79 seconds ==============================
```
- test_positive_provision_pxe_host_non_admin (BZ 1638403)
```
=============================== 1 passed, 20 deselected in 443.69 seconds ===============================
```

Discovery BZ:1638403 automated along with first pxe discovery API test

---

tests/foreman/ui/test_repository.py

- Added check to check last version Capsule/Tools repos exist or not .. i.e. bug https://bugzilla.redhat.com/show_bug.cgi?id=1776108

Added check around last sat version capsule/tools repos

---

tests/foreman/api/test_subscription.py
tests/foreman/cli/test_subscription.py

As promised in https://github.com/SatelliteQE/robottelo/pull/7452#pullrequestreview-311632309

Bz1669241 cli api

---

tests/foreman/cli/test_setting.py

Skipping Test Because of Open Bug https://bugzilla.redhat.com/show_bug.cgi?id=1778599

updated the skip bugzilla open 1778599 for test case

---

robottelo/constants.py

Fixed naming convention for red hat software collections.

Export Import CV with huge contents

---

robottelo/issue_handlers/bugzilla.py

Port fix #7486 to 6.6.z branch
as requested in https://github.com/SatelliteQE/robottelo/issues/7486#issuecomment-559426295

Port fix #7486 to 6.6.z branch

---

tests/foreman/api/test_activationkey.py

Based on BZ:1156555 with a won't fix status, deleting test case.

Invalid AK test case

---

tests/foreman/ui/test_settings.py

Test cases to check that a user can change values in a small text box and change values in a large text box.

Input box and text area test case

---

robottelo/cli/factory.py
robottelo/cli/http_proxy.py
tests/foreman/cli/test_http_proxy.py
tests/foreman/ui/test_http_proxy.py

Fixes #7529 - Add CRUD tests for http-proxy component.

---

tests/foreman/cli/test_activationkey.py

See 
https://bugzilla.redhat.com/show_bug.cgi?id=1633094
Test Results
```
platform linux -- Python 3.6.6, pytest-4.6.3, py-1.8.0, pluggy-0.13.1 -- /home/[*******]/shiningpanda/jobs/ad0ef6b5/virtualenvs/d41d8cd9/bin/python3.6
rootdir: /home/[*******]/workspace/satellite6-standalone-automation
plugins: xdist-1.25.0, services-1.3.1, mock-1.10.4, forked-1.1.3, env-0.6.2
collecting ... 2019-12-10 22:30:18 - conftest - DEBUG - Collected 53 test cases
2019-12-10 17:30:18 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7fd0e08d5ba8
2019-12-10 17:30:18 - robottelo.ssh - INFO - Connected to [redacted.example.com]
2019-12-10 …
```

Add closed loop test for bz 1633094

---

tests/foreman/ui/test_host.py

QE-test-coverage
[BZ-link](https://bugzilla.redhat.com/show_bug.cgi?id=1642076#h6)
I figured that I have to use read_all, because read action in Host entity in airgun is defined by `edit 'btn-group'` but when only view_host permissions are used there is no edit button. 
Test result:
```
============= 1 passed, 28 deselected, 2 warnings in 66.39 seconds =============
```

basic host view with neccesary permisssions with non-admin-user

---

tests/foreman/ui/test_package.py

Facter package doesn't exist anymore and the katello-agent has a lot more files in the list.  Switching over to something that exist and has few list of files.

Report Portal Fix

---

tests/foreman/api/test_repository.py
tests/foreman/cli/test_repository.py

- Updated assert based on BZ:1778055
- Add `upgrade` decorator.
- Test results :
```
PASSED2019-12-11 10:15:56 - robottelo - DEBUG - Finished Test: RepositoryTestCase/test_positive_srpm_list_end_to_end
```

Updated assert based on BZ#1778055

---

tests/foreman/cli/test_satellitesync.py

The export error was changed due to a PR from katello #[27838](https://github.com/Katello/hammer-cli-katello/pull/697).  Updating the test case to incorporate the new error message.

Fixing export error message

---

robottelo/cli/hammer.py
tests/robottelo/test_hammer.py

Connected to issue: #7514 
I think this needs a bit of testing, as it can change every `hammer entity info output`. 
But I didn't find any input, output hammer_parser test.

hammer parser, wrong insertion to dictionary when value is a list

---

tests/foreman/api/test_role.py

For https://bugzilla.redhat.com/show_bug.cgi?id=1569395

Stubs for Role Filter with LCE search

---

tests/foreman/ui/test_computeresource.py

Depends on https://github.com/SatelliteQE/nailgun/pull/681 making it to stable-satellite

Disassociate before deleting

---

tests/foreman/cli/test_reporttemplates.py

Report template named 'Ansible Inventory' (default name is specified in settings) must be present in Satellite 6.7 and later in order to provide enhanced functionality for Ansible Tower inventory synchronization with Satellite.
This test checks that the proper template is present on the Satellite side and that it is renderable by a user with minimal required permissions.

Add test for Ansible Tower Inventory syncing

---

tests/foreman/sys/test_rename.py

Previously the satellite-rename tests relied on the original name being the one from settings.server.hostname
In case test_positive_rename_satellite went first in the thread and renamed the satellite successfully, the subsequent negative tests errored on trying to rename to the same name. With this change tests first check the actual hostname of the machine then they adjust it
```
pytest tests/foreman/sys/test_rename.py -k negative
========================================================================================== test session starts ==========================================================================================
collected 5 items / 2 deselected / 3 selected …
```

more isolation for rename tests

---

robottelo/api/utils.py
robottelo/constants.py
robottelo/errors.py
robottelo/helpers.py
tests/foreman/ui/test_computeresource_gce.py
tests/foreman/ui/test_host.py
tests/upgrades/test_host.py

- An upgrade Scenario which tests:

Upgrade Scenario for GCE

---

tests/foreman/api/test_product.py
tests/foreman/api/test_repository.py

Fixes #7560 - Tests for assigning http_proxy to repos.

---

tests/foreman/cli/test_remoteexecution.py

removing the skip_if_not_set from the fixture definition

settings defined outside of fixture definition

---

tests/foreman/api/test_template.py
tests/foreman/endtoend/test_api_endtoend.py

Fixes tests failing in 6.7 for my components.

Fix 6.7 Automation Fixes

---

tests/foreman/cli/test_activationkey.py

Hello
this branch depends on (must not be merged before):
Add test create AK with syspurpose values (#7578)
Thank you

Test update AK with syspurpose values

---

tests/foreman/cli/test_user.py

remove test_negative_create_with_empty_email user test

---

robottelo.properties.sample
robottelo/config/base.py
robottelo/constants.py
tests/foreman/data/uri.sh

- Added support for AzureRM properties

Added support for AzureRM properties

---

tests/foreman/api/test_reporttemplates.py
tests/foreman/cli/test_reporttemplates.py

Created test case in the api to generate a report using the entitlements template. 
Created test cases in the cli to generate reports with formats yaml, json, and csv using the entitlements template.
API:
platform linux -- Python 3.7.5, pytest-4.6.3, py-1.8.0, pluggy-0.13.1 -- /home/colehiggins/projects/venv/bin/python3
rootdir: /home/colehiggins/projects/robottelo
plugins: mock-1.10.4, services-1.3.1
collecting ... 2020-01-22 18:56:30 - conftest - DEBUG - Collected 1 test cases
2020-01-22 13:56:30 - robottelo.issue_handlers.bugzilla - DEBUG - Calling Bugzilla API for {'1680458'}
2020-01-22 13:56:31 - robottelo.ssh - DEBUG - …

Added API and CLI test cases for Entitlement reports

---

robottelo/helpers.py
tests/foreman/api/test_computeresource_gce.py
tests/foreman/conftest.py
tests/upgrades/test_host.py

GCE API Tests - Part 1

---

tests/foreman/cli/test_repository.py

bz1664631 has been closed WONTFIXed.

Wait for image tags to be non-zero unconditionally

---

robottelo/virtwho_utils.py
tests/upgrades/test_virtwho.py

**Description**
Add virt-who upgrade scenarios.
Add 2 files:
1. robottelo/tests/upgrades/test_virtwho.py - virt-who upgrade cases
2. robottelo/robottelo/virtwho_utils.py - copy from /robottelo/tests/foreman/virtwho/utils.py, will use this file in the future, will remove it(virtwho/utils.py) in another PR.
**Test Result**
```
(venv) [hkx303@kuhuang upgrades]$ pytest -m "pre_upgrade" test_virtwho.py;pytest -m "post_upgrade" test_virtwho.py
================================================== test session starts ==================================================
platform linux -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /home/hkx303/Documents/CI/robottelo/robottelo
plugins: services-1.3.1, forked-1.0.2, mock-1.10.4, cov-2.7.1, xdist-1.29.0
collected 2 items / 1 deselected / …
```

Add virt-who upgrade scenarios

---

tests/foreman/cli/test_location.py

loc description now returned in a list
```
pytest tests/foreman/cli/test_location.py -k test_positive_create_update_delete
================================================================== test session starts ==================================================================
collected 8 items / 7 deselected / 1 selected                                                                                                           
tests/foreman/cli/test_location.py .                                                                                                              [100%]
======================================================== 1 passed, 7 deselected in 62.18 seconds ========================================================
```

fixed cli location crud test

---

tests/upgrades/test_virtwho.py

Solved issue:
https://github.com/SatelliteQE/robottelo/issues/7632

create virt-who org using default_location

---

tests/foreman/api/test_contentview.py

This reverts commit 7737854b1cb5012da02284e454f2c7133831c322.

Revert "CV optimize PR" where parameterized tests breaks pytest xDist collection

---

.pre-commit-config.yaml
tests/foreman/sys/test_foreman_rake.py

Update flake8 configuration for pre-commit
Re-apply it, 7553 brought it non-compliant changes.

Fix pre commit

---

tests/foreman/sys/test_rename.py

putting the manifest upload to the single test that actually uses it

moved manifest upload from setupclass

---

robottelo/api/utils.py
robottelo/cli/base.py
robottelo/cli/computeprofile.py
robottelo/cli/computeresource.py
tests/foreman/cli/test_computeresource_azurerm.py

- Added tests around AzureRm CLI 
```
tests/foreman/cli/test_computeresource_azurerm.py::TestAzureRMComputeResourceTestCase::test_positive_crud_azurerm_cr PASSED                                                            [ 14%]
tests/foreman/cli/test_computeresource_azurerm.py::TestAzureRMComputeResourceTestCase::test_positive_crud_finish_template_image PASSED                                                 [ 28%]
tests/foreman/cli/test_computeresource_azurerm.py::TestAzureRMComputeResourceTestCase::test_positive_crud_cloud_init_image PASSED                                                      [ 42%]
tests/foreman/cli/test_computeresource_azurerm.py::TestAzureRMComputeResourceTestCase::test_positive_check_available_networks PASSED …
```

AzureRm CLI automation - part1

---

tests/foreman/ui/test_http_proxy.py

Test Result:
```
$ pytest tests/foreman/ui/test_http_proxy.py -k test_positive_assign_http_proxy_to_products_repositories
2020-02-28 05:53:17 - conftest - DEBUG - Collected 2 test cases
collected 2 items / 1 deselected / 1 selected
tests/foreman/ui/test_http_proxy.py .                                    [100%]
============ 1 passed, 1 deselected, 17 warnings in 494.82 seconds =============
```

Add test for assigning Http proxy to Repository and Products.

---

tests/foreman/ui/test_user.py

This is in regards to a closed loop bz: 1771937.  A user with limited permission should be able to create a product without issues.
Test result:
```
$ pytest tests/foreman/ui/test_user.py::test_positive_create_product_with_limited_user_permission
================================= test session starts ==========================
platform linux -- Python 3.6.8, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /home/ltran/Projects/robottelo
plugins: services-1.3.1, mock-1.10.4
collecting ... 2020-01-09 15:28:12 - conftest - DEBUG - Collected 1 test cases
2020-01-09 10:28:12 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f1fce183cf8
2020-01-09 10:28:12 - robottelo.ssh - INFO - Connected to [dhcp-2-252.vms.sat.rdu2.redhat.com] …
```

Creating Product with limited permissions

---

tests/foreman/data/generate-ca.sh
tests/foreman/data/generate-crt.sh
tests/foreman/data/openssl.cnf
tests/foreman/sys/test_katello_certs_check.py

* Avoids problem of certs expiring
* Avoids tying certs to specific infrastucture servers

Generate custom certs in setup

---

robottelo/constants.py
tests/foreman/ui/test_ldap_authentication.py

- an added scenario for new RHSSO user and verify the login details. 
- Fixed flaky test-related to https AD instance
- Refactored rhsso helper methods 
```
Launching py.test with arguments test_ldap_authentication.py::test_positive_create_with_ad_https in /home/okhatavk/Satellite/robottelo/tests/foreman/ui                     [100%]
========================== 1 passed in 275.29 seconds ==========================
test_ldap_authentication.py                                             [100%]
========================== 1 passed in 128.38 seconds ==========================
```

added rhsso scenario, fix flaky tests and refactored some tests

---

tests/foreman/api/test_discoveryrule.py

Refactor tests to end to end

---

tests/foreman/ui/test_contenthost.py

Closed loop test for:
Bug 1651852 - Missing timeout for "Actions::Katello::Host::Package::Update" task

Add test for package update timeout

---

robottelo/rhsso_utils.py
tests/foreman/ui/test_ldap_authentication.py

- Refactored/Reorganise the code so it can be used across CLI and API 
- Eventually, Reduce the size of the file LDAP tests. 
- New code can mange properly

refactored the rhsso code as this needs in API or CLI tests

---

tests/foreman/ui/test_settings.py

Automated 2 stubbed test cases one for positive and other for the negative scenario.
1- test_positive_update_login_page_footer_text_with_long_string
2- test_negative_settings_access_to_non_admin

Automated stubbed test cases of settings.

---

tests/foreman/ui/test_settings.py

Airgun issue.
https://github.com/SatelliteQE/airgun/issues/476

Added settings "Sendmail" test case to verify the "Test Email" functionality. 

---

requirements.txt

SSIA.
See:
- https://github.com/SatelliteQE/robottelo/issues/7731
- https://github.com/SatelliteQE/nailgun/issues/713
- https://github.com/SatelliteQE/airgun/issues/478

Update requirements for 6.7.z

---

tests/foreman/ui/test_contenthost.py

Hello
This is close loop test for:
Bug 1642549 - Content Host filter is showing only 1 page of result
https://bugzilla.redhat.com/show_bug.cgi?id=1642549

Add test for C-Host pagination

---

tests/foreman/ui/test_ldap_authentication.py

 added the upgrade decorator

---

tests/foreman/cli/test_reporttemplates.py

This caused consistent failures in automation.

Reports ids are not stable accross instances.

---

robottelo/vm.py

[6.7.z] re-adding changes to robottelo vm after wrong squash

---

tests/foreman/ui/test_oscappolicy.py
tests/foreman/ui/test_oscaptailoringfile.py

Airgun PR: https://github.com/SatelliteQE/airgun/pull/482

Fixes Oscap policy UI tests

---

tests/foreman/virtwho/test_cli_virtwho.py

#7749
Converted cases as below:
-  test_positive_deploy_configure_by_id
-  test_positive_deploy_configure_by_script
-  test_positive_debug_option
-  test_positive_interval_option
-  test_positive_hypervisor_id_option
-  test_positive_filter_option
-  test_positive_proxy_option
-  test_positive_rhsm_option
-  test_positive_post_hypervisors

Convert virt-who cli cases to Pytest

---

tests/foreman/ui/test_ldap_authentication.py

Audience Settings is changed now from String to Array(list) type, updated that fix in test code. This is after valid changes are made in the product side

updated the settings related to rhsso

---

tests/foreman/api/test_setting.py

Automation for stubbed test "test_negative_update_hostname_with_empty_fact"

---

tests/foreman/cli/test_contentview.py

The test case has a bz with closed errata status so moving this to be part of automation run.  Removing ostree because it's deprecated until 7.0
```
$ pytest tests/foreman/cli/test_contentview.py -k test_positive_republish_after_content_removed
============================= test session starts =================
platform linux -- Python 3.6.8, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /home/ltran/Projects/robottelo
plugins: services-1.3.1, mock-1.10.4
collecting ... 2020-05-13 21:04:28 - conftest - DEBUG - Collected 102 test cases
2020-05-13 17:04:28 - robottelo.issue_handlers.bugzilla - DEBUG - Calling Bugzilla API for {'1625783', '1610309'}
2020-05-13 17:04:29 - robottelo.ssh - DEBUG - Instantiated Paramiko client …
```

Fix up test case

---

tests/foreman/api/test_template.py

- replacing deprecated `config_template` references by `provisioning_templates`
- refactor crud tests for api `ProvisioningTemplate` tests
- unittest to pytest conversion for api `ProvisioningTemplate` tests
- refactor `test_positive_build_pxe_default` test case
```
Testing started at 12:10 AM ...
/home/rplevka/.virtualenvs/robottelo/bin/python /usr/share/java/pycharm-community/plugins/python-ce/helpers/pycharm/_jb_pytest_runner.py --target test_template.py::TestProvisioningTemplate
Launching pytest with arguments test_template.py::TestProvisioningTemplate in /home/rplevka/work/rplevka/robottelo/tests/foreman/api
platform linux -- Python 3.7.7, pytest-4.6.3, py-1.8.1, pluggy-0.13.1 -- …
```

[api] Provisioning templates test refactor

---

tests/foreman/ui/test_reporttemplates.py

```
$ pytest tests/foreman/ui/test_reporttemplates.py::test_positive_schedule_generation_and_get_mail
==================================================== test session starts =====================================================
platform linux -- Python 3.7.7, pytest-4.6.3, py-1.8.1, pluggy-0.13.1
plugins: forked-1.1.3, cov-2.8.1, mock-1.10.4, xdist-1.31.0, services-1.3.1
collecting ... 2020-05-12 13:26:03 - conftest - DEBUG - Collected 1 test cases
2020-05-12 15:26:04 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7fcb72600a10
2020-05-12 15:26:04 - robottelo.ssh - INFO - Connected to [dhcp-3-76.vms.sat.rdu2.redhat.com]
2020-05-12 15:26:04 - robottelo.ssh - INFO - >>> rpm -q satellite …
```

Ui report schedule

---

tests/foreman/ui/test_host.py

[cherry-pick] more storage size to gce tests

---

robottelo/datafactory.py
tests/foreman/api/test_usergroup.py

Test results:
```
collected 64 items       
test_usergroup.py::TestUserGroup::test_positive_create_with_name[alpha] PASSED            [  1%]
test_usergroup.py::TestUserGroup::test_positive_create_with_name[numeric] PASSED         [  3%]
test_usergroup.py::TestUserGroup::test_positive_create_with_name[alphanumeric] PASSED [  4%]
test_usergroup.py::TestUserGroup::test_positive_create_with_name[latin1] PASSED    [  6%]
test_usergroup.py::TestUserGroup::test_positive_create_with_name[utf8] PASSED      [  7%]
test_usergroup.py::TestUserGroup::test_positive_create_with_name[cjk] PASSED       [  9%]
test_usergroup.py::TestUserGroup::test_positive_create_with_name[html] PASSED      [ 10%]
test_usergroup.py::TestUserGroup::test_positive_create_with_user[alpha] PASSED     [ 12%] …
```

conversion to pytest

---

tests/foreman/cli/test_errata.py

This implements stubbed out test for restrict flags.
I changed the repo for the class to FAKE_9_YUM_REPO. This was to make use of some of the constants related to that repo. That means I need to test the whole class.
Thank you

Add test affected_chosts_by_erratum_restrict_flag

---

tests/foreman/api/test_contentview.py

IMO, this is a low impact test case that should be removed.  Let me know if you think otherwise.

Code Coverage 1: low impact test case

---

robottelo/cli/factory.py

[Fixes Travis Failing] Removed hammer options help from factory helper docstrings

---

tests/foreman/api/test_errata.py

Replacing hard coded values with erratum count constants

Add erratum count constants

---

robottelo/api/entity_fixtures.py
tests/foreman/api/test_oscap_tailoringfiles.py
tests/foreman/api/test_oscappolicy.py
tests/foreman/conftest.py

Test Results:
```
$ pytest tests/foreman/api/test_oscappolicy.py 
=================================================================================== test session starts ===================================================================================
collecting ... 2020-05-27 08:52:50 - conftest - DEBUG - Collected 1 test cases
2020-05-27 14:22:53 - robottelo.ssh - INFO - >>> rpm -q satellite
2020-05-27 14:22:55 - robottelo.ssh - INFO - <<< stdout
satellite-6.8.0-0.3.beta.el7sat.noarch
2020-05-27 14:22:55 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f1e73f81470
2020-05-27 14:22:55 - robottelo.host_info - DEBUG - Host Satellite version: 6.8
2020-05-27 14:22:55 - robottelo.helpers - DEBUG - Generated file bz_cache.json with BZ collect data …
```

Add API crud testcase for Oscap feature

---

tests/foreman/api/test_user.py

~Depends on #7824~
Test results:
```
pytest -v test_user.py
========================================= test session starts =========================================
platform linux -- Python 3.8.3, pytest-4.6.3, py-1.8.1, pluggy-0.13.1 
-- /home/pdragun/.virtualenvs/test_robottelo/bin/python
plugins: mock-1.10.4, services-1.3.1, cov-2.9.0, xdist-1.32.0, forked-1.1.3
collecting 121 items                                                                                  
2020-06-10 11:28:30 - conftest - DEBUG - Collected 141 test cases
2020-06-10 13:28:31 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f661d997220
2020-06-10 13:28:31 - robottelo.ssh - INFO - …
```

convert api user tests to pytest

---

tox.ini

Fix travis-tox for fixture plugins PR

---

tests/foreman/ui/test_settings.py

I have added a test case for settings to test the entries_per_page feature.
Validation Point:
- The value should be updated from UI.
- After the update changes should be applied in the Monitors task's page (per page entry and page count should be updated according to the new set value)
Test Result:
```
pytest tests/foreman/ui/test_settings.py::test_positive_entries_per_page
tests/foreman/ui/test_settings.py .                                                                                                                                                                         [100%] …
```

Add test for entries per page in settings.

---

tests/foreman/cli/test_errata.py

Closed loop: BZ#1810774
[Bug 1810774 - Applying errata via Host Collection the errata are trying to be applied to all hosts associated with the host collection](https://bugzilla.redhat.com/show_bug.cgi?id=1810774)

Add test install errata to one host in a hc

---

tests/foreman/ui/test_computeresource_azurerm.py

- Updated tests based on new enhancement 
```
tests/foreman/ui/test_computeresource_azurerm.py::test_positive_end_to_end_azurerm_ft_host_provision PASSED                                                           [ 50%]
tests/foreman/ui/test_computeresource_azurerm.py::test_positive_azurerm_host_provision_ud PASSED                                                                      [100%]
```

[Azure-UI] Updated tests based on enhancements

---

tests/foreman/ui/test_errata.py

Tests search commands in web UI's Content Hosts page.
Tests for Applicable versus Installable
closed loop for:
[Bug 1707335 - Unable to search the content host list in Satellite 6.4 webui using the filter 'errata_status = security_needed' and 'errata_status = errata_needed'](https://bugzilla.redhat.com/show_bug.cgi?id=1707335)

Add test c-host errata search commands web ui

---

pytest_fixtures/api_fixtures.py
tests/foreman/api/test_computeresource_azurerm.py

- Updated tests based on new enhancements 
- Added tests around ``Shared Gallery and Custom Image``
```
tests/foreman/api/test_computeresource_azurerm.py::TestAzureRm_Shared_Gallery_FinishTemplate_Provisioning::test_positive_azurerm_shared_gallery_host_provisioned PASSED [100%]
tests/foreman/api/test_computeresource_azurerm.py::TestAzureRm_Custom_Image_FinishTemplate_Provisioning::test_positive_azurerm_custom_image_host_provisioned PASSED   [100%]
```

[Azure-API] Updated and added tests

---

tests/foreman/ui/test_errata.py

Hello
This test depends on updates to robottelo/constants.py in:
Fix fake 9 security erratum constant #7806 
I will rebase when that is merged.
Edit: Done
Thank you

Improve errata test pos c-host search type

---

tests/foreman/cli/test_user.py

```
pytest tests/foreman/cli/test_user.py::UserTestCase::test_positive_CRUD
platform linux -- Python 3.7.7, pytest-4.6.3, py-1.7.0, pluggy-0.12.0
plugins: repeat-0.8.0, cov-2.10.0, mock-1.10.4, forked-0.2, services-1.3.1, xdist-1.33.0
collecting ... 2020-07-17 08:07:32 - conftest - DEBUG - Collected 1 test cases
collected 1 item                                                                                                     
tests/foreman/cli/test_user.py .                                                                               [100%] …
```

fixes in cli user tests

---

tests/foreman/cli/test_host.py

There should be 4 SLES distro versions, 
I want run `test_positive_report_package_installed_removed` for all of them. `[11.4,12.3,12.4,15.1]`.
If you need any additional info to approve this commit please let me know. 
I am definitely not sure by all of the tags that should be used here.

adding stubbed test case for SLES 6.8 feature

---

robottelo/constants.py

test result:
```
pytest tests/foreman/api/test_permission.py::PermissionTestCase::test_positive_search
tests/foreman/api/test_permission.py .                                                                         [100%]
============================================= 1 passed in 15.05 seconds ==============================================
```
Other tests in the class fail due to the nailgun issue https://github.com/SatelliteQE/nailgun/issues/731

updated permissions

---

tests/foreman/cli/test_model.py

Test results:
```
pytest -v tests/foreman/cli/test_model.py
================================== test session starts ===================================
platform linux -- Python 3.7.8, pytest-4.6.3, py-1.8.0, pluggy-0.12.0 --
collecting ... 2020-08-20 11:21:56 - conftest - DEBUG - Collected 32 test cases
collected 32 items                                                                       
tests/foreman/cli/test_model.py::TestModel::test_positive_crud_with_name[0] PASSED      [  3%]
tests/foreman/cli/test_model.py::TestModel::test_positive_crud_with_name[1] PASSED      [  6%] …
```

convert cli/model to pytest

---

tests/foreman/installer/test_installer.py

Added stubbed test cases of the Satellite and Capsule installation for IPv6. All these test cases execute on IPv6 machine manually.

Added Stubbed test cases of Satellite and Capsule installation on IPv6.

---

tests/foreman/longrun/test_capsule_loadbalancer.py

For the reference of tests, please visit [Test matrics](https://docs.google.com/spreadsheets/d/1ERA9g-nVsKOFVrxIv5R3wj_Mzxh_yvcoU4JM2_HnUBU/edit?usp=sharing) sheet.

Stubbed test cases for capsule loadbalancer

---

tests/foreman/api/test_architecture.py

Removing the Test Class in order to make the individual test parametrization work
```
$ pytest test_architecture.py 
===================== test session starts =====================
platform linux -- Python 3.7.7, pytest-4.6.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/rplevka/work/rplevka/robottelo
plugins: xdist-1.33.0, services-1.3.1, forked-1.2.0, repeat-0.8.0, cov-2.10.1, mock-1.10.4
collecting ... 2020-08-28 18:38:49 - conftest - DEBUG - Collected 15 test cases
collected 15 items                                            
test_architecture.py ...............                    [100%]
====================== warnings summary =======================
```

remove the TestClass

---

robottelo/api/utils.py
tests/foreman/ui/test_lifecycleenvironment.py
tests/foreman/ui/test_repository.py

Reverts SatelliteQE/robottelo#7928
See https://github.com/SatelliteQE/robottelo/issues/7958

Revert "Filter: Resourch Type changes for roles" (#7958)

---

tests/foreman/ui/test_ldap_authentication.py

Verify the failure of login for the external rhsso user in case same username internal user exists.
```
plugins: forked-1.1.3, xdist-1.31.0, cov-2.8.1, mock-1.10.4, services-1.3.12020-09-02 12:54:14 - conftest - DEBUG - Collected 1 test cases
test_ldap_authentication.py                                             [100%]
```

[qe_test-coverage] - added qe coverage for bugzilla 1873439

---

tests/foreman/ui/test_contenthost.py

- Install modular errata using katello-agent
- Added as qe coverage for https://bugzilla.redhat.com/show_bug.cgi?id=1713417
```
Testing started at 6:44 PM ...
/home/okhatavk/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --target test_contenthost.py::test_install_modular_errata
Launching py.test with arguments test_contenthost.py::test_install_modular_errata in /home/okhatavk/Satellite/robottelo/tests/foreman/ui
plugins: forked-1.1.3, xdist-1.31.0, …
```

[qe_test-coverage] - Install modular errata using katello-agent bugzilla 1713417

---

robottelo/constants.py
tests/foreman/ui/test_remoteexecution.py

The test was added pre 6.7 in connection with manual mode feature -- essentially preparation for leapp integration. For 6.8 the integration is complete and took a different course, making this test no longer valid.

removing rex manual mode test

---

testimony.yaml

SSIA, no testing needed.
Component is already added in Bugzilla and Polarion.

Add new component (Leapp integration) to testimony config

---

tests/foreman/ui/test_ldap_authentication.py

```
pytest tests/foreman/ui/test_ldap_authentication.py -k test_onthefly_functionality
platform linux -- Python 3.6.8, pytest-4.6.3, py-1.9.0, pluggy-0.13.1
plugins: services-1.3.1, mock-1.10.4, cov-2.10.1, forked-1.3.0, xdist-2.1.0
collecting ... 2020-09-05 13:09:37 - conftest - DEBUG - Collected 30 test cases
collected 30 items / 29 deselected / 1 selected                                                                                                                             
tests/foreman/ui/test_ldap_authentication.py . …
```

Test: onthefly functionality

---

tests/foreman/api/test_location.py

Test results:
```
pytest -v test_location.py 
platform linux -- Python 3.8.3, pytest-4.6.3, py-1.8.1, pluggy-0.13.1 -- /home/pdragun/.virtualenvs/test_robottelo/bin/python
plugins: mock-1.10.4, services-1.3.1, cov-2.9.0, xdist-1.32.0, forked-1.1.3
collecting ... 2020-06-03 10:23:59 - conftest - DEBUG - Collected 32 test cases
2020-06-03 12:23:59 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7fe0cb5c4b20
2020-06-03 12:23:59 …
```

convert api location test to pytest

---

tests/foreman/cli/test_realm.py

```
pytest tests/foreman/cli/test_realm.py -k test_positive_delete_by_name
tests/foreman/cli/test_realm.py .                                                                              [100%]
============================================= 1 passed in 28.95 seconds =============================================
```

realm tests moved to pytest

---

tests/foreman/ui/test_ldap_authentication.py

These are the manual tests needed to run with CAC card.

added CAC card manual tests related to rhsso

---

tests/foreman/ui/test_computeresource_azurerm.py

Fix AzureRM test assertions thats causing tests to fail.

Fix AzureRM assertions

---

tests/foreman/ui/test_hostcollection.py

due to API change
need to change 
data={'environment_id' to data={'environment_ids'

Change environment_id to environment_ids (#8000)

---

tests/foreman/sys/test_katello_certs_check.py

```
plugins: forked-1.1.3, xdist-1.31.0, cov-2.8.1, mock-1.10.4, services-1.3.12020-09-11 14:52:27 - conftest - DEBUG - Collected 12 test cases
collected 12 items
========= 5 passed, 7 skipped, 5 warnings in 760.95 seconds ========== 
```

pytest conversion for component certificate

---

tests/foreman/api/test_hostcollection.py

Hello
this depends on:
https://github.com/SatelliteQE/nailgun/pull/747

Adding a "remove subs from a host collection" step

---

tests/foreman/api/test_hostcollection.py

ref: nailgun issue#750
Hello this PR depends on https://github.com/SatelliteQE/nailgun/pull/754

fix to use subscription entity

---

tests/foreman/ui/test_syncplan.py

Closed loop: [BZ#1693795](https://bugzilla.redhat.com/show_bug.cgi?id=1693795)
Hello
Depends on https://github.com/SatelliteQE/airgun/pull/523

Add check for save after product remove

---

pytest_fixtures/api_fixtures.py
tests/foreman/api/test_templatesync.py
tests/foreman/cli/test_satellitesync.py
tests/foreman/cli/test_templatesync.py
tests/foreman/ui/test_templatesync.py

Automated Bugs:
https://bugzilla.redhat.com/show_bug.cgi?id=1778177
https://bugzilla.redhat.com/show_bug.cgi?id=1778139
https://bugzilla.redhat.com/show_bug.cgi?id=1778181
https://bugzilla.redhat.com/show_bug.cgi?id=1671319
and a fix of:
https://bugzilla.redhat.com/show_bug.cgi?id=1856287 (including default org / loc fixture)

Close Loop 1 and fix of 1856287

---

pytest_fixtures/satellite_auth.py
requirements.txt
robottelo/api/utils.py
robottelo/rhsso_utils.py
tests/foreman/cli/test_ldapauthsource.py
tests/foreman/ui/test_ldap_authentication.py

1. Added RH-SSO-Satellite CLI integration tests.
2. Refactored the RH-SSO utils and common utils files.
3. Added support for the Pexpect python module. 
```
plugins: forked-1.1.3, xdist-1.31.0, cov-2.8.1, mock-1.10.4, services-1.3.12020-08-11 10:43:49 - conftest - DEBUG - Collected 3 test cases
collected 3 items
test_ldapauthsource.py                                                [100%]
```
https://github.com/SatelliteQE/airgun/pull/503

added rh_sso cli tests, refactored some common code

---

tests/foreman/cli/test_repository.py

Hello
"Forbidden" failure message is now "Access denied."

Update failure message

---

tests/foreman/cli/test_reporttemplates.py

Test 'Host - compare content hosts packages' (closed loop).

Closed loop: BZ 1860351 , BZ 1860430

---

tests/foreman/ui/test_ldap_authentication.py

When the user is created manually(i.e., onthefly disabled) from an authsource, the attributes such as first name, last name and email should be synced with LDAP.

qe_test_coverage for BZ:1670397

---

tests/foreman/api/test_lifecycleenvironment.py

Convert all test cases into pytest for api/lce

Pytest conversion for api/lifecycleenvironment

---

tests/foreman/ui/test_contentview.py

This test case is confusing, unnecessary, low priority, and plainly makes no sense.  The main goal is to subscribe to a repo, but it seems to be more focused on testing filters.  Both are captured else where already so I'm deleting this test case.

Remove confusingly named test case in cv

---

tests/foreman/longrun/test_n_1_upgrade.py

Added stubbed test cases of the N-1 upgrade. All these test cases execute on the N-1 environment(Satellite one version ahead of capsule).

Added N-1 stubbed test cases for upgrade

---

robottelo/constants/__init__.py
tests/foreman/cli/test_contentaccess.py

Simple Content Access test was very slow
Use only CDN Tools repo for SCA tests
Use RPMs from that repo to trigger errata

Improve and simplify SCA test

---

tests/foreman/cli/test_host.py

cherry pick test fix test_negative_without_attach_with_lce

---

tests/foreman/cli/test_host.py

cherry pick - test syspurpose fix

---

tests/foreman/endtoend/test_api_endtoend.py

Changes and their source:
/api/hosts/:host_id/subscriptions/events is marked as deprecated in 6.7;
reports dropped in https://bugzilla.redhat.com/show_bug.cgi?id=1791658;
scap_content_profiles in https://github.com/theforeman/foreman_openscap/pull/431/files;
override_values is in 6.7 already;
template=>templates is https://projects.theforeman.org/issues/28750/ (only category name changed, path is same);
status dropped in https://bugzilla.redhat.com/show_bug.cgi?id=1791656;
available_virtual_machines added in https://projects.theforeman.org/issues/28548;
recurring logics bulk_destroy added in https://github.com/theforeman/foreman-tasks/pull/501;
bulk_cancel added in https://github.com/theforeman/foreman-tasks/pull/516;
bulk_stop added in …

Changing expected API endpoints.

---

tests/foreman/api/test_setting.py

The purpose of this test case is to validate the default download policy of the custom repository, The default download policies value of the new creating repository gets changed according to the set value in the settings.
In this test case, we are validating both available policies.
Test Results:
```
$ pytest tests/foreman/ui/test_settings.py::test_positive_custom_repo_download_policy
platform linux -- Python 3.6.6, pytest-4.6.3, py-1.8.1, pluggy-0.13.1 …
```

Added test case for custom repo download policies

---

tests/foreman/api/test_lifecycleenvironment.py
tests/foreman/api/test_location.py
tests/foreman/api/test_organization.py
tests/foreman/cli/test_ldapauthsource.py
tests/foreman/cli/test_remoteexecution.py
tests/foreman/cli/test_role.py

Missing token results in mismatched polarion result uploading.

Fix parametrized tokens for polarion

---

requirements.txt

Breaking change for using the ibutsu instance hosted by the IQE team.

Ibutsu server has moved to PSQL, requiring dependencies version bump

---

tests/foreman/cli/test_lifecycleenvironment.py

Pytest conversion for cli_lce.
Refactored all CRUD test cases into one.  Can someone checkout the last two test cases and see if they're ok the way they are or if there's another way to refactor them.
```
pytest tests/foreman/cli/test_lifecycleenvironment.py
====================== test session starts =====================
platform linux -- Python 3.7.7, pytest-4.6.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/ltran/Projects/robottelo
plugins: services-1.3.1, forked-1.3.0, ibutsu-1.0.34, xdist-1.34.0, mock-1.10.4, cov-2.10.1
collecting ... 2020-10-19 21:15:41 - conftest - DEBUG - Collected 5 test cases
collected 5 items …
```

pytest conversion for lifecycleenvironment cli

---

robottelo/cli/factory.py
robottelo/cli/ldapauthsource.py
robottelo/constants/__init__.py
robottelo/rhsso_utils.py
tests/foreman/ui/test_ldap_authentication.py

```
Testing started at 9:14 PM ...
/home/okhatavk/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --target test_ldap_authentication.py::test_user_permissions_rhsso_user_multiple_group
Launching py.test with arguments test_ldap_authentication.py::test_user_permissions_rhsso_user_multiple_group in /home/okhatavk/Satellite/robottelo/tests/foreman/ui
plugins: forked-1.1.3, cov-2.8.1, mock-1.10.4, xdist-1.34.0, lazy-fixture-0.6.3, services-1.3.12020-10-19 15:44:12 …
```

added the user-group sync test with external auth rhsso

---

tests/foreman/ui/test_ldap_authentication.py

Fixes duplicate fixture introduced by #8045

Fix duplicate fixture definition

---

tests/foreman/cli/test_capsule_installer.py

Cherry-picking PR #8094 into 6.8.z

[cherry-pick] Remove test_positive_reinstall_on_same_node_after_remove

---

tests/foreman/cli/test_syncplan.py

Hello
Convert cli syncplan unittest to pytest
Thank you

Convert cli syncplan unittest to pytest

---

tests/foreman/api/test_remoteexecution.py

Cherry-picking PR #8087 into 6.8.z

[cherry-pick] Add tests for Capsule Upgrade playbook

---

requirements.txt

Update all direct git requirements to specify a branch explicitly

Update nailgun requirement to use master branch

---

pytest_plugins/rerun_rp/README.adoc

This PR:
The Doc Preview:
https://github.com/jyejare/robottelo/blob/update_rerunrp_doc/pytest_plugins/rerun_rp/README.adoc

Update the Rerun RP plugin doc with new improvements

---

tests/foreman/installer/test_installer.py

The purpose of this PR to convert installers test cases from unit-test to pytest.
```
$ pytest tests/foreman/installer/test_installer.py
platform linux -- Python 3.6.6, pytest-6.1.1, py-1.9.0, pluggy-0.13.1                                                                                                                                                                                                 
tests/foreman/installer/test_installer.py ...sss …
```

Pytest conversion for installer test cases

---

tests/foreman/api/test_syncplan.py

Convert API syncplan from unittest to pytest

---

tests/foreman/conftest.py
tests/robottelo/test_helpers.py

Simply ran pre-commit.  A few urgent PRs were merged without waiting for travis, a few reformats were missed.

Fix Black formatting

---

tests/foreman/virtwho/api/test_kubevirt.py
tests/foreman/virtwho/cli/test_kubevirt.py

I broke this in #8092, missed in review/CI.

Fix skip_if_open marker use

---

tests/foreman/ui/test_ldap_authentication.py

PR: Updating the 4 tests so that they use the new ipa_data() values.

Fix authentication tests

---

tests/foreman/api/test_computeresource_gce.py

Cherrypicks https://github.com/SatelliteQE/robottelo/pull/8144 to `6.8.z`

[6.8.z] Fix fixture resolution on a typo

---

tests/foreman/cli/test_reporttemplates.py

https://github.com/SatelliteQE/robottelo/pull/8089

Cherry pick - Add report to default org before using it. Some tests remove it. Fixes automation.

---

Dockerfile

This should allow the build to complete.
Anyone using this container will need to overwrite settings at runtime.

Add broker_settings.yaml to Dockerfile

---

pytest_plugins/manual_skipped.py
pytest_plugins/rerun_rp/rerun_rp.py
robottelo/cleanup.py
robottelo/cli/factory.py
robottelo/config/base.py
robottelo/config/virtwho.py
robottelo/decorators/__init__.py
robottelo/decorators/func_locker.py
robottelo/decorators/func_shared/file_storage.py
robottelo/decorators/func_shared/shared.py
robottelo/decorators/host.py
robottelo/helpers.py
robottelo/host_info.py
robottelo/hosts.py
robottelo/libvirt_discovery.py
robottelo/report_portal/portal.py
robottelo/ssh.py
robottelo/test.py
robottelo/utils/issue_handlers/bugzilla.py
robottelo/vm.py
robottelo/vm_capsule.py
tests/foreman/api/test_multiple_paths.py

Plinko fails if logger called using  __name__

Call robottelo by name for logger

---

pytest_plugins/markers.py

This marker will be used by component owners to define a sanity test collection.

Add sanity marker

---

virtwho.properties.sample

Add the virtwho.properties.sample file

---

tests/foreman/cli/test_role.py
tests/foreman/cli/test_user.py

tests.foreman.cli.test_role.TestRole.test_positive_create_with_permission (from tier1-parallel)
Took 22 sec.
tests.foreman.cli.test_user.UserTestCase.test_positive_CRUD_admin (from tier1-parallel)
Took 1 min 14 sec.

sanity decorators for user and role tests

---

tests/foreman/api/test_host.py

adding sanity host test introduced in #8153 
the `test_positive_create_and_update_with_name` in my environment takes `~21 sec`

sanity host test

---

robottelo/cli/factory.py

Travis was failing due to docs build issues. This should fix Travis CI for 6.7.z

Fix docs build for 6.7.z

---

tests/upgrades/test_activation_key.py

The purpose of this PR to convert test_activation_keys customer upgrade scenarios from unit test to pytest.
**Test Results**
1.  **Pre-Upgrade:**
```
$ pytest -m "pre_upgrade" tests/upgrades/test_activation_key.py
platform linux -- Python 3.6.6, pytest-6.1.1, py-1.9.0, pluggy-0.13.1                                                                                                                                                             
tests/upgrades/test_activation_key.py . …
```

[Upgrade Customer Scenario]Pytest conversion for activation keys test cases

---

tests/foreman/api/test_contentmanagement.py

The conversion of `tests/foreman/api/test_contentmanagement.py` to pytest makes the following changes:
1.) Change class names, remove inheritance from unittest class `APITestCase`.
`ContentManagementTestCase` -> `TestSatelliteContentManagement`
`CapsuleContentManagementTestCase` -> `TestCapsuleContentManagement`
2.) Change unittest `assert*` method calls to regular `assert` calls.
3.) Move capsule VM setup and teardown from unittest `setUpClass` and `tearDownClass` class methods to a class-scoped pytest fixture named `capsule_vm`. Use the fixture instead of a test class/instance attribute for tests that need it.
4.) Move `skip_if_not_set` decorators from the deleted `setUpClass` method to each test directly.
5.) Use f-strings.
Test output:
```
tests/foreman/api/test_contentmanagement.py …
```

Convert test_contentmanagement from unittest to pytest

---

pytest_fixtures/api_fixtures.py

Fixtures shouldn't have default arguments like `default_os` was using.
If the fixture is to be indirectly parametrized, it should use `request.param` instead to specify an argument from the requesting scope at runtime.
This impacts many modules and tests, and we may want a larger run, but for some context and validation, test_architecture does use `default_os` fixture.
From what I've seen so far, there aren't any test cases parametrizing default_os. I'll continue to look.
```
setup@localhost:~/repos/robottelo (bad-fixture-signature%=) % pytest -vx tests/foreman/api/test_architecture.py 
=========================================================== test session starts ===========================================================
platform linux -- Python 3.8.6, pytest-5.4.3, py-1.9.0, …
```

Update `default_os` fixture with correct signature and indirect parametrization

---

tests/foreman/ui/test_ldap_authentication.py

Updating the tests so that new ipa_data() values are used.

Fix auth tests

---

tests/foreman/api/test_permission.py

Test results:
```
================================== test session starts ===================================
platform linux -- Python 3.7.9, pytest-4.6.3, py-1.9.0, pluggy-0.13.1 --
collecting ... 2020-11-02 12:46:55 - conftest - DEBUG - Collected 15 test cases
collected 15 items                                                                       
tests/foreman/api/test_permission.py::TestPermission::test_positive_search_by_name PASSED [  6%]
tests/foreman/api/test_permission.py::TestPermission::test_positive_search_by_resource_type PASSED [ 13%] …
```

convert api/test_permission to pytest

---

tests/foreman/cli/test_location.py

This PR converts `tests/foreman/cli/test_location.py` to use pytest. Setup and teardown for location, proxy, and other records are moved to helper / fixture methods.
Test output:
```
collected 8 items
tests/foreman/cli/test_location.py ........                              [100%]
[...]
================== 8 passed, 3 warnings in 523.80s (0:08:43) ===================
```

Pytest conversion for test_location

---

tests/foreman/cli/test_realm.py

The idea is to clean up only if it actually frees up resources

no cleanup on fake capsules

---

docs/code_standards.rst

This pr introduces some new changes to this project's code standards.
Highlighted changes revolve around string formatting, fixture naming,
string concatenation, and black.

Update code standards

---

pytest_plugins/rerun_rp/rerun_rp.py

[CherryPick - #8109] Fix Reruning all failed tests check

---

tests/upgrades/test_usergroup.py

The purpose of this PR to convert the test_usergroup unit test(Customer upgrade scenario) to pytest.
Test Results:
**Pre-Upgrade:**
```
$ pytest -m "pre_upgrade" tests/upgrades/test_usergroup.py 
collected 2 items / 1 deselected / 1 selected                                                                                                                                                                     
tests/upgrades/test_usergroup.py . …
```

[Upgrade Customer Scenario] Pytest conversion for test_usergroup. 

---

robottelo/constants/__init__.py

```
pytest tests/foreman/api/test_permission.py -k test_positive_search_by_name
tests/foreman/api/test_permission.py .                                                                         [100%]
============================== 1 passed, 14 deselected, 2 warnings in 214.92s (0:03:34) ==============================
```

permission changes

---

requirements-optional.txt

Remove docker-py from requirements

---

tests/upgrades/test_syncplan.py

The purpose of this PR to convert the syncplan unit test(Customer upgrade scenario) to pytest and check the update of all the sync interval types.
Test Results:
**Pre-Upgrade**
```
$ pytest -s -m "pre_upgrade" tests/upgrades/test_syncplan.py
platform linux -- Python 3.6.6, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
plugins: rerunfailures-9.1.1, forked-1.1.3, mock-1.10.4, xdist-1.34.0, services-1.3.1, cov-2.8.1
collected 2 items / 1 deselected / 1 selected …
```

[Upgrade Customer Scenario] Pytest conversion for syncplan test cases

---

pytest_fixtures/api_fixtures.py
tests/upgrades/test_satellitesync.py

The purpose of this PR to convert the Satellite Sync unit test(Customer upgrade scenario) to pytest.
Test Results:
**Pre-Upgrade**
```
$ pytest -m "pre_upgrade" tests/upgrades/test_satellitesync.py 
platform linux -- Python 3.6.6, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
collected 2 items / 1 deselected / 1 selected                                                                                                                                                                     
tests/upgrades/test_satellitesync.py . …
```

[Upgrade Customer Scenario] Pytest conversion for Updated Satellite Sync API

---

tests/foreman/cli/test_host_collection.py

Hello
Converting CLI test_host_collection , unittest to pytest

Convert cli Host-Collection unittest to pytest

---

pytest_fixtures/api_fixtures.py

Unecessary deletions create load on Satellite
Deleting org can cause race conditions

Do not delete as part of teardown

---

tests/foreman/api/test_discoveredhost.py
tests/foreman/cli/test_content_credentials.py
tests/foreman/cli/test_ldapauthsource.py
tests/foreman/ui/test_settings.py

- Fixes the newly added / missed tests with parameterized token.
- One test cases needed to remove the parameterized token since it was not parameterized.

Fix Parameterized Token - Newly added / missed in last

---

tests/foreman/api/test_multiple_paths.py

This PR converts `tests/foreman/api/test_multiple_paths.py` from unittest to pytest. Subtests are converted to parametrized tests, and workarounds related to
Bug 1118015 - Receive HTTP 200 after creating operating system, not HTTP 201
https://bugzilla.redhat.com/show_bug.cgi?id=1118015
have been removed.
```
$ pytest tests/foreman/api/test_multiple_paths.py
[...]
collected 236 items
tests/foreman/api/test_multiple_paths.py ............................... [ 13%]
........................................................................ [ 43%]
........................................................................ [ 74%]
.............................................................            [100%]
[...]
================ 236 passed, 746 warnings in 715.86s (0:11:55) =================
```

pytest conversion for test_multiple_paths.py

---

.github/workflows/action.yml
.github/workflows/update_robottelo_image.yml

Meant to include this in #8249

Update pip in workflows before installing requirements

---

pytest_plugins/rerun_rp/rerun_rp.py

Until now/today, The Rerun RP plugin was helpful to rerun regular tier tests, but with this improvement, one can also rerun upgrade failed/skipped tests on an upgraded setup.
The usage is simple and just adds one more option `upgrades-rerun` to this plugin.
Usage:
```
```

[Rerun RP Pytest Plugin Improvement] Rerun Upgrade Tests

---

tests/upgrades/test_contentview.py

The purpose of this PR to convert the content view unit test(Customer upgrade scenario) to pytest.
Test Results:
**Pre-Upgrade:**
```
$ pytest -s -m "pre_upgrade" tests/upgrades/test_contentview.py 
platform linux -- Python 3.6.6, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
plugins: rerunfailures-9.1.1, ibutsu-1.12, services-2.2.1, forked-1.1.3, mock-3.3.1, xdist-1.34.0, cov-2.8.1
collected 2 items / 1 deselected / 1 selected …
```

[Upgrade Customer Scenario] Pytest conversion for content view test cases

---

tests/foreman/api/test_bookmarks.py

This PR converts `tests/foreman/api/test_bookmarks.py` from unittest to pytest. Subtests are converted to parametrized tests. Because the full parametrization for all tests in the module amounted to over 2,500 tests, I've restricted each test to a randomly-chosen value from `invalid_values_list()` or `valid_data_list()`, instead of parametrizing over all values. This reduces the number of tests to 660.
```
$ pytest tests/foreman/api/test_bookmarks.py
[...]
collected 660 items
tests/foreman/api/test_bookmarks.py .................................... [  5%]
........................................................................ [ 16%]
........................................................................ [ 27%]
........................................................................ [ …
```

Convert test_bookmarks.py to pytest

---

tests/foreman/api/test_audit.py

This PR converts `tests/foreman/api/test_audit.py` to pytest.
```
$ pytest tests/foreman/api/test_audit.py
[...]
collected 3 items
tests/foreman/api/test_audit.py ...                                      [100%]
[...]
================= 3 passed, 166 warnings in 140.34s (0:02:20) ==================
```

Pytest conversion for test_audit.py

---

robottelo/constants/__init__.py

```
pytest tests/foreman/api/test_permission.py -k test_positive_search
platform linux -- Python 3.9.0, pytest-6.2.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/pondrejk/Documents/robottelo, configfile: pyproject.toml
plugins: xdist-2.2.0, services-2.2.1, forked-1.3.0, cov-2.10.1, mock-3.4.0, ibutsu-1.13
collected 15 items / 12 deselected / 3 selected                                                                                                       
tests/foreman/api/test_permission.py ... …
```

new organization permissions

---

tests/upgrades/test_capsule.py

The purpose of this PR to convert the capsule's unit test(Customer upgrade scenario) to pytest and fix some earlier failures that happened due to the orphaned process.
Test Results:
**Pre-Upgrade**
```
$ pytest -s -m "pre_upgrade" tests/upgrades/test_capsule.py
platform linux -- Python 3.6.6, pytest-6.1.1, py-1.9.0, pluggy-0.13.1                                                                                                                                                           
tests/upgrades/test_capsule.py .
==================================================================== …
```

[Upgrade Customer Scenario]Pytest conversion for capsule test cases

---

tests/foreman/api/test_smartproxy.py
tests/foreman/cli/test_capsule.py

Test results:
```
(venv) [vsedmik@localhost robottelo]$ pytest tests/foreman/api/test_smartproxy.py tests/foreman/cli/test_capsule.py
=================================== test session starts ====================================
platform linux -- Python 3.7.7, pytest-6.1.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/vsedmik/PycharmProjects/robottelo, configfile: pyproject.toml
plugins: mock-3.3.1, forked-1.3.0, services-2.2.1, ibutsu-1.13, xdist-2.1.0
collecting ... 2020-12-21 20:11:18 - conftest - DEBUG - Collected 45 test cases
collected 45 items …
```

Pytest conversion capsule

---

tests/foreman/installer/test_installer.py

Satellite 6.9 Super Simple Installer features:

[6.9 - Super Simple Installer] Stubs tests and Automated installer sections test

---

tests/foreman/api/test_discoveredhost.py
tests/foreman/cli/test_discoveredhost.py

first step in the refactoring of CLI discovered tests.

remove or merge redundant or non needed tests

---

requirements.txt

add reportportal agent to dependencies to enable live logging

---

robottelo/constants/__init__.py
tests/foreman/cli/test_repository.py

rather than hardcoded repo name
Change to mirror.gcr.io
see also https://github.com/SatelliteQE/robottelo/pull/8310#issuecomment-770266796

Use DOCKER_UPSTREAM_NAME in repo test

---

pytest_fixtures/api_fixtures.py
tests/foreman/cli/test_bootstrap_script.py

This  adds test for bootstrap.py, a.k.a the bootstrap script.

Add test for bootstrap.py

---

requirements.txt

backport of https://github.com/SatelliteQE/robottelo/pull/8311/files

[6.7.z] add reportportal agent to dependencies to enable live logging

---

requirements.txt

backport of https://github.com/SatelliteQE/robottelo/pull/8311/files

[6.8.z] add reportportal agent to dependencies to enable live logging

---

tests/foreman/api/test_computeprofile.py

Test result:
```
$ pytest tests/foreman/api/test_computeprofile.py 
=========================================== test session starts ===================================================================================
platform linux -- Python 3.8.6, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/akjha/satelliteqe/robottelo, inifile: pytest.ini
plugins: forked-1.3.0, ibutsu-1.12, xdist-1.34.0, mock-3.3.1, cov-2.10.1, services-2.2.1
collecting ... 2020-11-24 09:23:34 - conftest - DEBUG - Collected 5 test cases
collected 5 items …
```

Pytest conversion for /api/test_computeprofile.py

---

scripts/polarion-test-case-upload.sh
scripts/polarion-test-run-upload.sh

- added polarion test case upload script
- added polarion test run upload script

Add polarion test case and test run scripts into robottelo

---

tests/foreman/ui/test_reporttemplates.py

Refrects changes in 6.9 (mainly template names)

Fix reporting 69

---

conftest.py
pytest_plugins/disable_rp_params.py

backport of:
https://github.com/SatelliteQE/robottelo/pull/8340

[6.8.z] Disable Report Portal parameter logging

---

pytest_fixtures/api_fixtures.py
tests/foreman/api/test_activationkey.py
tests/foreman/cli/test_activationkey.py
tests/foreman/ui/test_activationkey.py

Pytest Conversions ActivationKey

---

pytest_fixtures/oscap_fixtures.py

Test results:
```
$ pytest tests/foreman/cli/test_oscap.py 
platform linux -- Python 3.8.6, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/jpathan/projects/robottelo, inifile: pytest.ini
plugins: mock-3.3.1, services-2.2.1, cov-2.10.1, xdist-1.34.0, forked-1.3.0, ibutsu-1.1.1
2021-02-11 05:35:11 - conftest - DEBUG - Collected 31 test cases
collected 31 items
tests/foreman/cli/test_oscap.py ............................sss          [100%]
================== 28 passed, 3 skipped in 571.02s (0:09:31) ===================
```

[Cherry pick] Fix scap_content fixture (#8166)

---

tests/foreman/cli/test_myaccount.py

fixed NotAutomated tag in test_positive_update_all_locales

---

README.rst

Using this to test PRT trigger, these updates are largely inconsequential but might be nice to merge anyway.

Update README with some links to airgun/nailgun/ssh2-python

---

tests/foreman/sys/test_rename.py

rename issue received a spin-off bug, modified skip accordingly

skip rename on different bz

---

tests/foreman/sys/test_katello_certs_check.py

This is the PR for adding the QE test coverage for cname scenarios in a capsule cerificate.

added the test coverage for bugzilla_1857176

---

tests/foreman/cli/test_user.py

covered in test_ldap_authentication.py

removing stub test_positive_create_in_ldap_modes

---

tests/foreman/ui/test_host.py

Tests for global registration 6.9 feature:
- end-to-end test covers the registration scenario with rex and insights enabled via global parameter, rhel 7 host is registred via capsule
- additional test checks the form selections translate to curl command parameters as expected
results:
```
pytest tests/foreman/ui/test_host.py -k global_registration_end_to_end
===================================================== test session starts =====================================================
collected 32 items / 31 deselected / 1 selected                                                                               
tests/foreman/ui/test_host.py .                                                                                         [100%]
================================== 1 passed, 31 …
```

global registration test

---

pytest_fixtures/api_fixtures.py
tests/foreman/api/test_template_combination.py

unit test to pytest conversion of  template combination
`======================= 2 passed, 17 warnings in 18.92s ========================`
Please wait for ack of @rplevka , component owner of this file.

u2p conversion of test template combination

---

tests/foreman/cli/test_template.py

unitetest to pytest conversion
I removed as much usage of `cli.factory` as possible. 
Please do not merge before @rplevka ack's this, he is owner of the ProvisioningTemplates.
`================== 11 passed, 6 warnings in 251.04s (0:04:11) ==================`

cli templates.py u2p

---

robottelo/api/utils.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/longrun/test_provisioning_computeresource.py

- VMWare Bug (1679225)
- Discovery Bug (1367549)

Close Loop - VMWare Bug (1679225) and Discovery Bug (1367549)

---

tests/foreman/cli/test_errata.py

Convert CLI test_errata.py from unittest to pytest

Convert cli errata unittest to pytest

---

pytest_fixtures/satellite_auth.py
tests/foreman/ui/test_ldap_authentication.py

Result Updated: 23 Feb 2021
NOTE:
1) RHSSO tests not included as they are environment depended.
2) HTTPS ldap will fail while executing PRT because of improper certs.

Parameterize ldap auth

---

tests/foreman/api/test_filter.py
tests/foreman/cli/test_filter.py

```
pytest tests/foreman/api/test_filter.py 
tests/foreman/api/test_filter.py ...                                                                            [100%]
=========================================== 3 passed, 12 warnings in 13.71s ===========================================
```
```
pytest tests/foreman/cli/test_filter.py 
================================================= test session starts =================================================                                                                                                 
tests/foreman/cli/test_filter.py ........                                                                       [100%] …
```

filter tests moved to pytest

---

tests/foreman/cli/test_user.py

api verision already converted, resutls (one failure unrelated):
```
pytest tests/foreman/cli/test_user.py
tests/foreman/cli/test_user.py F.........                                                                       [100%]
================================= 1 failed, 9 passed, 1 warning in 528.14s (0:08:48) ==================================
```

user cli test moved to pytest

---

pytest_plugins/markers.py
tests/foreman/cli/test_host.py

forgotten tests, 
More info is written in #8339.

katello host tools unittest2pytest

---

tests/foreman/api/test_role.py

All test passed, except this one. Not sure what is causing this problem, but it is also failing in current automation. Test behavior wasn't changed by this PR. Needs some more investigation.
```
===================================== short test summary info =====================================
FAILED tests/foreman/api/test_role.py::TestCannedRole::test_negative_create_taxonomies_by_org_admin
======================= 1 failed, 42 passed, 7 skipped in 659.58s (0:10:59) =======================
```

convert api/role to pytest

---

tests/foreman/ui/test_host.py

I need this to run now (current ci, current snaps)

old VM style for global registartion test

---

tests/foreman/ui/test_host.py

adding changes I didn't realize were needed in  #8412

more fixes to globreg test with old VM

---

tests/foreman/ui/test_host.py

This reverts commit e5dcede1bfb5e3d5eaeaf9b36f78ce6288a4b768.

Revert "old VM style for global registartion test"

---

tests/foreman/api/test_errata.py

Hello
converted to pytest and classes removed

convert api errata unittest to pytest

---

tests/foreman/cli/test_usergroup.py

usergroup cli tests moved to pytest
results (one failure unrelated):
```
pytest tests/foreman/cli/test_usergroup.py 
tests/foreman/cli/test_usergroup.py .....F..                                                                    [100%]
======================================= 1 failed, 7 passed in 366.79s (0:06:06) ======================================
```

usergroup moved to pytest

---

tests/foreman/cli/test_subnet.py

`================== 21 passed, 18 skipped in 327.16s (0:05:27) ==================`
please @rdrazny look at the tests, 
Important thing is that I added at the begining `:CaseImportance: Medium` 
Because we require this information for the tests.  
If you want to change it please let me know.

cli test subnet u2p

---

conf/fake_manifest.yaml.template

dynaconf conversion for fake_manifest

Dynaconf template file for fake_manifest

---

tests/foreman/cli/test_http_proxy.py

This PR converts the small cli test_http_proxy to pytest.

Convert cli test_http_proxy to pytest

---

tests/upgrades/test_activation_key.py
tests/upgrades/test_classparameter.py
tests/upgrades/test_errata.py
tests/upgrades/test_hostgroup.py
tests/upgrades/test_repository.py
tests/upgrades/test_role.py
tests/upgrades/test_subnet.py
tests/upgrades/test_syncplan.py
tests/upgrades/test_user.py
tests/upgrades/test_usergroup.py
tests/upgrades/test_virtwho.py
tests/upgrades/test_yum_plugins.py

Everyone involved should review

Give upgrade tests to their rightful owners, API is incorrect component

---

conf/azure.yaml.template
robottelo/config/facade.py

Dynaconf Conversion for Azure RM section. 
Close this along with satelliteqe-jenkins#163.

[DynaConf] Azure Compute Resource settings

---

tests/foreman/cli/test_logging.py

Hello
I have converted logging test to pytest

Convert CLI logging test to pytest

---

tests/foreman/api/test_computeresource_libvirt.py
tests/foreman/cli/test_computeresource_libvirt.py

- Fix parametrization in `api/test_computeresource_libvirt.py`
- Enhance datapoints in `cli/test_computeresource_libvirt.py`: more descriptive suffixes than [0], [1], [2]...

Fix parametrization in cli/test_computeresource_libvirt

---

robottelo/constants/repos.py
tests/foreman/cli/test_contentview.py

Converted contentview view file for cli.  There will be a few failures due to some test cases not being fixed properly, but the goal here is ensure that the pytest conversion is correct.  I will open separate PRs for any failed test cases that follows after this PR is merged since this a very large file to review.  I will add test results on here soon.

Pytest conversion for content-view cli

---

tests/foreman/endtoend/test_cli_endtoend.py
tests/foreman/endtoend/utils.py

```
(.robottelo_py38) [gtalreja@gtalreja robottelo]$ pytest -v tests/foreman/endtoend/test_cli_endtoend.py 
===================================================== test session starts =====================================================
platform linux -- Python 3.8.2, pytest-6.2.2, py-1.9.0, pluggy-0.13.1 -- /home/gtalreja/sat_workspace/robottelo/.robottelo_py38/bin/python3.8
rootdir: /home/gtalreja/sat_workspace/robottelo, configfile: pyproject.toml
plugins: mock-3.5.1, xdist-2.2.1, cov-2.11.1, ibutsu-1.14.1, services-2.2.1, forked-1.3.0, reportportal-5.0.8
collected 4 items …
```

Refactor test_cli_endtoend for pytest

---

robottelo/constants/__init__.py

Hello
removed broker provider RHEV as no longer used
see: https://github.com/SatelliteQE/robottelo/pull/8420#discussion_r596816087

broker provider no longer used

---

tests/upgrades/test_classparameter.py

Unittest to pytest conversion.
@vsedmik in `tests/foreman/` these tests are under `Puppet` component, and you are the component owner. I did not change it as @lhellebr told me he will create separate PR, where he will change multiple component owners. 
Let me know if you do not like some changes here :) 
Test results 
pre upgrades are okay
but problem with post upgrades, so I keep it in draft

upgrade test class parameter u2p

---

tests/upgrades/test_foreman_maintain.py

**Pre-Upgrade:**
```
(.robottelo_py38) [gtalreja@gtalreja robottelo]$ pytest -m pre_upgrade tests/upgrades/test_foreman_maintain.py 
===================================================== test session starts =====================================================
platform linux -- Python 3.8.2, pytest-6.2.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/gtalreja/sat_workspace/robottelo, configfile: pyproject.toml
plugins: mock-3.5.1, xdist-2.2.1, cov-2.11.1, ibutsu-1.14.1, services-2.2.1, forked-1.3.0, reportportal-5.0.8
collected 2 items / 1 deselected / 1 selected                                                                                 
tests/upgrades/test_foreman_maintain.py . …
```

Refactor upgrades/test_foreman_maintain for pytest

---

tests/foreman/installer/test_infoblox.py

only stubbed tests :) 
Class removed.
@rdrazny, owner, was pinged about the change.

test_infoblox u2p for pytest tests

---

tests/upgrades/test_errata.py

Pre-upgrade (6.8.5) test results:
```
[...]
collected 4 items / 2 deselected / 2 selected
[...]
== 2 passed, 2 deselected, 177 warnings in 1711.31s (0:28:31) ===
```
Post-upgrade (6.9.0) test results:
```
[...]
collected 4 items / 2 deselected / 2 selected
[...]
=== 2 passed, 2 deselected, 149 warnings in 797.02s (0:13:17) ===
```

Convert tests/upgrades/test_errata.py to pytest

---

tests/upgrades/test_repository.py

Pre-upgrade (6.8.5) tests:
```
[...]
collected 4 items / 2 deselected / 2 selected
tests/upgrades/test_repository.py
[...]
=== 2 passed, 2 deselected, 53 warnings in 267.71s (0:04:27) ===
```
Post-upgrade (6.9.0) tests:
```
[...]
collected 4 items / 2 deselected / 2 selected  
[...]
=== 2 passed, 2 deselected, 18 warnings in 108.04s (0:01:48) ===
```

Convert tests/upgrades/test_repository.py to pytest

---

tests/upgrades/test_remoteexecution.py

Wasn't able to run the tests locally on master branch, going to ask the component owner for some help.  Pretty straightforward conversion though.

Refactor upgrades/test_remoteexecution for pytest

---

tests/foreman/api/test_subnet.py

`=========== 40 passed, 7 skipped, 115 warnings in 106.04s (0:01:46) ============`

test subnet u2p conv

---

tests/foreman/api/test_host.py

Depends on [nailgun PR](https://github.com/SatelliteQE/nailgun/pull/783)
`================ 1 passed, 61 deselected, 47 warnings in 52.49s ================`
While I was writing this test I found BZ. So I think it was worth the time.

api bulk destroy test added

---

conf/gce.yaml.template

Gitlab MR: 161
```
$ pytest -k test_positive_crud_gce_cr tests/foreman/api/test_computeresource_gce.py
platform linux -- Python 3.8.7, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: robottelo, configfile: pyproject.toml
plugins: reportportal-5.0.8, forked-1.3.0, xdist-2.2.1, mock-3.5.1, ibutsu-1.14.1, services-2.2.1
collected 9 items / 8 deselected / 1 selected                                                                                                                
tests/foreman/api/test_computeresource_gce.py . …
```

[Dynaconf] Dynaconf GCE conversion

---

tests/foreman/sys/test_pulp3_filesystem.py

Hello
Some low level checks to ensure the new filesystem for Pulp3 is ready for the migration from Pulp2

Add SELinux and systemd checks for pulp3 filesystem

---

robottelo/constants/__init__.py
tests/foreman/api/test_contentview.py
tests/foreman/api/test_contentviewfilter.py
tests/foreman/api/test_contentviewversion.py
tests/foreman/api/test_docker.py
tests/foreman/api/test_repository.py
tests/foreman/cli/test_contentview.py
tests/foreman/cli/test_contentviewfilter.py
tests/foreman/cli/test_docker.py
tests/foreman/cli/test_repository.py
tests/foreman/cli/test_vm_install_products_package.py
tests/foreman/data/hammer_commands.json
tests/foreman/ui/test_activationkey.py
tests/foreman/ui/test_containerimagetag.py
tests/foreman/ui/test_contentview.py
tests/foreman/ui/test_repository.py
tests/foreman/ui/test_sync.py

Since we no longer use the docker registry, we should update names
https://github.com/SatelliteQE/robottelo/pull/8473#pullrequestreview-623383351

Change DOCKER TO CONTAINER in constants

---

conf/server.yaml.template

Remove an unused setting and add additional information

clarify current server.yaml behavior

---

conf/performance.yaml.template
robottelo/config/validators.py

- Adding `performance.yaml`
- Updating/Removing some existing validators in performance settings since they are no longer been used anywhere in Robottelo.

[DynaConf] Performance settings conversion

---

tests/foreman/cli/test_jobtemplate.py

```
pytest tests/foreman/cli/test_jobtemplate.py 
======================================================================= test session starts ========================================================================                                                                                                                                                 
tests/foreman/cli/test_jobtemplate.py .......                                                                                                                [100%]
============================================================ 7 passed, 2 warnings in 178.98s (0:02:58) ==============
```

jobtemplate pytest conversion

---

tests/foreman/cli/test_ostreebranch.py

u2p conversion, change in robottelo constants for working ostree
Tested with commented `@pytest.mark.skip_if_open("BZ:1625783")`
=================== 6 passed, 1 warning in 108.41s (0:01:48) ===================
Don't know why, but when I test it without commented @pytest.mark.skip_if_open("BZ:1625783"). 
It should not work, but those tests do run. Any ideas ?

cli ostreeebranch to pytest

---

conf/certs.yaml.template

From certs section of robottelo.properties file

Add certs.yaml.template

---

tests/foreman/api/test_contentviewversion.py

Pytest conversion for contentviewversion.py
=========================== short test summary info ============================
FAILED test_contentviewversion.py::test_positive_remove_qe_promoted_cv_version_from_default_env
FAILED test_contentviewversion.py::test_positive_remove_prod_promoted_cv_version_from_default_env
======= 2 failed, 17 passed, 3 skipped, 5 warnings in 1119.75s (0:18:39) =======
It seems that docker is having issues with any sync. May not be an issue with the code

ContentViewVersion Pytest Conversion

---

tests/foreman/cli/test_discoveredhost.py

Test results:
```====== 4 passed, 11 deselected in 725.37s (0:12:05) =======```

convert cli/test_discoveredhost to pytest

---

pytest_fixtures/api_fixtures.py
robottelo/constants/__init__.py
tests/foreman/cli/test_contentaccess.py

Hello
Converted to pytest and converted to use broker
Created new fixtures for golden ticket
Thank you
Update:  removed broker provider RHEV as no longer used

Convert cli contentaccess to pytest

---

pytest_fixtures/broker.py
robottelo/hosts.py
tests/foreman/longrun/test_inc_updates.py

Convert long run incremental update checks to pytest.
These tests used two VMs, two RHEL repos, and a HC for the test and took between 942.31s (0:15:42) and 1729.99s (0:28:49).
I have simplified the set-up and now it takes  528.15s (0:08:48).
Thank you

convert inc updates to pytest

---

pytest_fixtures/xdist.py
robottelo/config/facade.py
tests/foreman/api/test_hostcollection.py

Convert the test in api/test_hostcollection that previously used
the VirtualMachine class.
Also, made some minor tweaks to broker's checkin and facade.

[VM -> Broker] Conversion of api/test_hostcollection

---

robottelo/hosts.py
tests/foreman/longrun/test_oscap.py

Test result:
```
$ pytest -Wignore --include-libvirt tests/foreman/longrun/test_oscap.py -k test_positive_oscap_run_via_ansible_bz_1814988 
platform linux -- Python 3.8.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/jpathan/projects/robottelo, configfile: pyproject.toml
plugins: ibutsu-1.13, services-2.2.1, mock-3.5.1, reportportal-5.0.7, xdist-2.2.1, forked-1.3.0
collected 13 items / 12 deselected / 1 selected
tests/foreman/longrun/test_oscap.py .                                    [100%]
================ 1 passed, 12 deselected in 1526.17s (0:25:26) =================
```

Add close loop test for BZ_1814988 and VM -> Broker conversion

---

tests/foreman/api/test_errata.py

This PR fixes `tests/foreman/api/test_errata.py::test_positive_sort_by_issued_date` so that the test correctly sets up the org for the red hat repository.
```
[...]
collected 14 items / 13 deselected / 1 selected                                                                                                                                                                                              
tests/foreman/api/test_errata.py . [100%]
=== 1 passed, 13 deselected in 134.56s (0:02:14) ===
```

Fix repo setup in errata api test test_positive_sort_by_issued_date

---

tests/foreman/api/test_organization.py

automation for https://bugzilla.redhat.com/show_bug.cgi?id=1828549
Checks for manifest cert exposed in organization api endpoint
```
pytest tests/foreman/api/test_organization.py -k test_negative_check_org_endpoint
tests/foreman/api/test_organization.py .                                                                      [100%]
=================================== 1 passed, 42 deselected, 2 warnings in 7.12s ====================================
```

closed loop, check org api

---

.github/workflows/merge_to_master.yml
robottelo/host_info.py
tests/robottelo/test_func_locker.py
tests/robottelo/test_issue_handlers.py

Read settings.robottelo.satellite_version instead

Remove use of SATELLITE_VERSION env var

---

tests/foreman/ui/test_jobinvocation.py

Test results:
`======================== 2 passed in 990.75s (0:16:30) =========================`

broker conv of ui/test_jobinvocation.py

---

conf/osp.yaml.template

```
$ pytest -v tests/foreman/cli/test_computeresource_osp.py 
========================================================================== test session starts ===========================================================================
platform linux -- Python 3.8.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /home/lvrtelov/PycharmProjects/lvrtelov/robottelo-lvrtelov/venv38/bin/python3.8
rootdir: /home/lvrtelov/PycharmProjects/lvrtelov/robottelo-lvrtelov, configfile: pyproject.toml
plugins: services-2.2.1, xdist-2.2.1, forked-1.3.0, cov-2.11.1, mock-3.5.1, ibutsu-1.14.1, reportportal-5.0.8
collected 9 items / 2 deselected / 7 selected …
```

dynaconf conversion for OSP compute resource

---

robottelo/constants/__init__.py

* Bump repo versions to 6.8
This will help with upgraded tests.

cherry-pick: Bump repo versions to 6.8 (#8172)

---

robottelo/constants/__init__.py

New permission added
```
pytest tests/foreman/api/test_permission.py -k test_positive_search
collected 15 items / 12 deselected / 3 selected                                                                     
tests/foreman/api/test_permission.py ...                                                                      [100%]
============================ 3 passed, 12 deselected, 384 warnings in 372.10s (0:06:12) =============================
```

added view_insights_hits permission

---

tests/foreman/ui/test_contentview.py

`FAKE_3_YUM_REPO` doesn't have `walrus` rpm anymore.  Fix to use `dolphin` instead.
results:
```
============== test session starts ====
platform linux -- Python 3.8.2, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/ltran/Projects/robottelo, configfile: pyproject.toml
plugins: mock-3.6.0, forked-1.3.0, services-2.2.1, cov-2.11.1, ibutsu-1.14.1, xdist-2.2.1, reportportal-5.0.8
collected 1 item                                                                                                                                                                                                                         
tests/foreman/ui/test_contentview.py . …
```

Fix test_positive_update_filter_affected_repos

---

conf/upgrade.yaml.template

CI pipeline failing because of unresolved reference to settings.upgrade

Uncomment fields in upgrade.yaml.template

---

pytest_fixtures/broker.py

The nick has been added to satelliteqe-jenkins/openshift/broker_settings.yaml

rhel7_contenthost_fips fixture added

---

pytest_fixtures/broker.py

Yield the host from rhel77_contenthost_class

---

tests/foreman/api/test_product.py
tests/foreman/api/test_repository.py
tests/foreman/cli/test_http_proxy.py
tests/foreman/cli/test_product.py
tests/foreman/ui/test_http_proxy.py
tests/foreman/ui/test_settings.py

I am assigning Http Proxy tests to myself.

Change Assignee for Http Proxy tests

---

.github/workflows/merge_to_master.yml

This should resolve issues we're seeing with the update container image workflow.

Add update to Master branch workflow

---

tests/upgrades/test_client.py

Converting `tests/upgrades/test_client.py` to pytest

Convert test_client.py to pytest

---

tests/foreman/cli/test_remoteexecution.py

Conversion to VMBroker and some refactoring

cli rex conversion to vmbroker

---

tests/foreman/sys/test_katello_certs_check.py

```
Testing started at 8:30 PM ...
/home/okhatavk/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --path /home/okhatavk/okhatavk/Satellite/robottelo/tests/foreman/sys/test_katello_certs_check.py -- -k test_negative_check_expiration_of_certificate
Launching py.test with arguments -k test_negative_check_expiration_of_certificate /home/okhatavk/okhatavk/Satellite/robottelo/tests/foreman/sys/test_katello_certs_check.py in /home/okhatavk/Satellite/robottelo
platform linux -- Python 3.8.6, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: …
```

cert expiration test-case with katello-cert-check

---

tests/foreman/api/test_hostcollection.py

Hello
There was a second error.
First one fixed here: https://github.com/SatelliteQE/robottelo/pull/8587

Fix 2nd typeerror in test_hostcollection

---

tests/foreman/cli/test_reporttemplates.py

Please do not merge until @lhellebr will ACK this.
Test results:
```
=========== 16 passed, 2 skipped, 3 deselected in 2168.97s (0:36:08) ===========
```

vm2br_cli_test_report_templates

---

robottelo/constants/__init__.py
tests/foreman/cli/test_contentaccess.py

and fix SCA test that uses it.
Hello
This change is for Satellite 6.9 Satellite Tools Release
OLD: https://access.redhat.com/errata/RHBA-2020:4367
NEW: https://access.redhat.com/errata/RHBA-2021:1314

Update to RHBA-2021:1314 for rhst7

---

tests/foreman/cli/test_activationkey.py

Replace uses of the VirtualMachine class with a broker-acquired host.
This can be done by either consuming a fixture in the test or by using the VMBroker class as a context manager.
Try to avoid specific version references, these can be abstracted via constants or with CI-defined nicks.
from broker import VMBroker
...
with VMBroker(...) as my_host:
my_host.register(...)

Broker Conversion cli/test_activationkey.py

---

robottelo/config/facade.py
robottelo/helpers.py
robottelo/hosts.py
tests/foreman/api/test_remoteexecution.py

Converted the one test in this module that used libvirt-based
provisioning
Enhanced the Host, Capsule, and Satellite classes
Additionally, added a new class to helpers that helps when dealing with
installer command construction.

VM->Broker Conversion for api/test_remoteexecution.py

---

tests/foreman/api/test_repository.py

Closed loop: BZ#1867287
Adding test for:
[Bug 1867287 - Error Row was updated or deleted by another transaction when deleting docker repository](https://bugzilla.redhat.com/show_bug.cgi?id=1867287)

Add test delete product with synced docker repo

---

tests/foreman/longrun/test_oscap.py

VM to Broker conversion for test_positive_upload_to_satellite test. Refs: https://github.com/SatelliteQE/robottelo/pull/8522#discussion_r615769266
This PR also tries to address issue related to long test name because parameterization.

VM to Broker conversion for Oscap test

---

tests/foreman/api/test_user.py
tests/foreman/cli/test_ldapauthsource.py

looking for test result, please take a look all checks. PRT is passed

fixed auth tests because of AD and Openldap Server

---

tests/foreman/api/test_hostgroup.py
tests/foreman/cli/test_hostgroup.py
tests/foreman/ui/test_hostgroup.py
tests/upgrades/test_hostgroup.py

updated the component ownership for hostgroup

---

tests/foreman/cli/test_errata.py

Hello
This adds a test for a package that is applicable for upgrade in Library, using Default Content View .
This test relates to the change to Pulp3.
Depends on: https://github.com/SatelliteQE/robottelo/pull/8619

Add test update_applicable_package_using_default_content_view

---

tests/foreman/api/test_subscription.py

Closed-Loop BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1949353

'Add test for re-registration of host with expired SCA cert

---

tests/foreman/ui/test_dashboard.py

vm2br conversion:
I fixed the test by passing `upload_manifest=True`
Test owner is on PTO. But I think we shouldn't wait.
```
tests/foreman/ui/test_dashboard.py::test_positive_user_access_with_host_filter
================= 1 passed, 3 deselected in 891.66s (0:14:51) ==================
```

vm2br_ui_test_dashboard

---

tests/foreman/sys/test_katello_certs_check.py

More Details https://bugzilla.redhat.com/show_bug.cgi?id=1858819

addition in check to validate the katello-cert-check installer command

---

tests/foreman/ui/test_subscription.py

The first two tests are failing due to bz1948758. Third test is failing at Line 510: `session.organization.select(org_name=org.name)`. I checked with pdb, the host gets registered with the satellite successfully.

Subscription UI vm broker

---

tests/foreman/cli/test_remoteexecution.py

applied some feedback collected in https://github.com/SatelliteQE/robottelo/pull/8608

cli rex fixes
