tests/foreman/api/test_contentmanagement.py

Capsule installation is failing due to a package.

Contentmanagement api vm broker

---

tests/upgrades/test_remoteexecution.py

Needs review from upgrade specialists :) Also I wasn't sure how to do the vm cleanup postupgrade

VMBroker conversion rex in upgrades

---

tests/foreman/ui/test_hostcollection.py

Hello
Convert UI host collection to VMBroker

Convert UI hostcollection to VMBroker

---

tests/foreman/api/test_docker.py
tests/foreman/api/test_repository.py
tests/foreman/api/test_repository_set.py
tests/foreman/cli/test_docker.py
tests/foreman/cli/test_repository.py
tests/foreman/cli/test_repository_set.py
tests/foreman/cli/test_vm_install_products_package.py
tests/foreman/ui/test_repository.py
tests/foreman/ui/test_sync.py
tests/upgrades/test_repository.py
tests/upgrades/test_yum_plugins.py

This PR changes the assignee for tests in the Repositories component.

Reassign repository tests

---

tests/foreman/cli/test_repository.py

Hello
Justin S approved this test.

Add stubbed test for file content in Pulp3

---

tests/foreman/sys/test_pulp3_filesystem.py

Remove check for static file

---

tests/foreman/api/test_user.py
tests/foreman/cli/test_user.py
tests/foreman/ui/test_user.py

Stubbed cases for new feature Personal Access Token. (API/CLI/UI)
issues: 600

stubbed cases for PAT

---

tests/foreman/cli/test_errata.py

Pulp3 related. Requested by jsherrill
Adding a test that downgrades a package and checks that the erratum for that package then shows as applicable.
Suitable for 6.9 onwards

Add test downgrade package shows errata

---

robottelo/config/__init__.py

Elements of this modification should have remained instances of self

Fix modified gpgkey init

---

tests/foreman/cli/test_host.py

Please do not merge until 6.10 branch.
based on https://bugzilla.redhat.com/show_bug.cgi?id=1910314
test result at 6.8.4
```
FAILED
tests/foreman/cli/test_host.py:981 (test_hammer_host_info_output)
4 != 7
Expected :7
Actual   :4
```
And result with fixed bz with 6.10 
```
tests/foreman/cli/test_host.py::test_hammer_host_info_output
================ 1 passed, 54 deselected, 4 warnings in 55.15s =================
```

qe test coverage bz 1910314

---

tests/foreman/api/test_subscription.py
tests/foreman/ui/test_remoteexecution.py

Adding stubbed test cases for the Ansible features delivered in Satellite 6.10.

6.10 ansible feature stubs

---

robottelo/constants/__init__.py

Update constant to 6.10

---

tests/foreman/cli/test_repository.py

Hello
some stubbed tests related to Pulp3 RPM content

Adding stubbed tests for RPM content

---

tests/foreman/cli/test_satellitesync.py

Hello
Stubbed tests for ISS
Thank you

Edit stubbed tests for Inter Satellite Sync (ISS)

---

tests/foreman/cli/test_logging.py

Added automated test case to verify logs from pulpcore. Pulp3 logs can be verified using correlation id present in production log.

Automated stubbed test case for logging of pulp3

---

tests/foreman/cli/test_remoteexecution.py

Cherry pick from  https://github.com/SatelliteQE/robottelo/pull/8715

[cherry-pick] parameter ids for cli rex tests

---

tests/foreman/api/test_syncplan.py
tests/foreman/cli/test_errata.py
tests/foreman/cli/test_syncplan.py

https://github.com/SatelliteQE/robottelo/pull/8706

Backport fix datetime serialization

---

tests/foreman/api/test_syncplan.py

Hello
a cherry pick from https://github.com/SatelliteQE/robottelo/pull/8718

[cherry-pick] Fix typo in api syncplan 6 9 branch

---

requirements.txt

Update broker to 0.1.20

---

tests/foreman/api/test_syncplan.py

Hello
bug is closed WONTFIX so I need to apply workaround
[Bug 1695733 - [RFE] Future dated Sync Plans with non-zero seconds value skip the first interval](https://bugzilla.redhat.com/show_bug.cgi?id=1695733)

Apply workaround for BZ#1695733

---

robottelo/constants/__init__.py
tests/foreman/ui/test_repository.py

Trim sat version to two digits
Bump Ansible to 2.9
Reverse change from fdrh8 to rhae2

Fix positive recommend repos test

---

tests/foreman/api/test_syncplan.py

Hello
cherry-pick of https://github.com/SatelliteQE/robottelo/pull/8732

[cherry-pick] Apply workaround for BZ#1695733

---

robottelo/cli/factory.py
robottelo/hosts.py

Hello
fixing settings path to `conf/repos` and `conf/robotelo` in hosts.py

Fix settings for sattools_repo and cdn

---

tests/foreman/api/test_computeresource_azurerm.py
tests/foreman/api/test_subscription.py

Added 6.10 Feature stubbed test case and SCA test case.  
Both are manual test cases and will not be automated.

added 6.10 stubbed test cases

---

tests/foreman/api/test_syncplan.py

Fix valid_sync_interval again

---

tests/foreman/api/test_errata.py

Moving from katello-agent to job invocation to install errata and removing one test since the api for that test is depreciated. There are similar test with the same functionality.
```
(env) [akjha@akjha robottelo]$ pytest -k test_positive_install_in_host tests/foreman/api/test_errata.py
platform linux -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/akjha/satelliteqe/robottelo, configfile: pyproject.toml
plugins: reportportal-5.0.8, forked-1.3.0, mock-3.6.1, xdist-2.3.0, cov-2.12.0, services-2.2.1, ibutsu-1.16
collected 14 items / 13 deselected / 1 …
```

Fix api test_errata.py

---

tests/foreman/api/test_location.py
tests/foreman/cli/test_ping.py

Automated Bugs :
BZ#1566630
BZ#1941240

close loop 1 for BZ#1941240 and BZ#1566630

---

requirements.txt

update broker to 0.1.21

---

robottelo/hosts.py
tests/foreman/ui/test_contenthost.py

Hello
some fixes due to changes in hosts.py [1]
[1] https://github.com/SatelliteQE/robottelo/pull/8665

Fixes due to changes in hosts.py

---

robottelo/cli/user.py
tests/foreman/cli/test_user.py

```
(env) [akjha@akjha robottelo]$ pytest tests/foreman/cli/test_user.py::TestPersonalAccessToken
platform linux -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/akjha/satelliteqe/robottelo, configfile: pyproject.toml
plugins: reportportal-5.0.8, forked-1.3.0, mock-3.6.1, xdist-2.3.0, cov-2.12.0, services-2.2.1, ibutsu-1.16
collected 3 items                                                                                                                                            
tests/foreman/cli/test_user.py ... …
```

Cli personal access token

---

tests/foreman/cli/test_host.py

I think with a bit of work test like this can be added to all entities. 
I would like to move parse method somewhere else but not sure where :neutral_face: 
Also firstly I made the test the different way. I asserted all the fields with all hosts but, that can be potentially really time consuming if sat has a lot of hosts. So I decided to add steps 1 and 4 and use only one host.
The `parse_two_columns` method is not necessary, but I though maybe it can be useful in future if we want to check also options from help messages. Let me know what you think about the way I parse this. 
Test result:
```
tests/foreman/cli/test_host.py::test_positive_search_all_field_sets
=========== 1 passed, 55 deselected, 4 warnings in 76.35s (0:01:16) ============
```

parse help message, new test search based on the fields

---

tests/foreman/cli/test_errata.py

Fixture is not used anywhere. 
So I decided to remove it.

not used fixture removed

---

tests/foreman/sys/test_rename.py

more post-rename checks

---

tests/foreman/api/test_rhcloud_inventory.py
tests/foreman/cli/test_rhcloud_inventory.py
tests/foreman/ui/test_rhcloud_inventory.py

This PR adds stubbed test cases for RH Cloud plugin and updates `BZ` and `customerscenario` docstring for some tests. 
It contains customer case scenarios, Bugzilla scenarios, and few other based on usage of the plugin.

Stubbed tests for RH Cloud plugin.

---

robottelo/constants/__init__.py

test fix
tests/foreman/ui/test_host.py::test_positive_check_permissions_affect_create_procedure
`=========== 1 passed, 36 deselected, 3 warnings in 112.67s (0:01:52) ===========`

organization permissions updated

---

tests/foreman/ui/test_contenthost.py

Add test update checkin time

---

tests/foreman/virtwho/ui/test_libvirt.py

Update virtwho settings references in test_libvirt

---

tests/foreman/cli/test_setting.py
tests/foreman/cli/test_usergroup.py
tests/foreman/sys/test_katello_certs_check.py
tests/foreman/sys/test_pulp3_filesystem.py
tests/foreman/ui/test_ldap_authentication.py

Add :parametrized: yes token to relevant cases

---

tests/foreman/virtwho/ui/test_libvirt.py

Backport 8799

---

conf/fake_capsules.yaml.template
pytest_fixtures/sys_fixtures.py
robottelo/helpers.py

[cherry-pick] Proxy port fixture

---

tests/foreman/api/test_repository.py
tests/foreman/ui/test_containerimagetag.py

simple 2 liner to change myself to the assignee for ContainerManagement test cases

Change assignee metadata for ContainerManagement: Content

---

robottelo/constants/__init__.py
robottelo/constants/repos.py
tests/foreman/ui/test_repository.py

```
pytest tests/foreman/ui/test_repository.py -k test_positive_sync_ansible_collection_gallaxy_repo
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/pondrejk/Documents/robottelo, configfile: pyproject.toml
plugins: forked-1.3.0, services-2.2.1, reportportal-5.0.8, mock-3.6.1, cov-2.12.1, xdist-2.3.0, ibutsu-1.16
collected 29 items / 28 deselected / 1 selected                                                                     
tests/foreman/ui/test_repository.py .                                                                         [100%]
============================= 1 passed, …
```

ansible collection repo test

---

tests/foreman/ui/test_hostcollection.py

Hello
updating test to use REX as puppet-agent support removed in 6.10
This test will not pass until this bugzilla is resolved:
[Bug 1983043 - undefined method `prune_known_hosts!` when executing a remote job](https://bugzilla.redhat.com/show_bug.cgi?id=1983043)

Update test to use REX for 6.10

---

tests/foreman/installer/test_installer.py

In this PR, I have addressed two issues one for installer flags and another for satellite services.
- Installer flags update
Few more flags are added in the satellite installer after PR#8736
**Added flags:**
```
--[no-]enable-foreman-cli-katello
--foreman-proxy-content-pulpcore-cache-enabled
--foreman-proxy-content-pulpcore-cache-expires-ttl
--foreman-proxy-content-pulpcore-use-rq-tasking-system
--reset-foreman-proxy-content-pulpcore-cache-enabled
--reset-foreman-proxy-content-pulpcore-cache-expires-ttl
--reset-foreman-proxy-content-pulpcore-use-rq-tasking-system
```
- Added and removed the services list
**Added services**
```
foreman
pulpcore-api
pulpcore-content
rh-redis5-redis
dynflow-sidekiq@worker-1
dynflow-sidekiq@worker-hosts-queue-1
```
**Removed (on newly installed setup)** 
``` …
```

Updated new added installer flags and satellite services.

---

tests/foreman/cli/test_hostgroup.py

```
platform linux -- Python 3.8.6, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/okhatavk/okhatavk/Satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, cov-2.10.1, xdist-2.2.1, reportportal-5.0.8, mock-3.5.1, forked-1.3.0, ibutsu-1.14.1, picked-0.4.6collected 17 items / 1 deselected / 16 selected
../../okhatavk/Satellite/robottelo/tests/foreman/cli/test_hostgroup.py  [  6%]                                                          [100%]
```

remove the puppet configuration from the host-group tests

---

tests/foreman/cli/test_remoteexecution.py

fixes https://github.com/SatelliteQE/robottelo/issues/8655

test rex with alternate dir

---

conf/azure.yaml.template
pytest_fixtures/api_fixtures.py
robottelo/constants/__init__.py
tests/foreman/api/test_computeresource_azurerm.py
tests/foreman/cli/test_computeresource_azurerm.py
tests/foreman/ui/test_computeresource_azurerm.py

[Cherry-Pick] Replacing the subscription and resource group in Azure

---

.gitignore

Adding in gitignore as they are created during test runs.

tmp and screenshots

---

tests/foreman/api/test_syncplan.py
tests/foreman/cli/test_syncplan.py
tests/foreman/ui/test_syncplan.py

Hello
three cherry-picks which should make syncplan tests more reliable

[cherry-pick] Cherry picks for syncplan tests

---

tests/foreman/ui/test_contenthost.py

Fix typo in test name
Change redundant call to vm to vm_module_streams

[cherry-pick] Increase margin of safety in time based search

---

tests/foreman/cli/test_computeresource_azurerm.py

- Some text formatting was failing Azure CLI tests

Azure text formatting issues

---

tests/foreman/cli/test_computeresource_azurerm.py

Azure Forematting issues in strings

---

pytest_fixtures/broker.py
pytest_fixtures/satellite_auth.py
pytest_fixtures/sys_fixtures.py
robottelo/hosts.py
tests/foreman/cli/test_ldapauthsource.py
tests/foreman/sys/test_foreman_service.py
tests/foreman/ui/test_contenthost.py

This commit introduces three refactors and some new patterns for
destructive tests.
These are part of the first phase of destructive test refactoring.

Initial destructive test refactors

---

tests/foreman/api/test_template.py
tests/foreman/api/test_template_combination.py
tests/foreman/cli/test_provisioning.py
tests/foreman/cli/test_template.py
tests/foreman/ui/test_provisioningtemplate.py

Change component owner of Provisioning and ProvisioningTemplates component

---

tests/foreman/ui/test_bookmarks.py

Dependency: https://github.com/SatelliteQE/airgun/pull/603
test coverage for 1920566
Test results:
```pytest -v tests/foreman/ui/test_bookmarks.py -k test_negative_create_with_duplicate_name
============================================================================== test session starts ==============================================================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /home/pdragun/.virtualenvs/robottelo3.9/bin/python
plugins: ibutsu-1.16, xdist-2.3.0, forked-1.3.0, mock-3.6.1, reportportal-5.0.8, services-2.2.1, cov-2.12.1
collected 5 items / 4 deselected / 1 selected …
```

test for duplicate bookmark name

---

pytest_fixtures/sys_fixtures.py
tests/foreman/ui/test_host.py

just pushing draft, so after vacation I can continue with written TODO's

install cockpit on default_sat in robottelo

---

pytest_fixtures/xdist.py

This may resolve issues we're seeing with unresolved hostnames
This is an alternative to #8860

Attempt to use dynaconf's explcit set to change settings.server.hostname

---

pytest_fixtures/xdist.py

This may resolve issues we're seeing with unresolved hostnames
Backporting #8861

[Cherry-pick] Attempt to use dynaconf's explcit set to change settings.server.hostname

---

robottelo/api/utils.py
tests/foreman/api/test_computeresource_azurerm.py
tests/foreman/cli/test_computeresource_azurerm.py
tests/foreman/ui/test_computeresource_azurerm.py

[Cherry Pick] Azure UI and VM cleanup fixes

---

.github/workflows/pull_request.yml

Check test collection under xdist

Add xdist collection to PR workflow

---

tests/foreman/ui/test_dashboard.py

Depends on https://github.com/SatelliteQE/airgun/pull/610
Test results:
```
pytest -v tests/foreman/ui/test_dashboard.py
============================================================================== test session starts ===============================================================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /home/pdragun/.virtualenvs/robottelo3.9/bin/python
plugins: ibutsu-1.16, xdist-2.3.0, forked-1.3.0, mock-3.6.1, reportportal-5.0.8, services-2.2.1, cov-2.12.1
collected 4 items …
```

UI/Dashboard - remove puppet, minor test fixes

---

tests/foreman/longrun/test_inc_updates.py

Hi
cherry-pick of https://github.com/SatelliteQE/robottelo/pull/8899

[cherry-pick] Remove CLI version of inc_updates test

---

tests/foreman/endtoend/test_api_endtoend.py
tests/foreman/endtoend/test_cli_endtoend.py

Test results:
```
pytest -v tests/foreman/endtoend/test_api_endtoend.py -k test_positive_end_to_end
====================================================================================== test session starts ======================================================================================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /home/pdragun/.virtualenvs/robottelo3.9/bin/python
plugins: ibutsu-1.16, xdist-2.3.0, forked-1.3.0, mock-3.6.1, reportportal-5.0.8, services-2.2.1, cov-2.12.1
collecting ... 2021-08-30 15:43:39 - robottelo.collection - INFO - Processing test items to add testimony token markers …
```

Remove puppet from endtoend tests

---

tests/foreman/cli/test_syncplan.py
tests/foreman/ui/test_syncplan.py

Remove cli custom cron stubbed test
Hello Robotoguys
cherry-pick of https://github.com/SatelliteQE/robottelo/pull/8893

[cherry-pick] Improve reliability of ui custom cron test

---

robottelo/cli/factory.py
tests/foreman/cli/test_repository.py

Initial take on ansible collection repo CLI tests:
```
pytest tests/foreman/cli/test_repository.py -k test_positive_sync_ansible_collecion_from_gallaxy 
collected 237 items / 236 deselected / 1 selected                                                                   
tests/foreman/cli/test_repository.py .                                                                        [100%]
================================== 1 passed, 236 deselected, 6 warnings in 51.16s ===================================
```

ansible collection repo cli test

---

tests/foreman/cli/test_installer.py
tests/foreman/installer/test_installer.py

In this PR, I addressed the following changes.
- Updated the component owner of disconnected satellite installation test cases.
- Removed non-supported installer test cases.
- Added few stubbed test cases in the satellite installer.
**test_positive_capsule_installer_logfile_check**
```
#pytest tests/foreman/installer/test_installer.py::test_positive_capsule_installer_logfile_check
collected 1 item / 1 deselected                                                                                                                                                                                   
================================================================================================ warnings summary ========================================================================= …
```

Updated satellite installer test cases

---

robottelo/constants/__init__.py
tests/foreman/ui/test_hostcollection.py

Hello
Convert test hostcollection to use REX
and  Move setup steps to before session start

Convert test hostcollection to use REX

---

tests/upgrades/test_capsule.py
tests/upgrades/test_contentview.py

- test_capsule - puppet file repo was removed
- test_contentview - puppet artifacts were removed, and also other options were considered, read below in thoughts section, if you want ;) 
@vsedmik  and @latran are component owners of these tests.
Tagging also @devendra104  to double check upgrade part.
So please take a look. 
Test results, I tried to run pre-upgrade and post-upgrade on 6.9 and again on 6.10, all passed
```
6.9
tests/upgrades/test_contentview.py::TestContentView::test_cv_preupgrade_scenario PASSED                                                                                                [100%]
tests/upgrades/test_contentview.py::TestContentView::test_cv_postupgrade_scenario PASSED …
```

puppet test parts removed in upgrade tests

---

tests/foreman/cli/test_remoteexecution.py

Added missing org context, fixed text comparison and added skip for blocked rhel8_fips parameter
```
pytest tests/foreman/cli/test_remoteexecution.py -k test_positive_run_effective_user_job
================================================== test session starts ===================================================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/pondrejk/Documents/robottelo, configfile: pyproject.toml
plugins: forked-1.3.0, services-2.2.1, reportportal-5.0.8, mock-3.6.1, cov-2.12.1, xdist-2.3.0, ibutsu-1.16
collected 16 items / 15 deselected / 1 selected                                                                          
tests/foreman/cli/test_remoteexecution.py . …
```

additional rex cli fixes

---

scripts/polarion-test-run-upload.sh

[cherry-pick] Polarion group ID updated to to exclude snap version.

[cherrypick] Updated Polarion Group ID

---

tests/foreman/api/test_classparameters.py
tests/foreman/cli/test_classparameters.py

Test results:
```
pytest -v tests/foreman/api/test_classparameters.py
================================================================================ test session starts =================================================================================
platform linux -- Python 3.9.6, pytest-6.2.5, py-1.10.0, pluggy-0.13.1 -- /home/pdragun/.virtualenvs/robottelo/bin/python
plugins: cov-2.12.1, forked-1.3.0, xdist-2.3.0, services-2.2.1, reportportal-5.0.8, mock-3.6.1, ibutsu-1.16
collected 29 items …
```

Workaround for classparameters puppet module

---

tests/foreman/api/test_errata.py

Pulp3 related. Requested by jsherrill
Hi, test works but can be improved
Hello @akhil-jha , although this is now your component I was asked to write this a while ago. You get first chance at feedback.
Thank you

Add test modular errata default CV

---

tests/foreman/installer/test_installer.py

In this PR, We are checking the inventory cloud plugin and puppet server tuning parameter update using the satellite installer.
```
$ pytest -s tests/foreman/installer/test_installer.py::test_installer_inventory_plugin_update 
tests/foreman/installer/test_installer.py
.
================================================================================================ warnings summary =================================================================================================
=================================================================================== 1 passed, 3 warnings in 1633.30s (0:27:13) ====================================================================================
$ pytest -s tests/foreman/installer/test_installer.py::test_installer_puppet_overload …
```

Added test coverage for BZ#1863597 and BZ#1920072

---

tests/foreman/ui/test_hostcollection.py

Hi
somehow package name changed back to incorrect version

Package name change regression

---

tests/foreman/ui/test_activationkey.py

Clean up formatting in another
And remove join call against stdout in a third

Fix typeerror in join statement

---

tests/foreman/api/test_contentview.py

Remove instances of puppet and fix a failed test case in contentview.
```
 pytest tests/foreman/api/test_contentview.py
=========================== 40 passed, 8 skipped, 521 warnings in 966.18s (0:16:06) ==============
```

Remove puppet and fix failures in api contentview

---

tests/foreman/ui/test_contenthost.py

Hello
Updating more tests in  /ui/test_contenthost.py  to use REX
Removed redundant `test_actions_katello_host_package_update_timeout` as its only relevant to katello-agent test.
------
I need to wait for this bugzilla to be resolved before I can test this file:
[Bug 1983043 - undefined method `prune_known_hosts!` when executing a remote job](https://bugzilla.redhat.com/show_bug.cgi?id=1983043)
Also
[1986554 – When trying to enable a module stream, 'unexpected token at "' error is displayed](https://bugzilla.redhat.com/show_bug.cgi?id=1986554)
EDIT: those are now verified. 
So now its just https://github.com/SatelliteQE/airgun/pull/607 that this PR needs.

Update test ui test_contenthost to use REX

---

tests/foreman/cli/test_hostgroup.py

```
platform linux -- Python 3.8.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/okhatavk/Satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, ibutsu-1.16, xdist-2.3.0, cov-2.12.1, reportportal-5.0.8, mock-3.6.1, forked-1.3.0collected 17 items / 1 deselected / 16 selected
tests/foreman/cli/test_hostgroup.py                      [100%]
```

Include of puppet classes for Sat-6.10

---

tests/foreman/api/test_syncplan.py
tests/foreman/cli/test_syncplan.py
tests/foreman/ui/test_syncplan.py

Reduce search rate to every 10s (reduce intermittent fails)
Fix logger commands to not use .format

Improve CLI and API sync tests

---

conftest.py
pytest_plugins/metadata_markers.py

component field in metadata is treated specially in ibutsu

Add ibutsu custom metadata

---

tests/foreman/cli/test_product.py

**Test Results - 6.10.0**
```
pytest tests/foreman/cli/test_product.py -k test_positive_product_sync_state
================================== test session starts=========================================
plugins: services-2.2.1, mock-3.6.1, reportportal-5.0.8, forked-1.3.0, xdist-2.3.0, ibutsu-1.16, cov-2.12.1
collected 17 items / 16 deselected / 1 selected                                                                                                                                                                   
tests/foreman/cli/test_product.py s  
========================1 skipped, 16 …
```

Automated stubbed test case for Products feature

---

conf/libvirt.yaml.template
robottelo/api/utils.py
robottelo/config/validators.py
robottelo/libvirt_discovery.py
tests/foreman/api/test_computeresource_libvirt.py
tests/foreman/cli/test_computeresource_libvirt.py
tests/foreman/cli/test_host.py
tests/foreman/cli/test_organization.py
tests/foreman/endtoend/test_api_endtoend.py
tests/foreman/endtoend/test_cli_endtoend.py
tests/foreman/ui/test_computeresource_libvirt.py
tests/foreman/ui/test_contenthost.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_location.py
tests/foreman/ui/test_organization.py
tests/foreman/ui/test_subscription.py
tests/upgrades/test_remoteexecution.py

Changes made by MR#327 of satelliteqe-jenkins repo

[6.9.z] Update top key references of libvirt.yaml

---

requirements.txt

Update broker to 0.1.23

---

robottelo/helpers.py
tests/foreman/api/test_discoveredhost.py

This change switches out the remaining paramiko-related code for our new
method of using host objects. Specifically it uses a host object's
session to create new interactive shell instances.

Use broker's new interactive shell to replace old paramiko functionality

---

conf/libvirt.yaml.template
robottelo/api/utils.py
robottelo/config/validators.py
robottelo/libvirt_discovery.py
tests/foreman/api/test_computeresource_libvirt.py
tests/foreman/cli/test_computeresource_libvirt.py
tests/foreman/cli/test_host.py
tests/foreman/cli/test_organization.py
tests/foreman/ui/test_computeresource_libvirt.py
tests/foreman/ui/test_contenthost.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_location.py
tests/foreman/ui/test_organization.py
tests/foreman/ui/test_subscription.py
tests/upgrades/test_remoteexecution.py

Changes made by MR#327 of satelliteqe-jenkins repo

Update top key references of libvirt.yaml

---

tests/foreman/api/test_ldapauthsource.py

```
rootdir: /home/okhatavk/Satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, ibutsu-1.16, xdist-2.3.0, cov-2.12.1, reportportal-5.0.8, mock-3.6.1, forked-1.3.0collected 2 items
tests/foreman/api/test_ldapauthsource.py                               [100%]
```

fix the ldap api test, updated because of module loc was not called from auth fixture

---

tests/foreman/cli/test_activationkey.py

Automated stubbed test case **test_positive_delete_manifest** in test_activationkey.py
```
pytest -k test_positive_delete_manifest tests/foreman/cli/test_activationkey.py 
=============================== test session starts ===============================
platform linux -- Python 3.8.8, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/sganar/satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, mock-3.6.1, reportportal-5.0.8, forked-1.3.0, xdist-2.3.0, ibutsu-1.16, cov-2.12.1
collected 144 items / 143 deselected / 1 selected …
```

Automated stubbed test case for activationkey feature

---

tests/foreman/ui/test_hostgroup.py

```
rootdir: /home/okhatavk/Satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, ibutsu-1.16, xdist-2.3.0, cov-2.12.1, reportportal-5.0.8, mock-3.6.1, forked-1.3.0collected 6 items / 5 deselected / 1 selected
tests/foreman/ui/test_hostgroup.py                                      [100%]
```

added the test coverage for bz 1996077

---

tests/foreman/cli/test_repository.py

**Test Results - 6.10.0**
```
pytest tests/foreman/cli/test_repository.py -k test_negative_update_red_hat_repo
================================================================= test session starts =============================================================================
plugins: services-2.2.1, mock-3.6.1, reportportal-5.0.8, forked-1.3.0, xdist-2.3.0, ibutsu-1.16, cov-2.12.1
collected 237 items / 236 deselected / 1 selected …
```

Automated stubbed testcase in repository feature

---

conf/server.yaml.template
robottelo/cli/base.py
robottelo/hosts.py
robottelo/ssh.py
tests/foreman/ui/test_reporttemplates.py
tests/robottelo/test_ssh.py

These are a collection of small changes that aim to improve stability of
some or many tests.
Included is the removal of an lru_cache on ssh get_client

Minor framework changes and fixes

---

tests/upgrades/conftest.py

Raise the `DependantTestFailed` error for the post_upgrade test if its dependant pre_upgrade test fails. So that the test will be marked as `blocked` in polarion instead of skipped.

Raise DependantTestFailed error in post_upgrade if pre_upgrade test failed

---

requirements.txt

Update broker to 0.1.25

---

tests/foreman/cli/test_host.py

that leads to:
- `wait_for_errata_applicability_task` is not longer working because there are no longer shown `Actions::Katello::Host::<name_of_the_action>`  actions shown in task manager
- when tested locally passed 7/7 times, but it is possible that errata will no be applied before the next commad/assert will ran
-  the test was failing with `This action uses katello-agent, which is currently disabled. Use remote execution instead`, so I listened and I used remote execution instead :smile: 
I looked at other occurrences in the code, afterwards spoke with @Gauravtalreja1 and he helped me to identify the issue and he also knows that the tests in `test_katello_agent.py` should be reviewed. EDIT: are already in review #9005 is the proof of it :+1: 
```
============================= test …
```

katello agent is no longer enabled by default

---

logging.yaml
robottelo/ssh.py

The get_client function is no longer cached, so the method is no longer
attached.
Also moved broker's file logging to debug

Remove no longer valid cache_clear call

---

tests/foreman/api/test_bookmarks.py
tests/foreman/ui/test_bookmarks.py
tests/upgrades/test_bookmarks.py

Own the tests

---

tests/foreman/api/test_repository.py

This PR adds a test for syncing redhat ansible repository using http proxy.
See [BZ#2011303](https://bugzilla.redhat.com/show_bug.cgi?id=2011303) for more info.
Test result(Satellite 6.10.0 snap 20):
```
$ pytest tests/foreman/api/test_repository.py -k test_positive_sync_redhat_repo_using_http_proxy 
rootdir: /home/jpathan/projects/robottelo, configfile: pyproject.toml
plugins: ibutsu-1.16, reportportal-5.0.8, xdist-2.4.0, services-2.2.1, cov-2.11.1, mock-3.6.1, forked-1.3.0
collected 194 items / 193 deselected / 1 selected
tests/foreman/api/test_repository.py . …
```

Add a test to sync redhat repo using http proxy

---

robottelo/ssh.py

This should allow us to run 6.9.z and current automation without having
to specify different timeout formats in config

Wrap smart timeout config values in a translation call

---

requirements.txt

Updating the broker version on the master branch to 0.1.26

Updating broker version on master

---

conf/robottelo.yaml.template
conf/ui.yaml.template
robottelo/config/__init__.py
robottelo/datafactory.py
tests/foreman/ui/test_host.py

(cherry picked from commit cf358d088dfec4abc4b565dcfb287b4890d86923)

[6.9.z] moving content from robottelo to ui.yaml

---

tests/foreman/cli/test_computeresource_osp.py

OSP compute resources that are not deleted will leave key pairs on OSP. So we need to delete every CR for proper teardown of test. Test were merged to CRUD test to archive this goal.
Test results:
```
pytest -v tests/foreman/cli/test_computeresource_osp.py
================================================================================================ test session starts =================================================================================================
platform linux -- Python 3.9.6, pytest-6.2.5, py-1.10.0, pluggy-0.13.1 -- /home/pdragun/.virtualenvs/robottelo/bin/python
plugins: cov-2.12.1, forked-1.3.0, services-2.2.1, …
```

Merge osp tests to crud

---

conf/report_portal.yaml.template
pytest_plugins/rerun_rp/rerun_rp.py
robottelo/report_portal/portal.py

Reworked plugin for [de]selecting tests based on the appropriate Report Portal launch.

Rp rerun failed refactor

---

requirements.txt

backporting
https://github.com/SatelliteQE/robottelo/pull/9115

bump the version of broker to 0.1.29

---

requirements.txt

This will VASTLY  decrease the time it takes to upload manifests!

Update broker to 0.1.30

---

tests/upgrades/test_syncplan.py

Hello
implementing feedback from https://github.com/SatelliteQE/robottelo/pull/9104

Improve disabled syncplan logic test

---

tests/foreman/api/test_repository.py

**Test result - 6.10**
```
pytest tests/foreman/api/test_repository.py -k test_positive_upload_file_to_file_repo
plugins: services-2.2.1, mock-3.6.1, reportportal-5.0.8, forked-1.3.0, ibutsu-1.16, cov-3.0.0, xdist-2.4.0
collected 187 items / 186 deselected / 1 selected …
```

Automated stubbed test case in repository api file upload feature.

---

tests/foreman/api/test_repository.py

For 6.10 user stories
"Content Protection:
As an unauthenticated user, I can access unprotected content."
Thank you

Add test unauth user download from unprotected repo

---

tests/foreman/cli/test_contentview.py

The path to add rpm in the published dir doesn't exist anymore due to pulp3 changes.  Rewriting the test case using filters and running incremental update on errata.
test result:
```
pytest tests/foreman/cli/test_contentview.py::TestContentView::test_positive_inc_update_no_lce
======================= 1 passed, 3 warnings in 93.48s (0:01:33) ==========
```

Fix Incremental Update Failure in Contentview CLI

---

tests/foreman/api/test_hostgroup.py
tests/foreman/installer/test_installer.py
tests/foreman/ui/test_hostgroup.py
tests/foreman/ui/test_ldap_authentication.py

- Updated the correct importance level to tests 
- Change the owner for the installer tests 
- Fixed some of the tests

update the case importance, change owner for installer tests

---

tests/foreman/ui/test_errata.py

Test failures mostly due to location errors.
Adding some BZ.
Removing SatelliteToolsRepository() where not required.

Fix UI test failures

---

conf/oscap.yaml.template
pytest_fixtures/oscap_fixtures.py
robottelo/config/validators.py
robottelo/constants/__init__.py
tests/foreman/data/ssg-rhel7-ds-tailoring.xml
tests/foreman/longrun/test_oscap.py

Test result:
```
$ pytest tests/foreman/api/test_oscap_tailoringfiles.py tests/foreman/cli/test_oscap_tailoringfiles.py
collected 25 items / 4 deselected / 21 selected
tests/foreman/api/test_oscap_tailoringfiles.py .                         [  4%]
tests/foreman/cli/test_oscap_tailoringfiles.py ....................      [100%]
========== 21 passed, 4 deselected, 20 warnings in 268.16s (0:04:28) ===========
```

Add tailoring file in robottelo

---

tests/foreman/cli/test_computeresource_azurerm.py

Quick Merge to fix the Azure TearDown timeouts in CLI command.

Azure CLI Timeouts updated for new SSH module

---

tests/foreman/cli/test_host.py

crud implemented,
and opened discussion with @JacobCallahan whether crud tests are worth our time
this one was fairly simple, but there are others crud tests not introduced in robottelo, they will take more time.

cli_host_interface_crud_test introduced

---

tests/foreman/api/test_subscription.py

Fixed tests failure, Removed parametrized testing for rhel6, rhel7, and rhel8. 
Open for discussion on whether we need to write 2 more tests for rhel6 and rhel8

changed registered host to rhel7 only

---

tests/foreman/api/test_errata.py

Adding wait_for_errata_applicability_task so that there is no assertion error.
```
(env) [akjha@akjha robottelo]$ pytest -k test_errata_installation_with_swidtags tests/foreman/api/test_errata.py
platform linux -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/akjha/satelliteqe/robottelo, configfile: pyproject.toml
plugins: reportportal-5.0.8, forked-1.3.0, mock-3.6.1, cov-3.0.0, xdist-2.3.0, services-2.2.1, ibutsu-1.16
collected 14 items / 13 deselected / 1 selected …
```

Adding wait_for for interop

---

tests/foreman/ui/test_product.py

```
$ pytest -k test_positive_bulk_action_advanced_sync tests/foreman/ui/test_product.py 
=========================================== test session starts ============================================
rootdir: /home/sganar/satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, mock-3.6.1, reportportal-5.0.8, forked-1.3.0, ibutsu-1.16, cov-3.0.0, xdist-2.4.0
collected 10 items / 9 deselected / 1 selected                                                                                                                                                                    
[](url)
tests/foreman/ui/test_product.py . …
```

Automate UI test related to product advanced sync

---

tests/foreman/api/test_location.py
tests/foreman/api/test_organization.py
tests/foreman/cli/test_organization.py
tests/foreman/ui/test_location.py
tests/foreman/ui/test_organization.py

Updated Case Importance of components Organization and Location.

Case importance update

---

tests/foreman/cli/test_remoteexecution.py

postfix no longer installed by default on rhel8, playing with rsyslog instead. This service is enabled by default so adding a stop service step to make sure rex job takes effect
```
pytest tests/foreman/cli/test_remoteexecution.py -k test_positive_run_packages_and_services_job
tests/foreman/cli/test_remoteexecution.py .                                                                   [100%]
============================= 1 passed, 15 deselected, 5 warnings in 618.57s (0:10:18) ==============================
```

fix in rhel8 service rex test

---

tests/foreman/cli/test_errata.py
tests/foreman/ui/test_errata.py

Will raise PR for api/test_errata.py after https://github.com/SatelliteQE/robottelo/pull/9046 gets merged.

Changing caseimportance {ui/cli}/test_errata.py

---

tests/foreman/ui/test_hostcollection.py

Hi
Adding location at the start of sessions in ui/test_hostcollection.py
issue #9040 refers

Add location to sessions in test_hostcollection.py

---

tests/foreman/ui/test_dashboard.py

**Test Results - 6.10**
```
pytest tests/foreman/ui/test_dashboard.py -k test_positive_sync_overview_widget
plugins: services-2.2.1, mock-3.6.1, reportportal-5.0.8, forked-1.3.0, ibutsu-1.16, cov-3.0.0, xdist-2.4.0
collected 5 items / 4 deselected / 1 selected …
```

Test Coverage for Dashboard Sync overview widget

---

pytest_fixtures/component/oscap.py
tests/foreman/cli/test_rhcloud_inventory.py

This PR automates `test_positive_sync_inventory_status` test and fixes `oscap_content_path` fixture.

Automate test_positive_sync_inventory_status

---

tests/foreman/cli/test_remoteexecution.py

6.9 backport changes in rex services test

---

tests/foreman/ui/test_contenthost.py

Hi
Adding location at the start of sessions in test_contenthost.py
issue #9040 refers

Adding a location to all sessions in test_contenthost.py

---

tests/foreman/ui/test_repository.py

Creating a manual test case for https://bugzilla.redhat.com/show_bug.cgi?id=1860957
There has been discussion around automating this, and it was determined to be more work than value. Not sure if this is the correct place to stick this, would like feedback.

test: Unable to select organization for Sync management

---

conf/ipa.yaml.template
pytest_fixtures/component/satellite_auth.py

changes in how freeipa.keytab is distributed, related to jira SATQE-6333, related satellitewqe mr pending

keytab pulled differently

---

tests/foreman/cli/test_errata.py

The BZ is not ON_QA. PRT will be skipped

Automation qe_test_coverage_1785146

---

tests/foreman/cli/test_repository.py

Writing a test to cover https://bugzilla.redhat.com/show_bug.cgi?id=1992967 
First test written, give me all the feedback :smiling_face_with_tear:

Test: positive create with new location and organization

---

tests/foreman/cli/test_remoteexecution.py

Results now contain one string instead of list of lines.
Also, it's necessary to output debugging information such as repolist
and invocation output to determine why this fails in the automation.

Fix receptor test.

---

tests/foreman/api/test_contentmanagement.py

Adding closed-loop test for https://bugzilla.redhat.com/show_bug.cgi?id=2025494
The BZ is still open, the fix should land in 6.10.2 by 12/21/2021. If not skipped, it currently fails as expected:
```
>       assert len(sync_status['last_failed_sync_tasks']) == 0
E       assert 1 == 0
E        +  where 1 = len([{'action': "Synchronize capsule 'capsule.redhat.com'", 'available_actions': {'cancellable': False, 'resumable': False}, 'cli_example': None, 'ended_at': '2021-12-10 18:34:41 UTC', ...}])
```

Closed-loop for BZ 2025494

---

tests/foreman/ui/test_contentview.py

It's not possible to add an rpm to the the /var/lib/pulp/published path anymore due to pulp3.  Rewriting test case another way.

fix contentview cli failures

---

requirements.txt
tests/foreman/ui/test_contentview.py

Merge this PR only if https://github.com/SatelliteQE/airgun/pull/647 is merged!
Read the discussions here why we are doing it : https://github.com/SatelliteQE/robottelo/pull/9177

Remove Selenium dependency as exception moved to airgun

---

conf/osp.yaml.template

Removing osp hostname from osp.yaml.template

---

requirements.txt
tests/foreman/ui/test_contentview.py

Cherry-Picked #9256 !
Merge it only after https://github.com/SatelliteQE/airgun/pull/650 merged !

[Cherry-Pick] Remove Selenium dependency from 6.10.z

---

robottelo/cli/factory.py
tests/foreman/cli/test_hostgroup.py

```
py.test with arguments -k test_positive_created_nested_hostgroup /home/okhatavk/Satellite/robottelo/tests/foreman/cli/test_hostgroup.py in /home/okhatavk/Satellite/robottelo
rootdir: /home/okhatavk/Satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, xdist-2.4.0, ibutsu-1.16, cov-2.12.1, reportportal-5.0.8, mock-3.6.1, forked-1.3.0collected 18 items / 17 deselected / 1 selected
tests/foreman/cli/test_hostgroup.py 2021-12-22 15:53:57 - robottelo.collection - INFO - Processing test items to add testimony token markers
[INFO 211222 15:53:57] Using username and …
```

added the customer scenarios for hg

---

tests/foreman/api/test_rhcloud_inventory.py
tests/foreman/cli/test_computeresource_azurerm.py
tests/foreman/cli/test_host.py
tests/foreman/cli/test_remoteexecution.py
tests/foreman/installer/test_installer.py
tests/foreman/ui/test_contentview.py
tests/foreman/ui/test_errata.py
tests/upgrades/test_bookmarks.py
tests/upgrades/test_repository.py
tests/upgrades/test_syncplan.py

closes #9260
closes #9264
Based on automated bz check that runs weekly, would be good to get this in this week to prevent unnecessary issue creation

added missing customerscenario tags

---

scripts/polarion-test-case-upload.sh
scripts/polarion-test-run-upload.sh
tests/upgrades/conftest.py
tests/upgrades/test_activation_key.py
tests/upgrades/test_bookmarks.py
tests/upgrades/test_capsule.py
tests/upgrades/test_classparameter.py
tests/upgrades/test_client.py
tests/upgrades/test_contentview.py
tests/upgrades/test_errata.py
tests/upgrades/test_foreman_maintain.py
tests/upgrades/test_host.py
tests/upgrades/test_hostgroup.py
tests/upgrades/test_performance_tuning.py
tests/upgrades/test_remoteexecution.py
tests/upgrades/test_repository.py
tests/upgrades/test_role.py
tests/upgrades/test_satellitesync.py
tests/upgrades/test_subnet.py
tests/upgrades/test_subscription.py
tests/upgrades/test_syncplan.py
tests/upgrades/test_user.py
tests/upgrades/test_usergroup.py
tests/upgrades/test_virtwho.py
tests/upgrades/test_yum_plugins.py

[CherryPick] Upgrade Scenarios pushing individually to polarion

---

conf/robottelo.yaml.template
conf/server.yaml.template
pytest_plugins/metadata_markers.py
robottelo/hosts.py

RHEL VERSION is now configurable in robottelo.yaml

Metadata for RHEL version

---

tests/foreman/api/test_contentview.py
tests/foreman/api/test_repository.py

Adding test stubs for the Pulp Task Clean-up feature.

Pulp Task Clean-up stubs

---

conf/repos.yaml.template
conf/server.yaml.template

[Cherry-Pick] Added satellite repository and rhel major version in repos.yml

---

tests/foreman/ui/test_rhcloud_insights.py

added cs tag for ui insights test

---

conf/remotedb.yaml.template
conftest.py
pytest_fixtures/component/maintain.py
robottelo/cli/base.py
robottelo/cli/fm_backup.py
robottelo/cli/fm_health.py
robottelo/cli/fm_restore.py
robottelo/cli/fm_service.py
robottelo/cli/fm_upgrade.py
robottelo/config/validators.py

[6.10.z] Initial RemoteDB config and foreman-maintain CLI's

---

conf/rhev.yaml.template
tests/foreman/ui/test_computeresource.py

Move RHEV cert from Sesame to config,
Remove APIv3 since it is not supported anymore,
Unmark tests as provisioning since they are not

Multiple RHEV test fixes

---

conf/repos.yaml.template
conf/server.yaml.template

[Cherry-Pick 6.9.z] Added satellite repository and rhel major version in repos.yml

---

scripts/polarion-test-case-upload.sh
scripts/polarion-test-run-upload.sh
tests/upgrades/conftest.py
tests/upgrades/test_activation_key.py
tests/upgrades/test_bookmarks.py
tests/upgrades/test_capsule.py
tests/upgrades/test_classparameter.py
tests/upgrades/test_client.py
tests/upgrades/test_contentview.py
tests/upgrades/test_errata.py
tests/upgrades/test_foreman_maintain.py
tests/upgrades/test_host.py
tests/upgrades/test_hostgroup.py
tests/upgrades/test_performance_tuning.py
tests/upgrades/test_remoteexecution.py
tests/upgrades/test_repository.py
tests/upgrades/test_role.py
tests/upgrades/test_satellitesync.py
tests/upgrades/test_subnet.py
tests/upgrades/test_subscription.py
tests/upgrades/test_syncplan.py
tests/upgrades/test_user.py
tests/upgrades/test_usergroup.py
tests/upgrades/test_virtwho.py
tests/upgrades/test_yum_plugins.py

Cherry-Pick #9278 !
Fixes #9316 !

Fixes #9316 - [6.9.z CherryPicked] Upgrade Scenarios pushing individually to Polarion

---

conf/capsule.yaml.template
conf/repos.yaml.template
conf/server.yaml.template
pytest_plugins/metadata_markers.py
robottelo/hosts.py

Cherry-picked PR#[9304](https://github.com/SatelliteQE/robottelo/pull/9304)

RHEL_VERSION(Fix#9304 6.10.z cherry-picked)

---

conf/capsule.yaml.template
conf/repos.yaml.template
conf/server.yaml.template
pytest_plugins/testimony_markers.py
robottelo/hosts.py

Cherry-picked PR#[9304](https://github.com/SatelliteQE/robottelo/pull/9304)

RHEL_VERSION(Fix#9304 6.9.z cherry-picked)

---

tests/foreman/api/test_repository.py

Skip Repo sync test with bug 2042473

---

tests/foreman/api/test_repository.py

Adding test for recreating deleted Pulp Repositories

added test for recreating deleted repos

---

pytest_plugins/fixture_markers.py

Adds the user_property for `Content host RHEL Version` for the tests which are using fixtures(spinning Content_hosts) from the `pytest_fixtures/core/content_hosts.py` fixture module.

ClientOS User Property

---

tests/foreman/longrun/test_inc_updates.py
tests/foreman/ui/test_contenthost.py

Hello
Due to:
[BZ#2017533 – API call to generate applicability does not return task info](https://bugzilla.redhat.com/show_bug.cgi?id=2017533)
I am changing the method used to check for completion of applicability calculation.
Also added module_org to a search.
Thank you

Change applicability task check

---

pytest_fixtures/component/subscription.py
robottelo/hosts.py

This previously checked the container object instead of stdout itself.

Fix incorrect check in subscribe_satellite

---

robottelo/cli/host.py
tests/foreman/cli/test_computeresource_rhev.py

#6497 Check host disassociation

---

conf/capsule.yaml.template
conf/content_host.yaml.template
conf/repos.yaml.template
pytest_fixtures/core/contenthosts.py
pytest_plugins/fixture_markers.py

backport of https://github.com/SatelliteQE/robottelo/pull/9327

[backport] 6.10.z rhel versions

---

.github/workflows/merge_to_master.yml
.github/workflows/pull_request.yml

Backport of #9341 to 6.10z branch

[cherry-pick] Temporarily Stop Updating pip

---

.github/workflows/merge_to_master.yml

This reverts commit 2ac459c3451b56313a87f02b78ae3c534baddd92.

Revert "Temporarily disable pip in merge_to_master"

---

requirements.txt

Update reqs for nailgun/airgun/upgrade for 6.10.z

---

requirements.txt

removed dependancy for widgetastic as airgun takes care

---

tests/foreman/cli/test_foremantask.py
tests/foreman/cli/test_http_proxy.py

Added two manual test cases
1. https://bugzilla.redhat.com/show_bug.cgi?id=1615015
2. https://bugzilla.redhat.com/show_bug.cgi?id=1886040

Add manual tests for BZ#1615015 and BZ#1886040

---

tests/foreman/cli/test_rhcloud_inventory.py

**Test results**
```
pytest tests/foreman/cli/test_rhcloud_inventory.py -k test_positive_inventory_recommendation_sync
plugins: services-2.2.1, mock-3.6.1, reportportal-5.0.8, forked-1.3.0, ibutsu-2.0.2, cov-3.0.0, xdist-2.5.0
collected 6 items / 5 deselected / 1 selected …
```

Test Coverage for insights inventory sync

---

tests/foreman/cli/test_location.py

Automated BZ https://bugzilla.redhat.com/show_bug.cgi?id=1937009

Close loop bz

---

robottelo/api/utils.py

Introducing an optional `strict` flag for `enable_rhrepo_and_fetchid` api helper function.
This allows us to choose a strategy for cases where we try to enable an already enabled repo.
if `strict=True`, a proper 409 is raised.
If not (new default), the Exception is ignored and the method continues its execution and eventually returns the desired repo id.
Motivation:
this helps in function-based fixtures that work with `module_org`
There's currently no exception-dependent use of the method, so change in the default is not a breaking change:
```
$ git grep  "= enable_rhrepo_and_fetchid"
api/test_activationkey.py:    rh_repo_id = enable_rhrepo_and_fetchid(
api/test_contentmanagement.py:        rh_repo_id = enable_rhrepo_and_fetchid(
api/test_contentmanagement.py:        rh_repo_id = …
```

add optional 'strict' flag for failing on 409 for reposet enable

---

tests/foreman/cli/test_katello_agent.py

Backport: https://github.com/SatelliteQE/robottelo/pull/9320

[6.10.z] Remove use of nested Satellite context manager

---

.gitignore
robottelo/host_helpers/__init__.py
robottelo/host_helpers/cli_factory.py
robottelo/host_helpers/contenthost_mixins.py
robottelo/host_helpers/satellite_mixins.py
robottelo/hosts.py

as we move forward with a larger helpers refactor.
Included in this change are the introduction of mixins for our host
objects and a replacement for the cli factory methods.
The goal of this is to consolidate helper functionality under the host
objects, to reduce conflicts between test systems.

This commit introduces some of the patterns that will be primarily used

---

robottelo/hosts.py

@JacobCallahan @mshriver As per offline conversation, replacing OS version from settings by `self.os_version`.

Use host's os_version instead of conf

---

tests/foreman/ui/test_reporttemplates.py

Cherry-pick of https://github.com/SatelliteQE/robottelo/pull/9373

Fix incorrect file naming after refactor. Use org with manifest.

---

.gitignore
conf/content_host.yaml.template
conf/supportability.yaml
pytest_fixtures/core/contenthosts.py
pytest_plugins/fixture_markers.py
pytest_plugins/markers.py
robottelo/config/validators.py

backport of: https://github.com/SatelliteQE/robottelo/pull/9334

[6.10.z] add rhel_contenthost-specific markers to filter os version parametrization

---

.gitignore
conf/content_host.yaml.template
conf/supportability.yaml
pytest_fixtures/content_hosts.py
pytest_plugins/fixture_markers.py
pytest_plugins/markers.py
robottelo/config/validators.py

backport of: https://github.com/SatelliteQE/robottelo/pull/9334

[6.9.z] add rhel_contenthost-specific markers to filter os version parametrization

---

pytest_fixtures/component/maintain.py
robottelo/hosts.py
tests/foreman/maintain/test_backup_restore.py

[cherrypick] Port/refactor of backup/restore tests from testfm

---

tests/foreman/api/test_computeresource_gce.py
tests/foreman/api/test_repository.py
tests/foreman/ui/test_computeresource_gce.py
tests/foreman/ui/test_containerimagetag.py

1. ComputeResources-GCE
2. ContainerManagement-Content

Updated component ownership

---

robottelo/hosts.py

Missed in reviews of PR https://github.com/SatelliteQE/robottelo/pull/9369

Fix rhel_version param in capsule_setup

---

tests/foreman/ui/test_contentview.py

This test case is not applicable anymore.  removing it for 6.10.z.

removing NA test case

---

pytest_fixtures/component/subscription.py

Fixes https://github.com/SatelliteQE/robottelo/issues/9403

Fix releasever for RHEL8

---

tests/foreman/api/test_role.py
tests/foreman/api/test_user.py
tests/foreman/api/test_usergroup.py
tests/foreman/cli/test_computeresource_osp.py
tests/foreman/cli/test_role.py
tests/foreman/cli/test_user.py
tests/foreman/cli/test_usergroup.py
tests/foreman/ui/test_role.py
tests/foreman/ui/test_user.py
tests/foreman/ui/test_usergroup.py
tests/upgrades/test_role.py
tests/upgrades/test_user.py
tests/upgrades/test_usergroup.py

Updated component ownership for:
1. Users&roles
2. Computeresource-OSP

Update component ownership

---

pytest_fixtures/core/contenthosts.py
pytest_fixtures/core/sys.py
robottelo/hosts.py
tests/foreman/ui/test_host.py

~~Merge after: SatelliteQE/airgun/pull/676~~ :heavy_check_mark: 
Adding parametrization for cockpit content host testing.

Cockpit rhel host parametrization

---

tests/foreman/ui/test_settings.py

Test failed for Settings had incorrect scenario. Updated the failed test.

Fix: Settings Test Case

---

tests/foreman/api/test_host.py

rebased on #9286 
using nailgun #807
test results:

Api testhost run puppet tests on destructive satellite with enabled puppet

---

tests/foreman/cli/test_location.py
tests/foreman/cli/test_setting.py
tests/foreman/ui/test_location.py
tests/foreman/ui/test_organization.py

Test Failures fix
1. tests/foreman/cli/test_setting.py::test_positive_failed_login_attempts_limit
2. tests/foreman/cli/test_location.py::test_positive_create_update_delete
3. tests/foreman/ui/test_organization.py::test_positive_end_to_end
4. tests/foreman/ui/test_location.py::test_positive_end_to_end

Test failures fix

---

tests/foreman/ui/test_contentview.py

There was a test case that was using an invalid piece of code.  Fixing it to use the correct one to pull in data.

Simple fix for a cv test case

---

tests/foreman/ui/test_settings.py

Cherrypick PR [9144](https://github.com/SatelliteQE/robottelo/pull/9144)

[6.10.z] cherrypick setings test fix

---

tests/foreman/api/test_repository.py

cherrypicking some test fixes into 6.10.4

Cherry-pick repo test fixes 

---

conf/repos.yaml.template
conf/robottelo.yaml.template
robottelo/constants/__init__.py
tests/foreman/api/test_repository.py
tests/foreman/cli/test_repository.py
tests/foreman/ui/test_repository.py
tests/upgrades/test_satellite_maintain.py

Update Satellite 7.0 references to 6.11

---

tests/foreman/cli/test_remoteexecution.py

Parametrized the rex permissions test to include also capsule host

test rex against capsule permissions

---

tests/foreman/cli/test_host.py

List infra hosts (satellite and capsule) using `infrastructure_facet.foreman` and `infrastructure_facet.smart_proxy_id`
results:
```
pytest tests/foreman/cli/test_host.py -k test_positive_list_infrastructure_hosts
================================================ test session starts ================================================                                                                 
tests/foreman/cli/test_host.py .                                                                              [100%]
```

test search for infrastructure hosts

---

tests/foreman/api/test_rhcloud_inventory.py
tests/foreman/cli/test_rhcloud_insights.py
tests/foreman/cli/test_rhcloud_inventory.py
tests/foreman/ui/test_rhcloud_insights.py
tests/foreman/ui/test_rhcloud_inventory.py

Updated component ownership for rh_cloud_plugin

Updated component ownership for rh_cloud_plugin

---

tests/foreman/api/test_contentmanagement.py

Fix the mirroring policy test cases for 7.0

Mirroring policy for 7.0

---

.pre-commit-config.yaml

Cherry-picked https://github.com/SatelliteQE/robottelo/pull/9470

bump black version in pre-commit

---

scripts/customer_scenarios.py

This change brings the script up-to-date with the latest authorization method accepted by the Bugzilla api.

Update customer scenarios script to new BZ auth

---

tests/foreman/cli/test_contentaccess.py
tests/foreman/longrun/test_inc_updates.py
tests/foreman/ui/test_contenthost.py

PR to change hosts-content assignee and related to tests from @swadeley to myself

Change Hosts-Content assignee to spusater

---

tests/foreman/cli/test_remoteexecution.py

this slipped my attention in former refactoring pr

removing unwanted skip from cli rex

---

tests/foreman/ui/test_host.py

For Global Registration form
User Story review for 6.11
Hello
adding a few lines to an end to end test to check that the "update packages" feature in the global registration form does work.
Thank you

Add check update packages

---

tests/foreman/ui/test_errata.py

1. Adding coverage for BZ2029192
2. Minor Assertion updates.
3. Removing 1 test as BZ is on WONTFIX

Fixing UI test_errata

---

tests/foreman/longrun/test_oscap.py

Removing Puppet related tests of Openscap.
I will be raising separate PR to add test scenarios to run on puppet enabled satellite.

Remove Openscap Puppet tests

---

robottelo/hosts.py

hotfix, installer colors breaking CI pipeline

---

tests/foreman/ui/test_computeresource_azurerm.py

**Test Results**
```
pytest  tests/foreman/ui/test_computeresource_azurerm.py
plugins: reportportal-5.0.12, services-2.2.1, mock-3.7.0, forked-1.3.0, ibutsu-2.0.2, cov-3.0.0, xdist-2.5.0
collected 2 items …
```

Compute_resource_azure - [UI fixes]

---

tests/foreman/api/test_contentmanagement.py

Adding close loop automation for above bz

automation for bz:1747177 for 6.11

---

tests/foreman/ui/test_remoteexecution.py

closes #9266
the test now looks also at the dashboard widget
depends on https://github.com/SatelliteQE/airgun/pull/686

rex dashboard check

---

tests/foreman/ui/test_organization.py

Few tests in tests/foreman/ui/test_organization.py needs refactor in airgun because of ui changes all tests won't pass in this PR.
pytest tests/foreman/ui/test_organization.py 
shared_function enabled - OFF - scope: None - storage: file
rootdir: /home/shwsingh/SatelliteQE/robottelo, configfile: pyproject.toml
plugins: forked-1.3.0, services-2.2.1, reportportal-5.0.8, cov-2.12.1, ibutsu-1.16, xdist-2.4.0, mock-3.6.1
collected 2 items …

Positive test scenarios for Organization

---

tests/foreman/cli/test_remoteexecution.py

me being stupid, in response to feedback in https://github.com/SatelliteQE/robottelo/pull/9493 I renamed fixture definitions but nothing else, fixing here

proper fixture rename in rex cli

---

robottelo/api/utils.py

Cherrypick PR #9348 into 6.10.z to resolve repo conflict errors in z-stream 
`E   requests.exceptions.HTTPError: 409 Client Error: Conflict for url: [https://satellite.redhat.com:443/katello/api/v2/repository_sets/7421/enable](https://satellite.redhat.com/katello/api/v2/repository_sets/7421/enable)`

[6.10.z] add optional 'strict' flag for failing on 409 for reposet enable

---

tests/foreman/ui/test_host.py

For 6.11 user stories
Hello
adding test for user story: As a user I want to upgrade subscription-manager to the latest version prior the registration 
Thank you

Add test update subs-man with global reg cmd

---

tests/foreman/ui/test_computeresource_ec2.py

Cherrypick of https://github.com/SatelliteQE/robottelo/pull/9535

skip_if_open 2032530

---

tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_discoveryrule.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/cli/test_discoveryrule.py
tests/foreman/ui/test_discoveredhost.py
tests/foreman/ui/test_discoveryrule.py

Updating assignee for Discovery Image and Discovery Plugin. I'm guessing we cherry pick these?

Changing assignee for gsulliva

---

tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_discoveryrule.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/cli/test_discoveryrule.py
tests/foreman/ui/test_discoveredhost.py
tests/foreman/ui/test_discoveryrule.py

6.10.z backport for https://github.com/SatelliteQE/robottelo/pull/9531

[6.10.z] Changing assignee for gsulliva

---

.env
.env.example
.github/workflows/merge_to_master.yml
.github/workflows/pull_request.yml
.github/workflows/weekly.yml
.gitignore
Makefile
docs/index.rst
requirements.txt
robottelo/config/__init__.py
robottelo/config/validators.py
robottelo/errors.py
scripts/vault_login.py

**The PR integrates Hashicorp Vault as a secret store via DynaConf.**
The PR is dependent on following 2 DynaConf Upstream PRs which are now merged:
And CI MR (Need to merge along with this PR):
Tests Results:
----------------
Check Critical Tests : https://{stage_url}/job/jyejare-6.11-rhel7-critical/2
Check High Tests: https://{stage_url}/job/jyejare-6.11-rhel7-high/1

[Merge with CI PR]  Secrets from vault via DynaConf

---

tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_discoveryrule.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/cli/test_discoveryrule.py
tests/foreman/ui/test_discoveredhost.py
tests/foreman/ui/test_discoveryrule.py

6.9.z backport for https://github.com/SatelliteQE/robottelo/pull/9531

[6.9.z] Changing assignee for gsulliva

---

.env
.env.example
.github/workflows/merge_to_master.yml
.github/workflows/pull_request.yml
.gitignore
Makefile
docs/index.rst
requirements.txt
robottelo/config/__init__.py
robottelo/config/validators.py
robottelo/errors.py
scripts/vault_login.py

[6.9 Cherrypick] Dynaconf acceess secrets from vault

---

.env
.env.example
.github/workflows/merge_to_master.yml
.github/workflows/pull_request.yml
.github/workflows/weekly.yml
.gitignore
Makefile
docs/index.rst
requirements.txt
robottelo/config/__init__.py
robottelo/config/validators.py
robottelo/errors.py
scripts/vault_login.py

[6.10 Cherrypick] Dynaconf acceess secrets from vault

---

robottelo/hosts.py

This new version is more resilient to being passed around by pickle.

Bring back changes around Satellite api/cli/ui_session properties

---

tests/foreman/ui/test_host.py

Closed loop: BZ#1923320
Hello
just adding BZ number to docstring and UUID to BZ
[Bug 1923320](https://bugzilla.redhat.com/show_bug.cgi?id=1923320) - Global Registration: of FIPS RHEL8 host fails with Transaction error: no digest

Adding :BZ: 1923320 to doctring

---

tests/foreman/sys/test_fam.py

Updating Ansible collection assignee on 6.10.z

[6.10.z] Update Ansible Collection assignee

---

robottelo/hosts.py

Cherry pick of https://github.com/SatelliteQE/robottelo/pull/9568

[6.10] install_katello_ca does not raise ContentHostError

---

tests/foreman/sys/test_fam.py

Updating Ansible Collection assignee on 6.9.z

[6.9.z] Update Ansible Collection assignee

---

tests/foreman/cli/test_contentview.py
tests/foreman/ui/test_contentview.py

Wrote automation for closed loop bz: https://bugzilla.redhat.com/show_bug.cgi?id=2041497
result:
```
pytest tests/foreman/cli/test_contentview.py -k test_positive_inc_update_should_not_fail
=============== 1 passed, 136 deselected in 117.00s (0:01:56) =============
pytest tests/foreman/ui/test_contentview.py -k test_positive_inc_update_should_not_fail
=========== 1 passed, 78 deselected, 1 warning in 122.57s (0:02:02) ===========
```

closed loop bz for 2041497 for 6.10.z

---

tests/foreman/maintain/test_backup_restore.py
tests/foreman/sys/test_sat_clone.py

Updating assignees for Sat-Clone and Foreman-Maintain

Update assignees to the component owners

---

tests/foreman/api/test_audit.py
tests/foreman/api/test_remoteexecution.py
tests/foreman/cli/test_remoteexecution.py
tests/foreman/ui/test_audit.py
tests/foreman/ui/test_remoteexecution.py

Pretty sure this is all I need to do

Change ownership of ansible/auditlog tests to me

---

tests/foreman/api/test_contentmanagement.py

@vsedmik suggest to putting this test case in the other class scope so it can be a better fit than in `capsule` space.  And I agree.

Rearrange uuid test case to correct class in file

---

tests/foreman/cli/test_contentview.py
tests/foreman/ui/test_contentview.py

Wrote this for 6.10 and moving it to 6.11 as well.

closed loop 2041497 for 6.11

---

tests/foreman/sys/test_sat_clone.py

[6.9.z] Update assignees to the component owners

---

tests/foreman/maintain/test_backup_restore.py
tests/foreman/sys/test_sat_clone.py

[6.10.z] Update assignees to the component owners

---

tests/foreman/api/test_role.py

**`Test Results:`**
```
$ pytest -k test_negative_access_entities_from_ldap_org_admin tests/foreman/api/test_role.py 
====================================== test session starts ===================================================
rootdir: /home/sganar/satellite/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, mock-3.6.1, forked-1.3.0, ibutsu-2.0.2, reportportal-5.0.11, cov-3.0.0, xdist-2.5.0
collected 50 items / 49 deselected / 1 selected …
```

Automate API stubbed tests in test_role.py

---

robottelo/hosts.py

cherry pick of https://github.com/SatelliteQE/robottelo/pull/9568

[6.9] install_katello_ca does not raise ContentHostError

---

tests/foreman/api/test_role.py
tests/foreman/cli/test_usergroup.py

Cherrypick of https://github.com/SatelliteQE/robottelo/pull/9458

[6.10]Fix cli usergroup tests

---

tests/foreman/sys/test_rename.py

[6.10] strip newline from stdout in rename tests

---

conf/content_host.yaml.template
conf/repos.yaml.template
pytest_fixtures/core/contenthosts.py
robottelo/config/validators.py
robottelo/constants/__init__.py
testimony.yaml
tests/foreman/api/test_convert2rhel.py

~~Depends on nailgun PR: SatelliteQE/nailgun/pull/827~~
Note that this PR requires changes in conf, so please merge alongside PR to our conf repo.

Add tests for convert2rhel feature

---

tests/foreman/ui/test_branding.py

1. Adding some basic test to check correct version and 'Beta' check.
2. Depends on https://github.com/SatelliteQE/airgun/pull/701

Adding some branding tests

---

tests/foreman/ui/test_branding.py

1. Adding some basic test to check correct version and 'Beta' check.
2. Depends on https://github.com/SatelliteQE/airgun/pull/701

[6.10.z] Adding some branding tests

---

tests/foreman/cli/test_repository.py

Fixed assertion for test_positive_export_ansible_collection

Fixed Anisble Collection Test

---

tests/foreman/ui/test_contenthost.py

This PR fixes an error that would appear when asserting against the uri, due to the equals sign `=` not being encoded properly. To fix this, I parsed the uri components individually using `urlparse()` and used `urlencode()` to properly format the assertion rather than hard coding it and running into potential similar errors in the future

Fix e2e bulk update test failure

---

tests/foreman/ui/test_repository.py

Add test for deleting rhrepo

---

conf/rh_cloud.yaml.template

Dependency for satelliteqe-jenkins MR 578

Add install_rhc in rh_cloud.yaml.template

---

tests/foreman/api/test_rhcloud_inventory.py

Test coverage for BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2035204

rh_cloud test coverage

---

tests/foreman/api/test_computeresource_azurerm.py
tests/foreman/cli/test_computeresource_azurerm.py
tests/foreman/ui/test_computeresource_azurerm.py

[6.10 CherryPick] Removed skip test for bug 1850934 and UI test teardown fix

---

tests/foreman/api/test_hostgroup.py
tests/foreman/cli/test_hostgroup.py

Hey @omkarkhatavkar, I've noticed there are some puppet-related hostgroup tests failing as they are run against the default sat (without puppet).
Here I propose a fix for the api/cli ones, where I just let them run against the puppet-enabled satellite:
```
tests/foreman/api/test_hostgroup.py::TestHostGroup::test_inherit_puppetclass
tests/foreman/api/test_hostgroup.py::TestHostGroup::test_positive_create_with_properties
tests/foreman/api/test_hostgroup.py::TestHostGroup::test_positive_update_puppet_ca_proxy
tests/foreman/api/test_hostgroup.py::TestHostGroup::test_positive_update_puppet_proxy
tests/foreman/api/test_hostgroup.py::TestHostGroupMissingAttr::test_positive_read_puppet_ca_proxy_name
tests/foreman/api/test_hostgroup.py::TestHostGroupMissingAttr::test_positive_read_puppet_proxy_name …
```

Fix puppet-related api/cli hostgroup tests

---

robottelo/hosts.py

rh_cloud inventory test cases were failing because of `broker teardown error` the issue was prevailing because of 
`return entities.Host().search(query={'search': self.hostname})[0]` this, as it was pointing towards the satellite in the server.yaml/local-sat, not the satellite got checked out by the fixture. Hence finding out the hosts at the wrong place to check out was resulting in the above error.
Thanks to @JacobCallahan for helping with another investigation!

Fix for broker teardown error

---

pytest_fixtures/component/activationkey.py
tests/foreman/cli/test_repository.py

Customer scenario testing that candlepin status is accurate when no certificate has been updated

test for accessible content status

---

tests/foreman/sys/test_rename.py

In #9601 I did omit one problem with checking stderr, fixing now

fixing negative rename test

---

conf/supportability.yaml
tests/foreman/cli/test_remoteexecution.py

For now, due to template readiness issue

wait with fips rhel9 client tesing

---

tests/foreman/sys/test_rename.py

Cherry pick of https://github.com/SatelliteQE/robottelo/pull/9643

[6.10] fixing negative rename test

---

tests/foreman/cli/test_repository.py

test_positive_update_mirror_on_sync[0] has been updated to test mirroring-policy not mirror-on-sync

Fixed mirror on sync tests

---

tests/foreman/api/test_remoteexecution.py
tests/foreman/cli/test_remoteexecution.py

inspired by https://github.com/SatelliteQE/robottelo/pull/9629

moving to module_capsule_configured in rex tests

---

pytest_fixtures/component/satellite_auth.py

Destructive tests get executed now, which uncovered some issues in idm related fixtures that were long time out of action.

fixes in enroll idm fixture

---

pytest_fixtures/component/rh_cloud.py
tests/foreman/api/test_rhcloud_inventory.py
tests/foreman/cli/test_rhcloud_inventory.py
tests/foreman/ui/test_rhcloud_insights.py
tests/foreman/ui/test_rhcloud_inventory.py

`Removing token-based fixtures for rh_cloud_inventory/insights for test fixes`

Restructuring rh_cloud test cases based on cert auth

---

conf/repos.yaml.template
robottelo/config/validators.py
robottelo/constants/__init__.py
robottelo/hosts.py
tests/foreman/sys/test_katello_certs_check.py

Fixed katello certs tests.  
```
collecting ... collected 13 items / 12 deselected / 1 selected
tests/foreman/sys/test_katello_certs_check.py::TestKatelloCertsCheck::test_positive_install_sat_with_katello_certs[rhel7] 
=========== 1 passed, 12 deselected, 8 warnings in 554.53s (0:09:14) ===========
```

fixed the katello cert tests

---

tests/foreman/api/test_contentcredentials.py
tests/foreman/cli/test_contentcredentials.py
tests/foreman/ui/test_contentcredentials.py

Hi,
I will be taking over the Content Credentials component from @swadeley, and this PR changes the assignee field in the files to reflect this change. 
Thanks

Change ContentCredentials assignee to myself (spusater)

---

tests/foreman/cli/test_discoveryrule.py
tests/foreman/ui/test_discoveredhost.py
tests/foreman/ui/test_discoveryrule.py

Backport of https://github.com/SatelliteQE/robottelo/pull/9683.
Fixing some discovery UI failures.

Fixing DiscoveryPlugin tests for 6.10.z

---

pytest_fixtures/component/taxonomy.py
tests/foreman/ui/test_repository.py

Hi
Adding test for bug[1].
[1]
[Bug 1924625](https://bugzilla.redhat.com/show_bug.cgi?id=1924625) - Sync status showing never synced even though the repositories has been synced successfully

Add test sync status persists after task delete

---

robottelo/hosts.py

[6.10] fix rpm check for katello-ca-consumer

---

tests/foreman/api/test_discoveredhost.py
tests/foreman/cli/test_discoveredhost.py
tests/foreman/ui/test_discoveredhost.py

Splitting discovery plugin and discovery image into separate components.

Updating test_discoveredhost to DiscoveryImage

---

robottelo/virtwho_utils.py

Hey,
Update the Json format for API /rhsm/hypervisors . [Bug2083444](https://bugzilla.redhat.com/show_bug.cgi?id=2083444)
Test Cases:PASS
```
(robottelo_vv) [yanpliu@yanpliu robottelo]$ pytest ./tests/foreman/virtwho/cli/test_esx.py -k test_positive_post_hypervisors 
platform linux -- Python 3.8.12, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/yanpliu/gitrepo/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, ibutsu-2.0.2, forked-1.4.0, xdist-2.5.0, cov-3.0.0, metadata-1.11.0, html-3.1.1, mock-3.7.0, …
```

Update Json format for api /rhsm/hypervisors : Bug2083444

---

.github/workflows/merge_to_master.yml
.github/workflows/pull_request.yml

This will actually allow for calls that check authentication against the bugzilla api

Add bugzilla key to pull request and merge actions

---

robottelo/cli/base.py

Backport of https://github.com/SatelliteQE/robottelo/pull/9283

Fixing hostname execute order on 6.10

---

tests/foreman/installer/test_installer.py

Update assignee for installer tests

---

tests/foreman/installer/test_installer.py

1. Add timeout to satellite-installer commands
2. Remove deprecated tomcat6 check for installer services tests, also included missing `pulpcore-worker@*.service`
3. Remove invalid bz from test metadata, will automate that in separate PR.

Fix installer tests for 6.10.z

---

tests/foreman/cli/test_remoteexecution.py

[6.10] fix in rex alternate dir test

---

.github/workflows/merge_to_master.yml
.github/workflows/pull_request.yml

This will actually allow for calls that check authentication against the bugzilla api
Hi
Cherry-pick from
https://github.com/SatelliteQE/robottelo/pull/9721

[Cherrypick] Add bugzilla key to pull request and merge actions

---

tests/foreman/api/test_errata.py
tests/foreman/cli/test_errata.py
tests/foreman/ui/test_errata.py
tests/upgrades/test_errata.py

[6.10.z]Errata component Ownership

---

tests/foreman/api/test_errata.py
tests/foreman/cli/test_errata.py
tests/foreman/ui/test_errata.py
tests/upgrades/test_errata.py

Errata management component ownership

Errata management component ownership

---

robottelo/hosts.py
tests/foreman/cli/test_puppetplugin.py

In 6.11 puppet-agent is delivered via Satellite-Client repo. This test just exercise it's install, configuration and run on a content host.

Add a test for puppet-agent install/config/run

---

tests/foreman/api/test_template.py
tests/foreman/api/test_template_combination.py
tests/foreman/cli/test_provisioning.py
tests/foreman/cli/test_template.py
tests/foreman/ui/test_provisioningtemplate.py

Component Ownership for provisioning tests

Update assignee for provisioning tests

---

robottelo/hosts.py

Didn't manage to address @mshriver 's comment https://github.com/SatelliteQE/robottelo/pull/9715#discussion_r912024683 in time, updating now.

Unclunking one-liner

---

tests/foreman/ui/test_contenthost.py

Hello
A lot of changes where made to this test during refactoring exercises  and it stopped working. After consulting with @omkarkhatavkar , who wrote the original, I have simplified it.
Thank you

Fix test_content_access_after_stopped_foreman

---

tests/foreman/ui/test_computeresource.py

Another instance of https://github.com/SatelliteQE/robottelo/pull/9454

Memory in MB

---

pytest_fixtures/core/broker.py
robottelo/constants/__init__.py
robottelo/hosts.py

Backport of PR#9681 into 6.10.z

[backport] Install capsule using  CDN repos

---

tests/foreman/ui/test_repository.py

Added test to Verify Content Checksum from the product page. Do not merge until airgun PR is merged 
https://github.com/SatelliteQE/airgun/pull/721

Test for Verifying Checksum

---

tests/foreman/api/test_webhook.py

Creating a new file and some initial tests for Webhooks API testing. 
Depends on: https://github.com/SatelliteQE/nailgun/pull/834

Adding Webhooks API tests

---

.github/workflows/auto_cherry_pick.yml
.github/workflows/required_labels.yml
tests/foreman/ui/test_contentview.py

CherryPicking Commits:
8752c886b03a0fe28e2ea0ad80aecadc1b35a765 15b97a6ecd3818fa40d04dcea55a6307e8ba4063 ddf4f05585c2faab0a07c999ca6ccc302025b701 0737cc75219ae7b4f7e1d5c3767f364d203281b8 4a025e18af3f1e7c6a8e17124f66629dcd0fb6dd

[6.10.z] Missing CherryPicks due to AutoCherryPick Issue

---

tests/foreman/cli/test_bootstrap_script.py
tests/foreman/cli/test_registration.py

Changing ownership of tests over to me now that I own these components

Change bootstrap and registration tests to sbible

---

.github/workflows/auto_cherry_pick.yml

Fixing permission issue with pull_request_target event

---

tests/foreman/ui/test_webhook.py

Basic UI testing of Webhooks CRUD functionality. Depends on https://github.com/SatelliteQE/airgun/pull/723

Adding UI Webhook tests

---

.github/workflows/auto_cherry_pick.yml

Removing job level permissions to use global

---

.github/workflows/auto_cherry_pick.yml

4eb9f85ff9258869d094208d1b59c2acd2575cbb 8bead63cba08cb3a8bd333ae1b171030c879092b 091005516ecc1db899d3350e20aec1e0301d0794

CherryPick all missing fixes of ACP GHA

---

tests/foreman/ui/test_contentview.py

Writing automation for a closed loop bz: bz 2032098.
Result:
```
pytest tests/foreman/ui/test_contentview.py -k test_positive_inc_publish_cv
====== 1 passed, 77 deselected, 3 warnings in 254.06s (0:04:14) ========
```

Automation for bz-2032098

---

tests/foreman/api/test_syncplan.py
tests/foreman/cli/test_syncplan.py
tests/foreman/ui/test_syncplan.py
tests/upgrades/test_syncplan.py

Finishing up changing ownership of @swadeley components over to me

Change ownership of syncplans to sbible

---

tests/foreman/ui/test_organization.py

Fixed fixture scope of few tests which were failing because of scope conflicts.

Fixed fixture scope

---

tests/foreman/ui/test_computeresource_vmware.py

This is what is actually done in Satellite

Round correctly, i.e. to 2 significant digits

---

tests/foreman/destructive/test_rename.py

This PR adds an /etc/hosts entry to pass s-c-h post-rename validation, negative tests now check for hostname initially

fixes in satellite-change-hostname tests

---

robottelo/constants/__init__.py

See failures in production and can't get a reproducer locally.

Adding and testing new roles

---

tests/foreman/ui/test_remoteexecution.py

Previously the check for rex jobs on dashboard expected just a single job to be listed, the test is now adjusted

fixed rex dashboard check

---

tests/foreman/installer/test_installer.py

Remove deprecated tomcat6 service from installer tests, which is unique to EL6 and lower
```
(.robottelo) ➜  robottelo git:(installer-fix-el6) ✗ pytest -q --disable-pytest-warnings tests/foreman/installer/test_installer.py -k test_positive_check_installer_services
/Users/gtalreja/sat_workspace/robottelo/.robottelo/lib/python3.8/site-packages/pytest_ibutsu/modeling.py:119: DeprecationWarning: _ibutsu["metadata"] will be deprecated in 3.0. Please use a corresponding TestRun field.
warnings.warn(
.                                                                                                                                 [100%]
1 passed, 14 deselected, 3 warnings in 25.47s
```

Remove deprecated tomcat6 service from installer tests

---

tests/foreman/api/test_contentmanagement.py
tests/foreman/ui/test_rhcloud_insights.py

Minor test fix -[ Rhcloud insights] 
**Test results**
```
pytest tests/foreman/ui/test_rhcloud_insights.py -k test_host_details_page
platform linux -- Python 3.8.6, pytest-7.1.2, pluggy-1.0.0
plugins: services-2.2.1, mock-3.7.0, forked-1.3.0, cov-3.0.0, xdist-2.5.0, ibutsu-2.2.2, reportportal-5.1.2
collected 10 items / 9 deselected / 1 selected …
```

[UI] - Minor test fixes

---

tests/foreman/cli/test_activationkey.py
tests/foreman/ui/test_activationkey.py

Adding coverage for this candlepin bz.  Will post test results later.

Automation for bz-2038388

---

robottelo/constants/__init__.py

After branching, we need to make sure we're falling back to the correct version.

Update the Sat version fallback to 6.12

---

requirements.txt

satellite-upgrade will also need to be updated, but will wait for Lukas for that.

[6.11.z] Update nailgun and airgun requirements to point to 6.11.z branches

---

tests/foreman/cli/test_remoteexecution.py
tests/foreman/destructive/test_remoteexecution.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_jobinvocation.py
tests/foreman/ui/test_jobtemplate.py
tests/foreman/ui/test_remoteexecution.py

Adjusting to terminology change in 6.12, also shifting focus to rhel8 hosts

SSH provider renamed to Script

---

tests/upgrades/test_yum_plugins.py

Easy fix: Updated an error string discussed in PR [9858](https://github.com/SatelliteQE/robottelo/pull/9858#discussion_r935591109)

Constant cleanup

---

tests/foreman/ui/test_dashboard.py

Depends on: SatelliteQE/airgun/pull/731

Fix tasks pagination issue

---

pytest_fixtures/component/maintain.py
pytest_fixtures/component/rh_cloud.py
robottelo/hosts.py
tests/foreman/destructive/test_ldap_authentication.py
tests/foreman/ui/test_ldap_authentication.py

Influenced by https://github.com/SatelliteQE/robottelo/pull/9782#discussion_r929434758 in PR #9782 and forgot that SFTP get wont work with HTTP get.
Adding a new `download_file` from the existing code itself without brainstorming much on its improvement  https://github.com/SatelliteQE/robottelo/pull/9782/commits/a6d8f55a11e3f88d4f4c3a9e412905b9bdc446b6#diff-825c5b0e0eb8cd7eeda6528dcbe21f2de66967c2ca7e60ab281cc56d46e9aa45L96-L143 , but that works as expected !
Some tests are failing in CI so this is bit urgent !!!!!!!!

Fixed file downloading by avoiding SFTP

---

tests/foreman/ui/test_branding.py

Updated Assignee name for Branding Component

Updated Assignee name for branding component

---

tests/foreman/ui/test_host.py
tests/foreman/ui/test_jobinvocation.py

Seems like this is the right place to add these test cases. Added myself as assignee since the rest of this file belongs to @tstrych 
If this doesn't make sense, I'm happy to split them out into a seperate file.

Stubbing the host Ansible tests

---

pytest_fixtures/component/satellite_auth.py
robottelo/api/utils.py
robottelo/rhsso_utils.py
tests/foreman/destructive/test_ldap_authentication.py
tests/foreman/destructive/test_ldapauthsource.py

cherry pick 3ff5c06eb22d218d14d63788d6fd54f0b56767bb
[ fixed the auth tests for RHSSO #9900 ](https://github.com/SatelliteQE/robottelo/pull/9900)

fixed the auth tests for RHSSO

---

robottelo/constants/repos.py
tests/foreman/api/test_repository.py
tests/foreman/cli/test_repository.py
tests/foreman/ui/test_repository.py

Automating a closed loop [bz: 2024889](https://bugzilla.redhat.com/show_bug.cgi?id=2024889).  Waitng for #9798 to be merged first.

Automation for bz-2024889

---

tests/foreman/api/test_repository.py

New customer scenario for testing contents_changed after repo sync

Test for checking null contents_changed after repo sync

---

requirements.txt
robottelo/api/utils.py
tests/foreman/api/test_environment.py
tests/foreman/api/test_smartproxy.py
tests/robottelo/test_api_utils.py

The use of Inflector here was overkill for what we needed.
I replace the calls with the result of the calls and removed the dependency and unit test.

Remove Inflector dependency

---

conf/supportability.yaml

This reverts commit 7307333ae65932dd0f3238fae265e87bbba7cbe3.

RHEL9 template is available again

---

tests/foreman/cli/test_remoteexecution.py

Long, winding road for a really short drink of water
Thanks @synkd for the indepth debugging help

Use subscription-manager refresh

---

tests/foreman/cli/test_satellitesync.py

Adding docstring to already existing test case that covers https://bugzilla.redhat.com/show_bug.cgi?id=1944733

Add docstring coverage for bz-1944733

---

tests/foreman/cli/test_satellitesync.py

Add coverage docstring for existing automation coverage: https://bugzilla.redhat.com/show_bug.cgi?id=1995827

Docstring for automation coverage for bz-1995827

---

tests/foreman/api/test_location.py
tests/foreman/ui/test_settings.py

Test Failure fixes: 
1. ui.test_settings.py:test_positive_update_email_delivery_method_sendmail
2. api.test_location.py --> Removed Environment while creating entity

Fixes for test failures

---

tests/foreman/ui/test_branding.py
tests/foreman/ui/test_settings.py

For best results run with https://github.com/SatelliteQE/airgun/pull/738
```
Test result :
pytest tests/foreman/ui/test_settings.py -k test_positive_update_login_page_footer_text_with_long_and_empty_string
platform linux -- Python 3.8.6, pytest-7.1.2, pluggy-1.0.0
plugins: services-2.2.1, mock-3.7.0, forked-1.3.0, cov-3.0.0, xdist-2.5.0, ibutsu-2.2.2, reportportal-5.1.2
collected 16 items / 15 deselected / 1 selected …
```

Improvising tests & also aims feature automation

---

tests/foreman/ui/test_host.py

~~Depends on: SatelliteQE/airgun/pull/720~~

Automate tests for new UI content tab

---

robottelo/constants/__init__.py

Updating the LOCALES constant as the test is failing for `test_positive_update_all_locales` in cli/test_user.py

Update LOCALES Constant

---

tests/foreman/cli/test_remoteexecution.py

Closes #9985
Removed an unused fixture and moved a heavily used assertion pattern to a function

rex cli slight refactor

---

tests/foreman/api/test_contentmanagement.py

until a newly reported BZ#2121583 is resolved.

Skip Ansible Collection sync to Caps test

---

pytest_fixtures/component/satellite_auth.py
tests/foreman/destructive/test_ldap_authentication.py

Proposed changes:
- moved the setup to the fixture completely
- added `--membership-software=samba` in enroll_ad fixture
- added changes in sssd.conf and auth_gssapi.conf per other discussion with DEVs

Make the AD tests work again

---

tests/foreman/ui/test_host.py

Depends on: SatelliteQE/airgun/pull/742

Add test for new host UI integration with rex

---

tests/foreman/api/test_location.py
tests/foreman/api/test_operatingsystem.py
tests/upgrades/test_activation_key.py

Replace entities with sat object.

Replace entities with sat object

---

tests/foreman/api/test_provisioning.py

Changing Job template search query for 6.12

Provisioning test fix

---

tests/foreman/ui/test_hardwaremodel.py

Fix typo in HW model test

---

.github/workflows/auto_cherry_pick.yml

- Adds `auto-cherrpicked` branch label to the auto cherrypicked PR.

Adding branch label to the auto cherrypicked PR

---

pytest_fixtures/component/subscription.py
pytest_fixtures/core/sys.py
tests/foreman/destructive/test_host.py

- Depends on https://github.com/SatelliteQE/airgun/pull/743

Add rhel repos before installing cockpit

---

.github/workflows/auto_cherry_pick.yml
.github/workflows/merge_to_master.yml
.github/workflows/pull_request.yml
.github/workflows/weekly.yml
pytest_fixtures/component/subscription.py
pytest_fixtures/core/sys.py
robottelo/cli/factory.py
robottelo/host_helpers/cli_factory.py
tests/foreman/cli/test_ping.py
tests/foreman/destructive/test_host.py

Cherrypick of following commits missed in ACP GHA due to the issue and fix PR #10044 !
Refer: https://github.com/SatelliteQE/robottelo/actions/workflows/auto_cherry_pick.yml
880af86dd34e516d2ec9cbccef984c16dc8a3023 0ed808615d045eaa0bb9b1df18ad011ea2588300 a8110bc3850181d6294234bb5015afb1e4e62305 0dc8256f94039f83d65263d25ccf4cada5aacf87 cb05b3f41ff33e0751f42a1ca096159d23daa0f0 5b12e6ab17746dbb4eca296ac6af50570eae0870

[6.11.z] Failed Auto Cherrypicks in 6.11.z due to ACP GHA issue

---

pytest_fixtures/core/contenthosts.py

I have changed "use_containers" to "no_containers" in contenhosts.py

Changed use_containers to no_containers in contenhosts.py

---

tests/foreman/ui/test_host.py

- Requires: SatelliteQE/airgun/pull/756

Use table for recent jobs instead of list

---

conf/rh_cloud.yaml.template
conftest.py
robottelo/constants/__init__.py
tests/foreman/ui/test_remoteexecution.py
tests/foreman/ui/test_rhc.py

This is a cherry-pick pr for:
- https://github.com/SatelliteQE/robottelo/pull/9780
- https://github.com/SatelliteQE/robottelo/pull/10072

[Manual cherry-pick] Add setup for iqe remediation tests.

---

tests/foreman/ui/test_repository.py

Automation coverage for https://bugzilla.redhat.com/show_bug.cgi?id=1973329.
I still need to add `rhel8_baseos` as another repo to the test case, but the implementation is a bit tricky.  If I can't figure it out, I may skip it.

Automation coverage for bz-1973329

---

robottelo/host_helpers/contenthost_mixins.py

This feature has been requested in the following discussions:
* https://github.com/SatelliteQE/robottelo/pull/9986#discussion_r961925131
* https://github.com/SatelliteQE/robottelo/pull/9986#discussion_r952389184
* https://github.com/SatelliteQE/robottelo/pull/10033/files#r968362516

Give users greater control over dogfood_repofile

---

tests/foreman/api/test_contentview.py

pytest: tests/foreman/api/test_contentview.py

API cv promote takes in dict for its parameter to promote to an lce

---

pytest_fixtures/component/satellite_auth.py
robottelo/rhsso_utils.py
robottelo/utils/issue_handlers/bugzilla.py
tests/foreman/destructive/test_katello_certs_check.py
tests/foreman/destructive/test_ldap_authentication.py
tests/foreman/sys/test_katello_certs_check.py

rhsso tests for RHEL8 and certificate tests

fixed: rhsso tests for RHEL8 and certificate tests

---

tests/foreman/api/test_errata.py
tests/foreman/ui/test_errata.py

```
With better results run with https://github.com/SatelliteQE/airgun/pull/754/
Attempts to fix:
test_positive_view_cve
test_positive_get_count_for_host
test_positive_get_applicable_for_host
test_content_host_errata_page_pagination
test_end_to_end
test_positive_apply_for_all_hosts
```

Test fixes for errata

---

robottelo/host_helpers/contenthost_mixins.py

This will fix the https://github.com/SatelliteQE/robottelo/issues/10141

fix 10141: release can be float but needs casting to string object

---

pytest_fixtures/component/satellite_auth.py

[6.11.z] Fix resolv.conf hacking for AD setup

---

robottelo/hosts.py
tests/foreman/destructive/test_puppetplugin.py

[6.11.z] Fix puppet configure test

---

tests/foreman/cli/test_remoteexecution.py

few more tests not relying on rex_contenthost needed no_containers tag

adding no_contaiers tags for a couple of rex tests

---

pytest_fixtures/core/broker.py
robottelo/hosts.py
tests/foreman/cli/test_remoteexecution.py

fixes #10081 currently skipped on BZ:2128209

async ssh rex provider test

---

tests/foreman/ui/test_computeresource.py

Just as https://github.com/SatelliteQE/robottelo/pull/10109

Cluster instead of datacenter. Used to work when those were equal.

---

tests/foreman/destructive/test_clone.py

sat-clone: Enable modules on RHEL 8+

---

pytest_fixtures/component/satellite_auth.py
robottelo/rhsso_utils.py
tests/foreman/destructive/test_ldap_authentication.py

[6.11.z] Fix RHSSO multi-group test

---

pytest_fixtures/core/broker.py

the current implementation was causing runtime errors since the loop was messing with the dict keys

fix runtime error introduced by 884fb93

---

pytest_fixtures/component/satellite_auth.py

Use another user for IDM tests

---

pytest_fixtures/component/satellite_auth.py

[6.11.z] Use another user for IDM tests (#10177)

---

tests/foreman/api/test_ldapauthsource.py
tests/foreman/cli/test_auth.py
tests/foreman/cli/test_ldapauthsource.py
tests/foreman/cli/test_sso.py
tests/foreman/destructive/test_auth.py
tests/foreman/destructive/test_ldap_authentication.py
tests/foreman/destructive/test_ldapauthsource.py
tests/foreman/ui/test_ldap_authentication.py

Cherrypick of commit: 4a2e72aa1042b3f5e8f26b1c4dbd86c2c5b35b59
null

[6.11.z] Take over the LDAP and Auth components

---

tests/foreman/cli/test_host.py
tests/foreman/ui/test_host.py

[6.11] [Cherry-pick] Fix fake yum on rhel6 

---

tests/foreman/ui/test_hostgroup.py

Added the test coverage for the clone host group as [bz 2122261](https://bugzilla.redhat.com/show_bug.cgi?id=2122261)
Airgun PR :  https://github.com/SatelliteQE/airgun/pull/773
```
Launching pytest with arguments -k test_positive_clone_host_groups /Users/okhatavk/satellite/robottelo/tests/foreman/ui/test_hostgroup.py --no-header --no-summary -q in /Users/okhatavk/satellite/robottelo
collecting ... collected 7 items / 6 deselected / 1 selected
tests/foreman/ui/test_hostgroup.py::test_positive_clone_host_groups 
=========== 1 passed, 6 deselected, 25 warnings in 246.58s (0:04:06) ===========
```

added test coverage for clone host-group

---

tests/foreman/api/test_contentmanagement.py

A test to sync a CV to multiple LCEs.

Closed loop BZ#1830403

---

tests/foreman/cli/test_remoteexecution.py

cherry pick of https://github.com/SatelliteQE/robottelo/pull/10159

fixing KeyError in parametrized fixture

---

tests/foreman/ui/test_hostgroup.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10190
Added the test coverage for the clone host group as [bz 2122261](https://bugzilla.redhat.com/show_bug.cgi?id=2122261)
Airgun PR :  https://github.com/SatelliteQE/airgun/pull/773
```
Launching pytest with arguments -k test_positive_clone_host_groups /Users/okhatavk/satellite/robottelo/tests/foreman/ui/test_hostgroup.py --no-header --no-summary -q in /Users/okhatavk/satellite/robottelo
collecting ... collected 7 items / 6 deselected / 1 selected
tests/foreman/ui/test_hostgroup.py::test_positive_clone_host_groups 
=========== 1 passed, 6 deselected, 25 warnings in 246.58s (0:04:06) ===========
```

[6.11.z] added test coverage for clone host-group

---

tests/foreman/ui/test_provisioningtemplate.py

Dependent Airgun PR: https://github.com/SatelliteQE/airgun/pull/774

Test fix for e2e provisioning_template test

---

.github/workflows/auto_cherry_pick.yml

I have created the sample POC with issue structure here https://github.com/omkarkhatavkar/github-action-test-repo/issues/9

GHA: Added support to handle auto-cherry-pick failure & create issue

---

tests/foreman/ui/test_provisioningtemplate.py

Cherrypick of commit: 281729e5516c05e3115cb5900b616f18fbd4d8bf
Dependent Airgun PR: https://github.com/SatelliteQE/airgun/pull/774

[6.11.z] Test fix for e2e provisioning_template test

---

tests/foreman/cli/test_contentaccess.py
tests/foreman/destructive/test_contenthost.py
tests/foreman/longrun/test_inc_updates.py
tests/foreman/ui/test_contenthost.py
tests/upgrades/test_client.py
tests/upgrades/test_hostcontent.py

Ownership updated for Host-Content

Host content ownership

---

requirements.txt
robottelo/hosts.py

This PR should be merged after the above Broker PR has been merged.
This update's the version and the name of an attribute we need to keep.
Note: Checks won't pass until the new version of Broker is released.

Companion to Broker #170

---

tests/foreman/api/test_rhcloud_inventory.py
tests/foreman/cli/test_rhcloud_inventory.py

**Test result**
```
pytest tests/foreman/cli/test_rhcloud_inventory.py -k test_positive_generate_all_reports_job
platform linux -- Python 3.8.6, pytest-7.1.3, pluggy-1.0.0
plugins: forked-1.4.0, services-2.2.1, cov-3.0.0, xdist-2.5.0, ibutsu-2.2.4, reportportal-5.1.2, mock-3.10.0
collected 7 items / 6 deselected / 1 selected                                                                                                                               
tests/foreman/cli/test_rhcloud_inventory.py . …
```

Close loop BZ_2110163

---

requirements.txt
robottelo/hosts.py

Cherrypick of commit: dd9a78c883cf3d3d36bc44db63fdd930fecd3786
This PR should be merged after the above Broker PR has been merged.
This update's the version and the name of an attribute we need to keep.
Note: Checks won't pass until the new version of Broker is released.

[6.11.z] Companion to Broker #170

---

.github/workflows/auto_assignment.yaml
.github/workflows/auto_cherry_pick.yml
.github/workflows/pull_request.yml

fix the broken create issue with adding needs

fix the broken create issue with adding needs

---

tests/foreman/api/test_remoteexecution.py

pr fixes an assertion in test_positive_run_capsule_upgrade_playbook

assertion fix in capsule upgrade test

---

.github/workflows/auto_cherry_pick.yml

Fix the issue of GHA of `create_issue` failing with error `sequence not expected`.

Fix Create Issue failing for sequence not expected

---

tests/foreman/api/test_remoteexecution.py

Cherrypick of commit: f679049a7cb9da7e60434d1230f70badbbea53db
pr fixes an assertion in test_positive_run_capsule_upgrade_playbook

[6.11.z] assertion fix in capsule upgrade test

---

robottelo/host_helpers/contenthost_mixins.py
robottelo/hosts.py
robottelo/upgrade_utility.py
tests/upgrades/test_repository.py

Currently, open for review as POC to port all upgrade scenarios as done in this PR.
Here are the facts and Considerations considered for the porting effort:
- Upgrade_utiliity helpers are mostly being used in upgrade scenarios.
- Upgrade Scenarios are using helpers from upgrade repo and the upgrade_utility module helpers are supporting to upgrade repo helpers as an additional help.
- All upgrade scenarios container content host test cases can be ported to use new container host from broker.
- Use ContentHost class methods to replace the helpers from upgrade repo that does post registration utilities on content host.
- Port required / remaining upgrade_utility.py helpers in ContentHost class to be used for upgrade scenarios, etc.
- Aligns with our upgrade future improvement plan for …

[POC] Upgrade Scenarios moving to use broker container hosts object and its methods

---

.github/auto_assign.yml
.github/workflows/auto_assignment.yml
.github/workflows/auto_cherry_pick.yml

Cherry pick 10241 and fixed the needs

Cherry pick 10241 and fixed the needs 

---

pytest_fixtures/component/rh_cloud.py
tests/foreman/ui/test_rhcloud_insights.py

```
pytest tests/foreman/ui/test_rhcloud_insights.py -k test_insights_registration_with_capsule
collected 11 items / 10 deselected / 1 selected                                                                                                                                                                   
tests/foreman/ui/test_rhcloud_insights.py .                                                                                                                                                                 [100%] …
```

Rhcloud plugin integration tests with capsule

---

robottelo/host_helpers/contenthost_mixins.py
robottelo/hosts.py
tests/upgrades/test_repository.py

Cherrypick of PRs:
- https://github.com/SatelliteQE/robottelo/pull/10274 
- https://github.com/SatelliteQE/robottelo/pull/10119 
Fixes https://github.com/SatelliteQE/robottelo/issues/10284, https://github.com/SatelliteQE/robottelo/issues/10275

Missing Cherrypicks for upgrade scenario and ACP GHA fixes

---

tests/foreman/cli/test_contentaccess.py
tests/foreman/longrun/test_inc_updates.py
tests/foreman/ui/test_contenthost.py
tests/upgrades/test_client.py

Manual Cherrypick for : https://github.com/SatelliteQE/robottelo/pull/10235

[6.10.z cherrypick] Host content ownership

---

pytest_fixtures/component/maintain.py
pytest_fixtures/core/broker.py
pytest_plugins/fixture_markers.py
pytest_plugins/markers.py
robottelo/cli/base.py
robottelo/cli/sm_upgrade.py
robottelo/hosts.py
tests/foreman/maintain/test_upgrade.py

CherryPick of https://github.com/SatelliteQE/robottelo/pull/10227
Fixes #10300

[6.11.z] Add f-m upgrade tests to robottelo with capsule parametrization

---

tests/foreman/api/test_errata.py
tests/foreman/api/test_rhcloud_inventory.py
tests/foreman/cli/test_errata.py
tests/foreman/cli/test_rhcloud_inventory.py

`Added e2e markers for Errata and Rhcloud plugin.`
Signed-off-by: Adarsh Dubey <addubey@redhat.com>

Adding e2e markers

---

tests/foreman/cli/test_hammer.py

1. Adding automation coverage for [BZ 2053843](https://bugzilla.redhat.com/show_bug.cgi?id=2053843),
2. Some fixes to use target_sat's cli/cli_factory
3. Using request.addfinalizer instead of try-finally blocks
```
(.robottelo) ➜  robottelo git:(hammer-shell) ✗ pytest -q --disable-pytest-warnings tests/foreman/cli/test_hammer.py -k test_positive_hammer_shell
.                                                                                                                                                     [100%]
1 passed, 3 deselected, 2 warnings in 38.74s
```

Automation coverage for BZ 2053843

---

tests/foreman/cli/test_hammer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10310
1. Adding automation coverage for [BZ 2053843](https://bugzilla.redhat.com/show_bug.cgi?id=2053843),
2. Some fixes to use target_sat's cli/cli_factory
3. Using request.addfinalizer instead of try-finally blocks
```
(.robottelo) ➜  robottelo git:(hammer-shell) ✗ pytest -q --disable-pytest-warnings tests/foreman/cli/test_hammer.py -k test_positive_hammer_shell
.                                                                                                                                                     [100%]
1 passed, 3 deselected, 2 warnings in 38.74s
```

[6.11.z] Automation coverage for BZ 2053843

---

robottelo/cli/sm_service.py
robottelo/constants/__init__.py
tests/foreman/maintain/test_service.py

Cherrypick of https://github.com/SatelliteQE/robottelo/pull/10231
Fixes https://github.com/SatelliteQE/robottelo/issues/10307
(cherry picked from commit 5f34d4dd2ef1904d47f45875bc8660e53ee69b54)

[6.11.z] Port/refactor of f-m service tests from testfm

---

.github/workflows/auto_assignment.yaml
.github/workflows/auto_cherry_pick.yml

This will copy the PRT comment from the Parent PR to cherrypick PR. 
https://github.com/jyejare/github-cherry-pick-action/pull/7
https://github.com/omkarkhatavkar/google-chat-notification/pull/1

[GHA]:Added support to copy the PRT comment in auto-cherry-pick pr's

---

.github/workflows/auto_cherry_pick.yml

missed the correct branch name

fix the google chat using right branch master

---

.github/workflows/stale.yml

- Warns on Issue and PRs for stale
- Closes the issues and PRs after stale warnings
Please check config file for more details.

Warn and Close Stale Issues and PRs

---

.github/workflows/auto_cherry_pick.yml

resolves https://github.com/SatelliteQE/robottelo/issues/10323

[cherrypick fix] [GHA]:Added support to copy the PRT comment in auto-cherry-pick pr's

---

tests/foreman/ui/test_reporttemplates.py

https://bugzilla.redhat.com/show_bug.cgi?id=2109421

Make sure postfix is running

---

Makefile
pytest_fixtures/component/maintain.py
robottelo/cli/sm_advanced.py
robottelo/cli/sm_advanced_by_tag.py
robottelo/hosts.py
tests/foreman/maintain/test_advanced.py
tests/foreman/maintain/test_backup_restore.py
tests/foreman/maintain/test_service.py
tests/foreman/maintain/test_upgrade.py

1. Port/refactor f-m advanced subcommand tests from TestFM to robottelo
https://github.com/SatelliteQE/testfm/blob/master/tests/test_advanced.py
It includes changes from https://github.com/SatelliteQE/robottelo/pull/10227, and it will be rebased when either PR is merged

Port/refactor of f-m advanced tests from testfm

---

conf/rh_cloud.yaml.template
tests/foreman/ui/test_rhc.py

Fixes #10352  - [cherry-pick] skip manifest import when running test against stage env

---

Makefile
pytest_fixtures/component/maintain.py
robottelo/cli/sm_advanced.py
robottelo/cli/sm_advanced_by_tag.py
tests/foreman/maintain/test_advanced.py
tests/foreman/maintain/test_backup_restore.py
tests/foreman/maintain/test_service.py
tests/foreman/maintain/test_upgrade.py

cherrypick of https://github.com/SatelliteQE/robottelo/pull/10242
(cherry picked from commit 101084cfe66d51b0e150a5f68c3f1b473db3c514)

[6.11.z] Port/refactor of f-m advanced tests from testfm

---

.github/workflows/auto_assignment.yaml
.github/workflows/auto_cherry_pick.yml

https://github.com/omkarkhatavkar/google-chat-notification/pull/2/files

updating the bot user to satqe bot

---

.github/workflows/auto_assignment.yml
.github/workflows/auto_cherry_pick.yml

cherry-pick for PR #10357

---

tests/foreman/ui/test_host.py

- depends on SatelliteQE/airgun/pull/770

Add test for repo sets in new host details ui

---

robottelo/host_helpers/contenthost_mixins.py
robottelo/hosts.py
robottelo/utils/ohsnap.py
scripts/vault_login.py

[cherry-pick 6.11] Ohsnap repositories

---

pytest_fixtures/component/maintain.py
robottelo/hosts.py
tests/foreman/maintain/test_backup_restore.py

Adding parametrization of the f-m backup/restore tests to be run against the Capsule as well.

Parametrize backup/restore tests to run on capsule

---

tests/foreman/maintain/test_backup_restore.py
tests/foreman/maintain/test_maintenance_mode.py

Manually cherrypicked #10246
(cherry picked from commit 6774aceab12b29928598b6da43207654c54f2e05)

[6.11.z] Port/refactor of f-m maintenance-mode tests from testfm

---

pytest_fixtures/component/provision_pxe.py
robottelo/constants/__init__.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_provisioning.py

This PR modifies the pxeloader parametrization PR (https://github.com/SatelliteQE/robottelo/pull/10237)

Fix pxeloader parametrization

---

robottelo/cli/hammer.py
tests/foreman/cli/test_hammer.py
tests/foreman/data/hammer_commands.json

1. Update hammer-cli options for 6.12 in hammer_commands.json, generated from running `scripts/hammer_command_tree.py`, which are confirmed with devs and upstream PRs already
2. Fixing parse_help helper to run help on diff commands/subcommands, which caused above script to generate nothing
```
(.robottelo) ➜  robottelo git:(fix-hammer-options612) ✗ pytest -q --disable-pytest-warnings tests/foreman/cli/test_hammer.py -k test_positive_all_options
.                                                                                                                                            [100%]
1 passed, 3 deselected, 3 warnings in 28.56s
```
**Confirmed added/removed commands/options with the following upstream PR's included in the 6.12**
ACS - 6.12 feature …

Update hammer-cli options test for 6.12

---

tests/foreman/ui/test_rhc.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10382
null

[6.11.z] Search for organization when running test against stage env

---

pytest_fixtures/component/maintain.py
tests/foreman/maintain/test_backup_restore.py

Manual cherry-pick of #10348 
Fixes #10373

[6.11.z] Parametrize backup/restore tests to run on capsule

---

tests/foreman/maintain/test_advanced.py
tests/foreman/maintain/test_health.py

based on bot's suggestions, closes #10355

customerscenario tags added to maintain tests

---

tests/foreman/maintain/test_advanced.py
tests/foreman/maintain/test_health.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10376
based on bot's suggestions, closes #10355

[6.11.z] customerscenario tags added to maintain tests

---

tests/upgrades/test_client.py

Host-Content Cleanup:
1. Update some fixtures and remove some duplicate fixtures created in this module
2. Replace entities.

Content host test cleanup

---

tests/upgrades/test_client.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10245
Host-Content Cleanup:
1. Update some fixtures and remove some duplicate fixtures created in this module
2. Replace entities.

[6.11.z] Content host test cleanup

---

.pre-commit-config.yaml
pytest_fixtures/component/satellite_auth.py
tests/foreman/api/test_contentmanagement.py
tests/foreman/api/test_reporttemplates.py
tests/foreman/cli/test_satellitesync.py
tests/foreman/installer/test_installer.py
tests/foreman/maintain/test_health.py
tests/upgrades/test_activation_key.py
tests/upgrades/test_syncplan.py

[6.11.z] Update URL of flake8 repo, bump version Fixes #10400

---

robottelo/hosts.py
tests/foreman/destructive/test_remoteexecution.py

making sure host is registered to the destructive satellite

fix in alternate directory rex test

---

tests/foreman/destructive/test_leapp_satellite.py

Added assert for satellite's health

Fix leapp test

---

robottelo/hosts.py
tests/foreman/destructive/test_remoteexecution.py

[6.11.z] fix in alternate directory rex test

---

conf/robottelo.yaml.template
robottelo/constants/__init__.py

Mostly done for waiting for last minute changes if any. The main changes needed from Automation are:
- The version change in robottelo.yaml (Same needed to be done in CI via the environment variables cause now we have 6.13 and 6.14 poininting to the same conf files)
- The version change in constants

Streams/Master Branch changes to target 6.14

---

tests/foreman/destructive/test_leapp_satellite.py

I have added assert to chek if the satellite is ok after upgrading.

Fix for leapp test upgrade

---

tests/foreman/destructive/test_realm.py

this was causing `BoxKeyError` at some of realm tests

fix how realm tests access proxy locations

---

.github/workflows/automerge.yaml

This PR adds support to auto-merge the auto-cherry-pick PRs. This might need PRT Comment and Passing all test checks.   
https://github.com/omkarkhatavkar/github-action-test-repo/pull/111
https://github.com/omkarkhatavkar/github-action-test-repo/actions/runs/3591634233

added support to auto-merge the auto-cherry-pick pr

---

tests/foreman/destructive/test_leapp_satellite.py

[6.13.z] Cherry-pick of #10410 - Fix leapp test

---

tests/foreman/destructive/test_leapp_satellite.py

 [6.12.z] Cherry-pick of #10410 - Fix leapp test 

---

.github/workflows/auto_cherry_pick.yml

* Labelled Cherrypicking
* adding the auto cherry pick merging feature
Co-authored-by: omkarkhatavkar <okhatavkar007@gmail.com>

[6.13.z] Cherrypicking based on branch labels added to the parent PR (#10366)

---

.github/workflows/auto_cherry_pick.yml

* Labelled Cherrypicking
* adding the auto cherry pick merging feature
Co-authored-by: omkarkhatavkar <okhatavkar007@gmail.com>

[6.12.z] Cherrypicking based on branch labels added to the parent PR (#10366)

---

.github/workflows/auto_cherry_pick.yml

* Labelled Cherrypicking
* adding the auto cherry pick merging feature
Co-authored-by: omkarkhatavkar <okhatavkar007@gmail.com>

[6.11.z] Cherrypicking based on branch labels added to the parent PR (#10366)

---

tests/foreman/api/test_remoteexecution.py
tests/foreman/destructive/test_remoteexecution.py

Working around the branding issue in 6.13 to keep capsule upgrade playbook tested

capsule upgrade playbook naming change

---

.github/workflows/auto_cherry_pick.yml

corrected the outputs to number (#10450)

---

.github/workflows/automerge.yaml

fixing the https://github.com/SatelliteQE/robottelo/actions/runs/3740676253
also noticed the auto merging is getting triggered https://github.com/SatelliteQE/robottelo/actions/runs/3740710868 here. so avoiding that trigger

fixing the auto-merge issue

---

.github/workflows/automerge.yaml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10457
fixing the https://github.com/SatelliteQE/robottelo/actions/runs/3740676253
also noticed the auto merging is getting triggered https://github.com/SatelliteQE/robottelo/actions/runs/3740710868 here. so avoiding that trigger

[6.12.z] fixing the auto-merge issue

---

.github/workflows/automerge.yaml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10457
fixing the https://github.com/SatelliteQE/robottelo/actions/runs/3740676253
also noticed the auto merging is getting triggered https://github.com/SatelliteQE/robottelo/actions/runs/3740710868 here. so avoiding that trigger

[6.13.z] fixing the auto-merge issue

---

.github/workflows/automerge.yaml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10457
fixing the https://github.com/SatelliteQE/robottelo/actions/runs/3740676253
also noticed the auto merging is getting triggered https://github.com/SatelliteQE/robottelo/actions/runs/3740710868 here. so avoiding that trigger

[6.11.z] fixing the auto-merge issue

---

tests/foreman/api/test_contentmanagement.py

Passes locally for 6.12.1, the fix needs to be cherry-picked to 6.13.0.

Extend test coverage for BZ#2148813

---

tests/foreman/api/test_contentmanagement.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10442
Passes locally for 6.12.1, the fix needs to be cherry-picked to 6.13.0.

[6.13.z] Extend test coverage for BZ#2148813

---

requirements.txt

Cherry-pick of #10494 and #10472

[6.13.z] Cherry pick of #10472 - Bump cryptography from 38.0.4 to 39.0.0

---

tests/foreman/cli/test_ansible.py
tests/foreman/destructive/test_ansible.py

Close loop: https://bugzilla.redhat.com/show_bug.cgi?id=1786358
Ability to make persistent changes in "ansible.cfg" on Satellite Server.

persistent ansible changes

---

.github/workflows/automerge.yaml

- Added checkpoint for PRT status using Status API 
- Added checkpoint for other check-runs 
- Marking Failure in case any of the above conditions fails. 
- Verbose logs to identify for the owner what has gone wrong.  
https://github.com/omkarkhatavkar/robottelo/actions/runs/3882465855/jobs/6622647642

added the check to wait for PRT status using status API

---

tests/foreman/cli/test_ansible.py
tests/foreman/destructive/test_ansible.py

6.13.z cherrypick: https://github.com/SatelliteQE/robottelo/pull/10525/

[6.13.z Cherrypick] Persistent ansible.cfg change

---

tests/foreman/ui/test_ansible.py

Test results:
```
pytest tests/foreman/ui/test_ansible.py -k test_positive_config_report_ansible
======================================================================================= test session starts =======================================================================================
platform linux -- Python 3.8.6, pytest-7.1.3, pluggy-1.0.0
plugins: forked-1.4.0, services-2.2.1, cov-3.0.0, xdist-3.1.0, ibutsu-2.2.4, reportportal-5.1.3, mock-3.10.0
collected 5 items / 3 deselected / 2 selected …
```

Add coverage for ansible config report

---

requirements.txt

[6.11.z] Bump broker from 0.2.10 to 0.2.11

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10578
Do it

[6.13.z] Update broker to 0.2.12

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10578
Do it

[6.12.z] Update broker to 0.2.12

---

pytest_fixtures/component/provision_gce.py
tests/foreman/api/test_computeresource_gce.py

Some of the test cases will be breaking because of the open BZs just putting a quick fix here.
Directly implies to https://github.com/SatelliteQE/nailgun/pull/886
Signed-off-by: Adarsh Dubey <addubey@redhat.com>

Removing email and project as a part of new GCE feature plugin

---

tests/foreman/sys/test_dynflow.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10611
null

[6.13.z] Update file name and add check for failure. Timeout was checked already.

---

tests/foreman/sys/test_dynflow.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10611
null

[6.12.z] Update file name and add check for failure. Timeout was checked already.

---

tests/foreman/sys/test_dynflow.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10611
null

[6.11.z] Update file name and add check for failure. Timeout was checked already.

---

pytest_fixtures/component/provision_gce.py
tests/foreman/api/test_computeresource_gce.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10571
Some of the test cases will be breaking because of the open BZs just putting a quick fix here.
Directly implies to https://github.com/SatelliteQE/nailgun/pull/887
Signed-off-by: Adarsh Dubey <addubey@redhat.com>

[6.13.z] Removing email and project as a part of new GCE feature plugin

---

pytest_fixtures/component/provision_pxe.py
robottelo/constants/__init__.py
tests/foreman/api/test_discoveredhost.py
tests/foreman/api/test_provisioning.py

Manual cherry-pick of https://github.com/SatelliteQE/robottelo/pull/10273
fixes #10267 and https://github.com/SatelliteQE/robottelo/issues/10380

[ 6.11.z] Parametrization of provisioning test(bios/uefi)

---

pytest_fixtures/component/provision_pxe.py
robottelo/cli/host_registration.py
robottelo/constants/__init__.py
robottelo/hosts.py
tests/foreman/api/test_convert2rhel.py
tests/foreman/api/test_registration.py
tests/foreman/cli/test_registration.py
tests/foreman/cli/test_remoteexecution.py
tests/foreman/destructive/test_remoteexecution.py

Manual cherrypick of #10458
Fixes #10541

[6.13.z] Add e2e tests for Global Registration

---

pytest_fixtures/component/provision_pxe.py
robottelo/cli/host_registration.py
robottelo/constants/__init__.py
robottelo/hosts.py
tests/foreman/api/test_convert2rhel.py
tests/foreman/api/test_registration.py
tests/foreman/cli/test_registration.py
tests/foreman/cli/test_remoteexecution.py
tests/foreman/destructive/test_remoteexecution.py

Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/10458 and https://github.com/SatelliteQE/robottelo/pull/10404
Fixes https://github.com/SatelliteQE/robottelo/issues/10543

[6.12.z] Add e2e tests for Global Registration

---

tests/foreman/data/hammer_commands.json

A bunch of subcommands added to product-content subcommand

6.12 hammer command list updated

---

scripts/config_helpers.py

This change add the ability for the script to merge in changes from another config directiory. This will most likely be used to merge in changes from the upstream config repository.
I also made some optimisations to the existing symlink functionality.

Add merge functionality to config_helpers script

---

tests/foreman/data/hammer_commands.json

Updated commands data to match the reality in 6.13, result: 
```
pytest tests/foreman/cli/test_hammer.py -k test_positive_all_options
=================================================================== test session starts ===================================================================
rootdir: /home/pondrejk/Documents/robottelo, configfile: pyproject.toml
plugins: xdist-3.1.0, services-2.2.1, mock-3.10.0, cov-3.0.0, reportportal-5.1.3, ibutsu-2.2.4
collected 4 items / 3 deselected / 1 selected                                                                                                              …
```

hammer command list updated

---

tests/foreman/cli/test_remoteexecution.py

Adding a couple of asserts to the existing test to check the effective user setting.

test effective user for pull provider jobs

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10669
null

[6.13.z] Update broker to 0.2.13

---

requirements.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10669
null

[6.12.z] Update broker to 0.2.13

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10637
Adding a couple of asserts to the existing test to check the effective user setting.

[6.13.z] test effective user for pull provider jobs

---

requirements.txt

Fixes https://github.com/SatelliteQE/robottelo/issues/10674

Update broker to 0.2.13

---

tests/foreman/endtoend/test_api_endtoend.py

dev approval requested on satellite-dev list, draft state until then

api paths updated for 6.13

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10465
Test results:
```
pytest tests/foreman/ui/test_ansible.py -k test_positive_config_report_ansible
======================================================================================= test session starts =======================================================================================
platform linux -- Python 3.8.6, pytest-7.1.3, pluggy-1.0.0
plugins: forked-1.4.0, services-2.2.1, cov-3.0.0, xdist-3.1.0, ibutsu-2.2.4, reportportal-5.1.3, mock-3.10.0
collected 5 items / 3 deselected / 2 selected …
```

[6.12.z] Add coverage for ansible config report

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10465
Test results:
```
pytest tests/foreman/ui/test_ansible.py -k test_positive_config_report_ansible
======================================================================================= test session starts =======================================================================================
platform linux -- Python 3.8.6, pytest-7.1.3, pluggy-1.0.0
plugins: forked-1.4.0, services-2.2.1, cov-3.0.0, xdist-3.1.0, ibutsu-2.2.4, reportportal-5.1.3, mock-3.10.0
collected 5 items / 3 deselected / 2 selected …
```

[6.13.z] Add coverage for ansible config report

---

tests/foreman/endtoend/test_api_endtoend.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10659
dev approval requested on satellite-dev list, draft state until then

[6.13.z] api paths updated for 6.13

---

robottelo/cli/ansible.py
robottelo/cli/host.py
tests/foreman/api/test_ansible.py
tests/foreman/cli/test_ansible.py
tests/foreman/ui/test_ansible.py

Signed-off-by: Adarsh Dubey <addubey@redhat.com>
(cherry picked from commit 6666afc8f335a9b2e5aca1bf988f64d9ad09f57d)

[6.12.z] - Ansible e2e test coverage - CLI

---

tests/foreman/ui/test_host.py
tests/foreman/ui/test_rhcloud_insights.py

Changes caused by [BZ 2059829](https://bugzilla.redhat.com/show_bug.cgi?id=2059829)
Depends on: Airgun PR https://github.com/SatelliteQE/airgun/pull/802

Updated activation key field in UI for global registration page

---

tests/foreman/api/test_classparameters.py
tests/foreman/api/test_environment.py
tests/foreman/api/test_puppetbootstrap.py
tests/foreman/cli/test_classparameters.py
tests/foreman/cli/test_environment.py
tests/foreman/cli/test_report.py
tests/foreman/destructive/test_puppetplugin.py

1. Mark e2e in Puppet tests and some CaseImportance changes
2. Moved test_positive_install_configure to test_reports

Puppet e2e

---

conf/dynaconf_hooks.py
conf/ohsnap.yaml.template
conf/repos.yaml.template
robottelo/config/validators.py
robottelo/host_helpers/contenthost_mixins.py
robottelo/utils/ohsnap.py
tests/foreman/cli/test_remoteexecution.py

implement retry logic in ohsnap helper methods using wait-for library

[6.12.z] Implement retry logic in ohsnap helper methods using wait-for library

---

conf/dynaconf_hooks.py
conf/ohsnap.yaml.template
conf/repos.yaml.template
robottelo/config/validators.py
robottelo/host_helpers/contenthost_mixins.py
robottelo/utils/ohsnap.py
tests/foreman/api/test_repository.py

implement retry logic in ohsnap helper methods using wait-for library

[6.11.z] Implement retry logic in ohsnap helper methods using wait-for library

---

tests/foreman/ui/test_ansible.py

Test results :
```
pytest tests/foreman/ui/test_ansible.py -k test_positive_ansible_custom_role
collected 7 items / 6 deselected / 1 selected                                                                                                                               
tests/foreman/ui/test_ansible.py . …
```

Coverage for execution of custom role in ansible

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10740
Test results :
```
pytest tests/foreman/ui/test_ansible.py -k test_positive_ansible_custom_role
collected 7 items / 6 deselected / 1 selected …
```

[6.13.z] Coverage for execution of custom role in ansible

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10740
Test results :
```
pytest tests/foreman/ui/test_ansible.py -k test_positive_ansible_custom_role
collected 7 items / 6 deselected / 1 selected …
```

[6.12.z] Coverage for execution of custom role in ansible

---

tests/foreman/cli/test_discoveryrule.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10798
null

[6.13.z] Fix discovery rule priority tests

---

tests/foreman/cli/test_discoveryrule.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10798
null

[6.11.z] Fix discovery rule priority tests

---

tests/foreman/api/test_computeresource_gce.py

A enhancement done on the wrapanapi to incorporate Projects while listing images : https://github.com/RedHatQE/wrapanapi/pull/461
Test result:
```
pytest tests/foreman/api/test_computeresource_gce.py -k test_positive_check_available_images
collected 9 items / 8 deselected / 1 selected …
```

GCE_CR fix for available images

---

tests/foreman/api/test_computeresource_gce.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10765
A enhancement done on the wrapanapi to incorporate Projects while listing images : https://github.com/RedHatQE/wrapanapi/pull/461
Test result:
```
pytest tests/foreman/api/test_computeresource_gce.py -k test_positive_check_available_images
collected 9 items / 8 deselected / 1 …
```

[6.13.z] GCE_CR fix for available images

---

tests/foreman/ui/test_host.py
tests/foreman/ui/test_rhcloud_insights.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10606
Changes caused by [BZ 2059829](https://bugzilla.redhat.com/show_bug.cgi?id=2059829)
Depends on: Airgun PR https://github.com/SatelliteQE/airgun/pull/802

[6.13.z] Updated activation key field in UI for global registration page

---

robottelo/constants/__init__.py
robottelo/host_helpers/satellite_mixins.py
tests/upgrades/test_repository.py

[6.12.z]added upgrade refactor for component Repository

---

tests/foreman/destructive/test_infoblox.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10828
null

[6.13.z] Fix infoblox plugin install tests

---

tests/foreman/destructive/test_infoblox.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10828
null

[6.12.z] Fix infoblox plugin install tests

---

tests/foreman/destructive/test_host.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_ldap_authentication.py

(cherry picked from commit 2c42113735f06d50d4a1ab37ebe99e1cfcf19cfe)
Parent #10883

Change constant to match new letter case in sat 6.13+ (PART2) [6.13.z]

---

tests/foreman/destructive/test_installer.py

This pr adds automation coverage for [RFE#1978995](https://bugzilla.redhat.com/show_bug.cgi?id=1978995) (The satellite-installer should display the mismatched FQDN additionally rather than just showing the commands to verify the output).
Test result:
```
pytest tests/foreman/destructive/test_installer.py -k test_positive_mismatched_satellite_fqdn 
collected 3 items / 2 deselected / 1 selected
tests/foreman/destructive/test_installer.py .                            [100%]
================= 1 passed, 2 deselected, 7 warnings in 25.69s =================
```

Add test_positive_mismatched_satellite_fqdn

---

tests/foreman/ui/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10155
This requires https://github.com/SatelliteQE/nailgun/pull/841 to work properly, as it uses those nailgun endpoints for setup. 
Gonna put this up and get some feedback, and maybe some assistance with some weird behavior I'm seeing. This is using https://github.com/SatelliteQE/airgun/pull/717 as well for Views/Entities.

[6.13.z] Ansible Host Details Test

---

tests/foreman/destructive/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10682
This pr adds automation coverage for [RFE#1978995](https://bugzilla.redhat.com/show_bug.cgi?id=1978995) (The satellite-installer should display the mismatched FQDN additionally rather than just showing the commands to verify the output).
Test result:
```
pytest tests/foreman/destructive/test_installer.py -k test_positive_mismatched_satellite_fqdn 
collected 3 items / 2 deselected / 1 selected
tests/foreman/destructive/test_installer.py .                            [100%]
================= 1 passed, 2 deselected, 7 warnings in 25.69s =================
```

[6.13.z] Add test_positive_mismatched_satellite_fqdn

---

pytest_fixtures/component/contentview.py
pytest_fixtures/component/puppet.py
pytest_fixtures/core/upgrade.py
robottelo/constants/__init__.py
robottelo/host_helpers/__init__.py
robottelo/host_helpers/satellite_mixins.py
tests/foreman/cli/test_satellitesync.py
tests/foreman/destructive/test_puppetplugin.py
tests/upgrades/conftest.py
tests/upgrades/test_bookmarks.py
tests/upgrades/test_classparameter.py
tests/upgrades/test_satellitesync.py

- Upgrade Refactor for class parameter scenarios 
- Use of Class Fixtures 
- Fixing the upgrade scenario test 
```
Launching pytest with arguments -m pre_upgrade /Users/okhatavk/satellite/robottelo/tests/upgrades/test_classparameter.py --no-header --no-summary -q in /Users/okhatavk/satellite/robottelo
collecting ... collected 18 items / 9 deselected / 9 selected
tests/upgrades/test_classparameter.py::TestScenarioPositivePuppetParameterAndDatatypeIntact::test_pre_puppet_class_parameter_data_and_type[1] 
tests/upgrades/test_classparameter.py::TestScenarioPositivePuppetParameterAndDatatypeIntact::test_pre_puppet_class_parameter_data_and_type[2] 
tests/upgrades/test_classparameter.py::TestScenarioPositivePuppetPar …
```

[class_parameter, bookmark, satellite_sync] - Upgrade scenario refactor 

---

tests/upgrades/test_contentview.py

```
/Users/okhatavk/satellite/robottelo/env/bin/python "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/_jb_pytest_runner.py" --path /Users/okhatavk/satellite/robottelo/tests/upgrades/test_contentview.py -- -m post_upgrade
Testing started at 4:45 PM ...
Launching pytest with arguments -m post_upgrade /Users/okhatavk/satellite/robottelo/tests/upgrades/test_contentview.py --no-header --no-summary -q in /Users/okhatavk/satellite/robottelo
collecting ... collected 2 items / 1 deselected / 1 selected
tests/upgrades/test_contentview.py::TestContentView::test_cv_postupgrade_scenario 
============ 1 passed, 1 deselected, 2 warnings in 81.91s (0:01:21) ============
Process finished with exit …
```

[content_view] - Upgrade scenario refactor

---

tests/upgrades/test_contentview.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10879
```
/Users/okhatavk/satellite/robottelo/env/bin/python "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/_jb_pytest_runner.py" --path /Users/okhatavk/satellite/robottelo/tests/upgrades/test_contentview.py -- -m post_upgrade
Testing started at 4:45 PM ...
Launching pytest with arguments -m post_upgrade /Users/okhatavk/satellite/robottelo/tests/upgrades/test_contentview.py --no-header --no-summary -q in /Users/okhatavk/satellite/robottelo
collecting ... collected 2 items / 1 deselected / 1 selected
tests/upgrades/test_contentview.py::TestContentView::test_cv_postupgrade_scenario 
============ 1 passed, 1 deselected, 2 …
```

[6.13.z] [content_view] - Upgrade scenario refactor

---

tests/upgrades/test_contentview.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10879
```
/Users/okhatavk/satellite/robottelo/env/bin/python "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/_jb_pytest_runner.py" --path /Users/okhatavk/satellite/robottelo/tests/upgrades/test_contentview.py -- -m post_upgrade
Testing started at 4:45 PM ...
Launching pytest with arguments -m post_upgrade /Users/okhatavk/satellite/robottelo/tests/upgrades/test_contentview.py --no-header --no-summary -q in /Users/okhatavk/satellite/robottelo
collecting ... collected 2 items / 1 deselected / 1 selected
tests/upgrades/test_contentview.py::TestContentView::test_cv_postupgrade_scenario 
============ 1 passed, 1 deselected, 2 …
```

[6.12.z] [content_view] - Upgrade scenario refactor

---

tests/upgrades/test_contentview.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10879
```
/Users/okhatavk/satellite/robottelo/env/bin/python "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/_jb_pytest_runner.py" --path /Users/okhatavk/satellite/robottelo/tests/upgrades/test_contentview.py -- -m post_upgrade
Testing started at 4:45 PM ...
Launching pytest with arguments -m post_upgrade /Users/okhatavk/satellite/robottelo/tests/upgrades/test_contentview.py --no-header --no-summary -q in /Users/okhatavk/satellite/robottelo
collecting ... collected 2 items / 1 deselected / 1 selected
tests/upgrades/test_contentview.py::TestContentView::test_cv_postupgrade_scenario 
============ 1 passed, 1 deselected, 2 …
```

[6.11.z] [content_view] - Upgrade scenario refactor

---

pytest_fixtures/component/contentview.py
pytest_fixtures/component/puppet.py
pytest_fixtures/core/upgrade.py
robottelo/constants/__init__.py
robottelo/host_helpers/__init__.py
robottelo/host_helpers/satellite_mixins.py
tests/foreman/cli/test_satellitesync.py
tests/foreman/destructive/test_puppetplugin.py
tests/upgrades/conftest.py
tests/upgrades/test_bookmarks.py
tests/upgrades/test_classparameter.py
tests/upgrades/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10638

[6.13.z] Cherry_pick for the PR 10638

---

pytest_fixtures/component/puppet.py
pytest_fixtures/core/upgrade.py
robottelo/constants/__init__.py
robottelo/host_helpers/__init__.py
robottelo/host_helpers/satellite_mixins.py
tests/foreman/cli/test_satellitesync.py
tests/foreman/destructive/test_puppetplugin.py
tests/upgrades/conftest.py
tests/upgrades/test_bookmarks.py
tests/upgrades/test_classparameter.py
tests/upgrades/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10638

[6.11.z] Cherry pick for the PR 10638

---

tests/foreman/ui/test_ansible.py

Test results:
```
pytest tests/foreman/ui/test_ansible.py
plugins: services-2.2.1, mock-3.10.0, reportportal-5.1.5, ibutsu-2.2.4, xdist-3.2.0, cov-3.0.0
collected 7 items                                                                                                                                                                                                 
tests/foreman/ui/test_ansible.py ....... …
```

Ansible Test fixes

---

pytest_fixtures/core/contenthosts.py

New item has been added to `request.param` dict so we can log to promtail.

Added parameter for promtail

---

pytest_fixtures/core/contenthosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10945
New item has been added to `request.param` dict so we can log to promtail.

[6.11.z] Added parameter for promtail

---

pytest_fixtures/core/contenthosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10945
New item has been added to `request.param` dict so we can log to promtail.

[6.12.z] Added parameter for promtail

---

pytest_fixtures/core/contenthosts.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10945
New item has been added to `request.param` dict so we can log to promtail.

[6.13.z] Added parameter for promtail

---

pytest_fixtures/component/contentview.py
pytest_fixtures/component/puppet.py
pytest_fixtures/core/upgrade.py
robottelo/constants/__init__.py
robottelo/host_helpers/__init__.py
robottelo/host_helpers/satellite_mixins.py
tests/foreman/cli/test_satellitesync.py
tests/foreman/destructive/test_puppetplugin.py
tests/upgrades/conftest.py
tests/upgrades/test_bookmarks.py
tests/upgrades/test_classparameter.py
tests/upgrades/test_satellitesync.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10638

[6.12.z] Cherry pick for the PR 10638

---

tests/foreman/maintain/test_advanced.py

I thought this scenario would fit in well with this test. Requires creating two sync plans, deleting one while all are disabled, and then enabling all again.

Adding coverage for 2175007 and 1997186

---

tests/foreman/maintain/test_advanced.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10952
I thought this scenario would fit in well with this test. Requires creating two sync plans, deleting one while all are disabled, and then enabling all again.

[6.12.z] Adding coverage for 2175007 and 1997186

---

conf/dynaconf_hooks.py
robottelo/host_helpers/contenthost_mixins.py
tests/foreman/cli/test_remoteexecution.py

(cherry picked from commit db072dc0c738d6d8858d056718b188c71eaf7f12)
Cherry-pick of #10983

[6.12.z] Adapt to the current API endpoint path for client repos (#10983)

---

conf/dynaconf_hooks.py
robottelo/host_helpers/contenthost_mixins.py

(cherry picked from commit db072dc0c738d6d8858d056718b188c71eaf7f12)
Cherry-pick of #10983

[6.11.z] Adapt to the current API endpoint path for client repos (#10983)

---

tests/foreman/data/hammer_commands.json

Opened as a result of discussion in https://github.com/SatelliteQE/robottelo/pull/10970 Thanks @JacobCallahan @Gauravtalreja1

[6.13] hammer commands updated

---

robottelo/constants/__init__.py
tests/foreman/cli/test_remoteexecution.py

Fixes #10905
(cherry picked from commit 2282906819af8c36ea3afdf852e5319735aff037)

[6.11.z] Fix and extend ansible_collection install test

---

pytest_fixtures/component/provisioning_template.py
tests/foreman/api/test_provisioningtemplate.py

Adding closed loop [BZ#2149030](https://bugzilla.redhat.com/show_bug.cgi?id=2148433) for Provisioning Templates

Add closed loop BZ#2148433 for Provisioning Templates

---

tests/foreman/api/test_capsulecontent.py
tests/foreman/api/test_contentcredentials.py
tests/foreman/cli/test_contentcredentials.py
tests/foreman/virtwho/api/test_nutanix.py

as reported by the weekly workflow,
closes https://github.com/SatelliteQE/robottelo/issues/10979

added customerscenario tags

---

tests/foreman/api/test_ansible.py
tests/foreman/ui/test_ansible.py

Fixes for ansible

---

tests/foreman/api/test_ansible.py
tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11044
Some refactoring and fixes

[6.13.z] Fixes for ansible

---

tests/foreman/api/test_ansible.py
tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11044
Some refactoring and fixes

[6.12.z] Fixes for ansible

---

tests/foreman/cli/test_remoteexecution.py

Manual cherrypick, close https://github.com/SatelliteQE/robottelo/issues/10997

[6.12] force register hosts fror rex

---

pytest_fixtures/component/provisioning_template.py
tests/foreman/api/test_provisioningtemplate.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10993
Adding closed loop [BZ#2149030](https://bugzilla.redhat.com/show_bug.cgi?id=2148433) for Provisioning Templates

[6.13.z] Add closed loop BZ#2148433 for Provisioning Templates

---

tests/foreman/api/test_reporttemplates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10999
Simple test exercising the new Job - Invocation Report Template.

[6.13.z] Test for new Job - Invocation Report Template

---

tests/foreman/ui/test_remoteexecution.py

see https://github.com/SatelliteQE/airgun/pull/819#issuecomment-1486676435

skip rex UI tests on 2182353

---

tests/foreman/api/test_capsulecontent.py

Forgot to cherrypick this one to 6.13 last week.

Cherrypick capsule-sync test

---

tests/foreman/ui/test_host.py

Katello-Tracer Cherrypick PR

---

robottelo/cli/acs.py
robottelo/constants/repos.py
testimony.yaml
tests/foreman/cli/test_acs.py

Adds basic cli tests (CRUD and validations) for Alternate Content Sources.

Add cli tests for ACSes

---

tests/foreman/ui/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10965
related to the new rex wizard UI, requires https://github.com/SatelliteQE/airgun/pull/819

[6.13.z] changes in rex ui tests

---

tests/foreman/virtwho/cli/test_esx_sca.py
tests/foreman/virtwho/ui/test_esx_sca.py

Add virt who config cases to All Tiers Upgrade Tests

Add virt who config cases to All Tiers Upgrade Tests

---

robottelo/host_helpers/contenthost_mixins.py
robottelo/hosts.py
tests/foreman/cli/test_host.py

backport of https://github.com/SatelliteQE/robottelo/pull/10460

[6.13.z] test_host - disable SCA on the module_org

---

tests/foreman/api/test_subscription.py
tests/foreman/cli/test_reporttemplates.py
tests/foreman/ui/test_reporttemplates.py

Adding testing for Rhel 7, 8 and 9 on top of merged PR https://github.com/SatelliteQE/robottelo/pull/10937

Updated installed report rhel versions

---

tests/foreman/cli/test_reporttemplates.py
tests/foreman/ui/test_reporttemplates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11155
Adding testing for Rhel 7, 8 and 9 on top of merged PR https://github.com/SatelliteQE/robottelo/pull/10937

[6.13.z] Updated installed report rhel versions

---

robottelo/cli/content_export.py
tests/foreman/cli/test_satellitesync.py

Adds two tests for export of docker-type repos and few other fixes related to this module.

Add coverage for docker-type repository exports

---

tests/foreman/destructive/test_auth.py

not part of #11150 as this works ok in 6.12, the response format changed, hence the test failure

reset password test fix

---

tests/foreman/cli/test_auth.py

1903693 closed wontfix, LOGEDOFF_MSG no longer used, removed some nonsensical format calls

fixes  in cli auth tests

---

tests/foreman/api/test_provisioningtemplate.py

Adding closed loop [BZ#2149030](https://bugzilla.redhat.com/show_bug.cgi?id=2149030) for Provisioning Templates
Dependent Nailgun PR: https://github.com/SatelliteQE/nailgun/pull/898

Add closed loop BZ#2149030 for Provisioning Templates

---

tests/foreman/api/test_provisioningtemplate.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10781
Adding closed loop [BZ#2149030](https://bugzilla.redhat.com/show_bug.cgi?id=2149030) for Provisioning Templates
Dependent Nailgun PR: https://github.com/SatelliteQE/nailgun/pull/898

[6.12.z] Add closed loop BZ#2149030 for Provisioning Templates

---

conf/dynaconf_hooks.py
pytest_fixtures/component/katello_agent.py
robottelo/constants/__init__.py
robottelo/host_helpers/__init__.py
robottelo/host_helpers/api_factory.py
robottelo/host_helpers/contenthost_mixins.py
robottelo/hosts.py
tests/foreman/api/test_errata.py
tests/foreman/ui/test_errata.py
tests/upgrades/test_client.py
tests/upgrades/test_errata.py
tests/upgrades/test_repository.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10930
null

[6.13.z] [errata] - Upgrade scenario refactor

---

robottelo/constants/__init__.py

From a recent PR: https://github.com/SatelliteQE/robottelo/pull/10930
Simple lil' text goof :)

Fix DISTROS_SUPPORTED

---

pytest_fixtures/component/taxonomy.py
tests/upgrades/test_subscription.py

Resolves https://github.com/SatelliteQE/robottelo/issues/11169

[6.13.z]-[subscription] refactored the upgrade scenario automation

---

robottelo/constants/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11194
From a recent PR: https://github.com/SatelliteQE/robottelo/pull/10930
Simple lil' text goof :)

[6.13.z] Fix DISTROS_SUPPORTED

---

robottelo/constants/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11194
From a recent PR: https://github.com/SatelliteQE/robottelo/pull/10930
Simple lil' text goof :)

[6.12.z] Fix DISTROS_SUPPORTED

---

robottelo/constants/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11194
From a recent PR: https://github.com/SatelliteQE/robottelo/pull/10930
Simple lil' text goof :)

[6.11.z] Fix DISTROS_SUPPORTED

---

pytest_fixtures/component/puppet.py
robottelo/constants/__init__.py
robottelo/host_helpers/__init__.py
robottelo/host_helpers/capsule_mixins.py
robottelo/host_helpers/satellite_mixins.py
tests/foreman/cli/test_report.py
tests/foreman/destructive/test_puppetplugin.py

[6.13.z] Add automation for BZ 2026239

---

pytest_fixtures/component/puppet.py
robottelo/constants/__init__.py
robottelo/host_helpers/__init__.py
robottelo/host_helpers/capsule_mixins.py
robottelo/host_helpers/satellite_mixins.py
tests/foreman/cli/test_report.py
tests/foreman/destructive/test_puppetplugin.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11013
null

[6.12.z] Add automation for BZ 2026239

---

pytest_fixtures/component/puppet.py
robottelo/constants/__init__.py
robottelo/host_helpers/__init__.py
robottelo/host_helpers/capsule_mixins.py
robottelo/host_helpers/satellite_mixins.py
tests/foreman/cli/test_report.py
tests/foreman/destructive/test_puppetplugin.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11013
null

[6.11.z] Add automation for BZ 2026239

---

pytest_fixtures/component/taxonomy.py
tests/upgrades/test_subscription.py

Resolves https://github.com/SatelliteQE/robottelo/issues/11170

[6.12.z]-[subscription] refactored the upgrade scenario automation

---

pytest_fixtures/component/taxonomy.py
tests/upgrades/test_subscription.py

Resolves https://github.com/SatelliteQE/robottelo/issues/11168

[6.11.z]-[subscription] refactored the upgrade scenario automation

---

tests/foreman/destructive/test_infoblox.py

Manual cpick https://github.com/SatelliteQE/robottelo/pull/10828
Fixes https://github.com/SatelliteQE/robottelo/issues/10889

[6.11.z] Fix infoblox plugin install tests

---

robottelo/constants/__init__.py

- Update Constant value of "SCAP Content profile for Firefox"
- SCAP content profiles > Title: Mozilla Firefox STIG

Updating Constant value of SCAP content profiles for Firefox

---

robottelo/constants/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11211
- Update Constant value of "SCAP Content profile for Firefox"
- SCAP content profiles > Title: Mozilla Firefox STIG

[6.13.z] Updating Constant value of SCAP content profiles for Firefox

---

robottelo/constants/__init__.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11211
- Update Constant value of "SCAP Content profile for Firefox"
- SCAP content profiles > Title: Mozilla Firefox STIG

[6.12.z] Updating Constant value of SCAP content profiles for Firefox

---

tests/foreman/destructive/test_capsule_loadbalancer.py

Manual Cherrypick of PR [10931](https://github.com/SatelliteQE/robottelo/pull/10931)

Cherrypick 6.13.z:Add test for host registration through LB

---

tests/foreman/api/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10442

[6.12.z] Extend test coverage for BZ#2148813

---

pytest_fixtures/component/domain.py
pytest_fixtures/component/provision_gce.py
tests/foreman/api/test_computeresource_gce.py
tests/upgrades/test_host.py

Resolves https://github.com/SatelliteQE/robottelo/issues/11229

[Host]-Refactor upgrade tests for Host

---

.github/workflows/auto_cherry_pick.yml

resolves https://github.com/SatelliteQE/robottelo/issues/11266

remove the gchat notification using the github action

---

pytest_fixtures/core/upgrade.py
robottelo/constants/__init__.py
robottelo/content_info.py
robottelo/host_helpers/capsule_mixins.py
tests/foreman/api/test_capsulecontent.py
tests/upgrades/test_capsule.py

This PR is a cherry-pick of #10770.
* Refactor Capsule Upgrade scenario
* All tests pass \o/
* Reorder imports
* Change remove() to discard() for set
Co-authored-by: Omkar Khatavkar <okhatavk@redhat.com>
* Remove unnecessary checks, add logging to pre_configured_capsule fixture
---------
Co-authored-by: Omkar Khatavkar <okhatavk@redhat.com>
(cherry picked from commit edd9623cfae7314c8c128b2cdb3cb5bb03f9b3c3)

[6.13.z] [capsule] - Upgrade scenario refactor (#10770)

---

pytest_fixtures/core/upgrade.py
robottelo/constants/__init__.py
robottelo/content_info.py
robottelo/host_helpers/capsule_mixins.py
tests/foreman/api/test_capsulecontent.py
tests/upgrades/test_capsule.py

This PR is a cherry-pick of #10770.
Closes #11288.
* Refactor Capsule Upgrade scenario
* All tests pass \o/
* Reorder imports
* Change remove() to discard() for set
Co-authored-by: Omkar Khatavkar <okhatavk@redhat.com>
* Remove unnecessary checks, add logging to pre_configured_capsule fixture
---------
Co-authored-by: Omkar Khatavkar <okhatavk@redhat.com>
(cherry picked from commit edd9623cfae7314c8c128b2cdb3cb5bb03f9b3c3)

[6.12.z] [capsule] - Upgrade scenario refactor (#10770) 

---

pytest_fixtures/component/katello_agent.py

This functionality was removed in #10930. This PR brings it back but puts a different logic in place.
This fixture now assumes that if satellite-installer RC == 0, katello-agent fixture was installed successfully.

Install katello-agent if it is not installed already

---

pytest_fixtures/component/katello_agent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11299
This functionality was removed in #10930. This PR brings it back but puts a different logic in place.
This fixture now assumes that if satellite-installer RC == 0, katello-agent fixture was installed successfully.

[6.13.z] Install katello-agent if it is not installed already

---

pytest_fixtures/component/katello_agent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11299
This functionality was removed in #10930. This PR brings it back but puts a different logic in place.
This fixture now assumes that if satellite-installer RC == 0, katello-agent fixture was installed successfully.

[6.12.z] Install katello-agent if it is not installed already

---

pytest_fixtures/component/katello_agent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11299
This functionality was removed in #10930. This PR brings it back but puts a different logic in place.
This fixture now assumes that if satellite-installer RC == 0, katello-agent fixture was installed successfully.

[6.11.z] Install katello-agent if it is not installed already

---

tests/upgrades/test_errata.py

added customerscenario tags for errata upgrade tests

---

tests/upgrades/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11333
closes #11323

[6.11.z] added customerscenario tags for errata upgrade tests

---

tests/upgrades/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11333
closes #11323

[6.12.z] added customerscenario tags for errata upgrade tests

---

tests/upgrades/test_errata.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11333
closes #11323

[6.13.z] added customerscenario tags for errata upgrade tests

---

tests/foreman/api/test_audit.py
tests/foreman/api/test_ping.py
tests/foreman/cli/test_auth.py
tests/foreman/cli/test_hammer.py
tests/foreman/cli/test_host.py
tests/foreman/cli/test_hostgroup.py
tests/foreman/cli/test_location.py
tests/foreman/cli/test_organization.py
tests/foreman/cli/test_templatesync.py
tests/foreman/destructive/test_capsule_loadbalancer.py
tests/foreman/destructive/test_realm.py
tests/foreman/sys/test_dynflow.py
tests/foreman/ui/test_domain.py
tests/foreman/ui/test_hardwaremodel.py
tests/foreman/ui/test_host.py
tests/foreman/ui/test_hostgroup.py
tests/foreman/ui/test_jobtemplate.py
tests/foreman/ui/test_location.py
tests/foreman/ui/test_media.py
tests/foreman/ui/test_organization.py
tests/foreman/ui/test_partitiontable.py
tests/foreman/ui/test_role.py
tests/foreman/ui/test_user.py
tests/foreman/ui/test_usergroup.py

added e2e marks for Endeavour components

---

tests/foreman/virtwho/ui/test_esx_sca.py
tests/foreman/virtwho/ui/test_hyperv_sca.py
tests/foreman/virtwho/ui/test_kubevirt_sca.py
tests/foreman/virtwho/ui/test_libvirt_sca.py

[6.13.z] virt-who config SCA support UI for esx kubevirt libvirt hyperv #11024

---

tests/foreman/destructive/test_clone.py

```
==================================================================== 14/5794 tests collected (5780 deselected) in 31.22s ====================================================================
2023-04-27 11:57:11 - robottelo.collection - INFO - Processing test items to add testimony token markers
```

cast fix for settings.server.version.rhel_version for 6.11.z

---

tests/foreman/cli/test_hammer.py
tests/foreman/ui/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11366
Added a bunch of bz and customerscenario tags, resulting from checking endeavour's 6.13 RFEs

[6.13.z] added some bz tags for traceablity

---

requirements-optional.txt

update sphinx to 7.0

---

conf/ldap.yaml.template
conftest.py
pytest_fixtures/component/satellite_auth.py
pytest_fixtures/component/user.py
robottelo/cli/base.py
robottelo/hosts.py
tests/foreman/destructive/test_ldap_authentication.py

Cherrypick https://github.com/SatelliteQE/robottelo/pull/10844

Cherrypick kerberos tests

---

tests/foreman/api/test_repositories.py

added tests for expired manifest.
Refreshing an expired manifest should fail

Added test for expired manifest [Repository Rewrite]

---

tests/foreman/api/test_repositories.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/10428
added tests for expired manifest.
Refreshing an expired manifest should fail

[6.13.z] Added test for expired manifest [Repository Rewrite]

---

tests/foreman/maintain/test_backup_restore.py

Adding a test that mostly copies the functionality of `test_positive_backup_restore` for testing backup and restore on a puppet enabled satellite. The reasoning for adding a new test and not parametrizing is because the run time of the test is quite significant (8 tests * 15 - 30 minutes each). If we parametrize that test we now run it 16 times. Instead I thought copying the test and running it once for offline and once for online would be enough coverage.
During my testing I also discovered a bug with our backup and restore tests. In 6.13, `pg_globals.dump` was removed, so I removed that file from the list and updated anything that depended on it (like `REMOTE_SAT_FILES`).

Adding puppet enabled backup and restore

---

pytest_fixtures/component/satellite_auth.py
tests/foreman/destructive/test_ldap_authentication.py
tests/foreman/ui/test_ldap_authentication.py

Cherrypick and answer to https://github.com/SatelliteQE/robottelo/pull/11253#issuecomment-1512501994 : No :)

[6.13.z] Cherrypick ad 2019

---

pytest_fixtures/component/satellite_auth.py
tests/foreman/destructive/test_ldap_authentication.py
tests/foreman/ui/test_ldap_authentication.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11398
Cherrypick and answer to https://github.com/SatelliteQE/robottelo/pull/11253#issuecomment-1512501994 : No :)

[6.12.z] [6.13.z] Cherrypick ad 2019

---

tests/foreman/ui/test_webhook.py

manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/11399 somehow the autocherrypick process didn't trigger

[6.12] webhook bz coverage added

---

tests/foreman/ui/test_bookmarks.py

This wasn't skipped on 1992652, hence failing since 6.10, then after the bz was closed wontfix half a year ago no amendments were made. So this pr changes the assertions so that the test doesn't rely on an error box that is not shown

fix in search bookmark assertion

---

tests/foreman/maintain/test_backup_restore.py

Cherry pick for failure: https://github.com/SatelliteQE/robottelo/issues/11410

[6.13.z] Adding puppet enabled backup and restore

---

tests/foreman/ui/test_bookmarks.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11411
This wasn't skipped on 1992652, hence failing since 6.10, then after the bz was closed wontfix half a year ago no amendments were made. So this pr changes the assertions so that the test doesn't rely on an error box that is not shown

[6.13.z] fix in search bookmark assertion

---

tests/foreman/ui/test_webhook.py

manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/11399 somehow the autocherrypick process didn't trigger

[6.13] webhook bz coverage added

---

tests/foreman/ui/test_bookmarks.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11411
This wasn't skipped on 1992652, hence failing since 6.10, then after the bz was closed wontfix half a year ago no amendments were made. So this pr changes the assertions so that the test doesn't rely on an error box that is not shown

[6.12.z] fix in search bookmark assertion

---

tests/foreman/ui/test_bookmarks.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11411
This wasn't skipped on 1992652, hence failing since 6.10, then after the bz was closed wontfix half a year ago no amendments were made. So this pr changes the assertions so that the test doesn't rely on an error box that is not shown

[6.11.z] fix in search bookmark assertion

---

pytest_fixtures/component/provision_gce.py
tests/foreman/api/test_computeresource_gce.py
tests/foreman/ui/test_computeresource_gce.py
tests/upgrades/test_host.py

Adding parametrization for puppet/non_puppet based scenarios and entities refactor for GCE module
Test results **API**:
```
pytest tests/foreman/api/test_computeresource_gce.py
================================================================================================================================== test session starts ===================================================================================================================================
platform linux -- Python 3.11.1, pytest-7.2.2, pluggy-1.0.0
plugins: services-2.2.1, mock-3.10.0, reportportal-5.1.6, ibutsu-2.2.4, xdist-3.2.1, cov-3.0.0
collected 11 items …
```

Gce parametrization and entities refactor

---

tests/foreman/api/test_provisioningtemplate.py

Adding a closed loop for provisioning templates for BZ : https://bugzilla.redhat.com/show_bug.cgi?id=1607706

Add closed loop for BZ#1607706

---

pytest_fixtures/component/provision_gce.py
tests/foreman/api/test_computeresource_gce.py
tests/foreman/ui/test_computeresource_gce.py
tests/upgrades/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11221
Adding parametrization for puppet/non_puppet based scenarios and entities refactor for GCE module
Test results **API**:
```
pytest tests/foreman/api/test_computeresource_gce.py
================================================================================================================================== test session starts ===================================================================================================================================
platform linux -- Python 3.11.1, pytest-7.2.2, pluggy-1.0.0
plugins: services-2.2.1, mock-3.10.0, reportportal-5.1.6, ibutsu-2.2.4, xdist-3.2.1, …
```

[6.13.z] Gce parametrization and entities refactor

---

tests/foreman/api/test_provisioningtemplate.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11432
Adding a closed loop for provisioning templates for BZ : https://bugzilla.redhat.com/show_bug.cgi?id=1607706

[6.13.z] Add closed loop for BZ#1607706

---

tests/foreman/cli/test_hammer.py

...for added hammer option in 2154512

one more bz tag added

---

tests/foreman/cli/test_hammer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11450
...for added hammer option in 2154512

[6.13.z] one more bz tag added

---

tests/foreman/endtoend/test_api_endtoend.py

```
pytest tests/foreman/endtoend/test_api_endtoend.py -k test_positive_get_links
collected 6 items / 5 deselected / 1 selected                                                                        
tests/foreman/endtoend/test_api_endtoend.py .                                                                  [100%]
```

exports added to api paths

---

tests/foreman/ui/test_settings.py

Extending the existing test to cover for 2157869, also removed some old skips from the test_settings file
Local result:
```
pytest tests/foreman/ui/test_settings.py -k test_positive_update_login_page_footer_text
collected 16 items / 15 deselected / 1 selected                                                                      
tests/foreman/ui/test_settings.py .                                                                            [100%]
============================== 1 passed, 15 deselected, 2 warnings in 126.77s (0:02:06) ==============================
```

test settings change from non-default to default

---

tests/foreman/endtoend/test_api_endtoend.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11462
```
pytest tests/foreman/endtoend/test_api_endtoend.py -k test_positive_get_links
collected 6 items / 5 deselected / 1 selected                                                                        
tests/foreman/endtoend/test_api_endtoend.py .                                                                  [100%]
```

[6.12.z] exports added to api paths

---

tests/foreman/api/test_contentviewfilter.py

Requires https://github.com/SatelliteQE/nailgun/pull/921

Add test for filter_applied flag

---

tests/foreman/maintain/test_service.py

See https://bugzilla.redhat.com/show_bug.cgi?id=1995783 for bug description. When https://github.com/theforeman/foreman_maintain/pull/730 lands in stream this should pass and we can verify the BZ.

Updating service enable/disable to test on stream

---

.github/workflows/auto_cherry_pick.yml

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11379
$subject

[6.11.z] Run Autocherrypick on merged PRs

---

tests/foreman/api/test_capsulecontent.py
tests/foreman/api/test_contentcredentials.py
tests/foreman/cli/test_contentcredentials.py
tests/foreman/virtwho/api/test_nutanix.py

closes #11039
closes #11082
Not sure what was the problem, this cherry-picked cleanly, also not sure why 2 issues were created, anyway here's the manual cherry-pick

[6.13] added customerscenario tags

---

.github/workflows/auto_cherry_pick.yml

Manual Cherrypick of https://github.com/SatelliteQE/robottelo/pull/11379
Failed AutoCherrypick in https://github.com/SatelliteQE/robottelo/actions/runs/5025576376
Closes #11489

[6.13.z] Run Autocherrypick on merged PRs

---

.github/workflows/auto_cherry_pick.yml

Manual Cherrypick of https://github.com/SatelliteQE/robottelo/pull/11379
Failed AutoCherrypick in https://github.com/SatelliteQE/robottelo/actions/runs/5025576376
Closes #11488

[6.12.z] Run Autocherrypick on merged PRs

---

tests/upgrades/test_puppet.py
tests/upgrades/test_remoteexecution.py

Closes #11493
Cherry-pick of #11406

[6.13.z] Use pre_configured_capsule fixture to ensure we get the correct Capsule

---

tests/foreman/ui/test_settings.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11437
Extending the existing test to cover for 2157869, also removed some old skips from the test_settings file
Local result:
```
pytest tests/foreman/ui/test_settings.py -k test_positive_update_login_page_footer_text
collected 16 items / 15 deselected / 1 selected                                                                      
tests/foreman/ui/test_settings.py .                                                                            [100%]
============================== 1 passed, 15 deselected, 2 warnings in 126.77s (0:02:06) ==============================
```

[6.13.z] test settings change from non-default to default

---

testimony.yaml
tests/foreman/cli/test_host.py
tests/foreman/ui/test_host.py

[6.13.z] Katello-tracer Alligned in CI (#11547)

---

testimony.yaml
tests/foreman/cli/test_host.py

[6.12.z] Katello-tracer Alligned in CI (#11547)

---

testimony.yaml

[6.11.z] Katello-tracer Aligned in CI (#11547)

---

tests/foreman/cli/test_contentviewfilter.py

Satellite 6.14.0 is going to implement indication and listing of filters applied to a CVV. This PR adds a test to ensure the correct functionality in hammer CLI.
Note: The upstream changes tested in this PR should land in the next stream snap (16.0). Expect the PRT to fail until then.

Add CLI test for applied filters

---

tests/foreman/cli/test_contentviewfilter.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11542
Satellite 6.14.0 is going to implement indication and listing of filters applied to a CVV. This PR adds a test to ensure the correct functionality in hammer CLI.
Note: The upstream changes tested in this PR should land in the next stream snap (16.0). Expect the PRT to fail until then.

[6.14.z] Add CLI test for applied filters

---

tests/foreman/cli/test_contentviewfilter.py

Manual cherry-pick of #11596
Closes #11598

[6.14.z] Remove @stream decorator

---

pytest_fixtures/component/satellite_auth.py
robottelo/hosts.py
tests/foreman/destructive/test_ldapauthsource.py

1) Fix setting a redirect URL to the actual Satellite
2) Fix issues setting client access to public
Test results: satellite-jenkins MR#1033

Fix RHSSO bugs.

---

conf/infoblox.yaml.template
tests/foreman/destructive/test_infoblox.py
tests/foreman/installer/test_infoblox.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11482  to 6.14.z
Fixes https://github.com/SatelliteQE/robottelo/issues/11605

[6.14.z] Add Infoblox end to end test

---

pytest_fixtures/component/satellite_auth.py
robottelo/hosts.py
tests/foreman/destructive/test_ldapauthsource.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11546
1) Fix setting a redirect URL to the actual Satellite
2) Fix issues setting client access to public
Test results: satellite-jenkins MR#1033

[6.12.z] Fix RHSSO bugs.

---

tests/foreman/api/test_user.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11609
Requires https://github.com/SatelliteQE/nailgun/pull/928 . Test results included there.

[6.14.z] Close-loop 1757394

---

tests/foreman/api/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11631
null

[6.14.z] Add customercase

---

tests/foreman/api/test_host.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11631
null

[6.13.z] Add customercase

---

pytest_plugins/requirements/req_updater.py
pytest_plugins/requirements/update_requirements.py
requirements-optional.txt

[Req Assist] Update more reqs names deviation and other improvements

---

pytest_plugins/requirements/req_updater.py
pytest_plugins/requirements/update_requirements.py
requirements-optional.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11563
PR includes:

[6.13.z] [Req Assist] Update more reqs names deviation and other improvements

---

pytest_plugins/requirements/req_updater.py
pytest_plugins/requirements/update_requirements.py
requirements-optional.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11563
PR includes:

[6.11.z] [Req Assist] Update more reqs names deviation and other improvements

---

pytest_plugins/requirements/req_updater.py
pytest_plugins/requirements/update_requirements.py
requirements-optional.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11563
PR includes:

[6.14.z] [Req Assist] Update more reqs names deviation and other improvements

---

robottelo/cli/bootdisk.py
robottelo/constants/__init__.py
testimony.yaml
tests/foreman/cli/test_bootdisk.py

Adding closed loop for https://bugzilla.redhat.com/show_bug.cgi?id=2173199

Add Closed loop BZ#2173199

---

pytest_plugins/requirements/req_updater.py
pytest_plugins/requirements/update_requirements.py
requirements-optional.txt

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11563
PR includes:

[6.12.z] [Req Assist] Update more reqs names deviation and other improvements

---

robottelo/cli/bootdisk.py
robottelo/constants/__init__.py
tests/foreman/cli/test_bootdisk.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11608
Adding closed loop for https://bugzilla.redhat.com/show_bug.cgi?id=2173199

[6.13.z] Add Closed loop BZ#2173199

---

robottelo/cli/bootdisk.py
robottelo/constants/__init__.py
tests/foreman/cli/test_bootdisk.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11608
Adding closed loop for https://bugzilla.redhat.com/show_bug.cgi?id=2173199

[6.14.z] Add Closed loop BZ#2173199

---

pytest_fixtures/component/satellite_auth.py
robottelo/hosts.py
tests/foreman/destructive/test_ldapauthsource.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11546
1) Fix setting a redirect URL to the actual Satellite
2) Fix issues setting client access to public
Test results: satellite-jenkins MR#1033

[6.14.z] Fix RHSSO bugs.

---

tests/foreman/api/test_repository.py

6.14 implements a feature where the `treeinfo` file can be added to the repository's ignorable_content. I that case the `treeinfo` file is not synced (as well as any content referenced by it like `images\`).
This introduces a test that exercises the functionality.

Add treeinfo ignore test

---

tests/foreman/api/test_capsulecontent.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11683
Adds coverage for:
https://bugzilla.redhat.com/show_bug.cgi?id=2043089
https://bugzilla.redhat.com/show_bug.cgi?id=2211962
Requires https://github.com/SatelliteQE/nailgun/pull/935

[6.13.z] Add test for orphaned content removal from capsule

---

tests/foreman/api/test_repository.py

Cherry-pick of #11573 into 6.14.z.

[6.14.z] Add treeinfo ignore test

---

.github/workflows/auto_cherry_pick.yml
.github/workflows/dependency_merge.yml

- Add dependencies label in cherry-picked PRs 
- Automerge fix for the dependabot PR's

[6.14.z] - added the fix for the automerge cherry-pick dependabot PR's

---

.github/workflows/auto_cherry_pick.yml
.github/workflows/dependency_merge.yml

- Add dependencies label in cherry-picked PRs
- Automerge fix for the dependabot PR's

[6.13.z] - added the fix for the automerge cherry-pick dependabot PR's

---

.github/workflows/auto_cherry_pick.yml
.github/workflows/dependency_merge.yml

- Add dependencies label in cherry-picked PRs
- Automerge fix for the dependabot PR's

[6.12.z] - added the fix for the automerge cherry-pick dependabot PR's

---

.github/workflows/auto_cherry_pick.yml
.github/workflows/dependency_merge.yml

- Add dependencies label in cherry-picked PRs
- Automerge fix for the dependabot PR's

[6.11.z]- added the fix for the automerge cherry-pick dependabot PR's

---

robottelo/cli/bootdisk.py
robottelo/constants/__init__.py
tests/foreman/cli/test_bootdisk.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11608
Adding closed loop for https://bugzilla.redhat.com/show_bug.cgi?id=2173199

[6.12.z] Add Closed loop BZ#2173199

---

tests/foreman/endtoend/test_api_endtoend.py
tests/foreman/endtoend/test_cli_endtoend.py
tests/foreman/longrun/test_inc_updates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11669
This PR converts to manifester all tests using manifests to that are not contained in the API, CLI, or UI namespaces.

[6.13.z] Convert remaining tests to manifester

---

tests/foreman/endtoend/test_api_endtoend.py
tests/foreman/endtoend/test_cli_endtoend.py
tests/foreman/longrun/test_inc_updates.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11669
This PR converts to manifester all tests using manifests to that are not contained in the API, CLI, or UI namespaces.

[6.14.z] Convert remaining tests to manifester

---

testimony.yaml
tests/foreman/cli/test_host.py

Manual cherry-pick of PR: #11708 
Fixes #11712

[6.12.z] Fix Katello-tracer component case

---

tests/foreman/endtoend/test_api_endtoend.py

Updated the path list with the 6.14 changes, awaiting approval on sat-eng list for one remaining bit

api changes in 6.14

---

tests/upgrades/test_virtwho.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11706
Because ORG_DATA = {'name': 'virtwho_upgrade_org_name'} exist will effect the pre-upgrade case, so clean it before run the case, not use the dynamic name ,because post-upgrade will also this name
case : PASS
```
(robottelo_vv) [virtwho@dell-per740-68-vm-04 robottelo]$ pytest ./tests/upgrades/test_virtwho.py  -m pre_upgrade --disable-pytest-warnings
platform linux -- Python 3.10.9, pytest-7.3.2, pluggy-1.0.0
shared_function enabled - OFF …
```

[6.13.z] add delete org before run virt-who config upgrade cases

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11657
As per SAT-17647 the cronline for rex scheduling can now use extended expressions (using library fugit). This tests check that jobs are scheduled as expected when these expressions are used.

[6.14.z] extended cronline tests for rex

---

conf/capsule.yaml.template
conf/flavors.yaml.template
pytest_fixtures/core/sat_cap_factory.py
robottelo/config/validators.py
tests/foreman/destructive/test_capsulecontent.py

Manual cherry-pick of #10424
Closes #11747

[6.13.z] Add test for the Capsule sync deadlock issue

---

tests/foreman/destructive/test_infoblox.py

Removing stream marker on Infoblox test.

[6.13.z] Remove stream marker from Infoblox test

---

tests/foreman/api/test_repositories.py

Pulp test fix

---

tests/foreman/api/test_repositories.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11702
Fixed Pulp test case

[6.14.z] Pulp test fix

---

tests/foreman/cli/test_remoteexecution.py

Adding a simple extension to an existing test to cover for 2129432

check recurring logic cli keys

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11767
Adding a simple extension to an existing test to cover for 2129432

[6.14.z] check recurring logic cli keys

---

tests/foreman/api/test_reporttemplates.py

Adds test_positive_installable_errata, which tests that some host with installable errata generates the correct report from the installable-errata report template (6.14.0 feature). 
~Depends on fixes to factory.py and cli_factory.py in PR #11561, pulled those into here.~ [Merged]
Similar to the applied errata report template test found in that linked pr
BZ: [1726504](https://bugzilla.redhat.com/show_bug.cgi?id=1726504)

[RFE] test Installable Errata Report Template

---

tests/foreman/installer/test_installer.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11797
Add `foreman-rails-cache-store type:redis` to satellite-installer test.

[6.14.z] Add test for redis type foreman-rails-cache-store

---

conf/capsule.yaml.template
conf/flavors.yaml.template
pytest_fixtures/core/sat_cap_factory.py
robottelo/config/validators.py
robottelo/host_helpers/api_factory.py
tests/foreman/destructive/test_capsulecontent.py

Manual cherry-pick of #10424
Closes #11746

[6.12.z] Add test for the Capsule sync deadlock issue

---

conf/infoblox.yaml.template
pytest_fixtures/component/provisioning_template.py
robottelo/host_helpers/api_factory.py
tests/foreman/destructive/test_infoblox.py
tests/foreman/installer/test_infoblox.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11482
Closed Loop BZ -> https://bugzilla.redhat.com/show_bug.cgi?id=1813953

[6.12.z] Add Infoblox end to end test

---

tests/foreman/cli/test_remoteexecution.py

Faster setup with custom repo using global registration

fixes in rex packgage job tests

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11798
Faster setup with custom repo using global registration

[6.13.z] fixes in rex packgage job tests

---

pytest_fixtures/component/repository.py
tests/foreman/ui/test_repositories.py

SAT-16807
Switching on SCA should not give hosts access to new custom repositories

[6.13.z RFE] Added sca override test for Hosts

---

robottelo/hosts.py
tests/foreman/longrun/test_oscap.py

Manual cherry-pick for - https://github.com/SatelliteQE/robottelo/pull/11813
Automation coverage for :
https://bugzilla.redhat.com/show_bug.cgi?id=2081777
https://bugzilla.redhat.com/show_bug.cgi?id=2211952

[6.14.Z] - Support the --local-files oscap argument

---

robottelo/hosts.py
tests/foreman/longrun/test_oscap.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11836
Manual cherry-pick for - https://github.com/SatelliteQE/robottelo/pull/11813
Automation coverage for :
https://bugzilla.redhat.com/show_bug.cgi?id=2081777
https://bugzilla.redhat.com/show_bug.cgi?id=2211952

[6.13.z] [6.14.Z] - Support the --local-files oscap argument

---

tests/foreman/ui/test_ansible.py

Test fixes for Ansible

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11843
Ansible UI fixes

[6.14.z] Test fixes for Ansible

---

tests/foreman/ui/test_ansible.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11843
Ansible UI fixes

[6.13.z] Test fixes for Ansible

---

tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11798
Faster setup with custom repo using global registration

[6.14.z] fixes in rex packgage job tests

---

pytest_fixtures/component/maintain.py

Fix remote db tests failing because of the wrong satellite fixture being used.

Fix remote db tests

---

pytest_fixtures/component/maintain.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11851
Fix remote db tests failing because of the wrong satellite fixture being used.

[6.13.z] Fix remote db tests

---

pytest_fixtures/component/maintain.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11851
Fix remote db tests failing because of the wrong satellite fixture being used.

[6.14.z] Fix remote db tests

---

tests/foreman/cli/test_repositories.py

cs tag added for repos test

---

tests/foreman/cli/test_repositories.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11858
closes #11835

[6.14.z] cs tag added for repos test

---

tests/foreman/endtoend/test_api_endtoend.py
tests/foreman/endtoend/test_cli_endtoend.py

skip-if removed from e2e tests

---

tests/foreman/endtoend/test_api_endtoend.py
tests/foreman/endtoend/test_cli_endtoend.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11892
2216461 has been fixed

[6.14.z] skip-if removed from e2e tests

---

pytest_fixtures/component/maintain.py

Fix remote db tests failing because of session_capsule_configured.

Fix remote db tests failing because of session_capsule_configured

---

pytest_fixtures/component/maintain.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11910
Fix remote db tests failing because of session_capsule_configured.

[6.14.z] Fix remote db tests failing because of session_capsule_configured

---

pytest_fixtures/component/maintain.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11910
Fix remote db tests failing because of session_capsule_configured.

[6.13.z] Fix remote db tests failing because of session_capsule_configured

---

pytest_fixtures/component/maintain.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11910
Fix remote db tests failing because of session_capsule_configured.

[6.12.z] Fix remote db tests failing because of session_capsule_configured

---

tests/foreman/api/test_provisioningtemplate.py

Closes #11440 
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/11432

[6.11.z] Add closed loop BZ#2149030 for Provisioning Templates

---

pytest_fixtures/core/contenthosts.py
pytest_fixtures/core/sat_cap_factory.py
robottelo/constants/__init__.py
robottelo/hosts.py
tests/foreman/destructive/test_clone.py
tests/foreman/installer/test_installer.py

Add test for foreman-proxy-content-pulpcore-hide-guarded-distributions installer setting.

Add test for foreman-proxy-content-pulpcore-hide-guarded-distributions installer setting

---

.github/workflows/pull_request.yml
conftest.py
pytest_fixtures/component/puppet.py
pytest_fixtures/core/broker.py
pytest_fixtures/core/sat_cap_factory.py
pytest_fixtures/core/sys.py
pytest_fixtures/core/xdist.py
pytest_plugins/sanity_plugin.py
robottelo/hosts.py
robottelo/utils/ohsnap.py
setup.py
testimony.yaml
tests/foreman/api/test_computeresource_gce.py
tests/foreman/api/test_host.py
tests/foreman/api/test_organization.py
tests/foreman/api/test_repository.py
tests/foreman/api/test_syncplan.py
tests/foreman/api/test_user.py
tests/foreman/cli/test_contentcredentials.py
tests/foreman/cli/test_contentview.py
tests/foreman/cli/test_hostcollection.py
tests/foreman/cli/test_ping.py
tests/foreman/cli/test_role.py
tests/foreman/cli/test_user.py
tests/foreman/endtoend/test_api_endtoend.py
tests/foreman/installer/test_installer.py
tests/foreman/sanity/test_bvt.py

Cherrypick of https://github.com/SatelliteQE/robottelo/pull/11645 in 6.11.z.

[6.11.z] Sanity Plugin with new sanity tests runs on installer tests satellite

---

conftest.py
pytest_fixtures/component/puppet.py
pytest_fixtures/core/broker.py
pytest_fixtures/core/contenthosts.py
pytest_fixtures/core/sat_cap_factory.py
pytest_fixtures/core/sys.py
pytest_fixtures/core/xdist.py
pytest_plugins/sanity_plugin.py
robottelo/hosts.py
robottelo/utils/ohsnap.py
testimony.yaml
tests/foreman/api/test_computeresource_gce.py
tests/foreman/api/test_host.py
tests/foreman/api/test_organization.py
tests/foreman/api/test_repository.py
tests/foreman/api/test_syncplan.py
tests/foreman/api/test_user.py
tests/foreman/cli/test_contentcredentials.py
tests/foreman/cli/test_contentview.py
tests/foreman/cli/test_hostcollection.py
tests/foreman/cli/test_ping.py
tests/foreman/cli/test_role.py
tests/foreman/cli/test_user.py
tests/foreman/endtoend/test_api_endtoend.py
tests/foreman/installer/test_installer.py
tests/foreman/sanity/test_bvt.py

Cherrypick of https://github.com/SatelliteQE/robottelo/pull/11645 in 6.14.z.

[6.14.z] Sanity Plugin with new sanity tests runs on installer tests satellite

---

tests/foreman/maintain/test_service.py

This is currently failing because the foreman service takes a little bit of time to "wake up". When this was originally merged we were waiting for the fix, so I wasn't able to catch it until we found it in CI.

Adding wait_for to test_positive_service_enable_disable

---

pytest_fixtures/core/sat_cap_factory.py
robottelo/constants/__init__.py
robottelo/hosts.py
tests/foreman/destructive/test_clone.py
tests/foreman/installer/test_installer.py

Cherry-pick #11885 
Fixes #11965

[Cherry-pick #11885] Add test for foreman-proxy-content-pulpcore-hide-guarded-distributions installer setting

---

tests/foreman/maintain/test_service.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11952
This is currently failing because the foreman service takes a little bit of time to "wake up". When this was originally merged we were waiting for the fix, so I wasn't able to catch it until we found it in CI.

[6.14.z] Adding wait_for to test_positive_service_enable_disable

---

tests/foreman/endtoend/test_api_endtoend.py

all changes tied to BZ#2159105

api endpoints updated

---

tests/foreman/endtoend/test_api_endtoend.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11893
all changes tied to BZ#2159105

[6.14.z] api endpoints updated

---

tests/foreman/endtoend/test_api_endtoend.py
tests/foreman/endtoend/test_cli_endtoend.py

#11892 should have been cherry-picked to 6.13 as well, the blame is solely on me for not adding the label

[6.13.z] skip-if removed from e2e tests

---

tests/foreman/ui/test_webhook.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12020
Fixes failures when there is more than one webhook.
PRT will probably fail due to unrelated vertical nav error.

[6.14.z] Don't just take random webhook, search by name

---

tests/foreman/ui/test_webhook.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12020
Fixes failures when there is more than one webhook.
PRT will probably fail due to unrelated vertical nav error.

[6.13.z] Don't just take random webhook, search by name

---

tests/foreman/ui/test_webhook.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12020
Fixes failures when there is more than one webhook.
PRT will probably fail due to unrelated vertical nav error.

[6.12.z] Don't just take random webhook, search by name

---

tests/foreman/api/test_provisioning.py
tests/foreman/api/test_provisioningtemplate.py

QETestCoverage for [BZ 2168967](https://bugzilla.redhat.com/show_bug.cgi?id=2168967) / [BZ 2175005](https://bugzilla.redhat.com/show_bug.cgi?id=2175005) and [BZ 1955861](https://bugzilla.redhat.com/show_bug.cgi?id=1955861) / [BZ 1784012](https://bugzilla.redhat.com/show_bug.cgi?id=1784012)
Dependant PR - https://github.com/SatelliteQE/nailgun/pull/966

Add automation for BZ 2175005, BZ 1955861/1784012

---

tests/foreman/api/test_provisioning.py
tests/foreman/api/test_provisioningtemplate.py
tests/foreman/api/test_template_combination.py
tests/foreman/cli/test_provisioningtemplate.py
tests/foreman/ui/test_provisioningtemplate.py

Fixes https://github.com/SatelliteQE/robottelo/issues/12064
Manual cherrypick of https://github.com/SatelliteQE/robottelo/pull/11940 and old missed cherrypick https://github.com/SatelliteQE/robottelo/pull/11833

[6.12.z] Add automation for BZ 2175005, BZ 1955861/1784012

---

robottelo/host_helpers/repository_mixins.py
tests/foreman/ui/test_dashboard.py

Fixing problem in UI dashboard tests

dashboard test fix

---

.github/CODEOWNERS

Tier2 Codeowners for framework based changes

---

robottelo/host_helpers/repository_mixins.py
tests/foreman/ui/test_dashboard.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11100
Fixing problem in UI dashboard tests

[6.14.z] dashboard test fix

---

tests/foreman/api/test_repositories.py
tests/foreman/api/test_subscription.py

Cherrypick into 6.14.z
Parent PR: https://github.com/SatelliteQE/robottelo/pull/11249

[6.14.z]Cherrypick Test for multiple orgs with the same repo[Repository Rewrite]

---

tests/foreman/api/test_repositories.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11702
Fixed Pulp test case

[6.11.z] Pulp test fix

---

tests/foreman/api/test_repositories.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/11702
Fixed Pulp test case

[6.12.z] Pulp test fix

---

robottelo/constants/__init__.py
tests/foreman/longrun/test_oscap.py

Update scap tests to use deploy_flavor and Global Registration

---

requirements-optional.txt
requirements.txt

Sync with master commit
42a058ae13a80a461306a867412e37acae14197f

[6.13.z] Sync requirements with master branch

---

tests/foreman/api/test_reporttemplates.py

Cherrypick of this previously merged PR into 6.14.z: https://github.com/SatelliteQE/robottelo/pull/11633
[Failed Cherrypick](https://github.com/SatelliteQE/robottelo/issues/11806)

[6.14.z] Cherrypick RFE Installable Errata

---

requirements-optional.txt
requirements.txt

Sync with master commit
42a058ae13a80a461306a867412e37acae14197f

[6.14.z] Sync requirements with master branch

---

robottelo/host_helpers/repository_mixins.py
tests/foreman/ui/test_dashboard.py

[6.13.z] dashboard test fix

---

conftest.py
pytest_fixtures/component/puppet.py
pytest_fixtures/core/broker.py
pytest_fixtures/core/sat_cap_factory.py
pytest_fixtures/core/sys.py
pytest_fixtures/core/xdist.py
pytest_plugins/sanity_plugin.py
robottelo/hosts.py
robottelo/utils/ohsnap.py
testimony.yaml
tests/foreman/api/test_computeresource_gce.py
tests/foreman/api/test_host.py
tests/foreman/api/test_organization.py
tests/foreman/api/test_repository.py
tests/foreman/api/test_syncplan.py
tests/foreman/api/test_user.py
tests/foreman/cli/test_contentcredentials.py
tests/foreman/cli/test_contentview.py
tests/foreman/cli/test_hostcollection.py
tests/foreman/cli/test_ping.py
tests/foreman/cli/test_role.py
tests/foreman/cli/test_user.py
tests/foreman/endtoend/test_api_endtoend.py
tests/foreman/installer/test_installer.py
tests/foreman/sanity/test_bvt.py

Cherrypick of https://github.com/SatelliteQE/robottelo/pull/11645 in 6.13.z.

[6.13.z] Sanity Plugin with new sanity tests runs on installer tests satellite

---

robottelo/constants/__init__.py
tests/foreman/longrun/test_oscap.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12098
$SSIA

[6.14.z] Update scap tests to use deploy_flavor and Global Registration

---

tests/foreman/api/test_reporttemplates.py
tests/foreman/cli/test_contentcredentials.py
tests/foreman/ui/test_contentcredentials.py

CC updates previously merged into master: https://github.com/SatelliteQE/robottelo/pull/11736
Failed cherrypicks for 6.13.z 6.14.z

[6.14.z] cherrypick of ContentCredentials Updates

---

tests/foreman/maintain/test_backup_restore.py

Manual cherry-pick for https://github.com/SatelliteQE/robottelo/pull/11716

[6.12.z] Adding service status coverage to backup and restore

---

requirements-optional.txt
requirements.txt

Sync with master commit
42a058ae13a80a461306a867412e37acae14197f

[6.11.z] Sync requirements with master branch

---

tests/foreman/api/test_rhc.py
tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12162
null

[6.13.z] Mark test_positive_configure_cloud_connector as destructive

---

tests/foreman/api/test_rhc.py
tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12162
null

[6.14.z] Mark test_positive_configure_cloud_connector as destructive

---

tests/foreman/api/test_rhc.py
tests/foreman/cli/test_remoteexecution.py

Cherrypick of PR: https://github.com/SatelliteQE/robottelo/pull/12162
null

[6.12.z] Mark test_positive_configure_cloud_connector as destructive

---

robottelo/cli/contentview.py
tests/foreman/destructive/test_capsulecontent.py

Automation coverage for [BZ 2170535](https://bugzilla.redhat.com/show_bug.cgi?id=2170535) and [BZ 2218661](https://bugzilla.redhat.com/show_bug.cgi?id=2218661)

Add another test for capsule sync deadlock issue

---

tests/foreman/api/test_registration.py

This change updates test_positive_allow_reregistration_when_dmi_uuid_changed to use global registration method in-place of old method of registration.
Also BZ#2229112 is added and this test case will get skipped until the BZ is fixed.

Registration test dmi_uuid fix
